crates/polars-arrow/src/array/null.rs, crates/polars-core/src/chunked_array/builder/list/null.rs, crates/polars-core/src/series/implementations/null.rs, crates/polars/tests/it/core/series.rs, py-polars/tests/unit/functions/test_as_datatype.py, py-polars/tests/unit/test_constructors.py
IIRC, This should be fixed as we discussed in discord.
=> fix: fix the construction of List<Null>

.github/ISSUE_TEMPLATE/bug_report_python.yml, .github/ISSUE_TEMPLATE/bug_report_rust.yml, .github/ISSUE_TEMPLATE/documentation.yml, .github/ISSUE_TEMPLATE/feature_request.yml
The user guide will soon live in this repo. We should have a dedicated issue type for documentation to keep things streamlined.
=> chore: Add Documentation issue type

crates/polars-json/src/json/deserialize.rs, py-polars/tests/unit/namespaces/test_string.py
=> feat: json_extract supports extract static and string value to list dtype

crates/polars-plan/src/logical_plan/optimizer/collect_members.rs, crates/polars-plan/src/logical_plan/optimizer/mod.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/semi_anti_join.rs, py-polars/polars/expr/expr.py, py-polars/tests/unit/test_cse.py
=> fix: toggle off cse if ext_context is used

crates/polars-io/src/parquet/predicates.rs, py-polars/tests/unit/io/test_lazy_parquet.py
=> fix: ensure null_count statistics accounts for null array

crates/polars-plan/src/dsl/function_expr/temporal.rs, py-polars/tests/unit/namespaces/test_datetime.py
=> feat: dt.offset_by supports broadcasting lhs

py-polars/polars/dataframe/frame.py
=> docs(python): Add deprecation message in groupby docs

py-polars/pyproject.toml
New matplotlib version broke some things in our CI pipeline :)
=> test(python): Ignore matplotlib warning

py-polars/polars/io/database.py
IIUC if `batch_size` is None, no batching is attempted.
=> docs(python): Fix `read_database` `batch_size` docstring

crates/polars-ops/src/chunked_array/binary/namespace.rs, crates/polars-ops/src/chunked_array/strings/namespace.rs, crates/polars-plan/src/dsl/function_expr/strings.rs, py-polars/tests/unit/namespaces/test_binary.py, py-polars/tests/unit/namespaces/test_string.py
Per comments: https://github.com/pola-rs/polars/pull/11091#discussion_r1326012967
=> fix: propagate null value for str/binary starts/ends_with and contains

crates/polars-core/src/chunked_array/ops/arity.rs, crates/polars-plan/src/dsl/dt.rs, crates/polars-plan/src/dsl/function_expr/datetime.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-time/src/truncate.rs, py-polars/polars/expr/datetime.py, py-polars/polars/series/datetime.py, py-polars/src/expr/datetime.rs, py-polars/tests/unit/datatypes/test_temporal.py
=> feat: argument every of datetime.truncate can be expression

crates/polars-time/src/truncate.rs
from https://github.com/pola-rs/polars/pull/11155#discussion_r1328637081
> You should only use try_binary_elementwise_values if your function is very, very cheap (cheaper than a branch mispredict) and not worth skipping nulls for
`truncate_*s` is definitely not very very cheap, especially if truncating by weeks or months
=> perf(rust, python): use try-binary-elementwise instead of try-binary-elementwise-values in dt_truncate

docs/src/rust/user-guide/expressions/lists.rs
=> docs(rust): Fix user_guide of str.split

crates/polars-plan/src/logical_plan/builder.rs, py-polars/tests/unit/operations/test_filter.py
=> fix: replace n-th in filter

docs/src/rust/user-guide/expressions/casting.rs, docs/src/rust/user-guide/transformations/time-series/filter.rs, docs/src/rust/user-guide/transformations/time-series/parsing.rs, docs/src/rust/user-guide/transformations/time-series/timezones.rs
=> docs(rust): fix un-compilable rust example in user guide.

crates/polars-ops/src/series/ops/is_in.rs, py-polars/tests/unit/operations/test_is_in.py
=> fix: is_in for bool evaluate has_false incorrectly

crates/polars-io/src/csv/write_impl.rs
=> fix: use POOL when writing csv

crates/polars-io/src/cloud/adaptors.rs, crates/polars-io/src/cloud/mod.rs, crates/polars-io/src/parquet/async_impl.rs
@universalmind303 thanks for the pointer. Found the culprit thanks to that. :+1:
=> fix: handle url encoded paths in objectpath creation

crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs
@ritchie46 The simple way would've worked out of the box if it weren't for the trait solver limitation that requires you to manually specify the turbofish. I don't blame you for missing it, it should've just worked.
=> refactor(rust): remove unnecessary transmute

crates/polars-plan/src/dsl/dt.rs, crates/polars-plan/src/dsl/function_expr/datetime.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-time/src/round.rs, crates/polars-time/src/windows/window.rs, py-polars/polars/expr/datetime.py, py-polars/polars/series/datetime.py, py-polars/src/expr/datetime.rs, py-polars/tests/unit/datatypes/test_temporal.py
=> feat: introduce ambiguous option for dt.round

crates/polars-ops/src/frame/hashing.rs
fixes #11303
@stinodego  can you do a test run on this?
=> fix: set partitions independent of thread pool

crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs, crates/polars-plan/src/logical_plan/schema.rs, py-polars/tests/unit/streaming/test_streaming.py
=> fix: don't panic on multi-nodes in streaming conversion

crates/Makefile, crates/nano-arrow/src/bitmap/bitmask.rs, crates/nano-arrow/src/compute/concatenate.rs, crates/polars-core/Cargo.toml, crates/polars-core/src/chunked_array/ops/gather.rs, crates/polars-core/src/datatypes/mod.rs, crates/polars-core/src/datatypes/static_array.rs, crates/polars-ops/Cargo.toml, crates/polars-ops/src/chunked_array/gather_skip_nulls.rs, crates/polars-ops/src/chunked_array/mod.rs, py-polars/Cargo.lock
In the future we may wish to expose this implementation, but in the near future I'll make a PR to use this internally for the quantile operator.
=> feat(rust): add gather_skip_nulls implementation

Cargo.toml, crates/polars-core/Cargo.toml, crates/polars-core/src/chunked_array/array/mod.rs, crates/polars-core/src/chunked_array/from.rs, crates/polars-core/src/chunked_array/list/mod.rs, crates/polars-core/src/chunked_array/ops/unique/mod.rs, crates/polars-core/src/frame/from.rs, crates/polars-core/src/prelude.rs, crates/polars-core/src/series/from.rs, crates/polars-core/src/series/mod.rs, crates/polars-ops/Cargo.toml, crates/polars-ops/src/series/ops/mod.rs, crates/polars-ops/src/series/ops/rank.rs, crates/polars-plan/Cargo.toml, crates/polars/Cargo.toml, py-polars/Cargo.lock
=> chore(rust): move rank to polars-ops

crates/polars-arrow/src/array/list.rs, py-polars/tests/unit/datatypes/test_list.py
=> fix(rust): Fix empty check when building a list

crates/polars-plan/src/logical_plan/alp.rs
=> fix(python): fix opaque python reader schema

crates/polars-io/src/lib.rs
=> feat: support 'abfss' for azure

crates/polars-core/src/chunked_array/logical/categorical/merge.rs, py-polars/tests/unit/datatypes/test_categorical.py
=> fix: fix categorical collect

crates/polars-ops/src/frame/join/hash_join/zip_outer.rs, py-polars/tests/unit/operations/test_join.py
=> fix: fix outer join on bools

py-polars/polars/io/database.py, py-polars/tests/unit/io/test_database_read.py
Closes #11334.
Adds transparent support for using SQLAlchemy [Selectable](https://docs-sqlalchemy.readthedocs.io/ko/latest/core/selectable.html#selectables-tables-from-objects) query objects with `pl.read_database`, in conjunction with an established SQLAlchemy connection.
_(Brings parity with equivalent capability in pandas/dask)._
Connect to an existing table...
```python
from sqlalchemy import MetaData, Table, create_engine, select
conn = create_engine( "sqlite:///existing_test_database.db" )
t = Table( "test_data", MetaData(), autoload_with=conn )
```
...and load into polars using an alchemy "selectable" query object:
```python
alchemy_query = select(t.c.date, t.c.name, t.c.value).where(t.c.id < 3)
df = pl.read_database( alchemy_query, connection=conn.connect() ) …
```
=> feat(python): support use of SQLAlchemy "selectable" query objects with `pl.read_database`

py-polars/docs/requirements-docs.txt, py-polars/polars/testing/parametric/strategies.py, py-polars/requirements-dev.txt
Closes https://github.com/pola-rs/polars/pull/11441.
`dependabot` tried to setup the PR but was defeated by a small (new) typing lint ;)
=> chore(python): update hypothesis package to `6.87.1`

crates/polars-io/src/parquet/async_impl.rs
The previous implementation wasn't concurrent. Streams are polled sequentially.
Partially fixes #11390
=> perf: ensure we download row-groups concurrently.

crates/nano-arrow/src/io/parquet/read/deserialize/binary/nested.rs
=> fix: fix deserialization of parquets with large string list columns causing stack overflow

.github/workflows/release-python.yml
=> ci(python): Small fix in release workflow

crates/polars-io/src/parquet/read.rs, crates/polars-io/src/parquet/read_impl.rs, crates/polars-io/src/utils.rs, crates/polars-lazy/src/physical_plan/executors/scan/ipc.rs, crates/polars-lazy/src/physical_plan/executors/scan/mod.rs, crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs, crates/polars-pipe/src/executors/sources/parquet.rs, py-polars/tests/unit/io/test_hive.py
=> fix: correct projection pushdown in hive partitioned read

crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
Continues on #11502
Don't know why we didn't do this. Let's see what CI thinks of it.
=>  feat: allow predicates in csv scans 87b325f 

py-polars/src/dataframe.rs, py-polars/src/series/mod.rs
=> feat: Use IPC for (un)pickling dataframes/series

crates/polars-io/src/parquet/read_impl.rs
=> fix: fix parquet deserialization Overflow error by using i64 offset types when promoting Arrow Lists to LargeLists

crates/polars-plan/src/logical_plan/builder.rs, py-polars/tests/unit/io/test_hive.py
=> fix: respect 'hive_partitioning' argument in parquet

crates/polars-io/src/parquet/read_impl.rs, crates/polars-lazy/src/physical_plan/executors/union.rs, py-polars/tests/unit/io/test_hive.py
=> fix: correct schema empty df in hive partitioning read

crates/nano-arrow/src/bitmap/bitmask.rs, py-polars/tests/unit/dataframe/test_df.py
Fixes https://github.com/pola-rs/polars/issues/11522.
=> fix: bug in BitMask::get_u32

crates/polars-core/src/chunked_array/ops/fill_null.rs, crates/polars-plan/src/dsl/functions/horizontal.rs, py-polars/polars/functions/aggregation/horizontal.py, py-polars/tests/unit/operations/test_aggregations.py
=> fix: respect identity in horizontal sum

crates/nano-arrow/src/array/binary/mutable_values.rs, crates/nano-arrow/src/array/list/mutable.rs, crates/nano-arrow/src/array/physical_binary.rs, crates/nano-arrow/src/array/utf8/mutable_values.rs, crates/nano-arrow/src/compute/cast/binary_to.rs, crates/nano-arrow/src/compute/cast/primitive_to.rs, crates/nano-arrow/src/io/avro/read/nested.rs, crates/nano-arrow/src/io/parquet/read/deserialize/binary/utils.rs, crates/nano-arrow/src/offset.rs, crates/polars-json/src/json/deserialize.rs
This will practically never happen.
=> feat: elide overflow checks on i64

crates/polars-core/src/frame/group_by/proxy.rs, crates/polars-ops/src/series/ops/is_last_distinct.rs
=> fix: mark take_group_last function as unsafe

py-polars/polars/functions/lit.py, py-polars/tests/unit/functions/test_lit.py
Fixes https://github.com/pola-rs/polars/issues/11571.
=> fix(python): parse time unit properly in pl.lit

py-polars/polars/lazyframe/frame.py
Fixes https://github.com/pola-rs/polars/issues/11603.
=> fix(python): normalize filepath in sink_parquet

crates/polars-core/src/series/from.rs
=> fix: ensure nested logical types are converted to physical

py-polars/polars/config.py, py-polars/polars/dataframe/frame.py, py-polars/polars/io/csv/functions.py, py-polars/polars/io/parquet/functions.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py
Credit to @braaannigan in #10981 for many of these improvements.
I had to re-open this because some work got lost with me pushing to the branch on a fork.
=> docs(python): Improve some docstrings

Cargo.toml, crates/nano-arrow/Cargo.toml, crates/nano-arrow/src/array/binary/mod.rs, crates/nano-arrow/src/array/boolean/mod.rs, crates/nano-arrow/src/array/dictionary/mod.rs, crates/nano-arrow/src/array/fixed_size_binary/mod.rs, crates/nano-arrow/src/array/fixed_size_list/mod.rs, crates/nano-arrow/src/array/list/mod.rs, crates/nano-arrow/src/array/map/mod.rs, crates/nano-arrow/src/array/mod.rs, crates/nano-arrow/src/array/null.rs, crates/nano-arrow/src/array/primitive/mod.rs, crates/nano-arrow/src/array/struct_/mod.rs, crates/nano-arrow/src/array/union/mod.rs, crates/nano-arrow/src/array/utf8/mod.rs, crates/nano-arrow/src/bitmap/immutable.rs, crates/nano-arrow/src/buffer/immutable.rs, crates/nano-arrow/src/buffer/mod.rs, crates/nano-arrow/src/datatypes/field.rs, crates/nano-arrow/src/datatypes/mod.rs, crates/polars-core/Cargo.toml, crates/polars-core/src/series/mod.rs
Adds a direct method to go from arrow array to Series.
=> feat(rust): easier arrow2/arrow-rs conversion

Makefile, py-polars/Makefile
=> chore: better align `help` command output following addition of some longer options

Cargo.toml, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/src/conversion.rs
https://github.com/PyO3/pyo3/releases/tag/v0.20.0
=> build(python): upgrade pyo3 to 0.20.0

docs/src/rust/user-guide/expressions/folds.rs
=> docs: update document of folds

py-polars/polars/io/database.py, py-polars/tests/unit/io/test_database_read.py
Closes #11668.
Allows for seamless use of both parameterisation forms with SQLAlchemy connections, _without_ adding any additional user-facing complexity/parameters:
Named:
```python
pl.read_database(
query = "SELECT * FROM test_data WHERE value < :n",
connection = alchemy_connection,
execute_options = {"parameters": {"n": 0}},
)
```
Qmark:
```python
pl.read_database(
query = "SELECT * FROM test_data WHERE value < ?",
connection = alchemy_connection,
execute_options = {"parameters": [0]},
)
```
=> feat(python): transparently support "qmark" parameterisation of SQLAlchemy queries in `read_database`

crates/polars-plan/src/dsl/string.rs, crates/polars-plan/src/logical_plan/optimizer/delay_rechunk.rs, crates/polars-sql/src/functions.rs, py-polars/src/expr/string.rs
=> perf: rechunk before grouping on multiple keys

crates/polars-core/src/chunked_array/ops/any_value.rs, crates/polars-core/src/chunked_array/ops/downcast.rs, crates/polars-ops/src/chunked_array/strings/concat.rs
We have already added tests in previous fix.
=> fix(rust): index_to_chunked_index's fast path is not correct

docs/user-guide/io/cloud-storage.md
=> Fix typo in docs

py-polars/polars/testing/asserts.py, py-polars/tests/unit/testing/test_testing.py
Related to https://github.com/pola-rs/polars/issues/11771
* Update docstrings with examples and See Also section - improve wording of parameter descriptions
* Slightly improve some error messages
* Add tests for the `not_equal` functions
=> refactor(python): Minor updates to assertion utils and docstrings

.github/workflows/lint-global.yml, py-polars/polars/series/utils.py, py-polars/polars/utils/_async.py, py-polars/polars/utils/_construction.py, py-polars/requirements-lint.txt, py-polars/tests/test_udfs.py, py-polars/tests/unit/operations/test_aggregations.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/sql/test_sql.py, py-polars/tests/unit/test_exprs.py
New versions of `ruff` and `mypy` came out recently, wanted to give them a spin.
=> chore(python): Bump lint dependencies

Cargo.toml, py-polars/Cargo.lock, py-polars/Cargo.toml
See https://github.com/tkaitchuck/aHash/issues/166.
=> fix: patch broken aHash AES intrinsics on ARM

.github/dependabot.yml, docs/requirements.txt, docs/src/python/user-guide/sql/intro.py, mkdocs.yml
CI failed on a deprecation warning - I believe bumping `mkdocs-material` should fix it.
* Bump docs dependencies
* Fix reference to deprecated extension
* Fix some file paths
* Add dependabot config for docs dependencies
=> build: Bump docs dependencies

py-polars/src/series/export.rs, py-polars/tests/unit/test_interop.py
=> fix(rust): series.to_numpy fails with dtype=Null

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/dataframe/test_df.py
=> fix(python): Frame slicing single column

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/polars/testing/asserts/frame.py, py-polars/polars/testing/asserts/series.py, py-polars/polars/testing/asserts/utils.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/testing/test_assert_series_equal.py
...not there yet, but I caught a few bugs already and made some parts more readable.
Next I'll study/refactor the logic for nested values...
I realize this is hardly reviewable because there's so much changing, so I'm going to have to invoke the **Trust me bro™** card. When I have the final version ready, I'm happy to discuss any possible improvements!
=> refactor(python): Further assert utils refactor

py-polars/polars/io/spreadsheet/functions.py
=> docs(python): fix typo in read_excel docstring

py-polars/polars/utils/_construction.py, py-polars/src/series/construction.rs, py-polars/tests/unit/datatypes/test_list.py
Per comment(https://github.com/pola-rs/polars/issues/11849#issuecomment-1772295528), this fixes #11849 and #11878.
=> fix: construct list series from any values subject to dtype

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_sql.py
=> fix(rust, python, cli): sql In should work without specific ops

crates/polars-plan/src/logical_plan/format.rs, py-polars/tests/unit/io/test_lazy_json.py
=> fix(python): fix panic in format of anonymous scans

Cargo.toml, py-polars/Cargo.lock, py-polars/Cargo.toml
https://github.com/tkaitchuck/aHash/pull/167 has been merged and released to crates.io.
=> chore(rust): use ahash from crates.io release

Cargo.toml, crates/polars-arrow/src/legacy/kernels/ewm/mod.rs, crates/polars-core/src/series/series_trait.rs, crates/polars-ops/src/series/ops/rank.rs, crates/polars-plan/Cargo.toml, crates/polars-plan/src/dsl/function_expr/mod.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/tests/unit/test_cse.py
=> fix: implement proper hash for identifier in cse

crates/polars-pipe/src/executors/sinks/sort/sink_multiple.rs, crates/polars-pipe/src/executors/sources/parquet.rs, crates/polars-pipe/src/pipeline/convert.rs, py-polars/tests/unit/io/test_hive.py, py-polars/tests/unit/streaming/test_streaming_sort.py
And add test for streaming hive partitioning
=> fix: fix streaming multi-column/multi-dtype sort

crates/polars-lazy/src/frame/mod.rs, crates/polars-sql/src/context.rs, crates/polars-sql/src/sql_expr.rs, crates/polars-sql/tests/statements.rs
=> fix(sql): table aliases

crates/polars-plan/src/dot.rs, py-polars/tests/unit/io/test_lazy_json.py
fixes on issue mentioned in #11992
=> fix: fix dot visualization of anonymous scans

crates/polars-plan/src/dsl/function_expr/strings.rs, py-polars/tests/unit/namespaces/string/test_string.py
fixes https://github.com/pola-rs/polars/issues/12038
=> fix(rust,python): display fmt for str split

crates/polars-plan/src/logical_plan/builder.rs, crates/polars-plan/src/logical_plan/schema.rs, py-polars/polars/utils/_construction.py, py-polars/tests/unit/io/test_hive.py, py-polars/tests/unit/series/test_series.py
=> fix: Error on duplicates in hive partitioning

docs/src/python/user-guide/expressions/aggregation.py
This PR addresses a potential issue related to `pl.Categorical` discovered in the final example of the Expressions/Aggregation section of the user guide. The original question pertains to determining whether alphabetically sorted names are associated with `M` or `F`.
Given that the `first_name` column is of type `pl.Categorical`, the result of `pl.col("gender").sort_by("first_name").first().alias("gender")` is influenced by the ordering type, which is set to `physical` by default.
To better align the code with the original question, I propose adding `.with_columns(pl.col("first_name").cat.set_ordering("lexical"))`.
```
shape: (5, 5)
┌───────┬─────────────────┬─────────────────┬────────────────────┬────────┐
│ state ┆ youngest        ┆ oldest          ┆ alphabetical_first ┆ gender │
│ --- …
```
=> docs(python): Minor tweak in code example in section Expressions/Aggregation

crates/polars-io/src/parquet/async_impl.rs, crates/polars-io/src/pl_async.rs
=> feat: add concurrency budget

crates/polars-plan/src/dsl/function_expr/schema.rs, py-polars/tests/unit/namespaces/test_array.py
=> fix: fix scheme of arr.min/max

crates/polars-core/src/chunked_array/builder/list/mod.rs, py-polars/tests/unit/datatypes/test_array.py
This partially addresses #12137.
=> fix: fix panic when initializing Series with array of list dtype

py-polars/polars/dataframe/frame.py
=> docs(python): fix rendering of note in DataFrame.fold

crates/polars-row/src/decode.rs, crates/polars-row/src/fixed.rs, py-polars/tests/unit/streaming/test_streaming_sort.py
=> feat: support reverse sort in streaming

py-polars/Cargo.lock, py-polars/Cargo.toml
=> chore: pin ring

py-polars/polars/testing/parametric/strategies.py, py-polars/tests/parametric/test_series.py, py-polars/tests/parametric/test_testing.py, py-polars/tests/unit/series/test_to_numpy.py
Partially addresses https://github.com/pola-rs/polars/issues/12138
Starting with the low-hanging fruit 😅 
Besides adding the `Binary` type, also some minor cleanup.
@alexander-beedie Mind a quick review?
=> feat(python): Add binary dtype to hypothesis tests

crates/polars-io/src/pl_async.rs, crates/polars-pipe/src/executors/sources/parquet.rs
=> fix: always start a new thread if the thread is already blocking

crates/polars-time/src/windows/duration.rs
clean up ahead of addressing #12149
This just factors out some code from truncate_impl, and does some sharing between daily and subdaily (truncate_subweekly)
=> refactor(rust): factor out some shared code in `truncate_impl`

crates/polars-lazy/src/physical_plan/expressions/apply.rs, crates/polars-lazy/src/physical_plan/expressions/mod.rs
=> fix: respect return_scalar of list scalars

crates/polars-lazy/src/physical_plan/expressions/aggregation.rs, crates/polars-lazy/src/physical_plan/expressions/apply.rs, crates/polars-lazy/src/physical_plan/expressions/mod.rs, py-polars/tests/unit/operations/test_group_by.py
=> fix: fix ambiguous aggregation type

Cargo.lock, Cargo.toml, crates/polars-io/src/cloud/glob.rs
Update object_store to fix https://github.com/pola-rs/polars/issues/12006
=> chore(rust): update object_store (#12006)

crates/polars-core/src/chunked_array/arithmetic/numeric.rs, py-polars/tests/unit/operations/test_arithmetic.py, py-polars/tests/unit/operations/test_sort.py
=> fix(rust): update null_count after arithmetic

py-polars/polars/config.py
https://github.com/pola-rs/polars/pull/12099 should have been rebased after merging https://github.com/pola-rs/polars/pull/12224
Simple fix.
=> chore: Fix rebase issue breaking CI

crates/polars-io/src/parquet/read.rs, crates/polars-io/src/parquet/read_impl.rs, py-polars/tests/unit/io/test_lazy_parquet.py
=> fix: parquet, add row_count to empty file materialization

crates/polars-time/src/date_range.rs, py-polars/polars/functions/range/date_range.py, py-polars/tests/unit/functions/range/test_date_range.py, py-polars/tests/unit/functions/range/test_datetime_range.py
=> fix: Fix behavior of month intervals in `date_range`

docs/src/rust/user-guide/basics/joins.rs, docs/src/rust/user-guide/basics/reading-writing.rs, docs/src/rust/user-guide/concepts/expressions.rs, docs/src/rust/user-guide/expressions/aggregation.rs, docs/src/rust/user-guide/expressions/folds.rs, docs/src/rust/user-guide/expressions/structs.rs, docs/src/rust/user-guide/io/cloud-storage.rs, docs/src/rust/user-guide/io/csv.rs, docs/src/rust/user-guide/io/json.rs, docs/src/rust/user-guide/io/parquet.rs, docs/src/rust/user-guide/transformations/pivot.rs
Trying to enforce that the doc examples compile properly - first steps...
=> docs(rust): Run rustfmt on doc examples

Cargo.toml, py-polars/Cargo.toml
* Use `workspace = true` for the polars dependency in the `py-polars` crate
* Organize the workspace dependencies alphabetically
=> chore: Organize Cargo.toml

crates/polars-lazy/src/physical_plan/expressions/ternary.rs, py-polars/polars/utils/various.py, py-polars/tests/unit/functions/test_whenthen.py
Fixes https://github.com/pola-rs/polars/issues/12354.
=> fix: ternary broadcasting with empty truthy or falsy and agg predicate

crates/polars-core/src/chunked_array/object/extension/mod.rs, crates/polars-core/src/frame/group_by/aggregations/agg_list.rs, crates/polars-core/src/frame/group_by/aggregations/boolean.rs, crates/polars-core/src/frame/group_by/aggregations/mod.rs, crates/polars-core/src/frame/group_by/aggregations/utf8.rs, crates/polars-core/src/frame/group_by/hashing.rs, crates/polars-core/src/frame/group_by/perfect.rs, crates/polars-core/src/frame/group_by/proxy.rs, crates/polars-lazy/src/physical_plan/expressions/filter.rs, crates/polars-lazy/src/physical_plan/expressions/slice.rs, crates/polars-lazy/src/physical_plan/expressions/sort.rs, crates/polars-lazy/src/physical_plan/expressions/sortby.rs, crates/polars-lazy/src/physical_plan/expressions/window.rs, crates/polars-lazy/src/tests/aggregations.rs, crates/polars-time/src/group_by/dynamic.rs, crates/polars-utils/src/idx_vec.rs, crates/polars/tests/it/core/date_like.rs
Try @orlp's indexvec in the group-by operation.
=> perf: indexvec in group-by

crates/polars-lazy/src/physical_plan/planner/expr.rs, py-polars/tests/unit/operations/test_aggregations.py
=> fix: ensure first/last return null if empty

crates/polars-arrow/src/ffi/mmap.rs, py-polars/src/series/construction.rs
This was actually very easy to add. We keep the numpy object alive as foreign memory owner and memory map the data.
```python
a = np.ones(int(1e7))
pl.Series("a", a)
pl.DataFrame({
"a": a,
"b": a
})
```
=> perf(python): make 1D numpy to polars conversion zero-copy for numeric data

crates/polars-arrow/src/array/mod.rs, crates/polars-arrow/src/compute/filter.rs, py-polars/tests/unit/datatypes/test_decimal.py
fixes #12393
Also fixes the failing test. `test_decimal_aggregations`
=> feat: include i128 in more primitive functions

crates/polars-lazy/src/physical_plan/expressions/apply.rs, crates/polars-lazy/src/physical_plan/expressions/binary.rs, crates/polars-lazy/src/physical_plan/expressions/mod.rs, py-polars/tests/unit/operations/test_group_by_dynamic.py
=> fix: update groups state after binary aggregation

crates/polars-lazy/src/physical_plan/expressions/binary.rs, py-polars/tests/unit/operations/test_aggregations.py
Fixes https://github.com/pola-rs/polars/issues/12423.
=> fix: binary operations in aggregation context on literals

py-polars/pyproject.toml
Includes some bugfixes we need.
=> build(python): Update for new maturin release

crates/polars-io/src/csv/utils.rs, py-polars/tests/unit/io/test_csv.py
=> fix: empty csv no-raise

.github/workflows/release-python.yml
Finnicky stuff... this should fix it.
=> ci(python): Fix docs trigger

crates/polars-arrow/src/array/dictionary/mod.rs, crates/polars-arrow/src/compute/mod.rs, crates/polars-io/src/parquet/write.rs, crates/polars-lazy/src/lib.rs, crates/polars-lazy/src/physical_plan/expressions/window.rs, crates/polars-plan/src/dsl/functions/horizontal.rs
=> docs(rust): Fix some typos

crates/polars-pipe/src/executors/sinks/joins/cross.rs, py-polars/tests/unit/streaming/test_streaming_join.py
=> fix: fix streaming cross join on empty df

crates/polars-core/src/series/mod.rs
=> fix: fix as_list logical types

py-polars/tests/unit/datatypes/test_list.py
=> test: add test for previous commit

crates/polars-io/src/parquet/async_impl.rs, py-polars/tests/unit/io/test_lazy_parquet.py
=> fix: pre-fefetch struct columns in async projection pd

docs/user-guide/expressions/plugins.md
=> docs: Add `polars-ds` to list of community plugins

crates/polars-core/src/series/mod.rs, py-polars/docs/source/reference/dataframe/modify_select.rst, py-polars/docs/source/reference/expressions/modify_select.rst, py-polars/docs/source/reference/lazyframe/modify_select.rst, py-polars/docs/source/reference/series/modify_select.rst, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py, py-polars/polars/slice.py, py-polars/src/expr/general.rs, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/operations/test_slice.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/test_lazy.py
Ref https://github.com/pola-rs/polars/issues/10972
=> depr(python,rust!): Rename `take_every` to `gather_every`

py-polars/docs/source/reference/series/modify_select.rst, py-polars/polars/series/series.py, py-polars/src/series/mod.rs, py-polars/src/series/scatter.rs, py-polars/tests/unit/series/test_scatter.py, py-polars/tests/unit/series/test_series.py
Ref https://github.com/pola-rs/polars/issues/10972#issuecomment-1713538324
I wasn't quite sure what to do with the Rust side on this one 🤔 I left it as-is for now.
=> depr(python): Rename `Series.set_at_idx` to `scatter`

Cargo.lock, crates/polars-core/src/config.rs, crates/polars-io/src/cloud/options.rs, crates/polars-io/src/pl_async.rs, crates/polars-pipe/Cargo.toml, crates/polars-pipe/src/executors/sources/parquet.rs
=> perf: speed up parquet download of streaming engine

crates/polars-lazy/src/frame/mod.rs, crates/polars-pipe/src/executors/sinks/file_sink.rs, crates/polars-pipe/src/pipeline/convert.rs
Continuation of #9976 / #10060 : Implements an `IpcCloudSink` which works very similar to the `ParquetCloudSink`.
=> feat(rust): Adds sink_ipc_cloud

crates/polars-lazy/src/frame/mod.rs, crates/polars-pipe/src/executors/sinks/file_sink.rs, crates/polars-pipe/src/pipeline/convert.rs
Reverts pola-rs/polars#11008
This was broken. @Qqwy can you rebase and re-open?
=> Revert "feat(rust): Adds sink_ipc_cloud"

crates/polars-pipe/src/executors/sources/parquet.rs
Not being killed by latencies, made this ~7x faster in an IO bound query.
=> perf: ensure streaming parquet download remains concurrent `~7x`

crates/polars-lazy/src/dsl/list.rs, py-polars/tests/unit/test_schema.py
Fixes https://github.com/pola-rs/polars/issues/11188
=> fix: list schema of list `eval`

crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, py-polars/tests/unit/io/test_lazy_parquet.py
Fixes https://github.com/pola-rs/polars/issues/12480.
=> fix: fix lazy parquet slice with nested columns

crates/polars-lazy/src/tests/predicate_queries.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
linked to #10841
Added the semi join into the list of joins that can accept this predicate pushdown optimization.
Also remove the TODO because no other join can benefit from it.
=> perf: apply left side predicate pushdown also to right side on semi join

crates/polars-arrow/src/compute/cast/mod.rs, py-polars/tests/unit/datatypes/test_array.py, py-polars/tests/unit/namespaces/test_list.py, py-polars/tests/unit/test_errors.py
=> fix: error when invalid list to array is given

crates/polars/src/lib.rs
=> docs: update custom allocator instructions to include macOS

crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs, crates/polars-parquet/src/arrow/read/deserialize/simple.rs
=> feat: implement 'DeltaByteArray' decoding for parquet

crates/polars-ops/src/chunked_array/list/sets.rs, py-polars/tests/unit/namespaces/test_list.py
=> fix: fix oob in set operations

crates/polars-io/src/parquet/async_impl.rs, crates/polars-io/src/pl_async.rs
=> fix: fix concurrency budget assertion

py-polars/src/dataframe.rs, py-polars/tests/unit/dataframe/test_df.py
Fix https://github.com/pola-rs/polars/issues/12642.
=> fix: support negative slice on eager frame

py-polars/polars/utils/_construction.py, py-polars/tests/unit/test_constructors.py
Closes #12669.
Instead of using a naïve conversion inside a Python loop, we now reshape the input numpy array as 1D, fast-initialise a Series from that, and then defer to a Rust-side reshape operation to optimally recover the given dimensions.
In the specific example given in the issue this results in initialising the frame ~2,500x faster  🚀
(The degree of speedup depends on the dimensionality, but it's typically ~1-3 orders of magnitude).
* **Average case**
```python
from codetiming import Timer
a = np.arange(1_000_000).reshape(-1, 5)
with Timer():
df = pl.DataFrame({"a": a})
```
```
Before: 0.6246 seconds
After: 0.0151 seconds
-------------------------
Speedup: ~41x 
-------------------------
```
* **Extreme case**
```python
a = …
```
=> perf(python): order(s) of magnitude speedup when initialising `List` dtype `Series` from 2D numpy array

crates/polars-core/src/chunked_array/ops/zip.rs, py-polars/tests/unit/test_arity.py
=> fix: fix ternary zip_with null broadcast

crates/polars-plan/src/dsl/function_expr/correlation.rs, py-polars/tests/unit/operations/test_statistics.py, py-polars/tests/unit/test_lazy.py
=> fix: cov/corr respect f32 type

crates/polars-io/src/ndjson/buffer.rs, crates/polars-json/src/json/infer_schema.rs, crates/polars-json/src/ndjson/file.rs, crates/polars/tests/it/io/json.rs, py-polars/tests/unit/io/test_json.py
fixes #12671
fixes #7858
fixes #11860
=> fix: json null inference

crates/polars-ops/src/chunked_array/cov.rs, py-polars/tests/unit/operations/test_statistics.py
=> fix: corr return nan if denominator is invalid

Cargo.lock, py-polars/Cargo.toml
=> python polars 0.19.17

crates/polars-parquet/src/arrow/read/deserialize/simple.rs
Closes https://github.com/pola-rs/polars/issues/12729
=> fix: undo regression in ability to read certain parquet files

Cargo.lock, Cargo.toml, crates/polars-arrow/src/compute/cast/binary_to.rs, crates/polars-io/src/csv/buffer.rs, py-polars/tests/unit/operations/test_cast.py
Fixes https://github.com/pola-rs/polars/issues/12743.
=> fix: allow leading zero and plus in integer parsing

crates/polars-ops/src/chunked_array/mode.rs
#12758
@paddymul can you give this one a test run?
`$ make build-debug-opt-native` in the `/py-polars` should give you a fast binary.
=> feat: determine mode parallelism depending on current tasks

crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/frame/mod.rs, crates/polars-core/src/series/mod.rs, py-polars/tests/unit/dataframe/test_vstack.py
=> feat: support nested null in vstack/append/extend/concat

Cargo.lock, crates/polars-io/src/parquet/write.rs, crates/polars-parquet/src/arrow/write/binary/basic.rs, crates/polars-parquet/src/arrow/write/dictionary.rs, crates/polars-parquet/src/arrow/write/mod.rs, crates/polars-parquet/src/arrow/write/pages.rs, crates/polars-parquet/src/arrow/write/primitive/basic.rs, crates/polars-pipe/src/executors/sinks/file_sink.rs, py-polars/Cargo.toml, py-polars/build.rs, py-polars/polars/dataframe/frame.py, py-polars/src/dataframe.rs, py-polars/tests/unit/io/test_parquet.py
=> fix: write only one dict page per row rowgroup

py-polars/docs/source/_static/version_switcher.json
=> Revert "docs(python): Update version switcher for `0.20`"

py-polars/polars/datatypes/convert.py, py-polars/src/conversion.rs, py-polars/tests/unit/datatypes/test_enum.py
=> fix(python): Fix error message for uninstantiated `Enum` types

crates/polars-ops/src/frame/join/merge_sorted.rs, py-polars/tests/unit/operations/test_sort.py
=> fix(rust): don't panic on empty df in `merge_sort`

py-polars/polars/datatypes/classes.py, py-polars/polars/functions/as_datatype.py, py-polars/tests/unit/test_datatypes.py
Closes [#12620](https://github.com/pola-rs/polars/issues/12620)
Also some other minor cleanup.
=> feat(python): Update `repr` of `Struct` data type class

py-polars/polars/utils/_construction.py, py-polars/tests/unit/test_constructors.py
Closes [#11930](https://github.com/pola-rs/polars/issues/11930)
=> feat(python): Raise if expression passed to DataFrame constructor

crates/polars-parquet/src/lib.rs
=> Refer to arrow unambiguously fro polars-arquet

crates/polars-core/src/chunked_array/cast.rs, py-polars/tests/unit/datatypes/test_enum.py
=> feat(rust): Cast to an enum from int

crates/polars-core/src/series/implementations/null.rs, py-polars/tests/unit/datatypes/test_null.py
=> feat: implement group-tuples for null dtype

py-polars/polars/datatypes/classes.py
Also a minor update to the `Enum` hash implementation to more closely other hash implementations (specifically Struct).
=> feat(python): Minor update to `Array` data type repr

crates/polars-ops/src/series/ops/horizontal.rs, crates/polars-plan/src/dsl/function_expr/boolean.rs, crates/polars-plan/src/dsl/functions/horizontal.rs, py-polars/polars/functions/aggregation/horizontal.py, py-polars/tests/unit/functions/aggregation/test_horizontal.py, py-polars/tests/unit/operations/test_filter.py
=> perf: ensure we reduce for any/all horizontal (2)

docs/user-guide/expressions/functions.md
=> docs(python): update outdated links to api in Expressions/Functions page

docs/user-guide/basics/series-dataframes.md
not sure exactly what the intention of this phrase, think this makes sense now though
=> docs: Minor typo fix

crates/polars-io/src/cloud/object_store_setup.rs, crates/polars-io/src/cloud/options.rs
fixes #13008 
fixes #13006
fixes #12596
=> fix: timeout errors in concurrent downloads

py-polars/polars/dataframe/frame.py
Ref https://github.com/pola-rs/polars/issues/12935
We can no longer rely on min/max returning `None` for unsupported types, so we have to manually set these to `null` in the describe results.
=> refactor(python): Update `describe` calculation of min/max

py-polars/polars/utils/udfs.py, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py
=> feat(python): expand set of numpy functions which emit "inefficient map_* warning"

crates/polars-arrow/src/legacy/kernels/sort_partition.rs, crates/polars-core/src/chunked_array/ops/compare_inner.rs, crates/polars-core/src/chunked_array/ops/sort/arg_sort_multiple.rs, crates/polars-core/src/chunked_array/ops/sort/mod.rs, crates/polars-core/src/frame/group_by/hashing.rs, crates/polars-core/src/series/implementations/binary.rs, crates/polars-core/src/series/implementations/boolean.rs, crates/polars-core/src/series/implementations/categorical.rs, crates/polars-core/src/series/implementations/floats.rs, crates/polars-core/src/series/implementations/list.rs, crates/polars-core/src/series/implementations/mod.rs, crates/polars-core/src/series/implementations/object.rs, crates/polars-core/src/series/implementations/utf8.rs, crates/polars-core/src/series/series_trait.rs, crates/polars-ops/src/chunked_array/hist.rs, crates/polars-ops/src/chunked_array/top_k.rs, crates/polars-ops/src/series/ops/rolling.rs, crates/polars-ops/src/series/ops/search_sorted.rs, crates/polars-utils/src/sort.rs
Nothing really interesting here.
=> refactor(rust): further use TotalOrd

crates/polars-json/src/json/infer_schema.rs, py-polars/tests/unit/namespaces/string/test_string.py
=> bug(rust): fix for incorrect schema inference on nested columns

py-polars/docs/source/reference/datatypes.rst
=> docs: add Enum to dtype list

.github/workflows/docs-global.yml, .gitignore, Makefile, crates/polars-plan/src/dsl/functions/coerce.rs, crates/polars-plan/src/dsl/functions/index.rs, crates/polars-plan/src/dsl/functions/mod.rs, docs/pyproject.toml, docs/src/python/user-guide/lazy/execution.py, docs/src/python/user-guide/lazy/using.py, docs/src/python/user-guide/sql/intro.py, docs/src/python/user-guide/transformations/concatenation.py, py-polars/pyproject.toml
* Add `make pre-commit` at the repo top-level. It runs everything except `blackdoc` (will be replaced by ruff soon) and `mypy` (have to figure out how to handle the config first).
* Run `ruff` instead of `black` on the docs folder.
* Fix some feature flags
* Fix some lints
=> chore: Linting updates

py-polars/polars/expr/string.py
=> docs(python): Fix column name in `contains_any` example

crates/polars-plan/src/logical_plan/builder.rs, py-polars/tests/unit/io/test_csv.py
=> fix: Raise if scan zstd compressed csv file

crates/polars-io/src/csv/buffer.rs, crates/polars-io/src/csv/parser.rs, crates/polars-io/src/csv/utils.rs, py-polars/tests/unit/io/test_csv.py
=> fix: [csv] raise on single quote char

Cargo.lock, py-polars/Cargo.toml
=> python polars 0.20.1

crates/polars-core/src/chunked_array/builder/list/categorical.rs, py-polars/tests/unit/datatypes/test_categorical.py
=> fix: fix category list builder append series with multiple chunks

crates/polars-core/src/series/comparison.rs, py-polars/tests/unit/series/test_series.py
=> fix: fix neq for series cmp str

crates/polars-core/src/chunked_array/comparison/categorical.rs, crates/polars-core/src/series/comparison.rs, py-polars/tests/unit/datatypes/test_categorical.py, py-polars/tests/unit/datatypes/test_enum.py
=> fix: Fix comparison of categoricals

docs/requirements.txt, mkdocs.yml, py-polars/docs/source/conf.py
Move from GA to more privacy friendly framework
=> feat: Move from GA to more privacy friendly framework

.github/workflows/release-python.yml
MacOS making our lives difficult again 🙃 
If someone knows how to run bash commands on GitHub Actions in a cross-platform way, I would love to know.
=> ci(python): Fix release LTS CPU step

py-polars/tests/parametric/test_groupby_rolling.py
Closes https://github.com/pola-rs/polars/issues/11754
=> test(python): Fix failing test

crates/polars-lazy/src/physical_plan/expressions/window.rs, py-polars/tests/unit/operations/test_window.py
=> fix: maintain old join behavior in window expression

.github/workflows/lint-python.yml, docs/development/contributing/index.md, py-polars/Makefile, py-polars/polars/api.py, py-polars/polars/config.py, py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/group_by.py, py-polars/polars/expr/expr.py, py-polars/polars/functions/as_datatype.py, py-polars/polars/functions/lazy.py, py-polars/polars/io/csv/functions.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/selectors.py, py-polars/polars/series/categorical.py, py-polars/polars/sql/context.py, py-polars/polars/string_cache.py, py-polars/polars/testing/parametric/primitives.py, py-polars/polars/testing/parametric/strategies.py, py-polars/pyproject.toml, py-polars/requirements-lint.txt
Formatting difference is minimal - mostly ruff makes a different choice about empty `...` prompts.
Speed difference is amazing :zap:
=> chore(python): Replace blackdoc by ruff's new docstring formatter

crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/series/mod.rs, crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
=> fix: don't cast to unknown dtypes

crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs, py-polars/tests/unit/test_schema.py
=> bug: fix enum dtype conversion

crates/polars-core/src/series/mod.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py, py-polars/src/expr/general.rs, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/test_lazy.py
Resolves #13133.
I'm not sure what the use of `gather_every` is aside from taking equally-spaced elements, so it makes sense to me to be able to pick the starting point.
=> feat(rust,python): add `offset` parameter to `gather_every`

crates/polars-io/src/json/infer.rs, crates/polars-io/src/json/mod.rs, crates/polars-io/src/ndjson/core.rs, crates/polars-io/src/ndjson/mod.rs, crates/polars-json/src/json/infer_schema.rs, crates/polars-json/src/json/mod.rs, crates/polars-json/src/ndjson/file.rs, crates/polars-json/src/ndjson/mod.rs, crates/polars-lazy/src/physical_plan/executors/scan/ndjson.rs, py-polars/tests/unit/io/test_json.py
Use our `get_supertype` as that can deal with nested nulls.
=> fix: ndjson nested null schema inference

crates/polars-ops/src/series/ops/is_in.rs, crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs, py-polars/tests/unit/operations/test_is_in.py
=> fix: `is_in` operator for categoricals

crates/polars-io/src/csv/write.rs, crates/polars-io/src/csv/write_impl.rs, crates/polars-pipe/src/executors/sinks/file_sink.rs
=> fix: sink_csv deadlock

crates/polars-compute/src/comparisons/simd.rs, crates/polars-compute/src/min_max/simd.rs, crates/polars-core/Cargo.toml
Closes https://github.com/pola-rs/polars/pull/13237.
Some silly mistakes, Rust ~~conditional compilation~~ features will be the death of me someday :)
=> fix(rust): enable and fix SIMD in polars-compute

crates/polars-core/src/chunked_array/logical/categorical/builder.rs, crates/polars-core/src/datatypes/_serde.rs, crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/serde/series.rs, crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs, py-polars/tests/unit/io/test_json.py
=> fix: round trip to JSON and back should preserve Enum type

.github/workflows/docs-python.yml
Closes [#13266](https://github.com/pola-rs/polars/issues/13266)
=> docs(python): Fix source link for dev docs

crates/polars-core/src/chunked_array/ops/sort/categorical.rs, py-polars/tests/unit/datatypes/test_categorical.py
=> fix: sorting categorical lexically bugs on null values

docs/user-guide/index.md
Closes [#11102](https://github.com/pola-rs/polars/issues/11102)
=> docs(rust): Add note about Rust examples versioning in user guide

crates/polars-core/src/chunked_array/cast.rs, crates/polars-core/src/datatypes/dtype.rs, py-polars/tests/unit/datatypes/test_array.py, py-polars/tests/unit/namespaces/array/test_to_list.py, py-polars/tests/unit/namespaces/test_list.py
=> fix(rust): casting list/arr to arr/list shouldn't convert chunks to logical type

.github/workflows/release-python.yml, py-polars/polars/__init__.py, py-polars/polars/_cpu_check.py
Closes https://github.com/pola-rs/polars/issues/11658.
=> build(python): Add CPU compatibility check

crates/polars-plan/src/logical_plan/aexpr/schema.rs, crates/polars-plan/src/logical_plan/builder.rs, py-polars/tests/unit/test_schema.py
=> fix: fix schema when subtracting

crates/polars-lazy/src/physical_plan/expressions/column.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs, py-polars/tests/unit/test_predicates.py
=> fix: invalid predicate optimization

crates/polars-arrow/src/bitmap/immutable.rs, crates/polars-arrow/src/bitmap/utils/mod.rs
For platforms where this matters, the bitcount is now aligned. We also have a better fast path for when the bitcount fits in one u64 (typically when the number of elements is <= 64).
More importantly, we avoid re-counting bits when slicing arrays that do not have any nulls (or only nulls).
=> perf: optimize set bit count

crates/polars-core/src/chunked_array/array/mod.rs, crates/polars-core/src/chunked_array/list/mod.rs, crates/polars-core/src/chunked_array/ops/full.rs, crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-core/src/frame/group_by/aggregations/agg_list.rs, crates/polars-core/src/series/implementations/categorical.rs, crates/polars-core/src/series/ops/to_list.rs, crates/polars-lazy/src/physical_plan/expressions/ternary.rs, py-polars/tests/unit/datatypes/test_array.py
=> fix: fix invalid dtype setting in array

crates/polars-ffi/src/version_0.rs
Should fix https://github.com/pola-rs/pyo3-polars/issues/54
@ion-elgreco could you give this a spin?
=> fix: nested dtypes: export logical type in plugins

crates/polars-plan/src/dsl/function_expr/plugin.rs
together with https://github.com/pola-rs/pyo3-polars/pull/55
=> feat: gracefully handle panics in plugins

py-polars/polars/datatypes/constants.py, py-polars/polars/series/series.py, py-polars/polars/type_aliases.py, py-polars/src/series/buffers.rs, py-polars/src/series/mod.rs, py-polars/tests/unit/series/buffers/test_from_buffer.py, py-polars/tests/unit/series/buffers/test_from_buffers.py
=> feat(python): Allow construction of `Series` from memory buffers

crates/polars-plan/src/dsl/function_expr/strings.rs, crates/polars-plan/src/dsl/function_expr/temporal.rs
=> chore(rust): dont panic of ambiguous is of wrong type

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py
=> docs(python): use named series in Series.plot example

crates/polars-ops/src/series/ops/is_in.rs, py-polars/tests/unit/operations/test_is_in.py
=> fix(rust): fix is_in operator when comparing string with global categoricals

.github/CODEOWNERS
@orlp did not appreciate the notification spam so I am changing the ownership again :sweat_smile: 
Will look into a better way of managing this later.
=> chore: Update CODEOWNERS again

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_sql.py
We already support the binary concat operator `||`; this adds support for the function-equivalent `CONCAT`.
```python
"x": ["a", None, "c"],
"y": ["d", "e", "f"],
"z": [1, 2, 3],
})
pl.SQLContext(data=lf).execute(
"""
SELECT 
"x" || "y" || "z" AS c1, 
CONCAT("x","y","z") AS c2 
FROM data
""",
).collect()
```
=> feat(python): feat(rust,python,cli): add SQL engine support for variadic `CONCAT` function

py-polars/polars/datatypes/convert.py, py-polars/polars/series/series.py, py-polars/tests/unit/series/test_equals.py
=> fix(python): Fix Series equality for List/Array types

docs/user-guide/expressions/plugins.md
Adding a link to the distance plugin, if that's ok : )
=> docs(python): add polars-distance to plugins page

crates/polars-ops/src/frame/join/general.rs, crates/polars-ops/src/frame/join/hash_join/mod.rs, crates/polars-ops/src/frame/join/mod.rs, py-polars/tests/unit/operations/test_join.py
=> fix: correct 'outer_coalesce' logic in case of duplicate names

py-polars/polars/functions/range/int_range.py
=> docs(python): Add note to `int_range` docs for creating an index column

crates/polars-plan/src/logical_plan/optimizer/fast_projection.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, py-polars/tests/unit/test_projections.py
https://discord.com/channels/908022250106667068/911186243465904178/1193846195710349332
=> fix: fix projection pushdown for new outer join schema

crates/polars-lazy/src/physical_plan/expressions/apply.rs, py-polars/tests/unit/io/test_hive.py
This fixes the bug reported in the issue https://github.com/pola-rs/polars/issues/13358.
=> feat: improve hive partition pruning (#13358)

crates/polars-arrow/src/legacy/kernels/fixed_size_list.rs, crates/polars-arrow/src/legacy/kernels/mod.rs, crates/polars-core/src/chunked_array/ops/arity.rs, crates/polars-ops/src/chunked_array/array/get.rs, crates/polars-ops/src/chunked_array/array/mod.rs, crates/polars-ops/src/chunked_array/array/namespace.rs, crates/polars-plan/src/dsl/array.rs, crates/polars-plan/src/dsl/function_expr/array.rs, py-polars/docs/source/reference/expressions/array.rst, py-polars/docs/source/reference/series/array.rst, py-polars/polars/expr/array.py, py-polars/polars/series/array.py, py-polars/src/expr/array.rs, py-polars/tests/unit/namespaces/array/test_array.py
This based on #13528, so should only be merged after that one(feel free to ping me to rebased this then).
=> feat(python): Impl and dispatch arr.first/last to get

crates/polars-ops/src/series/ops/cum_agg.rs, py-polars/polars/expr/expr.py, py-polars/polars/functions/lazy.py, py-polars/polars/series/series.py, py-polars/tests/benchmark/test_release.py, py-polars/tests/unit/functions/test_cum_count.py, py-polars/tests/unit/test_exprs.py
Closes [#13473](https://github.com/pola-rs/polars/issues/13473)
=> fix: Fix `cum_count` with regards to start value / null values

docs/development/contributing/ide.md
I struggled a bit figuring out my ruff linter so here's the solution that I found for the next person.
=> docs(python): Hint about ruff setting in VSCode

crates/polars-row/src/encode.rs, crates/polars-row/src/variable.rs, py-polars/tests/unit/streaming/test_streaming_sort.py
=> fix: fix reverse variable row decoding

docs/development/contributing/index.md
=> docs: Add note about toolchain issue under native Windows

docs/user-guide/concepts/contexts.md
Closes https://github.com/pola-rs/polars/issues/12651.
=> docs: Improve documentation on broadcasting

py-polars/docs/source/conf.py, py-polars/docs/source/reference/io.rst, py-polars/polars/lazyframe/frame.py
Closes #13533 
Amend `sink_ndjson` docstring and add to API reference.
driveby: Update copyright `year`
=> docs(python): Add `sink_ndjson` to API reference.

crates/polars-lazy/src/physical_plan/expressions/apply.rs, crates/polars-lazy/src/physical_plan/expressions/filter.rs, py-polars/tests/unit/operations/test_aggregations.py
=> fix: Empty series of AggregatedList should also have list dtype

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/projection.rs, py-polars/tests/unit/test_projections.py
=> fix: Make sure rolling key is projected when process projection

crates/polars-parquet/src/arrow/write/boolean/basic.rs, crates/polars-parquet/src/arrow/write/primitive/basic.rs, crates/polars-pipe/src/executors/sinks/joins/cross.rs, crates/polars-pipe/src/pipeline/convert.rs, py-polars/tests/unit/streaming/test_streaming_io.py
=> fix: streaming cross join if swapped is hit

crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/projection.rs
@reswqa I think this way more optimization rules will include it.
=> refactor: make rolling index column visible to optimizer

crates/polars-core/src/datatypes/any_value.rs, crates/polars-core/src/frame/row/av_buffer.rs, py-polars/tests/unit/dataframe/test_from_dict.py
=> fix: Allow `av_buffer` cast numeric record to temporal type

crates/polars-lazy/src/physical_plan/executors/projection_utils.rs, crates/polars-lazy/src/physical_plan/expressions/rolling.rs, crates/polars-lazy/src/physical_plan/planner/expr.rs, py-polars/tests/unit/operations/test_rolling.py
=> fix: ensure we hit proper cache in nested `rolling` expressions

crates/polars-plan/src/dsl/array.rs, crates/polars-plan/src/dsl/function_expr/array.rs, py-polars/docs/source/reference/expressions/array.rst, py-polars/docs/source/reference/series/array.rst, py-polars/polars/expr/array.py, py-polars/polars/expr/list.py, py-polars/polars/series/array.py, py-polars/polars/series/list.py, py-polars/src/expr/array.rs, py-polars/tests/unit/namespaces/array/test_array.py
Since we have already supports `is_in` for array. It's not hard to implement `contains` then.
=> feat: Impl `contains` for ArrayNameSpace

crates/polars-parquet/src/parquet/write/file.rs
Required by the spec. 
closes #13642 closes #10956
=> feat: write parquet ColumnOrder

crates/polars-plan/src/logical_plan/aexpr/schema.rs, py-polars/tests/unit/operations/test_gather.py
=> fix: gather.get schema

py-polars/docs/source/reference/series/string.rst
@alexander-beedie 😉 (no blame!)
=> docs(python): add missing Series.str.find reference

crates/polars-json/src/json/deserialize.rs, crates/polars-json/src/json/write/serialize.rs
Also removed unused code as drive-by.
=> feat: implement binview for polars-json

py-polars/polars/expr/array.py, py-polars/polars/expr/list.py, py-polars/polars/series/array.py, py-polars/polars/series/list.py, py-polars/src/expr/array.rs, py-polars/src/expr/list.rs, py-polars/tests/unit/namespaces/array/test_array.py, py-polars/tests/unit/namespaces/test_list.py
=> feat: Add `nulls_last` for `list/array.sort`

.github/workflows/release-python.yml
Ref https://github.com/pola-rs/polars/issues/13264
Getting rid of some duplication in the workflow.
=> ci: Refactor Python release workflow

crates/polars-core/src/datatypes/any_value.rs, crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/datatypes/field.rs, crates/polars-core/src/series/from.rs, py-polars/tests/unit/io/test_parquet.py
=> fix(rust): When reading Parquet or Arrow, convert +00:00 timezone to UTC

crates/polars-io/src/csv/read_impl/mod.rs, py-polars/tests/unit/io/test_csv.py
Closes https://github.com/pola-rs/polars/issues/10584.
=> fix(rust): decompress the right number of rows when reading compressed CSVs

crates/polars-arrow/src/array/binview/ffi.rs, crates/polars-arrow/src/array/binview/mod.rs, crates/polars-arrow/src/ffi/array.rs, crates/polars-arrow/src/ffi/schema.rs, crates/polars-arrow/src/mmap/array.rs, crates/polars-arrow/src/mmap/mod.rs, crates/polars-arrow/tests/it/ffi/data.rs, crates/polars-arrow/tests/it/ffi/mod.rs, crates/polars-arrow/tests/it/main.rs
Following https://github.com/apache/arrow/pull/38443/files
=> feat: implement ffi for `binview`

crates/polars-arrow/src/array/growable/binview.rs, crates/polars-arrow/src/compute/filter.rs
We need to write a proper filter. Hope to get to that soon.
=> perf: improve binview filter

README.md
Write support wasn't mentioned in read me.
=> docs(python): Mention deltalake write support in README

crates/polars-core/src/chunked_array/ops/chunkops.rs, crates/polars-ops/src/chunked_array/list/sets.rs, py-polars/tests/unit/operations/test_sets.py
=> fix: prune emtpy chunks before set operations

crates/polars-compute/src/filter/boolean.rs, crates/polars-compute/src/filter/mod.rs, crates/polars-compute/src/filter/primitive.rs
Used a very expensive dynamic dispatch.
=> perf: speedup boolean filter

crates/polars-arrow/src/array/primitive/mutable.rs, crates/polars-core/src/utils/mod.rs, crates/polars-ops/src/chunked_array/list/sets.rs, crates/polars-utils/src/total_ord.rs, py-polars/tests/unit/namespaces/test_list.py
=> feat: List set_operations supports float

crates/polars-plan/src/dsl/function_expr/datetime.rs, py-polars/tests/unit/namespaces/test_datetime.py
=> feat: raise better error message for .dt.time on Date column

py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/dataframe/test_glimpse.py
=> test(python): Add `glimpse` test

crates/polars-core/src/chunked_array/array/mod.rs, crates/polars-core/src/chunked_array/list/mod.rs, crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/datatypes/field.rs, crates/polars-core/src/frame/from.rs, crates/polars-core/src/schema.rs, crates/polars-core/src/series/from.rs, crates/polars-io/src/parquet/read_impl.rs, py-polars/src/functions/io.rs, py-polars/tests/unit/conftest.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/interop/test_to_pandas.py, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/io/test_delta.py, py-polars/tests/unit/io/test_ipc.py, py-polars/tests/unit/io/test_parquet.py, py-polars/tests/unit/io/test_pyarrow_dataset.py, py-polars/tests/unit/streaming/test_streaming_io.py
Third try is a charm :)
fix #13260 
fix #13262
=> feat: preserve Enum information when going to IPC

crates/polars-core/src/fmt.rs, py-polars/polars/expr/binary.py
A combination of hex and ascii.
=> feat: improve binary formatting

crates/polars-core/src/chunked_array/logical/categorical/mod.rs, py-polars/tests/unit/datatypes/test_categorical.py
=> fix: Fix casting from categorical to numeric

crates/polars-core/src/chunked_array/list/mod.rs, py-polars/tests/unit/namespaces/test_list.py
=> fix: count matches on list categorical

crates/polars-core/src/chunked_array/ops/reverse.rs, py-polars/tests/unit/series/test_series.py
Easy quick fix for #14016 multiple chunk issue found by @nameexhaustion. Added small unit test as well.
=> fix(rust): quick fix for multiple chunks binary reverse

crates/polars-arrow/src/array/binview/mod.rs, crates/polars-arrow/src/io/ipc/write/serialize/binview.rs
=> feat: gc binview when writing ipc

crates/polars-pipe/src/executors/sinks/slice.rs, crates/polars-pipe/src/pipeline/convert.rs, py-polars/tests/unit/streaming/test_streaming.py
Fixes https://github.com/pola-rs/polars/issues/13770
=> fix(rust,python): handle `SliceSink` with empty data

py-polars/polars/utils/_construction.py
=> refactor(python): remove unused argument

crates/polars-ops/src/series/ops/mod.rs, crates/polars-ops/src/series/ops/not.rs, crates/polars-plan/src/dsl/function_expr/boolean.rs, py-polars/polars/series/series.py, py-polars/src/series/mod.rs, py-polars/tests/unit/datatypes/test_integer.py, py-polars/tests/unit/series/test_series.py
=> feat: add integer negation

crates/polars-arrow/src/compute/cast/mod.rs, crates/polars-plan/src/dsl/function_expr/struct_.rs, py-polars/tests/unit/namespaces/test_struct.py
=> fix: json_encode should respect to logical type

crates/polars-core/src/frame/explode.rs, crates/polars-plan/src/logical_plan/builder_functions.rs, py-polars/tests/unit/operations/test_melt.py
Closes https://github.com/pola-rs/polars/issues/10075
This now returns an empty frame.
=> fix: Fix `melt` panic when there are no value vars

crates/polars-core/src/chunked_array/logical/categorical/mod.rs, py-polars/tests/unit/operations/test_cast.py
=> fix: Preserve name when casting from categorical

crates/polars-lazy/src/physical_plan/executors/projection_utils.rs
This needs some testing by users. This may deadlock. Please compile and run your window expressions.
I cannot get it to deadlock.
=> perf: run window functions more in parallel

crates/polars-core/src/series/implementations/null.rs, py-polars/tests/unit/operations/arithmetic/test_arithmetic.py
=> feat: Implement arithmetic operations for `Null` columns

crates/polars-core/src/chunked_array/ops/compare_inner.rs, crates/polars-core/src/hashing/vector_hasher.rs, crates/polars-core/src/series/implementations/null.rs, py-polars/tests/unit/datatypes/test_null.py, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/operations/unique/test_unique.py
=> feat: Supports `unique` and `hash_rows` for `null` column

py-polars/polars/functions/aggregation/horizontal.py, py-polars/polars/functions/aggregation/vertical.py, py-polars/polars/series/series.py
=> docs(python): Document that Kleene logic is followed in `any_horizontal` and `all_horizontal`

Cargo.lock, crates/polars-ops/src/chunked_array/list/sets.rs
This should close the other dependabot PRs.
=> chore: Run `cargo update`

crates/polars-io/src/csv/read.rs, crates/polars-io/src/csv/read_impl/mod.rs, crates/polars-io/src/csv/utils.rs, crates/polars-lazy/src/physical_plan/executors/scan/csv.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-plan/src/logical_plan/builder.rs, crates/polars-plan/src/logical_plan/options.rs
=> fix: make csv parser more robust to edge cases

docs/src/python/user-guide/lazy/schema.py, docs/user-guide/concepts/lazy-vs-eager.md, docs/user-guide/lazy/schemas.md
=> docs: fix code block in user-guide/lazy/schemas

py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/operations/test_random.py, py-polars/tests/unit/operations/test_with_columns.py
Adds coverage for a few uncovered paths in `frame.py`
=> test(python): frame.py missing test coverage

crates/polars-plan/src/dsl/function_expr/struct_.rs, crates/polars-plan/src/dsl/name.rs, py-polars/docs/source/reference/expressions/name.rst, py-polars/polars/expr/name.py, py-polars/src/expr/name.rs, py-polars/tests/unit/namespaces/test_struct.py
=> feat: Implements `prefix/suffix_fields`

crates/polars-core/src/chunked_array/list/iterator.rs, crates/polars-ops/src/chunked_array/list/namespace.rs, crates/polars-plan/src/dsl/function_expr/list.rs, crates/polars-plan/src/dsl/list.rs, py-polars/docs/source/reference/expressions/list.rst, py-polars/docs/source/reference/series/list.rst, py-polars/polars/expr/list.py, py-polars/polars/series/list.py, py-polars/src/expr/list.rs, py-polars/tests/unit/namespaces/list/test_list.py
=> feat: Implements `list.gather_every`

crates/polars-core/src/chunked_array/logical/categorical/merge.rs, crates/polars-ops/src/chunked_array/list/sets.rs, crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs, py-polars/tests/unit/operations/test_sets.py
=> fix: allow set operations on list of categoricals

py-polars/polars/series/series.py, py-polars/src/series/export.rs
* `Boolean` types did an unnecessary copy with `astype(bool)` - this has been changed to `view(bool)` to avoid the copy.
* `Datetime` and `Duration` types are now zero copy if they do not contain nulls. Similar to `Boolean`, there was an `astype` call that introduced a copy - this has been changed to a `view` call.
* `Date` types cannot be converted zero copy as they are `i32` vs NumPy's `i64`. This now properly raises an error when `zero_copy_only` is enabled.
* Temporal types with nulls used to copy twice: first creating an `f32/f64` array with NaN values, then converting to NumPy datetime type which is `i64`. This has been implemented in Rust to directly generate an `i64`.
* Various related refactors
=> perf(python): Avoid unnecessary copies in `Series.to_numpy` for boolean/temporal types

crates/polars-arrow/src/array/growable/binview.rs
Hard to test, will come up with one after some sleep.
Fixes #14201
=> fix: deduplicate recursive growables

crates/polars-core/src/fmt.rs, py-polars/tests/unit/datatypes/test_object.py
=> fix: Allow format object series with registry

py-polars/polars/series/binary.py
A portion of #13161 
First contribution, so please let me know if something isn't right. All advice is appreciated.
I'll look for additional doc improvements once it looks like everything is working.
=> docs(python): Add example for `Series.bin.contains`

py-polars/polars/series/series.py, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
Closes https://github.com/pola-rs/polars/issues/14340
=> fix(python): Handle chunked Series in `Series.to_numpy`

py-polars/polars/series/series.py, py-polars/src/conversion/chunked_array.rs, py-polars/src/conversion/mod.rs, py-polars/src/series/export.rs
Maybe this also saves a copy - not sure how NumPy handles Python list input.
=> refactor(python): Update `Series.to_numpy` to handle Decimal/Time types in Rust

crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/series/comparison.rs, crates/polars-core/src/utils/supertype.rs, py-polars/src/series/comparison.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> feat: support decimal comparison

crates/polars-arrow/src/array/dictionary/value_map.rs
Clippy failed on main, I am addressing the issue here:
https://github.com/pola-rs/polars/actions/runs/7831168872/job/21366878467
=> refactor(rust): Minor refactor to satisfy clippy

crates/polars-arrow/src/array/primitive/mod.rs, crates/polars-arrow/src/array/static_array_collect.rs, crates/polars-compute/src/arity.rs, crates/polars-json/src/ndjson/file.rs, crates/polars-json/src/ndjson/write.rs, crates/polars-lazy/src/dsl/functions.rs, crates/polars-parquet/src/parquet/read/compression.rs, crates/polars-parquet/src/parquet/read/page/indexed_reader.rs, crates/polars-plan/src/utils.rs, crates/polars-time/src/chunkedarray/string/strptime.rs, crates/polars/tests/it/lazy/group_by.rs, docs/user-guide/concepts/data-types/overview.md, docs/user-guide/expressions/structs.md, docs/user-guide/migration/pandas.md, py-polars/polars/dataframe/frame.py, py-polars/polars/io/database.py, py-polars/polars/utils/_construction.py
started reading the docs today to learn some polars and noticed couple typos
=> docs: Fix some typos

crates/polars-parquet/src/arrow/read/deserialize/boolean/basic.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/decoder.rs, crates/polars-parquet/tests/it/roundtrip.rs, py-polars/tests/unit/io/test_parquet.py
=> feat: add boolean rle decoding for parquet

Makefile, py-polars/Makefile
Just some super minor things I ran into by accident.
=> chore: Update `make clean` command

py-polars/src/to_numpy.rs
@stinodego here is the `numpy` ndarray view on the `Series` side. I expect this to work. The view only works IFF we have a single chunk and no-null data
=> feat(python): expose numpy view to integer types

crates/polars-ops/src/chunked_array/hist.rs, py-polars/tests/unit/operations/test_statistics.py
=> fix: Series.hist panicking on empty/all-null

py-polars/tests/unit/functions/test_when_then.py, py-polars/tests/unit/namespaces/list/test_set_operations.py, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/series/test_series.py
Some very minor things I encountered while working on an issue.
=> test(python): Minor test refactor

py-polars/tests/unit/streaming/test_streaming.py, py-polars/tests/unit/streaming/test_streaming_group_by.py, py-polars/tests/unit/streaming/test_streaming_sort.py, py-polars/tests/unit/streaming/test_streaming_unique.py
Hopefully addresses some spurious failures.
=> test(python): Set specific temp dir for OOC tests

crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs, py-polars/tests/unit/test_arity.py
=> feat: apply negate in simplify expression pass

py-polars/tests/docs/test_user_guide.py
=> test(python): Use resolved path in `test_user_guide`

py-polars/pyproject.toml, py-polars/tests/docs/test_user_guide.py
Ref #14466
Once again closes #14442
=> ci(python): Ignore unclosed file warnings for now

crates/polars-arrow/src/io/ipc/write/common.rs, crates/polars-arrow/src/io/ipc/write/serialize/binview.rs, py-polars/tests/unit/io/test_ipc.py
=> fix: don't gc after variadic buffers are written

py-polars/polars/api.py, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/polars/series/struct.py, py-polars/polars/utils/various.py, py-polars/tests/unit/operations/test_pivot.py, py-polars/tests/unit/test_lazy.py
Ref https://github.com/pola-rs/polars/pull/13236
Credit to @Object905 for this change. I am splitting some work off from #13236 to make it easier to review.
Also removed tests that guarantee subclasses. We no longer give this guarantee, so the tests can be removed (they may block the improvements in the linked PR).
=> refactor(python): Use constant for checking Sphinx building

crates/polars-core/src/chunked_array/ops/sort/mod.rs, crates/polars-row/src/encode.rs
A regression from the string rewrite. Reported via: https://github.com/coiled/benchmarks/issues/1396
=> fix: fix binary-offset row-encode

crates/polars-ops/src/chunked_array/gather/chunked.rs
reported via https://github.com/coiled/benchmarks/issues/1396
=> fix: fix logical dtypes in take_chunked

py-polars/tests/unit/streaming/test_streaming_group_by.py, py-polars/tests/unit/streaming/test_streaming_sort.py
These can be re-enabled since #14510
=> test(python): Re-enable streaming OOC tests

crates/polars-io/src/csv/write.rs, crates/polars-pipe/src/executors/sinks/output/csv.rs, py-polars/tests/unit/streaming/test_streaming_io.py
Fixes: https://github.com/pola-rs/polars/issues/14494
=> fix: write csv header if necessary when finishing sinks

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/src/to_numpy.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py
Closes https://github.com/pola-rs/polars/issues/14519
=> feat(python): Add `writable` flag to `DataFrame.to_numpy`

crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs, crates/polars-lazy/src/tests/io.rs, crates/polars-pipe/src/executors/operators/pass.rs, crates/polars-pipe/src/executors/sinks/joins/cross.rs, crates/polars-pipe/src/executors/sinks/joins/generic_build.rs, crates/polars-pipe/src/operators/sink.rs, crates/polars-pipe/src/pipeline/convert.rs, crates/polars-pipe/src/pipeline/dispatcher.rs, py-polars/tests/unit/streaming/test_streaming_join.py
reported via #https://github.com/coiled/benchmarks/issues/1396
=> fix: ensure the streaming dispatcher can replace placeholders in unions

crates/polars-pipe/src/executors/sinks/io.rs, py-polars/tests/unit/streaming/test_streaming_group_by.py, py-polars/tests/unit/streaming/test_streaming_sort.py
supersedes #14677
fixes #13526
=> fix: Fix contention panics in file gc threads

py-polars/polars/functions/lazy.py
See https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.count.html
=> docs(python): Fix bad link due to boldness in `pl.count`

crates/polars-arrow/src/array/binview/mod.rs, crates/polars-arrow/src/array/binview/mutable.rs, crates/polars-arrow/src/array/binview/view.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/basic.rs
=> perf: fix accidental quadratic utf8 validation in parquet

crates/polars-io/src/parquet/async_impl.rs, crates/polars-io/src/pl_async.rs
@kszlim care to give this a try?
We try to increment the concurrency budget until download speeds peak.
=> perf: auto-tune concurrency budget

crates/polars-core/src/frame/group_by/hashing.rs, py-polars/tests/unit/operations/test_aggregations.py
=> fix: fix hashing specialization

Cargo.lock, py-polars/Cargo.toml, py-polars/src/conversion/mod.rs
=> python polars 0.20.12

crates/polars-io/src/parquet/read_impl.rs, crates/polars-pipe/src/executors/sources/parquet.rs
Ensure we drain the FIFO stack if limit is reached.
=> fix: Fix streaming parquet limit

py-polars/polars/datatypes/classes.py, py-polars/tests/unit/datatypes/test_datatype.py, py-polars/tests/unit/test_serde.py
Closes https://github.com/pola-rs/polars/issues/14771
=> fix(python): Remove custom `__reduce__` implementation on `DataType` object

crates/polars-pipe/src/operators/chunks.rs, crates/polars-plan/src/logical_plan/functions/count.rs
=> fix(rust): fix feature flags

crates/polars-ops/src/series/ops/cum_agg.rs, py-polars/tests/unit/functions/test_cum_count.py
Some simple and free perf opportunity :)
=> feat: Set sorted flag for `cum_count` on columns

py-polars/tests/unit/test_cpu_check.py
This affected testing on Apple M1.
=> fix: not all cpu feature flag tests were mocked

py-polars/polars/api.py, py-polars/polars/dataframe/frame.py, py-polars/polars/datatypes/classes.py, py-polars/polars/expr/expr.py, py-polars/polars/expr/whenthen.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/selectors.py, py-polars/polars/series/series.py
Reverts https://github.com/pola-rs/polars/pull/13236
Closes https://github.com/pola-rs/polars/issues/14851
=> feat(python): Revert addition of `__slots__` to Polars classes

Cargo.lock, crates/polars-ops/Cargo.toml
Requires: https://github.com/jvdd/argminmax/issues/65
=> chore: reactivate argminmax simd

crates/polars-io/src/parquet/async_impl.rs
in `ParquetObjectStore::from_uri`.
=> test(rust): Make assumption about wildcards having been resolved explicit

py-polars/polars/convert.py
=> docs(python): add note about `include_index` in `from_pandas` regarding "default indices"

crates/polars-arrow/src/array/binview/mod.rs, crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, crates/polars-lazy/src/physical_plan/planner/lp.rs, py-polars/tests/unit/operations/test_group_by.py
=> fix: Fix invalid paritionable query

crates/polars-ops/src/chunked_array/list/sets.rs, crates/polars-pipe/src/executors/sinks/memory.rs, crates/polars-pipe/src/executors/sinks/sort/ooc.rs
=> chore: fix features

crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/scan/ndjson.rs
to "Reduce memory usage at the expense of performance"
=> docs(rust): Fix typo in comment

crates/polars-io/src/csv/buffer.rs, crates/polars-io/src/csv/parser.rs, py-polars/tests/unit/io/test_csv.py
=> fix: CSV do utf8-validation after escaping fields

py-polars/polars/dataframe/frame.py
I don't think the current example really demonstrates what `join_asof` does - how about showing the same example with the different strategies and commenting on how the output changes?
=> docs(python): improve join_asof example

crates/polars-core/src/datatypes/dtype.rs, py-polars/tests/unit/datatypes/test_enum.py
=> fix: Enum equality based on categories

crates/polars-core/src/series/implementations/decimal.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> fix: agg_list on decimal lost scale

crates/polars-core/src/chunked_array/ops/sort/mod.rs, crates/polars-row/src/encode.rs, py-polars/tests/unit/operations/test_pivot.py, py-polars/tests/unit/testing/test_assert_frame_equal.py
=> feat: Support single nested row encodings

crates/polars-core/src/chunked_array/mod.rs, crates/polars-ops/src/chunked_array/strings/concat.rs
=> refactor(rust): always assert on ChunkedArray::get

crates/polars-ops/src/chunked_array/gather/chunked.rs
=> fix: Fix chunked_id gather for binview buffers

crates/polars-ops/src/chunked_array/gather/chunked.rs
=> fix: Binview chunked gather; don't modify inlined view

crates/polars-plan/src/dsl/function_expr/rolling.rs, crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs, crates/polars-time/src/chunkedarray/rolling_window/mod.rs, py-polars/polars/expr/expr.py, py-polars/tests/unit/operations/rolling/test_rolling.py
closes https://github.com/pola-rs/polars/issues/15097
=> feat: raise if both `closed` and `by` are passed to `rolling_*` aggregations

crates/polars-core/src/series/any_value.rs, py-polars/tests/unit/constructors/test_any_value_fallbacks.py
Ref #14427 
There is some duplication in the code, not sure how to solve that nicely though. Suggestions welcome.
=> feat(rust): Implement strict AnyValue construction for temporal types

crates/polars-lazy/src/physical_plan/executors/scan/ipc.rs, crates/polars-lazy/src/physical_plan/executors/scan/mod.rs, crates/polars-lazy/src/physical_plan/executors/scan/support.rs
Depends on https://github.com/pola-rs/polars/pull/15040
=> refactor(rust): Move ConsecutiveCountState into support module

crates/polars-pipe/src/executors/sources/parquet.rs
Closes https://github.com/pola-rs/polars/issues/15138
=> fix(python): fix nested runtime panic

py-polars/polars/_utils/construction/dataframe.py, py-polars/src/conversion/mod.rs, py-polars/src/dataframe/construction.rs, py-polars/src/expr/general.rs, py-polars/src/expr/meta.rs, py-polars/src/expr/mod.rs, py-polars/src/lazyframe/mod.rs, py-polars/src/series/mod.rs
Ref #15245
I am preparing to introduce propagate the `strict` parameter here, some preparation is required.
=> refactor(python): Minor refactor of `PyDataFrame.from_dicts`

crates/polars-arrow/src/bitmap/utils/iterator.rs
While in most scenarios you'd ideally avoid using `BitmapIter` in the first place, we currently do use it a lot for quick feature support. This should speed it up by loading 64 bits at a time from memory.
=> perf: load bits one word at a time for BitmapIter

.github/CODEOWNERS
=> chore: Update CODEOWNERS (polars-sql)

crates/polars-io/src/csv/write_impl.rs, py-polars/tests/unit/io/test_csv.py
=> feat: CSV-writer escape carriage return

crates/polars-plan/src/logical_plan/conversion.rs, py-polars/tests/unit/test_schema.py
=> fix: Don't prune alias in function subtree

crates/polars-arrow/src/compute/cast/utf8_to.rs, crates/polars-io/src/parquet/read_impl.rs, py-polars/tests/unit/io/test_lazy_parquet.py
Fixes https://github.com/pola-rs/polars/issues/15172
Finally found a good way to fix this :)
=> fix: Fix deadlock in async parquet scan

crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> fix: block decimal in streaming

crates/polars-core/src/chunked_array/bitwise.rs, crates/polars-lazy/src/physical_plan/planner/expr.rs, crates/polars-lazy/src/physical_plan/planner/lp.rs, crates/polars-plan/src/logical_plan/aexpr/mod.rs, crates/polars-plan/src/logical_plan/aexpr/schema.rs, crates/polars-plan/src/logical_plan/conversion.rs, crates/polars-plan/src/logical_plan/expr_ir.rs, crates/polars-plan/src/logical_plan/optimizer/fused.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs, crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs, crates/polars-plan/src/logical_plan/optimizer/simplify_functions.rs, crates/polars-plan/src/logical_plan/optimizer/slice_pushdown_expr.rs, crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs, crates/polars-plan/src/logical_plan/pyarrow.rs, crates/polars-plan/src/logical_plan/visitor/expr.rs, py-polars/tests/unit/operations/test_shift.py, py-polars/tests/unit/test_cse.py, py-polars/tests/unit/test_predicates.py, py-polars/tests/unit/test_schema.py
Not fully familiar with the new `ExprIR` architecture yet, so not sure if this is the right fix. This PR is more about showing the root cause of the problem.
This fixes #15442.
fixes #15442
fixes #15536
=> fix: Resolve function names and prune all aliases.

crates/polars-plan/src/logical_plan/optimizer/mod.rs, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/test_cse.py
=> fix: Turn off cse if cache node found

docs/src/python/user-guide/sql/intro.py, docs/user-guide/sql/intro.md
Smoothed/clarified a few things.
=> docs: Various minor updates to User Guide's SQL intro section

crates/polars-io/Cargo.toml, crates/polars-io/src/cloud/object_store_setup.rs, crates/polars-plan/src/logical_plan/pyarrow.rs
fixes #15577
fixes #15436
Also reduce cache size. Don't want to hold on to them too long.
=> fix: Include cloud creds in cache key

docs/user-guide/installation.md
[#13676](https://github.com/pola-rs/polars/pull/13676#discussion_r1565603964)
=> docs: Fix typo in legacy install instructions

crates/polars-core/src/frame/group_by/hashing.rs, crates/polars-core/src/frame/group_by/into_groups.rs
Huge perf regression. Will patch and yank.
=> perf: Fix regression that led to using only a single thread

Cargo.lock, Cargo.toml, crates/polars-arrow/src/buffer/immutable.rs, crates/polars-core/src/chunked_array/drop.rs, crates/polars-core/src/chunked_array/ops/bit_repr.rs, crates/polars-core/src/series/implementations/object.rs, crates/polars-json/src/ndjson/deserialize.rs, crates/polars-pipe/src/pipeline/convert.rs, py-polars/src/lib.rs, rust-toolchain.toml
Had to update rustc to be able to release.
=> rust polars  0.39.1

README.md
Point to up to data benchmarks.
=> refactor: Update readme

crates/polars-io/src/csv/buffer.rs, crates/polars-io/src/csv/parser.rs, crates/polars-io/src/csv/read.rs, crates/polars-io/src/csv/read_impl/batched_mmap.rs, crates/polars-io/src/csv/read_impl/batched_read.rs, crates/polars-io/src/csv/read_impl/mod.rs, crates/polars-io/src/csv/utils.rs, crates/polars-lazy/src/physical_plan/executors/scan/csv.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-plan/src/logical_plan/builder_dsl.rs, crates/polars-plan/src/logical_plan/conversion/scans.rs, py-polars/polars/io/csv/batched_reader.py, py-polars/polars/io/csv/functions.py, py-polars/src/batched_csv.rs, py-polars/src/dataframe/io.rs, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_csv.py
=> refactor: Rename decimal_float to decimal_comma

py-polars/polars/dataframe/frame.py
See #9045. I'm not sure which country, if any, was used for the original example, but Germany seems close. I haven't included examples for `by_left` and `by_right` as it doesn't seem necessary.
=> docs(python): Extend docstring examples for asof_join

Cargo.lock, py-polars/src/arrow_interop/to_py.rs, py-polars/src/arrow_interop/to_rust.rs, py-polars/src/conversion/chunked_array.rs, py-polars/src/dataframe/construction.rs, py-polars/src/dataframe/export.rs, py-polars/src/dataframe/general.rs, py-polars/src/series/construction.rs, py-polars/src/series/export.rs
Fixes #15785
The journey continues.
=> chore(python): More upgrades to PyO3 0.21 Bound<> APIs

Cargo.lock
I'm on holiday during the monthly dependabot offensive, so I'm doing some updates now to get most of it out of the way.
=> build(python): Update Cargo.lock

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/functions/mod.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/operations/test_rename.py, py-polars/tests/unit/test_lazy.py, py-polars/tests/unit/test_schema.py
=> fix: Clear cached rename schema

.github/workflows/release-python.yml
=> Revert "build: use jemalloc in lts-cpu"

crates/polars-lazy/src/scan/parquet.rs, py-polars/polars/io/parquet/functions.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_parquet.py
=> feat: Add option to disable globbing in parquet

py-polars/src/lazygroupby.rs, py-polars/src/lib.rs, py-polars/src/map/dataframe.rs, py-polars/src/map/mod.rs, py-polars/src/map/series.rs, py-polars/src/series/mod.rs
=> chore(python): Even more Pyo3 0.21 Bound<> APIs

py-polars/polars/series/series.py, py-polars/tests/unit/interop/test_interop.py
=> fix(python): converting from numpy datetime64 and overriding dtype with a different resolution was returning incorrect results

docs/src/python/user-guide/expressions/user-defined-functions.py, docs/user-guide/expressions/user-defined-functions.md
=> docs(python): Improve user-guide doc of UDF

py-polars/polars/testing/parametric/strategies.py
Following up on #16001, I figured out a much cleaner way to do this using decimal Context and [`next_minus`](https://docs.python.org/3/library/decimal.html#decimal.Context.next_minus).
=> refactor(python): Clean up hypothesis decimal strategy

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py
Add hints to:
- `pl.col("colname").native_method()`
- `pl.col("colname").list.eval(pl.element().native_method())`
Fixes #15874.
=> improve docstring of `(Expr|Series).map_elements`

crates/polars-pipe/src/executors/sources/csv.rs, py-polars/tests/unit/io/test_csv.py
and add a test for this as a safeguard
regression introduced by https://github.com/pola-rs/polars/pull/16126
=> fix: Fix CSV skip_rows_after_header for streaming

README.md, docs/index.md
Updating the banners of the README and User Guide to align with the Polars logo and branding.
=> Update banners in README and User Guide

crates/polars-core/src/chunked_array/list/mod.rs, crates/polars-core/src/chunked_array/ops/explode_and_offsets.rs, py-polars/polars/series/series.py, py-polars/src/series/export.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
=> feat(python): Support List types in `Series.to_numpy`

py-polars/polars/io/database/_executor.py, py-polars/tests/unit/io/database/test_read.py
Closes #16206.
Guarantees that the optional cursor close is deferred until after the last batch has been yielded (when `iter_batches=True`). This prevents Oracle "thick mode"[^1] clients from raising a `DPY-1006: cursor is not open` error, but is also the right way to handle this in the general case (despite no other reports about similar issues with other cursors/drivers).
Fix validated against an Oracle container running in a Linux VM running on my NAS (which does double-duty as the unofficial Polars database testing node, running a decent/representative selection of various containerised DBs 😅)
[^1]: Differences between `python-oracledb` "Thin" and "Thick" Modes: https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_b.html
=> fix(python): Improve cursor close behaviour with respect to Oracle "thick mode" connections

crates/polars-plan/src/dsl/function_expr/struct_.rs, py-polars/tests/unit/test_expansion.py
=> fix: Fix struct 'with_fields' schema for update dtypes

crates/polars-core/src/frame/chunks.rs, crates/polars-io/src/utils.rs, crates/polars-lazy/src/physical_plan/executors/filter.rs, crates/polars-lazy/src/physical_plan/executors/scan/csv.rs, py-polars/tests/unit/io/test_lazy_parquet.py, py-polars/tests/unit/io/test_parquet.py
=> perf: Fix pathological small chunk parquet writing

py-polars/polars/functions/lazy.py, py-polars/polars/lazyframe/frame.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/test_cwc.py
This adds a toggle for the `cluster_with_columns` (#16274) optimization
=> fix(python): add cluster_with_columns optimization toggle in python

py-polars/polars/dataframe/frame.py, py-polars/polars/io/delta.py, py-polars/tests/unit/io/test_delta.py
=> fix(python): write_delta()  apparently does support Categorical columns

crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/logical_plan/alp/format.rs, crates/polars-plan/src/logical_plan/conversion/expr_to_ir.rs, crates/polars-plan/src/logical_plan/expr_ir.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/projection.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix: Handle struct.fields as special case of alias

py-polars/polars/_utils/getitem.py, py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/group_by.py, py-polars/polars/expr/expr.py
Adds a fast path and updates some references.
=> feat(python): Minor `DataFrame.__getitem__` improvements

crates/polars-plan/src/logical_plan/conversion/expr_expansion.rs, py-polars/tests/unit/test_expansion.py
=> fix: Mix of column and field expansion

crates/polars-core/src/series/mod.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix(rust): properly fill null into unknown struct fields

crates/polars-expr/src/expressions/gather.rs, crates/polars-expr/src/expressions/mod.rs, py-polars/tests/unit/operations/test_gather.py
=> fix: Fix group gather of single literal

crates/polars-core/src/frame/mod.rs, crates/polars-core/src/utils/mod.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, crates/polars-ops/src/frame/join/asof/groups.rs, crates/polars-pipe/src/executors/sinks/group_by/ooc.rs, crates/polars-pipe/src/executors/sinks/sort/source.rs, crates/polars-pipe/src/executors/sources/frame.rs, crates/polars/tests/it/core/joins.rs, py-polars/tests/unit/operations/test_group_by.py
We removed most automatic rechunks and that made clear there were some chunking bugs that were hidden all along.
Will go through them today.
fixes #16516
=> fix: Ensure strict chunking in chunked partitioned group by

crates/polars-core/src/frame/chunks.rs, crates/polars-core/src/frame/mod.rs, crates/polars-core/src/series/mod.rs, py-polars/tests/unit/datatypes/test_struct.py
fixes #16536
Probably fixes #16537, but i cannot test
=> fix: Properly split struct columns

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/projection.rs, py-polars/tests/unit/io/test_lazy_parquet.py
=> fix: Project last column if count query

Cargo.lock
Quick update before dependabot spams us down a day or two from now.
=> build(python): Run `cargo update`

crates/polars-plan/src/logical_plan/optimizer/cluster_with_columns.rs
I woke up in the middle of the night and realized I wrote an unsound implementation here. This fixes an issue in CWC where some unsafe code could potentially lead to unsoundness. This should never actually have triggered. But it the spirit of keeping things maintainable in the future, I thought I would properly fix it.
=> fix(rust): small safety issue in CWC filtermap

crates/polars-io/src/parquet/read/read_impl.rs, py-polars/tests/unit/streaming/test_streaming_io.py
=> fix: ensure df in empty parquet

py-polars/docs/source/reference/expressions/functions.rst, py-polars/polars/sql/functions.py
=> docs(python): Add missing `polars.sql` docs entry and slight docstring update

crates/polars-core/src/series/implementations/null.rs, py-polars/tests/unit/datatypes/test_null.py
=> fix: Fix filter shape on empty null

crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/series/ops/null.rs, py-polars/tests/unit/test_empty.py
=> fix: Full null on dyn int

crates/polars-sql/src/functions.rs, py-polars/docs/source/reference/sql/functions/math.rst, py-polars/docs/source/reference/sql/functions/trigonometry.rst, py-polars/tests/unit/sql/test_numeric.py
* Support `SELECT DIV(a, b) AS a_div_b FROM tbl` (behaves as integer floor div).
* Also updated numeric and trig function SQL docs with extended examples.
=> feat: Add `DIV` function support to the SQL interface

crates/polars-arrow/src/bitmap/mutable.rs, py-polars/polars/functions/lazy.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/type_aliases.py, py-polars/src/conversion/mod.rs
Also adding a doc entry I forgot to add in https://github.com/pola-rs/polars/pull/16786
=> refactor(rust): Remove deprecated `MutableBitmap.null_count` method

crates/polars-core/src/chunked_array/array/iterator.rs, crates/polars-core/src/chunked_array/list/iterator.rs, crates/polars-core/src/series/unstable.rs, crates/polars-expr/src/expressions/group_iter.rs, crates/polars-ops/src/chunked_array/array/dispersion.rs, crates/polars-ops/src/chunked_array/array/join.rs, crates/polars-ops/src/chunked_array/array/sum_mean.rs, crates/polars-ops/src/series/ops/is_in.rs, py-polars/src/series/export.rs, py-polars/tests/unit/operations/test_random.py
=> fix: Reset if next caller clones inner series

crates/polars-io/src/ipc/ipc_reader_async.rs
Will speed up repeated queries
=> feat: Cache downloaded cloud IPC files

crates/polars-core/src/chunked_array/ops/sort/mod.rs
This will lead to a lot less moves during sorting as the item to swap is now 4 bytes instead of 24. It also saves a full pass from sort tuples to args.
Eventually I want to enable this for all our multicolumn sorts. First I will follow up with fixed with optimizations for row encodings that are guaranteed to be fixed with. For instance sorting by multiple integers.
=> perf: Optimize generic argsort of row-encoding

py-polars/polars/_utils/parse/__init__.py, py-polars/polars/_utils/parse/expr.py, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/array.py, py-polars/polars/expr/binary.py, py-polars/polars/expr/datetime.py, py-polars/polars/expr/expr.py, py-polars/polars/expr/list.py, py-polars/polars/expr/string.py, py-polars/polars/expr/struct.py, py-polars/polars/expr/whenthen.py, py-polars/polars/functions/aggregation/horizontal.py, py-polars/polars/functions/as_datatype.py, py-polars/polars/functions/business.py, py-polars/polars/functions/lazy.py, py-polars/polars/functions/range/date_range.py, py-polars/polars/functions/range/datetime_range.py, py-polars/polars/functions/range/int_range.py, py-polars/polars/functions/range/time_range.py, py-polars/polars/functions/repeat.py, py-polars/polars/functions/whenthen.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/lazyframe/group_by.py, py-polars/polars/plugins.py, py-polars/polars/selectors.py, py-polars/tests/unit/utils/parse/test_expr.py, py-polars/tests/unit/utils/test_parse_expr_input.py
Setting up the `parse` module to prepare an update to data type parsing.
This has zero user impact.
=> refactor(python): Refactor expression parsing utils

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
these don't currently render, see https://docs.pola.rs/api/python/dev/reference/api/polars.DataFrame.write_parquet.html
=> docs(python): fixup bullet points in write_parquet

py-polars/tests/unit/io/cloud/test_aws.py
Ref https://github.com/pola-rs/polars/issues/16910
=> test(python): Skip another intermitently failing AWS test

crates/polars-arrow/src/array/binview/buffers.rs, crates/polars-compute/src/if_then_else/view.rs
=> perf: GC buffers in if_then_else view kernel

py-polars/tests/unit/operations/test_cross_join.py
=> test: Use proper join type in test

_typos.toml, docs/releases/upgrade/1.md, mkdocs.yml
Ref https://github.com/pola-rs/polars/issues/16773
This includes all changes up to this point. Will do another update before 1.0.0 final release.
=> docs(python): Add upgrade guide for Python Polars 1.0.0

crates/polars-ops/src/frame/join/mod.rs, crates/polars-pipe/src/executors/sinks/joins/row_values.rs, py-polars/tests/unit/operations/test_join.py
=> fix: Fix oob of join with literals and empty table

crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, py-polars/tests/unit/operations/test_group_by_dynamic.py
=> fix: Exclude index from expansion in rolling/group_by_dynamic

py-polars/tests/unit/operations/test_pivot.py
=> test: Add pivot test #17081

py-polars/src/allocator.rs
Closes #17040
We should do a better job of gating these allocators, it's a bit confusing 😕
=> build(python): Fix config flag for Tracemalloc

py-polars/polars/functions/as_datatype.py
Ref https://github.com/pola-rs/polars/issues/8510
=> docs(python): Add doc examples to `concat_list`

crates/polars-lazy/src/scan/mod.rs, crates/polars-lazy/src/scan/ndjson.rs, crates/polars-lazy/src/scan/parquet.rs
=> fix(rust): Fix feature gate

crates/polars-mem-engine/src/executors/scan/mod.rs, crates/polars-plan/src/plans/builder_dsl.rs
Fixes https://github.com/pola-rs/polars/issues/17138
=> fix(rust): Fix feature gates

crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs
=> fix: Use explicit turbofish to help rustc

crates/polars-plan/src/plans/aexpr/schema.rs, py-polars/tests/unit/operations/arithmetic/test_arithmetic.py
=> fix: Allow sub on date/datetime

crates/polars-ops/src/series/ops/round.rs
Fixes https://github.com/pola-rs/polars/issues/17240.
=> feat: allow no-op round/ceil/floor on int types

crates/polars-arrow/src/legacy/kernels/list.rs, py-polars/tests/unit/operations/test_gather.py
=> fix: Fix list getter with nulls

py-polars/docs/source/reference/sql/functions/types.rst
101010 is greater than uint2 max of 65535
=> correct try_cast example

Cargo.lock, Cargo.toml
=> rust Polars 0.41.3

crates/polars-core/src/schema.rs
=> refactor(rust): Remove dead code

py-polars/polars/dataframe/frame.py
Following up on https://github.com/pola-rs/polars/pull/17383
=> docs(python): Update `partition_by` docstring to match new behavior

py-polars/docs/source/reference/io.rst
Just adding the Sphinx entry to include it in the API HTML docs.
=> docs(python): Add `write_parquet_partitioned`

README.md
An update of the SQL examples in the README. I have replaced the `pl.SQLContext` with the recently added more accessible `df.sql()` and `pl.sql()`. Tried to keep the example as small as possible. 
As a bonus I have also aligned, tested and updated the SQL example queries for the polars-cli.
=> docs: Update SQL examples in README

crates/polars-plan/src/plans/functions/schema.rs
=> fix: Don't needlessly unwrap in `pivot_schema`

py-polars/polars/expr/binary.py
an attempt at #17469 
I tried sticking with the theme of colors for the example and made sure to run the code example double check that the output is the same
=> docs: Create example for `polars.Expr.bin.decode`

crates/polars-core/src/chunked_array/ops/gather.rs, crates/polars-core/src/frame/group_by/aggregations/agg_list.rs, py-polars/tests/unit/datatypes/test_struct.py
=> refactor: Fix struct gather

crates/polars-ops/src/series/ops/is_in.rs, py-polars/tests/unit/operations/test_is_in.py
=> fix: Fix struct -> enum is_in

crates/polars-io/src/file_cache/cache.rs, crates/polars-io/src/file_cache/entry.rs, crates/polars-io/src/file_cache/file_fetcher.rs, crates/polars-io/src/file_cache/metadata.rs
Fixes https://github.com/pola-rs/polars/issues/17683
=> fix: Use ETag for HTTP file cache invalidation

py-polars/requirements-dev.txt
Reverts https://github.com/pola-rs/polars/pull/17695, issue fixed upstream (https://github.com/pypa/setuptools/issues/4480).
=> chore(python): Unpin `setuptools`

py-polars/src/lazyframe/mod.rs
=> feat(python): Release the GIL in `collect_schema`

crates/polars-core/src/frame/horizontal.rs, crates/polars-core/src/frame/mod.rs, crates/polars-core/src/functions.rs
=> perf: Fix accidental quadratic horizontal concat

crates/polars-plan/src/plans/expr_ir.rs, crates/polars-plan/src/plans/optimizer/projection_pushdown/projection.rs, py-polars/tests/unit/test_projections.py
=> fix: Fix projection pusdhown of literals without names

docs/src/python/user-guide/io/hugging-face.py, docs/user-guide/io/hugging-face.md
This needs https://github.com/pola-rs/polars/pull/17785
This also removes the live network request to HF as it can cause some instability in our CI - we just print a pre-recorded result instead
=> docs(python): Mention `read_*` functions in Hugging Face section in user guide

py-polars/polars/io/ipc/functions.py, py-polars/polars/io/ndjson.py
ref https://github.com/pola-rs/polars/pull/17785/files#r1688138058
=> fix(python): Restore accidentally removed deprecated parameters

crates/polars-plan/src/plans/schema.rs, py-polars/tests/unit/operations/test_join_right.py
=> fix: Fix right join schema

crates/polars-plan/src/dsl/list.rs, py-polars/tests/unit/test_errors.py
=> fix: Check input type on list.to_struct

crates/polars-core/src/chunked_array/ops/fill_null.rs
Go via `gather`. This will likely be faster for binary/string and nested data. For the binary/strings we can keep views and buffers and can prevent a lot of data copy.
=> feat: Implement forward/backward fill for all types

docs/src/rust/user-guide/getting-started/joins.rs
=> docs: Updating the join example input for rust for consistency with python example

crates/polars-plan/src/dsl/function_expr/shrink_type.rs
=> fix: Handle `cfg(feature)` for `shrink_dtype`

docs/user-guide/concepts/data-types/overview.md
=> docs: Mention 'Array' in data types overview

crates/polars-core/src/chunked_array/binary.rs, crates/polars-core/src/chunked_array/ops/sort/mod.rs, crates/polars-core/src/frame/group_by/into_groups.rs, crates/polars-core/src/frame/group_by/perfect.rs, crates/polars-ops/src/chunked_array/top_k.rs, py-polars/src/conversion/mod.rs
=> perf: Use single threaded algorithms if only 1 core given

.cargo/config.toml, .gitignore, py-polars/Cargo.toml
Closes https://github.com/pola-rs/polars/issues/18088.
=> perf: Tune jemalloc to not create muzzy pages

crates/polars-core/src/chunked_array/builder/list/anonymous.rs, crates/polars-core/src/chunked_array/ops/shift.rs, crates/polars-core/src/series/implementations/struct__.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix: Fix struct shift and list builder

py-polars/polars/expr/expr.py, py-polars/tests/unit/operations/test_gather.py
=> fix(python): Fix gather str as lit

crates/polars-ops/src/series/ops/rank.rs, py-polars/tests/unit/expr/test_exprs.py, py-polars/tests/unit/operations/test_random.py, py-polars/tests/unit/operations/test_rank.py, py-polars/tests/unit/series/test_series.py
=> fix: Fix unit null rank

crates/polars-io/src/csv/read/schema_inference.rs
=> feat: Improve decimal_comma error message

docs/user-guide/io/hugging-face.md
missed a spot, caused a gateway error
https://github.com/pola-rs/polars/actions/runs/10611269926/job/29410451125?pr=18425
=> refactor: Remove network call in hive docs

crates/polars-io/src/parquet/read/read_impl.rs, py-polars/tests/unit/io/test_parquet.py
=> fix: Handle Parquet projection pushdown with only row index

Cargo.lock, py-polars/Cargo.toml
The merge of #18425 accidentally reset this to 1.5.
=> fix(python): Fix advertised version in source builds

py-polars/requirements-dev.txt
Ref https://github.com/pola-rs/polars/issues/18543
=> ci: Temporarily pin NumPy in CI to address dependency resolving issue

crates/polars-plan/src/plans/conversion/join.rs, py-polars/tests/unit/operations/test_inequality_join.py
=> chore: Check predicates in join_where

crates/polars-json/src/ndjson/deserialize.rs
It's entirely unnecessary, the code wants a `u8` buffer so we can just use a `u8` buffer.
=> refactor(rust): Remove unsafe in polars-json deserialize code

py-polars/pyproject.toml
=> chore(python): Remove TODO comment regarding NumPy pinning

crates/polars-stream/src/execute.rs, crates/polars-stream/src/pipe.rs
Very subtle but luckily panics caught this error.
=> refactor(rust): Fix topological sort in new streaming engine

docs/source/_build/API_REFERENCE_LINKS.yml, docs/source/user-guide/sql/select.md
=> docs: Fix broken user-guide API links

crates/polars-core/src/datatypes/any_value.rs, crates/polars-python/src/dataframe/export.rs, py-polars/tests/unit/test_convert.py
=> fix: Properly cast AnyValue string

crates/polars-core/src/chunked_array/list/iterator.rs, crates/polars-python/src/interop/numpy/to_numpy_series.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
=> fix(python): Fix list to numpy conversion

crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/plans/aexpr/schema.rs, py-polars/tests/unit/test_schema.py
=> fix: Fix nested flag of functions with multiple arguments

crates/polars-pipe/src/pipeline/dispatcher/drive_operator.rs, py-polars/tests/unit/streaming/test_streaming_join.py
=> fix: Ensure `must_flush` flag is not reset

docs/source/src/python/user-guide/lazy/schema.py, docs/source/user-guide/lazy/schemas.md
=> docs: Fix example of lazy schema verification

crates/polars-core/src/chunked_array/ops/chunkops.rs, crates/polars-ops/src/series/ops/cum_agg.rs, py-polars/tests/unit/series/test_series.py
Fixes https://github.com/pola-rs/polars/issues/19052.
=> feat: Add cum(_min/_max) for pl.Boolean

crates/polars-mem-engine/src/executors/projection_utils.rs
=> feat: Improve scalar strict message

crates/polars-core/src/chunked_array/ops/zip.rs, py-polars/tests/unit/functions/test_when_then.py
=> fix: Properly broadcast Struct when then validity

crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, py-polars/tests/unit/io/test_parquet.py
=> fix: Properly handle non-nullable nested Parquet

docs/source/user-guide/getting-started.md
Small spelling error fix on `getting_started`
=> docs: spelling error on getting_started.md

docs/source/user-guide/misc/visualization.md, py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/plotting.py, py-polars/polars/series/plotting.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/namespaces/test_plot.py
=> fix: Plotting was not interacting well with Altair schema wrappers

crates/polars-io/src/parquet/read/read_impl.rs
=> fix: Don't remember Parquet statistics if filtered

docs/source/user-guide/ecosystem.md
We love polars @ marimo and have great integration with polars. We would love to be a part of your ecosystem page
=> docs: Add marimo to ecosystem.md

py-polars/docs/source/reference/sql/functions/aggregate.rst, py-polars/polars/expr/expr.py
* Added Sphinx entries for the new SQL functions.
* Also made a minor clarification to the forward/backward fill definition.
=> docs: Add SQL docs for new `QUANTILE_CONT` and `QUANTILE_DISC` functions

crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-parquet/src/arrow/read/deserialize/simple.rs, crates/polars-parquet/src/arrow/read/schema/metadata.rs, crates/polars-parquet/src/parquet/metadata/sort.rs, crates/polars-parquet/src/parquet/parquet_bridge.rs, crates/polars-parquet/src/parquet/schema/types/spec.rs, py-polars/tests/unit/io/test_parquet.py
This can only be merged once #19275 is merged.
Fixes #19265.
=> feat: Support decoding Float16 in Parquet

crates/polars-core/src/series/ops/reshape.rs, py-polars/tests/unit/operations/namespaces/list/test_list.py
=> fix: Fix struct reshape fast path

crates/polars-expr/src/expressions/alias.rs, crates/polars-mem-engine/src/planner/lp.rs
=> fix: Don't vertically parallelize literal select

crates/polars-plan/src/dsl/function_expr/list.rs, py-polars/tests/unit/operations/test_gather.py
=> fix: Fix list gather invalid fast path

crates/polars-lazy/src/physical_plan/exotic.rs
=> fix: Error on invalid query

crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/utils/supertype.rs, crates/polars-ops/src/frame/pivot/unpivot.rs, py-polars/tests/unit/operations/test_unpivot.py
=> fix: Merge categorical rev-map in `unpivot`

crates/polars-arrow/src/compute/take/fixed_size_list.rs, py-polars/tests/unit/operations/test_gather.py
=> fix: Fix empty array gather

crates/polars-core/src/series/implementations/struct_.rs, py-polars/tests/unit/datatypes/test_struct.py
Fixes https://github.com/pola-rs/polars/issues/19445
=> fix: Fix incorrect reverse on struct containing NULLs

crates/polars-core/src/frame/group_by/perfect.rs, py-polars/tests/unit/datatypes/test_categorical.py
=> fix: Fix perfect groupby

crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs, crates/polars-mem-engine/src/planner/lp.rs, crates/polars-plan/src/plans/aexpr/utils.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/conversion/join.rs, crates/polars-plan/src/plans/mod.rs, crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs, crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs, crates/polars-stream/src/skeleton.rs
=> perf: Don't split par if cast to categorical

py-polars/tests/unit/io/test_parquet.py
Fixed by https://github.com/pola-rs/polars/pull/19476
=> test(python): Unskip Decimal test

crates/polars-io/src/csv/read/read_impl.rs, py-polars/tests/unit/io/test_csv.py
Fixes https://github.com/pola-rs/polars/issues/19535
=> fix: Ignore quoted newlines when skipping lines in CSV

crates/polars-expr/src/expressions/aggregation.rs, crates/polars-expr/src/expressions/gather.rs, py-polars/tests/unit/operations/test_gather.py
=> fix: Fix gather len in group-by state

crates/polars-io/src/path_utils/hugging_face.rs, crates/polars-plan/src/plans/ir/scan_sources.rs, rust-toolchain.toml
Together with https://github.com/pola-rs/polars/pull/19545 this should probably fix our CI woes.
=> refactor: Update nightly compiler version

crates/polars-plan/src/dsl/list.rs
=> fix: Only allow `list.to_struct` to be elementwise when width is fixed

Cargo.lock, Cargo.toml, crates/Makefile, crates/polars-dylib/Cargo.toml, crates/polars-dylib/README.md, crates/polars-dylib/src/lib.rs, crates/polars/Cargo.toml
Add a dynamic library for Rust users.
=> feat(rust): Add dylib

py-polars/polars/functions/lazy.py
Fixed small typo in function description according to this issue #19757
=> fix(python): Fixed typo in file lazy.py

crates/polars-core/src/frame/column/mod.rs, py-polars/tests/unit/operations/test_join.py
=> fix: Fix gather of Scalar null + idx w/ validity

crates/polars-arrow/src/ffi/array.rs
For when we want to move the casting code in the future.
=> refactor(rust): Remove use of cast in `ArrowArray::new`

crates/polars-core/src/frame/column/scalar.rs
=> fix: Fix panic when joining with empty frame (debug only)

crates/polars-core/src/chunked_array/logical/categorical/builder.rs, crates/polars-core/src/chunked_array/logical/categorical/mod.rs, crates/polars-core/src/chunked_array/logical/enum_/mod.rs, crates/polars-core/src/frame/group_by/mod.rs, crates/polars-core/src/frame/group_by/perfect.rs, crates/polars-core/src/series/implementations/categorical.rs, crates/polars-ops/src/series/ops/cut.rs, py-polars/tests/unit/datatypes/test_categorical.py
=> fix: Toggle 'fast_unique' on new_from_index

crates/polars-core/src/frame/column/mod.rs, py-polars/tests/unit/test_scalar.py
=> fix: Fix `gather_every` for `Scalar`

.github/workflows/release-python.yml
=> Revert "build: Add windows-aarch64 to python binaries"

crates/polars-core/src/chunked_array/ops/sort/mod.rs, py-polars/tests/unit/operations/test_sort.py
Fixes #19945.
Separated this from #19872.
=> fix: Bug fix in existing fast path for sorted series

crates/polars-core/src/frame/mod.rs
=> perf: Cache the DataFrame schema in get_column_index

Cargo.lock, Cargo.toml
Doing a round of Rust updates, one at a time to be sure...
=> build: Bump `chrono-tz` to `0.10`

Cargo.lock, Cargo.toml
Changelog here:
https://github.com/RazrFalcon/memmap2-rs/blob/master/CHANGELOG.md
=> build: Bump `memmap2` to version `0.9`

crates/polars-core/src/frame/mod.rs, py-polars/tests/unit/dataframe/test_df.py
=> fix: DataFrame `.get_column` after `drop_in_place`

crates/polars-io/src/parquet/read/read_impl.rs, py-polars/tests/unit/io/test_hive.py, py-polars/tests/unit/io/test_parquet.py
Fixes https://github.com/pola-rs/polars/issues/20175
=> fix: Column name mismatch or not found in Parquet scan with filter

crates/polars-io/src/csv/read/buffer.rs, py-polars/tests/unit/datatypes/test_enum.py
=> feat: Support reading Enum dtype from csv

crates/polars-core/src/series/mod.rs, py-polars/polars/dataframe/frame.py, py-polars/tests/unit/datatypes/test_object.py
=> fix: Estimated size for object

py-polars/polars/_utils/udfs.py
Ref: #20272.
* Spotted an opportunity to early-exit on first detection of a known-unparseable instruction during initial bytecode introspection/rewrite.
* Can significantly reduce overhead when checking the bytecode of functions for which we cannot offer an equivalent Polars expression (no change in speed otherwise).
```python
df = pl.DataFrame([], schema={'x': pl.Float64})
def add_with_locals(x):
y = 3
z = 4
return x + y + z
```
_(disassembled function bytecode)_
```python
```
```
%timeit df.select(pl.col('x').map_elements(add_with_locals, int))
```
~4x lower latency (in this case) because as soon as the `STORE_FAST` instruction is seen (we don't support intermediate assignment such as `y=3` in the function body) we now _immediately_ exit the parsing loop instead of finishing instruction …
=> perf(python): Lower overhead for `BytecodeParser` on introspection of incompatible UDFs

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
=> docs: Clarify the join pre-condition of `join_asof`

Cargo.lock, Cargo.toml
https://github.com/calebzulawski/multiversion/blob/master/CHANGELOG.md
=> chore: Bump multiversion from 0.7 to 0.8

.github/workflows/benchmark.yml
=> ci: Remove upload/download sizes 

py-polars/docs/source/reference/datatypes.rst
=> docs: Add docs reference for `Field`

docs/source/user-guide/plugins/index.md
Just saw a small typo in #20653
=> docs: Fix small typo in plugins

py-polars/polars/selectors.py
=> fix(python): Fix xor operation of selector with Expr

crates/polars-python/src/series/map.rs, py-polars/tests/unit/operations/map/test_map_elements.py
=> fix: Fix `map_elements` panicking with Decimal type

py-polars/polars/expr/expr.py, py-polars/tests/unit/operations/test_window.py
=> feat: Expose descending and nulls last in window order-by

crates/polars-core/src/datatypes/field.rs, py-polars/tests/unit/datatypes/test_float.py
=> fix: Add Arrow Float16 conversion DataType

crates/polars-plan/src/plans/options.rs, crates/polars-stream/src/physical_plan/lower_expr.rs, crates/polars-stream/src/physical_plan/lower_ir.rs, py-polars/tests/unit/operations/test_with_columns.py
Fixes https://github.com/pola-rs/polars/issues/20981.
Fixes https://github.com/pola-rs/polars/issues/20930.
=> fix: Ensure scalar-only with_columns are broadcasted on new-streaming

crates/polars-stream/src/nodes/joins/equi_join.rs
This is actually a pretty large improvement, the old system created a huge amount of morsels for no good reason.
=> perf: Recombine into larger morsels in new-streaming join

crates/polars-time/src/windows/group_by.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
=> fix: Fix rolling on empty DataFrame panicking

py-polars/polars/dataframe/frame.py, py-polars/requirements-dev.txt, py-polars/requirements-lint.txt, py-polars/tests/unit/dataframe/test_getitem.py, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/io/test_other.py, py-polars/tests/unit/lazyframe/cuda/test_node_visitor.py, py-polars/tests/unit/lazyframe/test_getitem.py, py-polars/tests/unit/operations/arithmetic/test_arithmetic.py, py-polars/tests/unit/operations/test_hist.py, py-polars/tests/unit/sql/test_set_ops.py, py-polars/tests/unit/streaming/test_streaming.py, py-polars/tests/unit/test_api.py, py-polars/tests/unit/test_config.py
Upgrades `ruff` and `pytest-codspeed` packages and applies latest formatting per #21035
=> chore(python): Upgrade packages and apply latest formatting

crates/polars-expr/src/reduce/convert.rs, crates/polars-expr/src/reduce/count.rs, crates/polars-expr/src/reduce/mod.rs, crates/polars-stream/src/physical_plan/lower_expr.rs, crates/polars-stream/src/physical_plan/lower_group_by.rs
Kinda silly I forgot about this one for so long.
=> perf: Implement native Expr.count() on new-streaming

crates/polars-plan/src/plans/optimizer/cse/cse_expr.rs, py-polars/tests/unit/test_cse.py
=> fix: Fix cse panic

crates/polars-mem-engine/src/executors/scan/python_scan.rs, py-polars/tests/unit/io/test_io_plugin.py
=> fix: Fix IO plugin predicate with failed serialization

crates/polars-plan/src/plans/optimizer/projection_pushdown/functions/mod.rs, crates/polars-plan/src/plans/optimizer/projection_pushdown/functions/unpivot.rs, crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs, py-polars/tests/unit/test_projections.py
=> fix: Fix projection count query optimization

docs/source/index.md
The recently changed Arrow key feature description seems a little awkward and maybe missing some words. Hopefully this improves the flow a little.
=> docs: Improve Arrow key feature description

crates/polars-plan/src/plans/optimizer/mod.rs
per https://github.com/pola-rs/polars/pull/20949#discussion_r1947548695
=> chore: Add feature gate to old streaming deprecation warning

crates/polars-plan/src/plans/aexpr/evaluate.rs, crates/polars-plan/src/plans/aexpr/predicates/column_expr.rs, crates/polars-plan/src/plans/aexpr/predicates/mod.rs, crates/polars-plan/src/plans/aexpr/predicates/skip_batches.rs, crates/polars-python/src/expr/general.rs, py-polars/polars/expr/expr.py, py-polars/tests/unit/io/test_skip_batch_predicate.py
This fixes a regression that caused us to not skip row groups sometimes.
=> fix: Properly implement and test Skip Batch Predicate

crates/polars-plan/src/dsl/function_expr/struct_.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix: Adding a struct field using a literal raises InvalidOperationError

crates/polars-python/src/conversion/any_value.rs, py-polars/tests/unit/datatypes/test_temporal.py
=> fix: try converting pandas `pytz` timezone to `zoneinfo` timezone

crates/polars-ops/src/frame/join/merge_sorted.rs, py-polars/tests/unit/operations/test_merge_sorted.py
=> fix: Incorrect result for merge_sorted with lexical categorical

py-polars/polars/io/cloud/credential_provider/_providers.py
ref https://github.com/pola-rs/polars/pull/21047#issuecomment-2657911847
=> feat(python): Rename `credentials` parameter to `credential` in `CredentialProviderAzure`

docs/source/user-guide/migration/pandas.md
Informing our docs AI of some differences.
=> docs: Add pandas strictness API difference

crates/polars-stream/src/nodes/io_sources/csv.rs, crates/polars-stream/src/nodes/io_sources/ipc.rs, crates/polars-stream/src/nodes/io_sources/mod.rs, crates/polars-stream/src/nodes/io_sources/multi_scan.rs, crates/polars-stream/src/nodes/io_sources/parquet/mod.rs, crates/polars-stream/src/physical_plan/lower_ir.rs, crates/polars-stream/src/physical_plan/mod.rs, py-polars/tests/unit/io/test_multiscan.py
=> feat: Add negative slicing to new streaming multiscan

crates/polars-lazy/src/tests/mod.rs
=> fix: Rust test race condition

crates/polars-core/src/chunked_array/logical/enum_/mod.rs, py-polars/tests/unit/operations/test_group_by.py
=> fix: Properly set `fast_unique` in EnumBuilder

py-polars/tests/unit/operations/test_join.py
Because it is flaky: https://github.com/pola-rs/polars/actions/runs/13435902725/job/37537994733?pr=21366
=> fix: Mark test as may_fail_auto_streaming

crates/polars-core/src/series/arithmetic/borrowed.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix: Struct arithmetic broadcasting behavior

crates/polars-compute/src/cast/mod.rs, crates/polars-compute/src/cast/primitive_to.rs, py-polars/tests/unit/test_format.py
=> feat: Implement i128 -> str cast

crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/mean.rs, crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/sum.rs, crates/polars-arrow/src/legacy/kernels/rolling/nulls/mean.rs, crates/polars-arrow/src/legacy/kernels/rolling/nulls/sum.rs, crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
fixes #11146
fixes #21358
@MarcoGorelli  know of any more issues this will close?
=> fix: Use Kahan summation for rolling sum kernels. Fix numerical stability issues

crates/polars-time/src/chunkedarray/datetime.rs
https://github.com/pola-rs/polars/pull/21410#discussion_r1966738203
=> chore(rust): Refactor ordinal_day

py-polars/polars/lazyframe/frame.py
Cloud needs them and preparation of the coupling of the `sink_*` to the new streaming engine, which I expect to land soon.
=> feat: Activate all optimizations in sinks

py-polars/polars/series/series.py, py-polars/tests/unit/datatypes/test_duration.py
fixes #9637
fixes #14094 
closes #11387
Notes: 
#14094 includes a mention of floordiv but #19908 is an open issue specific to duration floordiv.
#11387 is related and already fixed so just closing as part of this.
=> fix(python): Duration Series arithmetic operations

docs/source/user-guide/polars_llms.md, mkdocs.yml
=> docs(python): Add Polars & LLMs page to the user guide

crates/polars-compute/src/var_cov.rs, crates/polars-expr/src/reduce/var_std.rs
@ritchie46 I believe this should work.
=> refactor(rust): Add remove_one to VarState for use in rolling variance

crates/polars-arrow/src/array/builder.rs, crates/polars-core/src/frame/builder.rs, crates/polars-core/src/frame/mod.rs, crates/polars-core/src/series/builder.rs, crates/polars-core/src/series/mod.rs
Not used/tested yet, but a nice standalone PR regardless.
=> refactor(rust): Add SeriesBuilder and DataFrameBuilder

crates/polars-arrow/src/array/binview/builder.rs, crates/polars-arrow/src/array/boolean/builder.rs, crates/polars-arrow/src/array/builder.rs, crates/polars-arrow/src/array/fixed_size_binary/builder.rs, crates/polars-arrow/src/array/fixed_size_list/builder.rs, crates/polars-arrow/src/array/list/builder.rs, crates/polars-arrow/src/array/null.rs, crates/polars-arrow/src/array/primitive/builder.rs, crates/polars-arrow/src/array/struct_/builder.rs, crates/polars-arrow/src/bitmap/builder.rs, crates/polars-core/src/frame/builder.rs, crates/polars-core/src/series/builder.rs
Forgot these are needed for the join.
=> refactor(rust): Add opt_gather and extend_nulls to builders

crates/polars-arrow/src/array/binview/builder.rs, crates/polars-arrow/src/array/builder.rs
Also makes the builders `Send`.
=> fix: Bad view index in BinaryViewBuilder

crates/polars-row/src/variable/no_order.rs, py-polars/tests/unit/streaming/test_streaming_group_by.py
Fixes https://github.com/pola-rs/polars/issues/21593.
=> fix: Bad null handling in unordered row encoding

crates/polars-python/src/lazyframe/general.rs
=> fix(python): Release the gil on explain

crates/polars-core/src/chunked_array/logical/categorical/builder.rs, crates/polars-io/src/csv/read/buffer.rs, py-polars/tests/unit/io/test_csv.py
=> fix: Check enum categories when reading csv

crates/polars-io/src/cloud/adaptors.rs, crates/polars-io/src/file_cache/file_fetcher.rs, crates/polars-io/src/file_cache/utils.rs, crates/polars-io/src/path_utils/mod.rs, crates/polars-io/src/pl_async.rs, crates/polars-io/src/utils/file.rs, crates/polars-mem-engine/src/executors/scan/ipc.rs, crates/polars-mem-engine/src/executors/scan/parquet.rs, crates/polars-pipe/src/executors/sources/parquet.rs, crates/polars-plan/src/plans/conversion/scans.rs, crates/polars-python/src/catalog/unity.rs
Makes it clear that the function can also be called from an async thread.
=> refactor(rust): Rename `block_on_potential_spawn` to `block_in_place_on`

crates/polars-expr/src/state/execution_state.rs, crates/polars-mem-engine/src/executors/cache.rs, crates/polars-mem-engine/src/executors/merge_sorted.rs, crates/polars-mem-engine/src/planner/lp.rs, crates/polars-plan/src/plans/optimizer/cache_states.rs, py-polars/tests/unit/test_cse.py
This ensures we can always parallelize downstream.
closes #21637
=> perf: Pre-fill caches

Cargo.lock, crates/polars-ffi/src/version_0.rs, crates/polars-plan/Cargo.toml, crates/polars-plan/src/client/check.rs, crates/polars-plan/src/plans/python/utils.rs, crates/polars-python/Cargo.toml, crates/polars-python/src/dataframe/general.rs, py-polars/tests/unit/cloud/test_prepare_cloud_plan.py
This makes it work with different compilation units.
=> feat: Use FFI to read dataframe instead of transmute

crates/polars-compute/src/var_cov.rs
Fixes https://github.com/pola-rs/polars/issues/21677.
=> fix: Variance can never be negative

crates/polars-expr/src/reduce/sum.rs, py-polars/tests/unit/streaming/test_streaming.py
=> fix: Support 128 sum reduction on new streaming

crates/polars-stream/src/nodes/io_sources/multi_scan.rs, py-polars/polars/_typing.py, py-polars/polars/_utils/cloud.py, py-polars/polars/_utils/deprecation.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/datatypes/test_struct.py, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/io/test_hive.py, py-polars/tests/unit/io/test_lazy_csv.py, py-polars/tests/unit/io/test_lazy_parquet.py, py-polars/tests/unit/io/test_parquet.py, py-polars/tests/unit/io/test_scan.py, py-polars/tests/unit/lazyframe/test_with_context.py, py-polars/tests/unit/operations/test_concat.py, py-polars/tests/unit/operations/test_is_sorted.py, py-polars/tests/unit/operations/test_join.py, py-polars/tests/unit/streaming/test_streaming.py, py-polars/tests/unit/streaming/test_streaming_categoricals.py, py-polars/tests/unit/streaming/test_streaming_cse.py, py-polars/tests/unit/streaming/test_streaming_group_by.py, py-polars/tests/unit/streaming/test_streaming_io.py, py-polars/tests/unit/streaming/test_streaming_join.py, py-polars/tests/unit/streaming/test_streaming_sort.py, py-polars/tests/unit/streaming/test_streaming_unique.py
=> chore: Remove old-streaming from engine argument

crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, py-polars/tests/unit/operations/test_sort.py
=> fix: Support nulls in multi-column sort

crates/polars-mem-engine/src/executors/scan/python_scan.rs, py-polars/tests/unit/io/test_io_plugin.py
=> fix: IO plugin; support empty iterator

crates/polars-plan/src/plans/python/predicate.rs
=> feat: Support all elementwise functions in IO plugin predicates

crates/polars-io/src/utils/mod.rs, crates/polars-io/src/utils/sync_on_close.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-mem-engine/src/executors/executor.rs, crates/polars-mem-engine/src/planner/lp.rs, crates/polars-plan/src/dsl/options.rs, crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs, crates/polars-python/src/lazyframe/sink.rs, crates/polars-stream/src/nodes/io_sinks/csv.rs, crates/polars-stream/src/nodes/io_sinks/ipc.rs, crates/polars-stream/src/nodes/io_sinks/json.rs, crates/polars-stream/src/nodes/io_sinks/mod.rs, crates/polars-stream/src/nodes/io_sinks/parquet.rs
This is a prerequisite for #21689.
=> refactor: Add sinks into the DSL before optimization

crates/polars-arrow/src/array/fixed_size_list/builder.rs, crates/polars-arrow/src/array/list/builder.rs
Honestly just silly bugs from me. Also improved the grouping logic a bit / made it more robust against overflows.
=> fix: Incorrect (FixedSize)ListArrayBuilder gather implementation

crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs, py-polars/tests/unit/operations/test_join.py
Enabled via row encoding.
closes #14826
closes #18120
=> feat: Enable joins on list/array dtypes

py-polars/tests/unit/operations/test_join_right.py
As seen in https://github.com/pola-rs/polars/actions/runs/13816141080/job/38649729686?pr=21717
=> chore: Remove order check from flaky test

crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs
Properly implemented in https://github.com/pola-rs/polars/pull/21528.
=> chore: Remove variance numerical stability hack

crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs, py-polars/tests/unit/operations/test_rolling.py
Closes https://github.com/pola-rs/polars/issues/21740.
=> feat: Add support for rolling_(sum/min/max) for booleans through casting

crates/polars-core/src/chunked_array/cast.rs, py-polars/tests/unit/operations/test_cast.py
=> fix: Disallow cast from boolean to categorical/enum

docs/source/user-guide/ecosystem.md
Fixes https://github.com/pola-rs/polars/issues/21759
=> docs: Add skrub to ecosystem.md

crates/polars-io/src/file_cache/cache_lock.rs, crates/polars-io/src/file_cache/entry.rs, crates/polars-io/src/file_cache/eviction.rs
Should resolve some file not found errors in CI.
=> fix: Fix error due to race condition in file cache

py-polars/polars/_utils/deprecation.py, py-polars/tests/unit/streaming/test_streaming.py
=> fix: Deprecation of `streaming=False`

crates/polars-stream/src/nodes/io_sinks/csv.rs
=> fix: Respect header separator in `sink_csv`

crates/polars-arrow/src/array/boolean/mod.rs, crates/polars-core/src/chunked_array/ops/chunkops.rs, crates/polars-core/src/chunked_array/ops/set.rs, crates/polars-expr/src/expressions/aggregation.rs, py-polars/tests/unit/operations/test_group_by.py
=> fix: Fix div 0 partitioned group-by

crates/polars-mem-engine/src/executors/group_by_partitioned.rs, py-polars/tests/unit/operations/test_group_by.py
=> fix: Fix partitioned group-by broadcast 

crates/polars-ops/src/series/ops/rle.rs, crates/polars-plan/src/dsl/options.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/conversion/mod.rs, crates/polars-python/src/lazyframe/sink.rs, crates/polars-stream/src/nodes/io_sinks/partition/by_key.rs, crates/polars-stream/src/nodes/io_sinks/partition/mod.rs, crates/polars-stream/src/nodes/io_sinks/partition/parted.rs, crates/polars-stream/src/physical_plan/lower_ir.rs, crates/polars-stream/src/physical_plan/to_graph.rs, py-polars/docs/source/reference/io.rst, py-polars/polars/__init__.py, py-polars/polars/io/__init__.py, py-polars/polars/io/partition.py, py-polars/tests/unit/io/test_partition.py, py-polars/tests/unit/operations/test_rle.py
```python
pl.scan_parquet("/path/to/file.parquet").sink_csv(
PartitionParted(
"./out/{key[0].name}={key[0].value}.csv",
by="year",
),
)
```
Fixes #21787.
=> feat: Add `PartitionParted`

crates/polars-core/src/frame/mod.rs, crates/polars-io/src/csv/read/read_impl.rs, crates/polars-io/src/csv/read/read_impl/batched.rs, crates/polars-io/src/ipc/ipc_file.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-io/src/shared.rs, crates/polars-mem-engine/src/executors/scan/csv.rs, crates/polars-mem-engine/src/executors/scan/ndjson.rs, crates/polars-stream/src/nodes/io_sources/csv.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/apply.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/cast_columns.rs, crates/polars-stream/src/nodes/io_sources/multi_scan.rs, crates/polars-stream/src/nodes/io_sources/ndjson/negative_slice_pass.rs, crates/polars-stream/src/nodes/io_sources/ndjson/row_index_limit_pass.rs
And resolves some review points from https://github.com/pola-rs/polars/pull/21812
=> refactor(rust): Mark `with_row_index_mut` as unsafe

Cargo.lock, Cargo.toml, crates/polars-io/Cargo.toml, crates/polars-stream/Cargo.toml, crates/polars-stream/src/async_primitives/mod.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/apply.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/builder.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/mod.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/output.rs
Traits are `dyn` compatible 🙂
@coastalwhite
=> refactor(rust): Add new `FileReader` / `FileReaderBuilder` interfaces for multi file

crates/polars-core/src/chunked_array/logical/categorical/revmap.rs, crates/polars-core/src/chunked_array/logical/categorical/string_cache.rs, crates/polars-core/src/series/builder.rs, crates/polars-error/src/lib.rs, crates/polars-expr/src/hash_keys.rs, py-polars/tests/unit/conftest.py, py-polars/tests/unit/datatypes/test_categorical.py, py-polars/tests/unit/interop/test_from_pandas.py, py-polars/tests/unit/operations/test_cut.py, py-polars/tests/unit/operations/test_join.py, py-polars/tests/unit/operations/unique/test_unique.py, py-polars/tests/unit/test_predicates.py
=> fix: Join with categoricals on new-streaming engine

crates/polars-core/src/series/implementations/decimal.rs
Fixes https://github.com/pola-rs/polars/issues/21866.
=> fix: Null panic on decimal aggregate

crates/polars-stream/src/nodes/io_sources/multi_file_reader/bridge.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs
Bridge that connects morsels from readers to the compute node output.
@coastalwhite
=> refactor(rust): Add bridge for multi scan

py-polars/polars/_utils/construction/dataframe.py, py-polars/polars/dataframe/frame.py, py-polars/tests/unit/dataframe/test_df.py
<html>
<body>
Closes #20042
--
 Hello, I have resolved the issue and added test cases. Thank you for reviewing my code.
<br class="Apple-interchange-newline">
</body>
</html>
=> fix(python): Fix `DataFrame.nan_to_null` work for tuple

crates/polars-expr/src/groups/mod.rs, crates/polars-expr/src/groups/row_encoded.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-python/src/conversion/any_value.rs, crates/polars-stream/src/nodes/group_by.rs, crates/polars-stream/src/nodes/joins/equi_join.rs, crates/polars-stream/src/nodes/joins/mod.rs, crates/polars-stream/src/nodes/joins/semi_anti_join.rs, crates/polars-stream/src/physical_plan/fmt.rs, crates/polars-stream/src/physical_plan/lower_ir.rs, crates/polars-stream/src/physical_plan/mod.rs, crates/polars-stream/src/physical_plan/to_graph.rs, crates/polars-utils/src/idx_map/bytes_idx_map.rs
This doesn't yet lower `is_in` to this, I realized just now we also need a variant that returns a boolean filter rather than directly filtering the rows.
=> perf: Add native semi/anti join in new streaming engine

crates/polars-python/src/lazyframe/general.rs
maybe fixes deadlock in `test_io_plugin_predicate_no_serialization_21130`
=> fix: Release GIL in `collect_with_callback`

py-polars/polars/_utils/construction/dataframe.py
=> test(python): Fix pydantic model_fields deprecation

crates/polars-stream/src/nodes/multiplexer.rs
I'm honestly really puzzled how this wasn't deadlocking all over the place all the time, we should not keep the same consume token for the multiple separate pipelines the multiplexer feeds into.
=> fix: Deadlock in new-streaming multiplexer

crates/polars-ops/src/frame/join/mod.rs
=> perf: Fast path for empty inner join

crates/polars-core/src/frame/row/av_buffer.rs, py-polars/tests/unit/operations/test_transpose.py
=> fix: Ensure AV is static before pushing to row buffer

crates/polars-io/src/csv/read/read_impl.rs, crates/polars-io/src/csv/read/schema_inference.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-mem-engine/src/executors/scan/csv.rs, py-polars/tests/unit/io/test_csv.py
=> feat: Support growing schema if line lenght increases during csv schema inference

crates/polars-stream/src/nodes/reduce.rs, py-polars/tests/unit/operations/aggregation/test_aggregations.py
Fixes https://github.com/pola-rs/polars/issues/22005.
=> fix: Panic on empty aggregation in streaming

crates/polars-plan/src/plans/builder_ir.rs, crates/polars-plan/src/plans/conversion/mod.rs, crates/polars-plan/src/plans/conversion/stack_opt.rs
This PR makes it possible to add IR to the `IRBuilder` and have its expressions optimized.
=> feat(rust): Add `add_alp_optimize_exprs` to `IRBuilder`

crates/polars-plan/src/plans/conversion/functions.rs, crates/polars-python/src/functions/lazy.rs, py-polars/tests/unit/functions/test_repeat.py
=> fix: Add scalarity checks to `pl.repeat`

crates/polars-error/src/lib.rs, crates/polars-ops/src/series/ops/ewm_by.rs, py-polars/tests/unit/functions/test_ewm_by.py
=> fix: Panic for unequal length `ewm_mean_by` args

crates/polars-stream/src/physical_plan/to_graph.rs
Caused by `create_column_predicates` accidentally set to `false`
=> fix: Parquet filter performance regression from multiscan dispatch

crates/polars-core/src/chunked_array/logical/categorical/merge.rs, crates/polars-ops/src/chunked_array/list/sets.rs, crates/polars-ops/src/frame/join/merge_sorted.rs, crates/polars-ops/src/frame/join/mod.rs, crates/polars-ops/src/series/ops/is_in.rs, py-polars/tests/unit/operations/test_merge_sorted.py
=> fix: Join revmaps for categoricals in `merge_sorted`

crates/polars-ops/src/chunked_array/strings/namespace.rs, py-polars/polars/series/string.py, py-polars/tests/unit/operations/namespaces/string/test_string.py
=> fix: Error on unequal length `str.to_integer` arguments

crates/polars-core/src/datatypes/dtype.rs, crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs, py-polars/tests/unit/operations/test_rolling.py
=> fix: Throw error for unsupported rolling operations

crates/polars-core/src/chunked_array/list/iterator.rs, crates/polars-core/src/frame/column/mod.rs, crates/polars-core/src/series/mod.rs, crates/polars-ops/src/chunked_array/list/namespace.rs, crates/polars-plan/src/dsl/function_expr/dispatch.rs, py-polars/tests/unit/operations/namespaces/list/test_list.py
=> fix: Throw error for `n=0` on `list.gather_every`

crates/polars-stream/src/nodes/io_sources/ipc.rs
=> fix: Build error in new-streaming IPC source

crates/polars-stream/src/physical_plan/lower_expr.rs, py-polars/tests/unit/operations/test_replace_strict.py
Fixes https://github.com/pola-rs/polars/issues/22134.
=> fix: Schema error during lowering

crates/polars-lazy/src/tests/queries.rs, crates/polars-plan/src/dsl/function_expr/dispatch.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/plans/conversion/functions.rs, crates/polars-python/src/expr/general.rs, crates/polars-python/src/lazyframe/visitor/expr_nodes.rs, crates/polars/tests/it/lazy/group_by.rs, py-polars/polars/expr/expr.py, py-polars/tests/unit/operations/test_diff.py
=> feat: Allow scalar expr in `Expr.diff`

crates/polars-json/src/json/write/serialize.rs, py-polars/tests/unit/io/test_json.py
=> fix: Writing masked out list values to json

crates/polars-utils/src/cache.rs, py-polars/tests/unit/operations/namespaces/test_strptime.py
=> fix: Don't panic for `LruCachedFunc` for `size=0`

crates/polars-ops/src/frame/join/mod.rs, py-polars/tests/unit/operations/test_join.py
Fixes https://github.com/pola-rs/polars/issues/22206.
@ritchie46 A classic mistake :)
=> fix: Incorrect condition on empty inner join fast path

py-polars/tests/unit/io/test_scan.py
These were closed by #22153.
Fixes #21945.
Fixes #21706.
Fixes #21526.
Fixes #20578.
=> chore: Close async reader issues

crates/polars-stream/src/physical_plan/to_graph.rs
This is a problem I ran into while working on #22178.
=> fix: Check matching key datatypes for new streaming joins

py-polars/polars/sql/context.py, py-polars/tests/unit/sql/test_miscellaneous.py
Closes #20559.
Allows Polars to transparently execute SQL against _any_ object that implements the `PyCapsule` interface (which would include `DuckDBPyRelation` in more recent builds of DuckDB, as requested in the original Issue).
```python
import duckdb
rel = duckdb.query("FROM VALUES (1, 4, 9), (2, 5, 8), (3, 6, 7) tbl(a, b, c)")
type(rel)
rel
pl.sql("SELECT * FROM rel WHERE b >= 5").collect()
```
=> feat(python): Support running Polars SQL queries against any objects implementing the PyCapsule interface

docs/source/polars-cloud/release-notes.md
@ritchie46 Anything we should add regarding distributed?
=> chore: Add Polars Cloud 0.0.7 release notes

crates/polars-core/src/series/from.rs, crates/polars-io/src/predicates.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs, py-polars/tests/unit/io/test_parquet.py
=> fix: Parquet filters for logical types and operations

crates/polars-stream/src/physical_plan/lower_group_by.rs, py-polars/tests/unit/operations/test_group_by.py
Fixes https://github.com/pola-rs/polars/issues/22238.
=> fix: Duplicate key column name in streaming group_by due to CSE

crates/polars-plan/src/dsl/mod.rs, docs/source/user-guide/expressions/missing-data.md, docs/source/user-guide/installation.md, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py
=> docs: Improve interpolation documentation to clarify behavior of null values

crates/polars-core/src/series/any_value.rs
=> fix: Set revmap for empty `AnyValue` to `Series`

crates/polars-core/src/chunked_array/ops/sort/categorical.rs, crates/polars-core/src/chunked_array/ops/sort/mod.rs, py-polars/tests/unit/operations/test_sort.py
=> feat: Add `.sort(nulls_last=True)` to booleans, categoricals and enums

crates/polars-stream/src/nodes/joins/equi_join.rs, py-polars/tests/unit/streaming/test_streaming_join.py
=> fix: Coalesce correct column for new streaming full join

.github/workflows/benchmark.yml
Hopefully this fixes our benchmark CI.
=> chore: Update mozilla-actions/sccache-action

crates/polars-io/src/ndjson/buffer.rs, py-polars/tests/unit/io/test_json.py
=> fix: Fix nested datetypes in ndjson

crates/polars-io/src/ndjson/buffer.rs, py-polars/tests/unit/io/test_json.py, py-polars/tests/unit/io/test_lazy_json.py
=> fix: Fix ndjson nested types

crates/polars-ops/src/series/ops/rolling.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/function_expr/rolling.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-python/src/expr/rolling.rs, crates/polars-python/src/lazyframe/visitor/expr_nodes.rs, py-polars/docs/source/reference/expressions/computation.rst, py-polars/docs/source/reference/series/computation.rst, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/rolling/test_rolling.py
=> feat: Add `rolling_kurtosis`

crates/polars-mem-engine/src/executors/cache.rs, py-polars/tests/unit/test_cse.py
=> fix: Don't leak state during prefill CSE cache

py-polars/docs/source/reference/expressions/modify_select.rst, py-polars/docs/source/reference/series/modify_select.rst, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/series/test_series.py
Just adding an .rst entry for the expressions to show up in the docs.
Added them to the Series dispatch while there.
=> feat(python): Add Series `backward_fill` / `forward_fill`

crates/polars-stream/src/nodes/io_sources/parquet/row_group_decode.rs
Fixes #22428. This should fix the pesky CI error.
Edit: we are green!
=> fix: Last thread in parquet predicate filter oob

docs/source/src/python/user-guide/lazy/multiplexing.py, docs/source/user-guide/lazy/multiplexing.md, mkdocs.yml
=> docs: Add multiplexing page

crates/polars-parquet/src/arrow/read/deserialize/simple.rs, crates/polars-parquet/src/arrow/read/schema/metadata.rs, py-polars/tests/unit/io/test_parquet.py
=> fix: Reading of reencoded categorical in Parquet

py-polars/tests/unit/operations/test_over.py
=> chore: Add test for `implode` + `over`

crates/polars-ops/src/chunked_array/array/get.rs
=> fix: Add implementation for `array.get` with idx overflow

crates/polars-expr/src/reduce/count.rs, crates/polars-expr/src/reduce/first_last.rs, crates/polars-expr/src/reduce/len.rs, crates/polars-expr/src/reduce/min_max.rs, crates/polars-expr/src/reduce/mod.rs, crates/polars-stream/src/nodes/group_by.rs, crates/polars-stream/src/nodes/reduce.rs
=> refactor: Remove unused reduction code

crates/polars-parquet/src/arrow/read/deserialize/binview/mod.rs, py-polars/tests/unit/io/test_parquet.py
=> fix: Integer underflow when checking parquet UTF-8

crates/polars-plan/src/client/check.rs, crates/polars-plan/src/dsl/options/sink.rs, py-polars/tests/unit/cloud/test_prepare_cloud_plan.py
This PR updates the cloud eligibility check to match what we expect in cloud.
=> refactor(rust): Update the cloud eligibility check

Cargo.lock, Cargo.toml, crates/polars-io/Cargo.toml, crates/polars-io/src/cloud/polars_object_store.rs, crates/polars-io/src/ipc/ipc_reader_async.rs, crates/polars-io/src/parquet/read/async_impl.rs, crates/polars-io/src/utils/byte_source.rs
the main breaking change in object_store is usize to u64
=> build(rust): Update object_store to 0.12

crates/polars-expr/src/expressions/apply.rs, crates/polars-plan/src/dsl/functions/horizontal.rs, crates/polars-python/src/functions/lazy.rs, crates/polars/tests/it/lazy/folds.rs, docs/source/src/rust/user-guide/expressions/folds.rs, py-polars/polars/functions/lazy.py, py-polars/tests/unit/operations/test_window.py
=> fix: Fold flags and verify scalar correctness in apply

crates/polars-core/src/datatypes/field.rs, py-polars/tests/unit/io/test_parquet.py
* Fixes https://github.com/pola-rs/polars/issues/22506
This is a patch PR that copies the logic from https://github.com/pola-rs/polars/blob/7771b3f13b62ad0d875d9e27d0a0e1ea7522c7db/crates/polars-core/src/series/from.rs#L261-L269 to the schema conversion code.
I also have a more involved fix at https://github.com/pola-rs/polars/pull/22523, but it's probably safer to merge that after the next patch release.
=> fix: Fix error reading parquet with datetimes written by pandas

crates/polars-stream/src/nodes/joins/equi_join.rs, py-polars/tests/unit/operations/test_join.py
=> fix: Streaming outer join coalesce bug

crates/polars-core/src/frame/group_by/into_groups.rs, py-polars/tests/unit/operations/test_group_by.py
=> feat: Support grouping by `pl.Array`

py-polars/tests/unit/operations/namespaces/temporal/test_truncate.py
fixes #22590 
Follow-up to fix the modified test case introduced in #22592 and unblock CI for other contributions.
=> ci: Fix test_truncate_path test case

.github/workflows/release-python.yml, .github/workflows/test-pyodide.yml, crates/Makefile, crates/polars-core/Cargo.toml, crates/polars-lazy/Cargo.toml, crates/polars-ops/Cargo.toml, crates/polars-stream/Cargo.toml, crates/polars-stream/src/physical_plan/fmt.rs, crates/polars-time/Cargo.toml, crates/polars/Cargo.toml
=> fix: Add `new_streaming` feature to `polars` crate

crates/polars-mem-engine/src/executors/group_by_rolling.rs, py-polars/tests/unit/operations/test_group_by_dynamic.py
fixes #22585 
fixes #22595
Kindly review.
=> fix: Panic in group_by_dynamic on single-row df with group_by

flake.lock, flake.nix
This is, by no means, the perfect flake at the moment. It will allow nix users to both develop and build polars reliably though.
=> chore: Add a nix flake with a devShell and package

Cargo.lock, crates/polars-ops/Cargo.toml
=> fix: Bump argminmax to 0.6.3

crates/polars-utils/src/regex_cache.rs
Fixes https://github.com/pola-rs/polars/issues/22636.
=> feat: Allow setting of regex size limit using `POLARS_REGEX_SIZE_LIMIT`

crates/polars-parquet/src/parquet/parquet_bridge.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
Fixes https://github.com/pola-rs/polars/issues/22678.
=> fix: Gzip has maximum compression of 9, not 10

py-polars/polars/io/iceberg/functions.py
=> docs(python): Fix non-rendering bullet points in `scan_iceberg`

py-polars/polars/schema.py
=> fix(python): Fix the default value type in `Schema` init

crates/polars-core/src/utils/series.rs, py-polars/tests/unit/operations/test_cast.py
=> fix: Fallback to non-strict casting for deprecated casts

crates/polars-ops/src/series/ops/search_sorted.rs
Needed it for my successful distributed sort. :sunglasses:
=> feat: Support binaryoffset in search sorted

crates/polars-plan/src/plans/aexpr/properties.rs, crates/polars-plan/src/plans/optimizer/predicate_pushdown/utils.rs, py-polars/tests/unit/test_predicates.py
=> perf: Allow predicate passing set_sorted

crates/polars-core/src/frame/mod.rs, crates/polars-core/src/utils/mod.rs, py-polars/tests/unit/operations/test_cross_join.py
=> fix: Don't panic for cross join with misaligned chunking

flake.nix
Add support for macos by optionally building non-compatible packages only on linux and fixing connectorx builds.
For connectorx the problem was that `libgssapi-sys` couldn't read the gss headers for macos (I assume newer macos may have introduced this problem) and couldn't find `krb5` either. To solve this, I patched a newer commit that added `pkg-config` support for the build script into `0.2.4` (the old version we are using via tiberius). Ideally, both `ray` and `connectorx` could be upstreamed.
=> chore: Fix flake.nix to work on macos

crates/polars-core/src/chunked_array/ops/reverse.rs, py-polars/tests/unit/lazyframe/test_lazyframe.py, py-polars/tests/unit/operations/test_reverse.py, py-polars/tests/unit/series/test_series.py
=> fix: Fix reverse list type

crates/polars-plan/src/plans/aexpr/properties.rs, py-polars/tests/unit/test_predicates.py
=> fix(python): Fix map_elements predicate pushdown

crates/polars-lazy/src/frame/mod.rs, crates/polars-plan/src/dsl/mod.rs
This fixes:
- building `polars-lazy` with the `new_streaming` feature
- building `polars-lazy` with the `list_sets` feature
cc #22610
=> build: Fix building `polars-lazy` with certain features

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/io/test_write.py
* Fixes https://github.com/pola-rs/polars/issues/22873
=> fix: Fix error using `write_csv` with `storage_options`

crates/polars-compute/src/arithmetic/float.rs, crates/polars-compute/src/arithmetic/mod.rs, crates/polars-compute/src/arithmetic/signed.rs, crates/polars-compute/src/arithmetic/unsigned.rs, crates/polars-compute/src/cast/primitive_to.rs, crates/polars-core/src/chunked_array/arithmetic/numeric.rs, crates/polars-core/src/chunked_array/logical/date.rs, crates/polars-core/src/chunked_array/logical/datetime.rs, crates/polars-core/src/chunked_array/logical/duration.rs, py-polars/tests/unit/operations/test_cast.py
=> fix: Don't silently overflow for temporal casts

crates/polars-core/src/series/implementations/array.rs
Broken out of #22633.
Start setting the is_sorted flags on sorted `pl.Array` Series, which will probably result in performance improvements in some cases. This matches the behavior of other dtypes which were already doing this.
=> fix(rust): Set the sorted flag on Array after it is sorted

py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_top_k.py
I don't know how I managed to mess this up. But this is #22872 again.
=> fix(python): Add {top, bottom}_k_by to Series

crates/polars-expr/src/expressions/aggregation.rs, crates/polars-plan/src/dsl/expr/expr_dyn_fn.rs, crates/polars-plan/src/plans/conversion/type_coercion/mod.rs, crates/polars-plan/src/plans/lit.rs, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/operations/aggregation/test_implode.py, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/operations/test_over.py
=> fix: Add inline implodes in type coercion

Cargo.lock, Cargo.toml, crates/polars-arrow/src/io/ipc/read/file.rs, py-polars/tests/unit/interop/test_interop.py
Fix #22323
Based on pola-rs/arrow-format#2
=> fix: Update arrow format

crates/polars-io/src/cloud/credential_provider.rs
This is very spammy, I am also freeing up some space on stderr that I plan to use later 😄.
```
[FetchedCredentialsCache]: Call update_func: current_time = 1748373252, last_fetched_expiry = 0
[FetchedCredentialsCache]: Finish update_func: new expiry = (never expires)
[FetchedCredentialsCache]: Using cached credentials: current_time = 1748373252, expiry = (never expires)
[FetchedCredentialsCache]: Using cached credentials: current_time = 1748373253, expiry = (never expires)
[FetchedCredentialsCache]: Using cached credentials: current_time = 1748373253, expiry = (never expires)
...
[FetchedCredentialsCache]: Using cached credentials: current_time = 1748373253, expiry = (never expires)
[FetchedCredentialsCache]: Using cached credentials: current_time = 1748373253, expiry = (never expires) …
```
=> feat: Remove duplicate verbose logging from `FetchedCredentialsCache`

crates/polars-compute/src/propagate_nulls.rs, crates/polars-core/src/chunked_array/struct_/mod.rs, crates/polars-error/src/lib.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, py-polars/tests/unit/functions/as_datatype/test_struct.py, py-polars/tests/unit/functions/test_when_then.py
Fixes https://github.com/pola-rs/polars/issues/22959.
=> fix: Integer underflow in `propagate_nulls`

crates/polars-core/src/frame/mod.rs, crates/polars-stream/src/physical_plan/to_graph.rs, py-polars/tests/unit/io/test_io_plugin.py
=> fix: Allow for IO plugins with reordered columns in streaming

crates/polars-plan/src/dsl/expr/expr_dyn_fn.rs, crates/polars-plan/src/dsl/expr/mod.rs, crates/polars-plan/src/dsl/name.rs
=> refactor: Implement `Hash` and use `SpecialEq` for `RenameAliasFn`

crates/polars-arrow/src/compute/concatenate.rs
=> fix: View buffer exceeding 2^32 - 1 bytes in concatenate_view

crates/polars-expr/src/expressions/window.rs, py-polars/Makefile, py-polars/tests/unit/operations/test_window.py, py-polars/tests/unit/test_errors.py
This should just be part of the Makefile as more people start developing on the streaming engine, I've just been using a local setup with a similar command.
=> chore: Add make test-streaming

crates/polars-parquet/src/arrow/read/deserialize/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/simple.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
=> chore: Add environment variable to get Parquet decoding metrics

crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs, py-polars/tests/unit/io/test_io_plugin.py
fixes #22110
Kindly review.
Ping @nameexhaustion , @coastalwhite .
=> fix: Respect column order in `register_io_source` schema

crates/polars-python/src/lazyframe/visitor/nodes.rs, py-polars/tests/unit/lazyframe/cuda/test_node_visitor.py
* Fixes https://github.com/pola-rs/polars/issues/22766
=> fix: Preserve `file://` in LazyFrame node traverser

crates/polars-core/src/frame/column/mod.rs, py-polars/tests/unit/functions/test_functions.py
Fixes https://github.com/pola-rs/polars/issues/23156.
=> fix: Null return from var/std on scalar column

crates/polars-plan/src/plans/optimizer/simplify_expr/arity.rs, crates/polars-plan/src/plans/optimizer/simplify_expr/binary.rs, crates/polars-plan/src/plans/optimizer/simplify_expr/mod.rs, py-polars/tests/unit/functions/test_when_then.py
=> feat: Improve arity simplification

crates/polars-plan/src/plans/optimizer/mod.rs, py-polars/tests/unit/test_cse.py
=> perf: Trigger cache/cse optimizations when multiplexing

crates/polars-io/src/predicates.rs, crates/polars-stream/src/nodes/io_sources/parquet/row_group_decode.rs, py-polars/tests/unit/io/test_lazy_parquet.py
* Fixes https://github.com/pola-rs/polars/issues/23268
=> fix: Fix filters on inserted columns did not remove rows

crates/polars-plan/src/plans/conversion/dsl_to_ir/join.rs, crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs, py-polars/tests/unit/operations/test_join.py
* Fixes https://github.com/pola-rs/polars/issues/23307
=> fix: Fix panic filtering after left join

crates/polars-utils/src/plpath.rs
This also adds some tests to make sure that the behavior is somewhat consistent now.
=> fix: Properly join URI paths in `PlPath`

crates/polars-arrow/src/bitmap/mutable.rs, py-polars/tests/unit/datatypes/test_bool.py
=> fix: Fix boolean `min()` in `group_by` aggregation (streaming)

py-polars/polars/io/delta.py, py-polars/tests/unit/constructors/test_constructors.py, py-polars/tests/unit/io/test_delta.py
* Fixes https://github.com/pola-rs/polars/issues/21572
This will be quite a nice QoL improvement.
=> feat: Support `pathlib.Path` as source for `read/scan_delta()`

crates/polars-compute/src/rolling/nulls/mean.rs, crates/polars-compute/src/rolling/nulls/sum.rs, py-polars/tests/unit/operations/test_group_by_dynamic.py
Fixes https://github.com/pola-rs/polars/issues/22724.
Fixes https://github.com/pola-rs/polars/issues/23433.
=> fix: Null handling in full-null group_by_dynamic mean/sum

Cargo.lock, Cargo.toml, crates/polars-compute/src/rolling/no_nulls/quantile.rs, crates/polars-compute/src/rolling/nulls/quantile.rs, crates/polars-compute/src/rolling/window.rs, crates/polars-core/src/serde/mod.rs, crates/polars-parquet/Cargo.toml, crates/polars-utils/src/pl_serialize.rs
Can now get the sorted items in a single pass instead of passes.
Combined with other updates.
=> perf: Rolling quantile lower time complexity

crates/polars-core/src/series/builder.rs, crates/polars-stream/src/nodes/io_sinks/metrics.rs, py-polars/tests/unit/io/test_partition.py
=> fix: Don't panic for `finish_callback` with nested datatypes

crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
=> feat(rust): Expose `IRFunctionExpr::FillNullWithStrategy` in the python visitor

crates/polars-plan/src/plans/prune.rs
Follow-up on https://github.com/pola-rs/polars/pull/23499
=> refactor: Pruning follow-up

py-polars/tests/unit/operations/test_join.py
* Regression from https://github.com/pola-rs/polars/pull/23487
=> test(python): Fix join test

crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
=> feat(rust): Expose `IRFunctionExpr::Rank` in the python visitor

py-polars/polars/convert/general.py
=> docs: Correct note in `from_pandas` about data being cloned

crates/polars-mem-engine/src/planner/lp.rs
- Background: https://github.com/pola-rs/polars/pull/22672
=> fix: Prevent in-mem partition sink deadlock

py-polars/tests/unit/io/test_partition.py
follow-up to https://github.com/pola-rs/polars/pull/23462
=> test: Mark select test case as `write_disk`

crates/polars-core/src/chunked_array/comparison/categorical.rs, py-polars/tests/unit/operations/test_comparison.py
Comparison kernels are tricky...
=> fix: Bug in Categorical <-> str compare with nulls

crates/polars-plan/src/plans/builder_ir.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/join.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/mod.rs, crates/polars-plan/src/plans/conversion/stack_opt.rs, crates/polars-plan/src/plans/conversion/type_check/mod.rs, crates/polars-plan/src/plans/optimizer/stack_opt.rs, crates/polars-plan/src/plans/schema.rs, py-polars/tests/unit/operations/test_join.py
* Fixes https://github.com/pola-rs/polars/issues/23236
=> fix: Fix ColumnNotFound error when joining on `col().cast()`

crates/polars-arrow/src/array/fixed_size_list/mod.rs, crates/polars-arrow/src/array/list/mod.rs, crates/polars-arrow/src/array/mod.rs, crates/polars-arrow/src/datatypes/mod.rs, crates/polars-arrow/src/ffi/schema.rs, crates/polars-core/src/chunked_array/array/mod.rs, crates/polars-core/src/chunked_array/list/mod.rs, crates/polars-core/src/chunked_array/ops/full.rs, crates/polars-core/src/datatypes/any_value.rs, crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/series/arithmetic/fixed_size_list.rs, crates/polars-core/src/series/mod.rs, crates/polars-io/src/json/mod.rs, crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/column_selector.rs
* ref https://github.com/pola-rs/polars/pull/23532#discussion_r2204826653
=> refactor(rust): Replace `PlSmallStr::from_static("item")` with `LIST_VALUES_NAME`

crates/polars-plan/src/dsl/datatype_expr.rs, crates/polars-plan/src/dsl/expr/mod.rs, crates/polars-plan/src/dsl/meta.rs, crates/polars-plan/src/plans/builder_ir.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/concat.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/expr_expansion.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/expr_to_ir.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/functions.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/join.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/mod.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/utils.rs, crates/polars-plan/src/plans/prune.rs, crates/polars-python/src/expr/general.rs, crates/polars-python/src/lazyframe/visit.rs, py-polars/tests/unit/operations/namespaces/list/test_eval.py
=> fix: Selectors in `{Lazy,Data}Frame.filter`

crates/polars-python/src/file.rs, py-polars/tests/unit/io/test_lazy_csv.py
fixes #23629 
ping @coastalwhite
=> fix: Fix handling of UTF-8 in `write_csv` to `IO[str]`

crates/polars-plan/src/plans/aexpr/function_expr/strings.rs, py-polars/tests/unit/operations/namespaces/string/test_string.py
Partial fix for #23663.
More to come.
Ping @coastalwhite .
=> fix: Fix output field dtype for `ToInteger`

crates/polars-plan/src/plans/conversion/dsl_to_ir/expr_to_ir.rs, py-polars/tests/unit/operations/namespaces/test_name.py
=> fix: Revert to old behavior with `name.keep`

crates/polars-plan/src/plans/aexpr/function_expr/strings.rs
Note that this does not fix all cases, namely when the format is not given. The planner and engine might still disagree.
xref: #23663.
=> fix: Correct the planner output datatype for `strptime`

crates/polars-stream/src/nodes/dynamic_slice.rs, crates/polars-stream/src/nodes/mod.rs, crates/polars-stream/src/nodes/streaming_slice.rs, crates/polars-stream/src/physical_plan/fmt.rs, crates/polars-stream/src/physical_plan/lower_expr.rs, crates/polars-stream/src/physical_plan/mod.rs, crates/polars-stream/src/physical_plan/to_graph.rs
Fixes https://github.com/pola-rs/polars/issues/23041.
=> perf: Lower Expr.slice to streaming engine

crates/polars-mem-engine/src/planner/lp.rs
These are free assertions / sanity checks to make.
=> refactor(rust): Add assertions for unique ID

crates/polars-ops/src/frame/join/asof/groups.rs, py-polars/tests/unit/operations/test_join_asof.py
=> fix: Support i128 in asof join

Cargo.lock, Cargo.toml, crates/polars-plan/src/dsl/plan.rs, crates/polars-utils/Cargo.toml, crates/polars-utils/src/pl_serialize.rs, py-polars/tests/unit/test_serde.py
Fixes stack overflow when de/serializing deeply nested plans.
Fixes https://github.com/polars-inc/polars-cloud/issues/2625
=> fix: Stack overflow in `DslPlan` serde

crates/polars-core/src/prelude.rs, crates/polars-core/src/series/implementations/null.rs, crates/polars-ops/src/chunked_array/repeat_by.rs, py-polars/tests/unit/functions/test_repeat.py
=> feat: Implement `repeat_by` for `Array` and `Null`

crates/polars-core/src/chunked_array/logical/categorical.rs, py-polars/tests/unit/operations/namespaces/test_categorical.py
Fixes https://github.com/pola-rs/polars/issues/23823.
=> fix: Filter sorted flag from physical in CategoricalChunked

crates/polars-stream/src/execute.rs
Needed for https://github.com/pola-rs/polars/pull/23672#issuecomment-3109611738.
=> refactor(rust): Add subphase and query task spawning to StreamingExecState

crates/polars-plan/src/plans/schema.rs, py-polars/tests/unit/operations/test_join_asof.py
=> fix: Correctly raise DuplicateError on asof_join with suffix=""

crates/polars-stream/src/execute.rs
=> fix: Spawning tokio task outside reactor

pyo3-polars/pyo3-polars/src/alloc.rs
Fixes https://github.com/pola-rs/polars/issues/23893.
=> fix: Incorrect datatype passed to libc::write

crates/polars-io/src/predicates.rs, crates/polars-stream/src/nodes/io_sources/multi_scan/pipeline/tasks/reader_starter.rs
* Implements a proper fix and removes the old one from https://github.com/pola-rs/polars/pull/23303 
What we want to do is to set `is_sumwise_complete` to `false` if one of the live filter columns originating from the file was missing.
The code on the current main achieves this effect by checking if any inserted column is NULL - this works based on the fact that inserted missing columns are currently always NULL, but this will no longer be the case going into the future as Iceberg allows for specifying default values for missing columns.
Test already exists (`test_parquet_prefiltering_inserted_column_23268`)
=> fix: Properly set sumwise complete on filter for missing columns

crates/polars-core/src/chunked_array/logical/categorical.rs
This reverts commit d9ca548dd2eceb4bd5033409fd69716d7be22cdd.
This commit led to errors when writing IPC.
=> fix: Revert "fix: Don't encode entire CategoricalMapping when going to Arrow (#24036)"

crates/polars-row/src/decode.rs, py-polars/tests/unit/sql/test_group_by.py
Fixes https://github.com/pola-rs/polars/issues/24049.
=> fix: Categorical in nested data in row encoding

py-polars/tests/conftest.py, py-polars/tests/unit/io/test_parquet.py
After the little problem with the IPC writer. Let's try again.
=> chore: Make tests with sinks run on cloud again

crates/polars-plan/src/utils.rs, py-polars/tests/unit/operations/namespaces/test_meta.py
Fixes https://github.com/pola-rs/polars/issues/24003.
=> fix: Expr.meta.output_name for struct fields

py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/group_by.py, py-polars/tests/unit/dataframe/test_partition_by.py, py-polars/tests/unit/io/test_hive.py, py-polars/tests/unit/operations/test_group_by.py
=> fix(python): Make `group_by`/`partition_by` iterator keys `tuple[Any, ...]` to enable tuple-unpacking

crates/polars-core/src/datatypes/dtype.rs, py-polars/tests/unit/functions/range/test_linear_space.py, py-polars/tests/unit/operations/test_cast.py
=> feat: Improve Debug formatting of DataType

crates/polars-plan/src/plans/aexpr/function_expr/plugin.rs
`_polars_plugin_get_last_error_message` returns a pointer to a thread-local buffer containing the error message. This buffer may die/get replaced implicitly very easily, so to be safe let's immediately clone it into a proper `String`. This adds an extra allocation when getting an error message but that's a price I'm willing to pay.
=> refactor(rust): Fool-proof retrieve_error_msg

crates/polars-stream/src/physical_plan/lower_ir.rs, py-polars/tests/unit/operations/test_top_k.py
Fixes https://github.com/pola-rs/polars/issues/24163.
=> fix: Allow non-elementwise by in top_k

py-polars/polars/series/series.py, pyo3-polars/README.md, pyo3-polars/pyo3-polars/src/lib.rs, pyo3-polars/pyo3-polars/src/types.rs
Fixes https://github.com/pola-rs/polars/issues/24109.
=> fix: PyO3 extension types giving compat_level errors

docs/source/user-guide/gpu-support.md
Updating the list of supported and unsupported GPU features as of the upcoming 25.10 cudf_polars release
=> docs(python): Update GPU un/supported features

py-polars/polars/io/cloud/_utils.py, py-polars/tests/unit/io/cloud/test_credential_provider.py
* Fixes https://github.com/pola-rs/polars/issues/24143
=> fix(python): Fix credential provider did not auto-init on partition sinks

crates/polars-io/src/file_cache/cache.rs, crates/polars-io/src/file_cache/utils.rs, crates/polars-io/src/ipc/ipc_reader_async.rs, crates/polars-plan/src/dsl/scan_sources.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir/scans.rs, crates/polars-plan/src/plans/functions/count.rs, crates/polars-stream/src/nodes/io_sources/csv.rs, crates/polars-stream/src/nodes/io_sources/ipc.rs, crates/polars-stream/src/nodes/io_sources/multi_scan/config.rs, crates/polars-stream/src/nodes/io_sources/multi_scan/pipeline/initialization.rs, crates/polars-stream/src/nodes/io_sources/multi_scan/reader_interface/capabilities.rs, crates/polars-stream/src/nodes/io_sources/ndjson/builder.rs, crates/polars-utils/src/lib.rs
Note that the panic only reproduces when running on the cloud engine and scanning from a cloud URL.
=> fix: Fix panic in polars cloud CSV scan

crates/polars-dylib/Cargo.toml, crates/polars-python/Cargo.toml
=> refactor(rust): Propagate some python feature flags

crates/polars-core/src/datatypes/_serde.rs, crates/polars-core/src/datatypes/mod.rs
This was preventing remote benchmark CI.
=> chore: Remove unused `Wrap`

crates/polars-python/src/dataframe/general.rs
Fixes https://github.com/pola-rs/polars/issues/24216.
This does remove a scary comment about a segfault from releasing the GIL in https://github.com/pola-rs/polars/pull/1872. However that is now 4 years ago and I can't reproduce the segfault even if I do release the GIL so I'm assuming we fixed the real problem somewhere along the way.
=> fix: Release the GIL in map_groups

crates/polars-plan/src/plans/optimizer/set_order.rs, py-polars/tests/unit/operations/unique/test_unique.py
Fixes https://github.com/pola-rs/polars/issues/24260.
=> fix: Unique with keep="none" in new optimization pass

crates/polars-plan/src/plans/python/pyarrow.rs, py-polars/polars/io/pyarrow_dataset/anonymous_scan.py, py-polars/polars/io/pyarrow_dataset/functions.py
=> fix: Sanitize and warn about eval usage

.github/workflows/release-python.yml, rust-toolchain.toml
See: https://github.com/pola-rs/polars/pull/24257#issuecomment-3236335025
=> build: Re-enable macos-x86-64

docs/source/user-guide/expressions/categorical-data-and-enums.md
Resolves https://github.com/pola-rs/polars/issues/24159.
=> docs(python): Update categorical comparison documentation in user guide

crates/polars-plan/src/plans/optimizer/mod.rs, py-polars/tests/unit/test_queries.py
Reverts pola-rs/polars#24269
This lead to infinite recursion. We can redo more carefully later.
=> Revert "perf: Do ordering simplification step after common sub-plan elimination"

crates/polars-plan/src/plans/aexpr/builder.rs, crates/polars-stream/src/physical_plan/lower_expr.rs
=> perf: Lower `arg_unique` natively to the streaming engine

py-polars/polars/io/database/functions.py
Closes #23623, by improving the docs.
See https://github.com/pola-rs/polars/issues/23623#issuecomment-3195368984 for more detail/explanation.
=> docs(python): Add detail about server-side cursor behaviour for SQLAlchemy in the "iter_batches" parameter of `read_database`

crates/polars-stream/src/nodes/negative_slice.rs, py-polars/tests/unit/operations/test_slice.py
Fixes https://github.com/pola-rs/polars/issues/24325.
=> fix: Incorrect logic in negative streaming slice

py-polars/tests/unit/io/cloud/test_credential_provider.py, py-polars/tests/unit/test_serde.py
These are quite slow and should probably not be run every time locally. The CI should be enough.
=> chore: Mark some tests as slow

crates/polars-io/src/parquet/read/mmap.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/predicate.rs, crates/polars-parquet/src/arrow/read/deserialize/boolean.rs, crates/polars-parquet/src/arrow/read/deserialize/categorical.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/predicate.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary.rs, crates/polars-parquet/src/arrow/read/deserialize/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-parquet/src/arrow/read/deserialize/null.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/float.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/plain/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/plain/predicate.rs, crates/polars-parquet/src/arrow/read/deserialize/simple.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs, crates/polars-parquet/src/arrow/read/expr.rs, crates/polars-parquet/src/parquet/page/mod.rs, crates/polars-parquet/src/parquet/types.rs, crates/polars-stream/src/nodes/io_sources/parquet/row_group_decode.rs, crates/polars/tests/it/io/parquet/read/file.rs, crates/polars/tests/it/io/parquet/read/row_group.rs
Reverts pola-rs/polars#24324
Regresses q16 and q3
=> Revert "perf: Allocate only for read items when reading Parquet with predicate"

crates/polars-expr/src/expressions/cast.rs
* Slight optimization for https://github.com/pola-rs/polars/pull/24373
=> perf: Don't aggregate groups for strict cast if original len

README.md
Declutter and remove outdated lines. Most is handled in user-guide. Also add a section about managed/distributed.
=> docs: Update readme.

crates/polars-plan/src/plans/ir/format.rs
=> fix: Show IR sort options in `explain`

crates/polars-io/src/path_utils/mod.rs, py-polars/polars/io/cloud/_utils.py, py-polars/tests/unit/io/cloud/test_cloud.py
* Fixes https://github.com/pola-rs/polars/issues/24522
=> fix: Fix regression error when scanning AWS presigned URL

crates/polars-core/src/utils/supertype.rs, py-polars/tests/unit/datatypes/test_decimal.py
Fixes https://github.com/pola-rs/polars/issues/24586.
=> fix: Decimal <-> literal arithmetic supertype rules

.github/workflows/release-python.yml, Cargo.lock, crates/polars-python/src/c_api/mod.rs, py-polars/Cargo.toml, py-polars/polars/_plr.py, py-polars/polars/pyproject.toml
The `polars` directory should be included in the wheel RECORD, otherwise pip will not uninstall it properly
=> build: Include source in main package

crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
Fixes https://github.com/pola-rs/polars/issues/24653.
=> fix: Overflow in slice-slice optimization

crates/polars-arrow/src/io/ipc/read/read_basic.rs
Fixes https://github.com/pola-rs/polars/issues/24667.
=> fix: Support reading of mixed compressed/uncompressed IPC buffers

crates/polars-python/src/conversion/categorical.rs, py-polars/polars/datatypes/classes.py, py-polars/tests/unit/test_categories.py
* Fixes https://github.com/pola-rs/polars/issues/24690
=> fix: Make `Categories` pickleable

Makefile
=> chore: Fix Makefile `uv pip` option syntax

crates/polars-stream/src/nodes/gather_every.rs, crates/polars-stream/src/nodes/mod.rs, crates/polars-stream/src/physical_plan/fmt.rs, crates/polars-stream/src/physical_plan/lower_expr.rs, crates/polars-stream/src/physical_plan/mod.rs, crates/polars-stream/src/physical_plan/to_graph.rs
=> perf: Native streaming `gather_every`

crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs, py-polars/tests/unit/lazyframe/test_optimizations.py
* Fixes https://github.com/pola-rs/polars/issues/24734
=> perf: Pushdown slices on plans within unions

README.md, crates/polars-core/src/utils/mod.rs, crates/polars-error/src/constants.rs, crates/polars-error/src/lib.rs, crates/polars-io/src/parquet/read/mod.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-stream/src/nodes/io_sources/ipc.rs, docs/source/user-guide/installation.md, py-polars/src/polars/_cpu_check.py, py-polars/src/polars/dataframe/frame.py, py-polars/src/polars/lazyframe/frame.py
as mentioned in https://discord.com/channels/908022250106667068/911186243465904178/1423566833746972733
=> docs: Mention polars[rt64] and polars[rtcompat] instead of u64-idx and lts-cpu

py-polars/src/polars/expr/whenthen.py, py-polars/src/polars/functions/whenthen.py
=> docs(python): Document output name determination in when/then/otherwise

crates/polars-arrow/src/legacy/kernels/take_agg/mod.rs, crates/polars-core/src/frame/group_by/aggregations/mod.rs, crates/polars-ops/src/chunked_array/nan_propagating_aggregate.rs, crates/polars-utils/src/kahan_sum.rs
Fixes https://github.com/pola-rs/polars/issues/24755.
=> fix: Use Kahan summation for in-memory groupby sum/mean

crates/polars-plan/src/plans/optimizer/cse/cse_lp.rs, crates/polars-plan/src/plans/optimizer/cse/mod.rs, crates/polars-plan/src/plans/optimizer/mod.rs, py-polars/tests/unit/test_cse.py
=> feat: Recursively apply CSPE
