crates/polars-core/src/chunked_array/logical/categorical/merge.rs, crates/polars-ops/src/frame/join/mod.rs, py-polars/tests/unit/datatypes/test_categorical.py, py-polars/tests/unit/test_string_cache.py
fix #7632 
With this PR it becomes possible to join on two different local categoricals. Polars will make the mapping from the rhs compatible with the lhs and throw a performance warning.
=> feat: Join operations on local categoricals

crates/polars-arrow/src/legacy/data_types.rs, crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/sum.rs, crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/variance.rs, crates/polars-arrow/src/legacy/kernels/rolling/nulls/sum.rs, crates/polars-arrow/src/legacy/kernels/rolling/nulls/variance.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
fix #12682 12682
infinity skips the `is_nan` check and is carried over to non-related windows.
=> fix: fix carrying over infinity into other windows

py-polars/polars/utils/_construction.py, py-polars/tests/unit/test_constructors.py
Closes #12696.
Tweaked/fixed square numpy array tiebreak resolution; could bleed out into non-square arrays. Fixed the bug and added the missing test coverage. (Strongly tempted to try simplifying the whole function later, as it is feeling a bit tangled 🤔)
=> fix(python): address a numpy ndarray init regression

py-polars/polars/utils/show_versions.py
More meaningful/useful to show the `adbc` driver manager version.
=> feat(python): favour showing "adbc_driver_manager" over "adbc_driver_sqlite" in `show_versions`

crates/polars-core/src/frame/mod.rs, crates/polars-core/src/series/mod.rs, py-polars/tests/unit/dataframe/test_vstack.py, py-polars/tests/unit/series/test_append.py, py-polars/tests/unit/series/test_extend.py
This PR is a partial fix for issue https://github.com/pola-rs/polars/issues/11824. It solves the case when one cannot `df1.vstack(df2)` because eg. `df1["x"].dtype == pl.Int64` but `df2["x"].dtype == pl.Null`.
https://github.com/pola-rs/polars/issues/11824 also mentions a more complex example, when we get conflict between eg. `List[Int64]` and `List[Null]`. This is related to behaviour introduced by PR https://github.com/pola-rs/polars/pull/12677 which produces these `List[Null]` columns when parsing empty JSON arrays.
=> fix: support `append`/`extend` with null series (#11824)

py-polars/polars/io/parquet/functions.py
Reading from hive partitioned data now supported natively:
```
hive_partitioning (bool: True)
Infer statistics and schema from hive partitioned URL and use them
to prune reads.
```
=> docs(python): now that `scan_parquet` supports hive partitioning, remove note pointing to `scan_pyarrow_dataset`

docs/src/python/user-guide/io/database.py
Closes #12697. While `libpq` typically allows both forms [^1], "postgresql" is the official URI prefix used by PostgreSQL itself, and should be preferred for maximum compatibility.
[^1]: https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS
=> docs(python): update URI prefix in examples (prefer "postgresql" to "postgres")

py-polars/requirements-dev.txt
Latest release now supports Python 3.12, so we can drop this (it will still be installed as a transitive dependency).
=> chore(python): Remove pinned `aiohttp` dependency

py-polars/polars/dataframe/frame.py, py-polars/polars/io/database.py, py-polars/polars/type_aliases.py, py-polars/pyproject.toml, py-polars/requirements-dev.txt, py-polars/tests/unit/io/test_database_write.py
Closes #12684.
Ref: https://github.com/pola-rs/polars/pull/10763, https://github.com/pola-rs/polars/pull/11282#issuecomment-1736224273.
Updates `pl.write_database` and associated tests with various improvements now that some key issues (https://github.com/apache/arrow-adbc/issues/1000, https://github.com/apache/arrow-adbc/issues/1109) have been resolved in the ADBC `0.7` and `0.8` releases, respectively.
* Enables correct resolution of schema-qualified names (eg: `schema.table_name`).
* Adds ADBC engine support for `if_exists = "fail"` (simulated).
* Adds ADBC engine support for `if_exists = "replace"` (native).
* All write tests now able to run under Python `3.12`.
Requires that the caller has installed at least ADBC version `0.7` for "replace" support, or `0.8` if using schema-qualified …
=> feat(python): Improve `write_database`, accounting for latest `adbc` fixes/updates

crates/polars-core/src/config.rs, crates/polars-ops/src/chunked_array/list/sets.rs
=> fix: fix oob in set operations

py-polars/polars/utils/_construction.py, py-polars/tests/unit/test_constructors.py
This PR is related to the Issue #12718. 
I modified 
Since version 0.19.16, this code (`DataFrame(np.zeros((2, 1)))`) has a new behavior.
```python
>>> arr = np.zeros((2, 1))
>>> DataFrame(arr)
... ┌───────────┐
... │ column_0  │
... │ ---       │
... │ list[i32] │
... ╞═══════════╡
... │ [0]       │
... │ [0]       │
... └───────────┘
```
Function `numpy_to_pydf` of file `_construction.py` has been changed, that a numpy array with 2 dimensions, one column and a consistent schema, to have the previous behaviour (`if two_d and n_columns == 1 and shape[1] > 1 else ...`)
```python
>>> arr = np.zeros((2, 1))
>>> DataFrame(arr)
... ┌──────────┐
... │ column_0 │
... │ ---      │
... │ i32      │
... ╞══════════╡
... │ 0        │
... │ 0        │
... └──────────┘
```
Then this code does not …
=> numpy array with 2 dimensions with a schema of same second dimension give a DataFrame with same dimension and same type, even with only one column

py-polars/polars/expr/list.py, py-polars/tests/unit/namespaces/test_list.py
This change enables `list_to_struct` with `fields` to work in a lazy context, closes https://github.com/pola-rs/polars/issues/11143
=> fix(python): Enable special casing of sequence in list_to_struct

Cargo.lock, Cargo.toml
atoi_simd has been fixed and released, so no `[patch.crates-io]` is required
Initial #12744
=> build: Use latest `atoi_simd` release

crates/polars-arrow/src/ffi/stream.rs, crates/polars-core/src/datatypes/dtype.rs, crates/polars-ops/src/chunked_array/strings/extract.rs
The `unreachable!` throw could cause confusion; clarified that the error is being raised as dtype being `Unknown` at this point (which likely indicates that the schema is not bring properly tracked through the query plan for some reason; raising a better error here should make it more obvious what's really at fault).
**Update**:
* As suggested, adds fallible `try_to_arrow` variant, which `to_arrow` now calls and unwraps.
* The `panic!` (on Object) and `unreachable!` (on Unknown) are now both `polars_bail!(InvalidOperation: <err>`).
=> feat: Improve error messages on attempted Arrow conversions involving incompatible/unknown dtypes

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/io/test_database_write.py
Closes #12779.
Deprecates `if_exists` in favour of `if_table_exists`, clarifying _what it is_ that exists.
As per the linked Issue, it's not unreasonable that somebody may think they are replacing some existing _data_ in a table. Given that the downside of getting this wrong is potentially deleting an entire _table_, it's good to remove the potential for ambiguity...
---
@stinodego: as a follow-up we should probably make the `write_database` "if_table_exists" and `write_delta` "mode" parameters consistent, given that they have the same options/behaviour, but use different param/value names 🤔 (Can be left to a subsequent PR).
=> feat(python): improve/deprecate `write_database` "if_exists" param name as "if_table_exists" instead

py-polars/polars/expr/expr.py, py-polars/polars/type_aliases.py, py-polars/tests/unit/interop/test_numpy.py
Closes #12782
Reverts the type hint change in #12709
This change basically meant that type hinting was disabled for anyone that did not have NumPy installed, as `np.ndarray` is treated as `Any`.
I am not sure what the best way to go about this is, but I'd rather have some false positives on NumPy inputs (that you can mute by wrapping with `lit`) than no type hinting at all. We can revisit this at a later point.
=> fix(python): Revert type hint change on expression inputs

py-polars/docs/source/_static/version_switcher.json
This will make sure the version dropdown will work correctly when the new version is released.
=> docs(python): Update version switcher for `0.20`

crates/polars-ops/src/series/ops/is_in.rs, crates/polars-utils/src/total_ord.rs, py-polars/tests/unit/operations/test_is_in.py
Now all nans and signed zeros correctly match each other in `is_in`.
=> fix: use total float ordering in is_in

crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs, py-polars/tests/unit/io/test_parquet.py
Fix https://github.com/pola-rs/polars/issues/12814, https://github.com/pola-rs/polars/issues/12788
Comparing the 2 match blocks, the 2nd match block forgot to `.take` out of `Single`. This PR introduces a loop to re-use the same match.
=> fix: incorrect values from parquet RLE decoding

py-polars/polars/functions/lit.py, py-polars/polars/utils/_parse_expr_input.py, py-polars/src/functions/lazy.rs, py-polars/tests/unit/functions/test_lit.py, py-polars/tests/unit/test_errors.py
This behavior was previously deprecated - this introduces the breaking change.
* List and tuple inputs to `lit` now result in a `List` type literal where each element corresponds to the given input.
* NumPy array inputs to `lit` are now named `"literal"` rather than having an empty name.
* `dtype` argument now correctly works for list/tuple/NumPy inputs
**Before**
```pycon
>>> df = pl.DataFrame({"a": [1, 2]})
>>> df.with_columns( pl.lit([5,6]) )
shape: (2, 2)
┌─────┬─────┐
│ a   ┆     │
│ --- ┆ --- │
│ i64 ┆ i64 │
╞═════╪═════╡
│ 1   ┆ 5   │
│ 2   ┆ 6   │
└─────┴─────┘
```
**After**
```pycon
>>> df.with_columns( pl.lit([5,6]) )
shape: (2, 2)
┌─────┬───────────┐
│ a   ┆ literal   │
│ --- ┆ ---       │
│ i64 ┆ list[i64] │
╞═════╪═══════════╡
│ 1   ┆ [5, 6]    │
│ 2   ┆ [5, 6]    │ …
```
=> feat(python)!: Update `lit` behavior for list/tuple inputs

py-polars/polars/datatypes/classes.py, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/datatypes/test_struct.py
**THIS IS A BREAKING CHANGE**
Ref https://github.com/pola-rs/polars/issues/12196
This completes the data type checking methods.
Note this is an accellerated breaking change because the intended usage could not be introduced without breaking the previous usage.
**Before**
```
>>> pl.List(pl.Int8).is_nested
True
```
**After**
```
>>> pl.List(pl.Int8).is_nested()
True
```
=> feat(python)!: Change `DataType.is_nested` from property to classmethod

crates/polars-arrow/src/compute/temporal.rs, crates/polars-lazy/Cargo.toml, crates/polars-plan/Cargo.toml, crates/polars-plan/src/dsl/function_expr/datetime.rs, crates/polars-time/src/chunkedarray/date.rs, crates/polars-time/src/chunkedarray/datetime.rs, crates/polars-time/src/chunkedarray/kernels.rs, crates/polars-time/src/chunkedarray/mod.rs, crates/polars-time/src/chunkedarray/time.rs, crates/polars-time/src/series/mod.rs, py-polars/polars/expr/datetime.py, py-polars/polars/series/datetime.py, py-polars/tests/unit/namespaces/test_datetime.py
**THIS IS A BREAKING CHANGE**
Closes #6079, closes https://github.com/jorgecarleitao/arrow2/issues/1372
Updates the return type for datetime components as follows:
| method      | dtype old | dtype new |
|-------------|-----------|-----------|
| year        | i32       | i32       |
| iso_year        | i32       | i32       |
| quarter     | u32       | i8        |
| month       | u32       | i8        |
| week        | u32       | i8        |
| day         | u32       | i8        |
| weekday     | u32       | i8        |
| ordinal_day | u32       | i16       |
| hour        | u32       | i8        |
| minute      | u32       | i8        |
| second      | u32       | i8        |
| millisecond | u32       | i32*       |
| microsecond | u32       | i32       |
| nanosecond  | u32       | …
=> feat!: Smaller integer data types for datetime components

py-polars/polars/selectors.py, py-polars/tests/unit/test_selectors.py
Was reminded to add this missing selector by #12837  :)
```python
data = [],
schema = {
"flt": pl.Float64,
"dec1": pl.Decimal,
"dec2": pl.Decimal(10, 10),
}
)
df.select(cs.numeric()).columns
df.select(cs.decimal()).columns
```
=> feat(python): add dedicated `Decimal` selector

.github/workflows/lint-rust.yml, crates/Makefile
Should improve dev flow.
Also make sure to run the lint workflow when doc examples are changed.
=> chore(rust): Update `make check` to only check `polars` crate

crates/polars-plan/src/logical_plan/format.rs, py-polars/tests/unit/test_exprs.py
On the latest release we see
```python
In [43]: print(pl.col('a').gather(0))
col("a").take(0)
```
=> fix: fixup repr of Expr.gather (which was still showing deprecated take)

py-polars/polars/series/list.py
Currently: `Series.list.take` deprecation docstring refers to `:func:'len'`.
Corrected to `:func:'gather'`.
=> docs(python): Fix docstring for deprecated `list.take`

crates/polars-core/src/chunked_array/logical/categorical/merge.rs, crates/polars-error/src/warning.rs, py-polars/polars/__init__.py, py-polars/polars/exceptions.py, py-polars/polars/utils/various.py, py-polars/src/error.rs, py-polars/src/lib.rs, py-polars/src/on_startup.rs, py-polars/tests/unit/datatypes/test_categorical.py, py-polars/tests/unit/test_string_cache.py
fix #12753 
Right now, we issue warnings from rust to python. These all lead to the base `UserWarning` class which is not very user friendly for ignoring certain warnings. This PR introduces a way to issue specific warnings from Rust to python and uses the categorical remapping as a start
```python
s = pl.Series(['a','b'],dtype=pl.Categorical)
s2 = pl.Series(['b','a'],dtype=pl.Categorical)
s.append(s2)
```
```
PerformanceWarningCategoricalRemapping: Local categoricals have different encodings, expensive re-encoding is done to perform this merge operation. Consider using a StringCache or an Enum type if the categories are known in advance
```
You can now ignore this warning with
```python
import warnings
warnings.simplefilter('ignore',pl.PerformanceWarningCategoricalRema …
```
=> feat: specific performance warnings from rust to python

py-polars/polars/dataframe/frame.py, py-polars/polars/datatypes/classes.py, py-polars/polars/io/delta.py, py-polars/polars/io/ipc/functions.py, py-polars/polars/io/parquet/functions.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/datetime.py, py-polars/polars/series/series.py, py-polars/polars/series/struct.py, py-polars/polars/testing/asserts/series.py, py-polars/src/conversion.rs, py-polars/tests/parametric/test_series.py, py-polars/tests/unit/datatypes/test_duration.py, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/functions/range/test_datetime_range.py, py-polars/tests/unit/interop/test_interop.py, py-polars/tests/unit/io/test_ipc.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/test_datatypes.py, py-polars/tests/unit/test_errors.py
Closes #6163 
This went a lot more smoothly than I expected. This update should cause almost no friction with users.
* The following methods now return instantiated `DataType` objects, rather than a mix of classes/instances:
* `Series.dtype`
* `DataFrame.dtypes`
* `LazyFrame.dtypes`
* `DataFrame.schema`
* `LazyFrame.schema`
* `Series.struct.schema`
* Instantiating a DataType will now actually return an instantiated object, e.g. `Int8()` is no longer magically converted into an `Int8` _class_.
* Update the DataType class with default `__hash__`, `__eq__`, and `__repr__` methods. These are valid for 'simple' data types. 'Complex' data types like `Datetime` and `List` overwrite these defaults as they did before.
* Update conversion of DataTypes to/from Rust. Instantiated data types are now …
=> feat(python)!: Return instantiated DataType objects in `schema`/`dtype` methods

py-polars/docs/source/reference/expressions/string.rst, py-polars/docs/source/reference/series/string.rst, py-polars/polars/expr/list.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/list.py
These links don't work in the current docs https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.list.intersection.html#polars.Expr.list.intersection
This fixes them, I built the docs locally to check
=> docs(python): fixup links in deprecation notes

crates/polars-plan/src/dsl/function_expr/dispatch.rs
I would get this error otherwise: 
```
thread '<unnamed>' panicked at crates/polars-plan/src/dsl/function_expr/dispatch.rs:41:27:
called `Result::unwrap()` on an `Err` value: SchemaMismatch(ErrString("invalid series dtype: expected `Utf8`, got `i32`"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> fix(python,rust): don't panic when ambiguous is not utf8

crates/polars-plan/src/logical_plan/lit.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs, crates/polars-plan/src/utils.rs, py-polars/tests/unit/test_predicates.py
Would close https://github.com/pola-rs/polars/issues/12637.
This PR would enable a partial pushdown of predicates past window expressions in both projections and predicates (at the expense of code complexity):
* unoptimized
```javascript
FILTER [(col("key")) == (1)] FROM
FILTER [(count().over([col("key")])) == (1)] FROM
DF ["key", "value"]; PROJECT */2 COLUMNS; SELECTION: "None"
```
* `0.19.16`
```javascript
FILTER [([(count().over([col("key")])) == (1)]) & ([(col("key")) == (1)])] FROM
DF ["key", "value"]; PROJECT */2 COLUMNS; SELECTION: "None"
```
* this PR
```rust
FILTER [(count().over([col("key")])) == (1)] FROM
DF ["key", "value"]; PROJECT */2 COLUMNS; SELECTION: "[(col(\"key\")) == (1)]"
```
Other changes:
* improves predicate re-naming
=> feat: enable partial predicate pushdown past window exprs

py-polars/polars/__init__.py, py-polars/polars/convert.py, py-polars/polars/interchange/from_dataframe.py, py-polars/tests/unit/interchange/test_from_dataframe.py
Closes https://github.com/pola-rs/polars/issues/12377
I decided to keep `from_dataframe` available at the top level, but wrap it to avoid importing anything until it's called. So this does not change the API at all.
=> feat(python): Avoid importing interchange module by default

crates/polars-time/src/windows/duration.rs, py-polars/tests/unit/datatypes/test_temporal.py
closes #12937
haven't timed this yet, but it should come with a nice perf improvement, as for the naive case the arithmetic can all be done on the underlying integers
UPDATE
------
Timing result from truncating 50 million rows by 3 weeks: https://www.kaggle.com/code/marcogorelli/polars-timing?scriptVersionId=154070136
- main: 2.8141296769999826
- here: 2.207328452333362
That's > 20% improvement!
=> fix: correct `truncate` when truncating by multiple weeks

py-polars/polars/dataframe/group_by.py, py-polars/polars/expr/expr.py, py-polars/polars/expr/list.py, py-polars/polars/functions/lazy.py, py-polars/polars/lazyframe/group_by.py, py-polars/polars/series/list.py, py-polars/polars/series/series.py
Followup of #12934, slightly improving docstrings and examples of `count` methods/function.
=> docs(python): Expand docstrings for `count`

py-polars/polars/series/utils.py
This should reduce some overhead in dispatching Series methods to the expression engine.
=> perf(python): Use `select_seq` for expression dispatch

crates/polars-time/src/windows/duration.rs, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/operations/test_group_by_dynamic.py
this gives about a 4% improvement for `truncate`, from a benchmark I ran here https://www.kaggle.com/code/marcogorelli/polars-timing/notebook?scriptVersionId=154169901
nothing major, but nice to have IMO - no offense taken if it's too minor
=> perf: add fastpaths for UTC in temporal truncate and add functions

crates/polars-arrow/src/io/ipc/write/serialize.rs, py-polars/polars/utils/_construction.py, py-polars/tests/unit/series/test_series.py
Resolves #12616.
Not sure in which cases we want to use `with_match_primitive_type` vs `with_match_primitive_type_full`, but changing it in this scenario fixes this issue and don't see errors pop up from the tests suite with this change.
note: running make-precommit reformatted some files I did not touch
~~**Edit**: Seems like the ruff formatter here wants to undo the fomatting changes. Any idea what part from my setup is out of sync and how i can fix it?~~
**Edit 2**: will add test if this is the way 2 go
=> fix(rust): Dataframes with Decimal columns cannot be pickled

py-polars/polars/dataframe/frame.py, py-polars/polars/io/database.py, py-polars/tests/unit/io/test_database_read.py
Closes #12951.
The update is generic, not `sqlite3` specific, so if there are any other similar cursor "execute" methods out there (that don't take keyword args), we will now handle those transparently/correctly too. 
Added suitable test coverage.
=> fix(python): support parameterised `read_database` calls against cursors that only take positional args

crates/polars-arrow/src/buffer/immutable.rs, py-polars/tests/unit/series/test_extend.py
=> fix: don't get mutable if buffer is sliced

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
- Better align the method signature with `join`
- Properly add the "experimental" warning.
- It was argued before that the experimental status should be stripped, however, I would suggest this method be fully implemented in Rust before stripping experimental status.
There is no deprecation for this as it was considered experimental (though not properly indicated on the `LazyFrame` variant...).
=> feat(python)!: Update `update` signature

crates/polars-time/src/date_range.rs, py-polars/tests/unit/functions/range/test_date_range.py, py-polars/tests/unit/functions/range/test_time_range.py
Ref https://github.com/pola-rs/polars/issues/11892
Instead of erroring, this will return an empty Series.
=> feat: Allow `end` before `start` in `date/time_range`

py-polars/polars/utils/udfs.py, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py, py-polars/tests/unit/operations/map/test_map_elements.py, py-polars/tests/unit/streaming/test_streaming.py, py-polars/tests/unit/test_lazy.py
This came up on Discord:
> because when you read it, it's quite strange. Replace map_elements by more map_elements
To be fair, the current message:
```diff
In this case, you can replace your `map_elements` with the following:
- pl.col("a").map_elements(lambda x: ...)
+ ((pl.col("a") * 9) / 5) + 32
```
might be confusing if you don't immediately recognise it as a git diff
I'm suggesting to make it much simpler:
```diff
Don't do this:
- pl.col("a").map_elements(lambda x: ...)
Do this instead:
+ ((pl.col("a") * 9) / 5) + 32
```
=> feat(python): clarify "inefficient map_elements warning" message

py-polars/polars/series/series.py, py-polars/src/series/mod.rs
=> perf(python): Avoid dispatching `Series.head/tail` to the expression engine

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/namespaces/test_struct.py
Closes #12947.
Seems reasonable to be consistent here; the standard behaviour when creating a Series directly (without giving it an explicit name) is to assign the default name as the empty string.
The following now  behave consistently:
```python
struct_data = [ {'a':1,'b':2}, {'a':2,'b':4} ]
pl.Series( values=struct_data )
pl.DataFrame( struct_data ).to_struct()
```
Previously the second of these would result in the following error:
```
TypeError: DataFrame.to_struct() missing 1 required positional argument: 'name'
```
=> feat(python): default `to_struct` Series name made consistent with the usual default Series name (empty string)

crates/polars-plan/src/dsl/function_expr/range/date_range.rs, crates/polars-plan/src/dsl/function_expr/range/datetime_range.rs, crates/polars-plan/src/dsl/function_expr/range/int_range.rs, crates/polars-plan/src/dsl/function_expr/range/time_range.rs, crates/polars-plan/src/dsl/function_expr/range/utils.rs, py-polars/tests/unit/functions/range/test_date_range.py, py-polars/tests/unit/functions/range/test_datetime_range.py, py-polars/tests/unit/functions/range/test_int_range.py, py-polars/tests/unit/functions/range/test_time_range.py
Closes https://github.com/pola-rs/polars/issues/11892
Also changes the way capacity is allocated for `int_ranges`.
=> fix: Allow broadcasting in `ranges` 

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_sql.py
Closes #13011.
SQL is 1-indexed on strings/arrays, not 0-indexed.
Validated the updated test results here against SQLite; when I have a little more time I plan to follow up with a new assert/utility that actually executes the query being tested against both polars _and_ SQLite (or, better, a local/ephemeral PostgreSQL instance [^1]) so we can avoid similar gremlins in the future 🤔
[^1]: #12815
=> fix(rust,python,cli): fix SQL substring indexing

py-polars/polars/functions/eager.py, py-polars/tests/unit/functions/test_functions.py
* Take advantage of `outer_coalesce` to streamline frame-alignment function.
* Don't rely on the frame object's `id` for column deduplication via "suffix" (this fixes an edge-case if the identical frame appears more than once in the alignment input).
```python
df1 = pl.DataFrame( [[3, 5, 6], [5, 8, 9]], orient="row" )
df2 = pl.DataFrame( [[2, 5, 6], [3, 8, 9], [4, 2, 0]], orient="row" )
pl.align_frames( df1, df2, df2, on="column_0" )
```
**Before**
```
DuplicateError: 
unable to hstack, column with name "column_14438432720" already exists
```
**After**
```
[shape: (4, 3)
┌──────────┬──────────┬──────────┐
│ column_0 ┆ column_1 ┆ column_2 │
│ ---      ┆ ---      ┆ ---      │
│ i64      ┆ i64      ┆ i64      │
╞══════════╪══════════╪══════════╡
│ 2        ┆ null     ┆ …
```
=> fix(python): streamline `align_frames` and fix edge-case where the identical frame object appears more than once

crates/polars-json/src/ndjson/deserialize.rs, crates/polars-ops/src/chunked_array/strings/json_path.rs
Simd-json had a max::u32 buffer length, so I am just parsing per max buffer length and then concatenating all the arrays at at the end.
closes https://github.com/pola-rs/polars/issues/13028
=> fix(rust,python): parse json_decode per max buffer length

crates/polars-core/src/chunked_array/comparison/categorical.rs, crates/polars-core/src/chunked_array/comparison/mod.rs, crates/polars-core/src/chunked_array/logical/categorical/builder.rs, crates/polars-core/src/chunked_array/logical/categorical/mod.rs, crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-core/src/chunked_array/ops/nulls.rs, crates/polars-core/src/series/comparison.rs, crates/polars-error/src/lib.rs, docs/src/python/user-guide/concepts/data-types/categoricals.py, docs/user-guide/concepts/data-types/categoricals.md, py-polars/polars/series/series.py, py-polars/tests/unit/datatypes/test_categorical.py, py-polars/tests/unit/datatypes/test_enum.py
relates to #7636 
Allow users to compare two Enums based on order in categories
```python
dtype = pl.Enum(["LOW", "MEDIUM", "HIGH"])
df_enum = pl.DataFrame(
[
pl.Series("a_cat", ["LOW", "MEDIUM", "MEDIUM", "HIGH", "MEDIUM"], dtype=dtype),
pl.Series("b_cat", ["HIGH", "HIGH", "MEDIUM", "LOW", "LOW"], dtype=dtype),
]
)
df_cmp = df_enum.select((pl.col("a_cat") <= pl.col("b_cat")).alias("cmp"))
```
```
shape: (5, 1)
┌───────┐
│ cmp   │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
│ true  │
│ true  │
│ false │
│ false │
└───────┘
```
```
df_cmp = df_enum.select((pl.col("a_cat") <= "MEDIUM").alias("cmp"))
```
```
shape: (5, 1)
┌───────┐
│ cmp   │
│ ---   │
│ bool  │
╞═══════╡
│ true  │
│ true  │
│ true  │
│ false │
│ true  │
└───────┘
```
It also changes behaviour when comparing two categoricals. …
=> feat(rust,python): Allow order operators (<,>,>=,<=) on Enum types

.github/workflows/test-python.yml
It happens relatively often that all tests pass but you forgot to update the doctests. This will give you slightly faster feedback in that case.
=> ci(python): Run doctests before other tests

crates/polars-core/src/chunked_array/temporal/mod.rs, crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs, crates/polars-plan/src/dsl/function_expr/range/datetime_range.rs, crates/polars-time/src/date_range.rs, crates/polars-time/src/upsample.rs, crates/polars-time/src/utils.rs, py-polars/tests/unit/functions/range/test_datetime_range.py
closes #11713
This was _so_ satisfying
There gist of the change is to avoid a "remove time zone, then put it back again" cycle, thus avoiding running into ambiguous datetimes
By doing that, quite a lot of unnecessary functions and logic can be removed - always nice to fix a bug by removing code!
=> fix: dont raise for datetime_range if starting on ambiguous datetime and earliest was specified

py-polars/polars/io/_utils.py, py-polars/polars/io/csv/functions.py, py-polars/polars/io/ipc/anonymous_scan.py, py-polars/polars/io/ipc/functions.py, py-polars/polars/io/parquet/anonymous_scan.py, py-polars/polars/io/parquet/functions.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/io/cloud/test_aws.py, py-polars/tests/unit/io/test_lazy_parquet.py, py-polars/tests/unit/io/test_parquet.py
Ref https://github.com/pola-rs/polars/issues/13040
* Dispatch `read_parquet` to `scan_parquet` where appropriate. This means that for purposes of cloud reading, it no longer uses fsspec.
* Add `hive_partitioning` and `retries` parameters.
* Shuffle around some parameters to make the order more sensible.
=> feat(python)!: Use Object Store instead of fsspec for `read_parquet`

docs/releases/upgrade/0.20.md, docs/releases/upgrade/index.md, mkdocs.yml
Closes #12887
This version includes quite a few breaking changes.
We are preparing for the `1.0` release and aim to make the upgrade from `0.20` to `1.0` as smooth as possible.
Therefore, we prioritized getting any breaking changes in now rather than with `1.0`.
Please bear with us while we continue to make Polars the best tool it can be!
=> docs(python): Add upgrade guide for Python Polars 0.20

crates/polars-error/src/lib.rs
the context manager is only needed for initialising the categories, operations can be done outside of it
=> docs: take pl.concat out of StringCache context manager in "mismatched string cache" error message

docs/_build/API_REFERENCE_LINKS.yml, docs/src/python/user-guide/expressions/user-defined-functions.py, docs/src/rust/user-guide/expressions/user-defined-functions.rs, docs/user-guide/expressions/user-defined-functions.md
I'd like to make a separate PR to do a bit of an overhaul of this page, as it's quite complex and am not too keen on starting off with a gotcha...but that's for a separate PR, first I'd suggest just updating the syntax
---
The Rust examples are similar to the Python ones, but don't actually match 100% (this is already the case, regardless of this PR) - for example, the Python dataframe has `i64` values, whereas the Rust one `i32`. No big deal, just something I noticed
---
this is how the rewritten part in the middle looks like now:
<details>
<summary>
Preview (click here)
</summary>
</details>
=> docs: update user-defined-functions for 0.19.x

crates/polars-arrow/src/legacy/kernels/rolling/quantile_filter.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
This needs a patch. The rolling quantile introduced a rather complicated algorithm and got in a incorrect state. This fixes that.
=> fix: rolling_quantile can get incorrect state

crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/utils.rs, py-polars/tests/unit/operations/test_is_in.py
Resolves #13084
The function is called `all_leaf_literal` but its intent is to determine whether a scalar should be returned (the only place this function is ever called is in the `is_in` function:
```python
// lit(true).is_in() returns a scalar.
let returns_scalar = all_leaf_literal(&self);
```
This function was returning true ([here](https://github.com/pola-rs/polars/blob/main/crates/polars-plan/src/utils.rs#L151-L161)) when there were no leaf literals because `all([]) == true`, as is the case when self is a `Range` expr. If our node is a `Function` we should look up whether it's expected to return a scalar.
=> fix(rust): use `FunctionExpr`'s scalar return type for `is_in`

py-polars/polars/functions/lit.py, py-polars/tests/unit/test_exprs.py
=> fix(python): allow timeunit-less dtype in `pl.lit` creation

crates/polars-arrow/src/legacy/array/mod.rs, py-polars/tests/unit/functions/test_repeat.py
=> fix: repeat_by should not raise if by contains nulls

crates/polars-plan/src/dsl/mod.rs, py-polars/tests/unit/namespaces/string/test_string.py
Minor clean up. remove the legacy param name `auto_explode`.
=> chore: Update `auto_explode` param name to `returns_scalar`

py-polars/polars/dataframe/frame.py, py-polars/polars/utils/various.py
Closes #13097.
Several wins here:
* Can drop the pyarrow[^1] conversion path completely, omitting another implicit (though optional) legacy dependency.
* We can do this because new benchmarking shows fully-native conversion to dicts is now ~2-3x faster than pyarrow  ;)
Using the schema provided in the linked issue:
```python
"Col0": range(60_000),
"Col1": datetime.now(),
"Col2": "xxx",
"Col3": "yyy",
"Col4": "zzz",
"Col5": 5.5,
"Col6": 6.6,
"Col7": 7.7,
"Col8": "!!!",
"Col9": "###",
})
%timeit df.to_dicts()
%timeit list(df.iter_rows(named=True))
%timeit df.to_arrow().to_pylist()
```
The last of those used to be a fast path inside `iter_rows`; since then our own/native conversion has become a lot more streamlined and it …
=> perf(python): drop the pyarrow conversion path in `iter_rows`; we can now do fully native conversion ~2-3x faster

crates/polars-arrow/src/legacy/array/mod.rs, py-polars/tests/unit/functions/test_repeat.py
The same as #13105. Somehow I forgot to fix other similar branches. 😞
=> fix: Update offsets of null value correctly for all `from_iter_xxx_trusted_len`

crates/polars-plan/src/logical_plan/optimizer/simplify_functions.rs, py-polars/tests/unit/test_predicates.py
This creates cleaner logical plans and makes might enable downstream optimizations to trigger.
=> feat: prune all/any_horizontals with single inputs

crates/polars-ops/src/series/ops/horizontal.rs, crates/polars-plan/src/dsl/function_expr/dispatch.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/functions/aggregation/horizontal.py, py-polars/polars/functions/lazy.py, py-polars/tests/unit/functions/aggregation/test_horizontal.py
As we discussed before, expression shouldn't have a specific name.
=> fix: Use the name of the leftmost expression in horizontal operations

crates/polars-lazy/src/frame/mod.rs, py-polars/docs/source/reference/dataframe/aggregation.rst, py-polars/docs/source/reference/lazyframe/aggregation.rst, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/src/lazyframe.rs, py-polars/tests/unit/operations/test_statistics.py
=> feat: Implement `count` for DataFrame/LazyFrame

py-polars/polars/io/parquet/functions.py
The Python read/scan_parquet api docs for storage_options link to version 0.7.0 of object_store while polars uses 0.8.
Instead of putting a fixed version in there, `latest` might be better.
resolves #13175
=> docs(python): Link to latest object_store docs in api doc

py-polars/polars/datatypes/constructor.py, py-polars/polars/io/spreadsheet/_write_utils.py, py-polars/pyproject.toml, py-polars/requirements-lint.txt, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/datatypes/test_enum.py, py-polars/tests/unit/io/test_spreadsheet.py, py-polars/tests/unit/test_lazy.py
Newest ruff has a nicer way to specify docstring conventions.
Apparently, we also get some additional commas :)
=> chore(python): Update ruff & ruff settings

Cargo.toml
It no longer exists. I'm surprised Cargo doesn't throw a warning or error. It trips up dependabot though so I am removing it.
=> chore(rust): Remove `polars-algo` reference in Cargo.toml

Cargo.lock, Cargo.toml
polars-utils uses bytemuck::allocation::zeroed_vec which was added in [v1.11.0](https://docs.rs/bytemuck/1.11.0/bytemuck/allocation/fn.zeroed_vec.html) (compare to [v1.10.0](https://docs.rs/bytemuck/1.10.0/bytemuck/?search=zeroed_vec)). However, polars only pins the version at 1, which leads to a compile error if for historical reasons or due to other packages the version is lower than 1.11.
Fixes #13190
=> build(rust): Set minimum version for `bytemuck` to `1.11`

crates/polars-plan/src/dsl/python_udf.rs, py-polars/polars/expr/expr.py, py-polars/src/expr/general.rs, py-polars/src/map/lazy.rs, py-polars/tests/unit/operations/map/test_map_batches.py, py-polars/tests/unit/test_errors.py
This will default to a safer version of `map_batches`. We will now assume you cannot run on batches. E.g. don't merely do an elementwise operation like `+` or `pow`, but do something that requires all data. E.g. `sort`, `sum`, `rolling_min`, etc.
`map_batches` will now not run by default on the streaming engine unless you set `is_elementwise=True`. In that case it can produce wrong results in a group-by, but hey, you said it was elementwise. :shrug:
=> feat: make python `map_batches` safer

crates/polars-arrow/src/compute/cast/mod.rs, py-polars/tests/unit/datatypes/test_array.py
This closes #12160.
The original algorithm only worked if list is `non-null`, because `null` value should occupy the number of `width` slot in `FixedSizeList`.
=> fix(rust): Allow casting nullable list to array

crates/polars-plan/src/dsl/function_expr/range/date_range.rs, crates/polars-plan/src/dsl/function_expr/range/datetime_range.rs, crates/polars-plan/src/dsl/function_expr/range/int_range.rs, crates/polars-plan/src/dsl/function_expr/range/mod.rs, crates/polars-plan/src/dsl/function_expr/range/time_range.rs, crates/polars-plan/src/dsl/function_expr/range/utils.rs, crates/polars-plan/src/dsl/functions/range.rs, py-polars/polars/functions/range/int_range.py, py-polars/src/functions/range.rs, py-polars/tests/unit/functions/range/test_int_range.py
Theoretically we can expressify `step/interval` for both numeric and temporal ranges, but only the former is supported here. Things are more complicated for temporal ranges:
1. For the `interval` parameter, we do not want it to participate in the casting of common super type with `start & end`. We could add new special branch to the type conversion rule, but I'd like to see a more general solution, especially as we increasingly turn arguments into expressions.
2. For `datetime_ranges`, the type conversion of `start/end` depends in part on the value of `interval`.
So I think of it as follow-up PR(At that time, maybe we can unify `temporal_ranges_impl_broadcast` and `numeric_ranges_impl_broadcast`, or maybe we can't. Sometimes it's hard to unify the handling of numeric and utf8 types …
=> feat: Allow `step` parameter in `int_ranges` to take an expression

crates/polars-core/src/series/any_value.rs, py-polars/tests/unit/datatypes/test_array.py
Closes #12719.
Observationally the cast from `List` to `Array` is (as expected) _extremely_ cheap (eg: a  "with_columns" cast of a 25_000_000 x 4 `List` col to `Array` only takes 0.0096 secs), so this PR seems to be a simple/minimal way to support `Array` AnyValues (absent a dedicated micro-optimised path 🤔)
This opens up `Array` usage to additional constructors, such as `pl.from_dicts` in the linked issue, which otherwise fail.
=> feat: Support `Array` dtype AnyValue Series construction

crates/polars-core/src/chunked_array/ops/chunkops.rs, crates/polars-core/src/series/implementations/null.rs, py-polars/tests/unit/io/test_parquet.py
Just to show that there is a bug here. I wonder do we have a better way to avoid `rechunk`.
This fixes #13170.
=> fix(rust): slice for `NullChunked` no longer force single chunk

docs/src/python/user-guide/transformations/concatenation.py, docs/src/rust/user-guide/transformations/concatenation.rs, docs/user-guide/transformations/concatenation.md
The horizontal concatenation documentation in the user guide states that it is an error to concatenate DataFrames of different lengths, but columns will actually be padded with nulls at the end if lengths are different.
=> docs: fix horizontal concatenation documentation

crates/polars-time/src/windows/calendar.rs, crates/polars-time/src/windows/duration.rs, py-polars/tests/parametric/time_series/test_truncate.py
closes #13157 
benchmark: https://www.kaggle.com/code/marcogorelli/polars-timing?scriptVersionId=155987273
going to take my time on this one, as there's a few details which are easy to get wrong and I don't think the current test coverage covers everything...looks promising though
=> perf: make `.dt.truncate('*mo')` more than 3x faster

crates/polars-ops/src/series/ops/replace.rs, py-polars/tests/unit/operations/test_replace.py
Closes https://github.com/pola-rs/polars/issues/13164
I'm not too happy with the error message here, but I hope we can actually support this rather than raise an error, so I'm not putting in more effort into cleaning up this error message for now.
=> fix(python): Raise error on `replace` categoricals with strings

crates/polars-ops/src/series/ops/replace.rs, py-polars/Makefile, py-polars/tests/unit/operations/test_replace.py
Using a strict cast solves some obscure behavior due to values being set to null and then replacing null values.
=> fix: Better handle mismatched dtypes in `replace`

crates/polars-core/src/chunked_array/object/extension/mod.rs, crates/polars-lazy/src/frame/exitable.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/physical_plan/executors/filter.rs, crates/polars-lazy/src/physical_plan/executors/group_by.rs, crates/polars-lazy/src/physical_plan/executors/group_by_dynamic.rs, crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, crates/polars-lazy/src/physical_plan/executors/group_by_rolling.rs, crates/polars-lazy/src/physical_plan/executors/join.rs, crates/polars-lazy/src/physical_plan/executors/projection.rs, crates/polars-lazy/src/physical_plan/executors/python_scan.rs, crates/polars-lazy/src/physical_plan/executors/sort.rs, crates/polars-lazy/src/physical_plan/executors/stack.rs, crates/polars-lazy/src/physical_plan/executors/udf.rs, crates/polars-lazy/src/physical_plan/executors/union.rs, crates/polars-lazy/src/physical_plan/executors/unique.rs, crates/polars-lazy/src/physical_plan/state.rs, crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs, crates/polars-pipe/src/operators/context.rs, crates/polars-pipe/src/pipeline/dispatcher.rs, py-polars/docs/source/reference/lazyframe/in_process, py-polars/polars/__init__.py, py-polars/polars/lazyframe/__init__.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/lazyframe/in_process.py, py-polars/src/lazyframe/exitable.rs, py-polars/src/lazyframe/mod.rs, py-polars/src/lib.rs
This gives you an `InProcessQuery` handler that allows you to cancel the query
```python
import time
def sleep(df: pl.DataFrame) -> pl.DataFrame:
time.sleep(1)
return df
ipq = pl.LazyFrame({"a": [1]}).map_batches(sleep).map_batches(sleep).collect(background=True)
out = ipq.fetch()
if out is not None:
print("query finished", df)
if condition():
ipq.cancel()
ipq.fetch_blocking()
```
=> feat: add cancellable queries

py-polars/polars/dataframe/frame.py, py-polars/polars/io/_utils.py, py-polars/polars/io/ipc/functions.py, py-polars/polars/io/parquet/functions.py, py-polars/tests/unit/io/test_parquet.py
Closes https://github.com/pola-rs/polars/issues/13099
=> fix(python): Correctly use `read_parquet` for all binary inputs

crates/polars-core/src/chunked_array/mod.rs, py-polars/tests/unit/operations/test_filter.py
=> fix(rust): match_chunks shouldn't change the dtype

py-polars/polars/series/series.py
Related to: Add missing docstring examples #13161 
Includes the following examples from the provided csv file
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.abs.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.cbrt.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.exp.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.log.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.log10.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.log1p.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.skew.html …
=> docs(python): Add a couple of docstring examples to Series methods

crates/polars-ops/src/chunked_array/list/count.rs, py-polars/tests/unit/datatypes/test_list.py
Add fast path to `count_bits_set_by_offsets` when all bits are either set or cleared.
Some benchmarks:
```python
df = pl.DataFrame({'A': [[False, True] * 100, [True] * 200] * 500})
%timeit df.with_columns(sum=pl.col('A').list.sum())
304 µs ± 2.34 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
df = pl.DataFrame({'A': [[False, False] * 100, [False] * 200] * 500})
%timeit df.with_columns(sum=pl.col('A').list.sum())
68.7 µs ± 301 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
df = pl.DataFrame({'A': [[True, True] * 100, [True] * 200] * 500})
%timeit df.with_columns(pl.col('A').list.sum())
72.4 µs ± 392 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
=> perf: add fast path to `count_bits_set_by_offsets`

py-polars/polars/utils/udfs.py
There's 3 cleanups I'm suggesting here:
1. make `try` blocks smaller. I think this is uncontroversial
2. remove an unused `try` block in `_is_raw_function`. The whole test suite passes without it, I think it the code can be simplified by just removing it
3. removing the `_can_attempt_rewrite` dict. I think this was originally introduced for performance reasons, but:
- I'm not seeing any perf difference here vs on `main` (timing `pl.col('a').map_elements(lambda x: abs(x))` here and on `main` takes about `8.988900013459247e-05` seconds on my laptop
- it adds quite a lot of complexity
It's already super-fast, I don't think the extra complexity is warranted
=> chore(python): clean up bytecode parsing a bit

py-polars/docs/requirements-docs.txt, py-polars/docs/source/conf.py
This removes typing overloads from the API reference.
See the `read_excel` docs to find out why it's currently a problem:
https://pola-rs.github.io/polars/docs/python/dev/reference/api/polars.read_excel.html
After this update:
=> docs(python): Fix display of overloaded signatures

crates/polars-ops/src/series/ops/replace.rs, py-polars/tests/unit/operations/test_replace.py
fix #13215
Ideally, we find a way to improve the casting to one step. For strings, we now cast str -> categorical and then do the remapping. We should use the existing mapping in the first cast.
=> fix: improve replace on categoricals

Cargo.lock, py-polars/Cargo.toml, py-polars/tests/unit/test_consortium_standard.py
We made some updates to the build system we want to try out.
We now check whether or not your CPU can run Polars (https://github.com/pola-rs/polars/pull/13134). If not, we throw a warning. We want to make sure this check does not cause problems for our users. If you can, please install the pre-release version and see if everything runs correctly for you!
Some tests failed due to a dependency not handling pre-release versions, these are skipped now and an issue has been created: https://github.com/data-apis/dataframe-api-compat/issues/62
=> release(python): Python Polars 0.20.3-rc.1 (pre-release)

crates/polars-arrow/src/array/growable/binary.rs, crates/polars-arrow/src/array/growable/boolean.rs, crates/polars-arrow/src/array/growable/dictionary.rs, crates/polars-arrow/src/array/growable/fixed_binary.rs, crates/polars-arrow/src/array/growable/fixed_size_list.rs, crates/polars-arrow/src/array/growable/list.rs, crates/polars-arrow/src/array/growable/map.rs, crates/polars-arrow/src/array/growable/primitive.rs, crates/polars-arrow/src/array/growable/structure.rs, crates/polars-arrow/src/array/growable/utf8.rs, crates/polars-arrow/src/array/growable/utils.rs
This came to light in #13243. During a concat/rechunk, we always allocate (and write/copy to) a `validity` buffer, even when there are no nulls.
This ensures we don't.
=> perf: don't needlessly allocate validity in concat/rechunk

py-polars/tests/unit/test_consortium_standard.py
Disabled in #13285 , issue has since been fixed.
=> test(python): Re-enable consortium standard tests

Makefile, py-polars/Makefile
I want to be able to do everything from the repo root. For convenience, commands are still available in `py-polars`.
=> chore(python): Copy Makefile build commands to top level

crates/polars-arrow/src/array/static_array.rs, crates/polars-core/src/chunked_array/ops/arity.rs, crates/polars-core/src/datatypes/mod.rs, crates/polars-core/src/datatypes/static_array.rs, crates/polars-core/src/utils/mod.rs, crates/polars-ops/src/chunked_array/binary/namespace.rs, crates/polars-ops/src/chunked_array/strings/namespace.rs, crates/polars-ops/src/chunked_array/strings/strip.rs, py-polars/tests/unit/test_arity.py
Would fix https://github.com/pola-rs/polars/issues/12632.
=> fix: broadcasting of unit LHS in string operations

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/functions/aggregation/test_horizontal.py, py-polars/tests/unit/namespaces/test_meta.py, py-polars/tests/unit/operations/test_aggregations.py, py-polars/tests/unit/operations/test_filter.py, py-polars/tests/unit/test_exprs.py
Closes #12577 (following up #12603).
Adds the same support for multiple predicates and kwargs as recently added to frame-level `filter` and `when/then`.
```python
"key": ["a", "a", "a", "a", "b", "b", "b", "b", "b"],
"n": [1, 2, 2, 3, 1, 3, 3, 2, 3],
})
df.group_by("key").agg(
n_0 = pl.col("n").filter( n=1 ).sum(),
n_1 = pl.col("n").filter( n=2 ).sum(),
n_2 = pl.col("n").filter( n=3 ).sum(),
).sort(by="key")
```
=> feat(python): enhance expression-level `filter` syntax with support for multiple predicates and kwargs

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_sql.py
Closes #13302.
It's a coin-flip as to which spelling ("stdev" or "stddev") is used in different database dialects, and there's no harm in supporting both; will make it a little more accessible if you're not a longtime PostgreSQL user (also added support for "var" as an alias for "variance" for much the same reason - didn't add "std" for "stddev" as it is a little more ambiguous and less widely used).
Added new test coverage for both "stddev" and "variance".
=> feat(rust,python,cli): support common variant spelling `STDEV` in the SQL engine

py-polars/src/series/construction.rs
This is still slower. As it will always be, but it removes the unexpected contention.
#13282
=> perf: don't trigger internal borrwing in numpy memmap

crates/polars-time/src/windows/duration.rs
This speeds up `.dt.truncate('100y')` >2x by first doing the whole years, and then the individual months
https://www.kaggle.com/code/marcogorelli/polars-timing?scriptVersionId=156901483
=> perf: speed up `.dt.truncate` for large numbers of years

py-polars/docs/source/conf.py
=> docs(python): Restore light/darkmode switch in API reference

crates/polars-io/src/csv/parser.rs, crates/polars-io/src/csv/read_impl/mod.rs, py-polars/tests/unit/io/test_csv.py
Closes #13022.
The linked issue mentions `raise_if_empty` but that's a red herring; the real issue is that we were trying to skip the header row _before_ we had skipped the pre-header rows (including comments), instead of after. Reordering those two operations so that the correct lines are skipped solves the error.
Added some additional comment/skip permutations to the existing test coverage.
Also: the slightly misleadingly-named `skip_header` function didn't actually have any header-specific logic; was just a simple redirect to `skip_this_line`, so we may as well just call that directly.
=> fix(rust,python): fix `csv` parser error when commented-out rows precede the header row

crates/polars-plan/src/dsl/meta.rs, py-polars/polars/expr/expr.py, py-polars/polars/expr/meta.py, py-polars/polars/functions/lazy.py, py-polars/polars/selectors.py, py-polars/polars/utils/__init__.py, py-polars/polars/utils/various.py, py-polars/src/expr/meta.rs, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/namespaces/test_meta.py, py-polars/tests/unit/test_selectors.py
Closes #13247.
* Implemented `pl.exclude` as a dedicated selector (it now redirects to the new `cs.exclude`); adds flexibility, combining all input names/dtypes/selectors into a single/compound selector expression before subtracting that from `cs.all()`.
* Adds `expr.meta.is_column()`, as it's useful to know if an expression is a simple column or not; this allows for some parsing simplifications/extensions here, and a follow-up PR taking additional advantage is coming shortly.
We can consider retiring `pl.exclude` in the future as it is now a pure redirect to the more capable `cs.exclude`.
```python
df = pl.DataFrame({"a": [1], "b": [2], "c": [3]})
pl.exclude(cs.first(), cs.last()) + 100
)
```
=> feat(python): rework `pl.exclude` as a pure selector, allowing other selectors as input

crates/polars-core/src/datatypes/dtype.rs, py-polars/tests/unit/datatypes/test_enum.py
Closes #13330.
Updated `DataType::Display` trait for enum categoricals.
```python
compass_points = ["North", "East", "South", "West"]
data = {"directions": compass_points},
schema_overrides = {"directions": pl.Enum(compass_points)},
)
print( df )
```
=> fix(rust,python): updated Display trait for enum categoricals

py-polars/polars/functions/repeat.py, py-polars/polars/utils/_parse_expr_input.py, py-polars/tests/unit/functions/test_repeat.py
Various minor fixes/improvements to the `ones` and `zeros` convenience functions.
(Follow up from https://github.com/pola-rs/polars/issues/13121#issuecomment-1864318096).
* Raise a suitable error on invalid/unsuitable "dtype" value instead of returning a series of `null` values.
* Ensure proper "dtype" pass-through from `repeat` → `parse_as_list_of_expressions` → `lit`.
* Extended test coverage to include error conditions, expected defaults, additional dtypes.
* Improve handling of `Array` dtype (get width and create 1/0 arrays of that length).
```python
pl.ones(n=2, dtype=pl.Array(pl.UInt8,width=3), eager=True)
```
Before
```
shape: (2,)
Series: 'ones' [null]
[
null
null
]
```
After
```
shape: (2,)
Series: 'ones' [array[u8, 3]]
[
[1, 1, 1]
[1, 1, 1]
]
```
```python
pl.zeros(n=2, …
```
=> fix(python): don't lose track of `ones` and `zeros` dtype, improve use with `Array`, raise error if dtype invalid

.github/workflows/release-python.yml
I merged #13353 and #13354 a bit too quickly. There were some breaking changes I should have addressed. Doing so here.
=> ci(python): Update release workflow for new upload/download artifact versions

py-polars/polars/utils/udfs.py
instead of
```
if not condition:
logic_1
logic_2
```
do
```
if condition:
logic_2
logic_1
```
Super-minor, I know, but it helps simplify things ahead of further complexity from https://github.com/pola-rs/polars/pull/13347
=> chore(python): reverse condtion order in udfs _expr function

crates/polars-sql/src/context.rs, crates/polars-sql/src/functions.rs, crates/polars-sql/src/keywords.rs, crates/polars-sql/src/sql_expr.rs, crates/polars-sql/src/table_functions.rs, py-polars/tests/unit/sql/test_sql.py
* Adds polars SQL engine support for `REGEXP` and `RLIKE` pattern matching (functionally identical to each other).
* Minor tidy-up; inconsistent use of "Sql" vs "SQL" in the crate's object/func names - standardised on "SQL".
* Bonus unit test coverage for `CASE … WHEN … ELSE … END` and `COALESCE`.
Literal pattern match:
```python
"idx": [0, 1, 2, 3, 4],
"val": ["ABC", "abc", "000", "A0C", "a0c"],
})
with pl.SQLContext(test_data=lf, eager_execution=True) as ctx:
print( ctx.execute("SELECT * FROM test_data WHERE val NOT REGEXP '.*c$'") )
```
Expression pattern match (new: not available through the existing `~`, `~*`, etc regex ops):
```python
"idx": [0, 1, 2, 3, 4],
"val": ["ABC", "abc", "000", "A0C", "a0c"],
"pat": ["^A", "^A", "^A", r"[AB]\d.*$", …
```
=> feat(rust,python,cli): support `REGEXP` and `RLIKE` pattern matching in SQL engine

crates/polars-plan/src/dsl/function_expr/range/date_range.rs, crates/polars-plan/src/dsl/function_expr/range/datetime_range.rs, crates/polars-plan/src/dsl/function_expr/range/int_range.rs, crates/polars-plan/src/dsl/function_expr/range/mod.rs, crates/polars-plan/src/dsl/function_expr/range/time_range.rs, crates/polars/tests/it/lazy/expressions/apply.rs, py-polars/polars/expr/datetime.py, py-polars/polars/functions/range/date_range.py, py-polars/polars/functions/range/datetime_range.py, py-polars/polars/functions/range/int_range.py, py-polars/polars/functions/range/time_range.py, py-polars/polars/series/datetime.py, py-polars/tests/benchmark/test_release.py, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/functions/range/test_date_range.py, py-polars/tests/unit/functions/range/test_datetime_range.py, py-polars/tests/unit/functions/range/test_int_range.py, py-polars/tests/unit/functions/range/test_time_range.py, py-polars/tests/unit/operations/rolling/test_rolling.py, py-polars/tests/unit/operations/test_window.py
This fixes #13314.
Maybe one could argue that It's weird that `pl.int_ranges(5, 0, -1)`'s name is `literal`. But we prefer to follow the same leftmost rule as the other expressions.
=> fix(rust): range/ranges output name should follow lhs rule

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/polars/utils/_construction.py, py-polars/tests/unit/datatypes/test_struct.py, py-polars/tests/unit/test_constructors.py
Closes  #13338.
Various init enhancements. Can already init Series and DataFrame objects directly from an existing Series; now we can additionally init both DataFrame _and_ Series from an existing DataFrame (improving cross-class constructor consistency). 
Also now preserves Series name on Series(Series) init, and adds some (marginal) fast-paths if neither "schema" nor "schema_overrides" params are passed to the DataFrame constructor when initialising from either type (if these parameters _are_ passed, they are handled appropriately).
```python
df1 = pl.DataFrame( {"id": [0, 1], "misc": ["a", "b"], "val": [-10, 10]} )
df2 = pl.DataFrame( df1, schema=["a", "b", "c"], schema_overrides={"val": pl.Int8} )
s1 = pl.Series( "s", df2 )
s2 = pl.Series( s1 )
```
=> feat(python): improve Series/DataFrame init from existing Series/DataFrame objects

py-polars/polars/datatypes/classes.py, py-polars/polars/utils/various.py, py-polars/tests/unit/datatypes/test_enum.py
Split-out from #13345, and contains only the category-validation checks.
Prevents creation of invalid Enums (eg: with categories of the wrong type or duplicate values).
Category type check:
```python
pl.Enum([1.234, 5.678])
```
Category uniqueness check:
```python
pl.Enum(["misc", "value", "value", "other"])
```
=> feat(python): validate Enum categories

crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/tests/queries.rs, crates/polars-plan/src/dsl/mod.rs
=> fix(rust): use different generics for `shift_and_fill` parameters

py-polars/src/series/buffers.rs
We did not take into account the offset when constructing numeric buffers. While we define such buffers with an offset of 0, other libraries (e.g. pyarrow) do things differently and this can lead to issues when roundtripping chunked data.
=> fix(python): Fix offsets for numeric types in `from_buffer`

docs/src/python/user-guide/expressions/aggregation.py
Resolves #13418.
The "proper" age calculation looks pretty messy with the standard black formatter but the old formula, while simple, was incorrect.
Also, this points out that the imports used in the setup blocks of our code snippets aren't rendered in the documentation (note the word "import" isn't found anywhere in the [doc page](https://docs.pola.rs/user-guide/expressions/aggregation)). This caused me confusion when I first came to polars, as our code snippets used modules without any mention of importing them.
=> docs(python): show `datetime.date` import in code block

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_sql.py
Support SQL "IFNULL" (essentially equivalent to a two-argument "COALESCE").
```python
"x": [1, None, 3],
"y": [10, 20, 30],
})
pl.SQLContext(df=df).execute(
"""
SELECT
"x",
IFNULL("x", "y") as "c1",
IFNULL("x",-100) as "c2",
FROM df
""",
eager=True,
)
```
=> feat(rust,python,cli): add SQL engine support for `IFNULL` function

py-polars/polars/dataframe/group_by.py, py-polars/tests/unit/operations/test_group_by.py
fix #12869
As `temp_col` is added before the `.group_by` it's possible for column selectors to pick it up.
Use `.agg_groups()` instead to avoid the issue.
=> fix(python): Fix `group_by` iteration when grouping by certain selectors

py-polars/docs/source/reference/series/struct.rst
Method `Series.struct.json_encode` is now in the attributes section of autosummary and as a result, it's not rendered correctly.
=> docs(python): Move `Series.struct.json_encode` to methods in Sphinx autosummary

py-polars/polars/datatypes/classes.py, py-polars/src/conversion.rs, py-polars/tests/unit/datatypes/test_enum.py
This allows zero copy conversion between Python/Rust, which can be a big deal when the number of categories is large.
@alexander-beedie FYI as this touches the Enum validation you implemented recently.
=> perf(python): Represent `Enum` categories as Series

py-polars/polars/datatypes/classes.py, py-polars/tests/unit/datatypes/test_enum.py
`pl.Enum([])` would error on the dtype check - now it passes.
=> fix(python): Handle empty inputs to Enum constructor

py-polars/tests/unit/test_async.py
Closes #13297
Not 100% sure how these tests work but I expect this should dramatically reduce the spurious test failures.
=> test(python): Increase timeout for gevent async test

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_sql.py
Adds SQL support for "REPLACE" (equivalent to polars `replace_all` when "literal=True").
```python
df = pl.DataFrame({"txt": ["Yemeni coffee is the best coffee"]})
with pl.SQLContext(df=df) as ctx:
out = ctx.execute(
"""
SELECT *,
REPLACE(
REPLACE(txt, 'coffee', 'tea'),
'Yemeni',
'English breakfast'
) AS "updated"
FROM df
"""
).collect()
with pl.Config( fmt_str_lengths=50 ):
print(out)
```
=> feat(rust,python,cli): add SQL engine support for `REPLACE` string function

crates/polars-core/src/chunked_array/array/iterator.rs, crates/polars-ops/src/chunked_array/array/namespace.rs, crates/polars-plan/src/dsl/array.rs, crates/polars-plan/src/dsl/function_expr/array.rs, py-polars/docs/source/reference/expressions/array.rst, py-polars/docs/source/reference/series/array.rst, py-polars/polars/expr/array.py, py-polars/polars/series/array.py, py-polars/src/expr/array.rs, py-polars/tests/unit/namespaces/array/test_array.py, py-polars/tests/unit/namespaces/test_list.py, py-polars/tests/unit/series/test_series.py
Implements some missed ordering ops `sort`/`reverse`/`arg_min`/`arg_max`.
=> feat(rust,python): Impl ordering ops for array namespace

crates/polars-ops/src/chunked_array/strings/replace.rs, py-polars/tests/unit/namespaces/string/test_string.py
=> fix(rust): skip null/empty values if replace_lit_n_char

crates/polars-sql/Cargo.toml, crates/polars-sql/src/sql_expr.rs, crates/polars-sql/tests/statements.rs, py-polars/tests/unit/sql/test_sql.py
This is a fix for the issue described here https://github.com/pola-rs/polars/issues/11290
Hi @alexander-beedie, tbh I am not very happy with how I managed to organize it. I also had a  hard time thinking of the test cases, so I'd like to hear your recommendations!
=> #11290 add support for AND in SQL context

py-polars/polars/datatypes/classes.py, py-polars/src/conversion.rs, py-polars/tests/unit/datatypes/test_enum.py
This doesn't matter much, but the singular form is probably more correct than plural. We had similar issues in the past with "count" vs "counts".
=> fix(python): Rename Enum categories internal series to "category"

py-polars/polars/expr/expr.py, py-polars/polars/expr/whenthen.py, py-polars/polars/functions/aggregation/horizontal.py, py-polars/polars/functions/whenthen.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/utils/_parse_expr_input.py, py-polars/tests/unit/test_predicates.py
I am refactoring some of the input parsing that has gotten quite complex.
This has some performance benefits as I am skipping a second round of input checks in `all_horizontal` by going straight to Rust.
I still have to do `LazyFrame.filter` - it is more complicated for some reason.
=> perf(python): Refactor expression parsing logic of predicates/constraints

crates/polars-utils/src/wasm.rs
👋 First PR here.
With this, `streaming` and `ipc_streaming` features work on `wasm32-wasi`.
=> feat(rust): Implement wasm Pool::scope

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_strings.py
Add `CONCAT_WS`[^1] support to the SQL engine (aka: "concat with separator").
Interleaving a separator is common when concatenating; this function allows for a more lightweight syntax.
```python
"x": ["a", "b", "c", "d"],
"y": ["e", "f", "g", "h"],
"z": ["i", "j", "k", "l"],
})
pl.SQLContext(data=df).execute(
"""
SELECT
("x" || ':' || "y" || ':' || "z") AS c1,   -- concat operator
CONCAT("x", ':', "y", ':', "z")   AS c2,   -- basic concat function
CONCAT_WS(':', "x", "y", "z")     AS c3,   -- concat 'with separator' variant
FROM data
""",
eager=True,
)
```
[^1]: PostgreSQL docs: [concat_ws](https://www.postgresql.org/docs/current/functions-string.html#FUNCTIONS-STRING-OTHER)
=> feat(rust,python,cli): add SQL engine support for `CONCAT_WS` string function

crates/polars-parquet/src/arrow/write/binary/basic.rs
At first glance it looks like a reimplementation of `cmp`.
=> chore(rust): simplify parquet binary ordering function

py-polars/polars/utils/meta.py
A portion of #13161.
Questions:
- Should `polars.get_index_type` be included in doctest or skipped?
=> docs(python): Doc examples for `threadpool_size` and `get_index_type`

crates/polars-sql/Cargo.toml, crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_strings.py
Apparently when I committed this the first time I had forgotten that `concat_str` exists in Rust too...😅 Reworked the new `CONCAT` and `CONCAT_WS` functions to take advantage of the dedicated fast path.
=> perf(rust,python,cli): optimise SQL engine string concat

py-polars/tests/unit/io/test_delta.py, py-polars/tests/unit/namespaces/test_plot.py, py-polars/tests/unit/operations/test_join.py, py-polars/tests/unit/test_api.py, py-polars/tests/unit/test_async.py, py-polars/tests/unit/test_polars_import.py, py-polars/tests/unit/utils/test_utils.py
Closes #13297
I increased the import time restriction to 250ms as I saw a bunch of spurious failures at 205ms.
Plus a workaround for #13500 slowing down the test suite.
=> test(python): Fix some test failures/slowdowns

docs/user-guide/concepts/data-structures.md, docs/user-guide/expressions/window.md, py-polars/polars/dataframe/frame.py, py-polars/polars/io/json.py, py-polars/polars/io/ndjson.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/string.py
Changes include
- Typos, grammar, punctuation, formatting
- Erroneous "underlying data, the names given here will overwrite them." line was repeated in docstrings
- Fix some "smallest" / "largest" references in `top_k` / `bottom_k`
- References to a `LazyFrame` being a `DataFrame` and vice-versa
I did notice a few more references to a `LazyFrame` being a `DataFrame` and vice-versa (for example in `LazyFrame.join`), but will leave for another PR to keep the size manageable.
=> docs(python): Fix various typos, grammar and formatting in docstrings and user guide

docs/user-guide/expressions/plugins.md
I've added [skip-ci] not to use up CI unnecessarily, is that ok for such a small pr?
=> docs: update polars-business > polars-xdt link

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_numeric.py
Adds SQL support for `MOD`[^1] as a function, in addition to the existing support for the modulo `%` operator.
```python
"a": [1.5, None, 3.0, 10.0, 5.0],
"b": [6, 7, 8, 9, None],
})
with pl.SQLContext(df=df) as ctx:
out = ctx.execute(
"""
SELECT
a % 2 AS a_mod_2,
MOD(b,3) AS b_mod_3,
FROM df
"""
).collect()
```
[^1]: `MOD` function: https://www.postgresql.org/docs/current/functions-math.html#id-1.5.8.9.6.2.2.19.1.1.1
=> feat(rust,python,cli): add SQL engine support for `MOD` function

py-polars/polars/io/database.py
=> docs(python): add a note to the `read_database_uri` docstring about escaping special characters in the connection string

crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/scan/ipc.rs, crates/polars-lazy/src/scan/ndjson.rs, crates/polars-lazy/src/scan/parquet.rs, py-polars/polars/io/csv/functions.py, py-polars/polars/io/ipc/functions.py, py-polars/polars/io/parquet/functions.py
This will likely be faster in some cases. A rechunk can always be triggered when needed.
=> feat: don't rechunk by default in lazy scans

py-polars/polars/expr/datetime.py, py-polars/polars/series/datetime.py, py-polars/tests/unit/namespaces/test_datetime.py
Closes https://github.com/pola-rs/polars/issues/13505
We already have `dt.replace_time_zone(None)` which does exactly the same and is much more explicit.
=> depr(python): Deprecate `dt.datetime`

py-polars/polars/utils/udfs.py, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py
closes #13523
this regressed in https://github.com/pola-rs/polars/pull/13221 , sorry about that - but hey, increased test coverage now
=> fix(python): dont raise when partial function is passed to map_elements

py-polars/polars/functions/range/int_range.py, py-polars/tests/unit/functions/range/test_int_range.py
You can now write `pl.int_range(3)` to get a range from 0 to 3.
=> feat(python): Add compact syntax for `int_range` starting from 0

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_strings.py
Closes #12399.
Closes #9104.
A long-requested addition, implementing `LIKE` and `ILIKE` for the SQL interface (though this first cut does not yet support the optional follow-on `ESCAPE` clause).
Rewrites the given pattern as a regular expression match, appropriately escaping special characters and replacing `%` and `_` with `.*` and `.`, before dispatching the translated pattern to `str().contains`. Has a simple fast-path if the pattern contains no wildcard characters (and is not case insensitive).
```python
data = [
("Dubai", 3564931),
("Abu Dhabi", 1807000),
("Sharjah", 1405000),
("Al Ain", 846747),
("Ajman", 490035),
("Ras Al Khaimah", 191753),
("Fujairah", 118933),
("Umm Al Quwain", 59098), 
],
schema = {"City": pl.String, "Population": …
```
=> feat(rust,python,cli): add SQL engine support for `LIKE` and `ILIKE` pattern matching

README.md
Closes #13519.
We were showing the long-deprecated (and now defunct) `query` method instead of `execute`.
=> docs: update SQL section of the README

py-polars/polars/dataframe/frame.py, py-polars/polars/functions/lazy.py, py-polars/polars/functions/range/int_range.py, py-polars/polars/lazyframe/frame.py
Ref #12420
Added the same example to `count` and both `with_row_count` methods to improve discoverability of the usefulness of `pl.count`.
=> docs(python): Add more doc examples on how to create an index column

crates/polars-core/src/datatypes/any_value.rs
Fixes #12455 .
`AnyValue::Struct` and `AnyValue::StructOwned` had the same underlying hash impl which involved code to create an iterator over all of the `AnyValue` fields in `AnyValue::Struct` struct. However, this code only handled matching `AnyValue::Struct` and thus panicked when given an `AnyValue::StructOwned` value. Fixed by separating `AnyValue::StructOwned` to have its own hash impl separate from the more complex logic necessary for `AnyValue::Struct`.
=> fix(rust): `AnyValue::StructOwned` panic when hashing

py-polars/polars/convert.py, py-polars/polars/interchange/column.py, py-polars/polars/interchange/from_dataframe.py, py-polars/polars/interchange/utils.py, py-polars/tests/unit/interchange/test_buffer.py, py-polars/tests/unit/interchange/test_column.py, py-polars/tests/unit/interchange/test_from_dataframe.py, py-polars/tests/unit/interchange/test_roundtrip.py, py-polars/tests/unit/interchange/test_utils.py
Closes #10035 
* Implement `from_dataframe` natively rather than relying on the PyArrow implementation.
This means pyarrow is no longer a required dependency when using `from_dataframe`, and we no longer suffer any limitations of their implementation.
This implementation does everything the previous one did, with some additional benefits:
* (Some) categoricals can be converted zero-copy
* Supports time and duration types
* Better support for various sentinel values for constructing the validity buffer
* Better support for zero-copy in certain edge cases
This implementation has been tested extensively with regular unit tests (100% coverage) as well as a lot of parametric tests for testing integration with pyarrow and pandas. Oddities and bugs are handled and have been reported to the …
=> feat(python): Implement `from_dataframe` natively (interchange protocol)

py-polars/polars/utils/meta.py
It returns an instantiated type now.
=> chore(python): Narrow type hint for `get_index_type` util

py-polars/polars/interchange/column.py, py-polars/tests/unit/interchange/test_column.py, py-polars/tests/unit/interchange/test_roundtrip.py
I believe there is an issue with the way data buffer dtypes are represented across various implementations of the protocol (ours, pyarrow, pandas, ...). 
The issue is that the data buffer is assigned the column dtype. This is only correct for integers and floats. Categoricals, strings, and datetime types have a some integer as their physical representation. The data buffer should have this physical data type associated with it.
The fix in this PR is simple enough, but this cannot be merged until other libraries fix their `from_dataframe` implementation. I opened some issues:
When those libraries update their `from_dataframe` implementations per the issues above, the roundtrip tests should pass and this can be merged.
=> fix(python): Fix interchange protocol data buffer dtype

py-polars/polars/series/series.py
New branch to fix the issues with the previous PR I opened.
Adding more missing docstrings as discussed here: https://github.com/pola-rs/polars/issues/13161
=> docs(python): Adding additional examples to docstrings

py-polars/polars/series/series.py, py-polars/src/series/scatter.rs, py-polars/tests/unit/series/test_scatter.py
Ref #13547 (not a fix, just running into issues as I look into this)
=> fix(python): Fix `scatter` to allow single temporal inputs

.github/ISSUE_TEMPLATE/bug_report_python.yml, .github/ISSUE_TEMPLATE/bug_report_rust.yml
I'm not sure if this actually fixes the issue since the [preview in the main branch](https://github.com/pola-rs/polars/blob/main/.github/ISSUE_TEMPLATE/bug_report_python.yml) doesn't actually show the extra line break, but you can see it when you click on almost any issue.
I looked up the yaml specs and the [section on scalars](https://yaml.org/spec/1.2.2/#23-scalars) seems to indicate that using > where the next line has indented code causes a newline, so my hope is that this removes the extra newline. But I'm not really sure how to test this.
=> chore: Remove extra line break between checkboxes in GitHub bug report issues

Makefile
Before:
```
$ make build
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.8
🐍 Not using a specific python interpreter
Ignoring adbc_driver_sqlite: markers 'extra == "adbc"' don't match your environment
Ignoring cloudpickle: markers 'extra == "cloudpickle"' don't match your environment
Ignoring connectorx: markers 'extra == "connectorx"' don't match your environment
Ignoring deltalake: markers 'extra == "deltalake"' don't match your environment
Ignoring fsspec: markers 'extra == "fsspec"' don't match your environment
Ignoring gevent: markers 'extra == "gevent"' don't match your environment
Ignoring hvplot: markers 'extra == "plot"' don't match your environment
Ignoring matplotlib: markers 'extra == "matplotlib"' don't match your environment …
```
=> chore: Filter unhelpful messages in `make build`

crates/polars-core/src/chunked_array/ops/apply.rs, crates/polars-ops/src/chunked_array/strings/namespace.rs, crates/polars-plan/src/dsl/function_expr/strings.rs, crates/polars-plan/src/dsl/string.rs, py-polars/polars/expr/string.py, py-polars/polars/io/csv/functions.py, py-polars/polars/series/string.py, py-polars/src/expr/string.rs, py-polars/tests/unit/namespaces/string/test_string.py
Implements expressified `str.find` string functionality for `Expr` and `Series`, returning the index/position of a given pattern (regex or literal) in the underlying string. Returns ~~`-1`~~ _(updated)_ `None` if the pattern is not found.
(Also closes #13552 by adding a note about requiring a capture group in the given regex in the `extract` and `extract_groups` docstrings).
```python
data=[
("Dubai", 3564931, "b[ai]"),
("Abu Dhabi", 1807000, "b[ai]"),
("Sharjah", 1405000, "[ai]n"),
("Al Ain", 846747, "[ai]+n"),
("Ajman", 490035, "[ai]n"),
("Ras Al Khaimah", 191753, "a.+a"),
("Fujairah", 118933, "a.+a"),
("Umm Al Quwain", 59098, "a.+a"),
],
schema={"city": pl.String, "population": pl.Int32, "pattern": pl.String},
)
rx_a = …
```
=> feat(rust,python): add new `str.find` expression, returning the index of a regex pattern or literal substring

crates/polars-core/src/chunked_array/object/builder.rs, crates/polars-core/src/chunked_array/ops/any_value.rs, crates/polars-core/src/series/any_value.rs, py-polars/src/functions/lazy.rs, py-polars/src/series/construction.rs, py-polars/tests/unit/datatypes/test_object.py
This fixes #13538.
Alos fixes #13512.
=> fix: Treat Python `None` as null value for `Object` dtype

crates/polars-arrow/src/legacy/compute/decimal.rs, crates/polars-core/src/chunked_array/ops/decimal.rs, crates/polars-core/src/datatypes/any_value.rs
Closes #13546. Closes #13568.  Also fixes bug found in process of writing this, where, eg, "12.-2" is parsed as 11.98.  Checks precision and scale in what I believe is the correct way, and simplifies the code somewhat.  Removes comments that appeared to be either wrong or confusing.
Original description is below.
---
fix: Parse string without "." as decimal even with scale > 0.
Note, however, that I'm confused by some behavior of `deserialize_decimal`, and it seems like it might be worth changing it further while looking at it.  Given the way decimals are stored (in an i128), my assumption was that the scale would be, essentially, the multiplier ($10^{scale}$), while the precision would be the maximum total number of digits.  A comment states that the function doesn't check precision or …
=> fix(rust,python): Fix precision/scale handling and invalid numbers in string-to-decimal conversions.

py-polars/polars/dataframe/frame.py
Use different numbers and names within examples so you can tell things apart.
Use the same numbers and names across examples so the resemblance is easier to see.
---
This was prompted by [this Stack Overflow question](https://stackoverflow.com/q/77790639/4518341 "How to do transpose in Polars").
=> docs(python): Clarify examples for .transpose()

py-polars/polars/functions/lazy.py, py-polars/polars/selectors.py, py-polars/polars/utils/__init__.py, py-polars/polars/utils/deprecation.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/functions/test_functions.py, py-polars/tests/unit/test_lazy.py
All of the following `pl.<function>` entries have been extended with support for multiple column names (and remain backwards compatible with existing single-column calling syntax, so there is no breakage):
* `approx_n_unique`,
* `count`
* `first`
* `implode`
* `last`
* `mean`
* `median`
* `n_unique`
In addition, all functions in the updated module (and vertical aggregations) can now take bare `pl.col("name")` expressions as well as `"name"` strings, bringing them a little closer to more generic functions such as `pl.all_horizontal`.
Added new docstring examples for each, and extended test coverage accordingly.
```python
"a": [1, 2, None],
"b": [9, 8, 7],
"c": ["foo", "bar", "foo"],
})
df.select( pl.count("a", "b") )
```
Before:
```
TypeError: …
```
=> feat(python): additional multi-column support for `pl.<function>` entries

crates/polars-core/src/chunked_array/ops/chunkops.rs, crates/polars-ops/src/chunked_array/scatter.rs, py-polars/tests/unit/series/test_scatter.py
=> fix: Fix `scatter` for null values

crates/polars-arrow/src/array/static_array_collect.rs, crates/polars-arrow/src/bitmap/immutable.rs, crates/polars-arrow/src/bitmap/mutable.rs, crates/polars-arrow/src/ffi/array.rs, py-polars/tests/unit/operations/test_slice.py
In the future we can possibly extend this logic to the `ChunkedArray` as well, with potential intermediate representations that indicate "not all valid" without having to do a full count.
Basically the idea is to eventually have `all_valid_hint() -> bool` and `full_null_hint() -> bool` that when they return `true` are correct, but when they return `false` might be a false negative. This allows us to be more efficient than when writing
`if ca.null_count() == 0 { fast_path }` which has to compute a full null count just to check if we might want to do a fast path.
Either way, for now this PR already means slices on arrays can be done without triggering a forced full nullcount.
=> perf: do not eagerly compute bitcount

crates/polars-sql/src/functions.rs, crates/polars-sql/src/sql_expr.rs, py-polars/docs/source/reference/expressions/string.rst, py-polars/tests/unit/sql/test_strings.py
Building on `str.find` (and adding its missing API docs entry!), this PR adds SQL support for the `POSITION` and `STRPOS`[^1] functions.
```python
df = pl.DataFrame({"txt": ["AbCdEXz", "XyzFDkE"]})
with pl.SQLContext(txt=df) as ctx:
print(ctx.execute(
"""
SELECT
txt,
POSITION('C' IN txt) AS find_C,
POSITION('E' IN txt) AS find_E,
STRPOS(txt,'D') AS find_D,
STRPOS(txt,'X') AS find_X
FROM txt
"""
).collect())
```
[^1]: https://www.postgresql.org/docs/current/functions-string.html#FUNCTIONS-STRING-SQL
=> feat(rust,python,cli): add SQL engine support for `POSITION` and `STRPOS`

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/dataframe/test_describe.py
Supersedes #12336
Credit to @chrstfer for signalling this issue.
=> fix(python): Fix formatting in `describe` for precise quantiles

.github/release-drafter-python.yml, .github/release-drafter-rust.yml
I think it's useful to have these in the changelog separately.
=> chore: Add `Documentation` / `Build system` sections to the changelog

crates/polars-lazy/src/frame/mod.rs
The `JoinArgs` fields `validation`, `join_nulls` and `suffix` were not considered before.
The builder currently has no option for the `slice` parameter, so I didn't add it, but wrote a comment.
=> fix(rust): `LazyFrame::join()` no longer ignores 3 `JoinArgs` parameters

crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs, py-polars/tests/unit/operations/test_cast.py
This fixes #13588.
To be safe, it's best to keep the fallback mechanism and gradually align inline_cast and cast kernels.
I'll implement the string/binary type AnyValue to numeric type conversion later.
=> fix: fallback to cast kernel if `inline_cast` AnyValue raise

py-polars/polars/dataframe/frame.py, py-polars/polars/functions/lazy.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/selectors.py, py-polars/polars/utils/deprecation.py, py-polars/tests/unit/operations/test_drop.py
Closes #11746
This also deprecates keyword input, e.g.: `df.drop(columns="x")`
Technically we can do this without the deprecation (see the first commit), but I like simplifying the function signature (commit 2). Feedback is welcome.
=> feat(python): Allow drop with no inputs as a no-op

crates/polars-sql/src/functions.rs, crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_temporal.py
The SQL string functions have had some love recently, but the temporal functions could do with some more attention; this PR adds support for the key `EXTRACT` and `DATE_PART` funcs (which are equivalent to each other, with just a minor difference in syntax):
* `EXTRACT(year FROM date_col)`
* `DATE_PART(date_col,'year')`
First cut supports most of the major parts; I don't think people will be knocking down the door for "century", but it can always be added later 😅 
* "day" 
* "dayofweek" | "dow"
* "dayofyear" | "doy"
* "decade"
* "epoch" 
* "hour" 
* "isodow"
* "isoweek" | "week" 
* "isoyear"
* "microsecond(s)"
* "millisecond(s)"
* "nanosecond(s)"
* "minute" 
* "month" 
* "quarter" 
* "second"
* "time"
* "year" 
Validated the unit test results against a PostgreSQL instance.
```python …
```
=> feat(rust,python,cli): add SQL engine support for `EXTRACT` and `DATE_PART`

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_cast.py
Adds support for `<jsonstr>::json` and `CAST(<jsonstr> AS JSON)` syntax.
```python
"txt":['{"a":[1,2,3], "b":["x","y","z"], "c":5.0}']
})
with pl.SQLContext(df=df, eager_execution=True) as ctx:
res = ctx.execute("SELECT txt::json AS jsn FROM df")
res.unnest("jsn")
```
=> feat(rust,python,cli): add SQL engine support for string cast to `json`

crates/polars-arrow/src/datatypes/field.rs, crates/polars-arrow/src/datatypes/mod.rs, crates/polars-io/src/parquet/read_impl.rs, crates/polars-parquet/src/arrow/read/deserialize/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/simple.rs, crates/polars-parquet/src/arrow/read/deserialize/utils.rs, crates/polars-parquet/src/arrow/read/schema/convert.rs, crates/polars-parquet/src/arrow/read/schema/metadata.rs
Ensure that the parquet types always get converted to polars supported data-types. Before this, deeply nested datatypes were still of the wrong type, leading to unneeded casts.
All code increase is due to formatting longer lines.
supersedes #12762
=>  perf: elide all possible casts in parquet reading

py-polars/polars/series/series.py
Would close #13166, if this is found to be a valid issue.
=> feat(python): typing overloads for Series operator methods `ge, gt, ...`

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/polars/utils/various.py, py-polars/tests/unit/series/test_equals.py
* Make `Series.eq_missing` and `ne_missing` return an expression when the input is an expression. This is consistent with `eq` and `ne` and other comparisons.
* Fix some type hints
* Rename a util (remove the 'private' marker)
=> fix(python): `Series.eq_missing` should return an Expr when the input is an Expr

py-polars/polars/expr/whenthen.py, py-polars/polars/functions/whenthen.py
Ref https://github.com/pola-rs/polars/issues/13611
String inputs being parsed as literals for `when`, `then` and `otherwise` was removed in the last breaking release. This PR updates the docstrings for `then` and `otherwise` to note this. Updated wording is consistent with other existing docstrings.
Also has very minor updates in `when` docstrings with:
- `colname = value` -> `col_name = value`
- `when, thens` -> when-then operations ~`when, then`s~
=> docs(python): Update `then` and `otherwise` docstrings with "strings are parsed as column names"

py-polars/polars/lazyframe/frame.py
In https://github.com/pola-rs/polars/pull/11644 the docstrings for `sink` methods were updated from 
> Persists a LazyFrame at the provided path.
to 
> Evaluate the query in streaming mode and write to a {format} file.
Also, all other sink methods have the `slice_pushdown` parameter second last and the `no_optimization` parameter last.
This brings `sink_ndjson` in line with both of those.
PS: sorry for the tiny PR - hopefully not too spammy
=> docs(python): bring sink_ndjson docstring in line with other sink docstrings

crates/polars-io/src/ndjson/buffer.rs, crates/polars-io/src/ndjson/core.rs, crates/polars-json/src/json/infer_schema.rs, crates/polars-lazy/src/physical_plan/executors/scan/ndjson.rs, crates/polars-lazy/src/scan/ndjson.rs, py-polars/polars/io/ndjson.py, py-polars/polars/lazyframe/frame.py, py-polars/src/lazyframe/mod.rs
fixes #8279
Also added `ignore_errors` kwarg in `scan_ndjson` as driveby.
=> fix: fix schema inference for json

docs/_build/scripts/macro.py
minor fix to ensure that the links work again when a user clicks the 'Available on feature xxxx'. this currently gives a 404 as the URL doesn't exist.
for example here: 
https://docs.pola.rs/user-guide/io/bigquery/
=> docs: fix linking to feature flags in user guide

crates/polars-time/src/windows/group_by.rs
Due to a bug in a check we didn't parallelize the grouping of `rolling`. This fixes that. It also improves the fallback on duplicates, by not immediately going to single threaded, but by pruning partitions that are invalid.
Partial fix for #13654
=> perf: ensure time groups are parallelized

crates/polars-lazy/src/physical_plan/executors/projection_utils.rs, crates/polars-time/src/windows/group_by.rs
Ensure that the grouping logic will determine its parallelism based on the work in the queue.
Closes #13654
=> perf: elide parallelism restriction on generic rolling expressions

py-polars/polars/expr/expr.py
This closes #13612.
Any ideas about this are welcome :).
=> docs(python): Clarify documentation for the `agg_list` argument in `Expr.map_batches`

.github/workflows/test-bytecode-parser.yml
The other Python versions are tested as part of the regular Python test suite.
=> ci(python): Only run bytecode parser CI workflow for Python 3.9/3.10

py-polars/polars/expr/datetime.py, py-polars/polars/series/datetime.py
=> docs(python): document %A and %B to get day name and month name

py-polars/tests/unit/dataframe/test_describe.py
=> test(python): Add test for `describe` on Object types

crates/polars-sql/src/table_functions.rs, crates/polars-sql/tests/empty_table_function.rs
closes https://github.com/pola-rs/polars-cli/issues/51
=> fix(rust, sql): error instead of panicking in sql if empty function

py-polars/polars/expr/string.py, py-polars/polars/series/string.py
I found the following sentence in the docstring to (primarily in the case of `strip_chars`) make it sound like characters anywhere in the string can be stripped, rather than just leading/trailing.
> All combinations of this set of characters will be stripped. If set to None (default), all whitespace is removed instead.
With `strip_chars` I missed the "Remove leading and trailing characters." sentence that provides all the additional context.
This PR makes the behaviour of the methods more explicit throughout the docstring and removes wording that could pontentially be understood as conflicting.
=> docs(python): Be more explicit about behaviour in `str.strip_chars` / `strip_chars_start` / `strip_chars_end` docstrings

crates/polars-io/src/csv/write.rs, crates/polars-io/src/json/mod.rs, crates/polars-io/src/ndjson/core.rs, crates/polars-lazy/src/physical_plan/executors/scan/ndjson.rs, crates/polars-lazy/src/scan/ndjson.rs, crates/polars-plan/src/logical_plan/options.rs, crates/polars/tests/it/io/json.rs, py-polars/src/dataframe.rs, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/io/test_lazy_json.py, py-polars/tests/unit/streaming/test_streaming_io.py
Supersedes #12088 - credit to @gwik for signalling this issue!
Fixes a hang when `batch_size=0` for affected functions.
=> fix: Use `NonZeroUsize` for `batch_size` parameter in `write_csv/sink_csv/scan_ndjson`

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/operations/test_statistics.py
I also took the liberty of adding rowvar=False in np.corrcoef(), to avoid having to transpose the array before correlating.
Before:
```python
>>> pl.DataFrame([1, 2, 3]).corr()
File "polars/dataframe/frame.py", line 10223, in corr
return DataFrame(np.corrcoef(self.to_numpy().T, **kwargs), schema=self.columns)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "polars/dataframe/frame.py", line 430, in __init__
raise TypeError(msg)
TypeError: DataFrame constructor called with unsupported type 'float64' for the `data` parameter
```
After:
```python
>>> pl.DataFrame([1, 2, 3]).corr()
shape: (1, 1)
┌──────────┐
│ column_0 │
│ ---      │
│ f64      │
╞══════════╡
│ 1.0      │
└──────────┘
```
=> fix(python): support corr() for single-column DataFrames

py-polars/polars/utils/_construction.py, py-polars/tests/unit/interop/test_interop.py
Before:
```python
>>> pl.DataFrame(np.array(1))
File "polars/py-polars/polars/dataframe/frame.py", line 394, in __init__
self._df = numpy_to_pydf(
^^^^^^^^^^^^^^
File "polars/py-polars/polars/utils/_construction.py", line 1451, in numpy_to_pydf
raise ValueError(msg)
ValueError: cannot create DataFrame from array with more than two dimensions; shape = ()
```
After:
```python
>>> pl.DataFrame(np.array(1))
File "polars/py-polars/polars/dataframe/frame.py", line 394, in __init__
self._df = numpy_to_pydf(
^^^^^^^^^^^^^^
File "polars/py-polars/polars/utils/_construction.py", line 1454, in numpy_to_pydf
raise ValueError(msg)
ValueError: cannot create …
```
=> fix(python): fix error message when creating DataFrame from 0-dimensional NumPy array

py-polars/polars/expr/datetime.py, py-polars/polars/series/datetime.py, py-polars/tests/unit/datatypes/test_temporal.py
=> depr: Deprecate `dt.with_time_unit` in favor of `cast(pl.Int64).cast(pl.Datetime(time_unit, time_zone))`

py-polars/polars/selectors.py, py-polars/tests/unit/test_selectors.py
Closes https://github.com/pola-rs/polars/issues/10855
Currently the selectors are being created with an unpacked list `F.col(*all_names)`, but since `F.col` can manage iterables, by not unpacking we allow selecting nothing by inputing an empty list.
```python
cols_to_process = [] # This could come from an input file
df = pl.DataFrame({"a": [1,2,3]}) 
df_processed = df.with_columns(cs.by_name(cols_to_process) * 2)
```
Fixing this in my opinion gives more consistency on how some functions work: `with_columns` also works with empty lists for example.
=> fix(python): selectors by_name and by_dtype should allow empty list as input

crates/polars-arrow/src/array/binary/ffi.rs, crates/polars-arrow/src/array/binview/ffi.rs, crates/polars-arrow/src/array/binview/mod.rs, crates/polars-arrow/src/array/fixed_size_binary/ffi.rs, crates/polars-arrow/src/array/list/ffi.rs, crates/polars-arrow/src/array/map/ffi.rs, crates/polars-arrow/src/array/primitive/ffi.rs, crates/polars-arrow/src/array/union/ffi.rs, crates/polars-arrow/src/array/utf8/ffi.rs, crates/polars-arrow/src/buffer/immutable.rs, crates/polars-arrow/src/legacy/conversion.rs
This should avoid an extra indirection in thing such as `value_unchecked`.
=> perf: directly embed data ptr in Buffer

crates/polars-arrow/src/legacy/compute/arithmetics/decimal/commutative.rs, py-polars/polars/series/series.py, py-polars/tests/unit/datatypes/test_decimal.py
Currently, while arithmetic between two Series with Decimal dtype is possible, the conversion for Python Decimals  and its isn't implemented within _arithmetic to allow them to be used for Series/number arithmetic.  This PR implements conversion to allow things like
```python
pl.Series([D("1.2"), D("2.35")]) * D(4.3)
pl.Series([D("1.2"), D("2.35")]) * 43 / 10
```
Note that this does not work normally with DataFrames yet, as `pl.lit` is not implemented for decimals (eg, #13341).
In the process of writing tests for this, found an unnecessary panic, so closes #13651.
The code here uses scale inference for the PyDecimal (or, for ints, just 0), then casts to the max of the Series' scale and the PyDecimal scale.  This has the effect at the …
=> feat(python) Support arithmetic between Decimal Series and Python Decimal or int.

py-polars/polars/io/spreadsheet/functions.py
Closes #13718.
Small (three line 😅) update to run the path passed to `read_excel` through the same utility function as `read_csv` (for paths that begin with the "http" prefix).
```python
remote_file = "https://atb-archive.nrel.gov/electricity/2020/files/2020-ATB-Data.xlsm"
pl.read_excel(remote_file, sheet_name="LCOE Range")
```
=> feat(python): allow `read_excel` to load from remote http locations

py-polars/polars/expr/expr.py
Added a note about `null` being considered a distinct value in its own right for the purposes of `n_unique`, and extended the examples a little to better illustrate the functionality.
=> docs(python): improve `n_unique` and `approx_n_unique` docs

crates/polars-core/src/chunked_array/temporal/mod.rs, crates/polars-core/src/series/from.rs, py-polars/tests/unit/interop/test_interop.py
closes #12893
demo with the example reported in the issue:
```python
tz = dt.timezone(dt.timedelta(hours=10))
df = pd.DataFrame.from_records(
data=[(dt.datetime(2024, 1, 1, tzinfo=tz),)], columns=("naughty_date",)
)
print(df)
df.to_parquet("naughty.parquet")
print(pl.read_parquet("naughty.parquet"))
tz = dt.timezone(dt.timedelta(hours=-10))
df = pd.DataFrame.from_records(
data=[(dt.datetime(2024, 1, 1, tzinfo=tz),)], columns=("naughty_date",)
)
print(df)
df.to_parquet("naughty.parquet")
print(pl.read_parquet("naughty.parquet"))
```
```
naughty_date
0 2024-01-01 00:00:00+10:00
shape: (1, 1)
┌──────────────────────────┐
│ naughty_date             │
│ ---                      │
│ datetime[ns, Etc/GMT-10] │
╞══════════════════════════╡
│ 2024-01-01 00:00:00 +10  │
└──────────────────────────┘ …
```
=> feat: convert fixed-offset timezones to respective Etc timezone from time zone database

crates/polars-plan/src/dsl/function_expr/datetime.rs, crates/polars-plan/src/dsl/function_expr/temporal.rs, crates/polars-plan/src/dsl/functions/mod.rs, crates/polars-plan/src/dsl/functions/temporal.rs, py-polars/tests/unit/dataframe/test_from_dict.py, py-polars/tests/unit/functions/as_datatype/test_duration.py, py-polars/tests/unit/io/test_pickle.py
=> refactor: Make `pl.duration` non-anonymous

crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/tests/projection_queries.rs, crates/polars-plan/src/logical_plan/builder.rs, crates/polars-sql/src/context.rs, crates/polars/tests/it/lazy/queries.rs, py-polars/src/lazyframe/mod.rs
Ref #13745
To align with the public API on the Python side.
=> feat(rust!): Rename `drop_columns` to `drop`

crates/polars-lazy/src/physical_plan/planner/expr.rs, crates/polars-plan/src/logical_plan/aexpr/schema.rs, py-polars/tests/unit/operations/test_join.py
=> fix: Raise error instead of panic when joining on wildcard/nth

py-polars/polars/expr/string.py, py-polars/polars/series/string.py, py-polars/tests/unit/namespaces/string/test_concat.py, py-polars/tests/unit/namespaces/string/test_string.py
The default should be changed to an empty string. Here's the deprecation.
=> depr(python): Deprecate default delimiter value for `str.concat`

py-polars/polars/datatypes/convert.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_arithmetic.py
Adds test coverage for operator arithmetic against `None` (and tests the associated named methods). Discovered that `Series` was inconsistently raising an error where the same ops on `Expr` and `DataFrame` succeeded.
**Note:**
This may be an implicit regression of some kind (from the `0.19.x` series) as it was found via unit testing while trying to upgrade our work codebase to `0.20.x` 🤔 
All of the following formulations work consistently...
```python
df = pl.DataFrame({"n": [2, 3]})
df.select( pl.col("n") * pl.lit(None) )
df.select( pl.col("n") * None )
df * pl.Series([None])
df * None
df["n"] * pl.Series([None])
```
... _only_ this variant failed:
```python
df["n"] * None
```
I've fixed this and added the missing test coverage.
=> fix(python): validate operator arithmetic with `None`, fix `Series` edge-case

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py
Tagging @MarcoGorelli who added the super nice plotting functionality.
I noticed that I didn't get type hinting on the `df.plot` namespace, so decided to add it here. Were there any particular reasons you didn't do so?
Note that since we `from __future__ import annotations`, the return type won't raise a runtime this (without strings) despite hvplot possibly not being installed.
=> feat(python): Add typing to hvplot plot namespace

crates/polars-ops/src/series/ops/cut.rs, py-polars/tests/unit/operations/test_qcut.py
Fixes https://github.com/pola-rs/polars/issues/13707.
Probably not the best way to handle this with regards to labelling, but since `qcut` is getting reworked anyway, this will do now.
=> fix: don't panic on full null qcut

crates/polars-ops/src/series/ops/int_range.rs, crates/polars-ops/src/series/ops/mod.rs, crates/polars-plan/src/dsl/function_expr/range/int_range.rs, py-polars/polars/functions/range/int_range.py, py-polars/src/functions/eager.rs, py-polars/src/lib.rs
We probably want something more robust for eager expressions in general, but this should at least resolve https://github.com/pola-rs/polars/issues/13796.
=> perf: fast-path for eager int_range

py-polars/src/expr/general.rs, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/namespaces/test_list.py
=> fix: `gather_every` should work on agg context

crates/polars-arrow/src/array/binview/ffi.rs, crates/polars-arrow/src/array/binview/mod.rs
=> perf: lazy cache binview bytes len

crates/polars-ops/src/series/ops/abs.rs, py-polars/tests/unit/expr/test_exprs.py, py-polars/tests/unit/functions/test_functions.py, py-polars/tests/unit/operations/test_abs.py, py-polars/tests/unit/series/test_series.py
I noticed `abs` just operated on the physical type, but that makes no sense for dates, e.g. `date(1960, 1, 1)` gets changed to `date(1980, 1, 1)`. Now it properly raises an error.
=> fix: Implement `abs` for Decimal, error on Date/Time/Datetime

crates/polars-sql/Cargo.toml, crates/polars-sql/src/sql_expr.rs, crates/polars/Cargo.toml, py-polars/tests/unit/sql/test_numeric.py
Assuming decimal support is activated, adds SQL syntax/parsing for:
```sql
colx::numeric,       colx::decimal,        colx::dec
colx::numeric(10),   colx::decimal(10),    colx::dec(10)
colx::numeric(10,5), colx::decimal(10,5),  colx::dec(10,5)
```
Note that `decimal` is simply an alias for `numeric` in PostgreSQL[^1]; they are the exact same type.
Also adds type-recognition of additional PostgreSQL integer aliases:
* `int8` (8 byte) → `Int64` 
* `int4` (4 byte )→ `Int32`
* `int2` (2 byte) → `Int16`
[^1]: PostgreSQL [numeric types](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-NUMERIC-TABLE/)
=> feat(rust,python,cli): add SQL support for `numeric` and/or `decimal` types

crates/polars-arrow/src/array/binview/mod.rs
We were applying the GC in cases where it wasn't appropriate (mainly many short strings).
=> perf: apply string view GC more conservatively

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/test_lazy.py
Closes https://github.com/pola-rs/polars/issues/13229.
There seemed to be a lot of popular demand for this (based on the number of likes on the original issue), so I went ahead and implemented it.
=> feat(python): allow df.rename and lf.rename to take a renaming function

py-polars/docs/source/reference/api.rst
Thanks for developing such an amazing library! Just fixing argument names to ones for polars rather than ones for pandas. The original code blocks did work by just copy-and-pasting but now they should.
=> docs(python): use proper argument names in the code blocks of api.rst

py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/functions/aggregation/test_horizontal.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/test_predicates.py
Closes #13861.
Frame-level `filter` was behaving inconsistently with `expr.filter` and with its own docstring. Should have been using `eq` instead of `eq_missing` when accumulating filters from kwargs.
Fixed, also extending test coverage to validate generation of a suitable `UserWarning` on use of `eq` with "None", and to confirm that the query plan doesn't contain a reference to `eq_missing`.
=> fix(python): ensure kwargs `filter` behaviour matches docstring (expect equivalence with `eq`)

crates/polars-core/src/chunked_array/ops/fill_null.rs, py-polars/tests/unit/functions/aggregation/test_horizontal.py, py-polars/tests/unit/series/test_series.py
=> feat(rust, python): Support zero fill null strategy for binary and string columns

Cargo.lock, Cargo.toml
This version of object_store seems to have slightly more robust retry logic, which might help resolve some transient failures when scanning numerous objects from the cloud. See https://github.com/apache/arrow-rs/pull/5278 for more details.
=> chore(rust): bump object_store to 0.9

crates/polars-core/src/chunked_array/builder/list/mod.rs, py-polars/tests/unit/datatypes/test_list.py
=> fix(rust, python): allow list creation of decimals

crates/polars-arrow/src/array/binview/mod.rs, crates/polars-arrow/src/array/binview/mutable.rs, crates/polars-arrow/src/array/binview/view.rs, crates/polars-core/src/fmt.rs, crates/polars-io/src/parquet/read_impl.rs, crates/polars-parquet/src/arrow/read/deserialize/mod.rs
as feature as  we didn't release this yet.
=> feat: fix parquet for binview

py-polars/polars/functions/range/int_range.py, py-polars/tests/unit/functions/range/test_int_range.py
Closes https://github.com/pola-rs/polars/issues/13787
PS: I see that arange is an alias for int_range, should we unify signatures? This will lead to a breaking change though
=> feat(python): Align `int_range` and `int_ranges` signatures

crates/polars-lazy/src/tests/projection_queries.rs, crates/polars-ops/src/chunked_array/strings/concat.rs, crates/polars-plan/src/dsl/function_expr/strings.rs, crates/polars-plan/src/dsl/functions/concat.rs, crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs, crates/polars-plan/src/logical_plan/optimizer/simplify_functions.rs, crates/polars-sql/src/functions.rs, docs/src/rust/user-guide/expressions/folds.rs, py-polars/polars/functions/as_datatype.py, py-polars/src/functions/lazy.rs, py-polars/tests/unit/functions/as_datatype/test_as_datatype.py, py-polars/tests/unit/functions/as_datatype/test_concat_str.py, py-polars/tests/unit/functions/test_concat.py, py-polars/tests/unit/sql/test_strings.py
I set the default value of `ignore_nulls` to `False` so that we can keep the same behavior as before. We could change it to `True` in the breaking release then.
=> feat: Add `ignore_nulls` for `pl.concat_str`

py-polars/src/dataframe.rs
Resolves #13844
Not sure if covered every one, or if additional tests are needed. Also not all write cases are covered i think, but i didn't want to go out of scope on this issue.
=> perf(python): allow python threads in read_ functions

crates/polars-pipe/src/executors/sinks/memory.rs
=> fix(rust): don't return NaN as free memory fraction

crates/polars-core/src/chunked_array/ops/rolling_window.rs, crates/polars/tests/it/core/rolling_window.rs, py-polars/tests/unit/operations/rolling/test_map.py
=> fix(rust, python): include null count in rolling window validity with `min_periods`

crates/polars-plan/src/dsl/mod.rs, py-polars/tests/unit/operations/test_slice.py
=> feat: register 'set_sorted' as batch/elementwise

crates/polars-core/src/frame/mod.rs, py-polars/tests/unit/functions/aggregation/test_horizontal.py
Fixes #13113 
- Null columns are treated as additive identity in the presence of non-null columns. They can be skipped in the computation
- If all columns are Null, return Null
I have also changed the behaviour of single columns sums. This seems more consistent to multi-column sums. Example:
```python
{
"A": [5, None, 3, None],
"B": [5, 3, None, None],
}
)
```
As reference, when summing multiple columns
`sum_horizontal("A", "B") = [10, 3, 3, 0]`
Before
`sum_horizontal("A") = [5, None, 3, None]`
After
`sum_horizontal("A") = [5, 0, 3, 0]`
=> fix(rust, python): treat null columns as zero in `sum_horizontal`

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/io/test_hive.py
As this wasn't deprecated after all, the warning filters added in #13467 can be removed again.
Also skipping the pyarrow tests for now.
=> refactor(python): Revert pandas warning filter

crates/polars-ops/src/chunked_array/array/join.rs, crates/polars-ops/src/chunked_array/array/namespace.rs, crates/polars-plan/src/dsl/array.rs, crates/polars-plan/src/dsl/function_expr/array.rs, py-polars/polars/expr/array.py, py-polars/polars/expr/list.py, py-polars/polars/series/array.py, py-polars/polars/series/list.py, py-polars/src/expr/array.rs, py-polars/tests/unit/namespaces/array/test_array.py
This will change the behavior of handing null values. But as the same reasons as `list.join` and `str.concat`, we think of it as fixing rather than breaking change.
This closes #13633.
=> feat: Add `ignore_nulls` for `arr.join`

crates/polars-plan/src/logical_plan/aexpr/schema.rs, py-polars/tests/unit/streaming/test_streaming_group_by.py
Closes https://github.com/pola-rs/polars/issues/7651 based on the implementation suggested by @advoet [here](https://github.com/pola-rs/polars/issues/7651#issuecomment-1491398261).
Before:
```python
pl.DataFrame({"a": [True, True, True, False, False]}).select(100 * pl.col("a").mean())
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ i32     │
╞═════════╡
│ 0       │
└─────────┘
```
After:
```python
>>> pl.DataFrame({"a": [True, True, True, False, False]}).select(100 * pl.col("a").mean())
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ f64     │
╞═════════╡
│ 60.0    │
└─────────┘
```
=> fix(rust): make 100 * pl.col(pl.Boolean).mean() work

py-polars/polars/dataframe/frame.py
This PR works on https://github.com/pola-rs/polars/issues/9368
Presorting columns makes describe much faster especially when the user inputs a lot of percentiles;
The presort will happen once, all quantiles/min/max on numerical columns will be O(1);
Here are some benchmarks on real sales data I am working on:
```
In [18]: df
Out[18]:
shape: (28_061_078, 10)
┌───────────────┬───────────────┬───────────────┬───┬──────────┬──────────┐
│ aaaaa_aaaa_aa ┆ bbbbb_bbbb_bb ┆ ccccc_cccc_cc ┆ … ┆ ddddd_ddd┆ eeee_eee │
│ ---           ┆ ---           ┆ ---           ┆   ┆ ---      ┆ ---      │
│ f64           ┆ f64           ┆ f64           ┆   ┆ f64      ┆ f64      │
╞═══════════════╪═══════════════╪═══════════════╪═══╪══════════╪══════════╡
│ null          ┆ null          ┆ 0.0           ┆ … ┆ 33.38 …
```
=> perf: optimize `DataFrame.describe` by presorting columns

crates/polars-core/src/series/implementations/struct_.rs, py-polars/tests/unit/operations/test_drop_nulls.py, py-polars/tests/unit/operations/test_is_null.py
Closes https://github.com/pola-rs/polars/issues/9443
A struct field is null if ALL fields are null.
A struct field is NOT null if ANY of its fields are NOT null.
A simple one-line fix, with a bunch of tests.
=> fix: Fix `is_not_null` for Struct columns

crates/polars-pipe/src/executors/sinks/output/file_sink.rs, crates/polars-pipe/src/executors/sinks/sort/source.rs, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-pipe/src/executors/sources/frame.rs, crates/polars-pipe/src/executors/sources/mod.rs, crates/polars-pipe/src/executors/sources/parquet.rs
=> fix: ensure order is preserved if streaming from different sources

crates/polars-pipe/src/pipeline/convert.rs, crates/polars-pipe/src/pipeline/dispatcher.rs
=> fix: recurse less in streaming shared sinks

Makefile
This should make sure that `make test` will not call pytest after `maturin develop` fails.
=> chore(python): Fix pip warning filter return code

docs/user-guide/ecosystem.md, mkdocs.yml
Related to this issue: #13778
This is an initial version. We can extend with more tools and maybe add code examples (this is an open question in #13778). I think this is a good start for now!
=> docs: Introduce ecosystem page in user guide

crates/polars-core/src/datatypes/dtype.rs, py-polars/tests/unit/datatypes/test_enum.py
=> fix(rust, python): Allow dtype merge when inner dtype is enum

crates/polars-sql/src/functions.rs, crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_numeric.py, py-polars/tests/unit/sql/test_strings.py
Builds on top of @reswqa's great work expressifying string `slice` (see #13747).
* Extends SQL `LEFT`, `RIGHT`, and `SUBSTR` SQL string functions with expression support.
* Adds support for negative length to both the `LEFT` and `RIGHT` functions.
* Adds supports for negative start and negative length for `SUBSTR`.
* Also fixes `ROUND` error checking for negative 'n_decimals' as a drive-by.
Getting this correct was a bit headache-inducing, as SQL has a different idea of what negative values mean here _and_ it's 1-indexed. 
For example, with`SUBSTR`:
* Starting at -10 _doesn't_ mean _"start 10 chars back from the end of the string"_, as you would likely expect; instead it really does mean _"start 10 chars back from the front"_. So, `SUBSTR(colt,-10,13)` and `SUBSTR(colx,1,2)` both return …
=> feat(rust,python,cli): support negative indexing and expressions for `LEFT`, `RIGHT` and `SUBSTR` SQL string funcs

crates/polars-sql/src/context.rs, crates/polars-sql/src/functions.rs, crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_numeric.py, py-polars/tests/unit/sql/test_regex.py, py-polars/tests/unit/sql/test_strings.py, py-polars/tests/unit/sql/test_temporal.py
Adds recognition of PostgreSQL compatible timestamp precision[^1] modifier.
Supports values that map to our `Datetime` time units, specifically `3 → 'ms'`, `6 → 'us'`, `9 → 'ns'`:
```python
"ts": [
datetime(2024, 1, 7, 1, 2, 3, 123456),
datetime(1999, 1, 1, 23, 59, 59, 555555),
datetime(2020, 12, 30, 10, 30, 45, 987654),
],
})
with pl.SQLContext(frame_data=df, eager_execution=True) as ctx:
print(ctx.execute(
f"SELECT ts::timestamp(3) FROM frame_data")
)
```
[^1]: https://www.postgresql.org/docs/current/datatype-datetime.html
=> feat(rust,python,cli): add SQL support for `timestamp` precision modifier

py-polars/tests/unit/streaming/__init__.py, py-polars/tests/unit/streaming/test_streaming.py, py-polars/tests/unit/streaming/test_streaming_categoricals.py, py-polars/tests/unit/streaming/test_streaming_cse.py, py-polars/tests/unit/streaming/test_streaming_group_by.py, py-polars/tests/unit/streaming/test_streaming_io.py, py-polars/tests/unit/streaming/test_streaming_join.py, py-polars/tests/unit/streaming/test_streaming_sort.py, py-polars/tests/unit/streaming/test_streaming_unique.py
Apparently using the mark in `__init__.py` was not supported.
=> test(python): Fix xdist streaming group

py-polars/src/conversion/chunked_array.rs, py-polars/src/conversion/mod.rs
This is preparing another PR. Figured I'd make a separate PR for the refactor to make the changes more clear in the next one.
=> refactor(python): Move PyO3 ChunkedArray conversion logic into its own module

py-polars/polars/dataframe/frame.py
It seems there was an arbitrary limit of 100 characters for the length of the string showing the column name and dtype in `glimpse()`. If you have long column names and pass a `max_colname_length` that is too long, you will get a formatting error because the format width specifier for the last line item becomes negative. Specifically, If you have a `df` with a column named `a = 'some_long_col_name_xxxxxxxxx...'`, then `df.glimpse(max_colname_length=b)` throws a formatting error for any `b > len(a) + len(f"<{_dtype_str_repr(df[a].dtype)}>")` (see below). This PR just removes the width specifier on the last line item which was redundant anyway.
```py
def test(max_colname_length):
df = pl.DataFrame({'a' * 100: [1, 2, 3]})
df.glimpse(max_colname_length=max_colname_length)
```
```py
test(95) …
```
=> fix(python): Fix `max_colname_length` formatting in `glimpse()`

crates/polars-plan/src/dsl/function_expr/array.rs, crates/polars-plan/src/dsl/function_expr/list.rs, py-polars/tests/unit/namespaces/array/test_array.py, py-polars/tests/unit/namespaces/array/test_contains.py, py-polars/tests/unit/namespaces/test_list.py
Almost all operations in `list/arr` namespace ensures the input type when unpack series. But `contains` is an exception due to the reuse of `is_in` ops. As a result, you can even call `arr.contains` on list series. 
IMO, we should raise for things like `ListSeries.arr.xxx` or `ArraySeries.list.xxx`. After all, they are not essentially the same type. In particular, you can't even convert a list to an array with unequal width.
=> fix: check input type for `arr/list.contains`

crates/polars-core/src/datatypes/_serde.rs, py-polars/tests/unit/test_serde.py
Adds decimal to serializable dtypes
- closes https://github.com/pola-rs/polars/issues/13991
=> fix(python,rust): serialize decimal type

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/tests/unit/interop/test_to_pandas.py
I was doing some minor docs cleanup and I ran into this inconsistency between `Series.to_pandas` and `DataFrame.to_pandas`.
I'm not 100% certain I like using the `datetime64[ms]` types for dates, but I guess it's more useful than an Object type. So let's align on the current DataFrame implementation.
I also removed the leading `*args` for both methods. These were unused.
=> fix(python): Use `date_as_object=False` as default for `Series.to_pandas` (just like `DataFrame.to_pandas`)

py-polars/polars/series/series.py, py-polars/polars/utils/_construction.py, py-polars/tests/unit/operations/test_rolling.py
LONG road ahead, but I'm taking baby steps as it's easy to inadvertently cause breaking changes with this stuff.
=> refactor(python): Constructor improvements - part 1

py-polars/docs/source/reference/dataframe/group_by.rst, py-polars/docs/source/reference/lazyframe/descriptive.rst, py-polars/docs/source/reference/lazyframe/group_by.rst
#13999 made me realize I had forgotten to add GroupBy.len too.
Also adding `LazyFrame.describe` which was added in #13982 (@alexander-beedie adding it here as to not pollute your other PR with unrelated stuff).
=> docs(python): Add missing doc entries

crates/polars-ops/src/series/ops/arg_min_max.rs, py-polars/tests/unit/series/test_series.py
=> fix(rust): `arg_min/max` on categoricals should respect ordering

py-polars/tests/unit/test_polars_import.py
This _may_ help further reduce noise... 🤔
See: https://docs.python.org/3/using/cmdline.html#cmdoption-S
=> fix(python): omit implicit 'site' from import-timing test

docs/user-guide/getting-started.md
The "Getting Started" section of the user guide has a minor typo. I've also rephrased the rest of the sentence it to make it a bit clearer (IMO).
=> fix(docs): Fixed typo and a minor rephrasing in the user guide

crates/polars-io/src/csv/parser.rs, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/test_cse.py
fixes #13933 and partly fix for #12763 
addresses a few issues of `read_csv` (adding issue links later)
Currently `read_csv` trims whitespace at the start of each line (only for the first value). This is a bug. Whitespace should be preserved as is belongs to the value. Also this only happens for the first value.
```python
DATA = """col
a
b
c
d"""
pl.read_csv(source=StringIO(DATA))
shape: (4, 1)
┌─────┐
│ col │
│ --- │
│ str │
╞═════╡
│ a   │
│ b   │
│ c   │
│ d   │
└─────┘
shape: (4, 1)
┌───────────┐
│ col       │
│ ---       │
│ str       │
╞═══════════╡
│ a         │
│     b     │
│         c │
│ d         │
└───────────┘
```
Currently `read_csv` removed empty lines if the csv has multiple columns and keeps empty lines as `null` for csv with a single column. All whitespace in csv files …
=> fix(python,rust): read_csv preserve whitespace and newlines

crates/polars-arrow/src/legacy/compute/decimal.rs, crates/polars-core/src/chunked_array/ops/decimal.rs
I think it's allowed in RDBMS and arrow-rs.
Also fix a edge case with positive signed number string.
=> allow casting string to decimal with insufficient scale 

crates/polars-ops/src/chunked_array/list/namespace.rs, py-polars/tests/unit/namespaces/test_list.py
=> fix(rust): allow get access to list of categoricals

crates/polars-ops/src/chunked_array/list/min_max.rs, py-polars/tests/unit/datatypes/test_list.py
=> fix: `list.min/max` with empty and/or None elements

crates/polars-core/src/frame/row/av_buffer.rs, crates/polars-core/src/series/any_value.rs, crates/polars-io/src/csv/write_impl.rs, crates/polars-ops/src/frame/pivot/positioning.rs, crates/polars-ops/src/series/ops/is_in.rs, crates/polars-pipe/src/executors/sinks/group_by/generic/hash_table.rs, crates/polars-plan/src/logical_plan/format.rs, crates/polars-plan/src/logical_plan/lit.rs, crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs, crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs, crates/polars-plan/src/logical_plan/pyarrow.rs, crates/polars-sql/src/sql_expr.rs, py-polars/polars/utils/__init__.py, py-polars/polars/utils/_construction.py, py-polars/polars/utils/convert.py, py-polars/src/conversion/any_value.rs, py-polars/src/conversion/chunked_array.rs, py-polars/src/conversion/mod.rs, py-polars/src/functions/lazy.rs, py-polars/src/map/series.rs, py-polars/src/on_startup.rs, py-polars/src/series/construction.rs, py-polars/tests/unit/operations/map/test_map_elements.py
`anyvalue` and `any_value` were used interchangably, e.g. Rust had `Series::from_any_values`, but in the PyO3 bindings it was called `Series::new_from_anyvalues`.
~Since the object is called `AnyValue` and "any value" could have a different meaning, let's settle on using `anyvalue` when referring to AnyValue functionality in function names/variables.~
We settled on using `any_value` everywhere.
Besides the change in the title, the same change was made in several internal functions/references.
=> refactor(rust!): Rename `LiteralValue::to_anyvalue` to `LiteralValue::to_any_value`

crates/polars-core/src/fmt.rs, py-polars/tests/unit/test_format.py
Resolves #14041.
```python
df = pl.DataFrame({"int_col" : [100, 1_000, 10_000, 100_000]})
df = df.with_columns(pl.col("int_col").cast(pl.UInt64).alias("uint_col"))
with pl.Config(thousands_separator=True):
print(df)
```
```
shape: (4, 2)
┌─────────┬──────────┐
│ int_col ┆ uint_col │
│ ---     ┆ ---      │
│ i64     ┆ u64      │
╞═════════╪══════════╡
│ 100     ┆ 100      │
│ 1,000   ┆ 1,000    │
│ 10,000  ┆ 10,000   │
│ 100,000 ┆ 100,000  │
└─────────┴──────────┘
```
=> fix: Use int formatter for unsigned ints

crates/polars-io/src/utils.rs, crates/polars/tests/it/io/csv.rs, py-polars/tests/unit/io/test_csv.py
fix schema inference using `read_csv` with leading whitespace
fix #10587 
fix #12763 
added tests.
```python
DATA = """bool,bool-,-bool,float,float-,-float,int,int-,-int
true,true , true,1.2,1.2 , 1.2,1,1 , 1
"""
pl.read_csv(
StringIO(DATA),
ignore_errors=True,
)
```
```
shape: (1, 9)
┌──────┬───────┬───────┬───────┬────────┬────────┬─────┬──────┬──────┐
│ bool ┆ bool- ┆ -bool ┆ float ┆ float- ┆ -float ┆ int ┆ int- ┆ -int │
│ ---  ┆ ---   ┆ ---   ┆ ---   ┆ ---    ┆ ---    ┆ --- ┆ ---  ┆ ---  │
│ bool ┆ str   ┆ bool  ┆ f64   ┆ str    ┆ f64    ┆ i64 ┆ str  ┆ i64  │
╞══════╪═══════╪═══════╪═══════╪════════╪════════╪═════╪══════╪══════╡
│ true ┆ true  ┆ null  ┆ 1.2   ┆ 1.2    ┆ 1.2    ┆ 1   ┆ 1    ┆ 1    │
└──────┴───────┴───────┴───────┴────────┴────────┴─────┴──────┴──────┘
```
Bugs:
- bug …
=> fix(python,rust): correct field type schema inference (using read_csv)

py-polars/polars/series/series.py, py-polars/tests/unit/interop/test_to_pandas.py
Closes #10977
We have to cast the `u32` values to `i64`.
=> fix(python): Allow `Series.to_pandas` for categorical types

crates/polars-time/src/series/mod.rs, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/namespaces/test_datetime.py
closes #13208
this could be done with a deprecation cycle, but is it really worth it? this could just be a breaking 1.0 change imho
=> fix: Raise for .dt.epoch and .dt.timestamp for Duration dtype

crates/polars-lazy/src/physical_plan/expressions/apply.rs, crates/polars-lazy/src/tests/io.rs
Fixes: [13427](https://github.com/pola-rs/polars/issues/13427)
Old code skipped row groups only if values passed to `is_in` are _ALL_ under min or _ALL_ above max. Imroved to skip if _ALL_ values are either under min or above max
=> perf: improve skip row group using statistics condition

py-polars/polars/config.py, py-polars/polars/expr/categorical.py, py-polars/polars/expr/expr.py, py-polars/polars/series/categorical.py, py-polars/polars/series/series.py
Docstring bullet points not rendering as expected  strike again
(and similarly for the others)
=> docs(python): fix more docstring bullet points

py-polars/polars/series/series.py
See comment:
https://github.com/pola-rs/polars/pull/13976#issuecomment-1914425400
=> docs(python): Improve deprecation message of `dtype_if_empty` param

py-polars/polars/expr/expr.py
xref https://github.com/pola-rs/polars/issues/14062
Landing on `Expr.__bool__` is so common, because `if expr:` triggers `expr.__bool__`, and people often have no idea why they're seeing this error message at all
I'd suggest making the error message a bit rustier
Here's what the err message looks like now
```ipython
TypeError: the truth value of an Expr is ambiguous
You probably got here by using a Python standard library function instead of the native expressions API.
Here are some things you might want to try:
- instead of `pl.col('a') and pl.col('b')`, use `pl.col('a') & pl.col('b')`
- instead of `pl.col('a') in [y, z]`, use `pl.col('a').is_in([y, z])`
- instead of `max(pl.col('a'), pl.col('b'))`, use `pl.max_horizontal(pl.col('a'), pl.col('b'))`
```
=> feat(python): raise more informative error message if someone lands on Expr.__bool__

crates/polars-core/src/chunked_array/temporal/datetime.rs
Following #13960, this method is no longer useful. Let's get rid of it. Use `set_time_zone` instead.
=> refactor(rust!): Remove `DatetimeChunked::convert_time_zone`

crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs, py-polars/tests/unit/test_cse.py
=> fix: fix cse bug when window function is nested

py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/group_by.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/utils/deprecation.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/datatypes/test_categorical.py, py-polars/tests/unit/operations/test_aggregations.py, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/test_schema.py
@stinodego Replacing [this](https://github.com/pola-rs/polars/pull/13415) one from a clean slate.
fixes https://github.com/pola-rs/polars/issues/11957
=> feat(python): Allow renaming expressions with keyword syntax in `group_by`

crates/polars-core/src/chunked_array/logical/datetime.rs, py-polars/tests/parametric/time_series/test_to_datetime.py, py-polars/tests/unit/test_queries.py
Rust's standard integer division truncates, so the effect is round towards zero, and this is the root cause of some temporal conversion gremlins when we scale negative `i64` values (eg: pre-epoch).
Sample data:
```python
s = pl.Series([-1, 0, 1]).cast(pl.Datetime("us"))
```
Extracting the date (or casting to date):
```python
s.dt.date()
```
Downcasting timeunits (eg: `us` → `ms`):
```python
s.cast(pl.Datetime("ms"))
```
Extracting the time (or casting to time):
```python
s.dt.time()
```
* Downcasting (datetime to date, or from higher to lower precision) can be fixed by using floor division instead. Note that`div_floor` is unstable, but `div_euclid` is not - the two are equivalent with respect to the quotient (though not the remainder, which we don't need here) so I …
=> fix(rust,python): some temporal conversion errors for datetimes earlier than `1970-01-01`

crates/polars-lazy/src/frame/mod.rs, py-polars/polars/io/spreadsheet/functions.py, py-polars/tests/unit/io/test_spreadsheet.py, py-polars/tests/unit/sql/test_temporal.py
* ~~Fixes casting from Datetime to Time for specific pre-epoch values where the time was 00:00:00~~ 
(See: #14050)
* Type inference fix when using "calamine" engine (added missing `all` when determining if a cast should be applied).
* Deprecate `read_csv_options` in favour of more generic `read_options`, which can now be used by other engines.
* Minor optimisation when using "calamine" engine (use `eq`, not `eq_missing`).
* Additional unit test coverage.
=> fix(python): multiple `read_excel` updates

py-polars/polars/expr/name.py
addresses the documentation part of https://github.com/pola-rs/polars/issues/14010
=> docs(python): note that only one `name` operation per expression

crates/polars-lazy/Cargo.toml, crates/polars/src/lib.rs, docs/user-guide/installation.md
Closes #14104
Feature flag was removed in #13390, apparently there were some remnants.
=> docs(rust): Remove outdated reference to horizontal concat feature

crates/polars-lazy/src/physical_plan/expressions/window.rs
Very surprised the compiler didn't warn about this. Wonder if this was in the final binary, but it was completely unneeded work.
=> perf: elide unneeded work in window?

docs/development/contributing/ci.md
=> docs: fix bullet point formatting in CI contributing guide

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py
fixes https://github.com/pola-rs/polars/issues/14096
the [user-guide](https://docs.pola.rs/user-guide/expressions/user-defined-functions/#return-types) was already correct.
=> docs(python): Fix description of `return_dtype` parameter for `map_elements` and `map_batches`

crates/polars-io/src/csv/read_impl/mod.rs, py-polars/tests/unit/io/test_csv.py
Fixes: https://github.com/pola-rs/polars/issues/11667
Comment were not ignored at the beginning of the csv file if the schema was provided; I changed to skip all comments at that point.
=> fix: ignore comments at beginning of csv if schema provided

crates/polars-arrow/src/compute/cast/boolean_to.rs, crates/polars-arrow/src/compute/cast/mod.rs, crates/polars-core/src/chunked_array/cast.rs
=> chore: hoist boolean -> string cast

crates/polars-arrow/src/array/static_array.rs, crates/polars-arrow/src/legacy/utils.rs, crates/polars-core/src/chunked_array/iterator/mod.rs, crates/polars-core/src/chunked_array/logical/struct_/mod.rs, crates/polars-core/src/chunked_array/mod.rs, crates/polars-core/src/chunked_array/ops/unique/mod.rs, crates/polars-core/src/chunked_array/upstream_traits.rs, crates/polars-core/src/frame/group_by/into_groups.rs, crates/polars-core/src/frame/row/transpose.rs, crates/polars-core/src/serde/chunked_array.rs, crates/polars-lazy/src/physical_plan/expressions/window.rs, crates/polars-ops/src/chunked_array/array/join.rs, crates/polars-ops/src/chunked_array/gather_skip_nulls.rs, crates/polars-ops/src/chunked_array/list/namespace.rs, crates/polars-ops/src/chunked_array/strings/concat.rs, crates/polars-ops/src/chunked_array/strings/json_path.rs, crates/polars-ops/src/chunked_array/strings/namespace.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs, crates/polars-ops/src/series/ops/approx_unique.rs, crates/polars-ops/src/series/ops/arg_min_max.rs, crates/polars-ops/src/series/ops/cum_agg.rs, crates/polars-ops/src/series/ops/is_in.rs, crates/polars-ops/src/series/ops/is_unique.rs, crates/polars-ops/src/series/ops/unique.rs, crates/polars-time/src/upsample.rs, crates/polars/src/docs/eager.rs, crates/polars/tests/it/io/csv.rs, py-polars/src/series/export.rs
Fixed a long standing annoyance. The `IntoIterator` trait doesn't allow for enough generics so we had to return a `Box<dyn Iterator>`. Which meant a dynamic function call on every iteration and the iterator is completely opaque to the compiler.
This adds an `iter` metod directly on `ChunkedArray<T>` for all `T: PolarsDataType`. This should be preferred over `into_iter` at all cost.
Note that it still is a nested iterator (as wel iterate over different chunks). So if you can please unpack your nestedness during iteration with:
```rust
// when you have null values
for arr ca.downcast_iter() {
// Non nested iteration so this saves a branch, e.g. fast and completely visible by compiler 
for value in arr.iter() {
// do work
}
}
// when you don't have null values
for arr ca.downcast_iter() {
// …
```
=> perf: improve iteration performance

crates/polars-core/src/chunked_array/logical/date.rs, crates/polars-core/src/chunked_array/logical/time.rs, crates/polars-core/src/series/implementations/dates_time.rs, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/test_cast.py
Closes #14124
* Casting from `Date` to `Time` now raises instead of producing `00:00:00` for every value.
* Casting from `Time` to `Date` now raises instead of using the underlying physical representation.
This should probably be considered a breaking change, at least the `Date->Time` part. The other way around was nonsense, e.g.:
```python
from datetime import time
s = pl.Series([time(0, 0)])
result = s.cast(pl.Date)
print(result)
```
```
shape: (1,)
Series: '' [date]
[
1970-01-01
]
```
=> feat!: Forbid casting from `Date` to `Time` and vice versa

crates/polars-plan/src/dsl/function_expr/strings.rs
It seems that we forget to add this flag when introduce `str.find`(No blame). I'm just curious if it's possible to get this error exposed early in the CI phase. 🤔 
This fixes #14121.
=> fix(rust): add missing conditional compile flag for `StringFunction::Find`

crates/polars-plan/src/logical_plan/hive.rs
=> fix: don't see files as hive partitions

crates/polars-io/src/csv/buffer.rs, crates/polars-io/src/csv/utils.rs, crates/polars/tests/it/io/csv.rs, py-polars/tests/unit/io/test_csv.py
fix #14064 (maybe a few more. will check)
fix a few issues and inconsistencies regarding date/datetime parsing/inference using `read_csv`.
current logic:
- column contains only type `T` -> infer type `T` ✅ 
- column contains `Int64` and `Float64` -> infer type `Float64` ✅ 
- column contains at least 1x `Date/DateTime` and any amount of `String` -> infer type `Date/DateTime` 💥  (PROBLEM, inconsistent)
new logic for date/datetime:
- only infer type `Date/DateTime` if no other dtypes are present (like for the other types)
Example:
```python
DATA = """d
2024-01-01
apple
banana
orange
"""
pl.read_csv(
source=DATA.encode(),
try_parse_dates=True,
)
```
Current/old output:
```
shape: (4, 1)
┌────────────┐
│ d          │
│ ---        │
│ date       │ >>>>> PROBLEM: should be str
╞════════════╡
│ …
```
=> fix(python,rust): fix read_csv date/datetime inference and parsing

docs/user-guide/concepts/data-structures.md
Fixes the code blocks on this page so that they are visible: https://docs.pola.rs/user-guide/concepts/data-structures/
Currently, only the output is visible:
=> docs: fix code blocks in user-guide/concepts/data-structures

crates/polars-core/src/chunked_array/ops/take/take_chunked.rs, crates/polars-core/src/datatypes/aliases.rs, crates/polars-core/src/prelude.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-ops/src/frame/join/general.rs, crates/polars-ops/src/frame/join/hash_join/mod.rs, crates/polars-pipe/src/executors/sinks/joins/generic_build.rs, crates/polars-pipe/src/executors/sinks/joins/generic_probe_inner_left.rs, crates/polars-utils/src/index.rs
For `bigidx` this saves 8 bytes.
=> perf: improve `ChunkId`

docs/user-guide/ecosystem.md
- Removed 'integration' from title as this might set wrong expectations about the content of page.
- adding duckdb under Other
- updated plotly after community remark - also more aligned with upcoming plotting examples.
=> docs: Small improvements Ecosystem page

.github/workflows/lint-rust.yml, Makefile, crates/Makefile, crates/polars-arrow/src/legacy/kernels/list.rs, py-polars/Makefile
This should help avoid debug statements making it into the main branch by accident (I found and removed two of them).
Clippy docs:
https://rust-lang.github.io/rust-clippy/master/index.html#/dbg
=> chore(rust): Enable `clippy` lint to warn on debug macros

crates/polars-core/src/chunked_array/object/extension/mod.rs, crates/polars-core/src/frame/group_by/hashing.rs, crates/polars-lazy/src/tests/aggregations.rs, crates/polars-ops/src/frame/join/hash_join/multiple_keys.rs, crates/polars-ops/src/frame/join/hash_join/single_keys.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_outer.rs, crates/polars-time/src/group_by/dynamic.rs, crates/polars-utils/src/idx_vec.rs
Can now be used throughout the library to elide early allocations (where we didn't already). Things that come to mind: 
- streaming joins
- expression/logical-plan iterations
Both mostly have a single value, but can grow to unknown size.
=> feat: make `IdxVec` generic as `UnitVec`

docs/development/contributing/index.md, docs/requirements.txt, docs/src/python/user-guide/misc/visualization.py, docs/user-guide/misc/visualization.md, mkdocs.yml, py-polars/tests/docs/test_user_guide.py
Simple page with a guide to making a chart in 4 key libraries.
The Altair plot renders on my screen with a strange actions tab on the right. I've never seen this before but haven't been able to get it back to the traditional output.
I've put this in the misc section. Perhaps we want an Integrations section that could have a page about ML, interchange protocols or similar?
=> docs(python): Add visualisation page to user guide

crates/polars-parquet/src/parquet/compression.rs
My impression is that #11699 is due to multiple different performance issues. This PR fixes one of them, but does not fix the whole performance difference. See below for numbers.
Perf showed the following:
```
-   51.46%     0.11%  python  [.] polars_parquet::parquet::compression::compress 
- ▒   - 51.35% polars_parquet::parquet::compression::compress                                                                                                                                   
- ▒      - 28.61% ZSTD_compressStream                                                                                                                                                           
- ▒         - ZSTD_compressStream2 …
```
=> perf: Use a compression API that is designed for this use case (#11699)

crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs, py-polars/tests/unit/operations/test_join.py
Fixes #13550 and #13852
Joins on string columns were only being validated on the probe side
=> fix: Fix join validation for String types

py-polars/polars/exceptions.py, py-polars/polars/expr/expr.py, py-polars/tests/unit/operations/map/test_map_batches.py
Fixes https://github.com/pola-rs/polars/issues/13557
I was back burnering whether or not there was a good way to tell if a ufunc was elementwise for a while now when I realized that they're all elementwise.
I did this test:
```
import scipy.special as ss
from polars.testing import assert_frame_equal
npufuncs = []
for x in dir(np):
if getattr(np,x).__class__==np.ufunc:
npufuncs.append(x)
ssufuncs = []
for x in dir(ss):
if getattr(ss, x).__class__==np.ufunc:
ssufuncs.append(x)
df=pl.DataFrame({'a':[1,1,2,2],
'b':[1.1,2.2,3.3,4.4],
'c':[3.1,4.2,5.3,6.4]})
goodufuncs = {"<module 'numpy' from '/usr/local/lib/python3.11/site-packages/numpy/__init__.py'>":[],
"<module 'scipy.special' from '/usr/local/lib/python3.11/site-packages/scipy/special/__init__.py'>": …
```
=> fix(python): fix ufunc in agg (change __ufunc_array__ so it uses `is_elementwise=True` parameter)

py-polars/polars/series/series.py, py-polars/tests/unit/interop/test_numpy.py
This used to return 'object' which is unnecessary.
This cannot be done zero-copy as a NumPy boolean is 1 byte.
=> fix(python): Make `Series.to_numpy` on booleans without nulls return `bool` type

py-polars/polars/datatypes/constructor.py, py-polars/tests/unit/interop/test_interop.py
numpy_type_to_constructor now supports columns containing np arrays ( == is not supported by them) Added related unit tests
Fixes #14237
=> fix: load numpy array with np array values #14237

py-polars/polars/series/series.py
I wanted to deprecate this, but turns out it doesn't even work currently because we also pass the keyword arguments directly:
```python
pl.Series([1, 2]).to_numpy(True)
```
So I'm removing this.
=> refactor(python): Remove `*args` in `Series.to_numpy`

crates/polars-ops/src/series/ops/log.rs, py-polars/tests/unit/expr/test_exprs.py
This PR addresses https://github.com/pola-rs/polars/issues/14245, where the `entropy` function was found to return a negative zero (`-0.0`) when applied to a series with only a single value. To solve this, the this PR introduces a check within the `entropy` function to assess the length of the input series. If the length of the series is `1`, the function now returns `0.0`, bypassing the standard entropy calculation process.
=> Fix: ensure non-negative output from the entropy function for single-value series

crates/polars-lazy/src/physical_plan/expressions/apply.rs, crates/polars-lazy/src/tests/io.rs
Closes https://github.com/pola-rs/polars/issues/13908
I tried to add row groups pruning when handling `is_between` conditions.
example df:
```python
>>> df
shape: (90, 1)
┌─────┐
│ d   │
│ --- │
│ i64 │
╞═════╡
│ 10  │
│ 11  │
│ 12  │
│ 13  │
│ 14  │
│ …   │
│ 95  │
│ 96  │
│ 97  │
│ 98  │
│ 99  │
└─────┘
>>> pl.scan_parquet('test.parquet').filter(pl.col('d').is_between(4, 9)).collect()
parquet file can be skipped, the statistics were sufficient to apply the predicate.
shape: (0, 1)
┌─────┐
│ d   │
│ --- │
│ i64 │
╞═════╡
└─────┘
>>> pl.scan_parquet('test.parquet').filter(pl.col('d').is_between(200, 900)).collect()
parquet file can be skipped, the statistics were sufficient to apply the predicate.
shape: (0, 1)
┌─────┐
│ d   │
│ --- │
│ i64 │
╞═════╡
└─────┘
>>> …
```
=> perf: use is_between to skip parquet row groups

Cargo.lock, py-polars/Cargo.toml, py-polars/polars/series/series.py, py-polars/src/series/export.rs, py-polars/tests/unit/interop/test_numpy.py
Not sure this can just be merged, but returning `f32` here was not correct since it may lose precision.
=> feat(python): Change `Series.to_numpy` to return `f64` for `Int32/UInt32` Series with nulls instead of `f32`

py-polars/polars/series/series.py, py-polars/src/series/c_interface.rs, py-polars/src/series/mod.rs
This allows `pyo3-polars` to directly use polars for `ffi`. Meaning we drop the required `pyarrow` dependency there (and we can use the new types).
=> feat(python): read arrow-c-interface without requiring pyarrow

crates/polars-plan/src/logical_plan/optimizer/simplify_functions.rs, py-polars/tests/unit/functions/aggregation/test_horizontal.py
Turning `simplify_expression` on and off will return different dtype(input type vs. boolean).  It should always has a `Boolean` type indeed.
=> fix: `any/all_horizontal` with single input has incorrect type

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/dataframe/test_glimpse.py
Though glimpse implementation has default values for all arguments, the corresponding @overload missed default value for return_as_string.
Mypy didn't catch it because there was no call in tests without arguments
=> fix: Fix `glimpse` overload signature

py-polars/polars/testing/parametric/__init__.py, py-polars/polars/testing/parametric/primitives.py, py-polars/polars/testing/parametric/strategies.py, py-polars/tests/parametric/test_testing.py, py-polars/tests/parametric/time_series/test_truncate.py
In addition to `List` (already supported) can now declare/use the `Array` dtype in parametric tests.
```python
from hypothesis import given
from polars.testing.parametric import column, create_array_strategy
@given(
df=dataframes(
cols=[
column("colx", dtype=pl.Array(pl.UInt8, width=3)),
column(
name="coly", 
strategy=create_array_strategy(
inner_dtype=pl.Array(pl.String, width=2),
select_from=["a", "b", "c"],
width=2,
))]
))
def test_array_stuff(df: pl.DataFrame) -> None:
print(df)
```
=> feat(python): add parametric testing support for the `Array` dtype

crates/polars-core/src/chunked_array/logical/decimal.rs, py-polars/tests/unit/datatypes/test_decimal.py
Decimal `div` is only effected by this.
=> fix: relax precision when up scaling

crates/polars-arrow/src/compute/take/mod.rs, crates/polars-core/src/chunked_array/builder/list/mod.rs, crates/polars-core/src/chunked_array/builder/list/primitive.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> fix: `list.get` does not work on list of decimals

py-polars/polars/series/series.py, py-polars/src/series/export.rs, py-polars/tests/unit/interop/numpy/test_numpy.py, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
Also closes #14274
Plus a bunch of tests for zero-copyness.
=> feat(python): Support `Categorical/Enum` in `Series.to_numpy`

py-polars/polars/io/delta.py
Update the delta docstrings to point to the new webpage
closes #14281
=> docs(python): Update deltalake docstrings to new link

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
=> docs(python): Fix explode docstring mentioning String types

py-polars/tests/unit/io/test_delta.py
Awaiting feedback on https://github.com/delta-io/delta-rs/issues/2165, I am skipping the row order check in this test.
=> test(python): Temporarily fix failing deltalake test

docs/development/contributing/index.md, docs/development/contributing/test.md, py-polars/tests/unit/io/test_delta.py
Ref https://github.com/delta-io/delta-rs/issues/2165
Ref #14150
Ref https://github.com/pola-rs/polars/pull/14151#discussion_r1475198073
Thanks to @BGR360 for signalling the contributing guide issues!
=> docs(python): Small clarifications in the contributing guide

crates/polars-core/src/chunked_array/logical/categorical/mod.rs, py-polars/tests/unit/operations/test_cast.py
Resolves #14318.
```python
dtype1 = pl.Enum(["a", "b"])
dtype2 = pl.Enum(["a", "b", "Null"])
s = pl.Series(name="x", values=["a", "b", None], dtype=dtype1)
print(s.name)
```
```
x
```
=> fix: Preserve name when casting to Enum

crates/polars-core/src/chunked_array/logical/decimal.rs, crates/polars-core/src/series/ops/null.rs, py-polars/tests/unit/datatypes/test_decimal.py
Closes #14002 
More specifically, the PR attempts to address the following two issues:
**1. Panic when casting from an empty Series without explicitly setting a scale:**
```python
pl.Series().cast(pl.Decimal)
```
In this case, we just set scale to 0, in the same way as it's done when constructing an empty Series with `dtype=pl.Decimal`:
```python
pl.Series([], dtype=pl.Decimal) 
```
**2. An error is raised when casting a Series, whose dtype is already pl.Decimal, without setting scale explicitly:**
```python
from decimal import Decimal
pl.Series([Decimal("10.0")]).cast(pl.Decimal)
```
I don't know why anyone would want to do that but raising an error seems too punishing; the existing scale can be kept. For example:
```python
from decimal import Decimal …
```
=> feat: Do not panic when casting from an empty Series to pl.Decimal

crates/polars-lazy/src/dsl/functions.rs, py-polars/tests/unit/functions/test_functions.py
Resolves #14321.
```python
df1 = pl.DataFrame()
"a": ["a", "b"],
"b": [1, 2],
})
out = pl.concat((df1, df2), how="diagonal_relaxed")
print(out)
```
```
shape: (2, 2)
┌───────┬───────┐
│ col_1 ┆ col_2 │
│ ---   ┆ ---   │
│ str   ┆ i64   │
╞═══════╪═══════╡
│ a     ┆ 1     │
│ b     ┆ 2     │
└───────┴───────┘
```
=> Fix: don't add null row when "diagonal-relaxed" used with empty frames

crates/polars-core/src/chunked_array/list/iterator.rs, crates/polars-ops/src/chunked_array/list/namespace.rs, crates/polars-plan/src/dsl/function_expr/list.rs, crates/polars-plan/src/dsl/list.rs, py-polars/docs/source/reference/expressions/list.rst, py-polars/docs/source/reference/series/list.rst, py-polars/polars/expr/list.py, py-polars/polars/series/list.py, py-polars/src/expr/list.rs, py-polars/tests/unit/namespaces/list/test_list.py
Half work of #14273. Will submit Its counterpart in array namespace in another PR to avoid conflicts.
=> feat: Implements `list.n_unique`

crates/polars-ops/src/chunked_array/list/sets.rs, py-polars/tests/unit/namespaces/list/test_set_operations.py
=> fix: Fix `set_operation` if the input is sliced and be broadcast

crates/polars-core/src/chunked_array/array/iterator.rs, crates/polars-ops/src/chunked_array/array/namespace.rs, crates/polars-plan/src/dsl/array.rs, crates/polars-plan/src/dsl/function_expr/array.rs, py-polars/docs/source/reference/expressions/array.rst, py-polars/docs/source/reference/series/array.rst, py-polars/polars/expr/array.py, py-polars/polars/series/array.py, py-polars/src/expr/array.rs, py-polars/tests/unit/namespaces/array/test_array.py
Digression: We are not far away from the ability to fully align list and array namespace. `eval` is probably the most troublesome part, if we want it to return an array instead of list in some cases.
=> feat: Implements `arr.shift`

crates/polars-lazy/src/tests/err_msg.rs, crates/polars-lazy/src/tests/mod.rs, crates/polars-plan/src/dot.rs, crates/polars-plan/src/logical_plan/builder.rs, crates/polars-plan/src/logical_plan/format.rs, crates/polars-plan/src/logical_plan/mod.rs, py-polars/tests/unit/test_errors.py
Should fix #8079 , but ***please avoid merging for now***, as I have only tested a small subset of the things this might affect (and I have not yet added any formal tests at all; what's below is the extent of my testing). I would also like input on this to see if this the ideal way to handle this problem and to report errors in general.
- Prevented exponential growth of error messages by avoiding nesting of error messages
- Instead, used a counter to track how many operations had been applied to a LazyFrame after an error
- Error message contains stack depth and original error
- Renamed `ErrorState` to `ErrorStateEncounters` and made it crate-private
- Renamed `ErrorStateSync` to `ErrorState` and removed its `Deref` impl so that the only way to access its data is through (crate-private) …
=> fix: Remove duplicated content in error messages

py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
Since NumPy does not have time zones, we simply use the underlying physical representation. This is equivalent to converting to UTC first.
This was already handled correctly, just adding a test here to make sure.
=> test(python): Add test for `Series.to_numpy` with timezones

py-polars/polars/expr/expr.py, py-polars/tests/unit/operations/map/test_map_batches.py
fixes https://github.com/pola-rs/polars/issues/10512
https://github.com/pola-rs/polars/issues/14216
Since the ufunc only passes to `__ufunc_array__` the number of args that are actually required, we can't reduce (see the linked issue for more details). Users must reduce themselves. As such, I took out the `pyreduce` and instead we can create structs automatically. Before this change, the usage of pyreduce just allowed for exactly 2 inputs but no more than 2 so it wasn't really reducing in the true sense of the word.
When this gets merged I'll revise https://github.com/pola-rs/polars/pull/13392 this to incorporate the new capabilities.
=> fix(python): fix ufunc for unlimited column args

docs/src/python/user-guide/basics/series-dataframes.py, docs/src/rust/Cargo.toml, docs/src/rust/user-guide/basics/series-dataframes.rs
I have added missing Rust examples to user-guide/concepts/data-structures/
Maybe double check the code as these are my very first efforts in Rust
=> docs: Rust examples for data structures in user guide

py-polars/polars/testing/asserts/series.py, py-polars/tests/unit/testing/test_assert_series_equal.py
Now that we have https://github.com/pola-rs/polars/pull/14338, we no longer need to cast Decimals to floats. This also means that inexact checking no longer applies to Decimals, as was intended (see the docstring). So this classifies as a fix.
=> fix(python): Require exact checking for Decimals in assertion utils

crates/polars-lazy/src/frame/mod.rs
This allows functions to accept either `DataFrame` or `LazyFrame`
```
fn foo(frame : impl IntoFrame);
```
=> feat(rust): Implements the IntoLazy for LazyFrame

crates/polars-core/src/datatypes/field.rs
Supersedes #8767
Credit to @jay-johnson for signalling this issue.
=> feat(rust): Improve panic message for missing struct feature in `DataType::from_arrow`

py-polars/polars/expr/expr.py, py-polars/src/expr/general.rs
Clashes with built-ins should be resolved by appending an underscore, not prepending one (signalling a private method).
=> refactor(python): Internal rename of `_or` to `or_` in PyO3 (same for `_xor/_and`)

py-polars/polars/dataframe/frame.py
When I read the docs for this method for the first time, it was not at all clear to me how the returned dictionary was constructed until I scrolled all the way down to the examples. And even then, it took me a little while to understand.
I edited the description to be a bit more clear about how the dictionary is structured, while trying not to be too redundant with the examples and parameter docs.
Also, while I was here, I added a little blurb to the `rows` docs as well.
=> docs(python): Clarify behavior of `DataFrame.rows_by_key`

py-polars/polars/expr/string.py, py-polars/polars/series/string.py
Closes #10349
Credit to @mcrumiller who signalled this issue and started this in #10339. I am splitting this out as the implementation of the `str.head/tail` should not block this doc improvement.
=> docs(python): Define what a 'character' means in `slice` / `len_chars`

crates/polars-sql/src/sql_expr.rs, crates/polars-sql/tests/statements.rs
This very simple PR allows brackets in join conditions, for example
```SQL
SELECT * FROM df1
INNER JOIN df2 ON
df1.a = df2.a AND
((df1.b = df2.b AND
df1.c = df2.c) AND
df1.d = df2.d)
```
Since only AND is allowed currently and AND is associative, this is not terribly useful yet except when migrating existing SQL code, but if we ever implement OR or other binary operations, brackets will be necessary.
Note: not all places where brackets would be allowed are covered yet in this PR.
=> feat: Allow brackets in SQL join conditions

py-polars/polars/expr/expr.py, py-polars/tests/unit/operations/map/test_map_elements.py
=> fix(python): Raise if invalid strategy is passed to `map_elements`

crates/polars-ops/src/series/ops/clip.rs, crates/polars-plan/src/dsl/function_expr/clip.rs, py-polars/polars/expr/expr.py, py-polars/tests/unit/operations/test_clip.py
Taking out the useful work from #13713
`clip` doesn't support strings so we can interpret strings as column names.
Also refactoring some tests.
=> feat(python): Allow column name input in `clip`

py-polars/src/series/mod.rs, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/operations/map/test_map_elements.py
Fixes: https://github.com/pola-rs/polars/issues/14390
The regression was introduced by https://github.com/pola-rs/polars/pull/13518 on `0.20.4` by not rechunking scanned/read files by default.
Iterating through a chunked series panics here:
https://github.com/pola-rs/polars/blob/b2207b895a8ef8f066ff1126e240ad3b91dc60d4/crates/polars-core/src/series/iterator.rs#L66-L74
I call `rechunk()` on the series before iterating through them.
=> fix(python,rust): rechunk series when apply_lambda

crates/polars-ops/src/series/ops/clip.rs, py-polars/tests/unit/operations/test_clip.py
Ref #11385
Ref #14413
**Before**
```python
s = pl.Series([1, 2, 3, 4], dtype=pl.UInt32)
result = s.clip(-1, 5)
print(result)
```
```
shape: (4,)
Series: '' [u32]
[
null
null
null
null
]
```
**After**
```
polars.exceptions.ComputeError: conversion from `i32` to `u32` failed in column 'literal' for 1 out of 1 values: [-1]
```
=> fix: Error on some invalid `clip` inputs

crates/polars-ops/src/series/ops/cum_agg.rs, py-polars/tests/unit/series/test_series.py
this came up whilst teaching - can these be simplified?
passes tests locally at least...gonna sleep on it and think if there's anything I missed
=> perf: simplify and speed up cum_sum and cum_prod

py-polars/polars/testing/asserts/frame.py, py-polars/polars/testing/asserts/series.py, py-polars/tests/unit/testing/test_assert_frame_equal.py, py-polars/tests/unit/testing/test_assert_series_equal.py
Currently, pytest generates very long and uninformative tracebacks for failing tests that use `polars.testing.assert_frame_equal()`:
```python
from polars.testing import assert_frame_equal
def test_df():
df1 = pl.DataFrame({'a': [1, 2]})
df2 = pl.DataFrame({'a': [1, 3]})
assert_frame_equal(df1, df2)
```
<details>
<summary>Long stack trace</summary>
```
============================= test session starts ==============================
platform linux -- Python 3.10.0, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/kale
plugins: cov-4.0.0, env-0.6.2, subtests-0.7.0, xdoctest-1.1.1, hypothesis-6.39.4, devtools-0.12.2, unordered-0.4.1, hydra-core-1.3.2, pytest_tmp_files-0.0.0, xonsh-0.12.1, xdist-2.5.0, forked-1.4.0, anyio-3.7.1, typeguard-4.0.0
collected 1 item
test_df.py F …
```
=> feat(python): Hide `polars.testing.*` in pytest stack traces

crates/polars-core/src/chunked_array/ops/aggregate/mod.rs, crates/polars-core/src/series/implementations/categorical.rs, py-polars/tests/unit/series/test_series.py
Implements `Series.min`/`max` for categoricals as follows:
- `ordering="lexical"` behaves just like `dtype=pl.String`.
- `ordering="physical"` returns the first (last for max) non-null value in the series.
=> feat: Implement `min`/`max` for categorical dtype

py-polars/tests/unit/streaming/test_streaming_group_by.py, py-polars/tests/unit/streaming/test_streaming_sort.py
Ref https://github.com/pola-rs/polars/issues/13526
=> test(python): Skip some OOC tests that fail randomly in the CI

crates/polars-arrow/src/legacy/utils.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/projection.rs, py-polars/tests/unit/test_projections.py
=> fix: remove literal `Series` from projection state

py-polars/tests/unit/series/test_series.py
arg_min/arg_max test case has become a little long and bloated. Broke it down a bit, removed some duplicate test instances, and parametrized it.
=> test(python): Refactor `arg_min/max` test case

py-polars/tests/unit/test_polars_import.py
Ref #14442
This doesn't really address the issue with this test, but at least makes it more transparent (it was failing with a weird error in the subsequent `read_csv` call).
=> test(python): Raise better error in import timings test

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/operations/test_pivot.py
Ref https://github.com/pola-rs/polars/issues/12087
Positional args will be enabled again once order of parameters has been changed.
=> depr(python): Deprecate positional args in `pivot` to prepare new functionality

py-polars/tests/docs/test_user_guide.py
Reverts pola-rs/polars#14449
Unfortunately this causes new test failures. So until the issue is addressed properly, I am reverting this.
=> Revert "test(python): Use resolved path in `test_user_guide`"

crates/polars-ops/src/frame/pivot/positioning.rs, py-polars/tests/unit/operations/test_pivot.py
closes #14307
the final major piece of the pivot puzzle! (at least, until someone finds anything else...)
---
The gist of this is:
- in `compute_row_idx`, for the `index.len() > 1` case, combine the indexes into a struct
- use the specialised struct path
- unnest
=> fix: DataFrame.pivot was returning incorrect results when multiple columns were passed to `index` and one of them was Struct

py-polars/src/file.rs
I noticed when reading csv files from inside a zip archive that it kept "warning" that I shouldn't do that and that I couldn't ignore the warning because it was printing rather than warning.
=> feat: change print to warn in reading csv from python file like object

crates/polars-core/src/frame/group_by/aggregations/dispatch.rs, crates/polars-core/src/series/implementations/duration.rs, crates/polars-lazy/src/frame/mod.rs, py-polars/polars/series/datetime.py, py-polars/src/series/aggregation.rs, py-polars/tests/unit/namespaces/test_datetime.py
Resolves #14375. Part of overall #13599.
This also moves one step closer to deprecating `Series.dt.mean` and `Series.dt.median`, as the base Series' `mean` and `median` now support duration dtypes.
Using the example from the issue, all cases now properly output a duration:
```
6 days, 0:00:00
2 days, 0:00:00
6 days, 0:00:00
2 days, 0:00:00
shape: (1, 2)
┌──────────────┬──────────────┐
│ mean         ┆ median       │
│ ---          ┆ ---          │
│ duration[μs] ┆ duration[μs] │
╞══════════════╪══════════════╡
│ 6d           ┆ 2d           │
└──────────────┴──────────────┘
shape: (1, 3)
┌─────┬──────────────┬──────────────┐
│ key ┆ mean         ┆ median       │
│ --- ┆ ---          ┆ ---          │
│ i64 ┆ duration[μs] ┆ duration[μs] │
╞═════╪══════════════╪══════════════╡
│ 1   ┆ 6d …
```
=> fix: Return appropriate data type for duration `mean` and `median`

py-polars/polars/io/database.py
The behaviour of `str(sqlalchemy_url)` was changed in v2 to hide the password by default.
The docs was updated to use `render_as_string(hide_password=False)`
Ref: https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#change-8567
=> docs(python): Update `read_database` docstring note about getting the connection URI string for sqlalchemy

py-polars/polars/series/binary.py
A portion of #13161 
Added examples for remaining `Series.bin` methods.
=> docs(python): Add examples for `Series.bin.ends_with`, `Series.bin.starts_with`, `Series.bin.decode`, `Series.bin.encode`.

py-polars/polars/datatypes/convert.py, py-polars/polars/utils/_construction.py, py-polars/tests/unit/constructors/test_constructors.py
Closes #12178
Supersedes #12209
I did some refactoring of the `_unpack_schema` utility. This also closes the linked issue.
* Error when the elements of the `schema` input cannot be unpacked into two variables (column, dtype).
* Allow non-tuple elements (`list` and other sequences are now also allowed, but MyPy will still complain).
=> fix(python): Error on invalid `schema` input in DataFrame constructor

crates/polars-pipe/src/operators/operator.rs, crates/polars-pipe/src/pipeline/dispatcher.rs
This is required for the streaming outer join, as we need to flush the rows that didn't have any matches when the operation is finished.
=> feat: add `flush` operator to streaming operators

py-polars/polars/series/series.py, py-polars/tests/unit/datatypes/test_duration.py
Supersedes #12881
Credit to @ion-elgreco - I tried to adjust the original PR but the commit history wasn't linear so I had trouble rebasing/updating. So I'm opening a new PR.
It seems behavior has changed since the original PR opened. Overflows now result in a panic rather than null. Which is definitely better. So let's go ahead with this, and we can see how to address the panic later.
Unsupported types should raise anyway rather than return None, so this is a good move regardless.
=> fix(python): Remove `is_numeric` check on `Series.std/var`

crates/polars-time/src/upsample.rs
The current documentation of the `upsample_stable` is identical to the `upsample`.
So users can not know what the difference is between `upsample` and `upsample_stable.`
I think this should be fixed.
=> docs(rust): Clarify doc summary of `upsample_stable`

crates/polars-plan/src/dot.rs
Additionally, should there be a space here? (i.e. "CACHE: {} times")
https://github.com/jdanford/polars/blob/86e82d7a376b3a83d0eb36de725f8f0cb304c320/crates/polars-plan/src/dot.rs#L169
=> feat: Make formatting more consistent in DOT graphs

Cargo.lock, Cargo.toml, crates/polars-arrow/Cargo.toml, crates/polars-core/src/utils/mod.rs, crates/polars-pipe/Cargo.toml, crates/polars-pipe/src/executors/sinks/io.rs, crates/polars-pipe/src/executors/sinks/sort/ooc.rs
fixes #13526
- adds a proper uuid. This wasn't the culprit, but is properly better than system time.
- ensures we don't panic if another thread already cleared the IO buffer.
=> fix: race conditions in OOC writing

crates/polars-core/src/frame/row/transpose.rs, py-polars/src/dataframe.rs, py-polars/tests/unit/operations/test_transpose.py
Resolves #14524.
This changes the signature of `transpose` from `&self` to `&mut self` because it now rechunks...is this considered a breaking change?
=> fix: Ensure series are contiguous prior to `transpose`

py-polars/polars/convert.py, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/string.py, py-polars/polars/io/csv/functions.py, py-polars/polars/io/json.py, py-polars/polars/io/ndjson.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/string.py
Fixes #14232 by:
- Fixing default value
- Adding description for `None` case
=> docs(python): Fix `infer_schema_length` param description

codecov.yml
Right now, code coverage is experimental, we should not fail PR's or add a failure status before finding out the right parameters. 
This PR removes all status updates from codecov.
=> feat: disable status from code coverage

py-polars/polars/utils/udfs.py, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py
Ref: #9968.
(Implements the _".dt.month and other stdlib datetime functions"_ suggestion).
Saw somebody do this in our own codebase today (shame on that person 🤣), so have added new bytecode detection logic for temporal attrs/methods, along with the appropriate native expression mapping. 
Covers the following temporal attributes...
`date`
`day`
`hour`
`microsecond`
`minute`
`month`
`second`
`year`
...and temporal methods:
`isoweekday()`
`date()`
`time()`
```python
df = pl.DataFrame({"dtm": [datetime(2024,2,16,10,30,45)]})
time = pl.col("dtm").map_elements(lambda d: d.time())
)
```
Can still do it, but now triggers a `PolarsInefficientMapWarning`:
```python
```
Now optimises out unnecessary implicit existence checks from the final suggestion, eg: …
=> feat(python): warn on inefficient use of `map_elements` for temporal attributes/methods

py-polars/polars/utils/_construction.py
=> perf(python): Avoid loading pandas in `from_arrow` when array has 0 chunks

.github/workflows/codecov.yml, .github/workflows/test-python.yml, py-polars/tests/unit/test_serde.py
Following up on https://github.com/pola-rs/polars/pull/14532
This brings the workflow more in line with the existing testing workflows.
* Only run store the cache on main, avoiding cache storage space issues.
* Only run workflow when Rust or Python files have been modified.
* Make setup more modular (more easily see where things go wrong and how long each step takes)
(I did a random test refactor to trigger the workflow)
I'm also thinking this could be much improved by running coverage in the existing test workflows and combining the results. We should look into that later.
=> ci: Refactor code coverage workflow

py-polars/polars/io/csv/functions.py
Hi,
I noticed on `pl.read_csv` that the tooltip documentation needed a newline after a list to be formatted correctly. 
As you can see in the picture below, all of the attributes after `missing_utf8_is_empty_string` are listed under the `Dict[str, str]` bullet point. 
It's just a small fix. This is my first time contributing so hopefully this is helpful!
=> docs(python): Fix markdown newline for rendering function description in VSCode

py-polars/polars/io/database.py, py-polars/polars/type_aliases.py, py-polars/tests/unit/io/test_database_read.py
Closes #13926.
Further streamlines use of `read_database` by ensuring seamless interop with SQLAlchemy's `Session` object (we were mostly fine, but some specific flavours of cursor result needed a little additional introspection).
* Improves column inference from cursor/result object (eg: `ChunkedIteratorResult`, as seen in the linked issue).
* Adds explicit test coverage for SQLAlchemy's `Session` object.
=> feat(python): improve `read_database` interop with sqlalchemy `Session` connections

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
* Add `allow_copy` parameter to `DataFrame.to_numpy`, which will raise an error if a copy is required to perform the conversion
* For `Series.to_numpy`, deprecate the `zero_copy_only` parameter in favor of `allow_copy` which is the inverse.
=> feat(python): Add `allow_copy` parameter to `DataFrame.to_numpy`

py-polars/polars/utils/udfs.py, py-polars/polars/utils/various.py, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py
Ref: #9968.
The `BytecodeParser` can now also detect/translate Python string ops such as...
* `s.strip()`
* `s.lstrip()`
* `s.rstrip()`
* `s.endswith('x')`
* `s.endswith(('x','y'))`
* `s.startswith('x')`
* `s.startswith(('x','y'))`
Note that as we don't (currently ;) support multiple strings being passed in to `starts_with` and `ends_with`, such expressions are translated to a suitable `contains` regex instead.
````python
df = pl.DataFrame({"s":["xxyx","123xx", "45yx?"]})
match = pl.col("s").map_elements(lambda s: s.endswith(("?", "!"))),
)
```
=> feat(python): Warn on inefficient use of `map_elements` for additional string functions

crates/polars-ops/src/frame/join/hash_join/multiple_keys.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_semi_anti.rs, crates/polars-ops/src/frame/join/hash_join/sort_merge.rs
Fixes https://github.com/pola-rs/polars/issues/14535
This happens because a `ParallelIterator` is constructed inside of `POOL.install` but this iterator is collected outside of the `POOL` context. I.e.:
```rust
POOL.install(|| { x.par_iter().map(..) }).collect() // this runs outside the pool
POOL.install(|| { x.par_iter().map(..).collect() }) // this runs inside the pool
```
This was hard to spot at first because we see `POOL.install` next to `par_iter` and are led to believe it is used properly, but in fact the key requirement was to ensure the iteration (usually `.collect()`) was being done inside of `POOL.install`.
I also fixed some other places aside from semi-join that did this (but restricted to `crates/polars-ops/src/frame/join/`)
Not sure how to add tests for this, but here's a …
=> fix: semi-join and multiple keys outer-join did not respect POLARS_MAX_THREADS

docs/development/contributing/index.md
PR titles are used as changelog entries directly. Changelog entries are sentences and should start with an uppercase letter. Right now, it's a mix of upper/lowercase and it makes the release notes looks unprofessional.
Unfortunately, this cannot easily be automated currently: https://github.com/release-drafter/release-drafter/issues/1363
So far I've been randomly updating PRs manually, but it's a chore. So I'm at least including this as a rule in the contributing guide.
=> docs: Mention in contributing guide that PR titles should start with an uppercase letter

crates/polars-compute/src/arity.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-ops/src/frame/join/cross_join.rs, crates/polars/src/lib.rs, docs/user-guide/installation.md, docs/user-guide/transformations/joins.md, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py, py-polars/tests/unit/io/test_csv.py
Closes #14578
I'm also updating the spelling `writeable -> writable` to unify the spelling (both are correct, we use "writable" in our public API).
=> docs: Fix typo of "Cartesian" product

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/operations/unique/test_approx_n_unique.py
Closes https://github.com/pola-rs/polars/issues/13498
Deprecated because users may expect the approximate number of unique rows (rather than the number of unique values in each column).
=> depr(python): Deprecate `DataFrame/LazyFrame.approx_n_unique`

crates/polars-core/src/chunked_array/ops/sort/arg_sort_multiple.rs, crates/polars-core/src/frame/arithmetic.rs, crates/polars-core/src/frame/group_by/into_groups.rs, crates/polars-core/src/frame/row/transpose.rs, crates/polars-io/src/csv/read.rs, crates/polars-ops/src/frame/join/asof/groups.rs
Found these by running `py.test` with a rayon fork that panicked on attempts to use the global thread pool.
In theory it might be possible to initialize rayon's global thread pool with a `start_handler`  that panics for debug builds, but I couldn't try it because I don't know where to put the call to build the thread pool - I can't call it outside of function contexts because it wasn't a `const fn`.
=> fix: Polars thread pool was not used properly in various functions

py-polars/polars/datatypes/convert.py, py-polars/polars/series/series.py, py-polars/src/to_numpy.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
* Use the new NumPy view functionality implemented in Rust for creating views in `to_numpy` and `__array_ufunc__`.
* The `SeriesView` class is kept around for now for use in the deprecated `Series.view`. It can be removed with the next breaking release.
=> refactor(python): No longer use `SeriesView` in `Series.to_numpy`

py-polars/Makefile
~~More cleanly separates the linting and formatting options in the`Makefile` (it was never clear to me why "fmt" would also trigger linting as they are not the same thing)~~
Update; PR now just adds `make lint` (no change to fmt).
```
make lint  # new; runs only the ruff/mypy linting ✔️
```
=> chore(python): Add a lint-only `Makefile` option

.github/workflows/codecov.yml, py-polars/tests/unit/datatypes/test_enum.py
Right now are code coverage does not take into account the python tests. It seems the `coverage.xml` is overwritten by codecov itself
=> ci: Rename coverage file

docs/user-guide/getting-started.md
While reading trough documentation I have noticed an output that was missing preceding code block.
After looking into documentation source I have noticed that it is due to typo in a path to code block.
Before:
After:
=> docs: Fix code block path for group by example in getting started guide

Makefile, py-polars/docs/requirements-docs.txt, py-polars/requirements-dev.txt
https://github.com/astral-sh/uv
It's definitely a lot faster - no real reason not to use it.
* Using `pip`: ~30 seconds
* Using `uv`: ~3 seconds
The `--prefer-binary` syntax is not supported (yet?): https://github.com/astral-sh/uv/issues/1794
...but I don't think we really need to include this anyway.
=> chore(python): Use `uv` for `make requirements`

crates/polars/src/lib.rs
I spotted a small typo in the Rust API docs: a duplicate "the"
=> docs(rust): Remove some outdated information in `polars` crate docs

py-polars/tests/unit/datatypes/test_enum.py
fix #13269 
close #13891
We already support it with the current code base, this PR supersedes the previous one and adds the test to the code base.
Thanks @collinprince!
=> test(python): Add test on selecting Enum columns

docs/user-guide/expressions/plugins.md
A few things:
- teach to use the `"abi3-py38"` feature by default to avoid installation issues like https://github.com/pola-rs/polars-xdt/discussions/59. Advanced users who know what they're doing can always remove it
- separate teaching to write a plugin from registering a custom accessor
- add some extra links to the community material:
- polars-reverse-geocode (something I used for a client, which they kindly allowed me to open source)
- polars plugins tutorial
- cookiecutter-polars-plugins
- uses `Expr.register_plugin` instead of the deprecated `Expr._register_plugin`
closes #13899
=> docs: Separate "writing a plugin" from "registering an expression" in user guide, add some extra links, don't use deprecated _register_plugin

crates/polars-core/src/utils/mod.rs, crates/polars-io/src/parquet/write.rs
Fixes #14484 
Before:
```
COLLECT+WRITE 0.9387576580047607
STREAMING COLLECT+WRITE 5.633932828903198
```
After:
```
COLLECT+WRITE 0.9567661285400391
STREAMING COLLECT+WRITE 0.9884464740753174
```
```
COLLECT+WRITE 0.9158937931060791
STREAMING COLLECT+WRITE 1.0007367134094238
```
=> perf: If there are many small chunks in write_parquet(), convert to a single chunk (#14484)

crates/polars-parquet/src/parquet/encoding/hybrid_rle/encoder.rs
Improve the change from https://github.com/pola-rs/polars/pull/13883.
might also give a tiny performance bump
=> refactor(internal): simplify compressed_chunk_size calculation and leave comments to explain for rle encode

crates/polars-arrow/src/array/binview/view.rs
closes #14619
Not much we can do, as we have to be more branchy.
=> perf: add utf8-validation fast paths for utf8view

py-polars/polars/utils/_construction.py
By requiring an exact dtype match we could end up in this branch when it's not required. Example:
```python
df = pl.DataFrame({"a": [[datetime(1990, 1, 1)]]}, schema={"a": pl.List(pl.Datetime)})
```
We should just use the equality operator here.
=> refactor(python): Avoid unnecessary cast in Series constructor

crates/polars-core/src/chunked_array/logical/categorical/mod.rs, crates/polars-core/src/chunked_array/logical/categorical/ops/unique.rs, crates/polars-core/src/chunked_array/ops/aggregate/mod.rs, crates/polars-core/src/frame/group_by/perfect.rs, crates/polars-core/src/series/implementations/categorical.rs, crates/polars-ops/src/series/ops/is_in.rs, crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs, py-polars/tests/unit/operations/test_is_in.py
Resolves #14575.
Prequisite to #14559 being fixed.
=> fix: Enable `is_in` for string in categorical/enum

crates/polars-arrow/src/array/primitive/mutable.rs, crates/polars-core/src/chunked_array/object/mod.rs, crates/polars-core/src/chunked_array/ops/unique/mod.rs, crates/polars-core/src/datatypes/any_value.rs, crates/polars-core/src/frame/group_by/hashing.rs, crates/polars-core/src/frame/group_by/into_groups.rs, crates/polars-core/src/frame/group_by/mod.rs, crates/polars-core/src/hashing/vector_hasher.rs, crates/polars-ops/src/chunked_array/hist.rs, crates/polars-ops/src/chunked_array/list/hash.rs, crates/polars-ops/src/chunked_array/list/sets.rs, crates/polars-ops/src/frame/join/asof/groups.rs, crates/polars-ops/src/frame/join/hash_join/single_keys.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_inner.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_left.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_outer.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_semi_anti.rs, crates/polars-ops/src/frame/join/mod.rs, crates/polars-ops/src/frame/pivot/positioning.rs, crates/polars-ops/src/series/ops/approx_unique.rs, crates/polars-ops/src/series/ops/is_first_distinct.rs, crates/polars-ops/src/series/ops/is_in.rs, crates/polars-ops/src/series/ops/is_last_distinct.rs, crates/polars-ops/src/series/ops/is_unique.rs, crates/polars-ops/src/series/ops/unique.rs, crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs, crates/polars-utils/src/total_ord.rs, py-polars/tests/unit/dataframe/test_df.py
This should be a slight perf improvement for hashing primitive types, but more importantly will revert the change in the hash output values for integer types introduced by https://github.com/pola-rs/polars/pull/14617 (see https://github.com/pola-rs/polars/pull/14617#issuecomment-1960587029).
<details>
<summary>Benchmark</summary>
```
running 1 test
n_iterations: 70000000
(10 as i32) hash_one(TotalOrdWrap(x)) vs hash_one(x.to_total_ord()): 2449ms vs 2157ms
(10 as i32) hash_one(TotalOrdWrap(x)) vs hash_one(x.to_total_ord()): 2411ms vs 2151ms
(10 as i32) hash_one(TotalOrdWrap(x)) vs hash_one(x.to_total_ord()): 2400ms vs 2122ms
(10 as i32) hash_one(TotalOrdWrap(x)) vs hash_one(x.to_total_ord()): 2437ms vs 2145ms
(10 as i32) hash_one(TotalOrdWrap(x)) vs hash_one(x.to_total_ord()): 2440ms vs …
```
=> perf: Elide the total order wrapper for non-(float/option) types

crates/polars-arrow/src/pushable.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/utils.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/utils.rs, crates/polars-parquet/src/arrow/read/deserialize/utils.rs, py-polars/tests/unit/io/test_parquet.py
Fix https://github.com/pola-rs/polars/issues/14638.
=> fix: Reading RLE_DICTIONARY-encoded parquet incorrectly coalesced NULL to empty string in some cases

crates/polars-time/src/group_by/dynamic.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/operations/test_rolling.py
closes #7360
This one's been bugging me for a while, not being able to just do `df.with_row_index().rolling("index", period="2i")` and instead having to do `df.with_row_index().rolling(pl.col("index").cast(pl.Int64), period="2i")`
The result index should be the same as the input, so the cast back to an unsigned integer should always work without surprises
=> feat: let `rolling` accept `index_column` of type UInt32 or UInt64 

py-polars/polars/series/series.py
A portion #13161.
Added a few simple examples for `Series.kurtosis`.
=> docs(python): Add examples for `Series.kurtosis`.

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py
A few minor things:
- for `rolling`, `- 1i    (1 index count)` is already documented, I don't an extra paragraph showing it in bold is warranted
- for `rolling_*`, the default is now `closed='right'`, so I think that's what the example should show. I don't think the explanation of `closed='left'` adds much
- for `ewm_*`, note that `adjust=True` is the default (it's quite a long docstring, easier to see it there than to scroll up to the signature)
=> docs(python): Improve docstrings for `ewm_*` and `rolling_*` methods

crates/polars-plan/src/logical_plan/format.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs, crates/polars-plan/src/logical_plan/tree_format.rs, py-polars/tests/unit/operations/unique/test_unique.py
Fix https://github.com/pola-rs/polars/issues/14595.
Also improves the display in `explain()` to show `maintain_order` and `keep_strategy`, as these are useful to know when debugging.
=> fix: Only push predicates depending on the subset columns past `unique()`

crates/polars-lazy/src/frame/pivot.rs, crates/polars-ops/src/frame/pivot/mod.rs, crates/polars/tests/it/core/pivot.rs, docs/src/rust/user-guide/transformations/pivot.rs, py-polars/polars/dataframe/frame.py, py-polars/src/dataframe.rs, py-polars/tests/unit/operations/test_pivot.py
Resolves #12087.
I think we hold off until the next breaking release.
=> feat(python,rust!): Infer `values` columns in `DataFrame.pivot` when `values` is None

.github/workflows/benchmark.yml, .github/workflows/codecov.yml, .github/workflows/docs-global.yml, .github/workflows/test-python.yml, Makefile
Closes #14680
We have to do `unset CONDA_PREFIX` and it works fine.
Unrelated change: looks like `maturin develop` now works without an active virtual environment, so I'm deleting the explicit venv activation.
=> chore(python): Fix `make requirements` when conda environment is active

py-polars/polars/dataframe/_html.py, py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/dataframe/test_repr_html.py, py-polars/tests/unit/test_config.py
Closes https://github.com/pola-rs/polars/issues/14515
* For DataFrames: changed from 25 to 10.
* For Series: changed from 25 to ~20~ 10 also.
* Fix display when row limit is an odd number
~I guess we could also do 10 rows for both?~
=> feat(python): Change default number of rows printed in Notebooks for DataFrame/Series to 10

crates/polars-core/src/datatypes/any_value.rs
This PR improves the organization of the `AnyValue` casting logic. The current logic uses a few helper functions that are somewhat sporadically called, and it makes it a little hard to detect where holes in our casting logic exist.
This implementation has the general format of `match (from_dtype, to_dtype)`, sorted by `from_dtype`, with logic to deal with special cases first, and the non-special cases at the end to catch all remaining. This both removes a few function calls and makes it clearer where future casts should be placed. Overall, the result is a bit cleaner with fewer LOC, fewer function calls, and fewer total matche branches.
=> refactor(rust): Refactor `AnyValue` casting logic

py-polars/polars/api.py, py-polars/polars/dataframe/frame.py, py-polars/polars/datatypes/classes.py, py-polars/polars/expr/expr.py, py-polars/polars/expr/whenthen.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/selectors.py, py-polars/polars/series/series.py
Closes https://github.com/pola-rs/polars/issues/13198
In this PR are "safe" additions of `__slots__`. Mostly for classes that are not usually subclassed by users -  `pl.Expr`, its subclasses and build in namespaces.
`polars.datatypes.classes` also really good candidates, since they are instantiated now, but not included in this PR (yet?). 
Adding `__slots__` for LazyFrame (and `DataFrame`/`Series`) turned out to be a breaking change because of subclassing.
Using `ldf.__class__ = SubClassedLazyFrame`, like in [test_preservation_of_subclasses](https://github.com/pola-rs/polars/blob/bb0081236ec05af304ec36dcf38673b36fdad706/py-polars/tests/unit/test_lazy.py#L1105) is an error because of different object layouts. And even if subclass were to define `__slots__` - they can only be empty, without …
=> perf(python): Add `__slots__` to most Polars classes

crates/polars-plan/src/logical_plan/optimizer/slice_pushdown_lp.rs, crates/polars-plan/src/utils.rs, py-polars/tests/unit/operations/test_slice.py
Fix https://github.com/pola-rs/polars/issues/14349
=> fix: Block slice pushdown past non-literal projections or when the projection doesn't contain any columns from the input

crates/polars-io/src/parquet/read.rs, crates/polars-io/src/parquet/read_impl.rs
Fixes #13507 
When manually setting the ParallelStrategy, it is not being passed down to the ParquetReader. This is because when creating a new BatchedParquetReader, the parallel strategy is set to Row or Column for us. This change allows a parallel strategy to be passed to BatchedParquetReader::new(), defaulting to the original implementation when parallel strategy is set to auto.
=> fix: Fix parallel strategy for LazyFrame not being applied

py-polars/docs/source/reference/expressions/meta.rst, py-polars/docs/source/reference/expressions/miscellaneous.rst, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/datetime.py, py-polars/polars/expr/expr.py, py-polars/polars/expr/meta.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py, py-polars/src/expr/meta.rs, py-polars/tests/unit/test_serde.py
We updated `LazyFrame` in a similar fashion not too long ago.
* Rename `Expr.meta.write_json` to `Expr.meta.serialize`.
* Rename `Expr.from_json` to `Expr.deserialize`.
* It now operates on file inputs instead of a string. This follows the API `LazyFrame.deserialize`. Maybe this doesn't make sense for Expressions though? Or maybe both should read directly from a string? Open to feedback.
=> depr(python): Rename `Expr.meta.write_json/Expr.from_json` to `Expr.meta.serialize/Expr.deserialize`

py-polars/polars/datatypes/classes.py, py-polars/polars/functions/lit.py, py-polars/polars/utils/_construction.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/expr/test_exprs.py, py-polars/tests/unit/sql/test_temporal.py
`None` is not a valid time unit, so it should not be accepted. The user should either pass nothing to use the default value, or pass a valid time unit.
The constructor for `Duration` is already correct.
=> depr(python): Deprecate passing `time_unit=None` to `Datetime` constructor

py-polars/polars/functions/lit.py, py-polars/polars/utils/convert.py, py-polars/tests/unit/utils/test_utils.py
I was refactoring and spotted a performance improvement opportunity.
Instead of converting to datetime and going through that path, there is now a dedicated path for dates.
* Internal conversion util `_date_to_pl_date` :  1.43 µs -> 23.4 ns
* Creating a literal expression `lit` :  23.4 µs -> 10.8 µs
* Creating a Series from a list of a million dates : 2.97s -> 1.14s
=> perf(python): 2-3x speedup in creating literals/Series of type `Date`

py-polars/polars/datatypes/classes.py
Moved some docs from `__init__` to the class docstring, and added some notes to temporal types.
=> docs(python): Improve some DataType docstrings

.github/workflows/codecov.yml, .github/workflows/release-python.yml
Presumably spawned too many threads
```
make[2]: *** read jobs pipe: Resource temporarily unavailable.  Stop.
```
=> ci: Limit CMake threads to fix crash compiling `libz-ng-sys` on macOS

crates/polars-lazy/src/frame/mod.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> fix: Fix `DataFrame.sum` for decimals

docs/user-guide/expressions/plugins.md
Ritchie suggested linking to the tutorial in the last paragraph before "community plugins"
I think it would be good to also link to the plugins keynote from PyData Eindhoven
=> docs: Link to plugins tutorial more prominently

crates/polars-plan/src/logical_plan/functions/mod.rs, crates/polars-plan/src/logical_plan/optimizer/count_star.rs
The alias was ignored in the optimization which lead to schema mismatches between optimized and non-optimized.
=> fix: Fix bug where alias was ignored in COUNT(*) optimization

crates/polars-core/src/utils/mod.rs, crates/polars-ops/src/series/ops/is_in.rs, py-polars/tests/unit/operations/test_is_in.py
fix #14559 
Also a drive by fix for the List[categorical] <-> str where only the first value in the StringChunked was used:
```python
[(["a", "b"], "c"), (["a", "b"], "a")],
schema={"li": pl.List(pl.Categorical), "x": pl.Categorical},
)
print(df.select(pl.col("li").list.contains(pl.col("x").cast(pl.Utf8))))
shape: (2, 1)
┌───────┐
│ li    │
│ ---   │
│ bool  │
╞═══════╡
│ false │
│ false │
└───────┘
```
=> fix: Allow `list.contains()` for list of categoricals

crates/polars-ops/src/series/ops/replace.rs, crates/polars-plan/src/dsl/function_expr/fill_null.rs
`zip_with` already broadcasts efficiently
=> perf: Don't materialize for broadcasting `fill_null` value and default value of `replace`

crates/polars-core/src/frame/group_by/aggregations/mod.rs, py-polars/tests/unit/operations/test_aggregations.py
Fix https://github.com/pola-rs/polars/issues/14734
The rolling kernel was accidentally used sometimes causing it to return NULL
=> fix: Sum after filter in aggregation context sometimes returned NULL

py-polars/polars/_cpu_check.py
Add missing "pclmulqdq" entry to `read_cpu_flags()` to prevent RuntimeError on import of `0.20.12`. (Feature flag is found on bit 1 of ECX[^1]).
Closes #14759.
[^1]: https://en.wikipedia.org/wiki/CPUID
=> fix: add missing "pclmulqdq" instruction to `_cpu_check` ("read_cpu_flags")

crates/polars-parquet/src/arrow/read/schema/convert.rs, crates/polars/tests/it/io/parquet/arrow/read.rs
Parquet files not originating from arrow/polars were still read as `utf8/binary` and then casted to the view types.
This is very expensive. This ensures we read the proper type immediately.
=> perf: parquet elide utf8/binary cast

docs/user-guide/transformations/joins.md
=> docs: Seperate `asof` from join strategy, change parameter from `strategy` to `how` in user guide

Makefile
Two things:
* The maturin installation from the current venv was not used.
* The `RUSTFLAGS` for the native commands were not picked up correctly.
=> chore: Fix Makefile build commands

crates/polars-io/src/cloud/options.rs
This is also the default for `reqwest` client builder and the timeouts are very unpredictable for us.
=> feat: Disable timeouts

crates/polars-arrow/src/io/ipc/write/schema.rs
This refactor reduces some duplication and uses a functional programming style to construct a vector. There *should* not be any functional changes.
I understand that these sorts of changes may not be desired. I mostly opened this to practice the process and I am okay with this being closed.
=> refactor(rust): Extract key value construction

crates/polars-core/src/series/any_value.rs, py-polars/tests/unit/constructors/test_any_value_fallbacks.py, py-polars/tests/unit/testing/test_assert_frame_equal.py
Ref https://github.com/pola-rs/polars/issues/11156
Implement strict construction for primitives:
* Allow any mix of integers as long as they can be cast without overflow.
* Allow constructing `f64` from a mix of `f32/f64`
* Allow constructing `f32` only from `f32`
=> feat(rust): Implement strict/nonstrict conversion for primitive AnyValues

crates/polars-arrow/src/array/binview/mutable.rs, crates/polars-arrow/src/array/indexable.rs, crates/polars-arrow/src/compute/cast/binview_to.rs, crates/polars-arrow/src/compute/cast/mod.rs, crates/polars-io/src/parquet/write.rs, crates/polars-parquet/src/arrow/write/dictionary.rs, py-polars/tests/unit/io/test_parquet.py
=> feat: Ensure binview types are rle-encoded in parquet write

crates/polars-pipe/src/executors/sinks/joins/generic_build.rs, crates/polars-pipe/src/executors/sinks/joins/generic_probe_inner_left.rs, crates/polars-pipe/src/executors/sinks/joins/mod.rs, crates/polars-utils/src/hashing.rs, crates/polars-utils/src/lib.rs, crates/polars-utils/src/partitioned.rs
This can make working with partitioned tables less error prone. Only used now for streaming joins as pre-work for upcoming streaming outer join. Can be used in group-bys and default joins logic as well.
=> refactor(rust): introduce partitioned table

py-polars/polars/io/database.py, py-polars/polars/type_aliases.py, py-polars/pyproject.toml, py-polars/requirements-dev.txt, py-polars/tests/unit/io/files/graph-data/follows.csv, py-polars/tests/unit/io/files/graph-data/user.csv, py-polars/tests/unit/io/test_database_read.py, py-polars/tests/unit/utils/test_deprecation.py
Quite happy with how the `ConnectionExecutor` abstraction is holding up as it only required a few minor tweaks to add support for `kuzu`[^1] graph database queries (which make use of the Cypher[^2] query language). 
Registered it as having Arrow-aware return, so we will always load results efficiently (eg: _not_ via the row iterator), and also made a PR on their side adding direct Polars export support to their QueryResult object. (See: https://github.com/kuzudb/kuzu/pull/2985).
```python
df = pl.read_database(
query = "MATCH (a:User)-[f:Follows]->(b:User) RETURN a.name, f.since, b.name",
connection = kuzu_connection,
)
```
[^1]: KùzuDB: https://kuzudb.com/
[^2]: Cypher: https://kuzudb.com/docusaurus/cypher/
=> feat(python): support use of KùzuDB via `pl.read_database`

crates/polars-arrow/src/array/primitive/mutable.rs, crates/polars-core/src/frame/mod.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, crates/polars-lazy/src/physical_plan/streaming/checks.rs, crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs, crates/polars-lazy/src/tests/streaming.rs, crates/polars-ops/src/chunked_array/gather/chunked.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-ops/src/frame/join/general.rs, crates/polars-ops/src/frame/join/hash_join/mod.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_left.rs, crates/polars-ops/src/frame/join/mod.rs, crates/polars-pipe/src/executors/sinks/joins/generic_build.rs, crates/polars-pipe/src/executors/sinks/joins/generic_probe_inner_left.rs, crates/polars-pipe/src/executors/sinks/joins/generic_probe_outer.rs, crates/polars-pipe/src/executors/sinks/joins/mod.rs, crates/polars-pipe/src/executors/sinks/joins/row_values.rs, crates/polars-pipe/src/pipeline/convert.rs, crates/polars-pipe/src/pipeline/dispatcher/drive_operator.rs, crates/polars-pipe/src/pipeline/dispatcher/mod.rs, crates/polars-plan/src/frame/opt_state.rs, crates/polars-utils/src/index.rs, crates/polars-utils/src/partitioned.rs, py-polars/tests/unit/streaming/test_streaming_join.py
Also improves performance of chunked gather by storing `ChunkId` instead of `Option<ChunkId>`, meaning we save 50% space in cache.
=> feat: Streaming outer joins

crates/polars-io/src/pl_async.rs
On discord users mentioned a deadlock, so never await the rwlock.
We also don't tune if users set the budget manually. This will help testing if the tuner is the culprit.
=> feat: try-improve concurrency tuner

.github/workflows/codecov.yml, .github/workflows/test-rust.yml, crates/Makefile, crates/polars-compute/src/filter/boolean.rs
This shouldn't affect any deployed polars code since we only ever call pext64_polyfill if our mask is non-zero, hence chore and not a fix. Nevertheless, this test should be run, and it should pass.
=> chore: run and fix pext64_polyfill test

crates/polars-arrow/Cargo.toml, crates/polars-io/Cargo.toml
Added some conditional feature flags so that `polars-io` compiles on its own. Need this to run some unit tests without recompiling the whole project. 
P.S. What is this legacy timezone stuff?
=> chore(rust): Make polars-io compile on its own

crates/polars-arrow/src/compute/cast/mod.rs, crates/polars-arrow/src/compute/take/bitmap.rs, crates/polars-arrow/src/compute/take/boolean.rs, crates/polars-arrow/src/legacy/index.rs, crates/polars-arrow/src/legacy/kernels/fixed_size_list.rs, crates/polars-arrow/src/legacy/kernels/list.rs, crates/polars-arrow/src/legacy/kernels/set.rs, crates/polars-arrow/src/legacy/kernels/sort_partition.rs, crates/polars-arrow/src/legacy/kernels/sorted_join/mod.rs, crates/polars-arrow/src/legacy/kernels/take_agg/mod.rs, crates/polars-core/src/chunked_array/ops/chunkops.rs, crates/polars-core/src/datatypes/aliases.rs, crates/polars-core/src/frame/group_by/into_groups.rs, crates/polars-core/src/frame/group_by/perfect.rs, crates/polars-core/src/frame/top_k.rs, crates/polars-core/src/prelude.rs, crates/polars-core/src/series/implementations/null.rs, crates/polars-io/src/options.rs, crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs, crates/polars-ops/src/chunked_array/gather/chunked.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-ops/src/frame/join/general.rs, crates/polars-ops/src/series/ops/search_sorted.rs, crates/polars-pipe/src/executors/sinks/joins/generic_probe_inner_left.rs, crates/polars-pipe/src/executors/sinks/joins/generic_probe_outer.rs, crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/mod.rs, crates/polars-utils/src/index.rs, crates/polars-utils/src/lib.rs
This was defined on multiple places for legacy reasons. This cleans that up.
=> refactor(rust): centrally define IdxSize

crates/polars-arrow/src/bitmap/immutable.rs, crates/polars-arrow/src/legacy/kernels/sorted_join/left.rs, crates/polars-arrow/src/legacy/kernels/sorted_join/mod.rs, crates/polars-core/src/chunked_array/ops/gather.rs, crates/polars-lazy/src/physical_plan/expressions/window.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-ops/src/frame/join/hash_join/mod.rs, crates/polars-ops/src/frame/join/hash_join/multiple_keys.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_left.rs, crates/polars-ops/src/frame/join/hash_join/sort_merge.rs, crates/polars-utils/src/index.rs, crates/polars-utils/src/lib.rs
This fits twice as much of them on a cache line.
=> perf: Reduce size of optional join-indexes

crates/polars-lazy/src/physical_plan/executors/scan/csv.rs
The current code confused me so I tried to simplify it. I think I succeeded. Learnt about the existence of [`Arc::unwrap_or_clone`](https://doc.rust-lang.org/stable/std/sync/struct.Arc.html#method.unwrap_or_clone) in rustc 1.76.0+.
=> refactor(rust): Simplify computation of `with_columns` attribute in physical csv scanner of default engine.

crates/polars-arrow/src/bitmap/iterator.rs, crates/polars-compute/src/filter/boolean.rs, crates/polars-compute/src/filter/mod.rs, crates/polars-compute/src/filter/primitive.rs, crates/polars-compute/src/filter/scalar.rs
This PR uses the new boolean filters to handle nulls in all our filters, and has a reworked scalar path filter. It also lays the groundwork for easily slotting in specific SIMD paths instead of the scalar later.
Modest speedups all-around, with only very specific combinations being slightly slower. Below are some sample benchmarks for n = 10^8 on Apple M1.
Without any nulls in the payload:
```
selectivity       main         branch  speedup
u8
0.00001     0.03067962     0.00971654     3.2x
0.00010     0.03578900     0.01379362     2.6x
0.00100     0.05605988     0.02842633     2.0x
0.01000     0.10832329     0.05732238     1.9x
0.10000     0.18866021     0.14063879     1.3x
0.50000     0.38846837     0.25560483     1.5x
0.90000     0.62037029     0.28825442     2.2x
0.99000     0.41020429 …
```
=> perf: rework scalar filter kernels

py-polars/polars/meta/versions.py
closes: https://github.com/pola-rs/polars/issues/14868
This will make fastexcel appear in `pl.show_versions`
=> feat(python): Add `fastexcel` to `show_versions`

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/io/test_delta.py
`deltalake` changed their public API. They no longer have an `overwrite_schema` parameter. We exposed this parameter directly in our API.
I removed this parameter to defer directly to the `deltalake` API through `delta_write_options`. Users can pass `delta_write_options={"schema_mode": "overwrite"}` to get the same result.
Also had to update some tests as deltalake handles timezones differently now.
@ion-elgreco FYI
=> depr(python): Deprecate `overwrite_schema` parameter for `DataFrame.write_delta`

crates/polars-arrow/src/array/binview/mod.rs, crates/polars-arrow/src/array/binview/view.rs, crates/polars-arrow/src/array/mod.rs, crates/polars-ops/src/chunked_array/gather/chunked.rs
This still copy the string/binary data instead of the views. Ensure we now only copy the views and keep the buffers as is (unless we need to gc).
=> perf: Optimize chunked-id gather for binaryviews

CONTRIBUTING.md, README.md, docs/_build/snippets/under_construction.md, py-polars/debug/launch.py
Resolves #14855.
Made a couple minor edits to other references:
* Use `contributing guide` consistently across the documentation.
* Removed `CONTRIBUTING.md` as it is no longer referenced.
* Provided direct link to appropriate section in the `launch.py` exception message.
=> docs: Update contributing link

crates/polars-core/src/datatypes/dtype.rs, py-polars/tests/unit/datatypes/test_decimal.py
Now that decimals can be sorted (#14649), `is_ord` can be true for `DataType::Decimal`. This will in turn fix the following:
```python
pl.DataFrame({"a": [D("1.0"), D("2.0")]}).max()
```
output:
```
shape: (1, 1)
┌──────────────┐
│ a            │
│ ---          │
│ decimal[*,1] │
╞══════════════╡
│ null         │
└──────────────┘
```
expected:
```
shape: (1, 1)
┌──────────────┐
│ a            │
│ ---          │
│ decimal[*,1] │
╞══════════════╡
│ 2            │
└──────────────┘
```
Similar to #14652
=> fix: Fix `DataFrame.min`/`max` for decimals

.github/workflows/release-python.yml
The latest release of the PyPI publish action is broken. This commit includes the fix.
=> ci(python): Pin PyPI publish action to commit

py-polars/polars/io/database.py, py-polars/tests/unit/io/test_database_read.py
Closes #14631.
The `adbc` engine only has limited support for "execute_options" (and `connectorx` has no support at all), but we can still make the API more consistent for those cases where such options _are_ valid (such as use of "parameters" with the `adbc` engine and a SQLite backend).
=> feat(python): add "execute_options" support for `read_database_uri`

crates/polars-io/src/ipc/ipc_file.rs
Alternatively, we could do the conversion again if it has not occurred yet. 
The column name to indices conversion happens in multiple places in the code base. 
In those places we use only the column names if provided and ignore the column indices (projection) without warning. We could take the union instead, print a warning about ignoring the indices when the names are provided, or do nothing.
Depending on this choice, we may be able to represent the projection with a better data structure and deduplicate the conversion code.
=> test(rust): Make assumption about column name to index conversion having occurred explicit

crates/polars-core/src/config.rs, crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs, crates/polars-pipe/src/executors/sources/parquet.rs
Not sure about the name.
Perhaps we should parse and provide all of polars' configuration coming from env vars in one struct and cache it in a once cell. I don't think it would do much from a performance point of view. I also am not sure that would help organisationally because you're just putting things that look the same together rather than organizing by functionality. So... just doing the simplest thing now.
=> refactor: Deduplicate `POLARS_FORCE_ASYNC` env var parsing

py-polars/polars/meta/versions.py, py-polars/pyproject.toml, py-polars/requirements-dev.txt
Minor housekeeping; `fastexcel` was listed in "show_versions" but wasn't registered in the optional deps for install when doing `pip install "polars[all]"`. Refreshed the docstring output from "show_versions" while I was at it.
=> chore: optional deps should include `fastexcel` 

crates/polars-compute/src/filter/avx512.rs, crates/polars-compute/src/filter/mod.rs, crates/polars-compute/src/filter/primitive.rs, crates/polars-compute/src/filter/scalar.rs, crates/polars-compute/src/lib.rs, py-polars/tests/unit/operations/test_filter.py
This should improve performance when data is in cache, and it seems to improve performance by ~2x regardless for filtering u8s if AVX-512 is available. Unfortunately the speedups for other types when data doesn't fit in cache weren't there, I didn't realize the scalar path already achieves single-threaded memory bandwidth (at least on the machine I tested).
=> perf: add basic AVX-512 filters

py-polars/polars/io/database.py, py-polars/tests/unit/io/test_database_read.py
Closes #14906.
If nothing is yielded from `read_arrow_batches_from_odbc` (eg: no matching rows for the given query), we now construct an empty `RecordBatch` with the correct schema and yield that, allowing for successful frame init (vs the current `ValueError`).
Reproduced the issue (and validated the fix) against a local SQL Server instance running in a Docker container, connecting via ODBC.
=> fix(python): `read_database` now properly handles empty result sets from `arrow-odbc`

crates/polars-arrow/src/bitmap/utils/mod.rs, crates/polars-arrow/src/legacy/is_valid.rs, crates/polars-parquet/src/arrow/write/dictionary.rs, py-polars/tests/unit/io/test_parquet.py
=> fix: Fix sliced dictionary state in parquet

py-polars/polars/series/series.py, py-polars/tests/unit/series/test_series.py
=> fix(python): Add `drop_first` parameter to `Series.to_dummies`

.github/workflows/codecov.yml, .github/workflows/release-python.yml, Cargo.lock, py-polars/tests/unit/dataframe/test_df.py
`cc` `1.0.90` fixed the "Resource temporarily unavailable" error: https://github.com/rust-lang/cc-rs/pull/985.
=> chore: Update Cargo.lock and remove cmake limit workaround

crates/polars-arrow/src/bitmap/mutable.rs, crates/polars-compute/src/filter/boolean.rs
Fixes https://github.com/pola-rs/polars/issues/14914.
This only patches the what triggers this problem however, the real problem is that `MutableBitmap` has the following invariant:
```rust
// invariant: length.saturating_add(7) / 8 == buffer.len();
```
~~But it does nothing to ensure that invariant is true during initialization (and I haven't yet checked if it maintains it).~~
From a cursory glance it does seem to maintain the invariant, and now I also made sure it satisfies the invariant during initialization.
=> fix: boolean filter gave overly large buffers to Bitmap::from_u8_vec

py-polars/polars/_utils/construction.py
Closes #14919.
The reported error was not actually related to our database code, but it exposed a bug initialising from single `RecordBatch` objects if the user has a pyarrow version <= 12. 
We were relying on `RecordBatch` having the "column_names" attribute if no schema was given, but this attribute isn't found on `RecordBatch` until pyarrow 13.
The fix is straightforward; we can generically use `obj.schema.names` instead, as the "schema" attribute exists on both `Table` _and_ `RecordBatch` objects across all versions.
=> fix(python): Fix frame init from single `RecordBatch` objects when `pyarrow <= 12`

crates/polars-arrow/src/temporal_conversions.rs, crates/polars-core/src/chunked_array/temporal/conversion.rs, crates/polars-core/src/chunked_array/temporal/mod.rs, crates/polars-lazy/src/tests/queries.rs, crates/polars-plan/src/dsl/function_expr/temporal.rs, crates/polars-plan/src/logical_plan/lit.rs, crates/polars-time/src/chunkedarray/mod.rs, crates/polars-time/src/date_range.rs, crates/polars-time/src/group_by/dynamic.rs, crates/polars-time/src/windows/test.rs
@MarcoGorelli Could you check this out to make sure I didn't mess stuff up?
=> chore(rust): fix chrono deprecation warnings

crates/polars-parquet/src/arrow/read/deserialize/boolean/basic.rs, crates/polars-parquet/src/parquet/deserialize/hybrid_rle.rs
Fixes #14902
I don't like the way we force everything to be an iterator and map the result. This is overly expensive. Will go back to the drawing board on this one.
=> fix: parquet rle boolean decoder

py-polars/polars/io/database.py, py-polars/tests/unit/io/test_database_read.py
Minor follow-up to #14916.
* Additionally makes the behaviour consistent between ODBC queries and all other connection types when setting `iter_batches=True` _and_ we have an empty result set (the batch _iterator_ should be empty, vs a single RecordBatch with no rows).
* Adds "empty dataset" test coverage for KùzuDB.
=> fix(python): Ensure consistent `read_database` behaviour with empty ODBC "iter_batches"

crates/polars-core/src/series/mod.rs, py-polars/tests/unit/streaming/test_streaming_categoricals.py
=> fix: Don't rechunk categoricals when moving to physical

crates/polars-arrow/src/compute/take/bitmap.rs, crates/polars-arrow/src/compute/take/boolean.rs, crates/polars-arrow/src/compute/take/structure.rs, py-polars/tests/unit/datatypes/test_list.py
Fixes https://github.com/pola-rs/polars/issues/14927.
=> fix: Don't access out-of-bounds for null indices in bitmap gather

py-polars/polars/_utils/construction.py, py-polars/src/series/construction.rs, py-polars/tests/unit/datatypes/test_list.py
Currently, constructing a Series from a list of Series which also contains Nones raises:
```python
inner = pl.Series("inner", [1, 2, 3])
pl.Series("a", [inner, None])
```
This PR fixes this:
```python
inner = pl.Series("inner", [1, 2, 3])
pl.Series("a", [inner, None])
```
Output:
```shape: (2,)
Series: 'a' [list[i64]]
[
[1, 2, 3]
null
]
```
=> fix: Do not raise when constructing from a list of Series with Nones

crates/polars-parquet/src/arrow/write/mod.rs, crates/polars-parquet/src/arrow/write/nested/def.rs, crates/polars-parquet/src/arrow/write/nested/mod.rs, crates/polars-parquet/src/arrow/write/nested/rep.rs, crates/polars-parquet/src/arrow/write/pages.rs, py-polars/tests/unit/io/test_parquet.py
=> feat: Support writing `Array` type in parquet

crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/boolean/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/nested.rs, crates/polars-parquet/src/parquet/deserialize/hybrid_rle.rs, crates/polars-parquet/src/parquet/deserialize/utils.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/decoder.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs, crates/polars-utils/src/iter/fallible.rs, crates/polars-utils/src/iter/mod.rs, crates/polars/tests/it/io/parquet/read/binary.rs, crates/polars/tests/it/io/parquet/read/fixed_binary.rs, crates/polars/tests/it/io/parquet/read/primitive.rs, crates/polars/tests/it/io/parquet/read/primitive_nested.rs, crates/polars/tests/it/io/parquet/read/struct_.rs, crates/polars/tests/it/io/parquet/read/utils.rs
=> perf: hoist errors out of iterators in parquet

crates/polars-arrow/src/array/growable/binview.rs, crates/polars-pipe/src/executors/sinks/io.rs, crates/polars-pipe/src/executors/sinks/sort/ooc.rs, crates/polars-pipe/src/executors/sinks/sort/sink.rs, crates/polars-pipe/src/executors/sinks/sort/source.rs
Ensures the `binview` garbage collects after partitioning otherwise we multiply data by the factor of paritititons, which can be several orders of magnitude. :/
Also make the source phase make more use of available memory so that we get better parallelism. Fixes #14948
That query is now bound by the sink_parquet, which is still slow.
=> fix: ooc-sort issues

crates/polars-time/src/windows/duration.rs, py-polars/tests/unit/datatypes/test_temporal.py
=> fix: raise proper error instead of panicking when result of truncation is non-existent datetime

crates/polars-io/src/parquet/write.rs, crates/polars-pipe/src/executors/sinks/output/parquet.rs
This greatly speeds up sinking to parquet. What was a single threaded blocker is now fully parallel and only uses the writer thread for IO.
#14948 is now fully parallel
=> perf: Ensure parallel encoding/compression in `sink_parquet`

crates/polars-core/src/chunked_array/logical/categorical/mod.rs, py-polars/tests/unit/datatypes/test_enum.py
Resolves #14900.
@c-peters the downside of this PR is that it no longer prints your nice error messages when a value falls outside of the target Enum's categories, and instead assigns it a null value. Strict (normal) casts will still properly fail the casts because of the new null values introduced, but non-strict casts now convert values outside to null. On the plus side, this reduces the code a bit and removes two levels of option/result indirection. Here is the example from the issue after this PR:
```
>>> pl.Series(["a", "b"]).cast(pl.Enum(["a"]), strict=False)
shape: (2,)
Series: '' [enum]
[
"a"
null
]
>>> pl.Series(["a", "b"], dtype=pl.Categorical).cast(pl.Enum(["a"]), strict=False)
shape: (2,)
Series: '' [enum]
[
"a"
null
]
>>> pl.Series(["a", "b"], …
```
=> fix(rust, python): allow nonstrict cast of categorical/enum to enum

crates/polars-pipe/src/executors/sinks/mod.rs, crates/polars-pipe/src/executors/sinks/sort/ooc.rs, crates/polars-pipe/src/executors/sinks/sort/sink.rs, crates/polars-pipe/src/executors/sinks/sort/source.rs
```
OOC sort started
Temporary directory path in use: temp
run UdfExec
RUN STREAMING PIPELINE
parquet -> sort -> parquet_sink
RefCell { value: [] }
STREAMING CHUNK SIZE: 2941 rows
finished sinking into OOC sort in 3.982244806s
full file dump of OOC sort took 5.155624213s
processing 245 files
partitioning sort took: 5.063799475s
spilling all partitioned files took: 7.694338058s
started sort source phase
sort source phase took: 3.780204067s
full ooc sort took: 16.632243722s
```
Shows we are twiddling thumbs waiting for all files to be spilled. We probably can do something useful in that time.
=> feat: expose timings in verbose state of OOC sort

crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs, py-polars/tests/unit/datatypes/test_temporal.py
=> fix: replace_time_zone with single-null-element "ambiguous" was panicking

py-polars/polars/_utils/construction.py, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/io/test_json.py, py-polars/tests/unit/series/test_describe.py, py-polars/tests/unit/test_serde.py
When a Series of lists is constructed, it uses the AnyValue interface even when the dtype is provided. Besides the performance implications, this often leads to incorrect results because even though the type is provided, it is inferred anyhow and then, if the inferred type differs from the provided type, the result is cast to the latter. 
Here are some examples of incorrect cases:
```python
u64_max = (2**64) - 1
pl.Series("a", [[u64_max]], dtype=pl.List(pl.UInt64))
pl.Series("a", [[u64_max, 1]], dtype=pl.List(pl.UInt64))
```
*This case has been reported in #14277.
This PR changes the way a Series of lists is constructed when the dtype is provided, while still falling back to AnyValue when it is not. It does so by recursively applying `sequence_to_pyseries` to every …
=> fix(python): Use primitive constructors to create a Series of lists when dtype is provided

crates/polars-arrow/src/compute/aggregate/memory.rs, crates/polars-pipe/src/executors/sinks/sort/ooc.rs, crates/polars-pipe/src/executors/sinks/sort/sink.rs, crates/polars-pipe/src/executors/sinks/sort/source.rs, py-polars/polars/dataframe/frame.py
Don't force spilling before going to source phase. And try to keep in memory when we can.
=> perf: OOC sort improvements

crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs, py-polars/tests/unit/test_errors.py
=> fix: Don't panic in `string_addition_to_linear_concat`

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py
=> docs(python): Fix inadvertent swap of `new` and `old` parameters in `replace` description

crates/polars-core/src/lib.rs
This adds names to the threads in the Rayon thread pool. They are configurable via the `POLARS_THREAD_NAME` environment variable and default to `polars-{thread_idx}`.
Example without and with the change:
=> feat: Add thread names to rayon thread pool

crates/polars-parquet/src/arrow/read/statistics/list.rs, crates/polars-parquet/src/arrow/read/statistics/mod.rs, py-polars/tests/unit/io/test_parquet.py
=> feat: Support Array statistics in parquet

crates/polars-arrow/src/io/ipc/read/file.rs, crates/polars-arrow/src/io/ipc/read/mod.rs, crates/polars-io/src/ipc/ipc_file.rs, crates/polars-io/src/ipc/ipc_reader_async.rs, crates/polars-io/src/ipc/mod.rs, crates/polars-lazy/src/physical_plan/executors/scan/ipc.rs, crates/polars-lazy/src/physical_plan/planner/lp.rs, crates/polars-lazy/src/scan/ipc.rs, crates/polars-lazy/src/tests/io.rs, crates/polars-plan/src/logical_plan/builder.rs, crates/polars-plan/src/logical_plan/file_scan.rs, crates/polars-plan/src/logical_plan/functions/count.rs, py-polars/polars/io/ipc/functions.py, py-polars/polars/lazyframe/frame.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_lazy_ipc.py
=> feat(rust): Implement IpcReaderAsync

crates/polars-core/src/series/any_value.rs, py-polars/tests/unit/constructors/test_any_value_fallbacks.py
This does not impact the Python side as the Python constructors do not end up in this code (yet).
This more closely resembles existing behavior on the Python side - data with mixed types and no valid supertype are read as Object types.
=> feat(rust!): Return error when no supertype can be determined in AnyValue constructor when `strict=false`

crates/polars-core/src/series/any_value.rs, py-polars/polars/_utils/construction/dataframe.py, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py, py-polars/tests/unit/constructors/test_dataframe.py
Ref https://github.com/pola-rs/polars/issues/14427
The DataFrame constructor had no `strict` parameter, while the Series constructor does. Non-strict construction is useful when the input data is not guaranteed to be clean.
```python
data = {"a": [-1, 0, 1]}
df = pl.DataFrame(data, schema={"a": pl.UInt8})
df = pl.DataFrame(data, schema={"a": pl.UInt8}, strict=False)
print(df)
```
```
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ u8   │
╞══════╡
│ null │
│ 0    │
│ 1    │
└──────┘
```
In this example, the result is similar to a non-strict cast of the data to the desired data type.
This will also allow handling mixed ints/floats cleanly in the future.
**The default behavior is unchanged**, as previously DataFrame construction was always strict, corresponding to …
=> feat(python): Add `strict` parameter to `DataFrame` constructor to allow non-strict construction

crates/polars-arrow/src/compute/cast/mod.rs, py-polars/tests/unit/operations/test_cast.py
Resolves #15012.
All other numeric types can cast to boolean, no reason decimal shouldn't either, it's perfectly well-defined.
OP's test now passes:
```python
from decimal import Decimal as Dec
import pytest
@pytest.mark.parametrize(
("x", "y", "z"),
[
(1, 2, 3),
(0, 2, 3),
(0, 0, 0),
],
)
def test_cast_decimal_to_boolean(x, y, z):
col = pl.Series("a", [Dec(str(x)), Dec(str(y)), Dec(str(z))])
mask = col.cast(pl.Boolean)
other_mask = pl.Series("a", [bool(x), bool(y), bool(z)])
assert mask.dtype == pl.Boolean
assert (mask == other_mask).all()
assert mask.any() == any((x, y, z))
assert mask.all() == all((x, y, z))
```
```
(.venv) mcrumiller@Saline-PC:~/projects/polars/py-polars/scripts$ pytest check_decimal.py
=============================================================== …
```
=> feat: Allow cast of decimal to boolean

crates/polars-ops/src/frame/join/general.rs, py-polars/tests/unit/operations/test_join.py
closes #15035 
The example in that issue would now show:
```
polars.exceptions.DuplicateError: column with name 'c_right' already exists.
You may want to try:
- renaming the column prior to joining
- using `suffix` to specify a suffix different to the default one (`_right`)
```
=> feat: Raise informative error message when join would introduce duplicate column name

crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs, crates/polars-plan/src/utils.rs, py-polars/tests/unit/test_predicates.py
=> fix: Block predicate pushdown on equality that are use in join

crates/polars-pipe/src/executors/sinks/group_by/aggregates/convert.rs, crates/polars-pipe/src/executors/sinks/group_by/aggregates/count.rs, crates/polars-pipe/src/executors/sinks/group_by/aggregates/interface.rs, crates/polars-pipe/src/executors/sinks/group_by/generic/hash_table.rs, py-polars/tests/unit/streaming/test_streaming_group_by.py
=> fix: Don't count nulls in streaming `count` agg

crates/polars-io/src/parquet/read_impl.rs
=> fix: Prevent "index out of range for slice" error in parquet reader

crates/polars-arrow/src/legacy/kernels/time.rs, crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs, crates/polars-time/src/month_start.rs, crates/polars-time/src/utils.rs, crates/polars-time/src/windows/duration.rs, py-polars/polars/expr/datetime.py, py-polars/polars/expr/string.py, py-polars/polars/functions/as_datatype.py, py-polars/polars/series/datetime.py, py-polars/polars/series/string.py, py-polars/polars/type_aliases.py, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/namespaces/test_strptime.py
~~to be rebased onto https://github.com/pola-rs/polars/pull/14958~~
Quick demo of what this lets you do:
```python
In [13]: s = pl.datetime_range(datetime(2018, 10, 28), datetime(2018, 10, 28, 5), '1h', eager=True)
...: 
In [14]: s
Out[14]: 
shape: (6,)
Series: 'literal' [datetime[μs]]
[
2018-10-28 00:00:00
2018-10-28 01:00:00
2018-10-28 02:00:00
2018-10-28 03:00:00
2018-10-28 04:00:00
2018-10-28 05:00:00
]
In [15]: s.dt.replace_time_zone('Europe/Amsterdam', ambiguous='null')
Out[15]: 
shape: (6,)
Series: 'literal' [datetime[μs, Europe/Amsterdam]]
[
2018-10-28 00:00:00 CEST
2018-10-28 01:00:00 CEST
null
2018-10-28 03:00:00 CET
2018-10-28 04:00:00 CET
2018-10-28 05:00:00 CET
]
```
towards #11579. Based on https://github.com/pola-rs/polars/issues/14842#issuecomment-1977297717, I think …
=> feat: let "ambiguous" take "null" value

crates/polars-compute/src/min_max/simd.rs, py-polars/tests/unit/series/test_series.py
Fixes https://github.com/pola-rs/polars/issues/15058.
=> fix: return NaN for all-NaN min/max

crates/polars-core/src/series/any_value.rs
Just extracting some logic into functions and moving some stuff around.
=> refactor(rust): Minor refactor of Rust any value constructors

py-polars/polars/series/struct.py
Some missing examples in struct docstrings
=> docs(python): Add missing docstring examples in the Struct namespace

py-polars/polars/dataframe/frame.py, py-polars/polars/io/database.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/io/test_database_read.py
Closes #15059.
If not using an Arrow-aware driver or the "schema_overrides" parameter, and a column starts with  > 100 `null` values, we need to expose the "infer_schema_length" parameter to allow for more generous dtype inference. (The other options are preferred, but we still need to make this parameter available if they cannot be used).
=> feat(python): Expose `infer_schema_length` parameter on `read_database`

crates/polars-core/src/chunked_array/ops/aggregate/mod.rs, crates/polars-core/src/chunked_array/ops/float_sorted_arg_max.rs, crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-core/src/chunked_array/ops/search_sorted.rs, crates/polars-core/src/utils/mod.rs, crates/polars-ops/src/series/ops/arg_min_max.rs, crates/polars-ops/src/series/ops/mod.rs, crates/polars-ops/src/series/ops/search_sorted.rs, py-polars/tests/unit/datatypes/test_float.py
Fixes https://github.com/pola-rs/polars/issues/12931.
This PR uses a binary search to find non-NaN values for the sorted max/arg_max on floats (if they exist). In the case where all non-null values are NaNs, then the result will be NaN (note the result for all-null is still null).
Part of the binary search code was refactored and moved from `polars-ops` to `polars-core` to support this.
=> fix: Return largest non-NaN value for `max()` on sorted float arrays if it exists instead of NaN

crates/polars-io/src/cloud/adaptors.rs, crates/polars-io/src/cloud/glob.rs, crates/polars-io/src/cloud/mod.rs, crates/polars-io/src/cloud/object_store_setup.rs, crates/polars-io/src/cloud/options.rs, crates/polars-io/src/cloud/polars_object_store.rs, crates/polars-io/src/ipc/ipc_reader_async.rs, crates/polars-io/src/parquet/async_impl.rs, crates/polars-io/src/parquet/read.rs, crates/polars-parquet/src/parquet/mod.rs, crates/polars-pipe/src/pipeline/convert.rs, crates/polars-plan/src/logical_plan/file_scan.rs, crates/polars-plan/src/logical_plan/mod.rs
Fixes https://github.com/pola-rs/polars/issues/15032
For the record, I do like the idea of the `AsyncRead` and `AsyncSeek` and `AsyncWrite` abstraction. We just want to eliminate the possibility of the implementation causing network connection resets. Maybe I have to split the object store deduplication from this PR. 
@ritchie46 is there any way we can determine whether this solves https://github.com/pola-rs/polars/issues/14384?
=> refactor(rust): Use ObjectStore instead of AsyncRead in parquet get metadata

crates/polars-core/src/chunked_array/mod.rs, crates/polars-core/src/chunked_array/ops/append.rs, py-polars/tests/unit/operations/test_sort.py
Fixes https://github.com/pola-rs/polars/issues/15072.
Existing releases are incorrectly setting the sorted flag:
```python
s = pl.Series([None, 1])
out = pl.concat(3 * [s.sort()])
print(out)
shape: (4,)
Series: '' [i64]
[
null
1
null
1
]
print(out.flags)
{'SORTED_ASC': True, 'SORTED_DESC': False}
^^^^
```
=> fix: Incorrectly preserved sorted flag when concatenating sorted series containing nulls

crates/polars-core/src/chunked_array/cast.rs, py-polars/tests/unit/operations/test_cast.py, py-polars/tests/unit/test_errors.py
Closes https://github.com/pola-rs/polars/issues/15029
You could cast Array types to a different width, resulting in a width that did not match the data.
I also added a fast path for casting List/Array to the same dtype (clone).
=> fix: Raise error when casting Array to different width

crates/polars-core/src/series/mod.rs, crates/polars-plan/src/dsl/mod.rs, py-polars/src/series/aggregation.rs, py-polars/tests/unit/test_errors.py
Prevent the following from panicking:
```python
pl.Series("", [[1, 2]]).product()
```
and instead make it behave like:
```python
pl.Series("", [[1, 2]]).sum()
```
=> fix: Propagate error instead of panicking when calling `product` on an invalid type

crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, crates/polars-pipe/src/executors/sinks/sort/sink.rs
Resolves #15099.
Also found one more `eprintln` that wasn't properly wrapped.
Not worth adding a unit test, but OP's example no longer prints the result to stderr.
=> fix(rust): Ensure `eprintln!` is only called within debug/verbose context

crates/polars-core/src/chunked_array/mod.rs, crates/polars-core/src/chunked_array/ops/append.rs, py-polars/tests/unit/operations/test_sort.py
Minor perf :)
```python
pl.concat(
(
pl.Series([3, 2]).set_sorted(descending=True),
pl.Series([1])
)
).flags
```
`{'SORTED_ASC': False, 'SORTED_DESC': False}`
`{'SORTED_ASC': False, 'SORTED_DESC': True}`
=> perf: Coerce sorted flag of unit arrays during concat

crates/polars-core/src/frame/mod.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, py-polars/tests/unit/operations/test_aggregations.py, py-polars/tests/unit/test_schema.py
=> fix: Output `u32` when `sum_horizontal` provided with single boolean column

crates/polars-io/src/csv/parser.rs
=> fix(rust): use wrapping_add in csv line snooping

crates/polars-plan/src/dsl/function_expr/rolling.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
closes #15087 
the example from the linked issue would now raise
```
polars.exceptions.InvalidOperationError: in `rolling_min` operation, `by` argument of dtype `i64` is not supported (expected `date/datetime`)
```
=> feat: raise informative error for rolling_* aggs with `by` of invalid dtype

crates/polars-row/src/decode.rs, py-polars/tests/unit/streaming/test_streaming_group_by.py
=> fix: Support BinaryView in row decoder to prevent a panic in streaming group by

py-polars/tests/unit/io/test_scan.py
Ensure files contain multiple chunks where the format supports it. Add more tests
=> test: Extend and speed up scan tests

py-polars/polars/datatypes/convert.py, py-polars/polars/io/database.py, py-polars/tests/unit/io/test_database_read.py
Ref: https://github.com/pola-rs/polars/pull/15076#issuecomment-1999142134
Additional layer of `dtype` inference for query results that do not return Arrow data directly, and that do not have an explicit "schema_overrides" entry. 
This update adds support for inferring more accurate dtypes from the two simplest flavours of cursor "type_code"[^1] description, specifically simple python types (eg: `datetime`, `int`, `str`) and string descriptions (eg: "varchar", "double", "array[float4]"). The string-based inference is, by necessity, quite flexible/involved.
Also, if set in the cursor description, the "internal_size", "precision", and "scale" entries are also used to further refine the inferred dtypes (eg: if we have "type_code" = `int` and internal_size=4, we can infer the more accurate …
=> feat(python): improved dtype inference/refinement for `read_database` results

py-polars/polars/_utils/construction/series.py, py-polars/tests/unit/constructors/test_series.py
=> fix(python): Fix constructing a Series from a list of Series with given dtype

py-polars/polars/convert.py
Just something super minor I ran into while working on the code in this module. There are probably very few people using this parameter name directly as a keyword argument.
`tbl` isn't really in line with the naming conventions we usually use (write out the words in full). Also, when it's a Series, 'table' doesn't make much sense.
Better to just use `data` as a parameter name, matching all other `from_x` functions. It's just data in a specific format.
I also moved it some lines down the module because it's not as important as other functions like `from_pandas` etc.
=> depr(python): Rename `from_repr` parameter from `tbl` to `data`

py-polars/polars/convert.py, py-polars/polars/dataframe/frame.py
Following up on https://github.com/pola-rs/polars/pull/15034
These use the same logic as the DataFrame constructor, so they should also get a `strict` parameter.
=> feat(python): Add `strict` parameter to `from_dict/from_records`

crates/polars-arrow/Cargo.toml, crates/polars-parquet/Cargo.toml
Closes #15143
Not 100% sure about this one. Will sleep on it.
=> chore(rust): Set dual license for `polars-arrow` and `polars-parquet`

crates/polars-error/src/lib.rs, py-polars/src/series/construction.rs, py-polars/tests/unit/constructors/test_any_value_fallbacks.py, py-polars/tests/unit/constructors/test_dataframe.py, py-polars/tests/unit/constructors/test_series.py, py-polars/tests/unit/datatypes/test_decimal.py
The constructors would various errors depending on where they would fail, while the cause was the same: mixed types in the data. This makes sure the same error type is raised everywhere (TypeError) and includes a hint to set `strict=False`.
=> fix(python): Consistently raise `TypeError` on constructor failure

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py
Closes #15185.
Our `is_between` functionality is correct, and consistent with other implementations (see the equivalent `BETWEEN` keyword in SQL[^1] for an example of this), but we can better document the behaviour when `lower_bound > upper_bound`.
* Added a "Notes" section and a new example that includes this case.
[^1]: https://www.postgresql.org/docs/current/functions-comparison.html#FUNCTIONS-COMPARISON-PRED-TABLE
=> docs(python): Add a note about the behaviour of lower/upper bounds for `is_between`, and add an example

crates/polars-core/src/series/any_value.rs, py-polars/polars/_utils/construction/dataframe.py, py-polars/polars/datatypes/constructor.py, py-polars/src/conversion/any_value.rs, py-polars/src/conversion/chunked_array.rs, py-polars/src/conversion/mod.rs, py-polars/src/datatypes.rs, py-polars/src/prelude.rs, py-polars/src/series/construction.rs, py-polars/tests/unit/constructors/test_any_value_fallbacks.py, py-polars/tests/unit/constructors/test_constructors.py, py-polars/tests/unit/datatypes/test_array.py
Mostly a lot of refactoring, but also addressed some minor issues.
=> refactor(python): Clean up some of the AnyValue conversion logic

py-polars/polars/datatypes/convert.py, py-polars/polars/io/database.py, py-polars/polars/lazyframe/frame.py, py-polars/requirements-dev.txt, py-polars/tests/unit/io/test_database_read.py
Ref: https://stackoverflow.com/questions/77166897
Database connectivity continues to expand; with this PR we can now seamlessly init a `DataFrame` from _async_ SQLAlchemy `Connection`, `Engine`, and `Session` objects.
Added async unit test coverage using `aiosqlite` (SQLite), but additionally validated the PR locally using `asyncpg` (PostgreSQL) and `aioodbc` (ODBC) drivers.
**SQL Server over ODBC** (async driver):
```python
from sqlalchemy.ext.asyncio import create_async_engine
odbc_string = "Driver={ODBC Driver 17 for SQL Server};Server=localhost"
async_conn = create_async_engine(
f"mssql+aioodbc:///?odbc_connect={odbc_string}"
)
pl.read_database(
query = "SELECT optname,value FROM master.dbo.MSreplication_options",
connection = async_conn,
)
```
**SQLite** (async …
=> feat(python): Add support for `async` SQLAlchemy connections to `read_database`

py-polars/polars/datatypes/__init__.py, py-polars/polars/datatypes/classes.py, py-polars/polars/datatypes/constants.py, py-polars/tests/unit/series/buffers/test_from_buffers.py, py-polars/tests/unit/test_selectors.py
Closes  #13665.
We weren't matching `Datetime` dtypes _with_ time zones when using the `cs.temporal()` selector (or `DATETIME_DTYPES` and `TEMPORAL_DTYPES` dtype sets). Ensuring the match additionally uses the `time_zone="*"` wildcard fixes this.
```python
data = {"utc": [datetime(1950,7,5), datetime(2099,12,31)]},
schema = {"utc": pl.Datetime(time_zone="UTC")},
).with_columns(
idx = pl.int_range(0, 2),
naive = pl.col("utc").dt.replace_time_zone(None),
tokyo = pl.col("utc").dt.convert_time_zone("Asia/Tokyo"),
hawaii = pl.col("utc").dt.convert_time_zone("US/Hawaii"),
)
```
**Before:** _(missing datetime dtypes that have timezones)_
```python
df.select(cs.temporal())
```
**After:** _(all …
=> fix(python): Ensure the `cs.temporal()` selector uses wildcard time zone matching for `Datetime`

crates/polars-lazy/src/frame/mod.rs, crates/polars-time/src/group_by/dynamic.rs, docs/src/python/user-guide/transformations/time-series/rolling.py, py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/group_by.py, py-polars/polars/lazyframe/frame.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/rolling/test_rolling.py, py-polars/tests/unit/operations/test_group_by_dynamic.py, py-polars/tests/unit/operations/test_rolling.py
This hasn't been fully discussed, but it's related to https://github.com/pola-rs/polars/issues/10989 and it was pretty easy to `F2`-replace these. Sometimes, just opening a PR is the fastest way to make a decision, so... here this is 😄 
In summary: `by` in Polars usually refers to which operation you do the operation by (e.g. in `sort`, it sorts by the `by` columns), and sometimes to which columns you group by before applying the operation. For example:
- `df.upsample('a', '3d', by='b')` means "group by 'b' and then upsample by column 'a' every 3 days"
- `df.top_k(3, by='b')` means "take the 3 rows where column `'b'` is largest"
If an operation lets you group by certain columns before applying the operation, then I think it would be clearer to use `group_by` for that parameter.
This would …
=> depr(python,rust!): Rename parameter `by` to `group_by` in `DataFrame.upsample/group_by_dynamic/rolling`

py-polars/polars/series/series.py
A portion of #13161.
Added a few examples for `Series.search_sorted`.
=> docs(python): Add examples for `Series.search_sorted`

crates/polars-time/src/round.rs, crates/polars-time/src/truncate.rs, py-polars/tests/unit/namespaces/test_datetime.py
Polars will currently [round dates and datetimes to negative durations](https://github.com/pola-rs/polars/pull/12597#issuecomment-2008161686):
```
In [16]: pl.Series([datetime(2020, 2, 15)]).dt.round('-1mo')
Out[16]:
shape: (1,)
Series: '' [datetime[μs]]
[
2020-02-01 00:00:00
]
```
(Except not during development where negative durations hit a [`debug_assert`](https://github.com/pola-rs/polars/blob/e20492841f3cfc41e88754580d06ba80d611f238/crates/polars-time/src/windows/window.rs#L24).)
This PR disables that behavior for both rounding and truncating to negative durations, as discussed in #12597
=> fix(python, rust): Block rounding/truncating to negative durations

crates/polars-compute/src/arithmetic/float.rs, crates/polars-compute/src/arithmetic/mod.rs, crates/polars-compute/src/arithmetic/signed.rs, crates/polars-compute/src/arithmetic/unsigned.rs, crates/polars-core/src/chunked_array/arithmetic/numeric.rs, crates/polars-ops/src/series/ops/abs.rs, crates/polars-ops/src/series/ops/negate.rs, py-polars/tests/unit/operations/arithmetic/test_neg.py, py-polars/tests/unit/operations/test_abs.py
Helps address the test failures on release builds - see #15207
=> refactor: Add `wrapping_abs` to arithmetic kernel

.github/workflows/benchmark.yml, .github/workflows/codecov.yml, .github/workflows/test-python.yml, docs/development/contributing/test.md, py-polars/Makefile, py-polars/pyproject.toml, py-polars/tests/benchmark/test_release.py, py-polars/tests/unit/streaming/test_streaming_sort.py, py-polars/tests/unit/test_cse.py
Since we're building the release binary anyway, might as well run the other tests to make sure they also pass on a release build.
* Rename pytest marker `benchmark` to `release`
* Add new pytest marker `debug`. This marker is used for tests that rely on debug assertions to work.
=> ci: Run non-benchmark tests in benchmark workflow

docs/user-guide/io/database.md, docs/user-guide/io/excel.md
=> docs(python): Update Excel and database pages in user guide

crates/polars-core/src/series/any_value.rs, py-polars/tests/unit/constructors/test_any_value_fallbacks.py
Cleans up the implementation and adds tests.
There is some room for improvement here, may get back to it later. Left some TODOs for now.
=> refactor(rust): Refactor AnyValue construction for Categorical/Enum dtype

crates/polars-core/src/chunked_array/ops/compare_inner.rs, crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-core/src/chunked_array/ops/sort/arg_sort_multiple.rs, crates/polars-core/src/chunked_array/ops/sort/mod.rs, crates/polars-core/src/frame/mod.rs, crates/polars-lazy/src/physical_plan/expressions/sortby.rs, crates/polars-row/src/decode.rs, py-polars/tests/unit/operations/test_sort.py, py-polars/tests/unit/streaming/test_streaming_sort.py
Fixes https://github.com/pola-rs/polars/issues/15205.
=> fix: properly support nulls_last + descending

py-polars/polars/expr/list.py, py-polars/polars/series/list.py
closes https://github.com/pola-rs/polars/issues/15221
I checked and this does the right thing:
=> docs(python): Fix link to renamed method (.list.lengths -> .list.len)

py-polars/polars/io/database/_arrow_registry.py, py-polars/polars/io/database/_executor.py
Can directly use `get_as_pl()` now; requires a new version of `kuzu`, but this seems reasonable. Added an optional "minimum_version" module/driver check to gracefully handle this - raises a `ModuleUpgradeRequired` exception if an insufficiently recent version is found. 
Note that the next release of `kuzu` will also include an improvement[^1] in Arrow chunking inside `get_as_pl()`, meaning we'll no longer need to rechunk (will always get a single chunk from now on).
[^1]: https://github.com/kuzudb/kuzu/pull/3110
=> feat(python): Improve `read_database` when reading from Kùzu graph database

py-polars/polars/io/parquet/functions.py
Fixes #15098 
Without optimizations, all columns would be loaded regardless of the `columns` argument, leading to higher CPU and memory usage.
=> fix(python): Avoid loading all columns in `read_parquet` when `columns` parameter is specified

crates/polars-ops/src/chunked_array/array/get.rs, crates/polars-plan/src/dsl/function_expr/list.rs, py-polars/tests/unit/namespaces/array/test_array.py, py-polars/tests/unit/namespaces/list/test_list.py
Fixes https://github.com/pola-rs/polars/issues/15163.
=> fix: allow null index in list.get and array.get

crates/polars-core/src/chunked_array/mod.rs, crates/polars-core/src/utils/mod.rs, py-polars/tests/unit/namespaces/list/test_list.py, py-polars/tests/unit/operations/test_slice.py
Fixes https://github.com/pola-rs/polars/issues/15232 together with https://github.com/pola-rs/polars/pull/15140.
=> fix: do not clamp negative offsets to start of array prematurely

crates/polars-ops/src/chunked_array/strings/substring.rs, py-polars/tests/unit/namespaces/string/test_string.py
Fixes https://github.com/pola-rs/polars/issues/15136.
Issue identified by @mcrumiller here: https://github.com/pola-rs/polars/pull/14425#discussion_r1529068025.
=> fix: incorrect negative offset in multi-byte string slicing

crates/polars-core/src/series/any_value.rs
Currently the document is rendered as this:
https://docs.rs/polars/latest/polars/series/struct.Series.html#method.from_any_values_and_dtype
=> docs(rust): Fix formatting in `Series::from_any_values_and_dtype` docs

crates/polars-plan/src/dsl/function_expr/schema.rs, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_rle.py
While working on #15230 I found out that `rle/rle_id` had no test coverage at all.
I also found out the current lazy schema is wrong. The data types for the lengths column should actually be the index type (UInt32), but that would be a breaking change, so I'm throwing that it in with the column name change.
=> fix: Fix lazy schema for `rle` expression

crates/polars-time/src/group_by/dynamic.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/operations/test_group_by_dynamic.py, py-polars/tests/unit/operations/test_rolling.py
=> fix: Fix bug where rolling operations were ignoring `check_sorted` in some cases

crates/polars-plan/src/constants.rs, crates/polars-plan/src/dsl/functions/selectors.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/dsl/name.rs, crates/polars-plan/src/dsl/struct_.rs, crates/polars-plan/src/logical_plan/aexpr/mod.rs, crates/polars-plan/src/logical_plan/builder.rs, crates/polars-plan/src/logical_plan/builder_alp.rs, crates/polars-plan/src/logical_plan/conversion.rs, crates/polars-plan/src/logical_plan/expr_ir.rs, crates/polars-plan/src/logical_plan/functions/count.rs, crates/polars-plan/src/logical_plan/functions/mod.rs, crates/polars-plan/src/logical_plan/lit.rs, crates/polars-plan/src/logical_plan/mod.rs, crates/polars-plan/src/logical_plan/optimizer/cache_states.rs, crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs, crates/polars-plan/src/logical_plan/optimizer/file_caching.rs, crates/polars-plan/src/logical_plan/optimizer/fused.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/group_by.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/projection.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/rename.rs, crates/polars-plan/src/logical_plan/projection.rs, crates/polars-plan/src/logical_plan/tree_format.rs, crates/polars-plan/src/utils.rs
Constants like `"literal"` and `"len"` now always share a pre-allocated allocation and we ensure we only refer to them by `static` constants.
=> refactor: cleanup column names in optimizer

py-polars/polars/_utils/construction/dataframe.py, py-polars/polars/dataframe/group_by.py, py-polars/polars/lazyframe/group_by.py, py-polars/tests/unit/dataframe/test_df.py
Closes #15222.
Seems like a simple/reasonable addition? While adding tests for this, I also found/fixed a bug where a column name is legitimately the empty string, and we reference it from `schema_overrides`; was getting incorrectly renamed as "column_0".
=> feat(python): Add `name` parameter to `GroupBy.len` method

py-polars/polars/io/database/_executor.py, py-polars/polars/meta/versions.py, py-polars/pyproject.toml, py-polars/requirements-dev.txt, py-polars/tests/unit/io/test_database_read.py
Ref: https://github.com/pola-rs/polars/pull/15162#issuecomment-2011780504
@stinodego: This brings forward some additional `async` industrialisation that I was working on yesterday, while adding some initial `SurrealDB`[^1] integration (have got a new `SurrealDBCursorProxy` class working in another branch[^2]). 
I haven't been able to reproduce the `ResourceWarning` locally yet, but this _may_ solve it by explicitly closing any event loops that we know we created in-context (and it doesn't seem to have occurred in these tests, so... maybe? 🤔) 
Also improves/fixes interaction with Notebooks/Jupyter (nesting `asyncio` calls).
[^1]: SurrealDB features: https://surrealdb.com/features
[^2]: SurrealDB + Polars: https://github.com/surrealdb/surrealdb.py/pull/91#issuecomment-2009802667
=> feat(python): More robust handling of `async` database calls

crates/polars-ops/src/series/ops/moment.rs, py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_statistics.py
Fixes https://github.com/pola-rs/polars/issues/15067
skew and kurtosis were _mostly_ ports of the scipy.stats implementation but it skipped the bit where they check that the returned moments are too small to be valid.
I used `f64::EPSILON` whereas they use `np.finfo(np.float64).resolution`. The former is 2.220446049250313e-16 and the latter is 1e-15. I'm not sure if that's expected or if I used the wrong concept between the two.
=> fix(rust): fix kurtosis/skew

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs, py-polars/tests/unit/operations/test_join.py
=> fix: Raise when join projects name with suffix that doesn't exist

py-polars/polars/_utils/construction/dataframe.py, py-polars/polars/_utils/various.py, py-polars/tests/unit/dataframe/test_from_dict.py
Closes #15192.
New test coverage added for this edge-case.
Can follow-up with a further commit that handles nested values inside nested values (the dict expansion is currently constrained to a one-level scalar fast-path that allows us to make use of `extend_constant`).
=> fix(python): Consistent expansion of nested struct data during `DataFrame` init from dict

crates/polars-arrow/src/io/ipc/read/file.rs
reuse message parsing in IPC file reader when reading in dictionaries and recordbatches
=> refactor(rust): reuse message parsing in IPC

py-polars/polars/expr/datetime.py
Resolves #15275. The column was given an incorrect name.
=> docs(python): Fix time unit in `timestamp` example

crates/polars-core/src/frame/row/mod.rs, crates/polars-core/src/series/any_value.rs, crates/polars-core/src/utils/any_value.rs, crates/polars-core/src/utils/mod.rs, crates/polars-core/src/utils/supertype.rs, py-polars/src/conversion/any_value.rs
* Rename existing public util `any_values_to_dtype` to `any_values_to_supertype_and_n_dtypes` and move it to the `polars_core::utils` module. _(this is the breaking part)_
* Add two public utils based on existing functionality:
* `dtypes_to_supertype` for inferring the supertype of multiple dtypes
* `any_values_to_supertype` for inferring the supertype of a collection of AnyValues
=> refactor(rust!): Refactor AnyValue supertype logic

crates/polars-core/src/series/any_value.rs, py-polars/tests/unit/constructors/test_any_value_fallbacks.py
Also includes a bunch of tests to make sure struct construction is correct.
There is room for improvement here, but it's correct so I'll leave it for now.
=> fix: Properly propagate `strict` flag when constructing a Struct Series from any values

crates/polars-core/src/series/any_value.rs
This method may panic, so it's at least worth documenting when that may happen.
=> docs(rust): Improve docs for `Series::new` with `AnyValue` input

py-polars/polars/slice.py, py-polars/tests/unit/operations/test_slice.py
When sliced with the object `slice(0, None, -1)`, `LazyFrame` returns incorrect result. 
Fixes #15295
=> fix(python): Handle special case correctly when slicing a `LazyFrame`

py-polars/polars/_utils/construction/series.py, py-polars/tests/unit/constructors/test_series.py
=> fix(python): Preserve Decimal precision when constructing empty Series

py-polars/polars/testing/parametric/strategies.py, py-polars/tests/parametric/test_series.py, py-polars/tests/parametric/test_testing.py
Enabling this already helped me catch a bug. Let's enable it by default - our Decimals are a lot better supported already.
=> feat(python): In hypothesis testing strategies, enable Decimal strategy by default

py-polars/polars/convert.py, py-polars/tests/unit/interop/test_interop.py
Closes https://github.com/pola-rs/polars/issues/15195
This function was never intended to handle Series inputs. The docs clearly state that a sequence-of-sequences is expected. So the fact that a Series was supported and parsed into a DataFrame was not intended.
For a catch-all that parses all types of data, the DataFrame constructor can be used.
@alexander-beedie FYI this is the way we decided to go on this one.
=> feat(python): Only allow inputs of type `Sequence` in `from_records`

crates/Makefile
@ritchie46 This should have you (mostly) covered. If not, then we do have to use `stable`.
=> chore(rust): More clippy in Makefile

py-polars/src/functions/eager.rs, py-polars/src/functions/range.rs, py-polars/src/lib.rs, py-polars/tests/unit/functions/range/test_int_range.py
=> fix(python): Enforce integer `dtype` input for `int_range` and `int_ranges`

crates/polars-core/src/frame/row/dataframe.rs, crates/polars-core/src/frame/row/mod.rs, crates/polars-core/src/utils/mod.rs, crates/polars-core/src/utils/schema.rs, py-polars/polars/_utils/construction/dataframe.py, py-polars/src/dataframe/construction.rs, py-polars/src/map/dataframe.rs, py-polars/tests/unit/constructors/test_dataframe.py
This is mostly a refactor, but I encountered some things I could improve:
* fix: When constructing from rows, raise `SchemaError` when `schema_overrides` contains nonexistent column name
* perf: When constructing from rows, skip schema inference if the schema is fully specified.
* feat: Add `dtypes_to_schema` util that instantiates a schema with column names `column_0`, `column_1`, etc. _(perhaps this should be implemented as a trait?)_
=> fix(python,rust!): Raise error when `schema_overrides` contains nonexistent column name

crates/polars-lazy/src/tests/cse.rs, crates/polars-plan/src/dsl/expr.rs, crates/polars-plan/src/logical_plan/optimizer/cache_states.rs, crates/polars-plan/src/logical_plan/optimizer/mod.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
In this case we will favor memory reduction over scan sharing.
```
/// 1. This will ensure that all equal caches communicate the amount of columns
/// they need to project.
/// 2.
/// - This will ensure we apply predicate in the subtrees below the caches.
/// - If the predicate above the cache is the same for all matching caches that filter will be applied
///  as well.
///
/// # Example
/// Consider this tree, where `SUB-TREE` is duplicate and can be cached.
///
///
///                         Tree
///                         |
///                         |
///    |--------------------|-------------------|
///    |                                        |
///    SUB-TREE                                 SUB-TREE
///
/// STEPS:
/// - 1 CSE will run and will insert cache nodes
///
/// …
```
=> feat: CSE don't scan share if predicate pushdown predicates don't match

py-polars/polars/_utils/construction/dataframe.py, py-polars/src/dataframe/construction.rs, py-polars/tests/unit/constructors/test_dataframe.py, py-polars/tests/unit/interop/test_interop.py
Closes https://github.com/pola-rs/polars/issues/15245
Includes some minor refactoring.
=> fix(python): Propagate strictness in `from_dicts`

py-polars/polars/slice.py, py-polars/tests/parametric/test_lazyframe.py, py-polars/tests/unit/operations/test_slice.py
Found a couple more slice cases that are mishandled by LazyFrame. Specifically, both cases below are not supported by LazyFrame but they currently raise incorrect exceptions/errors:
1. `slice(None, 0, k)`, where `k < 0`
```python
ldf = pl.LazyFrame({"a": [1, 2, 3]})
ldf[:0:-1].collect()
```
2. `slice(i, None, k)`, where `i, k < 0`
```python
ldf = pl.LazyFrame({"a": [1, 2, 3]})
ldf[-1::-1].collect()
```
Both these cases should raise a `ValueError: the given slice is not supported by lazy computation`
=> fix(python): Raise properly for slices not supported by `LazyFrame`

crates/polars-core/src/chunked_array/array/iterator.rs, crates/polars-ops/src/chunked_array/array/namespace.rs, crates/polars-plan/src/dsl/array.rs, crates/polars-plan/src/dsl/function_expr/array.rs, py-polars/docs/source/reference/expressions/array.rst, py-polars/docs/source/reference/series/array.rst, py-polars/polars/expr/array.py, py-polars/polars/series/array.py, py-polars/src/expr/array.rs, py-polars/tests/unit/namespaces/array/test_array.py
Counterpart of `list.n_unique` in array namespace. This closes #14273.
(After a busy period, finally had time to play with polars 😉)
=> feat: Implements `arr.n_unique`

crates/polars-core/src/chunked_array/ops/apply.rs, crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-ops/src/chunked_array/binary/namespace.rs, crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs, crates/polars-plan/src/dsl/function_expr/temporal.rs, crates/polars-time/src/month_end.rs, crates/polars-time/src/month_start.rs, crates/polars-time/src/round.rs, crates/polars-time/src/truncate.rs
This method was essentially impossible to use correctly, as we would not want to propagate errors generated from mapping the values behind nulls.
=> chore: remove try_apply_values

crates/polars-ops/src/series/ops/log.rs
=> feat: check input type in entropy

crates/polars-arrow/src/datatypes/mod.rs
Fixes #15234
hey,
this is my first contribution.
If somehow the version of arrow-schema is higher or equal to v51.0.0 the match on DataType is non exhaustive, therefor not compiling.
This adds a ```_ => unimplemented!()``` arm to be able to compile it again.
Cheers!
=> fix(rust): Non-exhaustive patterns: arrow-schema::DataType in polars-arrow

crates/polars-time/src/windows/bounds.rs, crates/polars-time/src/windows/group_by.rs, crates/polars-time/src/windows/test.rs, crates/polars-time/src/windows/window.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/operations/test_group_by_dynamic.py
closes #15241
With the example from that issue, the output becomes:
```
shape: (2, 2)
┌─────────────────────────┬──────┐
│ t                       ┆ v    │
│ ---                     ┆ ---  │
│ datetime[ms, UTC]       ┆ i64  │
╞═════════════════════════╪══════╡
│ 2024-03-21 05:00:00 UTC ┆ 11   │
│ 2024-03-22 05:00:00 UTC ┆ 1100 │
└─────────────────────────┴──────┘
```
which is their expected output
This doesn't break any existing tested behaviour, but does make group-by-dynamic more user-friendly / expected to users using `offset`
Perf impact: there's a little extra computation for finding the first window, but that's only for the first window - after that, the windows just keep getting updated by adding `every` (no change)
=> fix: ensure first datapoint is always included in group_by_dynamic

py-polars/polars/expr/expr.py, py-polars/polars/functions/lazy.py, py-polars/polars/series/series.py
Related to #15316.
I think that `arg_sort` and `arg_sort_by` can be a bit confusing in polars, since polars doesn't use much indexing. It might help the docs to link to a related `gather` method (to use `arg_sort` results) or a related `rank` method (which people might want instead of `arg_sort`).
I kept the "See Also" descriptions in line with the method's documentation, but they could reference `arg_sort`/`arg_sort_by` instead.
=> docs(python): Add "See Also" for `arg_sort` and `arg_sort_by`

crates/polars-core/src/chunked_array/array/iterator.rs, crates/polars-core/src/frame/mod.rs, crates/polars-core/src/series/implementations/binary.rs, crates/polars-core/src/series/implementations/binary_offset.rs, crates/polars-core/src/series/implementations/boolean.rs, crates/polars-core/src/series/implementations/categorical.rs, crates/polars-core/src/series/implementations/dates_time.rs, crates/polars-core/src/series/implementations/datetime.rs, crates/polars-core/src/series/implementations/decimal.rs, crates/polars-core/src/series/implementations/duration.rs, crates/polars-core/src/series/implementations/floats.rs, crates/polars-core/src/series/implementations/mod.rs, crates/polars-core/src/series/implementations/string.rs, crates/polars-core/src/series/implementations/struct_.rs, crates/polars-core/src/series/mod.rs, crates/polars-core/src/series/series_trait.rs, crates/polars-lazy/src/physical_plan/expressions/sort.rs, crates/polars-ops/src/chunked_array/array/namespace.rs, crates/polars-ops/src/chunked_array/list/namespace.rs, crates/polars-ops/src/series/ops/cut.rs, crates/polars-pipe/src/executors/sinks/sort/sink.rs, crates/polars-plan/src/dsl/function_expr/array.rs, crates/polars-plan/src/dsl/function_expr/list.rs, crates/polars-sql/tests/iss_8395.rs, py-polars/src/series/mod.rs
=> fix: `sort` for series with unsupported dtype should raise instead of panic

crates/polars-plan/src/logical_plan/optimizer/cache_states.rs, crates/polars-plan/src/logical_plan/optimizer/mod.rs, py-polars/tests/unit/io/test_hive.py
Seems to fix (the first bug reported in) https://github.com/pola-rs/polars/issues/15375 for me, not sure if this is valid though? @ritchie46
=> fix(python): fix panic when doing a scan_parquet with hive partioning

crates/polars-lazy/src/physical_plan/planner/lp.rs, crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs, crates/polars-plan/src/logical_plan/expr_ir.rs, py-polars/polars/testing/__init__.py, py-polars/polars/testing/_constants.py, py-polars/tests/unit/streaming/test_streaming_group_by.py
=> fix: Conversion of expr_ir in partition fast path

crates/polars-core/src/datatypes/field.rs
=> fix: Add FixedSizeBinary to arrow field conversion

crates/polars-core/src/hashing/vector_hasher.rs, py-polars/tests/unit/dataframe/test_df.py
This apparently used to work before, ~~but how it did remains a mystery to me 🤔~~.
I think I know the story here - the previous combined vec hash must have done:
```
ahash_hash_one_specialized<T>(a) ^ ahash_hash_one_generic<&T>(&b)
```
when doing a combined hash. And since ahash gave different hash values for the ref, we avoided a collision even when `a == b`.
But after we switched to `total_ord`, we are now doing:
```
ahash_hash_one_specialized<T>(a) ^ ahash_hash_one_specialized<T>(b)
```
so we get `a == b  <=>  hash(a) == hash(b)`, so the xor would be 0.
This should fix https://github.com/pola-rs/polars/issues/15390, although I suspect we could eventually remove `vec_hash_combine` and dispatch to row-encoding instead.
=> fix: Hash failure combining hash of two numeric columns containing equal values

crates/polars-plan/src/logical_plan/lit.rs, py-polars/tests/unit/functions/test_repeat.py
=> fix: `to_any_value` should supports all LiteralValue type

docs/src/python/user-guide/transformations/joins.py, docs/src/rust/user-guide/transformations/joins.rs, docs/user-guide/transformations/joins.md
=> docs: Add `outer_coalesce` join strategy in the user guide

crates/polars-lazy/src/physical_plan/expressions/apply.rs, py-polars/tests/unit/expr/test_expr_apply_eval.py
=> fix: Unset UpdateGroups after group-sensitive expression

py-polars/polars/series/series.py
`Expr.__bool__` got a lot of love on Discord:
Might be good to do the same for `Series.__bool__`?
=> feat(python): make Series.__bool__ error message Rusttier

crates/polars-arrow/src/compute/cast/utf8_to.rs
=> fix: Ensure Binary -> Binview cast doesn't overflow the buffer size

crates/polars-core/src/chunked_array/logical/struct_/mod.rs, crates/polars-core/src/chunked_array/ops/sort/arg_sort_multiple.rs, crates/polars-core/src/frame/group_by/into_groups.rs, crates/polars-core/src/frame/group_by/mod.rs, crates/polars-pipe/src/executors/sinks/group_by/generic/eval.rs, crates/polars-pipe/src/executors/sinks/sort/sink_multiple.rs, crates/polars-row/src/decode.rs, crates/polars-row/src/encode.rs, crates/polars-row/src/fixed.rs, crates/polars-row/src/lib.rs, crates/polars-row/src/row.rs, crates/polars-row/src/variable.rs
Optimize row-encoding for non-order preserving operations like group-by, join. By dropping that requirement we can simply memcopy the bytes and don't have to add padding bytes/blocks.
=> perf: Add non-order preserving variable row-encoding

crates/polars-arrow/src/legacy/kernels/list.rs, crates/polars-ops/src/chunked_array/list/namespace.rs, crates/polars-ops/src/chunked_array/list/to_struct.rs, crates/polars-plan/src/dsl/function_expr/list.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/list.rs, crates/polars-sql/src/functions.rs, py-polars/polars/expr/list.py, py-polars/polars/series/list.py, py-polars/src/expr/list.rs, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/namespaces/list/test_list.py
Addresses first part of #15240 (first time contributing so I figured I'd add 1 and get feedback before embarking on the rest, especially as they don't seem to overlap as much as I'd expected.)
For now leaves the default behavior to `null_on_oob=True` (see discussion below; we will revisit the default behavior for once it has been implemented for all functions in #15240).
=> feat(rust, python): Add `null_on_oob` parameter to `expr.list.get`

py-polars/polars/expr/expr.py
- Added an example for `explode` mapping strategy in `pl.Expr.over`
- Modified the explanation to clarify the behavior of `explode` and when sorting by groups is required
Fixes: #15346
=> docs(python): Added example for `explode` mapping strategy in `pl.Expr.over`

Cargo.lock, Cargo.toml, py-polars/Cargo.toml, py-polars/docs/source/reference/io.rst, py-polars/polars/__init__.py, py-polars/polars/dataframe/frame.py, py-polars/polars/io/__init__.py, py-polars/polars/io/clipboard.py, py-polars/src/functions/io.rs, py-polars/src/lib.rs
Closes #9902
Similar to [`pandas.DataFrame.to_clipboard`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_clipboard.html#pandas.DataFrame.to_clipboard) and [`pandas.read_clipboard`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_clipboard.html), `read_clipboard` reads csv format text from clipboard and convert it into `DataFrame` whereas `DataFrame.write_clipboard` writes `DataFrame` into clipboard with csv format. 
These 2 methods are useful while exploring data from Excel or other similar software in interactive environment like jupyter notebook. 
- Reading and writing clipboard uses [arboard](https://github.com/1Password/arboard) in rust side, supporting Windows, macOS and Linux, maintained by 1Password. 
- `read_clipboard` just …
=> feat(python): Add `read_clipboard` and `DataFrame.write_clipboard`

crates/polars-core/src/series/implementations/decimal.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> feat: Supports `explode_by_offsets` for decimal

crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/mod.rs
trying to learn a lesson from https://github.com/pola-rs/polars/pull/15420/files#r1546380674
=> perf: avoid double-allocation in rolling_apply_agg_window

crates/polars-arrow/src/compute/temporal.rs, crates/polars-arrow/src/temporal_conversions.rs, py-polars/tests/unit/datatypes/test_temporal.py
=> fix: datetime operations (e.g. .dt.year) were raising when null values were backed by out-of-range integers

crates/polars-io/src/csv/read_impl/mod.rs, py-polars/src/batched_csv.rs, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/io/test_parquet.py
Fixes #15374 
* Add tests for memory usage of read_csv() and read_csv_batched()
* Add GIL removal for read_csv_batched(). Necessary for the tests, but also worth doing in general.
* Fixed minor performance/memory bug caused by the fact that if you set `batch_size=1000` the CSV code will read 1001 lines. The underlying buffer will only have size 1000, so this results in extra allocations and copying once you hit that last 1001th line being read into a buffer. To workaround this, the buffer size is made 1 larger than the nominal requested capacity.
For the last item, the ideal would be to fix the underlying off by one bug instead. The obvious cause would appear to be https://github.com/pola-rs/polars/blob/b0ece1e97aec58ab7ab7ce5a29e73c1dc54baa5c/crates/polars-io/src/csv/parser.rs#L449, …
=> perf(python): CSV reading memory usage tests and fixes

crates/polars-core/src/chunked_array/builder/list/mod.rs, crates/polars-core/src/chunked_array/builder/list/null.rs, crates/polars-core/src/frame/group_by/aggregations/agg_list.rs, crates/polars-core/src/series/implementations/null.rs, py-polars/tests/unit/operations/test_window.py
We must implements `agg_list` for `NullChunked`, otherwise it will be dispatched to the default implementation which doesn't produce a list series.
This fixes #15437.
=> feat: Implements `agg_list` for `NullChunked`

crates/polars-io/src/options.rs, crates/polars-io/src/predicates.rs, crates/polars-lazy/src/scan/parquet.rs, crates/polars-plan/src/logical_plan/builder.rs, crates/polars-plan/src/logical_plan/hive.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs, crates/polars-plan/src/logical_plan/options.rs, crates/polars-plan/src/logical_plan/schema.rs, py-polars/polars/io/parquet/functions.py, py-polars/polars/lazyframe/frame.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_hive.py
=> feat(python,rust!): Allow specifying Hive schema in `read/scan_parquet`

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_clear.py
This aligns the behavior of `series.clear(-1)` and `df.clear(-1)`. 
NB. Before this change, the error of `df.clear(-1)` is raised from the `extend_constant`(pass a negative n), I think a more explicit error would be nice.
The only difference is that for an empty series, passing a negative `n` does not throw an error before this change. I feel like it makes the function behave a bit more predictable if we reject `n < 0` outright, WDYT?
This fixes #15421.
=> fix(python): Raise if pass a negative `n` into `clear`

crates/polars-plan/src/logical_plan/conversion.rs, py-polars/tests/unit/test_schema.py
We have disabled alias pruning for `Expr::Function`, IIUC, this should also do for `AnonymousFunction`. Are there any exceptions?
This fixes #15438.
=> fix: Don't prune alias in AnonymousFunction subtree

crates/polars-json/src/json/write/serialize.rs
This improves the following benchmark in 50%:
```rust
use criterion::{black_box, criterion_group, criterion_main, Criterion};
use polars::prelude::*;
fn to_json(df: &mut DataFrame) -> Vec<u8> {
let mut json = Vec::new();
JsonWriter::new(&mut json)
.with_json_format(JsonFormat::Json)
.finish(df)
.unwrap();
json
}
fn my_benchmark(c: &mut Criterion) {
const SIZE: i32 = 10_000;
let mut df = df![
"a" => (0..SIZE).collect::<Vec<_>>(),
"b" => (0..SIZE).map(|v| v.to_string()).collect::<Vec<_>>(),
]
.unwrap();
c.bench_function("to_json", |b| b.iter(|| to_json(black_box(&mut df))));
}
criterion_group!(benches, my_benchmark);
criterion_main!(benches);
```
=> perf: Avoid allocation in the hot path for struct JSON serialization

crates/polars-plan/src/logical_plan/builder.rs, py-polars/tests/unit/operations/test_filter.py
=> fix(rust,python): Allow selectors inside frame-level `.filter()`

py-polars/polars/io/database/_executor.py
Closes #15470 and closes #15469.
The generator was inadvertently being drained on the first call by a rogue "list" invocation - while it was correctly using `fetchmany` internally, it should only have been retrieving one batch per iteration, not retrieving all batches and _then_ iterating (possibly something I was doing while debugging or refactoring that accidentally made it into a release 🤦).
=> fix(python): Address issue with `read_database` draining iter_batches early

crates/polars-plan/src/dsl/function_expr/temporal.rs
closes #15482 
this is my fault, from a commit I'd added to: https://github.com/pola-rs/polars/pull/9967/files 😳 🤦
=> perf: speed up offset_by when a single offset is passed

crates/polars-arrow/src/legacy/index.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/dsl/function_expr/struct_.rs, crates/polars-plan/src/logical_plan/conversion.rs, crates/polars-plan/src/logical_plan/projection.rs, py-polars/tests/unit/test_expansion.py
=> fix: Fix struct name resolving

py-polars/polars/io/parquet/functions.py
I got some good feedback about schema functionality in [#15441](https://github.com/pola-rs/polars/issues/15441).
In light of this, I'm marking this as unstable as we may want to revise the API.
=> chore(python): Add unstable warning to `hive_schema` functionality

crates/polars-lazy/src/physical_plan/expressions/window.rs, py-polars/tests/unit/operations/test_window.py
Closes #15483
In the case of a `GroupsProxy::Slice`, validity wasn't getting set if a group had all of its items filtered out. Instead, uninitialized values would be used, leading to a mix of nulls and garbage values.
The other variant of `GroupsProxy`, the `GroupsProxy::Idx`, doesn't seem to have a problem when groups are filtered out entirely. To be safe, I left the initialization code before the `match` so it affects both variants.
=> fix(python, rust): Initialize validity for `GroupsProxy::Slice` windows

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_conditional.py
_(Lack of support for these functions was mentioned on the Discord)._
SQL's `GREATEST` and `LEAST` functions map directly onto our max/min horizontal functions. We also already follow PostgreSQL's NULL handling (and compatible supertype) behaviour[^1] here, so no special adjustments needed.
```python
"a": [-100, None, 200, 99],
"b": [None, -0.1, 99., 9.],
"c": [50, -10, 125, -1000],
})
with pl.SQLContext(df=df) as ctx:
df_greatest = ctx.execute(
"""
SELECT
GREATEST("a", "b")    AS max_abc,
GREATEST("a", 0, "b") AS max_abc_zero, 
LEAST("a", "b")       AS min_abc,
LEAST("a", 0, "b")    AS min_abc_zero,  
FROM df
"""
).collect()
```
[^1]: https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-GREATEST-LEAST
=> feat: Add SQL support for `GREATEST` and `LEAST`

crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, py-polars/tests/unit/operations/test_group_by.py
=> fix(rust, python): `group_by` partitioned with literal `Series` panic

crates/polars-sql/src/context.rs, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/sql/test_table_operations.py, py-polars/tests/unit/test_lazy.py
Ref: https://github.com/pola-rs/polars/issues/7227.
* Adds SQL support for `TRUNCATE <TABLE> xyz` commands. This is an optimal way to drop all rows from a table while preserving the table itself (so the schema doesn't change, but the table is empty).
* Adds test coverage for this and most of the other non-query directives (`DROP`, `EXPLAIN`, `SHOW TABLES`).
```python
"x": [1, 2, 3],
"y": ["aaa", "bbb", "ccc"],
"z": [date(2000, 12, 31), date(1978, 11, 15), date(2077, 10, 20)],
})
with pl.SQLContext(frame=df, eager_execution=True) as ctx:
df1 = ctx.execute("TRUNCATE TABLE frame")
df2 = ctx.execute("SELECT * FROM frame")
df1
df2
```
=> feat: Add SQL support for `TRUNCATE TABLE` command

crates/polars-io/src/parquet/read_impl.rs, crates/polars-io/src/pl_async.rs
This has the effect of explicitly moving all futures to another thread (if the current thread was polling futures) before blocking on the function using the current thread. It is a no-op if the current thread is not in the tokio runtime.
https://docs.rs/tokio/latest/tokio/task/fn.block_in_place.html
=> perf: Replace std::thread spawn with tokio block_in_place

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
#14840 renamed the `by` parameter to `group_by` in
- `DataFrame.upsample/group_by_dynamic/rolling`
- `LazyFrame.group_by_dynamic/rolling`
This PR cleans up remaining references in the docstrings to the old `by` paramter.
=> docs(python): Update leftover references of `by` parameter to `group_by` in `DataFrame/LazyFrame.upsample/group_by_dynamic/rolling`

py-polars/polars/io/database/_executor.py, py-polars/polars/io/database/_inference.py
Some housekeeping, in advance of adding further capabilities (backing-out more accurate dtypes from the underlying db driver module when the cursor description contains a custom type_code). 
This finishes consolidating inference code out of the executor module.
=> refactor(python): Move dedicated inference code out of `io.database` executor module

py-polars/Makefile, py-polars/polars/_utils/various.py, py-polars/polars/dataframe/frame.py, py-polars/polars/io/_utils.py, py-polars/polars/io/avro.py, py-polars/polars/io/csv/batched_reader.py, py-polars/polars/io/csv/functions.py, py-polars/polars/io/ipc/functions.py, py-polars/polars/io/json.py, py-polars/polars/io/ndjson.py, py-polars/polars/io/parquet/functions.py, py-polars/polars/lazyframe/frame.py
The implementation of IO functionality was (unnecessarily) split between two places. This centralizes the logic in 1 place, makes subsequent refactors easier. There is a LOT of duplication here.
=> refactor(python): Remove private `DataFrame._read` classmethods

py-polars/polars/_utils/various.py, py-polars/polars/io/_utils.py, py-polars/polars/io/avro.py, py-polars/polars/io/csv/batched_reader.py, py-polars/polars/io/csv/functions.py, py-polars/polars/io/ipc/anonymous_scan.py, py-polars/polars/io/ipc/functions.py, py-polars/polars/io/ndjson.py, py-polars/polars/io/parquet/anonymous_scan.py, py-polars/polars/io/parquet/functions.py, py-polars/polars/io/spreadsheet/_utils.py, py-polars/polars/io/spreadsheet/functions.py, py-polars/tests/unit/io/cloud/test_utils.py, py-polars/tests/unit/io/test_utils.py, py-polars/tests/unit/utils/test_utils.py
=> refactor(python): Organize utils for I/O functionality

crates/polars-arrow/src/legacy/kernels/list.rs, py-polars/tests/unit/namespaces/list/test_list.py
Per discussion in discord, we should always take validity into account when play with list array as it sometimes has different layouts for null value.
=> fix: `list.get` should take validity into account

crates/polars-arrow/src/array/boolean/mutable.rs, crates/polars-ops/src/chunked_array/top_k.rs, py-polars/tests/unit/operations/test_sort.py
This allows more dtype to use `top_k` which only supported numeric dtypes before.
=> feat: Implement `string`, `boolean` and `binary` dtype in `top_k`

crates/polars-sql/src/functions.rs, py-polars/tests/unit/sql/test_group_by.py
Adds convenience SQL interface support for the `MEDIAN` aggregate function (usually PostgreSQL bundles median calculation inside a `PERCENTILE_CONT(x, 0.5)` expression but many/most databases now expose it explicitly; I'll look at adding a dedicated `PERCENTILE_CONT` implementation later).
Also: Adds some missing function names to the  `PolarsSQLFunctions::keywords` vec.
```python
with pl.SQLContext(foods=df, eager_execution=True) as ctx:
ctx.execute(
"""
SELECT
COUNT(category) as n,
category,
MAX(calories) AS max_cal,
MEDIAN(calories) AS median_cal,
MIN(fats_g) AS min_fats
FROM foods
GROUP BY category
HAVING n > 5
ORDER BY n, category DESC
"""
)
```
=> feat: Add SQL support for `MEDIAN` aggfunc

py-polars/src/dataframe/construction.rs, py-polars/tests/unit/constructors/test_dataframe.py
Reverts the change in https://github.com/pola-rs/polars/pull/15290
Closes https://github.com/pola-rs/polars/issues/15471
As per the discussion in the linked issue, being able to pass nonexistent columns in `schema_overrides` is actually pretty useful in certain situations. I had not foreseen this, so I am reverting the check I introduced for this.
=> fix(python): No longer error when `schema_overrides` contains nonexistent columns

py-polars/polars/io/csv/functions.py, py-polars/tests/unit/io/test_csv.py
=> fix(python): Pass `skip_rows_after_header` to pyarrow csv reader

crates/polars-core/src/series/ops/to_list.rs, crates/polars-plan/src/dsl/function_expr/dispatch.rs, crates/polars-plan/src/dsl/mod.rs
In #8017, the `reshape`'s argument name changed only on the Python side, so it no longer matches in Rust and in Python.
In #12288, update the error message from `reshape` in Rust, but used the Python argument name, making it difficult to understand. (It says ``reshape `dimensions` cannot be empty``, but the real argument name is `dims`, not `dimensions`)
So I think it's worth unifying the argument names.
=> refactor!(rust): update the argument name from `dims` to `dimensions` in `reshape`

crates/polars-io/src/csv/read_impl/mod.rs, py-polars/tests/unit/io/test_csv.py
#14192
read_csv wouldn't decompress file unless schema had None value. 
Ran with test file :
``` python
import gzip
import os
"id": [1, 2, 3, 4, 5],
"name": ["Alice", "Bob", "Charlie", "David", "Eve"],
"age": [25, 32, 37, 45, 29],
"city": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]
})
temp_filename = 'tempfile.csv'
df.write_csv(temp_filename)
compressed_filename = 'dataframe.csv.gz'
with open(temp_filename, 'rb') as temp_file:
with gzip.open(compressed_filename, 'wb') as gzip_file:
gzip_file.writelines(temp_file)
os.remove(temp_filename)
print("DataFrame is successfully exported to a gzipped CSV file.")
schema = {
"id": pl.Int64,
"name": pl.Utf8,
"age": pl.Int64,
"city": pl.Utf8,
}
df_reopened = pl.read_csv(
'dataframe.csv.gz', …
```
=> fix: Decompress moved out of schema initialization

crates/polars-core/src/datatypes/dtype.rs, crates/polars-ops/src/series/ops/is_first_distinct.rs, crates/polars-ops/src/series/ops/is_last_distinct.rs, py-polars/tests/unit/operations/test_is_first_last_distinct.py
Since we have shift to `row-encode` for `group-by` list. I think we could get rid of the limitation for `is_first/last_distinct` also.
=> feat: Enable `is_first/last_distinct` for not nested non-numeric list

crates/polars-parquet/src/parquet/compression.rs
Feature check for `inner_compress` function has a typo for "lz4" and this is causing a compilation error if only "lz4" feature is enabled.
=> build(rust): Fix a feature gate for `lz4` compression in `polars-parquet`

crates/polars-sql/src/context.rs, crates/polars-sql/tests/simple_exprs.rs
Trivial fix, but addresses a gremlin with quoted CTE identifiers in SQL queries; we needed to take the ident name's `value` field to consistently acquire/reference the unquoted name, _not_ convert via `to_string`.
*Worked -*
```sql
WITH cte_name AS (SELECT * FROM df) SELECT * FROM cte_name
```
*Errored -*
```sql
WITH "cte_name" AS (SELECT * FROM df) SELECT * FROM cte_name
```
With the fix in place, both of the example queries above succeed; test coverage extended accordingly.
=> fix: Handle quoted identifiers when registering CTEs in the SQL engine

crates/polars-time/Cargo.toml
Without having `smartstring/serde` compiling with `--all-features` fails because of the smartstring values not being serializable:
```
$ cargo build --all-features  -p polars-time
Compiling polars-time v0.38.3 (/home/fila/workspace/polars/crates/polars-time)
error[E0277]: the trait bound `SmartString<LazyCompact>: rolling_window::_::_serde::Serialize` is not satisfied
--> crates/polars-time/src/group_by/dynamic.rs:21:38
|
21   |   #[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
|                                        ^^^^^^^^^ the trait `rolling_window::_::_serde::Serialize` is not implemented for `SmartString<LazyCompact>`
22   |   pub struct DynamicGroupOptions {
23   | /     /// Time or index column.
24   | |     pub index_column: SmartString,
| …
```
=> fix: Enable missing features in polars-time

crates/polars-core/src/chunked_array/ops/arity.rs
First, this is unused. And second, even if it was used, a similar argument to applies #15336 - should people be using it at all?
=> chore(rust): remove try_binary_elementwise_values

crates/polars-sql/src/context.rs, crates/polars-sql/tests/functions_string.rs, crates/polars-sql/tests/simple_exprs.rs, py-polars/tests/unit/sql/test_group_by.py
Closes #14704.
We already had all the machinery in place for handling "GROUP BY" clauses[^1] that use ordinal position values, but were defeated by a classic "off by one" error (as SQL is 1-indexed). Fixed it and added the missing test coverage. Will look at adding support for ordinal position values in "ORDER BY" clauses separately.
(Having ordinal position values in both clauses is supported by standard PostgreSQL syntax).
```python
"a": ["xx", "yy", "xx", "yy", "xx", "zz"],
"b": [1, 1, 1, 2, 2, 2],
"c": [99, 99, 66, 66, 66, 66],
})
with pl.SQLContext(frame=df) as ctx:
df = ctx.execute(
"""
SELECT NULL::date as dt, c, SUM(b) AS total_b
FROM frame
GROUP BY 2, 1
"""
).collect()
```
[^1]: https://www.postgresql.org/docs/current/sql-select.html#SQL-GRO …
=> fix: SQL interface "off-by-one' indexing error with `GROUP BY` clauses that use position ordinals

Cargo.lock, py-polars/Cargo.toml, py-polars/src/on_startup.rs
Closes https://github.com/pola-rs/polars/issues/15345.
After Ritchie's refactor of the Arena IR this PR can now properly close this issue.
=> fix: use larger recursive stack in debug mode

crates/polars-core/src/chunked_array/ops/explode_and_offsets.rs, py-polars/tests/unit/operations/test_explode.py
This is annoying, but `ListArray` does have two layouts.
This fixes #15454.
=> fix: Explode list should take validity into account

crates/polars-io/src/parquet/write.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
addresses https://github.com/pola-rs/polars/issues/15586
=> feat: change default to write parquet statistics

crates/polars-plan/src/logical_plan/visitor/expr.rs, crates/polars-plan/src/logical_plan/visitor/lp.rs, crates/polars-plan/src/logical_plan/visitor/visitors.rs
Might help: #15551
We could hopefully get a more useful flamegraph at least.
=> perf: don't use dynamic dispatch in visitors

crates/polars-lazy/src/physical_plan/expressions/apply.rs, py-polars/tests/unit/operations/test_group_by.py
=> fix: Fix elementwise-apply if any input is `AggregatedScalar`

crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, py-polars/tests/unit/test_queries.py
=> refactor: Don't run streaming group-by in partitionable gb

Cargo.lock, Cargo.toml, py-polars/Cargo.toml, py-polars/src/conversion/any_value.rs, py-polars/src/conversion/mod.rs, py-polars/src/map/dataframe.rs, py-polars/src/series/export.rs, py-polars/src/series/numpy_ufunc.rs, py-polars/src/to_numpy.rs
Fixes #15621
Next step will probably be getting rid of the manual deprecation suppression by switching to the non-deprecated `numpy` APIs, in the hopes that's somewhat self-contained.
=> chore(python): Initial PyO3 0.21 support

crates/polars-pipe/src/executors/sinks/group_by/aggregates/convert.rs, py-polars/tests/unit/streaming/test_streaming_group_by.py
Fixes https://github.com/pola-rs/polars/issues/15610
This also happened non-deterministically on the standard engine as it sometimes ran streaming, but that will probably change soon with https://github.com/pola-rs/polars/pull/15611
=> fix: Mean of boolean in streaming group_by incorrectly always gave NULL

py-polars/polars/_utils/udfs.py, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py, py-polars/tests/unit/operations/map/test_map_elements.py
* Extended `BytecodeParser` so that it also identifies functions imported directly into the global namespace (previously would only have identified the more explicit `np.log10` or `numpy.log10` form), eg:
```python
from numpy import log10
df.with_columns(pl.col("x").map_elements(lambda x: log10(x)))
df.with_columns(pl.col("x").map_elements(log10))
```
* Added detection of `math` module functions (also works with global namespace detection).
```python
import math
df = pl.DataFrame({"x": [1,2,3]})
df.with_columns(pl.col("x").map_elements(math.log10))
```
* Fixed detection of inefficient `map_*` calls on `Series` with the default (empty string) name (ref: https://github.com/pola-rs/polars/issues/15587#issuecomment-2049753474).
* Fixed an edge-case involving `_caller_variables` (should have …
=> feat: Extended `BytecodeParser` to handle additional math functions, and imports from the global namespace

crates/polars-io/src/parquet/async_impl.rs, crates/polars-io/src/pl_async.rs, py-polars/src/functions/lazy.rs, py-polars/src/lazyframe/mod.rs
Looked through the uses of `spawn` and made some small improvements
=> perf: Remove extra thread spawn from row group fetcher

crates/polars-arrow/src/array/growable/binview.rs
=> perf: Fix binview growable complexity O(n*m) -> O(n)

crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/physical_plan/executors/cache.rs, crates/polars-lazy/src/physical_plan/executors/ext_context.rs, crates/polars-lazy/src/physical_plan/executors/filter.rs, crates/polars-lazy/src/physical_plan/executors/group_by.rs, crates/polars-lazy/src/physical_plan/executors/group_by_dynamic.rs, crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, crates/polars-lazy/src/physical_plan/executors/group_by_rolling.rs, crates/polars-lazy/src/physical_plan/executors/hconcat.rs, crates/polars-lazy/src/physical_plan/executors/join.rs, crates/polars-lazy/src/physical_plan/executors/projection.rs, crates/polars-lazy/src/physical_plan/executors/python_scan.rs, crates/polars-lazy/src/physical_plan/executors/slice.rs, crates/polars-lazy/src/physical_plan/executors/sort.rs, crates/polars-lazy/src/physical_plan/executors/stack.rs, crates/polars-lazy/src/physical_plan/executors/udf.rs, crates/polars-lazy/src/physical_plan/executors/union.rs, crates/polars-lazy/src/physical_plan/executors/unique.rs, crates/polars-plan/src/logical_plan/builder.rs, crates/polars-plan/src/logical_plan/builder_alp.rs, crates/polars-plan/src/logical_plan/builder_functions.rs, crates/polars-plan/src/logical_plan/functions/mod.rs, crates/polars-plan/src/logical_plan/functions/schema.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/functions/mod.rs, py-polars/tests/unit/test_cse.py, py-polars/tests/unit/test_lazy.py
=> fix: Recompute RowIndex schema after projection pd

py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py
Add indication that LazyFrame.deserialize() might execute arbitrary code coming from the deserialized data.
Fixes #14623
=> docs(python): Add security warning in LazyFrame.deserialize() docstring

py-polars/polars/datatypes/classes.py, py-polars/tests/unit/datatypes/test_enum.py
Resolves #14962.
Very minor addition to the API, allows Enum data types to be unioned:
```python
e1 = pl.Enum(["a", "b"])
e2 = pl.Enum(["b", "c"])
print(e1.union(e2))
print(e1 | e2)
```
=> feat(python): Add `union`/`or` operator for `pl.Enum`

py-polars/polars/io/spreadsheet/_write_utils.py
Closes #15629.
Fixes an operator precedence gremlin.
=> fix: Fix issue in `write_excel` that could lead to incorrect spanning range determination

py-polars/polars/exceptions.py
Part of #13161
Examples for ColumnNotFoundError, DuplicateError, InvalidOperationError
=> docs(python): Examples for errors

crates/polars-time/src/upsample.rs, py-polars/tests/unit/datatypes/test_temporal.py
fix #12207 
In this PR, I try to fix to support upsampling by index (ex. every="1i").
The upsampling document says upsample supports regular frequency that includes "1i", but it is not working now (#12207).
For the implementation, I referred to the group_by_dynamic function that supports "1i" freq.
https://github.com/pola-rs/polars/blob/a8bdc76000c059afdac1f215e3b95654a0057712/crates/polars-time/src/group_by/dynamic.rs#L198
Any comments and suggestions are welcome.
=> fix(rust):  Support index upsampling

crates/polars-pipe/src/executors/sinks/joins/cross.rs
This is a separate follow-up to #11699.
It fixes one particular edge case which generates small batches, as featured in the test script. Using the same script #14346, but without the fix in #14346, before:
```
SINK 2.8767316341400146
COLLECT+WRITE 0.9260973930358887
STREAMING COLLECT+WRITE 4.061856031417847
```
And after:
```
SINK 1.0176868438720703
COLLECT+WRITE 0.9198713302612305
STREAMING COLLECT+WRITE 0.9465274810791016
```
This is not a substitute for #14346, however, since there are likely other cases where small chunk sizes get generated. It's therefore worth fixing both sides (final sinks and intermediate steps):
1. Fixing intermediate steps should also speed up later intermediate calculation in cases where the overhead of small chunks is relevant, _before_ they hit the final …
=> perf: Fix cross join batch size when one of the DataFrames is tiny

docs/user-guide/installation.md
=> docs: Add legacy CPU install instructions in user guide

py-polars/tests/unit/datatypes/test_temporal.py
Two tests were failing due to this
I've removed `offset` from one (upsampling by integers, which is a new functionality anyway), and am catching the deprecation warning in the other
=> chore: fixup failing test due to `offset` deprecation in `upsample`

crates/polars-arrow/src/mmap/mod.rs, crates/polars-io/src/ipc/ipc_file.rs, crates/polars-lazy/src/physical_plan/executors/scan/ipc.rs, crates/polars-lazy/src/scan/ipc.rs, crates/polars-lazy/src/tests/io.rs, crates/polars-plan/src/logical_plan/options.rs, py-polars/src/lazyframe/mod.rs
When reading an Arrow IPC file, the following warning message may appear, but it may be unclear what it means because the Rust API uses `memmap` instead of `memory_map`.
https://github.com/pola-rs/polars/blob/7341aeeac16e77ccdbf5fdaf2fec5ab40beafea9/crates/polars-io/src/ipc/ipc_file.rs#L84
This PR updates `memmap` arguments to `memory_map`
=> refactor(rust!): rename `memmap` -> `memory_map` as like Python

crates/polars-time/src/windows/duration.rs
It's currently off by a factor of 1_000, `'20h'` gets displayed as `'72000000h'` instead of `'72000h'`
~~Pulling some constants together and using those instead~~
~~I may well have some typos here, but I'm just going out - will fixup when I get back~~
=> fix(rust): Fix Display implementation of Duration

crates/polars-ops/src/chunked_array/array/min_max.rs, py-polars/tests/unit/namespaces/array/test_array.py
=> fix: Correct the unsoundness slice range of `arr.min/max`

crates/polars-plan/src/dsl/mod.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
closes https://github.com/pola-rs/polars/issues/15656
=> fix: rolling_* aggs were behaving as if they return scalars in group-by

crates/polars-plan/src/logical_plan/functions/mod.rs, crates/polars-plan/src/logical_plan/functions/schema.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/functions/mod.rs, py-polars/tests/unit/test_projections.py
=> fix: Ensure 'CachedSchema' doesn't get synced between plans

crates/polars-core/src/chunked_array/ops/any_value.rs
#15237
Doesn't fix the culprit, but at leasts panicks now.
=> fix: Panic if invalid array in object

crates/polars-plan/src/dsl/function_expr/temporal.rs, crates/polars-time/src/windows/duration.rs
splitting this off from https://github.com/pola-rs/polars/pull/15638
There's currently a method `Duration.is_constant_duration`, which returns `false` if the duration contains calendar durations (months, weeks, days).
However, for the time-zone-naive case (and the UTC case), days and weeks are constant durations too, as they're not affected by daylight saving time
There's no implication for the current tests (but it will help with #15638, as there `half_life` has to be a constant duration)
=> chore: make Duration.is_constant_duration less strict for non-timezone-aware case

py-polars/src/series/numpy_ufunc.rs
Fixes #15666
(There are still many deprecated _PyO3_ APIs being used, suppressed by the `gil-refs` feature of the `pyo3` crate, so that's what I will be looking at next.)
=> chore(rust): Remove the remaining usage of deprecated `numpy` crate APIs

py-polars/polars/__init__.py, py-polars/polars/_utils/deprecation.py, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/datetime.py, py-polars/polars/expr/string.py, py-polars/polars/io/__init__.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/datetime.py
- added "Deprecated since version" to `DataFrame/LazyFrame.with_row_count`
- fix deprecated version in `Expr.str.json_extract`
-  was discrepancy between decorator and docstring. 0.19.15 is correct.
- do not advise use of deprecated `ambiguous` parameter as a replacement for `use_earliest` parameter in `Series/Expr.dt.truncate`
Drive bys:
- alphabetise `read_clipboard` inside `__all__`
- spelling mistake
=> docs(python): Various deprecation docstring improvements

crates/polars-lazy/src/physical_plan/exotic.rs, py-polars/tests/unit/namespaces/list/test_list.py
=> fix: `prepare_expression_for_context` shouldn't panic if exceptions raised from optimizer

crates/polars-plan/src/dsl/function_expr/ewm.rs, crates/polars-plan/src/dsl/function_expr/ewm_by.rs, crates/polars-plan/src/dsl/function_expr/mod.rs
=> fix: Add the missing feature flag for `ewm_mean_by`
