crates/polars-plan/src/dsl/function_expr/strings.rs, crates/polars-plan/src/dsl/string.rs, py-polars/src/expr/string.rs
Caught a fish that slipped through the net. 😉 
The next step is to expressify this one.
=> refactor: Make `json_path_match` expr non-anonymous

crates/polars-plan/src/logical_plan/optimizer/cache_states.rs, py-polars/tests/unit/test_cse.py
=> fix: Include predicate in cache state union

crates/polars-plan/src/logical_plan/builder.rs
=> fix: Ensure empty with_columns is a no-op

crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/series/mod.rs, crates/polars-plan/src/dsl/python_udf.rs, py-polars/tests/unit/datatypes/test_enum.py, py-polars/tests/unit/operations/map/test_map_elements.py
Fixes https://github.com/pola-rs/polars/issues/15695.
=> fix: allow null dtypes in UDFs if they match the schema

py-polars/polars/expr/datetime.py, py-polars/polars/series/datetime.py
Continuation of https://github.com/pola-rs/polars/pull/15648
Applies suggested phrasing from that PR consistently throughout docstring and deprecation warning.
=> docs(python): Align docstring phrasing in `Series/Expr.dt.truncate/round`

crates/polars-ops/src/frame/join/args.rs, crates/polars-ops/src/frame/join/mod.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
=> feat: Remove outdated join validation checks

crates/polars-core/src/chunked_array/comparison/scalar.rs
Fixes https://github.com/pola-rs/polars/issues/11805.
Currently only works if there are no nulls in the data, and only for primitive types (no strings / nested data).
Also only works for broadcasting equality, not `Series == Series`.
=> perf: use two binary searches for equality mask when data is sorted

crates/polars-lazy/src/physical_plan/expressions/window.rs
@ritchie46 fix for the usage we discussed
=> fix: Ensure we don't hold onto Mutex when grabbing join tuples

py-polars/src/functions/lazy.rs, py-polars/tests/unit/functions/test_lit.py, py-polars/tests/unit/operations/test_with_columns.py
Closes https://github.com/pola-rs/polars/issues/15588
=> feat(python): Improve error message when passing invalid input to `lit`

crates/polars-lazy/src/physical_plan/expressions/aggregation.rs, py-polars/tests/unit/operations/test_aggregations.py
=> fix: count of null column shouldn't panic in agg context

crates/polars-plan/src/dsl/mod.rs, py-polars/tests/unit/operations/test_cut.py
We should pass the name to apply, otherwise the name of bin column will be `_bin`.
=> fix: pass series name to apply for cut/qcut

crates/polars-arrow/src/array/growable/binview.rs
=> perf: Fix quadratic in binview growable same source

crates/polars-plan/src/dsl/function_expr/ewm_by.rs, crates/polars-time/src/windows/duration.rs
This would enable deduping a few things in https://github.com/pola-rs/polars/pull/12597/files
=> chore(rust): Factor out `ensure_is_constant_duration`

crates/polars-core/src/chunked_array/cast.rs, py-polars/tests/unit/datatypes/test_enum.py
=> fix: Remove incorrect unsafe pointer cast for int -> enum

crates/polars-core/src/chunked_array/logical/categorical/ops/full.rs, crates/polars-core/src/series/ops/null.rs, py-polars/tests/unit/datatypes/test_categorical.py
=> fix: Preserve lexical ordering on concat

crates/polars-arrow/src/compute/take/list.rs, py-polars/tests/unit/datatypes/test_list.py
=> fix: Handle null index correctly for list take

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/datetime.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/datetime.py
There are places where `"1i"` is allowed in the duration string language, but not always. `.dt.offset_by('3i')` for example doesn't make sense, because the operation can only be called on a temporal column anyway
`join_asof` already raises if `'1i'` is passed, I think the docs were just copy-and-pasted over
=> docs(python): Remove incorrect "1i (1 index count)" from some docs methods

crates/polars-error/src/lib.rs, crates/polars-plan/src/logical_plan/conversion/dsl_plan_to_ir_plan.rs, crates/polars-utils/src/io.rs, crates/polars/tests/it/lazy/projection_queries.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/src/error.rs, py-polars/tests/unit/test_lazy.py
Debuggin `LazyFrames` just got a lot easier:
=> feat(rust!, python): Add context trace to `LazyFrame` conversion errors

crates/polars-plan/src/logical_plan/pyarrow.rs, py-polars/tests/unit/io/test_pyarrow_dataset.py
Fixes https://github.com/pola-rs/polars/issues/15765
=> fix: Fix incorrect `is_between` pushdown to `scan_pyarrow_dataset`

py-polars/polars/datatypes/classes.py
Fixes a copy-paste related mistake where the description of `is_float` said it's checking for a temporal type instead of a floating point one which showed up in the API documentation.
=> docs(python): Fix a docstring mistake for DataType.is_float

crates/polars-core/src/datatypes/any_value.rs, py-polars/src/conversion/any_value.rs, py-polars/src/conversion/mod.rs, py-polars/src/dataframe/construction.rs, py-polars/src/file.rs, py-polars/src/functions/eager.rs, py-polars/src/functions/io.rs, py-polars/src/series/buffers.rs, py-polars/src/series/construction.rs
Fixes #15699
There will be more follow-up PRs, this is just a small chunk of the usages that need upgrading (although hopefully not as tricky).
=> chore(python): Start at using new Bound<> API from PyO3

crates/polars-plan/src/logical_plan/optimizer/collapse_and_project.rs, py-polars/tests/unit/operations/test_slice.py
=> fix: Don't deduplicate sort that has slice pushdown

crates/polars-ops/src/chunked_array/strings/json_path.rs, crates/polars-plan/src/dsl/function_expr/strings.rs, crates/polars-plan/src/dsl/string.rs, py-polars/polars/expr/string.py, py-polars/polars/series/string.py, py-polars/src/expr/string.rs, py-polars/tests/unit/namespaces/string/test_string.py
=> feat: Expressify `str.json_path_match`

crates/polars-time/src/truncate.rs, py-polars/tests/unit/datatypes/test_temporal.py
Probably not much, but this should also improve some performance as the duration parsing cache.
Closes #15743.
=> feat: `dt.truncate` supports broadcasting lhs

crates/polars-time/src/group_by/dynamic.rs, crates/polars-time/src/upsample.rs, crates/polars-time/src/windows/duration.rs, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/rolling/test_rolling.py, py-polars/tests/unit/operations/test_group_by_dynamic.py
=> fix: raise if index count like 2i is used when performing rolling, group_by_dynamic, upsample, or other temporal operatios

.github/workflows/codecov.yml
I suspect this will be faster than the current setup when the caching kicks in. Let's see! Otherwise, we can always revert.
=> ci: Split coverage calculation

crates/polars-utils/src/sys.rs
Fixes https://github.com/pola-rs/polars/issues/15797
=> fix: Consult cgroups to determine free memory

py-polars/polars/functions/as_datatype.py
=> docs(python): Add docstring examples for datetimes (#13161)

py-polars/polars/io/database/_inference.py, py-polars/tests/unit/io/database/test_inference.py
Adds basic recognition for "DURATION" and "NULL" type names/strings.
=> feat(python): Minor type-inference update for `read_database`

crates/polars-ops/src/series/ops/ewm_by.rs, py-polars/tests/unit/operations/test_ewm_by.py
On the latest release, initial null values are skipped when the dataframe is already known to be sorted by `'by'`, resulting in errors like
```
ShapeError: unable to add a column of length 4 to a DataFrame of height 5
```
=> fix: ewm_mean_by was skipping initial nulls when it was already sorted by "by" column

crates/polars-sql/src/sql_expr.rs, crates/polars-sql/tests/simple_exprs.rs, py-polars/docs/source/reference/dataframe/modify_select.rst, py-polars/docs/source/reference/lazyframe/modify_select.rst, py-polars/docs/source/reference/sql.rst, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/sql/context.py, py-polars/tests/unit/sql/test_array.py, py-polars/tests/unit/sql/test_conditional.py, py-polars/tests/unit/sql/test_joins.py, py-polars/tests/unit/sql/test_miscellaneous.py, py-polars/tests/unit/sql/test_numeric.py, py-polars/tests/unit/sql/test_strings.py, py-polars/tests/unit/sql/test_temporal.py
Been thinking about this for a while; introduces a new `sql()` method for both DataFrame and LazyFrame. Makes use of `SQLContext` internally, streamlining the usage of ad-hoc SQL on frames.
* Automatically registers the calling frame as "self" in the SQL context.
* Automatically identifies other frames from the globals.
* Plenty of examples and docstring detail.
```python
"a": [1, 2, 3],
"b": ["zz", "yy", "xx"],
"c": [date(1999, 12, 31), date(2010, 10, 10), date(2077, 8, 8)],
})
df.sql("SELECT a::float4, b, EXTRACT(year FROM c) AS c_year FROM self WHERE a > 1")
```
* Recognises additional PostgreSQL float casts: `::float4` (32bit) and `::float8` (64bit) and `::float(n)`.
* Allows the full range of `::timestamp(n)` precision …
=> feat(python): Add a low-friction `sql` method for DataFrame and LazyFrame

crates/polars-time/src/chunkedarray/string/mod.rs, crates/polars-utils/src/cache.rs
Fix #15736.
```
s = pl.datetime_range(date(2000, 1, 1), date(2001, 1, 1), '1s', eager=True)
strings = s.dt.strftime('%Y-%m-%dT%H:%M:%S')
```
Without cache:
```
%timeit strings.str.to_datetime(format='%Y-%m-%dT%H:%M:%S', cache=False)
1.47 s ± 71.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
With cache:
```
%timeit strings.str.to_datetime(format='%Y-%m-%dT%H:%M:%S', cache=True)
```
- Before this PR
```
18.2 s ± 790 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
- After this PR
```
1.88 s ± 59.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Consider that the test data are all unique(The cache will never hit) and large, I think the overhead is acceptable.
=> perf: Limit the cache size for `to_datetime`

docs/user-guide/lazy/query-plan.md, py-polars/polars/lazyframe/frame.py
See #15755 and maybe closes #12477
Adds links pointing to graphviz install page, let me know if I should change anything
=> docs(python): improve graphviz install documentation/error message

py-polars/pyproject.toml
This file must be included with the `sdist` to allow compiling from source. Wheels do not need to include it though.
=> build(python): Exclude `rust-toolchain.toml` from wheels

crates/polars-core/src/chunked_array/logical/categorical/builder.rs, crates/polars-ops/src/series/ops/cut.rs
This fixes https://github.com/pola-rs/polars/issues/15670, that is if you pass a fixed set of labels everything works now.
For dynamically generated labels like in https://github.com/pola-rs/polars/issues/15781 there are still issues, but they lie in the way categoricals are combined in the `over` handling. Perhaps @c-peters can look at that.
Also fixes https://github.com/pola-rs/polars/issues/13038.
=> fix: create (q)cut labels in fixed order

py-polars/polars/io/_utils.py, py-polars/polars/io/ipc/anonymous_scan.py, py-polars/tests/unit/io/cloud/test_aws.py
=> fix(python): Don't modify user-supplied `storage_options` dict (take a shallow-copy)

py-polars/polars/io/spreadsheet/functions.py, py-polars/tests/unit/io/test_spreadsheet.py
Fixes a potential edge-case where values that appear to be all-integer (but are explicitly designated as float in "schema_overrides") are converted _back_ to integer instead of respecting the override.
Added suitable/new test coverage.
=> fix(python): Refine interaction of "schema_overrides" with `read_excel` when using "calamine" engine

py-polars/src/batched_csv.rs, py-polars/src/conversion/mod.rs, py-polars/src/dataframe/general.rs, py-polars/src/dataframe/io.rs, py-polars/src/file.rs, py-polars/src/map/dataframe.rs, py-polars/src/map/mod.rs, py-polars/src/series/construction.rs
Fixes #15864 
More lifetime issues... the hardest one was keeping the temporary PyBytes object read from BytesIO.getvalue() alive. Perhaps there's another way to do this.
=> chore(python): More PyO3 0.21 bound APIs

crates/polars-arrow/src/array/binview/mod.rs, crates/polars-core/src/chunked_array/arithmetic/mod.rs, crates/polars-core/src/chunked_array/cast.rs, crates/polars-core/src/chunked_array/ops/append.rs, crates/polars-core/src/chunked_array/ops/filter.rs, crates/polars-core/src/chunked_array/ops/gather.rs, crates/polars-core/src/chunked_array/ops/reverse.rs, crates/polars-core/src/chunked_array/ops/shift.rs, crates/polars-core/src/chunked_array/ops/sort/mod.rs, crates/polars-core/src/chunked_array/ops/unique/mod.rs, crates/polars-core/src/datatypes/mod.rs, crates/polars-core/src/frame/group_by/aggregations/string.rs, crates/polars-ops/src/chunked_array/gather/chunked.rs, crates/polars-ops/src/chunked_array/top_k.rs
Gather by slices accidentally hit the generic gather. This is very expensive for binary/string views as all buffers get naively added.
#15847
=> perf: Ensure we hit specialized gather for binary/strings

crates/polars-core/src/chunked_array/mod.rs, crates/polars-core/src/frame/group_by/aggregations/agg_list.rs, crates/polars-core/src/frame/group_by/proxy.rs, crates/polars-ops/src/series/ops/various.rs
Fixes performance by making it a `gather` + `offset` wrap.
fixes #15847
=> perf: Improve non-trivial list aggregations

crates/polars-arrow/src/array/primitive/mod.rs, crates/polars-arrow/src/offset.rs, crates/polars-lazy/src/physical_plan/expressions/apply.rs, py-polars/tests/unit/operations/aggregation/test_aggregations.py
=> fix: Fix OOB in struct lit/agg aggregation

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/projection.rs, py-polars/tests/unit/test_projections.py
=> fix: double projection check should only take the upstream projections into account

crates/polars-arrow/src/compute/decimal.rs, py-polars/tests/unit/datatypes/test_decimal.py
fix #13985
currently decimal values are formatted without any decimal values **if value is an integer**.
Decimal[scale=2]
- 1.23 -> 1.23
- 1.2 -> 1.20
- 1 -> 1 💥 
This is inconsistent and different than in all other systems like databases.
new:
- 1 -> 1.00 ✅
=> fix(python,rust): fix inconsistent decimal formatting

py-polars/polars/_cpu_check.py
Our MacOS runners were failing due to invalid permissions for the `mmap` call. This may fix it.
=> fix: avoid WRITE+EXEC for CPUID check

.github/workflows/test-coverage.yml
Ref https://github.com/pola-rs/polars/issues/15917
Will look into this when I'm back from vacation. At least the CI can run normally until then.
=> ci(rust): Pin coverage job to MacOS 13 for now

crates/polars-io/src/csv/read/mod.rs, crates/polars-io/src/csv/read/options.rs, crates/polars-io/src/csv/read/reader.rs, crates/polars-lazy/src/physical_plan/executors/scan/csv.rs, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-plan/src/logical_plan/builder_dsl.rs, crates/polars-plan/src/logical_plan/conversion/scans.rs, crates/polars-plan/src/logical_plan/file_scan.rs, py-polars/polars/io/csv/functions.py
* Rename `CsvParserOptions` to `CsvReaderOptions`
* Allow passing a `CsvReaderOptions` to `CsvReader`.
There are many more places internally where we can use `CsvReaderOptions` - this will be implemented in followup PRs
=> feat(rust!): Rename to `CsvParserOptions` to `CsvReaderOptions`, use in `CsvReader`

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/polars/type_aliases.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/test_cse.py
=> fix(python): series.search_sorted could support more types of input

py-polars/polars/_utils/udfs.py, py-polars/polars/expr/expr.py
At some point/version of numba or numpy "they" made it so the ufunc that gets handed to `__array_ufunc__` changes its class so that looking at the class doesn't distinguish a numba ufunc from a native numpy ufuncs. This is relevant because all the numpy/scipy native ufuncs are elementwise whereas the numba ufuncs probably aren't.
Luckily, it still is the case that ufuncs produced by numba have a signature field whereas the native ufuncs have signature None so I just switched the custom ufunc to that check.
=> fix(python): Change recognition of numba ufunc

py-polars/polars/_utils/construction/dataframe.py, py-polars/polars/_utils/construction/series.py, py-polars/polars/_utils/construction/utils.py, py-polars/tests/unit/interop/test_interop.py
closes #15845
On main:
- converting from pandas to Polars without PyArrow installed always raises
Here:
- if a dataframe only has simple numpy-backed dtypes (like 'int64', 'bool', 'datetime64[ms]', ...), then conversion to Polars can happen without PyArrow installed. If PyArrow isn't installed, it raises
- if a dataframe has more complex dtypes (like categorical, nullable integers, anything pyarrow-backed), then pyarrow is required
Technically it's possible to convert pandas to Polars using the dataframe interchange protocol, although there have been too many bugs on the pandas side, I don't feel comfortable suggesting it as a solution
This is a simple fix which addresses scikit-learn's reported issue (wanting to convert pandas to Polars in their docs) which doesn't go via PyArrow and …
=> feat(python): don't require pyarrow for converting pandas to Polars if all columns have simple numpy-backed datatypes

crates/polars-arrow/src/legacy/kernels/ewm/mod.rs
Updated fn body to match documented formula.
=> fix(rust): typo in add_half_life takes ln(negative)

crates/polars-core/src/fmt.rs, py-polars/polars/config.py, py-polars/polars/dataframe/_html.py, py-polars/polars/expr/string.py, py-polars/polars/series/string.py, py-polars/polars/series/struct.py, py-polars/src/series/mod.rs, py-polars/tests/unit/test_config.py, py-polars/tests/unit/test_format.py
Closes https://github.com/pola-rs/polars/issues/15839
* Set the default character limit for displaying String columns to 30
* For DataFrames, changed from 32 to 30
* For Series, changed from 15 to 30
* Do not count quotes surrounding the value towards the character limit
* Update the HTML repr (Notebooks) to match.
* Make sure Categorical/Enum types follow the same rules (was already the case in the HTML repr).
**Example**
```python
with pl.Config(fmt_str_lengths=4):
print(pl.Series(["abc", "abcd", "abcde"]))
```
```
shape: (3,)
[
"abc"
"abcd"
"abcd…    <- note: no trailing quote
]
```
=> fix: Set default limit for String column display to 30 and fix edge cases

py-polars/tests/unit/io/test_parquet.py
Don't use `tmpdir`, use `tmp_path` instead.
EDIT: That wasn't the issue - the actual issue is that Windows doesn't allow asterisks in filenames. I added a glob test for Windows.
=> test(python): Fix failing test

py-polars/polars/io/csv/functions.py, py-polars/tests/unit/io/test_csv.py
* Support for "truncate_ragged_lines" existed, but it wasn't exposed - fixed.
* As a minor drive-by, added a bit more detail to the "decimal_comma" docstring.
=> fix(python): Add missing "truncate_ragged_lines" parameter to `read_csv_batched`

crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-core/src/chunked_array/ops/unique/mod.rs, crates/polars-core/src/series/implementations/binary_offset.rs, py-polars/tests/unit/operations/test_join.py
=> fix: Join validation for multiple keys

crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/series/comparison.rs, py-polars/tests/unit/operations/test_comparison.py, py-polars/tests/unit/test_errors.py
This is a small 'bandaid' fix for comparisons between non-compatible dtypes and categorical to avoid panicking
fix #15844
=> fix: do not panic when comparing against categorical with incompatible dtype

py-polars/polars/_utils/construction/series.py, py-polars/polars/series/series.py, py-polars/tests/unit/series/test_series.py
closes #15939, and is a little fix for #15933
=> fix(python): Fix dtype parameter in `pandas_to_pyseries` function

crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/tests/streaming.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-ops/src/frame/join/hash_join/mod.rs, crates/polars-ops/src/frame/join/mod.rs, crates/polars-pipe/src/executors/sinks/joins/generic_build.rs, crates/polars-pipe/src/pipeline/convert.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, crates/polars-plan/src/logical_plan/schema.rs, crates/polars-sql/src/context.rs, crates/polars/tests/it/core/joins.rs, crates/polars/tests/it/joins.rs, crates/polars/tests/it/lazy/projection_queries.rs, docs/src/rust/user-guide/transformations/joins.rs, py-polars/polars/lazyframe/frame.py, py-polars/src/conversion/mod.rs, py-polars/src/lazyframe/mod.rs
Prepare for a `coalesce: None | bool` argument in the join operator. This will default to `None` and keep the join specific join key coalescing behavior. But users will be able to set the behavior and force/turn off coalescing if needed.
TODO: instead of gathering the redundant column, clone it post-join as this will save 1 column of data.
=> refactor(rust!): prepare for join coalescing argument

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_temporal.py
@ritchie46: here you go ;)
(Otherwise it seems the `dt.second` op can overflow `int8` during scaling and wrap around to odd values; not immediately obvious why it decided to do this now vs earlier, but the solution is straightforward).
=> fix: Finish adding `typed_lit` to help schema determination in SQL "extract" func

crates/polars-core/src/chunked_array/from_iterator_par.rs, crates/polars-lazy/src/dsl/list.rs, crates/polars-lazy/src/physical_plan/expressions/apply.rs, crates/polars-lazy/src/physical_plan/expressions/sortby.rs, crates/polars-lazy/src/physical_plan/planner/expr.rs, crates/polars-lazy/src/tests/aggregations.rs, crates/polars-lazy/src/tests/queries.rs, crates/polars-plan/src/dsl/function_expr/cum.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/logical_plan/aexpr/schema.rs, py-polars/src/functions/lazy.rs
This will ensure we keep the `dtype` equal to the schema.
=> feat: Add typed collection from par iterators

Cargo.lock, LICENSE, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/mod.rs, py-polars/Cargo.toml, py-polars/src/conversion/mod.rs, py-polars/src/lazyframe/mod.rs, py-polars/src/lazyframe/visit.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/src/lazyframe/visitor/mod.rs, py-polars/src/lazyframe/visitor/nodes.rs, py-polars/src/lib.rs
This is a (reasonably complete) exposing of the `IR` and `AExpr` enums via `#[pyclass]` structs to Python.
The best place to start a review is probably `visitor/nodes.rs` (the `expr_nodes.rs` wrapping of expressions follows the same pattern, but there are more structs to go through). I am reasonably happy with the structure, but not fully up-to-speed on the most idiosyncratic ways of doing things. For example, should I implement `ToPyObject` for `Wrap<&IR>` rather than having an `into_py` free function?
=> feat(python): Expose plan and expression nodes through `NodeTraverser` to Python

crates/polars-core/src/chunked_array/ops/sort/arg_sort.rs, crates/polars-core/src/chunked_array/ops/sort/mod.rs, py-polars/tests/unit/dataframe/test_df.py
Since nulls compare equal, a stable sort should select the nulls in
the order of the input series, independently of whether we asked for a
descending or ascending sort of the Series.
- Closes https://github.com/pola-rs/polars/issues/9940
=> fix(rust): Do not reverse null indices in descending arg_sort

README.md
A follow up for pola-rs/r-polars#1067
We have moved the document to the repo's GitHub Pages.
=> docs: update the link to R API docs

crates/polars-arrow/src/array/mod.rs, crates/polars-arrow/src/mmap/array.rs, crates/polars-core/src/series/from.rs, py-polars/tests/unit/io/test_ipc.py
Resolves https://github.com/pola-rs/polars/issues/15920
128-bit values could be unaligned, in which case we need to do a copy (`write_ipc` currently doesn't align them).
=> feat: Support Decimal read from IPC

crates/polars-lazy/src/frame/mod.rs, py-polars/polars/lazyframe/__init__.py, py-polars/polars/lazyframe/frame.py, py-polars/src/lazyframe/mod.rs, py-polars/src/lazyframe/visit.rs, py-polars/src/lib.rs, py-polars/tests/unit/lazyframe/cuda/test_node_visitor.py
This allows a post-optimization python callback to be inserted.
=> feat(python): Add post-optimization callback

crates/polars-ops/src/chunked_array/strings/namespace.rs, crates/polars-ops/src/chunked_array/strings/split.rs, py-polars/tests/unit/namespaces/string/test_string.py
This PR fixes the behavior of `str.split`, `str.split_exact` and `str.splitn` by treating splitting by an empty string as iterating over chars.
Closes #14604
=> fix(rust): Treat splitting by empty string as iterating over chars

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_cast.py
Finally got to grips with destructuring a nested `vec` ("hello `as_slice`"😜) so was able to cleanly register some custom datatypes with the SQL parser.
* PostgreSQL supports the following integer types `int2`,`int4`,`int8` (for which we also allow the `smallint`, `integer` and `bigint` aliases). Unfortunately it does not offer _unsigned_ ints, and the parser doesn't offer them (directly) either. We also allow `tinyint` for 1 byte ints.
* There is an extension called `pguint`[^1] (maintained by one of the PostgreSQL core developers) that adds `uint1`,`uint2`,`uint4`, and `uint8` types (as well as `int1`). 
* This PR adds support for recognising these additional integer types by registering them with the parser's `SQLDataType::Custom` extension point.
* Also contains a fix for "CAST", …
=> feat: Additional `uint` datatype support for the SQL interface

crates/polars-core/src/chunked_array/logical/categorical/mod.rs, crates/polars-ops/src/series/ops/cut.rs, py-polars/tests/unit/operations/test_cut.py
Fixes https://github.com/pola-rs/polars/issues/15981.
We recently added the categories upfront to make them deterministic, but we forgot to ensure that the fast unique setting was set properly:
```python
>>> pl.Series([1]).cut([1, 2, 3])
shape: (1,)
Series: '' [cat]
[
"(-inf, 1]"
]
>>> pl.Series([1]).cut([1, 2, 3]).n_unique()
4
```
As a note, it looks like `CategoricalChunkedBuilder` automatically sets fast unique to `true` by default:
https://github.com/pola-rs/polars/blob/d5cf03856929ffa25180873754faef8238fc3b5d/crates/polars-core/src/chunked_array/logical/categorical/builder.rs#L195-L206
=> fix: Crash/incorrect group_by/n_unique on categoricals created by (q)cut

py-polars/polars/testing/parametric/primitives.py, py-polars/polars/testing/parametric/strategies.py, py-polars/tests/unit/conftest.py
It's now possible to supply a precision/scale and the proper decimal values will be generated.
I also set up the `dtype_strategies` strategy which will be key to upgrading the list/array strategies (these need to be converted to a composite strategy).
Next step will be to set up a `dtypes` strategy which generates a random Polars data type. This will be used by the list/array strategies. Then I will upgrade the list/array strategies and we can finally upgrade to the latest hypothesis version.
=> test(python): Improve hypothesis strategy for decimals

py-polars/polars/expr/expr.py
The docs examples state
> Compute the rolling var with the default left closure of temporal windows
although `closed='right'` has been the default for a while
=> docs(python): correct default in rolling_* function examples

crates/polars-lazy/src/dsl/functions.rs, crates/polars-lazy/src/tests/cse.rs, crates/polars-plan/src/logical_plan/optimizer/cache_states.rs, crates/polars-plan/src/logical_plan/schema.rs, py-polars/tests/unit/test_cse.py
=> fix: Fix CSE case where upper plan has no projection

crates/polars-arrow/src/array/dictionary/mod.rs, crates/polars-arrow/src/array/dictionary/typed_iterator.rs
Closes https://github.com/pola-rs/polars/issues/16004.
=> fix: properly handle nulls in DictionaryArray::iter_typed

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py
By changing double backslashes to single backslashes to prevent unwanted linebreak. Fixes #14454. Applies to `Series.bottom_k`, `Series.top_k`, `Expr.bottom_k` and `Expr.top_k`. I searched the Python and Rust files and did not notice any other instances where this change seemed to be needed.
=> docs(python): Remove unwanted linebreaks from docstrings

crates/polars-lazy/src/dsl/functions.rs, crates/polars-lazy/src/prelude.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/scan/file_list_reader.rs, crates/polars-plan/src/logical_plan/conversion/dsl_to_ir.rs, crates/polars-plan/src/logical_plan/conversion/mod.rs, crates/polars-plan/src/logical_plan/format.rs, crates/polars-plan/src/logical_plan/mod.rs, crates/polars-plan/src/logical_plan/options.rs, crates/polars-plan/src/logical_plan/tree_format.rs, py-polars/src/functions/lazy.rs
Ensure we don't expose IR state to the DSL.
=> refactor: Use UnionArgs for DSL side

py-polars/polars/io/database/_executor.py
Fixes some CI failures, following a `kuzu` version update that exposed an error.
=> fix(python): Do not close connection just because we're not returning Arrow data in batches

crates/polars-lazy/src/dsl/functions.rs, crates/polars-lazy/src/physical_plan/executors/projection_simple.rs, crates/polars-lazy/src/physical_plan/planner/lp.rs, crates/polars-plan/src/logical_plan/alp/inputs.rs, crates/polars-plan/src/logical_plan/alp/mod.rs, crates/polars-plan/src/logical_plan/builder_ir.rs, crates/polars-plan/src/logical_plan/conversion/convert_utils.rs, crates/polars-plan/src/logical_plan/conversion/dsl_to_ir.rs, crates/polars-plan/src/logical_plan/conversion/mod.rs, crates/polars-plan/src/logical_plan/mod.rs, crates/polars-plan/src/logical_plan/optimizer/collapse_and_project.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/hconcat.rs, crates/polars-plan/src/logical_plan/visitor/hash.rs, py-polars/src/lazyframe/visitor/nodes.rs, py-polars/tests/unit/functions/test_functions.py
This also make diagonal concat faster as we did mutliple `with_columns` sequentially. Now they are batched.
=> feat: Move diagonal & horizontal concat schema resolving to IR phase

py-polars/polars/functions/as_datatype.py
The default behavior of `ignore_nulls` in `concat_str` is incorrectly documented. 
Not sure which default value is more intuitive, I simply corrected the documentation to avoid breaking changes. Though it differs from `Series.list.concat` or `Series.string.concat`, where the default value is `True`, introducing some inconsistency.
=> docs(python): Fix docstring mistake for polars.concat_str

py-polars/polars/io/database/_inference.py, py-polars/tests/unit/io/database/test_inference.py
A much larger update for database-related type inference is brewing, but this is a minor update to catch "bpchar" and "cardinal number" type names (as used in PostgreSQL).
=> feat(python): Minor DB type inference updates

crates/polars-lazy/src/physical_plan/streaming/checks.rs, crates/polars-ops/src/frame/join/mod.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/operations/test_join.py
closes #14925
Left join still coalesces by default. Would need a breaking release to change the default.
=> feat: Support non-coalescing joins in default engine

crates/polars-arrow/src/compute/cast/binary_to.rs, crates/polars-arrow/src/compute/cast/binview_to.rs, crates/polars-arrow/src/compute/cast/primitive_to.rs, crates/polars-arrow/src/compute/cast/utf8_to.rs, crates/polars-io/src/parquet/write/writer.rs, crates/polars-parquet/src/arrow/write/dictionary.rs, crates/polars-parquet/src/arrow/write/mod.rs, crates/polars-parquet/src/arrow/write/nested/mod.rs, crates/polars-parquet/src/arrow/write/utils.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/encoder.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs, crates/polars/tests/it/io/parquet/write/binary.rs, crates/polars/tests/it/io/parquet/write/primitive.rs, py-polars/tests/unit/io/test_parquet.py
The `RLE_DICTIONARY` encoder currently only supports bit-packing. After this PR, the encoder will switch between bit-packing and RLE depending on whether a run is longer than 8 ([always bit-pack a multiple of 8 values at a time](https://parquet.apache.org/docs/file-format/data-pages/encodings/)).
This addresses the specific case pointed out in #10680. With these changes, I get 2745 bytes for `pl_zstd.pq` and 2962 bytes for `pa_zstd.pq` after running the following code:
```python
from random import randint
rand_value = randint(1, 10**15)
'A': [rand_value for _ in range(10_000_000)],
}, schema={
'A': pl.UInt64,
})
df.write_parquet('pa_zstd.pq', compression='zstd', use_pyarrow=True)
df.write_parquet('pl_zstd.pq', compression='zstd', use_pyarrow=False, …
```
=> feat(rust): Add RLE to `RLE_DICTIONARY` encoder

py-polars/polars/datatypes/convert.py, py-polars/src/conversion/any_value.rs, py-polars/tests/unit/constructors/test_series.py, py-polars/tests/unit/test_datatypes.py
=> fix(python): Correctly handle large timedelta objects in Series constructor

py-polars/docs/source/reference/expressions/modify_select.rst, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/src/expr/general.rs, py-polars/tests/unit/operations/test_sort.py
closes #16037 
Summary of changes:
- `top_k_by` is broken off from `top_k`
- removed `by` and `descending` args from `top_k` (they aren't in the latest stable release. `by` is being removed to split out `top_k_by`, and `descending` just doesn't seem useful for a single `top_k`, you can just use `bottom_k`...)
- drive-by: corrected `log{}n` to `log{n}` in the docstring
- removed some tests which are no longer relevant (that's one advantage of splitting the functions up actually)
(same for `bottom_k` / `bottom_k_by`)
=> feat(python): split Expr.top_k and Expr.top_k_by into separate functions

crates/polars-core/src/utils/supertype.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> fix: Decimal supertype for dyn int

py-polars/polars/_utils/construction/series.py, py-polars/tests/unit/constructors/test_series.py
Closes #16033
This should make it take the same path as List types.
=> fix(python): Fix Series constructor failure for Array types for large integers

crates/polars-time/src/chunkedarray/string/patterns.rs, py-polars/tests/unit/namespaces/test_strptime.py
close #14990
- add `dd.mm.YYYY` date pattern which is widely used.
- enables automatic date inference for `to_date` as well as in `read_csv`
- also added tests for all date patterns
```python
pl.DataFrame({"D.M.Y": ["01.02.2020", "03.04.2020", "31.12.2020"]}).with_columns(
pl.all().str.to_date()
)
shape: (3, 1)
┌────────────┐
│ D.M.Y      │
│ ---        │
│ date       │
╞════════════╡
│ 2020-02-01 │
│ 2020-04-03 │
│ 2020-12-31 │
└────────────┘
pl.read_csv(
source="dates\n01.02.2020\n03.04.2020\n31.12.2020".encode(),
try_parse_dates=True,
)
shape: (3, 1)
┌────────────┐
│ dates      │
│ ---        │
│ date       │
╞════════════╡
│ 2020-02-01 │
│ 2020-04-03 │
│ 2020-12-31 │
└────────────┘
```
=> feat(python,rust): add date pattern `dd.mm.YYYY`

py-polars/polars/functions/as_datatype.py
contributes to #13161 
I added examples for how to use `polars.date` and `polars.datetime` in combination with row filtering in a dataframe.
ping @MarcoGorelli
=> docs: add filter docstring examples to date and datetime

crates/polars-arrow/src/compute/cast/decimal_to.rs, py-polars/tests/unit/operations/test_cast.py, py-polars/tests/unit/sql/test_numeric.py
Closes https://github.com/pola-rs/polars/issues/16027
=> fix: Fix casting decimal to decimal for high precision

py-polars/polars/datatypes/convert.py, py-polars/polars/functions/col.py, py-polars/polars/selectors.py
I ran into this - minor typing improvement.
=> refactor(python): Add TypeGuard to `is_polars_dtype` util

py-polars/docs/source/reference/expressions/computation.rst, py-polars/polars/expr/expr.py, py-polars/tests/parametric/test_groupby_rolling.py, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/rolling/test_rolling.py
This took...quite some effort
OK if I start with the Python side, so people get the warning sooner rather than later? I've started the Rust side, it's going to take longer to complete. On the plus side, this simplifies _a lot_, really nice suggestion from Orson here
=> feat(python): split out rolling_*(..., by='foo') into rolling_*_by('foo', ...)

.github/workflows/test-python.yml, Makefile, py-polars/Makefile, py-polars/polars/dependencies.py, py-polars/polars/ml/torch.py, py-polars/pyproject.toml, py-polars/requirements-ci.txt, py-polars/requirements-dev.txt, py-polars/tests/unit/dataframe/test_to_torch.py
Streamlining the default dev environment...
* Moves `torch` package from "requirements-dev.txt" to new "requirements-ci.txt".
* Ensures that typing lint passes for `polars.ml.torch` with/without local `torch` install.
* Renames the `third_party_integration` marker to `ci_only` to better describe its purpose.
* Adds a `make requirements-all` command that installs the usual dev packages _and_ the "CI only" packages.
* Makes the top-level `torch` import in the "test_to_torch" unit tests lazy-load so that optional absence of the package doesn't cause `pytest` to complain when run locally (the CI runner will always have it installed, so no issue there).
We might want to make a couple of other packages CI-only by default, but for now this only covers the new `torch` integrations.
=> tests(python): Make `torch` install CI-only by default

crates/polars-core/src/frame/mod.rs, crates/polars-core/src/utils/mod.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-io/src/parquet/write/batched_writer.rs, crates/polars-io/src/parquet/write/mod.rs, crates/polars-io/src/utils.rs, crates/polars-lazy/src/physical_plan/executors/group_by_partitioned.rs, crates/polars-ops/src/frame/join/asof/groups.rs, crates/polars-parquet/src/arrow/write/file.rs, crates/polars-parquet/src/arrow/write/mod.rs, crates/polars-parquet/src/arrow/write/row_group.rs, crates/polars-parquet/src/parquet/write/file.rs, crates/polars-parquet/src/parquet/write/mod.rs, crates/polars-parquet/src/parquet/write/row_group.rs, crates/polars-parquet/src/parquet/write/stream.rs, crates/polars-pipe/src/executors/sinks/group_by/ooc.rs, crates/polars-pipe/src/executors/sinks/output/parquet.rs, crates/polars-pipe/src/executors/sinks/sort/source.rs, crates/polars-pipe/src/executors/sources/frame.rs, crates/polars/tests/it/core/joins.rs
If a chunk in a DataFrame was 100k rows and we split at 100k - 1 we wrote row-groups of 1, which is terrible. This ensures we keep reasonable sized chunks.
=> perf: Ensure better chunk sizes

.github/workflows/benchmark.yml, .github/workflows/docs-global.yml, .github/workflows/lint-python.yml, .github/workflows/test-coverage.yml
Added "requirements-ci.txt" where missing and tweaked some `uv` calls (by using `-r ` twice) so they only have to do a single resolve instead of two.
=> ci(python): Update benchmarks/coverage jobs with "requirements-ci"

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py
Closes #16055.
* Turns out we already had docstring warnings to draw attention to `nan` not being `null`, but only on the DataFrame/LazyFrame `fill_nan` methods, not the Expression or Series equivalents - now present on all.
* Made `Expr` an explicit part of the typing, since it _is_ supported (and already covered by tests).
* Added some bonus `See Also` sections to further increase visibility.
=> docs(python): Ensure consistent docstring warning in `fill_nan` methods (pointing out that `nan` isn't `null`)

crates/polars-core/src/datatypes/dtype.rs
=> fix: Materialize dtypes when converting to arrow

.github/workflows/benchmark.yml
This should fix a warning message for using an old version of node JS.
=> ci: Bump `sccache` action

crates/polars-plan/src/logical_plan/optimizer/cse/cse_lp.rs
=> perf: Don't traverse deep datasets that we repr as union in CSE

py-polars/polars/io/spreadsheet/functions.py
#15808  introduces a collision check between infer_schema_length and read_options["schema_sample_rows"]. However, users who previously specified only the `infer_schema_length` in `read_options` may still encounter the `ParameterCollisionError`.
=> fix(python): Improve error handling of `ParameterCollisionError` in `read_excel`

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_literals.py
Noticed SQL parsing didn't handle hex & bit string literals consistently between the `visit_literal` and `visit_any_value` codepaths, which would cause "IN" clauses using such literals to raise an error. 
Factored out some common code, aligned the conversions, and added some test coverage.
=> fix: Ensure hex and bitstring literals work inside SQL `IN` clauses

py-polars/polars/series/series.py
It is my intention that every feature listed in any API documentation should have an example. I'm happy to help make this a reality for Polars.
Fixes #16122
=> docs(python): Add example to polars.Series.flags

py-polars/polars/dataframe/frame.py, py-polars/polars/dependencies.py, py-polars/polars/type_aliases.py, py-polars/tests/unit/io/database/test_write.py
Closes #16095.
Closes #16053.
Closes #15538.
Also: ref #7852.
---
So, The Great Database Write Rewrite™ is still pending, but this PR closes a number of outstanding Issues and enables various opt-in speedups to ensure that we can take better advantage of the underlying engines that we currently call into.
ℹ️ This is a non-breaking change; all existing usage is unaffected.
* Can now supply an instantiated SQLAlchemy or ADBC connection directly; no longer limited to passing just the URI.
* This allows such connections to be established with specific optimisations, such as `fast_executemany` for pyodbc mssql connections, and other per-connection configuration parameters.
* Adds a new `engine_options` parameter that gets passed down to the chosen engine's underlying insert method (eg: pandas' …
=> feat(python): Support passing instantiated adbc/alchemy connection objects to `write_database`

py-polars/tests/docs/run_doctest.py
@MarcoGorelli 😁 
Further refines the optional nature of certain modules in the standard dev environment...
Adds a registration point in the `run_doctests` script that allows the "to_torch" doctests to be transparently skipped if the user has not installed the `torch` package; if they have it, the tests _do_ run (so the developers of such functionality will still be able to validate their doctests). Generic enough that we can register other modules/method associations as needed.
=> tests(python): Support skipping doctests associated with optional modules

py-polars/src/lib.rs, py-polars/src/memory.rs
Was unable to run `make pre-commit`:
```log
error: could not compile `py-polars` (lib) due to 3 previous errors
```
This simply adds the three missing allows.
Fixes #16129
=> fix(rust): Add missing allow macros for windows

docs/development/contributing/ide.md, docs/development/contributing/index.md, docs/development/contributing/test.md, py-polars/polars/dependencies.py, py-polars/polars/functions/eager.py, py-polars/pyproject.toml, py-polars/requirements-ci.txt, py-polars/requirements-dev.txt, py-polars/tests/unit/io/test_iceberg.py
Ref: https://github.com/pola-rs/polars/pull/16058.
Marks the iceberg tests/deps "ci-only", ensures that lint succeeds with/without the `pyiceberg` package installed, and includes some user guide additions to note the existence of `make requirements` and `make requirements-all`.
=> tests(python): Mark `iceberg` tests/requirements "ci-only" and make some related user guide updates

crates/polars-arrow/src/array/list/mod.rs, crates/polars-arrow/src/array/map/mod.rs, crates/polars-arrow/src/array/primitive/mutable.rs, crates/polars-arrow/src/array/union/mod.rs, crates/polars-arrow/src/buffer/immutable.rs
This PR fixed some inconsistency between code and comment in #15968 .
Closes #15968
=> docs(rust): Solve inconsistency between code and comment

py-polars/requirements-dev.txt, py-polars/tests/unit/io/database/test_read.py
New `connectorx` release (0.3.3) this morning - supports Python 3.12! 🎉 
* Updated unit tests to remove the conditional skip on 3.12.
* Updated dev requirements so we don't constrain install to <= 3.11.
=> tests(python): Update tests for new `connectorx` (now works with 3.12)

crates/polars-lazy/src/physical_plan/executors/scan/csv.rs, crates/polars-pipe/src/executors/sources/csv.rs
well, I traced it up to here:
https://github.com/pola-rs/polars/commit/28ed5326d5c90e771745b1a648e25ba50d600bf7#diff-e150944f2ee324c6d266b3ac68b6e0126b498ab282c7e08568a77c2f4b0d20cdR59
=> fix: Don't override CSV reader encoding with lossy UTF-8

py-polars/polars/series/series.py, py-polars/src/to_numpy.rs
* Update the `create_borrowed_np_array` util to take a `dtype` parameter with the desired numpy dtype.
* Add support for views on Datetime/Duration Series (and remove the workaround on the Python side).
Some more work required to also support views on DataFrames with datetime/duration types, will do in another PR.
=> refactor(python): Create NumPy view for Datetime/Duration Series on the Rust side

crates/polars-plan/src/logical_plan/lit.rs, crates/polars-plan/src/logical_plan/optimizer/cse/cse_expr.rs, crates/polars-plan/src/logical_plan/visitor/expr.rs, py-polars/tests/unit/test_cse.py
=> fix: Check CSE name aliases for collisions.

py-polars/polars/series/series.py, py-polars/src/series/export.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
Ref #14334
... as opposed to returning an integer array and then creating a view afterwards.
=> refactor(python): Return correct temporal type from Rust in `to_numpy`

examples/python_rust_compiled_function/Cargo.toml, examples/python_rust_compiled_function/src/ffi.rs, examples/python_rust_compiled_function/src/lib.rs
=> chore(python): Update plugin example to PyO3 0.21

.github/workflows/test-rust.yml, crates/polars-arrow/src/compute/cast/binary_to.rs, crates/polars-arrow/src/compute/cast/binview_to.rs, crates/polars-arrow/src/compute/cast/primitive_to.rs, crates/polars-arrow/src/compute/cast/utf8_to.rs, crates/polars-io/src/parquet/write/writer.rs, crates/polars-parquet/src/arrow/write/dictionary.rs, crates/polars-parquet/src/arrow/write/mod.rs, crates/polars-parquet/src/arrow/write/nested/mod.rs, crates/polars-parquet/src/arrow/write/utils.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/encoder.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs, crates/polars/tests/it/io/parquet/write/binary.rs, crates/polars/tests/it/io/parquet/write/primitive.rs, py-polars/tests/unit/io/test_parquet.py
Second attempt at #15959. This adds two commits on top of my original PR. One contains a fix for #16109 and better code comments (bb09b83). The other updates my test to use more realistic random data and adds new columns to check each possible branch condition (ee90a5e). I verified that these columns invoke the branch(es) mentioned in their associated comments by manually stepping through with a debugger. If you remove just the first new commit and run the test suite (running the new test on my original PR), it fails as expected.
=> feat(rust,python): Add run-length encoding to Parquet writer

py-polars/polars/series/series.py, py-polars/src/series/export.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
Moving more of the `to_numpy` implementation to Rust. This allows to create writable boolean arrays in one go, rather than casting to u8 and then copying.
=> feat(python): Avoid an extra copy when converting Boolean Series to writable NumPy array

crates/polars-io/src/parquet/write/batched_writer.rs, crates/polars-parquet/src/arrow/write/mod.rs, crates/polars-parquet/src/arrow/write/pages.rs, crates/polars-parquet/src/parquet/write/row_group.rs
Getting the `chunk`s size correct in this model is hard. I will wait for the new engine design.
=> fix: Flush parquet at end of batches tick

py-polars/polars/series/string.py
Randomly spotted, when browsing through the on-line documentation.
Note: the `ExprStringNameSpace.replace_all` docstring is correct.
=> Fix: StringNameSpace.replace_all docstring

py-polars/polars/functions/lazy.py
This PR adds deprecated messages in the docs for `cumfold` and `cumreduce`.
=> docs(python): Add deprecated messages to `cumfold` and `cumreduce`

crates/polars-ops/src/series/ops/ewm_by.rs, py-polars/tests/unit/operations/test_ewm_by.py
@orlp I've tried addressing your suggestion here, fancy taking a look please?
=> perf: use zeroable_vec in ewm_mean_by

crates/polars-core/src/frame/mod.rs, crates/polars-io/src/csv/read/read_impl/batched_mmap.rs, crates/polars-io/src/csv/read/read_impl/batched_read.rs, crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs, crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs, crates/polars-plan/src/logical_plan/optimizer/slice_pushdown_lp.rs, crates/polars-utils/src/arena.rs, py-polars/tests/unit/streaming/test_streaming_io.py
=> fix: Fix streaming glob slice

py-polars/polars/series/series.py
Added examples for multiple `Series` functions #13161
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.explode.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.limit.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.new_from_index.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.rechunk.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.shrink_dtype.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.reinterpret.html
https://pola-rs.github.io/polars/py-polars/html/reference/series/api/polars.Series.get_chunks.html
=> docs(python): Add examples for multiple `Series` functions

py-polars/polars/series/series.py, py-polars/src/conversion/chunked_array.rs, py-polars/src/series/export.rs
We used to always rechunk first when converting to NumPy. This is not great because:
* If we go through the copy path (e.g. Series contains nulls), we iterate over the values anyway and rechunking is unnecessary.
* If we go through the 'view' path (e.g. numeric Series without nulls), we do a copy (rechunk) but we end up with a non-writable array. Better to go through the copy path directly to ensure a writable array. Otherwise making the array writable is an additional copy.
Also changed some `into_iter` calls to `iter`.
=> perf(python): Avoid needless copy when converting chunked Series to NumPy

crates/polars-plan/src/dsl/expr.rs, crates/polars-plan/src/dsl/functions/selectors.rs, crates/polars-plan/src/logical_plan/expr_expansion.rs, crates/polars-plan/src/utils.rs, crates/polars-sql/src/context.rs, crates/polars-sql/tests/functions_string.rs, crates/polars-sql/tests/simple_exprs.rs, py-polars/tests/unit/sql/test_group_by.py
Closes #15585 (ref: https://github.com/pola-rs/polars/issues/14704#issuecomment-2048020360)
`GROUP BY ALL` is a useful SQL construct (as implemented by BigQuery, DuckDB, Snowflake, etc) that allows for automatic grouping by column expressions in the SELECT clause that are not (and do not contain) aggregate/window functions.
```python
dt1 = date(1999, 12, 31)
dt2 = date(2028, 7, 5)
"key": ["xx", "yy", "xx", "yy", "xx", "xx"],
"dt": [dt1, dt1, dt1, dt2, dt2, dt2],
"value": [10.5, -5.5, 20.5, 8.0, -3.0, 5.0],
})
df.sql(
"""
SELECT dt, key, SUM(value) AS total,
FROM self
GROUP BY ALL
ORDER BY dt, key
"""
)
```
* While implementing this I came across several errors with group-key aliasing/tracking, resolved them, and added test …
=> feat: Add SQL support for `GROUP BY ALL` syntax and fix several issues with aliased group keys

crates/polars-time/src/group_by/dynamic.rs, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/test_rolling.py
=> fix: Fix rolling empty group OOB

_typos.toml, py-polars/polars/series/utils.py, py-polars/polars/testing/parametric/strategies/core.py, py-polars/polars/testing/parametric/strategies/data.py, py-polars/polars/testing/parametric/strategies/dtype.py, py-polars/tests/unit/functions/range/test_date_range.py, py-polars/tests/unit/interchange/test_roundtrip.py, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py, py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py, py-polars/tests/unit/series/buffers/test_from_buffer.py, py-polars/tests/unit/testing/parametric/strategies/test_core.py
Null values are a frequent source of bugs, so we should really be testing for them.
* Enable `Null` data type by default. Dataframes/Series generated by our strategies may contain a `Null` column.
* Set `allow_null` to `True` by default. This may hit some users, but we should really make the change now while people are updating their parametric tests anyway.
* Setting `allow_null=False` will exlude the `Null` data type from the pool.
* Adjust tests to match.
This helped me find a bug, will investigate later:
https://github.com/pola-rs/polars/issues/16190
=> feat(python): Enable Null datatype and null values by default in parametric testing

crates/polars-plan/src/dsl/python_udf.rs, py-polars/Cargo.toml, py-polars/src/conversion/any_value.rs, py-polars/src/conversion/mod.rs, py-polars/src/datatypes.rs, py-polars/src/lazyframe/mod.rs, py-polars/src/map/dataframe.rs, py-polars/src/map/lazy.rs, py-polars/src/map/mod.rs, py-polars/src/on_startup.rs, py-polars/src/series/comparison.rs, py-polars/src/series/mod.rs, py-polars/src/series/numpy_ufunc.rs, py-polars/src/to_numpy.rs
Fixes #16142 
Note that I am not convinced we've caught _all_ usages of the old reference-style code (`&PyAny` and friends instead of `Bound<PyAny>`). Not everything is quite deprecated yet, is my impression. I have supplemented explicit warnings with some grepping, but still. But, presumably this will get caught as newer PyO3 releases come out.
=> chore(python): More PyO3 0.21 Bound<> APIs, and finally disable gil-refs backwards compat feature on pyo3 crate

crates/polars-io/src/ipc/ipc_file.rs, crates/polars-io/src/ipc/mmap.rs, crates/polars-io/src/mmap.rs, crates/polars-lazy/src/physical_plan/executors/scan/ipc.rs, crates/polars-utils/src/io.rs, crates/polars-utils/src/lib.rs, py-polars/src/dataframe/io.rs, py-polars/src/file.rs, py-polars/tests/unit/io/test_ipc.py
It isn't perfect, but this will at least catch the most common case in python where people read memory mapped and write to the same file.
fixes #16119
=> feat: Register memory mapped files and raise when written to

crates/polars-lazy/src/frame/mod.rs, crates/polars-plan/src/logical_plan/aexpr/mod.rs, crates/polars-plan/src/logical_plan/alp/format.rs, crates/polars-plan/src/logical_plan/alp/mod.rs, crates/polars-plan/src/logical_plan/expr_ir.rs, py-polars/tests/unit/operations/unique/test_unique.py, py-polars/tests/unit/test_predicates.py
This PR moves the `LazyFrame::describe_optimized_plan` to using the `IR` instead of `DslPlan`. Most code is based on the old formatting code and is located in the `polars-plan/src/logical-plan/alp/format.rs` file.
=> refactor: move describe to IR instead of DSL

crates/polars-plan/src/logical_plan/conversion/expr_to_ir.rs, py-polars/tests/unit/test_empty.py
=> fix: Fix empty drop nulls

crates/polars-lazy/src/physical_plan/executors/unique.rs, py-polars/tests/unit/test_empty.py
=> fix: Empty unique

crates/polars-lazy/src/physical_plan/executors/scan/csv.rs, crates/polars-lazy/src/physical_plan/planner/lp.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/tests/io.rs, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-pipe/src/pipeline/convert.rs, crates/polars-plan/src/logical_plan/builder_dsl.rs, crates/polars-plan/src/logical_plan/conversion/scans.rs, crates/polars-plan/src/logical_plan/optimizer/slice_pushdown_lp.rs, py-polars/tests/unit/io/test_lazy_csv.py
This replaces the existing codepath that dispatches multi-CSV file reads to the Union executor.
=> feat: Native CSV file list reading

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/dataframe/test_to_torch.py
* Setting "features" or "label" parameters when `return_type` is not "dataset" now raises an informative error (previously was a silent no-op).
* Added docstring note that selectors[^1] are supported for "label" and "features".
[^1]: Polars selectors: https://docs.pola.rs/py-polars/html/reference/selectors.html
=> feat(python): Clarify `to_torch` "features" and "label" parameter behaviour when return type is not "dataset"

py-polars/polars/testing/parametric/strategies/data.py, py-polars/polars/testing/parametric/strategies/dtype.py, py-polars/polars/testing/parametric/strategies/legacy.py, py-polars/tests/unit/testing/parametric/strategies/test_core.py
I ran into this issue, which we should really fix before enabling List types by default:
https://github.com/pola-rs/polars/issues/16209
=> fix(python): Fix some issues in parametric testing with nested dtypes

py-polars/polars/testing/_constants.py, py-polars/polars/testing/parametric/strategies/data.py, py-polars/tests/unit/conftest.py, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/streaming/test_streaming_group_by.py
I didn't account for the fact that Python floordiv rounds away from zero in negative numbers.
Also moving a constant that was only used in tests to a test fixture.
=> fix(python): Fix a rounding error in parametric test datetimes generation

crates/polars-lazy/src/dsl/eval.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/physical_plan/exotic.rs, crates/polars-lazy/src/physical_plan/planner/expr.rs, crates/polars-lazy/src/physical_plan/planner/lp.rs, crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs, py-polars/polars/config.py
=> feat: Show warning if expressions are very deep

py-polars/polars/io/database/functions.py, py-polars/tests/unit/io/database/test_read.py
This PR adds an overload when `iter_batches` is a `bool`, as opposed to `Literal[True]` or `Literal[False]`, most of the time in Polars, overloads like this aren't super helpful, as you're actually just passing in `True`/`False`.  However, with top-level functions like `read_database`, you might want to have a wrapper over it. This is basically the situation that I am in, where I have a custom version of `read_database`, with some additional functionality around retrieving the DB connection, and so want to have my own overloads on that function for `DataFrame`, and `Iterable[DataFrame]`, to make this possible there does need to be an overload for the non-literal case, at least with Pyright.
Here's basically an example of the issue I'm running into.
```python
def custom_read_db(
query: …
```
=> fix(python): Add missing `read_database` overload

crates/polars-pipe/src/executors/sources/csv.rs, py-polars/src/batched_csv.rs, py-polars/tests/unit/io/test_csv.py
Fixes https://github.com/pola-rs/polars/issues/16010
I've left the code in but removed calls to them for now, as I think I will be looking to do proper refactoring later.
=> fix: Reading CSV with low_memory gave no data

crates/polars-lazy/src/physical_plan/planner/expr.rs, crates/polars-plan/src/dsl/expr.rs, crates/polars-plan/src/dsl/functions/selectors.rs, crates/polars-plan/src/dsl/meta.rs, crates/polars-plan/src/logical_plan/aexpr/schema.rs, crates/polars-plan/src/logical_plan/conversion/dsl_to_ir.rs, crates/polars-plan/src/logical_plan/conversion/expr_to_ir.rs, crates/polars-plan/src/logical_plan/expr_expansion.rs, crates/polars-plan/src/logical_plan/format.rs, crates/polars-plan/src/logical_plan/iterator.rs, crates/polars-plan/src/logical_plan/visitor/expr.rs, crates/polars-plan/src/utils.rs, crates/polars-sql/tests/functions_string.rs, py-polars/polars/expr/expr.py, py-polars/polars/functions/col.py, py-polars/polars/functions/lazy.py, py-polars/polars/selectors.py, py-polars/src/functions/lazy.rs, py-polars/src/lib.rs, py-polars/tests/unit/operations/test_join.py, py-polars/tests/unit/test_selectors.py
Enables some interesting new column selection capabilities using indices (including negative indices) and `range` objects, as well as their union, intersection, etc (via selector combinatorics).
* Adds a new `by_index` selector that works with indices _and_ ranges.
* Allows `nth` to take _multiple_ indices.
```python
"key": ["abc"],
**{f"c{i:02}": [0.5 * i] for i in range(100)},
})
```
Select "key" col and the three first/last numeric columns:
_(can freely mix/match indexes and range objects)_
```python
df.select(pl.nth([0, 1, 2, 3, -3, -2, -1]))
df.select(cs.by_index(0, 1, 2, 3, -3, -2, -1))
df.select(cs.by_index(range(0,4), range(-3,0)))
```
Select every 10th column:
```python
df.select(cs.by_index(range(0,101,10))) …
```
=> feat: Adds new index/range based selector `cs.by_index`, allows multiple indices for `nth`

py-polars/polars/testing/parametric/strategies/core.py, py-polars/polars/testing/parametric/strategies/data.py, py-polars/src/conversion/mod.rs, py-polars/tests/unit/datatypes/test_object.py
Also added support for generating object data in parametric tests (but not enabled yet).
=> fix(python): Add missing support for parsing instantiated Object dtypes `Object()`

docs/src/python/user-guide/expressions/column-selections.py, py-polars/polars/selectors.py, py-polars/tests/unit/test_selectors.py
Closes #16242 (ref: https://github.com/pola-rs/polars/issues/16242#issuecomment-2112953328).
Fixes incomplete validation in `is_selector`, taking care of `expand_selector` in the process (it should have been raising a TypeError on non-selector input). Now that it's fixed, can use `is_selector` inside `_selector_proxy_` (in retrospect it was a bit of a red flag that we couldn't already do this ;p)
* Fixes invalid uses of `__sub__` and `__rsub__`.
* Adds an example to clarify `as_expr` usage.
* Adds missing entries to module `__all__`.
* Adds a few more user guide examples.
* Adds some missing test coverage.
* Removes a few lines of dead code.
=> fix(python): Address overly-permissive `expand_selectors` function, minor fixes

crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
=> fix: `rolling_*_by was throwing incorrect error when dataframe was sorted by contained multiple chunks

crates/polars-plan/src/dsl/function_expr/mod.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/src/lib.rs
Hello! First of all, thanks for polars!  
This PR follows up recent work to expose the logical plan to python by adding string expressions. This should allow a consumer of the plan on the python side to implement accelerated string computations. 
cc @wence-
=> feat(python): Expose string expression nodes to python

py-polars/polars/testing/parametric/strategies/core.py, py-polars/polars/testing/parametric/strategies/data.py, py-polars/polars/testing/parametric/strategies/dtype.py, py-polars/tests/unit/interchange/test_roundtrip.py, py-polars/tests/unit/series/buffers/test_from_buffer.py, py-polars/tests/unit/series/buffers/test_from_buffers.py, py-polars/tests/unit/testing/parametric/strategies/test_core.py
A few improvements:
* Rename `chunked` to `allow_chunks`. If allowed, hypothesis will decide whether to chunk or not.
* Improve performance when using `excluded_dtypes`
* Improve `structs` strategy to allow missing entries.
=> depr(python): Change parameter `chunked` to `allow_chunks` in parametric testing strategies

crates/polars-core/src/chunked_array/array/mod.rs, crates/polars-core/src/chunked_array/list/mod.rs, py-polars/polars/series/series.py, py-polars/src/series/export.rs, py-polars/src/to_numpy.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
Closes https://github.com/pola-rs/polars/issues/14268
* Move handling of Array types in `Series.to_numpy` to Rust
* Fix handling of null values (see linked issue)
* Fix handling of nested arrays
=> fix(python): Fix `Series.to_numpy` for Array types with nulls and nested Arrays

crates/polars-io/src/predicates.rs, crates/polars-plan/src/logical_plan/builder_dsl.rs, crates/polars-plan/src/logical_plan/conversion/scans.rs, crates/polars-plan/src/logical_plan/functions/count.rs
=> fix(rust): compilation error when both lazy and ipc features are enabled

crates/polars-plan/src/dsl/function_expr/boolean.rs, crates/polars-plan/src/logical_plan/conversion/expr_to_ir.rs
=> fix: Don't stackoverflow on all/any horizontal

crates/polars-core/src/chunked_array/ndarray.rs
=> perf: Don't rechunk when converting DataFrame to numpy/ndarray

crates/polars-plan/src/dsl/function_expr/schema.rs, py-polars/tests/unit/test_schema.py
=> fix: Fix list.sum dtype for boolean

py-polars/polars/expr/datetime.py
=> docs(python): document that month_start/month_end preserve the current time

py-polars/polars/dataframe/frame.py
Missing word in docstring for ```polars.DataFrame.join```, param: ```how:anti```. "Filter rows that not have a match in the right table." ->Filter rows that do not have a match in the right table."
=> docs(python): Add missing word in `join` docstring

py-polars/polars/datatypes/classes.py, py-polars/polars/series/series.py, py-polars/polars/testing/__init__.py
=> refactor(python): Use `cls` (not `self`) in classmethods

py-polars/tests/unit/test_polars_import.py
We should look into the reason behind the failures, e.g. some regression or something with the GitHub runners maybe. Until then I'm upping the threshold to avoid spurious failures.
=> test(python): Raise import timing test threshold

crates/polars-core/src/series/ops/to_list.rs, py-polars/tests/unit/series/test_series.py
This is a fix for https://github.com/pola-rs/polars/issues/15543
Improvements:
- `dimensions < -1` will raise an error instead of panicking
- dimensions will be inferred from placeholders `-1` whenever it is possible; `(-1, -1)` will be inferred to either `(0, 0)` for an empty series or to `(len(), 1)` for a non-empty series
- empty series can only be reshaped to `(0, 0)` or `(0, )` (after inferring)
- dimensions that do not fulfil `rows*cols == len()` after inferring placeholders will raise an error
=> fix(rust,python): Harden `Series.reshape` against invalid parameters 

crates/polars-core/src/datatypes/field.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/dsl/function_expr/struct_.rs, crates/polars-plan/src/dsl/struct_.rs, py-polars/docs/source/reference/expressions/struct.rst, py-polars/polars/expr/struct.py, py-polars/src/expr/struct.rs
Akin to `DataFrame.with_columns`.
Will follow up with a `select_fields` as well.
```python
>>> df = pl.DataFrame(
...     {
...         "coords": [{"x": 1, "y": 4}, {"x": 4, "y": 9}, {"x": 9, "y": 16}],
...         "multiply": [10, 2, 3],
...     }
... )
>>> df
shape: (3, 2)
┌───────────┬──────────┐
│ coords    ┆ multiply │
│ ---       ┆ ---      │
│ struct[2] ┆ i64      │
╞═══════════╪══════════╡
│ {1,4}     ┆ 10       │
│ {4,9}     ┆ 2        │
│ {9,16}    ┆ 3        │
└───────────┴──────────┘
>>> df = df.with_columns(
...     pl.col("coords").struct.with_fields(
...         pl.col("coords").struct.field("x").sqrt(),
...         y_mul=pl.col("coords").struct.field("y") * pl.col("multiply"),
...     ),
... )
>>> df
shape: (3, 2)
┌─────────────┬──────────┐
│ coords      ┆ multiply │
│ --- …
```
=> feat: Add `struct.with_fields`

py-polars/polars/_utils/udfs.py
Looking to get ahead of this one early. Slightly painful to analyse in depth at the moment as the debugger promptly crashes on attach to the 3.13 beta, but there's always the good old "print" statement, so...😎  
* Handle the new `bool(op)` wrapper.
* Handle the new `TO_BOOL` opcode 
(See: https://github.com/python/cpython/pull/106003).
Can't test with `numpy` translation yet, but these two small updates alone take the related tests from _"almost 100% of them fail"_ to _"only four fail"_, which is a good sign that the changes are going to be minor. 
As the betas are released I'll make incremental adjustments so we don't have to scramble come October. 
```python
from polars._utils.udfs import BytecodeParser
bp = BytecodeParser(
function = lambda x: not (x > 1) or x == 2,
map_target = …
```
=> feat(python): Start updating `BytecodeParser` for Python 3.13

py-polars/polars/_cpu_check.py
This fixes a regression in import times, as `ctypes.util` imports a lot of stuff we don't need.
=> perf: Avoid importing `ctypes.util` in CPU check script if possible

py-polars/polars/convert.py, py-polars/polars/dataframe/frame.py, py-polars/polars/io/spreadsheet/_utils.py, py-polars/polars/lazyframe/frame.py
Shaves another few `ms` off the initial `polars` import; definitely don't need Excel utility functions in the top-level DataFrame imports, and can avoid a premature `io` utils import too.
=> perf(python): Further optimise initial `polars` import

py-polars/polars/selectors.py, py-polars/tests/unit/test_selectors.py
Closes #15023.
Closes #16219.
Adds a new (opt-in) "match_any" param to the `by_name` selector.
Default behaviour remains unchanged.
_**Update:** have changed the parameter name from "any" (and then "match_any"), to "require_all" and adjusted the default value accordingly :sunglasses:_
Default behaviour; expect _all_ given columns to be present:
```python
"foo": ["x", "y"],
"bar": [123, 456],
"baz": [2.0, 5.5],
})
```
```python
df.select( cs.by_name("stroopwafel","baz","!!") )
```
Enable permissive matching on _any_ of the given columns:
```python
df.select( cs.by_name("stroopwafel","baz","!!", require_all=False) )
```
=> feat(python): Add `require_all` parameter to the `by_name` column selector

crates/polars-core/src/datatypes/dtype.rs, py-polars/src/series/export.rs, py-polars/src/to_numpy.rs, py-polars/tests/benchmark/interop/__init__.py, py-polars/tests/benchmark/interop/test_numpy.py, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
Ref #16267
Instead of iterating over the values, we rechunk and create a writable view.
This regressed in https://github.com/pola-rs/polars/pull/16178 - now we get the best of both worlds with a writable array _and_ only a single, fast copy.
Performance of converting a chunked Series of 50 million float32s:
* Before: ~60ms
* After: ~25ms
I added some benchmark tests so that we may catch regressions here in the future.
=> perf(python): Improve `Series.to_numpy` performance for chunked Series that would otherwise be zero-copy

.github/workflows/test-coverage.yml, Cargo.lock, crates/polars-parquet/Cargo.toml, crates/polars-parquet/src/lib.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/encode.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/mod.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/pack.rs
I replaced the Parquet bit-packing algorithm with a modified version of the scalar algorithm from https://github.com/quickwit-oss/bitpacking (unsure where/how to give credit). I ensured the new algorithm works by adding unit tests that encode/decode random data.
I added a microbenchmark in my first commit to help measure the performance gain.
|| Before  | After |
|-| ------------- | ------------- |
|Avg. (ns/iter)|93.75 | 4.25 |
|Std. (ns/iter)| 1.57 | 0.04 |
I removed the microbenchmark in a later commit because it requires nightly Rust and is probably not useful outside of this PR.
Other miscellaneous fixes:
- Packed array of 64 u64's should have a maximum length of 64 * 8 u8's (second commit)
- Input array length should be compared to expected unpacked length instead of expected packed …
=> perf: Faster bitpacking for Parquet writer

Cargo.lock, py-polars/Cargo.toml, py-polars/polars/meta/build.py, py-polars/src/lib.rs, py-polars/tests/unit/conftest.py, py-polars/tests/unit/meta/test_build.py
This crate only saved us ~50 LOC and included a hidden dependency on `email.utils` increasing our import times.
While in the process I also renamed the awkwardly named `pl.build_info()["build"]` to `pl.build_info()["compiler"]` and `pl.build_info()["info-time"]` is now a RFC2822 string `pl.build_info()["time"]`.
=> perf: do not use pyo3-built

py-polars/polars/selectors.py, py-polars/tests/unit/test_selectors.py
New selectors, making it even easier to classify column names by character type:
* `cs.alphanumeric()`: only names composed of letters and digits.
* `cs.alpha()`: only names composed of letters.
* `cs.digit()`: only names composed of digits.
One of the nice bonuses in having separate selectors for this is making sure that non-ASCII letters are handled automatically, eg: accented characters in words such as "tweeëntwintig", kanji such as "東京", hangul, etc. 
(I also suspect that, even amongst users familiar with regular expressions, a reasonable number wouldn't immediately know the equivalent `cs.matches` pattern `^[\p{Alphabetic}]+$`, which is also a little more cryptic in a codebase 🤔)
There is an optional flag `ascii_only` if you want to limit the definition of "alphabetic" to ASCII, but …
=> feat(python): Add new `alpha`, `alphanumeric` and `digit` selectors

py-polars/polars/expr/expr.py
Map elements accepts a callable `Callable[[Series], Series] | Callable[[Any], Any]`, this for all intensive purposes should just accept `Callable[[Any], Any]`. Previously, the former was fine in type-checkers such as Pyright, however as Eric Traut explains [here](https://github.com/microsoft/pyright/issues/7927#issuecomment-2113683345), there's not a great way for Pyright to deterministically determine which to use when evaluating lambdas, which can lead to Pyright errors when calling this function. Take this example, which will lead to an error in the latest version of Pyright, which I would imagine should be fully supported: 
```python
{
"a": [1, 2, None],
"b": [1.0, 2.0, 3.0],
"c": ["a", "b", "c"],
}
)
def transform_int(x: int) -> int:
return x + …
```
=> fix(python): Improve `map_elements` typing

crates/polars-lazy/src/tests/mod.rs, crates/polars-plan/src/logical_plan/expr_expansion.rs, py-polars/tests/unit/test_expansion.py
=> fix: Don't exclude explicitly named columns in group-by context' expr expansion

crates/polars-plan/src/dsl/function_expr/struct_.rs, crates/polars-plan/src/dsl/struct_.rs, crates/polars-plan/src/logical_plan/expr_expansion.rs, py-polars/polars/expr/struct.py, py-polars/src/expr/struct.rs, py-polars/tests/unit/test_expansion.py
```python
>>> df = pl.DataFrame(
...     {
...         "aaa": [1, 2],
...         "bbb": ["ab", "cd"],
...         "ccc": [True, None],
...         "ddd": [[1, 2], [3]],
...     }
... ).select(pl.struct(["aaa", "bbb", "ccc", "ddd"]).alias("struct_col"))
>>> df
shape: (2, 1)
┌──────────────────────┐
│ struct_col           │
│ ---                  │
│ struct[4]            │
╞══════════════════════╡
│ {1,"ab",true,[1, 2]} │
│ {2,"cd",null,[3]}    │
└──────────────────────┘
Use wildcard expansion:
>>> df.select(pl.col("struct_col").struct.field("*"))
shape: (2, 4)
┌─────┬─────┬──────┬───────────┐
│ aaa ┆ bbb ┆ ccc  ┆ ddd       │
│ --- ┆ --- ┆ ---  ┆ ---       │
│ i64 ┆ str ┆ bool ┆ list[i64] │
╞═════╪═════╪══════╪═══════════╡
│ 1   ┆ ab  ┆ true ┆ [1, 2]    │
│ 2   ┆ cd  ┆ null ┆ [3]       │ …
```
=> feat: Add struct.field expansion (regex, wildcard, columns)

crates/polars-core/src/series/mod.rs
Prevent `u64` overflow panic when combining AnyValue list-element hashes (in debug builds).
=> fix: Address overflow combining u64 hashes in Debug builds

Cargo.lock, crates/polars-time/Cargo.toml, crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs, crates/polars-time/src/chunkedarray/rolling_window/mod.rs, crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs, py-polars/polars/expr/expr.py, py-polars/src/expr/rolling.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
~~Needs rebasing onto https://github.com/pola-rs/polars/pull/16247~~
In summary this splits `rolling_apply_agg_window` into:
- `rolling_apply_agg_window_sorted` (no difference to the current `rolling_apply_agg_window`, this is the fastpath when data is already known to be sorted by `by`)
- `rolling_apply_agg_window`: doesn't require the data to be sorted by `by`, which is why it needs an extra argument (`sorting_indices`) which is used to place the results in the right place of the `out` `Vec`
- deprecated `warn_if_unsorted` on the Python side, removed it from the Rust side
**The gist of the change is `rolling_apply_agg_window` in crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs**
Perf impact:
- for data already known to be sorted: none
- for data not known …
=> feat: Don't require data to be sorted by `by` column in `rolling_*_by` operations

py-polars/src/to_numpy.rs
Going to take a look at the dataframe code next, starting out with some small refactors.
=> refactor(python): Very minor refactor of `DataFrame.to_numpy` code

crates/polars-ops/src/series/ops/various.rs, crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs, crates/polars-time/src/chunkedarray/rolling_window/mod.rs, py-polars/polars/series/series.py, py-polars/src/series/mod.rs, py-polars/tests/unit/operations/test_is_sorted.py
Should be much faster and failing fast in case of non-sorted data.
=> perf: Optimize `is_sorted` for numeric data

crates/polars-ops/src/chunked_array/interpolate.rs, py-polars/tests/unit/operations/rolling/test_rolling.py
applying some suggestions from https://github.com/pola-rs/polars/pull/16313 to some 'old' code
Removing so many levels of indentation was quite pleasing 😋
=> chore: simplify interpolate code, add test for rolling_*_by with nulls

crates/polars-ops/src/series/ops/ewm_by.rs, crates/polars-plan/src/dsl/function_expr/ewm_by.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/mod.rs, py-polars/polars/expr/expr.py, py-polars/src/expr/general.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/tests/unit/functions/test_ewm_by.py, py-polars/tests/unit/operations/test_ewm_by.py
If `is_sorted` has been improved, then I think it makes sense to just remove `check_sorted` - not sure users should be setting it really as it could lead to incorrect results if misused
=> perf: use is_sorted in ewm_mean_by, deprecate check_sorted

py-polars/polars/testing/parametric/strategies/core.py
See here for how this could go wrong:
https://github.com/pola-rs/polars/actions/runs/9151718672/job/25158171279?pr=16325
We have to explicitly copy mutable inputs to avoid this from happening.
_(I will address the actual reason the test failed separately)_
=> fix(python): Fix issue in parametric testing where `excluded_dtypes` list would grow indefinitely

py-polars/polars/io/spreadsheet/functions.py, py-polars/tests/unit/io/test_spreadsheet.py
Support more recent versions of `fastexcel` (>= 0.10) being able to read bytes data directly; relevant for `pl.read_excel` when the engine is "calamine".
=> feat(python): Allow `read_excel` to handle bytes/BytesIO directly when using the "calamine" (fastexcel) engine

py-polars/polars/dataframe/frame.py, py-polars/src/interop/numpy/to_numpy_df.rs, py-polars/src/interop/numpy/to_numpy_series.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
This is required to facilitate recursive handling of Structs.
=> refactor(python): Move `DataFrame.to_numpy` implementation to Rust side

py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/src/lazyframe/visitor/nodes.rs
Previously expr.sort() had a different order from expr.sortby(), which can only lead to confusion. Moreover, tighten up the types in to catch changes early.
=> fix(python): pick a consistent order for the sort options in PyIR

py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/src/lib.rs
Additionally, tidy up the StringFunction exposure and add hashing to the enum-like objects.
=> feat(python): expose BooleanFunction in expr IR

.github/workflows/release-python.yml, py-polars/Cargo.toml, py-polars/build.rs, py-polars/src/allocator.rs
@ritchie46 I expect this to resolve the issue, but I don't really have a good way of testing it except for trying the release again.
I also changed the build features from `use_mimalloc` and `default_allocator` to a feature with two possible values `allocator = "default"` or `allocator = "mimalloc"`. That is not required for the fix but should be a bit more sensible.
=> build(python): Fix allocator features

crates/polars-parquet/src/parquet/encoding/uleb128.rs
This fixes a clippy error for the `decode_uleb_bmi2` function.
=> fix(rust): cargo clippy for uleb128 safety comment

crates/polars-plan/src/logical_plan/aexpr/schema.rs, py-polars/tests/unit/test_schema.py
AExpr.to_field would incorrectly state that the bitwise and/or of integral columns was boolean, and conversely that the logical and/or was the common supertype. Fix this by matching on the correct operator names.
- Closes #16359
=> fix(rust): correct AExpr.to_field for bitwise and logical and/or

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py
Structs were just converted to an object type, but it makes much more sense for them to be nested structured arrays, which is supported by NumPy.
=> fix(python): Fix `DataFrame.to_numpy` for Struct columns when `structured=True`

py-polars/polars/_utils/construction/series.py, py-polars/tests/unit/constructors/test_series.py
There is currently no way to construct a Series with a nonexistent/ambiguous datetime value, as the Series constructor has no `ambigous/nonexistent` argument, and the default is to raise.
This PR sets those values to null if `strict=False` was passed to the constructor.
@MarcoGorelli would love to get your input on this fix.
=> fix(python): Handle ambiguous/nonexistent datetimes in Series construction

py-polars/src/interop/numpy/to_numpy_df.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py
The vstack operation would lead to errors / incorrect results because the numpy array representing these columns has more than 1 dimension. The arrays are now converted to 1D object arrays before stacking.
See https://github.com/pola-rs/polars/issues/14334#issuecomment-2070955932
=> fix(python): Fix `DataFrame.to_numpy` for Array/Struct types

py-polars/src/interop/numpy/to_numpy_df.rs, py-polars/src/interop/numpy/to_numpy_series.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
We choose to represent Structs as a 2D array. It's constructed by unnesting and calling `DataFrame.to_numpy`.
=> feat(python): Implement Struct support for `Series.to_numpy`

py-polars/polars/series/series.py, py-polars/src/series/numpy_ufunc.rs, py-polars/tests/unit/interop/numpy/test_ufunc_series.py
Fixes #16193
* If the output size is known, we can use an optimization where Polars allocates the memory using the size of the input as the presumed size of the output.
* Previously this was always done, and sometimes the Polars-allocated array was the wrong size, and then NumPy got annoyed and complained.
* In this PR, if we don't know the output size, we let the generalized ufunc allocate memory, and then copy the data out.
Future iterations could probably be smarter and use the optimized allocation scheme in more cases: often you can deduce output size by parsing the signature, e.g. `(n),(m)->(m)` means you use the length of the second input as the length of the output. But this at least _allows_ this sort of function, which wasn't possible before.
=> fix(python): Add support for generalized ufunc with different size input and output

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/tests/benchmark/interop/test_numpy.py, py-polars/tests/unit/interop/numpy/test_numpy.py, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
This is technically a breaking change, because our native engine behaves differently from PyArrow:
* Integer types with nulls become the smallest matching float (`float32` or `float64`) instead of always `float64`.
* Structs become a 2D array instead of a 1D object array of dicts.
Otherwise, behavior is identical.
I'll leave it up to @ritchie46 whether he wants to merge this or wait for a breaking release.
=> depr(python): Deprecate `use_pyarrow` parameter for `to_numpy` methods

crates/polars-core/src/chunked_array/ndarray.rs
This didn't cause an issue on the python side because there was an `if let Ok(..)` branch.
=> fix: Don't check nulls before conversion

crates/polars-core/src/frame/explode.rs, crates/polars-core/src/frame/group_by/mod.rs, crates/polars-core/src/frame/mod.rs, crates/polars-core/src/utils/flatten.rs, crates/polars-core/src/utils/mod.rs, crates/polars-expr/src/expressions/window.rs, crates/polars-io/src/csv/write/write_impl.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-io/src/predicates.rs, crates/polars-lazy/src/physical_plan/executors/projection.rs, crates/polars-lazy/src/physical_plan/executors/unique.rs, crates/polars-pipe/src/operators/chunks.rs, crates/polars/tests/it/lazy/predicate_queries.rs, py-polars/polars/dataframe/frame.py, py-polars/src/dataframe/general.rs, py-polars/src/interop/numpy/to_numpy_df.rs
This aligns the method with the Python side.
=> feat(rust!): Change `DataFrame.is_empty()` to check `height == 0` instead of `width == 0`

crates/polars-core/src/chunked_array/ndarray.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py
=> fix: Fix don't panic on chunked to_numpy conversion

crates/polars-arrow/src/bitmap/bitmap_ops.rs, crates/polars-arrow/src/bitmap/immutable.rs, crates/polars-arrow/src/bitmap/mutable.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/tests/optimization_checks.rs, crates/polars-plan/src/frame/opt_state.rs, crates/polars-plan/src/logical_plan/optimizer/cluster_with_columns.rs, crates/polars-plan/src/logical_plan/optimizer/mod.rs, crates/polars-plan/src/logical_plan/options.rs, crates/polars-plan/src/logical_plan/projection_expr.rs, crates/polars-plan/src/logical_plan/visitor/lp.rs, crates/polars-utils/src/arena.rs, py-polars/tests/unit/test_cwc.py
This adds a new optimization pass for the query engine that clusters several sequential `WITH COLUMNS` calls.
When the optimizer spots a chain of `WITH COLUMNS`, it tries to pull expressions as close to the source as possible. If all expressions can be pulled up closer to the source, the `WITH COLUMNS` node is removed entirely.
=> feat(rust): add cluster_with_columns plan optimization

py-polars/polars/dataframe/frame.py, py-polars/src/interop/numpy/to_numpy_df.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py
`vstack` followed by a transpose will result in an F-contiguous array. `column_stack` creates a C-contiguous array. So we can use one or the other depending on the order requested by the user.
Structured arrays are both C and F contiguous since they are 1-dimensional.
=> feat(python): Respect index order in `DataFrame.to_numpy` also for non-numeric frames

py-polars/polars/_utils/various.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/test_lazy.py
Fixes #16253
I tried to keep the logic as close to the original as possible. 
E.g, prioritising the fast paths. 
Was wondering if the `is_sequence` check that follows is the best option though.
Edit:
To elaborate on the `is_sequence` comment further.
Acceptable inputs at that stage are:
1. One or more `Expr`
2. An `str` representing a column name in `self.columns`
3. A `Sequence` that is not a `Series`
Where parsing `3` is defered to `parse_as_list_of_expressions`.
=> fix(python): Handle non-Sequence iterables in filter

crates/polars-plan/src/logical_plan/aexpr/schema.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix: Fix struct arithmetic schema

crates/polars-plan/src/logical_plan/conversion/expr_expansion.rs, py-polars/tests/unit/test_expansion.py
=> feat: Field expansion renaming

Cargo.lock, py-polars/Cargo.toml
0.20.27 will be yanked due to a bug in the `to_numpy` conversion.
=> release(python): Python Polars 0.20.28

py-polars/polars/exceptions.py
Sphinx is not happy with `Example` headers. I see warnings when compiling docs without cache.
=> docs(python): Fix sphinx headers: 'Example' → 'Examples'

py-polars/polars/_utils/various.py
Closes #16411
Just an old call to `apply` that was generating a warning.
Updated to use `map_elements` instead.
=> fix(python): Update `apply` call in `str_duration_` util.

py-polars/docs/source/reference/expressions/modify_select.rst, py-polars/docs/source/reference/series/modify_select.rst
Just noticed the new `interpolate_by` wasn't showing up in a docs search.
=> docs(python): Add `interpolate_by` entry to rst files.

py-polars/polars/io/parquet/functions.py, py-polars/src/dataframe/general.rs, py-polars/tests/unit/io/test_parquet.py
Fixes #16416 
While playing around with measuring memory I also discovered rechunk() doesn't release the GIL, so I fixed that too while I was at it.
=> fix(python): make read_parquet() respect rechunk flag when using pyarrow

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/tests/unit/interop/numpy/test_array_method.py, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py
Updating for NumPy 2.0.0. See:
https://numpy.org/devdocs/user/basics.interoperability.html#the-array-method
=> feat(python): Update `__array__` method for Series and DataFrame to support `copy` parameter

py-polars/polars/selectors.py, py-polars/tests/unit/test_selectors.py
Builds on https://github.com/pola-rs/polars/pull/16310.
* Allows alpha/alphanumeric matches to be determined independent of the presence of spaces (eg: _"This Is A Column"_ can optionally still be considered alphanumeric).
* Can distinguish between unicode digits (matched by default) and ascii-only digits.
* Improved selector typing (able to remove some `type: ignore` directives).
```python
"FirstCol": [100, 200, 300],
"2ndCol": [400, 500, 600],
"Last Col": [700, 800, 900],
})
```
Alpha/alphanumeric matches with/without spaces:
```python
df.select(cs.alpha())
df.select(cs.alpha(ignore_spaces=True))
df.select(cs.alphanumeric())
df.select(cs.alphanumeric(ignore_spaces=True))
```
Digit matches, unicode/ascii-only: …
=> feat(python): Add "ignore_spaces" to `alpha` and `alphanumeric` selectors, add "ascii_only" to `digit`

crates/polars-io/src/csv/read/read_impl.rs, crates/polars-io/src/csv/read/reader.rs, crates/polars-io/src/csv/read/schema_inference.rs, crates/polars-lazy/src/scan/csv.rs, py-polars/tests/unit/io/test_lazy_csv.py
Fixes https://github.com/pola-rs/polars/issues/16327
Turns out I just had to remove the skip_rows overwrite to make it correct because this exists:
https://github.com/pola-rs/polars/blob/ceb895e0ab0d6ab3eb2e8eb1fccacb8d3fe14524/crates/polars-io/src/csv/read/read_impl.rs#L291-L294
was this your plan all along Ritchie 😂
=> fix: Fix error reading lists of CSV files that contain comments

crates/polars-ops/src/series/ops/various.rs, crates/polars-plan/src/dsl/function_expr/dispatch.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/dsl/mod.rs, docs/src/rust/user-guide/expressions/structs.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/src/expr/general.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/src/series/mod.rs, py-polars/tests/unit/io/test_spreadsheet.py, py-polars/tests/unit/operations/test_value_counts.py
Closes #16425.
While we don't usually (but do sometimes https://github.com/pola-rs/polars/issues/15222), I think we should allow a "name" parameter here, because otherwise we are making the caller change _their_ column names (in the case of a clash) to account for _us_ forcing one called "count" onto them.
It is more user-friendly to allow our "count" column to be renamed, as there is no way for the caller to do so, and working around it with pre/post aliasing to maintain their original column name is pretty ugly (and verges on painful in the DataFrame case) 🤔
```python
s = pl.Series("count", [20, 20, 60, 50, 50, 50])
```
**_With_** a "name" parameter we have a clean call:
```python
s.value_counts(sort=True, name="n")
```
**_Without_** a "name" parameter achieving the same output is... …
=> feat: Allow designation of a custom name for the `value_counts` "count" column

crates/polars-plan/src/logical_plan/optimizer/cluster_with_columns.rs, py-polars/tests/unit/test_cwc.py
This fixes #16436, #16437. It fixes a panic in the optimizer pass of `cluster_with_columns`.
=> fix(rust): keep track of removed indices in CWC

py-polars/polars/expr/expr.py
The example for `cum_max` uses an ascending sequence. So `cum_max` doesn't do anything in that case. In reverse mode it does the same as the non-cumulative sum. This change makes the example data go up and down, so the behaviour of the function is clearer.
(I wasn't able to build polars, even off the main branch. But this change is so trivial, I'm hoping it's fine anyway.)
=> docs(python): Change ordering of values in example for `cum_max`

py-polars/polars/expr/struct.py
Just updating the doc examples to use the new `pl.field` syntax.
=> docs(python): Use `pl.field` inside `with_fields` examples.

crates/polars-core/src/series/implementations/duration.rs, py-polars/tests/unit/dataframe/test_describe.py
The implementation of min_reduce accidentally called `.as_duration()` twice. The second one panicked because the `AnyType` was no longer `Int64`.
Fixes #16382
=> fix(rust): Fix panic when computing min() of Duration series.

py-polars/polars/_utils/construction/dataframe.py, py-polars/tests/unit/interop/test_interop.py
Sorry I don't have the time to write a test case at the moment.
Closes #16453
=> fix(python): respect `nan_to_null` when using multi-thread in `pl.from_pandas`

crates/polars-core/src/schema.rs, crates/polars-plan/src/logical_plan/optimizer/cluster_with_columns.rs, py-polars/tests/unit/test_cwc.py
Fixes #16435.
This PR focuses on cluster_with_columns (CWC) and resolves the issue where a schema was improperly handled when a simple projection needed to be inserted. This PR also removes several of the clones and allocations that came before with CWC.
=> fix(rust): properly set schemas in cluster_with_columns when reassigning to columns

crates/polars-sql/src/context.rs, crates/polars-sql/src/functions.rs, crates/polars-sql/tests/simple_exprs.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/selectors.py, py-polars/tests/unit/sql/test_group_by.py
The difference between `len`/`count` caused the aggregate expression check in "GROUP BY" to miss `len` (it's not an AggExpr), as used by "COUNT(*)" in the SQL interface. Fixed, and added the missing coverage.
(Also includes two minor unrelated docstring updates).
```python
"a": ["xx", "yy", "xx", "yy", "xx", "zz"],
"b": [1, None, 3, 4, None, 6],
"c": [99, 99, 66, 66, 66, 66],
})
df.sql("""
SELECT
a,
COUNT(b) AS count_b,
COUNT(*) AS count_star
FROM self
GROUP BY a
ORDER BY a
""")
```
=> fix: Fix use of `COUNT(*)` in SQL `GROUP BY` operations

crates/polars-core/src/chunked_array/ops/float_sorted_arg_max.rs, crates/polars-core/src/chunked_array/ops/search_sorted.rs, crates/polars-ops/src/series/ops/search_sorted.rs, py-polars/polars/series/series.py, py-polars/tests/unit/expr/test_exprs.py
Closes https://github.com/pola-rs/polars/issues/16420.
=> fix: allow search_sorted directly on multiple chunks, and fix behavior around nulls

crates/polars-core/src/frame/group_by/aggregations/dispatch.rs
Fixes https://github.com/pola-rs/polars/issues/16457.
=> perf: only rechunk once per aggregate

crates/polars-arrow/src/legacy/utils.rs, crates/polars-arrow/src/trusted_len.rs, crates/polars-core/src/chunked_array/ops/fill_null.rs, py-polars/tests/unit/dataframe/test_df.py
Closes https://github.com/pola-rs/polars/issues/15480.
=> perf: improved numeric fill_(forward/backward)

crates/polars-plan/src/logical_plan/alp/format.rs, py-polars/tests/unit/test_format.py
This resolves an issue where the explain format of simple projection would show the wrong number under the "... n other columns"
=> fix(rust): properly display other length in simple project and display more columns up to a maximum length

crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/logical_plan/alp/format.rs, py-polars/tests/unit/test_schema.py
=> fix: Correct schema for list.sum

crates/polars-parquet/src/arrow/read/statistics/binary.rs, crates/polars-parquet/src/arrow/read/statistics/binview.rs, crates/polars-parquet/src/arrow/read/statistics/boolean.rs, crates/polars-parquet/src/arrow/read/statistics/fixlen.rs, crates/polars-parquet/src/arrow/read/statistics/mod.rs, crates/polars-parquet/src/arrow/read/statistics/primitive.rs, crates/polars-parquet/src/arrow/read/statistics/utf8.rs, crates/polars-parquet/src/arrow/write/binary/basic.rs, crates/polars-parquet/src/arrow/write/binview/basic.rs, crates/polars-parquet/src/arrow/write/boolean/basic.rs, crates/polars-parquet/src/arrow/write/dictionary.rs, crates/polars-parquet/src/arrow/write/fixed_len_bytes.rs, crates/polars-parquet/src/arrow/write/primitive/basic.rs, crates/polars-parquet/src/arrow/write/primitive/nested.rs, crates/polars-parquet/src/parquet/metadata/column_chunk_metadata.rs, crates/polars-parquet/src/parquet/page/mod.rs, crates/polars-parquet/src/parquet/statistics/binary.rs, crates/polars-parquet/src/parquet/statistics/boolean.rs, crates/polars-parquet/src/parquet/statistics/fixed_len_binary.rs, crates/polars-parquet/src/parquet/statistics/mod.rs, crates/polars-parquet/src/parquet/statistics/primitive.rs, crates/polars-parquet/src/parquet/write/column_chunk.rs, crates/polars-parquet/src/parquet/write/indexes/serialize.rs, crates/polars-parquet/src/parquet/write/page.rs, crates/polars-parquet/src/parquet/write/statistics.rs, crates/polars/tests/it/io/parquet/mod.rs, crates/polars/tests/it/io/parquet/read/mod.rs, crates/polars/tests/it/io/parquet/write/binary.rs, crates/polars/tests/it/io/parquet/write/mod.rs, crates/polars/tests/it/io/parquet/write/primitive.rs
This refactors the `polars-parquet` to provide an `enum` interface instead of a `trait` for `Statistics`. This makes the code a lot more debuggable and reduces the amount of `Arc` allocations needed. This does not really increase memory consumption as there are no long lived `Statistics` fields on `struct`s.
This should also:
- Reduce code-size and binary-size
- Allow for more inlining
- Improve error messages
- Improve the analysis by the rust compiler
=> refactor(rust): make Parquet `Statistics` into `enum` instead of `trait`

py-polars/polars/lazyframe/frame.py, py-polars/polars/type_aliases.py, py-polars/tests/unit/lazyframe/test_explain.py
A `format` parameter is more appropriate here, to facilitate potential other formats like proposed here:
https://github.com/pola-rs/polars/issues/12075
Also added some tests because there were 0 tests for the tree format parameter.
=> depr(python): Deprecate `tree_format` parameter for `LazyFrame.explain` in favor of `format`

py-polars/polars/expr/expr.py, py-polars/src/expr/general.rs
Ref https://github.com/pola-rs/polars/issues/15238#issuecomment-2127119299
The `multithreaded` parameter was passed to `maintain_order`.
We should use keyword arguments to deal with booleans - also when passing it to the PyO3 bindings.
=> fix(python): Fix boolean trap issue in `top_k`/`bottom_k`

py-polars/polars/series/series.py, py-polars/tests/unit/constructors/test_series.py
Closes #15518
Not too happy with this fix, but this code needs to be revised anyway. It does the trick for now!
=> fix(python): Fix handling NaT values when creating Series from NumPy ndarray

py-polars/docs/source/reference/expressions/boolean.rst, py-polars/docs/source/reference/series/descriptive.rst, py-polars/polars/dataframe/frame.py, py-polars/polars/datatypes/classes.py, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py, py-polars/tests/unit/interop/numpy/test_to_numpy_series.py, py-polars/tests/unit/operations/map/test_map_elements.py, py-polars/tests/unit/operations/test_has_nulls.py, py-polars/tests/unit/operations/test_shift.py, py-polars/tests/unit/testing/parametric/strategies/test_core.py
The presence of a validity buffer is internals information that should not be part of the public API.
This PR adds a `has_nulls` method that can be used to check for null values. For now it's only available on the Python side, and the implementation is naive. We can optimize this later.
The `has_nulls` method should be added to the Rust side as well.
@orlp FYI - I'll leave the Rust side to you :)
=> feat(python): Add `Series/Expr.has_nulls` and deprecate `Series.has_validity`

crates/polars-plan/src/dsl/meta.rs, crates/polars-plan/src/logical_plan/format.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/meta.py, py-polars/polars/io/spreadsheet/functions.py, py-polars/polars/selectors.py, py-polars/src/expr/meta.rs, py-polars/tests/unit/operations/namespaces/test_meta.py, py-polars/tests/unit/test_selectors.py
Closes #16448.
Extends the existing expression meta/introspection methods with a new one that determines if a given expression _exclusively_ selects columns. This includes selectors, bare/multi `col`, regex `col`, dtype `col`, use of `exclude`, and the positional top-level functions (first/last/nth). Aliased column selections are _optionally_ allowed, but not by default.
This allows `expand_selector` to offer a new "strict=False" option such that it can additionally expand expressions like `cs.starts_with("x").exclude("x!!")`, which would previously raise an error. 
Should cover the [Great Tables](https://posit-dev.github.io/great-tables/) use-case in the linked issue (@machow).
(**Also**: fixed some versionadded/changed tags as a trivial drive-by).
New `meta` method accurately identifies …
=> feat: Add `is_column_selection()` to expression meta, enhance `expand_selector`

crates/polars-arrow/src/record_batch.rs, crates/polars-core/src/frame/chunks.rs, crates/polars-core/src/series/mod.rs
=> fix: Fix `split_chunks` for nested dtypes

docs/development/contributing/index.md
I extended the "Contributing to the codebase" section under "Development" to make it easier for people to contribute to the code base. Many career changers in IT belong to an underrepresented group in tech and therefore having a more detailed documentation on how to contribute has the potential to increase the diversity of contributors to Polars. The changes will also make it easier for you to run "Contributing to Polars" community sprints (e.g. at conferences) if you're interested in running these.
In my opinion it would also be helpful to have a section about "Updating the development environment". I wasn't entirely sure how to do it but it seems like people need to run 
```
git checkout main
git fetch upstream
git merge upstream/main
make test
```
(Please correct me if I'm wrong.)
I …
=> docs: Update the Overview section of the contributing guide

crates/polars-core/src/frame/chunks.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix: Fix df.chunked for struct

py-polars/docs/source/conf.py, py-polars/tests/unit/interop/numpy/test_ufunc_expr.py, py-polars/tests/unit/interop/numpy/test_ufunc_series.py, py-polars/tests/unit/lazyframe/cuda/test_node_visitor.py, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py, py-polars/tests/unit/operations/test_join.py, py-polars/tests/unit/test_cse.py
Some of the code uses `-> None` for `__init__`: I put the change to require `None` in a separate commit to make it easy to revert if needed.
=> refactor(python): Fewer `typing.no_type_check`

py-polars/polars/_utils/getitem.py, py-polars/tests/unit/dataframe/test_getitem.py
Now that we have decided not to go ahead with https://github.com/pola-rs/polars/issues/4924 - we can definitively say that this is a bug: the first positional parameter indicates the rows to select. Selecting no rows should give zero rows but include all columns.
=> fix(python): Fix `DataFrame.__getitem__` for empty list input - `df[[]]`

crates/polars-core/src/chunked_array/ops/aggregate/mod.rs, crates/polars-core/src/series/implementations/list.rs, crates/polars-core/src/series/implementations/string.rs, crates/polars-error/src/lib.rs, docs/src/python/user-guide/concepts/expressions.py, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/functions/test_functions.py
=> fix(rust,python): throw an invalid operation exception on performing a `sum` over a `list` of `str`s

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/pyproject.toml, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/operations/test_join.py
Ref https://github.com/pola-rs/polars/issues/13441
* The default coalescing behavior of left join will change in the next breaking release. See the example below to compare the two behaviors. Set `coalesce=True` to keep the existing behavior and silence the deprecation warning.
**`coalesce=True` (current default)**
```pycon
>>> df1 = pl.DataFrame({"a": [1, 2, 3], "b": [9, 9, 9]})
>>> df2 = pl.DataFrame({"a": [2, 3, 4], "c": [0, 0, 0]})
>>> df1.join(df2, on="a", how="left", coalesce=True)
shape: (3, 3)
┌─────┬─────┬──────┐
│ a   ┆ b   ┆ c    │
│ --- ┆ --- ┆ ---  │
│ i64 ┆ i64 ┆ i64  │
╞═════╪═════╪══════╡
│ 1   ┆ 9   ┆ null │
│ 2   ┆ 9   ┆ 0    │
│ 3   ┆ 9   ┆ 0    │
└─────┴─────┴──────┘
```
**`coalesce=False` (future default)**
```pycon
>>> df1.join(df2, on="a", how="left", …
```
=> depr(python): Deprecate default coalesce behavior of left join

crates/polars-core/src/utils/series.rs, crates/polars-ops/src/frame/join/asof/mod.rs, crates/polars-ops/src/series/ops/various.rs, crates/polars-time/src/group_by/dynamic.rs, crates/polars-time/src/upsample.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/group_by.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/src/expr/general.rs, py-polars/src/lazyframe/mod.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/tests/unit/operations/test_group_by_dynamic.py, py-polars/tests/unit/operations/test_rolling.py
#16333 Introduced using `Series.is_sorted` instead of just checking `Series.is_sorted_flag`
I'd like to suggest doing the same for `group_by_dynamic`, `rolling` and `upsample`. I think this'll make a noticeable ergonomic difference to users
What's missing is, in the case when it's not sorted, to sort on behalf of the user. That's a bit harder to address, but I think already using `Series.is_sorted` instead of only checking the sorted flag would already be a positive change for users
---
Also, I think the current check isn't even correct, as it only checks if the sorted flag doesn't match `IsNot`, as opposed to checking that it matches `Ascending`
=> feat: check if by column is sorted, rather than just checking sorted flag, in `group_by_dynamic`, `upsample`, and `rolling`

docs/user-guide/expressions/window.md
The existing documentation for window functions in the user guide page included `implode` in the list of API, but there was no actual usage or example provided for `implode`. This led to potential confusion for users following the documentation.
=> docs(python): Remove erroneous `implode` reference from the user guide section on window functions

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, py-polars/tests/unit/test_projections.py
Fixes https://github.com/pola-rs/polars/issues/16515
=> fix: Crash selecting columns after non-coalesced join

py-polars/docs/source/reference/dataframe/miscellaneous.rst, py-polars/docs/source/reference/lazyframe/miscellaneous.rst, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/expr/meta.py, py-polars/polars/lazyframe/frame.py, py-polars/pyproject.toml, py-polars/src/dataframe/io.rs, py-polars/tests/unit/dataframe/test_serde.py, py-polars/tests/unit/io/test_json.py
Ref https://github.com/pola-rs/polars/issues/14526
This introduces `DataFrame.serialize/deserialize`. This functionality already existed as part of `pl.read_json/DataFrame.write_json`, but is now split off for clarity.
This will be followed up with a breaking change to `pl.read_json/DataFrame.write_json` that removes the serde functionality from those functions.
=> feat(python): Add `DataFrame.serialize/deserialize`

crates/polars-lazy/src/dsl/functions.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/tests/optimization_checks.rs, crates/polars-plan/src/logical_plan/conversion/dsl_to_ir.rs, crates/polars-plan/src/logical_plan/mod.rs, crates/polars-plan/src/logical_plan/schema.rs, crates/polars-sql/src/context.rs, crates/polars-sql/src/sql_expr.rs, crates/polars-utils/src/arena.rs, py-polars/src/lazyframe/mod.rs
Isn't perfect and we shouldn't count on it, but hopefully it helps the pathological cases we might create in the SQL side, because currently we require schema info there.
The long run improvement would be using the `IR::builder` there.
=> perf: Partial schema cache. 

crates/polars-plan/src/logical_plan/conversion/dsl_to_ir.rs, py-polars/tests/unit/operations/test_join.py
The fix for #16289 checked for expression identity when validating the join keys, but if multiple expressions are not identical, they may still produce matching output key names. Since this is ambiguous, catch this more general case and raise.
- Fixes #16547
=> fix(rust): Ensure deduced join key names are unique

crates/polars-core/src/series/mod.rs, crates/polars-plan/src/logical_plan/lit.rs, py-polars/tests/unit/test_cse.py
=> fix: Don't panic on hashing nested list types

py-polars/src/lazyframe/visit.rs
Since the CSE expressions don't appear in the schema that IR::Select publically advertises, deducing the dtype of expressions that depend upon them fails. To handle this, augmented the public schema with the dtypes of the CSE terms before asking for the dtype of the remaining expressions.
=> feat(rust): handle CSE dtypes in NodeTraverser.get_dtype

crates/polars-plan/src/logical_plan/optimizer/cluster_with_columns.rs, crates/polars/tests/it/lazy/cwc.rs, crates/polars/tests/it/lazy/mod.rs
This adds a small fuzzer that runs arbitrary sequences of `WITH_COLUMNS` and sees whether the optimized and unoptimized versions produce the same results. With that, I found another panic in the CWC implementation.
=> fix(rust): solve panic in `cluster_with_columns`, found with small fuzzer

Cargo.lock, crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/tests/cse.rs, crates/polars-lazy/src/tests/projection_queries.rs, crates/polars-lazy/src/tests/queries.rs, crates/polars-lazy/src/tests/streaming.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-plan/src/dsl/expr.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, crates/polars-sql/Cargo.toml, crates/polars-sql/src/context.rs, crates/polars-sql/src/sql_expr.rs, crates/polars-sql/tests/statements.rs, docs/src/rust/user-guide/transformations/joins.rs, py-polars/tests/unit/sql/test_joins.py, py-polars/tests/unit/sql/test_miscellaneous.py, py-polars/tests/unit/sql/test_subqueries.py, py-polars/tests/unit/test_queries.py
Both coalesce-related blockers issue (#16515 and #16554) now resolved ✌️ 
(Thanks @nameexhaustion!)
---
Closes #11927.
Closes #13618.
Closes #14217.
Closes #15663.
Closes #15929.
(Confirmed it also fixes #16255).
* Introduces a more robust method of tracking aliased columns through joins so that we can correctly resolve them on any follow-up projection/constraint ops. 
* Adds lots of extra test coverage for SQL joins, representing all of the closed issues.
=> fix: Resolve multiple SQL `JOIN` issues

docs/src/python/user-guide/expressions/window.py, py-polars/docs/source/reference/series/computation.rst, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
once again, fixing up docstring bullet points which don't render properly 😄 check the "coalesce" arg description in https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.join.html
bonus drive-bys:
- some ergonomic syntax
- Series.cum_count was left out of the docs
=> docs(python): Fix bullet points not rendering correctly in `DataFrame.join` docstring

crates/polars/tests/it/lazy/exprs.rs, crates/polars/tests/it/lazy/mod.rs
This adds a very basic fuzzer for expressions. Currently, if you run this, it will just panic in a few seconds because invalid ops commonly panic. Hopefully, this kind of starts the work of slowly phasing out those panics.
=> feat(rust): add fuzzer for expressions

crates/polars-ops/src/series/ops/floor_divide.rs, py-polars/tests/unit/operations/arithmetic/test_arithmetic.py
This adds an error message for a `floordiv` on a `bool`.
=> fix(rust): bail on bool `floordiv`

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_cast.py
Added SQL support for the `TRY_CAST` function (as implemented by various[^1] databases).
```python
df = pl.DataFrame({"n": [-10, 0, 10, 20]})
```
Strict (default) `CAST` fails on invalid values ...
```python
df.sql("SELECT CAST(n AS uint1) FROM df")
```
... whereas `TRY_CAST` replace invalid values with `null`:
```python
df.sql("SELECT TRY_CAST(n AS uint1) FROM df")
```
[^1]: TRY_CAST: [SQL Server](https://learn.microsoft.com/en-us/sql/t-sql/functions/try-cast-transact-sql?view=sql-server-ver16), [DuckDB](https://duckdb.org/docs/sql/expressions/cast#try_cast)
=> feat: Add SQL support for `TRY_CAST` function

py-polars/docs/source/reference/expressions/modify_select.rst, py-polars/docs/source/reference/series/computation.rst, py-polars/polars/_utils/various.py, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_replace.py, py-polars/tests/unit/operations/test_replace_all.py
Ref https://github.com/pola-rs/polars/issues/14302
* Add `replace_all`, which is exactly the same as `replace` was, with the exception that defaults to filling unmatched values with null.
* Deprecate the `default` and `return_dtype` parameters for `replace`.
This should be followed up with a breaking change that makes sure `replace` always keeps the original data type, instead of casting to the supertype of the original and the new values.
=> feat(python): Add `replace_all` expression to complement `replace`

crates/polars-plan/src/logical_plan/lit.rs, py-polars/tests/unit/test_cse.py
Fixes https://github.com/pola-rs/polars/issues/16577
=> fix: Crash using empty `Series` in `LazyFrame.select()`

py-polars/polars/datatypes/classes.py, py-polars/tests/unit/constructors/test_constructors.py, py-polars/tests/unit/dataframe/test_serde.py, py-polars/tests/unit/datatypes/test_array.py, py-polars/tests/unit/functions/test_repeat.py, py-polars/tests/unit/io/test_parquet.py, py-polars/tests/unit/operations/namespaces/array/test_to_list.py, py-polars/tests/unit/operations/namespaces/list/test_list.py, py-polars/tests/unit/series/test_equals.py, py-polars/tests/unit/test_serde.py, py-polars/tests/unit/testing/parametric/strategies/test_core.py
* Fixed a recursion issue where the shape of the Array type was constructed backwards, e.g. input `(1,2,3,4)` would result in an actual shape `(1,4,3,2)`.
* Deprecated the `width` input and the `width` attribute.
* Update the `repr` to always show a `shape`, instead of showing `size=...` on one-dimensional Arrays.
=> fix(python): Fix parsing of `shape` in `Array` constructor and deprecate `width` parameter

crates/polars-core/src/testing.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py, py-polars/polars/testing/asserts/frame.py, py-polars/polars/testing/asserts/series.py, py-polars/src/series/mod.rs, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/io/test_delta.py, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py, py-polars/tests/unit/series/test_equals.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/sql/test_group_by.py, py-polars/tests/unit/streaming/test_streaming_join.py, py-polars/tests/unit/test_lazy.py, py-polars/tests/unit/testing/test_assert_frame_equal.py, py-polars/tests/unit/testing/test_assert_series_equal.py
Related to [#13231](https://github.com/pola-rs/polars/issues/13231)
* In the assertion utils, rename parameter `check_dtype` to `check_dtypes`. This better matches the other parameter `check_names` (plural). I considered changing `check_names` to `check_name` instead, but plural makes more sense here.
* In `Series.equals`, rename `strict` parameter to `check_dtypes`. This aligns with `assert_series_equal` and is much clearer.
=> depr(python): Rename `Series.equals` parameter `strict` to `check_dtypes`  and rename assertion utils parameter `check_dtype` to `check_dtypes`

docs/src/python/user-guide/sql/create.py, docs/src/python/user-guide/sql/intro.py, docs/src/python/user-guide/sql/select.py, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/sql/context.py, py-polars/polars/sql/functions.py, py-polars/tests/unit/sql/test_cast.py, py-polars/tests/unit/sql/test_conditional.py, py-polars/tests/unit/sql/test_group_by.py, py-polars/tests/unit/sql/test_joins.py, py-polars/tests/unit/sql/test_literals.py, py-polars/tests/unit/sql/test_miscellaneous.py, py-polars/tests/unit/sql/test_numeric.py, py-polars/tests/unit/sql/test_operators.py, py-polars/tests/unit/sql/test_regex.py, py-polars/tests/unit/sql/test_strings.py, py-polars/tests/unit/sql/test_table_operations.py, py-polars/tests/unit/sql/test_temporal.py, py-polars/tests/unit/sql/test_union.py
Ref: #16594.
Split out the deprecation from the functional change; deprecates use of "eager_execution" in `SQLContext` in favour of the more standard/idiomatic "eager".
No functional changes, though I did remove the docstring examples that show multi-frame usage of `df.sql` and `lf.sql`, as that is going away in favour of `pl.sql`.
=> depr(python): Rename `SQLContext` "eager_execution" param to "eager"

crates/polars-core/src/chunked_array/cast.rs, crates/polars-core/src/chunked_array/from.rs, crates/polars-core/src/chunked_array/metadata.rs, crates/polars-core/src/chunked_array/mod.rs, crates/polars-core/src/chunked_array/ops/arity.rs, crates/polars-core/src/chunked_array/ops/chunkops.rs, crates/polars-core/src/chunked_array/ops/explode.rs, crates/polars-core/src/chunked_array/ops/nulls.rs, crates/polars-core/src/datatypes/mod.rs, crates/polars-io/src/parquet/read/to_metadata.rs
With this PR, I change the way we clone `ChunkedArray`s. Now, we have to explicitly state after the clone that it is okay to copy over some metadata properties. This clears the way to properly handle other kinds metadata and I implemented such handling for `slice` and `rechunk`.
=> refactor(rust): defensively invalidate metadata and start on copying of `min_value`, `max_value` and `distinct_count`

py-polars/src/lazyframe/visit.rs, py-polars/src/lazyframe/visitor/nodes.rs, py-polars/src/lib.rs
Both Select and HStack need to augment the schema for get_dtype with the dtypes of the CSE expressions, and everyone should look at their input to determine the schema in which the expressions are evaluated.
Also plumb through Reduce to provide that information to the outside world.
=> fix(rust): get_dtype handles input node schema and CSE

Cargo.toml, docs/development/contributing/ide.md, docs/mlc-config.json, dprint.json, py-polars/docs/source/_static/version_switcher.json
Apparently the new TOML formatter does some sorting within Cargo.toml files, which is nice.
I enabled JSON formatting - we don't have a lot of JSON files but it can't hurt.
=> chore: Update dprint hook versions and enable JSON linting

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
Ref #16328
Until we update the API, we can at least include a warning in the docs for our users.
=> docs(python): Include warning in docstrings that accessing `LazyFrame` properties may be expensive

crates/polars-sql/src/context.rs, py-polars/tests/unit/sql/test_joins.py, py-polars/tests/unit/sql/test_miscellaneous.py
It was possible for use of an `ORDER BY` clause to indirectly cause reordering of `SELECT` cols when using the SQL interface. Fixed, and added some test coverage.
=> fix: Use of SQL `ORDER BY` should not cause reordering of `SELECT` cols

.github/CODEOWNERS
Fixes a duplicate tag in the CODEOWNERS.
=> chore: Remove duplicate tag in CODEOWNERS

docs/src/python/user-guide/expressions/aggregation.py, py-polars/polars/_utils/deprecation.py, py-polars/polars/io/csv/batched_reader.py, py-polars/polars/io/csv/functions.py, py-polars/polars/io/spreadsheet/functions.py, py-polars/tests/unit/datatypes/test_categorical.py, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/io/test_lazy_csv.py, py-polars/tests/unit/io/test_spreadsheet.py, py-polars/tests/unit/streaming/test_streaming_io.py
Ref https://github.com/pola-rs/polars/issues/15431
This functionality is called `schema_overrides` everywhere except in the CSV reading functions. This improves the consistency.
The parameter for `csv` is slightly since it accepts a _list_ of data types, but I think that still qualifies as a schema override.
=> depr(python): Rename `dtypes` parameter to `schema_overrides` for `read_csv`/`scan_csv`/`read_csv_batched`

py-polars/tests/unit/operations/aggregation/test_aggregations.py
=> test: Add test for 16642

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py
=> docs(python): Update filter description to clarify that null evaluations are removed

crates/polars-pipe/src/executors/sinks/joins/cross.rs
Since I cannot reproduce, I am not sure. But this might be a fix for #16491.
Debugged via backtrace. I expect you get an empty df there. @cmdlineluser could you verify?
=> fix: Potentially deal with empty range

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py
Mention:
`col("col_name").struct.field("field_name").native_method()`.
(Follow-up on #15887).
=> docs(python): improve docstring of `(Expr|Series).map_elements`

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/semi_anti_join.rs, py-polars/tests/unit/test_projections.py
If there were no projected columns, the rhs of the `semi`/`anti` join was fully loaded.
=> perf: Always prune unused columns in semi/anti join

crates/polars-plan/src/logical_plan/conversion/expr_expansion.rs, py-polars/tests/unit/test_expansion.py
Wildcard and excludes are expanded first before we expand the struct's fields.
closes #16661
=> feat: Allow wildcard and exclude before struct expansions

crates/polars-lazy/src/physical_plan/streaming/checks.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-pipe/src/executors/sinks/joins/generic_build.rs, crates/polars-pipe/src/executors/sinks/joins/generic_probe_inner_left.rs, py-polars/tests/unit/streaming/test_streaming_join.py
=> feat: Support non-coalescing streaming left join

crates/polars-time/src/truncate.rs, py-polars/tests/unit/operations/namespaces/temporal/test_truncate.py
`broadcast_try_binary_elementwise` simplifies things here, but does seem to introduce a perf hit for the base case (when `every` isn't an expression): https://github.com/pola-rs/polars/pull/15768#issuecomment-2143946326
this makes a noticeable difference for the single-`every` case https://www.kaggle.com/code/marcogorelli/polars-timing?scriptVersionId=181122731:
- here: 0.05906398600003134
- main: 0.09365042766664071
=> perf: make `truncate` 1.5x faster when `every` is just a single duration (and not an expression)

crates/polars-core/src/chunked_array/logical/struct_/mod.rs, crates/polars-core/src/series/arithmetic/borrowed.rs, crates/polars-expr/src/expressions/binary.rs, crates/polars-ops/src/series/ops/floor_divide.rs
This PR removes many of the panics that happen when performing binary operations with invalid types. This is achieved by dividing the operation functions into a `try_{add, mul, ...}` and an `{add, mul, ...}` as was already done from some operations. We can then call these functions from the dispatcher.
=> refactor(rust): use binary `try_{add, mul, ...}` ops in borrowed dispatch

crates/polars-lazy/src/tests/projection_queries.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs
For 1.0 we will set `non-coalescing` joins as default for left joins. If the rhs key columns isn't selected afterwards, the materialization was for nothing, so we toggle the join to a `coalesce`ing one, if we detect that.
=> perf: Toggle coalesce if non-coalesced key isn't projected

Cargo.lock, docs/src/rust/Cargo.toml
This is a workaround for https://github.com/smithy-lang/smithy-rs/issues/3672.
=> fix: avoid AWS pinning to outdated crc32c version

py-polars/polars/_utils/construction/dataframe.py
Only when we cannot move zero-copy. We catch the FileNotFound error and recurse without multithreading if failed.
fixes #16675
=> fix(python): Reduce scope of multi-threaded numpy conversion

py-polars/polars/io/database/_executor.py, py-polars/tests/unit/io/database/test_async.py
=> fix: Improve `read_database` check for SQLAlchemy async Session objects

py-polars/polars/testing/asserts/series.py, py-polars/tests/unit/testing/test_assert_series_equal.py
Closes https://github.com/pola-rs/polars/issues/16196
=> fix(python): Handle nested categoricals in `assert_series_equal` when `categorical_as_str=True`

py-polars/polars/dataframe/frame.py
towards #14781 
I added an example for using the index count in `DataFrame.rolling` as there has been unclarity about how exactly it works.
=> docs(python): Add example for index count in `DataFrame.rolling`

crates/polars-core/src/testing.rs, py-polars/polars/series/series.py, py-polars/src/series/mod.rs, py-polars/tests/unit/series/test_equals.py
Closes [#13231](https://github.com/pola-rs/polars/issues/13231)
* Add a `check_names` parameter to `Series.equals` on the Python side. This parameter defaults to `False` - which is a breaking change for Python users.
* On the Rust side, `Series.equals` no longer checks the data types by default
* On the Rust side, `Series.equals_missing` and `equals` no longer check names by default.
**Before**
```pycon
>>> s1 = pl.Series("foo", [1, 2, 3])
>>> s2 = pl.Series("bar", [1, 2, 3])
>>> s1.equals(s2)
False
```
**After**
```pycon
>>> s1.equals(s2)
True
>>> s1.equals(s2, check_names=True)
False
```
=> feat!: Add `check_names` parameter to `Series.equals` and default to `False`

py-polars/polars/datatypes/classes.py, py-polars/polars/interchange/utils.py, py-polars/tests/unit/datatypes/test_temporal.py
* Remove the default `None` value from some `DataType` attributes. These should be instance variables, not class variables.
**Before**
```pycon
>>> dtype = pl.Datetime
>>> dtype.time_unit is None
True
```
**After**
```pycon
>>> dtype.time_unit is None
...
AttributeError: type object 'Datetime' has no attribute 'time_unit'
```
Use instead:
```pycon
>>> getattr(dtype, "time_unit", None) is None
True
```
=> feat(python)!: Remove default class variable values on DataTypes

crates/polars-ops/src/series/ops/rle.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_rle.py
Closes #15230
* The struct fields of the `rle` method have been renamed from `lengths/values` to `len/value`.
* The data type of the `len` field has been updated to match the index type (was previously `Int32`, now `UInt32`).
**Before**
```pycon
>>> s = pl.Series(["a", "a", "b", "c", "c", "c"])
>>> s.rle().struct.unnest()
shape: (3, 2)
┌─────────┬────────┐
│ lengths ┆ values │
│ ---     ┆ ---    │
│ i32     ┆ str    │
╞═════════╪════════╡
│ 2       ┆ a      │
│ 1       ┆ b      │
│ 3       ┆ c      │
└─────────┴────────┘
```
**After**
```pycon
>>> s.rle().struct.unnest()
shape: (3, 2)
┌─────┬───────┐
│ len ┆ value │
│ --- ┆ ---   │
│ u32 ┆ str   │
╞═════╪═══════╡
│ 2   ┆ a     │
│ 1   ┆ b     │
│ 3   ┆ c     │
└─────┴───────┘
```
=> feat!: Rename struct fields of `rle` output to `len`/`value` and update data type of `len` field

.github/release-drafter-python.yml
From now on, breaking changes will increment the major version:
- `1.0.0`
- `2.0.0`
- ...
Releases that _only_ include bug fixes will be patch releases:
- `1.0.1`
- `1.0.2`
- ...
Other releases will increase the minor version:
- `1.1.0`
- `1.2.0`
- ...
This adheres to [SemVer spec](https://semver.org/#summary):
> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backward compatible manner
> PATCH version when you make backward compatible bug fixes
=> chore: Update version resolver for `1.0.0` release

py-polars/polars/expr/expr.py, py-polars/polars/functions/lazy.py, py-polars/polars/selectors.py, py-polars/tests/unit/functions/test_functions.py, py-polars/tests/unit/functions/test_nth.py, py-polars/tests/unit/test_selectors.py
Closes #16511
* Update `nth` to remove the overloaded capability to select `values` from given columns at the specified indices.
* Now positional parameters are parsed as additional column indices to select.
**Before**
```pycon
>>> df = pl.DataFrame({"a": [1, 2], "b": [3, 4], "c": [5, 6]})
>>> df.select(pl.nth(1, "a"))
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 2   │
└─────┘
```
**After**
```pycon
>>> df.select(pl.nth(1, "a"))
...
TypeError: argument 'indices': 'str' object cannot be interpreted as an integer
```
Use instead:
```pycon
>>> df.select(pl.col("a").get(1))
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 2   │
└─────┘
```
=> feat(python)!: Update function signature of `nth` to allow positional input of indices, remove `columns` parameter

docs/src/python/user-guide/io/json.py, py-polars/polars/dataframe/frame.py, py-polars/pyproject.toml, py-polars/src/dataframe/io.rs, py-polars/tests/unit/dataframe/test_serde.py, py-polars/tests/unit/io/test_json.py, py-polars/tests/unit/test_errors.py
Closes https://github.com/pola-rs/polars/issues/14526
* `pl.read_json` no longer supports reading JSON files produced by `DataFrame.serialize`. Users should use `pl.DataFrame.deserialize` instead.
* `DataFrame.write_json` now only writes row-oriented JSON. The parameters `row_oriented` and `pretty` have been removed. Users should use `DataFrame.serialize` to serialize a DataFrame.
**Before - `write_json`**
```pycon
>>> df = pl.DataFrame({"a": [1, 2], "b": [3.0, 4.0]})
>>> df.write_json()
'{"columns":[{"name":"a","datatype":"Int64","bit_settings":"","values":[1,2]},{"name":"b","datatype":"Float64","bit_settings":"","values":[3.0,4.0]}]}'
```
**After - `write_json`**
```pycon
>>> df.write_json()  # Same behavior as previously `df.write_json(row_oriented=True)` …
```
=> feat(python)!: Remove serde functionality from `pl.read_json` and `DataFrame.write_json`

crates/polars-core/src/config.rs, crates/polars-core/src/series/from.rs, crates/polars-core/src/series/mod.rs, py-polars/polars/config.py, py-polars/tests/unit/constructors/test_constructors.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/io/test_parquet.py, py-polars/tests/unit/sql/test_numeric.py, py-polars/tests/unit/test_config.py
Closes #15152
* Update conversion from Arrow to always convert Decimals into Polars Decimals, rather than cast to Float64.
* Deprecate `Config.activate_decimals`
**Before**
```pycon
>>> from decimal import Decimal as D
>>> import pyarrow as pa
>>> arr = pa.array([D("1.01"), D("2.25")])
>>> pl.from_arrow(arr)
shape: (2,)
Series: '' [f64]
[
1.01
2.25
]
```
**After**
```pycon
>>> pl.from_arrow(arr)
shape: (2,)
Series: '' [decimal[3,2]]
[
1.01
2.25
]
```
=> feat(python)!: Support decimals by default when converting from Arrow

docs/development/versioning.md
The pre-1.0.0 example is no longer relevant.
Also adds a clause that states that deprecations introduced with a breaking release will be enforced on the next breaking release. This keeps the promise of "upgrade to the next major version without problems if you fixed all your deprecation warnings", but gives us a bit more flexibility.
=> docs(python): Update deprecation period example

py-polars/polars/testing/asserts/series.py, py-polars/tests/unit/testing/test_assert_series_equal.py
Minor issue with https://github.com/pola-rs/polars/pull/16700 which I didn't cover in unit tests (sorry). Testing it uncovered another bug, so it's still not covered, but at least it should be fixed.
=> fix(python): Fix deprecated call to Array.width in assertion util

crates/polars-expr/src/expressions/aggregation.rs, crates/polars-expr/src/planner.rs
This PR separates the evaluation of the `AggregationExpr` `PhysicalExpr` to its own method. In the way, I removed several no-longer-used fields and parameters.
=> refactor(rust): separate `Aggregation` evaluation PhysicalExpr from conversion

crates/polars-core/src/chunked_array/logical/date.rs, crates/polars-core/src/chunked_array/logical/datetime.rs, crates/polars-core/src/chunked_array/logical/duration.rs, crates/polars-core/src/chunked_array/logical/time.rs, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/test_cast.py, py-polars/tests/unit/test_errors.py
Ref #14124, #16440
Following up on https://github.com/pola-rs/polars/pull/14127
* Casting logical types Date, Time, Datetime, and Duration no longer falls back to casting the physical type. This means certain casts are disabled, such as `Duration -> Time` or `Datetime -> Boolean`, that could result in nonsense.
* Update unsupported cast failures from `ComputeError` to `InvalidOperationError`. This should be considered a breaking change.
**Before**
```pycon
>>> from datetime import timedelta
>>> s = pl.Series([timedelta(days=1)])
>>> s.cast(pl.Time)
shape: (1,)
Series: '' [time]
[
00:01:26.400
]
```
**After**
```pycon
>>> s.cast(pl.Time)
...
polars.exceptions.InvalidOperationError: casting from Duration(Microseconds) to Time not supported
```
=> feat!: Restrict casting for temporal data types

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
Change from `False` to `True` in 
> Use `include_nulls=True` to overwrite values in this frame with null values in the other frame.
Fixes #16379. Documentation is at https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.update.html#polars.DataFrame.update.
=> docs(python): Fix stated value of include_nulls in DataFrame.update

crates/polars-ops/src/series/ops/clip.rs, py-polars/tests/unit/operations/test_clip.py
Closes #13714
* Null values in the bounds no longer set the value to null - instead, the original value is retained.
**Before**
```pycon
>>> df = pl.DataFrame({"a": [0, 1, 2], "min": [1, None, 1]})
>>> df.select(pl.col("a").clip("min"))
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ i64  │
╞══════╡
│ 1    │
│ null │
│ 2    │
└──────┘
```
**After**
```pycon
>>> df.select(pl.col("a").clip("min"))
shape: (3, 1)
┌──────┐
│ a    │
│ ---  │
│ i64  │
╞══════╡
│ 1    │
│ 1    │
│ 2    │
└──────┘
```
=> feat!: Do not propagate nulls in `clip` bounds

py-polars/polars/_utils/construction/series.py, py-polars/tests/unit/constructors/test_constructors.py, py-polars/tests/unit/operations/namespaces/list/test_list.py, py-polars/tests/unit/series/test_series.py
=> feat(python)!: Read 2D numpy arrays as Array[dt, shape] instead of Listst[dt]

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/sql/test_miscellaneous.py
As discussed; updates `df.sql(query)` such that it can _only_ access "self", deferring to `pl.sql(query)` when access to frames in the current stack is required. 
This better-distinguishes the purpose of each function and allows for frame-level `df.sql` to be marginally optimised (as there is no longer any need to introspect globals).
```python
import python
df1 = pl.DataFrame({"id1": [1, 2]})
df2 = pl.DataFrame({"id2": [3, 4]})
```
Frame-level `df.sql` (has access to "self", but not globals):
```python
df1.sql("SELECT * FROM self WHERE id1 > 1")
```
Top-level `pl.sql` (has access to globals):
```python
pl.sql("SELECT * FROM df1 CROSS JOIN df2", eager=True)
```
=> feat(python)!: Constrain access to globals from `df.sql` in favour of top-level `pl.sql`

crates/polars-core/src/chunked_array/from.rs, py-polars/tests/unit/series/test_to_list.py
Converting an empty Array-of-Dates type resulted in a panic due to a debug assert:
```python
pl.Series(dtype=pl.Array(pl.Date, 1)).to_list()
```
```
pyo3_runtime.PanicException: assertion `left == right` failed
left: Date32
right: Int32
```
Looks like empty arrays end up with the wrong data type here. I followed the trace but couldn't work out exactly why that happens. I did find this TODO comment which seems related:
https://github.com/pola-rs/polars/blob/9ea3bb6ed0cbebf49bdb908d444ee9e39626d1aa/crates/polars-core/src/chunked_array/array/iterator.rs#L41-L43
For now I have disabled the debug assertion for empty arrays. It resolves this issue.
=> chore: Fix incorrect debug assertion in `ChunkedArray::from_chunks_and_dtype`

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/operations/test_group_by_dynamic.py
This may be a 2.0 or 3.0 change, just wanted to get something started anyway and see the impact
Currently, the start of the first window in `group_by_dynamic` is determined as follows:
1) take the earliest datapoint
2) truncate it by `every`
3) apply `offset`
4) shift the window backwards by `offset` until the earliest datapoint is in or in front of it
5) empty windows are skipped
The for typical case (where `every == period`), steps 5 and 3 cancel each other out, and the "offset defaults to negative every" just makes the logic harder to teach and understand. I think that the "negative every" default was originally introduced because at first there was no step 4). Now that step 4) exists, then defaulting to `-every` is no longer necessary to ensure that the earliest datapoint is included …
=> feat!: change default of `offset` in group_by_dynamic from "negative `every`" to "zero"

py-polars/src/lazyframe/visit.rs
Now that we don't have to handle CSE specially, we can always ask the current root node for its schema, and it is on the caller to arrange that the correct root is active for determining the dtype of an expression.
=> chore(rust): Simplify NodeTraverser.get_dtype

crates/polars-core/src/chunked_array/array/iterator.rs, crates/polars-core/src/chunked_array/array/mod.rs, crates/polars-core/src/chunked_array/cast.rs, crates/polars-core/src/chunked_array/iterator/mod.rs, crates/polars-core/src/chunked_array/ops/explode.rs, crates/polars-core/src/chunked_array/ops/explode_and_offsets.rs, crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-core/src/chunked_array/ops/reverse.rs, crates/polars-core/src/chunked_array/ops/shift.rs, crates/polars-ops/src/chunked_array/array/dispersion.rs, crates/polars-ops/src/chunked_array/array/get.rs, crates/polars-ops/src/chunked_array/array/namespace.rs, py-polars/tests/unit/test_errors.py, py-polars/tests/unit/testing/test_assert_series_equal.py
Properly raise for now instead of panic.
closes #16706
=> fix: Raise unsupported cat array

crates/polars-pipe/src/executors/sinks/joins/generic_probe_outer.rs, py-polars/tests/unit/streaming/test_streaming_join.py
=> fix: Only flush if operator can flush in streaming outer join

crates/polars-arrow/src/compute/cast/mod.rs, py-polars/tests/unit/operations/namespaces/list/test_list.py
=> fixes `.list.to_array()` with sliced df

Cargo.lock, crates/polars-plan/src/logical_plan/lit.rs, crates/polars-sql/Cargo.toml, crates/polars-sql/src/sql_expr.rs, crates/polars-sql/tests/simple_exprs.rs, crates/polars-time/src/windows/duration.rs, py-polars/tests/unit/sql/test_literals.py, py-polars/tests/unit/sql/test_numeric.py
Closes #16702.
Adds initial `INTERVAL '...'` support to the SQL interface, covering typical uses (follow-ups listed below).
Handles all the typical units in verbose and abbreviated form, is case-insensitive and whitespace tolerant, and also ignores commas (all of which are valid for PostgreSQL interval literals).
* Extends our existing `Duration` object with a new `parse_interval` option.
* Also adds "Literal" and "Neg" trait implementations to `Duration`.
```python
with pl.SQLContext(df=None, eager=True) as ctx:
df = ctx.execute(
"""
SELECT
INTERVAL '1w2h3m4s' AS i1,
INTERVAL '100ms, 100us' AS i2,
INTERVAL '1 quarter 2 months 987 microseconds' AS i3,
FROM df
"""
)
```
* Parsing support for negative interval components, eg: `'7 days -1 hour 30 minutes -10 seconds'`.
* …
=> feat: Initial SQL support for `INTERVAL` strings

crates/polars-core/src/series/from.rs, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/test_empty.py
=> fix(python): Panic on empty df / null List(Categorical)

crates/polars-core/src/series/any_value.rs, crates/polars-core/src/utils/supertype.rs, py-polars/tests/unit/functions/range/test_datetime_range.py, py-polars/tests/unit/operations/test_transpose.py, py-polars/tests/unit/test_errors.py
Closes #16440
Data type-related failures should raise a `SchemaError`. We often use a ComputeError instead, which is not as informative.
**Before**
```pycon
>>> from datetime import datetime, time
>>> s1 = pl.Series([datetime(1970, 1, 1, 0, 0, 1)])
>>> s2 = pl.Series([time(0, 0, 2)])
>>> s1 + s2
...
polars.exceptions.ComputeError: failed to determine supertype of datetime[μs] and time
```
**After**
```pycon
>>> s1 + s2
...
polars.exceptions.SchemaError: failed to determine supertype of datetime[μs] and time
```
=> feat!: Update some error types to more appropriate variants

crates/polars-io/src/csv/read/read_impl.rs, py-polars/tests/unit/io/test_csv.py
Fixes https://github.com/pola-rs/polars/issues/16606
=> fix: Column selection wasn't applied when reading CSV with no rows

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py
Closes https://github.com/pola-rs/polars/issues/16684
This aligns the `rolling_*` and `rolling_*_by` methods. This is not breaking as the methods are marked as unstable.
=> feat(python): Mark `min_periods` as keyword-only for `rolling` methods

crates/polars-plan/src/dsl/function_expr/range/date_range.rs, crates/polars-plan/src/dsl/function_expr/range/mod.rs, crates/polars-plan/src/dsl/functions/range.rs, py-polars/polars/functions/range/date_range.py, py-polars/polars/functions/range/datetime_range.py, py-polars/src/functions/range.rs, py-polars/tests/unit/functions/range/test_date_range.py
Ref https://github.com/pola-rs/polars/issues/13525
=> feat!: Update `date_range` to no longer produce datetime ranges

py-polars/polars/_utils/various.py, py-polars/polars/config.py, py-polars/polars/sql/context.py, py-polars/polars/sql/functions.py, py-polars/tests/unit/sql/test_literals.py, py-polars/tests/unit/sql/test_miscellaneous.py
@ritchie46 - as suggested 😉
Notably expands the scope of the Polars SQL interface .
* The `pl.sql` function can now transparently identify and register additional frame/object types when referenced from a Polars SQL query.
* `SQLContext` can also now operate on these additional types.
Compatible objects include:
* Polars `DataFrame`, `LazyFrame`, and (new) `Series`.
* Pandas `DataFrame` and `Series`.
* PyArrow `Table` and `RecordBatch`.
(💡If you have more types that you think would be a good fit for this, let me know).
Objects of these types are transparently converted/registered as LazyFrame _iff_ their variable name appears in the SQL query (this prevents unnecessary conversions of compatible objects that aren't actually referenced).
```python
import pandas as pd
import pyarrow as pa …
```
=> feat: Support executing polars SQL against `pandas` and `pyarrow` objects

crates/polars-sql/src/context.rs, py-polars/tests/unit/sql/test_group_by.py, py-polars/tests/unit/sql/test_order_by.py
Closes #15793.
Factored out the common code we're using to handle `GROUP BY`[^1] ordinals and used it to integrate support for the same capability in `ORDER BY`[^2] clauses.
```python
"a": ["xx", "xx", "yy", "yy"],
"b": [4000, 3000, 2000, 1000],
})
```
```python
df.sql("""
SELECT * 
FROM self 
ORDER BY 1 DESC, 2 ASC
""")
```
```python
df.sql("""
SELECT a, SUM(b) AS sum_b 
FROM self 
GROUP BY 1 
ORDER BY 2 DESC
""")
```
[^1]: https://github.com/pola-rs/polars/pull/15584
[^2]: _"A sort_expression can also be the column label **or number** of an output column"_ https://www.postgresql.org/docs/current/queries-order.html#QUERIES-ORDER
=> feat: Support use of ordinal values in SQL `ORDER BY` clause

Cargo.lock, Cargo.toml, crates/polars-sql/src/context.rs, crates/polars-sql/src/keywords.rs, crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_literals.py
Double-checking against a PostgreSQL instance confirmed that unary ops are invalid when applied to interval strings (eg: `INTERVAL -'7d'` instead of `INTERVAL '-7d'`), so can simplify the parsing and raise a clear error here instead.
Also upgraded `sqlparser-rs` from 0.39 to 0.45; the very latest release (0.47) will require a bit more work to upgrade to so I'll tackle that later. Still pick up a few good additions/fixes with this jump.
=> feat: Streamline SQL `INTERVAL` handling and improve related error messages, update `sqlparser-rs` lib

crates/polars-plan/src/dsl/function_expr/temporal.rs, py-polars/tests/unit/operations/namespaces/temporal/test_offset_by.py
closes #16722  (timing becomes in line with the alternative method presented - I couldn't reproduce the 10x difference reported)
timing results available here https://www.kaggle.com/code/marcogorelli/polars-timing?scriptVersionId=181508652
---
~~I think this is fine but I didn't sleep too well so I'll check over it again tomorrow before marking as 'ready for review'~~
---
The gist of the change is: in the simple case, keep things simple and use `apply_values`
=> perf: speed up offset_by 2x for constant durations

Cargo.lock, crates/polars-io/Cargo.toml, crates/polars-io/src/cloud/polars_object_store.rs, crates/polars-io/src/csv/read/parser.rs, crates/polars-io/src/file_cache/cache.rs, crates/polars-io/src/file_cache/cache_lock.rs, crates/polars-io/src/file_cache/entry.rs, crates/polars-io/src/file_cache/eviction.rs, crates/polars-io/src/file_cache/file_fetcher.rs, crates/polars-io/src/file_cache/file_lock.rs, crates/polars-io/src/file_cache/metadata.rs, crates/polars-io/src/file_cache/mod.rs, crates/polars-io/src/file_cache/utils.rs, crates/polars-io/src/lib.rs, crates/polars-io/src/pl_async.rs, crates/polars-io/src/utils.rs, crates/polars-lazy/src/physical_plan/executors/scan/csv.rs, crates/polars-lazy/src/physical_plan/planner/lp.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-parquet/Cargo.toml, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-pipe/src/pipeline/convert.rs, crates/polars-plan/src/logical_plan/builder_dsl.rs, crates/polars-plan/src/logical_plan/conversion/dsl_to_ir.rs, crates/polars-plan/src/logical_plan/conversion/scans.rs, crates/polars-plan/src/logical_plan/file_scan.rs, crates/polars-plan/src/logical_plan/functions/count.rs, crates/polars-plan/src/logical_plan/optimizer/slice_pushdown_lp.rs, py-polars/polars/io/csv/functions.py, py-polars/src/lazyframe/mod.rs
This adds support for cloud storage in `scan_csv`, using a local cache to avoid duplicates downloads. Cached files are removed if they are not accessed within an hour (configurable with `POLARS_FILE_CACHE_TTL`).
=> feat: Support cloud storage in `scan_csv`

py-polars/polars/dataframe/frame.py
Related to: Add missing docstring examples #13161
Add example for:
https://docs.pola.rs/py-polars/html/reference/dataframe/api/polars.DataFrame.limit.html
=> docs(python): Add docstring example for DataFrame.limit()

crates/polars-sql/src/functions.rs, crates/polars-sql/src/sql_expr.rs, py-polars/docs/source/reference/sql/functions/temporal.rst, py-polars/tests/unit/sql/test_numeric.py, py-polars/tests/unit/sql/test_temporal.py
Improves some error messages, raises on invalid use of "WEEK(weekday)" inside `EXTRACT` (which is BigQuery-specific and invalid elsewhere), and fixes `DATE_PART` parameter order (ouch).
=> fix: `DATE_PART` SQL syntax/parsing, improve some error messages

.github/release-drafter-python.yml, docs/development/versioning.md
Also added additional information about the release frequency.
=> docs(python): Update versioning docs for 1.0.0

crates/polars-parquet/src/arrow/write/primitive/basic.rs, py-polars/tests/unit/io/test_parquet.py
Fixes https://github.com/pola-rs/polars/issues/16683, https://github.com/pola-rs/polars/issues/15323
=> fix: Incorrect parquet statistics written for UInt64 values > Int64::MAX

py-polars/polars/_utils/deprecation.py, py-polars/polars/dataframe/frame.py, py-polars/polars/functions/lazy.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/test_drop.py, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/utils/test_deprecation.py
Ref https://github.com/pola-rs/polars/issues/13525
These were deprecated in early 0.20, but I want to expedite the deprecation because:
* In the case of `group_by`, it blocks the semantics of using `by` as a column name in `**named_by`.
* In other cases, the deprecation was unlikely to impact many people so we might as well clean up the decorators now.
I kept the decorator implementation and added some tests, as I feel it may come in handy in the future.
=> feat(python)!: Enforce deprecation of keyword arguments as positional

py-polars/polars/testing/asserts/frame.py, py-polars/polars/testing/asserts/series.py, py-polars/tests/unit/testing/test_assert_series_equal.py
Similar to `assert_frame_equal`, this allows you to ignore the order in which elements appear.
=> feat(python): Add `check_order` parameter to `assert_series_equal`

docs/user-guide/io/excel.md, py-polars/polars/io/spreadsheet/functions.py, py-polars/polars/meta/versions.py, py-polars/polars/type_aliases.py, py-polars/pyproject.toml, py-polars/requirements-dev.txt, py-polars/tests/unit/io/test_spreadsheet.py
This engine has been superseded by `calamine`. I'd gather get rid of the optional dependency now.
@alexander-beedie Any objections?
=> feat(python)!: Remove `pyxlsb` engine from `read_database`

py-polars/polars/functions/lazy.py, py-polars/src/functions/lazy.rs, py-polars/src/lib.rs
The user should call ` arctan2(x, y).degrees()` instead.
=> depr(python): Deprecate `arctan2d`

py-polars/polars/io/database/functions.py, py-polars/tests/unit/io/database/test_read.py
@stinodego ✌️
Drops the long-deprecated passthrough from `read_database` to `read_database_uri`, when given a URI string (instead of an actual connection object).
=> feat(python)!: Removal of `read_database_uri` passthrough from `read_database`

crates/polars-arrow/src/bitmap/bitmap_ops.rs, crates/polars-arrow/src/bitmap/immutable.rs, crates/polars-compute/src/distinct_count.rs
=> fix(rust): properly set boolean distinct count

py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/group_by.py, py-polars/polars/expr/datetime.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/datetime.py, py-polars/polars/series/series.py, py-polars/polars/series/string.py, py-polars/tests/unit/operations/test_ewm_by.py, py-polars/tests/unit/operations/test_group_by_dynamic.py, py-polars/tests/unit/operations/test_rolling.py
Ref #13525
* Remove deprecated `check_sorted` parameter from `ewm_by` and `rolling`. This was only deprecated recently, but I'd rather not leave this useless parameter laying around. We made the same update for the other rolling functions.
* Remove deprecated `utc` parameter from `str.to_datetime`.
* Remove deprecated `ambiguous` parameter in `dt.round`.
=> feat(python)!: More removal of deprecated functionality

crates/polars-lazy/src/tests/cse.rs, crates/polars-lazy/src/tests/optimization_checks.rs, crates/polars-lazy/src/tests/predicate_queries.rs, crates/polars-lazy/src/tests/streaming.rs, crates/polars-ops/src/frame/join/args.rs, crates/polars-ops/src/series/ops/replace.rs, crates/polars-time/src/upsample.rs, crates/polars/tests/it/chunks/parquet.rs, crates/polars/tests/it/core/joins.rs, crates/polars/tests/it/lazy/predicate_queries.rs, py-polars/polars/lazyframe/frame.py, py-polars/pyproject.toml, py-polars/tests/unit/datatypes/test_object.py, py-polars/tests/unit/io/test_hive.py, py-polars/tests/unit/operations/test_join.py, py-polars/tests/unit/operations/test_sort.py, py-polars/tests/unit/streaming/test_streaming_categoricals.py, py-polars/tests/unit/streaming/test_streaming_join.py, py-polars/tests/unit/test_cse.py, py-polars/tests/unit/test_predicates.py, py-polars/tests/unit/test_string_cache.py
Closes https://github.com/pola-rs/polars/issues/13441
* Change default `coalesce` behavior for `join(how="left")` from `True` to `False`.
**Before**
```pycon
>>> df1 = pl.DataFrame({"a": [1, 2, 3], "b": [9, 9, 9]})
>>> df2 = pl.DataFrame({"a": [2, 3, 4], "c": [0, 0, 0]})
>>> df1.join(df2, on="a", how="left")
shape: (3, 3)
┌─────┬─────┬──────┐
│ a   ┆ b   ┆ c    │
│ --- ┆ --- ┆ ---  │
│ i64 ┆ i64 ┆ i64  │
╞═════╪═════╪══════╡
│ 1   ┆ 9   ┆ null │
│ 2   ┆ 9   ┆ 0    │
│ 3   ┆ 9   ┆ 0    │
└─────┴─────┴──────┘
```
**After**
```pycon
>>> df1.join(df2, on="a", how="left")
shape: (3, 4)
┌─────┬─────┬─────────┬──────┐
│ a   ┆ b   ┆ a_right ┆ c    │
│ --- ┆ --- ┆ ---     ┆ ---  │
│ i64 ┆ i64 ┆ i64     ┆ i64  │
╞═════╪═════╪═════════╪══════╡
│ 1   ┆ 9   ┆ null    ┆ null │
│ 2   ┆ 9   ┆ 2       ┆ 0 …
```
=> feat!: Default to `coalesce=False` in left outer join

crates/polars-ops/src/chunked_array/strings/concat.rs, crates/polars-plan/src/dsl/function_expr/strings.rs, crates/polars-plan/src/dsl/string.rs, py-polars/polars/expr/string.py, py-polars/polars/series/string.py, py-polars/src/expr/string.rs, py-polars/tests/unit/expr/test_expr_apply_eval.py, py-polars/tests/unit/operations/namespaces/string/test_concat.py, py-polars/tests/unit/operations/namespaces/string/test_string.py, py-polars/tests/unit/sql/test_table_operations.py
This brings the method in line with `list.join` and `arr.join`, and Python's `join` method on strings.
=> depr(python, rust!): Rename `str.concat` to `str.join`

py-polars/polars/dataframe/frame.py, py-polars/polars/dataframe/group_by.py, py-polars/tests/unit/dataframe/test_partition_by.py, py-polars/tests/unit/operations/rolling/test_rolling.py, py-polars/tests/unit/operations/test_group_by.py, py-polars/tests/unit/operations/test_group_by_dynamic.py, py-polars/tests/unit/test_rows.py
Ref https://github.com/pola-rs/polars/issues/13525 , https://github.com/pola-rs/polars/issues/13371
- Update `group_by` iteration to always return tuple keys
- Update `partition_by(as_dict=True)` to always return tuple keys
**Before**
```pycon
>>> df = pl.DataFrame({"a": [1, 1, 2], "b": [3, 4, 5]})
>>> df.partition_by("a", as_dict=True).keys()
dict_keys([1, 2])
```
**After**
```pycon
>>> df.partition_by("a", as_dict=True).keys()
dict_keys([(1,), (2,)])
```
=> feat(python)!: Update group-by iteration to always return tuple keys

crates/polars-core/src/utils/supertype.rs, py-polars/tests/unit/datatypes/test_integer.py
Fixes https://github.com/pola-rs/polars/issues/16798
=> fix: Fix comparison of UInt64 with zero

crates/polars-parquet/src/arrow/write/binview/basic.rs, crates/polars-parquet/src/arrow/write/primitive/nested.rs
This adds further usage of `polars-compute` in `polars-parquet`. I cannot get it to work for Primitives since there is a very, very annoying trait bound I cannot really circumvent without changing `polars-compute`.
=> refactor(rust): start further use of polars-compute in polars-parquet

py-polars/requirements-ci.txt, py-polars/requirements-dev.txt
Ref https://github.com/delta-io/delta-rs/issues/2577
=> chore(python): Skip latest deltalake release on macos

crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs, crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs, crates/polars-plan/src/logical_plan/alp/dot.rs, crates/polars-plan/src/logical_plan/alp/format.rs, crates/polars-plan/src/logical_plan/alp/mod.rs, crates/polars-plan/src/logical_plan/alp/tree_format.rs, crates/polars-plan/src/logical_plan/functions/mod.rs, crates/polars-utils/src/arena.rs
This PR adds back the possibility to `describe` / `explain` streaming engine plans. As these plans are not stored in the main `IRPlan`, there need to be special cases for that in each `describe` format.
This specifically addresses it for:
- Base format: Adds streaming header, prints the underlying plan
- Tree format: Adds streaming header into top node, prints the underlying plan
- Dot format: Prints the underlying plan
Fixes #16762
=> fix(rust): `describe` / `explain` streaming plan

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/test_errors.py
Put clear warnings on every `set_sorted` def and don't accept multiple columns. If you want to indicate that multiple columns are sorted individually, you'd have to do that manually. This makes it extra clear that the columns are sorted individually.
=> feat(python)!: Only accept a single column in `set_sorted`

py-polars/requirements-dev.txt, py-polars/tests/unit/operations/test_value_counts.py
I messed up in https://github.com/pola-rs/polars/pull/16803. I verified now that this works.
=> chore(python): Properly skip deltalake 0.18.0 for MacOS

crates/polars-io/src/json/infer.rs, crates/polars-io/src/json/mod.rs, crates/polars-io/src/ndjson/core.rs, crates/polars-io/src/ndjson/mod.rs, crates/polars-json/src/ndjson/file.rs, crates/polars-lazy/src/physical_plan/executors/scan/ndjson.rs, crates/polars/tests/it/io/json.rs, py-polars/polars/io/ndjson.py, py-polars/src/dataframe/io.rs, py-polars/tests/unit/io/test_lazy_json.py
=> fix: Raise on non-positive json schema inference

crates/polars-core/src/chunked_array/ops/sort/arg_sort.rs, crates/polars-core/src/chunked_array/ops/sort/mod.rs, py-polars/tests/unit/operations/test_sort.py
Slightly less work by adding a non-null branch. Will follow up with a proper speed up and special implementation for view types and binaryoffset (row encoding).
=> perf: Special no null branch in arg-sort

py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/src/expr/general.rs, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/operations/test_top_k.py
Closes https://github.com/pola-rs/polars/issues/15236
* Rename the `descending` parameter to `reverse` in `DataFrame/LazyFrame.top_k/bottom_k` and `Expr.top_k_by/bottom_k_by`.
=> depr(python): Rename parameter `descending` to `reverse` in `top_k` methods

crates/polars-plan/src/dsl/function_expr/pow.rs, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/arithmetic/test_arithmetic.py
closes #15897
I'll maintain that the change introduced in https://github.com/pola-rs/polars/pull/15506 is a net-positive, and that avoiding floating point imprecision for this operation is desirable - so I've just improved the error  message and docs
Demo:
```python
In [1]: import polars as pl
...: data = pl.DataFrame({"a": [1,2,3]})
...: data.select([pl.col("a").pow(-1)])
InvalidOperationError                     Traceback (most recent call last)
Cell In[1], line 3
1 import polars as pl
2 data = pl.DataFrame({"a": [1,2,3]})
----> 3 data.select([pl.col("a").pow(-1)])
File ~/polars-dev/py-polars/polars/dataframe/frame.py:8318, in DataFrame.select(self, *exprs, **named_exprs)
8218 def select(
8219     self, *exprs: …
```
=> feat: improve error message when raising integers to negative integers, improve docs

crates/polars-core/src/series/comparison.rs, py-polars/tests/unit/test_errors.py
#16791 already removed most needless panics in arithmetic. Now also remove them in comparisons. I think these might hit users the most. They were also trivially fixed, so let's squash more of those.
Fixes #16824
=> fix: Reduce needless panics in comparisons

py-polars/polars/expr/string.py, py-polars/polars/series/string.py
Closes #13698
This is a breaking change. If a deprecation is desired first, let me know.
Similar to #7860, the use of this argument is much more natural as a keyword argument, so impact should be limited.
Also stated there, these are hard to properly deprecate due to the Series -> Expr dispatch.
=> refactor(python)!: Set `infer_schema_length` as keyword-only for `str.json_decode`

crates/polars-core/src/utils/mod.rs, crates/polars-ops/src/frame/join/asof/groups.rs
=> fix: Ensure that splitted ChunkedArray also flattens chunks

crates/polars-sql/src/context.rs, py-polars/polars/sql/context.py, py-polars/tests/unit/sql/test_literals.py, py-polars/tests/unit/sql/test_miscellaneous.py
Closes #16826.
* Allows SQL queries of the form `SELECT 1 AS "one", 2.0 AS "two"` (project literals without reference to a table)[^1].
**Also:**
* Improves/streamlines use of `SQLContext` with globals (cleaner/better handling of reserved SQL keywords).
* Removes a potential `SQLContext` footgun; can only automatically register non-Polars globals via `pl.sql` or `SQLContext.execute_global` now; this ensures that we only register objects referenced in an actual query.
[^1]: PostgreSQL "SELECT" syntax: https://www.postgresql.org/docs/current/sql-select.html#:~:text=SELECT%20retrieves%20rows%20from%20zero%20or%20more%20tables.
=> feat: Support `SQL` "SELECT" with no tables, optimise registration of globals

py-polars/polars/io/spreadsheet/functions.py, py-polars/tests/unit/io/test_spreadsheet.py
Closes #16408.
* Ensures consistent behaviour between all supported engines when `infer_schema_length` == 0.; we expect _no_ inference in this case, meaning all columns should be loaded as strings.
* Validated for  "xlsx2csv", "openpyxl", and "calamine".
* Also covers `read_ods`.
=> fix(python): Consistent behaviour when "infer_schema_length=0" for `read_excel`

py-polars/polars/expr/array.py, py-polars/polars/expr/list.py, py-polars/polars/series/array.py, py-polars/polars/series/list.py, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/operations/namespaces/list/test_list.py
=> feat(python!): Default to raising for oob on all `get`/`gather` operations

.github/workflows/docs-global.yml
The link to the API references will be updated. The old location will redirect to the new location.
Reasons the old URLs are not great:
* The `py-polars/html` path in our current stable docs doesn't make much sense - this is old and was kept for backwards compatibility.
* Now that our base domain is `docs.pola.rs`, it doesn't make sense for our dev references to start with `docs/...`.
Logic behind the new URLs:
* The links are set up like https://docs.pola.rs/api/{language}/{version}
* This matches nicely with the existing docs page for the API refs: https://docs.pola.rs/api/
This is not a super important issue, but it's just a nice professional touch if the URLs make sense. We have previously moved our user guide to a new path using redirects and it was easy and was picked up by search …
=> chore: Prepare update of API reference URLs

.github/ISSUE_TEMPLATE/documentation.yml, .github/workflows/docs-python.yml, .github/workflows/docs-rust.yml, README.md, docs/_build/API_REFERENCE_LINKS.yml, docs/api/index.md, docs/development/contributing/index.md, docs/development/versioning.md, docs/user-guide/expressions/functions.md, docs/user-guide/expressions/plugins.md, docs/user-guide/expressions/user-defined-functions.md, py-polars/docs/source/_static/version_switcher.json, py-polars/docs/source/conf.py, py-polars/pyproject.toml
Followup of https://github.com/pola-rs/polars/pull/16816
=> chore: Update links to API references

.github/workflows/docs-global.yml, .github/workflows/docs-python.yml, .github/workflows/release-python.yml, py-polars/docs/source/conf.py
This makes sure that the **stable** API reference remains at the latest full release (currently `0.20.31`) when we start publishing pre-releases of 1.0.0.
Also prepares to publish 1.0.0 versions to `api/python/version/1`.
=> ci(python): Do not update stable API reference on prerelease

crates/polars-core/src/frame/mod.rs, py-polars/tests/unit/test_chunks.py
=> fix: Fix `should_rechunk` check

crates/polars-arrow/src/array/mod.rs, crates/polars-core/src/chunked_array/ops/chunkops.rs, crates/polars-core/src/frame/mod.rs, crates/polars-core/src/series/implementations/array.rs, crates/polars-core/src/series/implementations/binary.rs, crates/polars-core/src/series/implementations/binary_offset.rs, crates/polars-core/src/series/implementations/boolean.rs, crates/polars-core/src/series/implementations/categorical.rs, crates/polars-core/src/series/implementations/date.rs, crates/polars-core/src/series/implementations/datetime.rs, crates/polars-core/src/series/implementations/decimal.rs, crates/polars-core/src/series/implementations/duration.rs, crates/polars-core/src/series/implementations/floats.rs, crates/polars-core/src/series/implementations/list.rs, crates/polars-core/src/series/implementations/mod.rs, crates/polars-core/src/series/implementations/null.rs, crates/polars-core/src/series/implementations/object.rs, crates/polars-core/src/series/implementations/string.rs, crates/polars-core/src/series/implementations/struct_.rs, crates/polars-core/src/series/implementations/time.rs, crates/polars-core/src/series/series_trait.rs, crates/polars-core/src/utils/mod.rs
Can add this to more splitting functionality.
=> perf: Use `split_at` instead of double slice in chunk splits.

py-polars/polars/functions/lit.py, py-polars/tests/unit/functions/test_lit.py
Closes #16668
We now take the Enum value as a literal. If it's a string Enum, and dtype is not set, we set the dtype to a Polars `Enum`.
=> feat(python): Support Python `Enum` values in `lit`

crates/polars-sql/Cargo.toml, crates/polars-sql/src/context.rs, py-polars/tests/unit/sql/test_miscellaneous.py, py-polars/tests/unit/sql/test_numeric.py
Adds new SQL interface support for...
* The `VALUES`[^1] clause (doesn't support inline literal casts yet).
* Column (re)naming in derived table aliases (eg: CTEs and VALUES clause).
Standalone `VALUES` clause:
```python
pl.sql("VALUES (1,2), (3,4)").collect()
```
Select from `VALUES`, applying column names with the table alias:
```python
pl.sql("SELECT * FROM (VALUES(1,2), (3,4)) AS tbl(colx, coly)").collect()
```
Demonstrate/stress-test name/alias resolution; select from inner `VALUES` and show that we successfully map column/table names through multiple levels of nested CTEs and derived table column aliasing.
```python
df = pl.sql(
"""
WITH
x AS (SELECT w.* FROM (VALUES(1,2), (3,4)) AS w(a, b)),
y (m, n) AS (
WITH z(c, d) AS (SELECT a, b FROM x)
SELECT d*2 AS d2, c*3 AS c3 FROM z
) …
```
=> feat: Support SQL `VALUES` clause and inline renaming of columns in CTE & derived table definitions

crates/polars-core/src/utils/mod.rs
This will save a lot of double null_counts.
=> perf: Use `split_at` in `split`

crates/polars-io/src/file_cache/entry.rs
We already always wrap it in an `Arc` on the outside (`Arc<FileCacheEntry>`)
=> refactor: Remove inner `Arc` from `FileCacheEntry`

crates/polars-sql/src/table_functions.rs, py-polars/tests/unit/sql/test_miscellaneous.py
Several modest improvements to SQL table-read function:
* Sets "try_parse_dates=True" by default for `read_csv`.
* Raises a `SQLSyntax` error if more than one argument is passed (all read funcs).
* Adds extra test coverage (null vs empty string, dates) for CSV reads from SQL.
```python
df = pl.sql(f"SELECT * FROM read_csv('some_file.csv')").collect()
```
=> feat: Improve `read_csv` SQL table reading function defaults (better handle dates)

crates/polars-arrow/src/array/binview/mod.rs, crates/polars-core/src/chunked_array/ops/downcast.rs, crates/polars-core/src/chunked_array/ops/sort/categorical.rs, crates/polars-core/src/chunked_array/ops/sort/mod.rs, py-polars/tests/unit/operations/test_sort.py
Sort by the views directly and go through the whole constructors, leaving the buffers as is.
=> perf: Optimize string/binary sort

py-polars/docs/source/_static/version_switcher.json
**DO NOT MERGE**
This should be merged right before our first `1.0.0` pre-release.
It will make sure people can select version `1` from the version switcher.
The stable version remains at 0.20 until the definitive `1.0.0` version is released.
=> docs(python): Update version switcher for 1.0.0 prereleases

crates/polars-core/src/frame/mod.rs, py-polars/tests/unit/functions/test_functions.py
Closes #16882 by replacing the unwrap with proper error propagation. This still leaves open the other aspect, where the pl.DataFrame() constructor and pl.lit() treat literal ints inconsistently.
=> fix: Remove unwrap in `extend()`

crates/polars-ops/src/series/ops/rle.rs, py-polars/tests/unit/operations/test_group_by_dynamic.py, py-polars/tests/unit/operations/test_is_sorted.py, py-polars/tests/unit/operations/test_join.py, py-polars/tests/unit/operations/test_sort.py, py-polars/tests/unit/streaming/test_streaming_join.py
Faster iteration and set proper flags. closes #16887
=> perf: Improve rle_id iteration perf and set sorted flags

crates/polars-core/src/utils/series.rs, crates/polars-plan/src/logical_plan/conversion/type_coercion/binary.rs, py-polars/polars/interchange/from_dataframe.py, py-polars/tests/unit/constructors/test_dataframe.py, py-polars/tests/unit/datatypes/test_enum.py, py-polars/tests/unit/functions/range/test_int_range.py, py-polars/tests/unit/functions/test_when_then.py, py-polars/tests/unit/operations/namespaces/string/test_string.py, py-polars/tests/unit/operations/namespaces/temporal/test_to_datetime.py, py-polars/tests/unit/operations/namespaces/test_strptime.py, py-polars/tests/unit/operations/test_cast.py, py-polars/tests/unit/operations/test_clip.py, py-polars/tests/unit/operations/test_replace.py, py-polars/tests/unit/series/test_series.py, py-polars/tests/unit/sql/test_cast.py, py-polars/tests/unit/sql/test_temporal.py, py-polars/tests/unit/test_errors.py, py-polars/tests/unit/test_format.py, py-polars/tests/unit/test_lazy.py
A lot of casting failures were already `InvalidOperationError`. Now a whole bunch of others are as well.
=> feat!: Change casting failures from `ComputeError` to `InvalidOperationError`

crates/polars-compute/src/comparisons/array.rs, crates/polars-compute/src/comparisons/mod.rs, crates/polars-compute/src/comparisons/null.rs, crates/polars-compute/src/comparisons/struct_.rs, py-polars/tests/unit/testing/test_assert_series_equal.py
This PR adds more types of equality checks for different types of `FixedSizeList`s. There are two many areas remaining which are the `Offset` based arrays and the `DictionaryArray`.
=> feat(rust,python): add `eq`/`ne` for more `FixedSizeList`s

py-polars/tests/unit/io/cloud/test_aws.py
Ref #16910
I've seen this fail more often, for example:
https://github.com/pola-rs/polars/actions/runs/9486777587/job/26141912223?pr=16906
Failure seems to be in the test rather than in the functionality, so skipping for now.
=> test(python): Skip intermittently failing AWS test

py-polars/polars/series/datetime.py, py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py
We can now use `Series.mean` and `Series.median` for all temporal dtypes.
=> depr(python): Deprecate `dt.mean`/`dt.median` in favor of `mean`/`median`

.github/workflows/docs-python.yml, .github/workflows/release-python.yml, py-polars/docs/source/reference/expressions/string.rst, py-polars/docs/source/reference/series/string.rst, py-polars/polars/expr/string.py, py-polars/polars/series/string.py
Followup on https://github.com/pola-rs/polars/pull/16790 - I missed some things.
Also enabling publishing of docs on pre-releases. It's useful for people to have access to the migration guide and API reference when trying out a pre-release.
=> docs(python): Add missing deprecation entry for `str.concat`, API ref entry for `str.join`, build docs on pre-release

crates/polars-ops/src/series/ops/various.rs, crates/polars-plan/src/dsl/function_expr/dispatch.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/dsl/mod.rs, docs/src/rust/user-guide/expressions/structs.rs, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/src/expr/general.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/src/series/mod.rs, py-polars/tests/unit/operations/test_value_counts.py
=> feat: Normalize `value_counts`

py-polars/docs/source/reference/index.rst, py-polars/docs/source/reference/schema/index.rst, py-polars/polars/__init__.py, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/name.py, py-polars/polars/functions/as_datatype.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/schema.py, py-polars/polars/series/struct.py, py-polars/tests/unit/constructors/test_dataframe.py, py-polars/tests/unit/test_schema.py
Ref https://github.com/pola-rs/polars/issues/16328
* Introduce a new `Schema` class. It is currently basically just an `OrderedDict`, but has some additional methods:
* `names`
* `dtypes`
* `len`
* Update various `schema` methods to return this new Schema class instead of an `OrderedDict`.
Because it inherits `OrderedDict`, it can also be used as input for `schema` arguments anywhere in the API, e.g. the `DataFrame` constructor, `read_csv`, etc.
I will expand the Schema class in the future to be a bit more user friendly for direct use. For now it's already useful as a returned object from the upcoming `LazyFrame.collect_schema` method.
=> feat(python): Add `Schema` class

crates/polars-plan/src/logical_plan/conversion/type_coercion/mod.rs, crates/polars/tests/it/lazy/expressions/slice.rs, py-polars/polars/expr/expr.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/expr/test_exprs.py
=> fix(rust): Reject non-integral offset and length in AExpr::Slice

crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-utils/src/fixedringbuffer.rs
This provides some small follow-up changes for #16747.
=> refactor(rust): Follow-up changes to polars-parquet

crates/polars-core/src/series/arithmetic/borrowed.rs, crates/polars-core/src/series/implementations/duration.rs, crates/polars-core/src/series/implementations/floats.rs, crates/polars-core/src/series/implementations/mod.rs, crates/polars-expr/src/expressions/binary.rs, crates/polars-plan/src/logical_plan/aexpr/schema.rs, crates/polars-plan/src/logical_plan/conversion/type_coercion/binary.rs, py-polars/tests/unit/operations/arithmetic/test_arithmetic.py, py-polars/tests/unit/test_errors.py
Ensure we get the proper types and raise better errors if not supported.
fixes #16927
=> feat: Implement multiply and division for lhs duration

crates/polars-expr/src/expressions/literal.rs, crates/polars-plan/src/logical_plan/lit.rs, py-polars/src/functions/lazy.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/tests/unit/functions/test_lit.py
Closes https://github.com/pola-rs/polars/issues/13341
Previously, passing Python Decimal objects to `lit` was unsupported. Now it works:
```python
from decimal import Decimal
expr = pl.lit(Decimal("0.1"))
print(pl.select(expr))
```
```
shape: (1, 1)
┌──────────────┐
│ literal      │
│ ---          │
│ decimal[*,1] │
╞══════════════╡
│ 0.1          │
└──────────────┘
```
=> feat(python): Support Decimal inputs for `lit`

crates/polars-io/src/avro/write.rs, crates/polars-io/src/ipc/write.rs, crates/polars-io/src/json/mod.rs, crates/polars-io/src/parquet/write/writer.rs, crates/polars-io/src/shared.rs, py-polars/src/dataframe/io.rs, py-polars/tests/unit/datatypes/test_object.py
=> fix: Raise informative error when writing object to file

crates/polars-core/src/chunked_array/list/mod.rs, crates/polars-core/src/chunked_array/metadata/mod.rs, crates/polars-core/src/chunked_array/ops/append.rs, py-polars/tests/unit/operations/test_explode.py
Fixes #16923.
This resolves very dumb mistake (I made), where the `FAST_EXPLODE_LIST` was only ever set to `true` when calling `set_fast_explode_list`.
We now use `set` instead of `insert`.
=> fix: properly set `FAST_EXPLODE_LIST` metadata

py-polars/src/conversion/any_value.rs, py-polars/tests/unit/test_errors.py
=> fix(python): Don't panic in object to anyvalue

Cargo.lock, crates/polars-io/src/cloud/options.rs, crates/polars-io/src/file_cache/cache.rs, crates/polars-io/src/file_cache/entry.rs, crates/polars-io/src/file_cache/eviction.rs, crates/polars-io/src/file_cache/file_lock.rs, crates/polars-io/src/file_cache/metadata.rs, crates/polars-io/src/file_cache/mod.rs, crates/polars-io/src/file_cache/utils.rs, crates/polars-io/src/utils.rs, py-polars/Cargo.toml, py-polars/polars/__init__.py, py-polars/polars/io/csv/functions.py, py-polars/polars/io/ipc/functions.py, py-polars/requirements-dev.txt, py-polars/src/functions/io.rs, py-polars/src/lazyframe/mod.rs, py-polars/src/lib.rs, py-polars/tests/unit/io/test_file_cache.py
Note this means we need to pay the cost of needing to load every metadata file to check the TTL for eviction
=> feat: Allow setting file cache TTL on a per-file basis

crates/polars-core/src/datatypes/any_value.rs, crates/polars-core/src/series/any_value.rs, py-polars/polars/config.py, py-polars/polars/series/series.py, py-polars/tests/unit/constructors/test_any_value_fallbacks.py, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/operations/test_cast.py, py-polars/tests/unit/test_format.py
Ref https://github.com/pola-rs/polars/issues/14427
* Implement casting for AnyValue to Decimal
* Update AnyValue constructors to properly apply the `strict` parameter. This means that the following will raise unless `strict=False` is set:
* Mixing Decimals with non-decimals
* Mixing Decimals with different scales
* Decimals that do not match the given `dtype`
=> fix: Handle strictness for Decimal Series construction

py-polars/src/conversion/mod.rs, py-polars/src/series/construction.rs, py-polars/tests/unit/datatypes/test_object.py
=> fix(python): Raise on list of objects

py-polars/polars/_utils/deprecation.py, py-polars/polars/_utils/unstable.py, py-polars/polars/_utils/various.py, py-polars/polars/exceptions.py, py-polars/polars/lazyframe/frame.py, py-polars/src/error.rs, py-polars/src/lib.rs, py-polars/tests/unit/io/cloud/test_aws.py, py-polars/tests/unit/lazyframe/test_lazyframe.py, py-polars/tests/unit/operations/arithmetic/test_arithmetic.py, py-polars/tests/unit/test_exceptions.py, py-polars/tests/unit/utils/test_various.py
Closes https://github.com/pola-rs/polars/issues/16328
* Add new `PerformanceWarning` warning. This is a base class for some other warnings, including `PolarsInefficientMapWarning` and `CategoricalRemappingWarning`.
* Make `LazyFrame` properties emit a warning, informing the user of the potential performance cost, and redirecting to `LazyFrame.collect_schema`.
=> feat(python): Add `PerformanceWarning` to LazyFrame properties

crates/polars-core/src/datatypes/dtype.rs, crates/polars-core/src/series/any_value.rs, docs/src/python/user-guide/getting-started/expressions.py, docs/src/python/user-guide/getting-started/joins.py, py-polars/polars/_utils/construction/series.py, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/io/spreadsheet/functions.py, py-polars/polars/series/series.py, py-polars/src/series/construction.rs, py-polars/tests/unit/constructors/test_constructors.py, py-polars/tests/unit/constructors/test_dataframe.py, py-polars/tests/unit/constructors/test_series.py, py-polars/tests/unit/dataframe/test_getitem.py, py-polars/tests/unit/dataframe/test_serde.py, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/operations/aggregation/test_aggregations.py, py-polars/tests/unit/operations/aggregation/test_horizontal.py, py-polars/tests/unit/operations/test_ewm.py, py-polars/tests/unit/series/test_getitem.py, py-polars/tests/unit/test_convert.py, py-polars/tests/unit/test_errors.py
Closes https://github.com/pola-rs/polars/issues/14427
This PR finally switches over to the strategy to try the fast constructors first, and then fall back to AnyValue constructors.
=> feat(python)!: Properly apply `strict` parameter in Series constructor

crates/polars-core/src/series/comparison.rs, crates/polars-ops/src/chunked_array/scatter.rs, py-polars/src/series/scatter.rs, py-polars/tests/unit/series/test_scatter.py, py-polars/tests/unit/test_errors.py
Fixes #16905 
Previously various interactions in Python of assigning to a Series would clear the data from the Series if an error occurred. In interactive usage, for example in a Jupyter notebook, this is undesirable behavior because typos or just playing around shouldn't result in data disappearing.
Example of previous, buggy behavior that this PR fixes:
```python
>>> s = pl.Series([1, 2, 3])
>>> s[-200] = 5
File "/home/itamarst/devel/sandbox/venv311/lib/python3.11/site-packages/polars/series/series.py", line 1250, in __setitem__
self.scatter(key, value)
File "/home/itamarst/devel/sandbox/venv311/lib/python3.11/site-packages/polars/series/series.py", line 4895, in scatter …
```
=> fix(16905): Fix a number of edge cases where assignment corrupted a Series

crates/polars-io/src/json/mod.rs, crates/polars-io/src/mmap.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-plan/src/dsl/cat.rs, py-polars/src/dataframe/io.rs, py-polars/src/file.rs, py-polars/tests/unit/io/test_json.py
=> feat(python): Handle textio even if not correct

py-polars/polars/_utils/construction/dataframe.py, py-polars/tests/unit/constructors/test_constructors.py
I found an edge case where the input `[[1]]` would be interpreted row-wise when it could be interpreted column-wise.
We'll get rid of this logic anyway, but I have to fix this to properly deprecate it, otherwise we get false positives.
=> fix(python): Fix edge case in DataFrame constructor data orientation inference

py-polars/tests/unit/constructors/test_constructors.py, py-polars/tests/unit/dataframe/test_describe.py, py-polars/tests/unit/dataframe/test_df.py, py-polars/tests/unit/datatypes/test_decimal.py, py-polars/tests/unit/datatypes/test_list.py, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/functions/test_cum_count.py, py-polars/tests/unit/interop/test_interop.py, py-polars/tests/unit/operations/aggregation/test_aggregations.py, py-polars/tests/unit/operations/aggregation/test_horizontal.py, py-polars/tests/unit/operations/namespaces/string/test_string.py, py-polars/tests/unit/operations/namespaces/test_binary.py, py-polars/tests/unit/operations/test_ewm.py, py-polars/tests/unit/operations/test_is_in.py, py-polars/tests/unit/operations/test_pivot.py, py-polars/tests/unit/operations/test_shift.py, py-polars/tests/unit/sql/test_temporal.py, py-polars/tests/unit/test_api.py, py-polars/tests/unit/test_cse.py, py-polars/tests/unit/test_queries.py, py-polars/tests/unit/test_rows.py, py-polars/tests/unit/test_string_cache.py
Ref https://github.com/pola-rs/polars/issues/16818
This will raise a warning in the future.
=> refactor(python): Update test suite to explicitly use `orient="row"` in DataFrame constructor when applicable

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, py-polars/tests/unit/operations/test_join.py
=> fix: Fix projection pushdown with literal joins

crates/polars-plan/src/logical_plan/optimizer/join_utils.rs, crates/polars-plan/src/logical_plan/optimizer/mod.rs, crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs, crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs, py-polars/tests/unit/operations/test_cross_join.py
=> fix: Don't pushdown predicates in cross join if the refer to both tables

crates/polars-io/src/file_cache/cache_lock.rs, crates/polars-io/src/file_cache/eviction.rs
I played around a bit, I think what happens is pytest joins on the N workers it spawns together at the end, and some workers finish running tests earlier. This and combined with that pytest I think only silences test output during execution of a test, so the workers that have finished (and are getting joined on) no longer have silenced stdout/stderr, the printing from the background task then gets displayed after the background task runs, as POLARS_VERBOSE was set to true during the test execution 
I can seemingly confirm because the more I increase the worker count, the more messages get logged.
This is fixed by not caching the `config::verbose` value, as it gets unset after the test finishes.
=> test: Fix file cache verbose logging leakage during pytest

crates/polars-core/src/series/implementations/boolean.rs, crates/polars-core/src/series/implementations/date.rs, crates/polars-core/src/series/implementations/floats.rs, crates/polars-core/src/series/implementations/mod.rs, crates/polars-core/src/series/mod.rs, crates/polars-core/src/series/series_trait.rs, crates/polars-expr/src/expressions/aggregation.rs
This introduces the use of the `min_value` and `max_value` metadata for the aggregation expressions. Currently, this is only enabled for `POLARS_METADATA_FLAGS=extensive` under debug builds, but after some testing, we can try to enable it for more people.
For large parquet data sets with statistics, where the metadata is already loaded. This massively speeds up the computation.
As an example.
```python
yellow_tripdata = pl.read_parquet("yellow_tripdata_2024-01.parquet")
yellow_tripdata.write_parquet("a.parquet", statistics='full')
df = pl.read_parquet("a.parquet")
for _ in range(1000):
_ = df.select(pl.col.total_amount.min())
```
Enabling `POLARS_METADATA_FLAGS=extensive`, speeds up 20+ seconds to basically instantly.
=> feat(rust): use min/max metadata on debug builds with `POLARS_METADATA_FLAGS=extensive`

crates/polars-core/src/series/arithmetic/borrowed.rs, py-polars/tests/unit/operations/arithmetic/test_arithmetic.py
=> fix: Raise on invalid arithmetic shapes

_typos.toml, crates/polars-plan/src/logical_plan/conversion/dsl_to_ir.rs, crates/polars-plan/src/logical_plan/conversion/stack_opt.rs
@alexander-beedie FYI. This should ensure the same performance as explicit nodes.
=> perf: Desugar `AND` filter into multiple nodes

crates/polars-core/src/chunked_array/ndarray.rs, py-polars/tests/unit/interop/numpy/test_to_numpy_df.py
https://github.com/pola-rs/polars/pull/16288 introduced a regression that caused `to_numpy(order="c")` calls to silently yield erroneous NumPy arrays whenever the data frame has more than one chunk. To reproduce with the latest release or polars `main`:
```python
from polars.testing import assert_frame_equal
rng = np.random.default_rng()
f"col_{i}": rng.normal(size=100_000)
for i in range(1000)
})
df_chunked = pl.concat([df.slice(i * 10_000, 10_000) for i in range(10)])
assert_frame_equal(
df_chunked,
pl.from_numpy(df_chunked.to_numpy(order="c"), schema=df_chunked.schema)
)
```
Currently, this results in an assertion failure. This PR fixes the issue.
---
I'm not sure if this is easily feasible but it would be great if this change …
=> fix(rust, python): Correctly convert data frames to NumPy for C index order

py-polars/docs/source/reference/exceptions.rst, py-polars/polars/__init__.py, py-polars/polars/exceptions.py, py-polars/tests/unit/operations/test_sort.py, py-polars/tests/unit/testing/test_assert_frame_equal.py
I caught two bugs, made separate issue for them:
https://github.com/pola-rs/polars/issues/17007
https://github.com/pola-rs/polars/issues/17009
Also an unrelated update to the docs - I had inadvertently added `ChronoFormatWarning` twice.
=> test(python): Add some parametric tests for sort functionality

py-polars/tests/unit/io/test_file_cache.py
I think the eviction task ran instantly - to fix this we won't check if the paths were created, instead we just check the file is successfully read.
=> test: Fix failing file cache test in CI

crates/polars-sql/src/context.rs, crates/polars-sql/tests/functions_io.rs, crates/polars-sql/tests/simple_exprs.rs, py-polars/docs/source/_static/css/custom.css, py-polars/docs/source/reference/dataframe/index.rst, py-polars/docs/source/reference/lazyframe/index.rst, py-polars/docs/source/reference/series/index.rst, py-polars/docs/source/reference/sql/clauses.rst, py-polars/docs/source/reference/sql/functions/aggregate.rst, py-polars/docs/source/reference/sql/functions/math.rst, py-polars/docs/source/reference/sql/functions/string.rst, py-polars/docs/source/reference/sql/index.rst, py-polars/docs/source/reference/sql/python_api.rst, py-polars/docs/source/reference/sql/table_operations.rst, py-polars/tests/unit/sql/test_miscellaneous.py
* Extends the Python API section of the SQL docs with frame-level (`DataFrame.sql`, `LazyFrame.sql`) and top-level (`pl.sql` and `pl.sql_expr`) entries, with details/examples (including executing Polars SQL against pyarrow/pandas).
* Minor enhancement to code blocks; applies a small/faint drop-shadow that exactly matches admonitions. Looks slightly nicer and more visually consistent, especially when admonitions are found immediately adjacent.
* Added supported function aliases to several SQL functions (eg: `CEIL` can also be `CEILING`).
* Added `DISTINCT` to "clauses" docs.
More to come...
=> docs: Lots of additions to the SQL reference docs

crates/polars-core/src/chunked_array/metadata/collect.rs, crates/polars-core/src/chunked_array/metadata/env.rs, crates/polars-expr/src/expressions/aggregation.rs
This renames the metadata flag from `POLARS_METADATA_FLAGS` to `POLARS_METADATA_USE`. I also renamed `extensive` to `experimental`. There are 3 settings that can be controlled.
| Setting      | Debug Build                        | Release Build                      |
|--------------|------------------------------------|------------------------------------|
| Enabled      | `POLARS_METADATA_USE=1` (default)  | `true`                             |
| Experimental | `POLARS_METADATA_USE=experimental` | `POLARS_METADATA_USE=experimental` |
| Logging      | `POLARS_METADATA_USE=log`          | `false`                            |
In the debug-mode, the value can be changed during runs to make A/B testing possible. For release-mode builds, the value is cached and cannot be changed after it is …
=> feat: allow experimental metadata use on release

crates/polars-plan/src/logical_plan/functions/dsl.rs, py-polars/tests/unit/operations/test_explode.py
Fixes #15852.
This adds a check for whether a column is defined or not in `explode`.
=> fix: properly catch not found explode cols

py-polars/polars/io/database/_executor.py
Closes #17022.
* Hardens `async` checks for `sqlalchemy` connections so they are resilient to old library versions (that do not actually implement any such support).
=> fix: Harden "async" check for users with out-of-date `sqlalchemy` libraries

crates/polars-plan/src/logical_plan/conversion/dsl_to_ir.rs, py-polars/tests/unit/operations/test_filter.py
=> fix: Don't split up ANDed filters that are group-aware

crates/polars-sql/src/context.rs, crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_joins.py
Ref: https://github.com/pola-rs/polars/issues/16662.
* Catch use of old-school implicit JOIN syntax (multiple tables in the FROM clause, constraints in the WHERE) and raise an informative error; currently we require use of explicit JOIN constraints.
* A few minor renames/cleanups, eg: `process_set_expr` -> `process_query`.
Note that I do expect to have the implicit form working in the not-too-distant future, but at the moment anyone using this syntax may experience less useful errors or incorrect results, so we need to catch it until it is properly supported.
=> fix: Don't silently accept multi-table FROM clauses (implicit JOIN syntax)

py-polars/polars/io/delta.py, py-polars/tests/unit/io/test_delta.py
Closes https://github.com/pola-rs/polars/issues/16982
1. Add rechunk=False to polars.read_delta();
2. Add unit test for pl.read_delta(..., rechunk=False) with reference to [https://github.com/itamarst/polars/blob/616861217faf097f0568c8ede15d72b156d52561/py-polars/tests/unit/io/test_parquet.py#L109](#16416)
=> feat(python): Add `rechunk` parameter to `read_delta`

crates/polars-lazy/src/frame/mod.rs, crates/polars-plan/src/plans/builder_dsl.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/functions/dsl.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/operations/test_drop.py
Closes https://github.com/pola-rs/polars/issues/11913
This PR adds the `strict` flag on `LazyFrame::drop` that is set to `True` by default. When it is enabled, `drop` will validate the given column names against the schema and throw a `ColumnNotFound` error if the column is not defined instead of quietly ignore it. The flag can be set to `False` to re-enable the previous quiet ignoring behavior.
@stinodego
=> feat!: Add `strict` parameter to `DataFrame/LazyFrame.drop` and fix behavior to default to True

crates/polars-core/src/chunked_array/metadata/mod.rs, crates/polars-core/src/datatypes/into_scalar.rs, crates/polars-core/src/datatypes/mod.rs, crates/polars-core/src/series/implementations/boolean.rs, crates/polars-core/src/series/implementations/date.rs, crates/polars-core/src/series/implementations/floats.rs, crates/polars-core/src/series/implementations/mod.rs, crates/polars-core/src/series/series_trait.rs, crates/polars-expr/src/expressions/aggregation.rs
This adds a `MetadataTrait` with which `polars-expr` can freely access the metadata. This does require multiple instances of dynamic dispatch, but this seems like the proper solution and should be on a cold path in the code.
This is reliant on #17005.
=> refactor(rust): expose all metadata to polars-expr

crates/polars-arrow/src/bitmap/bitmap_ops.rs, crates/polars-arrow/src/bitmap/immutable.rs, crates/polars-compute/src/arithmetic/signed.rs, crates/polars-compute/src/arithmetic/unsigned.rs, crates/polars-compute/src/comparisons/array.rs, crates/polars-compute/src/comparisons/binary.rs, crates/polars-compute/src/comparisons/boolean.rs, crates/polars-compute/src/comparisons/dictionary.rs, crates/polars-compute/src/comparisons/dyn_array.rs, crates/polars-compute/src/comparisons/list.rs, crates/polars-compute/src/comparisons/mod.rs, crates/polars-compute/src/comparisons/null.rs, crates/polars-compute/src/comparisons/scalar.rs, crates/polars-compute/src/comparisons/simd.rs, crates/polars-compute/src/comparisons/struct_.rs, crates/polars-compute/src/comparisons/utf8.rs, crates/polars-compute/src/comparisons/view.rs, crates/polars-core/src/chunked_array/comparison/mod.rs, crates/polars-core/src/chunked_array/comparison/scalar.rs, py-polars/tests/unit/io/test_parquet.py, py-polars/tests/unit/testing/test_assert_series_equal.py
Closes #16698.
This implements general array equality checks for all array types except `Union` and `Map`.
This makes checking equality in tests a lot easier as well as just removing limitations for expressions.
=> feat: Implement general array equality checks

crates/polars-core/src/frame/arithmetic.rs, crates/polars-core/src/frame/mod.rs, crates/polars-core/src/series/arithmetic/borrowed.rs, crates/polars-core/src/series/arithmetic/owned.rs, crates/polars-core/src/series/implementations/date.rs, crates/polars-core/src/series/implementations/duration.rs, crates/polars-core/src/series/mod.rs, crates/polars-expr/src/expressions/aggregation.rs, crates/polars-expr/src/expressions/binary.rs, crates/polars-lazy/src/tests/queries.rs, crates/polars-ops/src/series/ops/business.rs, crates/polars-ops/src/series/ops/diff.rs, crates/polars-ops/src/series/ops/fused.rs, crates/polars-ops/src/series/ops/log.rs, crates/polars-ops/src/series/ops/moment.rs, crates/polars-plan/src/dsl/function_expr/datetime.rs, crates/polars-plan/src/dsl/function_expr/temporal.rs, crates/polars-sql/tests/udf.rs, crates/polars-time/src/group_by/dynamic.rs, crates/polars/tests/it/core/date_like.rs, crates/polars/tests/it/core/series.rs, crates/polars/tests/it/lazy/folds.rs, crates/polars/tests/it/lazy/queries.rs, docs/src/rust/user-guide/expressions/folds.rs, py-polars/src/series/arithmetic.rs, py-polars/src/series/mod.rs
This PR makes the ops for `Series` and `ChunkedArray` completely fallible, which allows us to more strictly enforce propagating the error or ignoring it.
This is the first part of #16958.
=> refactor(rust): Make Series and ChunkedArray ops fallible

py-polars/polars/series/series.py, py-polars/tests/unit/series/test_series.py
Closes #17048.
The correct typing for "other" here is `Any` (it can legitimately be almost anything, and we handle the case that it is not a Series internally; fixing this also lets us ditch a few "type: ignore" directives in the unit tests).
=> fix(python): Update some `Series` dunder method type signatures

crates/polars-lazy/src/scan/file_list_reader.rs, crates/polars-plan/src/plans/hive.rs, py-polars/tests/unit/io/test_hive.py
Before:
```python
scan_parquet("data/a=1/**/*.parquet")
shape: (5, 3)
┌─────┬───┬─────┐
│ a   ┆ … ┆ x   │
│ --- ┆   ┆ --- │
│ i64 ┆   ┆ i32 │
╞═════╪═══╪═════╡
│ 1   ┆ … ┆ 1   │
│ 1   ┆ … ┆ 1   │
│ 1   ┆ … ┆ 1   │
│ 1   ┆ … ┆ 1   │
│ 1   ┆ … ┆ 1   │
└─────┴───┴─────┘
```
After:
```python
scan_parquet("data/a=1/**/*.parquet")
┌───┬─────┐
│ … ┆ x   │
│   ┆ --- │
│   ┆ i32 │
╞═══╪═════╡
│ … ┆ 1   │
│ … ┆ 1   │
│ … ┆ 1   │
│ … ┆ 1   │
│ … ┆ 1   │
└───┴─────┘
```
=> feat!: Do not parse hive partitions from user provided directory/glob path

py-polars/pyproject.toml
Ref https://github.com/pola-rs/polars/issues/16998
I should have done this earlier - apologies. I had misjudged the implications here.
To be clear: 
* This will make sure `pip install polars[numpy]` gets you a compatible version.
* If you have NumPy 2.0 installed, you can still `pip install polars` without problems. Polars works with NumPy 2.0 with certain limitations (see linked issue).
=> build(python): Pin optional NumPy dependency to `< 2.0.0` for now

crates/polars-lazy/src/scan/ndjson.rs, crates/polars-mem-engine/src/executors/scan/ndjson.rs, py-polars/tests/unit/io/test_lazy_json.py
This properly expands globs in NDJson into one scan with multiple files.
This also fixes the `n_rows` parameter for DataFrame::scan_ndjson with multiple files.
=> feat: Expand NDJson glob into one SCAN

crates/polars-mem-engine/src/executors/join.rs, crates/polars-ops/Cargo.toml, crates/polars-ops/src/frame/join/args.rs, crates/polars-ops/src/frame/join/asof/groups.rs, crates/polars-ops/src/frame/join/asof/mod.rs, crates/polars-ops/src/frame/join/mod.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/optimizer/projection_pushdown/joins.rs, crates/polars-plan/src/plans/schema.rs, py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/datatypes/test_temporal.py, py-polars/tests/unit/operations/test_join.py, py-polars/tests/unit/operations/test_join_asof.py
Joining on any expression other than `col` will turn off coalescing behavior and will keep all columns of both tables. This also fixes several bugs with regard to accidentally mutating the underlying columns and adding literal expressions to the tables.
fixes #13220
fixes #9621
=> feat: Turn of coalescing and fix mutation of join on expressions

crates/polars-io/src/json/mod.rs, crates/polars-io/src/ndjson/core.rs, crates/polars-io/src/utils.rs, crates/polars-mem-engine/src/executors/scan/ndjson.rs, crates/polars-mem-engine/src/planner/lp.rs, crates/polars-plan/src/plans/conversion/scans.rs, crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs, crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs, py-polars/tests/unit/io/test_lazy_json.py
This PR adds predicate and projection pushdown in NDJson in a similar fashion as is done in CSV. This currently just filters after each chunk is deserialized, which is not perfectly efficient. It would probably be a good idea to do the projection during the `into_series` call and the predicate during the `...ChunkedBuilder` append value.
=> feat: predicate + projection pushdown in NDJson

crates/polars-core/src/frame/mod.rs, crates/polars-io/src/avro/write.rs, crates/polars-io/src/ipc/ipc_stream.rs, crates/polars-io/src/ipc/write.rs, crates/polars-io/src/ipc/write_async.rs, crates/polars-io/src/json/mod.rs, crates/polars-io/src/parquet/write/batched_writer.rs, py-polars/polars/dataframe/frame.py, py-polars/src/dataframe/export.rs
@djouallah created a benchmark with only string columns and calls `to_arrow`. 
Because Polars has adopted the new string-view type, we are conservative and must covert to the old `large-string`. This conversion must move all data. Therefore let's make it parallel.
You can default to `string-view` in pyarrow 16 by setting `to_arrow(future=True)`, but the delta-writer still doesn't support that datatype. https://github.com/delta-io/delta-rs/issues/2613
=> perf: Parallelize arrow conversion if binview -> large_bin

crates/polars-io/src/ipc/write.rs, py-polars/polars/dataframe/frame.py, py-polars/src/dataframe/io.rs, py-polars/tests/unit/io/test_ipc.py
Pyarrow 16 can now correctly read binview data, so let's write them. This allows us to memory map IPC again.
If users want to remain on an older pyarrow they can set  `future=False`.
breaking: `compression` is keyword only.
=> perf: Default to writing binview data to IPC

py-polars/polars/expr/expr.py, py-polars/polars/expr/whenthen.py, py-polars/polars/selectors.py, py-polars/tests/unit/test_selectors.py
We discussed that we find autocomplete very important to work correctly in Polars.
I found that if we don't return `Self`, but explicitly return `Expr` in expression methods, this fixes in Ipython.
I think this is much, much more important than any subclassing we intended to support, so I really want to fix this. It also removed a bunch op `type: ignore`'s.
@alexander-beedie @stinodego @MarcoGorelli FYI/RFC
=> fix(python): Fix expression autocomplete in ipython

crates/polars-core/src/frame/explode.rs, py-polars/tests/unit/operations/test_melt.py
=> fix: Fix melt panic

crates/polars-plan/src/plans/ir/dot.rs, crates/polars-plan/src/plans/ir/format.rs
This PR improves the explanation when calling `explain` or `show_graph` on a scan. It now:
- more neatly formats the paths,
- displays the row_index if it is defined,
- does not count the row_index as a column in the total_columns.
=> feat: print row index in explain + dot

py-polars/docs/source/reference/dataframe/group_by.rst, py-polars/docs/source/reference/lazyframe/group_by.rst, py-polars/docs/source/reference/lazyframe/in_process.rst, py-polars/docs/source/reference/lazyframe/index.rst, py-polars/polars/__init__.py, py-polars/polars/lazyframe/__init__.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/lazyframe/in_process.py
Also remove the top-level re-export. It doesn't need to be re-exported because users do not instantiate it themselves. Similar to `GroupBy`.
=> docs(python): Properly expose `InProcessQuery` in docs, mark as unstable

crates/polars-core/src/chunked_array/ops/bit_repr.rs, crates/polars-core/src/chunked_array/ops/mod.rs, crates/polars-core/src/frame/group_by/into_groups.rs, crates/polars-core/src/series/implementations/categorical.rs, crates/polars-core/src/series/implementations/date.rs, crates/polars-core/src/series/implementations/datetime.rs, crates/polars-core/src/series/implementations/decimal.rs, crates/polars-core/src/series/implementations/duration.rs, crates/polars-core/src/series/implementations/mod.rs, crates/polars-core/src/series/implementations/null.rs, crates/polars-core/src/series/implementations/object.rs, crates/polars-core/src/series/implementations/struct_.rs, crates/polars-core/src/series/implementations/time.rs, crates/polars-core/src/series/series_trait.rs, crates/polars-ops/src/chunked_array/list/hash.rs, crates/polars-ops/src/frame/join/asof/groups.rs, crates/polars-ops/src/frame/join/hash_join/mod.rs, crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs, crates/polars-ops/src/frame/pivot/positioning.rs
This PR refactors the code surrounding bit representations and properly bubbles errors up if no bit representation is defined.
This resolves the panic in #14826, but does not implement the wanted behavior.
I am not sure a test case is useful here as the behavior should be added in the end.
=> fix(rust): bubble error when no available bitrepr

crates/polars-lazy/src/dsl/eval.rs, crates/polars-lazy/src/dsl/list.rs, crates/polars-plan/src/dsl/array.rs, crates/polars-plan/src/dsl/expr_dyn_fn.rs, crates/polars-plan/src/dsl/functions/horizontal.rs, crates/polars-plan/src/dsl/list.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/dsl/name.rs, crates/polars-plan/src/dsl/python_udf.rs, crates/polars-plan/src/plans/aexpr/schema.rs, py-polars/src/map/lazy.rs
Fixes #15444.
This PR makes the `get_field` method of `GetOutput` fallible. Consequently, we can bubble up a lot more errors related to super typing instead of panicking.
Although, I would normally add a test case here. I don't think this PR warrants one as the exact super typing behavior might be changed later.
=> fix: make `GetOutput::get_field` fallible

crates/polars-core/src/frame/group_by/aggregations/mod.rs, py-polars/tests/unit/operations/test_window.py
Fixes https://github.com/pola-rs/polars/issues/17102
=> fix: Fix incorrect window std for chunked series

crates/polars-ops/src/series/ops/replace.rs, crates/polars-plan/src/dsl/function_expr/dispatch.rs, crates/polars-plan/src/dsl/function_expr/mod.rs, crates/polars-plan/src/dsl/function_expr/schema.rs, crates/polars-plan/src/dsl/mod.rs, py-polars/docs/source/reference/expressions/modify_select.rst, py-polars/docs/source/reference/series/computation.rst, py-polars/polars/_utils/udfs.py, py-polars/polars/_utils/various.py, py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/src/expr/general.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/tests/unit/operations/map/test_inefficient_map_warning.py, py-polars/tests/unit/operations/test_replace.py, py-polars/tests/unit/operations/test_replace_strict.py
Closes https://github.com/pola-rs/polars/issues/14302
* Add `replace_strict` method to `Expr` and `Series`. This method is similar to what `replace` was previously, with the exception that it raises an error if any non-null values were not replaced. Specify a `default` to set all values that were not replaced to that default.
* `replace` now always keeps the existing data type - this is a breaking change _(see example below)_. The`default` and `return_dtype` parameters are deprecated. 
**Example**
Before:
```pycon
>>> s = pl.Series([1, 2, 3])
>>> s.replace(1, "a")
shape: (3,)
[
"a"
"2"
"3"
]
```
After:
```pycon
>>> s.replace(1, "a")
...
polars.exceptions.InvalidOperationError: conversion from `str` to `i64` failed in column 'literal' for …
```
=> feat!: Split `replace` functionality into two separate functions

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
Can again confirm that this ensures autocomplete remains working in notebooks.
=> feat(python): Improve ipython autocomplete for LazyFrame and DataFrame

crates/polars-core/src/chunked_array/object/extension/mod.rs, crates/polars-core/src/chunked_array/object/mod.rs, py-polars/polars/__init__.py, py-polars/src/on_startup.rs
Closes https://github.com/pola-rs/polars/issues/16609
Not sure if this is an acceptable fix - feedback welcome.
I couldn't think of a good way to test this 🤔
=> build(python): Do not change environment on import

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
The most upvoted SO Polars question is about drop_duplicates: https://stackoverflow.com/questions/71196661/what-is-the-equivalent-of-dataframe-drop-duplicates-from-pandas-in-polars
Let's insert a cheeky `drop_duplicates` mention so that people can be directed to the Polars equivalent 😎
=> docs(python): Add "coming from pandas" note to `DataFrame.unique` docstring

crates/polars-arrow/src/array/equal/mod.rs, crates/polars-arrow/src/array/fmt.rs, crates/polars-arrow/src/array/mod.rs, crates/polars-arrow/src/io/avro/read/deserialize.rs, crates/polars-arrow/src/scalar/equal.rs, crates/polars-arrow/src/scalar/mod.rs
Closes #16111 
Update primitive match to use ```with_match_primitive_type_full!``` macro instead.
The original ```with_match_primitive_type!``` macro now only remains for the ```polars_arrow::compute::aggregate::sum``` function. This is due to not being able to implement simd_sum for f16 types: https://github.com/rust-lang/rust/issues/116909.
=> fix(rust): Expand i128 primitive type match

crates/polars-lazy/src/frame/pivot.rs, crates/polars-ops/src/frame/pivot/mod.rs, crates/polars/tests/it/core/pivot.rs, docs/releases/upgrade/1.md, docs/src/rust/user-guide/transformations/pivot.rs, py-polars/polars/dataframe/frame.py, py-polars/src/dataframe/general.rs, py-polars/tests/unit/operations/test_pivot.py
closes https://github.com/pola-rs/polars/issues/11592, though using a different solution than suggested - here I'm implementing "if `index` is not specified, use all remaining columns", just as is already done for `values`, as well as for `unpivot`. Related discussion #17095 
I've also rewritten the `pivot` docstring examples, as I think they started off too complicated. It now starts with the simplest case, and then builds up
=> feat: Update `DataFrame.pivot` to allow `index=None` when `values` is set

py-polars/polars/testing/parametric/strategies/core.py, py-polars/tests/unit/testing/parametric/strategies/test_core.py
`size` is rarely used - usually you'll want to pass an upper or lower bound (e.g. `max_size=0` or `min_size=1`). It's not necessary, so let's get rid of it.
=> depr(python): Deprecate `size` parameter in parametric testing strategies in favor of `min_size`/`max_size`

py-polars/Cargo.toml
See https://github.com/pola-rs/polars/commit/5cad69e5d4af47e75ae0abbf88dc2bafbc8f66d2#r143437580, this is causing CI to fail. `dprint` didn't like the formatting, the following was fixed:
* spaces around `workspace = true`
* dependency sections, which can be separated by newlines must be in alphabetical order. `polars-stream` was listed after `polars-utils` which it didn't like.
=> chore: Add missing spaces in `cargo.toml`

py-polars/polars/expr/whenthen.py, py-polars/tests/unit/functions/test_when_then.py
Perhaps it was a miss copy that was confused with Then or ChainedThen.
```python
>>> pl.when(True).then(1).when(True)
File "/home/vscode/.local/lib/python3.9/site-packages/polars/expr/expr.py", line 137, in __repr__
if len(expr_str := self._pyexpr.to_str()) > 30:
AttributeError: 'NoneType' object has no attribute 'to_str'
```
=> fix(python): `ChainedWhen` should not inherit `Expr`

crates/polars-core/src/utils/supertype.rs, crates/polars-plan/src/dsl/functions/concat.rs, crates/polars-plan/src/dsl/functions/correlation.rs, crates/polars-plan/src/dsl/functions/horizontal.rs, crates/polars-plan/src/dsl/functions/range.rs, crates/polars-plan/src/dsl/list.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/plans/conversion/type_coercion/mod.rs, crates/polars-plan/src/plans/optimizer/fused.rs, crates/polars-plan/src/plans/options.rs, py-polars/src/functions/misc.rs, py-polars/tests/unit/operations/test_sets.py
=> fix: Set intersection supertype

crates/polars-compute/src/min_max/dyn_array.rs, crates/polars-compute/src/min_max/mod.rs, crates/polars-parquet/src/arrow/write/primitive/basic.rs
Fixes #16687.
This PR now fully utilizes the MinMaxKernel to calculate the Parquet statistics. Specifically this PR adds this for `PrimitiveArray` which is the majority of values.
=> refactor(rust): MinMaxKernel in prim parquet stats

crates/polars-io/src/predicates.rs, crates/polars-mem-engine/src/executors/scan/parquet.rs, crates/polars-pipe/src/executors/sources/parquet.rs, crates/polars-plan/src/plans/hive.rs, crates/polars-plan/src/plans/ir/mod.rs, crates/polars-plan/src/plans/mod.rs, crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs, crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs, py-polars/tests/unit/io/test_hive.py
Fixes https://github.com/pola-rs/polars/issues/17104, https://github.com/pola-rs/polars/issues/15823 (projection pd)
Fixes https://github.com/pola-rs/polars/issues/17155 (corrupted reads)
=> fix: Fix corrupted reads for hive parts from cloud and projection pushdown failure on hive parts

crates/polars-ops/src/chunked_array/list/sets.rs, py-polars/tests/unit/operations/test_sets.py
=> fix: Raise on invalid set dtypes

crates/polars-lazy/src/frame/mod.rs
I guess there is no reason why something like shouldn't work:
```rust
ldf.sink_parquet("foo.parquet");
```
=> feat(rust): Use AsRef<Path> instead of PathBuf in sink_ methods

crates/polars-lazy/src/tests/io.rs
Adding Ritchie's test from #17131 to the test suite.
I just made a couple of small changes from the one in the issue:
- Instead of comparing the options to `None`, I check that the length of the projection and the slice are correct.
- I added a `with_column` to the query, which I think was causing my original problem.
=> test(rust): Add a test for AnonymousScan options (projection and slice pushdown)

crates/polars-core/src/chunked_array/metadata/collect.rs, crates/polars-core/src/chunked_array/metadata/guard.rs, crates/polars-core/src/chunked_array/metadata/interior_mutable.rs, crates/polars-core/src/chunked_array/metadata/md_trait.rs, crates/polars-core/src/chunked_array/metadata/mod.rs, crates/polars-core/src/chunked_array/mod.rs, crates/polars-core/src/chunked_array/ops/aggregate/mod.rs, crates/polars-core/src/series/implementations/boolean.rs, crates/polars-core/src/series/implementations/floats.rs, crates/polars-core/src/series/implementations/mod.rs, crates/polars-core/src/series/mod.rs, crates/polars-core/src/series/series_trait.rs
This PR illustrates a basic workflow for keeping track of and utilizing metadata. Currently, this is still all behind `POLARS_METADATA_USE=experimental`, but now we can start implementing a lot of places where metadata can be inferred or used.
In this PR, I implemented all the infrastructure necessary to write the metadata from `chunked_array::ops` and to read the metadata from `polars-expr`.
The writing is done using interior mutability. I attempted several approaches and this is the one that I settled on as being the easiest to work with and not providing to much overhead.
The reading is done through a trait object over the `MetadataTrait`, this makes all data available as `Scalar`s.
The follow snippet illustrates that it works.
```python
import os …
```
=> feat(rust): POC metadata reading and writing

crates/polars-compute/src/min_max/dyn_array.rs, crates/polars-compute/src/min_max/mod.rs, crates/polars-compute/src/min_max/scalar.rs, crates/polars-compute/src/min_max/simd.rs, crates/polars-parquet/src/arrow/write/binary/basic.rs
Fixes #16687.
This PR now fully utilizes the MinMaxKernel to calculate the Parquet statistics. Specifically this PR adds this for `PrimitiveArray` and `BinaryArray` which is the majority of values.
=> refactor(rust): MinMaxKernel in primitive/binary parquet stats

crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/nested.rs, crates/polars-parquet/src/parquet/encoding/byte_stream_split/decoder.rs, crates/polars-parquet/src/parquet/encoding/byte_stream_split/mod.rs, crates/polars-parquet/src/parquet/encoding/mod.rs, py-polars/tests/unit/io/test_parquet.py
Fixes #17042 
This PR adds support for reading Parquet files with float or double values that are encoded with the byte stream split encoding. I started out using the changes in https://github.com/jorgecarleitao/parquet2/pull/221, but refactored the way the decoder worked to avoid needing to change the State enums for the basic and nested PrimitiveDecoder structs too much (I think these would have at least needed extra type parameters for the ParqueNativeType and converter function).
Version 2.11 of the Parquet format extended the byte stream split encoding to be valid for integer types and fixed length byte arrays, motivated by the addition of the float16 logical type which uses a 2-byte fixed length byte array physical type. But it looks like Polars doesn't support reading float16 data …
=> feat: Support reading byte stream split encoded floats and doubles in parquet

crates/polars-sql/src/functions.rs, crates/polars-sql/src/sql_expr.rs, py-polars/docs/source/reference/sql/functions/array.rst, py-polars/tests/unit/sql/test_array.py
* Adds SQL support for array subscript notation[^1] (in addition to existing `ARRAY_GET`).
* Fixes array indexing to match SQL, eg: `arr[0]` → `NULL` (as SQL is 1-indexed, this array position is out of bounds).
* New test coverage for additional SQL array functions.
(Note that, unlike PostgresSQL, we _do_ support negative array indexing).
Using subscript notation:
```python
pl.sql(
"""
SELECT
arr[0] AS a0,
arr[1] AS a1,
arr[2] AS a2,
arr[3] AS a3,
arr[-1] AS am1,
arr[-2] AS am2,
arr[-3] AS am3,
arr[-4] AS am4,
FROM (SELECT [99,66,33] AS arr) tbl
"""
).collect()
```
Using `ARRAY_GET`:
```python
pl.sql(
"""
SELECT
ARRAY_GET(arr, 0) AS a0,
ARRAY_GET(arr, 1) AS a1,
ARRAY_GET(arr, 2) AS a2,
ARRAY_GET(arr, 3) AS a3,
ARRAY_GET(arr, -1) AS am1,
ARRAY_GET(arr, -2) AS am2, …
```
=> feat: Improve SQL support for array indexing, increase test coverage

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/dataframe/test_df.py
Closes #17170.
* Adds an optional "default" param to `DataFrame.get_column`; provides some additional usability in a few cases.
* This method is analogous to `dict.get`, which allows for the same sort of behaviour, but instead of returning None if no default is actively specified we will continue to raise.
Note: existing behaviour is entirely unchanged _unless_ the new parameter is invoked.
```python
"foo": [1, 2, 3],
"bar": [4, 5, 6],
})
```
Without `default` (existing/standard behaviour):
```python
res = df.get_column("baz")
```
With (optional) use of `default`:
```python
if (srs := df.get_column("baz", default=None)) is not None:
do_some_stuff(srs)
```
```python
default_baz = pl.Series("baz",["?","?","?"])
df.get_column("baz", …
```
=> feat(python): Add optional "default" to `get_column` DataFrame method

docs/requirements.txt, docs/src/python/user-guide/expressions/structs.py, docs/src/python/user-guide/expressions/user-defined-functions.py, py-polars/docs/requirements-docs.txt, py-polars/tests/docs/test_user_guide.py
New pydata theme version is out, which solves an issue that blocked us from upgrading for a long time. So, time for an update!
Also fixes a warning during doc build.
=> docs(python): Bump docs dependencies

crates/polars-time/src/chunkedarray/string/mod.rs
Ref https://github.com/chronotope/chrono/pull/588
This is a minor clean up to address a TODO. The current version of `chrono` has `ParseErrorKind` as a public enum. Hence, `polars-time` no longer needs to define its own enum and use `std::mem::transmute` to convert between the two types
=> refactor(rust): `chrono`'s ParseErrorKind is now public

docs/user-guide/installation.md, py-polars/polars/dataframe/frame.py, py-polars/pyproject.toml, py-polars/requirements-dev.txt
Credit to @alexander-beedie for the initial work in https://github.com/pola-rs/polars/pull/17064
Closes https://github.com/pola-rs/polars/issues/17143
* Breaking:
* `fastexcel` group was renamed to `calamine` to align with the engine name in the API.
* `async` group now installs `gevent` instead of `nest-asyncio`. The `gevent` group was removed. `nest-asyncio` is installed as part of the new `database` group.
* `matplotlib` group was renamed to `graph`, since it enables the `LazyFrame.show_graph` functionality.
* Non-breaking:
* `adbc` and `plot` group now also install pandas/pyarrow, which are required for them to work.
* New groups `excel` and `database` install all the engines for their respective functionality.
Here's the logic by which the new extras group structure was constructed: …
=> build(python)!: Streamline optional dependency definitions in `pyproject.toml`

py-polars/polars/_utils/construction/dataframe.py, py-polars/polars/_utils/construction/series.py, py-polars/polars/datatypes/__init__.py, py-polars/polars/datatypes/_parse.py, py-polars/polars/datatypes/classes.py, py-polars/polars/datatypes/convert.py, py-polars/polars/expr/expr.py, py-polars/polars/expr/string.py, py-polars/polars/io/csv/batched_reader.py, py-polars/polars/io/csv/functions.py, py-polars/polars/io/database/_inference.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/series/series.py, py-polars/tests/unit/constructors/test_constructors.py, py-polars/tests/unit/constructors/test_dataframe.py, py-polars/tests/unit/datatypes/test_parse.py, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/test_datatypes.py, py-polars/tests/unit/test_errors.py
Ref https://github.com/pola-rs/polars/issues/13117
Refactoring the logic that parses dtype inputs to a Polars data type, for example in the `Series` constructor.
This is towards improving the logic and consistently applying it across the API.
=> refactor(python): Refactor parsing of data type inputs to Polars data types

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py
Looks like I hadn't added `unstable` the first time round, sorry - adding it now then
=> docs(python): mark .plot property as unstable

crates/polars-plan/src/dsl/function_expr/strings.rs
Closes #17195
I think this should fix the issue of `regex` being imported when the feature is not used.
=> fix(rust): Avoid using the regex dependency when the regex feature is not used

crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/utils.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/decode.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/mod.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/unpack.rs, crates/polars-parquet/src/parquet/encoding/delta_bitpacked/decoder.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/decoder.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs, crates/polars/tests/it/io/parquet/read/binary.rs, crates/polars/tests/it/io/parquet/read/fixed_binary.rs, crates/polars/tests/it/io/parquet/read/primitive.rs, crates/polars/tests/it/io/parquet/read/primitive_nested.rs, crates/polars/tests/it/io/parquet/read/struct_.rs, crates/polars/tests/it/io/parquet/read/utils.rs
This PR performs several optimization surrounding the HybridRLE decoding:
- A lot of iterators in favor of collecting and buffering
- Flatten nested iterators into a single iterators
- Remove many memcopies in `bitpacked::decode`.
Overall, my microbenchmarks showed an improvement of roughly 10x for the HybridRLE decoding. In order to get a better view on how to much impact this has on totality of parquet decoding I did a benchmark using the Yellow NYC Taxi dataset. This got me a roughly 1.8x speed-up for general parquet decoding.
=> perf(rust): faster decode on Parquet HybridRLE

py-polars/tests/unit/dataframe/test_serde.py, py-polars/tests/unit/expr/test_serde.py, py-polars/tests/unit/lazyframe/test_serde.py, py-polars/tests/unit/test_serde.py
Ref https://github.com/pola-rs/polars/issues/17108
=> test(python): Refactor serde tests, add hypothesis tests

crates/polars-core/src/serde/chunked_array.rs, crates/polars-core/src/serde/series.rs, py-polars/tests/unit/dataframe/test_serde.py, py-polars/tests/unit/lazyframe/test_serde.py
This was previously unimplemented, which led to a panic. Now it works!
=> feat: Implement serde for Null columns

crates/polars-core/src/frame/top_k.rs, crates/polars-lazy/src/frame/mod.rs, py-polars/tests/unit/operations/test_top_k.py
Fixes https://github.com/pola-rs/polars/issues/17165.
=> fix: top_k directly on dataframes

crates/polars-expr/src/expressions/mod.rs, crates/polars-expr/src/expressions/slice.rs, py-polars/tests/unit/operations/test_group_by.py
=> fix: Fix literal slice in group by

crates/polars-expr/src/expressions/sortby.rs, py-polars/tests/unit/operations/aggregation/test_aggregations.py
Fixes #17243.
From the issue example:
```python
"a": [1, 10, 9, 3, 2, 4, 7, 5, 6, 8, None, None],
"b": [1, 2, 3, 1, 4, 2, 3, 3, 2, 1, 1, 2],
})
pl.Config.set_tbl_rows(12)
print(df.select(pl.all().sort_by("a", nulls_last=True).over("b")))
```
```
shape: (12, 2)
┌──────┬─────┐
│ a    ┆ b   │
│ ---  ┆ --- │
│ i64  ┆ i64 │
╞══════╪═════╡
│ 1    ┆ 1   │
│ 4    ┆ 2   │
│ 5    ┆ 3   │
│ 3    ┆ 1   │
│ 2    ┆ 4   │
│ 6    ┆ 2   │
│ 7    ┆ 3   │
│ 9    ┆ 3   │
│ 10   ┆ 2   │
│ 8    ┆ 1   │
│ null ┆ 1   │
│ null ┆ 2   │
└──────┴─────┘
```
=> fix: respect `nulls_last` parameter in aggregate `sort_by`

py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/src/lazyframe/visitor/nodes.rs
Explicitly handle the options and hive partitioning in scans. I decided to use the serde-based serialization for the type-specific options in `Scan` rather than laboriously writing a translation for the options structs. 
Question: does this need to be gated behind `#[cfg(all(feature = "json", feature = "serde_json"))]`? I think it's reasonable to require those features for the IR translation to function, but if we don't think so, I do stuff by hand.
Additionally, build out a bit more of the expression translation. The major one is that `IRAggExprs` now hold a `Vec<Node>` rather than a single `Node` as arguments, since `Quantile` takes two expressions.
=> feat(rust): Expose some more information in translated expression IR to python

crates/polars-core/src/datatypes/_serde.rs, py-polars/polars/_utils/serde.py, py-polars/polars/dataframe/frame.py, py-polars/polars/expr/expr.py, py-polars/polars/expr/meta.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/type_aliases.py, py-polars/src/dataframe/general.rs, py-polars/src/dataframe/io.rs, py-polars/src/dataframe/mod.rs, py-polars/src/dataframe/serde.rs, py-polars/src/expr/general.rs, py-polars/src/expr/meta.rs, py-polars/src/expr/mod.rs, py-polars/src/expr/serde.rs, py-polars/src/lazyframe/mod.rs, py-polars/src/lazyframe/serde.rs, py-polars/tests/unit/dataframe/test_serde.py, py-polars/tests/unit/expr/test_serde.py, py-polars/tests/unit/lazyframe/test_serde.py
Closes https://github.com/pola-rs/polars/issues/17108
* Add `format` parameter to the `serialize/deserialize` methods on `DataFrame/LazyFrame/Expr` with the options `"json"` (existing) and `"binary"` (new).
* Set `"binary"` as the default format. This is a breaking change. You can retain the previous behavior by specifying `format="json"`
**Example**
Before:
```pycon
>>> lf = pl.LazyFrame({"a": [1, 2, 3]}).sum()
>>> serialized = lf.serialize()
>>> serialized
'{"MapFunction":{"input":{"DataFrameScan":{"df":{"columns":[{"name":...'
>>> from io import StringIO
>>> pl.LazyFrame.deserialize(StringIO(serialized)).collect()
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 6   │
└─────┘
```
After:
```pycon
>>> lf = pl.LazyFrame({"a": [1, 2, 3]}).sum()
>>> serialized = lf.serialize()
>>> …
```
=> feat(python)!: Implement binary serialization of LazyFrame/DataFrame/Expr and set it as the default format

py-polars/polars/testing/parametric/profiles.py, py-polars/polars/testing/parametric/strategies/core.py, py-polars/polars/testing/parametric/strategies/data.py, py-polars/polars/testing/parametric/strategies/dtype.py, py-polars/polars/testing/parametric/strategies/legacy.py
There is quite some fine-tuning needed still - I don't want to be constrained by the existing API.
I don't think there are a _lot_ of people out there using this functionality. Plus, it's purely for testing code, so changes here are not going to break production pipelines.
So let's mark these as unstable for now to make improvements easier.
Note: I did not make these raise an `UnstableWarning` on use because it's testing functionality and raising warnings from testing utils might disturb the testing suite.
=> docs(python): Mark hypothesis testing functionality as unstable

crates/polars-io/src/csv/read/buffer.rs, crates/polars-io/src/csv/read/mod.rs, crates/polars-io/src/options.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/hive.rs, py-polars/polars/io/parquet/functions.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_hive.py
Resolves https://github.com/pola-rs/polars/issues/12894
=> feat: Support date/datetime for hive parts

crates/polars-sql/src/functions.rs, crates/polars-sql/src/sql_expr.rs, crates/polars-time/src/chunkedarray/string/mod.rs, crates/polars-time/src/chunkedarray/string/patterns.rs, py-polars/docs/source/reference/sql/functions/aggregate.rst, py-polars/docs/source/reference/sql/functions/math.rst, py-polars/docs/source/reference/sql/functions/string.rst, py-polars/docs/source/reference/sql/functions/temporal.rst, py-polars/tests/unit/operations/namespaces/test_strptime.py, py-polars/tests/unit/sql/test_array.py, py-polars/tests/unit/sql/test_conditional.py, py-polars/tests/unit/sql/test_numeric.py, py-polars/tests/unit/sql/test_regex.py, py-polars/tests/unit/sql/test_strings.py, py-polars/tests/unit/sql/test_temporal.py
Improves the slightly sparse temporal SQL support with some key functions.
* Added support for `STRFTIME` (temporal → string)
* Added support for `STRPTIME` (string → temporal)
* Added support for temporal "typed literal" syntax for, eg: 
`SELECT DATETIME '2077-07-05 10:30:45'`
`SELECT DATE '2077-07-05'`
`SELECT TIME '10:30:45'`
* New SQL doc entries and test coverage for all of the above.
* Closes #17093 (introducing `TIMESTAMP` and `DATETIME` to join the existing `DATE`).
* Improved our default `Time` inference patterns to account for fractional seconds.
* Improved SQL _"invalid number of argument"_ error messages by additionally including how many arguments were actually expected.
`STRFTIME`:
```python
pl.DataFrame({
"dtm": [None, datetime(1980, 9, 30, 1, 25, 50)],
"dt": [date(1978, 7, …
```
=> feat: Support `SQL` temporal functions `STRFTIME` and `STRPTIME`, and typed literal syntax

crates/polars-sql/src/context.rs, py-polars/tests/unit/sql/test_structs.py, py-polars/tests/unit/sql/test_wildcard_opts.py
Following on from #17109, which added `RENAME` and `REPLACE` modifiers:
* Added support for the `SELECT * ILIKE …`  wildcard select-modifier[^1]. 
This is a pattern-match on column names, using SQL "%" and "_" glob chars. 
* Fixed interaction of `ORDER BY` and `REPLACE` modifier (should sort on post-replace values).
* Fixed use of ordinal values with `ORDER BY` clause if _also_ using `SELECT * EXCLUDE`.
* Improved use of `ORDER BY` on columns targeted by `RENAME` modifier.
* Some code refactoring/consolidation to improve clarity around select-modifiers.
* Extended select-modifier unit tests to cover additional permutations/combinations of modifiers.
With this final addition, we will support _all_ `SELECT *` wildcard modifiers for the 1.0 🎉 
```
SELECT * EXCLUDE …
SELECT * ILIKE …
SELECT * …
```
=> feat: Support SQL `SELECT * ILIKE` wildcard syntax

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_operators.py, py-polars/tests/unit/sql/test_strings.py
Adds support for the following PostgreSQL string matching operators [^1]:
* `^@`: "starts with" 
* `~~`: "like"
* `~~*`: "ilike"
* `!~~`: "not like"
* `!~~*`: "not ilike"
```python
"x": ["aaa", "bbb", "a"],
"y": ["abc", "b", "aa"],
})
```
```python
df.sql("""
SELECT
x,
x ^@ 'a' AS x_starts_with_a,
x ~~* '%B' AS x_ends_with_b
FROM self
""")
```
```python
df.sql("""
SELECT
x,
y,
x ^@ y AS x_starts_with_y
x ~~ '%a' AS x_ends_with_a
FROM self
""")
```
[^1]: https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-LIKE
=> feat: Support PostgreSQL `^@` ("starts with"), and `~~`,`~~*`,`!~~`,`!~~*` ("like", "ilike") string-matching operators

crates/polars-sql/src/context.rs, py-polars/tests/unit/sql/test_group_by.py, py-polars/tests/unit/sql/test_order_by.py
Continuing the recent onslaught of modern/friendly SQL syntax support...
* `SELECT * FROM df ORDER BY ALL`
This syntax automatically orders by _all_ columns found in the final selection[^1]. 
Can also apply `DESC` and `NULLS FIRST/LAST` modifiers, which get broadcast to all columns in the sort.
This query...
```python
pl.sql("""
SELECT a, b, c, d, e, f, g FROM df
ORDER BY 
a DESC NULLS LAST, 
b DESC NULLS LAST, 
c DESC NULLS LAST,
d DESC NULLS LAST, 
e DESC NULLS LAST, 
f DESC NULLS LAST,
g DESC NULLS LAST
""")
```
...can now be written much more succinctly as:
```python
pl.sql("""
SELECT a, b, c, d, e, f, g FROM df 
ORDER BY ALL DESC NULLS LAST
""")
```
[^1]: **Note:** if an actual column called "ALL" (irrespective of case) is present, that is prioritised.
=> feat: Support SQL `ORDER BY ALL` syntax

crates/polars-io/src/cloud/glob.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/scan/file_list_reader.rs, crates/polars-lazy/src/scan/ipc.rs, crates/polars-lazy/src/scan/parquet.rs, crates/polars-mem-engine/src/executors/scan/ipc.rs, crates/polars-mem-engine/src/executors/scan/parquet.rs, py-polars/tests/unit/conftest.py, py-polars/tests/unit/io/test_scan.py
Resolves https://github.com/pola-rs/polars/issues/17105
=> feat: Exclude directories from glob expansion result

crates/polars-sql/src/keywords.rs, crates/polars-sql/src/sql_expr.rs, crates/polars-sql/tests/simple_exprs.rs, py-polars/tests/unit/sql/test_structs.py
Builds on #17109, which added support for querying into Struct fields using dot-notation.
In addition to that, this PR adds the PostgreSQL operator versions[^1].
Can use for both array and field indexing.
* `-> ` Extract value at key/index.
* `->>` Extract value at key/index, as a string.
* `#> ` Extract value at specified path, where path elements can be keys or indexes.
* `#>>` Extract value at specified path, where path elements can be keys or indexes, as a string.
Unlike standard array-indexing in PostgreSQL, which is 1-indexed, these operators expect 0-indexing as they follow JSON conventions, so the following two queries are equivalent (and both now parse):
* `df.sql('SELECT nested."0"[1] FROM self')`
* `df.sql("SELECT nested -> '0' -> 0 FROM self")`
_"Yay for consistency"_ 🙄 …
=> feat: Support `SQL` Struct/JSON field access operators

crates/polars-arrow/src/legacy/kernels/list.rs, py-polars/tests/unit/operations/test_gather.py
=> fix: Don't oob on nulls in `list.get`

crates/polars-arrow/src/array/fixed_size_list/ffi.rs, crates/polars-arrow/src/ffi/array.rs, py-polars/tests/unit/io/test_parquet.py
This fixes the slicing behavior of FixedSizeLists when loaded with PyArrow. I am not sure if this behavior is also faulty at other places (I especially suspect structs), but as long as there are no reported problems there I think this fix is okay for now.
Fixes #16614.
=> fix: deal with sliced PyArrow record batches

crates/polars-compute/src/unique/boolean.rs, crates/polars-compute/src/unique/mod.rs, crates/polars-compute/src/unique/primitive.rs, crates/polars-core/src/chunked_array/ops/unique/mod.rs, crates/polars-parquet/src/arrow/write/boolean/basic.rs
This PR adds a unique value kernel that is selected based on the metadata for `PrimitiveArray`. When the difference between the metadata min and max value is small enough a different kernel is used that does not require sorting the data first.
This is mostly to show how the new metadata can be used to select a different kernel.
For a microbenchmark on release mode, we see the following results:
```python
xs = list(np.random.randint(5, 100, size = 500000))
df = pl.DataFrame({ "x": xs, }, schema = { "x": pl.Int32 })
def rand_unique():
df.select(pl.col.x.unique())
t = timeit(rand_unique, number = 10000)
print(f'Before Time = {t}')
df.select(xmin = pl.col.x.min(), xmax = pl.col.x.max())
t = timeit(rand_unique, number = 10000) …
```
=> perf: add RangedUniqueKernel for primitive array

crates/polars-plan/src/dsl/function_expr/list.rs, py-polars/tests/unit/operations/test_gather.py
Followup to #17262, closes #17252. Fixes the column idx case.
Added more test coverage.
=> fix: Don't null on oob in `list.get` for column index

crates/polars-plan/Cargo.toml
Closes #17204
The feature `approx_n_unique` doesn't exist, I guess it was removed.
=> docs(rust): Fix polars-plan docs.rs build

crates/polars-io/src/cloud/glob.rs, crates/polars-io/src/cloud/options.rs, py-polars/tests/unit/io/test_hive.py
This allows us to scan datasets written by pyarrow that are patitioned on datetime columns, as pyarrow `%`-encodes the colons
=> feat: Support '%' in pathnames for async scan

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/io/database/test_write.py
Closes #17293.
Extant ADBC connections were implicitly closed in `write_database` via context manager; fixed, and added coverage.
=> fix(python): Ensure we don't close extant `adbc` connections in `write_database`

py-polars/docs/source/reference/lazyframe/miscellaneous.rst, py-polars/polars/dataframe/frame.py, py-polars/polars/io/csv/functions.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/io/test_parquet.py, py-polars/tests/unit/lazyframe/test_lazyframe.py
Closes #17267.
Removes a long-standing footgun ... 👌 
---
Double-checking if we want to deprecate, or if we should make it a breaking change to clean things up for the 1.0 (in which case we can just add the breaking tag and merge). Given its status as a debug-only function that already has warnings on it, this probably isn't unreasonable - by definition it can't be used in production workflows 🤔
**Update**: deprecation it is!
=> depr(python): Make debug `fetch` function private

py-polars/polars/io/spreadsheet/functions.py, py-polars/polars/selectors.py, py-polars/tests/unit/io/test_spreadsheet.py
Closes https://github.com/pola-rs/polars/issues/17177
* Set `"calamine"` as the default engine for `read_excel` for all file types, instead of only for `.xlsb` and `.xls`.
* Added a common `columns` parameter that can constrain _which_ columns are returned (ref: #17265).
```python
pl.read_excel(file_path, columns=["ColA","ColC","ColE"])
```
=> feat(python)!: Change default engine for `read_excel` to `"calamine"`

py-polars/docs/source/reference/selectors.rst
More pleasant table layout, and gave _"exclusive or"_ its proper name in set terminology of _"symmetric difference"_.
=> docs: Minor layout/terminology improvement for `selector` set ops

Cargo.lock, crates/polars-parquet/Cargo.toml, crates/polars-parquet/src/parquet/encoding/bitpacked/mod.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/pack.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/unpack.rs
After looking for a long time at how to SIMD this bitpacking, I am pausing for a bit to work on something else. There are some code deletions, namely removing the unused u8 and u16 implementations of bit(un)packing. This also removes the `seq_macro` crate.
Maybe, I will look at this again in the future.
=> refactor(rust): remove seqmacro and u8,u16 bitpack

py-polars/polars/dataframe/group_by.py
=> perf(python): Rechunk before groups iter

_typos.toml, crates/polars-ops/src/chunked_array/strings/find_many.rs, crates/polars-plan/src/dsl/function_expr/strings.rs, crates/polars-plan/src/dsl/string.rs, py-polars/docs/source/reference/expressions/string.rst, py-polars/docs/source/reference/series/string.rst, py-polars/polars/expr/string.py, py-polars/polars/series/string.py, py-polars/src/expr/string.rs, py-polars/src/lazyframe/visitor/expr_nodes.rs, py-polars/tests/unit/operations/namespaces/string/test_string.py
=> feat: Add `str.extract_many` expression

crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/operations/test_cross_join.py
=> fix: raise if keys passed to cross join

docs/releases/upgrade/1.md
Closes https://github.com/pola-rs/polars/issues/16773
=> docs(python): Finish upgrade guide for 1.0.0

crates/polars-io/src/parquet/read/async_impl.rs, crates/polars-parquet/src/arrow/write/row_group.rs, crates/polars-parquet/src/parquet/compression.rs, crates/polars-parquet/src/parquet/error.rs, crates/polars-parquet/src/parquet/read/compression.rs, crates/polars-parquet/src/parquet/read/page/reader.rs, crates/polars-parquet/src/parquet/read/page/stream.rs, crates/polars-parquet/src/parquet/schema/types/spec.rs
There are mixed uses of `ParquetError::oos` and `ParquetError::OutOfSpec` where it would just be clearer to pick one. So I favored the convenience constructor that saves a few keystrokes. I didn't make changes to the tests because that requires making `pub fn oos(..)` and I am not sure if people want that API to be exposed. If we made that change, there would be a few dozen more references cleaned up.
(This is my first commit to Polars - I'm doing some minor refactors to get my bearings so I can implement some improvements I need at work)
=> Refactor: Prefer ParquetError::oos to ParquetError::OutOfSpec

crates/polars-pipe/src/executors/sinks/output/file_sink.rs, crates/polars-pipe/src/pipeline/dispatcher/mod.rs, py-polars/tests/unit/streaming/test_streaming_io.py
=> fix: Raise errors instead of panicking when `sink_csv` fails

crates/polars-sql/src/context.rs, crates/polars-sql/src/functions.rs, crates/polars-sql/src/sql_expr.rs, crates/polars-sql/tests/statements.rs, py-polars/docs/source/reference/sql/clauses.rst, py-polars/tests/unit/sql/test_joins.py
* Adds `NATURAL [INNER|LEFT|FULL] JOIN`[^1] support for the SQL interface (this flavour of join automatically uses the common cols between the two tables as the join-key), and the associated SQL docs entries/examples.
* Partial implementation of the useful DuckDB `COLUMNS`[^2] function; this maps almost 1:1 onto Polars' `col` expression, enabling use of regular expressions to select multiple columns. Also offers some (currently limited) broadcasting capabilities; at the moment broadcasting support only works in the `WHERE` clause.
* Ensure `SQLFunctionVisitor` translations also have access to the current/active schema.
* Some refactoring, with more to come later. Some of the logic is getting quite involved, and could do with more inline comments, explanations and additional cleanups. …
=> feat: Add SQL support for `NATURAL` joins and the `COLUMNS` function

crates/polars-mem-engine/src/executors/projection_utils.rs, py-polars/tests/unit/operations/test_window.py
=> fix: Fix panic in window case

py-polars/docs/source/_static/version_switcher.json
**DO NOT MERGE**
This should be merged right before the final `1.0.0`.
It will set the `1.0.0` docs as the stable version in the version dropdown.
=> docs(python): Update version switcher for 1.0.0 final release

crates/polars-arrow/src/datatypes/schema.rs, crates/polars-core/src/schema.rs, crates/polars-io/src/parquet/read/reader.rs, crates/polars-io/src/utils.rs, crates/polars-mem-engine/src/executors/scan/parquet.rs, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-pipe/src/executors/sources/parquet.rs, crates/polars-plan/src/plans/conversion/scans.rs, crates/polars-plan/src/plans/functions/count.rs, py-polars/tests/unit/io/test_lazy_parquet.py
This has been reported quite a bit lately, so got around to it
Fixes https://github.com/pola-rs/polars/issues/13436, fixes https://github.com/pola-rs/polars/issues/17067, fixes https://github.com/pola-rs/polars/issues/17255, fixes https://github.com/pola-rs/polars/issues/13438
Maybe also https://github.com/pola-rs/polars/issues/17311, but I don't have a repro for that one
=> fix: Raise proper error for mismatching parquet schema instead of panicking

crates/polars-core/src/series/comparison.rs, py-polars/tests/unit/test_errors.py
Just a typo in the `SchemaError` message.
=> fix: Fix typo in `SchemaError` exception message

py-polars/polars/dataframe/group_by.py
Closes https://github.com/pola-rs/polars/issues/17376
This should have been updated in https://github.com/pola-rs/polars/pull/16793 - my mistake!
=> docs(python): Update `GroupBy.__iter__` docstring to match new behavior

py-polars/polars/series/series.py, py-polars/src/series/export.rs
There is a `future` argument in `DataFrame.to_arrow`, but it is missing in `Series.to_arrow`. This PR adds it. `Series.to_arrow` is used in `pyo3-polars`, and using `future=True` significantly improve its performance for e.g. string series.
=> perf(python): add future arg to Series.to_arrow

crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs, py-polars/tests/unit/io/test_scan.py
=> fix(rust): Cull row index in scan if projection pushdown removes it

crates/polars-plan/src/plans/conversion/type_coercion/mod.rs, py-polars/tests/unit/expr/test_exprs.py
=> fix: Fix `slice` length no longer allowing `None`

py-polars/tests/unit/operations/map/test_map_batches.py, py-polars/tests/unit/operations/map/test_map_groups.py, py-polars/tests/unit/test_errors.py
Splitting this off from the other PR just to separate concerns.
=> test(python): Avoid use of `np.trapz` in tests to prepare for NumPy 2.0

Cargo.lock, docs/requirements.txt, py-polars/Cargo.toml, py-polars/docs/requirements-docs.txt, py-polars/pyproject.toml, py-polars/requirements-dev.txt
Closes https://github.com/pola-rs/polars/issues/16998
* Pin the `numpy` crate in Cargo.toml to a git commit that includes NumPy 2.0 support. The git commit is based on https://github.com/PyO3/rust-numpy/pull/429 and includes a minor fix to enable Windows support.
* Remove `< 2.0.0` version constraint for NumPy dependency
We are dependent on the `numpy` crate for NumPy support. There is a PR open that adds NumPy 2.0 support, however, it is still in review. We understand that reviews in open source take time, since we are open source maintainers ourselves. However, due to the great impact on our users, we elect to build Polars based off of that PR. This passes our full test suite, both on NumPy 1.26 and 2.0.
=> build(python): Add support for NumPy 2.0

crates/polars-plan/src/plans/optimizer/projection_pushdown/projection.rs, py-polars/tests/unit/test_projections.py
When the schema of a frame is empty, a count expression is still valid since it does not refer to any columns. In this scenario, selecting the "last" column in the schema would previously panic, since there are none. Fix this by handling this edge case explicitly.
- Closes #16904
=> fix(rust): avoid panic when projecting solitary count into empty frame

crates/polars-io/src/ipc/mmap.rs, crates/polars-io/src/mmap.rs, py-polars/src/dataframe/io.rs, py-polars/src/file.rs, py-polars/src/functions/io.rs, py-polars/tests/unit/io/test_ipc.py
If a Python file object is passed as the argument of IO functions (e.g. `read_*` & `write_*`), currently it is wrapped into a `PyFileLikeObject`, and each read & write will acquire the GIL and call into Python, which is inefficient. This PR introduces a improvement that extracts the underlying fd through `fileno()` and opens the fd as a Rust `File`, which does not require GIL and have better performance.
=> perf(python): Use underlying fileno for Python files when possible

crates/polars-io/src/cloud/object_store_setup.rs, crates/polars-io/src/file_cache/utils.rs, crates/polars-io/src/ipc/ipc_reader_async.rs, crates/polars-io/src/parquet/read/async_impl.rs, crates/polars-lazy/src/scan/file_list_reader.rs
See https://github.com/apache/arrow-rs/issues/5993#issuecomment-2205840396
Turns out there was a function I missed to do this
=> refactor: Remove transmute for object store path

crates/polars-mem-engine/src/executors/scan/parquet.rs
Deserializing wide parquet metadata is expensive. This ensures we do it in parallel.
closes #17259
@nameexhaustion FYI.
=> perf: Parallelize parquet metadata deserialization

py-polars/polars/sql/context.py, py-polars/tests/unit/sql/test_miscellaneous.py
Closes #17398.
Simple fix, though a better one would be having the underlying parser analyse the statement properly; I'll look into doing that at a later date (am on vacation at the moment ;)
=> fix(python): Fix a global variable table-discovery edge case for the `SQL` interface

py-polars/polars/_utils/construction/utils.py, py-polars/tests/unit/interop/numpy/test_numpy.py, py-polars/tests/unit/interop/test_from_pandas.py, py-polars/tests/unit/interop/test_interop.py
Closes https://github.com/pola-rs/polars/issues/17355
* No longer allow going through NumPy for columns of type `object` if the column contains missing values. The PyArrow path is used instead.
@MarcoGorelli FYI
=> fix(python): Fix `from_pandas` for string columns with missing values

.github/pr-title-checker-config.json, .github/workflows/pr-labeler.yml, docs/development/contributing/index.md
Pull request titles require a valid tag in order to determine in which changelog and which section they should be included. The text that follows is included in the changelog directly.
This means that PR titles must be formatted correctly, otherwise the changelog is useless.
Unfortunately I spend more time than I am comfortable with editing people's pull request titles to make sure the changelog makes sense and looks OK. I have previously posted a PSA with some guidance on the Discord channel, which helped, but not enough.
So I'm taking out the big guns: regex 😄 
A simple check will make sure pull requests have the right formatting, otherwise the CI will fail and the PR will be labelled `title needs formatting`. If you check out the failed job, it will link you to relevant section of the …
=> ci: Add automated check for PR title formatting

crates/polars-io/src/hive.rs, crates/polars-io/src/ipc/ipc_file.rs, crates/polars-io/src/lib.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-io/src/parquet/read/utils.rs, crates/polars-lazy/src/scan/ipc.rs, crates/polars-lazy/src/tests/io.rs, crates/polars-mem-engine/src/executors/scan/ipc.rs, crates/polars-mem-engine/src/executors/scan/mod.rs, crates/polars-mem-engine/src/planner/lp.rs, crates/polars-plan/src/plans/builder_dsl.rs, py-polars/polars/io/ipc/functions.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_hive.py
Resolves https://github.com/pola-rs/polars/issues/14885
=> feat: Support hive partitioning in `scan_ipc`

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/io/database/test_write.py
https://github.com/pola-rs/polars/issues/17432#issue-2391646360
=> fix(python): Support sa session

.github/workflows/test-python.yml, py-polars/polars/dataframe/frame.py, py-polars/src/file.rs, py-polars/tests/unit/io/test_csv.py
Fixes "write to closed file" in `write_csv`:
```python
>>> df.write_csv(open("test.csv", "w"))
OSError: write to closed file
```
=> fix(python): Fix handling of TextIOWrapper in write_csv

crates/polars-core/src/chunked_array/cast.rs, crates/polars-core/src/datatypes/dtype.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> fix: Raise on oob decimal precision

py-polars/polars/io/spreadsheet/functions.py, py-polars/tests/unit/io/test_spreadsheet.py
Closes #17407.
Fixes `calamine` and `xlsx2csv` boolean reads, adding multi-engine test coverage.
=> fix(python): Make boolean reads consistent across all `read_excel` engines

crates/polars-core/src/series/mod.rs, py-polars/tests/unit/operations/test_gather.py
=> fix: Don't rechunk on phys_repr

crates/polars-arrow/src/bitmap/utils/iterator.rs, crates/polars-arrow/src/legacy/utils.rs, crates/polars-arrow/src/pushable.rs, crates/polars-arrow/src/trusted_len.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/boolean/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs, crates/polars-parquet/src/arrow/read/deserialize/utils.rs, crates/polars-parquet/src/parquet/encoding/bitpacked/decode.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/buffered.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/fuzz.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/translator.rs, crates/polars/tests/it/io/parquet/read/binary.rs, crates/polars/tests/it/io/parquet/read/fixed_binary.rs, crates/polars/tests/it/io/parquet/read/primitive.rs, crates/polars/tests/it/io/parquet/read/primitive_nested.rs, crates/polars/tests/it/io/parquet/read/struct_.rs, crates/polars/tests/it/io/parquet/read/utils.rs
This is rather large change that changes quite fundamentally how HybridRLE and Parquet decoding works. There are now two important concepts that speed up the performance of the Parquet reader while utilizing less memory than before. This does how increase the complexity of the code.
First, for a benchmark using the NYC Yellow-Taxi dataset (we decode the whole dataset 100x). Here, we see the following results.
No maximum threads:
```
Benchmark 1: After Optimization
Time (mean ± σ):      4.918 s ±  0.076 s    [User: 28.748 s, System: 2.486 s]
Range (min … max):    4.819 s …  5.064 s    10 runs
Benchmark 2: Before Optimization
Time (mean ± σ):      7.333 s ±  2.144 s    [User: 60.374 s, System: 3.054 s]
Range (min … max):    5.416 s … 11.132 s    10 runs
Summary
After Optimization ran
1.49 ± …
```
=> perf: Batch parquet primitive decoding

py-polars/polars/_utils/construction/dataframe.py, py-polars/tests/unit/interop/test_from_pandas.py
In the issue #16025 , the author converts a pandas dataframe who's columns are 0 and '0'. In polars dataframes, this is illegal, as all the column names are converted to strings. This is done in the pl.from_pandas, but the conversion happens in a way that overwrites a prior column. For example, if 0 and '0' are columns, the '0' will overwrite the first column, since that column was converted first, to a '0'.
I check the uniqueness of the stringified names in `from_pandas`. This should also catch some unusual column names, like arbitrary objects with __str__ methods.
I did change the behavior of `test_from_pandas_duplicated_columns` in `test_interop`. The test now raises the error message I wrote since the duplicate columns were caught earlier. I understand this may be undesirable since …
=> fix(python): Verify the integrity of pandas column names before implied string conversion

crates/polars-plan/src/plans/optimizer/cache_states.rs
=> perf: Keep more parallelism when CSE plan cache hits

crates/polars-core/src/utils/supertype.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> fix: Fix decimal dyn float supertype

py-polars/polars/io/database/_inference.py
Closes #17466.
Not all drivers adhere to the DBAPI2 standard[^1] for the cursor description; the standard specifies exactly 7 attributes, but MariaDB's native driver (and possibly others, though no reports of such yet) returns more.
Trivial fix to handle the additional params.
[^1]: https://peps.python.org/pep-0249/#cursor-attributes
=> fix(python): Handle DB cursor descriptions that contain more fields than the DBAPI2 standard

docs/user-guide/getting-started.md
=> docs: Fix typo in Getting Started section of user guide

py-polars/polars/lazyframe/frame.py
=> fix(python): Normalize path in `sink_csv`

py-polars/polars/dataframe/frame.py, py-polars/tests/unit/io/database/test_write.py
`pandas` supports `sa.engine.Connectable`.
Passing `sa.engine.Connectable` allows the user to control the transaction.
=> feat(python): Support use of SQLAlchemy "Connectable" in `write_database`

crates/polars-core/src/serde/series.rs, py-polars/src/dataframe/serde.rs, py-polars/src/expr/serde.rs, py-polars/src/lazyframe/serde.rs, py-polars/tests/unit/dataframe/test_serde.py, py-polars/tests/unit/lazyframe/test_serde.py
These are not supported by design, so it should throw a nice error.
=> fix: Turn panic into error when serializing Object types

crates/polars-io/src/cloud/glob.rs, crates/polars-lazy/src/scan/file_list_reader.rs, py-polars/tests/unit/io/test_scan.py
Fixes https://github.com/pola-rs/polars/issues/17362
Empty files/objects are now excluded from both directory and glob expansion.
=> feat: Exclude empty files from directory/glob expansion

crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/scan/file_list_reader.rs, crates/polars-lazy/src/scan/ipc.rs, crates/polars-lazy/src/scan/ndjson.rs, crates/polars-lazy/src/scan/parquet.rs, py-polars/tests/unit/io/test_scan.py
If the user passes a single directory to a `scan_*` function, we will now check that all files underneath it have the same file extension. If this is not the case an error message is raised showing the offending paths and recommending to use glob patterns if they still wish to scan all files.
Combining this with https://github.com/pola-rs/polars/pull/17478 will also make it so that file extensions of empty files are ignored.
Fixes https://github.com/pola-rs/polars/issues/17436
=> feat: Raise more informative error message for directories containing files with mixed extensions

py-polars/polars/dataframe/frame.py
Ensures that the `style` namespace does not get overridden
=> chore(python): Add `style` accessor to `DataFrame`

.github/CODEOWNERS, py-polars/src/lazyframe/visitor/expr_nodes.rs
Easy issue with "untyped" code, sorry! (cc @MarcoGorelli)
I also added myself as codeowner for the python IR subsystem: so that I get a heads up when things are changing (cc @ritchie46)
=> fix(rust): Add missing commas in python IR interchange

py-polars/polars/lazyframe/frame.py
Just a missing 'right' in the `how :` part of the lazyframe join docstring
=> fix(python): Add right to lazyframe join docstring

crates/polars-arrow/src/bitmap/utils/iterator.rs, crates/polars-io/src/cloud/object_store_setup.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/dictionary.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/utils.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/dictionary.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/boolean/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-parquet/src/arrow/read/deserialize/null/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/utils.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/translator.rs
This PR is a follow up to #17462. This batches the collects in the nested Parquet decoders, with that we can also simplify the code quite a lot.
I did a benchmark where we had one column `{ 'x': pl.List(pl.Int8) }` of length `10_000_000`. Then, we read that Parquet file 50 times. Here are the results.
```
Benchmark 1: After Optimization
Time (mean ± σ):      3.398 s ±  0.064 s    [User: 49.412 s, System: 4.362 s]
Range (min … max):    3.311 s …  3.490 s    10 runs
Benchmark 2: Before Optimization
Time (mean ± σ):      4.135 s ±  0.015 s    [User: 59.506 s, System: 5.234 s]
Range (min … max):    4.105 s …  4.149 s    10 runs
Summary
After Optimization ran
1.22 ± 0.02 times faster than Before Optimization
```
The nested decoder is still relatively inefficient, but this is a step in the …
=> perf: Batch nested Parquet decoding

crates/polars-parquet/src/arrow/read/deserialize/binary/utils.rs, crates/polars-parquet/src/arrow/read/deserialize/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-parquet/src/arrow/read/deserialize/struct_.rs
This continues on #17542 and now also batches the actual Nesting, not only the top decoder.
I did the same benchmark with `POLARS_MAX_THREADS=1` and we again see a small speedup. But I suspect that the speedup is larger for `FixedSizeList`s and `Struct`s.
```
Benchmark 1: After Optimization
Time (mean ± σ):     13.306 s ±  0.018 s    [User: 12.661 s, System: 0.614 s]
Range (min … max):   13.263 s … 13.335 s    10 runs
Benchmark 2: Before Optimization
Time (mean ± σ):     14.973 s ±  0.065 s    [User: 14.422 s, System: 0.517 s]
Range (min … max):   14.887 s … 15.129 s    10 runs
Summary
After Optimization ran
1.13 ± 0.01 times faster than Before Optimization
```
=> perf: Batch nested embed parquet decoding

crates/polars-io/src/cloud/glob.rs, crates/polars-io/src/cloud/options.rs, crates/polars-io/src/file_cache/utils.rs, crates/polars-io/src/utils/path.rs, crates/polars-plan/src/plans/conversion/scans.rs
Closes https://github.com/pola-rs/polars/issues/17567
=> fix: Fix scanning from HTTP cloud paths

crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/filter.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs, crates/polars-parquet/src/parquet/deserialize/filtered_rle.rs
This PR removes a lot of the crazy stuff that was being done in the Parquet reader for primitive decoding. This should also make it quite easy to add `Filter` to other decoders.
=> refactor(rust): Smaller filter / valid in Parquet

crates/polars-io/src/parquet/read/read_impl.rs
Closes https://github.com/pola-rs/polars/issues/17565
Closes https://github.com/pola-rs/polars/issues/16915
=> fix: Don't unwrap send attempt to oneshot channel

crates/polars-core/src/chunked_array/ops/sort/mod.rs
=> fix(rust): Correct logic for descending sort of BooleanChunked

crates/polars-expr/src/expressions/apply.rs, crates/polars-io/src/predicates.rs, py-polars/tests/unit/io/test_hive.py
Fixes https://github.com/pola-rs/polars/issues/14712
=> perf: Support datetime in predicate during hive partition pruning

crates/polars-core/src/series/implementations/decimal.rs, crates/polars-core/src/series/mod.rs, py-polars/tests/unit/datatypes/test_decimal.py
=> feat: Support `describe` on decimal

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py, py-polars/tests/unit/functions/test_business_day_count.py
the deprecation isn't currently rendering
also, drive-by, by `parse_version` parses a string as a tuple of ints - it would be better to just construct the tuple of ints directly
=> docs(python): Fixup "deprecated" directive for `DataFrame.melt` and `LazyFrame.melt`

py-polars/pyproject.toml, py-polars/tests/unit/interchange/test_roundtrip.py, py-polars/tests/unit/io/database/test_async.py, py-polars/tests/unit/io/database/test_read.py
Closes #17487.
Adds/tweaks some version-gating for a couple of tests.
* One test should have been gated on the Pandas version, but was using the Python version to imply this instead.
* Also, there's still a large SQLAlchemy 1.x install base (and it has been updated independently of 2.x as recently as March), so allowing tests to run with both versions is worthwhile (we still run it in a few places at work, for example, due to some otherwise incompatible drivers).
=> test(python): Add/fix version-gating in some SQLAlchemy and Pandas tests

crates/polars-time/src/truncate.rs, py-polars/polars/expr/datetime.py, py-polars/polars/series/datetime.py, py-polars/tests/unit/operations/namespaces/temporal/test_truncate.py
=> fix: Method dt.truncate was sometimes returning incorrect results for pre-1970 datetimes

crates/polars-io/src/ipc/ipc_file.rs, crates/polars-io/src/parquet/read/read_impl.rs, crates/polars-io/src/parquet/read/reader.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/scan/ipc.rs, crates/polars-lazy/src/scan/ndjson.rs, crates/polars-lazy/src/scan/parquet.rs, crates/polars-lazy/src/tests/io.rs, crates/polars-mem-engine/src/executors/scan/csv.rs, crates/polars-mem-engine/src/executors/scan/ipc.rs, crates/polars-mem-engine/src/executors/scan/parquet.rs, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-pipe/src/executors/sources/parquet.rs, crates/polars-plan/src/plans/builder_dsl.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/optimizer/cache_states.rs, crates/polars-plan/src/plans/optimizer/mod.rs, crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs, crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs, crates/polars-plan/src/plans/options.rs, py-polars/polars/io/csv/functions.py, py-polars/polars/io/ipc/functions.py, py-polars/polars/io/parquet/functions.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_scan.py
Closes https://github.com/pola-rs/polars/issues/10481
This introduces an `include_file_paths` parameter, which accepts a column name to use for the column storing the file path.
```python
pl.scan_csv(
["https://j.mp/iriscsv", ".env/iris.csv"], include_file_paths="path"
).collect()
shape: (300, 6)
┌──────────────┬─────────────┬──────────────┬─────────────┬───────────┬─────────────────────────────────┐
│ sepal_length ┆ sepal_width ┆ petal_length ┆ petal_width ┆ species   ┆ path                            │
│ ---          ┆ ---         ┆ ---          ┆ ---         ┆ ---       ┆ ---                             │
│ f64          ┆ f64         ┆ f64          ┆ f64         ┆ str       ┆ str                             │
╞══════════════╪═════════════╪══════════════╪═════════════╪═══════════╪═══════ …
```
=> feat: Add option to include file path for Parquet, IPC, CSV scans

py-polars/src/file.rs
This is a minor fix for #17315.
Both Python and Rust set O_CLOEXEC for opened files. However, `dup` clears this flag. This PR uses `F_DUPFD_CLOEXEC` to explicitly make dupped fd non-inheritable.
=> fix(python): Set `O_CLOEXEC` on duplicated file descriptor

py-polars/polars/io/database/functions.py
Closes #17534; nested bullets not rendering properly on VSCode (and no real need for them).
=> docs(python): Adjust rendering of links in `read_database_uri` docstring

py-polars/polars/schema.py, py-polars/tests/unit/test_schema.py
fixes #17523 
during unpickling, an instance of `Schema` is instantiated without passing the `schema` argument. In this case, we should create an empty Schema instead of erroring.
=> fix(python): Make schema picklable

crates/polars-arrow/src/bitmap/utils/iterator.rs, py-polars/tests/unit/io/test_parquet.py
Fixes #17579.
This fixes a regression in #17542. This now properly checks the safety within the `BitmapIter::collect_n_into`. This was sloppy on my end and it is now much better tested.
=> fix: Bitmap collect into safety

py-polars/tests/unit/sql/test_joins.py, py-polars/tests/unit/streaming/test_streaming.py, py-polars/tests/unit/streaming/test_streaming_join.py
Hi Polars team, while working on the GPU backend I encountered a few join tests that seem to rely on the order of rows returned by the join to pass, where the docs only indicate a particular ordering for left joins. This PR proposes some minor changes to the py-polars test suite that drop this as a pass condition in the places I encountered it. Hopefully I've not missed any obvious ones here, let me know if so.
=> fix(python): Don't enforce row order in join test results where not guaranteed

crates/polars-arrow/src/compute/concatenate.rs, crates/polars-arrow/src/offset.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/utils.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/boolean/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/dictionary/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/filter.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/buffered.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/gatherer.rs, crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs, py-polars/tests/unit/io/test_parquet.py
This PR completely redoes the Parquet read/deserialize workings, removing all the combinatorics and trait objects. After this, I want to remove the rest of the iterators and remove even more abstraction layers.
=> refactor: Completely redo structure of Parquet decoder

py-polars/src/lazyframe/mod.rs
This does not seem to be referenced anywhere.
=> refactor(python): Remove unused `with_column` method of PyLazyFrame

crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/tests/queries.rs, crates/polars-lazy/src/tests/streaming.rs, crates/polars-lazy/src/tests/tpch.rs, crates/polars-sql/src/context.rs, crates/polars-sql/tests/ops_distinct_on.rs, crates/polars-sql/tests/simple_exprs.rs, crates/polars/src/docs/lazy.rs, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/dataframe/test_df.py
=> fix(rust!, python): Reject literal input in `sort_by_exprs()`

crates/polars-plan/src/plans/aexpr/schema.rs, py-polars/polars/datatypes/_parse.py, py-polars/polars/expr/expr.py, py-polars/tests/unit/test_schema.py
=> feat: Expose `returns_scalar` to map_elements

crates/polars-lazy/src/scan/ndjson.rs, crates/polars-plan/src/plans/builder_dsl.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/conversion/mod.rs, crates/polars-plan/src/plans/mod.rs
This will ensure that a program like this:
```python
inital_q = my_lazy_frame_q...
for expr in my_exprs:
result = initial_q.filter(expr).collect()
```
Will only resolve the schema of initial_q once. And subsequent loops will have resolved schema.
@stinodego this is similar to the path resolving case.
=> perf: Cache schema resolve back to DSL

crates/polars-core/src/frame/mod.rs, crates/polars-io/src/partition.rs, py-polars/src/dataframe/io.rs
=> perf: Rechunk before we go into grouped gathers

crates/polars-io/src/ndjson/core.rs, py-polars/tests/unit/io/test_scan.py
Fixes https://github.com/pola-rs/polars/issues/17553
Also add NDJSON to some parametric tests
=> fix: Fix row index disappearing after projection pushdown in NDJSON

crates/polars-io/src/cloud/glob.rs, crates/polars-io/src/utils/path.rs, py-polars/tests/unit/io/test_scan.py
Fixes https://github.com/pola-rs/polars/issues/17629
=> fix: Expand brackets in async glob expansion

py-polars/polars/io/csv/functions.py, py-polars/tests/unit/io/test_csv.py
=> feat(python): Add `infer_schema` parameter to `read_csv` / `scan_csv`

py-polars/polars/_utils/construction/dataframe.py, py-polars/tests/unit/interop/test_from_pandas.py
Hi Polars team, this pr does 3 main things. First, it solves for #15938 and #16023 , by checking the stringified index names for overlap w/column names. Second, it solves for duplicated index names, post string conversion. For example, an index of 0 and '0' would not be caught without this explicit check. Third, I combine this logic with the code I wrote for issue #16025 , because I considered this all a part of the same general problem.
I altered some unit tests to include the new error message, two of which I already altered for my pr on #16025 . I wrote/borrowed a new unit test that was written directly from the desired behavior in #15938 .
Let me know if you need anything else. I'd love for any feedback on the code, if there's anything you'd change.
Thank you.
=> fix(python): Raise for overlapping index/column names in pandas dataframes post string coercion

crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs, crates/polars-plan/src/utils.rs, py-polars/tests/unit/operations/test_join.py
After discussion in #17184:
- Reject multiple join key expressions if they are not all elementwise
- Emit UserWarning if a coalescing join is requested but not all key expressions are column references, in which case the coalescing behaviour is turned off.
=> fix(rust): Tighten up error checking on join keys

crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/dictionary.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/simple.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/array_chunks.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs, crates/polars-parquet/src/parquet/types.rs
This increases visibility and allows for better control of inlining.
From the first commit we get the following benchmark.
```
Benchmark 1: After Optimization
Time (mean ± σ):     18.095 s ±  0.135 s    [User: 10.459 s, System: 7.564 s]
Range (min … max):   17.976 s … 18.412 s    10 runs
Benchmark 2: Before Optimization
Time (mean ± σ):     20.863 s ±  0.041 s    [User: 13.129 s, System: 7.648 s]
Range (min … max):   20.794 s … 20.918 s    10 runs
Summary
After Optimization ran
1.15 ± 0.01 times faster than Before Optimization
```
=> perf: Add `ArrayChunks` to optimize codegen of BatchDecoder

crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/scan/ndjson.rs, crates/polars-plan/src/plans/builder_dsl.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/conversion/mod.rs, crates/polars-plan/src/plans/mod.rs, py-polars/tests/unit/io/test_lazy_csv.py
Closes https://github.com/pola-rs/polars/issues/17584
* Update the `DslPlan` after resolving paths. This avoids re-resolving the paths upon repeated `collect` calls on the same LazyFrame.
=> perf: Cache path resolving of `scan` functions

crates/polars-expr/src/expressions/sortby.rs
=> perf: Fix pathological perf issue in window-order-by

crates/polars-core/src/frame/explode.rs, py-polars/tests/unit/operations/test_explode.py
=> fix: Fix explode invalid check

crates/polars-error/src/lib.rs, crates/polars-lazy/Cargo.toml, crates/polars-lazy/src/prelude.rs, crates/polars-plan/Cargo.toml, crates/polars-plan/src/client/dsl.rs, crates/polars-plan/src/client/mod.rs, crates/polars-plan/src/lib.rs, crates/polars/Cargo.toml, py-polars/Cargo.toml, py-polars/polars/_utils/cloud.py, py-polars/src/cloud.rs, py-polars/src/lib.rs, py-polars/tests/unit/cloud/test_assert_cloud_eligible.py
@stinodego @c-peters here is the skeleton for the DSL cloud validation
=> refactor: Add DSL validation for cloud eligible check

crates/polars-io/Cargo.toml, crates/polars-io/src/cloud/glob.rs, crates/polars-io/src/path_utils/hugging_face.rs, crates/polars-io/src/path_utils/mod.rs
This should allow us to scan Parquet, CSV and IPC from `hf://`
```python
r = pl.scan_parquet(
"hf://datasets/roneneldan/TinyStories/data/train-00000-of-00004-2d5a1467fff1081b.parquet"
).head(1)
print(r.collect())
r = pl.scan_parquet(
"hf://datasets/roneneldan/TinyStories@~parquet/default/train/*.parquet"
).head(1)
print(r.collect())
r = pl.scan_csv("hf://datasets/fka/awesome-chatgpt-prompts/*.csv")
print(r.collect())
```
ref https://github.com/pola-rs/polars/issues/17625
=> feat: Hugging Face path expansion

crates/polars-time/src/chunkedarray/string/strptime.rs, py-polars/tests/unit/operations/namespaces/temporal/test_to_datetime.py
closes #17213 
Personally I don't think the cutoff should be configurable (for a start, Chrono doesn't make it configurable, so there'd be no way to control what happens when the Chrono parser is used)
The Polars docs already point to the Chrono docs, so I think that's sufficient (I've also made a PR to chrono to note the cutoff in their docs https://github.com/chronotope/chrono/pull/1598)
This is one of those borderline bugfix / breaking changes that I think would be better suited to 1.2 than to 1.1.1. At the same time, I don't think it's significant enough that it warrants waiting until 2.0
=> fix: Interpret %y consistently with Chrono in to_date/to_datetime/strptime

py-polars/polars/expr/expr.py, py-polars/tests/unit/interop/numpy/test_ufunc_expr.py
=> fix(python): Support duplicate expression names when calling ufuncs

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py
This PR fixes this [issue](https://github.com/pola-rs/polars/issues/17660)
=> docs(python): Fixed default name for `value_counts` methods based on normalize parameter

crates/polars-plan/src/plans/ir/dot.rs
Under some circumstances, compiling Polars failed with a type inference error involving `openssl::error::ErrorStack`. It was possibly related to compiling with libssl-dev. This PR fixes that issue by removing a nasty double `transpose`. A nice side effect is that the problematic code has become a lot cleaner.
=> fix(rust): Fix type inference failure caused by double transpose

crates/polars-core/src/utils/mod.rs, crates/polars-lazy/src/scan/ndjson.rs, crates/polars-mem-engine/src/executors/scan/ndjson.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, py-polars/polars/io/ndjson.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_scan.py
ref https://github.com/pola-rs/polars/issues/10481
=> feat: Include file path option for NDJSON

.github/workflows/release-python.yml, py-polars/polars/_cpu_check.py
This PR makes use of standard x86 microarhitecture levels[^1] for `target-cpu` instead of manually specified `target-features` when building the release wheels. This brings the following benefits:
- Consistent with the standard: Many Linux distros, e.g. openSUSE[^2] and CachyOS[^3], use x86 microarhitecture levels when compiling optimized versions of packages. Using standard levels better aligns with the downstream packaging.
- Reduce maintain burden: No need to define and update[^4] a list of features. Each level includes all supported features. 
- Performance improvement: Setting `target-cpu` implies `tune-cpu`, while setting `target-features` does not. e.g., `target-cpu=x86-84-v3` enables tuning for those v3 cpu models[^5].
This PR uses:
- `x86-64-v3` for normal release; it includes …
=> perf(python): Specify tune-cpu & add more features

crates/polars-compute/src/if_then_else/view.rs, crates/polars-core/src/frame/explode.rs, crates/polars-ops/src/chunked_array/strings/extract.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/dictionary.rs, crates/polars-parquet/src/arrow/read/statistics/mod.rs, py-polars/tests/unit/interop/test_from_pandas.py, py-polars/tests/unit/operations/test_is_in.py, py-polars/tests/unit/operations/test_sort.py
Looks like there's a repeat of https://github.com/pola-rs/polars/issues/6316 😛 
Drive-by: use `MutablePlString` instead of `MutableBinaryViewArray::<str>`
=> test: Name tests so they actually run

py-polars/polars/io/database/_executor.py, py-polars/polars/io/database/functions.py, py-polars/tests/unit/io/database/test_read.py
Closes #17404.
Fixes an issue with Arrow-aware drivers that don't support exact batch sizes (so far this only means Snowflake, but the fix is generic). Also allows the same drivers to skip setting a dummy "batch_size" value.
=> fix(python): Address `read_database` issue with batched reads from Snowflake

py-polars/requirements-dev.txt
CI runs have been failing:
* Test Python / test-python (windows-latest, 3.12) (pull_request)
* Code coverage / coverage-python (pull_request)
It's something to do with the setuptools upgrade, but unsure of the exact cause.
```python
=================================== FAILURES ===================================
______________________________ test_tracebackhide ______________________________
[gw1] darwin -- Python 3.12.4 /Users/runner/work/polars/polars/.venv/bin/python3
/Users/runner/work/polars/polars/py-polars/tests/unit/testing/test_assert_frame_equal.py:411: in test_tracebackhide
result.assert_outcomes(passed=0, failed=4)
/Users/runner/work/polars/polars/.venv/lib/python3.12/site-packages/_pytest/pytester.py:568: in parseoutcomes
return self.parse_summary_nouns(self.outlines) …
```
=> build(python): Pin `setuptools` to fix failing CI

docs/src/python/user-guide/misc/arrow.py, docs/user-guide/misc/arrow.md, mkdocs.yml, py-polars/polars/__init__.py, py-polars/polars/interchange/__init__.py, py-polars/polars/series/series.py, py-polars/src/series/c_interface.rs
Library maintainers can interface with Polars/Arrow directly without requiring pyarrow.
=> feat(python): Expose Arrow C interface directly on Polars

crates/polars-core/src/datatypes/any_value.rs
A `todo!()` was used in the wildcard scenario for the serialize method. Replaced it with panic so that the method is useable
=> feat: Raise error instead of panic in unsupported serde

Cargo.lock, crates/polars-parquet/Cargo.toml, crates/polars-parquet/src/arrow/read/deserialize/utils/array_chunks.rs, crates/polars-parquet/src/parquet/types.rs
=> fix: Use bytemuck in slice reinterpret for Parquet ArrayChunks

crates/polars-io/src/parquet/read/mmap.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/dictionary.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs, crates/polars-parquet/src/arrow/read/deserialize/null/mod.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs, crates/polars-parquet/src/arrow/read/row_group.rs, crates/polars-parquet/src/arrow/write/dictionary.rs, crates/polars-parquet/src/arrow/write/utils.rs, crates/polars-parquet/src/parquet/page/mod.rs, crates/polars-parquet/src/parquet/read/column/mod.rs, crates/polars-parquet/src/parquet/read/compression.rs, crates/polars-parquet/src/parquet/read/mod.rs, crates/polars-parquet/src/parquet/read/page/indexed_reader.rs, crates/polars-parquet/src/parquet/read/page/memreader.rs, crates/polars-parquet/src/parquet/read/page/mod.rs, crates/polars-parquet/src/parquet/read/page/reader.rs, crates/polars-parquet/src/parquet/read/page/stream.rs, crates/polars-parquet/src/parquet/write/compression.rs, crates/polars-parquet/src/parquet/write/page.rs, crates/polars/tests/it/io/parquet/read/mod.rs, crates/polars/tests/it/io/parquet/write/binary.rs, crates/polars/tests/it/io/parquet/write/indexes.rs, crates/polars/tests/it/io/parquet/write/mod.rs, crates/polars/tests/it/io/parquet/write/primitive.rs
This PR introduces three structures:
- `MemReader`: Abstraction over part of a Parquet file loaded into memory
- `MemReaderSlice`: A slice of a `MemReader`. This should should not be kept around outside the Parquet crate.
- `CowBuffer`: A Cow that abstracts between a `MemReaderSlice` and a `Vec<u8>`.
Following this PR, we can avoid copying the memory around in the Parquet crate. This also allows us to guarantee that the memory is in RAM and does not need to be loaded from disk anymore. Leading to less page faults.
Later it might be useful to make the reads a bit more granular so that we don't need to load unnecessary data pages.
=> perf: Introduce `MemReader` to file buffer in Parquet reader

crates/polars-io/src/partition.rs, crates/polars-io/src/path_utils/hugging_face.rs, crates/polars-io/src/utils/mod.rs
This allows us to scan paths with special characters from Hugging Face (e.g. datetime-partitioned hive data)
=> fix: Percent encode for Hugging Face paths

crates/polars-lazy/src/scan/ndjson.rs, crates/polars-mem-engine/src/executors/scan/ndjson.rs, crates/polars-mem-engine/src/planner/lp.rs, crates/polars-plan/src/plans/conversion/dsl_to_ir.rs, crates/polars-plan/src/plans/conversion/scans.rs, crates/polars-plan/src/plans/file_scan.rs, crates/polars-plan/src/plans/functions/count.rs, py-polars/polars/io/ndjson.py, py-polars/src/lazyframe/mod.rs, py-polars/src/lazyframe/visitor/nodes.rs, py-polars/tests/unit/io/test_lazy_count_star.py, py-polars/tests/unit/io/test_scan.py
It is quite a common format, especially in LLM datasets
=> feat: Cloud support for NDJSON

.github/workflows/release-python.yml
cc @orlp 
It turns out the `cc` crate does not pass `target-features` and `tune-cpu` to the C compiler, as a result the C dependencies do not benefit from these tunings. This PR workarounds this by setting `CFLAGS` accordingly.
=> perf(python): Also set target features and tune cpu for CC

docs/_build/API_REFERENCE_LINKS.yml, docs/src/python/user-guide/io/hugging-face.py, docs/user-guide/io/hugging-face.md, docs/user-guide/io/index.md, mkdocs.yml
this needs https://github.com/pola-rs/polars/pull/17717
=> docs(python): Add Hugging Face section to user guide

crates/polars-io/src/pl_async.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/dsl/python_udf.rs, crates/polars-plan/src/plans/options.rs, crates/polars-stream/src/async_executor/mod.rs, crates/polars-stream/src/execute.rs, crates/polars-stream/src/morsel.rs, crates/polars-stream/src/nodes/select.rs, crates/polars-stream/src/physical_plan/lower_ir.rs, crates/polars-stream/src/physical_plan/mod.rs, crates/polars-stream/src/physical_plan/to_graph.rs, crates/polars-stream/src/skeleton.rs
You still need to manually compile with `new_streaming` feature turned on, but now when environment variable `POLARS_AUTO_NEW_STREAMING=1` is set Polars will first try to enter the new streaming engine and only when that panics with an unimplemented error it will try the normal choice of engine. Any panics which are not the `todo!()` error are propagated as real errors.
=> refactor(rust): Add the capability to run new streaming engine on test suite

crates/polars-core/src/chunked_array/struct_/mod.rs, crates/polars-core/src/series/from.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix: Fix out nullability for structs coming from arrow

crates/polars-core/src/series/ops/reshape.rs, py-polars/tests/unit/functions/as_datatype/test_concat_list.py, py-polars/tests/unit/test_empty.py
Fixes https://github.com/pola-rs/polars/issues/16519
Fixes https://github.com/pola-rs/polars/issues/16924
ref https://github.com/pola-rs/polars/issues/15208 (fix one of repro panics), still wrong.
=> fix: Panic in pl.concat_list and list.concat on empty inputs

crates/polars-arrow/src/io/ipc/write/common.rs
#17627 changed the logic of `maybe_gc()`, which was used in `write_ipc()`. GC might not be performed for arrays with multiple references when writing ipc files, which could result in huge files. This PR fixes it. `write_ipc()` now decide whether to gc or not based on `total_bytes_len()` and `total_buffer_len()`.
=> fix(rust,python): Fix GC logic in `write_ipc`

crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs, crates/polars-parquet/src/arrow/read/deserialize/binary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/binview/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/boolean/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/nested.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs, crates/polars-parquet/src/arrow/read/deserialize/primitive/nested.rs
=> chore: Rename Unit to Plain in Parquet reader

py-polars/polars/series/series.py
`_import_from_c` is mainly used by pyo3 extensions. This PR makes its deprecate message more informative.
=> chore(python): Better deprecate message for _import_from_c

crates/polars-plan/src/dsl/functions/coerce.rs, py-polars/polars/functions/as_datatype.py, py-polars/src/functions/lazy.rs, py-polars/tests/unit/datatypes/test_struct.py
=> fix: Raise empty struct

crates/polars-expr/src/planner.rs
=> fix: Don't panic in invalid agg_groups

crates/polars-plan/src/dsl/functions/horizontal.rs, crates/polars-plan/src/dsl/mod.rs, crates/polars-plan/src/plans/conversion/expr_expansion.rs, crates/polars-plan/src/plans/options.rs, py-polars/tests/unit/datatypes/test_struct.py, py-polars/tests/unit/test_empty.py, py-polars/tests/unit/test_errors.py
=> fix: Check funtion input len at expansion

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_is_first_last_distinct.py
=> feat(python): Expose 'strict' argument to 'is_in'

py-polars/polars/functions/as_datatype.py, py-polars/tests/unit/datatypes/test_struct.py
Resolves #16509
The fix seem very simple. I added a test that shows the (imho) expected behavior.
=> fix(python): Simultaneous usage of `named_expr` and `schema` in `pl.struct`

crates/polars-io/src/path_utils/mod.rs
This functionality requires we send 1 HEAD request per path in a serial manner - this can be extremely slow if the user provides a list of cloud file paths. This PR makes it so that an explicit trailing slash must be given if you want to scan from a cloud directory. This matches the behavior of the AWS CLI and improves performance.
=> perf: Remove async directory auto-detection

py-polars/polars/expr/expr.py
Closes #17658
I think this is a useful addition as:
- this is the best way to call non-ufuncs from numpy/scipy that take more than 1 argument
- it is something that may not be immediately obvious to beginners on how to do
=> docs(python): Add function with multiple arguments example to `Expr.map_batches`

crates/polars-plan/src/plans/optimizer/cse/cse_expr.rs, py-polars/tests/unit/test_cse.py
We should have avoided broadcasting the newly introduced temporary CSE
expressions in the HStack rewrite rule, as well as the Select rewrite
rule. Previously we only did the latter.
- Closes https://github.com/pola-rs/polars/issues/17732
=> fix(rust): Correctly set should_broadcast flag in HStack CSE rewrite

crates/polars-lazy/src/dsl/functions.rs, crates/polars-lazy/src/frame/mod.rs, crates/polars-lazy/src/scan/csv.rs, crates/polars-lazy/src/scan/ipc.rs, crates/polars-lazy/src/scan/parquet.rs, crates/polars-lazy/src/tests/predicate_queries.rs, crates/polars-plan/src/frame/opt_state.rs, crates/polars-plan/src/plans/builder_dsl.rs, crates/polars-plan/src/plans/optimizer/mod.rs, py-polars/src/functions/misc.rs, py-polars/src/lazyframe/mod.rs
=> perf: Use bitflags for OptState

crates/polars-plan/src/plans/optimizer/collapse_and_project.rs, crates/polars-plan/src/plans/optimizer/projection_pushdown/joins.rs, py-polars/tests/unit/test_projections.py
=> perf: Ensure only nodes that are not changed are cached in collapse optimizer

py-polars/polars/expr/expr.py, py-polars/polars/series/series.py, py-polars/tests/unit/operations/test_is_first_last_distinct.py
=> Revert "feat(python): Expose 'strict' argument to 'is_in'"

crates/polars-parquet/src/arrow/write/schema.rs, crates/polars-parquet/src/parquet/schema/types/converted_type.rs, py-polars/tests/unit/io/test_parquet.py
=> fix(rust): Non-compliant Parquet list element name

_typos.toml, crates/polars-plan/src/dsl/string.rs, py-polars/src/lazyframe/mod.rs
This is how `typos` can be configured to prevent hiding future typos.
Found new typos 🎁
=> ci: Make better use of `typos` configuration features

crates/polars-io/src/path_utils/mod.rs, crates/polars-io/src/utils/other.rs, crates/polars-lazy/src/scan/ndjson.rs, crates/polars-plan/src/plans/conversion/scans.rs, crates/polars-plan/src/plans/options.rs, crates/polars-utils/src/io.rs, py-polars/polars/io/csv/functions.py, py-polars/polars/io/ipc/functions.py, py-polars/polars/io/ndjson.py, py-polars/src/lazyframe/mod.rs, py-polars/tests/unit/io/test_csv.py
For CSV and IPC, only `hf://` paths are dispatched to their `scan_*` equivalents. They can't dispatch for all paths as it would cause a breaking change to `storage_options` as they currently use `fsspec`, which uses different configuration keys. For CSV as well there is also the issue of compressed files.
`read_ndjson` doesn't suffer from the above issues, so I've added the full set of parameters from `scan_ndjson` and set it to always dispatch to `scan_ndjson`.
=> feat: Support `hf://` in  `read_(csv|ipc|ndjson)` functions

py-polars/docs/source/reference/series/attributes.rst
Closes https://github.com/pola-rs/polars/issues/17640
Example before
Example after (consistent with `DataFrame` and `LazyFrame` docs)
=> docs(python): Show return type for Series attributes in API reference

py-polars/polars/_utils/cloud.py, py-polars/tests/unit/cloud/test_prepare_cloud_plan.py
Minor followup to https://github.com/pola-rs/polars/pull/17802 - I forgot to add a test / update the docstring when addressing the PR feedback.
=> refactor(python): Add test and fix docstring for `prepare_cloud_plan` util

py-polars/polars/io/spreadsheet/functions.py, py-polars/requirements-dev.txt
Since worksheets are directly converted to polars, fastexcel's eager loading functions can be used. This makes fastexcel use borrowed types under the hood, which allows it to run faster and have a slightly lower memory footprint. See https://github.com/ToucanToco/fastexcel/pull/147#issuecomment-2176264631
=> feat(python): Optimise `read_excel` when using "calamine" engine with the latest `fastexcel`

.github/workflows/release-python.yml
This change ensures that during the release, `pyproject.toml` contains the name of the released package. This way, we avoid bringing in `polars` package when one installs other package types (like `polars-u64-idx`) with optional dependencies.
Fixes #14301
=> build(python): Correctly reference released package in optional dependencies

Cargo.lock, crates/polars-arrow/Cargo.toml, crates/polars-arrow/src/array/null.rs, crates/polars-arrow/src/bitmap/immutable.rs, crates/polars-arrow/src/buffer/mod.rs, crates/polars-parquet/src/arrow/write/primitive/nested.rs, crates/polars-utils/src/foreign_vec.rs, crates/polars-utils/src/lib.rs, py-polars/tests/unit/io/test_parquet.py
=> fix: Properly write nested `NullArray` in Parquet

crates/polars-core/src/chunked_array/ops/fill_null.rs
fixes #15782 fixes #17830
We should expand functionality here.
=> fix: Raise on unsupported fill strategy dtype

py-polars/polars/dataframe/frame.py, py-polars/polars/lazyframe/frame.py
See https://github.com/pola-rs/polars/issues/17782
I hope this slight rewording makes it clearer that 'semi' and 'anti' do not return rows of the right table.
=> docs(python): Reword "how" param docstring entry for 'semi' and 'anti' `join` types for clarity

py-polars/polars/_typing.py, py-polars/polars/io/spreadsheet/_write_utils.py
Somewhere along the line it turns out that the "column_totals" parameter of `write_excel` stopped working for the boolean and string 'func_name' variations (dict/list input was still fine, which is likely why this wasn't noticed earlier), eg:
* `column_totals=True`
* `column_totals="average"`
This PR fixes both of these uses, and updates "column_totals" typing (it supports selectors).
=> fix(python): Fix bool/string usage of "column_totals" parameter in `write_excel`

py-polars/polars/_utils/construction/dataframe.py, py-polars/tests/unit/dataframe/test_df.py
Using an arrow `struct` column type in an arrow table causes `from_arrow` to fail with the following error message:
```
tests/unit/dataframe/test_df.py:210: in test_from_arrow
df = cast(pl.DataFrame, pl.from_arrow(b))
polars/convert/general.py:433: in from_arrow
arrow_to_pydf(
polars/_utils/construction/dataframe.py:1171: in arrow_to_pydf
elif isinstance(column.type, pa.StructType) and column.num_chunks > 1:
E   AttributeError: 'pyarrow.lib.StructArray' object has no attribute 'num_chunks'
```
* Fix `arrow_to_pydf` function to first check for the `num_chunks` attribute 
* Update unit test
* Ruff updates
=> fix: Fix `from_arrow` for struct type

py-polars/src/lazyframe/visitor/expr_nodes.rs
We missed these when first introducing the transliteration.
Make a small breaking change as well by aligning the names of function expressions to match those that are used in the public python Expr API.
=> refactor(python): Pass through missing rolling and stringfunction information in pyir

py-polars/polars/dataframe/frame.py
Resolves #17756.
Previously, `write_column` was used to write data to the table, which writes formatting to each cell individually. This update writes the data in the `add_table` step, which is much simpler, and which also supplies formatting to the table, which in turn formats the columns. The result is simpler data write, simpler formatting, and (very minor) reduction in file size.
=> feat(python): Write data at table level in `write_excel`

py-polars/polars/dataframe/frame.py, py-polars/polars/io/spreadsheet/_write_utils.py, py-polars/tests/unit/io/test_spreadsheet.py
Much better default output when given a "dark" `table_style`:
```python
"dtm": [date(2023, 1, 1), date(2023, 1, 2), date(2023, 1, 3)],
"str": ["xxx", "yyy", "xxx"],
"val": [100.5, 55.0, -99.5],
})
df.write_excel(
workbook="output.xlsx",
table_style="Table Style Dark 2",
column_totals=True,
autofit=True,
)
```
Numeric formatting does not work with _dark_ styles -
Now it does -
=> fix(python): Improve default `write_excel` int/float format when using a dark "table_style"

Cargo.lock, Cargo.toml, crates/polars-sql/src/context.rs, crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_set_ops.py, py-polars/tests/unit/sql/test_temporal.py, py-polars/tests/unit/sql/test_wildcard_opts.py
Updates `sqlparser-rs` to 0.49 to take advantage of some PRs I've made upstream.
* Adds support for the `BY NAME` qualifier across _all_ set ops; like the existing support for this in `UNION`, the modifier aligns the second frame to the first by column name (in much the same way as "diagonal" frame concat).
* Follows-up https://github.com/pola-rs/polars/pull/17109 by enabling `SELECT * REPLACE … RENAME …` query patterns (previously you could not use _both_ REPLACE and RENAME in the same sequence of SELECT modifiers - with the upstream fix available, now you can).
* A few other minor internal improvements/tidy-ups.
Setup:
```python
"x": [1, 9, 1, 1],
"y": [2, 3, 4, 4],
"z": [5, 5, 5, 5],
})
"y": [2, None, 4],
"w": ["?", "!", …
```
=> feat: Support "BY NAME" qualifier for `SQL` "INTERSECT" and "EXCEPT" set ops

py-polars/polars/__init__.py, py-polars/polars/_typing.py, py-polars/polars/lazyframe/__init__.py, py-polars/polars/lazyframe/engine_config.py, py-polars/polars/lazyframe/frame.py, py-polars/pyproject.toml, py-polars/tests/unit/lazyframe/test_engine_selection.py
Introduce option to collect a query using the cudf_polars gpu engine. By default this falls back transparently to the default cpu engine if the query cannot be executed. This can be controlled by setting POLARS_GPU_DISABLE_FALLBACK (mostly useful for testing/debugging).
The import of cudf_polars is currently quite expensive (will improve in the coming months), so since we lazy-load the gpu engine, the first query executed on gpu will pay this (one-time) cost.
=> feat(python): Enable collection with gpu engine

crates/polars-parquet/src/arrow/write/pages.rs, py-polars/tests/unit/io/test_parquet.py
Fixes #17805.
This fixes an issue in the Parquet writer where values that would be valid in the primitive array but invalid at a higher nesting level would still be written. This could for example be true when do `x = (x == "") ? [ x ] : None`. In this case, the empty string might still be valid but the above list is not valid anymore.
This is solved by walking through the structure and propagating the nulls to the lower levels in the parquet writer.
=> fix: Properly write nest-nulled values in Parquet

crates/polars-io/src/cloud/options.rs
ref https://github.com/huggingface/dataset-viewer/pull/2997#pullrequestreview-2199284560
ref https://github.com/huggingface/hub-docs/pull/1345#discussion_r1691497655
Support a login mechanism Hugging Face uses that stores the token in a file under `$HF_HOME/token`.
We attempt to source the token in the following order:
* `storage_options` passed to `pl.(scan|read)_(...)`
* `HF_TOKEN` environment variable
* `$HF_HOME/token` on the filesystem
=> feat: Support authentication with HuggingFace login

crates/polars-io/src/cloud/adaptors.rs, crates/polars-io/src/cloud/glob.rs, crates/polars-io/src/cloud/object_store_setup.rs, crates/polars-io/src/cloud/options.rs, crates/polars-io/src/file_cache/utils.rs, crates/polars-io/src/ipc/ipc_reader_async.rs, crates/polars-io/src/parquet/read/async_impl.rs, crates/polars-io/src/path_utils/mod.rs, crates/polars-utils/src/io.rs, py-polars/tests/unit/io/test_csv.py, py-polars/tests/unit/io/test_other.py, py-polars/tests/unit/io/test_parquet.py
Fixes https://github.com/pola-rs/polars/issues/17822
=> fix: Respect `glob=False` for cloud reads

py-polars/src/lazyframe/visit.rs
We add a major.minor versioning scheme to the NodeTraverser so that we can advertise breaking changes independently of the polars version.
=> refactor(python): Add version field for python IR

py-polars/polars/dataframe/frame.py, py-polars/src/dataframe/general.rs, py-polars/tests/unit/dataframe/test_df.py
Invalid column name lookups were returning `None` from `get_column_index`.
This isn't consistent with `get_column` or the function typing (which indicates it will only return `int`, or raise an error), and was discovered after tracking down a much more cryptic error in some work code caused by the unexpected `None` propagation :)
Now raises the expected `ColumnNotFoundError`.
Test coverage added.
```python
"foo": [1, 2, 3],
"bar": [4, 5, 6],
"ham": [7, 8, 9],
})
```
Column exists; returns index:
```python
df.get_column_index("ham")
```
Column does not exist; raises the expected error:
```python
df.get_column_index("sandwich")
```
=> fix(python): Raise suitable error when invalid column passed to `get_column_index`

crates/polars-io/src/cloud/glob.rs, crates/polars-io/src/cloud/options.rs, crates/polars-io/src/path_utils/hugging_face.rs, crates/polars-io/src/path_utils/mod.rs
Fixes https://github.com/pola-rs/polars/issues/17888
=> fix: Scanning '%' from cloud

Cargo.lock, crates/polars-arrow/src/array/dictionary/typed_iterator.rs, crates/polars-arrow/src/scalar/fixed_size_list.rs, crates/polars-core/src/frame/row/av_buffer.rs, crates/polars-expr/src/expressions/binary.rs, crates/polars-io/src/pl_async.rs, crates/polars-json/src/json/write/mod.rs, crates/polars-parquet/src/arrow/write/utils.rs, crates/polars-pipe/src/executors/sinks/io.rs, crates/polars-pipe/src/executors/sources/csv.rs, crates/polars-plan/src/client/check.rs, crates/polars-plan/src/plans/iterator.rs, rust-toolchain.toml
Only a few minor updates.
Also updated Cargo.lock.
=> build: Update Rust toolchain to `nightly-2024-07-26`

Cargo.lock, crates/polars-io/src/csv/read/mod.rs, crates/polars-io/src/csv/read/read_impl.rs, crates/polars-io/src/csv/read/reader.rs, crates/polars-io/src/csv/read/utils.rs, crates/polars-io/src/utils/compression.rs, crates/polars-io/src/utils/mod.rs, crates/polars-io/src/utils/other.rs, crates/polars-mem-engine/Cargo.toml, crates/polars-mem-engine/src/executors/scan/csv.rs, crates/polars-mem-engine/src/executors/scan/ndjson.rs, crates/polars-pipe/src/executors/sinks/group_by/generic/source.rs, crates/polars-plan/Cargo.toml, crates/polars-plan/src/plans/conversion/scans.rs, crates/polars-utils/src/io.rs, crates/polars/tests/it/io/parquet/write/mod.rs, py-polars/tests/unit/io/test_csv.py
We can have support for this without too much trouble if we concede that we end up fully decompressing twice (once during IR conversion / `file_info`, and then again during the actual read) - I can open an issue afterwards for that.
```python
print(
pl.read_ndjson(
"hf://datasets/Anthropic/hh-rlhf/helpful-rejection-sampled/train.jsonl.gz"
)
)
```
```python
polars.exceptions.ComputeError: stream did not contain valid UTF-8 at line 0
```
```python
shape: (52_421, 2)
┌───────────────────────────────┬───────────────────────────────┐
│ chosen                        ┆ rejected                      │
│ ---                           ┆ ---                           │
│ str                           ┆ str                           │
╞═══════════════════════════════╪═══════════════════════════════╡ …
```
=> feat: Decompress in CSV / NDJSON scan

.github/workflows/benchmark.yml, .github/workflows/docs-global.yml, .github/workflows/lint-python.yml, .github/workflows/test-coverage.yml, .github/workflows/test-python.yml, Makefile
Ref https://github.com/pola-rs/polars/issues/17899
Setting to verbose to hopefully get more information about the issue.
=> ci(python): Set `uv pip install` to verbose

py-polars/src/allocator.rs, py-polars/src/lib.rs
Currently, pyo3 extensions and plugins are statically linked to their own copy of allocator (jemalloc/mimalloc). This does not only bloat the code size, but also increase memory usage and fragmentation: arenas of allocators are not shared, and dirty pages may not be purged after use. (purging only happens on new allocation; when an extension/plugin finishes its work, it does not allocate anymore, so the dirty pages allocated by its allocator cannot be purged.)
This PR adds the allocator capsule (`polars.polars._allocator`), which exposes the allocator used by python polars. pyo3 extensions and plugins can import this capsule and relay allocations to it. All allocations can now be managed by one single jemalloc/mimalloc.
=> feat(python): Expose allocator to capsule

crates/polars-core/src/chunked_array/ops/apply.rs, crates/polars-core/src/chunked_array/ops/arity.rs, docs/user-guide/expressions/plugins.md
This does a couple of things:
- add `binary_elementwise_into_string_amortized` as a utility for plugin authors (and it may end up being useful internally if the great expressification continues?)  - there's a a few plugins that have binary operations which produce strings which could benefit from this
- remove `apply_to_buffer` and recommend `apply_into_string_amortized` to plugin authors instead - their perf is about the same, but the latter has the advantage that the input isn't required to be exactly `StringChunked`
=> feat: Expose binary_elementwise_into_string_amortized for plugin authors, recommend `apply_into_string_amortized` instead of `apply_to_buffer`

.github/workflows/docs-global.yml, .github/workflows/docs-python.yml
Closes https://github.com/pola-rs/polars/issues/17329
I believe the issue is that the global docs workflow and the Python docs workflow try updating the `gh-pages` branch simultaneously. This leads to some of the updates being lost, e.g.:
* A checks out branch
* B checks out branch
* A writes to branch
* B writes to branch (updates from A are lost)
Now the global docs will be built _after_ the Python API docs. That should take care of the issue.
Not super happy with this fix - it introduces some complexity - but it should work.
=> ci(python): On Python release, trigger docs build after API reference build

py-polars/polars/dataframe/frame.py, py-polars/polars/series/series.py
Closes https://github.com/pola-rs/polars/issues/17921
=> fix(python): Default to `None` in pycapsule interface export

crates/polars-core/src/datatypes/dtype.rs, py-polars/tests/unit/io/test_parquet.py
=> feat: Allow for parsing parquet file where the time zone is stored as lowercase "utc"

crates/polars-sql/src/sql_expr.rs, py-polars/tests/unit/sql/test_literals.py
A quick coffee-break-sized PR ☕ 
Adds SQL support for PostgreSQL dollar-quoted string literals[^1].
```python
pl.sql("""
SELECT
$$string$$ AS s1,
$tag$another string$tag$ AS s2
""").collect()
```
[^1]: https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING
=> feat: Add `SQL` interface support for PostgreSQL dollar-quoted string literals

crates/polars-core/src/chunked_array/arithmetic/mod.rs, crates/polars-core/src/chunked_array/float.rs, crates/polars-core/src/chunked_array/mod.rs, crates/polars-core/src/chunked_array/ops/aggregate/var.rs, crates/polars-core/src/chunked_array/ops/apply.rs, crates/polars-core/src/chunked_array/ops/arity.rs, crates/polars-ops/src/chunked_array/binary/namespace.rs, crates/polars-ops/src/chunked_array/strings/concat.rs, crates/polars-ops/src/chunked_array/strings/find_many.rs, crates/polars-ops/src/chunked_array/strings/namespace.rs, crates/polars-ops/src/chunked_array/strings/reverse.rs, crates/polars-ops/src/chunked_array/strings/strip.rs, crates/polars-ops/src/series/ops/clip.rs, crates/polars-ops/src/series/ops/cum_agg.rs, crates/polars-ops/src/series/ops/index.rs, crates/polars-ops/src/series/ops/is_in.rs, crates/polars-ops/src/series/ops/various.rs, crates/polars-plan/src/dsl/function_expr/pow.rs, crates/polars-time/src/chunkedarray/string/mod.rs, crates/polars/src/docs/eager.rs
This is what I was talking about yesterday
It seems to me that `apply_generic` and `unary_elementwise` overlap? There's an extra little fastpath in the first one for when there's no nulls (which I ported over), but other than that, is it necessary to have both?
=> chore: Remove apply_generic, use unary_elementwise

docs/src/python/user-guide/misc/arrow_pycapsule.py, docs/user-guide/misc/arrow.md
Ref https://github.com/pola-rs/polars/pull/17676#pullrequestreview-2198799598
=> docs(python): Documentation for Arrow PyCapsule interface integration

crates/polars-io/src/predicates.rs, py-polars/tests/unit/io/test_lazy_parquet.py
Fixes https://github.com/pola-rs/polars/issues/17944
Fixes https://github.com/pola-rs/polars/issues/17744
Regression by https://github.com/pola-rs/polars/pull/17545
=> fix: Incorrect filter on categorical columns from parquet files

py-polars/polars/dataframe/group_by.py, py-polars/polars/expr/array.py, py-polars/polars/expr/expr.py, py-polars/polars/lazyframe/frame.py, py-polars/polars/lazyframe/group_by.py, py-polars/polars/series/array.py
Closes #17826
I have never heard of this being a thing, but one less open accepted issue is always better haha
=> docs(python): Ensure `last` is never ambiguous with `max`

py-polars/polars/testing/parametric/strategies/core.py
Trivial fix as I'm going through the Hypothesis strategy implementation
=> chore(python): Suggest `allow_null` as replacement
