pola-rs/polars

- py-polars/tests/unit/operations/namespaces/string/test_string.py
Was going to pick up #17220 and noticed there were no tests for these two methods. Good to add tests first before making any changes.
I've only included tests that conform to more strict Series function signature, so that the Series and Expression methods can be tested together. I'm unsure if the Expression function signature is intentionally more lax than the Series counterpart. The expression methods also give some unexpected results IMO (I raised #17863 for this).
In terms of the PR - I tried to test a good variety of input types and combinations, but let me know if this is overboard.
> test: Add unit tests for `str.contains_any` and `str.replace_many`

- crates/polars-plan/src/plans/schema.rs
- py-polars/tests/unit/operations/test_join_asof.py
> fix: Fix Asof join by schema

- py-polars/src/conversion/any_value.rs
- py-polars/tests/unit/constructors/test_structs.py
> fix(python): Respect `strict` argument

- crates/polars-utils/src/mmap.rs
Learned a few things after looking into the `bytes::Bytes` implementation. They essentially already do most of what we want from `MemSliceInner`, just without the Mmap support:
* Creating a `Bytes` from a `Vec` is zero-copy
* Creating an empty `Bytes::new()` doesn't heap-allocate
* They have `const fn Bytes::from_static` we can use for the `&'static [u8]` case, which also doesn't allocate
This shrinks the size of `MemSliceInner` from 40 to 32 bytes
> perf: Shrink `MemSliceInner` enum

- crates/polars-io/src/csv/read/options.rs
- crates/polars-io/src/csv/read/read_impl.rs
- crates/polars-io/src/csv/read/reader.rs
- py-polars/tests/unit/io/test_csv.py
Resolves #17349, also including support for `pl.Time` and `pl.Categorical`.
`read_csv` actually already supported passing these types to `schema_overrides`, but not to `schema` directly. This is mostly moving that to be shared functionally (which is the cause of the ugly diff in `reader.rs`) and fixing another bug I found in testing that prevented `pl.Time` from being read correctly.
> fix(rust): Allow `read_csv` `schema` to take unparsable types

- crates/polars-arrow/src/temporal_conversions.rs
- crates/polars-time/src/chunkedarray/date.rs
- crates/polars-time/src/chunkedarray/kernels.rs
- crates/polars-time/src/series/mod.rs
- py-polars/tests/unit/datatypes/test_temporal.py
TL;DR: use maths instead of Chrono
> perf: Make `.dt.weekday` 20x faster

- crates/polars-arrow/src/array/binview/mod.rs
- crates/polars-core/src/chunked_array/ops/apply.rs
- crates/polars-ops/src/chunked_array/strings/namespace.rs
- crates/polars-ops/src/chunked_array/strings/substring.rs
Didn't do every length combinations, but the most occurring are handled.
This doesn't do a memcopy of the string anymore, but updates the views. Depending on the size of the slice this has increasing performance improvements:
```
length,    improvement
4               1.17x
19             1.42
``` 
And this will scale linearly.
> perf: Optimize strings slices

- crates/polars-sql/src/context.rs
- py-polars/tests/unit/sql/test_joins.py
> feat: Add nested SQL join support

- docs/src/python/user-guide/expressions/aggregation.py
- docs/user-guide/expressions/aggregation.md
addresses https://github.com/pola-rs/polars/issues/17858
> docs: Fix aggregation guide discrepancies

- Cargo.lock
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-plan/src/dsl/mod.rs
- crates/polars-plan/src/dsl/selector.rs
- crates/polars-plan/src/plans/builder_dsl.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/expr_expansion.rs
- crates/polars-plan/src/plans/functions/dsl.rs
- py-polars/Cargo.toml
- py-polars/polars/lazyframe/frame.py
- py-polars/polars/selectors.py
- py-polars/src/expr/mod.rs
- py-polars/src/lazyframe/mod.rs
fixes #18008
Sets up architecture for this. We can follow up with all methods that expand.
> perf: Delay selection expansion

- crates/polars-core/Cargo.toml
No changes needed on our side; just picking up a minor width-calc fix on the off-chance someone is using (or wants to use) ANSI escape sequences somewhere. (See: https://github.com/Nukesor/comfy-table/releases)
> chore: Minor bump to `comfy-table` version

- crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs
- crates/polars-parquet/src/parquet/read/page/reader.rs
- crates/polars-parquet/src/parquet/read/page/stream.rs
This removes more than 50% of the temporary allocations in the Parquet readers. The only temporary allocations left are in the Thrift definitions and the `polars_io` code.
> perf: Remove temporary allocations in Parquet

- crates/polars-compute/src/min_max/dyn_array.rs
- crates/polars-compute/src/min_max/mod.rs
- crates/polars-compute/src/min_max/scalar.rs
- crates/polars-compute/src/min_max/simd.rs
- crates/polars-parquet/src/arrow/write/primitive/basic.rs
- crates/polars-parquet/src/arrow/write/utils.rs
- crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs
- crates/polars-parquet/src/parquet/types.rs
This improves the performance writing of primitive arrays into Parquet.
Running the following program, which is made to really test this function.
```rust
use std::io::Seek;
use polars::frame::DataFrame;
use polars::prelude::NamedFrom;
use polars::series::Series;
use polars_io::parquet::write::ParquetWriter;
use rand::Rng;
const NUM_VALUES: usize = 10_000_000;
fn main() -> Result<(), Box<dyn std::error::Error>> {
let mut rng = rand::thread_rng();
let mut values: Vec<f32> = Vec::with_capacity(NUM_VALUES);
unsafe { values.set_len(NUM_VALUES) };
rng.fill(&mut values[..]);
let values = &values[..];
let s = Series::new("a", values);
let mut f = std::fs::OpenOptions::new()
.write(true)
.create(true)
.open("output.parquet")
.unwrap();
for _ in 0..100 {
f.seek(std::io::SeekFrom::Start(0))?;
let …
```
> perf: Speedup writing of Parquet primitive values

- py-polars/polars/dataframe/frame.py
- py-polars/polars/io/spreadsheet/_write_utils.py
- py-polars/tests/unit/io/test_spreadsheet.py
Closes #17994.
Closes #17968.
```python
from xlsxwriter import Workbook
"id": ["a123", "b345", "c567", "d789", "e101"],
"points": [99, 45, 50, 85, 35],
})
with Workbook("basic_chart.xlsx") as wb:
ws = wb.add_worksheet("demo")
df.write_excel(
workbook=wb,
worksheet=ws,
table_name="DataTable",
table_style="Table Style Medium 26",
hide_gridlines=True,
)
chart = wb.add_chart({"type": "column"})
chart.set_title({"name": "Example Chart"})
chart.set_legend({"none": True})
chart.set_style(38)
chart.add_series({
"values": "=DataTable[points]",
"categories": "=DataTable[id]",
"data_labels": {"value": True},
})
ws.insert_chart("D1", chart)
```
> feat(python): Support passing `Worksheet` objects to the `write_excel` method

- crates/polars-io/src/parquet/write/writer.rs
- crates/polars-parquet/src/arrow/write/boolean/basic.rs
- crates/polars-parquet/src/arrow/write/mod.rs
This is a more efficient encoding for `Boolean`s especially when considering columns that might be biased towards either true or false.
For a column with `100_000_000` times `True`, we see.
```
No Hybrid RLE: 12M
Hybrid RLE: 66K
No Hybrid RLE: 75K
Hybrid RLE: 70K
```
> feat: Add boolean Parquet HybridRle encoding

- py-polars/polars/expr/expr.py
addresses https://github.com/pola-rs/polars/issues/17963
> docs: Update map_batches docstring

- crates/polars-parquet/src/arrow/write/dictionary.rs
This adds a fast path for the slowest part of parquet writing which is (attemping) the dictionary encoding. Normally this involves a lot of hashing which is quite slow. With this PR, it will first look at the minimum and maximum values for integers. If these are sufficiently close together, we create the dictionary using those values.
> perf: Integer fast path Parquet dict encoding

- crates/polars-plan/src/plans/conversion/expr_expansion.rs
- py-polars/tests/unit/test_selectors.py
> fix(python): Fix drop selector

- crates/polars-mem-engine/src/executors/scan/parquet.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
Fixes https://github.com/pola-rs/polars/issues/18035
> fix: Subtraction with overflow on negative slice offset in Parquet

- py-polars/polars/dataframe/frame.py
addresses https://github.com/pola-rs/polars/issues/17967
> docs: Update pivot docstring for clarity

- crates/polars-arrow/src/array/binview/view.rs
- crates/polars-arrow/src/compute/cast/binary_to.rs
This is still not perfect because the code-generation for `View::new_inline_unchecked` is absolutely horrible, but that can be addressed in a later PR.
> perf: Zerocopy buffers for `FixedSizeBinary` to `BinaryView` cast

- crates/polars-expr/src/expressions/mod.rs
- crates/polars-io/src/parquet/read/mmap.rs
- crates/polars-io/src/parquet/read/options.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-io/src/predicates.rs
- crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs
- crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs
- crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs
- crates/polars-parquet/src/arrow/read/deserialize/binview.rs
- crates/polars-parquet/src/arrow/read/deserialize/boolean.rs
- crates/polars-parquet/src/arrow/read/deserialize/dictionary.rs
- crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary.rs
- crates/polars-parquet/src/arrow/read/deserialize/null.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
- crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
- crates/polars-parquet/src/parquet/encoding/bitpacked/decode.rs
- crates/polars-parquet/src/parquet/encoding/hybrid_rle/buffered.rs
- crates/polars-parquet/src/parquet/encoding/hybrid_rle/fuzz.rs
- crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs
- crates/polars-pipe/src/executors/sinks/group_by/aggregates/convert.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/plans/optimizer/cluster_with_columns.rs
- crates/polars-utils/src/vec.rs
- py-polars/polars/_typing.py
- py-polars/polars/io/parquet/functions.py
- py-polars/src/conversion/mod.rs
This adds the `prefiltered` option to `scan_parquet(parallel='...')` which first evaluates the predicates and then only reads the relevant rows. For large files with predicates that are clustered or biased towards selecting or not-selecting, this provides a significant speed-up.
> perf: Use bitmask to filter Parquet predicate-pushdown items

- crates/polars-io/src/cloud/adaptors.rs
- examples/write_parquet_cloud/Cargo.toml
- examples/write_parquet_cloud/src/main.rs
The issue started after the bump of `ObjectStore` to v0.10. Before that, ObjectStore was doing an internal buffer.
The implementation is using `ObjectStore::BufWriter`, that is going to perform a "put" request if the size of data is below the "capacity". Otherwise it is going to do a "put multipart" instead.
Fixes https://github.com/pola-rs/polars/issues/17172
> fix: Fix `CloudWriter` to use buffer before making requests

- crates/polars-io/src/file_cache/utils.rs
Fixes https://github.com/pola-rs/polars/issues/18053
> fix: Panic reading multiple CSV files from cloud

- crates/polars-io/src/path_utils/mod.rs
- crates/polars-lazy/src/scan/csv.rs
- crates/polars-lazy/src/scan/file_list_reader.rs
- crates/polars-lazy/src/scan/ipc.rs
- crates/polars-lazy/src/scan/ndjson.rs
- crates/polars-lazy/src/scan/parquet.rs
- crates/polars-mem-engine/src/executors/scan/csv.rs
- crates/polars-mem-engine/src/executors/scan/ipc.rs
- crates/polars-mem-engine/src/executors/scan/ndjson.rs
- crates/polars-mem-engine/src/executors/scan/parquet.rs
- crates/polars-pipe/src/executors/sources/csv.rs
- crates/polars-pipe/src/executors/sources/parquet.rs
- crates/polars-plan/src/plans/builder_dsl.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/functions/count.rs
- crates/polars-plan/src/plans/functions/mod.rs
- crates/polars-plan/src/plans/hive.rs
- crates/polars-plan/src/plans/ir/mod.rs
- crates/polars-plan/src/plans/mod.rs
- crates/polars-plan/src/plans/optimizer/count_star.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
- crates/polars-stream/src/utils/late_materialized_df.rs
This saves some copying as constructing an `Arc<Vec<_>>` re-uses the buffer. For paths and hive partitions in particular, they are potentially re-constructed during predicate pushdown.
> perf: Use `Arc<Vec<_>>` instead of `Arc<[_]>` for paths and hive partitions

- crates/polars-arrow/src/array/binview/mod.rs
- crates/polars-parquet/src/arrow/write/pages.rs
- py-polars/tests/unit/io/test_parquet.py
This is a relatively small fix for what was a quite nasty bug.
Fixes #18069.
> fix: Properly write Parquet for sliced lists

- docs/user-guide/transformations/concatenation.md
addresses https://github.com/pola-rs/polars/issues/18052
> docs: Correct concat rechunk in user guide

- crates/polars-io/src/cloud/adaptors.rs
- crates/polars-pipe/src/executors/sinks/output/ipc.rs
- crates/polars-pipe/src/executors/sinks/output/parquet.rs
- examples/write_ipc_cloud/Cargo.toml
- examples/write_ipc_cloud/src/main.rs
Fixes #13614
When writing to ObjectStore-compatible storage using the IPC format, it seems like the `block_on` calls inside the constructed `CloudWriter` might sometimes get called inside another `block_on` call. Tokio does not like this, resulting in a panic.
This PR resolves this issue by using `block_on_potential_spawn` in the necessary places instead.
This is a fix that was originally written by @Qqwy in another PR: https://github.com/pola-rs/polars/pull/14262
> fix: Fix `sink_ipc_cloud` panicking with runtime error

- crates/polars-io/src/csv/read/parser.rs
- crates/polars-io/src/utils/other.rs
- crates/polars-mem-engine/src/executors/scan/csv.rs
- crates/polars-mem-engine/src/executors/scan/ndjson.rs
- crates/polars-plan/src/plans/conversion/scans.rs
- py-polars/tests/unit/io/test_lazy_csv.py
Fixes https://github.com/pola-rs/polars/issues/18057
Fixes https://github.com/pola-rs/polars/issues/18070
> fix: Incorrect lazy CSV `select(len())` for compressed files

- crates/polars-plan/src/dsl/functions/selectors.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/io/spreadsheet/_write_utils.py
- py-polars/polars/selectors.py
- py-polars/tests/unit/io/test_spreadsheet.py
When setting `column_totals=True` we should account for any columns created via `row_totals` (we used to[^1], and it seems this went missing somewhere in a refactor).
Also:
* The `row_totals` column(s) dtype (int/float) should be determined by the constant columns; if all are int, the total should _also_ be int, not float.
* Default numeric value formats now better-match explicit table style colours.
```python
"id": ["aaa", "bbb", "ccc", "ddd", "eee"],
"q1": [100.0, 55.5, -20.0, 0.5, 35.0],
"q2": [30.5, -10.25, 15.0, 60.0, 20.5],
"q3": [-50, 0, 40, 80, 80],
"q4": [75, 55, 25, -10, -55],
})
df.write_excel(
"testing.xlsx",
table_style = "Table Style Light 2",
sparklines = {"trend": ["q1", "q2", "q3", "q4"]},
row_totals = {
"h1": ("q1","q2"),
"h2": …
```
> fix(python): When setting `write_excel` column totals, don't forget to include any row-total cols

- crates/polars-ops/src/chunked_array/strings/case.rs
- py-polars/polars/expr/string.py
- py-polars/polars/series/string.py
- py-polars/tests/unit/operations/namespaces/string/test_string.py
Closes #18116.
Note, closes the issue by better-aligning `to_titlecase` to the standard implementation, not by adding new options. (We were defining "word" boundaries by whitespace, but that is a _much_ narrower definition than normal, which considers all non-alphanumeric chars as boundaries).
```python
"quotes": [
"'e.t. phone home'",
"i feel the need--the need for speed",
"to infinity,and BEYOND!",
"say 'what' again!i dare you - I\u00a0double-dare you!",
"What.we.got.here... is#failure#to#communicate",
]
})
with pl.Config(fmt_str_lengths=50):
print(
df.select(cs.string().str.to_titlecase())
)
```
```python
```
```python
```
> fix: String transform `to_titlecase` was too narrowly defined

- py-polars/src/dataframe/general.rs
- py-polars/src/lazyframe/visitor/expr_nodes.rs
- py-polars/src/lib.rs
This fixes the compilation of py-polars with no features.
And should address the compilation failure in #18117.
> fix: Py-polars compilation with no features

- crates/polars-io/src/csv/read/parser.rs
- crates/polars-io/src/csv/read/read_impl.rs
- py-polars/tests/unit/io/test_csv.py
Closes #18128, if this is desireable behavior.
> fix: Don't remove leading whitespace in `read_csv`

- crates/polars-core/src/datatypes/any_value.rs
- py-polars/tests/unit/functions/test_lit.py
closes #17773 
Fixed:
```
>>> pl.select(pl.lit(3.2, dtype=pl.Utf8))
shape: (1, 1)
┌─────────┐
│ literal │
│ ---     │
│ str     │
╞═════════╡
│ 3.2     │
└─────────┘
```
This is my first time doing a PR for this project so set it to draft to hear feedback. If I keep the below line in test where we use agg, max, min break for Categorical data.
` (_, DataType::String) => {
AnyValue::StringOwned(format_smartstring!("{}", self.extract::<i64>()?))
},`
I can add more cases for string casting if that is wanted so we define all types.
> fix(python): Fix cast Float to String where Float is not turn to Integer before turning to String

- py-polars/polars/_utils/construction/dataframe.py
- py-polars/tests/unit/interop/test_from_pandas.py
> fix: Don't raise when converting from pandas if index contains duplicate names when `include_index=False` (the default)

- crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs
> fix: Parquet with `filter=None`

- crates/polars-core/src/utils/supertype.rs
- crates/polars-plan/src/dsl/list.rs
- crates/polars-plan/src/dsl/mod.rs
- crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
- py-polars/tests/unit/expr/test_exprs.py
- py-polars/tests/unit/operations/test_is_in.py
- py-polars/tests/unit/operations/test_search_sorted.py
- py-polars/tests/unit/test_errors.py
> fix: Prevent unwanted supertype cast in 'search_sorted'

- crates/polars-io/src/pl_async.rs
Work spawned onto tokio threads are generally lightweight I/O tasks that spend most of their time `await`ing, so we don't need a lot of threads for it.
> perf: Reduce default async thread count

- crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
- py-polars/tests/unit/io/test_pyarrow_dataset.py
> fix: Fix pyarrow predicate pushdown regression

- Cargo.lock
```rust
mod tests {
#[test]
fn test() {
struct X {}
impl std::ops::Deref for X {
type Target = [u8];
fn deref(&self) -> &Self::Target {
&[]
}
}
let x = X {};
let _deref = &*x;
let _asref = x.as_ref();
}
}
```
The above currently fails on Linux due to `bstr` - updating Cargo.lock removes it from the dependencies
> chore: Update Cargo.lock to fix build error on Linux

- py-polars/polars/dataframe/group_by.py
Fixes a pathological case where every group, triggers a rechunk.
> perf(python): Rechunk group-by __iter__

- crates/polars-io/src/parquet/read/mmap.rs
- crates/polars-parquet/src/arrow/read/deserialize/mod.rs
- crates/polars-parquet/src/arrow/read/mod.rs
- crates/polars-parquet/src/arrow/read/row_group.rs
- crates/polars-parquet/src/parquet/read/column/mod.rs
- crates/polars-parquet/src/parquet/read/mod.rs
- crates/polars-parquet/src/parquet/read/page/mod.rs
- crates/polars-parquet/src/parquet/read/page/reader.rs
- crates/polars-parquet/src/parquet/read/page/stream.rs
- crates/polars/tests/it/io/parquet/read/mod.rs
- py-polars/tests/unit/io/test_parquet.py
> fix: Properly handle empty Parquet row groups with no dictionary

- py-polars/polars/config.py
- py-polars/tests/unit/test_config.py
Found a bug with `Config` object load and save methods; configuration options that had not been explicitly set to a non-default value were not being properly captured or restored.
Fixed this and added suitable test coverage.
> fix(python): Ensure default values are included when saving/restoring the current `Config` state

- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/datatypes/test_temporal.py
Closes #18103.
(Also a quick drive-by fix: addresses a false-positive error in a parametric test).
> docs(python): Fix references to old methods in `lazy` docstring

- crates/polars-core/src/series/iterator.rs
Add this
```rust
impl FromIterator<Option<&'a str>> for Series
impl FromIterator<Option<String>> for Series
````
> feat(rust): Add missing impl for `Series`

- crates/polars-plan/Cargo.toml
- crates/polars-plan/src/dsl/functions/mod.rs
- crates/polars-plan/src/dsl/functions/temporal.rs
- crates/polars/tests/it/lazy/expressions/apply.rs
- crates/polars/tests/it/lazy/expressions/literals.rs
- crates/polars/tests/it/lazy/expressions/mod.rs
- crates/polars/tests/it/lazy/expressions/window.rs
- crates/polars/tests/it/lazy/predicate_queries.rs
- crates/polars/tests/it/lazy/projection_queries.rs
The optimizer understands those better.
> feat: Create literals in 'datetime' expression

- crates/polars-arrow/src/compute/cast/primitive_to.rs
- crates/polars-arrow/src/temporal_conversions.rs
- crates/polars-core/src/datatypes/dtype.rs
- crates/polars-plan/src/dsl/functions/temporal.rs
- crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
- crates/polars/tests/it/lazy/expressions/literals.rs
Much clearer for the optimizer.
> feat: Create literals for datetime/date expressions

- crates/polars-io/src/parquet/read/mmap.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-parquet/src/arrow/read/deserialize/mod.rs
- crates/polars-parquet/src/arrow/read/mod.rs
- crates/polars-parquet/src/arrow/read/row_group.rs
- crates/polars-parquet/src/arrow/read/statistics/mod.rs
> fix: Don't load Parquet nested metadata

- crates/polars-io/Cargo.toml
- crates/polars-io/src/ndjson/core.rs
This speeds it up by 40% in the following benchmark:
```rust
use criterion::{criterion_group, criterion_main, Criterion};
use mimalloc::MiMalloc;
use polars::prelude::*;
use polars_core::POOL;
use rand::{thread_rng, Rng};
#[global_allocator]
static MIMALLOC: MiMalloc = MiMalloc;
fn from_json(json: &[u8]) -> DataFrame {
JsonReader::new(std::io::Cursor::new(json))
.with_json_format(JsonFormat::JsonLines)
.set_rechunk(false)
.finish()
.unwrap()
}
fn my_benchmark(_c: &mut Criterion) {
POOL.install(|| {
let mut c = Criterion::default().configure_from_args();
const SIZE: i32 = 5_000_000;
let mut rng = thread_rng();
let mut df = df![
"a" => (0..SIZE).map(|_| rng.gen::<i32>()).collect::<Vec<_>>(),
"b" => (0..SIZE).map(|v| v.to_string()).collect::<Vec<_>>(),
]
.unwrap();
let mut json = Vec::new(); …
```
> perf: Speedup ndjson reader `~40%`

- py-polars/polars/meta/versions.py
Instead of waiting for all imports to finish before showing any output, now `pl.show_versions()` will show versions as we compute them.
> feat(python): Make show_versions more responsive

- py-polars/tests/unit/io/database/test_read.py
Closes #18218. Bifurcation occurs at 3.9.5, see the following for version evidence:
<details><summary><b>3.9.4</b></summary>
```
mcrumiller@Saline-PC:~/projects/polars/py-polars$ pyenv global 3.9.4
mcrumiller@Saline-PC:~/projects/polars/py-polars$ python
Python 3.9.4 (default, Aug 15 2024, 12:38:05) 
[GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> uri = "fakedb://123:456@account/database/schema?warehouse=warehouse&role=role"
>>> pl.read_database_uri("SELECT * FROM data", uri=uri, engine="connectorx")
thread '<unnamed>' panicked at 'not implemented: Connection: fakedb://123:456@account/database/schema?warehouse=warehouse&role=role not supported!', /__w/connector-x/connector-x/connectorx/src/source_router.rs:80:18 …
```
> test(python): Fix version bifurcation for `test_read_database_cx_credentials`

- py-polars/polars/functions/lit.py
- py-polars/src/functions/lazy.rs
- py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py
> fix(python): Convert date and datetime in literal construction

- py-polars/polars/dataframe/frame.py
While the `TODO` in the first line of the implementation is still around, we can doctest the examples in this function without a warning. In this particular case, the column name was incorrect.
> docs(python): Fix column name output in example of `DataFrame.map_rows`

- README.md
Run with rust 1.77 stable, Rust Polars 0.42.0:
```
cargo run -r
Compiling polars-arrow v0.42.0
error[E0658]: inline-const is experimental
--> E:\Program-Files\rust\.cargo\registry\src\rsproxy.cn-0dccff568467c15b\polars-arrow-0.42.0\src\array\static_array.rs:70:9
|
70 |         no_call_const!()
|         ^^^^^^^^^^^^^^^^
|
= note: see issue #76001 <https://github.com/rust-lang/rust/issues/76001> for more information
= note: this error originates in the macro `no_call_const` (in Nightly builds, run with -Z macro-backtrace for more info)
```
I found that this macro uses `Inline const expressions`, which has been stable since version Rust 1.79 stable:  
```rust
#[macro_export]
macro_rules! no_call_const {
() => {{
const { assert!(false, "should not be called") }
unreachable!()
}};
}
```
refer …
> chore: Update the required version of rust in README.md

- py-polars/tests/unit/io/test_delta.py
We need to explicitly provide overwrite mode when setting overwrite_schema = True
@stinodego :)
> test(python): Fix test for new deltalake release

- crates/polars-python/Cargo.toml
- crates/polars-python/src/dataframe/construction.rs
- crates/polars-python/src/dataframe/export.rs
- crates/polars-python/src/dataframe/general.rs
- crates/polars-python/src/dataframe/io.rs
- crates/polars-python/src/dataframe/mod.rs
- crates/polars-python/src/dataframe/serde.rs
- crates/polars-python/src/expr/mod.rs
- crates/polars-python/src/functions/misc.rs
- crates/polars-python/src/lazyframe/exitable.rs
- crates/polars-python/src/lazyframe/mod.rs
- crates/polars-python/src/lazyframe/visit.rs
- crates/polars-python/src/lazyframe/visitor/nodes.rs
- crates/polars-python/src/lib.rs
- crates/polars-python/src/on_startup.rs
- crates/polars-python/src/series/aggregation.rs
- crates/polars-python/src/series/arithmetic.rs
- crates/polars-python/src/series/buffers.rs
- crates/polars-python/src/series/c_interface.rs
- crates/polars-python/src/series/export.rs
- crates/polars-python/src/series/general.rs
- crates/polars-python/src/series/import.rs
- crates/polars-python/src/series/mod.rs
- crates/polars-python/src/series/numpy_ufunc.rs
- crates/polars-python/src/series/scatter.rs
- py-polars/Cargo.toml
- py-polars/src/lib.rs
This feature gates the stuff that is only useful for the `py-polars` crate behind the `pymethods` feature.
> refactor(rust): Add feature gates for `polars-python` crate

- crates/polars-ops/src/series/ops/interpolation/interpolate_by.rs
- py-polars/tests/unit/operations/test_interpolate_by.py
Ok, splitting this out in to a simpler PR. Fixes #16794
> feat: Allow float in interpolate_by by column

- crates/polars-arrow/src/array/struct_/mod.rs
- py-polars/tests/unit/io/test_json.py
fixes https://github.com/pola-rs/polars/issues/10234
> feat: Support empty structs

- crates/polars-core/src/chunked_array/ops/mod.rs
- crates/polars-core/src/frame/mod.rs
- crates/polars-core/src/series/implementations/struct__.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-mem-engine/src/executors/scan/parquet.rs
- crates/polars-pipe/src/executors/sources/csv.rs
- py-polars/tests/unit/io/test_scan.py
Fixes https://github.com/pola-rs/polars/issues/18219#issuecomment-2295184914
Also fixes a panic for batched CSV and Parquet (fixes https://github.com/pola-rs/polars/issues/18257)
```rust
py-polars/tests/unit/io/test_scan.py ..thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/mod.rs:643:9:
index: 10 out of bounds for len: 1
```
> fix: Fix duplicate column output and panic for `include_file_paths`

- crates/polars-time/src/round.rs
- crates/polars-time/src/truncate.rs
- py-polars/polars/dependencies.py
- py-polars/polars/expr/datetime.py
- py-polars/polars/series/datetime.py
- py-polars/tests/unit/operations/namespaces/temporal/test_round.py
> fix: Consistently round half-way points down in dt.round

- py-polars/polars/expr/binary.py
> docs(python): Add missing "Parameters" section to `bin.size` expr docstring

- crates/polars-io/src/cloud/options.rs
As it turns out, this functionality was already there (ref https://github.com/pola-rs/polars/pull/13062) - it's just that it failed to load if the credential lines didn't have space padding 😄. But now we will be able to load them regardless of spaces.
Fixes https://github.com/pola-rs/polars/issues/18254
> fix: Fix failed AWS credential load from '~/.aws/credentials' due to formatting

- crates/polars-python/src/functions/lazy.rs
- py-polars/polars/functions/lit.py
- py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py
Slight followup to #16018, allows direct construction of literals from `datetime.time` and `datetime.timedelta` objects.
> perf: Use direct path for `time`/`timedelta` literals

- crates/polars-lazy/src/frame/cached_arenas.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/tests/optimization_checks.rs
- crates/polars-lazy/src/tests/queries.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-python/src/lazygroupby.rs
Rename `schema` to `collect_schema` to indicate we are doing work.
> refactor(rust): Change fn schema to fn collect_schema

- crates/polars-sql/src/context.rs
- py-polars/tests/unit/sql/test_set_ops.py
We don't support the `ALL` modifier for `EXCEPT` and `INTERSECT` set ops in the SQL interface (_yet_ - I know how we can add this, and plan to do so in the near future). 
Until this support is implemented we need to make sure we raise a suitable error instead (`ALL` already did this, but the `ALL BY NAME` qualifier was sneaking through):
```python
df1 = pl.DataFrame({"n": [1, 1, 1, 2, 2, 2, 3]})
df2 = pl.DataFrame({"n": [1, 1, 2, 2]})
pl.sql("SELECT * FROM df1 EXCEPT ALL BY NAME TABLE df2")
```
Was previously returning (incorrectly) the same result as `EXCEPT BY NAME`.
> fix: Raise suitable error on unsupported `SQL` set op syntax

- crates/polars-ops/src/chunked_array/hist.rs
- py-polars/polars/series/series.py
- py-polars/tests/unit/operations/test_statistics.py
Resolves #16912.
This implementation affects `pl.hist(x, bin_counts=...)` and makes two behavioral modifications:
1. The first and last bucket no longer extend to infinities. We now mimic pandas' behavior, where the left-most (open interval) edge is extended by 0.1% the total range, and the right-most (closed interval) edge is the maximum value.
2. We no longer return an empty "garbage" bin as the first bin. Previously, this bin always returned 0 items, and was not meaningful.
This implementation is a little simpler than the previous and I *believe* it removes the need for the special stability logic for rounding near integers. It mimics the behavior of pandas' `cut`, which is reasonable behavior. I don't see any tests that cover that logic, unless the `test_hist_rand` function covers it …
> fix: Use appropriate bins in `hist` when `bin_count` specified

- py-polars/polars/expr/expr.py
addresses https://github.com/pola-rs/polars/issues/18233
> docs: Add note to `Expr.shuffle` differentiating from df method

- py-polars/polars/io/database/_executor.py
Closes #18263.
One of those rare two-character fixes... ;)
Following the "duckdb_engine" code a little more closely showed that we didn't need to expose the inner/private connection object to take advantage of the `fetch_arrow_table` fast-path; the driver connection's `__getattr__` accesses it implicitly for us. (Explicit access via `.c` was deprecated and removed recently, hence the reported error).
Confirmed the fix works and still takes the Arrow-aware fast path with old/new versions of the "duckdb_engine" alchemy driver.
> feat(python): Support the most recent version of "duckdb_engine" connections via `read_database`

- crates/polars-python/src/lazyframe/general.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
closes #18089 
Join asof is like a left-join, so I think the argument (and description) can be simplified too, right? it's either true or false, nothing join-dependent
> docs: Clarify `coalesce` behaviour in `join_asof`

- crates/polars-io/src/cloud/polars_object_store.rs
Fixes https://github.com/pola-rs/polars/issues/18186
I don't have GCS to test but it should also fix https://github.com/pola-rs/polars/issues/14908
> feat: Support pre-signed URLs for cloud scan

- crates/polars-core/src/schema.rs
- crates/polars-plan/src/plans/ir/schema.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/mod.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
- crates/polars-stream/src/skeleton.rs
This is necessary for lowering expressions, we need to be able to get the schema of arbitrary `PhysNode`s.
> refactor(rust): Add output_schema to all PhysNodes

- crates/polars-time/src/upsample.rs
- py-polars/tests/unit/dataframe/test_upsample.py
In the case of `group_by` being provide as an extra argument to `upsample`, the index needs to be only sorted within those groups. This tries to fix the issue observed in https://github.com/pola-rs/polars/issues/18229.
Tests are added to check that
- No error occurs if the index is only sorted within groups and groups are provided.
- An error occurs if the index is only sorted within groups and _no_ groups are provided.
Note, this is my first commit and **I am not a Rust developer**.
> fix: Arguments for `upsample` only have to be sorted within groups

- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/lazyframe/test_serde.py
Doesn't need to be human readable. Especially since json cannot support all our state, so this may not round-trip. Also want to remove it, so I can drop the serde proc macro's on our DSL.
> refactor(python): Deprecate serialize json for LazyFrame

- crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
- py-polars/tests/unit/operations/test_slice.py
> perf: Slice pushdown for SimpleProjection

- crates/polars-arrow/src/array/binview/mutable.rs
- crates/polars-arrow/src/array/binview/view.rs
- crates/polars-arrow/src/trusted_len.rs
- crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs
- crates/polars-parquet/src/arrow/read/deserialize/binary/decoders.rs
- crates/polars-parquet/src/arrow/read/deserialize/binview.rs
- crates/polars-parquet/src/parquet/encoding/delta_bitpacked/decoder.rs
- crates/polars-parquet/src/parquet/encoding/delta_bitpacked/mod.rs
This introduces an intermediate buffer for decode `DELTA_LENGTH_BYTE_ARRAY` lengths. This has the benefits that we can dispatch to fast paths for many common cases.
For the following dataset.
```python
import pyarrow as pa
import pyarrow.parquet as pq
import uuid
NUM_ROWS = 10_000_000
LENGTH = 9
cols = {
'a': pa.array([str(uuid.uuid4())[:LENGTH] for _ in range(NUM_ROWS)]),
'b': pa.array([str(uuid.uuid4())[:LENGTH] for _ in range(NUM_ROWS)]),
'c': pa.array([str(uuid.uuid4())[:LENGTH] for _ in range(NUM_ROWS)]),
'd': pa.array([str(uuid.uuid4())[:LENGTH] for _ in range(NUM_ROWS)]),
'e': pa.array([str(uuid.uuid4())[:LENGTH] for _ in range(NUM_ROWS)]),
}
tab = pa.table(cols)
pq.write_table(
tab, 'test.parquet',
compression="NONE",
use_dictionary=False,
column_encoding={
'a': …
```
> perf: Batch `DELTA_LENGTH_BYTE_ARRAY` decoding

- crates/polars-io/src/ndjson/core.rs
- crates/polars-plan/src/plans/functions/count.rs
Fixes: https://github.com/pola-rs/polars/issues/18258
Some codepaths included in json flag needed imports that are only supplied by possibly other (parquet/ipc + parquet) flags but not with json flag and polars_io::SerReader was missing altogether.
Not sure if this is the way you handle flags for this repo, you can let me know if within function imports are preferred? It could be better in case of use polars_io::SerReader's case, since requiring count_rows_ndjson function is behind a json flag already.
> fix: Json feature flag missing imports

- crates/polars-plan/src/dsl/functions/correlation.rs
- py-polars/tests/unit/operations/rolling/test_rolling.py
> fix: Compute joint null mask before calling rolling corr/cov stats

- py-polars/docs/source/reference/dataframe/export.rst
- py-polars/docs/source/reference/dataframe/modify_select.rst
- py-polars/docs/source/reference/series/export.rst
- py-polars/docs/source/reference/series/modify_select.rst
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/engine_config.py
- py-polars/polars/series/series.py
I was adding docs for these in Narwhals and noticed they don't appear in the Polars docs. Let's add them!
> docs: Document `DataFrame.__getitem__` and `Series.__getitem__`

- crates/polars-core/src/utils/mod.rs
We can follow up with a alignment strategy that never rechunks. This fixes the completely unneeded case.
> perf: Don't rechunk aligned chunks in owned_binary_chunk_align

- py-polars/docs/source/reference/series/aggregation.rst
- py-polars/docs/source/reference/series/computation.rst
- py-polars/docs/source/reference/series/index.rst
- py-polars/docs/source/reference/series/operators.rst
Closes https://github.com/pola-rs/polars/issues/17786
Missing doc items identified by looking at any methods without links [here](https://docs.pola.rs/api/python/stable/reference/series/index.html#:~:text=2%0A%20%20%20%20%20%20%20%203%0A%5D-,Methods%3A,-abs). Have validated that all works as expected against a local docs build.
Also note that `Series` does not implement many of the operator methods offered on DataFrame.
> docs(python): Add missing `Series` methods to API reference

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-plan/src/plans/builder_dsl.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/functions/dsl.rs
- py-polars/tests/unit/operations/test_slice.py
> fix: Fix group-by slice on all keys

- crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs
- crates/polars-parquet/src/arrow/read/deserialize/null.rs
- crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
- crates/polars-parquet/src/parquet/read/compression.rs
- crates/polars/tests/it/io/parquet/read/mod.rs
This only decompresses pages if they are actually going to be read from. This is only possible for unnested values and should save quite some time on slice pushdown and `parallel=prefiltered`.
> perf: Lazy decompress Parquet pages

- crates/polars-python/src/lazyframe/visit.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
This covers the remaining "easy" ones where we just need to pass names and some trivial information through.
> refactor(rust): Expose many more function expressions to python IR

- crates/polars-arrow/src/offset.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs
- crates/polars-parquet/src/arrow/read/deserialize/binview.rs
- crates/polars-parquet/src/arrow/read/deserialize/boolean.rs
- crates/polars-parquet/src/arrow/read/deserialize/dictionary.rs
- crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary.rs
- crates/polars-parquet/src/arrow/read/deserialize/nested.rs
- crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs
- crates/polars-parquet/src/arrow/read/deserialize/null.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/mod.rs
- crates/polars-parquet/src/arrow/read/deserialize/utils/array_chunks.rs
- crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
- crates/polars-parquet/src/arrow/write/binary/basic.rs
- crates/polars-parquet/src/arrow/write/binary/nested.rs
- crates/polars-parquet/src/arrow/write/binview/basic.rs
- crates/polars-parquet/src/arrow/write/binview/nested.rs
- crates/polars-parquet/src/arrow/write/boolean/basic.rs
- crates/polars-parquet/src/arrow/write/boolean/nested.rs
- crates/polars-parquet/src/arrow/write/dictionary.rs
- crates/polars-parquet/src/arrow/write/fixed_len_bytes.rs
- crates/polars-parquet/src/arrow/write/mod.rs
- crates/polars-parquet/src/arrow/write/primitive/basic.rs
- crates/polars-parquet/src/arrow/write/primitive/nested.rs
- py-polars/tests/unit/io/test_parquet.py
This fixes several small parquet problems.
I would recommend reviewing this PR commit by commit.
Fixes #18304.
Fixes #18303.
> fix: Parquet several smaller issues

- crates/polars-core/src/schema.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-plan/src/plans/expr_ir.rs
- crates/polars-plan/src/plans/options.rs
- crates/polars-stream/src/execute.rs
- crates/polars-stream/src/expression.rs
- crates/polars-stream/src/graph.rs
- crates/polars-stream/src/nodes/multiplexer.rs
- crates/polars-stream/src/physical_plan/lower_expr.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/mod.rs
- crates/polars-stream/src/skeleton.rs
Most non-elementwise expressions still fall back to the in-memory-map, but at least the groundwork is laid for lowering more and more expressions to the streaming engine over time.
Known bug: common subexpression elimination does not work for the streaming engine in general.
An example:
```python
df.lazy().select(
gt_avg = pl.col.x.filter(pl.col.x > pl.col.x.mean()).sum(),
mae = (pl.col.x - pl.col.y).abs().mean()
)
```
> refactor(rust): Lower arbitrary expressions in the new streaming engine

- crates/polars-error/src/lib.rs
You can now specify `POLARS_BACKTRACE_IN_ERR=1` to include a Rust backtrace inside errors to see where they get created:
```python
>>> df = pl.DataFrame({"x": [1]})
>>> df.select(pl.col.y)
File "/Users/orlp/programming/rust/polars/py-polars/polars/dataframe/frame.py", line 8853, in select
return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/orlp/programming/rust/polars/py-polars/polars/lazyframe/frame.py", line 2034, in collect
return wrap_df(ldf.collect(callback))
^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.ColumnNotFoundError: y
Rust backtrace:
0: std::backtrace_rs::backtrace::libunwind::trace
at …
```
> feat: Add POLARS_BACKTRACE_IN_ERR for debugging

- py-polars/polars/_typing.py
- py-polars/polars/datatypes/_parse.py
- py-polars/polars/datatypes/classes.py
- py-polars/polars/datatypes/convert.py
- py-polars/polars/schema.py
- py-polars/tests/unit/test_errors.py
- py-polars/tests/unit/test_schema.py
A few updates that largely finish making interop between Polars/Python types a little smoother and more consistent for the `DataType` and `Schema` classes.
* Adds missing conversion/mapping for Struct and Object dtypes.
* Adds a `to_python` method to both DataType and Schema classes.
* Parses any Python types given to Schema `__init__` (or `__setitem__`).
In addition to making Schema init consistent with the allowed DataFrame/Series dtype init this looser schema definition can also be helpful during EDA, for example, before assigning more exact/specific dtypes in a final production pipeline.
```python
schema = pl.Schema({
"foo": pl.Int8(),
"bar": pl.String(),
"baz": pl.Object(),
"ham": pl.Categorical("lexical"),
"spam": pl.Struct({"time": …
```
> feat(python): Improve Schema and DataType interop with Python types

- crates/polars-lazy/src/frame/mod.rs
Closes https://github.com/pola-rs/polars/issues/18318.
Sadly does mean we compile the plan twice now when `POLARS_AUTO_NEW_STREAMING` is set and the query fails the first time.
> refactor(rust): Disable common sub-expr elim for new streaming engine

- Cargo.lock
- crates/polars-core/src/datatypes/_serde.rs
- crates/polars-core/src/serde/series.rs
- crates/polars-core/src/utils/mod.rs
- crates/polars-error/src/lib.rs
- crates/polars-io/src/cloud/polars_object_store.rs
- crates/polars-io/src/parquet/read/mmap.rs
- crates/polars-io/src/parquet/read/mod.rs
- crates/polars-io/src/parquet/read/predicates.rs
- crates/polars-io/src/utils/byte_source.rs
- crates/polars-io/src/utils/mod.rs
- crates/polars-io/src/utils/slice.rs
- crates/polars-plan/src/plans/conversion/scans.rs
- crates/polars-plan/src/plans/functions/count.rs
- crates/polars-stream/Cargo.toml
- crates/polars-stream/src/async_executor/mod.rs
- crates/polars-stream/src/async_executor/task.rs
- crates/polars-stream/src/async_primitives/distributor_channel.rs
- crates/polars-stream/src/nodes/mod.rs
- crates/polars-stream/src/nodes/parquet_source.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/mod.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
- crates/polars-stream/src/utils/mod.rs
- crates/polars-stream/src/utils/notify_channel.rs
- crates/polars-stream/src/utils/task_handles_ext.rs
- crates/polars-utils/Cargo.toml
- crates/polars-utils/src/mem.rs
- crates/polars-utils/src/mmap.rs
Enables scanning parquet files in the new streaming engine. This is done via a new parquet source
node that has been built to run natively on the new async executor for maximum performance.
<details>
<summary>Dataset generation</summary>
```python
import os
os.environ["POLARS_VERBOSE"] = "1"
from pathlib import Path
prefix = Path(".env/data/")
file_path = prefix / "data.parquet"
partitioned_files_path = prefix / "data"
def write_datasets():
cols = {}
for i in range(10):
cols[f"a{i}"] = range(50_000_000)
cols[f"b{i}"] = range(-50_000_000, 0)
cols[f"c{i}"] = "a_string_value"
cols[f"d{i}"] = "another_string_value"
cols[f"e{i}"] = date.today()
df = pl.DataFrame(data=cols).select(
(1 + pl.int_range(pl.len()) // 1_000_000).alias("partition_id"), …
```
> refactor(rust): Add parquet source node to new streaming engine

- py-polars/docs/source/reference/expressions/aggregation.rst
Resolves #18334.
The missing entries now appear in the generated Python documentation.
> docs(python): Add missing aggregation entries (#18334)

- crates/polars-stream/src/physical_plan/to_graph.rs
- crates/polars-stream/src/skeleton.rs
During our lowering to a PhysicalPlan we end up producing some physical plan nodes that end up going unused (e.g. because a node ends up being input independent). We ended up spawning execution graph nodes for this which caused failed asserts, etc.
> refactor(rust): Only instantiate used portion of graph

- crates/polars-io/src/parquet/read/async_impl.rs
- crates/polars-io/src/parquet/read/metadata.rs
- crates/polars-io/src/parquet/read/mod.rs
- crates/polars-io/src/parquet/read/predicates.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-parquet/src/arrow/read/mod.rs
- crates/polars-parquet/src/arrow/read/statistics/mod.rs
- crates/polars-stream/src/nodes/parquet_source.rs
- crates/polars/tests/it/io/parquet/arrow/mod.rs
- crates/polars/tests/it/io/parquet/arrow/write.rs
fixes #18319
I am convinced we need a metadata supertype so we can amortize this as we need this all over.
We also need the arrow schema to be backed by an `IndexSet`. Currently we need a linear search to get a dtype.
> perf: Partition metadata for parquet statistic loading

- py-polars/polars/_utils/construction/series.py
- py-polars/polars/datatypes/_parse.py
- py-polars/tests/unit/constructors/test_series.py
addresses part of #18127
`pd.Timestamp` subclasses `datetime.datetime`, but the current code checks type too tightly (`elif input is datetime`)
> feat: Respect input time zone if input is pandas Timestamp

- crates/polars/src/lib.rs
document env var added in https://github.com/pola-rs/polars/commit/380db3263a64771482e0422441c805a6f5977fd3
> docs: Document POLARS_BACKTRACE_IN_ERR env var

- README.md
rustc version should be >=`1.80`. 
refer to https://blog.rust-lang.org/2024/07/25/Rust-1.80.0.html, `impl Default for Arc<[T]>` is stable in rustc 1.80.
Close #18356
> chore: Fix the required version of rust in README.md

- crates/polars-plan/src/plans/functions/count.rs
- py-polars/tests/unit/io/test_lazy_count_star.py
- py-polars/tests/unit/io/test_lazy_csv.py
re-opened, this time with 100% plaintext 😁
> fix: Fix compressed ndjson row count

- crates/polars-plan/src/plans/ir/dot.rs
- crates/polars-plan/src/plans/ir/format.rs
- crates/polars-plan/src/plans/ir/mod.rs
- crates/polars-stream/src/physical_plan/mod.rs
> refactor(rust): Improve dot formatting of new-streaming parquet source

- crates/polars-plan/src/plans/functions/count.rs
Very minor fix - ran into this while working on Polars Cloud.
See line 115 of the affected file - it uses the functionality that is gated behind the `json` feature in the `parquet` feature flag.
> fix(rust): Fix broken feature gate for `ParquetReader`

- crates/polars-stream/src/execute.rs
- crates/polars-stream/src/graph.rs
- crates/polars-stream/src/nodes/filter.rs
- crates/polars-stream/src/nodes/in_memory_map.rs
- crates/polars-stream/src/nodes/in_memory_sink.rs
- crates/polars-stream/src/nodes/in_memory_source.rs
- crates/polars-stream/src/nodes/map.rs
- crates/polars-stream/src/nodes/mod.rs
- crates/polars-stream/src/nodes/multiplexer.rs
- crates/polars-stream/src/nodes/ordered_union.rs
- crates/polars-stream/src/nodes/parquet_source.rs
- crates/polars-stream/src/nodes/reduce.rs
- crates/polars-stream/src/nodes/select.rs
- crates/polars-stream/src/nodes/simple_projection.rs
- crates/polars-stream/src/nodes/streaming_slice.rs
- crates/polars-stream/src/nodes/zip.rs
- crates/polars-stream/src/physical_plan/fmt.rs
- crates/polars-stream/src/physical_plan/lower_expr.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/mod.rs
- crates/polars-stream/src/skeleton.rs
Just bumping that failure count down :)
> refactor(rust): Various small fixes for the new streaming engine

- crates/polars-plan/src/dsl/mod.rs
Necessary for the new streaming engine, but also fixes this (obscure) bug in the current engine:
```python
>>> df = pl.DataFrame({"a": [1, 2, 3, 2, 1]})
>>> df.group_by("a").agg(pl.col("a").lower_bound().alias("lower"))
File "/Users/orlp/.localpython/lib/python3.11/site-packages/polars/dataframe/group_by.py", line 231, in agg
.collect(no_optimization=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/orlp/.localpython/lib/python3.11/site-packages/polars/lazyframe/frame.py", line 2027, in collect
return wrap_df(ldf.collect(callback))
^^^^^^^^^^^^^^^^^^^^^
polars.exceptions.InvalidOperationError: output length of `map` (1) must be equal to the input length (5); consider using `apply` instead
Error originated in expression: …
```
> fix: Mark Expr.(lower|upper)_bound as returning scalar

- crates/polars-stream/src/physical_plan/lower_expr.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/mod.rs
- crates/polars-stream/src/skeleton.rs
This fixes issues that the new streaming engine had, such as this:
```python
>>> df = pl.DataFrame({"x": [1, 2, 3]})
>>> df.select(pl.col.x.max().sin())
shape: (1, 1)
┌─────────┐
│ x       │
│ ---     │
│ f64     │
╞═════════╡
│ 0.14112 │
└─────────┘
>>> df.lazy().select(pl.col.x.max().sin()).collect(new_streaming=True)
shape: (3, 1)
┌──────────┐
│ x        │
│ ---      │
│ f64      │
╞══════════╡
│ 0.841471 │
│ 0.909297 │
│ 0.14112  │
└──────────┘
```
> refactor(rust): Recursively evaluate is_elementwise for function expressions

- py-polars/docs/source/reference/expressions/array.rst
- py-polars/docs/source/reference/expressions/functions.rst
- py-polars/docs/source/reference/expressions/list.rst
- py-polars/docs/source/reference/expressions/name.rst
- py-polars/docs/source/reference/expressions/operators.rst
- py-polars/docs/source/reference/expressions/string.rst
- py-polars/docs/source/reference/lazyframe/index.rst
- py-polars/docs/source/reference/series/array.rst
- py-polars/docs/source/reference/series/attributes.rst
- py-polars/docs/source/reference/series/export.rst
- py-polars/docs/source/reference/series/index.rst
- py-polars/docs/source/reference/series/list.rst
- py-polars/docs/source/reference/series/miscellaneous.rst
- py-polars/docs/source/reference/sql/functions/aggregate.rst
It is evident based on the existing API reference that the methods are intended to be in alphabetical order (and they mostly are).
This does the remainder.
Note that there were a few exceptions where I decided alphabetical order was not better. `strip_chars_end` coming after `strip_chars_start` being one example. Let me know if you have a difference of opinion.
> docs(python): Alphabetise methods in Python API reference

- crates/polars-ops/src/series/ops/search_sorted.rs
Fixes https://github.com/pola-rs/polars/issues/16943.
Fixes https://github.com/pola-rs/polars/issues/16476.
> fix: Allow search_sorted on boolean series

- crates/polars-parquet/src/arrow/read/schema/metadata.rs
fixes #14639
When encountering a map column (which in Arrow is a `List<Struct<K, V>>`), the code failed to recursively convert subtypes into valid Polars types. This caused an error when a map column contained a string (UTF-8) type, as it would not convert the UTF-8 column into a UTF-8 view type, leading to type assertion failures later.
> fix: Recurse on map field during type conversion

- crates/polars-parquet/src/arrow/read/deserialize/binview.rs
```
$ POLARS_MAX_THREADS=1 poop './plparbench-before 10 plain.parquet auto' './plparbench-after 10 plain.parquet auto'
Benchmark 1 (3 runs): ./plparbench-before 10 plain.parquet auto
measurement          mean ± σ            min … max           outliers         delta
wall_time          13.0s  ±  701ms    12.5s  … 13.8s           0 ( 0%)        0%
peak_rss           1.46GB ±  407KB    1.46GB … 1.46GB          0 ( 0%)        0%
cpu_cycles         37.9G  ± 84.2M     37.8G  … 38.0G           0 ( 0%)        0%
instructions        113G  ± 46.7M      113G  …  113G           0 ( 0%)        0%
cache_references    426M  ±  397K      425M  …  426M           0 ( 0%)        0%
cache_misses        111M  ±  777K      110M  …  112M           0 ( 0%)        0%
branch_misses       634K  ± 53.6K      597K  … …
```
> perf: Batch Plain Parquet UTF-8 verification

- crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs
- crates/polars-parquet/src/arrow/read/deserialize/utils/filter.rs
- crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
- py-polars/tests/unit/io/test_parquet.py
Fixes #18400.
This completely rewrites the logic that deal with decoding filtered nested values. This was needed to accommodate the fact that any kind of row value might span several data pages. This was not really accounted for in the previous implementation and where it worked, it was mostly by coincidence.
This also made it possible to add many fast paths for the decoder that were previously not there. Therefore, I think there are also some performance improvements here, but I am not sure how much.
I also wrote two tests to make sure that it actually works.
> fix: Parquet nested values that span several pages

- crates/polars-io/src/csv/read/splitfields.rs
Fixes https://github.com/pola-rs/polars/issues/18409.
> fix(rust): Unsoundness in CSV SplitFields

- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
The group by window can go back to `2021-12-15 23:00:00` depending on the end-point option `closed` as shown by the code examples. Hence removing the misleading comment "... starting at 2021-12-16 00:00:00".
> docs(python): Fix incorrect comments in `group_by_dynamic`

- py-polars/polars/functions/range/date_range.py
- py-polars/polars/functions/range/datetime_range.py
There currently aren't any examples without `eager=True`, and the question of what the (default) `eager=False` variant is for comes up sometimes
> docs(python): Add date_range and datetime_ranges examples without `eager=True`

- crates/polars-lazy/src/dsl/functions.rs
- crates/polars-lazy/src/frame/cached_arenas.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/scan/csv.rs
- crates/polars-lazy/src/scan/ipc.rs
- crates/polars-lazy/src/scan/parquet.rs
- crates/polars-lazy/src/tests/predicate_queries.rs
- crates/polars-lazy/src/tests/queries.rs
- crates/polars-plan/src/frame/opt_state.rs
- crates/polars-plan/src/plans/builder_dsl.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
- crates/polars-plan/src/plans/mod.rs
- crates/polars-plan/src/plans/optimizer/mod.rs
- crates/polars-plan/src/plans/schema.rs
- crates/polars-python/src/lazyframe/general.rs
This is preparation for a fix where we set `CSE` in eager if we apply expression expansion.  This is required as those expressions look stateful in the API, whilst it actually is syntactic sugar for multiple expressions. `CSE` will hide the symptoms here and align with expectation (except for random).
> refactor(rust): Group arguments in conversion in a Context

- crates/polars-io/src/csv/read/splitfields.rs
For some slice `v` of length `n`, it is UB to call `get_unchecked` with a range starting at `n+1`. Previously, we asserted that `pos <= n`, which is the requirement for `v.get_unchecked(..pos)`, but not `v.get_unchecked(pos+1..)` which has the tighter requirement `pos < n`.
While here, after #18413, tighten the extent of an unsafe block.
> refactor(rust): Fencepost error in debug assertion in splitfields

- py-polars/polars/functions/lazy.py
- py-polars/tests/unit/datatypes/test_temporal.py
addresses the ci failure https://github.com/pola-rs/polars/actions/runs/10597709102/job/29368505390?pr=18426
also closes #17796  (simple drive-by)
> test: Address spurious hypothesis test failure

- crates/polars-arrow/src/bitmap/bitmap_ops.rs
- crates/polars-arrow/src/bitmap/immutable.rs
- crates/polars-arrow/src/datatypes/mod.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-parquet/src/arrow/read/deserialize/binview.rs
- crates/polars-parquet/src/arrow/read/deserialize/boolean.rs
- crates/polars-parquet/src/arrow/read/deserialize/dictionary.rs
- crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary.rs
- crates/polars-parquet/src/arrow/read/deserialize/nested.rs
- crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs
- crates/polars-parquet/src/arrow/read/deserialize/null.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/float.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
- crates/polars-parquet/src/arrow/read/deserialize/primitive/mod.rs
- crates/polars-parquet/src/arrow/read/deserialize/simple.rs
- crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
- crates/polars-parquet/src/parquet/page/mod.rs
- py-polars/tests/unit/io/test_parquet.py
- Only verify UTF-8 on a dictionary page once (*duh*)
- Don't even worry about the page validity if it is never null
- Dispatch between pre-filter and post-filter for `parallel=prefiltered`.
> perf: Several large parquet optimizations

- crates/polars-core/src/chunked_array/builder/string.rs
> docs(rust): Fix BinViewChunkedBuilder arguments (#17277)

- py-polars/polars/dataframe/frame.py
> fix(python): Fixed `Worksheet` definition in `write_excel` type annotations

- py-polars/polars/testing/asserts/frame.py
- py-polars/polars/testing/asserts/series.py
- py-polars/tests/unit/testing/test_assert_frame_equal.py
- py-polars/tests/unit/testing/test_assert_series_equal.py
Closes #18401.
Ensures both of the "not_equal" asserts _also_ raise on mismatched input types, as their "equal" counterparts do; while such inputs are indeed technically _not equal_, that is not what the functions are testing.
Added quite a bit of bonus test coverage for the "not_equal" asserts while I was at it, along with additional validation of the expected assert error messages.
> fix(python): Ensure `assert_frame_not_equal` and `assert_series_not_equal` raise on mismatched input types

- crates/polars-pipe/src/executors/sinks/io.rs
Fixes a hung test `test_streaming_group_by_struct_key` for me.
> fix(rust): Add missing chunk align in pipe sink

- crates/polars-expr/src/expressions/column.rs
- crates/polars-io/src/ipc/ipc_reader_async.rs
- crates/polars-io/src/partition.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-ops/src/frame/join/mod.rs
- crates/polars-plan/src/dsl/function_expr/struct_.rs
- crates/polars-plan/src/dsl/struct_.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/expr_expansion.rs
- crates/polars-plan/src/plans/conversion/scans.rs
- crates/polars-plan/src/plans/functions/dsl.rs
- crates/polars-plan/src/plans/functions/schema.rs
- crates/polars-plan/src/plans/ir/tree_format.rs
- crates/polars-plan/src/plans/optimizer/cache_states.rs
- crates/polars-plan/src/plans/optimizer/collapse_and_project.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/joins.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/projection.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/rename.rs
- crates/polars-plan/src/plans/python/pyarrow.rs
- crates/polars-plan/src/utils.rs
- crates/polars-python/src/lazyframe/visitor/nodes.rs
- crates/polars-sql/src/context.rs
- crates/polars-sql/src/functions.rs
- crates/polars-sql/src/sql_expr.rs
- crates/polars-time/src/upsample.rs
- crates/polars-utils/src/pl_str.rs
- crates/polars/tests/it/core/joins.rs
- crates/polars/tests/it/io/csv.rs
- crates/polars/tests/it/lazy/expressions/literals.rs
* Organize the impls
* Some remaining cleanup of `.as_ref().into()` -> `.clone()`
* ~~Removes `From<&&str>`:~~ *breaks a lot of things - will do separately
* ~~Existing code calling with constant arrays are changed from e.g. `Series::new(_, &["a", ...])` to `Series::new(_, ["a", ...])`~~
* ~~`&[&str]` can no longer be passed to most API functions accepting `impl IntoIterator<Item = impl Into<PlSmallStr>>`~~
* Add `AsRef<Path>`, `AsRef<[u8]>`, `AsRef<OsStr>`
> refactor(rust): More refactor for PlSmallStr

- py-polars/polars/series/series.py
When using `POLARS_AUTO_NEW_STREAMING` `.to_physical()` can cause the output to be chunked.
> refactor(python): Ensure physical arguments to np ufuncs are rechunked

- crates/polars-plan/src/plans/aexpr/schema.rs
- crates/polars-plan/src/plans/conversion/expr_to_ir.rs
- crates/polars-plan/src/plans/conversion/functions.rs
- crates/polars-plan/src/plans/conversion/mod.rs
- crates/polars-plan/src/plans/conversion/type_coercion/binary.rs
- crates/polars-plan/src/plans/conversion/type_coercion/functions.rs
- crates/polars-plan/src/plans/conversion/type_coercion/is_in.rs
- crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
- py-polars/tests/unit/test_datatypes.py
- fix: Window expressions now show proper schema
- fix: Raise when namespace is called in invalid dtypes
- chore: Split up code for maintainability
- perf: Ensure we don't hit the function resolving every time
- perf: Delay alloction
fixes #18468
> fix: Various schema corrections

- py-polars/polars/series/series.py
@stinodego Theoretically backwards-incompatible, but I consider it a bug that the `Series` method did something different than the `Expr` method. However, in any sensible use-case of `Series.entropy` the probabilities would have already summed to 1, meaning that turning on normalize shouldn't *actually* change behavior for users.
> fix(python): Normalize by default in Series.entropy like Expr.entropy does

- docs/user-guide/expressions/plugins.md
- py-polars/polars/series/plotting.py
the way the user guide currently shows, it re-computes `plugin_path` each time the plugin function is called (probably my fault from https://github.com/pola-rs/polars/pull/14804)
> docs: Pre-compute plugin_path before defining plugin

- crates/polars-core/src/chunked_array/bitwise.rs
- py-polars/tests/unit/operations/test_bitwise.py
Fixes https://github.com/pola-rs/polars/issues/18442.
I noticed also that the `xor` operation uses the `or` operation when dealing with single `None` column, wheras in multiple `None` values column, it takes the general path, which is `xor` operation:
```rust
fn bitxor(self, rhs: Self) -> Self::Output {
match (self.len(), rhs.len()) {
// make sure that we fall through if both are equal unit lengths
// otherwise we stackoverflow
(1, 1) => {},
(1, _) => {
return match self.get(0) {
Some(true) => {
let mut rhs = rhs.not();
rhs.rename(self.name().clone());
rhs
},
Some(false) => {
let mut rhs = rhs.clone();
rhs.rename(self.name().clone());
rhs
},
None => &self.new_from_index(0, rhs.len()) | rhs,
};
},
(_, 1) => {
return match rhs.get(0) {
Some(true) => self.not(),
Some(false) => self.clone(), …
```
> fix: Wrong output column name in `or` and `xor` operations

- crates/polars-plan/src/plans/conversion/expr_expansion.rs
- py-polars/tests/unit/test_selectors.py
> fix: Properly raise on invalid selector expressions

- crates/polars-plan/src/client/check.rs
- crates/polars-plan/src/dsl/expr.rs
- crates/polars-plan/src/dsl/expr_dyn_fn.rs
- crates/polars-plan/src/dsl/python_udf.rs
- py-polars/tests/unit/cloud/test_prepare_cloud_plan.py
- py-polars/tests/unit/test_serde.py
Changes:
* Update `Expr::AnonymousFunction` to implement SerDe for Python functions.
* Update `Expr::RenameAlias` to raise an error when serializing instead of simply being skipped. Can implement SerDe for this later.
* Update the Polars Cloud prep functionality accordingly.
> feat(python): Make expressions containing Python UDFs serializable

- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/io/database/test_write.py
This is my first contribution to polars! Feedback welcome.
Fixes https://github.com/pola-rs/polars/issues/18478
It's a simple one line fix that allows things like properly creating temporary tables when using any ADBC driver. The test I added is written for sqlite3, but it also works when using the Postgres ADBC driver.
> fix(python): DataFrame.write_database() not passing along engine_options when using ADBC

- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
closes https://github.com/pola-rs/polars/issues/18377
~~the ewm_mean part can be improved too...will address this a bit later today~~
This does a few things:
- corrects the formula for `ewm_mean_by` to include `1-` for `\alpha`
- makes the `ewm_mean` variable for `half-life` consistent with the `ewm_mean_by` one (and also with https://quant.stackexchange.com/a/46197)
- adds verbs at the beginning of these docstrings
> docs(python): Fix formula in ewm_mean_by

- crates/polars-utils/src/pl_str.rs
From `PlSmallStr`, `&PlSmallStr`, and all the iterator types that `String::from_iter` supports
> refactor(rust): Add `FromIterator` impls for `PlSmallStr`

- py-polars/polars/functions/eager.py
- py-polars/tests/unit/functions/test_functions.py
Internally `align_frames` uses joins, but the default behaviour for joins is for NULL values not to match, which can result in extraneous/incorrect rows being generated during frame alignment if the alignment column(s) contain such values.
This PR fixes that oversight 👌 
```python
"key": ["x", "y", None],
"value": [1, 2, 0],
})
"key": ["x", None, "z", "y"],
"value": [4, 3, 6, 5],
})
```
_Additional row gets (incorrectly) introduced:_
```python
pl.align_frames(df1, df2, on="key")
```
_Correct number of appropriately aligned rows:_
```python
pl.align_frames(df1, df2, on="key")
```
> fix(python): Address incorrect `align_frames` result when the alignment column contains NULL values

- py-polars/requirements-dev.txt
Numba, prior to version 0.54, did not provide upper bound pins for numpy. uv's backtracking resolver therefore assumes that 0.53.1 is compatible with new numpy releases. This causes problems for python versions >= 3.10 since that version of numba has a runtime dependency on python < 3.10.
Since numba 0.54 is already quite old (older than what is installed on any supported python version), just provide a lower-bound pin to stop uv backtracking too far. This way we can remove the pin on numpy again. See also astral-sh/uv#7020.
- Closes #18543
cc @stinodego
> ci: Add lower-bound pin for numba

- crates/polars-plan/src/plans/aexpr/mod.rs
- crates/polars-python/Cargo.toml
Minor updates to make the Polars Cloud worker work correctly.
> build(rust): Remove extension-module from polars-python

- crates/polars-plan/src/plans/optimizer/collapse_and_project.rs
- py-polars/tests/unit/lazyframe/optimizations.py
Fixes https://github.com/pola-rs/polars/issues/18558
> fix: Do not remove double-sort if `maintain_order=True`

- py-polars/polars/io/database/_executor.py
- py-polars/tests/unit/io/database/test_read.py
Closes #18526 👍 
We now raise a proper `DuplicateError` if/when the database result cursor contains multiple instances of the same column name; currently we map the cursor description to a Schema dict without checking for this, which eats any duplicates - this then goes on to raise a much less obvious error later.
> fix(python): Check for duplicate column names in `read_database` cursor result, raising `DuplicateError` if found

- crates/polars-python/src/map/mod.rs
- crates/polars-python/src/map/series.rs
- crates/polars-python/src/series/map.rs
- py-polars/tests/unit/operations/map/test_map_elements.py
Closes [#18472](https://github.com/pola-rs/polars/issues/18472)
This makes sure we respect the `return_dtype` if it's a `List` type, rather than discarding it and relying on auto-inference.
> fix: Fix `map_elements` for List return dtypes

- crates/polars-core/src/chunked_array/ops/aggregate/mod.rs
- crates/polars-core/src/chunked_array/ops/mod.rs
- crates/polars-core/src/series/implementations/boolean.rs
- crates/polars-core/src/series/implementations/date.rs
- crates/polars-core/src/series/implementations/datetime.rs
- crates/polars-core/src/series/implementations/decimal.rs
- crates/polars-core/src/series/implementations/duration.rs
- crates/polars-core/src/series/implementations/floats.rs
- crates/polars-core/src/series/implementations/mod.rs
- crates/polars-core/src/series/implementations/time.rs
- crates/polars-core/src/series/series_trait.rs
- crates/polars-expr/src/reduce/convert.rs
- crates/polars-expr/src/reduce/mean.rs
Now using `_sum_as_f64` and making sure to get the dtype from the input rather than the output (which is different for `Date`s).
> refactor(rust): Fix mean reduction in new-streaming

- crates/polars-python/src/lazyframe/visit.rs
The migration of `Schema` into its own crate in #18539 changed the (internal) field name from `inner` to the more obvious `fields`. This was exposed in the Python IR, so bump the major version.
cc: @ritchie46
> refactor(rust): Bump NodeTraverser major version

- crates/polars-lazy/src/dsl/list.rs
- py-polars/tests/unit/operations/namespaces/list/test_eval.py
- py-polars/tests/unit/operations/namespaces/list/test_list.py
Closes [#18510](https://github.com/pola-rs/polars/issues/18510)
> fix: Fix output type for `list.eval` in certain cases

- crates/polars-plan/src/dsl/function_expr/pow.rs
- py-polars/tests/unit/operations/test_group_by.py
We must transfer the name from the base column to the result so that the rule that the left operand produces the result name is obeyed.
- Closes #18524
> fix(rust): Ensure result name of pow matches schema in grouped context

- docs/user-guide/misc/multiprocessing.md
> docs: Fix multiprocessing docs regarding fork method check

- crates/polars-sql/src/context.rs
- crates/polars-sql/src/function_registry.rs
- crates/polars-sql/src/keywords.rs
- crates/polars-sql/src/lib.rs
- crates/polars-sql/src/sql_expr.rs
- crates/polars-sql/src/types.rs
- py-polars/tests/unit/sql/test_miscellaneous.py
Closes #18373.
* Shortcut-eval for common SQL "WHERE" clause filters such as:
* `WHERE TRUE`
* `WHERE FALSE`
* `WHERE 1 = 1`
* `WHERE 1 != 0`
This pattern is a bit weird, but often arises from programmatic query builders that want to append to a WHERE clause without having to check if a new filter is the first (so they can always "AND" it onto the existing clause). As a result a query may _always_ contain "WHERE 1=1" (or equivalent), with the expectation that it is optimised out.
When the SQL parser sees that a WHERE clause represents such a pattern it now skips frame filtering entirely, immediately returning the same frame (if TRUE) or an empty frame with an identical schema (if FALSE).
(Note: you usually see the "TRUE" version of this, but once in a blue moon you'll see something …
> feat(python): Support shortcut eval of common boolean filters in SQL interface "WHERE" clause

- crates/polars-expr/src/expressions/slice.rs
- py-polars/tests/unit/operations/test_slice.py
> fix: Fix group first value after group-by slice

- py-polars/docs/source/reference/config.rst
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
@nameexhaustion I think this may have been changed accidentally as part of #18566 ?
> ci: Fix Python docs build

- crates/polars-plan/src/plans/conversion/join.rs
- py-polars/tests/unit/operations/test_inequality_join.py
> refactor: Raise on suffixed predicate in join_where

- crates/polars-parquet/src/parquet/metadata/column_chunk_metadata.rs
- crates/polars-parquet/src/parquet/metadata/file_metadata.rs
- crates/polars-parquet/src/parquet/metadata/row_metadata.rs
- crates/polars-parquet/src/parquet/read/mod.rs
> perf: Remove cloning of `ColumnChunkMetadata`

- crates/polars-ops/src/chunked_array/list/namespace.rs
- py-polars/tests/unit/operations/namespaces/list/test_list.py
Fixes https://github.com/pola-rs/polars/issues/18039.
> fix(rust): Indicative error in `list.gather` when wrong indices type is supplied

- py-polars/tests/benchmark/test_join_where.py
This is a follow-up to #18365 to add a couple of benchmarks for the IEJoin algorithm.
These take around 0.01 s using a release build on my machine, compared with around 3 s if doing a cross join then filtering.
> test(python): Add benchmark tests for join_where with inequalities

- crates/polars-io/src/path_utils/mod.rs
- py-polars/tests/unit/io/test_scan.py
Also fixes a panic when the expanded paths were empty
> perf: Don't traverse file list twice for extension validation

- Cargo.lock
- crates/polars-core/src/schema.rs
- crates/polars-io/Cargo.toml
- crates/polars-io/src/csv/read/options.rs
- crates/polars-io/src/csv/write/writer.rs
- crates/polars-io/src/hive.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-io/src/utils/other.rs
- crates/polars-mem-engine/src/executors/projection_simple.rs
- crates/polars-mem-engine/src/planner/lp.rs
- crates/polars-pipe/src/executors/operators/reproject.rs
- crates/polars-pipe/src/executors/sinks/reproject.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/optimizer/cache_states.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
- crates/polars-schema/src/schema.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars/tests/it/io/csv.rs
* Move required methods to the main `polars_schema::Schema<D>` struct
* Split impls for `Schema<D>`, most functions don't need `D: Default + Clone`
> refactor(rust): Remove extra schema traits

- py-polars/polars/expr/expr.py
- py-polars/tests/unit/operations/test_replace.py
- py-polars/tests/unit/operations/test_replace_strict.py
Closes https://github.com/pola-rs/polars/issues/18185
> fix(python): Raise if single argument form in `replace`/`replace_strict` is not a mapping

- crates/polars-plan/src/dsl/expr.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/join.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/operations/test_inequality_join.py
@cmdlineluser we decided to go for your initial intuition. 
That is unambiguous and more versatile. It is not dependent on the order of the comparisons for one.
> refactor: Change join_where semantics

- crates/polars-io/Cargo.toml
That feature is never enabled, so we can't dump NDJSON with datetimes that contain timezones.
The original problem was described in https://github.com/elixir-explorer/explorer/issues/977
PS: I'm not really sure if we can get rid of the `chrono-tz` feature and consolidate all in the `timezones` feature there.
> fix: Enable "polars-json/timezones" feature from "polars-io"

- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
This is a small change to the join_where docs to add that this behaves like an inner join, and emphasise that row order isn't preserved.
> docs(python): Update join_where docs to clarify behaviour

- crates/polars-parquet/src/parquet/metadata/file_metadata.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_fetch.rs
- crates/polars-stream/src/nodes/parquet_source/row_group_data_fetch.rs
> refactor(rust): Push down max row group height calc to file metadata

- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/io/test_parquet.py
> fix(python): Use IO[bytes] instead of BytesIO in `DataFrame.write_parquet()`

- py-polars/polars/_utils/udfs.py
Still mildly painful to install/debug under the Python 3.13rc1, but here's another update for the `BytecodeParser`, building on #16304. Might be the last one needed, but will have to wait on the final release to be sure 🤔
We now recognise specific "superinstructions"[^1] and unpack them to the underlying individual instructions (eg: `LOAD_FAST_LOAD_FAST`→`LOAD_FAST`+`LOAD_FAST`).
```python
from polars._utils.udfs import BytecodeParser
bp = BytecodeParser(
function = lambda x: (x/x) * (x+x),
map_target = "expr",
)
```
* Python 3.11/3.12 bytecode:
```python
bp.dis()
```
* Python 3.13 bytecode (note presence of superinstructions):
```python
bp.dis()
```
* Result (across all Python versions):
```python
bp.to_expression("x")
```
[^1]: https://github.com/faster-cpython/ideas/issues/16
> feat(python): Update `BytecodeParser` for upcoming Python 3.13

- crates/polars-ops/src/series/ops/cut.rs
- py-polars/tests/unit/operations/test_qcut.py
This PR is fixing an issue where if `qcut` is called for a series wth only null values, and with labels as an argument, it will panic.
Fixing https://github.com/pola-rs/polars/issues/10876
I've modified `qcut` function to call `cut` with None as labels after detecting all values are null in the series.
A unit test was added to check this specific scenario
> fix(rust): Qcut all nulls panics

- crates/polars-io/src/csv/read/parser.rs
- crates/polars-io/src/csv/read/read_impl.rs
- crates/polars-io/src/csv/read/utils.rs
- crates/polars-io/src/json/mod.rs
- crates/polars-io/src/utils/compression.rs
- crates/polars-io/src/utils/mod.rs
- crates/polars-io/src/utils/other.rs
- crates/polars-mem-engine/src/executors/scan/csv.rs
- crates/polars-mem-engine/src/executors/scan/ndjson.rs
- crates/polars-plan/src/plans/conversion/scans.rs
- crates/polars-plan/src/plans/functions/count.rs
- py-polars/tests/unit/io/test_json.py
It looks like the bulk of the work for supporting on the fly decompression (https://github.com/pola-rs/polars/issues/8323) was already implemented. However there appeared to be a couple of inconsistencies, some of which this PR attempts to address. 
The first commit is refactoring the compression detection logic to only be performed in a single function, instead of checking prefix bytes in multiple places. It also moves `maybe_decompress_bytes` to live with other compression related code. 
The second commit is a small change to add automatic decompression for JSON files. This essentially mirrors what is done for the Lazy JSON reader + the CSV reader, adapted for use with `simd_json`
There does seem to be some extra unification work that could be done around CSV and Lazy reader …
> fix(rust): Refactor decompression checks and add support for decompressing JSON

- crates/polars-pipe/Cargo.toml
> fix(rust): Fix use of undeclared crate or module error

- crates/polars-arrow/src/storage.rs
Whenever we have `*mut T` to actually store an owning reference to `T`, that struct should also have `PhantomData<T>`.
https://github.com/rust-lang/rfcs/blob/master/text/0769-sound-generic-drop.md#phantom-data
> fix(rust): Add missing PhantomDatas to BackingStorage

- crates/polars-plan/src/plans/functions/count.rs
fix this compile error with following feature gate
```toml
polars = { version = "0.43", features = [
"lazy",
"async",
"parquet",
"is_in",
"dtype-categorical",
"performant",
] }
```
> fix(rust): fix `async` feature compile error

- crates/polars-core/src/datatypes/any_value.rs
- crates/polars-core/src/scalar/mod.rs
- crates/polars-expr/src/expressions/literal.rs
- crates/polars-plan/src/plans/lit.rs
- crates/polars-python/src/functions/lazy.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- py-polars/polars/functions/lit.py
- py-polars/tests/unit/expr/test_literal.py
> fix: Fix scalar literals

- crates/polars-stream/src/nodes/parquet_source/init.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_fetch.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_utils.rs
- crates/polars-stream/src/nodes/parquet_source/mod.rs
- crates/polars-stream/src/nodes/parquet_source/row_group_data_fetch.rs
- crates/polars-stream/src/nodes/parquet_source/row_group_decode.rs
More prep work for pre-filtering and some drive-bys
* Change `projected_arrow_fields` from `Vec<Field>` to `ArrowSchema`, we will need to use this for live/dead columns lookups in prefiltering
* Move parallelism splitting calculation to `calc_cols_per_thread` function, and avoid spawning short-lived tasks by processing small remainder batches on the current thread.
* Factor out more code into functions - `decode_all_columns`, `async fn filter_cols` ..
> refactor(rust): Refactor code into functions in new parquet source

- crates/polars-io/src/parquet/read/read_impl.rs
- py-polars/tests/unit/io/test_parquet.py
> fix: Parquet prefiltered with projection pushdown

- crates/polars-ops/src/frame/join/iejoin/mod.rs
- crates/polars-plan/src/plans/conversion/join.rs
- py-polars/tests/benchmark/test_join_where.py
- py-polars/tests/unit/operations/test_inequality_join.py
This implements the "piecewise merge join" algorithm (described in [this DuckDB article](https://duckdb.org/2022/05/27/iejoin.html#piecewise-merge-join)) to handle `join_where` with a single inequality, without using a cross join and filter.
I've reused the `IEJoin` join type internally due to the similarities in how these two join types are handled. Technically this isn't using the IEJoin algorithm but it is another type of inequality join, so this seems OK, but it could be pulled out into its own join type if needed.
> feat: Implement single inequality joins for join_where

- .github/workflows/lint-rust.yml
- crates/polars-utils/src/mmap.rs
This fix is similar to what was done in #18498. We also added windows to `lint-rust.yml` in CI to prevent similar issues from occuring again.
It fixes `cargo check` regression in windows as of 5c4e7e97a66007d3052042543486c42d23cfac74 with the message
```
$ cargo check --workspace --all-targets --all-features
...
--> crates\polars-utils\src\mmap.rs:130:20
|
130 | use polars_error::{polars_bail, PolarsResult};
|                    ^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
...
```
This is caused by #18532 at
https://github.com/pola-rs/polars/blob/ac2456c7ce4db7ac0acc2b259c84fbb09f747ab9/crates/polars-utils/src/mmap.rs#L127
https://github.com/pola-rs/polars/blob/ac2456c7ce4db7ac0acc2b259c84fbb09f747ab9/crates/polars-utils/src/mmap.rs#L311-L319
> refactor(rust): Allow polars to pass cargo check on windows

- crates/polars-python/src/expr/general.rs
They seems have been unused after #8098, but not removed.
> refactor(python): Remove unused methods

- crates/polars-core/src/frame/mod.rs
- crates/polars-mem-engine/src/executors/stack.rs
- py-polars/tests/unit/dataframe/test_extend.py
> fix: Fix accidental raise on shape 1

- docs/_build/API_REFERENCE_LINKS.yml
- docs/_build/scripts/macro.py
- docs/index.md
- docs/src/python/user-guide/lazy/gpu.py
- docs/user-guide/gpu-support.md
- docs/user-guide/installation.md
- docs/user-guide/lazy/gpu.md
- docs/user-guide/lazy/index.md
- docs/user-guide/misc/multiprocessing.md
- mkdocs.yml
- py-polars/docs/source/reference/lazyframe/gpu_engine.rst
- py-polars/docs/source/reference/lazyframe/index.rst
- py-polars/polars/lazyframe/engine_config.py
- py-polars/polars/lazyframe/frame.py
This PR adds initial documentation for the beta Polars GPU engine. It includes:
- A general overview of the beta GPU engine in the user guide, including information on what's supported, how it works, testing, interoperability, installation, and similar
- Updated docs for the GPUEngine configuration object
- Minor updates to API docs where relevant
> docs(python): Add documentation for beta gpu support

- crates/polars-stream/src/nodes/in_memory_source.rs
- crates/polars-stream/src/nodes/input_independent_select.rs
- crates/polars-stream/src/nodes/mod.rs
- crates/polars-stream/src/physical_plan/fmt.rs
- crates/polars-stream/src/physical_plan/lower_expr.rs
- crates/polars-stream/src/physical_plan/mod.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
- py-polars/tests/unit/streaming/test_streaming_io.py
This involves a temporary and fragile hack, where we make the `InMemorySource` node always produce at least 1 morsel, even if that morsel is empty. This makes the `FastCount` work for now. 
This is fragile because other nodes may not preserve this morsel, we should remove this once we properly lower `FunctionIR` to a physical plan.
> refactor(rust): Fix input independence tests in new-streaming engine

- crates/polars-ops/src/series/ops/cum_agg.rs
> fix: Fix `cum_max` using exception text of `cum_min` for invalid dtype

- Cargo.lock
- crates/polars-io/src/parquet/read/read_impl.rs
- py-polars/Cargo.toml
- py-polars/tests/unit/io/test_lazy_parquet.py
Fixes https://github.com/pola-rs/polars/issues/18739
Fixes https://github.com/pola-rs/polars/issues/18779
> fix: Dropped/shifted rows in parquet scan with `streaming=True`

- crates/polars-stream/src/nodes/parquet_source/metadata_fetch.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_utils.rs
ArrowSchema lookup is now O(1)
> refactor: Remove extra hashmap construction in new-streaming parquet

- py-polars/polars/expr/expr.py
I'm suggesting a few changes to the `over` docs:
- add an example with `order_by`
- show how to use `mapping_strategy='explode'` properly
- simplify a bit
> docs(python): Improve `over` docs, add example with `order_by`

- crates/polars-core/src/chunked_array/ops/zip.rs
- py-polars/tests/unit/functions/test_when_then.py
> fix: Broadcast zip_with for structs

- crates/polars-core/src/frame/mod.rs
- crates/polars-expr/src/expressions/sortby.rs
- crates/polars-expr/src/planner.rs
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/test_empty.py
As I see it, sorting with `by=[]` is equivalent to sorting using the empty row as key value, and all empty rows are by definition equal. So this should just successfully return the original input. `DataFrame.sort` already did this, now `Expr.sort_by` also does.
> fix: Allow empty sort by columns

- docs/development/contributing/index.md
- mkdocs.yml
This PR makes some minor improvements to the contributing guide, reflecting the experience I just had setting everything up.
- Add two notes to things that are required when setting up the dev environment for the first time and when building the docs for the first time.
- Fix formatting of a nested list that was being poorly formatted by `dprint` because it uses a different standard from the one followed by the markdown parser used by MkDocs.
- Add a “copy to clipboard” button to all code snippets which is SUCH a quality of life improvement!
> docs: Minor improvements to contributing guide

- crates/polars-python/src/lazyframe/visit.rs
This enables us the create the GPU callback in Polars Cloud.
> refactor(python): Make `NodeTraverser` struct public

- crates/polars-io/src/parquet/read/reader.rs
- crates/polars-io/src/parquet/read/utils.rs
- crates/polars-mem-engine/src/executors/scan/mod.rs
- crates/polars-mem-engine/src/executors/scan/parquet.rs
- crates/polars-pipe/src/executors/sources/parquet.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
Fixes https://github.com/pola-rs/polars/issues/18568
Fixes https://github.com/pola-rs/polars/issues/17254
* Support reading from a list of parquet files that have the same set of columns, but not necessarily in the same order
* The dtype of every column must be equal
* When the files have differing columns:
* If there are extra columns in files following the first file, those columns are silently ignored (not read)
* Let me know if we want to error here instead
* If there are columns in the first file missing from the files after it, an error will be raised. Later I will make a PR to introduce an option to instead project NULL rows for this case.
> feat: Relaxed schema alignment for parquet file list read

- crates/polars-python/src/export.rs
- crates/polars-python/src/lib.rs
This allows dependent code in the Polars Cloud worker to use the same PyO3 version.
> refactor(python): Re-export PyO3 in `polars-python` crate

- crates/polars-core/src/series/any_value.rs
> fix(rust): Handle AnyValue::Struct to prevent null returns

- crates/polars-io/src/json/mod.rs
- py-polars/tests/unit/io/test_json.py
fixes https://github.com/pola-rs/polars/issues/7355
new issue after closing https://github.com/pola-rs/polars/pull/18663 due to skill issues with git
> fix(rust): Return empty DF when input is empty json list

- py-polars/polars/functions/lit.py
They seem to have been wrong for a long time.
> docs(python): Fix literal type mapping example in `lit` docstrings

- crates/polars-arrow/src/legacy/kernels/rolling/mod.rs
- crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/mean.rs
- crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/min_max.rs
- crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/mod.rs
- crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/quantile.rs
- crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/sum.rs
- crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/variance.rs
- crates/polars-arrow/src/legacy/kernels/rolling/nulls/mean.rs
- crates/polars-arrow/src/legacy/kernels/rolling/nulls/min_max.rs
- crates/polars-arrow/src/legacy/kernels/rolling/nulls/mod.rs
- crates/polars-arrow/src/legacy/kernels/rolling/nulls/quantile.rs
- crates/polars-arrow/src/legacy/kernels/rolling/nulls/sum.rs
- crates/polars-arrow/src/legacy/kernels/rolling/nulls/variance.rs
- crates/polars-arrow/src/legacy/prelude.rs
- crates/polars-core/src/chunked_array/ops/rolling_window.rs
- crates/polars-core/src/frame/group_by/aggregations/mod.rs
- crates/polars-plan/src/dsl/mod.rs
- crates/polars-python/src/expr/rolling.rs
- crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs
- crates/polars-time/src/chunkedarray/rolling_window/mod.rs
- crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs
- py-polars/tests/unit/expr/test_serde.py
This PR presents one way to fix #18595.
Information present in `DynArgs` was being lost after a serialization/deserialization roundtrip, so I had to implement `Serialize` and `Deserialize` in order to handle them.
This is my first contribution so I'm pretty excited about that!
> refactor(rust): Replace `DynArgs` with an enum containing all its variants

- py-polars/polars/io/csv/functions.py
The `read_csv` function expects that the order of the columns in a provided schema match the order of the columns in the CSV file being read. This was not documented and led to unexpected behavior. Since `dict` types do not guarantee the ordering of their keys this requirement was surprising to me. 
[This](https://github.com/pola-rs/polars/issues/15854) issue discusses the fact that this happens but no fix has been implemented. Improving the documentation is quick and will enable users from experiencing the issue if they are willing to read.
```python
from io import StringIO
csv = """A,B
1,"foo"
3,"bar"
"""
buf = StringIO(csv)
schema_good = {"A": pl.Int64, "B": pl.String}
pl.read_csv(buf, schema=schema_good)
buf.seek(0)
schema_bad = {"B": pl.String, "A": pl.Int64} …
```
> docs(python): Clarify documentation for `schema` in `read_csv` function

- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/operations/test_cross_join.py
- py-polars/tests/unit/operations/test_join.py
- py-polars/tests/unit/streaming/test_streaming_join.py
Closes #18842 and closes #18846.
> fix(python): Improve `join` argument checks

- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/io/test_csv.py
Fixes https://github.com/pola-rs/polars/issues/18825.
> fix(python): Pass missing user params in `write_csv`

- crates/polars-io/src/parquet/read/reader.rs
- crates/polars-mem-engine/src/executors/scan/parquet.rs
- crates/polars-pipe/src/executors/sources/parquet.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_fetch.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_utils.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
Follow-up for https://github.com/pola-rs/polars/pull/18803
> fix: Raise when parquet file has extra columns and no `select()` was done

- docs/source/user-guide/gpu-support.md
There were two small issues on the new GPU support page. 
1. Installation example showed a `bash` command. Brought that back in line with the rest of the user guide and contribution guidelines.
2. Link to the issue tracker at the end of the page pointed to the contribution guidelines, instead of the Polars issue tracker on Github.
> docs: Fix link to issue tracker and code snippet format in GPU docs

- py-polars/polars/dataframe/plotting.py
- py-polars/tests/unit/operations/namespaces/test_plot.py
closes #18830
cc @dangotbanned in case you have time/interest to take a look
Summary: the solution used in #18625 breaks if some extra options (e.g. `sort`, `axis`) are specified to the `encode` arguments. What I'm proposing is to extract `'shorthand'` in such cases, so that the tooltips can keep being shown by default
> fix: DataFrame plot was raising when some extra keywords were passed to encodings (e.g. `x=alt.X(a, axis=alt.Axis(labelAngle=30))`)

- crates/polars-io/src/parquet/read/read_impl.rs
This should fix the PDS benchmarks.
> fix: Properly merge live- and dead columns in prefiltered

- py-polars/polars/plugins.py
closes #18857 
Can confirm that this resolves the issue
before:
after:
> perf: Cache register plugin function

- crates/polars-core/src/chunked_array/arithmetic/mod.rs
- crates/polars-core/src/chunked_array/mod.rs
- crates/polars-core/src/series/arithmetic/borrowed.rs
- crates/polars-core/src/series/mod.rs
- crates/polars-core/src/utils/mod.rs
Super minor, removes some apostrophes that shouldn't be there.
> docs: Fix minor rogue apostrophes

- crates/polars-arrow/src/array/primitive/mod.rs
- crates/polars-arrow/src/compute/cast/mod.rs
- crates/polars-arrow/src/compute/cast/primitive_to.rs
- crates/polars-core/src/chunked_array/logical/time.rs
- crates/polars-core/src/series/mod.rs
- crates/polars-expr/src/expressions/literal.rs
- py-polars/tests/unit/datatypes/test_time.py
> fix: Check values in strict cast Int to Time

- crates/polars-ops/src/series/ops/duration.rs
- py-polars/tests/unit/datatypes/test_duration.py
@alexander-beedie
Operator precedence is hard sometimes :sweat_smile:
> fix: Properly calculate duration units

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-plan/src/frame/opt_state.rs
- crates/polars-plan/src/plans/expr_ir.rs
- crates/polars-plan/src/plans/optimizer/collapse_joins.rs
- crates/polars-plan/src/plans/optimizer/collect_members.rs
- crates/polars-plan/src/plans/optimizer/mod.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-utils/src/idx_vec.rs
- py-polars/polars/functions/lazy.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/lazyframe/test_optimizations.py
This PR adds the `collapse_joins` optimization pass.
This collapses a join and filters into a faster join. For example, `a.join(b, how='cross').filter(pl.col.l == pl.col.r)` can be collapsed into `a.join(b, how='inner', left_on=pl.col.l, right_on=pl.col.r)` if `l` is a column of `a` and `r` is a column of `b`.
This currently only collapses `cross` joins into `inner` or `iejoin`, but theoretically other joins could be simplified as well.
closes #18753
> perf: Collapse cross-joins to faster joins

- Cargo.lock
- crates/polars-lazy/src/dsl/eval.rs
> fix: Use proper thread pool in cumulative_eval

- crates/polars-json/src/json/infer_schema.rs
- py-polars/tests/unit/io/test_json.py
Would infinitely recurse before
> fix: Fix SO in json inference

- crates/polars-core/src/chunked_array/logical/enum_/mod.rs
- crates/polars-core/src/chunked_array/logical/mod.rs
- crates/polars-core/src/series/any_value.rs
- py-polars/tests/unit/constructors/test_any_value_fallbacks.py
> fix: AnyValue Series from Categorical/Enum

- crates/polars-core/src/chunked_array/builder/list/primitive.rs
> fix(rust): Ensure ListPrimitiveBuilder dtype invariant is asserted

- crates/polars-arrow/src/array/mod.rs
- crates/polars-core/src/chunked_array/mod.rs
- crates/polars-core/src/chunked_array/ops/zip.rs
- py-polars/tests/unit/datatypes/test_struct.py
> fix: Properly zip struct validities

- crates/polars-plan/src/plans/functions/rename.rs
Closes [#17336](https://github.com/pola-rs/polars/issues/17336)
For the python rename API, if we pass a dictionary arguments, we convert to LazyFrame and internally call the rename operation; the issue is that we need to get index number for all the columns we are renaming; this is an O(n^2) operation.
If we pass a function as argument to rename, we convert to LazyFrame and internally call the select operation; here we get the index for each column from the Schema, which is an IndexMap and hence overall the operation becomes O(n).
Have tried to fix this issue in a similar fashion by constructing the schema first and then getting index from it.
After the fix :
```
df = pl.DataFrame({f"column_{i}": ['x', 'y', 'z'] for i in range(10000)})
cols_map = {f"column_{i}": …
```
> perf: Improve rename performace for Lazy API

- crates/polars-mem-engine/src/executors/stack.rs
> feat: Improve scalar strict message

- crates/polars-lazy/src/frame/mod.rs
- py-polars/tests/unit/io/test_scan.py
Fixes https://github.com/pola-rs/polars/issues/18892
This only happens if the `LazyFrame` is a direct scan without any subsequent operations.
> fix: Adding `with_row_index()` to previously collected lazy scan does not take effect

- crates/polars-ops/src/frame/mod.rs
- Fixing a typo: "Crea" to "Create" in the docs for the `IntoDf` trait.
> docs(rust): Typo for `IntoDf` trait

- crates/polars-core/src/datatypes/mod.rs
- crates/polars-core/src/datatypes/reshape.rs
- crates/polars-core/src/frame/column/mod.rs
- crates/polars-core/src/series/arithmetic/borrowed.rs
- crates/polars-core/src/series/ops/reshape.rs
- crates/polars-expr/src/expressions/aggregation.rs
- crates/polars-expr/src/expressions/mod.rs
- crates/polars-ops/src/chunked_array/list/namespace.rs
- crates/polars-plan/src/dsl/function_expr/dispatch.rs
- crates/polars-plan/src/dsl/function_expr/list.rs
- crates/polars-plan/src/dsl/function_expr/mod.rs
- crates/polars-plan/src/dsl/function_expr/schema.rs
- crates/polars-plan/src/dsl/mod.rs
- crates/polars-plan/src/dsl/options.rs
- crates/polars-python/src/expr/general.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- crates/polars-python/src/series/general.rs
- py-polars/tests/unit/operations/test_reshape.py
This fixes the `reshape` function to properly infer dimensions in the schema.
I did this by adding a "zero-cost" `ReshapeDimension` enum that can either be `Specified(u64)` or `Infer`. This also makes the reshaping behavior more consistent as now all negative values are always assumed to be `Infer`.
During this work, I saw an unneeded allocation in `reshape_array` and removed it.
Fixes #18879.
> fix: Infer reshape dims when determining schema

- crates/polars-core/src/chunked_array/ops/full.rs
- py-polars/tests/unit/datatypes/test_array.py
> fix: Properly choose inner physical type for Array

- crates/polars-ops/src/chunked_array/mode.rs
- py-polars/tests/unit/series/test_series.py
Fixes the following:
```python
>>> df = pl.DataFrame({"a": [1, 1, 2]})
>>> df.select(pl.col.a.mode())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 1   │
└─────┘
>>> df.set_sorted("a").select(pl.col.a.mode())
shape: (1, 1)
┌─────┐
│ a   │
│ --- │
│ i64 │
╞═════╡
│ 2   │
└─────┘
```
> fix: Incorrect mode for sorted input

- crates/polars-core/src/datatypes/any_value.rs
- crates/polars-core/src/frame/column/arithmetic.rs
- crates/polars-core/src/frame/column/mod.rs
- crates/polars-core/src/frame/column/scalar.rs
- crates/polars-core/src/frame/mod.rs
- crates/polars-core/src/series/any_value.rs
- crates/polars-io/src/utils/other.rs
- crates/polars-lazy/src/tests/aggregations.rs
- crates/polars-lazy/src/tests/queries.rs
- crates/polars-ops/src/series/ops/duration.rs
- crates/polars-plan/src/dsl/function_expr/round.rs
- py-polars/tests/unit/test_scalar.py
> fix: Properly fetch type of full None List Series

- crates/polars-core/src/frame/group_by/proxy.rs
- crates/polars-expr/src/expressions/window.rs
- crates/polars/tests/it/lazy/expressions/window.rs
- py-polars/tests/unit/operations/test_window.py
Fixes https://github.com/pola-rs/polars/issues/18943
> fix: Fix `Expr.over` with `order_by` did not take effect if group keys were sorted

- crates/polars-lazy/src/dsl/eval.rs
Small typo stemming from #18664.
Fixes #18917.
> fix: Parallel evaluation of `cumulative_eval`

- crates/polars-plan/src/plans/aexpr/scalar.rs
- py-polars/tests/unit/expr/test_exprs.py
Fixes https://github.com/pola-rs/polars/issues/18755
> fix: Fix `lit().shrink_dtype()` broadcasting

- crates/polars-io/src/parquet/read/async_impl.rs
- crates/polars-io/src/parquet/read/predicates.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-io/src/parquet/read/reader.rs
- crates/polars-lazy/src/scan/ndjson.rs
- crates/polars-lazy/src/scan/parquet.rs
- crates/polars-mem-engine/src/executors/scan/parquet.rs
- crates/polars-parquet/src/arrow/read/deserialize/utils/filter.rs
- crates/polars-parquet/src/parquet/metadata/row_metadata.rs
- crates/polars-parquet/src/parquet/read/column/mod.rs
- crates/polars-pipe/src/executors/sources/parquet.rs
- crates/polars-plan/src/plans/builder_dsl.rs
- crates/polars-plan/src/plans/options.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-python/src/lazyframe/visit.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_fetch.rs
- crates/polars-stream/src/nodes/parquet_source/row_group_data_fetch.rs
- crates/polars-stream/src/nodes/parquet_source/row_group_decode.rs
- crates/polars/tests/it/io/parquet/read/mod.rs
- crates/polars/tests/it/io/parquet/read/row_group.rs
- crates/polars/tests/it/io/parquet/write/mod.rs
- py-polars/polars/io/parquet/functions.py
- py-polars/tests/unit/io/test_parquet.py
~~Let me know if there is a better name for this parameter~~
> feat: Add `allow_missing_columns` option to `read/scan_parquet`

- crates/polars-compute/src/comparisons/array.rs
- crates/polars-compute/src/comparisons/list.rs
- crates/polars-core/src/chunked_array/comparison/mod.rs
> refactor: Add FixedSizeList equality broadcasting

- docs/source/development/contributing/ide.md
This prevents PyO3 from constantly recompiling, at least until https://github.com/PyO3/pyo3/issues/1708 is fixed. It also prevents annoying 'waiting for lock' issues, so it might be a good idea regardless.
The downside is that your build directory becomes even bigger as you now store artifacts twice, but it's honestly already a lost cause trying to get the artifact size small during development.
> docs: Recommend targetDir for rust-analyzer

- crates/polars-arrow/src/io/ipc/write/common.rs
- crates/polars-plan/src/plans/ir/scan_sources.rs
- py-polars/tests/unit/io/test_ipc.py
> fix: IPC don't write variadic_buffer_counts in blocks, but only dictionaries

- crates/polars-core/src/chunked_array/ops/zip.rs
- py-polars/tests/unit/functions/test_when_then.py
Fixes https://github.com/pola-rs/polars/issues/18961.
> fix: Return correct value for `when().then().else()` on structs when using `first()`\`last()`

- crates/polars-io/src/parquet/read/reader.rs
- crates/polars-io/src/parquet/read/utils.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_utils.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
- py-polars/tests/unit/io/test_parquet.py
Fixes [pull/18922#issuecomment-2378998065](https://github.com/pola-rs/polars/pull/18922#issuecomment-2378998065)
> refactor: Mention `allow_missing_columns` in error message when column not found (parquet)

- crates/polars-arrow/src/compute/cast/primitive_to.rs
- crates/polars-core/src/datatypes/any_value.rs
- py-polars/tests/unit/operations/test_cast.py
> fix: Ensure same fmt in Series/AnyValue to string cast

- crates/polars-compute/src/comparisons/list.rs
- crates/polars-core/src/chunked_array/comparison/mod.rs
- py-polars/tests/unit/operations/test_explode.py
This utilizes `List`'s variant of `TotalEqKernel` and implements broadcasting for that kernel. This gives a nice speed-up, reduces code-bloat and reduces chance of bugs.
For a measure on how much faster this is, I did a microbenchmark:
```python
lists = [None] + [list(range(i)) for i in range(11)]
a = [lists[length] for length in np.random.randint(0, 11, 1_000_000)]
b = [lists[length] for length in np.random.randint(0, 11, 1_000_000)]
a = pl.Series('a', a)
b = pl.Series('b', b)
t = timeit(lambda: a == b, number=100)
print(f"Time: {t:.2}s")
```
- Before: `Time: 16s`
- After: `Time: 1.9s`
I feel like there is more that can be done to make this a lot faster, but I feel like this is good enough for now.
> perf: Use List's TotalEqKernel

- Cargo.lock
- Cargo.toml
This addresses the security alert related to `lexical-core`, which is a dependency of `simd-json`.
Also ran a `cargo update`.
> build: Bump `simd-json` to 0.14

- crates/polars-python/src/conversion/any_value.rs
- crates/polars-python/src/dataframe/construction.rs
- crates/polars-python/src/functions/lazy.rs
- crates/polars-python/src/series/construction.rs
- py-polars/tests/unit/functions/test_lit.py
Fixes #18906.
```python
import pandas as pd
pl.select(a=pl.lit(pd.Timedelta(minutes=1)))
```
This update pushes `allow_object` into the `AnyValue` conversion, and by doing so avoids the double-gil lock for subclassed items (@ritchie46 I think it's what you were thinking in [this](https://github.com/pola-rs/polars/pull/18497#discussion_r1740639543) comment). I think it should help tidy up some of the subclass issues with temporals. I also added checks on `time` and `timedelta` temporal classes as well, as is the case in the linked issue where `pd.Timedelta` subclasses `datetime.timedelta`.
> fix: Improve literals for temporal subclasses

- crates/polars-core/src/chunked_array/ops/zip.rs
- py-polars/tests/unit/functions/test_when_then.py
Similar to https://github.com/pola-rs/polars/pull/18969, with different path.
> fix: Wrong result on `when().then().otherwise()` on struct when both result are broadcast

- crates/polars-core/src/chunked_array/comparison/mod.rs
- py-polars/tests/unit/operations/test_comparison.py
> fix: Fix struct broadcasting comparisons

- crates/polars-arrow/src/legacy/kernels/take_agg/mod.rs
- crates/polars-arrow/src/legacy/kernels/take_agg/var.rs
- crates/polars-compute/src/arithmetic/signed.rs
- crates/polars-compute/src/arithmetic/unsigned.rs
- crates/polars-core/src/chunked_array/binary.rs
- crates/polars-core/src/chunked_array/ops/sort/categorical.rs
- crates/polars-expr/src/expressions/apply.rs
- crates/polars-io/src/cloud/glob.rs
- crates/polars-io/src/csv/write/write_impl/serializer.rs
- crates/polars-lazy/src/frame/exitable.rs
- crates/polars-ops/src/chunked_array/list/dispersion.rs
- crates/polars-ops/src/chunked_array/list/sum_mean.rs
- crates/polars-ops/src/chunked_array/strings/namespace.rs
- crates/polars-pipe/src/executors/sinks/group_by/ooc_state.rs
- crates/polars-pipe/src/executors/sinks/group_by/primitive/mod.rs
- crates/polars-plan/src/dsl/dt.rs
- crates/polars-python/src/conversion/mod.rs
- crates/polars-stream/src/nodes/parquet_source/row_group_decode.rs
- crates/polars-time/src/windows/window.rs
- crates/polars-utils/src/pl_str.rs
- crates/polars/tests/it/io/avro/read_async.rs
- crates/polars/tests/it/io/avro/write_async.rs
- docs/source/src/rust/user-guide/io/cloud-storage.rs
- py-polars/build.rs
- rust-toolchain.toml
You can check commit by commit for the newly added lints.
There's an issue with one of the new lints that requires a few ignores. See:
https://github.com/rust-lang/rust-clippy/issues/13458
> build: Bump Rust toolchain to `nightly-2024-09-29`

- py-polars/polars/series/series.py
Now docstring references `eq` instead of `ne`.
Closes #18976.
> docs(python): Change `eq_missing` comparison to wrong method 

- py-polars/polars/io/parquet/functions.py
> feat(python): Add `include_file_paths` parameter to `read_parquet`

- crates/polars-core/src/chunked_array/comparison/mod.rs
- crates/polars-expr/src/expressions/binary.rs
- py-polars/tests/unit/operations/test_comparison.py
Fixes https://github.com/pola-rs/polars/issues/18870.
> fix: Return the truth values of `ne_missing` and `eq_missing` operations for struct instead of `null`

- py-polars/tests/unit/functions/test_lit.py
I'm not 100% sure why the new temporal literal tests were sometimes failing. It appears as though sometimes the `to_datetime` anyvalue converter was being called when the input was a `time` or `timedelta`.
My theory is that because the superclass types were parametrized in `pytest`, and because the tests are run in parallel, the `MyClass` classes were somehow colliding across threads. Thus, the `MyClass(datetime)` subclass defined in the test function would be defined in one thread while the `lit(MyClass(time_input))` was being run in another, and the class ancestry lookup on the rust side would find the wrong superclass. I've split the tests and given the subclasses separate names so I *hope* this fixes it. However, all tests have passed before, so all tests passing now doesn't …
> fix: Separate temporal tests

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/tests/mod.rs
- crates/polars-ops/src/frame/join/args.rs
- crates/polars-plan/src/plans/ir/format.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/joins.rs
- py-polars/tests/unit/operations/test_inequality_join.py
> fix: Fix projection pushdown bug in IEJOINS

- crates/polars-stream/src/nodes/parquet_source/row_group_decode.rs
> refactor: Fix new-streaming `test_lazy_parquet::test_row_index`

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/tests/cse.rs
- crates/polars-lazy/src/tests/optimization_checks.rs
- crates/polars-plan/src/plans/functions/dsl.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-sql/src/context.rs
- crates/polars-sql/src/sql_expr.rs
- crates/polars/tests/it/lazy/predicate_queries.rs
- crates/polars/tests/it/lazy/projection_queries.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/lazyframe/test_rename.py
- py-polars/tests/unit/test_projections.py
Closes #18954.
Useful; brings the same `strict` parameter behaviour already found in "drop" to "rename". Default behaviour remains unchanged (eg: `strict=True`).
```python
"siteid": ["xx", "yy", "zz"],
"value1": [5, 4, 6],
"value2": [7, 3, 3],
})
```
When `strict=True` (default) it is an error to reference a column that is not present.
```python
df.rename({"siteid":"id", "other":"misc"})
```
When `strict=False` (opt-in) the same rename will succeed for columns that _are_ present.
```python
df.rename({"siteid":"id", "other":"misc"}, strict=False)
```
> feat: Add `strict` param to eager/lazy frame "rename"

- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/join.rs
- py-polars/tests/unit/operations/test_inequality_join.py
> fix: Raise invalid predicate join_where

- crates/polars-error/src/lib.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/join.rs
- crates/polars-utils/src/arena.rs
Debugging `LazyFrames` can be tedious as it is unclear where the error of query originated. 
Until this day. :)
We can show the resolved plan up until that failed node. That should give users information on where to look for their invalid query/bug.
```python
q = pl.LazyFrame({"A": [0, 1, 0], "B": [1, 0, 1], "C": [1, 2, 3], "D": [4, 5, 6]})
(
q.with_columns(pl.col("A") * 10)
.join(q, on="A")
.join(q, on="A")
.select(pl.col("not-exist"))
).collect()
```
```
ColumnNotFoundError                       Traceback (most recent call last)
Cell In[2], line 7
1 q = pl.LazyFrame({"A": [0, 1, 0], "B": [1, 0, 1], "C": [1, 2, 3], "D": [4, 5, 6]})
2 (
3  q.with_columns(pl.col("A") * 10)
4  .join(q, on="A")
5  .join(q, on="A")
6 …
```
> feat: Improved error message DSL -> IR resolving

- crates/polars-stream/src/async_primitives/distributor_channel.rs
The old implementation was racy and could miss the last message(s) sent by the sender right before closing. It would check if there are messages available, and if not if the channel is closed, but between these two checks new messages could've come in.
This only affected the new streaming engine.
> refactor(rust): Fix race condition in DistributorChannel

- crates/polars-core/src/chunked_array/comparison/mod.rs
- py-polars/tests/unit/operations/test_comparison.py
Follow-up for @coastalwhite CR comment on https://github.com/pola-rs/polars/pull/18930.
> fix: Force nested struct `missing` equality

- crates/polars-stream/src/nodes/mod.rs
- crates/polars-stream/src/nodes/with_row_index.rs
- crates/polars-stream/src/physical_plan/fmt.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/mod.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
```python
n = 100_000_000
df = pl.DataFrame({"x": np.arange(n)})
query = df.lazy().with_row_index().select((pl.col.x * pl.col.index).sum())
print(timeit(lambda: query.collect(), number=50))
print(timeit(lambda: query.collect(streaming=True), number=50))
print(timeit(lambda: query.collect(new_streaming=True), number=50))
```
```
20.35326350000105
25.54412454200792
1.9409049579990096
```
> refactor(rust): Add WithRowIndexNode to new-streaming engine

- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/dataframe/test_df.py
Closes #18406.
Streamlines insertion of an Expr at an arbitrary index in a DataFrame; currently `insert_column` only supports this for Series, but it's straightforward to allow Expr too.
Without this affordance the user has to make two calls - one to add the new Expr (typically via `with_columns`), and then a second call to explicitly reorder the columns. 
More ergonomic to allow this in a single call, and it's consistent with `with_columns`, which also supports both Expr and Series input.
```python
"id": ["xx", "yy", "zz"],
"v1": [5, 4, 6],
"v2": [7, 3, 3],
})
df.insert_column(3, (pl.col("v1") * pl.col("v2")).alias("v3"))
df.insert_column(1, (pl.col("v2") - pl.col("v1")).alias("v0"))
```
> feat(python): Allow `insert_column` to take expressions

- Cargo.lock
- py-polars/Cargo.toml
`build_info` has been commented out. This failed due to https://github.com/lukaslueg/built/issues/71
> Python Polars 1.9.0

- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/lazyframe/test_lazyframe.py
fixes https://github.com/pola-rs/polars/issues/18944
> fix(python): Don't ignore multiple columns in LazyFrame.unnest

- py-polars/tests/unit/functions/test_lit.py
@mcrumiller You can re-introduce these when everything works as expected, right now it's causing spurious CI failures.
> fix: Remove failing datetime subclass test

- crates/polars-arrow/src/array/mod.rs
- crates/polars-compute/src/bitwise/mod.rs
- crates/polars-core/src/chunked_array/ops/bitwise_reduce.rs
- crates/polars-python/Cargo.toml
- crates/polars-python/src/series/aggregation.rs
- py-polars/docs/source/reference/expressions/aggregation.rst
- py-polars/docs/source/reference/expressions/computation.rst
- py-polars/docs/source/reference/series/computation.rst
- py-polars/polars/series/series.py
- py-polars/tests/unit/operations/test_bitwise.py
Fixes https://github.com/pola-rs/polars/issues/19065.
Also fixes https://github.com/pola-rs/polars/issues/19066.
> fix: Bitwise aggregations should ignore null values

- Cargo.toml
Fixes https://github.com/pola-rs/polars/issues/19063.
Hashbrown 0.15 has backwards-incompatible changes we need to migrate to manually.
> refactor(rust): Pin hashbrown to 0.14 until migrated

- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/functions/dsl.rs
- py-polars/tests/unit/test_errors.py
> fix: Check validity of columns of keys/aggs in dsl->ir

- crates/polars-plan/src/plans/conversion/join.rs
- crates/polars-plan/src/plans/optimizer/collapse_joins.rs
- py-polars/tests/unit/operations/test_inequality_join.py
> fix: Only rewrite numeric ineq joins

- crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs
- py-polars/polars/expr/expr.py
- py-polars/tests/unit/operations/rolling/test_rolling.py
example:
```python
In [1]: import polars as pl
...: 
...: df = pl.DataFrame({"a": [1, 4, 2, 5]}).with_row_index()
...: print(df.with_columns(pl.col("a").rolling_sum_by("index", "2i")))
...: 
shape: (4, 2)
┌───────┬─────┐
│ index ┆ a   │
│ ---   ┆ --- │
│ u32   ┆ i64 │
╞═══════╪═════╡
│ 0     ┆ 1   │
│ 1     ┆ 5   │
│ 2     ┆ 6   │
│ 3     ┆ 7   │
└───────┴─────┘
```
which `DataFrame.rolling` already supports
It should be possible for both `Expr.rolling_*_by` and `DataFrame.rolling` to support Duration and Time too, but i'll keep that separate
> feat: Allow for rolling_*_by to use index count as window

- crates/polars-io/src/parquet/read/options.rs
- crates/polars-lazy/src/scan/parquet.rs
- crates/polars-mem-engine/src/executors/scan/parquet.rs
- crates/polars-pipe/src/executors/sources/parquet.rs
- crates/polars-plan/src/plans/builder_dsl.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-stream/src/nodes/parquet_source/mod.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
Fixes https://github.com/pola-rs/polars/issues/19081
> fix: Ensure parquet `schema` arg is propagated to IR

- Cargo.lock
- Cargo.toml
- crates/polars-core/Cargo.toml
- crates/polars-core/src/chunked_array/builder/list/categorical.rs
- crates/polars-core/src/chunked_array/logical/categorical/builder.rs
- crates/polars-io/src/file_cache/cache.rs
Includes a temporary hack to set the nightly flag on an older hashbrown version until we've eliminated/upgraded all dependencies that depend on hashbrown 0.15. See https://github.com/rust-lang/hashbrown/issues/564 for rationale.
> refactor(rust): Migrate to hashbrown 0.15

- crates/polars-python/src/lazyframe/general.rs
> fix: Throw proper error for empty char params in scan_csv

- crates/polars-core/src/series/any_value.rs
> fix: Allow converting `DatetimeOwned` to `ChunkedArray`

- crates/polars-mem-engine/src/executors/projection_utils.rs
- py-polars/tests/unit/constructors/test_dataframe.py
- py-polars/tests/unit/dataframe/test_shape.py
- py-polars/tests/unit/lazyframe/test_with_context.py
- py-polars/tests/unit/operations/test_slice.py
- py-polars/tests/unit/test_scalar.py
> fix: Raise on invalid shape of shape 1, empty combination

- py-polars/polars/convert/normalize.py
- py-polars/polars/dataframe/frame.py
- py-polars/polars/io/csv/batched_reader.py
- py-polars/polars/io/delta.py
- py-polars/polars/lazyframe/in_process.py
- py-polars/polars/series/series.py
- py-polars/polars/series/utils.py
- Python3.9 has `removeprefix`, so the `_remove_prefix` utily isn't needed
- `Generator[Any]` instead of `Generator[Any, None, None]` (https://peps.python.org/pep-0696/)
- walrus operator in some bits where I think it's tasty - it's already used in quite a few places, I guess Polars has already decided to embrace it 😄
> chore: Clean remove_prefix since python3.9 is now the minimum Python

- crates/polars-arrow/src/array/ffi.rs
- crates/polars-arrow/src/ffi/array.rs
- crates/polars-arrow/src/ffi/mod.rs
- py-polars/tests/unit/interop/test_interop.py
> fix: Recursively align when converting to ArrowArray

- crates/polars-core/src/frame/chunks.rs
- crates/polars-core/src/frame/mod.rs
- crates/polars-core/src/utils/mod.rs
- crates/polars-io/src/ipc/write.rs
- crates/polars-io/src/json/mod.rs
- crates/polars-io/src/utils/other.rs
- crates/polars-pipe/src/executors/sinks/io.rs
- crates/polars-python/src/dataframe/export.rs
> fix: Ensure aligned chunks in OOC sort

- py-polars/polars/config.py
- py-polars/tests/unit/test_config.py
Adds a TypedDict listing all valid options you can pass directly to Config()
Closes #18987
> docs(python): Annotate Config kwarg options

- crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/mod.rs
- crates/polars-sql/src/functions.rs
- crates/polars-sql/tests/functions_aggregate.rs
This implements a feature requested in https://github.com/pola-rs/polars/issues/7227: quantile functions in SQL. I also went ahead and added median function tests as those were missing.
> feat: Quantile function in SQL

- crates/polars-plan/src/plans/conversion/join.rs
- crates/polars-python/src/lazyframe/visitor/nodes.rs
- py-polars/tests/unit/operations/test_inequality_join.py
When checking if both sides of an expression in a `join_where` call are from the right table (for which overlapping names will be suffixed) we must exclude undecorated names which also appear in the left table.
- Closes #19119
> fix(rust,python): Allow partial name overlap in join_where resolution

- crates/polars-core/src/chunked_array/comparison/mod.rs
- py-polars/tests/unit/operations/test_explode.py
- py-polars/tests/unit/series/test_equals.py
Regression causing `eq/ne_missing` to incorrectly give NULL when comparing NULLs instead of True/False
Fixes https://github.com/pola-rs/polars/issues/19153
Adds
* `test_eq_lists_arrays` for `==` / `!=`
* `test_eq_missing_lists_arrays_19153` for `eq_missing` / `ne_missing`
---
Tests are parametrized to test both lists and arrays
> fix: Fix incorrect `(eq|ne)_missing` on List/Array types

- py-polars/polars/__init__.py
- py-polars/tests/unit/test_polars_import.py
This is an alternative implementation for #5342, which was reverted due to side-effects.
This implementation should not affect any non-Polars using code. It won't catch all cases of people using Polars in a fork()-without-execve() child, but it will catch many of them.
> feat(python): Raise an error when users try to use Polars API in a fork()-without-execve() child

- py-polars/tests/unit/test_polars_import.py
> fix(python): Don't fail test if e.g. jax has been used first, since jax installs a fork handler that warns

- crates/polars-plan/src/dsl/python_udf.rs
- py-polars/tests/unit/lazyframe/test_serde.py
[cloudpickle](https://github.com/cloudpipe/cloudpickle) does not support serde across Python versions:
> Cloudpickle can only be used to send objects between **the exact same version of Python**.
Currently, failing to adhere to this restriction can cause code execution to hang.
So we should only use `cloudpickle` when necessary, and when we do, we should encode the Python version during serialization and check it during deserialization. I chose to only encode the **minor** version, as we only support Python 3 anyway and the patch version doesn't seem to matter.
> feat: Check Python version when deserializing UDFs

- crates/polars-python/src/file.rs
Fixes #18417 
When passing something like a `gzip.GzipFile` or `zipfile.ZipExtFile`, it's not possible to pass a file path instead. And since #17315, Polars will extract the underlying fileno for faster IO performance if possible, so it doesn't appear that this warning is useful any more.
> fix(python): Remove incorrect warning when using an `IO[bytes]` instance

- examples/read_csv/Cargo.toml
- examples/read_csv/src/main.rs
Fixes https://github.com/pola-rs/polars/issues/19129
> docs(rust): Fix `examples/read_csv` rust example

- crates/polars-plan/src/dsl/mod.rs
Clears up current API docs ambiguity.
> docs: Clarify difference between bitwise/logical ops

- crates/polars-core/src/series/into.rs
- py-polars/tests/unit/interop/test_interop.py
Fixes #18810 
Currently there is no special branch to handle to_arrow conversion for Arrays, due to which Array of logical types are not converted properly. This fix implements this branch, similar to the one for Lists.
While converting to pickle, to_arrow is used, hence converting to arrow properly also fixes the above issue.
> fix: Implement to_arrow functionality properly for Arrays

- crates/polars/src/docs/lazy.rs
Hi, since `as_struct` no longer accepts slices and now only accepts a `Vec`, I've updated the documentation.
> docs: Fix example of `as_struct`

- py-polars/polars/__init__.py
- py-polars/tests/unit/test_polars_import.py
This reverts commit 48bc09b544b3638472f64db3391d597bd5da720e to fix the Python docs build.
IIUC the commit replaces everything in the `pl` namespace with a dummy function, and I'm guessing sphinx, or some other package in the Python docs build process does some forking. Then sphinx complains with `AttributeError: 'function' object has no attribute '__arrow_c_stream__'` (the `'function'` object being the dummy function).
> ci: Revert "feat(python): Raise an error when users try to use Polars API in a fork()-without-execve() child (#19149)

- README.md
Very minor tweak to `README.md`: the large Polars banner on the [main github page](https://github.com/pola-rs/polars) currently links to the svg file, which is probably not desirable. This links to https://pola.rs, so when users click on the banner they are brought to the main polars page.
[See the update here](https://github.com/mcrumiller/polars/tree/header-link).
> docs: Link to main website from banner

- py-polars/polars/dataframe/frame.py
Closes #18950.
Closes #18668.
A previous update caused the "hidden_columns" parameter to become inadvertently entangled with "column_widths" (for `write_excel`). This PR unentangles them, fixing the related issue(s) 😅
> fix(python): Fix use of "hidden_columns" parameter in `write_excel`

- crates/polars-core/src/chunked_array/builder/list/mod.rs
- crates/polars-core/src/chunked_array/from_iterator.rs
- crates/polars-core/src/chunked_array/from_iterator_par.rs
- crates/polars-core/src/chunked_array/object/extension/list.rs
- crates/polars-core/src/chunked_array/object/extension/mod.rs
- crates/polars-core/src/chunked_array/object/registry.rs
- crates/polars-expr/src/expressions/apply.rs
- crates/polars-expr/src/expressions/mod.rs
- py-polars/tests/unit/operations/test_group_by.py
fixes #19173
Also makes `get_list_builder` work for `Object` types and thus is now infallible.
I can get rid of the extra `if len == 0` branch, but must fix some IR bugs to do that. Will follow up.
> fix: Fix invalid list collection in expression engine

- crates/polars-plan/src/plans/conversion/expr_expansion.rs
> fix: Don't unwrap() expansion

- .github/workflows/release-python.yml
- py-polars/polars/_cpu_check.py
- py-polars/polars/meta/versions.py
- py-polars/tests/unit/meta/test_versions.py
- py-polars/tests/unit/test_cpu_check.py
closes #19109
This PR both exposes LTS CPU in `show_versions()` and fixes an issue in the release workflow where the `_POLARS_LTS_CPU` wasn't set correctly.
The LTS CPU was originally supposed to be taken into account by `check_cpu_flags` however, because of the mentioned issue it was practically always False and so we can deem it safe to remove it from that check
> feat: Expose LTS CPU in show_versions()

- crates/polars-core/src/datatypes/dtype.rs
- crates/polars-core/src/datatypes/field.rs
- crates/polars-expr/src/expressions/apply.rs
- crates/polars-expr/src/expressions/column.rs
- crates/polars-expr/src/planner.rs
- crates/polars-lazy/src/dsl/eval.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/physical_plan/exotic.rs
- crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs
- crates/polars-mem-engine/src/planner/lp.rs
- crates/polars-pipe/src/executors/sinks/group_by/aggregates/convert.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/plans/aexpr/schema.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
- crates/polars-stream/src/physical_plan/lower_expr.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
- crates/polars/tests/it/lazy/aggregation.rs
- crates/polars/tests/it/lazy/queries.rs
- py-polars/polars/functions/lazy.py
- py-polars/tests/unit/operations/map/test_map_groups.py
> refactor: Make expression output type known

- py-polars/polars/io/spreadsheet/functions.py
- py-polars/tests/unit/io/test_spreadsheet.py
Follows-on from #18253; adds the same new "drop_empty_rows" param to `read_ods`.
> feat(python): Add 'drop_empty_rows' parameter for `read_ods`

- Cargo.lock
- Cargo.toml
- crates/polars-plan/src/dsl/functions/horizontal.rs
- crates/polars-plan/src/dsl/python_udf.rs
- crates/polars-python/Cargo.toml
- crates/polars-python/src/conversion/any_value.rs
- crates/polars-python/src/conversion/mod.rs
- crates/polars-python/src/dataframe/construction.rs
- crates/polars-python/src/dataframe/general.rs
- crates/polars-python/src/dataframe/io.rs
- crates/polars-python/src/dataframe/serde.rs
- crates/polars-python/src/expr/general.rs
- crates/polars-python/src/expr/list.rs
- crates/polars-python/src/expr/serde.rs
- crates/polars-python/src/expr/string.rs
- crates/polars-python/src/file.rs
- crates/polars-python/src/functions/lazy.rs
- crates/polars-python/src/functions/meta.rs
- crates/polars-python/src/functions/range.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- crates/polars-python/src/lazyframe/visitor/nodes.rs
- crates/polars-python/src/lazygroupby.rs
- crates/polars-python/src/series/buffers.rs
- crates/polars-python/src/series/general.rs
- crates/polars-python/src/series/map.rs
Closes #17273 
This also tweaks the abi3 in the `polars-python` crate to match what was in py-polars (3.9), since Python 3.8 is now EOL.
The commits are a commit per category of change I made.
> chore: Migrate to PyO3 0.22 and released verion of rust-numpy crate

- py-polars/docs/source/reference/expressions/struct.rst
- py-polars/polars/expr/struct.py
- py-polars/tests/unit/test_expansion.py
> feat(python): Add Expr.struct.unnest() as alias for Expr.struct.field("*")

- crates/polars-plan/src/plans/conversion/expr_to_ir.rs
- crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
- crates/polars-plan/src/plans/lit.rs
- crates/polars-python/src/functions/lazy.rs
- py-polars/tests/unit/functions/test_lit.py
Also make `AnyValue -> Literal` infallible.
fixes #19204
> fix: Fix struct literals

- crates/polars-error/src/constants.rs
- py-polars/polars/_utils/construction/series.py
> fix(python): Don't trigger row limit in array construction

- crates/polars-core/src/series/from.rs
- crates/polars-ops/src/chunked_array/array/to_struct.rs
- crates/polars-ops/src/chunked_array/list/to_struct.rs
- py-polars/tests/unit/datatypes/test_struct.py
> fix: Use all chunks in `Series` from arrow struct

- crates/polars-time/src/date_range.rs
- py-polars/tests/unit/functions/range/test_datetime_range.py
closes #19179 
from https://www.kaggle.com/code/marcogorelli/polars-timing/notebook?scriptVersionId=200783587 it's ~10x faster
EDIT: disregard the name of the branch 🙈
> perf: Make date_range / datetime_range ~10x faster for constant durations

- crates/polars-arrow/src/bitmap/immutable.rs
- crates/polars-arrow/src/bitmap/mutable.rs
- crates/polars-arrow/src/offset.rs
- crates/polars-compute/src/arithmetic/mod.rs
- crates/polars-compute/src/arithmetic/pl_num.rs
- crates/polars-core/src/series/arithmetic/borrowed.rs
- crates/polars-core/src/series/arithmetic/list_borrowed.rs
- crates/polars-core/src/series/arithmetic/mod.rs
- crates/polars-core/src/series/ops/reshape.rs
- crates/polars-core/src/series/series_trait.rs
- crates/polars-expr/src/expressions/binary.rs
- crates/polars-ops/src/series/ops/floor_divide.rs
- crates/polars-plan/src/plans/aexpr/schema.rs
- crates/polars-plan/src/plans/conversion/type_coercion/binary.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/operations/arithmetic/test_arithmetic.py
- py-polars/tests/unit/operations/arithmetic/test_list_arithmetic.py
Introduces numeric list kernels that operate directly on the list offsets and leaf arrays.
* Support for
* List<->List operations where both lists must only have 1 level of nesting
* List<->Numeric operations, where the list can have any level of nesting
* Adds support for floor divide
* I haven't added dedicated codepaths for when the outer validity is NULL to reduce codegen - I've instead forced the outer validity to be materialized
* Have not added feature gates yet
Fixes https://github.com/pola-rs/polars/issues/19010
Fixes https://github.com/pola-rs/polars/issues/19025
> feat: Improved list arithmetic support

- py-polars/polars/dataframe/frame.py
Fixes #19181
cc @alexander-beedie
> docs(python): Improve DataFrame.write_database docstring

- crates/polars-expr/src/expressions/apply.rs
- crates/polars-expr/src/expressions/binary.rs
- crates/polars-io/src/parquet/read/predicates.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
> fix: Parquet predicate pushdown for `lit(_) !=`

- crates/polars-mem-engine/src/executors/scan/ndjson.rs
fixes:
```
error[E0433]: failed to resolve: use of undeclared type `JsonLineReader`
--> /polars/crates/polars-mem-engine/src/executors/scan/ndjson.rs:88:30
|
88 |                 let reader = JsonLineReader::new(curs);
|                              ^^^^^^^^^^^^^^ use of undeclared type `JsonLineReader`
|
help: consider importing this struct
|
1  + use polars_io::prelude::JsonLineReader;
|
For more information about this error, try `rustc --explain E0433`.
error: could not compile `polars-mem-engine` (lib) due to 1 previous error
```
> fix: Compilation error missing use JsonLineReader

- py-polars/polars/io/database/_executor.py
Closes #19221.
Improves `read_database` integration with DuckDB, when using a SQLAlchemy-based `duckdb_engine` connection. 
Previously we accessed the raw connection directly in order to take advantage of native Arrow return, but this didn't work when using a SQLAlchemy `Selectable` as the query.
Now we handle this case properly, as it turns out that `duckdb_engine` supports transparent pass-through to the underlying raw connection via `__getitem__`, allowing us to take advantage of DuckDB Arrow return in _all_ cases, for maximum performance, _without_ having to interact with the raw connection ourselves.
Setup (assuming `duckdb_engine` installed):
```python
from sqlalchemy import MetaData, Table, create_engine, select
df_test_data = pl.DataFrame({
"key": ["aa", "bb", …
```
> fix(python): Ensure that `read_database` takes advantage of Arrow return from a `duckdb_engine` connection when using a SQLAlchemy `Selectable`

- crates/polars-arrow/src/types/native.rs
- crates/polars-compute/src/cardinality.rs
- crates/polars-compute/src/lib.rs
- crates/polars-parquet/Cargo.toml
- crates/polars-parquet/src/arrow/write/dictionary.rs
- crates/polars-parquet/src/parquet/read/page/reader.rs
This PR adds two things:
1. HyperLogLog to determine estimate the cardinality of an array. If the estimated cardinality is too high, no group-by has to be done. This speeds up Parquet writing by ~2x for high cardinality data.
2. An extension of the fast path for integers. Where if the min and the max are close enough, a bitmask is created to determine the cardinality. If cardinality is low enough or the cardinality is too high, the HyperLogLog path can be skipped. This can also lead to more than 2x improvements while writing.
> perf: Fast decision for Parquet dictionary encoding

- py-polars/polars/io/delta.py
- py-polars/tests/unit/io/test_delta.py
https://github.com/pola-rs/polars/issues/19074
> feat: Allow DeltaTable input to scan_delta and read_delta

- py-polars/polars/io/database/_executor.py
Small follow-up to #19255.
Fixes some docstring comments, and improves the SQLAlchemy object/connection check.
(FYI: @daniel-thom, this addresses your issue yesterday on the DuckDB fix).
> fix(python): Make the SQLAlchemy connection check more robust

- crates/polars-arrow/src/compute/cast/mod.rs
- py-polars/tests/unit/operations/test_cast.py
See https://github.com/pola-rs/polars/issues/18991 for comment and conclusion. This MR is step 1 of proposed solution.
It is technically breaking, but old version of transform `binary -> numerical` can be done via `binary -(decode)> string -> numerical)`.
Note that I wasn't sure what was going on with `Decimal` since it is allowed in string, but not for binary. I removed it, but please let me know if it should be interpreted somehow
> fix: Only apply string parsing to String dtype

- crates/polars-arrow/src/array/list/mod.rs
- crates/polars-core/src/chunked_array/list/mod.rs
- crates/polars-core/src/series/arithmetic/list_borrowed.rs
- crates/polars-core/src/series/ops/reshape.rs
For example, given this ListArray:
```rust
values: 0..10_000
offsets: [5000, 5001, 5002]
repr: [[5000], [5001]]
```
Currently, the list arithmetic kernel would:
* Allocate a result array of `10_000` values, when we only need `5002 - 5000 = 2` values
* If the one side is a broadcasting primitive, we would end up calling the `ArithmeticKernel` on all 10,000 values, when we only need to call it on a slice `values[5000..5002]` of 2 values.
This can be a performance footgun if one performs list arithmetic across sliced chunks of a DataFrame - we would end up performing allocation/compute on the entire DataFrame for every chunk.
This PR trims the sliced-out memory from the ListArrays so that we don't over-allocate / perform compute on sliced-out memory.
> refactor(rust): Trim sliced-out memory from ListArrays in list arithmetic

- crates/polars-plan/src/plans/optimizer/cse/cse_expr.rs
- py-polars/tests/unit/test_cse.py
> fix: Don't cse `as_struct`

- crates/polars-plan/src/plans/hive.rs
- py-polars/tests/unit/io/test_hive.py
ref https://github.com/pola-rs/polars/pull/19103#issuecomment-2395009937
We currently only split on backslashes, but Windows paths can use both forwards and backwards slashes as separators
This should fix the test
> fix: Also split on forward slashes during hive path inference on Windows

- crates/polars-io/src/csv/write/write_impl/serializer.rs
- py-polars/tests/unit/io/test_csv.py
> fix: Fix quoting style of decimal csv output

- crates/polars-core/src/chunked_array/logical/enum_/mod.rs
- crates/polars-core/src/chunked_array/ops/aggregate/mod.rs
- py-polars/tests/unit/datatypes/test_enum.py
> fix: Fix enum scalar output

- crates/polars-lazy/src/tests/cse.rs
- crates/polars-plan/src/plans/optimizer/cache_states.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/projection.rs
- py-polars/tests/unit/test_cse.py
> fix: Fix cse union schema

- crates/polars-io/src/cloud/credential_provider.rs
- crates/polars-io/src/cloud/object_store_setup.rs
- py-polars/docs/source/reference/io.rst
- py-polars/polars/__init__.py
- py-polars/polars/_typing.py
- py-polars/polars/io/_utils.py
- py-polars/polars/io/cloud/__init__.py
- py-polars/polars/io/cloud/_utils.py
- py-polars/polars/io/cloud/credential_provider.py
- py-polars/polars/io/parquet/functions.py
- py-polars/requirements-dev.txt
- py-polars/tests/unit/io/cloud/test_cloud.py
ref https://github.com/pola-rs/polars/pull/19271#discussion_r1804601805
* Adds `CredentialProviderAWS`, `CredentialProviderGCP`
`CredentialProviderAWS` can be used to select a different AWS profile:
```python
lf = pl.scan_parquet(
"s3://...",
credential_provider=pl.CredentialProviderAWS(profile_name="..."),
)
import os
os.environ['AWS_PROFILE'] = 'dummy'
lf = pl.scan_parquet(
"s3://...",
credential_provider=pl.CredentialProviderAWS(),
)
```
Todos:
* In local testing, GCP is not being cached properly
> feat: Add credential provider utility classes for AWS, GCP

- py-polars/polars/_utils/various.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/dataframe/test_df.py
When calling sort with single `str` column and list of single `descending` parameter it fails with error:  
```
ldf = pl.DataFrame({
"age": [2, 5, 1],
"names": ["Alice", "Cob", "Bob"]
}).lazy()
sorted_df = ldf.sort("age", descending=[False])
print(sorted_df)
```
```
File "..../site-packages/polars/lazyframe/frame.py", line 1378, in sort
self._ldf.sort(
TypeError: argument 'descending': 'list' object cannot be converted to 'PyBool'
```
It checks for types and avoids path that does not use list.
> fix(python): DataFrame descending sorting by single list element

- crates/polars-io/src/csv/read/read_impl.rs
- py-polars/tests/unit/io/test_csv.py
> refactor: Fix csv offset

- py-polars/polars/convert/general.py
Closes #19234.
We actually accept an `Iterable` for the "data" param, not just a `Sequence`.
> fix(python): More accurate `from_dicts` typing/signature

- crates/polars-sql/src/context.rs
- py-polars/tests/unit/sql/test_group_by.py
Ref #19310.
While some (but not all) SQL dialects allow a bare HAVING (eg: outside of GROUP BY context) it is usually clearer to implement such constraints using a WHERE. However, currently we are silently ignoring such HAVING clauses :\
We should raise a syntax error here for now (can consider allowing such clauses in the future, though use of HAVING outside of GROUP BY is pretty niche - it requires _implicitly_ treating all rows as a single group, _and_ the presence of aggregate functions in the SELECT, but in the meantime can easily be written with a follow-on WHERE clause, without any ambiguity).
```python
"key": ["aaa", "aaa", "bbb", "bbb", "bbb"],
"value": [100, 25, -200, 50, 135],
})
```
Bare HAVING clause now raises a SQLSyntaxError: …
> fix: Use of `HAVING` outside of `GROUP BY` should raise a suitable SQLSyntaxError

- crates/polars-ops/src/series/ops/to_dummies.rs
- py-polars/tests/unit/series/test_series.py
> fix: Don't produce duplicate column names in Series.to_dummies

- crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
- py-polars/tests/unit/io/test_scan.py
ref https://github.com/pola-rs/polars/issues/18257#issuecomment-2425104313
> fix: Projection pushdown was ignored by `include_file_paths`

- crates/polars-parquet/src/parquet/statistics/mod.rs
> fix: Ignore Parquet `is_{min,max}_value_exact` when set to `true`

- crates/polars-io/src/csv/read/read_impl.rs
- crates/polars-io/src/csv/read/schema_inference.rs
- crates/polars-io/src/mmap.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-io/src/utils/other.rs
- crates/polars-utils/src/mmap.rs
It should be sound since it matches what we did a long time ago https://github.com/pola-rs/polars/blob/04714b933c72cb5f754069bb31f1af7750c0ab6a/crates/polars-io/src/parquet/read/read_impl.rs#L496
> refactor(rust): Reduce memcopy in parquet

- docs/source/user-guide/migration/pandas.md
Hi 👋 I've been getting into polars recently and it's absolutely mind blowing- thanks for building/maintaining such an awesome tool!
As I was reading through the documentation I came across a bit saying something like "dask also performs lazy evaluation but does not optimise queries" which was probably true when this was written. Dask since something like April this year has a ('dask-expr')[https://github.com/dask/dask-expr] library as it's backend which does optimise queries, so I thought I'd be a helpful and put in a tiny PR to update/remove that bit.
> docs: Tiny correction post dask-expr

- crates/polars-arrow/src/storage.rs
This will come in handy in the future, this lets us safely transmute between `SharedStorage`s.
> refactor(rust): Add capability to transmute to SharedStorage

- crates/polars-plan/src/dsl/function_expr/strings.rs
- py-polars/tests/unit/operations/namespaces/string/test_string.py
Fixes https://github.com/pola-rs/polars/issues/18238.
From the docs, (https://docs.pola.rs/api/python/stable/reference/expressions/api/polars.Expr.str.replace_all.html#polars-expr-str-replace-all), when literal=True, then capture groups should be ignored. As the docs say:
```
The dollar sign ($) is a special character related to capture groups. To refer to a literal dollar sign, use $$ instead or set literal to True.
```
Fix the Rust logic which did not apply this logic for multi-row replacement.
> fix: Capture groups should be ignored in replace_all when literal=True

- crates/polars-stream/src/async_executor/mod.rs
- crates/polars-stream/src/execute.rs
- crates/polars-stream/src/skeleton.rs
A profiler is useless in an async engine if something is a blocking bottleneck - all threads will just show spending a lot of time in condvar waiting inside the executor loop.
With this PR if you set `POLARS_TRACK_WAIT_STATS=1` we track the time between right before we park a thread, and when that thread finds a new task, and adds the time spent blocked to that tasks metadata. After a new streaming query we print these stats, which can look like this:
```
Time spent waiting for async tasks:
crates/polars-stream/src/nodes/parquet_source/mod.rs:230 - 971.347764ms
crates/polars-stream/src/nodes/parquet_source/init.rs:179 - 493.140887ms
crates/polars-stream/src/nodes/in_memory_source.rs:75 - 16.806251ms
crates/polars-stream/src/nodes/in_memory_sink.rs:58 - 4.832292ms …
```
> refactor(rust): Add tracking of async task wait time statistics

- crates/polars-parquet/src/arrow/write/schema.rs
> refactor: Improve error message for Zero-Field Structs with Parquet

- py-polars/polars/io/parquet/functions.py
This can be passed directly after https://github.com/pola-rs/polars/pull/18532
> refactor(python): Remove unsued bytes->BytesIO conversion

- crates/polars-io/src/json/mod.rs
- crates/polars-json/src/json/deserialize.rs
- crates/polars-json/src/ndjson/deserialize.rs
- crates/polars-ops/src/chunked_array/strings/json_path.rs
- py-polars/tests/unit/io/test_json.py
- py-polars/tests/unit/operations/namespaces/string/test_string.py
Fixes https://github.com/pola-rs/polars/issues/13061
* Raise if JSON data cannot be decoded to dtype instead of silently appending NULL
* Raise if there are extra keys in struct data outside of the schema instead of silently ignoring them
```python
print(pl.Series([None, "1"]).str.json_decode(infer_schema_length=1))
#
print(
pl.Series(['{"a": 1}', '{"a": 2, "b": 2}']).str.json_decode(infer_schema_length=1)
)
#
```
Todo: I think our NDJSON and JSON readers also suffer from this issue
> fix: Raise on data mismatch in `str.json_decode`

- py-polars/polars/io/database/functions.py
- py-polars/tests/unit/io/database/test_read.py
This PR improves the typing of `read_database_uri` by adding overloads so that the core set of exceptions it raises are caught by type-checkers, that being:
Trying to pass in `excecute_options` with the connector is `connector-x`:
```python
df = pl.read_database_uri(
"SELECT * from user",
"postgresql://localhost:5432/postgres",
execute_options={"Test": None},
)
```
And, passing in a list of strings when `adbc` is the driver:
```python
df = pl.read_database_uri(
["SELECT 1", "SELECT * from user"],
"postgresql://localhost:5432/postgres",
engine="adbc",
)
```
I personally encountered the first, and would have valued from having this represented through the overloads.
> feat: Improve `read_database_uri` typing

- crates/polars-arrow/src/array/iterator.rs
- crates/polars-arrow/src/bitmap/iterator.rs
- crates/polars-compute/src/lib.rs
- crates/polars-compute/src/var_cov.rs
- crates/polars-core/src/chunked_array/ops/aggregate/var.rs
- crates/polars-ops/src/chunked_array/cov.rs
This uses a new algorithm that should be more numerically stable, and is also 2x faster on my machine than the old implementation.
It's also written in such a way that it can be easily parallelized and integrated into the streaming engine now.
> perf: Improve var/cov/corr performance

- py-polars/polars/io/cloud/_utils.py
- py-polars/polars/io/cloud/credential_provider.py
Adds support for using an assumed role to `CredentialProviderAWS`
```python
pl.scan_parquet(
"s3://.../...",
credential_provider=pl.CredentialProviderAWS(
assume_role={
"RoleArn": "arn:aws:iam::0000000:role/ExampleRole",
"RoleSessionName": "example",
}
),
)
```
ref https://github.com/pola-rs/polars/issues/18979
ref https://github.com/pola-rs/polars/issues/15838
> feat(python): AssumeRole support for AWS Credential Provider

- crates/polars-python/src/dataframe/general.rs
- py-polars/tests/unit/dataframe/test_getitem.py
Fixes the _reported_ part of #19358, but there may be other similar regressions as yet unreported.
Given that caveat, @ritchie46 also wanted to (temporarily) revert #19199 too since that's what made this regression start happening.
The full fix will be #19382, after which #19199 can be reapplied.
> fix(python): Release GIL in `gather_with_series()` and friend

- Cargo.lock
- Cargo.toml
- crates/polars-python/Cargo.toml
- crates/polars-python/src/conversion/mod.rs
- crates/polars-python/src/file.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- crates/polars-utils/src/python_function.rs
Partially reverts #19199
At the request of Ritchie. Apparently this should solve a deadlock.
@ritchie46 is a full revert needed or just the version rollback?
> build: Revert PyO3 version back to `0.21`

- crates/polars-io/src/cloud/credential_provider.rs
- crates/polars-io/src/cloud/object_store_setup.rs
We use the memory address `*const T` of the `Arc<T>` instead.
> refactor(rust): Don't pickle entire python function for object store keying

- py-polars/polars/_reexport.py
- py-polars/polars/dataframe/frame.py
- py-polars/polars/datatypes/convert.py
- py-polars/polars/io/spreadsheet/functions.py
- py-polars/polars/lazyframe/frame.py
- py-polars/polars/schema.py
- py-polars/polars/series/struct.py
- py-polars/tests/unit/constructors/test_constructors.py
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/datatypes/test_list.py
- py-polars/tests/unit/datatypes/test_struct.py
- py-polars/tests/unit/datatypes/test_temporal.py
- py-polars/tests/unit/interop/test_from_pandas.py
- py-polars/tests/unit/interop/test_interop.py
- py-polars/tests/unit/io/test_spreadsheet.py
- py-polars/tests/unit/operations/test_group_by.py
- py-polars/tests/unit/test_schema.py
- py-polars/tests/unit/test_selectors.py
A few improvements (arguably fixes) for equality/inequality checks, and dtype init:
*  We require that a `Schema` is initialised with instantiated dtypes (and make a point of it in the docstring), but don't actually check that we are given such; this PR validates that nested dtypes _are_ given in instantiated form (eg: `pl.List(Float64)`, not just `pl.List`), as without the inner dtype we don't actually have a valid `Schema`. I haven't done a full recursive check (eg: walking into `Struct` fields), but can look at it in a second pass.
* Uninstantiated non-nested types (such as `Int64` that do _not_ take modifying parameters) are allowed, and are automatically instantiated on the way in to guarantee that a `Schema` instance is _always_ composed of instantiated dtypes. Those that take …
> feat(python): Various `Schema` improvements (equality/init dtype checks)

- crates/polars-pipe/src/executors/sources/csv.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/hstack.rs
- py-polars/tests/unit/io/test_scan.py
- py-polars/tests/unit/test_projections.py
Was a challenging puzzle as it turned out to be a combination of different bugs in different places from where I thought the issue was.
Fixes https://github.com/pola-rs/polars/issues/19172 : Wrong columns shifting during scan with row index
* Caused by accidentally passing full schema instead of `reader_schema`
Fixes https://github.com/pola-rs/polars/issues/19397 : include_file_paths for streaming CSV causes PanicException: index out of bounds: the len is 5 but the index is 5
* Caused by accidentally passing full schema instead of `reader_schema`
Fixes https://github.com/pola-rs/polars/issues/19395 : `with_columns` may not push down projections if schema length remains unchanged
> fix: Fix `include_file_paths` and `with_row_index` for streaming CSV scan

- crates/polars-expr/src/expressions/gather.rs
Fixes https://github.com/pola-rs/polars/issues/15163.
> fix: Allow .get(null) in groupby context

- Cargo.lock
- crates/polars-arrow/Cargo.toml
- crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/mod.rs
- crates/polars-arrow/src/legacy/kernels/time.rs
- crates/polars-core/Cargo.toml
- crates/polars-core/src/frame/mod.rs
- crates/polars-ops/Cargo.toml
- crates/polars-ops/src/frame/join/args.rs
- crates/polars-ops/src/series/ops/is_between.rs
- crates/polars-plan/src/dsl/function_expr/bitwise.rs
- crates/polars-plan/src/dsl/options.rs
- crates/polars-python/src/lazyframe/visit.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- crates/polars-python/src/lazyframe/visitor/nodes.rs
- crates/polars-time/Cargo.toml
- crates/polars-time/src/windows/group_by.rs
Previously we were just ignoring this, which meant we would sometimes fail to fall back correctly in the GPU engine.
> refactor(python): Expose group_by_dynamic in pyir

- py-polars/polars/io/iceberg.py
- py-polars/tests/unit/io/test_iceberg.py
This PR adds support for querying historical table snapshots when using `scan_iceberg` by adding an optional "snapshot_id" argument that is propagated to the underlying pyiceberg DataScan.
> feat(python): Support querying specific snapshot by id in scan_iceberg

- crates/polars-core/src/frame/group_by/perfect.rs
- py-polars/tests/unit/operations/unique/test_unique.py
Fixes https://github.com/pola-rs/polars/issues/19409.
> fix: Bug in group_tuples_perfect, tail was not processed properly

- py-polars/polars/expr/datetime.py
- py-polars/polars/series/datetime.py
> depr(python): Make some parameters of `dt.add_business_days` keyword-only

- crates/polars-ops/src/frame/join/dispatch_left_right.rs
- crates/polars-ops/src/frame/join/hash_join/mod.rs
- crates/polars-ops/src/frame/join/mod.rs
- py-polars/Cargo.toml
- py-polars/tests/unit/operations/test_join.py
Fixes https://github.com/pola-rs/polars/issues/19405
Fixes https://github.com/pola-rs/polars/issues/19403
A long time ago a fast-path was added to left-join that would identify a left-join didn't have any duplicate matches by checking the height of the join_tuples matches the height of the input DF:
https://github.com/pola-rs/polars/commit/2f5f3ecf3aff3ba6cb403692c56cef2b1ea114f9#diff-33db4b397429a6dc2297400e2fe812fb12f17ed977dfeee5f96e34fdb9b05757R728-R730
At some point we added slicing to the input left DF and also the join tuples, meaning that we would incorrectly identify the left-join as having no duplicate matches.
> fix: Incorrect `.join(..., how="left").head(N)` if `N <= left_df.height()` and there are duplicate matches

- crates/polars-io/src/csv/read/parser.rs
Very small PR. I found it a little annoying that the error message recommends using an argument that has been deprecated and gives a warning, instead of recommending the updated argument. So I decided to try and fix it :smile:
> fix: Updates error message in csv parser to recommend schema_overrides instead of deprecated dtypes argument

- crates/polars-lazy/src/physical_plan/exotic.rs
- py-polars/tests/unit/operations/namespaces/list/test_list.py
Fixes https://github.com/pola-rs/polars/issues/19317
Fixes https://github.com/pola-rs/polars/issues/19345
> fix: Fix `ColumnNotFound` when using `pl.element()` inside `list.eval`

- py-polars/docs/source/reference/series/string.rst
- py-polars/polars/series/string.py
- py-polars/tests/unit/operations/namespaces/string/test_string.py
Just noticed the new `Expr.str.escape_regex()` did not yet have an entry In the Series dispatch code.
> feat(python): Add Series `.str.escape_regex()` 

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-mem-engine/src/planner/lp.rs
- crates/polars-stream/src/nodes/io_sinks/ipc.rs
- crates/polars-stream/src/nodes/io_sinks/mod.rs
- crates/polars-stream/src/nodes/mod.rs
- crates/polars-stream/src/physical_plan/fmt.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/mod.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
- crates/polars-stream/src/skeleton.rs
> feat: Add IPC sink in new streaming engine

- crates/polars-plan/src/dsl/function_expr/strings.rs
- py-polars/tests/unit/operations/namespaces/string/test_string.py
Followup to https://github.com/pola-rs/polars/pull/19366
```
in replace, when literal=True, then capture groups should be ignored.
```
I missed that in the original bug report, https://github.com/pola-rs/polars/issues/18238, the capture group issue affects `replace` in addition to `replace_all`.
This fixed the capture group logic for  `replace`.
> fix: Capture groups should be ignored in replace when literal=True

- crates/polars-sql/src/functions.rs
- py-polars/docs/source/reference/sql/functions/trigonometry.rst
The docs for `ATAN2` and `ATAN2D` (SQL functions) were incorrect because they claimed to be dividing `arg2/arg1` where it is actually the other way around. 
Alternatively, one could swap the arguments in the implementation, but I like the implementation and it follows `numpy`. 
Also, I changed the example in the docstring so that it uses lengths of 0, 1, or 2, and not the ambiguous "lengths" of 90, 360 etc.
> docs: Fix docstrings for ATAN2 and ATAN2D SQL functions

- crates/polars-python/src/lazyframe/general.rs
- py-polars/polars/_typing.py
- py-polars/polars/io/cloud/_utils.py
- py-polars/polars/io/cloud/credential_provider.py
- py-polars/polars/io/csv/functions.py
- py-polars/polars/io/ipc/functions.py
- py-polars/polars/io/ndjson.py
- py-polars/polars/io/parquet/functions.py
- py-polars/tests/unit/io/cloud/test_cloud.py
* read_parquet
* scan_csv
* scan_ndjson
* read_ndjson
* scan_ipc
Was not added to `read_csv` and `read_ipc` as they use fsspec
> feat(python): Add `credential_provider` argument to more read functions

- crates/polars-core/src/chunked_array/comparison/mod.rs
- py-polars/tests/unit/datatypes/test_struct.py
- py-polars/tests/unit/io/test_parquet.py
Fixes https://github.com/pola-rs/polars/issues/19156
> fix: Ensure struct `eq/ne_missing` also compares outer validity

- crates/polars-python/src/functions/lazy.rs
Since the Python side of the function is set up so that `None` does not come here, it does not seem to make sense for `ambiguous` to actually be an Option.
https://github.com/pola-rs/polars/blob/7a2f547d8792e3f37444b1d7680e3ba795979c66/py-polars/polars/functions/as_datatype.py#L26-L38
https://github.com/pola-rs/polars/blob/7a2f547d8792e3f37444b1d7680e3ba795979c66/py-polars/polars/functions/as_datatype.py#L134
> refactor(python): Simplify rust side of `datetime`

- crates/polars-plan/src/dsl/function_expr/mod.rs
- crates/polars-plan/src/dsl/function_expr/rolling.rs
- crates/polars-plan/src/dsl/function_expr/schema.rs
- crates/polars-plan/src/dsl/functions/correlation.rs
- crates/polars-python/src/lazyframe/visit.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
Still not a native rolling, but should improve. On a single thread I get a ca `5-8`x improvement over pandas.
> perf: Move rolling_corr/cov to an actual implementation on Series

- crates/polars-core/src/chunked_array/cast.rs
- py-polars/tests/unit/operations/test_cast.py
Fixes https://github.com/pola-rs/polars/issues/19424
Regression from https://github.com/pola-rs/polars/commit/f562b13dc6b775fd5bc8fe066598b5ed4a6efb92?diff=split&w=0#diff-2fa673dd53f64440ab23998a2ab3c26a2e465abdf3599c339db7072d110cfe9bR203-R224
> fix: Ensure sorted flag is unset after Int->String cast

- crates/polars-plan/src/dsl/selector.rs
- crates/polars-plan/src/plans/conversion/expr_expansion.rs
Closes #19456.
Note: while the Issue mentions selectors, the problem was more generic; selectors were just an easy way to trigger it. 
Tracked it down to the nesting of `replace_columns_with_column` inside the `expand_columns` loop, which introduced quadratic behaviour in column name comparisons. Refactored the function so the expensive "names" comparison could be moved outside of the loop and only done once, and streamlined the relevant code. 
New code is half the size and `O(n)` ✌️
(Did a minor cleanup of `replace_selector_inner` since I was looking at it, but no performance impact there).
```python
from codetiming import Timer
import random
for n_cols in (500, 1000, 2500, 5000, 10000, 25000, 50000):
df = pl.DataFrame({f"col{i}": [0] for …
```
> fix: Address inadvertent quadratic behaviour in `expand_columns`

- py-polars/polars/convert/general.py
- py-polars/tests/unit/interop/test_from_pandas.py
Fixes: #18859
For `pd.Series` I don't think it is a good idea to ignore the `include_index` argument if the index is the default index. Otherwise, the resulting type depends of the data.
> feat(python): Respect `include_index` for pandas series

- crates/polars-io/src/cloud/credential_provider.rs
- crates/polars-ops/src/chunked_array/list/to_struct.rs
- crates/polars-plan/src/dsl/function_expr/list.rs
- crates/polars-plan/src/dsl/list.rs
- crates/polars-python/src/expr/list.rs
- py-polars/polars/_typing.py
- py-polars/polars/exceptions.py
- py-polars/polars/expr/list.py
- py-polars/polars/series/list.py
- py-polars/tests/unit/operations/namespaces/list/test_list.py
- py-polars/tests/unit/test_errors.py
If we receive a list of names in the `fields` parameter, we will be able to return a dtype in `to_field` (or if we have a non-zero upper_bound)
Also refactors to define `list.to_struct` to be a `ListFunction` in the IR.
```python
print(lf.select(pl.first().list.to_struct(fields=["a", "b"])).collect_schema())
print(lf.select(pl.first().list.to_struct(fields=str, upper_bound=1)).collect_schema())
print(lf.select(pl.first().list.to_struct(upper_bound=1)).collect_schema())
print(lf.select(pl.first().list.to_struct(fields=str)).collect_schema())
print(lf.select(pl.first().list.to_struct()).collect_schema())
print(lf.select(pl.first().list.to_struct(upper_bound=1)).collect())
```
> fix: Make output dtype known for `list.to_struct` when `fields` are passed

- crates/polars-core/src/frame/mod.rs
- py-polars/tests/unit/test_errors.py
> fix: Properly raise on mean_horizontal with wrong dtypes

- crates/polars-sql/src/sql_expr.rs
- py-polars/tests/unit/sql/test_miscellaneous.py
Closes #19426.
Fixes a rogue `unwrap` and adds some test coverage.
> fix: Don't panic in SQL temporal string check; raise suitable `ColumnNotFound` error

- crates/polars-core/src/series/mod.rs
- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
> fix: Include Array in `to_physical`

- py-polars/polars/io/database/functions.py
- py-polars/tests/unit/io/database/test_read.py
This pull request aims to improve type hints in the codebase.
- The `query` parameter in `read_database` currently [accepts only `str` and `Selectable` types](https://github.com/pola-rs/polars/blob/425e251fa3fed25f1956fb5486ed1e41f51ce170/py-polars/polars/io/database/functions.py#L31), but `execute` [can handle `str | TextClause | Selectable`](https://github.com/pola-rs/polars/blob/425e251fa3fed25f1956fb5486ed1e41f51ce170/py-polars/polars/io/database/_executor.py#L476).
- In practice, `read_database` can execute successfully with a `TextClause` argument.
- However, mypy flags this as an error, causing issues during type-checking as in https://github.com/pola-rs/polars/actions/runs/11515095096/job/32055062473?pr=19444
- Added a test case that uses SQLAlchemy's `text` to validate that …
> feat: Improve `read_database` typing

- crates/polars-parquet/src/arrow/write/dictionary.rs
- crates/polars-parquet/src/arrow/write/fixed_size_binary/basic.rs
- crates/polars-parquet/src/arrow/write/fixed_size_binary/mod.rs
- crates/polars-parquet/src/arrow/write/fixed_size_binary/nested.rs
- crates/polars-parquet/src/arrow/write/mod.rs
- py-polars/tests/unit/io/test_parquet.py
This implements writing the writing of arbitrary nested `FixedSizeBinary`, which in particular allows for the writing of nested high-precision decimals. This removes the silent data-loss that was happening before.
Fixes #19448.
> feat: Implement nested Parquet writing for High-Precision Decimals

- .github/workflows/release-python.yml
- Cargo.toml
- Makefile
- README.md
- py-polars/Makefile
This does a couple things:
1. We now properly match the CPU flags to that of our release. Specify `LTS_CPU=1` e.g. `make build-release LTS_CPU=1` to build a lts-cpu variant.
2. You can now pass along arguments to maturin through the makefile commands, e.g. `make build ARGS="--no-default-features"`.
3. I redefined the build profiles. We now have (ordered by compilation speed):
| Name  | Optimization | Debug assertions | Debug symbols | Compilation Speed |
| - | - | - | - | - |
| `debug` | No | Yes | Yes | Fastest |
| `nodebug-release` | Yes | No | No | Slow |
| `release` | Yes | No | Minimal | Slower |
| `debug-release` | Yes | No | Yes | Slower still |
| `dist-release` | Extreme | No | No | Slowest |
Almost all the time you want `debug`, which is just `make build`. If you are …
> refactor: Improve makefile build commands

- crates/polars-python/src/dataframe/general.rs
- crates/polars-python/src/expr/general.rs
- crates/polars-python/src/expr/rolling.rs
- crates/polars-python/src/functions/range.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-time/src/windows/duration.rs
- py-polars/tests/unit/functions/range/test_date_range.py
- py-polars/tests/unit/functions/range/test_datetime_range.py
- py-polars/tests/unit/test_errors.py
> fix: Make Duration parsing fallible and not panic

- .github/workflows/benchmark.yml
- .github/workflows/test-python.yml
- crates/polars-python/Cargo.toml
This means it will be part of the next release, but still as an undocumented early prototype. The increase in binary size is fairly minimal (~2MB).
> refactor(rust): Enable new_streaming feature by default

- crates/polars-lazy/Cargo.toml
- crates/polars-plan/src/dsl/string.rs
- crates/polars-stream/Cargo.toml
Closes https://github.com/pola-rs/polars/issues/19485
> build(rust): Fix some feature flag issues

- crates/polars-stream/src/nodes/filter.rs
- crates/polars-stream/src/nodes/group_by.rs
- crates/polars-stream/src/nodes/in_memory_map.rs
- crates/polars-stream/src/nodes/in_memory_sink.rs
- crates/polars-stream/src/nodes/in_memory_source.rs
- crates/polars-stream/src/nodes/input_independent_select.rs
- crates/polars-stream/src/nodes/io_sinks/ipc.rs
- crates/polars-stream/src/nodes/map.rs
- crates/polars-stream/src/nodes/mod.rs
- crates/polars-stream/src/nodes/multiplexer.rs
- crates/polars-stream/src/nodes/ordered_union.rs
- crates/polars-stream/src/nodes/parquet_source/mod.rs
- crates/polars-stream/src/nodes/reduce.rs
- crates/polars-stream/src/nodes/select.rs
- crates/polars-stream/src/nodes/simple_projection.rs
- crates/polars-stream/src/nodes/streaming_slice.rs
- crates/polars-stream/src/nodes/with_row_index.rs
- crates/polars-stream/src/nodes/zip.rs
Just a bit more readable, `recv` and `send` was being shadowed a lot.
> refactor(rust): Rename ComputeNode::spawn parameters

- crates/polars-arrow/src/array/mod.rs
- crates/polars-arrow/src/compute/cast/binary_to.rs
- crates/polars-core/src/chunked_array/list/iterator.rs
- crates/polars-core/src/frame/row/mod.rs
- crates/polars-expr/src/expressions/ternary.rs
- crates/polars-expr/src/expressions/window.rs
- crates/polars-ffi/src/version_0.rs
- crates/polars-io/src/csv/write/write_impl/serializer.rs
- crates/polars-io/src/ipc/ipc_file.rs
- crates/polars-io/src/ipc/ipc_stream.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-mem-engine/src/executors/group_by_partitioned.rs
- crates/polars-ops/src/frame/join/general.rs
- crates/polars-ops/src/frame/pivot/positioning.rs
- crates/polars-parquet/src/arrow/read/schema/mod.rs
- crates/polars-parquet/src/parquet/read/page/reader.rs
- crates/polars-pipe/src/executors/sinks/group_by/generic/ooc_state.rs
- crates/polars-pipe/src/executors/sinks/group_by/ooc_state.rs
- crates/polars-pipe/src/executors/sinks/joins/cross.rs
- crates/polars-pipe/src/executors/sinks/sort/sink.rs
- crates/polars-pipe/src/operators/chunks.rs
- crates/polars-plan/src/dsl/functions/syntactic_sugar.rs
- crates/polars-plan/src/plans/optimizer/cluster_with_columns.rs
- crates/polars-plan/src/plans/optimizer/simplify_expr/mod.rs
- crates/polars-python/src/file.rs
- crates/polars-utils/src/vec.rs
- py-polars/polars/convert/general.py
- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/series/test_scatter.py
Ran a regex[^1] over the codebase after spotting some repeated words; cleaned them up.
[^1]: `\b([A-Za-z]+)[ ]{1,2}\1\b`
> docs: Fix various instances of repeated words in docs and comments

- crates/polars-arrow/Cargo.toml
- crates/polars-arrow/src/compute/take/fixed_size_list.rs
- crates/polars-lazy/Cargo.toml
- crates/polars-plan/Cargo.toml
- crates/polars/Cargo.toml
- py-polars/tests/unit/operations/test_gather.py
Outer validity of the array was not accounted for in the fast-path, causing outer NULLs to be unmasked.
Fixes https://github.com/pola-rs/polars/issues/19482
> fix: Incorrect gather for FixedSizeList with outer validity but no inner validities

- Cargo.toml
- Makefile
This adds a profile that forgoes full debug information to more quickly iterate on code.
Clean compile times:
```
mindebug-dev: 3m42s
debug: 4m13s
```
> chore: Add `mindebug-dev` rust profile

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-plan/src/plans/conversion/join.rs
- py-polars/tests/unit/operations/test_inequality_join.py
Ref: https://github.com/pola-rs/polars/pull/18365
One of the most useful applications of `join_where` is range joins, and the `is_between` expression is a natural way to express such ranges. This PR allows for use of such in the list of join predicates, streamlining these queries.
Also improved several related error messages, providing more detail if a given predicate is not suitable for use with `join_where` (such as actually including that predicate in the error).
Setup:
```python
"id": ["aa", "bb", "cc"],
"start": [date(2020,1,1), date(2022,10,10), date(2024,7,5)],
"end": [date(2022,12,31), date(2024,10,1), date(2024,12,31)],
})
"id": ["aa", "cc", "bb"],
"dt": [date(2022,12,31), date(2024,2,21), date(2024,8,8)],
"price": …
```
> feat: Support use of `is_between` range predicate with IEJoin operations (`join_where`)

- py-polars/tests/unit/operations/rolling/test_rolling.py
This PR is for fixing a small issue in the test `test_rolling_by_integer`.
This was noticed here: https://github.com/pola-rs/polars/pull/19071#discussion_r1824515876
> test(python): Fix `test_rolling_by_integer` not using parameterized dtype

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-plan/src/plans/conversion/join.rs
- py-polars/tests/unit/operations/test_inequality_join.py
Following on from #19547.
Small ease of use improvement for predicate conjunctions passed to `join_where`. 
Decomposes `And` conjunctions internally, rather than raise an unnecessary error (as it does now), so the caller can create and pass a single expression (instead of `n` expressions). Handles nested `And` (eg: `p1 & ((p2 & p3) & p4)`)
The following are all now allowed, and equivalent: 
```python
df1.join_where(
df2,
predicate1,
predicate2,
predicate3,
predicate4,
)
```
```python
df1.join_where(
df2,
predicate1 & predicate2,
predicate3 & predicate4,
)
```
```python
df1.join_where(
df2,
predicate1 & predicate2 & predicate3 & predicate4
)
```
> feat: Streamline use of predicates connected by `&` with IEJoin (`join_where`)

- crates/polars-plan/src/plans/conversion/type_coercion/functions.rs
- py-polars/tests/unit/datatypes/test_categorical.py
While trying to enforce type validation on all namespace functions, I encountered a lot of type erros inside the tests
> fix: Correct categorical namespace error message

- Cargo.lock
- Cargo.toml
- crates/polars-arrow/Cargo.toml
- crates/polars-arrow/src/compute/cast/binary_to.rs
- crates/polars-io/Cargo.toml
- crates/polars-io/src/csv/read/buffer.rs
- crates/polars-parquet/Cargo.toml
- crates/polars-utils/Cargo.toml
Also updated other packages.
closes #19541
closes #13035
> chore: Move to fast-float2

- crates/polars-ops/src/frame/join/args.rs
- crates/polars-plan/src/plans/conversion/join.rs
- crates/polars-plan/src/plans/optimizer/collapse_joins.rs
- crates/polars-plan/src/plans/optimizer/collect_members.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
- py-polars/tests/unit/operations/test_inequality_join.py
Inequality joins are, from the optimizer's point of view, the same as cross joins: they logically produce a cartesian product that is then filtered. Consequently, if a predicate combines columns from both tables, we cannot push the filter into the join.
- Fixes #19580
> fix(rust,python): Fix predicate pushdown into inequality joins

- crates/polars-ops/src/chunked_array/binary/namespace.rs
`starts_with` can use the views. We don't do that yet.
> perf: Use faster iteration in 'starts_with'/'ends_with'

- crates/polars-io/src/cloud/options.rs
- py-polars/tests/unit/io/cloud/test_credential_provider.py
Attempting to load default credentials may cause errors
ref https://github.com/pola-rs/polars/issues/18979#issuecomment-2450425632
> fix: Do not attempt to load default credentials when `credential_provider` is given

- crates/polars-stream/src/nodes/in_memory_source.rs
- crates/polars-stream/src/nodes/parquet_source/mod.rs
This ensures a stop request is propagated to all tasks as soon as possible.
> refactor(rust): Share source token between all sender tasks of source nodes in new-streaming engine

- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-mem-engine/src/executors/scan/parquet.rs
- crates/polars-pipe/src/executors/sources/parquet.rs
- crates/polars-stream/src/nodes/parquet_source/init.rs
- crates/polars-stream/src/nodes/parquet_source/metadata_fetch.rs
- crates/polars-stream/src/nodes/parquet_source/mod.rs
- crates/polars-stream/src/nodes/parquet_source/row_group_decode.rs
- crates/polars-utils/src/index.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
- py-polars/tests/unit/operations/namespaces/test_meta.py
Fixes https://github.com/pola-rs/polars/issues/19607
Fixes https://github.com/pola-rs/polars/issues/19606
Issues affect queries of the form:
```python
scan_parquet(...).with_row_index().slice(-N, ...)
scan_parquet(...).with_row_index().tail(N)
scan_parquet(...).with_row_index().collect(streaming=True)
```
For the negative-slice case we need to adjust the `RowIndex` offset accordingly. If we see that we need to add a row index we cannot stop early during reversed metadata scan, but instead need to scan through the metadata of the entire list of files to figure out the correct offset to begin from.
The other issue with streaming parquet was just forgetting to add the current row offset.
> fix: Fix incorrect `scan_parquet().with_row_index()` with non-zero slice or with streaming collect

- .github/dependabot.yml
Relevant docs here:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
This functionality was introduced about a year ago - it wasn't available yet when I set up dependabot for this repo.
This should drastically reduce the number of PRs opened by dependabot each month.
> ci: Configure grouped Dependabot updates

- crates/polars-plan/src/dsl/struct_.rs
- py-polars/tests/unit/datatypes/test_struct.py
Closes https://github.com/pola-rs/polars/issues/17356
```python
"x": [[{"a": 1, "b": 2}], [{"a": 3, "b": 4}]]
})
pl.col.x.list.eval(pl.element().struct.with_fields(c = pl.field("a") + 10))
)    
```
All tests still pass - but I'm not sure if there may be a reason why the flag is currently disabled.
> fix: Allow `.struct.with_fields` inside `list.eval`

- crates/polars-plan/src/dsl/array.rs
- crates/polars-plan/src/dsl/functions/temporal.rs
- crates/polars-plan/src/dsl/list.rs
- py-polars/tests/unit/functions/as_datatype/test_datetime.py
- py-polars/tests/unit/operations/namespaces/array/test_array.py
- py-polars/tests/unit/operations/namespaces/list/test_set_operations.py
Fixes #18795 
Continuing from the previous PR (#19449), have fixed wildcard/input expansion for a few more functions by removing INPUT_WILDCARD_EXPANSION  - 
Before -
```
df = pl.DataFrame({"a": [1], "b": [2]})
print(df.select(pl.datetime(year=pl.all(),month=pl.all(),day=pl.all()).name.keep() ))
shape: (1, 1)
┌─────────────────────┐
│ a                   │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ 0001-02-01 02:01:02 │
└─────────────────────┘
```
After - 
```
df = pl.DataFrame({"a": [1], "b": [2]})
print(df.select(pl.datetime(year=pl.all(),month=pl.all(),day=pl.all()).name.keep() ))
shape: (1, 2)
┌─────────────────────┬─────────────────────┐
│ a                   ┆ b                   │
│ ---                 ┆ ---                 │
│ datetime[μs]        ┆ …
```
> fix: Correct wildcard and input expansion for some more functions

- crates/polars-plan/src/plans/conversion/join.rs
- py-polars/tests/unit/operations/test_join.py
- py-polars/tests/unit/operations/test_join_asof.py
We previously ran type coercion for the left (respectively right) key expressions with the schema of the output join node active. This is incorrect since the keys may not even refer to column names in the output (if the expressions do not refer to columns). Instead, the left (right) key expressions must be coerced with the left (right) inputs active.
With this done, we now no longer need to run type coercion on the resulting Join node, and instead must just add it to the arena.
- Fixes #19597
> fix(rust): Run join type coercion with correct schemas active

- crates/polars-core/src/frame/mod.rs
> fix: Copy height in .vstack() for empty dataframes (#19641)

- crates/polars-time/src/windows/calendar.rs
This is a completely random shot as I was just reading polars source code for fun and have no insights into it. I can imagine the rust compiler optimises this anyway but I'd rule out 75 % of cases in the first check rather than 0.25 %.
> perf: Reorder conditions in is_leap_year

- py-polars/polars/expr/string.py
- py-polars/polars/series/string.py
Closes #19527 (and #19523).
The explanation relating to use of "$" (as part of a capture group reference vs use as a literal in the replacement value) was a little ambiguous/incomplete. Have made the explanation (given in the "Notes" section) clearer, with an illustrative example for each `replace` and `replace_all` function.
> docs: Improve `replace` and `replace_all` docstring explanation of the "$" character with reference to capture groups (vs use as a literal)

- crates/polars-core/src/frame/mod.rs
- py-polars/tests/unit/operations/aggregation/test_aggregations.py
- py-polars/tests/unit/operations/aggregation/test_horizontal.py
The `mean_horizontal` expression was the _only_ specialised horizontal function that wouldn't raise an error on incompatible input - instead it just filtered that input for the numeric/boolean columns, checked there was at least one, and operated on those. 
This is inconsistent; `selectors` can be used to trivially choose numeric columns - the expression shouldn't be doing it silently (and it isn't documented that it would do so).
Incompatible input now raises a clear error.
**Also:** 
Allow `Decimal` in `mean_horizontal` (was omitted by an `.is_numeric()` dtype check).
* **Catch invalid input**
```python
"cola": [D("1.5"), D("0.5"), D("5"), D("0"), D("-0.25")],
"colb": [[0,1], [2], [3,4], [5], [6]],
"colc": ["aa", …
```
> fix: Ensure `mean_horizontal` raises on non-numeric input

- py-polars/polars/_typing.py
According to the docs you can map a column name to `None` to let Polars infer the data type of the given column. If you use `None`, that's what happens, but typing complains because it's not expecting the value `None`, only an explicit data type.
> fix(python): Fix typing for SchemaDefinition

- crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
- py-polars/tests/unit/test_predicates.py
Fixes https://github.com/pola-rs/polars/issues/19632
> fix: Fix filter incorrectly pushed past struct unnest when unnested column name matches upper column name

- crates/polars-sql/src/context.rs
- crates/polars-sql/src/sql_expr.rs
- py-polars/tests/unit/sql/test_joins.py
* Exposes the `right join` support added in #17441 up to the SQL interface.
* Fixes #17552, where a SELECT on a single `alias.*` wildcard would _always_ select from the left-most frame; the columns are now resolved with respect to the alias in all cases.
* Additional test coverage for these cases, and join aliasing in general.
Establish some test frames:
```python
"a": [1, 2, 3],
"b": ["x", "y", "z"],
"c": [100, 200, 300],
})
"a": [1, 3, 2],
"b": ["qq", "pp", "oo"],
"c": [400, 500, 600],
})
```
Apply a `RIGHT JOIN` (new feature)...
...returning all cols from the _right-most_ frame (bugfix):
```python
pl.sql("""
SELECT df2.*
FROM df1 RIGHT JOIN df2 USING (a) ORDER BY a
""").collect()
```
> feat: Add SQL support for `RIGHT JOIN`, fix an issue with wildcard aliasing

- crates/polars-io/src/csv/read/buffer.rs
- crates/polars-io/src/csv/read/mod.rs
- crates/polars-io/src/csv/read/options.rs
- crates/polars-io/src/csv/read/parser.rs
- crates/polars-io/src/csv/read/read_impl.rs
- crates/polars-io/src/csv/read/read_impl/batched.rs
- crates/polars-io/src/csv/read/reader.rs
- crates/polars-io/src/csv/read/schema_inference.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-mem-engine/src/executors/scan/csv.rs
- crates/polars-mem-engine/src/executors/scan/ndjson.rs
- crates/polars-plan/src/plans/ir/scan_sources.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-time/src/chunkedarray/string/infer.rs
- crates/polars-time/src/chunkedarray/string/patterns.rs
- py-polars/tests/unit/io/test_csv.py
Some prep work.
As a side effect this also adds support parsing `Time` when reading CSV.
> refactor: Factor out logic for re-use by new streaming CSV source

- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/operations/test_fill_null.py
> fix(python): Fix fill null types

- crates/polars-expr/src/expressions/apply.rs
- crates/polars-expr/src/planner.rs
- crates/polars-plan/src/plans/aexpr/schema.rs
- py-polars/tests/unit/lazyframe/test_lazyframe.py
- py-polars/tests/unit/test_schema.py
Fixes https://github.com/pola-rs/polars/issues/19562
* `Explode` during dtype resolution mistakenly indicated that it did not need auto-imploding (see the `nested` variable in the code)
* Also adjusts the output dtype getting/checking logic for FunctionExpr to adhere to:
* If the function indicates RETURNS_SCALAR, its output dtype shall always be scalar (i.e. .agg(col(f64).sum()) -> Float64)
* Otherwise, if we are in a Context::Aggregation, we auto-implode the dtype (i.e. .agg(col(f64).shuffle()) -> list[Float64])
* Assertion was also adjusted during execution in `ApplyExpr`
* To do this properly we also propagate the `Context` recursively
> fix: Fix incorrect lazy schema for `explode()` in `agg()`

- crates/polars-sql/src/context.rs
- crates/polars-sql/tests/statements.rs
- py-polars/tests/unit/sql/test_joins.py
Improved SQL "JOIN ON" constraint resolution; there was a lot of redundant code in  `process_join_constraint` - now delegates properly to `process_join_on`, noticeably streamlining it (and making it easier to integrate some other upcoming fixes).
> refactor: Streamline internal SQL join condition processing

- crates/polars-io/src/csv/read/read_impl/batched.rs
- crates/polars-lazy/src/tests/streaming.rs
- crates/polars/tests/it/io/csv.rs
- py-polars/tests/unit/io/test_csv.py
Updates to use the new `CountLines` instead of the previous `accept_line` based logic, which had some incorrect edge cases.
> fix: Update line-splitting logic in batched CSV reader

- Cargo.lock
- crates/polars-lazy/Cargo.toml
- crates/polars-python/Cargo.toml
- crates/polars-python/src/functions/lazy.rs
- crates/polars-python/src/functions/misc.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- crates/polars-python/src/lazyframe/visitor/nodes.rs
- crates/polars-stream/Cargo.toml
- crates/polars-stream/src/nodes/io_sinks/mod.rs
- crates/polars-stream/src/nodes/mod.rs
- crates/polars-stream/src/physical_plan/fmt.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
- crates/polars/Cargo.toml
We should do this instead of unconditionally enabling things.
> refactor(rust): Delegate feature flags for polars-stream

- crates/polars-arrow/src/array/boolean/mod.rs
- crates/polars-arrow/src/array/mod.rs
- crates/polars-arrow/src/array/primitive/mod.rs
- crates/polars-arrow/src/bitmap/immutable.rs
- crates/polars-core/src/chunked_array/logical/categorical/mod.rs
- crates/polars-core/src/chunked_array/object/extension/mod.rs
- crates/polars-core/src/chunked_array/object/extension/polars_extension.rs
- crates/polars-core/src/chunked_array/struct_/mod.rs
- crates/polars-core/src/frame/explode.rs
- crates/polars-core/src/frame/group_by/mod.rs
- crates/polars-core/src/series/amortized_iter.rs
- crates/polars-core/src/series/mod.rs
- crates/polars-core/src/series/ops/downcast.rs
- crates/polars-core/src/series/series_trait.rs
- crates/polars-io/src/csv/read/options.rs
- crates/polars-io/src/shared.rs
- crates/polars-lazy/src/scan/csv.rs
- crates/polars-plan/src/dsl/mod.rs
- crates/polars-plan/src/plans/aexpr/mod.rs
- crates/polars/Cargo.toml
I added two feature flags to make sure they're included in the docs and when I was adding a bit of detail to a docstring I noticed a link was formatted in the wrong way. Ended up using a regex to find all such poorly formatted links across the Rust API docs.
> docs: Assorted fixes to Rust API docs

- py-polars/polars/_utils/udfs.py
- py-polars/tests/unit/operations/map/test_inefficient_map_warning.py
Ref: #9968
Can now identify (and warn against) Python-side string `replace` in UDFs:
```python
df = pl.DataFrame({"s1": ["x::y::z"]})
s2 = pl.col("s1").map_elements(lambda s: s.replace(":", ""))
)
s2 = pl.col("s1").map_elements(lambda s: s.replace(":", "", 2))
)
```
> feat: Identify inefficient use of Python string `replace` in `map_elements`

- py-polars/polars/series/series.py
I wondered about the rounding behaviour and ended up putting in a script to test it myself. If I'd seen this example it would have cleared it up for me very quickly!
> docs: Alter examples for round_sig_figs to make behaviour clearer

- crates/polars-core/src/frame/column/mod.rs
- crates/polars-core/src/series/arithmetic/bitops.rs
- crates/polars-core/src/series/arithmetic/mod.rs
- crates/polars-core/src/series/implementations/boolean.rs
- crates/polars-core/src/series/implementations/mod.rs
- crates/polars-core/src/series/series_trait.rs
- crates/polars-python/src/series/general.rs
This removes the `Series::{bitand, bitor, bitxor}` functions and instead moves them to the `std::ops::...` traits.
> refactor: Move Series bitops to `std::ops::Bit...`

- crates/polars-core/src/frame/column/mod.rs
- crates/polars-core/src/frame/column/scalar.rs
- crates/polars-core/src/scalar/from.rs
- crates/polars-core/src/testing.rs
- crates/polars-ops/src/series/ops/replace.rs
This is a continuation of #19660.
> refactor: Remove more `@scalar-opt`

- crates/polars-core/src/chunked_array/array/mod.rs
- crates/polars-core/src/series/arithmetic/borrowed.rs
- crates/polars-core/src/series/implementations/floats.rs
- crates/polars-core/src/series/implementations/mod.rs
- py-polars/tests/unit/datatypes/test_array.py
Fixes #19679.
Along side two other issues.
Issue 1:
```python
a = pl.Series('a', [[[1, 2, 3], [4, 5, 6]]], pl.Array(pl.Int64, (2, 3)))
print(a + pl.Series([1]))
print(pl.Series([1]) + a)
```
```console
shape: (1,)
Series: 'a' [array[i64, (2, 3)]]
[
[[2, 3, 4], [5, 6, 7]]
]
File "/home/johndoe/Projects/polars/array_elementwise_bug.py", line 6, in <module>
print(pl.Series([1]) + a)
~~~~~~~~~~~~~~~^~~
File "/home/johndoe/Projects/polars/py-polars/polars/series/series.py", line 1045, in __add__
return self._arithmetic(other, "add", "add_<>")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/johndoe/Projects/polars/py-polars/polars/series/series.py", line 994, in _arithmetic
return self._from_pyseries(getattr(self._s, op_s)(other._s)) …
```
> fix: Make Array arithmetic ops fully elementwise

- crates/polars-core/src/chunked_array/ops/fill_null.rs
- crates/polars-core/src/frame/column/mod.rs
- crates/polars-core/src/frame/column/scalar.rs
- crates/polars-core/src/frame/mod.rs
- crates/polars-core/src/series/mod.rs
- crates/polars-core/src/series/series_trait.rs
- crates/polars-ops/src/chunked_array/gather/chunked.rs
- crates/polars-ops/src/frame/join/dispatch_left_right.rs
This keeps `ScalarColumn` in even more places.
> refactor: Use `Column` for the `{try,}_apply_columns{_par,}` functions on `DataFrame`

- docs/source/user-guide/io/excel.md
The user guide page for Excel files has not been updated to account for calamine as the default reader. The PR updates the page along with some minor edits
> docs: Update Excel page of user guide to refer to fastexcel as the default engine

- crates/polars-expr/src/expressions/alias.rs
- crates/polars-expr/src/expressions/apply.rs
- crates/polars-expr/src/expressions/binary.rs
- crates/polars-expr/src/expressions/cast.rs
- crates/polars-expr/src/expressions/literal.rs
- crates/polars-expr/src/expressions/mod.rs
- crates/polars-expr/src/planner.rs
- crates/polars-io/src/predicates.rs
- py-polars/tests/unit/io/test_scan.py
`StatsEvaluator` currently only works if the inputs are literals as it directly takes from the `Expr` - 
* `col('A') < lit(1)` - [ok]
* `col('A') < lit('2024-01-01').str.strptime(..)` - [err]
* This type of predicate is created by `LazyFrame.sql()` - as it does not have access to the IR context / schema during creation.
This PR adds an `evaluate_inline` to `PhysicalExpr` with some basic support for literals, casting and `FuntionExpr`s. The function is intended to evaluate to `Some(column)` only if we consider the operation to be cheap:
* `Cast` / `FunctionExpr` will only evaluate if the input is of length 1, which is generally the case with literals in predicate expressions
* A depth_limit is used to protect against highly nested expressions
* Some PhysicalExprs also cache the result in a …
> perf: Improve hive partition pruning with datetime predicates from SQL

- crates/polars-core/src/frame/mod.rs
- crates/polars-mem-engine/src/executors/stack.rs
- crates/polars-mem-engine/src/planner/lp.rs
- py-polars/tests/benchmark/test_with_columns.py
> perf: Fix quadratic 'with_columns' behavior

- crates/polars-time/src/windows/window.rs
- py-polars/tests/unit/operations/test_group_by_dynamic.py
> fix: In group_by_dynamic, period and every were getting applied in reverse order for the window upper boundary

- py-polars/polars/io/spreadsheet/functions.py
- py-polars/tests/unit/io/test_spreadsheet.py
Remove dead private functions previously used in `_read_spreadsheet`. I'm assuming remove private functions isn't considered breaking within Polars, but let me know if there's disagreement here.
> refactor: Remove Dead Excel Code

- py-polars/polars/io/spreadsheet/functions.py
- py-polars/tests/unit/io/test_spreadsheet.py
This PR fixes https://github.com/pola-rs/polars/issues/19711 ensuring that a no data error is raised for Calamine reads even when schema overrides are provided.
> fix(python): Ensure `NoDataError` raised consistently between engines for Excel reads

- py-polars/polars/dataframe/frame.py
In the non-overloaded case it would still make sense to use a Literal for both options.
> feat(python): Improve `n_chunks` typing

- crates/polars-sql/src/sql_expr.rs
- py-polars/tests/unit/sql/test_conditional.py
Closes #19707.
When omitted, the `ELSE` branch in a `CASE WHEN…` should be implicitly equivalent to `ELSE NULL`.
Ref: https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-CASE
> fix: SQL `ELSE` clause should be implicitly `NULL` when omitted

- crates/polars-io/src/cloud/polars_object_store.rs
In the existing logic we didn't coalesce this if the `<massive range>` was large enough that the distance to the `chunk_size` would be too big.
But I do think this is more of a nitpick as we probably don't encounter this case very often 😄
> perf: Adjust coalesce for `[<tiny range>, <massive range>]`

- crates/polars-core/src/chunked_array/ops/sort/arg_bottom_k.rs
- crates/polars-core/src/chunked_array/ops/sort/arg_sort.rs
- crates/polars-core/src/chunked_array/ops/sort/categorical.rs
- crates/polars-core/src/chunked_array/ops/sort/mod.rs
- crates/polars-core/src/chunked_array/ops/sort/options.rs
- crates/polars-core/src/frame/mod.rs
- crates/polars-expr/src/expressions/sortby.rs
- crates/polars-lazy/src/tests/aggregations.rs
- crates/polars-lazy/src/tests/queries.rs
- crates/polars-ops/src/chunked_array/top_k.rs
- crates/polars-ops/src/frame/join/hash_join/sort_merge.rs
- crates/polars-pipe/src/executors/sinks/sort/source.rs
- crates/polars-python/src/expr/general.rs
- crates/polars-python/src/functions/lazy.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-python/src/series/general.rs
- py-polars/tests/unit/operations/test_top_k.py
Closes #19281
We went into row-encoding. This dispatches to primitives and thus saves an expensive encoding and a very expensive comparison function (strcmp).
> perf: Improve `DataFrame.sort().limit/top_k` performance

- py-polars/polars/datatypes/classes.py
`cls` should be taken for this class method.
> fix(python): Use `cls` for `to_python`

- crates/polars-io/src/cloud/polars_object_store.rs
Reverts https://github.com/pola-rs/polars/pull/19730 - from benchmarking it performed worse.
In hindsight it's not worth adding that rule - even without it we will only have up to half of our requests being tiny in the worst case (in this worst case they would be interleaved).
> perf: Fix cloud download speed regression

- crates/polars-core/src/datatypes/dtype.rs
- crates/polars-plan/src/dsl/function_expr/bounds.rs
- crates/polars-python/src/datatypes.rs
- py-polars/polars/datatypes/classes.py
- py-polars/src/lib.rs
- py-polars/tests/unit/test_datatypes.py
> feat(rust,python): Implement max/min methods for dtypes

- py-polars/polars/io/database/_executor.py
Closes #19729 (hopefully).
I do not have access to an SAP HANA instance to validate the fix, but some investigation and careful reading of [their docs](https://help.sap.com/docs/SAP_HANA_CLIENT/f1b440ded6144a54ada97ff95dac7adf/3b89755ceec042e5919313b40acf8794.html?locale=en-US#example) and the associated examples shows that they return a non-standard value from `Cursor.execute` - boolean "True" instead of the usual "None" or a ResultSet object of some kind. Accounting for this is a one-liner that won't impact anything else, and I'm _fairly_ optimistic that it'll work 🤔
> feat(python): Try to support native SAP HANA driver via `read_database`

- docs/source/user-guide/transformations/joins.md
> docs: Fix join API reference links

- docs/source/user-guide/expressions/index.md
`dprint` misformats nested lists because of differences in the implementation of dprint's MD parser and the one used by Sphinx (I think that was it). Hats off to @marcogorelli for letting me know on Discord.
> docs: Fix formatting of nested list

- py-polars/polars/selectors.py
- py-polars/tests/unit/test_selectors.py
Closes #19740.
Should resolve as an intersection, not a union.
```python
"a": [1],
"b": [2]
})
```
**Before**
```python
df.select(cs.by_name("a") & pl.col("b"))
```
**After**
```python
df.select(cs.by_name("a") & pl.col("b"))
```
> fix(python): Address incorrect `selector & col` expansion

- .github/workflows/test-coverage.yml
- crates/polars-plan/src/plans/aexpr/schema.rs
- py-polars/tests/unit/test_schema.py
Fixes https://github.com/pola-rs/polars/issues/19752
Also adjusts a CI workflow file to fix code coverage
> fix: Fix incorrect lazy schema for aggregations

- crates/polars-plan/src/dsl/function_expr/array.rs
- crates/polars-plan/src/plans/aexpr/schema.rs
- crates/polars-plan/src/plans/optimizer/simplify_expr/simplify_functions.rs
- py-polars/tests/unit/operations/test_join.py
- py-polars/tests/unit/test_schema.py
Fixes https://github.com/pola-rs/polars/issues/19763
Our lazy schema for an exploded array column was not correct. I think this was only starting causing issues with joins after https://github.com/pola-rs/polars/pull/19625 because we never used this schema information before then
> fix: Fix incorrect lazy schema for explode on array columns

- crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
- py-polars/tests/unit/test_predicates.py
Fixes https://github.com/pola-rs/polars/issues/19772
> fix: Fix incorrect filter after right-join on LazyFrame

- crates/polars-python/src/cloud.rs
- crates/polars-python/src/dataframe/construction.rs
- crates/polars-python/src/dataframe/export.rs
- crates/polars-python/src/dataframe/general.rs
- crates/polars-python/src/functions/range.rs
- crates/polars-python/src/interop/arrow/to_rust.rs
- crates/polars-python/src/interop/numpy/to_numpy_df.rs
- crates/polars-python/src/interop/numpy/to_numpy_series.rs
- crates/polars-python/src/map/mod.rs
- crates/polars-python/src/map/series.rs
Fixes #19382 
This (hopefully) covers the rest of the APIs. I skipped APIs that seemed immediate, and so I may have missed some, but hopefully coverage is significantly better.
There should be no other meaningful code changes, just GIL releasing.
> fix(python): Release the GIL in Python APIs, part 2 of 2

- crates/polars-plan/src/dsl/meta.rs
- crates/polars-python/src/expr/meta.rs
- py-polars/docs/source/reference/expressions/meta.rst
- py-polars/polars/expr/meta.py
- py-polars/tests/unit/operations/namespaces/test_meta.py
Added a simple `is_literal` extension to the "meta" namespace.
(There's a slight subtlety when matching datetime literals, as an implicit strict-cast gets injected; otherwise it's just simple matching).
```python
for value in (123, "four five", datetime.now()):
e = pl.lit(value)
e.meta.is_literal()
e = pl.lit(value).alias("foo")
e.meta.is_literal()
e = pl.lit(value).alias("foo")
e.meta.is_literal(allow_aliasing=True)
```
> feat: Add an `is_literal` method to expression `meta` namespace

- crates/polars-python/src/batched_csv.rs
- py-polars/polars/io/csv/batched_reader.py
- py-polars/tests/unit/io/test_csv.py
> fix(python): Respect schema_overrides in batched csv reader

- py-polars/polars/expr/meta.py
- py-polars/polars/lazyframe/frame.py
Link to Graphviz download is now formatted correctly ([see the docs](https://docs.pola.rs/api/python/stable/reference/lazyframe/api/polars.LazyFrame.show_graph.html#polars.LazyFrame.show_graph)). Fixed a couple of other tiny formatting issues while I was in the area.
> docs(python): Fix link to Graphviz download

- py-polars/polars/dataframe/plotting.py
- py-polars/polars/series/plotting.py
- py-polars/tests/unit/operations/namespaces/test_plot.py
closes #19787
An alternative would be to just never pass `tooltip` in the generic case, but I think `inspect.signature` is safe enough
> fix: Altair tooltip was being incorrectly applied to plots which did not accept it

- crates/polars-arrow/src/compute/take/binary.rs
- crates/polars-arrow/src/compute/take/boolean.rs
- crates/polars-arrow/src/compute/take/mod.rs
- crates/polars-core/src/hashing/vector_hasher.rs
- crates/polars-expr/src/groups/mod.rs
- crates/polars-expr/src/groups/row_encoded.rs
- crates/polars-expr/src/hash_keys.rs
- crates/polars-expr/src/lib.rs
- crates/polars-stream/src/nodes/group_by.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
This will be used in both the join / reduce interfaces to abstract over a key dataframe which may or may not be pre-hashed.
> refactor(rust): Use HashKeys abstraction

- py-polars/polars/dataframe/_html.py
- py-polars/tests/unit/dataframe/test_repr_html.py
Fixes #19665
Before:
After:
I've added a small unit test that checks for a right output for the repr in `test_repr_html.py`, not sure if it's the correct location. Please let me know.
> fix(python): Replace spaces with &nbsp; to support showing multiple spaces in HTML repr

- py-polars/polars/dataframe/frame.py
User coming from pandas will try to get the equivalent of `df.set_index([key1, key2]).to_dict()` but can easily miss `row_by_keys`. I think adding `row_by_keys` in the "see also" section of `to_dict` is a good addition
> docs(python): Mention `row_by_keys` in the `to_dict` documentation

- crates/polars-core/src/series/implementations/null.rs
- py-polars/tests/unit/operations/test_filter.py
> fix: Fix filter scalar nulls

- crates/polars-arrow/src/array/primitive/mutable.rs
- crates/polars-core/src/chunked_array/object/mod.rs
- crates/polars-parquet/src/parquet/encoding/mod.rs
- crates/polars-parquet/src/parquet/encoding/uleb128.rs
> fix(rust): Fix inconsistency between code and comment

- crates/polars-core/src/series/implementations/object.rs
fixes #18665
supersedes #19796
> fix: Fix object chunked gather

- crates/polars-lazy/src/scan/csv.rs
The `LazyCsvReader` appears to consume significant memory for certain inputs. This is primarily due to the large default `chunk_size` (262144) in the `CsvReadOptions`. While the `low_memory` option can help in some cases, it may not be sufficient for all use cases, introducing a way to control the amount of data that will be read and stored in memory can mitigate potential out-of-memory (OOM) issues at the cost of performance.
Related issues:
- https://github.com/pola-rs/polars/issues/17714
> feat(rust): Allow specification of `chunk_size` on `LazyCsvReader.read_options`

- crates/polars-expr/src/groups/row_encoded.rs
- crates/polars-utils/Cargo.toml
- crates/polars-utils/src/idx_map/bytes_idx_map.rs
- crates/polars-utils/src/idx_map/mod.rs
- crates/polars-utils/src/lib.rs
This is a very minimal byte-key-only `IndexMap` implementation we can then re-use in both the grouper and join code for strings, bytes and row-encoded keys.
Only the bare minimum for the grouper is implemented, feel free to add methods as needed.
> refactor(rust): Add BytesIndexMap and use in RowEncodedHashGrouper

- crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
- crates/polars-stream/src/async_primitives/wait_group.rs
- crates/polars-stream/src/nodes/csv_source.rs
- crates/polars-stream/src/nodes/mod.rs
- crates/polars-stream/src/nodes/parquet_source/init.rs
- crates/polars-stream/src/nodes/parquet_source/mod.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
- py-polars/polars/_utils/various.py
- py-polars/polars/convert/general.py
- py-polars/polars/io/csv/functions.py
- py-polars/tests/unit/io/test_csv.py
- py-polars/tests/unit/io/test_scan.py
- py-polars/tests/unit/io/test_spreadsheet.py
Adds a simple CSV source - we have one thread scanning for line batches which get sent to other threads for parsing
The performance is mostly equivalent with the in-memory-engine, except for one very specific type of query -
```python
q = pl.scan_csv(path_base + "yellow_tripdata_2015-01.csv").slice(10_000_000)
print(q.collect())
```
> refactor(rust): Add new streaming CSV source

- py-polars/polars/_utils/construction/dataframe.py
- py-polars/polars/_utils/construction/series.py
- py-polars/polars/_utils/construction/utils.py
- py-polars/polars/io/database/_executor.py
- py-polars/tests/unit/io/database/test_read.py
Closes #19816.
* With a trivial extension to the existing Sequence checks we can support direct DataFrame/Series init from a list of SQLAlchemy Row objects, as they intentionally mimic namedtuple in various ways[^1].
* This allows for a _**very** small_ (low single-digit percentage) speedup ingesting SQLAlchemy results via `read_database`, so I've taken advantage of that (against a 50000x10 row test dataset I was seeing ~1-2% gains, so it's extremely marginal - but it's not zero, so...)
[^1]: [sqlalchemy.engine.Row](https://docs.sqlalchemy.org/en/20/core/connections.html#sqlalchemy.engine.Row)
> feat(python): Support DataFrame init from raw SQLAlchemy rows

- crates/polars-plan/src/plans/conversion/join.rs
- py-polars/tests/unit/test_errors.py
> fix: Don't panic if column not found

- docs/source/src/python/user-guide/misc/visualization.py
Previously bokeh charts where saved as html with inline resources. This seems to have led to charts not appearing on first load and bokeh errors on subsequent loads as it tries to re-load resources. Now bokeh resources are instead loaded from CDN each time and the error disappears when I render in gh-pages.
Closes #19722
> docs(python): Update bokeh to use cdn to avoid Bokeh Error

- py-polars/polars/expr/expr.py
> fix: Type hints for window_size incorrectly included timedelta in some rolling functions

- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-io/src/pl_async.rs
Ensure we don't block tokio threads on compute.
> perf: Move row group decode off async thread for local streaming parquet scan

- crates/polars-core/src/utils/supertype.rs
- py-polars/tests/unit/operations/test_unpivot.py
> fix: Raise if merge non-global categoricals in unpivot

- crates/polars-io/src/pl_async.rs
Removes the division by 4 before clamping when calculating the async thread pool size.
This may benefit low core count systems, specifically those with less than 16 cores. Any potential performance gains may be observed particularly in systems with up to 7 cores, as the difference between having 1 vs 2 async threads is the most substantial.
| rayon threadpool size | old async thread count | new async thread count |
|-----------------------|------------------------|------------------------|
| 1                     | 1                      | 1                      |
| 2                     | 1                      | 2                      |
| 3                     | 1                      | 3                      |
| 4                     | 1                      | 4                      | …
> perf: Increase default async thread count for low core count systems

- crates/polars-plan/src/dsl/expr.rs
- crates/polars-plan/src/plans/aexpr/schema.rs
- crates/polars-plan/src/utils.rs
- py-polars/tests/unit/test_schema.py
> fix: Validate subnodes in validate IR

- crates/polars-plan/src/plans/conversion/expr_expansion.rs
- py-polars/polars/expr/list.py
closes #19812
```python
>>> df = pl.DataFrame({"a": [[1, 2, 3]]})
>>> df.select(pl.col("a").list.to_struct().struct.unnest()
InvalidOperationError                     Traceback (most recent call last)
Cell In[3], line 2
1 df = pl.DataFrame({"a": [[1, 2, 3]]})
----> 2 df.select(pl.col("a").list.to_struct().struct.unnest())
File ~/code/polars/py-polars/polars/dataframe/frame.py:9029, in DataFrame.select(self, *exprs, **named_exprs)
8929 def select(
8930     self, *exprs: IntoExpr | Iterable[IntoExpr], **named_exprs: IntoExpr
8931 ) -> DataFrame:
8932     """
8933     Select columns from this DataFrame.
8934 
(...)
9027     └──────────────┘
9028     """
-> 9029     return self.lazy().select(*exprs, …
```
> feat: Raise informative error on Unknown unnest

- py-polars/polars/io/database/_executor.py
- py-polars/polars/io/database/_utils.py
- py-polars/polars/io/database/functions.py
Closes #19800. 
Fixed the typing and while i was at it i fixed the typing a little deeper, including returning Iterator from inner functions and importing Selectable correctly in an if TYPE_CHECKING block.
> fix(python): Fix `read_database(…,iter_batches=True)` type annotations

- Cargo.lock
- crates/polars-python/Cargo.toml
- crates/polars-python/src/dataframe/general.rs
- crates/polars-python/src/datatypes.rs
- crates/polars-python/src/series/general.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/test_row_encoding.py
This adds the following method to be used internally to create tests.
- `pl.DataFrame._row_encode()`
- `pl.Series._row_decode()`
With this I added a bunch of tests to see the current state of row encoding.
> chore: Add proper tests for row encoding

- crates/polars-compute/src/filter/mod.rs
This adds a small step before doing a `filter` and trims away the leading and trailing filtered rows. This cost us practically nothing in the cases where there are no items to trim and saves massively where it can trim items. This is for example in cases where we are filtering by at least one sorted column.
Here is a code snippet to show the effectiveness. Before, it had to copy the memory and go into the filter loop. Now, it can just take the fast path. This also holds for sorted columns which is where I think most of the performance will come from.
```python
import os
SIZE = 10_000_000
os.environ['POLARS_MAX_THREADS'] = '1'
df = pl.DataFrame([
pl.Series('f', sum(([i] * (SIZE // 10) for i in range(10)), []), pl.Int32),
] + …
```
> perf: Initially trim leading and trailing filtered rows

- crates/polars-core/src/prelude.rs
- crates/polars-ops/src/chunked_array/gather/chunked.rs
- crates/polars-ops/src/frame/join/dispatch_left_right.rs
- crates/polars-ops/src/frame/join/hash_join/mod.rs
- crates/polars-pipe/src/executors/sinks/joins/generic_probe_inner_left.rs
- crates/polars-pipe/src/executors/sinks/joins/generic_probe_outer.rs
- crates/polars-utils/src/index.rs
We want to use a different bit width in the streaming join.
> refactor(rust): Make chunked gathers generic over chunk bit width

- docs/source/src/python/user-guide/expressions/categoricals.py
- docs/source/user-guide/expressions/structs.md
- docs/source/user-guide/installation.md
CI failure unrelated (VSCode marketplace URL is flaky).
> docs: Fix some warnings during docs build

- crates/polars-core/src/chunked_array/ops/row_encode.rs
- crates/polars-pipe/src/executors/sinks/group_by/generic/eval.rs
- crates/polars-pipe/src/executors/sinks/joins/generic_build.rs
- crates/polars-pipe/src/executors/sinks/joins/row_values.rs
- crates/polars-pipe/src/executors/sinks/sort/sink_multiple.rs
- crates/polars-python/src/dataframe/general.rs
- crates/polars-row/src/encode.rs
- py-polars/tests/unit/test_row_encoding.py
> fix: Properly handle Zero-Field Structs in row encoding

- py-polars/tests/benchmark/test_with_columns.py
I think this fails in CI a bit more often than we'd want - to address this, I've increased `num_columns` from 2,000 to 10,000. I've also updated the assertion to check the runtime relative to the time taken for applying calling `with_columns` on 10 columns rather than an exact time.
> test(python): Adjust flaky `with_columns` test

- crates/polars-core/src/series/arithmetic/borrowed.rs
- crates/polars-core/src/series/arithmetic/fixed_size_list.rs
- crates/polars-core/src/series/arithmetic/list.rs
- crates/polars-core/src/series/arithmetic/mod.rs
- py-polars/tests/unit/operations/arithmetic/test_array.py
- py-polars/tests/unit/operations/arithmetic/test_list.py
Fixes https://github.com/pola-rs/polars/issues/19839
We didn't validate that the `list` side of an arithmetic operation between `list<->primitive` columns has a `list` type at all nesting levels. This causes a panic when we later attempt to downcast to a numeric array type.
```python
pyo3_runtime.PanicException: not implemented for dtype Struct([Field { name: "a", dtype: Int64 }])
polars.exceptions.InvalidOperationError: cannot add columns: dtype was not list on all nesting levels: (left: list[struct[1]], right: i64)
```
Some drive-bys:
* Rename `arithmetic/list_borrowed.rs -> arithmetic/list.rs` (under `polars-core`)
* Rename `arithmetic/test_list_arithmetic.py -> arithmetic/test_list.py` (under `py-polars/tests`)
> fix: Raise informative error instead of panicking for list arithmetic on some invalid dtypes

- Cargo.lock
- Cargo.toml
- crates/polars-python/Cargo.toml
- crates/polars-python/src/conversion/mod.rs
- crates/polars-python/src/file.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- crates/polars-utils/src/python_function.rs
Now that much more of the Python API releases the GIL, the chance of deadlocks is lower and it seems worth upgrading to 0.22 again (especially since 0.23 was just released, and that is going to be its own whole thing...).
This reverts commit e1dfcdd186f2ddcc120a1e71bb14b90018c6dd89.
> chore: Switch back to PyO3 0.22

- crates/polars-io/src/hive.rs
- py-polars/tests/unit/io/test_hive.py
Fixes https://github.com/pola-rs/polars/issues/19861
This error occurs in the merge operation for the case where hive columns are also present in the data file and a `with_row_index()` is requested.
> fix: Fix panic using `scan_parquet().with_row_index()` with hive partitioning enabled

- py-polars/polars/expr/expr.py
> docs: Complete parameters description and add an example for `clip()`

- crates/polars-core/src/chunked_array/temporal/conversion.rs
- crates/polars-core/src/chunked_array/temporal/date.rs
- crates/polars-core/src/chunked_array/temporal/duration.rs
- crates/polars-core/src/chunked_array/temporal/time.rs
- py-polars/polars/expr/datetime.py
- py-polars/polars/series/datetime.py
- py-polars/tests/unit/datatypes/test_temporal.py
A follow-up to enable stricter ISO formatting for `dt.to_string()` with Datetime.
See https://github.com/pola-rs/polars/pull/19697#discussion_r1845979731 for the rationale/details 🤔
* `"iso"`: (what we have now) each _component_ is ISO, joined with a space (this was valid ISO 8601 for the majority of the spec's lifetime, but now falls under RFC 3339 - see the comments below for more explanation/details, and the "Spec Arcana" section).
* `"iso:strict"`: (new) same as the above, but with a "T" separator between date/time instead of a space; this conforms to the latest ISO spec amendment, ISO 8601-1:2019).
Making the "T" mandatory for Datetimes was an amendment made (around five years ago) in ISO 8601-1:2019. Consequently you will see _both_ forms (with a space or with a "T") used widely, …
> feat: Support both "iso" and "iso:strict" format options for `dt.to_string`

- py-polars/polars/dataframe/frame.py
- py-polars/polars/ml/utilities.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/ml/test_to_jax.py
- py-polars/tests/unit/ml/test_to_torch.py
Closes #19092.
This addresses some issues exporting 2D `pl.Array` data to PyTorch/Jax.
(Assuming support for ragged Tensors/Arrays is present in the target library we could consider supporting export from List data as an enhancement - for now List raises a `TypeError` suggesting use of Array 🤔)
Establish a test frame containing some 2D Array data:
```python
"sample": [1, 1, 1, 2, 2, 2],
"seq_pos": [2, 0, 1, 0, 1, 2],
"f1": np.random.rand(6),
"f2": np.random.rand(6),
}).sort(
by=["seq_pos"]
).group_by("sample").agg(
pl.concat_list("f1", "f2").alias("features")
).with_columns(
pl.col("features").cast(pl.Array(pl.Float64, (3,2)))
)
```
Export to PyTorch `Dataset`:
```python
ds = df.to_torch("dataset", label="sample")
ds.labels …
```
> fix(python): Improve export from 2D Array dtype columns to PyTorch Tensors (`to_torch`) and Jax Arrays (`to_jax`)

- crates/polars-python/src/conversion/any_value.rs
- py-polars/tests/unit/functions/range/test_date_range.py
Fixes a non-deterministic bug in AnyValue conversion from Python, where the incorrect object conversion function would be used when constructing from a Python object. This occurs when there are multiple dynamically created classes being used.
We have a cache `static LUT` for `get_conversion_function` keyed by the `usize` pointer address of the Python type class. This didn't account for dynamically constructed type objects that may be freed during execution. If a different type object gets allocated to the same location as a previously freed type object, we would incorrectly use the conversion_function meant for the previous type object.
<details>
<summary>Traceback</summary>
This is a traceback that I believe to be caused by the bug:
```shell
2024-11-19T11:31:25.2828286Z …
```
> fix: Ensure type object of inputs for cached any-value conversion functions are kept alive

- crates/polars-io/src/path_utils/mod.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/ir/scan_sources.rs
- py-polars/polars/io/delta.py
- py-polars/tests/unit/constructors/test_constructors.py
- py-polars/tests/unit/io/test_delta.py
- py-polars/tests/unit/io/test_hive.py
- py-polars/tests/unit/io/test_lazy_parquet.py
Fixes https://github.com/pola-rs/polars/issues/19876
Fixes https://github.com/pola-rs/polars/issues/19854
Fixes https://github.com/pola-rs/polars/issues/19890
For the case when `scan_parquet` is done on an empty directory and `schema` was given, we should return an empty DataFrame. Currently this case isn't accounted for in some areas of the code causing some errors / panics.
Also fixes a mypy lint issue due to a new pydantic release
> fix: Fix panic with empty delta scan, or empty parquet scan with a provided schema

- crates/polars-core/src/frame/mod.rs
- py-polars/tests/unit/dataframe/test_df.py
Closes https://github.com/pola-rs/polars/issues/19795.
> fix: Misleading `ShapeError` error message on dataframe creation

- crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
- py-polars/tests/unit/test_predicates.py
Fixes https://github.com/pola-rs/polars/issues/19772
> fix: Fix incorrect result from inequality filter after join on LazyFrame

- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- py-polars/tests/unit/io/test_hive.py
This is more of a quality-of-life change. After this PR if users do `scan_parquet(<glob or file path>, hive_schema={...})`, we will automatically enable hive partitioning instead of silently ignoring the `hive_schema`.
> feat: Auto-enable hive partitioning if hive_schema was given

- crates/polars-io/src/hive.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-plan/src/plans/hive.rs
- py-polars/tests/unit/io/test_hive.py
- py-polars/tests/unit/io/test_parquet.py
Fixes https://github.com/pola-rs/polars/issues/19766
We didn't handle hive columns properly in the prefiltering implementation
> fix: Fix panic with combination of hive and parquet prefiltering

- py-polars/polars/_utils/getitem.py
- py-polars/tests/unit/dataframe/test_getitem.py
- py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
- py-polars/tests/unit/series/test_getitem.py
Closes #19882.
* Resolves indexing error/edge-case with `np.array(n)` on DataFrame and Series `__getitem__`.
* Adds some extra coverage (and splits out the numpy indexing into its own test).
* ~~Drive-by fix for an overnight update that triggers some new `mypy` lint errors (in "test_constructors").~~
> fix(python): Address indexing edge-case with `numpy` arrays

- crates/polars-time/src/windows/group_by.rs
Adds a small branch that ensures we skip very expensive computations on duplicates.
closes #19912
> perf: Rolling 'iter_lookbehind' breeze through duplicates

- crates/polars-arrow/src/array/dictionary/typed_iterator.rs
- crates/polars-arrow/src/array/fixed_size_list/mod.rs
- crates/polars-arrow/src/offset.rs
- crates/polars-arrow/src/trusted_len.rs
- crates/polars-core/src/chunked_array/ops/row_encode.rs
- crates/polars-row/src/decode.rs
- crates/polars-row/src/encode.rs
- crates/polars-row/src/fixed.rs
- crates/polars-row/src/variable.rs
- py-polars/tests/unit/test_row_encoding.py
This adds row encoding and decoding for nested types.
It is now possible to properly roundtrip `pl.List`, `pl.Array` and `pl.Struct` including their outer and inner validities through the row encoding en decoding.
Fixes #10747.
> refactor: Implement nested row encoding / decoding

- crates/polars-arrow/src/array/binview/view.rs
- crates/polars-ops/src/chunked_array/strings/mod.rs
- crates/polars-ops/src/chunked_array/strings/namespace.rs
- crates/polars-ops/src/chunked_array/strings/starts_with.rs
- crates/polars-plan/src/dsl/function_expr/strings.rs
The string view type has a small (4 or <12 bytes) prefix inlined that we can use for comparisons. From a small test this is about the same speed on a worst case (search prefix > 12 bytes, string not inlined) and more than twice as fast on a best case (string <12 bytes so entirely inlined).
> feat(rust): Speed up starts_with for small prefixes

- py-polars/polars/dataframe/_html.py
- py-polars/tests/unit/dataframe/test_repr_html.py
Closes #19859.
Note: the related Issue isn't a Polars bug, it's a configurable setting in JetBrains IDEs.
However, we don't need to substitute _all_ spaces in the HTML output in order to preserve whitespace, just consecutive ones (eg: two or more adjacent spaces). This adjustment will tidy-up HTML table rendering in IDEs where showing special characters is the default.
> refactor(python): Minor non-breaking space (`&nbsp;`) tweak for HTML rendering

- py-polars/polars/datatypes/_parse.py
- py-polars/polars/datatypes/classes.py
- py-polars/tests/unit/constructors/test_dataframe.py
- py-polars/tests/unit/datatypes/test_enum.py
- py-polars/tests/unit/datatypes/test_parse.py
Closes https://github.com/pola-rs/polars/issues/19724
Python Enums (and `StrEnum`s) can now be used as `dtype` inputs, and can be passed to the Polars `Enum` constructor.
> feat(python): Allow Python Enums as dtype inputs

- crates/polars-arrow/src/bitmap/mutable.rs
- crates/polars-row/src/encode.rs
- crates/polars-row/src/fixed.rs
- crates/polars-row/src/row.rs
- crates/polars-row/src/variable.rs
- py-polars/tests/unit/test_row_encoding.py
This changes the encoding of `pl.Boolean` in the row encoding from needing 2 bytes (1 for validity, 1 for value) to 1 byte. Now, the encoding of Boolean values is as follows:
| Value   | Encoding |
|---------|----------|
| `None`  | `0x00`   |
| `False` | `0x20`   |
| `True`  | `0x30`   |
The null is bitwise inverted for `nulls_last=True` and `False` / `True` are inverted for `descending=True`.
This is a continuation of #19874.
> perf: Half the size of Booleans in row encoding

- crates/polars-arrow/src/compute/cast/primitive_to.rs
- py-polars/tests/unit/operations/test_cast.py
> fix: Raise InvalidOperationError for invalid float to decimal casts (e.g. Inf, NaN)

- crates/polars-time/src/windows/group_by.rs
Same as #19922 but for all paths.
> perf: Memoize duplicates in rolling-gb-dyn

- crates/polars-core/src/series/any_value.rs
- py-polars/tests/unit/datatypes/test_object.py
> fix: Fix scalar object

- crates/polars-arrow/src/array/primitive/mutable.rs
- crates/polars-core/src/chunked_array/builder/list/primitive.rs
- crates/polars-ops/src/chunked_array/strings/find_many.rs
- crates/polars-plan/src/dsl/function_expr/range/int_range.rs
- crates/polars-plan/src/dsl/function_expr/strings.rs
- crates/polars-plan/src/dsl/string.rs
- crates/polars-python/src/expr/string.rs
- crates/polars-python/src/lazyframe/visit.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- py-polars/docs/source/reference/expressions/string.rst
- py-polars/docs/source/reference/series/string.rst
- py-polars/polars/expr/string.py
- py-polars/polars/series/string.py
- py-polars/tests/unit/operations/namespaces/string/test_string.py
> feat: Add AhoCorasick backed 'find_many'

- crates/polars-time/src/date_range.rs
- py-polars/tests/unit/functions/range/test_datetime_range.py
closes #19931
~~🤔 or maybe it should produce an empty range~~ `interval='0ns'` raises that the interval must be positive, so I think it's right to raise
> fix: Raise proper error message when too small interval is passed to datetime_range

- crates/polars-io/src/cloud/options.rs
In delta-rs we also parse config keys that are uppercase, this provides more flexibility and allows people to use same storage options for delta-rs and pola-rs.
Additionally instead of raising for non existing config keys, we just filter them out. This would make it easier to keep engine specific keys in the storage options in python, since delta-rs has some of those to handle mounted storage.
- closes https://github.com/pola-rs/polars/issues/19849
> fix(python): Parse uppercase config keys

- crates/polars-core/src/chunked_array/ops/row_encode.rs
- crates/polars-pipe/src/executors/sinks/group_by/generic/eval.rs
- crates/polars-row/src/decode.rs
- crates/polars-row/src/encode.rs
- crates/polars-row/src/row.rs
- crates/polars-row/src/variable.rs
- py-polars/tests/unit/test_row_encoding.py
Before, row encoding and decoding would use the variable row encoding. Now, we use the fact that `0xFF` is always an invalid UTF-8 character. To encode, the string with bytes `b1, ..., bn` becomes `b1 + 2, ..., bn + 2, 0x01`. This way, we can just scan for the `0x01` when we want to know where to end. Nulls are encoded as `0x00`. Everything is bitwise inverted for descending.
This is always a size improvement and in particular saves massively for small strings. For example, encoding "a" went from 33 bytes to 2 bytes.
This is a continuation of #19874.
> perf: Reduce the size of row encoding UTF-8

- crates/polars-plan/src/plans/optimizer/projection_pushdown/joins.rs
- py-polars/tests/unit/operations/test_join.py
Fixes #19822 
Previously only the first column was added to the local projections while all of the columns in the sub expression should be added.
> fix: Fix lazy frame join expression

- crates/polars-core/src/chunked_array/temporal/conversion.rs
- crates/polars-core/src/chunked_array/temporal/datetime.rs
- crates/polars-time/src/series/mod.rs
- py-polars/tests/unit/datatypes/test_temporal.py
Closes #19970.
Makes sense to add a simple dtype check for use of `expr.dt.to_string("polars")` with non-Duration dtypes as it is a special-case.
> feat: Catch use of 'polars' in `to_string` for non-Duration dtypes and raise an informative error

- crates/polars-io/src/hive.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- py-polars/tests/unit/io/test_parquet.py
Fixes https://github.com/pola-rs/polars/issues/19968
Panic caused by assuming that hive columns were always in the file in the merge for prefiltering
> fix: Fix panic on schema merge for prefiltering

- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/operations/test_fill_null.py
Fixes #19889 
When used with type inference Decimal columns weren't added to the list of columns to be filled
> fix: Fix Decimal type fill_null

- py-polars/polars/dataframe/frame.py
> fix(python): Fix `row_by_key` typing

- crates/polars-plan/src/plans/aexpr/schema.rs
- py-polars/tests/unit/test_schema.py
Fixes https://github.com/pola-rs/polars/issues/19984
Fixes https://github.com/pola-rs/polars/issues/19990
Elementwise functions should maintain the `agg_list` of the input expr for schema resolution.
> fix: Incorrect `collect_schema()` for `fill_null()` after an aggregation expression in group-by context

- crates/polars-ops/src/chunked_array/strings/starts_with.rs
- py-polars/tests/unit/operations/namespaces/string/test_string.py
Fixes #20003 
If the prefix is shorter than 4 bytes then the slicing should be bounded.
> fix: Fix starts_with out of bounds

- crates/polars-ops/src/chunked_array/hist.rs
- py-polars/tests/unit/operations/test_hist.py
closes #19998 
I think the regression may have been introduced in #18761
> fix: Regression in `hist` panicking on out of bounds index

- crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
- py-polars/tests/unit/io/test_parquet.py
> fix: Reading nullable sliced / masked Categoricals from Parquet

- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/functions.rs
- py-polars/tests/unit/operations/test_filter.py
- py-polars/tests/unit/operations/test_hist.py
> perf: Expand more filters

- py-polars/polars/__init__.py
> fix: Less intrusive forking warnings

- crates/polars-core/src/series/mod.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-plan/src/plans/builder_dsl.rs
- crates/polars-python/src/lazyframe/general.rs
- py-polars/docs/source/reference/dataframe/modify_select.rst
- py-polars/docs/source/reference/lazyframe/modify_select.rst
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/operations/test_drop.py
API consistency: we already have `drop_nans` exposed on both `Series` and `Expr`, but were missing it at the frame-level. 
This is a useful one as there are many vectors by which we might be exposed to NaN values, especially when consuming the results of upstream numerical computation, so it's beneficial to provide a first-class method (while the first thought for NaN may be Pandas, in quant finance it's equally likely to be compute).
Slightly optimised over `drop_nulls` as it only has to consider floating point cols.
```python
{
"a": [1.0, float("nan"), 3.0, 4.0],
"b": ["hello", "foo", "world", "bar"],
"c": [-90.5, 25.0, 0.0, float("nan")],
},
schema_overrides={"a": pl.Float32, "c": pl.Float64},
)
```
**Default:**
* …
> feat: Add `drop_nans` method to DataFrame and LazyFrame

- crates/polars-ops/src/chunked_array/hist.rs
- py-polars/tests/unit/operations/test_hist.py
Closes #20030.
I added a skip condition to the `test_hist_rand` to address "flaky failure" in the same-value case, since including it would increase the complexity of the test. It's easier to just include the separate test.
New behavior uses a unit interval, as it does in the single-value case:
```pycon
>>> pl.Series([1, 1]).hist(bin_count=2)
shape: (2, 3)
┌────────────┬────────────┬───────┐
│ breakpoint ┆ category   ┆ count │
│ ---        ┆ ---        ┆ ---   │
│ f64        ┆ cat        ┆ u32   │
╞════════════╪════════════╪═══════╡
│ 1.0        ┆ (0.5, 1.0] ┆ 2     │
│ 1.5        ┆ (1.0, 1.5] ┆ 0     │
└────────────┴────────────┴───────┘
```
I think this could use a further improvement and should probably only have a single bin, but that can be a different discussion.
> fix: Improve binning in `Series.hist` with `bin_count` when all values are the same

- crates/polars-core/src/frame/column/mod.rs
- py-polars/tests/unit/test_schema.py
> fix: Fix empty scalar agg type

- crates/polars-row/src/decode.rs
- crates/polars-row/src/encode.rs
- crates/polars-row/src/fixed/decimal.rs
- crates/polars-row/src/fixed/mod.rs
- crates/polars-row/src/fixed/packed_u32.rs
- crates/polars-row/src/utils.rs
- py-polars/tests/unit/test_row_encoding.py
Adds a specialized fixed size row encoding for Decimals
> feat: Add optimized row encoding for Decimals

- crates/polars-plan/src/plans/optimizer/projection_pushdown/projection.rs
- py-polars/tests/unit/test_scalar.py
> fix: Fix invalid len due to projection pushdown selection of scalar

- py-polars/polars/datatypes/classes.py
- py-polars/tests/unit/datatypes/test_enum.py
Extends #19926.
* Seamless init from all types of string-valued Python Enums. This means that the caller's Enum definition doesn't _have_ to be explicitly declared as `SomeEnum(str, Enum)` _(py < 3.11)_ or `SomeEnum(StrEnum)` _(py >=3.11)_, as long as the referenced values are strings.
* More specific error message on attempt to initialise from unsupported Python enum types (eg: `Flag`, `IntEnum`, etc...)
```python
import enum
class PolarsURL(enum.Enum):
HOMEPAGE = "https://pola.rs"
BLOG = "https://pola.rs/posts/"
USER_GUIDE = "https://docs.pola.rs/"
PYTHON_API = "https://docs.pola.rs/py-polars/html/reference/"
RUST_API = "https://docs.rs/polars/latest/polars/"
SERVICES = "https://pola.rs/our-services/"
```
**Before:**
```python
pl.Enum(PolarsURL)
```
**After:** …
> feat(python): Improve Polars `Enum` dtype init from standard Python enums

- crates/polars-ops/src/chunked_array/hist.rs
- py-polars/tests/unit/operations/test_hist.py
Improves binning accuracy around breakpoints. Also seems to be 20-30% faster. 
```python
pl.Series([1, 2, 3, 4]).hist(bin_count=3)
```
> fix: Improve `hist` binning around breakpoints

- py-polars/polars/convert/general.py
- py-polars/polars/datatypes/classes.py
- py-polars/tests/unit/datatypes/test_enum.py
Improves an error message that could be raised when initialising Polars `Enum` from an unsuitable Python Enum type; instead of using the generic enum class name we now reference the specific enum, eg:
**Also**: minor tweak to `pl.from_repr` Series regex (4 -> 2).
(apparently some IDE configurations can collapse the usual leading four spaces to two).
```python
import enum
class Color(enum.IntEnum):
RED = enum.auto()
GREEN = enum.auto()
BLUE = enum.auto()
dtype = pl.Enum(Color)
```
**Before**: ```TypeError: Enum categories must be strings; Python `enum.IntEnum` values are integers```
**After**: ```TypeError: Enum categories must be strings; `Color` values are integers```
> feat(python): Improved error message on invalid Python `Enum` init

- py-polars/docs/source/reference/config.rst
- py-polars/polars/api.py
- py-polars/polars/config.py
- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/test_config.py
At the moment we set the options on `Config` init (or via the associated staticmethods); when used as a context manger or function decorator this means we need to explicitly supply all the options on _each_ usage - we cannot currently **reuse** an instance because scope-exit resets the options to the state they were in at scope entry, and having the same object enter a new scope will not set the options again (as the options are set at init).
* This PR enables _reusable_ `Config` instances. A new init parameter "apply_on_context_enter" is introduced which defers applying the indicated options until context/function scope is entered.
* Because the options are now stored and set on scope entry, bundles of `Config` options can now be created/managed centrally and then cleanly reused …
> feat(python): Enable creation of independently reusable `Config` instances

- crates/polars-core/src/chunked_array/temporal/datetime.rs
- py-polars/tests/unit/datatypes/test_temporal.py
Fixes #19309
See also my comment https://github.com/pola-rs/polars/issues/19309#issuecomment-2495681651
Error was introduced with  #14026 
Pre-epoch timestamps are negative, if we trunc div instead of floor div here, we get an incorrect distance to epoch.
> fix(rust): Fix datetime cast behavior for pre-epoch times

- crates/polars-arrow/src/array/binary/mod.rs
- crates/polars-arrow/src/array/binary/mutable.rs
- crates/polars-arrow/src/array/boolean/mod.rs
- crates/polars-arrow/src/array/boolean/mutable.rs
- crates/polars-arrow/src/array/fixed_size_binary/mod.rs
- crates/polars-arrow/src/array/fixed_size_binary/mutable.rs
- crates/polars-arrow/src/array/fixed_size_list/mod.rs
- crates/polars-arrow/src/array/list/mod.rs
- crates/polars-arrow/src/array/map/mod.rs
- crates/polars-arrow/src/array/primitive/mod.rs
- crates/polars-arrow/src/array/struct_/mod.rs
- crates/polars-arrow/src/array/utf8/mod.rs
- crates/polars-arrow/src/array/utf8/mutable.rs
- crates/polars-core/src/chunked_array/ops/chunkops.rs
- crates/polars-core/src/series/arithmetic/fixed_size_list.rs
- crates/polars-core/src/series/arithmetic/list.rs
- crates/polars-expr/src/expressions/apply.rs
- crates/polars-io/src/file_cache/cache_lock.rs
- crates/polars-io/src/file_cache/entry.rs
- crates/polars-io/src/file_cache/file_lock.rs
- crates/polars-ops/src/chunked_array/list/namespace.rs
- crates/polars-ops/src/series/ops/concat_arr.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
- crates/polars-python/src/exceptions.rs
- crates/polars-time/Cargo.toml
- rust-toolchain.toml
Two new lints that affect us:
- Unnecessary `map_or`: https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_map_or
- Unstable name collisions: https://github.com/rust-lang/rust/issues/48919
And an update to the config flag checks in external macros: https://github.com/rust-lang/rust/pull/132577
> build: Bump Rust toolchain to `nightly-2024-11-28`

- crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs
- crates/polars-mem-engine/src/executors/projection.rs
- crates/polars-mem-engine/src/executors/stack.rs
- crates/polars-mem-engine/src/planner/lp.rs
- crates/polars-plan/src/plans/aexpr/mod.rs
- crates/polars-plan/src/plans/aexpr/traverse.rs
- crates/polars-plan/src/plans/aexpr/utils.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/join.rs
- crates/polars-plan/src/plans/lit.rs
- crates/polars-plan/src/plans/optimizer/cache_states.rs
- crates/polars-plan/src/plans/optimizer/cse/cse_expr.rs
- crates/polars-plan/src/plans/optimizer/mod.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/group_by.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/utils.rs
- crates/polars-plan/src/plans/optimizer/slice_pushdown_expr.rs
- crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
- crates/polars-plan/src/plans/options.rs
- crates/polars-plan/src/utils.rs
- crates/polars-stream/src/physical_plan/lower_expr.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-stream/src/skeleton.rs
- py-polars/tests/unit/operations/test_is_in.py
- py-polars/tests/unit/streaming/test_streaming.py
- py-polars/tests/unit/test_predicates.py
Fixes https://github.com/pola-rs/polars/issues/15767
This PR also does some refactoring to consolidate and improve the way we identify expressions as elementwise.
A lot of places where we currently use the `streamable` terminology actually needed to use an even stricter `elementwise` requirement (e.g. filter / slice pushdown. `streamable` expressions include all elementwise expressions and more. For example, `filter()` / `explode()` expressions are streamable, but they are not elementwise.
Where this matters is if the result of a streamable expression needs to be projected next to other result columns, which is almost always the case. The existing in-memory engine and evaluators cannot do this properly as it projects the result columns independently within every chunk, which could lead to …
> fix: Allow nested `is_in()` in `when()/then()` for full-streaming

- py-polars/polars/series/series.py
- py-polars/tests/unit/operations/arithmetic/test_arithmetic.py
> fix: Preserve Series name in __rpow__ operation

- Cargo.lock
- Cargo.toml
Just running `cargo update` and manually bumping `ndarray` to 0.16 to make things compile.
> build: Update some Rust dependencies

- Cargo.lock
- docs/source/src/rust/Cargo.toml
These can be bumped now as the reason these were pinned has been resolved.
> chore(rust): Update AWS doc dependencies

- crates/polars-arrow/src/array/utf8/mod.rs
- crates/polars-arrow/src/offset.rs
> docs(rust): Fix inconsistency between code and comment

- crates/polars-core/src/frame/mod.rs
- py-polars/tests/unit/operations/test_slice.py
Closes #20079
```pycon
>>> pl.LazyFrame({"a": [None, 1.2]}).sort("a", nulls_last=True).slice(0, 10).collect()
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ f64  │
╞══════╡
│ 1.2  │
│ null │
└──────┘
```
> fix: Only slice after sort when slice is smaller than frame length

- crates/polars-arrow/src/legacy/kernels/rolling/nulls/mod.rs
- crates/polars-arrow/src/legacy/kernels/rolling/nulls/variance.rs
- py-polars/tests/unit/operations/rolling/test_rolling.py
> fix: Return null instead of 0. for rolling_std when window contains a single element and ddof=1 and there are nulls elsewhere in the Series

- Cargo.lock
- Cargo.toml
Changelog here, no big changes it seems:
https://github.com/apache/arrow-rs/blob/main/object_store/CHANGELOG-old.md
> build: Bump `object_store` to version `0.11`

- crates/polars-core/src/utils/supertype.rs
Based on this comment: https://github.com/pola-rs/polars/pull/20075#discussion_r1865621996
> fix: Materialize smallest dyn ints to use feature gate for i8/i16

- py-polars/polars/dataframe/frame.py
- py-polars/pyproject.toml
In next deltalake 0.22.3 release the view types will be fully supported. 
Only merge once 0.22.3 is released
cc @ritchie46
> feat(python): Enable view arrow export in `write_delta`

- crates/polars-compute/src/cast/binary_to.rs
When trying to deserialize an arrow IPC stream with a fixed-size binary array that contains no values, the code currently subtracts with underflow. In the Python package (which uses a release build), this is silently ignored as debug assertions are turned off. Instead, you get a panic about an out-of-bounds offset.
```PanicException: assertion failed: self.check_bound(offset)```
By checking for an underflow, everything works fine.
To reproduce the issue, you can try the following code:
```rust
// [dependencies]
// arrow = "53.3.0"
// polars = { version = "1.16.0", features = ["polars-io", "ipc", "ipc_streaming"] }
use std::sync::Arc;
use arrow::{datatypes::{DataType, Field, Schema}, record_batch::RecordBatch};
use polars::io::{SerReader, ipc::IpcStreamReader};
fn main() {
let mut buffer = …
```
> fix: Subtraction with underflow on empty FixedSizeBinaryArray

- crates/polars-core/src/frame/column/mod.rs
- crates/polars-expr/src/expressions/slice.rs
- py-polars/tests/unit/operations/aggregation/test_aggregations.py
Returned previously filtered values instead of NULL.
Fixes https://github.com/pola-rs/polars/issues/20115
> fix: Incorrect aggregation of empty groups after slice

- crates/polars-core/src/frame/group_by/mod.rs
- crates/polars-mem-engine/src/executors/group_by.rs
- py-polars/tests/unit/operations/test_group_by.py
> fix: Handle slice pushdown in PythonUDF GroupBy

- Cargo.lock
- docs/source/src/rust/Cargo.toml
- docs/source/src/rust/user-guide/concepts/lazy-vs-eager.rs
- docs/source/src/rust/user-guide/expressions/operations.rs
- docs/source/src/rust/user-guide/expressions/window.rs
- docs/source/src/rust/user-guide/getting-started.rs
- docs/source/src/rust/user-guide/io/csv.rs
- docs/source/src/rust/user-guide/io/json.rs
- docs/source/src/rust/user-guide/io/parquet.rs
- docs/source/src/rust/user-guide/transformations/joins.rs
Adds required features and fixes a few broken examples in the user guide.
> docs: Fix Rust examples in user guide

- py-polars/tests/unit/datatypes/test_datatype.py
Spotted while poking around.
Did a quick check on main for any other instances of `assert {self} == {self}` and there were none.
> test(python): Fix typo in assertion in datatype copy test

- crates/polars-io/src/cloud/adaptors.rs
- crates/polars-io/src/cloud/options.rs
- crates/polars-io/src/path_utils/mod.rs
- crates/polars-io/src/pl_async.rs
- crates/polars-io/src/utils/file.rs
- crates/polars-io/src/utils/mod.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-pipe/src/executors/sinks/output/csv.rs
- crates/polars-pipe/src/executors/sinks/output/ipc.rs
- crates/polars-pipe/src/executors/sinks/output/json.rs
- crates/polars-pipe/src/executors/sinks/output/parquet.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/plans/options.rs
- crates/polars-python/src/dataframe/io.rs
- crates/polars-python/src/file.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars-utils/src/io.rs
- crates/polars-utils/src/mmap.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/io/cloud/_utils.py
- py-polars/polars/io/cloud/credential_provider.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/io/test_write.py
- py-polars/tests/unit/streaming/test_streaming_io.py
Adds support for directly writing to cloud paths for Parquet, CSV and IPC.
Fixes https://github.com/pola-rs/polars/issues/14630
Fixes https://github.com/pola-rs/polars/issues/19749
> feat: Experimental cloud write support

- crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
> perf: Don't instantiate validity mask when unneeded in Parquet

- crates/polars-ops/src/chunked_array/hist.rs
- py-polars/tests/unit/operations/test_hist.py
Sometimes, index out of bounds happened in uniform_hist_count in cases when due to floating point representation imprecision idx value went over the maximum index (num_bins - 1). Example error message:
```
thread 'polars-4' panicked at crates/polars-ops/src/chunked_array/hist.rs:112:22:
index out of bounds: the len is 5 but the index is 5
```
To work around the issue, add an explicit check that forces value into expected number of intervals. I am not entirely sure this is mathematically correct solution, but it seems to work well.
I added a test that fails on current main branch on my machine just in case, but I know for sure it does not fail with error in other environments (like google colab, for example) .
> fix(rust): Fix index out of bounds in uniform_hist_count

- py-polars/polars/dataframe/frame.py
We have to push some changes in delta-rs that fixes some regressions first in 0.22.3, unfortunately we couldn't add the delta-kernel-rs update in there yet that would add the final bits and pieces for the view types inference.
I changed it to 0.23.0 so we have some leeway here for delta-rs to some more bugfix releases. I'll include the bumped delta-kernel-rs in the 0.23 release
> chore(python): Set delta version check higher

- py-polars/polars/datatypes/constructor.py
Can still detect/use the fast-path binary constructor rather than the generic object constructor even when the dtype was not explicitly set (as `pl.Binary`). 
Not a bad return on a one-line update ;)
```python
from codetiming import Timer
binary_data = [str(n).encode("utf8") for n in range(50_000_000)]
with Timer():
s = pl.Series(binary_data)
```
**Timings**  
```
Before: 5.6219 secs  (new_object)
After: 0.5609 secs  (new_binary) 🚀
```
> perf(python): Construct `Series` for bytes/binary data 10x faster when dtype not explicitly set

- crates/polars-mem-engine/src/executors/scan/ipc.rs
- crates/polars-plan/src/plans/ir/scan_sources.rs
- crates/polars-plan/src/plans/optimizer/count_star.rs
- crates/polars-python/src/conversion/mod.rs
- crates/polars-python/src/dataframe/io.rs
- crates/polars-python/src/file.rs
- crates/polars-utils/src/mmap.rs
Do this by making the backing memory an `Arc`ed trait object
> perf: Reduce memory copy when scanning from Python objects

- crates/polars-arrow/src/array/dictionary/mod.rs
- crates/polars-arrow/src/bitmap/bitmask.rs
- crates/polars-compute/src/unique/boolean.rs
- crates/polars-compute/src/unique/dictionary.rs
- crates/polars-compute/src/unique/mod.rs
- crates/polars-compute/src/unique/primitive.rs
- crates/polars-core/src/chunked_array/logical/categorical/ops/unique.rs
- crates/polars-core/src/chunked_array/ops/unique/mod.rs
I was improving the kernel in preparation for some Parquet work and I wanted to apply it somewhere before I got to the actual Parquet work.
This does lead to significant speedups (~11x in the following benchmark).
> perf: Utilize the RangedUniqueKernel for Enum/Categorical

- crates/polars-row/src/encode.rs
- py-polars/tests/unit/test_row_encoding.py
> fix: Deal with masked out list elements

- py-polars/polars/expr/list.py
- py-polars/polars/series/list.py
- py-polars/tests/unit/datatypes/test_struct.py
- py-polars/tests/unit/operations/namespaces/list/test_list.py
- py-polars/tests/unit/test_errors.py
- py-polars/tests/unit/test_projections.py
ref
* https://github.com/pola-rs/polars/issues/20137
We need to wait until 2.0 to fix the API for this, for now we can add a warning
> feat(python): Issue warning when using `to_struct()` without a list of field names

- crates/Makefile
- crates/polars-lazy/Cargo.toml
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-mem-engine/src/planner/lp.rs
- crates/polars-pipe/src/executors/sinks/output/ipc.rs
- crates/polars-pipe/src/executors/sinks/output/parquet.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/client/check.rs
- crates/polars-plan/src/plans/ir/dot.rs
- crates/polars-plan/src/plans/ir/format.rs
- crates/polars-plan/src/plans/ir/schema.rs
- crates/polars-plan/src/plans/ir/tree_format.rs
- crates/polars-plan/src/plans/options.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- crates/polars/Cargo.toml
`sink_parquet/sink_ipc` can now be used directly for cloud paths
> refactor(rust!): Remove dedicated `sink_(parquet/ipc)_cloud` functions

- py-polars/polars/datatypes/constructor.py
- py-polars/tests/unit/constructors/test_constructors.py
Took another look at Series construction following #20157, and found some additional large speedups (though in a more niche context).
Data composed of types that inherit from the standard builtin types (int, float, str, bytes) currently use the generic `new_object` constructor; however, it is actually still valid to use the specialised/fast-path constructors in this case. This PR makes a minor update to `py_type_to_constructor` to detect this and assign the faster constructors.
```python
import codecs
class BinaryReprInt(int):
def __new__(cls, value):
return super().__new__(cls, value)
def __repr__(self) -> str:
v = f"{abs(int(self)):>08b}"
return f"-{v}" if self < 0 else v
__str__ = __repr__
bn = BinaryReprInt(12345)
print(bn)
bn == 12345
```
```python
int_data = …
```
> perf(python): Much faster `Series` construction from subclasses of standard Python types

- crates/polars-plan/src/plans/aexpr/mod.rs
`StringFunction::Strptime` is only available with `feature = "temporal"`.
> fix(rust): Add temporal feature gate in `is_elementwise_top_level`

- py-polars/polars/_utils/construction/series.py
- py-polars/tests/unit/series/test_series.py
> fix(python): Series construct with large nested `u64`

- crates/polars-time/src/chunkedarray/string/infer.rs
- py-polars/tests/unit/operations/namespaces/test_strptime.py
To accommodate the default datetime format used by Excel in certain regional settings (e.g., China), as discussed in #16092 
closes #16092
The format mentioned in the original issue is actually H:m, with seconds omitted. However, since the seconds component is already optional in the current pattern, adding support for single-digit seconds shouldn't cause any issues.
> feat: Allow for `to_datetime` / `strftime` to automatically parse dates with single-digit hour/minute/second

- crates/polars-arrow/src/bitmap/bitmask.rs
- crates/polars-arrow/src/bitmap/mutable.rs
- crates/polars-io/src/parquet/write/writer.rs
- crates/polars-parquet/src/arrow/read/deserialize/boolean.rs
- crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/mod.rs
This is not really ready yet unless we have compatibility profiles.
Fixes #18819.
> fix: Don't use RLE encoding for Parquet Boolean

- crates/polars-parquet/src/arrow/read/deserialize/binview.rs
- py-polars/tests/unit/io/test_parquet.py
> fix: Only validate UTF-8 for selected items when all below len 128

- crates/polars-core/src/chunked_array/ops/row_encode.rs
- crates/polars-core/src/chunked_array/ops/sort/arg_sort.rs
- crates/polars-core/src/chunked_array/ops/sort/mod.rs
- crates/polars-core/src/series/implementations/array.rs
- crates/polars-core/src/series/implementations/list.rs
- py-polars/tests/unit/datatypes/test_array.py
- py-polars/tests/unit/datatypes/test_list.py
> feat: Allow sorting of lists and arrays

- py-polars/polars/_utils/construction/series.py
- py-polars/polars/datatypes/classes.py
- py-polars/polars/functions/lit.py
- py-polars/tests/unit/datatypes/test_enum.py
- py-polars/tests/unit/functions/test_lit.py
Improved detection and loading of Python Enum values from _all_ flavours of Python Enum base class. Lots of new Enum-related unit tests to extend coverage for this.
Ingest/inference for Python string-valued Enums:
```python
import enum
for EnumBase in (
(enum.Enum,),
(enum.StrEnum,),
(str, enum.Enum),
):
class Portfolio(*EnumBase):  # type: ignore[misc]
TECH = "Technology"
RETAIL = "Retail"
OTHER = "Other"
"trade_id": [123, 456], 
"portfolio": [Portfolio.OTHER, Portfolio.TECH],
})
df.schema["portfolio"]
```
We don't support Python integer-valued Enums _as_ Polars Enums, but we do expect to be able to load them by value:
```python
for EnumBase in (
(enum.Enum,),
(enum.Flag,),
(enum.IntEnum,),
(enum.IntFlag,),
(int, enum.Enum),
):
class …
```
> feat(python): Improve dtype inference and load for `DataFrame` cols constructed from Python Enums

- crates/polars-io/src/csv/read/read_impl.rs
- crates/polars-io/src/csv/read/splitfields.rs
> fix: Csv stop simd cache if eol char is hit

- crates/polars-io/src/cloud/adaptors.rs
- crates/polars-io/src/cloud/glob.rs
- crates/polars-io/src/cloud/object_store_setup.rs
- crates/polars-io/src/cloud/options.rs
- crates/polars-io/src/cloud/polars_object_store.rs
- crates/polars-io/src/file_cache/utils.rs
- crates/polars-io/src/ipc/ipc_reader_async.rs
- crates/polars-io/src/parquet/read/async_impl.rs
- crates/polars-io/src/path_utils/hugging_face.rs
- crates/polars-io/src/path_utils/mod.rs
- crates/polars-io/src/utils/byte_source.rs
- py-polars/tests/unit/io/cloud/test_cloud.py
ref https://github.com/pola-rs/polars/issues/19933
> feat: Retry with reloaded credentials on cloud error

- crates/polars-core/src/frame/mod.rs
- crates/polars-io/src/parquet/read/read_impl.rs
- crates/polars-plan/src/plans/file_scan.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
- crates/polars-schema/src/schema.rs
- crates/polars-stream/src/nodes/io_sources/parquet/row_group_decode.rs
- crates/polars-stream/src/physical_plan/lower_expr.rs
- py-polars/tests/unit/io/test_hive.py
- py-polars/tests/unit/io/test_parquet.py
> fix: Properly project unordered column in parquet prefiltered

- crates/polars-row/src/row.rs
> fix: Allow row encoding for 32-bit architectures (e.g. WASM)

- crates/polars-compute/src/var_cov.rs
- crates/polars-lazy/src/tests/arity.rs
- crates/polars-ops/src/chunked_array/cov.rs
- crates/polars-plan/src/dsl/function_expr/correlation.rs
- crates/polars-plan/src/dsl/function_expr/mod.rs
- crates/polars-plan/src/dsl/functions/correlation.rs
- crates/polars-python/src/functions/lazy.rs
- py-polars/polars/functions/lazy.py
- py-polars/tests/unit/lazyframe/test_lazyframe.py
- py-polars/tests/unit/operations/test_statistics.py
Fix https://github.com/pola-rs/polars/issues/19420
> refactor: Deprecate ddof parameter for correlation coefficient

- crates/polars-core/src/chunked_array/ops/sort/arg_sort.rs
- crates/polars-core/src/chunked_array/ops/sort/categorical.rs
- crates/polars-core/src/chunked_array/ops/sort/mod.rs
- crates/polars-core/src/frame/mod.rs
- py-polars/tests/unit/operations/test_sort.py
- py-polars/tests/unit/operations/test_top_k.py
Add fast paths for series.arg_sort and dataframe.sort(single column) in the following cases -
1) Key column has no nulls and is sorted in the required order 
2) Key column has no nulls and is sorted in the opposite order 
3) Key column has nulls ,is sorted in the required order and has nulls in the correct place
For the second case, if maintain_order is false, technically we can simply return the reverse of 0..len. However current behavior is that we still do a stable sort on it, maintaining order of elements. This is also the expectation in some unrelated test cases. To maintain this behavior, I have implemented a linear algorithm to do a stable reverse sort. This is faster than the current implementation which is also linear for sorting already sorted data, but takes more time due to …
> perf: Add fast paths for series.arg_sort and dataframe.sort

- crates/polars-core/src/chunked_array/builder/list/primitive.rs
- crates/polars-core/src/chunked_array/from.rs
- crates/polars-core/src/chunked_array/logical/categorical/ops/append.rs
- crates/polars-core/src/chunked_array/logical/enum_/mod.rs
- crates/polars-core/src/chunked_array/logical/time.rs
- crates/polars-core/src/chunked_array/mod.rs
- crates/polars-core/src/chunked_array/object/builder.rs
- crates/polars-core/src/chunked_array/ops/chunkops.rs
- crates/polars-core/src/chunked_array/ops/mod.rs
- crates/polars-core/src/chunked_array/ops/rolling_window.rs
- crates/polars-core/src/chunked_array/ops/zip.rs
- crates/polars-core/src/datatypes/mod.rs
- crates/polars-core/src/series/implementations/decimal.rs
- crates/polars-core/src/series/mod.rs
- crates/polars-core/src/series/ops/null.rs
- crates/polars-ops/src/chunked_array/scatter.rs
- crates/polars-ops/src/series/ops/is_in.rs
- crates/polars-plan/src/dsl/function_expr/range/utils.rs
- crates/polars-python/src/functions/mod.rs
- crates/polars-python/src/functions/utils.rs
- py-polars/polars/_utils/construction/series.py
- py-polars/polars/series/utils.py
- py-polars/src/lib.rs
> fix: Don't trigger length check in array construction

- crates/polars-plan/src/plans/optimizer/predicate_pushdown/utils.rs
- crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
- py-polars/tests/unit/operations/test_slice.py
Fixes https://github.com/pola-rs/polars/issues/20216
> fix: Fix assertion panic on LazyFrame `scratch.is_empty()`

- crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/utils.rs
- crates/polars-plan/src/plans/optimizer/slice_pushdown_expr.rs
- crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
- py-polars/tests/unit/operations/test_slice.py
Always `clear()` instead
* Also adds a change to skip checking projections when there is no slice for `with_columns()`
> refactor: Remove debug asserts on scratch space

- crates/polars-plan/src/plans/optimizer/projection_pushdown/projection.rs
- py-polars/tests/unit/test_scalar.py
Fixes https://github.com/pola-rs/polars/issues/20220
> fix: Fix incorrect lazy `select(len())` with some select orderings

- crates/polars-plan/src/plans/visitor/expr.rs
Needed for Polars-cloud engine
> feat: Expose AexprArena

- crates/polars-core/src/chunked_array/logical/categorical/ops/unique.rs
- py-polars/tests/unit/operations/unique/test_unique.py
> fix: Properly account for updated Categorical in .unique() kernel

- crates/polars-python/src/dataframe/io.rs
- crates/polars-python/src/dataframe/serde.rs
- crates/polars-python/src/file.rs
- py-polars/tests/unit/io/test_scan.py
Ensure that the LazyFrame is not affected by BytesIO being overwritten.
Also some refactor to reduce code duplication
> test(python): Add test for BytesIO overwritten after scan

- crates/polars-plan/src/dsl/cat.rs
- crates/polars-plan/src/dsl/function_expr/cat.rs
- crates/polars-python/src/expr/categorical.rs
- crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
- py-polars/docs/source/reference/expressions/categories.rst
- py-polars/docs/source/reference/series/categories.rst
- py-polars/polars/expr/categorical.py
- py-polars/polars/series/categorical.py
- py-polars/tests/unit/operations/namespaces/test_categorical.py
This adds a fast path for operations that can be performed on the categories of a categorical series. I've added `len_bytes` and `len_chars` for now. If desired, it would be trivial to add a few others such as `starts_with` and `ends_with`.
```python
with pl.StringCache():
pl.Series(["a", "b"], dtype=pl.Categorical)  # fill some cache
"a": pl.Series(["Café", "345", "Café", "東京", None], dtype=pl.Categorical)
})
pl.col("a").cat.len_bytes().alias("n_bytes"),
pl.col("a").cat.len_chars().alias("n_chars"),
)
```
These require the `strings` feature because they dispatch to `str.len_bytes` and `str.len_chars`.
> feat: Add `cat.len_chars` and `cat.len_bytes`

- crates/polars-plan/src/plans/aexpr/scalar.rs
- crates/polars-sql/src/context.rs
- crates/polars-sql/tests/simple_exprs.rs
- py-polars/tests/unit/sql/test_literals.py
- py-polars/tests/unit/test_scalar.py
Fixes https://github.com/pola-rs/polars/issues/20058
Fixes https://github.com/pola-rs/polars/issues/18404
> fix: Ensure height is maintained in SQL `SELECT 1 FROM`

- crates/polars-core/src/chunked_array/comparison/mod.rs
- py-polars/tests/unit/operations/test_comparison.py
Fixes https://github.com/pola-rs/polars/issues/20165
> fix: Incorrect comparison in some cases with filtered list/array columns

- crates/polars-io/src/utils/file.rs
This should fix https://github.com/pola-rs/polars/issues/20231. I couldn't reproduce the issue so this is just a guess based on the fact that we were apparently able to at least create the file.
> fix: Fix error writing on Windows to locations outside of C drive

- crates/polars-plan/src/plans/expr_ir.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/projection.rs
- py-polars/tests/unit/test_projections.py
Fixes https://github.com/pola-rs/polars/issues/20220
Fixes https://github.com/pola-rs/polars/issues/20221
This would supercede https://github.com/pola-rs/polars/pull/20222, but because it is a bigger rewrite, I want this to be merged after the next patch release.
> fix: Ensure output height does not change on lazy projection pushdown with aggregations

- .github/workflows/release-python.yml
This involves a manual step to downloads build tools and setup a rust environment on ARM Windows. Our existing x86 Windows runner apparently has this done automatically but I'm not sure how, as I couldn't find any explicit steps in the workflow file to do this.
Successful workflow run can be seen here - https://github.com/pola-rs/polars/actions/runs/12272593897/job/34241658384
> build(python): Build wheels for ARM Windows in Python release workflow

- py-polars/polars/schema.py
- py-polars/tests/unit/test_schema.py
Closes #20262.
Simple, but useful...
```python
s = pl.Schema({"x": pl.Int32(), "y": pl.String()})
s.to_frame()
```
> feat(python): Streamline creation of empty frame from `Schema`

- .github/workflows/test-bytecode-parser.yml
- docs/source/user-guide/installation.md
- py-polars/polars/_utils/convert.py
- py-polars/polars/dependencies.py
- py-polars/polars/testing/parametric/strategies/data.py
- py-polars/pyproject.toml
- py-polars/requirements-dev.txt
- py-polars/tests/unit/constructors/test_constructors.py
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/dataframe/test_upsample.py
- py-polars/tests/unit/datatypes/test_temporal.py
- py-polars/tests/unit/expr/test_exprs.py
- py-polars/tests/unit/functions/as_datatype/test_datetime.py
- py-polars/tests/unit/functions/range/test_datetime_range.py
- py-polars/tests/unit/interchange/test_roundtrip.py
- py-polars/tests/unit/io/database/test_read.py
- py-polars/tests/unit/io/database/test_write.py
- py-polars/tests/unit/ml/test_to_jax.py
- py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py
- py-polars/tests/unit/operations/namespaces/temporal/test_round.py
- py-polars/tests/unit/operations/namespaces/test_strptime.py
- py-polars/tests/unit/operations/test_group_by_dynamic.py
- py-polars/tests/unit/series/buffers/test_from_buffers.py
- py-polars/tests/unit/series/test_series.py
- py-polars/tests/unit/utils/test_utils.py
There was still a bunch of logic specific to Python 3.8 in the code base.
> chore(python): Clean up some remnants of Python 3.8 support

- docs/source/src/python/user-guide/io/bigquery.py
This ensures lists are interpreted correctly by BigQuery.
See also: https://github.com/googleapis/python-bigquery/issues/2008#issuecomment-2541921785 where I test this with a sample DataFrame. That issue discusses the possibility of google-cloud-bigquery automatically setting such an option in future.
Fixes #16938
> docs(python): Include parquet options in BigQuery I/O write sample

- crates/polars-core/src/datatypes/dtype.rs
- crates/polars-expr/src/planner.rs
- crates/polars-plan/src/dsl/functions/concat.rs
- crates/polars-plan/src/dsl/functions/correlation.rs
- crates/polars-plan/src/dsl/functions/horizontal.rs
- crates/polars-plan/src/dsl/functions/range.rs
- crates/polars-plan/src/dsl/list.rs
- crates/polars-plan/src/dsl/mod.rs
- crates/polars-plan/src/plans/conversion/type_coercion/functions.rs
- crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
- crates/polars-plan/src/plans/optimizer/fused.rs
- crates/polars-plan/src/plans/optimizer/simplify_expr/mod.rs
- crates/polars-plan/src/plans/options.rs
- crates/polars-python/src/functions/misc.rs
This changes three main things:
1. Refactor `FunctionsOptions::cast_to_supertypes` to `FunctionOptions::cast_options` in preparation for #19894.
2. Immediately prune casts when they are added into the IR through function upcasting
3. Do some conservative cast type-checking in the IR. For instance, if you try to cast from a `Boolean` to a `DateTime`, it is now rejected in the `type_coercion` stage.
> refactor: Add `FunctionCastOptions` and conservative IR-level cast type-checking

- crates/polars-plan/src/dsl/function_expr/temporal.rs
- py-polars/tests/unit/functions/as_datatype/test_datetime.py
Fixes #19696 
In the new code, the returned column is named as "datetime" for consistency. The column name issue of `pl.datetime` is tracked by #18808.
> fix: Ensure pl.datetime returns empty column when input columns are empty

- docs/source/requirements.txt
- docs/source/src/python/user-guide/misc/styling.py
- py-polars/polars/io/spreadsheet/functions.py
- py-polars/pyproject.toml
- py-polars/requirements-dev.txt
- py-polars/tests/docs/test_user_guide.py
This makes our 'regular' test suite pass on Python 3.13. There are some other things popping up in the parametric tests, will look at those another time.
> chore(python): Prepare test suite for Python 3.13 support

- crates/polars-core/src/series/implementations/time.rs
- crates/polars-plan/src/plans/aexpr/schema.rs
- py-polars/tests/unit/operations/arithmetic/test_arithmetic.py
Closes #19720 
Since the documentation specifies the Time dtype as
> The underlying representation of this type is a 64-bit signed integer. The integer indicates the number of nanoseconds since midnight.
we can specify the result of a substraction as a duration with nanosecond time unit.
> feat: Allow substraction of time dtype columns

- crates/polars-io/src/csv/read/parser.rs
- crates/polars-io/src/csv/read/read_impl.rs
- crates/polars-io/src/csv/read/schema_inference.rs
- py-polars/tests/unit/io/test_csv.py
> fix: Ignore quotes in csv comments

- crates/polars-sql/src/functions.rs
- py-polars/docs/source/reference/sql/functions/string.rst
> docs(python): Fix substr function param definition

- crates/polars-core/src/chunked_array/ops/row_encode.rs
- crates/polars-core/src/frame/group_by/into_groups.rs
- crates/polars-core/src/frame/group_by/mod.rs
- crates/polars-expr/src/hash_keys.rs
- crates/polars-ops/src/frame/join/mod.rs
- crates/polars-python/src/dataframe/general.rs
- crates/polars-python/src/series/general.rs
Now we can use `Column` for unordered Row-Encoding and the python interface now calls the standard functions.
> refactor: Use Column in Row Encoding

- crates/polars-core/src/chunked_array/array/mod.rs
- crates/polars-core/src/chunked_array/list/mod.rs
- crates/polars-core/src/chunked_array/struct_/mod.rs
- crates/polars-core/src/series/mod.rs
This fixes the following snippet panicking.
```python
dtype = pl.List(pl.Datetime)
df = pl.Series('a', [[date(1996, 10, 5)]], dtype).to_frame()
print(df)
re = df._row_encode([(False, False, False)])
rt = re._row_decode([('a', dtype)], [(False, False, False)])
print(rt)
```
> fix: Properly handle `from_physical` for List/Array

- crates/polars-parquet/src/arrow/read/deserialize/boolean.rs
- py-polars/tests/unit/io/test_parquet.py
> fix: Boolean optional slice pushdown

- docs/source/user-guide/expressions/missing-data.md
> docs: Improve docs about NaN

- crates/polars-core/src/series/ops/downcast.rs
I know you want to do better typechecking and error messages at the IR level, but meanwhile this is a monotonic and small change to improve the current state of things.
> feat: Improve error message on SchemaError

- py-polars/tests/unit/test_projections.py
Adds a test case from the repro at https://github.com/pola-rs/polars/issues/20337
> test(python): Add test for `select(len())`

- py-polars/pyproject.toml
This fixes installing using the latest version of `uv`, which otherwise
fails with
```
TOML parse error at line 5, column 1
|
5 | [project]
| ^^^^^^^^^
`pyproject.toml` is using the `[project]` table, but the required
`project.version` field is neither set nor present in the
`project.dynamic` list
```
CC: @ritchie46 https://github.com/astral-sh/uv/issues/9989
> build(python): Add `project.dynamic = ["version"]` to pyproject.toml

- py-polars/polars/_utils/various.py
- py-polars/polars/convert/general.py
- py-polars/tests/unit/interop/test_interop.py
Closes #20328.
Handles `inf`, `-inf`, and `nan` values in the repr string.
```python
pl.from_repr(
"""
Series: 'flt' [f64]
[
null
+inf
-inf
inf
0.0
NaN
]
>>> print("stuff")
"""
)
```
> fix(python): Correctly parse special float values in `from_repr`

- crates/polars-ops/src/frame/join/args.rs
- crates/polars-ops/src/frame/join/dispatch_left_right.rs
- py-polars/tests/unit/operations/test_join.py
Fixes #20350
When doing a right join the dataframes were swapped and a left join was done. For this the maintain_order argument also needs to be flipped. Thanks @rodrigogiraoserrao for catching this.
> fix: Flip order on right join

- crates/polars-io/src/file_cache/entry.rs
Adds a flag `POLARS_IGNORE_FILE_CACHE_ALLOCATE_ERROR` to ignore any allocation errors from the `std::fs::File::allocate` call. May help with:
* https://github.com/pola-rs/polars/issues/17946
There is a chance this allocate is incorrectly failing. I've also adjusted the print to include the IO error itself.
> feat: Add env var to ignore file cache allocate error

- crates/polars-stream/src/nodes/joins/equi_join.rs
This ensures the `Drop` happens in parallel and reduces clones which were bottlenecks.
> perf: Explicit transpose in new-streaming equi-join finalize

- crates/polars-stream/src/nodes/joins/equi_join.rs
This was a partial single-threaded bottleneck.
> perf(rust): Drop probe tables in parallel in new-streaming equi-join

- py-polars/polars/convert/normalize.py
A misspelled return value was corrected and the mixture of US and UK spelling (normalize vs. normalise) was unified.
> refactor(python): Correcting misspelled return value and unifying regional spelling

- docs/source/user-guide/gpu-support.md
- docs/source/user-guide/installation.md
- py-polars/polars/lazyframe/frame.py
This PR updates the GPU engine installation instructions to reflect that CUDA 12 packages can now be installed without using the `--extra-index-url=https://pypi.nvidia.com` because the relevant packages are now available via PyPI.
`pip install polars[gpu]` will now work for CUDA 12. For CUDA 11, the extra index will still be required.
> docs(python): Update GPU engine installation instructions to remove `--extra-index-url` from CUDA 12 packages

- crates/polars-io/src/cloud/credential_provider.rs
- py-polars/docs/source/reference/io.rst
- py-polars/polars/__init__.py
- py-polars/polars/io/cloud/__init__.py
- py-polars/polars/io/cloud/_utils.py
- py-polars/polars/io/cloud/credential_provider.py
- py-polars/polars/meta/versions.py
I don't have anything working locally with `DefaultAzureCredential()`, but it apparently works for some authentication setups -
* https://stackoverflow.com/a/75300867
> feat: Add Azure credential provider using `DefaultAzureCredential()`

- .github/workflows/release-python.yml
- .github/workflows/test-pyodide.yml
- Cargo.lock
- crates/polars-arrow/src/array/binview/mod.rs
- crates/polars-arrow/src/array/fixed_size_list/mod.rs
- crates/polars-arrow/src/array/mod.rs
- crates/polars-arrow/src/array/utf8/mod.rs
- crates/polars-arrow/src/compute/take/fixed_size_list.rs
- crates/polars-compute/src/cast/utf8_to.rs
- crates/polars-compute/src/comparisons/dictionary.rs
- crates/polars-compute/src/comparisons/list.rs
- crates/polars-compute/src/comparisons/struct_.rs
- crates/polars-core/src/chunked_array/comparison/mod.rs
- crates/polars-core/src/lib.rs
- crates/polars-core/src/series/ops/reshape.rs
- crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs
- crates/polars-plan/src/dsl/function_expr/pow.rs
- crates/polars-plan/src/plans/conversion/join.rs
- crates/polars-python/src/dataframe/io.rs
- crates/polars-python/src/lazyframe/exitable.rs
- crates/polars-python/src/lazyframe/general.rs
- crates/polars-python/src/lazyframe/mod.rs
- crates/polars-python/src/series/numpy_ufunc.rs
- crates/polars-sql/src/context.rs
- crates/polars-utils/src/sort.rs
- py-polars/Cargo.toml
- py-polars/src/allocator.rs
- py-polars/src/lib.rs
- rust-toolchain.toml
Hi @ritchie46 , it was nice chatting to you recently.
As discussed, here is all the work so far for building a Polars wheel for Pyodide. As an update from when we spoke last: the required changes to LLVM have now hit nightly Rust and the `inventory` crate, so this should work from LLVM 19.1.6 and Rust `nightly-2024-12-19` onwards. In the new CI for this PR, I have fixed the version of Rust nightly, but I believe after the next `stable` Rust release the pin can be dropped.
The PR makes a few changes, summarised below:
1) A couple of modifications have been made to deal with `wasm32`'s native 32bit pointer width and using `mimalloc` under the `emscripten` OS (corresponding to Pyodide).
2) For the `emscripten` OS I setup the thread pool to use a single thread. Use of threads on Emscripten in …
> feat: Polars build for Pyodide

- crates/polars-stream/src/physical_plan/lower_ir.rs
This centralizes a remaining `todo!()` on the slice for negative slices, and fixed a non-streaming predicate bug in one instance (wasn't translated) and a `todo!()` in another case.
> refactor(rust): Dispatch slice/filter lowering properly

- crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs
- crates/polars-mem-engine/src/planner/lp.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/plans/conversion/mod.rs
- crates/polars-plan/src/plans/ir/dot.rs
- crates/polars-plan/src/plans/ir/format.rs
- crates/polars-plan/src/plans/ir/inputs.rs
- crates/polars-plan/src/plans/ir/mod.rs
- crates/polars-plan/src/plans/ir/schema.rs
- crates/polars-plan/src/plans/ir/tree_format.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
- crates/polars-plan/src/plans/visitor/hash.rs
- crates/polars-python/src/lazyframe/visitor/nodes.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
This was intended as a special case for `select` which only returns a single row but physical planners can already inspect the expressions in a `select` to determine whether this is the case regardless.
> refactor(rust): Remove unused IR::Reduce node

- crates/polars-lazy/src/frame/mod.rs
- py-polars/tests/unit/operations/test_join.py
- py-polars/tests/unit/sql/test_joins.py
- py-polars/tests/unit/test_cse.py
The goal is to re-enable this ASAP by translating the cache nodes to multiplexer nodes (or something else), but this fixes a `todo!()` branch for now.
> refactor(rust): Temporarily disable common subplan elim for new-streaming

- py-polars/polars/dataframe/plotting.py
- py-polars/polars/series/plotting.py
- Add missing `f` prefixes for f-strings
- Add missing line in docstring of `DataFrame.plot.line`
- Fix typo in docstring of `Series.plot.line` examples section
Closes #18475
> fix(python): Fix plotting f-strings and docstrings

- crates/polars-core/src/chunked_array/arithmetic/decimal.rs
- crates/polars-core/src/chunked_array/arithmetic/mod.rs
- crates/polars-plan/src/plans/aexpr/schema.rs
- py-polars/tests/unit/datatypes/test_decimal.py
> fix: Fix decimal arithmetic schema

- py-polars/polars/series/series.py
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/datatypes/test_decimal.py
- py-polars/tests/unit/series/test_series.py
> fix(python): Fix decimal series dispatch

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs
- crates/polars-plan/src/frame/opt_state.rs
- crates/polars-plan/src/plans/aexpr/utils.rs
- crates/polars-plan/src/plans/conversion/join.rs
- crates/polars-plan/src/plans/optimizer/collapse_and_project.rs
- crates/polars-plan/src/plans/optimizer/collect_members.rs
- crates/polars-plan/src/plans/optimizer/mod.rs
- crates/polars-plan/src/plans/optimizer/set_order.rs
- crates/polars-plan/src/plans/options.rs
- crates/polars-python/src/lazyframe/general.rs
- py-polars/polars/functions/lazy.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/lazyframe/optimizations.py
- py-polars/tests/unit/operations/test_group_by.py
An operation doesn't have to maintain_order if it isn't observed. E.g. 
`concat().sort()` could do an unordered union for instance. 
`.sort().groupby().sum()` can remove the sort, etc.
> feat: Order observability optimizations

- py-polars/polars/series/datetime.py
The return type of `Series.dt.add_business_days` should be `Series`, not `Expr`
```python
>>> import datetime
>>> type(
pl.Series("date", [datetime.date(2024, 12, 23)]).dt.add_business_days(
1, roll="forward"
)
)
<class 'polars.series.series.Series'>
```
> fix(python): Fix return type of `Series.dt.add_business_days`

- crates/polars/src/lib.rs
There was a missing space in between "for" and "columnar"
> docs(rust): Fix "forcolumnar" typo in docs

- crates/polars-core/src/datatypes/dtype.rs
- crates/polars-core/src/schema.rs
- crates/polars-expr/src/reduce/convert.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/utils.rs
- crates/polars-stream/src/physical_plan/lower_expr.rs
- crates/polars-stream/src/physical_plan/to_graph.rs
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/io/test_parquet.py
- py-polars/tests/unit/operations/test_concat.py
- py-polars/tests/unit/series/test_series.py
- py-polars/tests/unit/test_projections.py
Always ensure dynamic types are materialized in schema as that is what will be produced.
Also fixes #20355
> feat: Always resolve dynamic types in schema

- crates/polars-lazy/src/scan/csv.rs
- py-polars/tests/unit/io/test_csv.py
Fixes https://github.com/pola-rs/polars/issues/19916
> fix: Fix using `new_columns` in `scan_csv` with compressed file

- crates/polars-arrow/Cargo.toml
- crates/polars-arrow/src/compute/mod.rs
- crates/polars-arrow/src/legacy/kernels/mod.rs
- crates/polars-compute/Cargo.toml
- crates/polars-compute/src/cast/mod.rs
- crates/polars-compute/src/gather/binary.rs
- crates/polars-compute/src/gather/binview.rs
- crates/polars-compute/src/gather/bitmap.rs
- crates/polars-compute/src/gather/boolean.rs
- crates/polars-compute/src/gather/fixed_size_list.rs
- crates/polars-compute/src/gather/generic_binary.rs
- crates/polars-compute/src/gather/list.rs
- crates/polars-compute/src/gather/mod.rs
- crates/polars-compute/src/gather/primitive.rs
- crates/polars-compute/src/gather/structure.rs
- crates/polars-compute/src/gather/sublist/fixed_size_list.rs
- crates/polars-compute/src/gather/sublist/list.rs
- crates/polars-compute/src/gather/sublist/mod.rs
- crates/polars-compute/src/lib.rs
- crates/polars-core/Cargo.toml
- crates/polars-core/src/chunked_array/ops/explode_and_offsets.rs
- crates/polars-core/src/chunked_array/ops/gather.rs
- crates/polars-core/src/series/ops/reshape.rs
- crates/polars-expr/src/hash_keys.rs
- crates/polars-ops/src/chunked_array/array/get.rs
- crates/polars-ops/src/chunked_array/list/namespace.rs
Fixes https://github.com/pola-rs/polars/issues/19655
> refactor(rust): Move gather kernels to polars-compute

- crates/polars-io/src/utils/other.rs
When running Polars in Pyodide, using `read_csv()` (and possibly other functions reading from file) causes a crash during `mmap` -- a huge chunk of memory is allocated as the length of the file is incorrectly provided to `mmap` by the file's metadata.
This PR implements a workaround that applies only when running under Emscripten so that the file length is derived by seeking to the end of the file, and setting the `mmap` size explicitly in the options before mapping.
With this, things work under Pyodide again:
Emscripten is currently working on reimplementing the virtual filesystem from scratch ([WasmFS](https://github.com/orgs/emscripten-core/projects/1)). Once that work has been merged and hits Pyodide, it's likely that we can remove this workaround.
cc @ritchie46
> fix: Workaround for `mmap` crash under Emscripten

- crates/polars-python/src/dataframe/general.rs
- crates/polars-python/src/map/dataframe.rs
- crates/polars-python/src/map/mod.rs
- crates/polars-python/src/map/series.rs
- crates/polars-python/src/series/map.rs
- py-polars/tests/unit/expr/test_udfs.py
Always raise the errors instead of silently ignoring them. Also removes a panics.
fixes #19315
fixes #17499
fixes #11823
fixes #12675
And I assume a few other panic related issues.
> fix(python): Properly raise UDF errors

- crates/polars-stream/src/nodes/io_sources/parquet/init.rs
Regression from https://github.com/pola-rs/polars/pull/20203/files#diff-554fb85df2859feb204caf7a9f438fb3fef8adc8affacb4c41ccf094a5e40c0cL278
> refactor(rust): Fix duplicate cols in new-streaming parquet prefilter

- crates/polars-core/src/chunked_array/array/mod.rs
- crates/polars-core/src/chunked_array/list/mod.rs
- crates/polars-core/src/chunked_array/ops/row_encode.rs
- crates/polars-core/src/chunked_array/struct_/mod.rs
- crates/polars-core/src/series/mod.rs
- crates/polars-expr/src/groups/row_encoded.rs
- crates/polars-ops/src/chunked_array/strings/json_path.rs
- crates/polars-pipe/src/executors/sinks/group_by/generic/eval.rs
- crates/polars-pipe/src/executors/sinks/group_by/generic/hash_table.rs
- crates/polars-pipe/src/executors/sinks/joins/generic_build.rs
- crates/polars-pipe/src/executors/sinks/joins/row_values.rs
- crates/polars-pipe/src/executors/sinks/sort/sink_multiple.rs
- crates/polars-python/src/series/general.rs
> fix: Properly handle `to_physical_repr` of nested types

- py-polars/polars/dataframe/frame.py
> docs: Improve docstring clarity

- crates/polars-python/src/map/series.rs
- py-polars/tests/unit/datatypes/test_object.py
> fix(python): Fix nullable object in map_elements

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-plan/src/dsl/expr_dyn_fn.rs
- crates/polars-plan/src/dsl/functions/horizontal.rs
- crates/polars-plan/src/frame/opt_state.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/join.rs
- crates/polars-plan/src/plans/conversion/mod.rs
- crates/polars-plan/src/plans/conversion/stack_opt.rs
- crates/polars-plan/src/plans/conversion/type_check/mod.rs
- crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
- crates/polars-plan/src/plans/expr_ir.rs
- crates/polars-plan/src/plans/optimizer/collapse_and_project.rs
- crates/polars-plan/src/plans/optimizer/count_star.rs
- crates/polars-plan/src/plans/optimizer/delay_rechunk.rs
- crates/polars-plan/src/plans/optimizer/flatten_union.rs
- crates/polars-plan/src/plans/optimizer/mod.rs
- crates/polars-plan/src/plans/optimizer/stack_opt.rs
- crates/polars-python/src/lazyframe/general.rs
- py-polars/polars/functions/lazy.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/test_errors.py
This PR fixes #17391 by properly adding a `TypeCheckRule` to the `ConversionOptimizer` that will verify that `filters` have a `Boolean` datatype.
This already caught #20424.
In the future, this can be expanded to type check additional parts of the IR such as arithmetic operators.
> refactor: Add a `TypeCheckRule` to the optimizer

- crates/polars-ops/src/chunked_array/gather/chunked.rs
Always blindly taking all data buffers of all input chunks leads to exponential behavior in the new join. Now if there is more than one chunk we deduplicate and only take those data buffers we actually reference.
> perf: Don't always take all data buffers when gathering views

- py-polars/polars/series/datetime.py
Return type for `Series.dt.add_business_days`'s type annotation was fixed in https://github.com/pola-rs/polars/pull/20402, but not its docstring. This PR fixes the docstring.
This PR also fixes the return types for `millennium`, `century` and `combine` in the `Series.dt` namespace.
> fix(python): Fix return type for `add_business_days`, `millennium`, `century` and `combine` methods in `Series.dt` namespace

- crates/polars-ops/src/chunked_array/gather/chunked.rs
For left-hand sides with many chunks (most notably in the new-streaming join) the `prepare_series` was very expensive and it's not necessary at all (we just have to match on a couple more logical types).
> perf: Remove prepare_series for gather kernels

- crates/polars-ops/src/chunked_array/gather/chunked.rs
This caused quadratic behavior in the new-streaming join.
> perf: Don't collect all LHS arrays in gather

- crates/polars-ops/src/chunked_array/gather/chunked.rs
@orlp FYI.
Instead of deduping for every view, I do a single dedup pass up front.
> perf: Dedup binviews up front

- crates/polars-core/src/frame/column/mod.rs
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/datatypes/test_categorical.py
- py-polars/tests/unit/operations/namespaces/test_categorical.py
- py-polars/tests/unit/operations/test_interpolate_by.py
- py-polars/tests/unit/operations/test_join.py
- py-polars/tests/unit/operations/test_sort.py
This makes the implementation of `arg_sort` take the fast path in `Column` before ever going into a specific SeriesTrait implementor. This now makes that every type has the same fast path that gets taken when sorted. It also now allows taking the fast path when `maintain_order=True`.
This PR needed to adjust some tests because they wrongly assumed things about the output order of the sorting when `maintain_order=False`.
There are some streaming tests that need to be disabled because of #20440.
> perf: Generalize the `arg_sort` fast path onto `Column`

- crates/polars-plan/src/dsl/function_expr/schema.rs
- py-polars/tests/unit/operations/aggregation/test_horizontal.py
> fix: Return correct schema for `sum_horizontal` with boolean dtype

- crates/polars-ops/src/frame/join/dispatch_left_right.rs
- py-polars/tests/unit/functions/test_functions.py
> fix: Fix `align_frames` with single row panicking

- py-polars/polars/io/spreadsheet/functions.py
- py-polars/tests/unit/io/test_spreadsheet.py
Extends the recent https://github.com/pola-rs/polars/pull/20404 update, allowing loading from multiple worksheets while loading from multiple workbooks, following discussion here: https://github.com/pola-rs/polars/pull/20404#discussion_r1895915463. 
(Currently can load one worksheet from multiple workbooks, or multiple worksheets from one workbook - this enables both options at the same time).
```python
pl.read_excel(
"/path/to/multiple/workbooks/**/data*.xlsx",
sheet_name=["sheet1","sheet2","sheet3"],
)
```
> feat(python): Allow loading data from multiple Excel/ODS workbooks and worksheets

- crates/polars-plan/src/plans/aexpr/mod.rs
- crates/polars-plan/src/plans/conversion/join.rs
Also lossless cast expression that aren't only column references.
> feat: Allow more join lossless casting

- py-polars/polars/io/spreadsheet/functions.py
- py-polars/tests/unit/io/test_spreadsheet.py
Closes #20447.
Adds an "include_file_paths" parameter to the spreadsheet reading functions, with the same signature and behaviour as we have elsewhere (the param takes the column name into which the path will be written, appends it as a new column to the end, and reads from BytesIO sources are tagged with the synthetic path "in-mem").
```python
pl.read_excel("~/data.xlsx", sheet_id="test", include_file_paths="wbook")
```
> feat(python): Add an "include_file_paths" parameter to `read_excel` and `read_ods`

- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/lazyframe/test_lazyframe.py
closes #16357
`floor/ceil` already worked on integers but was untested.
> test: Add tests for `floor/ceil` on integers

- crates/polars-plan/src/dsl/mod.rs
- py-polars/polars/expr/expr.py
> docs: Fix `Expr.all` description of Kleene logic

- crates/polars-stream/src/nodes/io_sources/parquet/init.rs
- crates/polars-stream/src/nodes/io_sources/parquet/mod.rs
- crates/polars-stream/src/nodes/io_sources/parquet/row_group_data_fetch.rs
The same should probably be done for the CSV one as well.
> perf(rust): Add proper distributor to new-streaming parquet reader

- crates/polars-plan/src/plans/optimizer/set_order.rs
- py-polars/tests/unit/operations/unique/test_unique.py
> fix: Don't remove sort if first/last strategy is set in unique

- crates/polars-ops/src/series/ops/floor_divide.rs
- crates/polars-ops/src/series/ops/horizontal.rs
- crates/polars-plan/src/dsl/function_expr/shift_and_fill.rs
- py-polars/tests/unit/datatypes/test_decimal.py
> fix: Decimal from physical in horizontal min/max and shift

- crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs
- crates/polars-lazy/src/tests/optimization_checks.rs
- crates/polars-mem-engine/src/executors/scan/mod.rs
- crates/polars-mem-engine/src/planner/lp.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/conversion/mod.rs
- crates/polars-plan/src/plans/ir/dot.rs
- crates/polars-plan/src/plans/ir/format.rs
- crates/polars-plan/src/plans/ir/inputs.rs
- crates/polars-plan/src/plans/ir/mod.rs
- crates/polars-plan/src/plans/ir/tree_format.rs
- crates/polars-plan/src/plans/optimizer/count_star.rs
- crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
- crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
- crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
- crates/polars-plan/src/plans/visitor/hash.rs
- crates/polars-python/src/lazyframe/visitor/nodes.rs
- crates/polars-stream/src/physical_plan/lower_ir.rs
- py-polars/tests/unit/lazyframe/test_explain.py
- py-polars/tests/unit/operations/unique/test_unique.py
- py-polars/tests/unit/test_predicates.py
Simplifies IR, saves a lowering step in streaming and ensures that the in-memory engine can parallelize if it wants to.
First solution for #20475
> perf: Remove predicate from `IR::DataFrame`

- crates/polars-plan/src/frame/opt_state.rs
- crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
- crates/polars-plan/src/plans/optimizer/mod.rs
> perf: Collapse expanded filters in eager

- py-polars/polars/functions/col.py
- py-polars/polars/selectors.py
- py-polars/tests/unit/test_selectors.py
Consistency/ergonomics; we accept Python types in most places already (eg: `Schema`, `schema_overrides`, etc), but were missing integration in the `cs.by_dtype` selector and `col`. This adds support for both. 
Note: selecting Python types that map to multiple Polars dtypes, such as `int`, `float`, `datetime`, or `timedelta` will select all of the related Polars dtypes (eg: matching on `int` is equivalent to matching on _all_ signed/unsigned Polars integer dtypes).
```python
{
"idx": [],
"dt1": [],
"dt2": [],
},
schema_overrides={
"idx": pl.UInt32,
"dt1": pl.Datetime("ms"),
"dt2": pl.Datetime(time_zone="Asia/Tokyo"),
},
)
```
```python
df.select(cs.by_dtype(datetime))
```
```python …
```
> feat(python): Allow use of Python types in `cs.by_dtype` and `col`

- py-polars/polars/expr/expr.py
This PR adds example documentation for [`bitwise_and`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.bitwise_and.html#), [`bitwise_or`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.bitwise_or.html#), and [`bitwise_xor`](https://docs.pola.rs/api/python/dev/reference/expressions/api/polars.Expr.bitwise_xor.html#) to include `select` usage and aggregation usage with `agg`.
> docs(python): Add examples for bitwise expressions

- crates/polars-core/src/chunked_array/logical/categorical/merge.rs
- py-polars/tests/unit/datatypes/test_categorical.py
After doing merge operation, the physical representation might get the sorted flag set. For lexical ordering we should not be setting this flag at all. Have added a small check which ensures that this flag is not set.
Fixes #19900 .
> fix: Fix incorrectly added sorted flag after append for lexically ordered categorical series
