pola-rs/polars

crates/polars-ops/src/series/ops/horizontal.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
py-polars/tests/unit/operations/aggregation/test_horizontal.py

fix: Ensure `ignore_nulls` is respected in horizontal sum/mean

---

py-polars/polars/expr/expr.py

add `maintain_order=True` to group_by example.

docs: Fix flaky doctests

---

crates/polars-io/src/parquet/read/read_impl.rs
py-polars/tests/unit/io/test_lazy_parquet.py

Fixes #20485 
The `row_count_start` values in the `rg_to_dfs_par_over_rg()` function were not properly reflecting the number of rows that had already been processed when the `slice_pushdown` optimization was being used.

fix(rust): `slice_pushdown` optimization leading to incorrectly sliced row index on parquet file

---

crates/polars-core/src/datatypes/mod.rs
crates/polars-core/src/datatypes/schema.rs
crates/polars-core/src/lib.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
py-polars/tests/unit/operations/test_concat.py

fix: Fix union

---

crates/polars-core/src/chunked_array/logical/categorical/ops/unique.rs
py-polars/tests/unit/operations/unique/test_unique.py

Closes #20528.
I don't think this will interfere with @coastalwhite's upcoming fixes.
Evidence of fix:
```pycon
>>> pl.enable_string_cache()
>>> pl.Series(["aaa", "bbb", "ccc"])  # pre-fill cache
>>> s = pl.Series(["a", "b", "c"], dtype=pl.Categorical)
>>> s_empty = s.slice(0, 0)          # create empty array
>>> s_empty.unique()
shape: (0,)
Series: '' [cat]
[
]
>>> s_empty.cat.get_categories()
shape: (3,)
[
"a"
"b"
"c"
]
```

fix: Add `unique` fast path for empty categoricals

---

py-polars/polars/dataframe/frame.py

docs(python): Fix typo in `DataFrame.cast`

---

crates/polars-core/src/chunked_array/logical/categorical/ops/unique.rs
py-polars/polars/_utils/various.py
py-polars/tests/unit/datatypes/test_categorical.py

fix: Revert categorical unique code

---

.github/workflows/benchmark.yml
crates/polars-core/src/chunked_array/comparison/categorical.rs
crates/polars-core/src/chunked_array/logical/categorical/ops/unique.rs
py-polars/tests/unit/datatypes/test_categorical.py

fix: Fix more global categorical issues

---

py-polars/tests/unit/conftest.py
py-polars/tests/unit/constructors/test_any_value_fallbacks.py
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/datatypes/test_list.py
py-polars/tests/unit/functions/as_datatype/test_concat_list.py
py-polars/tests/unit/interchange/test_from_dataframe.py
py-polars/tests/unit/io/test_delta.py
py-polars/tests/unit/io/test_lazy_parquet.py
py-polars/tests/unit/io/test_other.py
py-polars/tests/unit/io/test_parquet.py
py-polars/tests/unit/operations/namespaces/test_categorical.py
py-polars/tests/unit/operations/test_filter.py
py-polars/tests/unit/operations/test_group_by.py
py-polars/tests/unit/operations/unique/test_unique.py
py-polars/tests/unit/series/test_series.py

This PR adds a fixture (well--moved from a previous PR that only used it in a few specific tests) for use in categorical testing. When used via `@pytest.mark.usefixtures("test_global_and_local")`, it runs the test in both a local and global context. When the global context is used, the global cache is populated by a few strings so that the physical values do not match the local values.
There were a few tests that used `@StringCache()` but had no local testing, so I converted these to use the updated fixture, which tests both. I avoided touching tests that manually tested for local or global conditions.
In the process, I uncovered three tests that failed in a global context, and marked these with a `# TODO: fails with global string cache` and disabled the fixture for these tests. One of …

chore: Increase categorical test coverage

---

crates/polars-stream/src/execute.rs
crates/polars-stream/src/graph.rs
crates/polars-stream/src/physical_plan/fmt.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
crates/polars-stream/src/skeleton.rs

This does not yet allow a node with multiple output schemas, that will come in a follow-up PR.

refactor(rust): Groundwork for allowing multi-output nodes in the new streaming engine

---

crates/polars-plan/src/dsl/cat.rs
crates/polars-plan/src/dsl/function_expr/cat.rs
crates/polars-python/src/expr/categorical.rs
py-polars/docs/source/reference/expressions/categories.rst
py-polars/docs/source/reference/series/categories.rst
py-polars/polars/expr/categorical.py
py-polars/polars/series/categorical.py
py-polars/polars/series/string.py
py-polars/tests/unit/operations/namespaces/test_categorical.py

Follow up to #20211.
**Edit 2024-12-18**: expression implementation has been removed, along with the slow path. `cat.starts_with` and `cat.ends_with` now require `str` inputs and do not except expressions.

feat: Add `cat.starts_with`/`cat.ends_with`

---

crates/polars-time/src/windows/duration.rs
py-polars/tests/unit/operations/rolling/test_rolling.py

closes #20081 
Currently, the error message refers to `window_size`, but that's not correct, because `ensure_duration_matches_dtype` matches on the time/index column dtype
It's a little unfortunate that the name of this variable across operations:
- `upsample`: `time_column`
- `rolling`: `index_column`
- `rolling_*_by`: `by`
but I think referring to "temporal/index column" should be enough to clear up the confusion

fix: Fix variable name in error message for "unsupported data type" in rolling and upsampling operations

---

docs/source/user-guide/concepts/expressions-and-contexts.md

Deprecated since version 0.19.9: This method has been renamed to DataFrame.rolling().

docs: Update "group_by_rolling" (deprecated) to "rolling" in user guide

---

crates/polars-arrow/src/io/ipc/read/schema.rs
crates/polars-core/src/chunked_array/logical/categorical/revmap.rs
crates/polars-expr/src/expressions/apply.rs
crates/polars-expr/src/expressions/column.rs
crates/polars-expr/src/expressions/window.rs
crates/polars-io/src/partition.rs
crates/polars-mem-engine/src/executors/group_by.rs
crates/polars-mem-engine/src/executors/group_by_dynamic.rs
crates/polars-mem-engine/src/executors/group_by_partitioned.rs
crates/polars-mem-engine/src/executors/group_by_rolling.rs
crates/polars-mem-engine/src/executors/projection_utils.rs
crates/polars-mem-engine/src/executors/stack.rs
crates/polars-ops/src/series/ops/duration.rs
crates/polars-parquet/src/parquet/encoding/hybrid_rle/encoder.rs
crates/polars-plan/src/dsl/function_expr/datetime.rs
crates/polars-plan/src/dsl/function_expr/range/datetime_range.rs
crates/polars-plan/src/dsl/function_expr/range/time_range.rs
crates/polars-plan/src/dsl/mod.rs
crates/polars-python/src/lib.rs
crates/polars-python/src/map/dataframe.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-utils/src/index.rs
rust-toolchain.toml

Function symbols were being stripped from release builds on Apple due to a bug in the Rust compiler, this was fixed recently in https://github.com/rust-lang/rust/pull/135034.
Having symbols in the final shipped binary does make it slightly larger, but makes diagnosing performance issues/bugs on released Polars versions significantly easier. Note that this is only the function names for non-inlined functions, it does not keep all the other debug information.

fix(rust): Restore symbols on Apple by bumping nightly version

---

crates/polars-arrow/src/array/binary/mod.rs
crates/polars-arrow/src/array/dictionary/mod.rs
crates/polars-arrow/src/array/mod.rs
crates/polars-arrow/src/array/utf8/mod.rs
crates/polars-compute/src/cast/decimal_to.rs
crates/polars-compute/src/cast/primitive_to.rs
crates/polars-core/src/chunked_array/cast.rs
crates/polars-core/src/chunked_array/ndarray.rs
crates/polars-core/src/chunked_array/ops/apply.rs
crates/polars-io/src/parquet/read/read_impl.rs
crates/polars-lazy/src/frame/mod.rs
crates/polars-plan/src/plans/conversion/join.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
crates/polars-row/src/encode.rs
py-polars/polars/_utils/various.py
py-polars/polars/dataframe/frame.py
py-polars/polars/datatypes/classes.py
py-polars/polars/expr/binary.py
py-polars/polars/expr/string.py
py-polars/polars/series/string.py
py-polars/tests/unit/interchange/test_from_dataframe.py
py-polars/tests/unit/operations/namespaces/string/test_string.py

Fixed a few minor gremlins in Python/Rust docstrings:
* Updated "casted" → "cast" (it's irregular, so the past tense still conjugates as "cast" :)
* Updated "consecutives" → "consecutive" in a few places.
* Some "polars" → "Polars" adjustments for consistency.
* Fixed the output of the "reinterpret" example.

docs: Miscellaneous minor updates/fixes

---

crates/polars-io/src/cloud/options.rs
py-polars/polars/io/cloud/credential_provider.py
py-polars/polars/meta/versions.py

ref https://github.com/pola-rs/polars/issues/20545
This is a bit of guesswork as I don't have a local repro of it - we now pass `tenant_id` to `DefaultAzureCredential.get_token()` if we see it in `storage_options`.
Other drive-bys to help with future debugging:
* The Azure CLI version is now printed under `pl.show_versions()` - this affects the auth flow as one of the things we do is attempting to fetch the storage account key from the Azure CLI
* Add more debug prints when `POLARS_VERBOSE` is enabled

fix(python): Propagate `tenant_id` to `CredentialProviderAzure` if given

---

crates/polars-plan/src/plans/aexpr/properties.rs
crates/polars-plan/src/plans/lit.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
crates/polars-plan/src/utils.rs
py-polars/tests/unit/test_predicates.py

Fixes https://github.com/pola-rs/polars/issues/20489
Replaces all uses of `projects_as_scalar()` with `is_scalar()` to be consistent with the strictness check used by `with_columns()`

fix: Fix error filtering after `with_columns()` on unit height LazyFrame

---

Cargo.lock
Cargo.toml
crates/polars-sql/src/context.rs
crates/polars-sql/src/functions.rs
crates/polars-sql/src/sql_expr.rs
py-polars/tests/unit/sql/test_joins.py

Closes #20546, upgrading `sqlparser-rs` to  version`0.53` and taking advantage of some anti/semi join-parsing updates.
The following SQL queries are now both valid for use with Polars, and are equivalent (the "LEFT" keyword can be implicit, as per other dialects such as DuckDB):
```sql
SELECT * FROM tbl_a LEFT SEMI JOIN tbl_b USING (a,b,c)
SELECT * FROM tbl_a SEMI JOIN tbl_b USING (a,b,c)
```

feat: Update `sqlparser-rs`, enabling "LEFT" keyword to be optional for anti/semi joins in SQL queries

---

crates/polars-arrow/src/array/binview/mod.rs
crates/polars-parquet/src/arrow/read/statistics/binview.rs

fix: Soundness when loading Parquet string statistics

---

crates/polars-arrow/src/array/union/mod.rs
crates/polars-arrow/src/datatypes/mod.rs
crates/polars-arrow/src/ffi/schema.rs
crates/polars-arrow/src/io/avro/read/schema.rs
crates/polars-arrow/src/io/ipc/read/array/union.rs
crates/polars-arrow/src/io/ipc/read/common.rs
crates/polars-arrow/src/io/ipc/read/schema.rs
crates/polars-arrow/src/io/ipc/write/mod.rs
crates/polars-arrow/src/io/ipc/write/schema.rs
crates/polars-core/src/chunked_array/object/extension/drop.rs
crates/polars-core/src/chunked_array/object/extension/mod.rs
crates/polars-core/src/chunked_array/object/extension/polars_extension.rs
crates/polars-core/src/datatypes/field.rs
crates/polars-core/src/series/from.rs
crates/polars-io/src/parquet/read/read_impl.rs
crates/polars-parquet/src/arrow/read/schema/metadata.rs
crates/polars-parquet/src/arrow/write/schema.rs
crates/polars-row/src/decode.rs
crates/polars-row/src/encode.rs
crates/polars/tests/it/arrow/array/fixed_size_binary/mod.rs
crates/polars/tests/it/arrow/array/growable/list.rs
crates/polars/tests/it/arrow/array/growable/mod.rs
crates/polars/tests/it/arrow/array/mod.rs
crates/polars/tests/it/arrow/array/union.rs
py-polars/requirements-dev.txt

This reduces the size of `ArrowDataType` from 64 to 32 bytes.

refactor(rust): Reduce size of ArrowDataType by boxing heavy variants

---

py-polars/polars/dataframe/frame.py

`coalesce=True` has no effect when `how="left"` so it should be demonstrated with `how="full"` instead. I kept an example of `how="left"` (without `coalesce=True`) because it might be usefull too. I don't know Rust but the doc may be adapted there too

docs(python): Update `DataFrame` join examples

---

py-polars/tests/unit/datatypes/test_categorical.py

https://github.com/pola-rs/polars/actions/runs/12650506836/job/35249157771?pr=20590

test(python): Fix flaky categorical test

---

.github/workflows/benchmark-remote.yml
.github/workflows/benchmark.yml
.github/workflows/docs-python.yml
.github/workflows/lint-python.yml
.github/workflows/test-python.yml
docs/source/development/contributing/index.md
py-polars/pyproject.toml
py-polars/requirements-ci.txt
py-polars/tests/unit/ml/test_to_torch.py

Polars was already installable under Python 3.13 and already worked. This PR officially marks Python 3.13 as supported and updates our CI to also run tests under Python 3.13.
There's an issue with running MyPy with the latest NumPy version that came up because of this PR. I made a separate issue for this: https://github.com/pola-rs/polars/issues/20561

build(python): Officially support Python 3.13

---

crates/polars-stream/src/async_executor/task.rs

We were waiting (potentially very long) on a locked mutex when awaiting our own executors tasks, use an atomic waker for the join instead.

perf(rust): Use AtomicWaker in async engine task joiner

---

crates/polars-core/src/chunked_array/cast.rs

This gives a false-positive error, it thinks this is `Ord::max` for some reason.

chore(rust): Fix rust-analyzer misinterpretation

---

crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
py-polars/tests/unit/test_predicates.py

ref https://github.com/pola-rs/polars/pull/20493
* Skip the filter expansion step entirely if predicate pushdown is disabled (this is disabled from the Python side `collect()` if `_eager` is `True`) - 
https://github.com/pola-rs/polars/blob/04004b8cae0160023b4be3b610e1fe16f04896d9/py-polars/polars/lazyframe/frame.py#L1991
~~I don't see an easy way to add a test case since it runs in eager, but we can validate this manually using this script -~~
Explicit validation for `DataFrame.filter()` is a bit tricky, but it can be done manually like this -
```python
import os
os.environ["POLARS_FORCE_NEW_STREAMING"] = "1"
os.environ["POLARS_VISUALIZE_PHYSICAL_PLAN"] = ".env/plan.dot"
df = pl.scan_csv("https://j.mp/iriscsv").collect()
df.filter(
(pl.col("species") == "setosa")
& …
```

perf: Skip filter expansion in eager

---

crates/polars-json/src/json/deserialize.rs
py-polars/tests/unit/io/test_json.py
py-polars/tests/unit/operations/namespaces/string/test_string.py

Adds a hint in the error message on how to resolve the error - a few users have run into it and it currently isn't immediately clear what could be done to resolve it.

feat: Add hint to error message for extra struct field in JSON

---

crates/polars-io/src/partition.rs
crates/polars-io/src/shared.rs
crates/polars-python/src/dataframe/io.rs

Fixes https://github.com/pola-rs/polars/issues/20502

feat: Support writing partitioned parquet to cloud

---

.github/workflows/benchmark-remote.yml

I missed a spot in https://github.com/pola-rs/polars/pull/20549

ci: Fix Python deps installation in remote-benchmark workflow

---

crates/polars-expr/src/expressions/sortby.rs
py-polars/tests/unit/operations/test_sort.py

fix: Properly broadcast in sort_by

---

crates/polars-sql/src/context.rs
crates/polars-sql/src/sql_expr.rs
py-polars/tests/unit/sql/test_strings.py

Closes #20606.
The "%" pattern in SQL `LIKE` and `ILIKE` ops is expected to match across linebreaks [^1].
```python
s1 = "Hello World"
s2 = "Hello\nWorld"
s3 = "hello\nWORLD"
"idx": [10, 20, 30],
"txt": [s1, s2, s3],
})
```
🔴 **Before**
_(linebreaks interrupt the match)_
```python
df.sql("SELECT * FROM self WHERE txt ILIKE 'Hello%'")
```
🟢 **After**
_(linebreaks do **not** interrupt the match)_
```python
df.sql("SELECT * FROM self WHERE txt ILIKE 'Hello%'")
```
**Aside:** I think we should look at rendering "\n" in the table output here (and "\t", etc) instead of actually rendering newlines/tabs (etc) as-is. Might take a look at that later 👀 
[^1]: _"a percent sign (%) matches **any** sequence of zero or more characters."_ …

fix: Ensure that SQL `LIKE` and `ILIKE` operators support multi-line matches

---

py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #20630.
Closes #20526.
* Fixes a minor `calamine` engine regression.
* Adds missing `bytes` ingest support for `openpyxl` engine.
* Test coverage for `BytesIO`, `bytes`, and `memoryview` across _all_ supported engines.

fix(python): Ensure `read_excel` and `read_ods` support reading from raw `bytes` for all engines

---

py-polars/polars/_utils/construction/dataframe.py
py-polars/tests/unit/constructors/test_constructors.py

Closes #20616.
We already catch this case in `read_database` (see: https://github.com/pola-rs/polars/pull/18548), but `read_database_uri` has exposed a more generic gremlin in frame construction  from `pyarrow.Table` objects (eg: `connectorx` loads query results to `pyarrow.Table`, which gets passed to `pl.from_arrow`).
We weren't explicitly checking the incoming `pyarrow.Table` for duplicate columns, which leads to a somewhat non-obvious `ShapeError`; with this PR we now raise a more helpful `DuplicateError` that explicitly refers to the column name that appears more than once.
```python
import pyarrow as pa
tbl = pa.Table.from_arrays(
arrays=[
pa.array([1, 2, 3], type=pa.int32()),
pa.array([4, 5, 6], type=pa.int32()),
],
schema=pa.schema([
("dupe_col", pa.int32()), …
```

feat(python): Raise `DuplicateError` if given a pyarrow Table object with duplicate column names

---

crates/polars-core/src/series/ops/null.rs

fix: Don't panic but set null type if type is unknown

---

crates/polars-mem-engine/src/executors/join.rs
crates/polars-ops/src/frame/join/asof/default.rs
py-polars/tests/unit/operations/test_join_asof.py

fix: Fix `join_asof` panicking for invalid `tolerance` input

---

py-polars/polars/io/cloud/credential_provider.py

Fixes https://github.com/pola-rs/polars/issues/20640

fix: Add `.default` to azure credential provider scope URL

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/spreadsheet/_write_utils.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #18849.
Allows `write_excel` to export to file _objects_ as well as file _paths_ (and BytesIO).
```python
from pathlib import Path
df1 = pl.DataFrame({"colx": ["aaa", "bbb", "ccc"]})
with Path("dataframe.xlsx").open(mode="wb") as p:
df1.write_excel(p)
df2 = pl.read_excel(Path("dataframe.xlsx"))
df1.equals(df2)
```

feat(python): Support writing to file objects from `write_excel`

---

crates/polars-core/src/serde/df.rs
py-polars/tests/unit/test_serde.py

This wasn't released yet, so it never was broken. Now it is tested.

fix: Fix serialization of empty DF in LazyFrame

---

py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #18949.
* Adds a "table_name" parameter to `read_excel`, supporting load of named Excel Table objects[^1]; works with "openpyxl" and "calamine" (requiring `fastexcel` >= 0.12 for the latter).
* Table names are unique across the workbook, so it is _not_ required to provide a value to the "sheet_name" or "sheet_id" parameter.
* If a "sheet_name" or "sheet_id" _is_ given, an error is raised if the named table is not found on _that_ sheet.
```python
"x": ["aa", "bb", "cc"],
"y": [100, 325, -250],
"z": [975, -444, 123],
})
df.write_excel(
"demo.xlsx",
worksheet="data",
table_name="PolarsFrameTable",
column_totals=True,
)
```
```python
pl.read_excel("demo.xlsx", table_name="PolarsFrameTable")
```
[^1]: [Using structured references with Excel …

feat(python): Support loading Excel Table objects by name

---

crates/polars-plan/src/dsl/meta.rs
crates/polars-plan/src/plans/aexpr/properties.rs
crates/polars-plan/src/plans/aexpr/traverse.rs
crates/polars-plan/src/plans/conversion/stack_opt.rs
crates/polars-plan/src/plans/iterator.rs
crates/polars-plan/src/plans/optimizer/collapse_joins.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_expr.rs
crates/polars-plan/src/plans/optimizer/stack_opt.rs
crates/polars-plan/src/plans/visitor/expr.rs

Also clarifies that `AExpr::nodes` iterates over the input nodes in reverse order by renaming it to `AExpr::inputs_rev`.

refactor(rust): Remove implicit reverse from AExpr::replace_inputs()

---

crates/polars-core/src/datatypes/mod.rs
crates/polars-core/src/series/implementations/array.rs
crates/polars-core/src/series/implementations/binary.rs
crates/polars-core/src/series/implementations/binary_offset.rs
crates/polars-core/src/series/implementations/boolean.rs
crates/polars-core/src/series/implementations/categorical.rs
crates/polars-core/src/series/implementations/date.rs
crates/polars-core/src/series/implementations/datetime.rs
crates/polars-core/src/series/implementations/decimal.rs
crates/polars-core/src/series/implementations/duration.rs
crates/polars-core/src/series/implementations/floats.rs
crates/polars-core/src/series/implementations/list.rs
crates/polars-core/src/series/implementations/mod.rs
crates/polars-core/src/series/implementations/null.rs
crates/polars-core/src/series/implementations/object.rs
crates/polars-core/src/series/implementations/string.rs
crates/polars-core/src/series/implementations/struct_.rs
crates/polars-core/src/series/implementations/time.rs
crates/polars-core/src/series/mod.rs
crates/polars-core/src/series/series_trait.rs
crates/polars-expr/src/reduce/mod.rs

This sped up concat by ~2x for me.

perf: Use downcast_ref instead of dtype equality in `<dyn SeriesTrait as AsRef<ChunkedArray<T>>`

---

crates/polars-python/src/map/mod.rs
crates/polars-python/src/map/series.rs
py-polars/tests/unit/operations/map/test_map_elements.py

closes #10102 
```python
{
"a": [{"b": 1}, None],
}
)
df.select(
pl.col("a").map_elements(lambda x: x["b"], skip_nulls=True)
)
```
main:
```
polars.exceptions.ComputeError: TypeError: 'NoneType' object is not subscriptable
```
This PR:
```
shape: (2, 1)
┌──────┐
│ a    │
│ ---  │
│ i64  │
╞══════╡
│ 1    │
│ null │
└──────┘
```

fix: Fix `map_elements` ignoring `skip_nulls=True` for struct dtype

---

py-polars/polars/expr/string.py
py-polars/polars/series/string.py

depr(python): Make parameter of `str.to_decimal` keyword-only

---

crates/polars-io/src/csv/read/read_impl.rs
py-polars/polars/io/csv/functions.py
py-polars/tests/unit/io/test_csv.py

fixes #14989
Also renames existing tests from (deprecated) `dtype_overwrite` to `schema_overrides`.

fix: Validate length of `schema_overrides` in `read_csv`

---

py-polars/tests/unit/datatypes/test_struct.py
py-polars/tests/unit/io/test_csv.py
py-polars/tests/unit/operations/test_is_sorted.py
py-polars/tests/unit/operations/test_pivot.py
py-polars/tests/unit/operations/unique/test_unique.py

Adds test coverage for a few open issues that are fixed on main:
closes #15237 
closes #8240 
closes #14106 
closes #17065 
closes #19338

test: Add tests for various open issues that have been fixed

---

crates/polars-core/src/frame/column/scalar.rs
crates/polars-ops/src/series/ops/concat_arr.rs
py-polars/tests/unit/functions/as_datatype/test_concat_arr.py

We were accidentally materializing due to using `as_materialized_series()` / `c.array()` (which underneath does `.as_materialized_series()`.
Also adjusts some slicing operations for the `Scalar` column variant to avoid taking refcounts to materialized Series when slicing to 0 or unit-length.

perf: Broadcast without materialization in `concat_arr`

---

crates/polars-parquet/src/parquet/schema/types/parquet_type.rs
crates/polars-parquet/src/parquet/schema/types/spec.rs

Since Parquet's `LogicalType` replaced the `ConvertedType`, there is no equivalent to certain `LogicalType`s in the ConvertedType (e.g. `Timestamp::Nanos`). Therefore, we should only verify whether the `ConvertedType` is valid if no `LogicalType` was given.
Fixes #20628.

fix: Only verify Parquet ConvertedType if no LogicalType is given

---

crates/polars-ops/src/chunked_array/gather/chunked.rs

The old code did not correctly remap buffer offsets when deduping, leading to segfaults.

fix: Incorrect view buffer dedup

---

Cargo.lock
crates/polars-python/Cargo.toml
crates/polars-python/src/conversion/any_value.rs
crates/polars-python/src/conversion/chunked_array.rs
crates/polars-python/src/conversion/datetime.rs

fixes #16199
Waiting for pyo3 v0.23.4 to be released. https://github.com/PyO3/pyo3/pull/4835

perf(python): Use PyO3 to convert between Python and Rust datetimes

---

crates/polars-io/src/cloud/options.rs
py-polars/polars/io/cloud/credential_provider.py

ref https://github.com/pola-rs/polars/issues/20634
* Fixes a behavior where storage account keys retrieved from Azure CLI would in some cases override user-specified configurations
* Disables retrieving and using storage account keys from Azure CLI by default, this is now only done if `POLARS_AUTO_USE_AZURE_STORAGE_ACCOUNT_KEY=1` is in the environment (note that `azure.identity` must also be installed as well, so that `CredentialProviderAzure` gets instantiated)

feat: Make automatic use of Azure storage account keys opt-in

---

py-polars/polars/io/spreadsheet/functions.py

Closes #20698.
Handle minor change of behaviour in yesterday's `fastexcel 12.1` release.

test(python): Fixes an Excel test following new `fastexcel` release

---

crates/polars-plan/src/plans/aexpr/properties.rs
py-polars/tests/unit/operations/test_group_by.py

fix: Don't partition group-by with non-scalar literals in agg

---

crates/polars-core/src/frame/row/av_buffer.rs
py-polars/tests/unit/operations/test_pivot.py

This technically changes behavior for `df.pivot` (possibly other things), but the old behavior was honestly bugged (despite us having a test for it).
Old behavior:
```python
>>> df
┌─────┬──────┬──────┬──────┬───────────┐
│ id  ┆ week ┆ num1 ┆ num2 ┆ nums      │
│ --- ┆ ---  ┆ ---  ┆ ---  ┆ ---       │
│ str ┆ str  ┆ i64  ┆ i64  ┆ struct[2] │
╞═════╪══════╪══════╪══════╪═══════════╡
│ a   ┆ 1    ┆ 1    ┆ 4    ┆ {1,4}     │
│ a   ┆ 2    ┆ 3    ┆ 5    ┆ {3,5}     │
│ b   ┆ 3    ┆ 5    ┆ 3    ┆ {5,3}     │
│ c   ┆ 4    ┆ 4    ┆ 4    ┆ {4,4}     │
│ c   ┆ 3    ┆ 3    ┆ 6    ┆ {3,6}     │
│ c   ┆ 1    ┆ 6    ┆ 6    ┆ {6,6}     │
└─────┴──────┴──────┴──────┴───────────┘
>>> df.pivot(values="nums", index="id", on="week", aggregate_function="first") …
```

fix: Add outer validity to AnyValueBufferTrusted for structs

---

crates/polars-io/src/parquet/write/batched_writer.rs
crates/polars-io/src/parquet/write/mod.rs
crates/polars-io/src/parquet/write/writer.rs
crates/polars-io/src/shared.rs
crates/polars-parquet/src/arrow/write/file.rs
crates/polars-parquet/src/parquet/metadata/schema_descriptor.rs
crates/polars-parquet/src/parquet/write/compression.rs
crates/polars-stream/src/nodes/io_sinks/mod.rs
crates/polars-stream/src/nodes/io_sinks/parquet.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/to_graph.rs

feat: Add Parquet Sink to new streaming engine

---

py-polars/tests/unit/constructors/test_constructors.py
py-polars/tests/unit/datatypes/test_decimal.py
py-polars/tests/unit/io/test_lazy_csv.py
py-polars/tests/unit/streaming/test_streaming_join.py
py-polars/tests/unit/test_empty.py

Adds tests for the following open issues that are already fixed on the main branch:
closes #12957    
closes #14881
closes #14992
closes #15523
closes #15583
The following open issues also appear to be fixed on the main branch. This PR does not add any tests for these issues as it appears tests have already been added that cover the originally reported issue. I've noted the tests below and commented on the individual issues. These can either be closed by merging this PR or by closing each issue directly:
closes #12521 -> test_list.py::test_fill_null_empty_list
closes #15151 -> test_decimal.py::test_decimal_round
closes #15130 -> test_parquet.py::test_parquet_array_dtype_nulls
closes #16692 -> test_parquet.py::test_nested_decimal
closes #17013 -> …

test: Add tests for various open issues

---

crates/polars-expr/src/reduce/convert.rs
crates/polars-expr/src/reduce/first_last.rs
crates/polars-expr/src/reduce/len.rs
crates/polars-expr/src/reduce/mean.rs
crates/polars-expr/src/reduce/min_max.rs
crates/polars-expr/src/reduce/mod.rs
crates/polars-expr/src/reduce/sum.rs
crates/polars-stream/src/nodes/group_by.rs
crates/polars-stream/src/nodes/reduce.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-stream/src/physical_plan/lower_group_by.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/streaming/test_streaming_group_by.py

Only contains an `AnyValue`-based general implementation right now, will add more performant options later.

feat: Add new-streaming first/last aggregations

---

crates/polars-core/src/series/implementations/list.rs
py-polars/tests/unit/operations/unique/test_n_unique.py

fix: Fix `Series.n_unique` raising for list of struct

---

crates/polars-expr/src/reduce/first_last.rs
crates/polars-expr/src/reduce/mean.rs
crates/polars-expr/src/reduce/min_max.rs
crates/polars-expr/src/reduce/mod.rs
crates/polars-expr/src/reduce/var_std.rs

Ensures we don't use the generic `AnyValue` path for numeric/temporal types, string types and bools.

perf: Specialize first/last agg for simple types in new-streaming engine

---

Cargo.lock
crates/polars-sql/Cargo.toml
crates/polars-sql/src/functions.rs
py-polars/docs/source/reference/sql/functions/string.rst
py-polars/tests/unit/sql/test_strings.py

Closes #20692.
Adds SQL support (and docs) for the `NORMALIZE`[^1] string function; takes advantage of the recently-added `normalize` expression (see: https://github.com/pola-rs/polars/pull/20483).
Available forms[^2]:
* NFC: Canonical Decomposition, followed by Canonical Composition.
* NFD: Canonical Decomposition.
* NFKC: Compatibility Decomposition, followed by Canonical Composition.
* NFKD: Compatibility Decomposition.
```sql
NORMALIZE(strcol, NFC)
NORMALIZE(strcol, NFD)
NORMALIZE(strcol, NFKC)
NORMALIZE(strcol, NFKD)
```
If the normalization form is not provided, `NFC` is used by default.
```python
pl.DataFrame({
"txt": [
"Ｔｅｓｔ",
"Ⓣⓔⓢⓣ",
"𝕿𝖊𝖘𝖙",
"𝕋𝕖𝕤𝕥",
"𝗧𝗲𝘀𝘁",
],
}).sql("SELECT NORMALIZE(txt, NFKC) FROM self").to_series()
```
[^1]: [PostgreSQL string …

feat: Add SQL support for the `NORMALIZE` string function

---

crates/polars-expr/src/expressions/apply.rs
crates/polars-expr/src/expressions/binary.rs
crates/polars-expr/src/expressions/column.rs
crates/polars-expr/src/expressions/mod.rs
crates/polars-mem-engine/src/executors/multi_file_scan.rs

Don't do a manipulation of the `PhysicalExpr` instead just supply the columns when `evaulate` happens.

refactor: Simplify hive predicate handling in `NEW_MULTIFILE`

---

crates/polars-plan/src/plans/optimizer/collapse_joins.rs
py-polars/tests/unit/operations/test_join.py

fix: Don't collapse into a Nested Loop Join if the cross join maintains order

---

crates/polars-core/src/series/implementations/null.rs
py-polars/tests/unit/operations/unique/test_unique.py

fix: Fix `unique(maintain_order=True)` raising `InvalidOperationError` for null array

---

crates/polars-expr/src/expressions/apply.rs
crates/polars-lazy/src/tests/aggregations.rs
py-polars/tests/unit/operations/map/test_map_groups.py

Fixes https://github.com/pola-rs/polars/issues/15260
Fixes https://github.com/pola-rs/polars/issues/15260

fix: Incorrect output type for `map_groups` returning all-NULL column

---

crates/polars-io/src/cloud/options.rs

Fixes the general case of all ClientConfigKeys[^1] set in `storage_options` being ignored - we have a set of defaults `get_client_options()` that needs to be set at the beginning rather than after the config has been parsed to avoid overwriting them.
Should fix https://github.com/pola-rs/polars/issues/20727, but I can't verify this locally.
[^1]: https://docs.rs/object_store/latest/object_store/enum.ClientConfigKey.html

fix: Fix `allow_invalid_certificates` being ignored in `storage_options`

---

crates/polars-expr/src/expressions/apply.rs
py-polars/tests/unit/operations/map/test_map_groups.py

Fixes a flaky test due to a silly typo 🙈

refactor: Fix flaky test

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

docs(python): Add more information for cross joins

---

py-polars/tests/unit/dataframe/test_serde.py
py-polars/tests/unit/datatypes/test_enum.py
py-polars/tests/unit/io/test_csv.py
py-polars/tests/unit/operations/test_fill_null.py
py-polars/tests/unit/series/test_item.py

New tests added for the following already fixed issues:
closes #8632
closes #14331
closes #17173
closes #17230
closes #18026
The following issues appears to be fixed and already tested (noted below). This PR does not add any new tests for these issues.
closes #10047 - `test_list.py::test_sort`
closes #17745 - `test_explode.py::test_explode_struct_nulls`
closes #17820 - `test_array.py::test_array_arithmetic_values`
closes #18516 - `test_ipc.py::test_ipc_variadic_buffers_categorical_binview_18636`
closes #18671 - `test_csv.py::test_write_csv_passing_params_18825`
closes #17221 - `test_join.py::test_join_numeric_type_upcast_15338`

test: Add various tests

---

py-polars/polars/datatypes/convert.py
py-polars/tests/unit/interop/numpy/test_numpy.py

Adds an entry to the numpy kind/size conversion mapping covering `np.float16`. 
(We don't have a native `Float16`, so it loads as `Float32`).
```python
"n": [np.float16(123)],
})
```
**Before:**
```python
```
**After:**
```python
```

feat(python): Additional support for loading `numpy.float16` values (as Float32)

---

py-polars/polars/io/delta.py

In deltalake 0.24 I've added support for LakeFS, this means users can use `lakefs:// ` uri's to read and write delta tables in LakeFS.
Internally in delta-rs, we just construct an S3 ObjectStore and some other things which I won't bother you with :). Point is polars can safely read `lakefs://` uri's as `s3://` uris. If we find lakefs:// uri's we just rewrite them as s3://.
If you want I can also move this in to rust, but I want to mostly keep this for the delta reader/scanner.

feat(python): Support `lakefs://` URI for delta scanner

---

.github/workflows/lint-python.yml
py-polars/polars/series/series.py
py-polars/tests/unit/interop/numpy/test_to_numpy_df.py
py-polars/tests/unit/interop/numpy/test_to_numpy_series.py
py-polars/tests/unit/series/test_series.py

Closes https://github.com/pola-rs/polars/issues/20561
Not the ideal fix, as users may run into the same typing issue with the latest NumPy version, but since it's mostly an issue with MyPy/NumPy I think this is acceptable for now.

ci: Unpin NumPy in type checking workflow

---

py-polars/polars/io/database/_utils.py
py-polars/polars/meta/versions.py
py-polars/pyproject.toml
py-polars/requirements-dev.txt
py-polars/tests/unit/io/database/test_async.py

In Polars Cloud we implemented this nested async functionality without a dependency. Figured we should do the same for the open source repo.

feat(python): Drop `nest-asyncio` in favor of custom logic

---

crates/polars-io/src/file_cache/entry.rs

Update to automatically ignore the error without needing the environment variable to be set if the system does not permit `fallocate()`.
ref https://github.com/pola-rs/polars/issues/17946

fix: Ignore file cache allocation error if `fallocate()` is not permitted

---

crates/polars-core/src/config.rs
crates/polars-io/src/cloud/object_store_setup.rs

We often request logs with `POLARS_VERBOSE` turned on - to prevent accidental key exposure we should not log any sensitive information. This PR instead introduces `POLARS_VERBOSE_SENSITIVE` for allowing logging of sensitive information.

fix: Do not print sensitive information to output on `POLARS_VERBOSE`

---

crates/polars-plan/src/dsl/function_expr/strings.rs
crates/polars-plan/src/dsl/string.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
crates/polars-python/src/lazyframe/visitor/expr_nodes.rs

The external function is called `contains_any()` but internal structs were called `ContainsMany` (probably because `replace_many()` was implemented at the same time).

refactor: Rename `ContainsMany` to `ContainsAny`

---

crates/polars-ops/src/chunked_array/repeat_by.rs
py-polars/tests/unit/functions/test_repeat.py

fix(python): Propagate null instead of panicking in `pl.repeat_by()`

---

crates/polars-core/src/chunked_array/drop.rs
crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/logical/categorical/ops/append.rs
crates/polars-core/src/chunked_array/logical/mod.rs
crates/polars-core/src/chunked_array/ops/append.rs
crates/polars-core/src/datatypes/dtype.rs
crates/polars-core/src/frame/column/mod.rs
crates/polars-core/src/frame/mod.rs
crates/polars-core/src/series/implementations/array.rs
crates/polars-core/src/series/implementations/binary.rs
crates/polars-core/src/series/implementations/binary_offset.rs
crates/polars-core/src/series/implementations/boolean.rs
crates/polars-core/src/series/implementations/categorical.rs
crates/polars-core/src/series/implementations/date.rs
crates/polars-core/src/series/implementations/datetime.rs
crates/polars-core/src/series/implementations/decimal.rs
crates/polars-core/src/series/implementations/duration.rs
crates/polars-core/src/series/implementations/floats.rs
crates/polars-core/src/series/implementations/list.rs
crates/polars-core/src/series/implementations/mod.rs
crates/polars-core/src/series/implementations/null.rs
crates/polars-core/src/series/implementations/object.rs
crates/polars-core/src/series/implementations/string.rs
crates/polars-core/src/series/implementations/struct_.rs
crates/polars-core/src/series/implementations/time.rs
crates/polars-core/src/series/mod.rs
crates/polars-core/src/series/series_trait.rs
crates/polars-core/src/utils/mod.rs

This reduces runtime for me on a vconcat by roughly 33%.
In the end, I chose to do a non-parallel version. As this performance is primarily important for the streaming engine where we don't have the same kind of parallelism.

perf: Make an owned version of append

---

py-polars/polars/expr/expr.py
py-polars/tests/unit/operations/test_is_in.py

Closes #20784.
The `isinstance` check for `is_in` constraint values was a little too restrictive.

fix(python): Allow `is_in` values to be given as custom `Collection`

---

py-polars/polars/io/database/_cursor_proxies.py
py-polars/polars/io/database/functions.py
py-polars/tests/unit/conftest.py
py-polars/tests/unit/io/database/test_async.py

The [SurrealDB Python API](https://github.com/surrealdb/surrealdb.py) has been updated (at the end of last year) in conjunction with their latest major release, splitting out `SurrealDB` and `AsyncSurrealDB` classes.
This PR updates our `SurrealDBCursorProxy` shim so that it can handle both the sync and async variants of the client object.
Tested (thoroughly!) locally with the sync and async clients (executing the async loop under both `asyncio` and `uvloop`).
Synchronous (`SurrealDB`):
```python
def surreal_query_to_frame(url: str, query: str):
with SurrealDB(url) as client:
client.use(namespace="test", database="test")
client.sign_in(username="elvis", password="pr3sley")
return pl.read_database(query=query, connection=client)
surreal_query_to_frame(
url="http://127.0.0.1:8000", …
```

feat(python): Account for SurrealDB Python API updates (handle both `SurrealDB` and `AsyncSurrealDB` classes) in `read_database`

---

crates/polars-ops/src/series/ops/cum_agg.rs
py-polars/tests/unit/datatypes/test_decimal.py

Fixes #14745
```python
df = pl.Series("a", ["2.2", "1.1", "3.3"], pl.Decimal(21, 1)).to_frame()
df.select(
pl.col("a").cum_sum().alias("cumulative_sum"),
pl.col("a").cum_min().alias("cumulative_min"),
pl.col("a").cum_max().alias("cumulative_max"),
)
```
BEFORE: (`cum_sum` raised `InvalidOperationError`):
```
┌────────────────┬────────────────┐
│ cumulative_min ┆ cumulative_max │
│ ---            ┆ ---            │
│ decimal[21,1]  ┆ decimal[21,1]  │
╞════════════════╪════════════════╡
│ 22.0           ┆ 22.0           │
│ 11.0           ┆ 22.0           │
│ 11.0           ┆ 33.0           │
└────────────────┴────────────────┘
```
AFTER:
```
┌────────────────┬────────────────┬────────────────┐
│ cumulative_sum ┆ cumulative_min ┆ …
```

feat: Support cumulative aggregations for `Decimal` dtype

---

crates/polars-plan/src/dsl/function_expr/strings.rs
py-polars/tests/unit/operations/namespaces/string/test_pad.py
py-polars/tests/unit/operations/namespaces/string/test_string.py

Fixes https://github.com/pola-rs/polars/issues/16070
The original issue only mentioned `str.zfill()`. There was already a similar check for some functions (e.g. `str.head()`). This PR extends this check to more `str` functions and adds tests, but  I did not check for other namespaces.
**Before (1.20.0): silently truncate to parameter length**
```python
input = pl.Series(["foo", "bar", "baz"])
input.str.starts_with(pl.Series(["a", "b"]))
input.str.ends_with(pl.Series(["a", "b"]))
input.str.contains(pl.Series(["a", "b"]))
input.str.find(pl.Series(["a", "b"]))
input.str.zfill(pl.Series([1, 2]))
input.str.strip_chars(pl.Series(["a", "b"]))
input.str.strip_chars_start(pl.Series(["a", "b"]))
input.str.strip_chars_end(pl.Series(["a", "b"])) …
```

fix: Error instead of truncate if length mismatch for several `str` functions

---

crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/required_masked_dense.rs
py-polars/tests/unit/io/test_parquet.py

fix: Shift mask when skipping Bitpacked values in Parquet

---

crates/polars-ops/src/series/ops/clip.rs
py-polars/tests/unit/operations/test_clip.py

```python
df = pl.Series("a", ["1.1", "2.2", "3.3"], pl.Decimal(21, 1)).to_frame()
df.select(
pl.col("a").clip(lower_bound=D("1.5"), upper_bound=D("2.5"))
)
```
BEFORE:
```
shape: (3, 1)
┌───────────────┐
│ a             │
│ ---           │
│ decimal[21,1] │
╞═══════════════╡
│ 15.0          │
│ 22.0          │
│ 25.0          │
└───────────────┘
```
AFTER: 
```
shape: (3, 1)
┌───────────────┐
│ a             │
│ ---           │
│ decimal[21,1] │
╞═══════════════╡
│ 1.5           │
│ 2.2           │
│ 2.5           │
└───────────────┘
```

fix: Fix `clip` for `Decimal` returning wrong values

---

crates/polars-io/src/cloud/options.rs

Fixes https://github.com/pola-rs/polars/issues/20650
Issue is due to not handling the carriage return `\r` of the CRLF `\r\n` line terminator used in the configuration file.
This updates Rust-side code, however it is less-used after the Python-side CredentialProviderAWS was introduced.

fix: Fix panic `InvalidHeaderValue` scanning from S3 on Windows

---

py-polars/polars/io/cloud/credential_provider.py
py-polars/polars/selectors.py
py-polars/tests/unit/test_selectors.py

Closes #20821.
Selectors act as sets and support the standard set ops:
https://docs.pola.rs/api/python/stable/reference/selectors.html#set-operations
Operation | Expression
-- | --
UNION | A \| B
INTERSECTION | A & B
DIFFERENCE | A - B
SYMMETRIC DIFFERENCE | A ^ B
COMPLEMENT | ~A
_However_... sets do **not** support the `+` operator between themselves. 
```python
{1,2,3} + {2,3,4}
```
We are inadvertently passing-through `+` between selectors to Expr, leading to very peculiar (and unintended) results or errors in cases where the caller meant to use `|` or `&` instead. This PR fixes that (while retaining support for broadcasting).
```python
data = {
"col1": [1, 2, 3],
"col2": [4.1, 5.2, 6.3],
"col3": ["x", "y", "z"],
}
df = …
```

fix(python): Selectors should raise on `+` between themselves

---

crates/polars-core/src/frame/group_by/position.rs
py-polars/polars/series/series.py
py-polars/tests/unit/test_queries.py

Closes #20818.
Following the code further down, I think the panicking `assert` is invalid, and can be removed... @ritchie46, could you double-check, in case I missed some other paths that _do_ rely on this?🤞😅 It's not an error to ask for a slice larger than the number of available rows - in this case it should just get clipped to how many rows there actually are.
The `1.20.0` release panics on the following:
```python
"key": ["xx", "yy", "zz", "xx", "zz", "zz"],
"val": [15, 25, 10, 20, 20, 20],
})
grp = lf.group_by("key").agg(pl.col("val").sum())
grp.head(5).collect()  # aggregate result is 3 rows; head(5) panics
```

fix: Remove `assert` that panics on `group_by` followed by `head(n)`, where `n` is larger then the frame height

---

py-polars/polars/_utils/getitem.py
py-polars/tests/unit/dataframe/test_df.py

Closes #20775.
The issue is that `df.slice(idx, 1)` was being called for a single integer index key, and slices return the empty set instead of raising when `idx` is out of bounds. This PR adds a small height check.

fix(python): Add height check to frame-level row indexing when key is int

---

crates/polars-stream/src/nodes/io_sinks/csv.rs
crates/polars-stream/src/nodes/io_sinks/mod.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/to_graph.rs

feat: Add CSV sink for the new streaming engine

---

crates/polars-core/src/utils/supertype.rs
py-polars/tests/unit/expr/test_literal.py
py-polars/tests/unit/operations/test_index_of.py

Fixes #20807 
See also #20829 for related issues that also seem like they need fixing.

fix: Fix one edge case (out of many) of int128 literals not working

---

crates/polars-core/src/chunked_array/ops/fill_null.rs
py-polars/tests/unit/datatypes/test_decimal.py

Fixes the following:
```python
from decimal import Decimal
ser = pl.Series([Decimal("1.23"), None])
ser.fill_null(strategy="one")
```
BEFORE:
```
shape: (2,)
Series: '' [decimal[*,2]]
[
1.23
0.01
]
```
AFTER:
```
shape: (2,)
Series: '' [decimal[*,2]]
[
1.23
1.00
]
```

fix: Incorrect `Decimal` value for `fill_null(strategy="one")`

---

py-polars/tests/unit/constructors/test_constructors.py
py-polars/tests/unit/datatypes/test_duration.py
py-polars/tests/unit/interop/test_to_init_repr.py
py-polars/tests/unit/io/test_ipc.py
py-polars/tests/unit/operations/test_cast.py
py-polars/tests/unit/operations/unique/test_unique.py

Tests added for the following open issues that appear to already be fixed:
closes #2732
closes #6968
closes #7737
closes #9461
closes #12950
closes #13759
closes #15014
closes #17006
These open issues also appear to be fixed and already have tests. Just noting the existing tests in order to close these issues:
closes #9383 - `test_rolling_fixed.py::test_rolling_var_stability_12905`
closes #11194 - `test_decimal.py::test_df_constructor_convert_decimal_to_float_9873`

test: Add tests for open issues

---

crates/polars-mem-engine/src/executors/executor.rs
crates/polars-stream/src/physical_plan/lower_ir.rs

This is very suboptimal, but necessary for now.

chore: Dispatch to the in-memory engine for multifile sources

---

crates/polars-lazy/src/scan/csv.rs
docs/source/src/python/user-guide/expressions/aggregation.py
docs/source/src/rust/user-guide/expressions/aggregation.rs

The original URL at https://theunitedstates.io/congress-legislators/legislators-historical.csv currently returns a 404 and is causing CI to fail.

docs: Update source URL for `legislators-historical.csv`

---

py-polars/polars/io/cloud/credential_provider.py
py-polars/tests/unit/io/cloud/test_credential_provider.py

* For AWS, this enables auto-initialization of `CredentialProviderAWS` if `storage_options` contains only an `aws_region` config key.
* In general, for all supported cloud types:
*  Allows credential providers to be auto-initialized if `storage_options` contains client config keys[^1]
* Adjusts checking of keys on the Python-side to be case-insensitive
[^1]: https://docs.rs/object_store/latest/object_store/enum.ClientConfigKey.html

feat(python): Auto-initialize Python credential providers in more cases

---

crates/polars-python/src/dataframe/general.rs
py-polars/polars/dataframe/frame.py
py-polars/tests/unit/constructors/test_constructors.py

Closes  #20128.
We can redirect to `LazyFrame` to handle this consistently, dropping the passthrough method on `PyDataFrame`.

feat(python): Allow column expressions in DataFrame `unnest`

---

crates/polars-plan/src/plans/expr_ir.rs
crates/polars-plan/src/plans/optimizer/collapse_joins.rs
py-polars/tests/unit/lazyframe/test_optimizations.py

Fixes https://github.com/pola-rs/polars/issues/20831
* https://github.com/pola-rs/polars/issues/20831
We have had this issue for queries in the form `.join(.., how='cross').filter(..).select(..)` for quite a while (since version 1.8.2).

fix: Fix DuplicateError when selecting columns after `join_where` or cross join + filter

---

py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/operations/namespaces/test_categorical.py

chore: Remove todo and test restriction for new-streaming

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/cloud/_utils.py
py-polars/polars/io/cloud/credential_provider.py
py-polars/polars/io/delta.py

Adds automatic Python-side credential provider initialization to the Delta I/O functions (`read_delta`, `scan_delta`, `write_delta`), similar to those previously added to other I/O functions. This includes `DefaultAzureCredential` (ref https://github.com/pola-rs/polars/issues/20808):
* https://github.com/pola-rs/polars/issues/20808
Before calling into the Delta Python library, we directly call the credential provider on the Python-side and inject them into `storage_options`, as the Delta Python library does not accept a callable credential provider. This works as our built-in credential providers (`AWS`, `Azure`, `GCP`) all return `object_store`-compatible key-value pairs - i.e. it's valid to do something like this:
```python
creds, _expiry = pl.CredentialProviderAzure()()
pl.read_delta( …
```

feat(python): Experimental credential provider support for Delta read/scan/write

---

crates/polars-core/src/datatypes/dtype.rs
crates/polars-stream/src/physical_plan/lower_group_by.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/streaming/test_streaming_unique.py

This isn't the most efficient implementation possible, but it already avoids a complete fallback to the eager engine in a lot of cases. At some point we should make a proper streaming distinct node though.

feat: Implement df.unique() on new-streaming engine

---

Cargo.lock
Cargo.toml
crates/polars-arrow/Cargo.toml
crates/polars-arrow/src/compute/decimal.rs
crates/polars-compute/Cargo.toml
crates/polars-compute/src/cast/decimal_to.rs
crates/polars-core/src/fmt.rs
crates/polars-io/src/csv/write/write_impl/serializer.rs
crates/polars-json/src/json/write/serialize.rs

Possibly a bit slower but I doubt it's much different or it forming a bottleneck. Can always optimize it more later.

refactor(rust): Simplify decimal formatting and remove itoap dep

---

crates/polars-ops/src/series/ops/log.rs
py-polars/tests/unit/series/test_series.py

```python
df = pl.Series("a", [D("1.0")]).to_frame()
pl.col("a").log().alias("a_log"),
pl.col("a").exp().alias("a_exp"),
)
```
BEFORE:
```
┌──────────────┬──────────┬──────────────┐
│ a            ┆ a_log    ┆ a_exp        │
│ ---          ┆ ---      ┆ ---          │
│ decimal[*,1] ┆ f64      ┆ f64          │
╞══════════════╪══════════╪══════════════╡
│ 1.0          ┆ 2.302585 ┆ 22026.465795 │
└──────────────┴──────────┴──────────────┘
```
AFTER: 
```
┌──────────────┬───────┬──────────┐
│ a            ┆ a_log ┆ a_exp    │
│ ---          ┆ ---   ┆ ---      │
│ decimal[*,1] ┆ f64   ┆ f64      │
╞══════════════╪═══════╪══════════╡
│ 1.0          ┆ 0.0   ┆ 2.718282 │
└──────────────┴───────┴──────────┘
```

fix: Incorrect scale used in `log` and `exp` for Decimal type

---

crates/polars-python/src/conversion/any_value.rs
py-polars/tests/unit/datatypes/test_object.py

fixes #20572
Use fully qualified names to avoid name collisions in python types.

fix: Avoid name collisions and panicking in object conversion

---

crates/polars-arrow/src/array/static_array_collect.rs
crates/polars-arrow/src/legacy/trusted_len/push_unchecked.rs

In some cases this might be a bit slower but I don't think the heavy unrolling and macro inlining of the previous implementation was justified to use in such a general and often used method.

refactor(rust): Reduce bloat in static_array_collect by using BitmapBuilders

---

Cargo.lock
Cargo.toml
crates/polars-arrow/Cargo.toml
crates/polars-arrow/src/compute/decimal.rs
crates/polars-time/Cargo.toml
crates/polars-time/src/chunkedarray/string/strptime.rs

refactor(rust): Remove last instances of itoa

---

crates/polars-ops/src/frame/join/asof/groups.rs
crates/polars-ops/src/frame/join/asof/mod.rs
crates/polars-ops/src/frame/join/mod.rs
crates/polars-python/src/lazyframe/general.rs
docs/source/src/rust/user-guide/transformations/joins.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

fix: Warn if asof keys not sorted

---

py-polars/polars/io/iceberg.py
py-polars/tests/unit/io/test_iceberg.py

Filtering Iceberg table boolean columns on boolean literals fails trying to parse `pa.compute.scalar(True)`. This updates the Call predicate parser to handle the `scalar` type.
I originally posted about this in the Discord here which has a few more details: https://discord.com/channels/908022250106667068/1273409357685592159
```python
table = pl.scan_iceberg(iceberg.load_table("codes.icd10cm"))
table.filter(pl.col("is_header") == False).collect()
table.sql("SELECT count(*) from self where is_header = false").collect()
```
The error was
```
File .venv/lib/python3.12/site-packages/polars/lazyframe/frame.py:2027, in LazyFrame.collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, slice_pushdown, comm_subplan_elim, comm_subexpr_elim, cluster_with_columns, …
```

fix(python): Handle boolean comparisons in Iceberg predicate pushdown

---

py-polars/polars/_utils/construction/dataframe.py
py-polars/tests/unit/interop/numpy/test_from_numpy_df.py

fix: Fix `from_numpy` returning Null dtype for empty 1D numpy array

---

py-polars/polars/datatypes/classes.py
py-polars/tests/unit/datatypes/test_array.py

fix(python): Validate `pl.Array` shape argument types

---

py-polars/polars/dataframe/frame.py
py-polars/polars/series/series.py
py-polars/tests/unit/constructors/test_constructors.py

fixes https://github.com/pola-rs/polars/issues/20889

fix(python): Don't consume c_stream as iterable

---

crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/mod.rs
crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/required.rs

I did some more tests and found out the problem for the codegen problem here.

chore: Fix the `verify_dict_indices` codegen

---

py-polars/tests/unit/datatypes/test_decimal.py
py-polars/tests/unit/functions/as_datatype/test_concat_list.py
py-polars/tests/unit/functions/test_when_then.py
py-polars/tests/unit/operations/namespaces/list/test_list.py
py-polars/tests/unit/operations/test_fill_null.py
py-polars/tests/unit/operations/test_join_asof.py
py-polars/tests/unit/series/test_equals.py

Closes a few categories of open issues:
1. Fixed or implemented but does not appear to be tested (tests added in this PR):
closes #9084
closes #11232
closes #11362
closes #12199
closes #14875
closes #18014
closes #18375
closes #18587
2. Fixed or implemented and already tested (just noting existing tests that appear to cover the reported issue):
closes #11078 - `test_decimal.py::test_decimal_aggregations`
closes #11079 - `test_decimal.py::test_decimal_sort`
closes #11081 - `test_lit.py::test_lit_decimal`
closes #14773 - `test_csv.py::test_csv_quote_styles`
closes #19794 - `test_csv.py::test_csv_quoted_newlines_skip_rows_19535`
3. Feature requests that have since been implemented:
closes #7675
closes #12203
4. Usage questions which have been answered and are unlikely to be further …

test: Add tests for already resolved issues

---

crates/polars-plan/src/plans/optimizer/projection_pushdown/functions/mod.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/functions/unpivot.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/group_by.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/hconcat.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/hstack.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/joins.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/projection.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/semi_anti_join.rs
py-polars/tests/unit/test_projections.py

perf: Ensure count query select minimal columns

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

docs: Ensure `set_sorted` description references single-column behavior

---

crates/polars-plan/src/plans/optimizer/cse/cse_expr.rs
crates/polars-plan/src/utils.rs
py-polars/tests/unit/test_cse.py

fix: Ensure Function name correctness in cse

---

crates/polars-arrow/src/bitmap/builder.rs
crates/polars-parquet/src/arrow/read/deserialize/binview/mod.rs
crates/polars-parquet/src/arrow/read/deserialize/binview/predicate.rs
crates/polars-parquet/src/arrow/read/deserialize/boolean.rs
crates/polars-parquet/src/arrow/read/deserialize/categorical.rs
crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/mod.rs
crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/predicate.rs
crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary.rs
crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs
crates/polars-parquet/src/arrow/read/deserialize/null.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/float.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/plain/mod.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/plain/predicate.rs
crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs

refactor: Move Parquet deserialization to `BitmapBuilder`

---

py-polars/polars/_typing.py
py-polars/polars/functions/eager.py
py-polars/tests/unit/functions/test_functions.py
py-polars/tests/unit/test_errors.py

Closes #20637.
Simple extension to allow for more generic align options in `concat` (the concat strategy for "align" is directly associated with the "how" join method, so we can easily use join methods other than "full" - this can result in significant speedups if we know that "align_left" is sufficient/appropriate for our target frames 🚀)
* Extends `concat` "how" parameters with "align inner", "align_left", "align_right", and "align_full" (which is equivalent to the existing/default "align", but more explicit).
* Streamlines the internal concat/align code to use `coalesce=True` for all join types; no longer have to manually identify/drop the uncoalesced common join cols. Should get a (minor) speedup from this too.
```python
df1 = pl.DataFrame({"id": [1, 2], "x": [3, …
```

feat(python): Make the available `concat` alignment strategies more generic

---

crates/polars-plan/src/dsl/function_expr/strings.rs
py-polars/tests/unit/operations/namespaces/string/test_string.py

Closes #20962.
This was introduced in #20781 and noticed here: https://github.com/pola-rs/polars/pull/20781#discussion_r1930609364. Thanks @eitsupi.
Like other `str.*_many()` functions, `str.extract_many()` shouldn't check the length of the `patterns` arg. 
This was overlooked in the tests because the main test for `extract_many()` only had one value and one list of `patterns`. I updated it to ensure that lengths of input and `patterns` can be different. Sorry for the mistake.

fix: Revert length check of `patterns` in `str.extract_many()`

---

py-polars/polars/io/cloud/credential_provider.py
py-polars/tests/unit/dataframe/test_df.py

Closes https://github.com/pola-rs/polars/issues/18757
* https://github.com/pola-rs/polars/issues/18757
Adds handling for `aws_profile` being passed in `storage_options`. This is not natively supported by object_store, but we can check this on the Python side and forward it to `CredentialProviderAWS`. This requires `boto3` to be installed, so we also issue a warning if this is not the case.
Note that on the latest release (1.21.0) the environment variable `AWS_PROFILE` is already being implicitly picked up by boto3.

feat(python): Support passing `aws_profile` in `storage_options`

---

py-polars/polars/expr/expr.py
py-polars/tests/unit/operations/test_is_in.py

Closes #20937.
This was implicitly allowed before; the slight `isinstance` modification caused a minor regression. Fixed, and added the missing test coverage.

fix(python): Address minor regression for one-column DataFrame passed to `is_in` expressions

---

crates/polars-plan/src/plans/lit.rs
crates/polars-sql/Cargo.toml
crates/polars-sql/src/sql_expr.rs
crates/polars-sql/tests/simple_exprs.rs
crates/polars-time/src/windows/duration.rs
py-polars/tests/unit/sql/test_literals.py

As brought up in the Discord, there was a bug with SQL interface `INTERVAL` literals that don't represent fixed durations (eg: "1 month", "1 year").
Interval addition/subtraction from date or datetime values was not being done correctly for intervals that don't represent a fixed duration (eg: `SELECT datecol + '6 months'`; this fix ensures such queries are properly converted to `pl.col("datecol").dt.offset_by('6mo')`.
Standalone intervals can now _only_ be created where they represent a fixed duration (on the Python side such intervals are returned as `timedelta` literals, which also have to represent fixed durations).
**Valid:** `SELECT INTERVAL '1 week'` (allowed - represents an exact value)
**Invalid:** `SELECT INTERVAL '1 month'` (raises - does _not_ represent an exact value) …

fix: Improve SQL interface behaviour when `INTERVAL` is not a fixed duration

---

crates/polars-error/src/warning.rs
crates/polars-plan/src/plans/optimizer/mod.rs
crates/polars-python/src/error.rs
py-polars/pyproject.toml

Information on the new streaming engine: #20947.

chore: Deprecate the old streaming engine

---

py-polars/polars/_typing.py
py-polars/polars/convert/normalize.py
py-polars/requirements-dev.txt
py-polars/tests/unit/io/test_json.py

Closes #20950.
* Allows a custom json encoder function to be passed to `json_normalize`, enabling the caller to target specific performance/behaviour.
* Minor speedup (~6-7% faster) from optimising Python loops 🚀 
* No change to default behaviour (uses `json.dumps`).
* Additional JSON test coverage.
```python
data = [
{
"id": n,
"name": {"first": "Some", "middle": None, "last": "Name"},
"attrs": {"height": 185, "weight": 90},
"lifts": {
"max_deadlift": 190, 
"max_squat": 140, 
"max_bench": 100,
},
} for n in range(5)
]
```
```python
pl.json_normalize(data, max_level=0)
```
```python
import orjson
pl.json_normalize(data, max_level=0, encoder=orjson.dumps)
```

feat(python): Allow custom JSONEncoder for the `json_normalize` function, minor speedup

---

crates/polars-io/src/catalog/unity/client.rs
crates/polars-io/src/catalog/unity/models.rs
crates/polars-python/src/catalog/mod.rs
py-polars/docs/source/reference/catalog.rst
py-polars/polars/catalog.py

To avoid confusion with the internal schema type. Renames variable/struct/method names across all catalog code, including the user-facing Python API. E.g.:
* `schema_info` -> `namespace_info`
* `SchemaInfo` -> `NamespaceInfo`
* `schema_name` -> `namespace`

feat: Rename catalog `schema` to `namespace`

---

Cargo.lock
crates/polars-error/Cargo.toml
crates/polars-error/src/warning.rs

I doubt we'll be using warning functions at top speed.

refactor(rust): Remove unnecessary unsafe around warning function

---

.github/workflows/test-coverage.yml
py-polars/tests/unit/operations/test_inequality_join.py

Code coverage is currently failing as it runs on x86 macOS, which installs an old version of torch (2.2.2, March 2024) that is incompatible with the latest version of numpy (>v2). Note that torch wheels for x86 macOS have stopped being built since 2.2.2 due to deprecation.
We had previously pinned the macOS runner to use macos-13 due to difficulties on macos-latest at the time, this PR removes that pin and uses macos-latest instead.
* Closes https://github.com/pola-rs/polars/issues/15917
<details>
<summary>Debug notes</summary>
* Code coverage observed to be broken since at least 2025-01-29 07:35 UTC time, with no apparent changes to any dependency files
* Comparing the log differences, the `numpy` version being installed in the runner was suddenly changed from `1.26.3` to `2.1.2`. After …

ci: Update code coverage workflow to use macos-latest runners

---

crates/polars-stream/src/nodes/mod.rs
crates/polars-stream/src/nodes/negative_slice.rs
crates/polars-stream/src/physical_plan/fmt.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs

This should be the last computational `todo!` in the new-streaming engine.

feat: Add negative slice support to new-streaming engine

---

docs/source/user-guide/lazy/gpu.md

due to questions that arose, I wanted to clarify up front that the GPU Open beta works on a single GPU.

docs: Explicitly call out that the GPU open beta runs on a single GPU

---

crates/polars-ops/src/frame/join/merge_sorted.rs
py-polars/tests/unit/operations/test_merge_sorted.py

Fixes the cases for `Categorical` and `Decimal`.
fixes #20987
fixes #20989
fixes #20990

fix: Fix `merge_sorted` producing incorrect results or panicking for some logical types

---

Makefile
crates/Makefile
py-polars/Makefile

Working on Rust code? `make pre-commit` or the CI yells at you? Good chance `make fix` just solves it for you.

chore: Add make fix for running cargo clippy --fix

---

crates/polars-stream/src/nodes/io_sources/parquet/init.rs

This isn't very flexible but at least ensures that for single-rowgroup files we're parallel even if it would be smaller than the ideal row group size, in case it feeds into an expensive operator.

perf: Split last rowgroup among all threads in new-streaming parquet reader

---

crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/conversion/join.rs
crates/polars-plan/src/plans/conversion/stack_opt.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
py-polars/tests/unit/lazyframe/test_lazyframe.py
py-polars/tests/unit/operations/test_cast.py
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/test_cwc.py

* Fixes https://github.com/pola-rs/polars/issues/21009
* The expression gets recognized by `collapse_joins` without issue after we remove the extra cast
* Fixes https://github.com/pola-rs/polars/issues/21023
* Updates some old code to propagate `options: CastOptions` instead of `strict: bool`
Drive-by renames `fn coerce_types()` to `fn optimize_exprs()` under `ConversionOptimizer`, as it also does other optimizations aside from type coercion.

perf: Remove cast to boolean after comparison in optimizer

---

docs/source/user-guide/plugins/index.md
docs/source/user-guide/plugins/io_plugins.md
py-polars/docs/source/reference/plugins.rst
py-polars/polars/io/plugins.py
py-polars/polars/plugins.py

Closes #20996
Adds IO plugins to the Python API reference.
Given that plugins are a bit more advanced (like extending the API), I thought it would be useful to provide some extra detail in the API reference too. This text is copied from the user guide.
Few small drive-bys including updating user guide links. Note that these link do not work on the currently deployed user guide, but consider the changes in #20982
Personally I find the reST text a bit hard to envisage, so here are some screenshots of my local deployment of the docs with the changes.
https://github.com/user-attachments/assets/a4668566-1985-475e-aa4b-6586fad5f294
https://github.com/user-attachments/assets/5b434f44-57d1-4f3e-8888-0e10e4a88446
https://github.com/user-attachments/assets/5b46b6e2-f355-4ddc-9e6e-bbf4e1a6201d

docs(python): Add IO plugins to Python API reference

---

crates/polars-error/src/signals.rs
crates/polars-python/src/utils.rs

Using a custom exception object was more efficient but meant that we wouldn't suppress the panic input if the panic was wrapped inside another. This happens with e.g. `rayon` where a panic inside a worker will get caught and passed to the `join` result as an `Err(panic)`. Then when you call `unwrap` on that the exception is now a `JoinError` rather than the `KeyboardInterrupt`.
This does mean that we do string matching every time a panic, but ultimately the performance here doesn't really matter, we don't often cause panics.

refactor(rust): Use string-based keyboard interrupt panic detection

---

py-polars/polars/io/spreadsheet/_write_utils.py
py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

The function was written before we had the `Array` dtype and the `is_nested()` method on the dtype class, so explicitly enumerated the dtypes that needed to be cast to string on sheet export - and therefore missed `Array`.
* Now takes advantage of `.is_nested()` to guarantee that we consistently identify dtypes that Excel doesn't work with natively (List, Array, Struct). 
* Also made a few micro-optimisations, eg: `df.height` instead of `len(df)`, and `df.width` instead of `len(df.columns)`. Note that we can make this change in more places, avoiding the indirect/function call - I'll follow up with a separate PR for that.

fix(python): Ensure `write_excel` recognises the Array dtype and writes it out as a string

---

py-polars/tests/unit/datatypes/test_list.py

closes https://github.com/pola-rs/polars/issues/18522

test(python): Added test to check for the computation of list.len for null

---

crates/polars-core/src/fmt.rs
py-polars/polars/config.py
py-polars/tests/unit/test_config.py

fix: Fix `set_tbl_width_chars` panicking with negative width

---

py-polars/polars/dataframe/frame.py

- Resolves #20739 
- Gives a further example in the docstring of `DataFrame.write_delta` showing users how to change the compression format
- Includes two links to the parts of the docs in Delta Lake that give the parameters responsible for writing to delta lake and configuring the Rust parquet writer respectively

docs(python): Add example showing use of `write_delta` with `delta_lake.WriterProperties`

---

crates/polars-core/src/datatypes/dtype.rs
py-polars/polars/datatypes/classes.py
py-polars/tests/unit/test_datatypes.py

Suggested by https://github.com/pola-rs/polars/pull/19494#discussion_r1821291799
Since there are explicit upper and lower limits for the Time type in the Apache Arrow specification[^1], it may be useful to call them here.
[^1]: https://github.com/apache/arrow/blob/e79f65cbd7851a9c4abdde81bf444b6d6b1de1bb/format/Schema.fbs#L258-L275

feat: Support max/min method for Time dtype

---

crates/polars-ops/src/chunked_array/top_k.rs
py-polars/tests/unit/operations/test_top_k.py

fixes #17225 
#17225 identified list-of-list types as panicking, but simple list types that are unsorted also panic.

fix: Calling `top_k` on list type panics

---

py-polars/polars/sql/context.py
py-polars/tests/unit/io/database/test_read.py

fix new ruff lints failing in #21035

chore: Fix new ruff lints

---

docs/source/_build/API_REFERENCE_LINKS.yml
docs/source/src/python/user-guide/io/cloud-storage.py
docs/source/src/rust/user-guide/io/cloud-storage.rs
docs/source/user-guide/io/cloud-storage.md
py-polars/polars/io/cloud/credential_provider.py

ref https://github.com/pola-rs/polars/issues/18931#issuecomment-2623535321
* Closes https://github.com/pola-rs/polars/issues/20635
Introduces a `credentials` parameter to `CredentialProviderAzure`, which can provide a QoL improvement, as users can then do:
```python
pl.scan_parquet(
"abfss://...@.../...",
credential_provider=pl.CredentialProviderAzure(
credentials=DefaultAzureCredential(exclude_managed_identity_credential=True)
),
)
```
instead of:
```python
def credential_provider():
credential = DefaultAzureCredential(exclude_managed_identity_credential=True)
token = credential.get_token("https://storage.azure.com/.default")
return {"bearer_token": token.token}, token.expires_on
pl.scan_parquet(
"abfss://...@.../...",
credential_provider=credential_provider,
)
```
Also adds the above …

feat(python): Add CredentialProviderAzure parameter to accept user-instantiated azure credential classes

---

crates/polars-core/src/chunked_array/logical/categorical/mod.rs
py-polars/tests/unit/datatypes/test_categorical.py

Fixes #20864 .
As we never set sorted flags for pl.Categorical("lexical"), when casting to it we need to explicitly set it to not sorted.

fix: Invalidate sortedness flag when sorting from pl.Categorical to pl.Categorical("lexical")

---

crates/polars-parquet/src/parquet/metadata/column_descriptor.rs
crates/polars-parquet/src/parquet/metadata/row_metadata.rs
crates/polars-parquet/src/parquet/metadata/schema_descriptor.rs

fix: Quadratic allocations when loading nested Parquet column metadata

---

crates/polars-stream/src/nodes/io_sources/parquet/mem_prefetch_funcs.rs
crates/polars-utils/src/mem.rs

This ensures that in the new-streaming engine we forcibly pre-fault in e.g. the parquet reader to get clearer performance profiles.

chore(rust): Add force_populate_read for debugging pagefault performance problems

---

crates/polars-ops/src/frame/join/merge_sorted.rs
py-polars/tests/unit/operations/test_merge_sorted.py

Quite trivial, closes #20988
```python
"a": pl.Series("a", [b"1", b"3", b"5"], pl.Binary()),
"b": [1, 3, 5],
})
"a": pl.Series("a", [b"2", b"4", b"6"], pl.Binary()),
"b": [2, 4, 6],
})
print(df1.merge_sorted(df2, "a"))
```

feat: Implement `merge_sorted` for binary

---

py-polars/polars/_utils/construction/dataframe.py
py-polars/polars/_utils/getitem.py
py-polars/polars/dataframe/frame.py
py-polars/polars/io/spreadsheet/_write_utils.py
py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/dataframe/test_from_dict.py
py-polars/tests/unit/dataframe/test_getitem.py
py-polars/tests/unit/dataframe/test_null_count.py
py-polars/tests/unit/dataframe/test_to_dict.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/functions/test_lit.py
py-polars/tests/unit/io/test_csv.py
py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py
py-polars/tests/unit/operations/test_explode.py
py-polars/tests/unit/streaming/test_streaming.py

Ensure we are taking advantage of `DataFrame` "height" and "width" properties internally. 
* Using `df.width` instead of `len(df.columns)` avoids materialising a list of columns only to discard it after taking its length (this can be meaningful for very wide frames).
* Using `df.height` instead of `len(df)` only avoids a function-call (so _very_ minor).

perf(python): Micro-optimise internal `DataFrame` height and width checks

---

crates/polars-stream/src/nodes/joins/equi_join.rs

The gather of the payload after finding matches does a rechunk internally. We now rechunk eagerly (as long as 1 match is found) to avoid the repeated rechunk. This sped up query 16 in PDS-H by ~2x.

perf: Rechunk only once during join probe gather

---

py-polars/polars/convert/general.py
py-polars/polars/dataframe/frame.py
py-polars/polars/datatypes/classes.py
py-polars/polars/io/spreadsheet/_write_utils.py
py-polars/tests/unit/constructors/test_constructors.py
py-polars/tests/unit/constructors/test_dataframe.py
py-polars/tests/unit/constructors/test_series.py
py-polars/tests/unit/datatypes/test_object.py
py-polars/tests/unit/interop/test_to_pandas.py
py-polars/tests/unit/series/test_scatter.py

Minor nicety - adds missing `is_object()` method to DataType (we have all manner of other dtype helpers like `is_nested()`, `is_temporal()`, etc, but this one was absent).

feat(python): Add `is_object` method to Polars `DataType` class

---

docs/source/user-guide/migration/pandas.md

Fixes #20560 to replace pandas `.where` with `.mask`.

docs(python): Replace pandas `where` with `mask` in Migrating -> Coming from Pandas

---

py-polars/polars/catalog/unity/client.py
py-polars/tests/unit/io/cloud/test_catalog.py

Adds a Python-side function to write tables. The version in this PR will currently only support writing to delta tables (`data_source_format` is `DELTA` or `DELTASHARING`).
Drive-by forbids using unsecured `http://` URLs as the `workspace_url` by default unless `require_https=False` is passed

feat(python): Add `write_table()` function to Unity catalog client

---

py-polars/tests/unit/constructors/test_series.py
py-polars/tests/unit/datatypes/test_decimal.py
py-polars/tests/unit/io/test_json.py
py-polars/tests/unit/operations/aggregation/test_aggregations.py
py-polars/tests/unit/operations/map/test_map_elements.py
py-polars/tests/unit/operations/rolling/test_rolling.py
py-polars/tests/unit/operations/test_fill_null.py
py-polars/tests/unit/operations/test_join_asof.py
py-polars/tests/unit/streaming/test_streaming.py

tests added for open issues that appear to be fixed but untested:
closes #15122
closes #15145
closes #15546
closes #15574
closes #16296
closes #17669
closes #18244
closes #18369
open issues that appear to be fixed and already tested (noting tests in order to close):
closes #19528 - `test_concat.py::test_concat_invalid_schema_err_20355`
closes #15347 - `test_join_asof.py::test_join_asof_not_sorted`

test: Add various tests for open issues

---

crates/polars-ops/src/chunked_array/hist.rs
py-polars/tests/unit/operations/test_hist.py

Closes #21082 and closes #20879.
Minor fixes:
1) Ensure upper breakpoint is equal to upper value when bins are auto-computed (due to floating point issues, sometimes the max value would be e.g. 7.0 and the upper bin limit would be 6.999999...).
2) NaN values were not being skipped and sometimes fell into the default logical path which incremented a bucket.

fix(rust): Fix minor histogram issues

---

py-polars/polars/io/cloud/credential_provider.py

🙈
* Regression from https://github.com/pola-rs/polars/pull/21090

fix(python): Fix credential provider error

---

.github/workflows/test-coverage.yml
.github/workflows/test-python.yml

This seems to shave off around 50 seconds from the `test-python` jobs.

build: Speed up CI by running a few more tests in parallel

---

crates/polars-arrow/src/compute/concatenate.rs

This is a regression on new-streaming for query 9 and 10 due to adding contention on stringview `Arc`s, but that should be fixed in a separate PR.

perf: Deduplicate buffers again in stringview concat kernel

---

crates/polars-compute/src/gather/binview.rs
crates/polars-compute/src/gather/mod.rs
crates/polars-core/src/chunked_array/ops/gather.rs

We were spending quite a bit of time on this useless conversion in the new streaming engine, and it doesn't even really save codesize as the real codesize is in `take_values_and_validity_unchecked` on `View`s which is still shared.

perf: Reduce conversion cost in chunked string gather

---

py-polars/polars/io/cloud/credential_provider.py

Intended for cloud / remote execution support.
It currently uses the one sourced during local initialization even after being deserialized on a remote machine.
Note that a case that we still don't handle well is if a user's local machine doesn't have permissions to the cloud storage, while the remote machine does. In this case remote execution will also not use a credential provider.
What I think should instead happen is that the `_maybe_init_credential_provider()` credential provider resolution is performed on the remote machine before the query is executed. Doing this is a bit more involved, but I plan to get this working next week.

feat(python): Ensure AWS credential provider sources AWS_PROFILE from environment after deserialization

---

crates/polars-io/src/catalog/unity/schema.rs

The type returned from deltalake indicates microseconds.

fix: Use microseconds for Unity catalog datetime unit

---

crates/polars-arrow/src/array/binview/mod.rs
crates/polars-core/src/frame/mod.rs
crates/polars-expr/src/expressions/window.rs
crates/polars-ops/src/chunked_array/gather/chunked.rs
crates/polars-pipe/src/executors/sinks/joins/generic_probe_inner_left.rs
crates/polars-pipe/src/executors/sinks/joins/generic_probe_outer.rs
crates/polars-stream/src/nodes/joins/equi_join.rs

This is a regression on some queries in PDS-H but gets rid of really problematic contention in others, so makes behavior more predictable & scalable.
The PR also includes some unused code for avoiding sharing in a chunked gather. From experimenting that was slower but I left it in because it might come in handy in the future for more experimentation.

perf: Reduce sharing in stringview arrays in new-streaming equijoin

---

crates/polars-error/src/signals.rs

I messed up in my logic of when to suppress panics from keyboard interrupts leading to some backtraces being incorrectly suppressed.

fix: Restore printing backtraces on panics

---

crates/polars-io/src/path_utils/mod.rs

* Fixes https://github.com/pola-rs/polars/issues/21120
On unix systems this will use a unique temporary directory per user (generally `/tmp/polars-$USER`, and ensure that it is accessible only by the current user (i.e. `chmod 700`).
On Windows systems the temporary directory was already under the users data directory (e.g. `C:\Users\user\AppData\Local\Temp\polars`), so I haven't made any changes there

feat: Use unique temporary directory path per user and restrict permissions

---

py-polars/polars/functions/lit.py
py-polars/pyproject.toml
py-polars/tests/unit/expr/test_literal.py

Closes #20544.
* The Rust-side `AnyValue` path accounts for fixed offsets from UTC, but `lit` construction on the Python side didn't. Now works for both. 
* Plenty of new test coverage added.
```python
from dateutil.tz import tzoffset
dt = datetime(2020, 1, 1, tzinfo=tzoffset(None, 20700))
pl.select(pl.lit(dt))
```
**Previously**:
```
ComputeError: unable to parse time zone: 'tzoffset(None, 20700)'. 
Please check the Time Zone Database for a list of available time zones
```

fix(python): Ensure `lit` handles datetimes with tzinfo that represents a fixed offset from UTC

---

crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs
py-polars/tests/unit/operations/test_join.py

Join on `Struct` dtype via row encoding. 
closes #15500
closes #10721

feat: Implement join on struct dtype

---

crates/polars-io/src/path_utils/mod.rs

In the event something goes wrong with the newly added permission setting behavior from https://github.com/pola-rs/polars/pull/21125, this provides a way to allow for any errors to be ignored so that users can avoid needing to downgrade their polars version.

feat: Add `POLARS_ALLOW_UNSECURED_TEMP_DIR` environment variable

---

crates/polars-expr/src/expressions/window.rs
py-polars/tests/unit/datatypes/test_decimal.py

fixes #21096
```python
df = pl.Series("x", [1, 2], pl.Decimal(scale=2)).to_frame()
df.select(pl.col("x").min().over("x"))
```
Before:
```
shape: (2, 1)
┌──────────────┐
│ x            │
│ ---          │
│ decimal[*,2] │
╞══════════════╡
│ 100.00       │
│ 200.00       │
└──────────────┘
```
After:
```
shape: (2, 1)
┌──────────────┐
│ x            │
│ ---          │
│ decimal[*,2] │
╞══════════════╡
│ 1.00         │
│ 2.00         │
└──────────────┘
```

fix: Fix `Expr.over` applying scale incorrectly for Decimal types

---

crates/polars-plan/src/plans/schema.rs

docs(rust): Correct small typo in `FileInfo`

---

crates/polars-sql/src/context.rs
py-polars/tests/unit/sql/test_set_ops.py

as its actually reachable and causes a panic when attempting unsupported ops like INSERT, UPDATE, DELETE, etc.

fix: Raise error instead of panicking for unsupported SQL operations

---

crates/polars-time/src/chunkedarray/string/strptime.rs
py-polars/tests/unit/operations/namespaces/test_strptime.py

```python
df=pl.DataFrame({"a": ["2020-01-01"]})
df.select(pl.col("a").str.strptime(pl.Date, format="d%"))
```
**Before:**
```
pyo3_runtime.PanicException: invalid pattern
```
**After:**
```
polars.exceptions.InvalidOperationError: conversion from `str` to `date` failed in column 'a' for 1 out of 1 values: ["2020-01-01"]
You might want to try:
- setting `strict=False` to set values that cannot be converted to `null`
- using `str.strptime`, `str.to_date`, or `str.to_datetime` and providing a format string
```

fix: Do not panic in `strptime()` if `format` ends with '%'

---

crates/polars-sql/src/context.rs
py-polars/docs/source/reference/sql/table_operations.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/series/series.py
py-polars/tests/unit/sql/test_table_operations.py

Adds SQL support for the `DELETE FROM <table> [WHERE <constraint>]` statement.
(Validated edge-cases -such as constraints involving null values- against SQLite).
```python
"id": [100, 200, 300],
"dt": [date(2020, 10, 10), date(1999, 1, 2), date(2001, 7, 5)],
"v1": [3.5, -4.0, None],
"v2": [10.0, 2.5, -1.5],
})
```
```python
df.sql("DELETE FROM self WHERE v1 < 0")
```
```python
df.sql("DELETE FROM self WHERE EXTRACT(year FROM dt) >= 2000")
```

feat: Add SQL support for the `DELETE` statement

---

crates/polars-expr/src/hash_keys.rs
crates/polars-io/src/parquet/read/predicates.rs
crates/polars-stream/src/nodes/joins/equi_join.rs
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/operations/unique/test_unique.py
py-polars/tests/unit/streaming/test_streaming_join.py
py-polars/tests/unit/test_projections.py

The new streaming engine's join will now buffer at least `POLARS_JOIN_SAMPLE_LIMIT` rows (default 10 million) from both sides of the join before deciding which side will become a build or probe side.

perf: Add sampling to new-streaming equi join to decide between build/probe side

---

crates/polars-io/src/csv/read/parser.rs
crates/polars-stream/src/async_primitives/wait_group.rs
crates/polars-stream/src/nodes/io_sources/csv.rs
crates/polars-utils/src/lib.rs
crates/polars-utils/src/select.rs

Using `LineStats::analyze_chunk` we'll be able to do (almost) true parallel parsing of CSV where there is only a tiny serial dependency between chunks but all chunks can be processed in parallel.

refactor(rust): Use distributor channel in new-streaming CSV reader and prepare scanning routine for true parallel reading

---

crates/polars-ops/src/frame/join/merge_sorted.rs
py-polars/tests/unit/operations/test_merge_sorted.py

This PR implements `merge_sort` by struct-typed columns and fixes a bug where the field column names would be empty after merging.
Closes https://github.com/pola-rs/polars/issues/20986
Closes https://github.com/pola-rs/polars/issues/13485
```python
"a": [{"x": 1, "y": 1}, {"x": 1, "y": 3}, {"x": 2, "y": 2}],
})
"a": [{"x": 1, "y": 2}, {"x": 2, "y": 1}, {"x": 2, "y": 3}],
})
print(df1.merge_sorted(df2, "a"))
```

feat: Implement `merge_sorted` for struct

---

py-polars/docs/source/conf.py

Twitter was rebranded to X in 2023, so I thought it would be time to replace the Twitter logo in our API reference docs.

docs(python): Update social icons in API reference docs

---

py-polars/polars/dataframe/frame.py

Closes #21221.
Unnecessary import of the `packaging` module (inside `write_delta()`).
We can use our own `parse_version()` here to drop the dependency 👌

refactor(python): Avoid unnecessary `packaging` dependency

---

crates/polars-parquet/src/arrow/read/deserialize/binview/mod.rs
py-polars/tests/unit/io/test_parquet.py

fix: UTF-8 validation of nested string slice in Parquet

---

crates/polars-ops/src/chunked_array/top_k.rs
py-polars/tests/unit/operations/test_top_k.py

closes #21260
```python
pl.Series([1, 2, 3, 4]).sort().top_k(3)
```

fix: Incorrect result for top_k/bottom_k when input is sorted

---

crates/polars-stream/src/nodes/joins/equi_join.rs

I introduced early stopping during the cached morsel flushing but this wasn't correct. I also didn't correctly re-label the sequence ids leading to potentially the same morsel id being sent into multiple pipelines.

fix: Deadlock due to bad logic in new-streaming join sampling

---

crates/polars-core/src/chunked_array/comparison/mod.rs
crates/polars-core/src/chunked_array/struct_/mod.rs
py-polars/tests/unit/datatypes/test_struct.py

fix: Infinite recursion when broadcasting into struct zip_outer_validity

---

py-polars/polars/io/database/_utils.py

The new `connectorx` release (~8 hours ago) has removed the "arrow2" return type, and just uses "arrow" now (note that - amusingly - we don't use the "polars" return type directly as we want to apply `schema_overrides` ourselves).
This fixes the two tests that now fail in CI when `connectorx` v0.4.2 is picked up.

fix(python): Account for minor change in new `connectorx` release

---

crates/polars-arrow/src/array/mod.rs

Fixes #20239
This issue happens in release mode when integer overflow is wrapped.
We can use checked_add function of usize to check for overflow in release mode without letting it wrap.
Using expect, lets the code panic fulfilling the assertion.

fix: Checking overflow in Sliced function

---

crates/polars-ops/src/frame/join/asof/mod.rs
py-polars/tests/unit/operations/test_join_asof.py

Closes #21276.
The supertype of i64 and u64 is i128, so both sides are upcast to i128. However, there was no i128 match arm and so the take idx defaulted to the `i32` path in that case. The result is that values larger than `i32::MAX` failed to downcast and resulted in null.

fix: Add `Int128` path for `join_asof`

---

crates/polars-python/src/lazyframe/visitor/nodes.rs

Needed to implement in the polars GPU executor. xref https://github.com/rapidsai/cudf/issues/18012

feat(rust): Expose `include_file_paths` to python visitor

---

crates/polars-stream/src/async_primitives/connector.rs

This fixes a bug that made values in the `Connector` channel leak if the receiver was dropped before the value was received.
In the receiver drop it now:
1. Prevents a new value from entering the channel.
2. Eagerly drops the value if there's still a value in the channel.
3. Wakes the sender.
The reason this resolves a deadlock is because we were sending `WaitToken`s that we rely on dropping through the channel. If those aren't dropped the associated `WaitGroup` will never unblock.

fix: Resolve deadlock due to leaking in Connector recv drop

---

crates/polars-core/src/chunked_array/array/mod.rs
crates/polars-core/src/chunked_array/list/mod.rs
py-polars/tests/unit/series/test_series.py

This PR adds rechunking in `ArrayChunked::to_physical_repr` and `ListChunked::to_physical_repr` when needed.
Fixes #21285 
The test depends on the `Null` field causing rechunking and should be removed or updated if that behavior changes.

fix: Panic in `to_physical` for series of arrays and lists

---

crates/polars-ops/src/frame/join/args.rs
crates/polars-plan/src/plans/optimizer/collapse_joins.rs
crates/polars-plan/src/plans/optimizer/join_utils.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
py-polars/tests/unit/operations/test_join.py

* Fixes https://github.com/pola-rs/polars/issues/21142
Non-suffixed columns were incorrectly identified as belonging to the RHS table due to using `check_input_node(predicate.node(), &schema_right, expr_arena)` (which incorrectly matches to the non-suffixed column on the RHS before join). We now use `ExprOrigin` to correctly identify this.
This PR also improves predicate pushdown for predicates referring only to RHS columns in right-joins:
**Before**
```python
FILTER col("values_right").is_null() FROM
RIGHT JOIN:
LEFT PLAN ON: [col("key")]
DF ["key", "values"]; PROJECT */2 COLUMNS
RIGHT PLAN ON: [col("key")]
DF ["key", "values"]; PROJECT */2 COLUMNS
END RIGHT JOIN
```
**After**
```python
RIGHT JOIN:
LEFT PLAN ON: [col("key")]
DF ["key", "values"]; PROJECT */2 COLUMNS
RIGHT PLAN ON: …
```

fix: Fix incorrect predicate pushdown for predicates referring to right-join key columns

---

crates/polars-plan/src/plans/conversion/join.rs
crates/polars-plan/src/plans/optimizer/mod.rs
py-polars/tests/unit/operations/test_inequality_join.py
py-polars/tests/unit/operations/test_join.py

* Fixes https://github.com/pola-rs/polars/issues/21145

fix: Fix performance regression for eager `join_where`

---

crates/polars-lazy/src/frame/mod.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-sql/src/context.rs
py-polars/docs/source/reference/dataframe/modify_select.rst
py-polars/docs/source/reference/lazyframe/modify_select.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/array.py
py-polars/polars/expr/expr.py
py-polars/polars/expr/string.py
py-polars/polars/expr/struct.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/string.py
py-polars/tests/unit/test_predicates.py

We currently have frame-level `filter`, but after adding "DELETE" [support](https://github.com/pola-rs/polars/pull/21190) to the SQL engine it felt like we should really offer a dedicated `remove` method too:
* Aside from improved semantics (eg: it's much clearer to say _"remove rows that match this"_ rather than using `filter` to say _"don't remove rows that don't match this"_) there is also a slight subtlety as `remove(predicate)` is **not** the same thing as `filter(~predicate)`. This is because of null value comparison.
For `filter` and `remove` to share common/consistent semantics (we require the predicate to evaluate as `True` in order to be acted on) the correct conversion is actually `filter(predicate.ne_missing(true))` - this is not necessarily immediately obvious; handling it …

feat: Add a dedicated `remove` method for `DataFrame` and `LazyFrame`

---

crates/polars-plan/src/plans/aexpr/predicates/skip_batches.rs
py-polars/tests/unit/io/test_parquet.py
py-polars/tests/unit/io/test_skip_batch_predicate.py

fix: Skip Batches Expression for boolean literals

---

py-polars/polars/expr/name.py

Closes #21305.
(`removesuffix` was made available in py3.9, which has been our minimum supported version for a while now; updated the example to use it, as per the linked issue).

docs(python): Improve `Expr.name.map` docstring example

---

crates/polars-core/src/datatypes/field.rs
crates/polars-io/src/parquet/read/reader.rs
py-polars/tests/unit/interop/test_interop.py
py-polars/tests/unit/io/test_delta.py
py-polars/tests/unit/io/test_parquet.py

* Fixes https://github.com/pola-rs/polars/issues/21317
* On new-streaming, this is fixed only with `POLARS_FORCE_MULTISCAN` turned on
* Fixes https://github.com/pola-rs/polars/issues/19645
This involves adding a dispatch and fixing a bug.

feat: Support reading arrow Map type from Delta

---

crates/polars-core/src/frame/horizontal.rs
crates/polars-ops/src/frame/join/general.rs
crates/polars-plan/src/plans/schema.rs
crates/polars-schema/src/schema.rs
crates/polars-sql/src/context.rs
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/sql/test_joins.py

* Fixes https://github.com/pola-rs/polars/issues/21048
Updates to use (newly added) `Schema::try_insert()` instead of `Schema::with_column` during IR resolution to catch duplicate errors.
Note, there are a lot more places in the codebase that should probably be using `try_insert()` instead of `with_column`.

fix: Fix duplicate column names after join if suffix already present

---

py-polars/docs/source/reference/selectors.rst

Closes #21320.
Since the example was created, `group_by` now takes "*by" (args), not "by=" 😅

docs: Fix initial selector example

---

crates/polars-time/src/windows/duration.rs
py-polars/tests/unit/operations/namespaces/temporal/test_offset_by.py

closes #21283 
Previously, the logic was:
- `let mut new_t = t`
- then, when adding years / months, increment `new_t`
- then, when adding days, increment `new_t`
The issue was that for the last step, it was starting the calculation from `t` rather than from `new_t`, which is why the linked issue reports that if `'d'` is included, then `years` and `months` get discarded
I don't think `new_t` is necessary at all - `t` can just get incremented at each step, so like this there's no risk of accidentally incrementing the wrong variable

fix: Method `dt.offset_by` was discarding month and year info if day was included in offset for timezone-aware columns

---

crates/polars-core/src/chunked_array/ops/sort/mod.rs
crates/polars-core/src/series/implementations/struct_.rs
py-polars/tests/unit/operations/test_is_sorted.py

This PR implements sorted flags for struct series.
```python
s = pl.Series("a", [{"x": 3 }, {"x": 1 }, {"x": 2 }]).sort()
assert s.flags["SORTED_ASC"]
```
It removes a duplicate `StructChunked::arg_sort` function, it exists in `ChunkSort<StructType> for StructChunked` with the same name and implementation.
Closes #13484

feat: Implement sorted flags for struct series

---

crates/polars-stream/src/async_primitives/connector.rs

I don't know how I made these silly mistakes, in my mind I associated "Acquire" with receiving and "Release" with sending, but in fact both sender and receiver must both acquire and send to properly synchronize.

fix(rust): Incorrect atomic ordering in Connector

---

py-polars/polars/_utils/deprecation.py
py-polars/polars/functions/eager.py
py-polars/tests/unit/functions/test_functions.py

Closes #21133.
Non-breaking enhancement. Allows for list/iterable input of frames _in addition_ to the current positional input, enabling `pl.align_frames` and `pl.concat` to be called in a consistent fashion.
```python
df1 = pl.DataFrame({"x": [3,4,5], "y": [5,8,9]})
df2 = pl.DataFrame({"x": [2,5,4], "y": [3,8,9]})
```
```python
pl.align_frames(df1, df2, on="x")
```
```python
pl.align_frames([df1, df2], on="x")
```
_(additive; does not replace current calling convention)_

feat(python): Allow iterable of frames as input to `align_frames`

---

crates/polars-plan/src/plans/optimizer/projection_pushdown/semi_anti_join.rs
py-polars/tests/unit/operations/test_join.py

* Fixes https://github.com/pola-rs/polars/issues/21343
Note that there are a few other occurrences of `acc_projections.is_empty()` - I'm not sure whether those can be problematic:

fix: Fix ColumnNotFound error selecting `len()` after semi/anti join

---

.github/workflows/benchmark.yml
crates/polars-io/src/hive.rs
crates/polars-io/src/ipc/ipc_file.rs
crates/polars-io/src/parquet/read/read_impl.rs
crates/polars-io/src/parquet/read/utils.rs
py-polars/tests/unit/io/test_hive.py

* Fixes https://github.com/pola-rs/polars/issues/21327
* Fixes https://github.com/pola-rs/polars/issues/20894

fix: Fix unequal DataFrame column heights from parquet hive scan with filter

---

crates/polars-core/src/frame/horizontal.rs
crates/polars-core/src/frame/mod.rs
crates/polars-core/src/frame/validation.rs
crates/polars-ops/src/frame/pivot/mod.rs
crates/polars-ops/src/series/ops/to_dummies.rs
crates/polars-schema/src/schema.rs
py-polars/tests/unit/dataframe/test_df.py

If `self` was empty, we failed to check that the columns within the slice being added all had equal heights.
E.g. this currently passes and creates a DataFrame with invalid state:
```rust
let mut df = DataFrame::empty();
let result = df.hstack_mut(&[
Column::full_null("a".into(), 1, &DataType::Null),
Column::full_null("b".into(), 3, &DataType::Null),
]);
```
This PR adds a `DataFrame::validate_columns_slice` function, and we now take an approach where we perform the append first, and then call the validation function on the resulting slice.
There is a chance this PR may start to uncover implementation bugs elsewhere.

fix(rust): Fix height validation in `hstack_mut` was bypassed when adding to empty frame

---

crates/polars-expr/src/expressions/gather.rs
py-polars/tests/unit/operations/test_gather.py

I traced #21178 down to `gather` in aggregation context not updating the groups properly.
This PR makes sure the groups are updated, otherwise this causes wrong results or OOB access in the following operation. I checked that each changed line fixes the matching test.
I added Python tests to cover each of the changed lines, but they are a bit fragile, since there is no guarantee they will keep triggering this Rust code in the future. Is there a better way I can write the tests, maybe as Rust unit tests?
Closes #21178

fix: Properly update groups after `gather` in aggregation context

---

crates/polars-io/src/ipc/ipc_file.rs
py-polars/tests/unit/io/test_ipc.py
py-polars/tests/unit/io/test_scan.py

fix: Panic when projecting only row index from IPC file

---

crates/polars-io/src/predicates.rs
crates/polars-mem-engine/src/predicate.rs
crates/polars-plan/src/plans/optimizer/cache_states.rs
crates/polars-plan/src/plans/optimizer/mod.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
crates/polars-stream/src/nodes/io_sources/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_scan.rs
crates/polars-stream/src/nodes/io_sources/parquet/mod.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/io/test_hive.py
py-polars/tests/unit/io/test_multiscan.py

feat: Filter hive files using predicates in new streaming

---

Cargo.lock
Cargo.toml
crates/polars-io/src/cloud/object_store_setup.rs
crates/polars-plan/src/client/mod.rs
crates/polars-plan/src/dsl/python_dsl/python_udf.rs
crates/polars-plan/src/plans/python/predicate.rs
crates/polars-python/src/cloud.rs
crates/polars-python/src/expr/serde.rs
crates/polars-python/src/lazyframe/serde.rs
crates/polars-utils/Cargo.toml
crates/polars-utils/src/pl_serialize.rs

Though we don't guarantee anything, this makes it much more likely that binary serialized data can be read across versions. 
The data is serialized into IPC for both compact as self-describing, so that is a compact serialization in both cases. As we call `serialize_bytes` on the `Series` impl. I believe we should go in the most optimal (1 byte per u8) encoding.
The caller must decide if it wants the `FC: true` (forward compatible) encoding via msgpack or `FC: false` encoding via bincode.

feat: Make user facing binary formats mostly self describing

---

crates/polars-plan/src/plans/aexpr/schema.rs
py-polars/tests/unit/operations/arithmetic/test_arithmetic.py

Closes #21389.
Right now, duration * primitive does not propagate the dtype and results in a schema error if the resulting expression is used afterwards, despite it being a valid operation.
```python
from datetime import datetime, timedelta
from polars import col
"ts": [datetime(2025, 1, 1)],
"dur": [timedelta(days=1)],
})
df.select(col("dur") * 2)              # OK
df.select(2 * col("dur"))              # OK
df.select(col("ts") + col("dur"))      # OK
df.select(col("ts") + 2 * col("dur"))  # OK
df.select(col("ts") + col("dur") * 2)  # ERROR!!!
```
After fix:
```pycon
>>> df.select(col("ts") + col("dur") * 2)
shape: (1, 1)
┌─────────────────────┐
│ ts                  │
│ ---                 │
│ datetime[μs]        │
╞═════════════════════╡
│ …
```

fix: Allow duration multiplied w/ primitive to propagate in IR schema

---

crates/polars-time/src/chunkedarray/date.rs
crates/polars-time/src/chunkedarray/datetime.rs
py-polars/tests/unit/functions/as_datatype/test_datetime.py
py-polars/tests/unit/functions/range/test_date_range.py
py-polars/tests/unit/operations/namespaces/temporal/test_replace.py

Fixes #20977.
I am not sure if this is a breaking change or not.
Example of new behavior:
```pycon
>>> pl.select(pl.date(2025, 13, 1))  # month 13 is invalid (pl.Date)
polars.exceptions.ComputeError: Invalid date components (2025, 13, 1) supplied
>>> pl.select(pl.datetime(2025, 13, 1))  # month 13 is invalid (pl.Datetime)
polars.exceptions.ComputeError: Invalid date components (2025, 13, 1) supplied
>>> pl.select(pl.datetime(2025, 1, 1, 25))  # hour 25 is invalid
polars.exceptions.ComputeError: Invalid time components (25, 0, 0, 0) supplied
```

fix: Don't silently produce null values from invalid input to `pl.datetime` and `pl.date`

---

crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs
py-polars/tests/unit/operations/rolling/test_rolling.py

fixes #21318
Updates `Expr.rolling_sum` and `Expr.rolling_sum_by` to upcast small integer dtypes to `Int64` to be consistent with other sum operations such as `Expr.sum` and `Expr.cum_sum`.

fix: Upcast small integer dtypes for rolling sum operations

---

py-polars/docs/source/reference/sql/functions/bitwise.rst

The `bitwise.rst` file had "Temporal" as title.

docs(python): Fix doc for SQL Functions navigation

---

crates/polars-time/src/chunkedarray/datetime.rs
py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py

fix: Method `dt.ordinal_day` was returning UTC results as opposed to those on the local timestamp

---

py-polars/polars/io/spreadsheet/functions.py

Closes #21427.
Small fix for a `read_excel` regression.

fix(python): Address regression with `read_excel` not handling URL paths correctly

---

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/io/test_spreadsheet.py

fixes https://github.com/pola-rs/polars/issues/20870
I have what I believe is a working solution and it is passing all the pre-existing tests. However, I don't know how to test whether my change is creating the expected behavior or not (when the dataframe is too large to be compatible with Excel, an exception should be thrown). 
This is my very first commit to an open-source project, so I apologize in advance for any mistakes I might have made and I look forward to hearing any and all feedback.

fix(python): Throw exception if dataframe is too large to be compatible with Excel

---

py-polars/tests/unit/lazyframe/test_lazyframe.py

Fixes https://github.com/pola-rs/polars/issues/21349
This PR adds a test based on the bug repo.

test: Test for unique length on multiple columns

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

docs(python): Mention that `statistics=True` doesn't enable all statistics in `sink_parquet()`

---

py-polars/tests/unit/io/test_parquet.py

This was already fixed on main. Just adding a test to avoid a future regression.
Fixes #21450.

chore: Add test for empty `.is_in` predicate filter

---

py-polars/tests/unit/operations/rolling/test_rolling.py

test: Add test for rolling stability sort

---

crates/polars-stream/src/nodes/io_sinks/csv.rs
crates/polars-stream/src/nodes/io_sinks/ipc.rs
crates/polars-stream/src/nodes/io_sinks/json.rs
crates/polars-stream/src/nodes/io_sinks/mod.rs
crates/polars-stream/src/nodes/io_sinks/parquet.rs
crates/polars-stream/src/nodes/io_sources/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs

This will wrap all the sink nodes and allow generic functionality using the sink nodes.

refactor: Introduce a Sink Node trait in the new streaming engine

---

crates/polars-error/src/lib.rs
crates/polars-python/src/error.rs
crates/polars-python/src/exceptions.rs

This PR adds support for assertion errors to Polars error handling system. The assertion errors will ultimately be used in Rust when working on migrating `assert_series_equal` and `assert_frame_equal` to Rust to facilitate testing. This is the first part (of roughly 3) working on this issue: https://github.com/pola-rs/polars/issues/21388
`crates/polars-error/src/lib.rs`: 
* Added `AssertionError` variant to `PolarsError` enum
* Added `AssertionError` to implementation of `Display`
* Added `AssertionError` to `wrap_msg()`
* Added a macro for `AssertionError` under `macro rules! polars_err`
`crates/polars-python/src/error.rs`
* Imported `AssertionError` exception
* Added `AssertionError` `match` arm
`crates/polars-python/src/exceptions.rs`
* Added `AssertionError` to `create_exception!()`

feat: Add `AssertionError` variant to `PolarsError` in `polars-error`

---

crates/polars-json/src/json/write/serialize.rs
py-polars/tests/unit/io/test_json.py

Closes #21452.
I also removed two small branches that aren't relevant to Polars:
1. `ArrowDataType::Timestamp(s)` - this is our `Datetime` dtype, which only uses `ms`, `us`, and `ns`, we have no `s` implementation.
2. `ArrowDataType::Duration(s)` - same as `Datetime` units described above.

feat: Support writing `Time` type in json

---

crates/polars-expr/src/expressions/aggregation.rs

fix: Don't divide by zero in partitioned group-by

---

crates/polars-arrow/src/array/binview/builder.rs
crates/polars-arrow/src/array/binview/mod.rs
crates/polars-arrow/src/array/binview/mutable.rs
crates/polars-arrow/src/array/boolean/builder.rs
crates/polars-arrow/src/array/boolean/mod.rs
crates/polars-arrow/src/array/builder.rs
crates/polars-arrow/src/array/fixed_size_binary/builder.rs
crates/polars-arrow/src/array/fixed_size_binary/mod.rs
crates/polars-arrow/src/array/fixed_size_list/builder.rs
crates/polars-arrow/src/array/fixed_size_list/mod.rs
crates/polars-arrow/src/array/list/builder.rs
crates/polars-arrow/src/array/list/mod.rs
crates/polars-arrow/src/array/mod.rs
crates/polars-arrow/src/array/null.rs
crates/polars-arrow/src/array/primitive/builder.rs
crates/polars-arrow/src/array/primitive/mod.rs
crates/polars-arrow/src/array/struct_/builder.rs
crates/polars-arrow/src/array/struct_/mod.rs
crates/polars-arrow/src/bitmap/builder.rs
crates/polars-arrow/src/buffer/immutable.rs

This doesn't actually do anything (nor is it tested yet), but I have to slice it somewhere. These builders are intended for the join operator, letting us build arrays by gathering from other arrays, amortizing the allocation. I intend to expand them to more uses, and replace other parts of the code with them (such as the last remaining uses of the `Growable`).

refactor(rust): Add ArrayBuilders

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

Closes https://github.com/pola-rs/polars/issues/21464

docs(python): Specify that the key column must be sorted in ascending order in `merge_sorted`

---

crates/polars-compute/src/rolling/no_nulls/variance.rs
crates/polars-compute/src/rolling/nulls/variance.rs
crates/polars-compute/src/var_cov.rs
crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs
py-polars/tests/unit/operations/rolling/test_rolling.py

feat: Improve numeric stability `rolling_{std, var, cov, corr}`

---

crates/polars-lazy/src/frame/mod.rs
crates/polars-ops/src/frame/join/args.rs
crates/polars-ops/src/frame/join/dispatch_left_right.rs
crates/polars-ops/src/frame/join/hash_join/mod.rs
crates/polars-ops/src/frame/join/hash_join/single_keys.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_inner.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_left.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_outer.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_semi_anti.rs
crates/polars-ops/src/frame/join/hash_join/sort_merge.rs
crates/polars-ops/src/frame/join/mod.rs
crates/polars-ops/src/series/ops/replace.rs
crates/polars-pipe/src/executors/sinks/joins/generic_build.rs
crates/polars-pipe/src/executors/sinks/joins/generic_probe_inner_left.rs
crates/polars-pipe/src/executors/sinks/joins/generic_probe_outer.rs
crates/polars-pipe/src/executors/sinks/joins/row_values.rs
crates/polars-pipe/src/pipeline/convert.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-python/src/lazyframe/visitor/nodes.rs
crates/polars-sql/src/context.rs
crates/polars-stream/src/nodes/joins/equi_join.rs
crates/polars-stream/src/physical_plan/fmt.rs
docs/source/releases/upgrade/0.20.md
py-polars/polars/dataframe/frame.py
py-polars/polars/functions/eager.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/sql/test_joins.py
py-polars/tests/unit/streaming/test_streaming_join.py

As per [Ritchie's request](https://github.com/pola-rs/polars/pull/21426#issuecomment-2687842500), this brings more consistency to the parameter.
I kept the `join_nulls` function the same name since in that case it's a verb and it makes sense, but as a parameter name it was a simple rename.

chore: Rename 'join_nulls' parameter to 'nulls_equal' in join functions

---

crates/polars-expr/src/expressions/apply.rs
crates/polars-lazy/src/tests/io.rs
crates/polars-lazy/src/tests/predicate_queries.rs
crates/polars-lazy/src/tests/queries.rs
crates/polars-ops/src/series/ops/is_in.rs
crates/polars-ops/src/series/ops/replace.rs
crates/polars-plan/src/dsl/function_expr/array.rs
crates/polars-plan/src/dsl/function_expr/binary.rs
crates/polars-plan/src/dsl/function_expr/boolean.rs
crates/polars-plan/src/dsl/function_expr/list.rs
crates/polars-plan/src/dsl/mod.rs
crates/polars-plan/src/plans/aexpr/predicates/skip_batches.rs
crates/polars-plan/src/plans/aexpr/properties.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
crates/polars-plan/src/plans/python/pyarrow.rs
crates/polars-python/src/expr/general.rs
crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
crates/polars-sql/src/sql_expr.rs
crates/polars/tests/it/lazy/expressions/is_in.rs
crates/polars/tests/it/lazy/predicate_queries.rs
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/tests/unit/operations/test_is_in.py

Closes #12591.
**Edit**: after some discussion, the argument has been renamed from `missing` to ~`propagate_nulls`~ `nulls_equal` and it defaults to True.
---
#18728 had much more discussion but was closed as a duplicate. This solves the problem of `filter(~col("a").is_in(exclusion_list))` silently passing all nulls through the filter, which has been a pretty big source of error for me, at least.
This now gives `is_in` the ability to use `eq_missing`/`ne_missing` logic in order to treat null as a distinct value:
```python
pl.Series([1, 2, None]).is_in([1, 3])
shape: (3,)
Series: '' [bool]
[
true
false
null
]
pl.Series([1, 2, None]).is_in([1, 3], nulls_equal=True)
shape: (3,)
Series: '' [bool]
[
true
false
false
]
pl.Series([1, 2, None]).is_in([1, None], …
```

feat: Add 'nulls_equal' parameter to `is_in`

---

Cargo.lock
crates/polars/src/lib.rs
py-polars/Cargo.toml
py-polars/src/allocator.rs

The [jemallocator](https://crates.io/crates/jemallocator) crate mentions to use `tikv-jemallocator` instead which is otherwise identical.

chore: Use tikv-jemallocator

---

crates/polars-error/src/lib.rs
crates/polars-python/src/error.rs
crates/polars-python/src/exceptions.rs

This PR is regarding comments from @coastalwhite on this PR: https://github.com/pola-rs/polars/pull/21460# and from Discord regarding using pyo3's built in `AssertionError` and using the macro for more general assertions. 
Previous PR relates to issue: https://github.com/pola-rs/polars/issues/21388#.
- In `polars-error/lib.rs`, the macro has been updated to be more generalize and also match the already existing Python assertion error.
- In `error.rs`, `PolarsError::AssertionError` has been mapped to `PyAssertionError` rather than making a new exception.
- In `exceptions.rs`, the `create_exception_macro!()` has been removed for `AssertionError` since it will be relying on pyo3's existing implementation.

refactor(rust): Map Polars `AssertionError` to pyo3's `AssertionError` and improve macro flexibility

---

py-polars/polars/dataframe/plotting.py
py-polars/polars/expr/datetime.py
py-polars/polars/expr/expr.py
py-polars/polars/functions/eager.py
py-polars/polars/functions/escape_regex.py
py-polars/polars/functions/lazy.py
py-polars/polars/interchange/dataframe.py
py-polars/polars/ml/torch.py
py-polars/polars/testing/asserts/frame.py
py-polars/polars/testing/asserts/series.py

Does not resolve a specific issue. Just some light maintenance to fix typos and adjust grammar in some doc strings. No functional changes to the code base. 
For `py-polars/polars/interchange/dataframe.py`, the parameter was named `column` but it refers to a Polars DataFrame in the description, so it was changed to `df`.

docs(python): Correct typos and grammar in Python docstrings

---

crates/polars-core/src/chunked_array/ops/aggregate/mod.rs
py-polars/tests/unit/datatypes/test_categorical.py

Fixes the following panic:
```python
pl.enable_string_cache()
pl.Series(["a", "b"], dtype=pl.Categorical()).min()
```

fix: Categorical min/max panicking when string cache is enabled

---

crates/polars-stream/src/nodes/io_sources/csv.rs
crates/polars-stream/src/nodes/io_sources/ipc.rs
crates/polars-stream/src/nodes/io_sources/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_scan.rs
crates/polars-stream/src/nodes/io_sources/parquet/mod.rs
crates/polars-stream/src/nodes/negative_slice.rs
py-polars/tests/unit/operations/test_slice.py

Instead of an atomic integer, this ensures we explicitly block until the source has sent the final row count.
Also fixes a panic in new-streaming negative slice on empty morsel inputs.

refactor(rust): Use a oneshot channel for `unrestricted_row_count`, fix panic in new-streaming negative slice

---

py-polars/polars/io/cloud/credential_provider/_builder.py

* Fixes https://github.com/pola-rs/polars/issues/13138
* Fixes https://github.com/pola-rs/polars/issues/21417
```python
scan_parquet(..., storage_options = { 'token': '...' })
```

feat(python): Support passing `token` in `storage_options` for GCP cloud

---

crates/polars-io/src/parquet/read/read_impl.rs
crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs
crates/polars-lazy/src/scan/ndjson.rs
crates/polars-lazy/src/tests/io.rs
crates/polars-lazy/src/tests/optimization_checks.rs
crates/polars-mem-engine/src/executors/multi_file_scan.rs
crates/polars-mem-engine/src/executors/scan/csv.rs
crates/polars-mem-engine/src/executors/scan/ipc.rs
crates/polars-mem-engine/src/executors/scan/mod.rs
crates/polars-mem-engine/src/executors/scan/ndjson.rs
crates/polars-mem-engine/src/executors/scan/parquet.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-pipe/src/executors/sources/csv.rs
crates/polars-pipe/src/executors/sources/parquet.rs
crates/polars-plan/src/dsl/builder_dsl.rs
crates/polars-plan/src/dsl/options.rs
crates/polars-plan/src/plans/ir/format.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
crates/polars-python/src/lazyframe/visitor/nodes.rs
crates/polars-stream/src/nodes/io_sources/csv.rs
crates/polars-stream/src/nodes/io_sources/ipc.rs
crates/polars-stream/src/nodes/io_sources/parquet/init.rs
crates/polars-stream/src/nodes/io_sources/parquet/metadata_fetch.rs
crates/polars-stream/src/nodes/io_sources/parquet/mod.rs
crates/polars-stream/src/physical_plan/fmt.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/to_graph.rs

Made also clear that the slice is a `pre_slice`. Meaning pre-predicate.
fixes #21558

fix: Don't hit parquet::pre-filtered in case of pre-slice

---

crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs
py-polars/tests/unit/io/test_parquet.py

Fix the null handling in `ParquetColumnExpr` and apply dictionaries to ensure no panics occur.
Fixes #21538.

fix: Several aspects related to ParquetColumnExpr

---

crates/polars-mem-engine/src/executors/group_by_dynamic.rs
crates/polars-mem-engine/src/executors/group_by_rolling.rs
crates/polars-time/src/group_by/dynamic.rs

perf: Pre-sort groups in group-by-dynamic

---

crates/polars-lazy/src/frame/mod.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-pipe/src/pipeline/convert.rs
crates/polars-plan/src/dsl/options.rs
crates/polars-plan/src/dsl/plan.rs
crates/polars-plan/src/plans/ir/dot.rs
crates/polars-plan/src/plans/ir/format.rs
crates/polars-plan/src/plans/ir/schema.rs
crates/polars-plan/src/plans/ir/tree_format.rs
crates/polars-python/src/functions/mod.rs
crates/polars-python/src/functions/partitioning.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-stream/src/physical_plan/fmt.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/polars/io/partition.py
py-polars/polars/lazyframe/frame.py
py-polars/src/lib.rs
py-polars/tests/unit/streaming/test_streaming_io.py

This adds a generic `SinkType::Partition` that can (now still invisibly) be called from Python.
```python
from polars.io.partition import MaxSizePartitioning
import os
os.environ['POLARS_FORCE_NEW_STREAMING'] = '1'
lf = pl.LazyFrame(
{
"a": list(range(8)),
"b": [5, 10, 1996, 13, 37, 42, 00, 1],
}
)
lf.sink_ipc(MaxSizePartitioning("{part}.ipc", max_size=1))
```

refactor: Prepare skeleton for partitioning sinks

---

crates/polars-expr/src/state/execution_state.rs
crates/polars-expr/src/state/node_timer.rs
crates/polars-lazy/src/frame/exitable.rs
crates/polars-lazy/src/frame/mod.rs
crates/polars-mem-engine/src/executors/scan/python_scan.rs
crates/polars-python/src/lazyframe/general.rs
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/lazyframe/cuda/test_node_visitor.py

So that we can support the GPU engine in profiled collection of a lazyframe, plumb through a mechanism for recording raw timings for nodes that were executed through the PythonScan node.
This necessitates some small changes to the internals of the NodeTimer, since `Instant`s are opaque. We instead directly store durations (as nanoseconds since the query start) and when calling into the IR post-optimization callback, provide a duration that is the number of nanoseconds since the query was started. On the Python side we can then keep track and record durations independently, offsetted by this optimisation duration.
As a side-effect, `profile` now correctly measures the optimisation time in the logical plan, rather than as previously just the time to produce the physical plan from the …

feat(python,rust): Support engine callback for `LazyFrame.profile`

---

crates/polars-core/src/datatypes/dtype.rs

This existed in the Python testing infrastructure and needed to be migrated to Rust in preparation for moving `assert_series_equal()` and `assert_dataframe_equal()` to Rust. The goal was to create a function that unpacks the data types from nested structures and also allows for inclusion/exclusion of compound types (List, Array, Struct). 
Note: I didn't see any extensive doc strings in the `dtype.rs` file, so I just followed the same convention. If needed, they can be easily added.
It is related to this issue: https://github.com/pola-rs/polars/issues/21388
Tagging @coastalwhite since he is overlooking my work on transferring this functionality to Rust.

feat(rust): Implement `unpack_dtypes()` functionality with unit tests

---

crates/polars-arrow/src/array/binview/builder.rs
crates/polars-arrow/src/array/boolean/builder.rs
crates/polars-arrow/src/array/builder.rs
crates/polars-arrow/src/array/fixed_size_binary/builder.rs
crates/polars-arrow/src/array/fixed_size_list/builder.rs
crates/polars-arrow/src/array/list/builder.rs
crates/polars-arrow/src/array/null.rs
crates/polars-arrow/src/array/primitive/builder.rs
crates/polars-arrow/src/array/struct_/builder.rs
crates/polars-core/src/frame/builder.rs
crates/polars-core/src/series/builder.rs

This should avoid some extra overhead from repeatedly making builders.

refactor(rust): Add freeze_reset to the builders

---

docs/source/requirements.txt
docs/source/src/python/user-guide/misc/visualization.py
docs/source/user-guide/misc/visualization.md

This PR adds `Plotnine` to the visualization docs.

docs(python): Add a `Plotnine` example to the visualization docs

---

crates/polars-io/src/mmap.rs
crates/polars-io/src/utils/file.rs
crates/polars-pipe/src/executors/sinks/output/parquet.rs
crates/polars-python/src/conversion/mod.rs
crates/polars-python/src/dataframe/io.rs
crates/polars-python/src/file.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-utils/src/file.rs
crates/polars-utils/src/lib.rs

feat: Closeable files on unix

---

crates/polars-core/src/frame/chunks.rs

This might be a case of fixing symptoms however, we may need to take a harder look at aligning chunks and what that means in the context of non-series `Column`s.
Fixes https://github.com/pola-rs/polars/issues/21581.

fix: Take into account scalar/partitioned columns in DataFrame::split_chunks

---

crates/polars-io/src/cloud/adaptors.rs
crates/polars-io/src/utils/file.rs

Prepares for cloud support on new-streaming
~~Also implements `AsyncWrite` onto the `CloudWriter`.~~
A `Writeable` can generally be directly used for writing:
It can be `Deref`ed if a trait object is needed:
(similarly with `AsyncWriteable`)

refactor(rust): Introduce `Writeable` and `AsyncWriteable`

---

crates/polars-ops/src/chunked_array/array/namespace.rs
crates/polars-plan/src/dsl/array.rs
crates/polars-plan/src/dsl/function_expr/array.rs
crates/polars-python/src/expr/array.rs
py-polars/polars/expr/array.py
py-polars/polars/series/array.py
py-polars/tests/unit/operations/namespaces/array/test_array.py

I did a bit of an oopsie on the original PR #21513. I cannot seem to get that one back. Here it is again.

feat: Add len method to arr

---

crates/polars-plan/src/dsl/scan_sources.rs
crates/polars-python/src/lazyframe/sink.rs
crates/polars-stream/src/nodes/io_sinks/csv.rs
crates/polars-stream/src/nodes/io_sinks/ipc.rs
crates/polars-stream/src/nodes/io_sinks/json.rs
crates/polars-stream/src/nodes/io_sinks/parquet.rs
crates/polars-stream/src/nodes/io_sinks/partition/mod.rs
crates/polars-stream/src/nodes/io_sources/csv.rs
crates/polars-stream/src/nodes/io_sources/ipc.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/polars/io/cloud/_utils.py
py-polars/polars/io/partition.py

Enables cloud support for all scan and sink functions on new-streaming, including `PartitionMaxSize`.
Note that currently if any errors occur in writing they are silently ignored (there is a fix for this at  https://github.com/pola-rs/polars/pull/21589/files#diff-744a743b5337b77c8e26e0efabdfe8410bfd77e3d1e55ffa54eb0f29cc51e33bR1177)

feat: Cloud support for new-streaming scans and sinks

---

.typos.toml
py-polars/polars/_utils/nest_asyncio.py
py-polars/polars/io/database/_utils.py
py-polars/tests/unit/io/database/test_async.py

* ~~Reverts https://github.com/pola-rs/polars/pull/20793~~
* ref https://github.com/pola-rs/polars/issues/21263
* I don't have a local repro but this should fix

fix: Fix`Future attached to different loop` error on `read_database_uri`

---

crates/polars-core/src/chunked_array/struct_/mod.rs
py-polars/tests/unit/datatypes/test_struct.py

fix: Casting Struct to String panics if n_chunks > 1

---

crates/polars-ops/src/frame/join/mod.rs
py-polars/tests/unit/operations/test_join_right.py

fixes #20670
fixes #20671
Right join on multiple columns where `left_on` and `right_on` names do not match was failing to coalesce the `left_on` columns. The lazy schema was already producing the correct behavior.
```python
left = pl.LazyFrame({"a": [1, 2], "b": [1, 2]})
right = pl.LazyFrame({"c": [1, 2], "d": [1, 2]})
print(
left.join(right, left_on=["a", "b"], right_on=["c", "d"], how="left").collect()
)
print(
left.join(right, left_on=["a", "b"], right_on=["c", "d"], how="right").collect()
)
```

fix: Right join on multiple columns not coalescing left_on columns

---

crates/polars-stream/src/nodes/group_by.rs
py-polars/tests/unit/operations/unique/test_unique.py

Fixes https://github.com/pola-rs/polars/issues/21654.
We didn't hit this case in the CI because we run with `POLARS_MAX_THREADS=4` which makes it impossible to hit this case. I added a test case nevertheless.
It was hard to hit in general, you needed a combination of small morsel sizes and small input size. In most cases the number of partitions was equal to the number of local groupers.

fix: Incorrect loop length in new-streaming group by

---

.typos.toml

Workaround for https://github.com/crate-ci/typos/issues/593, `typos` doesn't work properly with exclude paths if run from a subdirectory (like `make precommit` from `py-polars` does right now).

chore: Work around typos ignore bug

---

crates/polars-compute/src/rolling/no_nulls/sum.rs
crates/polars-compute/src/rolling/nulls/sum.rs

@ritchie46 Just happened to spot these, the Rust compiler can't optimize Kahan summation out even without the black box, that would be semantics-changing optimizations. And `std::hint::black_box` isn't free, it actually forcibly writes the value to the stack and reads it back.

perf: Remove unnecessary black_boxes in Kahan summation

---

crates/polars-lazy/src/frame/python.rs
crates/polars-mem-engine/src/executors/scan/python_scan.rs
crates/polars-plan/src/dsl/python_dsl/source.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/python/source.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-python/src/lazyframe/visit.rs
py-polars/docs/source/reference/functions.rst
py-polars/polars/__init__.py
py-polars/polars/io/__init__.py
py-polars/polars/io/plugins.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/io/test_io_plugin.py

This defers `DataFrame` execution until `collect` is called. This can enable more parallelism if the plan is executed bushy (the in memory engine is), and the DataFrame producer releases the gil (numpy does).
This also enables `DataFrame`s to be constructed remotely in Polars Cloud. Hereby enabling eager sources to be read remotely.

 feat: Add `pl.defer`, a function that defers DataFrame construction. 

---

crates/polars-arrow/src/ffi/schema.rs

closes #21661
Still doesn't solve that snippet as pycapsule now assumes dataframes, not arrays.

feat: Support Polars int128 in from arrow

---

crates/polars-arrow/src/compute/concatenate.rs
crates/polars-arrow/src/io/ipc/write/common.rs
py-polars/tests/unit/io/test_ipc.py

fix: IPC round-trip of list of empty view with non-empty bufferset

---

crates/polars-core/src/series/implementations/array.rs
crates/polars-core/src/series/implementations/binary.rs
crates/polars-core/src/series/implementations/binary_offset.rs
crates/polars-core/src/series/implementations/boolean.rs
crates/polars-core/src/series/implementations/categorical.rs
crates/polars-core/src/series/implementations/date.rs
crates/polars-core/src/series/implementations/datetime.rs
crates/polars-core/src/series/implementations/decimal.rs
crates/polars-core/src/series/implementations/duration.rs
crates/polars-core/src/series/implementations/floats.rs
crates/polars-core/src/series/implementations/list.rs
crates/polars-core/src/series/implementations/mod.rs
crates/polars-core/src/series/implementations/null.rs
crates/polars-core/src/series/implementations/object.rs
crates/polars-core/src/series/implementations/string.rs
crates/polars-core/src/series/implementations/struct_.rs
crates/polars-core/src/series/implementations/time.rs
crates/polars-core/src/series/series_trait.rs

This lets us directly downcast from `Series` to the underlying physical `ChunkedArray` without needing to create a new `Series` with `to_physical_repr`.

refactor: Add as_phys_any to PrivateSeries for downcasting

---

crates/polars-core/src/datatypes/mod.rs
crates/polars-expr/src/hash_keys.rs
crates/polars-expr/src/idx_table/mod.rs
crates/polars-expr/src/idx_table/single_key.rs
crates/polars-plan/src/plans/expr_ir.rs
crates/polars-stream/src/nodes/joins/equi_join.rs
crates/polars-stream/src/physical_plan/to_graph.rs
crates/polars-utils/src/idx_map/mod.rs
crates/polars-utils/src/idx_map/total_idx_map.rs
crates/polars-utils/src/total_ord.rs
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/operations/test_join_right.py

Before this PR everything always went through the row-encoding in the new-streaming join, even for small single keys. This adds a single-key hashtable for the primitive types (or those logical types backed by primitive types). Not yet included is single-key string support, that still goes through the row encoding.

perf: Add primitive single-key hashtable to new-streaming join

---

crates/polars-core/src/series/mod.rs
py-polars/tests/unit/datatypes/test_enum.py
py-polars/tests/unit/operations/test_cast.py

Fixes #14665.
Old behavior allowed any cast of all-null arrays to any dtype, but empty Enums should not be allowed:
```python
pl.Series([]).cast(pl.Enum)  # works, but should not
```

fix: Disallow cast to empty Enum

---

crates/polars-io/src/csv/read/options.rs
crates/polars-lazy/src/scan/csv.rs
docs/source/src/rust/user-guide/getting-started.rs
docs/source/user-guide/transformations/time-series/parsing.md

This PR resolves #21298.
Context: the user guide getting started section has sample code that is inconsistent between Python and Rust. The Rust code sample sets 'infer_schema_length' to None, triggering a full table scan using computationally intensive schema inference logic. The Python code uses the default of 100 rows. Therefore, the Rust code has significant negative performance degradation when used on large tables.
Proposed changes:
- Make the user guide getting started code consistent between Python and Rust, switching to the default value.
- Document the performance risk in the user guide transformations/time-series/parsing/ section.
- Make the Rust reference method documentation for 'with_infer_schema_length' consistent and clear across the different implementations.

docs: Make python/rust getting-started consistent and clarify performance risk of infer_schema_length=None

---

crates/polars-expr/src/expressions/aggregation.rs
crates/polars-expr/src/planner.rs

Fixes #21325.
Currently, for aggregations, polars takes the wrong path when `allow_threading` is false, and tries to multithread with only one thread. Conversely, it *never* multithreads when `allow_threading` is true. This PR fixes this.
Once this path is enabled, we have to disable multithreading for categorical min/max, as the multithreaded path is the one that causes problems in the linked issue. The current algorithm `slice`s categorical columns into separate components and computes `min/max` on each, and in the process (I think) a new revmap is computed for each slice and results in the wrong result, or for some other reason (the proper min physical isn't returned in each sub-slice). So I have disabled multithreading in the IR planner--let me know if this is the proper place to do …

fix: Incorrect multithread path taken for aggregations

---

crates/polars-ops/src/frame/join/asof/groups.rs
crates/polars-ops/src/frame/join/asof/mod.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/operations/test_join_asof.py

Closes #21693.
When `join_asof` is called with `by` groups, the requirement for sortedness is that the `on` column is sorted within each group. The current behavior issues a warning if the entire column is not sorted, which is not really desirable, as this means warnings will be issued in almost every case where `by` is used (since often the data is sourced first by the group, then by the `on` column).
Instead, since it is currently too expensive to check sortedness on each group individually, we should simply raise a warning that we cannot check for sortedness when `by` groups are provided. Here is the new behavior:
```python
df = pl.DataFrame({"a": [1, 1, 1, 2, 2, 2], "b": [2, 1, 3, 1, 2, 3]})
df.join_asof(df, on="b")  # no by specified
df.join_asof(df, on="b", …
```

fix: Don't check sortedness in `join_asof` when 'by' groups supplied, but issue warning

---

crates/polars-core/src/fmt.rs
crates/polars-ops/src/chunked_array/strings/concat.rs
crates/polars-plan/src/dsl/function_expr/strings.rs
crates/polars-plan/src/dsl/list.rs
crates/polars-plan/src/dsl/mod.rs
crates/polars-plan/src/dsl/string.rs
crates/polars-plan/src/plans/aexpr/properties.rs
crates/polars-plan/src/plans/options.rs
crates/polars-plan/src/utils.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-stream/src/physical_plan/lower_group_by.rs
py-polars/tests/unit/operations/namespaces/string/test_pad.py
py-polars/tests/unit/operations/namespaces/string/test_string.py
py-polars/tests/unit/sql/test_group_by.py
py-polars/tests/unit/streaming/test_streaming.py

In the new streaming engine we already allowed elementwise functions in completely elementwise expressions, but this also allows us to lower elementwise functions applied to non-elementwise subexpressions without having to defer entirely to an in-memory map. For example `pl.col.x.sum().abs()` is now completely lowered to native new-streaming operations.

perf: Allow elementwise functions in recursive lowering

---

crates/polars-python/src/interop/arrow/to_rust.rs
py-polars/polars/selectors.py
py-polars/tests/unit/interop/test_interop.py

Closes #20700 (and its duplicate: #20849).
This is a conservative fix, targeting (for now) _only_ Arrow `Field` dtypes with recognised BigQuery metadata. I currently have access to a BigQuery instance to test on, so can confirm that the fix works well (and I was able to replicate/mock the issue with some new unit tests that don't require BigQuery access to run).
#20248 ensured that we do not drop the `Field`-associated metadata... https://github.com/pola-rs/polars/blob/5ce00116a9cc44803fc123957219e73d78610760/py-polars/polars/_utils/construction/dataframe.py#L1167-L1168 
...on DataFrame init, but also caused a regression where we now raise errors on init from common BigQuery Arrow data.
It's not entirely clear to me what sort of metadata we do want/expect to support, so this PR introduces …

fix: Allow init from BigQuery Arrow data containing ExtensionType cols with irrelevant metadata

---

crates/polars-compute/src/var_cov.rs
py-polars/tests/unit/operations/test_rolling.py

Fixes https://github.com/pola-rs/polars/issues/21758.

fix: Clear NaNs due to zero-weight division in rolling var/std

---

crates/polars-stream/src/expression.rs
crates/polars-stream/src/nodes/input_independent_select.rs

This used to just send one (possibly giant) morsel which inhibits parallelism down the line.

perf: Improve InputIndependentSelect by delegating to InMemorySourceNode

---

crates/polars-arrow/src/bitmap/immutable.rs
crates/polars-arrow/src/storage.rs

This should improve efficiency of empty `new()` calls down the line as well since `SharedStorage` won't allocate in this case anymore.

refactor(rust): Add allocation-free empty/default to SharedStorage

---

crates/polars-ops/src/series/ops/business.rs

`holidays` gets sorted by `normalise_holidays`, so `binary_search` can replace `contains`

perf: Use binary_search instead of contains in business-day functions

---

Cargo.lock
crates/Makefile
crates/polars-testing/Cargo.toml
crates/polars-testing/LICENSE
crates/polars-testing/README.md
crates/polars-testing/src/asserts/mod.rs
crates/polars-testing/src/asserts/series.rs
crates/polars-testing/src/asserts/utils.rs
crates/polars-testing/src/lib.rs

Tagging @coastalwhite since he is overseeing my work on transferring testing utilities from Python to Rust.
Resolves the first major part of this issue: https://github.com/pola-rs/polars/issues/21388
All unit tests pass. Tried to provide extensive coverage of scenarios, many of which are covered in the Python version, but some which are not.
Documentation has not been added yet due to the size of the PR. I am anticipating some comments and I have provided some in-line comments regarding some changes/improvements I implemented at that specific, so to make it easier to go through for Gijs and any other reviewers.
I will remove those comments once they have been addressed and add proper documentation either through an update to the commit or a new branch, depending on what happens.

feat(rust): Add `polars_testing` folder with relevant files and `add_series_equal!()` functionality

---

crates/polars-utils/src/lib.rs
crates/polars-utils/src/slice_enum.rs

Introduces a slice enum with explicitly named fields to avoid confusion.
Will be used initially in the new-streaming multi file refactor, and can also be added later to e.g. the DSL if we want.

refactor(rust): Add a slice enum to polars-utils

---

crates/polars-arrow/src/bitmap/immutable.rs
crates/polars-arrow/src/storage.rs

Fixes https://github.com/pola-rs/polars/issues/21732.
We leaked a small amount of memory every time one of two things happens:
1. `SharedStorage::from_static` was called.
2. `SharedStorage::try_into_vec`/`SharedStorage::try_take_vec` was called.
In both cases the cause is very similar: they would set the `backing_storage` to `None`. A side-effect of this is that this would disable refcounting, which was intended for eternally-leaked `SharedStorage`s, but would incorrectly leak the `SharedStorageInner` here.
In both cases the amount of leaked memory was only 48 bytes, but this could be amplified quite significantly due to causing extra fragmentation.

fix: Memory leaks in SharedStorage

---

py-polars/polars/plugins.py
py-polars/tests/unit/test_plugins.py

https://github.com/pola-rs/polars/issues/21643 
Add a `use_relpath` parameter to `register_plugin_function` that allows storing plugin paths relative to the virtual environment instead of absolute paths.

fix(python): Add option to use relative paths for plugin libraries

---

crates/polars-stream/src/async_primitives/mod.rs
crates/polars-stream/src/async_primitives/morsel_linearizer.rs

Makes it so that we can type:
* `linearizer: MorselLinearizer` instead of `Linearizer<Priority<Reverse<MorselSeq>, Morsel>>)`
* `.insert(morsel)` instead of `.insert(Priority(Reverse(morsel.seq()), morsel))`
@orlp

refactor(rust): Add MorselLinearizer convenience wrapper

---

crates/polars-plan/src/plans/ir/format.rs
py-polars/tests/unit/io/test_lazy_csv.py
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/test_predicates.py

A small indent fix, and a minor readability improvement:
* The `explain` formatting had some hardcoded `"\t"` chars which should instead have been the calculated `sub_indent`, leading to misaligned `GroupBy` plan output.
* Fixed this, and assigned an `indent_increment` var so we don't have a magic const (`2`) determining indent growth with increasing depth :)
*  Put `FROM` on a standalone line to improve readability; it was too easily lost at the end of even just a handful of columns/expressions, and it's quite an important marker.
```python
"key": ["xx", "yy", "zz", "xx", "zz", "zz"],
"v1": [15, 25, 10, 20, 20, 20],
"v2": [-33, 20, 44, -2, 16, 71],
}).group_by(
pl.col("key"),
).agg(pl.col("v1","v2").sum())
print(lf.explain())
```
_(rogue `"\t"` …

feat: Minor improvements to EXPLAIN plan output

---

crates/polars-io/src/csv/read/schema_inference.rs

Fixes https://github.com/pola-rs/polars/issues/21823.

fix: Incorrect quote check in CSV parser

---

crates/polars-core/src/chunked_array/logical/categorical/mod.rs

Added a missing DoubleEndedIterator implementation for CatIter.

feat(rust): Add DoubleEndedIterator for CatIter

---

crates/polars-core/src/frame/column/mod.rs
crates/polars-core/src/frame/mod.rs
crates/polars-stream/src/nodes/io_sources/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/apply.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/cast_columns.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/missing_columns.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/reorder_columns.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_scan.rs

Modules for e.g. attaching missing columns, hive columns, and in the future type casting. Note that nothing is hooked up yet.
@coastalwhite

refactor(rust): Add ops components for refactored multiscan

---

crates/polars-stream/src/nodes/joins/equi_join.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/lazyframe/test_lazyframe.py
py-polars/tests/unit/lazyframe/test_optimizations.py
py-polars/tests/unit/operations/test_is_sorted.py
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/operations/test_join_right.py
py-polars/tests/unit/streaming/test_streaming_join.py
py-polars/tests/unit/test_cse.py
py-polars/tests/unit/test_projections.py

For joins that expand a lot due to many matches the strict requirements of the linearizer made us mostly single-threaded. For unordered joins it now relabels the morsel sequence ids to mitigate that, but for a proper solution we should use unordered linearizers to 'linearize' unordered streams.

perf: Improve join performance for expanding joins

---

.cargo/config.toml
py-polars/Cargo.toml
py-polars/polars/__init__.py
py-polars/src/allocator.rs

If a system supports THP (transparent huge pages) but has it set by default to only use it when `madvise` is called (which is the default on for example Ubuntu server), then we wouldn't use THP before this PR. This PR ensures that jemalloc will `madvise` every allocation with `MADV_HUGEPAGE` so that they will be used on such systems.
On PDS-H SF=10 and SF=100 I observed performance increases of 15-20% with the new streaming engine. I expect THP to pretty much always be beneficial for Polars unless we start swapping memory in random access patterns (but arguably when you reach that point you have already lost as an OLAP system).
If for whatever reason you find THP to be a regression, please do let us know, in the meantime you can specify the env variable …

perf: Enable THP by default

---

py-polars/polars/__init__.py

This is a partial revert of https://github.com/pola-rs/polars/pull/21829.
We saw a big regression on some systems that needs further investigation. For now I've added the convenience environment variable `POLARS_THP=1` that you can use to enable THP, even if we may switch allocator.

perf: Put THP behind feature flag

---

crates/polars-core/src/chunked_array/ops/gather.rs

This was rather expensive in the in-memory groupby, which does a random sample of `sqrt(n)` which rechunked the entire array.

perf: Avoid rechunking in gather

---

Cargo.lock
crates/polars-arrow/src/array/binview/mod.rs
crates/polars-arrow/src/array/binview/mutable.rs
crates/polars-arrow/src/array/binview/view.rs
crates/polars-arrow/src/array/mod.rs
crates/polars-arrow/src/buffer/immutable.rs
crates/polars-compute/Cargo.toml
crates/polars-compute/src/binview_index_map.rs
crates/polars-compute/src/lib.rs
crates/polars-expr/src/hash_keys.rs
crates/polars-expr/src/idx_table/binview.rs
crates/polars-expr/src/idx_table/mod.rs
crates/polars-expr/src/idx_table/row_encoded.rs

Around a ~30% speedup on this microbenchmark:
```python
import timeit
df = pl.DataFrame({"x": pl.int_range(10_000_000, eager=True).cast(pl.String)})
print(timeit.timeit(lambda: df.lazy().join(df.lazy(), on="x").collect(engine="streaming"), number=10) / 10)
```

perf: Use views for binary hash tables and add single-key binary variant

---

py-polars/tests/unit/dataframe/test_df.py

I upgraded my pytest version and noted they added magic to the `assert` which prints its arguments. But this adds extra reference counts, failing this test.

chore: Fix refcount assert being messed up by pytest assertion magic

---

.github/workflows/benchmark.yml
.github/workflows/test-coverage.yml
.github/workflows/test-python.yml
py-polars/Makefile

This is a bit of an experimental PR. We added `--dist loadgroup` [~1.5 years ago](https://github.com/pola-rs/polars/pull/10469) as a bit of a hack to deal with some flaky tests. However, it seems `--dist loadgroup` is a bit buggy (https://github.com/pytest-dev/pytest-xdist/issues/1189) leading to pytest INTERNAL ERRORs when the Python process isn't exited cleanly, and honestly... we should probably fix whatever tests fail 'because they are ran in the same runner' properly, as that's not a proper excuse for why a test should be allowed to fail.
So let's see how bad the damage is from just turning it off in this PR.

chore: Disable --dist loadgroup in pytest

---

Cargo.lock
crates/polars-stream/Cargo.toml
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/apply.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/cast_columns.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/missing_columns.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/builder.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/capabilities.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/mod.rs
crates/polars-utils/src/slice_enum.rs

ref https://github.com/pola-rs/polars/pull/21839#discussion_r2002959813
This will allow us to push operations into external IO implementations in a much more generic way.
Also adds `Slice::end_position()`, `Slice::restrict_to_bounds()` and some other drive-bys.
@coastalwhite

refactor(rust): Remove `FileType` in favor of `ReaderCapabilities` for new-streaming multiscan

---

.github/workflows/benchmark.yml
.github/workflows/test-coverage.yml
.github/workflows/test-python.yml
crates/polars-python/src/lib.rs
crates/polars-python/src/timeout.rs
crates/polars-python/src/utils.rs
py-polars/Makefile

This adds the environment variable `POLARS_TIMEOUT_MS` that when set will cause any call to any Polars function automatically exit the process with an error if the function still isn't finished after that many milliseconds has passed. This is useful for figuring out with `pytest` which test is hanging, if any.
I've also turned it on in the CI and Makefile when testing, defaulting to 60 seconds. This may need to be raised, we'll see.
If the environment variable `POLARS_TIMEOUT_MS` is not set when the first call to a Polars function is made, the mechanic is disabled entirely for performance.

chore: Add POLARS_TIMEOUT_MS for timing out slow Polars tests

---

crates/polars-ops/src/frame/pivot/mod.rs
py-polars/tests/unit/operations/test_pivot.py

fix: Allow `pivot` on empty frame for all integer index dtypes

---

py-polars/polars/plugins.py

In the current state plugins don't work, because `dlopen` searches for relative paths with respect to the current directory, which is usually not the same as the virtual env root directory (and in general I don't think we should assume something about what the current working directory is).
For now I changed the default of `use_abs_path` to `True` as a quick bugfix, maybe there is a way to solve it using some `dlopen` tricks (some smart usage of `LD_LIBRARY_PATH` or such?), but I couldn't get it to work.

fix(python): Use absolute paths by defaults for plugins

---

crates/polars-core/src/series/implementations/string.rs
py-polars/polars/expr/string.py
py-polars/tests/unit/expr/test_exprs.py

fix(python): Add correct deprecation warning for .str.concat

---

docs/source/polars-cloud/run/compute-context.md
docs/source/polars-cloud/run/interactive-batch.md
docs/source/polars-cloud/run/workflow.md
docs/source/polars-cloud/workspace/settings.md
docs/source/src/python/polars-cloud/index.py
docs/source/src/python/polars-cloud/interactive-batch.py

Reflect recent changes in the Polars Cloud API in the Polars Cloud user guide.
When setting a compute context in the upcoming version that is released, users must do so with `.remote(context=ctx)` instead of `.remote(ctx)`.

docs: Change ctx to compute=ctx for all remote query examples

---

crates/polars-utils/src/cache.rs

Fixes https://github.com/pola-rs/polars/issues/21934.
I had forgotten hash tables can rehash under churn even when not exceeding max capacity.

fix: Panic in new RegexCache

---

crates/polars-stream/src/nodes/filter.rs
crates/polars-stream/src/nodes/in_memory_source.rs
crates/polars-stream/src/nodes/io_sinks/partition/parted.rs
crates/polars-stream/src/nodes/io_sources/ndjson/negative_slice_pass.rs
crates/polars-stream/src/nodes/merge_sorted.rs
crates/polars-stream/src/nodes/streaming_slice.rs

This replaces use of `df.is_empty()` with `df.height() == 0` in new streaming nodes - `is_empty()` would always return true on 0-width morsels, even if the height was non-zero.
There's currently no way to hit this behavior, but I have an optimization planned for the new streaming multiscan that will use this 🙂

refactor(rust): Fix slicing 0-width morsels on new streaming

---

crates/polars-io/src/predicates.rs
crates/polars-plan/src/dsl/scan_sources.rs
crates/polars-plan/src/plans/hive.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/apply.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/predicate.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/slice.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/post_apply_pipeline/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/capabilities.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_pipelines/generic.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_pipelines/mod.rs
crates/polars-utils/src/slice_enum.rs

PR contains an updated multiscan pipeline implementation. This is not hooked up yet - it is currently missing the IR lowering and refactoring of the individual readers to use the updated pipeline.
Some improvements include:
* Replacing monomorphized `<T: MultiScanable>` with `dyn FileReader`
* Generalized operation pushdown into the readers based on `ReaderCapabilities` (slice/predicate)
* Faster early stopping for some file formats when scanning with positive slice via `row_position_on_end`
* Faster negative slice resolution using concurrent row counting
* Parallelized post-apply pipeline (for missing columns, row index, column casting, reordering etc.)
The effects of these optimizations differ across file types - I will have more concrete benchmark numbers for them per file type in …

refactor(rust): Add updated multiscan pipeline

---

crates/polars-expr/src/groups/mod.rs
crates/polars-expr/src/groups/row_encoded.rs
crates/polars-expr/src/hash_keys.rs
crates/polars-stream/src/nodes/joins/semi_anti_join.rs
crates/polars-stream/src/physical_plan/fmt.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs

I didn't add a fast-path for when the number of keys is very low, and I also currently always goes through the row encoding, so it might be a bit slower for some queries. But this should be a good improvement down the line.

perf: Lower is_in to bitmap-output semi-join in new streaming engine

---

crates/polars-core/src/frame/row/av_buffer.rs
crates/polars-io/src/ndjson/buffer.rs
crates/polars-io/src/ndjson/core.rs
crates/polars-pipe/src/executors/sinks/group_by/generic/thread_local.rs
crates/polars/tests/it/io/json.rs
py-polars/tests/unit/io/test_json.py
py-polars/tests/unit/io/test_lazy_json.py

We currently always append NULL on parsing errors. This will ensure we only do so when `ignore_errors=True`.

fix: Raise error instead of silently appending NULL in NDJSON parsing

---

crates/polars-core/src/chunked_array/object/registry.rs
crates/polars-lazy/src/frame/mod.rs
crates/polars-plan/src/dsl/options.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/conversion/mod.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-python/src/lazyframe/sink.rs
crates/polars-python/src/on_startup.rs
crates/polars-stream/src/nodes/io_sinks/partition/by_key.rs
crates/polars-stream/src/nodes/io_sinks/partition/max_size.rs
crates/polars-stream/src/nodes/io_sinks/partition/mod.rs
crates/polars-stream/src/nodes/io_sinks/partition/parted.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
crates/polars-utils/src/python_function.rs
py-polars/docs/source/reference/io.rst
py-polars/polars/__init__.py
py-polars/polars/io/__init__.py
py-polars/polars/io/cloud/_utils.py
py-polars/polars/io/partition.py
py-polars/tests/unit/io/test_partition.py

This PR makes a breaking change to the currently unstable API for `PartitionMaxSize`, `PartitionByKey` and `PartitionParted`.
> [!TIP]
> **TLDR**: You now provide a `base_path` an optional `file_path` callback. This allows a type-checked, more flexible and pythonic API.
This essentially exchanges the previous adhoc implementation with a more permanent one. This allows for way more flexibility and possibilities around creating files.
```python
lf.sink_parquet(PartitionMaxSize('./{part}.parquet'))
lf.sink_parquet(PartitionMaxSize('./'))
```
You now modify the path per file with a callback.
```python
lf.sink_parquet(PartitionByKey(
'./',
file_path=lambda ctx: f"{ctx.keys[0].str_value}.parquet",
by="year",
))
```
Fixes #21886.
Fixes #21868.
Fixes #21848.

refactor(python)!: Change Partition API to `base_path` and `file_path`

---

crates/polars-time/src/offset_by.rs
crates/polars-time/src/round.rs
py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py

Fixes #21955 (but doesn't address the [comment](https://github.com/pola-rs/polars/issues/21955#issuecomment-2763965816) on invalid durations containing only a digit)
**Before**
```python
pl.Series(["2025-03-27"]).str.to_date().dt.offset_by("P")
pl.Series(["2025-03-27"]).str.to_date().dt.round("P")
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: InvalidOperation(ErrString("expected leading integer in the duration string, found P"))
```
**After**
```
polars.exceptions.InvalidOperationError: expected leading integer in the duration string, found P
```

fix: Error instead of panick for invalid durations in `dt.offset_by()` and `dt.round()`

---

crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/cast_columns.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/mod.rs
crates/polars-stream/src/nodes/io_sources/parquet/builder.rs
crates/polars-stream/src/nodes/io_sources/parquet/init.rs
crates/polars-stream/src/nodes/io_sources/parquet/metadata_utils.rs
crates/polars-stream/src/nodes/io_sources/parquet/mod.rs
crates/polars-stream/src/nodes/io_sources/parquet/row_group_data_fetch.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/io/test_lazy_parquet.py
py-polars/tests/unit/io/test_multiscan.py
py-polars/tests/unit/streaming/test_streaming_io.py

The performance is essentially idental - parquet doesn't benefit from the improved row count efficiency since the row count completes instantly.
Tested on c6gn.8xlarge
Paths:
* `file_path`: 1 file, 50 cols, 100M rows
* `partitioned_files_path`: 100x files, each 1M rows, 50cols
* `s3_*`: Equivalent files stored on S3
```
| index                                      | pypi_1_26                                    | updated                                      | speedup |
|--------------------------------------------|----------------------------------------------|----------------------------------------------|---------|
| # Var: file_path                           |                                              |                                              |         |
| # Script: …
```

refactor(rust): Dispatch new-streaming Parquet source to updated multiscan

---

crates/polars-core/src/chunked_array/logical/categorical/mod.rs

Closes #21984.
(On debug build, so probably much slower than a pip build, but still shows speedup):
```
table cast: 0.052s
direct cast: 118.639s
```
```
table cast: 0.074s
direct cast: 0.063s
```
<details>
<summary>Show test script</summary>
```python
from time import perf_counter
np.random.seed(0)
def random_Enum_Series():
series = pl.Series(np.random.choice(list("ACGT"), size=(50_000, 10))).map_elements(
"".join, return_dtype=pl.String
)
series = series.cast(pl.Enum(series.unique(maintain_order=True)))
return series
a = random_Enum_Series()
b = random_Enum_Series()
enum_type = pl.Enum(
pl.concat([a.cat.get_categories(), b.cat.get_categories()]).unique(
maintain_order=True
)
)
def cast_to_enum(series, enum_type):
old_categories = …
```

perf: Fix quadratic behavior when casting Enums

---

crates/polars-ops/src/chunked_array/strings/mod.rs
crates/polars-ops/src/chunked_array/strings/substring.rs
crates/polars-plan/src/dsl/cat.rs
crates/polars-plan/src/dsl/function_expr/cat.rs
crates/polars-python/src/expr/categorical.rs
py-polars/polars/expr/categorical.py
py-polars/polars/series/categorical.py
py-polars/tests/unit/operations/namespaces/test_categorical.py

As with the other categorical string operations this doesn't allow expression input, as that would negate the whole benefit from performing the operation on categoricals.
```pycon
>>> s = pl.Series(["foobar", "barfoo", "x", None], dtype=pl.Categorical)
>>> s.cat.slice(1, 3)
shape: (4,)
[
"oob"
"arf"
""
null
]
```

feat: Add `cat.slice`

---

crates/polars-plan/src/dsl/functions/concat.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
py-polars/tests/unit/functions/test_concat.py

Fixes https://github.com/pola-rs/polars/issues/21980.
Fixes https://github.com/pola-rs/polars/issues/19877.
Also fixes an issue that wasn't reported (to my knowledge) with `pl.concat` in `group_by`.

fix: Expression pl.concat was incorrectly marked as elementwise

---

Cargo.lock
crates/polars-expr/Cargo.toml
crates/polars-expr/src/planner.rs
crates/polars-lazy/src/dsl/eval.rs
crates/polars-lazy/src/frame/mod.rs
crates/polars-lazy/src/physical_plan/exotic.rs
crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-stream/src/physical_plan/to_graph.rs

Fixes https://github.com/pola-rs/polars/issues/22028.
We used to have this warning because we could overflow the stack. Now we added `#[recursive]` tags to prevent this stack overflow so things should just work. The warning had false-positives anyway because it didn't correctly track depth.

fix: Remove outdated depth warning

---

crates/polars-io/src/pl_async.rs
crates/polars-stream/src/execute.rs

This panic on calling the blocking `run_query` on a tokio task is a feature, not a bug.

fix: Revert #22017 and improve block(_in_place)_on doc comment

---

crates/polars-ops/src/chunked_array/strings/namespace.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
py-polars/tests/unit/operations/namespaces/string/test_string.py

fixes #22033
https://github.com/pola-rs/polars/issues/22033
Attempting to parse a number with an invalid base will now produce a ComputeError.

fix(rust): Fix to_integer panicing on invalid base

---

py-polars/polars/functions/lazy.py
py-polars/tests/unit/functions/test_functions.py

Closes #22081.
Adds `eager` flag to `pl.corr` (as with other such functions, this requires that at least one of the inputs is a `Series`, otherwise there is nothing that can be materialised).
```python
s1 = pl.Series("a", [10, 37, -40])
s2 = pl.Series("b", [70, -10, 35])
pl.corr(s1, s2, eager=True)
pl.corr(s1, s2, method="spearman", eager=True)
```

feat(python): Add an `eager` parameter to `pl.corr`

---

crates/polars-stream/src/nodes/group_by.rs

Fixes a sporadic panic in the streaming engine when running queries containing GroupBy with empty inputs. The node can update state and switch from a sink to a source before `spawn` is called, meaning the locals are still empty. Managed to reproduce only a few times in the cloud:
```python:
lf = pl.LazyFrame(
{},
schema={
"id": pl.Int32,
"x": pl.Int32,
},
)
q1 = (
lf.filter(pl.col("id") == 0)
.join(lf, how="left", left_on="id", right_on="id")
.group_by("id")
.agg(pl.col("x").sum())
)
print(pc.spawn_blocking(q1, dst=tmp_dst, distributed=True).plan())
```
```
AGGREGATE
[col("x").sum()] BY [col("id")]
FROM
simple π 2/3 ["id", "x"]
LEFT JOIN:
LEFT PLAN ON: [col("id")]
FILTER [(col("id")) == (0)]
FROM
DF ["id", "x"]; PROJECT["id", "x"] 2/2 COLUMNS
RIGHT PLAN ON: [col("id")]
DF ["id", "x"]; …
```

fix(rust): Panic in `GroupBySinkState::into_source` with empty locals

---

py-polars/polars/convert/general.py
py-polars/polars/functions/lazy.py
py-polars/tests/unit/functions/test_functions.py

Closes #22075.
Adds `eager` flag to `pl.coalesce` (as with other such functions, this requires that at least one of the inputs is a `Series`, otherwise there is nothing that can be materialised).
```python
s1 = pl.Series("colx", [None,2,None,None])
s2 = pl.Series("coly", [1,None,None,None])
s3 = pl.Series("colz", [None,None,3,None])
pl.coalesce(s1, s2, s3, 4, eager=True)
```

feat(python): Add an `eager` parameter to `pl.coalesce`

---

crates/polars-lazy/src/tests/queries.rs
crates/polars-plan/src/dsl/function_expr/dispatch.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/mod.rs
crates/polars-python/src/expr/general.rs
crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
py-polars/docs/source/reference/expressions/modify_select.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/dataframe/test_upsample.py
py-polars/tests/unit/lazyframe/test_lazyframe.py
py-polars/tests/unit/operations/test_group_by.py

This was a duplicate of `.fill_null(strategy="backward"/"forward")`, so deprecating in favor of those.

chore: Deprecate duplicate `backward_fill` and `forward_fill` interface

---

crates/polars-sql/src/context.rs
crates/polars-sql/src/types.rs
py-polars/tests/unit/sql/test_array.py
py-polars/tests/unit/sql/test_cast.py

The SQL interface now parses/recognises Int128 (aka: HUGEINT[^1]) types.
This means the following casts are all now valid:
* `CAST(value AS HUGEINT)`
* `CAST(value AS INT128)`
* `value::hugeint`
* `value::int128`
```python
df = pl.DataFrame({"value": [-2**32, 2**48]})
df.sql("""
SELECT *, value::int128 AS value128
FROM self
""")
```
[^1]: [Integer Types](https://duckdb.org/docs/stable/sql/data_types/numeric.html#integer-types)

feat: Add support for `Int128` parsing/recognition to the SQL interface

---

crates/polars-sql/src/sql_expr.rs
py-polars/tests/unit/sql/test_structs.py

Closes #22107.
If we had a column in the table root with the same name as a field in a nested column, and used dot-notation to refer to the nested column, we could incorrectly resolve to the root-level column with that name instead.
**Note:** using the dedicated/non-ambiguous operator `->` works correctly in all cases (eg: `author -> 'id' AS author_id`); the issue only occurred with dot-notation, as that _also_ covers table identifiers (eg: `tbl.column`) so it has to disambiguate usage.
```python
"id": ["012345", "987654"],
"name": ["A Book", "Another Book"],
"author": [
{"id": "888888", "name": "Iain M. Banks"},
{"id": "444444", "name": "Dan Abnett"},
],
})
```
* ### Before
Column `author.id` incorrectly resolves to `id`.
(Only occurs if a column …

fix: Ensure SQL dot-notation for nested column fields resolves correctly

---

py-polars/polars/functions/lazy.py
py-polars/tests/unit/functions/test_functions.py
py-polars/tests/unit/operations/test_statistics.py

Ref: #22081, #22097.
If we're adding an `eager` param to `corr`, it's consistent to have it on `cov` too.

feat(python): Add an `eager` parameter to `pl.cov`

---

crates/polars-io/src/cloud/glob.rs
crates/polars-io/src/path_utils/hugging_face.rs

Fixes https://github.com/pola-rs/polars/issues/21736
We do globs by converting first converting to regex (I assume to avoid a dependency). This PR rewrites the conversion and fixes the wildcard `**` glob accidentally matching extra files.
Previously we would convert `**` to `.*` in regex, but this would cause e.g. `a/**/b` to match `a/<dir>/xb`. It is now instead translated to `(.*/)?` to ensure the matching is halted at the last forward-slash.

fix: Fix glob expansion matching extra files

---

crates/polars-io/src/csv/read/reader.rs

This PR implements a new .with_options() method for CsvReader to allow custom CSV read options.
Although the existing into_reader_with_file_handle function from CsvReadOptions is useful for applying custom options, this PR introduces a helper function directly on CsvReader. This new function aims simplifying adding custom csv options—similar to how CsvWriter provides its own helper methods.
Fixes #16749.
Please feel free to let me know if you have any suggestions about this PR.

Add .with_options() method to CsvReader for easier configuration

---

crates/polars-ops/src/chunked_array/hist.rs
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/tests/unit/operations/test_hist.py

Closes #22056.
The old implementation made an attempt to follow pandas logic in that, when bins are automatically determined, the lowest edge is extended by a small amount. This allowed all intervals to remain left-open and include all of the data.
This results in ugly bins and also resulted in the issue above, where a user-supplied bins were respected, but the left-most bin was still open, and so if a data point fell on that edge, it was not counted. This was technically correct based on the logic, but is undoubtedly *not* what users want.
This PR simply makes the first bin closed, and all others left-open. It simplifies the internal logic (no more `pad_lower` argument) and has the side-effect of having all uniformly-spaced bins when `bin_counts` is provided (no more extending the left …

fix: Make bottom interval closed in `hist`

---

crates/polars-python/src/interop/arrow/to_rust.rs
py-polars/polars/_utils/construction/dataframe.py
py-polars/tests/unit/constructors/test_constructors.py

Resolves #22113 
This PR adds pre-checks to the rust code responsible for converting pyarrow tables into a polars DataFrame to prevent panics that appear to result from the unsafe construction of a DF without checking column uniqueness first.
Existing python post-checks are removed and a decimal column has been inserted into the existing test to cover the case that currently panics.

fix(python): Fix panic when constructing DF from pyarrow due to duplicate field names

---

crates/polars-core/src/utils/supertype.rs
py-polars/tests/unit/operations/arithmetic/test_arithmetic.py

Closes #22136 
```python
pl.Series([True]) + pl.Series([1], dtype=pl.Int128)
```

fix: Add `i128` as supertype to boolean

---

crates/polars-sql/src/functions.rs
crates/polars-sql/src/table_functions.rs
py-polars/docs/source/reference/sql/functions/string.rst
py-polars/tests/unit/sql/test_strings.py

Adds SQL support for the `STRING_TO_ARRAY`[^1] function, which splits a string by a delimiter. Also, minor docstring standardisation (ensure lines end with `"."`).
```python
df = pl.DataFrame({"s": ["xx,yy,zz", "abc,,xyz", None]})
df.sql("SELECT *, STRING_TO_ARRAY(s,',') AS s_array FROM self")
```
[^1]: https://www.postgresql.org/docs/current/functions-string.html#FUNCTION-STRING-TO-ARRAY

feat: Add `STRING_TO_ARRAY` function to the SQL interface

---

crates/polars-core/src/frame/mod.rs
py-polars/tests/unit/io/test_csv.py

Fixes #20273
Request review:
* See Issue #20273 for detailed observations
* Consider commit 962b576 as part of review, which contained the breaking change where `as_single_chunk()` dropped support for ScalarColumn.
* The equivalent `as_single_chunk_par()` works as expected (no panic observed)
* Question: is the incoming df (the result from cross_join and filter in the MRE) as expected? It has multiple chunks, some of which are empty, and uses ScalarColumn or SeriesColumn depending on the number of rows filter (1 vs 2+ respectively). Debug traces are available on request.

fix: Fix csv serializer panic by supporting ScalarColumn in as_single_chunk

---

crates/polars-sql/src/types.rs
py-polars/tests/unit/sql/test_cast.py

Minor update, adding recognition/support for the following unsigned integer aliases (we already support all of the same aliases without the leading `"U"`):
* `UTINYINT`
* `USMALLINT`
* `UINTEGER`
* `UBIGINT`
(ref: https://duckdb.org/docs/stable/sql/data_types/numeric.html#integer-types)

feat: Support additional unsigned int aliases in the SQL interface

---

py-polars/polars/series/series.py
py-polars/tests/unit/series/test_series.py

Fixes https://github.com/pola-rs/polars/issues/22067
I expected to have to do some plumbing to connect the `Expr` method to the `Series` method. I'm really impressed with the `@expr_dispatch` decorator, that is a really neat trick!

Add `repeat_by` to `Series`

---

crates/polars-stream/src/nodes/io_sources/ipc.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/io/test_multiscan.py

Also does some drive-by refactoring.
Performance is essentially identical.
Tested on AWS `c6gn.8xlarge`. Files are on local disk.
* `head(10_000_000)` (first 10 files)
```python
8.03s user 3.97s system 780% cpu 1.538 total
8.07s user 4.30s system 826% cpu 1.498 total
```
* `tail(10_000_000)` (last 10 files)
```python
8.11s user 4.00s system 773% cpu 1.564 total
8.11s user 4.56s system 845% cpu 1.498 total
```

refactor(rust): Dispatch new-streaming IPC source to updated multiscan

---

py-polars/polars/expr/expr.py
py-polars/tests/unit/dataframe/test_df.py

After having discussed it again internally, we are okay keeping these aliases around.
Fixes #22155.

chore: Undeprecate `backward_fill` and `forward_fill`

---

crates/polars-stream/src/execute.rs
crates/polars-stream/src/nodes/io_sources/batch.rs
crates/polars-stream/src/physical_plan/to_graph.rs

Note that IO plugins currently don't handle multiple files. The goal of this PR is to move the batch reader to use the new `FileReader` interface so that the old one can be removed.
@coastalwhite

refactor(rust): Dispatch new-streaming IO plugin source to updated multiscan

---

Cargo.lock
Cargo.toml
crates/polars-stream/Cargo.toml
crates/polars-stream/src/nodes/joins/equi_join.rs
crates/polars-stream/src/nodes/joins/semi_anti_join.rs

Fixes https://github.com/pola-rs/polars/issues/22135.
This one was very tricky to reason about, but thankfully the debugger showed me what's going on in a stacktrace. I spawned N tasks on the rayon threadpool, and these tasks can send information to each other to process. Only once all information is processed will any of the tasks exit.
The problem is that these tasks also called a gather kernel, and inside this gather kernel a rayon `POOL.join` was called. This causes rayon to task steal one of the outer tasks and start running it nested inside an other, leading to a deadlock.

fix: Deadlock in join due to rayon nested task-stealing

---

py-polars/polars/expr/list.py
py-polars/polars/series/list.py
py-polars/tests/unit/operations/test_sets.py

Closes #21905.
```python
a = pl.Series([[1, 2, 3], [], [None, 3], [5, 6, 7]])
a.list.set_intersection({1, 2, None})

fix: Allow set input to `list.set_*` operations

---

crates/polars-io/src/csv/read/read_impl.rs
crates/polars-stream/src/nodes/io_sources/csv.rs
crates/polars-stream/src/nodes/io_sources/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_scan.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/io/test_csv.py
py-polars/tests/unit/io/test_lazy_csv.py

Also does some drive-by refactoring.
I have skipped quite a few tests that began failing due to a lack of a `missing_columns` parameter on the API - I plan to get to this later.
Tested on AWS `c6gn.8xlarge`. Files are on local disk.
* `head(10_000_000)` (first 10 files)
```python
30.17s user 6.52s system 872% cpu 4.205 total
24.01s user 4.46s system 757% cpu 3.757 total
```
* `tail(10_000_000)` (last 10 files)
```python
29.63s user 6.27s system 621% cpu 5.772 total
25.36s user 5.00s system 778% cpu 3.901 total
```
@coastalwhite

refactor(rust): Dispatch new-streaming CSV source to updated multiscan

---

Cargo.lock
Cargo.toml
crates/polars-ops/Cargo.toml
crates/polars-ops/src/series/ops/round.rs
py-polars/tests/unit/operations/namespaces/temporal/test_round.py

Fixes https://github.com/pola-rs/polars/issues/22166.
In general fixes behavior for rounding very large or small numbers which would otherwise return `NaN`s or infinities.

fix: Incorrect rounding for very large/small numbers

---

crates/polars-io/src/predicates.rs
crates/polars-parquet/src/arrow/read/expr.rs

This speeds up the use-case of #22176 by a bit more than 2x.

perf: Speed-up new streaming predicate filtering

---

crates/polars-plan/src/plans/conversion/join.rs
py-polars/tests/unit/operations/test_inequality_join.py
py-polars/tests/unit/operations/test_join.py

1. Closes #22105
2. Closes #22046
3. Closes #22042
4. Closes #22047
5. Closes #22045
This PR brings brings a few enhancements to `join_where`, which I have been making great use of but hits a few snags:
Currently, predicates must contain columns from both tables being joined. As mentioned in #22105, this doesn't seem like it should be a requirement; one-sided predicates are fairly common in sql and are logically perfectly safe.
```python
df1 = pl.DataFrame({"a": [1, 2, 3]})
df2 = pl.DataFrame({"b": [4, 5]})
df1.join_where(df2, pl.col("a") < 3)  # ERROR, predicate must contain columns from both sides
df1.join_where(df2, pl.col("a") < 3)
```
The current behavior errors if any of part of the sub-expression contains a boolean evaluation (see #22046). This PR fixes this issue. It also has the …

fix: Enhance predicate validation and cast safety in `join_where`

---

crates/polars-sql/src/functions.rs
py-polars/docs/source/reference/sql/functions/string.rst
py-polars/tests/unit/sql/test_strings.py

Adds SQL support for the `SPLIT_PART`[^1] function, which splits a string by a delimiter and returns the indicated (1-indexed) element.
```python
df = pl.DataFrame({"s": ["xx,yy,zz", "abc,,xyz,???,hmm", None, ""]})
df.sql("""
SELECT
s,
SPLIT_PART(s,',',1) AS "s+1",
SPLIT_PART(s,',',3) AS "s+3",
SPLIT_PART(s,',',-2) AS "s-2",
FROM self
""")
```
[^1]: https://www.postgresql.org/docs/current/functions-string.html#:~:text=split_part

feat: Add `SPLIT_PART` string function to the SQL interface

---

crates/polars-plan/src/plans/optimizer/cse/cse_expr.rs
crates/polars-plan/src/plans/optimizer/cse/mod.rs
crates/polars-plan/src/plans/optimizer/mod.rs
crates/polars-stream/src/physical_plan/lower_group_by.rs

This ensures that the key and aggregate inputs to the `GroupBy` node are simple columns, while also doing CSE. This is a prerequisite for the new groupby implementation I'm working on, while also being a performance boost in case you have common expressions you compute multiple aggregates on.
It is currently only naive CSE though, not full CSE - only identical input expressions to different aggregates get deduplicated.

perf: Add CSE to streaming groupby

---

crates/polars-plan/src/plans/aexpr/predicates/skip_batches.rs
py-polars/tests/unit/io/test_hive.py

fix: Fallback predicate filter for `min=max` with `is_in`

---

crates/polars-python/src/lazyframe/visitor/nodes.rs

Exposes `FunctionIR::FastCount` in the Python visitor. It allows the Polars GPU executor to detect `.select(pl.len())` plans without reading the full dataset. This is needed to avoid unnecessary I/O and improve performance when only the row count is required.

feat(rust): Expose `FunctionIR::FastCount` in the python visitor

---

crates/polars-lazy/src/frame/mod.rs
crates/polars-mem-engine/src/lib.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-plan/src/dsl/file_scan.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
crates/polars-python/src/cloud.rs
crates/polars-stream/src/lib.rs
crates/polars-stream/src/nodes/io_sources/csv.rs
crates/polars-stream/src/nodes/io_sources/ipc.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/predicate.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/projection.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_pipelines/generic.rs
crates/polars-stream/src/physical_plan/lower_group_by.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
crates/polars-stream/src/skeleton.rs
py-polars/tests/unit/io/test_hive.py
py-polars/tests/unit/io/test_lazy_ipc.py
py-polars/tests/unit/io/test_lazy_parquet.py
py-polars/tests/unit/io/test_scan.py
py-polars/tests/unit/streaming/test_streaming_io.py

Hacks included in this PR:
* For `scan_csv`, `allow_missing_columns` is conditionally toggled to `true` based on whether the user provided a schema to mimic the current API behavior.
* TODO: Fix by adding https://github.com/pola-rs/polars/issues/21996, we will need to wait until 2.0 to change the behavior
* Conditionally enables (the newly added) `SchemaNamesMatchPolicy::ForbidExtra` only if there is no projection. Note this matches what the in-mem engine does but it's not technically correct
* TODO: Fix by resolving https://github.com/pola-rs/polars/issues/22218

feat: Dispatch scans to new-streaming by default

---

crates/polars-io/src/parquet/read/read_impl.rs
crates/polars-stream/src/nodes/io_sources/parquet/init.rs
crates/polars-stream/src/nodes/io_sources/parquet/row_group_decode.rs

This turns on `parallel=prefiltered` by default when there is a `predicate` on prefiltered.
This also does some other QOL changes.
- Decoding of `live` and `dead` columns is now parallelized. This is still not optimal as it could be parallelized, but already much better than before.
- If a `pre-slice` now consumes an entire row group, it does not block prefiltering for that row group.
- Fixed a panic when a prefilter only took `live_columns` and the `row_index`.

perf: Turn on `parallel=prefiltered` by default for new streaming

---

crates/polars-arrow/src/array/binary/builder.rs
crates/polars-arrow/src/array/binary/mod.rs
crates/polars-arrow/src/array/builder.rs
crates/polars-arrow/src/array/list/builder.rs

Hadn't implemented this with the other builders since we didn't need it but now I do need it to build up row-encoded `HashKeys` for hot key evicting.

refactor: Add BinaryArrayBuilder

---

crates/polars-ops/src/chunked_array/strings/namespace.rs

This PR addresses an issue https://github.com/pola-rs/polars/issues/22242 where calling str.to_integer() with strict=True unexpectedly panics for certain inputs.
The problem occurs because the values s and base at line 118 do not always correspond correctly, which leads to the bug. This PR modifies how some_failures is retrieved in original order so that s and base are properly paired, preventing the panic. 
https://github.com/pola-rs/polars/blob/69ad1ba3bd2382c59bd5b2420957d934e6447aa7/crates/polars-ops/src/chunked_array/strings/namespace.rs#L95-L124
close #22242

fix(rust): Fix `str.to_integer` panics for certain inputs

---

crates/polars-ops/src/chunked_array/hist.rs
py-polars/tests/unit/operations/test_hist.py

Closes #22234
Two minor adjustments:
1. When user-supplied bins are provided, the slow path is always taken. This guarantees that the user's bins are *always* respected. The prior implementation attempted to detect if the bins were uniformly distributed using a heuristic, but that heuristic can be foiled, and we were bound to encounter an issue on this sometime in the future.
2. In the fast path (now only when `bin_count` is supplied), the index calculation might generate results > 1 ULP of the bin edges in some cases, resulting in an invalid index, as see in the linked issue. There, we have `1.0 - 1e-17 == 1.0`:
```pycon
>>> pl.Series([1.0]) - 1e-17 == 1.0
shape: (1,)
Series: '' [bool]
[
true
]
```
There is now a check to see whether the value should be moved to …

fix: Ensure floating-point accuracy in `hist`

---

crates/polars-compute/src/var_cov.rs

This flips the sign of the delta from `a - b` to `b - a` to align with the definition in https://www.osti.gov/servlets/purl/1427275 for upcoming higher moments.

refactor(rust): Use more logical delta definition in var/cov calcs

---

crates/polars-time/src/chunkedarray/rolling_window/dispatch.rs
py-polars/tests/unit/operations/rolling/test_rolling.py

Closes #22251. Also `rolling_min_by` and `rolling_max_by`.
```python
"col1": pl.int_range(0, 7, eager=True),
"col2": pl.int_range(0, 7, eager=True).reverse(),
}).with_columns(
pl.when(pl.int_range(0, pl.len(), eager=False) < 2)
.then(None)
.otherwise(pl.all())
.name.suffix("_nulls")
).cast(pl.Date)
df.select([pl.all().rolling_min(3)])
df.select([pl.all().rolling_max(3)])
```

feat: Add rolling min/max for temporals

---

crates/polars-plan/src/plans/conversion/join.rs
py-polars/tests/benchmark/test_join_where.py

Fixes #22257.
This was a regression I inadvertently introduced in #22112.

fix: Raise `ColumnNotFoundError` for missing columns in `join_where`

---

py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #21068.
Strip any trailing zero-time components (eg: `00:00:00` or `00:00:00.000000`) before applying `.str.to_date()`, when `Date` dtype is indicated.
We were doing this in some places already, but this PR ensures that we do it consistently across all supported engines, and adds some test coverage to validate.

fix: More robust `str → date` conversion when reading from spreadsheet

---

crates/polars-expr/src/expressions/window.rs
crates/polars-lazy/src/tests/queries.rs
py-polars/tests/unit/operations/test_window.py

fix(rust): Expr.over() returning List type when DataFrame is empty

---

crates/polars-time/src/chunkedarray/string/strptime.rs
py-polars/tests/unit/io/test_csv.py
py-polars/tests/unit/operations/namespaces/test_strptime.py

closes https://github.com/pola-rs/polars/issues/22167
~~Exploring this further, as this nominally fixes the issue but isn't the end of the story~~ done, much happier with the current fix

fix: Datetime parser was incorrectly parsing 8-digit fractional seconds when format specified to expect 9

---

crates/polars-plan/src/dsl/udf.rs
crates/polars-sql/src/functions.rs
crates/polars-sql/tests/udf.rs

Closes https://github.com/pola-rs/polars/issues/15155
Over-eager schema validation is unfortunately rendering user-defined SQL functions unusable. Not sure why registered UDFs need to hardcode/pre-specify the names and dtypes of prospective arguments-- the plugin can handle invalid calling patterns much more flexibly. Reducing the strictness also allows SQL plugins to be variadic, just like Python plugins are.
I wrote this PR with a different and simpler approach because the original PR from @uhlarmarek has stalled: https://github.com/pola-rs/polars/pull/15159
The SQL functionality seems useful, but we can't move forward with it until we can register UDFs. Thanks for the great work as always!

fix(rust): Too-strict SQL UDF schema validation

---

crates/polars-parquet/src/parquet/statistics/mod.rs
py-polars/tests/unit/io/test_parquet.py

fix: Don't collect `NaN` from Parquet Statistics

---

crates/polars-ops/src/series/ops/duration.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
py-polars/tests/unit/datatypes/test_duration.py
py-polars/tests/unit/operations/unique/test_unique.py

fix: Move type coercion for `pl.duration` to planner

---

crates/polars-plan/src/dsl/function_expr/correlation.rs
py-polars/tests/unit/operations/test_statistics.py

fix: Check matching lengths for `pl.corr`

---

crates/polars-plan/src/plans/python/predicate.rs
py-polars/tests/unit/io/test_io_plugin.py

closes #21790
In the linked issue, setting the schema to be nanosecond precision, forces a cast on the column to compare to the python datetime, which was previously not getting pushed down to the IO plugin.

feat: Support Cast in IO plugin predicates

---

Cargo.lock
Cargo.toml

This was being hit particularly hard in the new streaming `group_by` implementation.

perf: Patch jemalloc to not purge huge allocs eagerly if we have background threads

---

crates/polars-stream/src/nodes/merge_sorted.rs
py-polars/tests/unit/operations/test_merge_sorted.py

fixes #21789
This (tactically) fixes the problem as reported (MRE), but expert input and review is required to assess the integrity of the modified `update_all_states` function and ensure we are not breaking anything (I doubt it).
Note, a precise definition of the `PortState` states and documentation of the state exchange algorithm would help me and others review the logic. If that is available, kindly share.

fix: Resolve streaming panic on multiple `merge_sorted`

---

py-polars/docs/source/reference/expressions/temporal.rst
py-polars/docs/source/reference/series/temporal.rst

I added the feature but forgot to add it to the docs reference 🤦

docs(python): Add missing `is_business_day` to documentation reference

---

crates/polars-expr/src/expressions/aggregation.rs
py-polars/tests/unit/operations/test_group_by.py

fixes #22328
We can prune that code soon and dispatch to the new streaming engine.

fix: Maintain float32 type in partitioned group-by

---

py-polars/polars/dependencies.py
py-polars/polars/functions/lit.py
py-polars/tests/unit/datatypes/test_temporal.py

Closes #21595.
When #21003 introduced handling on FixedOffset timezone, it only handled `zoneinfo.ZoneInfo` named timezone so `pytz` named timezone got converted to UTC. This PR fixed that. Also added tests to test all valid timezone objects.
```python
print(pl.DataFrame([[ts]]).with_columns(pl.lit(ts).alias("ts")))
shape: (1, 2)
┌────────────────────────────────┬─────────────────────────┐
│ column_0                       ┆ ts                      │
│ ---                            ┆ ---                     │
│ datetime[μs, America/New_York] ┆ datetime[μs, UTC]       │
╞════════════════════════════════╪═════════════════════════╡
│ 2020-01-01 00:00:00 EST        ┆ 2020-01-01 05:00:00 UTC │
└────────────────────────────────┴─────────────────────────┘
```
```python …
```

fix(python): Handle pytz named timezone in `lit`

---

py-polars/polars/functions/whenthen.py

There is a recent SO question[^1] from a new Polars user stuck due to ColumnNotFound errors.
I've added a Notes section and some examples of `lit()` being used.
I've removed mentions of `if` and `elif` as I've found people seem to think `when-then` performs conditional execution. 
I think describing it as similar to a `coalesce` that folds left to right is a good way to explain things?
`# fmt: skip` was added to keep the example columns on their own line as a visual aid.
Some additional examples added for common questions: structs, name.keep, etc.
[^1]: https://stackoverflow.com/questions/79574115/why-wont-polars-when-and-then-run-in-jupyters-notebook

docs(python): Update `pl.when` documentation

---

Cargo.lock
Cargo.toml
crates/polars-compute/Cargo.toml
crates/polars-compute/src/rolling/min_max.rs
crates/polars-compute/src/rolling/no_nulls/mean.rs
crates/polars-compute/src/rolling/no_nulls/mod.rs
crates/polars-compute/src/rolling/no_nulls/moment.rs
crates/polars-compute/src/rolling/no_nulls/quantile.rs
crates/polars-compute/src/rolling/no_nulls/sum.rs
crates/polars-compute/src/rolling/nulls/mean.rs
crates/polars-compute/src/rolling/nulls/mod.rs
crates/polars-compute/src/rolling/nulls/moment.rs
crates/polars-compute/src/rolling/nulls/quantile.rs
crates/polars-compute/src/rolling/nulls/sum.rs
crates/polars-compute/src/rolling/window.rs
crates/polars-core/src/frame/group_by/aggregations/mod.rs
crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs

closes #22343
Uses the proposed skiplist crate. There are some optimizations we can still do, but that requires vendoring or a native implementation. This is something we can look into later.

perf: Use optimize rolling_quantile with varying window sizes

---

crates/polars-expr/src/groups/mod.rs
crates/polars-expr/src/groups/row_encoded.rs
crates/polars-expr/src/hash_keys.rs
crates/polars-expr/src/hot_groups/row_encoded.rs

This reuse will make it easier to write the single-key variants.

refactor(rust): Improve code re-use for groupby and delete unused code

---

crates/polars-plan/src/plans/optimizer/predicate_pushdown/keys.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/rename.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/utils.rs
crates/polars-plan/src/utils.rs
py-polars/tests/unit/test_predicates.py

* Fixes https://github.com/pola-rs/polars/issues/22373
The current handling of `Rename` in predicate pushdown uses some complex logic to remove predicates. In this PR, we simplify by observing that all columns within a `Rename` are guaranteed to exist in the input node (with maybe a different name), so we can just pass all of the predicates through after mapping the column references.

fix: Fix incorrect filter after `LazyFrame.rename().select()`

---

py-polars/polars/_utils/getitem.py
py-polars/polars/_utils/various.py
py-polars/polars/convert/general.py
py-polars/polars/dataframe/frame.py
py-polars/polars/datatypes/convert.py
py-polars/polars/datatypes/group.py
py-polars/polars/expr/categorical.py
py-polars/polars/expr/datetime.py
py-polars/polars/expr/string.py
py-polars/polars/expr/struct.py
py-polars/polars/functions/eager.py
py-polars/polars/functions/escape_regex.py
py-polars/polars/functions/lazy.py
py-polars/polars/functions/repeat.py
py-polars/polars/interchange/from_dataframe.py
py-polars/polars/io/csv/functions.py
py-polars/polars/io/database/functions.py
py-polars/polars/io/spreadsheet/_write_utils.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/series.py
py-polars/polars/series/struct.py
py-polars/polars/sql/context.py
py-polars/tests/unit/functions/test_functions.py
py-polars/tests/unit/test_errors.py
py-polars/tests/unit/test_selectors.py

Closes #22387.
Clarifies the given/problematic type. Improvement not limited to the `join` methods (as reported in the linked issue); applies to _all_ errors where we report external type names -
```python
"id": [1, 2, 3],
"val": ["aa", "bb", "cc"],
})
"id": [1, 3],
"tag": ["xxxx", "yyyy"],
})
```
_(bare typename; potentially ambiguous)_
```python
df1.join(df2.to_pandas(), how="full", on="id")
```
_(module-qualified typename; unambiguous)_
```python
df1.join(df2.to_pandas(), how="full", on="id")
```

feat(python): When reporting unexpected types in errors, module-qualify the typename

---

crates/polars-utils/src/select.rs

This was mapped unnecessarily to an intrinsic in https://github.com/pola-rs/polars/pull/22342.

chore: Replace intrinsic with non-intrinsic

---

crates/polars-stream/src/nodes/group_by.rs

Without this the CI will essentially only test the hot table, not the other codepath.

refactor: Reduce hot table size in debug mode

---

crates/polars-arrow/src/array/binview/builder.rs
crates/polars-arrow/src/array/binview/view.rs
crates/polars-compute/src/binview_index_map.rs
crates/polars-expr/src/groups/binview.rs
crates/polars-expr/src/groups/mod.rs
crates/polars-expr/src/groups/row_encoded.rs
crates/polars-expr/src/groups/single_key.rs
crates/polars-expr/src/hash_keys.rs
crates/polars-expr/src/hot_groups/binview.rs
crates/polars-expr/src/hot_groups/fixed_index_table.rs
crates/polars-expr/src/hot_groups/mod.rs
crates/polars-expr/src/hot_groups/row_encoded.rs
crates/polars-expr/src/hot_groups/single_key.rs
crates/polars-expr/src/lib.rs
crates/polars-stream/src/nodes/group_by.rs
crates/polars-stream/src/nodes/joins/semi_anti_join.rs
crates/polars-utils/src/hashing.rs
crates/polars-utils/src/idx_map/bytes_idx_map.rs
crates/polars-utils/src/idx_map/total_idx_map.rs

This is a lot faster than going through the row encoding and doing string comparisons.

perf: Add single-key variants of streaming group_by

---

crates/polars-plan/src/dsl/function_expr/list.rs
py-polars/tests/unit/datatypes/test_list.py

Currently, list.get handles only two patterns:
1. Scalar index (index.len() == 1): one index for each list.
2. Per‑list indexing (index.len() == ca.len()): one index per list in the column.
Any other combination including a single list with multiple indices falls through to the match arm (which is what happens in https://github.com/pola-rs/polars/issues/21463), which throws an error:
```
polars.exceptions.ComputeError: `list.get` expression got an index array of length 3 while the list has 1 elements
```
I added a new match arm for exactly the scenario when there’s one list (ca.len() == 1) but index.len() > 1—to sort of “broadcast” the list across all requested positions. 
Now: 
```
df = pl.DataFrame({"a": [1, 2, 3]})
df.with_columns(b=pl.lit([1, 2, 3, …
```

fix(rust): Fix chaining pl.lit(<list>) with .list.get(pl.col(...))

---

crates/polars-stream/src/physical_plan/lower_expr.rs
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/datatypes/test_decimal.py
py-polars/tests/unit/datatypes/test_float.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/operations/unique/test_unique.py

These are equivalent to a zero-aggregate `group_by`, possibly followed by a length reduction.

perf: Lower Expr.(n_)unique to group_by on streaming engine

---

py-polars/tests/unit/operations/test_interpolate_by.py

The error threshold in my previous fix was still too strict.

chore: Make interpolate fix more robust

---

crates/polars-python/src/dataframe/general.rs
crates/polars-python/src/expr/rolling.rs
crates/polars-python/src/map/lazy.rs
crates/polars-python/src/on_startup.rs
crates/polars-python/src/py_modules.rs
crates/polars-python/src/series/export.rs
crates/polars-python/src/series/import.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/series/series.py
py-polars/tests/unit/operations/map/test_map_batches.py

This uses polars-ffi to convert between python and rust to support calling
python UDFs from rust polars. This is primarily used in polars-cloud.
As a consequence, this also fixes map_rolling and numpy ufuncs in polars-cloud

fix(rust): Fix rust -> python -> rust for map_batches

---

crates/polars-plan/src/plans/ir/format.rs
crates/polars-stream/src/physical_plan/fmt.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs

Note, this also removes the unused `PhysNodeKind::FileScan` node, we are now always using `MultiScan`.
**Before**
**After**

refactor(rust): Improve new-streaming multiscan physical plan visualization

---

crates/polars-lazy/src/tests/io.rs
crates/polars-plan/src/dsl/builder_dsl.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs

Restores some code deleted in https://github.com/pola-rs/polars/pull/22363 - we shouldn't assume all implementors of `AnonymousScan` are able to project 0-width frames.
Also does some refactoring to make the control flow of the code slightly cleaner.

fix(rust): Ensure at least one column projected for AnonymousScan

---

py-polars/polars/io/spreadsheet/_write_utils.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #22306; fixes the issue and adds suitable test coverage.

fix(python): Ensure `write_excel` correctly preserves null values in nested dtype data on export

---

py-polars/polars/io/csv/functions.py

This updates the docs for the schema arg in `scan_csv` to match `read_csv` and make it clear that the order of columns needs to match the order of columns in the CSV file being read.
Fixes #22326

docs(python): Update docs for schema arg in scan_csv to match read_csv

---

py-polars/requirements-ci.txt

I noticed the constraint in #22355 - it looks like this was resolved in the [latest pytorch release](https://download.pytorch.org/whl/cpu).

chore: Install pytorch for 3.13 on Windows

---

Cargo.lock
Cargo.toml
crates/polars-python/src/conversion/datetime.rs

This release has significant less breaking changes than the previous one 😅

build(python): Update `pyo3` and `numpy` crates to version `0.24`

---

.github/workflows/test-coverage.yml
py-polars/pyproject.toml
py-polars/requirements-ci.txt

**Note**: I am not 100% sure I have done this right so someone more familiar with project setup please review!
---
While ~~trying to fix~~ (whoops, triggered issue close keyword) work on #22348 (with no success so far), I discovered that by using `--extra-index-url` in `requirements-ci.txt`
https://github.com/pola-rs/polars/blob/3cfa7cdb1ba4ed9b570214887b4179e5f54f66d9/py-polars/requirements-ci.txt#L5
we were inadvertently using the pytorch repo for many package installations, including numpy, since when you use `--extra-index-url` it becomes prioritized ([see docs](https://docs.astral.sh/uv/configuration/indexes/#-index-url-and-extra-index-url)) over PyPi. This was causing packages to be installed from pytorch instead of PyPi, and subsequently was not installing the latest version. For …

chore: Only use pytorch index-url for `pytorch` package

---

.github/workflows/test-coverage.yml

I would recommend waiting until after resolving the 1.28 release issues before merging this.

ci: Pin to explicit macOS version in code coverage

---

crates/polars-lazy/src/tests/queries.rs
crates/polars-ops/src/series/ops/mod.rs
crates/polars-ops/src/series/ops/round.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/round.rs
crates/polars-plan/src/dsl/mod.rs
crates/polars-python/src/conversion/mod.rs
crates/polars-python/src/expr/general.rs
crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
crates/polars-sql/src/functions.rs
docs/source/src/rust/user-guide/expressions/expression-expansion.rs
docs/source/src/rust/user-guide/getting-started.rs
py-polars/polars/_typing.py
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py

fix #21800 (though as @orlp mentioned there are theoretically more round modes to add)
- current `round` expression has no `mode` and is inconsistent 
- `Decimal`: uses "half to even"
- `Float`: uses "half away from zero"
- implement missing round modes
- `Decimal`: implement "half away from zero"
- `Float`: implement "half to even"
- set "half to even" as default for float & decimal
```python
{
"f64": [-3.5, -2.5, -1.5, -0.5, 0.5, 1.5, 2.5, 3.5],
"d": ["-3.5", "-2.5", "-1.5", "-0.5", "0.5", "1.5", "2.5", "3.5"],
},
schema={
"f64": pl.Float64,
"d": pl.Decimal(scale=1),
},
)
pl.all().round().name.suffix("_default"),
pl.all().round(mode="half_away_from_zero").name.suffix("_away_from_zero"),
pl.all().round(mode="half_to_even").name.suffix("_to_even"),
) …
```

feat: Add `RoundMode` for Decimal and Float

---

crates/polars-ops/src/chunked_array/list/namespace.rs
crates/polars-plan/src/dsl/function_expr/list.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
py-polars/polars/expr/list.py
py-polars/tests/unit/operations/namespaces/list/test_list.py

Related to #22149.
This makes the only valid signature for `list.gather`: `(List(T), List(Int)) ->
List(T)` and deprecates the non-elementwise `(List(T), Int) -> List(T)` by adding an implicit implode for now. **NOTE**: This does not affect `list.gather([0, 1])` because it now (as is the case in the rest of polars) gets regarded as a list scalar.

fix: Deprecate flat `list.gather` and mark as elementwise

---

crates/polars-arrow/src/io/ipc/read/read_basic.rs
crates/polars-parquet/src/parquet/read/compression.rs

This very simple change was actually a huge performance boost on large machines when not running with `POLARS_THP=1`. If you call `vec![0; n]` it leads to `alloc_zeroed` which jemalloc implements (when transparent huge pages aren't enabled) by calling `MADV_DONTNEED`. This is the correct behavior if you allocate a huge piece of zeroed memory but only touch parts of it, as then the operating system will zero-fill pages for you on pagefault.
However, in these decompression cases we allocate a zero-buffer and then immediately completely fill it. Avoiding the constant syscalls here by simply doing a `memset` is way better.

perf: Avoid alloc_zeroed in decompression

---

crates/polars-stream/src/async_primitives/mod.rs
crates/polars-stream/src/async_primitives/opt_spawned_future.rs
crates/polars-stream/src/nodes/io_sources/parquet/row_group_decode.rs
py-polars/tests/unit/io/test_lazy_parquet.py

* Fixes https://github.com/pola-rs/polars/issues/22452
There was originally a function that implemented parallelism by writing something along the lines of:
```rust
let handles = (remainder..total).step_by(n_per_thread).map(|offset| spawn(decode[offset..offset + n_per_thread]))
// Evaluate remainder on this thread
(0..remainder).map(..)
for handle in handles { handle.await }
```
This got copied, but the copy began from 0 instead of `remainder`, which would cause OOB on the last partition:
```rust
(0..total).step_by(n_per_thread).map(|offset| tasks[offset..offset + n_per_thread])
```
Essentially, the original function was very prone to human error when being copied 😄
The intention behind the original function was that if we were to parallelize N tasks, we would keep and evaluate 1 of those …

fix: Fix index out of bounds panic on parquet prefiltering

---

crates/polars-error/src/lib.rs
crates/polars-ops/src/chunked_array/strings/find_many.rs
crates/polars-ops/src/series/ops/replace.rs
crates/polars-plan/src/dsl/function_expr/dispatch.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs

fix: Make `replace` and `replace_strict` properly elementwise

---

crates/polars-plan/src/plans/builder_ir.rs

feat(rust): Add more IRBuilder utils

---

crates/polars-compute/src/moment.rs

Ensures that for single-chunk moment calculations the two-pass algorithm output is directly used.

refactor(rust): Avoid combine when a weight is zero in moment.

---

crates/polars-expr/src/expressions/ternary.rs
crates/polars-plan/src/plans/aexpr/scalar.rs
py-polars/tests/unit/operations/test_window.py

* Fixes https://github.com/pola-rs/polars/issues/22478
Note, I haven't checked the other uses of `AggregationContext::with_values()` in the codebase.
This does **not** fix:
* https://github.com/pola-rs/polars/issues/22493
* It (could be) another misuse of `with_values()` for that one

fix: Fix incorrect ternary agg state with mixed columns and scalars

---

py-polars/polars/functions/lit.py

Ref: https://github.com/pola-rs/polars/pull/22177#discussion_r2066129875.
Ensures the `np.generic` check is behind a lazy dependency gate ("oops" 😅).

fix(python): Ensure numpy `isinstance` check is lazy (avoid forcing the dependency)

---

crates/polars-sql/src/sql_expr.rs
py-polars/tests/unit/sql/test_array.py
py-polars/tests/unit/sql/test_operators.py

Tweaked `SQLExprVisitor::array_expr_to_series` implementation to resolve a `FnMut` ownership/referencing issue that was preventing SQL support for using array literals within `IN` and `NOT IN` expressions.
(Also opportunistically closes #22463 to avoid triggering a `DeprecationWarning`).
```python
"rowid": [4, 3, 2, 1],
"values": [[1, 2], [3, 4], [5, 6], [7, 8]],
})
df.sql(
"""
SELECT * FROM self
WHERE values IN ([0], [5,6], [1,2], [8,8,8])
ORDER BY "rowid"
"""
)
```

feat: Add SQL support for checking array values with `IN` and `NOT IN` expressions

---

crates/polars-time/src/chunkedarray/string/strptime.rs
py-polars/tests/unit/operations/namespaces/test_strptime.py

fix: Invalid values were triggering panics instead of returning ``null`` in `dt.to_date` / `dt.to_datetime`

---

crates/polars-plan/src/plans/conversion/scans.rs
py-polars/tests/unit/io/test_lazy_csv.py
py-polars/tests/unit/io/test_lazy_json.py

* Fixes https://github.com/pola-rs/polars/issues/22514
The lazy schema was not updated with `schema_overrides` in DSL->IR schema inference. In older versions this just meant that `collect_schema()` would return an incorrect schema, as the old NDJSON reader would re-apply the schema_overwrite during execution. But this is problematic for the new-streaming NDJSON source as it scans according to the IR schema.

fix: Fix `schema_overrides` not taking effect in NDJSON

---

crates/polars-core/src/frame/mod.rs
crates/polars-lazy/src/frame/mod.rs
py-polars/tests/unit/operations/unique/test_unique.py

Fixes https://github.com/pola-rs/polars/issues/22470
This PR updates `unique_impl` to always slice after computing the full result, instead of slicing intermediate data (like groups or masks).
It also fixes the `UniqueKeepStrategy::None ` case, which previously could cause a shape mismatch when slicing the mask before filtering.

fix: Bug in `.unique()` followed by `.slice()`

---

crates/polars-expr/src/groups/binview.rs
crates/polars-expr/src/groups/mod.rs
crates/polars-expr/src/groups/row_encoded.rs
crates/polars-expr/src/groups/single_key.rs
crates/polars-stream/src/nodes/group_by.rs

Not sure yet if I want to end up nesting these, but in the case we do, we don't waste space on this for each grouper.

refactor: Don't store name/dtype in grouper

---

crates/polars-stream/src/nodes/zip.rs

The previous update would send `Blocked` to all inputs if any of them is blocked, but the zip should ignore an inputs own status and only consider the blocking status of the others when deciding whether or not to send to that input we are ready to receive from it.
For example, consider the following input scenario:
```
send:    R
recv: R R B R
```
In this scenario the old code would reply blocked to everything:
```
send:    B
recv: B B B B
```
But the following reply is more accurate:
```
send:    B
recv: B B R B
```
after all, should the third input switch to ready, everyone is ready.

refactor(rust): Improve zip state update

---

py-polars/polars/testing/asserts/frame.py

This does not resolve a particular issue. It is just a quick fix for a small error that I noticed while working on converting `assert_frame_equal()` from Python to Rust, supervised by @coastalwhite. I just ran an example and it still exists in the current iteration of `py-polars`.
There is a redundant `print()` statement before the `raise_assertion_error()` which essentially just prints the same exact information as the assertion error, resulting in output that looks like:
```python
{'a': Int64, 'b': Float64, 'c': String, 'd': Boolean} {'a': Float64, 'b': Float64, 'c': String, 'd': Int64}
Assertion Error: DataFrames are different (dtypes do not match)
[left]:  {'a': Int64, 'b': Float64, 'c': String, 'd': Boolean}
[right]: {'a': Float64, 'b': Float64, 'c': String, 'd': Int64}
```
Removal …

fix(python): Remove redundant print statement in `assert_frame_schema_equal()`

---

crates/polars-stream/src/physical_plan/fmt.rs

This PR adds support for styling the nodes in the streaming physical plan graph and a legend.
Currently any in-memory engine fallback nodes are red,  potentially memory-intensive nodes are yellow.

feat: Highlight nodes in streaming phys plan graph

---

crates/polars-stream/src/physical_plan/fmt.rs

This PR changes the node label font to a fixed-width font for better readability. Monospace should map to the user's preferred fixed-width font. A sans-serif font is used for the label.

feat: Use fixed-width font in streaming phys plan graph

---

py-polars/polars/selectors.py

Fixes https://github.com/pola-rs/polars/issues/22536.

fix: Multi-selector regex expansion

---

crates/polars-arrow/src/array/binary/builder.rs
crates/polars-arrow/src/array/binview/builder.rs
crates/polars-arrow/src/array/boolean/builder.rs
crates/polars-arrow/src/array/builder.rs
crates/polars-arrow/src/array/fixed_size_binary/builder.rs
crates/polars-arrow/src/array/fixed_size_list/builder.rs
crates/polars-arrow/src/array/list/builder.rs
crates/polars-arrow/src/array/null.rs
crates/polars-arrow/src/array/primitive/builder.rs
crates/polars-arrow/src/array/struct_/builder.rs
crates/polars-arrow/src/bitmap/builder.rs
crates/polars-core/src/chunked_array/object/builder.rs
crates/polars-core/src/frame/builder.rs
crates/polars-core/src/series/builder.rs

These kernels are needed for the streaming cross-join.

refactor(rust): Add extend_each_repeated to builders

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

Closes #22502.
I spiffied up the join docs a little bit. [Current docs for comparison](https://docs.pola.rs/api/python/stable/reference/dataframe/api/polars.DataFrame.join.html).
* Clarified the `coalesce` parameter
* Used tables for parameter descriptions, which IMO is much nicer looking.
* Declared default parameters.
* Fixed some minor formatting.
If people like this look with the description tables, I can update some of the other API docs too that have parameter list descriptions as well.
I don't think there's a way to show the results (can I generate docs in my fork's CI? Probably, not sure how to do it though), so here's a screenshot from local `DataFrame.join` (Lazyframe has same changes):

docs: Improve `join` documentation

---

py-polars/polars/dataframe/frame.py

* Adds the following docstring example that shows insert of an Expression, in addition to inserting a Series (it wasn't necessarily obvious that the function supports both).
```python
{"a": [2, 4, 2], "b": [0.5, 4, 10], "c": ["xx", "yy", "zz"]}
)
expr = (pl.col("b") / pl.col("a")).alias("b_div_a")
df.insert_column(2, expr)
```

docs(python): Improve `insert_column` docstring (description and examples)

---

crates/polars-plan/src/plans/ir/format.rs
crates/polars-plan/src/plans/ir/mod.rs
crates/polars-stream/src/physical_plan/fmt.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-stream/src/physical_plan/lower_group_by.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
crates/polars-stream/src/skeleton.rs

This now properly shows what is behind an `in-memory-map` and does some drive by clean-up on the plan.
```python
(
pl.LazyFrame({"x": [1], "y": [1], "j": [1]})
.select(pl.col.x.median(), pl.col.j.rolling_max(window_size=10))
.map_batches(lambda df: df)
.group_by('x', maintain_order=True).agg(pl.col.j)
.show_graph(engine='streaming', plan_stage='physical')
)
```

chore: Display the operation behind `in-memory-map`

---

crates/polars-ops/src/frame/pivot/mod.rs
py-polars/tests/unit/operations/test_pivot.py

Fixes #22543.
Missing match arm for `Time` dtype. Parametrized test to check for all dtypes. OP test result fixed:
```python
{
"a": [1, 2, 3, 4],
"col": ["a", "a", "b", "b"],
"time": ["13:00:00", "14:00:00", "13:00:00", "14:00:00"],
}
).with_columns(time=pl.col("time").str.to_time())
print(df.pivot(on="col", index="time"))
```
```
shape: (2, 3)
┌──────────┬─────┬─────┐
│ time     ┆ a   ┆ b   │
│ ---      ┆ --- ┆ --- │
│ time     ┆ i64 ┆ i64 │
╞══════════╪═════╪═════╡
│ 13:00:00 ┆ 1   ┆ 3   │
│ 14:00:00 ┆ 2   ┆ 4   │
└──────────┴─────┴─────┘
```

fix: Allow pivot on `Time` column

---

crates/polars-expr/src/expressions/apply.rs
crates/polars-expr/src/expressions/window.rs
crates/polars-expr/src/planner.rs
crates/polars-lazy/src/tests/aggregations.rs
crates/polars-lazy/src/tests/predicate_queries.rs
crates/polars-plan/src/dsl/function_expr/boolean.rs
crates/polars-plan/src/dsl/function_expr/business.rs
crates/polars-plan/src/dsl/function_expr/datetime.rs
crates/polars-plan/src/dsl/function_expr/list.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/range/mod.rs
crates/polars-plan/src/dsl/function_expr/strings.rs
crates/polars-plan/src/dsl/function_expr/struct_.rs
crates/polars-plan/src/dsl/functions/business.rs
crates/polars-plan/src/dsl/functions/concat.rs
crates/polars-plan/src/dsl/functions/horizontal.rs
crates/polars-plan/src/dsl/functions/temporal.rs
crates/polars-plan/src/dsl/mod.rs
crates/polars-plan/src/dsl/python_dsl/python_udf.rs
crates/polars-plan/src/dsl/string.rs
crates/polars-plan/src/plans/aexpr/predicates/skip_batches.rs
crates/polars-plan/src/plans/aexpr/properties.rs
crates/polars-plan/src/plans/aexpr/scalar.rs
crates/polars-plan/src/plans/optimizer/fused.rs
crates/polars-plan/src/plans/optimizer/simplify_expr/mod.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_expr.rs
crates/polars-plan/src/plans/options.rs
crates/polars-python/src/functions/misc.rs
crates/polars-stream/src/physical_plan/lower_expr.rs

This is the start of #22572.
This removes the `collect_groups` field on `FunctionOptions` and the `ApplyOptions` type. Instead, everything needed is now under `FunctionFlags`. This also splits elementwise into `row-separable` and `length preserving`.

refactor: Unify function flags into 1 bitset

---

crates/polars-io/src/csv/read/parser.rs
py-polars/tests/unit/io/test_lazy_count_star.py

* Fixes https://github.com/pola-rs/polars/issues/22564

fix: CSV count rows skipped last line if file did not end with newline

---

crates/polars-ops/src/series/ops/interpolation/interpolate.rs
py-polars/tests/unit/operations/test_interpolate.py

Fixes #22475. 
This includes `linear` and `nearest` methods.
Needs review. Consider:
* Return type is `Decimal`, not `f64`. Are we good with that?
* The interpolation is subject to accumulated precision gaps. See the test where interpolating `[1.0, None, None, 2.0]` returns `1.66` and not `1.67` for the second missing value. Below you can find an example edge case, e.g. when `step < 1` in physical and `n_steps` is high, see `signed_interp()` code. An alternative strategy would be to hold on to the Decimal type deeper into the implementation and/or update the algorithm (to be investigated).
* I was somehow expecting `cast()` to work similar to the other types but it doesn't - it casts an `Int128: 123` with `scale=2` to `123.00`. Most likely by design, still investigating.
* The use of …

fix: Fix interpolate on dtype Decimal

---

crates/polars-time/src/windows/duration.rs
py-polars/polars/expr/datetime.py
py-polars/polars/series/datetime.py
py-polars/tests/unit/operations/namespaces/temporal/test_truncate.py

fix: Consistently use Unix epoch as origin for ``dt.truncate`` (except weekly buckets which start on Mondays)

---

crates/polars-error/src/lib.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs

Related to #22596.
```python
"Column1": [1, 2],
"Column2": ["A", "B"]
})
df.select('Collumn1')
```
Makes the error go from 
```
File "/home/johndoe/Projects/polars/t.py", line 7, in <module>
df.select('Collumn1')
File "/home/johndoe/Projects/polars/py-polars/polars/dataframe/frame.py", line 9671, in select
return self.lazy().select(*exprs, **named_exprs).collect(_eager=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/johndoe/Projects/polars/py-polars/polars/_utils/deprecation.py", line 93, in wrapper
return function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/johndoe/Projects/polars/py-polars/polars/lazyframe/frame.py", line 2224, in collect
return …
```

chore: Remove confusing error context calling `.collect(_eager=True)`

---

py-polars/polars/_typing.py
py-polars/polars/dataframe/frame.py
py-polars/polars/dataframe/group_by.py
py-polars/polars/expr/expr.py
py-polars/polars/functions/lazy.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/lazyframe/group_by.py
py-polars/polars/series/series.py

In #19139, we introduced Equiprobable as a quantile method. However, the typing on the python side was never updated. Do this, and while touching the code, rename the type alias to QuantileMethod to match the Rust enum name.

refactor(python): Include equiprobable as valid quantile method

---

crates/polars-expr/src/expressions/gather.rs
py-polars/tests/unit/operations/test_gather.py

fixes #21610 
fixes #21553 
addresses panic but does not fix #22250 (*)
pending investigation #20478 (similar pattern, suspect different location in the code)
Kindly review. This addresses the panic's, but I am not confident stating this is the (only) right solution given the rich expression set.
Context from debugging: the `get()` gets mapped to `gather()` with `returns_scalar` set to `true`. This generates an aggregation context with state `AggregatedScalar` with inner `[i64]` but with `update_groups` set to `WithSeriesLen`. Later on, when `groups()` is called, the code panics. This only happens in advanced expressions, as `groups()` is not called unless needed. The submitted PR mimics the aggregation context from functions such as `first()` or `min()`, not `gather()`.
The other …

fix: Resolve `get()` SchemaMismatch panic

---

Cargo.lock
Cargo.toml
crates/polars-arrow/Cargo.toml
crates/polars-arrow/src/bitmap/mod.rs
crates/polars-arrow/src/bitmap/proptest.rs
crates/polars-parquet/Cargo.toml
crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/optional_masked_dense.rs
crates/polars-parquet/src/arrow/read/deserialize/dictionary_encoded/required_masked_dense.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/plain/mod.rs
crates/polars-parquet/src/parquet/encoding/hybrid_rle/mod.rs
crates/polars-parquet/src/parquet/encoding/hybrid_rle/proptest.rs
crates/polars/Cargo.toml

This was a bit of an experiment and learning project for me to see how `proptest` works. I want to see if it would be relatively simple to apply to testing of internals. I think the experiment was quite a success.
This PR just tests adds tests for some of the harder kernels from the parquet decoding.
Some of the takeaways:
- It is surprising to see how much faster it is then python hypothesis testing.
- We should quite easily be able define strategies for all our arrow array types.
- We circumvent the problems of `cargo-fuzz` where we start having to expose all of our internals and we don't need additional CI steps.
Overall, I would say this was a great success. We can expand on this.

chore: Add `proptest` testing for for parquet decoding kernels

---

crates/polars-ops/src/series/ops/round.rs
py-polars/tests/unit/series/test_series.py

Fixes https://github.com/pola-rs/polars/issues/22559.
cc @Julian-J-S

fix: Allow Expr.round() to be called on integer dtypes

---

crates/polars-arrow/src/array/struct_/builder.rs
crates/polars-core/src/frame/builder.rs
crates/polars-core/src/frame/mod.rs
crates/polars-plan/src/plans/optimizer/collapse_joins.rs
crates/polars-plan/src/plans/optimizer/mod.rs
crates/polars-stream/src/nodes/joins/cross_join.rs
crates/polars-stream/src/nodes/joins/mod.rs
crates/polars-stream/src/physical_plan/fmt.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/functions/as_datatype/test_concat_list.py
py-polars/tests/unit/operations/test_filter.py
py-polars/tests/unit/operations/test_pivot.py

This relieves a lot of memory pressure for plans with cross-joins as the full result doesn't have to be materialized at once.

perf: Add streaming cross-join node

---

py-polars/polars/series/series.py
py-polars/tests/unit/series/test_series.py

Closes #22620.
Simple ergonomic improvement (allow a literal value as "other" for Series `zip_with`), plus some additional test coverage.
```python
s1 = pl.Series("x", [153, 56, -45, 877, 37])
s2 = pl.Series("y", [56, 822, 4, 56, -345])
s1.zip_with(s1 <= s2, 0)
```

feat(python): Support use of literal values as "other" when evaluating `Series.zip_with`

---

crates/polars-plan/src/dsl/plan.rs

The `DSL_VERSION` is serialized as LE, but deserialized as BE. I changed the deserialization to LE since there are serialized DSLs out there already which contain the LE `DSL_VERSION`.

fix: DSL version deserialization endianness

---

crates/polars-core/src/chunked_array/arithmetic/decimal.rs
crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/logical/date.rs
crates/polars-core/src/chunked_array/logical/datetime.rs
crates/polars-core/src/chunked_array/logical/decimal.rs
crates/polars-core/src/chunked_array/logical/duration.rs
crates/polars-core/src/chunked_array/logical/mod.rs
crates/polars-core/src/chunked_array/logical/time.rs
crates/polars-core/src/chunked_array/temporal/datetime.rs
crates/polars-core/src/chunked_array/temporal/duration.rs
crates/polars-core/src/series/implementations/date.rs
crates/polars-core/src/series/implementations/datetime.rs
crates/polars-core/src/series/implementations/decimal.rs
crates/polars-core/src/series/implementations/duration.rs
crates/polars-core/src/series/implementations/time.rs
crates/polars-core/src/series/mod.rs
crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs
crates/polars-ops/src/chunked_array/gather/chunked.rs
crates/polars-python/src/conversion/chunked_array.rs
crates/polars-time/src/base_utc_offset.rs
crates/polars-time/src/chunkedarray/duration.rs
crates/polars-time/src/dst_offset.rs
crates/polars-time/src/month_end.rs
crates/polars-time/src/month_start.rs
crates/polars-time/src/offset_by.rs

This is a lot more readable than random `.0` and `.2`s everywhere.

refactor(rust): Use named fields for Logical

---

crates/polars-plan/src/dsl/builder_dsl.rs
py-polars/tests/unit/operations/test_drop.py

Fixes #22605
Listed here: https://gist.github.com/devdanzin/dc2ef895928fc5758ea66a1ccf2eedd2
Ping @devdanzin
---
**Before:**
```python
pl.DataFrame({"a": [1.0, float("nan")]}).drop_nans([])
```
```
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: ComputeError(ErrString("cannot return empty fold because the number of output rows is unknown"))
```
**After:**
```python
pl.DataFrame({"a": [1.0, float("nan")]}).drop_nans([])
```
```
shape: (2, 1)
┌─────┐
│ a   │
│ --- │
│ f64 │
╞═════╡
│ 1.0 │
│ NaN │
└─────┘
```

fix: Return input instead of panicking if empty subset in `drop_nulls()` and `drop_nans()`

---

crates/polars-core/src/frame/group_by/mod.rs
py-polars/tests/unit/operations/test_group_by.py

fixes #21959 
ping @coastalwhite 
This fixes the issue for `GroupByExec`. However, note that `PartitionGroupByExec` has dedicated functionality such as `keys()`/`compute_keys()` calling `check_expand_literals()` to ensure literals are expanded. If this approach is preferred, let me know and I will try to replicate and re-use this function.

fix: Panic on `group_by` with literal and empty rows

---

py-polars/polars/lazyframe/frame.py

This PR stabilizes
- `sink_parquet`
- `sink_ipc` (default `compression` changed to `uncompressed` to match `write_ipc`)
- `sink_csv`
- `sink_ndjson`
Fixes #11581.

chore: Stabilize `sink_*`

---

crates/polars-io/src/path_utils/hugging_face.rs
crates/polars-io/src/path_utils/mod.rs

* I wasn't able to reproduce locally, but this should fix https://github.com/pola-rs/polars/issues/22656

fix: Fix `index out of bounds` panic when scanning hugging face

---

crates/polars-plan/src/plans/aexpr/minterm_iter.rs
crates/polars-plan/src/plans/aexpr/properties.rs
crates/polars-plan/src/plans/conversion/convert_utils.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/optimizer/cache_states.rs
crates/polars-plan/src/plans/optimizer/mod.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/utils.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
py-polars/tests/unit/operations/test_slice.py
py-polars/tests/unit/test_predicates.py

* Fixes https://github.com/pola-rs/polars/issues/22284
Updates predicate pushdown to account for fallible expressions through the use of a new `ExprPushdownGroup` enum, where we categorize expressions into 3 groups - `Pushable`, `Fallible` and `Barrier` - I have left an explanation of these in comments in the code.
For detection of fallible expressions, I've added some commonly used ones - e.g. `strict-cast`, `strptime`, but there are likely much more expressions that should be caught.
This PR also adds a `POLARS_PUSHDOWN_OPT_MAINTAIN_ERRORS` flag. This can be used to ensure predicate pushdowns do not "mask" query errors by preventing predicates from being pushed past fallible projections.

fix: Fix predicate pushdown of fallible expressions

---

crates/polars-arrow/src/datatypes/field.rs
crates/polars-io/src/parquet/write/batched_writer.rs
crates/polars-io/src/parquet/write/mod.rs
crates/polars-io/src/parquet/write/options.rs
crates/polars-io/src/parquet/write/writer.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-parquet/src/arrow/write/file.rs
crates/polars-parquet/src/arrow/write/mod.rs
crates/polars-parquet/src/arrow/write/pages.rs
crates/polars-parquet/src/arrow/write/row_group.rs
crates/polars-parquet/src/arrow/write/schema.rs
crates/polars-plan/src/dsl/plan.rs
crates/polars-plan/src/plans/conversion/type_check/mod.rs
crates/polars-python/src/dataframe/io.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-stream/src/nodes/io_sinks/parquet.rs
crates/polars/tests/it/io/parquet/arrow/mod.rs
crates/polars/tests/it/io/parquet/arrow/write.rs
crates/polars/tests/it/io/parquet/roundtrip.rs
py-polars/docs/source/reference/io.rst
py-polars/polars/io/__init__.py
py-polars/polars/io/parquet/__init__.py
py-polars/polars/io/parquet/field_overwrites.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/io/test_parquet.py

This implements the start of #22278.
This is needed for Iceberg writing.

feat: Add options to write Parquet field metadata

---

py-polars/polars/expr/string.py

fix: Don't mark `str.replace_many` with Mapping as deprecated

---

py-polars/polars/convert/general.py
py-polars/polars/datatypes/convert.py
py-polars/polars/io/database/_executor.py
py-polars/polars/io/database/_inference.py
py-polars/tests/unit/interop/test_interop.py
py-polars/tests/unit/io/database/test_inference.py

A few databases support `Int128` datatypes as "HUGEINT" or "INT128" (for example, DuckDB). This PR adds support for dtype inference from these type names, and also slightly improves integer type name parsing.
A few minor updates to `from_repr` allow it to additionally parse DuckDB table-repr strings, so users can trivially drop such examples into Polars (the updated typename parsing makes translating their table-repr dtypes simple).
```python
df = pl.from_repr("""
┌────────────┬───────┬────────────────┬───────────────────┐
│   As Of    │ Rank  │ Days In Top 10 │ Streaming Seconds │
│    date    │ int32 │     int16      │      int128       │
├────────────┼───────┼────────────────┼───────────────────┤
│ 2025-05-09 │     1 │             29 │  5864939402857430 │
│ …
```

feat(python): Support inference of `Int128` dtype from databases that support it

---

crates/polars-python/src/dataframe/construction.rs
crates/polars-python/src/series/construction.rs
crates/polars-sql/src/sql_expr.rs
py-polars/polars/_utils/construction/dataframe.py
py-polars/polars/_utils/construction/series.py
py-polars/polars/_utils/construction/utils.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/io/database/test_read.py

Added a path for `from_records` (and DataFrame/Series construction) that can handle conversion from`PyMapping` in the Rust/pyO3 layer (currently we only handle `PyDict`).
This opens up efficient init from other useful Python record types that _look_ like dicts to the caller (and support the `Mapping` protocol), but that we couldn't load as such.
**Also:**
Fixes two long-standing errors with `from_records`, adding test coverage for both -
1) Incorrectly loading as Struct if the _first_ record was a `None` value.
2) Failing to load _at all_ if a `None` value was present _after_ the first element.
`TypeError: 'NoneType' object cannot be converted to 'PyDict'`
**And:** 
Optimises `PyDict` value lookup (by precomputing the keys as `PyString` so we don't create them in the row-building loop). …

feat: Support optimised init from non-dict `Mapping` objects in `from_records` and frame/series constructors

---

crates/polars-lazy/src/dsl/list.rs
py-polars/tests/unit/conftest.py
py-polars/tests/unit/operations/namespaces/list/test_list.py
py-polars/tests/unit/operations/test_join.py

Eligible expressions passed to `list.eval` can be directly applied over the underlying values:
* `ExprPushdownGroup::Pushable` (fully elementwise, non-fallible)
* `ExprPushdownGroup::Fallible` only if there are no masked out elements.
The targeted use case for this is extracting struct fields from within a `list[struct{}]` column `list.eval(pl.element().struct.field(<name>))`, which can be a fairly common operation.
Comparing the execution time when going from 100 rows to 10,000 rows, we go from a `~45x` slowdown on the PyPI release `1.29.0` to a `~8.9x` slowdown on this branch in a debug build.
* Supercedes https://github.com/pola-rs/polars/pull/21556

perf: Add elementwise execution mode for `list.eval`

---

crates/polars-lazy/src/frame/mod.rs
crates/polars-mem-engine/src/executors/cache.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-pipe/src/pipeline/convert.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/conversion/mod.rs
crates/polars-plan/src/plans/ir/dot.rs
crates/polars-plan/src/plans/ir/format.rs
crates/polars-plan/src/plans/ir/inputs.rs
crates/polars-plan/src/plans/ir/mod.rs
crates/polars-plan/src/plans/optimizer/expand_datasets.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/projection_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
crates/polars-plan/src/plans/visitor/hash.rs
crates/polars-python/src/lazyframe/visitor/nodes.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/utils/late_materialized_df.rs
crates/polars-utils/src/lib.rs
crates/polars-utils/src/unique_id.rs
py-polars/tests/unit/io/test_lazy_parquet.py

* Fixes https://github.com/pola-rs/polars/issues/22641
> sum_horizontal is calling into rayon here from the new-streaming parquet statistics evaluation, but the single rayon thread is blocked on the StreamingQueryExecutor.
Possible solutions I could think of:
(2) is very much a hack, but it's a hack that's nicely confined to the in-mem engine (which is also the only place where it's needed). In the future after everything runs on new-streaming, it may no longer be needed.

fix: Fix deadlock joining scanned tables with low thread count

---

py-polars/tests/unit/operations/namespaces/list/test_list.py

Test failure in CI at https://github.com/pola-rs/polars/actions/runs/14980822260/job/42084272257?pr=22728
We increase from 100k to 1M rows, and ensure it is single threaded by doing a rechunk. This runs on the latest (1.29) release with an 80x slowdown, compared to 1x (no slowdown) for the current main (since the elementwise eval of extracting a struct field is `O(1)`).

test(python): Fix unstable `list.eval` performance test

---

crates/polars-plan/src/dsl/string.rs
crates/polars-python/src/conversion/any_value.rs
py-polars/tests/unit/dataframe/test_df.py

Small follow-up to #22638.
* Adds generic `AnyValue` conversion support for `PyMapping` values.
* Adds test coverage for the same.

feat: Support `AnyValue` translation from `PyMapping` values

---

crates/polars-sql/src/types.rs
crates/polars-time/src/chunkedarray/string/patterns.rs
py-polars/tests/unit/operations/namespaces/test_strptime.py
py-polars/tests/unit/sql/test_temporal.py

Addresses an Issue raised on the Discord (in the `#sql` channel) by @etrotta.
* Generic time-string parsing improvement (adds `%R` chrono [hour-minute format](https://docs.rs/chrono/latest/chrono/format/strftime/index.html#:~:text=Hour%2Dminute%20format) to the set of recognised time specifiers - which we already identify in datetime strings).
* Brings SQL temporal literal string inference in-line with the underlying `to_datetime` and `to_time` functions so that hour-minute format (`%R`, aka:`%H:%M`) is also recognised in the SQL interface (both standalone, as a time, and as part of a larger datetime/timestamp string). A subsequent/follow-up PR will bring a similar improvement to SQL `CAST` ops.
Use of `'%H:%M'` literal strings in WHERE clauses:
```python
df = …
```

feat: Improved time-string parsing and inference (generally, and via the SQL interface)

---

crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/slice.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_pipelines/generic.rs
crates/polars-stream/src/physical_plan/to_graph.rs

* Fixes https://github.com/pola-rs/polars/issues/22683
There have been reports of performance regressions from users that scan 10,000's of small parquet files from the cloud. This is likely due to some default settings in the new-streaming I/O scans. In this PR we address this by:
* Increasing the default reader pre-initialization (i.e. parquet metadata fetch/decode) limit from 3 to `num_pipelines + 3`
* Adds a `POLARS_NUM_READERS_PRE_INIT` environment variable to allow this to be controlled
* Adds a verbose print line so that we can see the value used in the logs
* Changing the default concurrent reader limit from 8 to `num_pipelines`
* System: AWS EC2 `c6gn.8xlarge` (32 cores)
* Query: Full scan 1,000 parquet files (10,000 rows / ~1.1MB each)
* Build profile: Debug
| Configuration | # …

perf: Increase default cross-file parallelism limit for new-streaming multiscan

---

py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/series.py

Closes #22658
- Make sure all variants for `drop`/`fill` refer to the corresponding counterpart. For instance, `drop_nulls` will refer to `drop_nans` and vice-versa.
- For all variants, replicate a pre-existing notes (found in some cases) to indicate that "floating point NaNs (Not a Number) are not missing values" and vice-versa.

docs: Rework documentation for `drop`/`fill` for nulls/nans

---

crates/polars-core/src/chunked_array/logical/categorical/ops/append.rs
py-polars/tests/unit/series/test_append.py

fix: Don't merge `Enum` categories on append

---

py-polars/docs/source/reference/dataframe/modify_select.rst
py-polars/docs/source/reference/lazyframe/modify_select.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

Just adding reference entries for the new methods.
I added some blank lines to prevent mangling of the code examples:
<blockquote>
</blockquote>
Not sure if there is some lint rule to check for this?
It seems to happen with:
```python
foobar
>>> code here
```

docs(python): Add `match_to_schema` to API reference

---

crates/polars-stream/src/nodes/io_sinks/partition/mod.rs
py-polars/polars/dataframe/frame.py
py-polars/tests/unit/io/test_partition.py

fix: Correct the output order of `PartitionByKey` and `PartitionParted`

---

crates/polars-plan/src/dsl/array.rs
crates/polars-plan/src/dsl/function_expr/array.rs
crates/polars-plan/src/dsl/function_expr/list.rs
crates/polars-plan/src/dsl/list.rs
crates/polars-plan/src/dsl/plan.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
crates/polars-python/src/expr/array.rs
crates/polars-python/src/expr/list.rs
crates/polars-sql/src/functions.rs
py-polars/polars/expr/array.py
py-polars/polars/expr/list.py
py-polars/polars/series/array.py
py-polars/polars/series/list.py
py-polars/tests/unit/operations/namespaces/array/test_array.py
py-polars/tests/unit/operations/namespaces/list/test_list.py

Fixes #22755.
xref: #22754.
Note that as opposed to `.is_in` the nulls_equal is set to `True` by default to keep backwards compatible behavior.

feat: Add `nulls_equal` flag to `list/arr.contains`

---

crates/polars-plan/src/plans/ir/format.rs

Also skips formatting when it's None.
Before:
After:

refactor: Hide option in scan ID formatting

---

docs/source/polars-cloud/explain/authentication.md

Small fix to change a broken link in the Polars Cloud docs

docs: Fix broken link to service account page in Polars Cloud docs

---

crates/polars-compute/src/rolling/nulls/quantile.rs
py-polars/tests/unit/operations/rolling/test_rolling.py

fixes #22781
Minor change. Addresses panic, with test coverage expanded.
Kindly review the expected value in the test.

fix: Panic on quantile over nulls in rolling window

---

py-polars/polars/_utils/various.py
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/series.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/dataframe/test_equals.py
py-polars/tests/unit/dataframe/test_extend.py
py-polars/tests/unit/dataframe/test_merge_sorted.py
py-polars/tests/unit/dataframe/test_vstack.py
py-polars/tests/unit/lazyframe/test_lazyframe.py
py-polars/tests/unit/lazyframe/test_merged_sorted.py
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/series/test_append.py
py-polars/tests/unit/series/test_equals.py
py-polars/tests/unit/series/test_extend.py
py-polars/tests/unit/series/test_zip_with.py
py-polars/tests/unit/test_errors.py

Closes #22677 
Add a simple util function to confirm two objects are of the same type. Raise TypeError if that's not the case. There are two targets with this change:
* Easier onboarding of beginners to polars.
* Quicker inspection of this tedious error.
Also add several unit tests for affected methods

fix: Add type equality checking for relevant methods

---

Cargo.lock
crates/polars-arrow/Cargo.toml

Essentially I ran https://crates.io/crates/cargo-shear and checked that things worked with `make test` and `make check` inside `crates/`.
That tool still has some issues (https://github.com/Boshen/cargo-shear/issues/184), so I wasn't able to run it completely for all of Polars. Nevertheless, it worked for `polars-arrow` and it will save a couple crate downloads in CI according to the `Cargo.lock` changes.

chore(rust): Remove unused dependencies in `polars-arrow`

---

.typos.toml
flake.lock
flake.nix

Updates the `importCargoLock` outputHashses for the git based dependencies and uses my fork of nixpkgs while we wait for upstream https://github.com/NixOS/nixpkgs/pull/408174 to be merged.
cc @coastalwhite

chore: Fix `nix build`

---

crates/polars-error/Cargo.toml
crates/polars-parquet/Cargo.toml
crates/polars-parquet/src/parquet/metadata/column_chunk_metadata.rs
crates/polars-parquet/src/parquet/metadata/column_descriptor.rs
crates/polars-parquet/src/parquet/metadata/column_order.rs
crates/polars-parquet/src/parquet/metadata/schema_descriptor.rs
crates/polars-parquet/src/parquet/metadata/sort.rs
crates/polars-parquet/src/parquet/parquet_bridge.rs
crates/polars-parquet/src/parquet/schema/types/basic_type.rs
crates/polars-parquet/src/parquet/schema/types/converted_type.rs
crates/polars-parquet/src/parquet/schema/types/parquet_type.rs
crates/polars-parquet/src/parquet/schema/types/physical_type.rs
crates/polars-plan/Cargo.toml
crates/polars-plan/src/dsl/dt.rs
crates/polars-plan/src/dsl/function_expr/datetime.rs
crates/polars-plan/src/dsl/function_expr/temporal.rs
crates/polars-plan/src/dsl/functions/temporal.rs
crates/polars-plan/src/dsl/python_dsl/python_udf.rs
crates/polars-plan/src/plans/aexpr/properties.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
crates/polars-plan/src/plans/python/predicate.rs
crates/polars-plan/src/plans/python/pyarrow.rs
crates/polars-python/src/lazyframe/visitor/expr_nodes.rs
crates/polars-stream/Cargo.toml
crates/polars-testing/Cargo.toml

This PR adds missing features that prevent each crate from building on its own.
- `polars-error`: requires `arrow-format/ipc`
- `polars-parquet`: renamed `serde_types` feature to `serde`, requires `polars-utils/serde`
- `polars-plan`
- `python` requires `polars-core/object`
- `dynamic_group_by` requires either `dtype-date` or `dtype-datetime`, added dependency on both to prevent complex `cfg` attributes within the crate
- added missing `#[cfg(feature = "dtype-duration")]` within the crate
- added missing `#[cfg(feature = "string_normalize")]` within the crate
- `polars-stream`
- `dynamic_group_by` requires `polars-plan/dynamic_group_by`, `polars-expr/dynamic_group_by` and `polars-mem-engine/dynamic_group_by`
- `python` requires `polars-mem-engine/python`
- `polars-testing`
- requires …

build: Add missing features

---

.github/workflows/test-python.yml

To make sure the free-threaded build keeps compiling, this PR adds a basic import smoke tests. Full test coverage will be worked on in #21914.
Superseded #22466

chore(python): Add basic smoke test for free-threaded python

---

crates/polars-plan/src/dsl/file_scan/mod.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
crates/polars-python/src/conversion/mod.rs
py-polars/tests/unit/operations/test_cast.py
py-polars/tests/unit/test_predicates.py

~~Also ensures the cast is removed for `E.cast(<dtype>)` if `E` is already the same type.~~
* I will split this to a separate PR to avoid regressions (this remove casts, meaning it relies on IR schema correctness).
.
* Fixes https://github.com/pola-rs/polars/issues/22668
* Fixes https://github.com/pola-rs/polars/issues/22849

perf: Switch eligible casts to non-strict in optimizer

---

crates/polars-core/src/config.rs
crates/polars-io/src/cloud/credential_provider.rs
crates/polars-io/src/cloud/options.rs
py-polars/polars/_utils/logging.py
py-polars/polars/io/cloud/credential_provider/_builder.py
py-polars/polars/io/cloud/credential_provider/_providers.py
py-polars/tests/unit/io/cloud/test_credential_provider.py

* Fixes https://github.com/pola-rs/polars/issues/21784
* Fixes https://github.com/pola-rs/polars/issues/18420
Note, this will require `boto3` to be installed on the system that executes the query. It is not compatible with:
* Passing a custom credential provider to `credential_provider` (or passing `None`)

feat(python): Load AWS `endpoint_url` using boto3

---

crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/range/int_range.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
py-polars/tests/unit/functions/range/test_int_range.py

As mentioned in https://github.com/pola-rs/polars/issues/22640, `int_ranges` would silently cast non-integer inputs to null.
By doing a `strict_cast`, we ensure that output message throws correctly indicating an invalid input. 
The `strict_cast` is ideal in this scenario because any unrepresentable value will have been set to null which would trigger a polars error.

fix: Correct `int_ranges` to raise error on invalid inputs

---

crates/polars-core/src/utils/mod.rs
crates/polars-ops/src/series/ops/arg_min_max.rs
crates/polars-ops/src/series/ops/index_of.rs
py-polars/tests/unit/operations/test_index_of.py
py-polars/tests/unit/series/test_series.py

Spotted some nice speedups for the lower-level `first_not_null` and `last_non_null` validity/bitmap scans while working on #22880; breaking them out as a standalone PR so we can take advantage while deciding on a better API for that one.
So, switching out the following offset calculations...
```rust
mask = BitMask::from_bitmap(validity) 
Some(n) = mask.nth_set_bit_idx(0, 0)               // first non-null
Some(n) = mask.nth_set_bit_idx_rev(0, mask.len())  // last non-null
```
...for (more or less)...
```rust
validity.leading_zeros() < validity.len()   // first non-null
validity.trailing_zeros() < validity.len()  // last non-null
```
...and adjusting the surrounding code slightly allows us to get the required result directly from the validity bitmap _without_ mediating via `BitMask` and …

perf: Optimise low-level `null` scans and `arg_max` for bools (when chunked)

---

crates/polars-expr/src/reduce/mod.rs
crates/polars-lazy/src/frame/mod.rs
crates/polars-plan/src/dsl/options/sink.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/conversion/mod.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-python/src/lazyframe/sink.rs
crates/polars-python/src/on_startup.rs
crates/polars-stream/src/nodes/io_sinks/ipc.rs
crates/polars-stream/src/nodes/io_sinks/metrics.rs
crates/polars-stream/src/nodes/io_sinks/mod.rs
crates/polars-stream/src/nodes/io_sinks/parquet.rs
crates/polars-stream/src/nodes/io_sinks/partition/by_key.rs
crates/polars-stream/src/nodes/io_sinks/partition/max_size.rs
crates/polars-stream/src/nodes/io_sinks/partition/mod.rs
crates/polars-stream/src/nodes/io_sinks/partition/parted.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/mod.rs
crates/polars-stream/src/physical_plan/to_graph.rs
crates/polars-utils/src/lib.rs
crates/polars-utils/src/python_convert_registry.rs
py-polars/polars/io/partition.py
py-polars/tests/unit/io/test_partition.py

This adds 2 items to partition sinks
- `per_partition_sort_by` which sorts a partition before writing by certain expressions
- `finish_callback` which gets called with information about all the written files in the partition
These are needed for better Iceberg support.

feat: Add per partition sort and finish callback to sinks

---

py-polars/docs/source/reference/series/modify_select.rst

i think this was forgotten in https://github.com/pola-rs/polars/pull/22902/files

docs(python): Add missing `top_k_by` and `bottom_k_by` to `Series` reference

---

py-polars/docs/source/reference/lazyframe/modify_select.rst
py-polars/polars/lazyframe/frame.py

We have an entry for DataFrame `__getitem__`, this adds the same for LazyFrame (and fixes the type signature - we only accept `slice` here, not `int` or `range`). 
**Note:** looks like we need `__setitem__` entries for DataFrame and Series too; can look at those later.

docs: Add missing entry for LazyFrame `__getitem__`

---

py-polars/polars/expr/expr.py
py-polars/tests/unit/interop/numpy/test_ufunc_expr.py

fixes https://github.com/pola-rs/polars/issues/22874

fix: Return early in pl.Expr.__array_ufunc__ when only single input

---

py-polars/polars/_utils/various.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/dataframe/test_equals.py
py-polars/tests/unit/dataframe/test_extend.py
py-polars/tests/unit/dataframe/test_merge_sorted.py
py-polars/tests/unit/dataframe/test_vstack.py
py-polars/tests/unit/lazyframe/test_lazyframe.py
py-polars/tests/unit/lazyframe/test_merged_sorted.py
py-polars/tests/unit/series/test_equals.py
py-polars/tests/unit/series/test_zip_with.py

Closes #22914.
In #22802, I added a check for methods that expect an argument of the same type. The check raised if the `other` argument was not of the same type as the object itself. However, this check is too restrictive, as sometimes we want to provide objects that are subclassed. For that reason, modify the check to be less restrictive and allow for that flow.
Also modify `bad_input_type` types of unittests add add sub-tests that do not raise when subclassed objects are used.

fix: Allow subclasses in type equality checking

---

crates/polars-core/src/fmt.rs
crates/polars-python/src/map/mod.rs
crates/polars-python/src/map/series.rs
crates/polars-python/src/series/map.rs
py-polars/tests/unit/datatypes/test_object.py

fix(python): Guard against invalid nested objects in 'map_elements'

---

crates/polars-io/src/ipc/ipc_file.rs
crates/polars-io/src/parquet/read/options.rs
crates/polars-lazy/src/scan/anonymous_scan.rs
crates/polars-lazy/src/scan/csv.rs
crates/polars-lazy/src/scan/ipc.rs
crates/polars-lazy/src/scan/ndjson.rs
crates/polars-lazy/src/scan/parquet.rs
crates/polars-lazy/src/tests/io.rs
crates/polars-plan/src/dsl/file_scan/mod.rs
crates/polars-plan/src/plans/optimizer/expand_datasets.rs
crates/polars-python/src/conversion/mod.rs
crates/polars-python/src/io/mod.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-python/src/lib.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/mod.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
py-polars/polars/io/__init__.py
py-polars/polars/io/parquet/functions.py
py-polars/polars/io/scan_options/__init__.py
py-polars/polars/io/scan_options/_options.py
py-polars/polars/io/scan_options/cast_options.py
py-polars/tests/unit/io/test_lazy_parquet.py
py-polars/tests/unit/io/test_multiscan.py
py-polars/tests/unit/io/test_scan_options.py

Supercedes https://github.com/pola-rs/polars/pull/22695
* ref https://github.com/pola-rs/polars/issues/22450
Changes:
* Adds an `extra_columns` to `scan_parquet`
* (Rust) `extra_columns_policy` is now added under `UnifiedScanArgs`
* Introduces an internal `ScanOptions` Python class to consolidate input parsing of shared scan options (i.e. those in `UnifiedScanArgs`).
Fixes:
* Fixes https://github.com/pola-rs/polars/issues/22218
* This wasn't fixed until now, as users would not have been able to scan this case without the `extra_columns` parameter

feat(python): Add `extra_columns` parameter to `scan_parquet`

---

py-polars/polars/_utils/parse/expr.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/test_projections.py

Fixes https://github.com/pola-rs/polars/issues/17879
This enables dictionary information (which is a raw python `iterable` type under the hood) to not be passed to the `with_columns` operator. 
By guarding at the python level, this prevents it ever hitting the query planner and doing further work. 
Information in the format of a dictionary should be explicitly stated to meet the API requirements.

fix(python): Guard against dictionaries being passed to `with_columns`

---

py-polars/polars/datatypes/classes.py
py-polars/tests/unit/constructors/test_constructors.py

Currently, `pl.Int64.is_(pl.Int64)` is revealed as `Any`, as opposed to `bool`. This PR fixes that
@alexander-beedie fancy taking a look?
I spotted this while trying out `pyright --verifytypes polars --ignoreexternal` ([pyright-cov](https://github.com/MarcoGorelli/pyright-cov)), and this simple change is enough to bring PyRight's reported type completeness up by 26 percentage points (from 69% to 95%). Separately from this, do we want to enforce a minimum type completeness in CI, to ensure this doesn't regress?

fix(python): Narrow return type for `DataType.is_`, improve Pyright's type completeness from 69% to 95%

---

crates/polars-stream/src/nodes/io_sinks/ipc.rs
py-polars/tests/unit/io/test_lazy_ipc.py

fix: Setting `compat_level=0` for `sink_ipc`

---

crates/polars-io/src/parquet/read/reader.rs
crates/polars-python/src/io/mod.rs
crates/polars-python/src/lazyframe/general.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/missing_columns.rs
py-polars/polars/io/delta.py
py-polars/polars/io/iceberg/dataset.py
py-polars/polars/io/parquet/functions.py
py-polars/polars/io/scan_options/_options.py
py-polars/tests/unit/io/test_lazy_parquet.py
py-polars/tests/unit/io/test_multiscan.py
py-polars/tests/unit/io/test_parquet.py
py-polars/tests/unit/io/test_scan.py

* ref https://github.com/pola-rs/polars/issues/21997
* Depends on https://github.com/pola-rs/polars/pull/22699

depr(python): Deprecate `allow_missing_columns` in `scan_parquet` in favor of `missing_columns`

---

py-polars/polars/_utils/construction/dataframe.py

I think the pandas stubs aren't quite correct here, as `Hashable` is allowed, not just `int | str`:
```python
In [1]: import pandas as pd
In [2]: from datetime import datetime, date
In [3]: pd.DataFrame({date(2020,1,1): [1,2,3], date(2020,1,2): [2,3,4]}).set_index([date(2020,1,1), date(2020,1,2)]).index.get_level_values(date(2020,1,1))
Out[3]: Index([1, 2, 3], dtype='int64', name=2020-01-01)
```
So, I think it's ok to type ignore

chore(python): Fix CI for latest pandas-stubs release

---

crates/polars-io/src/csv/read/parser.rs
crates/polars-plan/src/plans/functions/count.rs
py-polars/tests/unit/io/test_csv.py
py-polars/tests/unit/io/test_lazy_count_star.py

fixes #22889
(Sorry @nameexhaustion , I did not realize you already self-assigned this, just seeing it now, my bad)
Submitting as draft to get feedback, as I lack some context on the multiple CSV routines, their history and potential performance tradeoffs. This issue involves FastCount, introduced for `count(*)` performance, see https://github.com/pola-rs/polars/pull/14574
* Is this the right place to fix it?
* On `schema_len` (see code): there is a minor inconsistency in the code on how we handle a leading blank line in case there is an UTF8-BOM and `schema_len == 1`. That said inferring schema may have a negative performance effect, as by default 100 rows will be parsed. Let me know if we want to infer schema_length consistently, that should not be hard. 
On a related note, is the …

fix: Support `skip_lines` for `scan_csv` with `pl.len()`

---

.github/workflows/test-python.yml
crates/polars-stream/src/nodes/io_sources/csv.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/apply.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_pipelines/generic.rs
py-polars/tests/unit/io/test_lazy_csv.py
py-polars/tests/unit/io/test_multiscan.py

Instead of before, as it would end up sliced out anyway.
* Adds `POLARS_FORCE_EMPTY_READER_CAPABILITIES` for test coverage, this forces all operations to be applied in post
* Drive-by - fixes https://github.com/pola-rs/polars/issues/22996

perf: Move row index materialization in post-apply to occur after slicing

---

crates/polars-expr/src/expressions/group_iter.rs

Running the tests with a standard library that has debug assertions enabled currently triggers an assertion failure [here](https://github.com/rust-lang/rust/blob/6de3a733122a82d9b3c3427c7ee16a1e1a022718/library/core/src/iter/traits/iterator.rs#L2024) due to a malformed `size_hint()`. Example:
```
thread 'polars-1' panicked at [...]/library/core/src/iter/traits/iterator.rs:2024:13:
Malformed size_hint (3, Some(0))
test tests::aggregations::test_binary_agg_context_2 ... FAILED
```
This can also be reproduced by adding a well-formedness assertion (`assert!(self.len <= self.offset)`, i.e. the lower bound must not be greater than the upper bound) here:
https://github.com/pola-rs/polars/blob/ba1293c27632dd366c69a7727fd99cc837edd99b/crates/polars-expr/src/expressions/group_iter.rs#L185-L187
My …

fix(rust): Fix incorrect `size_hint()` for `FlatIter`

---

crates/polars-python/src/conversion/mod.rs
crates/polars-python/src/io/mod.rs
crates/polars-python/src/lazyframe/general.rs
py-polars/polars/io/parquet/functions.py
py-polars/polars/io/scan_options/_options.py

Eventually should allow us to de-duplicate a lot of parameter parsing logic across scan types as well as supporting more parameters for them.

refactor: Move scan parameter parsing for parquet to reusable function

---

crates/polars-plan/src/plans/conversion/dsl_to_ir.rs
crates/polars-plan/src/plans/conversion/mod.rs
crates/polars-plan/src/plans/conversion/scans.rs
py-polars/tests/unit/io/test_multiscan.py

```python
polars.exceptions.SchemaError: extra column in file outside of expected schema: index
polars.exceptions.DuplicateError: cannot add row_index with name 'index': column already exists in file.
```

fix: Fix confusing error message on duplicate row_index

---

crates/polars-core/src/datatypes/dtype.rs
py-polars/tests/unit/series/test_append.py

I took a small liberty to take a stab at https://github.com/pola-rs/polars/issues/22639.
This patch changes the behavior of `DataType::matches_schema_type` such that structs wit different numbers of fields are not considered to match, not even with a cast.

fix: Do not schema-match structs with different field counts

---

py-polars/polars/_utils/pycapsule.py
py-polars/tests/unit/constructors/test_constructors.py
py-polars/tests/unit/interchange/test_from_dataframe.py
py-polars/tests/unit/interop/test_interop.py

closes https://github.com/pola-rs/polars/issues/23068
Based on the tests, there was an assumption that objects implementing `__arrow_c_array__` were `pyarrow.record_batch`es that wanted to be `unnest`ed. I don't think this is correct in the general case; therefore, the tests were updated to manually call `unnest`

fix(python): Don't call unnest for objects implementing `__arrow_c_array__`

---

crates/polars-compute/src/rolling/min_max.rs
py-polars/tests/unit/operations/test_rolling.py

Fixes https://github.com/pola-rs/polars/issues/23066.

fix: Incorrect null count in rolling_min/max

---

crates/polars-io/src/predicates.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-mem-engine/src/predicate.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/predicate.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/io/test_hive.py

* Fixes https://github.com/pola-rs/polars/issues/23005
We currently evaluate hive predicates using a `skip_batch_predicate` that was designed for parquet statistics. This is essentially an expression that operates on a `DataFrame` containing `{column}_min`, `{column}_max` columns.
The hive partitions were converted to such a `DataFrame`, however this is not compatible as `skip_batch_predicate` interprets NULL as "statistics are missing" and indicates that the data must be read, whereas in hive a NULL indicates that the actual row values are all NULL.
This PR changes it to directly use the original predicate expression. It is more of a quick fix as I am expecting to do larger refactors around predicate handling in the future for iceberg.

fix: Fix hive partition pruning not filtering out `__HIVE_DEFAULT_PARTITION__`

---

crates/polars-core/src/chunked_array/mod.rs

Closes #23079 
I need this to build a four-way versions of `align_chunks_ternary` for a Polars Expression plugin that I'm building.

feat(rust): Make match_chunks public

---

.github/workflows/test-python.yml
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/apply.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/deletion_files.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/initialization/slice.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/post_apply_pipeline/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_pipelines/generic.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/row_counter.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/io/test_scan_row_deletion.py

Finishes adding support for Iceberg position deletes. Internally, this adds generic logic for performing row deletions to the new-streaming multi-scan using a filter mask, which should allow for code re-use for other formats e.g. Iceberg V3 deletion vectors / Delta deletion vectors.
* Changed the semantics of the row count being sent to the post-apply pipeline (`current_row_position` parameter to `ApplyExtraOps::apply_to_df()`).
* Before - `current_row_position: 0` points to the first morsel, and `row_index.offset` is mutated during initialization to account for skipped rows (i.e. non-zero offset slice pushed to reader).
* After - `current_row_position: 0` points to the start of the file, and we do not mutate `row_index.offset`. This is preferred, as the old approach would require us to …

feat: Native implementation for Iceberg positional deletes

---

crates/polars-plan/src/plans/lit.rs

supersedes #22964
closes #22963

fix(rust): Don't create i128 scalars if dtype-128 is not set

---

crates/polars-plan/Cargo.toml

Currently attempting to run a `#[test]` in `polars-stream` fails due to this:
```rust
Compiling polars-mem-engine v0.48.1 (/Users/nxs/git/polars/crates/polars-mem-engine)
error[E0425]: cannot find function `serialize` in module `polars_plan::plans::python::predicate`
--> crates/polars-mem-engine/src/planner/lp.rs:188:75
|
188 |             predicate_serialized = polars_plan::plans::python::predicate::serialize(&dsl_expr)?;
|                                                                           ^^^^^^^^^ not found in `polars_plan::plans::python::predicate`
|
note: found an item that was configured out
--> /Users/nxs/git/polars/crates/polars-plan/src/plans/python/predicate.rs:6:8
|
6   | pub fn serialize(expr: &Expr) -> PolarsResult<Option<Vec<u8>>> {
|        ^^^^^^^^^
note: the item …
```

fix(rust): Enable serde feature with python in `polars-mem-engine`

---

py-polars/polars/expr/expr.py
py-polars/polars/series/series.py

I think this was an accidental typo from https://github.com/pola-rs/polars/pull/16921/files

docs(python): Fix reference to non-existent `Expr.replace_all` in `replace_strict` docs

---

crates/polars-ops/src/chunked_array/list/namespace.rs
py-polars/tests/unit/functions/as_datatype/test_concat_list.py

fixes #23102
Pending review, see issue for solution strategies.
Works for Datetime and Duration, but not for Decimal as cast behaves differently. Should we use `from_physical_unchecked` instead?
*edit: latest commit uses `from_physical_unchecked` and works for Decimal as well.

fix: Support Datetime broadcast in `list.concat`

---

py-polars/polars/expr/expr.py
py-polars/polars/expr/list.py
py-polars/polars/functions/aggregation/vertical.py
py-polars/polars/series/array.py
py-polars/polars/series/list.py
py-polars/polars/series/series.py

The question about empty sums comes up some times, with some people angrily commenting that they want the databases behaviour
So i think it's worthwhile to document it + show that the workaround is indeed very simple

docs(python): Document aggregations that return identity when there's no non-null values, suggest workaround for those who want SQL-standard behaviour

---

Cargo.lock
Cargo.toml
crates/polars-python/Cargo.toml
crates/polars-python/src/lib.rs
crates/polars-python/src/testing/mod.rs
crates/polars-python/src/testing/series.rs
crates/polars-testing/src/asserts/utils.rs
py-polars/polars/testing/asserts/series.py
py-polars/src/lib.rs
py-polars/tests/unit/testing/test_assert_series_equal.py

@coastalwhite 
This is the first PR to connect the the new Rust back-end testing functionality to Python. This PR only covers `assert_series_equal()` since I didn't want the PR to be too large and it was my first time doing something like this. The next PR will cover `assert_dataframe_equal()`. 
I didn't want to meddle too much in the existing Python tests since they are robust and well-written, so I only made 2 **very minor** changes to the tests because of how they were structured. Otherwise, all tests pass without any interference. 
Lastly, the now deprecated Python code has still not been removed from the related files. This is because the Python `assert_dataframe_equal()` functionality in Python still relies on that code, so if I delete it without first connecting it to the Rust …

refactor: Connect Python `assert_series_equal()` to Rust back-end

---

crates/polars-arrow/src/array/static_array_collect.rs
crates/polars-core/src/series/ops/downcast.rs

> Can the `FixedSizeList` in error messages be changed to `array[...]` or similar?
> 
> ```python
> pl.Series([["foo", "bar"]]).arr.first()
> # SchemaError: invalid series dtype: expected `FixedSizeList`, got `list[str]` for series with name ``
> ```
> 
> People are still finding old code from when `.arr` was the list namespace[^1]  and it's a bit confusing.
> 
> [^1]: https://stackoverflow.com/questions/79609395/ 
_Originally posted by @cmdlineluser in [#21302](https://github.com/pola-rs/polars/issues/21302#issuecomment-2868531809)_

chore: Added more descriptive error message by replacing `FixedSizeList` with `Array`

---

crates/polars-time/src/group_by/dynamic.rs
crates/polars-time/src/windows/duration.rs
crates/polars-time/src/windows/group_by.rs
crates/polars-time/src/windows/test.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/datetime.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/datetime.py
py-polars/tests/unit/operations/namespaces/temporal/test_truncate.py

closes #https://github.com/pola-rs/polars/issues/23153

fix: Raise ComputeError instead of panicking in `truncate` when mixing month/week/day/sub-daily units

---

py-polars/Cargo.toml
py-polars/src/allocator.rs

This can be used to build python polars for memory debugging.

chore: Add `default_alloc` feature to `py-polars`

---

py-polars/polars/_utils/various.py

Super minor improvement (IMO). Old `show_graph` showed tick marks with pixels that add no useful information to the graph:
This update removes the ticks:
It's easy to remove the box as well, should we do that too? e.g.:

fix(python): Remove AXIS ticks in `show_graph`

---

crates/polars-arrow/src/bitmap/immutable.rs

this pr improve the `Bitmap::make_mut` on bitmaps created by `Bitmap::new_zeroed`
by now, `Bitmap::new_zeroed`  optimized all-zero bitmaps by sharing 1MiB storage, which causes `Bitmap::make_mut` clone a 1 MiB `data.storage`

perf: Optimize `Bitmap::make_mut`

---

crates/polars-time/src/chunkedarray/datetime.rs
py-polars/tests/unit/operations/namespaces/temporal/test_datetime.py

I found that the test cases for `is_leap_year` of `datetime`, which has a non-default time unit, and `date` are missing while working on #23119.
This change covers these missing cases directly.

fix(rust): Fix time zone handling in `dt.iso_year` and `dt.is_leap_year`

---

crates/polars-ops/src/frame/join/args.rs
crates/polars-plan/src/plans/optimizer/collapse_joins.rs
crates/polars-plan/src/plans/optimizer/join_utils.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/utils.rs
crates/polars-python/src/lazyframe/general.rs
py-polars/tests/unit/lazyframe/test_optimizations.py
py-polars/tests/unit/operations/test_join.py

* ref https://github.com/pola-rs/polars/issues/23133
* Fixes https://github.com/pola-rs/polars/issues/23185
Refactors the filter pushdown code to allow more filters to be pushed.
* Filters on join key columns are now pushed to both sides instead of just 1 side, for inner/left/right/full/semi/anti join.
* Also handles joins with differing `left_on` / `right_on` names, both coalesce and non-coalesce. Non-column join key expressions are also properly identified and block pushdowns.
* Filters referring only to a single input side for cross-joins and iejoins (join_where) are now pushed to that side.
* AsOf join:
* Filters on "by" columns are now pushed to both sides
* Filters referring only to columns originating from the left side are now pushed to the left side.
<details>
<summary>Example - …

perf: Push more filters past joins

---

crates/polars-plan/src/plans/aexpr/function_expr/array.rs
crates/polars-plan/src/plans/conversion/expr_expansion.rs
py-polars/tests/unit/functions/as_datatype/test_concat_arr.py

Fixes https://github.com/pola-rs/polars/issues/23267
I think this is all that is required @coastalwhite?

fix: Restore `concat_arr` inputs expansion

---

crates/polars-ops/src/frame/mod.rs
crates/polars-ops/src/series/ops/to_dummies.rs
crates/polars-python/src/dataframe/general.rs
crates/polars-python/src/series/general.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/series/series.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/series/test_series.py

I felt like it would be very useful to have this option, instead of manually dropping resulting `null` columns after calling `to_dummies`. One advantage also is that the `null` column is not materialized at all.  
Edit: This also fixes https://github.com/pola-rs/polars/issues/19095. After reading through https://github.com/pola-rs/polars/issues/19325, I'm not sure if this PR is actually worthwhile moving forward. Imho I think adding this optional parameter makes a lot of sense, but let me know if you feel differently
Example: 
```python
s = pl.Series("a", [1, 2, None])
print("Keep Null Column", s.to_dummies()) # current and default behavior
print("Drop Null Column", s.to_dummies(drop_nulls=True))
```
```
Keep Null Column shape: (3, 3)
┌─────┬─────┬────────┐
│ a_1 ┆ a_2 …
```

feat: Added `drop_nulls` option to `to_dummies`

---

crates/polars-core/src/datatypes/dtype.rs
crates/polars-plan/src/dsl/file_scan/mod.rs
crates/polars-plan/src/plans/conversion/type_coercion/mod.rs
crates/polars-plan/src/plans/lit.rs
py-polars/polars/datatypes/group.py
py-polars/polars/functions/col.py
py-polars/tests/unit/operations/test_cast.py

I realized that, in 1.31, polars does not currently drop superfluous casts in the optimized plan. Namely, something like the following keeps the `cast` in the plan:
```python
lf = pl.LazyFrame({"a": [1]}, schema={"a": pl.Int64})
lf.select(pl.col("a").cast(pl.Int64))
```
While going through the code, I realized that the relevant code path already existed, it was simply commented out with a comment to enable it after 1.30. As there's no further information, I couldn't tell for sure whether it is actually fine to enable now but it does what it should in my local tests.

feat: Drop superfluous casts from optimized plan

---

crates/polars-compute/src/bitwise/mod.rs
crates/polars-core/src/series/implementations/boolean.rs
py-polars/polars/expr/expr.py
py-polars/tests/unit/operations/test_bitwise.py

fixes #23314
Kindly review. Keep the doc update?
Ping @orlp.

fix: Ignore null values in `bitwise` aggregation on bools

---

crates/polars-arrow/src/bitmap/bitmap_ops.rs
crates/polars-compute/src/bitwise/mod.rs

These kernels don't allocate intermediate results and directly aggregate, possibly short-circuiting.
CC @kdn36

perf: Improve boolean bitwise aggregate performance

---

crates/polars-testing/src/asserts/utils.rs
py-polars/tests/unit/testing/test_assert_series_equal.py

@coastalwhite 
Mentioned I wanted to look into some optimizations for the code.
* Added pointer equality check for same object comparisons (`if std::ptr::eq()`) to short-circuit when comparing identical objects.
* Updated `categorical_series_to_string()` to return a `PolarsResult<>` so it would not panic on `.unwrap()` if the cast failed.
* Renamed data type comparison functions to be more clear.
* Replaced temporary Series creation with direct scalar operations for better performance.
The Python test needed to be updated with the new pointer equality check, since it compared the same exact Series to itself (`s` and `s`). I just made them separate objects for the comparison (`s1` and `s2`).
If you had any other ideas or suggestions, let me know. Thanks!

refactor(rust): Optimize equality comparisons and fix error handling

---

crates/polars-plan/src/plans/conversion/dsl_to_ir/mod.rs

refactor: Only conver to `ExprIR` once in `with_columns`

---

crates/polars-python/src/functions/io.rs
py-polars/polars/io/parquet/functions.py
py-polars/src/lib.rs

* ref https://github.com/pola-rs/polars/issues/23346
This will make `read_parquet_schema()` work with cloud paths.

feat: Use `scan_parquet().collect_schema()` for `read_parquet_schema`

---

crates/polars-expr/src/expressions/mod.rs
py-polars/tests/unit/operations/test_group_by.py

fixes #23338
The underlying bug comes from the fact that empty lists `[]` get exploded to `null` values when flattening, while the group indices and offsets stay as-is.
Kindly review, also in context of the history of `explode()`.
Ping @coastalwhite

fix: Fix incorrect results with `group_by` aggregation on empty groups

---

crates/polars-arrow/src/bitmap/mutable.rs
crates/polars-expr/src/reduce/bitwise.rs
crates/polars-expr/src/reduce/convert.rs
crates/polars-expr/src/reduce/mod.rs
crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-stream/src/physical_plan/lower_group_by.rs
py-polars/tests/unit/operations/test_bitwise.py

closes #23042
This PR moves the execution of bitwise reductions {`Expr.bitwise_and`, `Expr.bitwise_or` and `Expr.bitwise_xor`) into the streaming engine. Scope includes integer and Boolean dtypes, including null values.
Needs a proper review, ping @orlp .

feat: Execute bitwise reductions in streaming engine

---

py-polars/polars/io/ndjson.py
py-polars/tests/unit/io/test_json.py

When using read_ndjson bytes like objects have special treatment. This is not needed as scan_ndjson can handle bytes like objects. The current implementation ignores most parameters with no information to the end user.
The most simple solutions seems to be to remove the special case and just use scan_ndjson.
Fixes #22807

fix(python): Removed special handling for bytes like objects in read_ndjson

---

crates/polars-plan/src/plans/aexpr/function_expr/strings.rs

Prior to this change, the `polars` crate would fail to compile with `cargo check --no-default-features --features lazy,strings`. After this change, that compilation failure no longer occurs.

fix(rust): Fix compilation failure with `--no-default-features` and `--features lazy,strings`

---

crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/cast_columns.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/capabilities.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_pipelines/generic.rs
crates/polars-stream/src/nodes/io_sources/parquet/builder.rs
crates/polars-stream/src/nodes/io_sources/parquet/init.rs
crates/polars-stream/src/nodes/io_sources/parquet/mod.rs
py-polars/tests/unit/io/test_parquet.py

We do this by casting the statistics table. This is currently fairly simple to reason about as we don't allow fallible casts (e.g. downcasting integers).
This will allow for row group skipping in native `scan_iceberg` as well as allowing type casting to be enabled by default in `scan_delta`.

feat: Support row group skipping with filters when `cast_options` is given

---

docs/source/user-guide/migration/pandas.md

The original code `sum("v1")` worked but was not technically correct—`pandas.DataFrameGroupBy.sum()` does not accept column names. Instead, it sums all numeric columns in the group. Since we already filtered to `["id1", "v1"]` with `.loc`, using `.sum()` is both correct and cleaner.  
If we want to sum `"v1"` column without selecting columns here, a clearer alternative is `df.groupby("id1")["v1"].sum()`.
Reference: https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.sum.html#pandas.core.groupby.DataFrameGroupBy.sum

docs(python): Update example code in pandas migration guide

---

crates/polars-plan/src/plans/conversion/dsl_to_ir/scans.rs
crates/polars-sql/src/table_functions.rs
crates/polars-stream/src/physical_plan/to_graph.rs
crates/polars-utils/src/plpath.rs

Note that constructing `PlPath` from an owned string doesn't actually re-use the allocation, it always gets copied because `PlPath` stores either `Arc<Path>` or `Arc<str>`.
fyi @kdn36

refactor(rust): Remove unneeded allocations when creating `PlPath`

---

crates/polars-compute/src/rolling/no_nulls/quantile.rs
crates/polars-compute/src/rolling/nulls/quantile.rs
crates/polars-compute/src/rolling/quantile_filter.rs
py-polars/polars/series/series.py
py-polars/tests/unit/operations/rolling/test_rolling.py

fixes #23392
In total, there are 4 instances of the `nearest` indexing logic, 3 of which were incorrect and are now fixed in this PR. The 4th instance was already addressed in https://github.com/pola-rs/polars/pull/13058.
*edit: (!) the example in the python documentation is also changed per doctest, please review
This PR also removes an erroneous `method` overwrite in a prior test case (PR #22781).
Kindly review, including the expected outcome of the respective new test cases.

fix: Fix index calculation for `nearest` interpolation

---

crates/polars-core/src/datatypes/dtype.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir/expr_to_ir.rs
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/operations/namespaces/list/test_eval.py

After https://github.com/pola-rs/polars/pull/23016 this was unnecessarily restricted.

feat: Allow cast to Categorical inside list.eval

---

crates/polars-expr/src/groups/mod.rs
crates/polars-expr/src/hash_keys.rs
crates/polars-expr/src/hot_groups/mod.rs
crates/polars-expr/src/idx_table/mod.rs

Now that categoricals have been reworked we don't have to go through the row encoding for a singular categorical column.

perf: Use single-key optimization with Categorical

---

py-polars/polars/io/cloud/_utils.py
py-polars/tests/unit/io/test_utils.py

Currently `_get_path_scheme("A")` incorrectly returns "A", after this PR it will correctly return `None`.
No existing releases are affected as they always matched the extracted scheme against specific cloud schemes.

fix(python): Fix incorrect `_get_path_scheme`

---

crates/polars-core/src/datatypes/dtype.rs
py-polars/tests/unit/datatypes/test_categorical.py

fix: Support min/max aggregation for DataFrame/LazyFrame Categoricals

---

py-polars/polars/io/delta.py

While upgrading to `deltalake=1.0.2` and `dagster-delta==0.5.0`, realized that `pl.scan_delta(DeltaTable).sql().collect()` would not inherit the storage_options from the DeltaTable definition but would instead require storage_options to be passed explicitly.
To solve this I have passed the storage options from the table to the local scope in case of the source being a DeltaTable and the storage_options not being explicitely provided to the `pl.scan_delta()` function.
This fixes [#23064](https://github.com/pola-rs/polars/issues/23064)

fix(python): Pass DeltaTable._storage_options if no storage_options are provided

---

py-polars/tests/unit/constructors/test_any_value_fallbacks.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/dataframe/test_serde.py
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/datatypes/test_enum.py
py-polars/tests/unit/datatypes/test_list.py
py-polars/tests/unit/functions/as_datatype/test_concat_arr.py
py-polars/tests/unit/functions/test_when_then.py
py-polars/tests/unit/operations/namespaces/string/test_string.py
py-polars/tests/unit/operations/test_hist.py
py-polars/tests/unit/operations/test_is_in.py
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/operations/test_merge_sorted.py
py-polars/tests/unit/operations/test_shift.py
py-polars/tests/unit/operations/test_transpose.py
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/streaming/test_streaming_unique.py
py-polars/tests/unit/test_datatypes.py

Various improvements (usually the Categorical rework) made this `may_fail_auto_streaming` markers unnecessary.

chore: Remove unnecessary may_fail_auto_streaming

---

crates/polars-compute/src/rolling/no_nulls/mean.rs
crates/polars-compute/src/rolling/no_nulls/sum.rs
crates/polars-compute/src/rolling/nulls/mean.rs
crates/polars-compute/src/rolling/nulls/sum.rs
crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs
crates/polars-utils/src/float.rs
py-polars/tests/unit/operations/rolling/test_rolling.py

Fixes https://github.com/pola-rs/polars/issues/23115.
Replaced the rolling sum kernels with ones that properly keep track of the number of non-finite values in the window such that any combinations of infinities/nans get correctly handled without ever having to recompute the window (which is actually quadratic in the worst case, although it's never been reported as an issue).

fix: Properly handle non-finite floats in rolling_sum/mean

---

crates/polars-lazy/src/tests/cse.rs
crates/polars-lazy/src/tests/io.rs
crates/polars-lazy/src/tests/optimization_checks.rs
crates/polars-lazy/src/tests/pdsh.rs
crates/polars-lazy/src/tests/predicate_queries.rs
crates/polars-lazy/src/tests/projection_queries.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir/expr_to_ir.rs
crates/polars-plan/src/plans/iterator.rs
crates/polars-plan/src/plans/optimizer/delay_rechunk.rs

Although this changes the public API, the existing  `ArenaLpIter` user code should still compile, just with `clippy::needless_borrow` warnings. The existing `ArenaExprIter::iter` user calls might need fixing.

refactor: Simpify arena iterators

---

py-polars/tests/unit/test_categories.py

A bit tricky because other tests can mess this up, so we run it in its own process.

refactor: Add test to ensure the global categories gets cleaned up

---

crates/polars-dtype/src/categorical/mod.rs

Before in this strange circumstance it would just print the dtypes being unequal which isn't true.

refactor: Improve Categories error message

---

docs/source/user-guide/concepts/streaming.md

Side note: I don't see the new "Streaming" page on the user guide. In the search bar, typing "streaming" leads to the old https://docs.pola.rs/user-guide/concepts/_streaming/ (note the "_streaming" instead of "streaming" in the URL).

docs: Fix a few typos in the "Streaming" section

---

crates/polars-core/src/chunked_array/comparison/mod.rs
py-polars/tests/unit/datatypes/test_struct.py

fix: Correctly handle null values when comparing structs

---

docs/source/polars-cloud/providers/aws/infra.md

This PR adds a section on the AWS infrastructure detailing how to use your own network configuration (VPC, subnets, ...) and changes the image to include multiple subnets

fix: Update AWS cloud documentation

---

crates/polars-stream/src/nodes/io_sinks/partition/max_size.rs
py-polars/tests/unit/io/test_partition.py

closes #23376
Note: file count within partition limited to an arbitrary 2^28

fix: Preserve row order within partition when sinking parquet

---

crates/polars-ops/src/frame/join/asof/groups.rs
py-polars/tests/unit/operations/test_join_asof.py

* Fixes https://github.com/pola-rs/polars/issues/23583
* Regression from https://github.com/pola-rs/polars/pull/11854
* Bug was first introduced in version 0.19.10, and has existed since then 👀
RHS table was incorrectly sliced at execution. Note that using `join_asof` without the `by` argument is not affected.

fix: Fix incorrect `join_asof` with `by` followed by `head/slice`

---

crates/polars-ffi/src/lib.rs
crates/polars-ffi/src/version_0.rs

Fixes https://github.com/pola-rs/polars/issues/22094.

fix: Round-trip Enum and Categorical metadata in plugins

---

py-polars/docs/source/reference/expressions/list.rst
py-polars/docs/source/reference/series/list.rst

This PR adds API reference documentation for Expr.list.filter and Series.list.filter methods in the Python bindings.
I ran make html locally and confirmed that the documentation pages build correctly and the new entries appear as expected. 
close #23555

docs(python): Add docs of Expr.list.filter and Series.list.filter

---

crates/polars-plan/src/plans/aexpr/function_expr/strings.rs
py-polars/tests/unit/operations/namespaces/string/test_string.py

fixes #23570
In addition, this PR has proposed code simplification similar to https://github.com/pola-rs/polars/pull/6777
Code is pending selection of preferred implementation option and review. 
*Edit: ready for review.

fix: Honor `n=0` in all cases of `str.replace`

---

py-polars/polars/dataframe/frame.py

Fixes https://github.com/pola-rs/polars/issues/23579.
Also fixes something from the documentation we weren't actually respecting:
> Unify the dtype of all returned tensors; this casts any column that is not of the required dtype before converting to Tensor. This includes the label column **unless the label is an expression (such as pl.col("label_column").cast(pl.Int16))**.

fix: Casting unused columns in to_torch

---

docs/source/user-guide/gpu-support.md
py-polars/polars/lazyframe/frame.py

RAPIDS CUDA 11 deprecation announcement: https://docs.rapids.ai/notices/rsn0048/

docs: Update GPU docs for RAPIDS CUDA 11 deprecation

---

crates/polars-core/src/frame/group_by/expr.rs
crates/polars-core/src/frame/group_by/position.rs
crates/polars-lazy/src/frame/pivot.rs
crates/polars-ops/src/frame/pivot/mod.rs
crates/polars-ops/src/frame/pivot/positioning.rs
crates/polars/tests/it/core/pivot.rs
py-polars/tests/unit/operations/test_pivot.py

fixes #23408
This PR will insert the result of the `agg_fn` on an empty column as the default value in the final pivot, as opposed to simply inserting `null` values. This is applicable for any combination of `index` value and `on` value for which there is no entry in the df.
*edited:
Notes for review:
1. This PR will change the behavior for `agg_fn` such as `sum` and `len`, for which the result is `0` rather than `null`. See also the modifications to a number of tests. This may impact existing workflows.
2. Included: refactor of `PivotAgg` variants into a single tuple struct. Update Rust integration tests.
3. As usual, code to be reviewed properly (thanks).
Excluded (future):
1. Refactor `pivot` and `pivot_stable` such that lowering from `PhysicalAggExpr` to `PhysicalExpr` happens …

fix: Apply `agg_fn` on `null` values in `pivot`

---

crates/polars-plan/src/plans/conversion/dsl_to_ir/functions.rs
crates/polars-python/src/functions/range.rs
py-polars/tests/unit/functions/range/test_date_range.py
py-polars/tests/unit/functions/range/test_int_range.py
py-polars/tests/unit/functions/range/test_linear_space.py
py-polars/tests/unit/functions/range/test_time_range.py

These functions should only accept scalars for their parameters, this prevents misuse.

feat: Add scalar checks to range expressions

---

crates/polars-ops/src/chunked_array/list/sets.rs
py-polars/tests/unit/operations/namespaces/list/test_set_operations.py

This PR addresses issue #23551 by fixing an error in the [binary-function](https://github.com/pola-rs/polars/blob/11643a6ca6250d9c81f643acc31e63f27201cdb5/crates/polars-ops/src/chunked_array/list/sets.rs#L261) implementation that mishandled the case when `broadcast_rhs=True` on `list[str]` columns. As a result of that bug, `pl.Expr.list.set_intersection` and `pl.Expr.list.set_symmetric_difference` sometimes return incorrect outputs.
new unit tests in tests/unit/operations/namespaces/list/test_set_operations.py verify reproducible examples described in [#23551](https://github.com/pola-rs/polars/issues/23551#issuecomment-3069912640)
close #23551

fix: Logic of broadcast_rhs in binary functions to correct list.set_intersection for list[str] columns

---

crates/polars-arrow/src/array/binview/ffi.rs
crates/polars-arrow/src/array/binview/mod.rs
crates/polars-arrow/src/bitmap/immutable.rs
crates/polars-arrow/src/compute/decimal.rs
crates/polars-core/src/chunked_array/flags.rs
crates/polars-core/src/chunked_array/object/extension/mod.rs
crates/polars-core/src/fmt.rs
crates/polars-expr/src/idx_table/binview.rs
crates/polars-expr/src/idx_table/row_encoded.rs
crates/polars-expr/src/idx_table/single_key.rs
crates/polars-expr/src/state/execution_state.rs
crates/polars-io/src/cloud/polars_object_store.rs
crates/polars-io/src/csv/read/read_impl.rs
crates/polars-io/src/pl_async.rs
crates/polars-lazy/src/frame/exitable.rs
crates/polars-python/src/timeout.rs
crates/polars-stream/src/async_executor/mod.rs
crates/polars-stream/src/execute.rs
crates/polars-stream/src/morsel.rs
crates/polars-stream/src/nodes/io_sinks/parquet.rs
crates/polars-stream/src/nodes/io_sinks/partition/max_size.rs
crates/polars-stream/src/nodes/io_sinks/partition/parted.rs
crates/polars-stream/src/nodes/joins/equi_join.rs
crates/polars-stream/src/pipe.rs
crates/polars-utils/src/arena.rs
crates/polars-utils/src/lib.rs
crates/polars-utils/src/pl_str.rs
crates/polars-utils/src/relaxed_cell.rs

This should make it easier at a glance to determine whether an atomic is being used for synchronization, or just for interior mutability / non-synchronizing signaling.

refactor(rust): Use RelaxedCell for fully relaxed atomics

---

crates/polars-testing/src/asserts/frame.rs
crates/polars-testing/src/asserts/utils.rs

Just tagging @coastalwhite because we is familiar with my work on the assertion functions. 
Realized that many of the helper functions for `assert_series_equal()` and `assert_dataframe_equal()` were public, but they are only used internally, so I made them private.
During this process, I noticed a test failure (both before and after making the helper functions private) and realized it had some faulty logic and was incorrect. I updated the test and added another one that uses logic the original test should have implemented.

refactor(rust): Make helper functions private for equality assertions and update test

---

crates/polars-core/src/frame/column/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/extra_ops/column_selector.rs

These are intended for internal use for now.

refactor(rust): Underscore prefix for `get_backing_series`/`to_new_from_backing`

---

README.md

Update the badge since it is recommend installing the release version from R-multiverse (the old link to the R-universe repository is used for development version).
https://github.com/pola-rs/r-polars/blob/a9102a92a00a43c68f2e0cdb52397c947c929646/README.md?plain=1#L40-L48

docs: Point the R Polars version on R-multiverse

---

crates/polars-plan/src/plans/expr_ir.rs
crates/polars-plan/src/plans/ir/inputs.rs

This PR:
- fix `with_exprs_and_input` for Sort not using the new expressions
- fix `with_exprs_and_input` for Scan not requiring a new predicate expr when the old is `Some`
- remove manual `Clone` impl for `ExprIR`, it does the same thing as derived

fix: Sort and Scan `with_exprs_and_input`

---

crates/polars-python/src/expr/rolling.rs
py-polars/tests/unit/operations/rolling/test_map.py

fix: Match output type to engine for `rolling_map`

---

crates/polars-ops/src/chunked_array/strings/extract.rs
py-polars/tests/unit/operations/namespaces/string/test_string.py

Partial fix for #23663.
The engine was modified: for the empty string pattern (""), it now generates an empty Struct, rather than a Struct containing the 'missing' value.

fix: Fix output for `str.extract_groups` with empty string pattern

---

Cargo.lock
crates/polars-expr/src/state/execution_state.rs
crates/polars-lazy/src/tests/cse.rs
crates/polars-mem-engine/src/planner/lp.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir/mod.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir/utils.rs
crates/polars-plan/src/plans/ir/dot.rs
crates/polars-plan/src/plans/ir/format.rs
crates/polars-plan/src/plans/ir/inputs.rs
crates/polars-plan/src/plans/ir/tree_format.rs
crates/polars-plan/src/plans/optimizer/cache_states.rs
crates/polars-plan/src/plans/optimizer/collapse_and_project.rs
crates/polars-plan/src/plans/optimizer/cse/cse_lp.rs
crates/polars-plan/src/plans/prune.rs
crates/polars-python/src/lazyframe/visit.rs
crates/polars-python/src/lazyframe/visitor/nodes.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-utils/Cargo.toml
crates/polars-utils/src/unique_id.rs

This PR switches `UniqueID` to use UUID internally. This ensures uniqueness and preserves the ability to generate new unique IDs even after deserialization.
@wence- This changes the Python IR interface. The `Cache::id_` field changes from `usize` to `u128` since the ids now use 128 bits. I bumped the `VERSION`.
Closes #23674

refactor: Use UUID for UniqueID

---

crates/polars-plan/src/plans/aexpr/function_expr/datetime.rs

fix: Correct output datatype for `dt.with_time_unit`

---

crates/polars-plan/src/plans/aexpr/properties.rs
py-polars/tests/unit/operations/namespaces/temporal/test_to_datetime.py

Existing code (from me) was just plain wrong.

fix: Fix `to_datetime()` fallible identification

---

crates/polars-plan/src/plans/aexpr/equality.rs
crates/polars-plan/src/plans/aexpr/mod.rs
crates/polars-plan/src/plans/aexpr/traverse.rs

chore: Add `AExpr::is_expr_equal_to`

---

crates/polars/src/prelude.rs

If `PlPathRef` is exposed here, downstream users will no longer need to use `polars_utils` in Cargo.toml.
Ref: pola-rs/r-polars#1452

refactor(rust): Expose `PlPathRef` via polars::prelude

---

crates/polars-io/src/cloud/credential_provider.rs

* Fixes regression from https://github.com/pola-rs/polars/pull/23730 which caused a 3-second sleep on initialization of credential providers.
This happened as `last_fetched_expiry` is always initialized as `0`.
This PR completely removes `MIN_REMAINING_TIME` / `sleep`s from the Rust-side. They shouldn't be needed since we already have object store rebuild-on-error logic.
Note however that rebuilds do not take place in cloud sinks as they use `object_store::buffered::BufWriter`, which directly uses `dyn ObjectStore` instead of `PolarsObjectStore`.

fix: Remove sleep for credential refresh

---

py-polars/polars/expr/name.py

docs: Correct the `name.*` methods on their removal of aliases

---

py-polars/polars/_utils/udfs.py

It's coming up to that time of year again, when Python comes up with new bytecode ops and drops a new release; got a 3.14rc environment running and went through the [disassembler docs](https://docs.python.org/3.14/library/dis.html#opcode-LOAD_SMALL_INT) to understand the new opcodes 💭
This year's release primarily adds optimising specialisations of existing ops, and it appears sufficient to make only minor updates to `RewrittenInstructions` to handle everything. For example, we can remap the following 3.14-specific instructions, then parse as normal:
`"LOAD_FAST_BORROW" → "LOAD_FAST"`
`"LOAD_SMALL_INT" → "LOAD_CONST"`
There is another small update for subscript access:
`"BINARY_OP ([])" → "BINARY_SUBSCR"`
Will keep an eye on the next release candidates, but so far this allows all …

feat(python): Update `BytecodeParser` opcode awareness for upcoming Python 3.14

---

crates/polars-expr/src/state/execution_state.rs
crates/polars-plan/src/plans/optimizer/expand_datasets.rs
crates/polars-plan/src/plans/optimizer/mod.rs
crates/polars-stream/src/execute.rs
crates/polars-stream/src/nodes/io_sources/batch.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/mod.rs
crates/polars-stream/src/nodes/io_sources/multi_file_reader/reader_interface/builder.rs
crates/polars-stream/src/physical_plan/io/python_dataset.rs
crates/polars-stream/src/physical_plan/lower_ir.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/io/test_io_plugin.py
py-polars/tests/unit/test_predicates.py

* Needed for https://github.com/pola-rs/polars/pull/23725
Properly propagates the `StreamingExecutionState` passed to `<MultiFileReader as ComputeNode>::spawn` to the IO plugin reader.
**Note**
This PR will change the behavior when scanning IO sources on the new-streaming engine with `validate=False` to raise an error instead of succeeding if the schema of the returned morsels do not match the schema provided to. It currently succeeds by calling `GetBatchFn` to retrieve the first morsel, and overriding the `output_schema` when `validate=False`. This relied on `StreamingExecutionState::default()` as it is done in `to_graph.rs`.
Existing tests that use `validate=False` failing on new-streaming after this PR (3 total):
```
FAILED tests/unit/io/test_io_plugin.py::test_defer - …
```

refactor(rust): Remove Default for StreamingExecutionState

---

Cargo.lock
Cargo.toml
crates/polars-plan/Cargo.toml
crates/polars-utils/Cargo.toml
crates/polars-utils/src/pl_serialize.rs

Not used anymore since #23709, now we check for the exact schema match.

chore: Remove `deserialize_with_unknown_fields`

---

crates/polars-stream/src/nodes/repeat.rs

Silly mistake by me, not caught because we still use `POLARS_AUTO_NEW_STREAMING` which automatically defers `todo!`s to the in-memory engine.

fix: Remove accidental todo! in repeat node

---

docs/source/_build/API_REFERENCE_LINKS.yml
docs/source/polars-cloud/index.md
docs/source/polars-cloud/quickstart.md
py-polars/polars/lazyframe/frame.py

feat(python): Change typing for `.remote()` from `LazyFrameExt` to `LazyFrameRemote`

---

crates/polars-json/src/json/write/serialize.rs
py-polars/tests/unit/io/test_json.py

Fixes #23826.
It still produces a weird result because nested casting is broken, but at least it doesn't panic.

fix: Allow encoding of `pl.Enum` with smaller physicals

---

README.md

pyo3-polars was moved from its own repository to the official polars one. The documentation was out of date.

docs: Fix `pyo3` documentation page link

---

crates/polars-io/src/cloud/polars_object_store.rs

* Fixes https://github.com/pola-rs/polars/issues/23832
Return empty Bytes object if the range is empty. I've also opened an issue upstream at https://github.com/apache/arrow-rs-object-store/issues/453.
Note that I cannot reproduce the Python MRE in the issue, but I've tested this in the Rust side:
```
---- cloud::polars_object_store::tests::test_ stdout ----
[crates/polars-io/src/cloud/polars_object_store.rs:552:13] store.1.get_range(&object_path_from_str("iris.parquet").unwrap(), 0..0).await = Ok(
b"",
)
[crates/polars-io/src/cloud/polars_object_store.rs:559:13] store.1.get_range(&object_path_from_str("iris.parquet").unwrap(), i32::MAX as usize..i32::MAX as usize).await = Ok(
b"",
)
[crates/polars-io/src/cloud/polars_object_store.rs:566:13] …
```

fix: Fix error on empty range requests

---

Cargo.lock
crates/polars-stream/src/async_primitives/opt_spawned_future.rs
crates/polars-stream/src/nodes/io_sources/parquet/init.rs
crates/polars-stream/src/nodes/io_sources/parquet/mod.rs
crates/polars-stream/src/nodes/io_sources/parquet/row_group_decode.rs
crates/polars-utils/Cargo.toml
crates/polars-utils/src/enum_unit_vec.rs
crates/polars-utils/src/lib.rs
py-polars/tests/unit/io/test_lazy_parquet.py

* Fixes https://github.com/pola-rs/polars/issues/23849
We currently have different codepaths depending on the amount of rows. One of these codepaths contained the bug in the issue.
This PR removes the extra row count dependent codepaths. The original motivation was to reduce task spawns / Vec allocations for small data sizes, but after this PR the overhead should be fairly minimal as we are using `parallelize_first_to_local` (added in https://github.com/pola-rs/polars/pull/22458) with a newly added `EnumUnitVec`.
A new `EnumUnitVec` is added that stores length-1 lists on the stack. This is used instead of a `Vec` and reduces allocations when e.g.:
* There is only a single future from `parallelize_first_to_local`
* Decoding / filtering tasks each return only a single column
Note that the …

fix: Fix index out of bounds panic filtering parquet

---

crates/polars-parquet/src/arrow/read/schema/convert.rs
crates/polars-plan/src/plans/optimizer/expand_datasets.rs
py-polars/polars/io/iceberg/dataset.py
py-polars/tests/unit/io/test_iceberg.py

* Fixes https://github.com/pola-rs/polars/issues/23841
* The IR was not overwritten on the 2nd execution of the query
* Fixes https://github.com/pola-rs/polars/issues/23842
* This file did not have `ARROW:schema`, causing us to go into a separate codepath for constructing the schema. This codepath has been updated in this PR to load the field IDs.

fix: Fix errors on native `scan_iceberg`

---

docs/source/development/contributing/index.md

This pull request updates the index.md file in the contributing documentation to improve links for Stack Overflow.
The current documentation links to the general Stack Overflow homepage, even though it later mentions that there are separate, language-specific tags for Python and Rust Polars.
This change replaces the general link with direct links to the relevant Stack Overflow pages for [Python Polars](https://stackoverflow.com/questions/tagged/python-polars) and [Rust Polars](https://stackoverflow.com/questions/tagged/rust-polars).

docs: Improve StackOverflow links in contributing guide

---

crates/polars-stream/Cargo.toml
crates/polars-stream/src/physical_plan/lower_expr.rs

Small break from the types work.
- `unique_counts` gets lowered to an ordered group-by (not yet natively streaming)
- `value_counts` gets lowered to an unordered group-by
xref: #20947.
```python
df = pl.LazyFrame(
{"color": ["red", "blue", "red", "green", "blue", "blue"]}
).select(pl.col("color").value_counts()).collect(engine='streaming')
```

feat: Lower `unique_counts` and `value_counts` to streaming engine

---

crates/polars-plan/src/dsl/file_scan/python_dataset.rs
crates/polars-plan/src/plans/optimizer/expand_datasets.rs
crates/polars-python/src/dataset/dataset_provider_funcs.rs
py-polars/polars/io/iceberg/dataset.py
py-polars/tests/unit/io/test_iceberg.py

* Fixes https://github.com/pola-rs/polars/issues/23905
* PR depends on https://github.com/pola-rs/polars/pull/23900
Note, that after a serialization roundtrip `q = pickle.loads(pickle.dumps))`, collection of the roundtripped LazyFrame will no longer see any modifications on the original Iceberg table object. This is due to the underlying table inside of the `IcebergDataset` becoming a separate object in memory.

fix: Ensure `collect()` native Iceberg always scans latest when no `snapshot_id` is given

---

pyo3-polars/example/extend_polars_python_dispatch/extend_polars/src/lib.rs
pyo3-polars/example/io_plugin/io_plugin/io_plugin/__init__.py
pyo3-polars/example/io_plugin/io_plugin/src/lib.rs
pyo3-polars/pyo3-polars/src/ffi/mod.rs
pyo3-polars/pyo3-polars/src/ffi/to_py.rs
pyo3-polars/pyo3-polars/src/ffi/to_rust.rs
pyo3-polars/pyo3-polars/src/lib.rs
pyo3-polars/pyo3-polars/src/types.rs

PR #23571 moves pyo3-polars into this repo from https://github.com/pola-rs/pyo3-polars.  However, in doing so, it removes most of pyo3-polars' functionality, and in particular, the `PyDataFrame`, `PyLazyFrame`, `PySeries`, etc structs and corresponding PyO3 type conversion implementations.  These are not the same as the similarly-named structs in `polars-python`: they are meant to allow bidirectional passing of the corresponding objects between python polars and rust polars in separately-compiled PyO3-based Rust code.   Much of the README refers to functionality that is no longer present (section 2, and "What to expect"), and all examples other than `derive_expression` are broken (`polars-python::PyDataFrame` cannot be used to replace `pyo3-polars::PyDataFrame`, etc).  The module now has …

fix: Restore Arrow-FFI-based Python<->Rust conversion in pyo3-polars

---

crates/polars-ops/src/frame/pivot/unpivot.rs
py-polars/tests/unit/operations/test_unpivot.py

Fixes #23165
Propagates the `ColumnNotFoundError` instead of a panic.

fix: Fix `unpivot` panic when `index=` column not found

---

crates/polars-python/src/c_api/allocator.rs
py-polars/requirements-ci.txt
py-polars/tests/unit/test_ds_plugin.py
pyo3-polars/pyo3-polars/src/alloc.rs

Fixes #23965.
Also adds this to the CI to ensure no more future regressions here.

fix: Correct allocator name in `PyCapsule`

---

crates/polars-plan/src/plans/optimizer/count_star.rs

`dyn OptimizationRule` are called in a tight loop. The `CountStar` optimization is called only once. This prevents confusion (I was already thinking this is too expensive for a tight loop).

refactor: Don't define CountStar as dyn OptimizationRule

---

docs/source/user-guide/lazy/execution.md

Just a small correction in user guide.

docs(python): Fix a typo in "lazy/execution" user-guide page

---

crates/polars-python/src/map/series.rs
crates/polars-python/src/series/map.rs
py-polars/tests/unit/operations/map/test_map_elements.py

fix: Align `map_elements` with and without `return_dtype`

---

crates/polars-plan/src/plans/ir/dot.rs

Fixes cache to have a valid dot graph id.
- broken in #23704
Before:
```dot
graph  polars_query {
c7e2e5b86-a92c-4b63-8baf-b397a32ad8f2 -- p1
p1[label="TABLE\nπ */1"]
c7e2e5b86-a92c-4b63-8baf-b397a32ad8f2[label="CACHE"]
}
```
After:
```dot
graph  polars_query {
"7e2e5b86-a92c-4b63-8baf-b397a32ad8f2" -- p1
p1[label="TABLE\nπ */1"]
"7e2e5b86-a92c-4b63-8baf-b397a32ad8f2"[label="CACHE"]
}
```

fix: Cache id is not a valid dot node id

---

crates/polars-io/src/utils/compression.rs
py-polars/tests/unit/io/test_csv.py

The library accpeted three possible zlib signatures, but https://en.wikipedia.org/wiki/List_of_file_signatures contains four options that have no preset dictionary,
based on compression levels. Some zlib-ng implementations seem to create only `0x78 0x5E` signatures, which was the one not polars, but it works fine.

fix: Accept another zlib "magic header" file signature

---

crates/polars-stream/src/physical_plan/lower_ir.rs
py-polars/tests/unit/operations/test_top_k.py

Follow-up from https://github.com/pola-rs/polars/pull/23979. Augments with a row index before applying the `top_k` if `maintain_order` is set.

perf: Lower .sort(maintain_order=True).head() to streaming top_k

---

pyo3-polars/example/derive_expression/Makefile
pyo3-polars/example/extend_polars_python_dispatch/Makefile
pyo3-polars/example/io_plugin/Makefile

This ensures our repository-wide .gitignore ignores these.

chore: Use .venv instead of venv in pyo3-polars examples

---

crates/polars-plan/src/plans/optimizer/slice_pushdown_lp.rs
py-polars/tests/unit/operations/test_slice.py

Fixes https://github.com/pola-rs/polars/issues/23920.

fix: Incorrect slice-slice pushdown

---

crates/polars-core/src/chunked_array/logical/categorical.rs

Fixes https://github.com/pola-rs/polars/issues/24034.
We should only actually include in the dictionary what we use.

fix: Don't encode entire CategoricalMapping when going to Arrow

---

py-polars/polars/dataframe/frame.py

This patch adds the `pipe_columns` method for `DataFrame`. This method makes it easy to chain eager-only operations on `Series` and does so in connection to make sure that changes related to #23625 are left with good alternatives.
```python
>>> df = pl.DataFrame({
...     "a": ['{"x":"a"}', None, '{"x":"b"}', None],
...     "b": ['{"a":1, "b": true}', None, '{"a":2, "b": false}', None],
... })
>>> df.map_columns(["a", "b"], lambda s: s.str.json_decode())
shape: (4, 2)
┌───────────┬───────────┐
│ a         ┆ b         │
│ ---       ┆ ---       │
│ struct[1] ┆ struct[2] │
╞═══════════╪═══════════╡
│ {"a"}     ┆ {1,true}  │
│ null      ┆ null      │
│ {"b"}     ┆ {2,false} │
│ null      ┆ null      │
└───────────┴───────────┘
```

feat: Add `DataFrame.map_columns` for eager evaluation

---

crates/polars-ops/src/chunked_array/peaks.rs
py-polars/tests/unit/series/test_series.py

This patch adds `peak_min` and `peak_max` support for boolean types.
The behavior of the patch is the same as for the integer types: On edge values, it is assumed that the out-of-bounds neighbor is equal to `False` (vs `0`).
Example:
```python
s = pl.Series("a", [False, True, False, True, True, False], dtype=pl.Boolean)
result = s.peak_min()
expected = pl.Series("a", [False, False, True, False, False, False])
assert_series_equal(result, expected)
result = s.peak_max()
expected = pl.Series("a", [False, True, False, False, False, False])
assert_series_equal(result, expected)
```

feat: Add peak_{min,max} support for booleans

---

crates/polars-plan/src/plans/schema.rs
py-polars/tests/unit/operations/test_join_asof.py

Fixes #24000.
The problem was actually larger than the original issue showed. The columns should also be out of order in the schema in certain situations.
This PR simplifies the code, resolves the order issues, ensures that the schema datatype is the datatype of the original schema not the datatype of the `on` expression, and removes a quadratic loop.

fix: Correct planner output schema for `join_asof`

---

py-polars/polars/_utils/udfs.py
py-polars/tests/unit/operations/map/test_inefficient_map_warning.py

For some reason we were only checking a subset of `date` and `datetime` attributes ("isoweekday" and "time"). Added the other obvious ones ("day", "hour", "microsecond", "month", "second", "strftime", "year") so that we can catch additional unnecessary Python UDF usage 🐞

feat(python): Catch additional temporal attributes in `BytecodeParser` function analysis

---

crates/polars-stream/src/physical_plan/lower_expr.rs
crates/polars-stream/src/physical_plan/lower_group_by.rs
crates/polars-stream/src/physical_plan/lower_ir.rs

Augments with a row index before grouping, adds a `first` aggregate to the group-by to find the first row index in the group, does a post-grouping sort on this first row index and removes the extra row index in the post-select.
Will fail test suite until https://github.com/pola-rs/polars/pull/24051 is merged.

perf: Lower order-preserving groupby to streaming engine

---

py-polars/polars/_utils/various.py
py-polars/tests/unit/interop/test_interop.py

* Fix the parsing of negative durations in `pl.from_repr()`
* Add a regression test for #24110
Fixes #24110

fix(python): Fix from_repr parsing of negative durations

---

crates/polars-error/src/warning.rs
crates/polars-plan/src/plans/aexpr/function_expr/shift_and_fill.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir/functions.rs
crates/polars-stream/src/nodes/shift.rs
py-polars/tests/unit/test_errors.py

Add a deprecation warning whenever shifting with a non-numeric value (e.g. `pl.Series([1, 2, 3]).shift(None)`) results in a new column consisting of only Null values.
Unfortunately, it is still possible to shift with data types that can be cast to i64, but are still very unreasonable values for shifting.  This includes non-integer floats, pl.Datetime, etc. We defer fixing this to when we have dtype signatures for all functions. (Cc @coastalwhite)
Fixes #24105

feat: Add a deprecation warning for pl.Series.shift(Null)

---

crates/polars-stream/src/physical_plan/fmt.rs

An InMemoryJoin _is_ memory intensive, but for the purposes of streaming physical plan visualisation it is probably better to be marked as an in memory fallback node.

refactor(rust): InMemoryJoin should be coloured as InMemoryFallback

---

crates/polars-expr/src/expressions/sortby.rs
py-polars/tests/unit/operations/test_sort.py
py-polars/tests/unit/test_errors.py

fixes #24057
Summary of changes:
- removed false positive check which was incorrect for overlapping groups
- added regression test
- added code fix for `literal`
- improved error message feedback

fix: Fix `sort_by` for `group_by_dynamic` context

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/database/_utils.py
py-polars/tests/unit/io/database/test_read.py
py-polars/tests/unit/io/database/test_write.py

Relates to https://github.com/pola-rs/polars/issues/22745
Fixes https://github.com/pola-rs/polars/issues/24117
Closes https://github.com/pola-rs/polars/issues/24118
From version 1.6.0, ADBC's `adbc_ingest` accepts a Polars DataFrame (specifically, an object implementing the PyCapsule Protocol) and does not require PyArrow to be installed. This implementation leverages that, and passes in a Polars df rather than a PyArrow table.
This is kind of hard to test in CI (suggestions welcome) given PyArrow is installed there, but I have tested it locally with the below script.
<details>
<summary> Demo: </summary>
```python
df = pl.DataFrame({"a": 1})
try:
rows_written = df.write_database("test", "sqlite:///:memory:", engine="adbc")
except Exception as e: …
```

feat(python): Drop PyArrow requirement for `write_database` with the ADBC engine

---

crates/polars-mem-engine/src/planner/lp.rs
py-polars/tests/unit/io/test_pyarrow_dataset.py

* ref https://github.com/pola-rs/polars/issues/24093
Set `POLARS_VERBOSE_SENSITIVE=1` in the environment:
```
pl.scan_pyarrow_dataset(dset).filter(pl.col("a") < 3).collect()
[SENSITIVE]: python_scan_predicate: predicate node: [(col("a")) < (3)], converted pyarrow predicate: (pa.compute.field('a') < 3)
```

feat: Log pyarrow predicate conversion result in sensitive verbose logs

---

crates/polars-expr/src/expressions/aggregation.rs
py-polars/tests/unit/datatypes/test_list.py

fixes #23974
Overview of changes:
- `implode()` on `AggregatedScalar` returns an `AggregatedScalar` instead of an `AggregatedList`
- amend existing test and add new regression test
ping @coastalwhite

fix: Fix engine type for `concat_list` on AggScalar `implode`

---

crates/polars-plan/src/plans/aexpr/mod.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/utils.rs
crates/polars-plan/src/plans/visitor/expr.rs
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/test_predicates.py

* Fixes https://github.com/pola-rs/polars/issues/23243
Renames `insert_and_combine_predicate` to `insert_predicate_dedup` and adds basic de-duplication by comparing  `<AExprArena as PartialEq>`.
```python
q = lf.filter(pl.col("x") == 2, pl.col("x") == 2)
FILTER [([(col("x")) == (2)]) & ([(col("x")) == (2)])]
FROM
DF ["x"]; PROJECT */1 COLUMNS
FILTER [(col("x")) == (2)]
FROM
DF ["x"]; PROJECT */1 COLUMNS
```
```python
q = (
pl.LazyFrame({"x": [1, 2, 3]})
.join(pl.LazyFrame({"x": [1, 2, 3]}), on="x", how="inner", coalesce=False)
.filter(
pl.col("x") == 2,
pl.col("x_right") == 2,
)
)
INNER JOIN:
LEFT PLAN ON: [col("x")]
FILTER [([(col("x")) == (2)]) & ([(col("x")) == (2)])]
FROM
DF ["x"]; PROJECT */1 COLUMNS
RIGHT PLAN ON: [col("x")]
FILTER [([(col("x")) == (2)]) & ([(col("x")) == (2)])] …
```

perf: Basic de-duplication of filter expressions

---

py-polars/polars/convert/general.py

* ref https://github.com/pola-rs/polars/issues/22921
Leaves a hint to directly use `pl.DataFrame()`/`pl.Series()` in the docstring of `from_arrow()`, which can avoid typing issues due to `from_arrow()` cannot be typed properly - (https://github.com/pola-rs/polars/pull/8011/files#diff-4c94e013bf5cbe1352b49c01958d0a6d58948f0abf030bf26f6f6c9089e4706eR426-R430).

docs(python): Add hint to use `DataFrame/Series` constructors in `from_arrow` docstring

---

py-polars/polars/series/series.py

This PR fixes a broken example in the value_counts documentation where the “relative frequency” snippet was rendered inline.
https://docs.pola.rs/api/python/stable/reference/series/api/polars.Series.value_counts.html

docs: Fix formatting of Series.value_counts examples

---

crates/polars-expr/src/expressions/mod.rs
crates/polars-expr/src/expressions/slice.rs
crates/polars-expr/src/expressions/sortby.rs
crates/polars-lazy/src/tests/queries.rs
crates/polars-plan/src/plans/optimizer/slice_pushdown_expr.rs
py-polars/tests/unit/operations/test_group_by.py
py-polars/tests/unit/operations/test_slice.py

fixes #23999
fixes #24102
Note (!), this PR changes the output dtype of the engine when `slice` is called on a `Literal` value, since `slice` does not meet the `is_scalar` criteria.
Overview of changes:
- Do not drop `Slice` on Literal in the optimizer.
- Triggerr aggregation for `LiteralScalar` in `slice.rs`.
- Adjust groups logic in `aggregated()`, from (*)
- Fix older test.
- Parametric type tests for `slice`, `gather`, `get`, `head` and `tail`. 
Builds upon: https://github.com/pola-rs/polars/pull/24078 (*)
Note that `slice` on an aggregated scalar value will raise per current behavior, but imo this could and should succeed with at most some minor changes.
More optimizations are possible.
*edit:
- Fixed regression in `sortby`
- clippy change
ping @coastalwhite

fix: Fix dtype for `slice` on `Literal` in agg context

---

.github/workflows/release-python.yml

Github has dropped support for macos_x86-64 runners. As cross-compiling did lead to many issues in the past, we will drop binary support for this target as well.
From source compilation will remain supported.

build: Drop binary support for macos_x86-64

---

crates/polars-compute/src/cast/primitive_to.rs
py-polars/tests/unit/datatypes/test_decimal.py

These were using powers of 9 rather than 10 for some reason.

fix: Correct size limits for Decimal cast

---

py-polars/Makefile

This was randomly broken in https://github.com/pola-rs/polars/pull/24192.

chore: Fix Makefile venv path

---

crates/polars-time/src/chunkedarray/string/mod.rs
py-polars/tests/unit/operations/namespaces/temporal/test_to_datetime.py

Fixes https://github.com/pola-rs/polars/issues/24263.
Also fixes an as-of-yet unreported bug where there are multibyte unicode characters in the string. A bit faster of an algorithm to boot as the suffix is directly chopped off using `parse_and_remainder`.

fix: Panic in inexact date(time) conversion

---

crates/polars-plan/src/plans/optimizer/mod.rs
py-polars/tests/unit/test_queries.py

This came up a lot in plans where it would decide to split an order observing operation into the order obsering and non-order observing variant because CSE was done afterwards.

perf: Do ordering simplification step after common sub-plan elimination

---

crates/polars-expr/src/hot_groups/binview.rs
crates/polars-expr/src/hot_groups/fixed_index_table.rs
crates/polars-expr/src/hot_groups/mod.rs
crates/polars-expr/src/hot_groups/row_encoded.rs
crates/polars-expr/src/hot_groups/single_key.rs
crates/polars-stream/src/nodes/group_by.rs
crates/polars-stream/src/physical_plan/to_graph.rs
py-polars/tests/unit/operations/test_group_by.py

Fixes https://github.com/pola-rs/polars/issues/24278.
This is more of a temporary workaround than a proper fix, but the hot/cold key paradigm I introduced in the streaming group-by has a problem with order-sensitive aggregates.
In my original design we had the guarantee that reducers are called within one dataframe in the correct order, which allows us to write order-sensitive reducers so long as we have the sequence id of the morsel. However, with the hot key cache we now bypass cold keys from the reducer entirely until later, violating this assumption.
For now I've just ensured that every key is always marked as hot if we have an order-sensitive aggregate. This means we have more evictions if this is the case. I'll have to do some more thinking about a proper solution later.

fix: Incorrect first/last aggregate in streaming engine

---

crates/polars-plan/src/dsl/scan_sources.rs
crates/polars-plan/src/plans/conversion/dsl_to_ir/scans.rs
py-polars/tests/unit/io/test_lazy_parquet.py
py-polars/tests/unit/io/test_scan.py

* Supercedes https://github.com/pola-rs/polars/pull/24322
```python
pl.scan_parquet("*non_existent*").collect()
ComputeError: expected at least 1 source
ComputeError: failed to retrieve first file schema (parquet):
expanded paths were empty (path expansion input: 'paths: [Local("*non_existent*")]', glob: true).
Hint: passing a schema can allow this scan to succeed with an empty DataFrame.
pl.scan_parquet([]).collect()
ComputeError: expected at least 1 source
ComputeError: failed to retrieve first file schema (parquet): empty input: paths: [].
Hint: passing a schema can allow this scan to succeed with an empty DataFrame.
```
Note, scanning empty list with a specified schema is only supported / (the hint printed) for parquet.

feat: User-friendly error message on empty path expansion

---

crates/polars-plan/src/plans/aexpr/schema.rs
py-polars/tests/unit/datatypes/test_struct.py
py-polars/tests/unit/operations/arithmetic/test_arithmetic.py

Partial fix for #23663.
*edit: Ready for review and merge.
Notes:
- In this PR, `collect_schema()` will match the engine output for `Struct` arithmetic. The intended output datatype might change in the future (see https://github.com/pola-rs/polars/issues/23797).
- Decimal works on some (e.g., `add`) but not all operations (e.g. `floordiv`). Given that Decimal arithmetic may change, no effort was put into resolving it now.
Ping @coastalwhite

fix: Match output type to engine for `Struct` arithmetic

---

crates/polars-ops/src/frame/join/asof/groups.rs
py-polars/tests/unit/operations/test_join_asof.py

Closes #24383
Fixed issue:
```python
lf1 = pl.LazyFrame(
data={"id": [1], "date": [date(2025, 12, 31)]},
schema={"id": pl.Int16, "date": pl.Date},
).sort("id", "date")
lf2 = pl.LazyFrame(
data={"id": [1], "date": [date(2025, 12, 31)], "value": [2.5]},
schema={"id": pl.Int16, "date": pl.Date, "value": pl.Float32},
).sort("id", "date")
lf1.join_asof(
other=lf2,
on="date",
by="id",
check_sortedness=False,
).collect()
```

fix: Enable all integer dtypes for `by` parameter in `join_asof`

---

crates/polars-arrow/src/ffi/generated.rs
crates/polars-python/src/c_api/mod.rs
crates/polars-python/src/interop/arrow/to_py.rs
py-polars/polars/io/iceberg/functions.py
py-polars/polars/schema.py
py-polars/tests/unit/interop/test_interop.py

* ref https://github.com/pola-rs/polars/issues/15563
This will allow e.g. -
```python
>>> pa.schema(pl.Schema({"x": pl.Int32}))
x: int32
```
Compared to doing:
```python
>>> pl.DataFrame(schema=pl.Schema({"x": pl.Int32})).to_arrow().schema
x: int32
```

feat(python): Add PyCapsule `__arrow_c_schema__` interface to `pl.Schema`

---

crates/polars-parquet/src/arrow/read/deserialize/binview/mod.rs
crates/polars-parquet/src/arrow/read/deserialize/boolean.rs
crates/polars-parquet/src/arrow/read/deserialize/categorical.rs
crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary.rs
crates/polars-parquet/src/arrow/read/deserialize/null.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/float.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
crates/polars-parquet/src/arrow/read/deserialize/utils/mod.rs

Fixes a small regression in Q16 caused by #24401.

perf: Use specialized decoding for all predicates for Parquet dictionary encoding

---

crates/polars-core/src/series/implementations/array.rs
py-polars/tests/unit/operations/unique/test_n_unique.py
py-polars/tests/unit/operations/unique/test_unique.py

Resolves #24389 
Basically mirror implementation of `*_unique` for `list` columns to `array`, with unit test.

feat: Support `unique` / `n_unique` / `arg_unique` for `array` columns

---

docs/source/polars-cloud/providers/aws/permissions.md

This PR adds a section on the Polars Cloud user guide which explains how to assume a different role (See https://github.com/pola-rs/polars-cloud-client/issues/3)

feat: Add user guide section on AWS role assumption

---

py-polars/requirements-dev.txt

This is to deal with jmcnamara/XlsxWriter#1154.

chore: Pin `xlsvwriter` to `3.2.5` or before

---

docs/source/src/python/user-guide/io/cloud-storage.py
docs/source/src/rust/user-guide/io/cloud-storage.rs
docs/source/user-guide/io/cloud-storage.md
py-polars/docs/source/reference/config.rst
py-polars/polars/config.py
py-polars/polars/io/cloud/credential_provider/_builder.py
py-polars/tests/unit/io/cloud/test_credential_provider.py

Mainly for interactive environments, this makes it so that users do not need to pass `credential_provider` on every scan/sink call.
```python
def credential_provider():
raise Exception("hello world")
pl.Config.set_default_credential_provider(credential_provider)
pl.scan_parquet("s3://.../...").collect()
```

feat(python): Add unstable `pl.Config.set_default_credential_provider`

---

crates/polars-plan/src/plans/conversion/dsl_to_ir/scans.rs

This PR adds the `POLARS_MAX_CACHED_METADATA_SCANS` environment variable to control the amount of cached Parquet metadata structs in the IR plan.
This can massively reduce the memory consumption for queries with a lot of scans, but will harm performance as the metadata will need to be resolved twice.
With 100 large file scans this was the outcome:
```shell
$ export POLARS_MAX_CACHED_METADATA_SCANS=1
$ time -f %M python3 100-scans.py
278436  # =  271 MB
$ export POLARS_MAX_CACHED_METADATA_SCANS=0 # turn off pruning
$ time -f %M python3 100-scans.py
3331172 # = 3253 MB
$ export POLARS_MAX_CACHED_METADATA_SCANS=8 # default value
$ time -f %M python3 100-scans.py
503148  # =  491 MB
```
This is a temporary solution until we can probably compress the metadata somehow.
Fixes #22366.

perf: Stop caching Parquet metadata after 8 files

---

crates/polars-plan/src/plans/ir/dot.rs

Closes https://github.com/pola-rs/polars/issues/24526

fix(rust): Escape backslashes in EscapeLabel to produce valid DOT labels

---

crates/polars-stream/src/physical_plan/lower_expr.rs
py-polars/tests/unit/operations/test_group_by.py

Fixes https://github.com/pola-rs/polars/issues/24489.

fix: Correct dtype for cum_agg in streaming engine

---

crates/polars-mem-engine/src/planner/lp.rs
crates/polars-stream/src/nodes/callback_sink.rs
py-polars/tests/unit/io/test_sink_batches.py

The early stop only worked on the streaming engine.
@eitsupi

fix: Sink batches early stop on in-memory engine

---

crates/polars-plan/src/plans/aexpr/function_expr/schema.rs
py-polars/polars/expr/expr.py
py-polars/tests/unit/operations/test_reshape.py

Related issue: #24536
Sibling PR: #24590
Cc @coastalwhite

fix: Do not allow inferring (`-1`) the dimension on any `Expr.reshape` dimension except the first

---

crates/polars-stream/src/physical_plan/fmt.rs

After https://github.com/pola-rs/polars/pull/24532 we were doing some double-escaping.

fix: Newline escaping in streaming show_graph

---

crates/polars-plan/src/plans/conversion/dsl_to_ir/scans.rs
crates/polars-stream/src/nodes/io_sources/multi_scan/components/errors.rs
crates/polars-stream/src/nodes/io_sources/multi_scan/components/forbid_extra_columns.rs
crates/polars-stream/src/nodes/io_sources/multi_scan/pipeline/tasks/reader_starter.rs
py-polars/tests/unit/io/test_multiscan.py

* To see which file the schema of the scan was inferred from, set `POLARS_VERBOSE=1` and search for the following:
`sourcing parquet scan file schema from: `
When encountering an error due to an extra column, the file path will now be included in the error message:
```
polars.exceptions.SchemaError: extra column in file outside of expected schema: c, hint: specify this column in the schema, or pass extra_columns='ignore' in scan options. File containing extra column: '/private/var/folders/40/dbrh5w851n163_9yfmf8v2t40000gn/T/pytest-of-nxs/pytest-203/test_extra_columns_not_ignored0/2'
```

feat: Log which file the schema was sourced from, and which file caused an extra column error

---

.github/workflows/release-python.yml

PyOdide for the so-manyth time has ran into build problems with `mio`. Since many things don't work on PyOdide anyway and the PyOdide package repository doesn't have a recent version of Polars, this disables the PyOdide build for now.

chore: Remove PyOdide from release for now

---

.github/workflows/release-python.yml

Remove the `sdist` as that would now become `sdist-polars-runtime-32`. Because of the indirection it doesn't make much sense anymore. The release will still include the source code with the instruction to compile from source.

ci: Remove dist/ from release python workflow

---

crates/polars-ops/src/frame/join/args.rs
crates/polars-ops/src/frame/join/cross_join.rs
crates/polars-ops/src/frame/join/mod.rs
crates/polars-plan/src/dsl/options/mod.rs
crates/polars-plan/src/plans/ir/format.rs
crates/polars-plan/src/plans/ir/inputs.rs
crates/polars-plan/src/plans/optimizer/predicate_pushdown/join.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/operations/test_cross_join.py

This was already implemented in the streaming engine, I now also quickly added it to the in-memory engine's implementation.
Fixes https://github.com/pola-rs/polars/issues/24663.
Fixes https://github.com/pola-rs/polars/issues/24664.

feat: Implement maintain_order for cross join

---

crates/polars-expr/src/expressions/apply.rs
py-polars/tests/unit/operations/test_over.py

fixes #24616
This PR fixes how `AggregatedScalar` is handled in `ApplyExpr` with single input on group_aware. 
Kindly review, especially around low-level performance implications.

fix: Fix handling of `AggregatedScalar` in `ApplyExpr` single input

---

crates/polars-plan/src/plans/aexpr/properties/general.rs
py-polars/tests/unit/test_predicates.py

Avoid marking `strptime` as `Fallible` if the input is a literal.

perf: Pushdown filter with `strptime` if input is literal

---

crates/polars-io/src/csv/read/buffer.rs
crates/polars-io/src/csv/read/parser.rs

Just spotted this while reviewing @kdn36 's PR (but he just copied what was already there, not blaming him).

refactor(rust): Cleaner whitespace skipping in CSV field parser

---

py-polars/src/polars/datatypes/classes.py

Fixes https://github.com/pola-rs/polars/issues/24729.

docs: Specify that precision=None becomes 38 for Decimal

---

SECURITY.md

Fixed a duplicated article ("a") in SECURITY.md for grammatical correctness.
No content or policy changes.

docs: Fix duplicated article in SECURITY.md

---

crates/polars-arrow/src/bitmap/bitmask.rs

In my local worktree, https://github.com/pola-rs/polars/pull/24298 introduced a type error, where a `u32` was not converted into a `u64`. This patch fixes that error.

fix: Type error in `bitmask::nth_set_bit_u64`

---

py-polars/src/polars/dataframe/group_by.py
py-polars/tests/unit/operations/test_group_by_dynamic.py

fixes #24394
Note - there is still an underlying bug in `agg_groups()`, as documented in the issue. Since this expression is to be deprecated, see https://github.com/pola-rs/polars/issues/22468, the iterable issue has been fixed in the Python code.

fix: Fix iterable on `dynamic_group_by` and `rolling` object

---

py-polars/requirements-dev.txt

* Latest release causes CI failure in our Iceberg interop. Upstream issues:
* https://github.com/apache/iceberg-python/issues/2590
* https://github.com/pydantic/pydantic/issues/12347

ci: Temporarily pin pydantic to fix CI
