pola-rs/polars

- polars/polars-core/src/chunked_array/ops/full.rs
> perf[rust]: use vec![value;n] for ChunkedArray::full

- py-polars/src/apply/mod.rs
- py-polars/tests/test_apply.py
> fix[python]: allow an apply that produces empty list values

- polars/polars-core/src/frame/row.rs
- py-polars/tests/test_schema.py
> fix[python]: improve from_dicts nested null inference

- polars/polars-lazy/src/logical_plan/iterator.rs
- py-polars/tests/test_expr_multi_cols.py
> fix[rust]: ensure left argument of functions is iterated first

- polars/polars-arrow/src/kernels/rolling/no_nulls/min_max.rs
- py-polars/tests/test_rolling.py
> fix[rust]: fix and test all rolling extrema paths

- polars/polars-ops/src/series/ops/various.rs
- py-polars/tests/test_struct.py
> fix[rust]: maintain logical type in value counts

- polars/polars-core/src/series/ops/ewm.rs
- py-polars/tests/test_series.py
> fix[rust]: ewm_mean leading nulls function

- polars/polars-lazy/src/dot.rs
- polars/polars-lazy/src/dsl/eval.rs
- polars/polars-lazy/src/dsl/list.rs
- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/logical_plan/alp.rs
- polars/polars-lazy/src/logical_plan/builder.rs
- polars/polars-lazy/src/logical_plan/conversion.rs
- polars/polars-lazy/src/logical_plan/format.rs
- polars/polars-lazy/src/logical_plan/mod.rs
- polars/polars-lazy/src/physical_plan/executors/cache.rs
- polars/polars-lazy/src/physical_plan/mod.rs
- polars/polars-lazy/src/physical_plan/planner/expr.rs
- polars/polars-lazy/src/physical_plan/planner/lp.rs
- polars/polars-lazy/src/physical_plan/planner/mod.rs
- polars/polars-lazy/src/physical_plan/state.rs
- polars/polars-lazy/src/prelude.rs
- py-polars/tests/test_lazy.py
> fix[rust]: fix cache on duplicate schemas

- polars/polars-lazy/src/logical_plan/mod.rs
- py-polars/tests/test_schema.py
> fix[rust]: make schema fallible

- polars/polars-time/src/chunkedarray/utf8/strptime.rs
- py-polars/tests/test_datelike.py
> fix[rust]: parse date when day is omitted

- polars/polars-core/src/chunked_array/logical/categorical/builder.rs
- polars/polars-core/src/chunked_array/logical/categorical/ops/full.rs
- py-polars/tests/test_categorical.py
> fix[rust]: Categorical::default respect global string cache

- polars/polars-core/src/datatypes/mod.rs
- polars/polars-core/src/frame/row.rs
- polars/polars-core/src/utils/mod.rs
- polars/polars-io/src/csv/utils.rs
- py-polars/src/apply/dataframe.rs
- py-polars/src/dataframe.rs
- py-polars/tests/test_schema.py
> fix[rust] schema inference use supertype instead of first non null

- polars/polars-lazy/src/logical_plan/mod.rs
- py-polars/polars/internals/lazyframe/frame.py
- py-polars/src/lazy/dataframe.rs
- py-polars/tests/test_schema.py
The outputs schema is now checked for correctness and users are able to set the output schema.
Also added warnings about using custom functions in the docstring.
closes #4484
> fix[python]: improve LazyFrame.map

- py-polars/Cargo.toml
- py-polars/src/apply/mod.rs
- py-polars/src/apply/series.rs
- py-polars/src/conversion.rs
- py-polars/src/dataframe.rs
- py-polars/src/datatypes.rs
- py-polars/src/lazy/dataframe.rs
- py-polars/src/lazy/dsl.rs
- py-polars/src/lazy/mod.rs
- py-polars/src/series.rs
This makes it faster to get a minimal release build for local benchmarking.
> chore[python]: feature flag features

- polars/polars-lazy/src/dsl/function_expr/mod.rs
- polars/polars-lazy/src/dsl/function_expr/strings.rs
- polars/polars-lazy/src/dsl/string.rs
- py-polars/polars/internals/expr/string.py
- py-polars/src/lazy/dsl.rs
- py-polars/tests/test_strings.py
> feat[rust]: allow expressions as arguments in str::replace(_all)

- polars/polars-core/src/series/unstable.rs
- py-polars/tests/test_datelike.py
> fix[rust]: keep logical type in deep-clone unstable series

- py-polars/polars/convert.py
- py-polars/polars/internals/construction.py
- py-polars/polars/internals/dataframe/frame.py
- py-polars/src/dataframe.rs
> feat[python]: add more infer_schema_length arguments

- polars/polars-core/src/series/ops/round.rs
- polars/polars-core/src/utils/mod.rs
This saves an expensive allocation.
> feat[rust]: make clip expr inplace when owned

- polars/polars-core/src/datatypes/mod.rs
- polars/polars-core/src/frame/asof_join/mod.rs
- polars/polars-core/src/series/ops/round.rs
- polars/polars-lazy/src/dsl/function_expr/clip.rs
- polars/polars-lazy/src/dsl/function_expr/mod.rs
- polars/polars-lazy/src/dsl/function_expr/nan.rs
- polars/polars-lazy/src/dsl/mod.rs
- py-polars/docs/source/reference/expression.rst
- py-polars/docs/source/reference/series.rst
- py-polars/polars/internals/expr/expr.py
- py-polars/polars/internals/series/series.py
- py-polars/src/lazy/dsl.rs
- py-polars/tests/test_lazy.py
Also manually implement serde for `AnyValue` to get rid of the static lifetime issues.
> feat[rust, python]: clip_min,clip_max exprs

- py-polars/polars/convert.py
> Clarify `polar.from_*` clones data

- polars/polars-lazy/src/dsl/function_expr/mod.rs
- polars/polars-lazy/src/dsl/function_expr/strings.rs
- polars/polars-lazy/src/dsl/string.rs
- py-polars/src/lazy/dsl.rs
- py-polars/tests/test_queries.py
> fix[python]: str.upper/lowercase correct schema

- polars/polars-core/src/error.rs
- polars/polars-core/src/frame/mod.rs
- polars/polars-lazy/src/physical_plan/executors/groupby_dynamic.rs
- polars/polars-lazy/src/physical_plan/executors/groupby_rolling.rs
- polars/polars-time/src/groupby/dynamic.rs
- polars/src/lib.rs
- py-polars/tests/test_rolling.py
> fix[rust]: fix slice pushdown in rolling/dynamic groupby

- README.md
List optional dependencies for polars in README.
Add link to nodejs-polars github repo in README.
> docs[python]: List optional dependencies for polars in README.

- .github/workflows/create-py-release-manylinux.yaml
- py-polars/Cargo.lock
- py-polars/Cargo.toml
> python polars 0.14.5

- .github/ISSUE_TEMPLATE/bug_report_nodejs.yml
- .github/ISSUE_TEMPLATE/bug_report_rust.yml
- .github/labeler.yml
- .github/workflows/docs.yaml
- CHANGELOG.md
- py-polars/CHANGELOG.md
- py-polars/docs/source/reference/datatypes.rst
- py-polars/docs/source/reference/exceptions.rst
Remove trailing whitespace from various files.
> [chore]: Remove trailing whitespace.

- polars/polars-core/src/chunked_array/mod.rs
- polars/polars-core/src/series/ops/to_list.rs
- polars/polars-lazy/src/dsl/function_expr/list.rs
- polars/polars-lazy/src/dsl/function_expr/mod.rs
- polars/polars-lazy/src/dsl/functions.rs
- py-polars/tests/test_datelike.py
> fix[rust]: fast to_list keep logical type

- polars/polars-io/src/csv/parser.rs
- polars/polars-io/src/csv/read_impl.rs
- polars/polars-io/src/ndjson_core/ndjson.rs
- py-polars/Makefile
- py-polars/tests_slower/test_csv.py
> fix[rust]: csv statistics also sample from end of file

- polars/polars-io/src/csv/parser.rs
- polars/polars-io/src/csv/read_impl.rs
- polars/polars-io/src/csv/utils.rs
- py-polars/tests/io/test_csv.py
> fix[rust]: skip_rows_after_header improve count

- py-polars/polars/internals/expr/expr.py
- py-polars/polars/internals/series/series.py
- py-polars/src/series.rs
- py-polars/tests/test_lists.py
> fix[python]: ensure is_in empty list has dtype null

- py-polars/polars/internals/construction.py
- py-polars/polars/internals/series/series.py
- py-polars/tests/test_series.py
fix[python]: Set dtype for empty Series if possible.
> fix[python]: Set dtype for empty Series if possible.

- polars/polars-core/src/frame/groupby/proxy.rs
- polars/polars-lazy/src/physical_plan/expressions/filter.rs
- polars/polars-lazy/src/physical_plan/expressions/mod.rs
- polars/polars-lazy/src/utils.rs
- py-polars/tests/test_filter.py
> fix[rust]: fix filter(is_in) in groupby context

- py-polars/polars/internals/expr/expr.py
- py-polars/polars/internals/series/series.py
- py-polars/src/series.rs
This is the last of the low-hanging fruit.
There are some cases where the methods are similar but slightly different - I will look into those and send a separate PR if needed.
> refactor[python]: Dispatch more `Series` methods to `Expr`

- polars/polars-core/src/series/arithmetic/borrowed.rs
- polars/polars-core/src/series/implementations/dates_time.rs
- polars/polars-core/src/utils/mod.rs
- polars/polars-lazy/src/logical_plan/optimizer/simplify_expr.rs
- py-polars/tests/test_datelike.py
> fix[rust]: keep date dtype in date + duration

- polars/polars-arrow/src/kernels/set.rs
- polars/polars-core/src/chunked_array/ops/mod.rs
- polars/polars-core/src/chunked_array/ops/set.rs
- py-polars/polars/internals/series/_numpy.py
- py-polars/polars/internals/series/series.py
- py-polars/polars/utils.py
- py-polars/src/series.rs
- py-polars/src/set.rs
- py-polars/tests/test_interop.py
- py-polars/tests/test_series.py
> fix[python]: make view memory safe

- polars/polars-core/src/serde/mod.rs
- polars/polars-core/src/serde/series.rs
- py-polars/tests/test_serde.py
> fix[rust]: serde timeunit of datetime type

- polars/polars-lazy/src/logical_plan/alp.rs
- polars/polars-lazy/src/logical_plan/builder.rs
- polars/polars-lazy/src/logical_plan/mod.rs
- polars/polars-lazy/src/logical_plan/schema.rs
- py-polars/tests/test_schema.py
> fix[rust]: fix joinasof + by schema

- polars/polars-arrow/src/kernels/sorted_join/left.rs
- polars/polars-core/src/chunked_array/ops/chunkops.rs
- polars/polars-core/src/datatypes/mod.rs
- polars/polars-core/src/series/from.rs
- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/tests/mod.rs
- polars/polars-lazy/src/tests/queries.rs
Changes:
* Fix warnings in Rust tests
> test[rust]: Fix test warnings

- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/expr/expr.py
- py-polars/polars/internals/series/series.py
- py-polars/src/series.rs
- py-polars/tests/test_exprs.py
> Revert "feat[python]!: Update `Expr.sample` signature and change random seeding"

- .github/workflows/test-python.yaml
- py-polars/polars/internals/series/series.py
> fix[python]: fix and test import without numpy

- .github/workflows/create-py-release-manylinux-lts-cpu.yaml
- .github/workflows/create-py-release-manylinux.yaml
- polars/polars-lazy/src/physical_plan/expressions/mod.rs
- py-polars/Cargo.lock
- py-polars/Cargo.toml
An early release because of many report issues with pip installs. Change manylinux 2_24 to 2_17
> python polars 0.14.7

- .github/workflows/benchmark.yaml
- .github/workflows/build-test.yaml
- .github/workflows/coverage.yaml
- .github/workflows/docs_check.yaml
- .github/workflows/fmt_all.yaml
- .github/workflows/test-python.yaml
- .github/workflows/test-windows-python.yaml
- .github/workflows/test-windows.yaml
> Revert "ci: Cancel in-progress runs"

- py-polars/src/conversion.rs
- py-polars/src/lazy/dsl.rs
- py-polars/src/lib.rs
- py-polars/tests/test_errors.py
> feat[python]: turn invalid datatype panic to error

- .github/workflows/create-py-mac-universal2-release.yaml
- .github/workflows/create-py-release-manylinux.yaml
- .github/workflows/create-py-release-windows-macos.yaml
- polars/polars-core/src/chunked_array/ops/aggregate.rs
- py-polars/Cargo.lock
- py-polars/Cargo.toml
- py-polars/polars/internals/series/series.py
- py-polars/tests/test_utf8.py
Patch for `0.14.7` which will be yanked. There was an infinite loop in the optimizer.
> python polars 0.14.8

- .github/workflows/coverage.yaml
> ci: do not run coverage on PRs

- py-polars/Cargo.lock
> chore[python]: run cargo update

- polars/polars-lazy/src/frame/mod.rs
- py-polars/tests/test_schema.py
> fix[rust]: fix rename edge case caused by redundant mappings

- polars/polars-core/src/chunked_array/logical/categorical/merge.rs
- polars/polars-core/src/chunked_array/logical/categorical/mod.rs
- polars/polars-core/src/chunked_array/ops/append.rs
- polars/polars-core/src/chunked_array/ops/chunkops.rs
- polars/polars-core/src/chunked_array/ops/extend.rs
- polars/polars-core/src/chunked_array/ops/shift.rs
- polars/polars-core/src/series/implementations/list.rs
- polars/polars-lazy/src/tests/queries.rs
- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/test_constructors.py
- py-polars/tests/test_datelike.py
- py-polars/tests/test_lists.py
> fix[rust]: keep list<cat> on rechunk

- polars/polars-core/src/series/implementations/object.rs
- polars/polars-lazy/src/logical_plan/lit.rs
- py-polars/Cargo.toml
- py-polars/polars/_html.py
- py-polars/polars/internals/lazy_functions.py
- py-polars/src/conversion.rs
- py-polars/src/lazy/dsl.rs
- py-polars/src/lib.rs
- py-polars/tests/test_object.py
> feat[python]: allow object literals

- polars/polars-io/src/avro/read.rs
- polars/polars-io/src/ipc/ipc_file.rs
- polars/polars-io/src/ipc/ipc_stream.rs
- polars/polars-io/src/ipc/mmap.rs
- polars/polars-io/src/parquet/read.rs
- polars/polars-io/src/utils.rs
- py-polars/tests/unit/io/test_ipc.py
> fix[rust]: process columns arg in memmapped ipc

- polars/polars-core/src/frame/asof_join/groups.rs
- polars/polars-core/src/frame/groupby/hashing.rs
- polars/polars-core/src/frame/hash_join/mod.rs
- polars/polars-core/src/frame/hash_join/multiple_keys.rs
- polars/polars-core/src/frame/mod.rs
- polars/polars-core/src/utils/mod.rs
- polars/polars-lazy/src/physical_plan/executors/groupby_partitioned.rs
- polars/tests/it/core/joins.rs
- py-polars/src/dataframe.rs
- py-polars/tests/unit/test_joins.py
> fix[rust]: fix alignment in joins

- polars/polars-lazy/src/logical_plan/alp.rs
- polars/polars-lazy/src/logical_plan/builder.rs
- polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs
- polars/polars-lazy/src/logical_plan/schema.rs
- polars/polars-lazy/src/physical_plan/planner/lp.rs
- polars/polars-lazy/src/utils.rs
- py-polars/tests/unit/test_joins.py
> fix[rust]: inform projection optimizer of inline join expressions

- polars/polars-arrow/Cargo.toml
- polars/polars-core/Cargo.toml
- polars/polars-io/Cargo.toml
- py-polars/Cargo.lock
See: https://github.com/jorgecarleitao/arrow2/pull/1243
> fix[rust]: fix comparison_and_validity kernels upstream

- polars/polars-arrow/src/compute/take/mod.rs
- polars/polars-core/src/chunked_array/ops/take/mod.rs
- polars/polars-core/src/chunked_array/ops/take/traits.rs
We had an early break which prevented auto SIMD.
> perf[rust]: SIMD accelerate bound checks in take

- polars/polars-core/src/frame/groupby/mod.rs
- polars/polars-lazy/src/frame/mod.rs
- py-polars/polars/internals/lazyframe/groupby.py
- py-polars/src/lazy/dataframe.rs
- py-polars/tests/unit/test_lazy.py
> fix[rust, python]: accept schema in lazy groupby apply

- py-polars/docs/source/reference/dataframe.rst
- py-polars/polars/internals/__init__.py
- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/type_aliases.py
> feat[python]: unstack operation

- polars/polars-arrow/Cargo.toml
- polars/polars-core/Cargo.toml
- polars/polars-io/Cargo.toml
- py-polars/Cargo.lock
- py-polars/tests/unit/test_queries.py
> fix: fix null not-equal; fixed upstream

- .github/workflows/build-test.yaml
- .github/workflows/docs.yaml
- .github/workflows/docs_check.yaml
- .github/workflows/test-python.yaml
- .github/workflows/test-windows-python.yaml
- .github/workflows/test-windows.yaml
- polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/utils.rs
- polars/polars-lazy/src/tests/queries.rs
- polars/polars-lazy/src/utils.rs
- py-polars/tests/unit/test_df.py
Could use a borrow checker for my expression arena. :sweat_smile: 
fixes #4770
> fix[rust]: fix predicate pushdown of unions

- polars/polars-lazy/src/logical_plan/aexpr.rs
- py-polars/tests/unit/test_lazy.py
fixes #4736
Can do the whole alphabet now. 💪
> fix[rust]: fix quadratic behavior in deeply nested expressions

- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/physical_plan/expressions/binary.rs
- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/lazyframe/frame.py
- py-polars/tests/unit/test_groupby.py
> fix[rust]: fix groupby_dynamic flat agg type

- README.md
- py-polars/pyproject.toml
Facilitates install all optional dependencies at once.
Needs #4809 to go in first.
> feat[python]: Add "all" optional dependency

- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/test_df.py
* add count and null_count (issue #4068)
* add support for non-numeric/bool types such as dates, strings and categoricals
> feat[python]: Improve DataFrame.describe()

- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/logical_plan/optimizer/aggregate_pushdown.rs
- polars/polars-lazy/src/logical_plan/optimizer/cache_states.rs
- polars/polars-lazy/src/logical_plan/optimizer/drop_nulls.rs
- polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs
- polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/utils.rs
- polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs
- polars/polars-lazy/src/logical_plan/optimizer/simplify_expr.rs
- polars/polars-lazy/src/physical_plan/planner/expr.rs
- polars/polars-lazy/src/physical_plan/planner/lp.rs
- polars/polars-lazy/src/utils.rs
- py-polars/polars/internals/lazy_functions.py
- py-polars/polars/internals/lazyframe/frame.py
@SimonSchneider Could you run your tests against this branch? I want to ensure that what we do is correct before shipping it.
> refactor[rust, python]: default to cse

- polars/polars-lazy/src/physical_plan/executors/cache.rs
- polars/polars-time/src/chunkedarray/utf8/strptime.rs
- py-polars/tests/unit/test_datelike.py
> fix[rust]: fix panic in strptime

- polars/polars-io/src/csv/utils.rs
- polars/tests/it/io/csv.rs
- py-polars/tests/unit/io/test_csv.py
> feat[rust]: autorename duplicated column in csv parsing

- py-polars/docs/source/conf.py
- py-polars/polars/convert.py
- py-polars/polars/internals/construction.py
- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/io.py
This is basically a replacement for https://github.com/pola-rs/polars/pull/4633. I brought the same config across and similar reference updates. Screenshots should still be relevant.
> docs[python]: configure intersphinx mapping & update references

- polars/polars-lazy/src/dsl/expr.rs
- polars/polars-lazy/src/dsl/mod.rs
- polars/polars-lazy/src/logical_plan/builder.rs
- polars/polars-lazy/src/logical_plan/iterator.rs
- polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs
- polars/polars-lazy/src/logical_plan/projection.rs
- polars/polars-lazy/src/logical_plan/schema.rs
- polars/polars-lazy/src/utils.rs
- polars/polars-utils/src/arena.rs
- py-polars/tests/unit/test_schema.py
> fix[rust]: fill_null static schema

- polars/polars-lazy/src/dsl/dt.rs
- polars/polars-lazy/src/dsl/function_expr/datetime.rs
- polars/polars-lazy/src/dsl/function_expr/mod.rs
- polars/polars-lazy/src/dsl/function_expr/schema.rs
- polars/polars-time/src/chunkedarray/date.rs
- polars/polars-time/src/chunkedarray/datetime.rs
- polars/polars-time/src/chunkedarray/kernels.rs
- polars/polars-time/src/series/mod.rs
- py-polars/docs/source/reference/expression.rst
- py-polars/docs/source/reference/series.rst
- py-polars/polars/internals/expr/datetime.py
- py-polars/polars/internals/series/datetime.py
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/test_datelike.py
> feat[rust]: add iso_year and make dt computed attributes serde

- polars/polars-lazy/src/frame/csv.rs
> fix[rust]: fix panic in csv globbing arguments

- py-polars/polars/internals/series/series.py
- py-polars/src/series.rs
- py-polars/tests/unit/test_apply.py
> feat[python]: allow Series.apply to include null values

- polars/polars-core/src/chunked_array/logical/struct_/mod.rs
- py-polars/tests/unit/test_struct.py
> fix[rust]: struct broadcasting

- py-polars/Cargo.lock
- py-polars/Cargo.toml
Revert using `zlib-ng` until #4858 and #3895 is resolved.
> refactor[python]: revert decompress-fast for python

- polars/polars-lazy/src/logical_plan/optimizer/simplify_expr.rs
- py-polars/polars/internals/expr/expr.py
- py-polars/polars/internals/lazy_functions.py
- py-polars/tests/unit/test_predicates.py
> fix[rust]: don't unwrap if lp has no input

- polars/polars-time/src/chunkedarray/utf8/strptime.rs
- py-polars/tests/unit/test_datelike.py
> fix[rust]: strptime should not panic on invalid dates

- polars/polars-lazy/src/physical_plan/executors/filter.rs
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/test_errors.py
- py-polars/tests/unit/test_utf8.py
> fix[python]: fix json_path_match dtype

- polars/polars-lazy/src/logical_plan/optimizer/cache_states.rs
- polars/polars-lazy/src/logical_plan/optimizer/cse.rs
- polars/polars-lazy/src/tests/cse.rs
- polars/polars-lazy/src/utils.rs
> fix[rust]: fix trails collection and comparison in cse optimzer

- py-polars/polars/internals/series/series.py
- py-polars/tests/unit/test_arithmetic.py
> fix[python]: dispatch logical type arithmetic to series

- polars/polars-core/src/chunked_array/logical/categorical/builder.rs
- polars/polars-core/src/frame/row.rs
- polars/polars-io/src/csv/buffer.rs
- polars/polars-io/src/csv/parser.rs
- polars/polars-io/src/csv/read.rs
- py-polars/tests/unit/io/test_csv.py
@ghuls can you take it for a spin :) ?
> perf[rust]: build categoricals in csv reader

- polars/polars-core/src/chunked_array/arithmetic.rs
- polars/polars-core/src/chunked_array/ops/apply.rs
- polars/polars-core/src/chunked_array/ops/downcast.rs
- polars/polars-ops/src/chunked_array/set.rs
- py-polars/tests/unit/test_sort.py
> fix[rust]: unset sorted flag on mutation

- polars/polars-core/src/series/series_trait.rs
- polars/polars-lazy/src/dsl/functions.rs
- py-polars/polars/internals/lazy_functions.py
- py-polars/src/lib.rs
- py-polars/tests/unit/test_functions.py
> feat[rust]: spearman rank null/nan handling

- polars/polars-arrow/src/kernels/ewm/average.rs
- polars/polars-arrow/src/kernels/ewm/variance.rs
- polars/polars-core/src/series/ops/ewm.rs
- py-polars/tests/unit/test_exprs.py
> fix[python, rust]: properly handle multiple chunks in ewm computations

- polars-sql/Cargo.toml
- polars-sql/src/context.rs
- polars-sql/src/lib.rs
- polars-sql/src/main.rs
- py-polars/src/dataframe.rs
> ci[python]: allow deprecated calls

- polars/polars-core/src/frame/groupby/aggregations/mod.rs
> fix[rust]: fix invalid length bitmask in _rolling_apply_agg_window_nulls

- py-polars/polars/internals/construction.py
- py-polars/tests/unit/test_constructors.py
- py-polars/tests/unit/test_series.py
> feat[python]: allow construction of 2D numpy arrays (list type)

- polars-sql/src/context.rs
- polars-sql/src/sql_expr.rs
- py-polars/docs/source/reference/sql.rst
- py-polars/tests/unit/test_sql.py
> feat[sql]: compounded names in join operation and is between expressions

- polars/polars-core/src/serde/chunked_array.rs
- polars/polars-core/src/serde/mod.rs
- polars/polars-core/src/serde/series.rs
- py-polars/polars/testing.py
- py-polars/tests/unit/io/test_json.py
> feat[rust]: add time and categorical to serde types

- polars/polars-lazy/src/dsl/function_expr/fill_null.rs
- py-polars/tests/unit/test_errors.py
> fix[rust]: error on unknown supertype in fill null

- polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs
- py-polars/tests/unit/test_projections.py
> fix[rust]: block projection pd on melt if no values-args given

- polars/polars-time/src/chunkedarray/kernels.rs
- py-polars/tests/unit/test_datelike.py
~~Unit test that simply reproduces time zone conversion bug. Sadly my Rust skills aren't good enough to actually fix it :)~~
Turns out the fix was straightforward :)
> Time zone conversion bug (NY -> UTC works, UTC -> NY doesn't)

- polars/polars-arrow/src/kernels/ewm/average.rs
Resolves numerical instability issue identified in #5011
> fix[python, rust]: special-case `ewm_mean(alpha=1)`

- polars/polars-lazy/polars-plan/Cargo.toml
- polars/polars-lazy/polars-plan/src/lib.rs
> docs: fix docs by activating docfg feature

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown.rs
- polars/polars-lazy/src/tests/optimization_checks.rs
> performance[rust]: improve predicate pushdown + with_columns

- .github/workflows/test-python.yaml
- py-polars/requirements-dev.txt
Properly resolves #4957
Properly resolves #4966
Changes:
* Update `mypy` from 0.971 to 0.981
> chore: Update mypy

- py-polars/polars/internals/lazyframe/frame.py
```python
(df, timings) = some_long_lazy_computation.profile(show_plot=True)
```
> feat(python): add gantt chart plot to LazyFrame::profile

- py-polars/polars/utils.py
- py-polars/tests/unit/test_datelike.py
> fix(python): tz-aware get_idx

- polars/polars-time/src/chunkedarray/kernels.rs
- py-polars/tests/unit/test_datelike.py
> fix(rust): fix iso_year for Date dtype

- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/test_df.py
> refactor(python): deprecate name argument in drop

- polars/polars-core/src/frame/asof_join/groups.rs
- py-polars/tests/unit/test_errors.py
> feat(rust, python): error on invalid asof join inputs

- polars/polars-core/src/chunked_array/ops/unique/mod.rs
- py-polars/tests/unit/test_lazy.py
> fix(rust, python): unique include null

- py-polars/polars/internals/series/series.py
> fix(python): add missing _NUMPY_AVAILABLE check in Series.__getitem__

- polars/polars-io/src/csv/parser.rs
+ some tests for it to assert behavior stays the same. 
Yeah buddy! :tada:
> Get rid of unnecessary check in SplitLines iterator

- polars/polars-core/src/datatypes/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/list.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- polars/polars-lazy/polars-plan/src/dsl/list.rs
- py-polars/polars/internals/expr/list.py
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/test_lists.py
> feat(rust, python): accept expressions in arr.slice

- py-polars/polars/internals/lazyframe/frame.py
- py-polars/tests/unit/test_series.py
> fix(python): DataFrame.fill_null include unsigned integers

- polars/polars-arrow/src/kernels/list.rs
- py-polars/tests/unit/test_lists.py
> fix(rust, python): include offset in arr.get

- py-polars/tests/unit/test_df.py
> test(python): skip failing test until #5177 is resolved

- py-polars/src/series.rs
- py-polars/tests/unit/test_apply.py
> fix(python): fix apply function over object dtype

- polars/polars-arrow/src/kernels/rolling/no_nulls/variance.rs
- py-polars/tests/unit/test_rolling.py
> fix(rust, python): improve numeric stability of rolling_variance

- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- py-polars/polars/utils.py
- py-polars/src/conversion.rs
- py-polars/tests/unit/test_datelike.py
> fix(rust, python): fix incorrect duration dtype

- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- polars/polars-time/Cargo.toml
- polars/polars-time/src/chunkedarray/datetime.rs
- polars/polars-time/src/date_range.rs
- polars/polars-time/src/groupby/dynamic.rs
- polars/polars-time/src/upsample.rs
- polars/tests/it/lazy/expressions/expand.rs
- polars/tests/it/lazy/groupby_dynamic.rs
- py-polars/Cargo.lock
- py-polars/polars/internals/functions.py
- py-polars/src/lib.rs
- py-polars/tests/unit/test_datelike.py
> feat(rust, python): make date_range timezone aware

- py-polars/polars/utils.py
> fix(python): don't use zoneinfo globally

- py-polars/Cargo.lock
- py-polars/Cargo.toml
> python polars 0.14.21

- polars/polars-core/src/series/from.rs
- polars/polars-core/src/series/implementations/categorical.rs
- polars/polars-core/src/series/implementations/dates_time.rs
- polars/polars-core/src/series/implementations/datetime.rs
- polars/polars-core/src/series/implementations/duration.rs
- polars/polars-core/src/series/implementations/mod.rs
- polars/polars-core/src/series/implementations/struct_.rs
> fix(rust): tag IntoSeries trait as unsafe

- py-polars/polars/convert.py
- py-polars/polars/import_check.py
- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/series/series.py
> perf(python): remove pandas imports

- polars/polars-core/src/frame/row.rs
- py-polars/polars/convert.py
- py-polars/polars/internals/dataframe/frame.py
- py-polars/src/dataframe.rs
- py-polars/tests/unit/test_constructors.py
> feat(python): accept schema in read_dicts

- py-polars/src/dataframe.rs
> fix(python): fix to_pandas edge case

- py-polars/src/apply/mod.rs
> feat(python): improve error message in struct apply

- polars/polars-core/src/series/any_value.rs
- py-polars/src/dataframe.rs
- py-polars/tests/unit/test_constructors.py
> feat(rust, python): improve dynamic inference of struct types

- py-polars/docs/source/reference/series.rst
- py-polars/polars/internals/series/list.py
Was already available as expression.
> feat(python): expose to_struct to series list namespace

- py-polars/polars/internals/construction.py
> fix(python): close multi-threading pool in df creation

- polars/polars-core/src/frame/hash_join/sort_merge.rs
- py-polars/tests/unit/test_joins.py
> fix(rust, python): fix sort-merge dispatch of utf8

- py-polars/Cargo.lock
- py-polars/Cargo.toml
An early patch release to fix the import issues on python 3.7. See: #5304
> python polars 0.14.23

- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/src/tests/queries.rs
- polars/tests/it/lazy/queries.rs
- py-polars/polars/internals/lazy_functions.py
- py-polars/src/lazy/apply.rs
- py-polars/src/lib.rs
> fix(rust): don't set auto-explode in apply_multiple

- polars/polars-lazy/polars-plan/src/dsl/expr.rs
- py-polars/tests/unit/io/test_pickle.py
> fix(python, rust): fix serde of expression (pickle)

- polars/polars-core/src/datatypes/aliases.rs
- polars/polars-core/src/series/any_value.rs
- py-polars/polars/datatypes.py
- py-polars/polars/internals/expr/list.py
- py-polars/polars/internals/series/list.py
- py-polars/src/conversion.rs
- py-polars/tests/unit/test_constructors.py
- py-polars/tests/unit/test_lists.py
> fix(python): nested dicts / list generation

- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/test_df.py
> fix(python): remove unused branch in getitem

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown.rs
- py-polars/tests/unit/test_projections.py
> fix(rust, python): unnest only pushdown column if there are projections

- polars/polars-time/src/chunkedarray/utf8/patterns.rs
- polars/tests/it/io/csv.rs
- py-polars/tests/unit/io/test_csv.py
Add possible solution for  #5365
> feat(rust, python): add support for am/pm notation in parse_dates read_csv

- py-polars/polars/internals/expr/expr.py
Added docstrings for:
- `search_sorted`
- `top_k`
- `nan_min`
- `nan_max`
Added nan examples for `min` and `max`
Added forward strategy to `fill_null`
> docs(python): Expression docstrings

- polars/polars-arrow/src/kernels/rolling/mod.rs
- polars/polars-core/src/chunked_array/ops/aggregate.rs
@zundertj does this change #5375?
> fix(rust, python): explicit nan comparison in min/max agg

- polars/polars-core/src/chunked_array/ops/sort/argsort_multiple.rs
- py-polars/tests/unit/test_sort.py
> fix(rust, python): don't set sorted flag in argsort

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/cache_states.rs
- polars/polars-lazy/src/tests/queries.rs
- py-polars/tests/unit/test_cse.py
> fix(rust, python): fix cse for nested caches

- .github/workflows/create-py-release-manylinux-lts-cpu.yaml
- py-polars/src/lib.rs
Linked to https://github.com/pola-rs/polars/issues/5401
> chore: Allow for choice in memory allocator and use mimalloc for polars-lts-cpu

- py-polars/Cargo.toml
Completes the work done here: https://github.com/pola-rs/polars/pull/5414
Fixes this issue: https://github.com/pola-rs/polars/issues/5401
> chore(python): Fix dependencies on memory allocator

- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/utils.rs
> refactor(rust): use IdHash for streaming groupby generic

- py-polars/polars/internals/lazyframe/frame.py
- py-polars/tests/unit/test_datelike.py
Use of `fill_null` with any temporal literal currently fails (eg: datetime, date, time, timedelta). Fixed, along with adding a generic `pl.lit` fallback and test coverage:
**Setup:** _(example)_
```python
data = [[date.today(), None, date.today()]], 
columns = ["dt"],
)
```
**Before:** _(exception)_
```python
df.fill_null( date.max )
```
**After:** _(succeeds)_
```python
df.fill_null( date.max )
```
> fix(python): use of `fill_null` with temporal literals

- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/test_serde.py
> fix(python): use json for expr pickle

- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- py-polars/polars/internals/lazy_functions.py
- py-polars/tests/unit/test_functions.py
> fix(rust, python): fix coalesce expreession expansion

- polars/polars-lazy/polars-plan/src/dsl/expr.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/builder.rs
- polars/polars-lazy/polars-plan/src/logical_plan/projection.rs
- py-polars/src/lazy/dsl.rs
Don't panic on a failing python lambda.
> feat(rust, python): make map_alias fallible

- py-polars/polars/internals/dataframe/frame.py
> feat(python): add dataframe.pearson_corr

- polars/polars-core/src/frame/mod.rs
- polars/polars-lazy/polars-pipe/src/executors/operators/projection.rs
- polars/polars-lazy/polars-pipe/src/pipeline/convert.rs
- polars/polars-lazy/src/physical_plan/executors/stack.rs
- py-polars/tests/unit/test_projections.py
> fix(rust, python): streaming hstack allow duplicates

- .github/workflows/lint-global.yaml
Fixes issue introduced in #5576
> ci(python): Fix broken lint workflow

- polars/polars-core/src/chunked_array/temporal/datetime.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- polars/polars-time/src/date_range.rs
- py-polars/polars/internals/construction.py
- py-polars/polars/internals/series/datetime.py
- py-polars/tests/unit/test_datelike.py
> fix(rust, python): invert cast_time_zone conversion

- polars/polars-core/src/chunked_array/temporal/datetime.rs
- polars/polars-time/src/truncate.rs
- py-polars/tests/unit/test_datelike.py
> fix(rust, python): fix tz-awareness of truncate

- polars/polars-core/src/chunked_array/ops/aggregate.rs
- py-polars/tests/unit/test_series.py
> feat(rust, python): add arg_min/arg_max for series of dtype boolean

- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-core/src/chunked_array/logical/struct_/mod.rs
- polars/polars-core/src/datatypes/dtype.rs
- polars/polars-core/src/series/any_value.rs
You can cast `List<Struct<List<64>` to `List<Struct<List<f32>`.
> feat(rust, python): make cast recursive

- py-polars/polars/internals/series/series.py
closes #4716 
NOTE: this is technically a breaking change
> feat(python)!: Change `null_equal` default to `True` for `Series.series_equal`

- polars/polars-time/Cargo.toml
- polars/polars-time/src/groupby/dynamic.rs
- polars/polars-time/src/windows/groupby.rs
- polars/polars-time/src/windows/test.rs
- polars/polars-time/src/windows/window.rs
- polars/tests/it/lazy/groupby_dynamic.rs
- polars/tests/it/lazy/queries.rs
- py-polars/Cargo.lock
- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/dataframe/groupby.py
- py-polars/polars/internals/lazyframe/frame.py
- py-polars/polars/internals/type_aliases.py
- py-polars/src/conversion.rs
- py-polars/src/lazy/dataframe.rs
- py-polars/tests/unit/test_datelike.py
- py-polars/tests/unit/test_rolling.py
> feat(rust, python): groupby_dynamic define start of first window

- .github/deploy_manylinux.sh
- .github/workflows/benchmark.yaml
- .github/workflows/build-test-rust.yaml
- .github/workflows/create-python-release.yaml
- .github/workflows/docs-deploy.yaml
- .github/workflows/lint-python.yaml
- .github/workflows/test-python.yaml
- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-core/src/frame/groupby/expr.rs
- polars/polars-core/src/series/any_value.rs
- polars/polars-core/src/series/mod.rs
- polars/polars-io/src/ndjson_core/buffer.rs
- polars/polars-io/src/ndjson_core/ndjson.rs
- polars/polars-lazy/polars-plan/src/logical_plan/builder.rs
- polars/polars-lazy/src/frame/pivot.rs
- rust-toolchain.toml
Comes with a nice substring search perf improvement. https://github.com/rust-lang/rust/pull/103779
> chore: update to rustc nightly-2022-11-24

- polars/polars-time/src/windows/groupby.rs
- polars/polars-time/src/windows/window.rs
- py-polars/tests/unit/test_rolling.py
no changelog as code was not released.
closes #5620
> no-changelog: fix period in new dynamic groupby starting points

- polars/polars-lazy/polars-plan/src/dot.rs
> fix(rust, python): fix dot diagram of single nodes

- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python): convert panic to err in concat_list

- polars/polars-core/src/frame/mod.rs
- polars/polars-core/src/frame/row.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/aggregates/convert.rs
- polars/polars-lazy/polars-plan/src/logical_plan/aexpr.rs
- polars/polars-lazy/src/physical_plan/planner/lp.rs
- py-polars/polars/internals/lazyframe/frame.py
- py-polars/tests/unit/test_groupby.py
- py-polars/tests/unit/test_streaming.py
> fix(rust, python): fix streaming groupby aggregate types

- py-polars/tests/unit/test_df.py
For some reason, this one slipped into master
> (chore)python: Fix formatting

- polars/polars-core/src/chunked_array/builder/list.rs
- polars/polars-core/src/chunked_array/list/mod.rs
- polars/polars-core/src/chunked_array/mod.rs
- polars/polars-core/src/chunked_array/ops/append.rs
- polars/polars-core/src/chunked_array/ops/explode.rs
- polars/polars-core/src/named_from.rs
- py-polars/polars/internals/series/series.py
- py-polars/src/series.rs
- py-polars/tests/unit/test_constructors.py
- py-polars/tests/unit/test_lists.py
> perf(rust, python): ensure fast_explode propagates

- polars/polars-core/src/chunked_array/ops/aggregate.rs
- py-polars/tests/unit/test_series.py
> fix(rust, python): fix boolean arg-max if all equal

- polars/polars-core/src/chunked_array/arithmetic.rs
- polars/polars-lazy/src/tests/queries.rs
- py-polars/tests/unit/test_schema.py
> fix(rust, python): fix owned arithmetic schema

- polars/polars-core/src/frame/hash_join/mod.rs
- polars/polars-core/src/schema.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown.rs
- polars/polars-lazy/polars-plan/src/logical_plan/schema.rs
- polars/polars-lazy/src/frame/mod.rs
- py-polars/tests/unit/test_joins.py
> fix(rust, python): fix asof join schema

- polars/polars-core/src/utils/mod.rs
- py-polars/docs/source/reference/series/miscellaneous.rst
- py-polars/polars/internals/series/series.py
- py-polars/src/series.rs
- py-polars/tests/unit/test_series.py
> feat(python): Series.get_chunks

- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- py-polars/tests/unit/test_series.py
> fix(rust, python): fix arange with column/literal input

- polars/polars-core/src/chunked_array/ops/bit_repr.rs
- polars/polars-core/src/chunked_array/ops/unique/mod.rs
- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-ops/src/pivot/mod.rs
- py-polars/tests/unit/test_pivot.py
> fix(rust, python): fix pivot on floating point indexes

- py-polars/polars/internals/dataframe/frame.py
> docs(python): fix incorrect accepted type in df.write_csv

- polars/polars-core/src/chunked_array/builder/list.rs
- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-core/src/chunked_array/ndarray.rs
- polars/polars-core/src/fmt.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- polars/polars-time/src/date_range.rs
- py-polars/src/lib.rs
- py-polars/tests/unit/test_datelike.py
> fix(rust, python): fix date_range on expressions

- polars/polars-lazy/polars-plan/src/dsl/expr.rs
- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/aexpr.rs
- polars/polars-lazy/polars-plan/src/logical_plan/conversion.rs
- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/lib.rs
- polars/polars-lazy/src/physical_plan/expressions/aggregation.rs
- polars/polars-lazy/src/physical_plan/planner/expr.rs
- polars/polars-lazy/src/tests/aggregations.rs
- polars/polars-lazy/src/tests/queries.rs
- polars/polars-time/src/windows/test.rs
- polars/tests/it/lazy/aggregation.rs
- polars/tests/it/lazy/mod.rs
- py-polars/polars/internals/expr/expr.py
- py-polars/polars/internals/lazy_functions.py
- py-polars/polars/internals/lazyframe/frame.py
- py-polars/src/lazy/dataframe.rs
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/test_aggregations.py
> feat(rust, python): allow expression as quantile input

- polars/polars-core/src/frame/asof_join/mod.rs
- polars/polars-time/src/windows/groupby.rs
- py-polars/Cargo.toml
- py-polars/src/dataframe.rs
- py-polars/src/lazy/dataframe.rs
- py-polars/src/lazy/dsl.rs
- py-polars/src/lib.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python): check null values in asof_join + groupby

- .github/workflows/lint-python.yaml
- py-polars/docs/source/reference/dataframe/descriptive.rst
- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/test_df.py
> feat(python): Add DataFrame.glimpse()

- polars/polars-io/src/ndjson_core/ndjson.rs
- polars/tests/it/io/json.rs
- py-polars/tests/unit/io/test_json.py
> fix(json): ndjson with trailing newlines

- polars/polars-core/src/chunked_array/logical/struct_/mod.rs
- polars/polars-core/src/utils/mod.rs
- py-polars/polars/internals/construction.py
- py-polars/tests/slow/test_parquet.py
- py-polars/tests/unit/test_struct.py
> fix(python): fix struct dataset

- py-polars/Cargo.toml
Yet another patch due to regression. Hopefully the last one.
> python polars 0.15.6

- polars/polars-core/src/frame/asof_join/groups.rs
- polars/polars-core/src/frame/mod.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_joins.py
> fix(rust, python): asof join by logical groups

- polars/polars-core/src/frame/groupby/aggregations/dispatch.rs
- polars/polars-core/src/frame/groupby/aggregations/mod.rs
- polars/polars-core/src/series/mod.rs
- py-polars/tests/unit/test_aggregations.py
> feat(rust, python): implement mean aggregation for duration

- py-polars/src/dataframe.rs
> feat(python): release GIL when writing

- polars/polars-lazy/polars-plan/src/global.rs
- polars/polars-lazy/src/physical_plan/executors/scan/parquet.rs
- polars/polars-lazy/src/physical_plan/executors/union.rs
- py-polars/tests/slow/test_parquet.py
> fix(rust, python): respect fetch in union

- polars/polars-core/src/fmt.rs
- py-polars/tests/unit/test_fmt.py
> fix(rust, python): duration formatting

- polars/polars-core/src/frame/groupby/mod.rs
- polars/polars-lazy/src/physical_plan/expressions/take.rs
- polars/polars-lazy/src/physical_plan/expressions/window.rs
> perf(rust, python): impove performance reducing window functions with numeric output `~-14%`

- polars/polars-core/src/chunked_array/ops/any_value.rs
- polars/polars-ops/src/series/ops/various.rs
- py-polars/tests/unit/test_struct.py
> fix(rust, python): correct invalid type in struct anyvalue access

- polars/polars-io/src/csv/read_impl/batched.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/slice.rs
- polars/polars-lazy/polars-pipe/src/pipeline/convert.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/slice_pushdown_lp.rs
- polars/polars-utils/src/atomic.rs
- polars/polars-utils/src/lib.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/io/test_lazy_csv.py
> fix(rust, python): fix slice in streaming

- polars/polars-ops/src/chunked_array/top_k.rs
- py-polars/tests/unit/test_empty.py
> fix(rust, python): fix top_k on empty

- polars/polars-core/src/chunked_array/comparison.rs
- polars/polars-core/src/chunked_array/ops/mod.rs
- polars/polars-core/src/frame/row.rs
- polars/polars-core/src/series/comparison.rs
- polars/polars-core/src/testing.rs
- py-polars/tests/unit/test_comparison.py
> fix(rust, python): improve equality consistency between types

- polars/polars-core/src/frame/mod.rs
- polars/polars-lazy/src/frame/mod.rs
- py-polars/tests/unit/test_schema.py
> fix(rust, python): fix lazy swapping rename

- polars/polars-ops/src/chunked_array/top_k.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_sort.py
> fix(rust, python): adapt k to len in topk

- polars/polars-lazy/src/physical_plan/streaming/convert.rs
- py-polars/tests/unit/io/test_parquet.py
> fix(rust, python): fix latest oob in streaming convertion

- polars/polars-core/src/chunked_array/object/builder.rs
- polars/polars-core/src/chunked_array/ops/filter.rs
- py-polars/tests/unit/test_object.py
> fix(rust, python): object filter should keep single chunk

- py-polars/docs/source/reference/dataframe/modify_select.rst
- py-polars/docs/source/reference/expressions/binary.rst
- py-polars/docs/source/reference/expressions/index.rst
- py-polars/docs/source/reference/lazyframe/modify_select.rst
- py-polars/docs/source/reference/series/binary.rst
- py-polars/docs/source/reference/series/descriptive.rst
- py-polars/docs/source/reference/series/index.rst
Those are forgotten in previous PRs.
> docs(python): add bin, series.is_sorted and merge_sorted

- polars/polars-core/src/chunked_array/logical/struct_/from.rs
- polars/polars-core/src/chunked_array/logical/struct_/mod.rs
- polars/polars-core/src/chunked_array/object/builder.rs
- polars/polars-core/src/chunked_array/object/extension/drop.rs
- polars/polars-core/src/chunked_array/object/extension/mod.rs
- polars/polars-core/src/chunked_array/object/extension/polars_extension.rs
- polars/polars-core/src/chunked_array/object/mod.rs
- polars/polars-core/src/chunked_array/object/registry.rs
- polars/polars-core/src/chunked_array/ops/any_value.rs
- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-core/src/fmt.rs
- polars/polars-core/src/series/any_value.rs
- polars/polars-core/src/series/from.rs
- polars/polars-core/src/series/into.rs
- py-polars/src/conversion.rs
- py-polars/tests/unit/test_object.py
> feat(python): allow objects in struct types

- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/mod.rs
- polars/polars-lazy/src/physical_plan/streaming/convert.rs
- py-polars/tests/unit/test_streaming.py
> fix(rust, python): don't create categoricals in streaming

- polars/polars-core/src/series/arithmetic/borrowed.rs
- polars/polars-core/src/utils/supertype.rs
- py-polars/src/series.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python): error on addition with datetime/time

- polars/polars-core/src/series/mod.rs
- py-polars/tests/unit/test_schema.py
> feat(rust, python): allow all null cast

- polars/polars-lazy/polars-plan/src/dsl/function_expr/list.rs
- py-polars/tests/unit/test_lists.py
> fix(rust, python): allow None in arr.slice length

- polars/polars-lazy/polars-plan/src/dot.rs
- polars/polars-lazy/polars-plan/src/logical_plan/format.rs
- py-polars/polars/internals/lazyframe/frame.py
> feat(rust, python): improve query plan scan formatting

- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-core/src/series/from.rs
Better to read something than to fail.
> feat(rust, python): read decimal as f64

- Cargo.toml
- py-polars/Cargo.lock
- py-polars/tests/unit/io/test_parquet.py
fixes #5762 via https://github.com/jorgecarleitao/arrow2/pull/1347
> chore: update arrow

- py-polars/docs/source/reference/dataframe/modify_select.rst
- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/test_df.py
- py-polars/tests/unit/test_rows.py
> feat(python): add iterrrows

- py-polars/polars/datatypes.py
- py-polars/src/dataframe.rs
- py-polars/tests/unit/test_interop.py
> fix(python): fix from_dict schema_inference=0

- polars/polars-lazy/src/dsl/list.rs
- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/test_schema.py
> fix(rust, python): adhere to schema in arr.eval of empty list

- py-polars/polars/datatypes.py
- py-polars/polars/internals/series/series.py
- py-polars/tests/unit/test_errors.py
> fix(python): error on invalid dtype

- py-polars/tests/unit/test_context.py
> fix(rust, python): don't panic on ignored context

- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-core/src/chunked_array/logical/categorical/builder.rs
- polars/polars-core/src/chunked_array/logical/categorical/stringcache.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/functions/mod.rs
- polars/polars-lazy/src/physical_plan/streaming/convert.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
> fix(rust, python): properly deal with categoricals in streaming queries

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
- py-polars/tests/unit/test_filter.py
> fix(rust, python): fix invalid boolean simplification

- polars/polars-core/src/chunked_array/logical/categorical/mod.rs
- polars/polars-core/src/chunked_array/ops/any_value.rs
- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-core/src/fmt.rs
- polars/polars-core/src/series/any_value.rs
- polars/polars-core/src/series/mod.rs
- polars/polars-io/src/csv/write_impl.rs
- polars/polars-lazy/polars-plan/src/logical_plan/lit.rs
- polars/polars-utils/src/sync.rs
- py-polars/src/conversion.rs
- py-polars/tests/unit/io/test_lazy_parquet.py
> fix(rust, python): fix categorical in struct anyvalue issue

- polars/polars-core/src/chunked_array/temporal/datetime.rs
- polars/polars-time/src/chunkedarray/datetime.rs
- polars/polars-time/src/chunkedarray/kernels.rs
- py-polars/tests/unit/test_datelike.py
> fix(rust, python): make weekday tz-aware

- py-polars/polars/internals/expr/expr.py
- py-polars/polars/internals/series/series.py
> feat(python): allow eq,ne,lt etc

- py-polars/Cargo.toml
A patch for a regression regarding categorical values in the new streaming engine. I will yank a few previous releases.
> python polars 0.15.11

- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/series/series.py
- py-polars/polars/utils.py
- py-polars/tests/unit/test_utils.py
> fix(python): Validate `estimated_size` parameter

- polars/polars-core/src/series/ops/diff.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- py-polars/tests/unit/test_functions.py
> fix(rust, python): fix diff overflow

- py-polars/polars/internals/construction.py
- py-polars/polars/internals/io.py
- py-polars/tests/unit/io/test_sql_db.py
Fix SIM105 issues: "Use 'contextlib.suppress(...)' instead of try-except-pass".
> chore(python): Fix SIM105 issues.

- polars/polars-core/src/chunked_array/logical/categorical/stringcache.rs
- py-polars/tests/slow/test_categorical.py
> fix(python): fix stringcache. latest refactor introduced a hashing error

- py-polars/polars/internals/expr/expr.py
> docs(python): suggest forward fill in cumsum/cummax

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/groupby.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/hstack.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/melt.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs
- polars/polars-lazy/polars-plan/src/utils.rs
- polars/tests/it/lazy/projection_queries.rs
> fix(rust, python): deal with unnest schema expansion in projection pd

- polars/polars-core/src/chunked_array/logical/categorical/builder.rs
- polars/polars-core/src/chunked_array/logical/categorical/stringcache.rs
> per(rust, python): use global string cache for rev cat

- polars/polars-core/src/chunked_array/logical/categorical/builder.rs
- polars/polars-core/src/series/comparison.rs
- py-polars/Cargo.lock
> perf(rust, python): first check rev-map on categorical equality check

- polars/polars-io/src/ipc/ipc_file.rs
Fix #6095.
I think the intention was to have an `if verbose`, so I did that.
> fix(rust): Print error message on mmap IPC file only in verbose mode

- py-polars/polars/internals/series/series.py
- py-polars/tests/db-benchmark/various.py
- py-polars/tests/unit/test_datelike.py
- py-polars/tests/unit/test_exprs.py
- py-polars/tests/unit/test_functions.py
- py-polars/tests/unit/test_lazy.py
- py-polars/tests/unit/test_schema.py
Turns out .item() is for the lib itself useful as well.
> chore(python): Use Dataframe.item internally and in tests

- .gitignore
- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-lazy/src/dsl/list.rs
- py-polars/tests/unit/test_categorical.py
> feat(rust, python): allow nested categorical cast

- polars/polars-core/src/fmt.rs
- polars/polars-core/src/lib.rs
- polars/polars-io/src/csv/write_impl.rs
- py-polars/tests/unit/io/test_csv.py
> fix(rust, python): write tz-aware datetimes to csv

- polars/polars-lazy/polars-pipe/src/executors/sinks/joins/generic_build.rs
- polars/polars-lazy/src/tests/streaming.rs
> fix(rust, python): fix empty streaming joins

- py-polars/polars/internals/series/list.py
Explain the behavior of the two n_field_strategy(s).
> docs(python): explain n_field_strategy

- polars/polars-arrow/src/index.rs
- py-polars/Cargo.lock
- py-polars/polars/internals/expr/list.py
- py-polars/polars/internals/series/list.py
- py-polars/tests/unit/test_lists.py
> fix(python): fix oob arr.take

- polars/polars-core/src/chunked_array/ops/explode.rs
- polars/polars-core/src/series/ops/extend.rs
- polars/polars-lazy/src/physical_plan/expressions/binary.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_df.py
> fix(rust, python): explode of empty nullable list

- py-polars/Cargo.toml
Accidentally merged these changes.
> chore(python): undo cargo.toml change

- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/options.rs
- polars/polars-lazy/src/physical_plan/expressions/apply.rs
- polars/polars-lazy/src/physical_plan/planner/expr.rs
- py-polars/tests/unit/test_struct.py
> fix(rust, python): pass name to value counts in aggregation

- py-polars/polars/internals/expr/expr.py
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/test_sort.py
> fix(python): set_sorted keep schema

- polars/polars-lazy/polars-plan/src/logical_plan/alp.rs
- polars/polars-lazy/polars-plan/src/logical_plan/builder.rs
- polars/polars-lazy/polars-plan/src/logical_plan/options.rs
These were missing, causing build to fail of csv-file feature was not enabled.
> chore(rust): Add missing feature attributes for csv-file

- polars/polars-time/src/chunkedarray/utf8/strptime.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_datelike.py
> fix(rust, python): Parse negative dates with polars parser

- py-polars/polars/internals/functions.py
- py-polars/tests/unit/test_datelike.py
> fix(python): Allow low and high in date_range to be str

- Cargo.toml
See: https://github.com/jorgecarleitao/arrow2/pull/1362
> perf(rust, python): reuse allocated scratches in ipc writer

- polars/polars-time/src/chunkedarray/utf8/infer.rs
- py-polars/tests/unit/test_datelike.py
> fix(python): infer y-m-d datetime even if single element

- polars/polars-core/src/series/from.rs
- py-polars/tests/unit/io/test_parquet.py
> fix(rust, python): convert nested dictionary with i64 keys

- py-polars/polars/internals/dataframe/frame.py
Relates to #6292
This will be followed by a breaking PR switching the behaviour to dictionary representation.
> feat(python): Add warning for new behaviour of named rows

- polars/polars-lazy/polars-pipe/src/pipeline/convert.rs
this was erroring out when using only 'parquet' feature.
> fix(rust): feature flag "get_sink" ipc

- polars/polars-time/src/chunkedarray/utf8/strptime.rs
- py-polars/tests/unit/test_datelike.py
> feat(rust, python): parse abbrev month name

- py-polars/polars/internals/series/series.py
- py-polars/tests/unit/test_filter.py
> fix(python): properly dispatch categorical string comparison

- py-polars/polars/internals/series/datetime.py
- py-polars/tests/unit/test_datelike.py
> doc(python): add examples for with_time_zone

- polars/polars-core/src/serde/chunked_array.rs
- polars/polars-core/src/serde/mod.rs
- polars/polars-core/src/serde/series.rs
> fix(rust,python): implement ser/de for StructChunked

- polars/polars-lazy/src/physical_plan/expressions/sortby.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python): raise error on invalid sort_by argument

- py-polars/polars/internals/construction.py
- py-polars/polars/io.py
- py-polars/tests/unit/test_df.py
Closes #6421, and adds the missing test coverage.
> fix(python): fixed interaction of `schema_overrides` with frame-init from list of dicts

- polars/polars-core/src/series/from.rs
- py-polars/tests/unit/test_interop.py
> fix(python): allow from pandas null structs

- polars/polars-lazy/Cargo.toml
- polars/polars-lazy/polars-plan/Cargo.toml
- polars/polars-lazy/polars-plan/src/logical_plan/debug.rs
- polars/polars-lazy/polars-plan/src/logical_plan/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs
- polars/polars-lazy/polars-plan/src/prelude.rs
- py-polars/tests/unit/test_joins.py
> fix(rust, python): fix projection pushdown on double semi join

- py-polars/docs/source/reference/dataframe/modify_select.rst
Shame on me for forgetting this yesterday 😮‍💨
Silver lining: this PR may take the polars land speed record - I'm on the [Shinkansen](https://en.wikipedia.org/wiki/Shinkansen)!
> docs(python): add missing `iter_slices` docs entry

- py-polars/polars/internals/lazy_functions.py
- py-polars/polars/internals/series/series.py
- py-polars/tests/parametric/test_series.py
Credits to @thomasaarholt who raised this issue in #5453 and proposed a fix.
I want this issue resolved so I'm finishing his work in this PR.
> fix(python) Fix typing issue for `Series.to_list`

- py-polars/Cargo.toml
Carefully chose my wording. Planned 0.15.x release. ;) Patch the regression regarding semi joins.
> python polars 0.15.18

- polars/polars-core/src/named_from.rs
- polars/polars-io/src/ipc/ipc_file.rs
- polars/polars-lazy/src/tests/predicate_queries.rs
- polars/polars-lazy/src/tests/streaming.rs
- polars/polars-time/src/chunkedarray/utf8/strptime.rs
- polars/polars-time/src/windows/test.rs
- polars/tests/it/core/pivot.rs
Also removed two unused imports.
> test(rust): Address chrono deprecation warnings

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/cache_states.rs
- polars/tests/it/lazy/cse.rs
- polars/tests/it/lazy/mod.rs
> fix(rust, python): fix cse schema

- polars/polars-lazy/polars-plan/src/dsl/function_expr/list.rs
- py-polars/tests/unit/test_lists.py
> fix(rust, python): fix oob in arr.get by expressions

- polars/polars-core/src/series/any_value.rs
- py-polars/tests/unit/test_constructors.py
> fix(rust, python): create from dicts directly as struct categorical

- polars/polars-lazy/polars-plan/src/logical_plan/projection.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python): error on invalid expanding expression

- py-polars/tests/slow/test_parquet.py
- py-polars/tests/unit/io/test_csv.py
- py-polars/tests/unit/io/test_ipc.py
- py-polars/tests/unit/io/test_lazy_parquet.py
- py-polars/tests/unit/io/test_parquet.py
- py-polars/tests/unit/io/test_pyarrow_dataset.py
Reverts pola-rs/polars#6511
I'm still figuring out exactly what's going on. Until then, let's revert this change so that the CI keeps running smoothly.
Resolves #6499
> revert(python): Disable some tests for Windows

- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- py-polars/tests/unit/test_lists.py
> fix(rust, python): make concat_list group aware

- polars/polars-core/src/chunked_array/temporal/datetime.rs
- polars/polars-lazy/polars-plan/src/dsl/dt.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- polars/polars-time/src/date_range.rs
- py-polars/polars/internals/expr/datetime.py
- py-polars/polars/internals/series/datetime.py
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/test_datelike.py
> feat(rust, python): let cast_time_zone accept None

- polars/polars-arrow/src/kernels/set.rs
- polars/polars-core/src/chunked_array/ops/take/take_single.rs
- polars/polars-io/src/tests.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
- polars/polars-lazy/src/tests/aggregations.rs
- polars/polars-lazy/src/tests/queries.rs
- py-polars/Cargo.lock
- py-polars/Cargo.toml
> python polars 0.16.0

- py-polars/Cargo.toml
> python polars 0.16.1

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_predicates.py
> fix(rust, python): add strptime to filter boundary

- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- polars/polars-lazy/src/physical_plan/expressions/apply.rs
- polars/polars-lazy/src/physical_plan/planner/expr.rs
- polars/tests/it/lazy/expressions/apply.rs
- py-polars/tests/unit/test_window.py
> fix(rust, python): fix schema of apply with many inputs on empty df

- py-polars/polars/cfg.py
- py-polars/polars/internals/lazyframe/frame.py
- py-polars/tests/unit/test_cfg.py
- py-polars/tests/unit/test_df.py
Some minor cleanup, now the setting is no longer experimental.
> refactor(python): cleanup last vestiges of experimental kwargs setting

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
- py-polars/tests/unit/test_predicates.py
> fix(rust, python): fix predicate pushdown key check

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
Make predicate pushdown better by only blocking the optimization when really needed. We were too conservative.
> feat(rust, python): improve predicate pushdown

- polars/polars-lazy/src/physical_plan/expressions/take.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python); raise oob if negative index given to take

- polars/polars-time/src/groupby/dynamic.rs
- polars/polars-time/src/windows/groupby.rs
- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/lazyframe/frame.py
> fix(rust, python): partially assert sortedness in groupby dynamic

- polars/polars-arrow/src/kernels/time.rs
- polars/polars-core/src/chunked_array/temporal/datetime.rs
- py-polars/tests/unit/test_datelike.py
closes #6410 
seems to work! still need to clean it up and raise the errors properly, will mark as ready for review when ready
> fix(rust, python) cast to and from fixed offsets

- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-core/src/chunked_array/ops/fill_null.rs
- polars/polars-core/src/chunked_array/ops/mod.rs
- polars/polars-core/src/series/implementations/binary.rs
- polars/polars-core/src/series/implementations/boolean.rs
- polars/polars-core/src/series/implementations/categorical.rs
- polars/polars-core/src/series/implementations/dates_time.rs
- polars/polars-core/src/series/implementations/datetime.rs
- polars/polars-core/src/series/implementations/duration.rs
- polars/polars-core/src/series/implementations/floats.rs
- polars/polars-core/src/series/implementations/list.rs
- polars/polars-core/src/series/implementations/mod.rs
- polars/polars-core/src/series/implementations/object.rs
- polars/polars-core/src/series/implementations/struct_.rs
- polars/polars-core/src/series/implementations/utf8.rs
- polars/polars-core/src/series/mod.rs
- polars/polars-core/src/series/series_trait.rs
- py-polars/tests/unit/test_df.py
fixes #6621
Also refactor `fill_null` code in the process.
> feat(rust, python): implement fill_null for list data

- polars/polars-core/src/datatypes/dtype.rs
- polars/polars-lazy/polars-plan/src/logical_plan/aexpr/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/aexpr/schema.rs
- py-polars/tests/unit/test_schema.py
> fix(rust, python): true-divide output type

- polars/polars-lazy/src/tests/aggregations.rs
- polars/tests/it/lazy/aggregation.rs
A test for #6097 which was fixed in #6629
> test(rust): add test for raising error in apply

- README.md
> docs(rust): update Required Rust version to 1.58->1.62

- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/test_df.py
> feat(python):Add return_as_string arg to DF.glimpse; default=False

- py-polars/polars/datatypes.py
- py-polars/tests/unit/test_series.py
> fix(python): Raise ValueError on adding float to Series of dtype date

- polars/Cargo.toml
> docs(rust): add groupby_dynamic to docs

- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-core/src/frame/row.rs
- py-polars/src/conversion.rs
- py-polars/src/dataframe.rs
- py-polars/tests/unit/test_schema.py
> fix(python): respect 'None' in from_dicts

- py-polars/polars/internals/series/series.py
- py-polars/src/error.rs
- py-polars/src/lazy/dsl.rs
- py-polars/src/npy.rs
- py-polars/src/series.rs
- py-polars/tests/unit/test_interop.py
> feat(python): don't require pyarrow for utf8 -> numpy conversion

- polars/polars-core/src/frame/mod.rs
Fixes #6714 
New error message reads:
> exceptions.ShapeError: Could not create a new DataFrame from Series. The Series have different lengths: found length 2 for Series named "a" and length 1 for Series named "b".
Comments on my Rust implementation are very welcome - I'm sure there's a cleaner way to do this.
> fix(rust,python): Improve error message in DataFrame constructor

- polars/polars-core/src/chunked_array/ops/aggregate.rs
- polars/polars-core/src/chunked_array/ops/mod.rs
- polars/polars-core/src/series/implementations/binary.rs
- polars/polars-core/src/series/implementations/boolean.rs
- polars/polars-core/src/series/implementations/dates_time.rs
- polars/polars-core/src/series/implementations/datetime.rs
- polars/polars-core/src/series/implementations/duration.rs
- polars/polars-core/src/series/implementations/floats.rs
- polars/polars-core/src/series/implementations/mod.rs
- polars/polars-core/src/series/implementations/utf8.rs
- polars/polars-core/src/series/series_trait.rs
- polars/polars-ops/src/chunked_array/list/namespace.rs
- polars/polars-ops/src/series/ops/arg_min_max.rs
- polars/polars-ops/src/series/ops/is_first.rs
- polars/polars-ops/src/series/ops/mod.rs
- py-polars/tests/unit/test_series.py
> feat(rust, python): add argmin/max for utf8 data

- polars/polars-lazy/polars-plan/src/logical_plan/functions/drop.rs
- polars/polars-lazy/polars-plan/src/logical_plan/functions/mod.rs
- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/tests/queries.rs
- py-polars/tests/unit/test_df.py
- py-polars/tests/unit/test_drop.py
- py-polars/tests/unit/test_lazy.py
- py-polars/tests/unit/test_series.py
> fix(rust, python): use explicit drop function node

- polars/polars-lazy/polars-plan/src/dsl/list.rs
- py-polars/tests/unit/test_lists.py
> fix(rust, python): make some list expressions aware of groupby context

- py-polars/polars/internals/functions.py
- py-polars/tests/unit/test_df.py
Closes #6774.
Probably a few other places where this might be a reasonable addition; will keep an eye out.
> feat(python): minor ergonomic affordance; allow `pl.concat` from generator expression

- polars/polars-core/src/chunked_array/temporal/datetime.rs
- polars/polars-lazy/polars-plan/src/dsl/dt.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- py-polars/polars/internals/expr/datetime.py
- py-polars/polars/internals/series/datetime.py
@stinodego as promised 😄 follow-up to https://github.com/pola-rs/polars/pull/6768
> feat(rust, python) rename 'tz' to 'time_zone' in convert_time_zone and replace_time_zone

- polars/polars-io/src/ndjson_core/buffer.rs
- py-polars/tests/unit/io/test_json.py
> fix(rust, python): fix ndjson empty array parsing

- polars/polars-core/src/frame/mod.rs
> fix(rust, python): always rechunk if n_chunks > n_rows

- py-polars/Cargo.toml
A patch release to fix regressions.
> python polars 0.16.4

- py-polars/polars/internals/expr/struct.py
- py-polars/polars/internals/lazyframe/frame.py
> docs(python): fix lazy `groupby` docstring/rendering

- polars/polars-core/src/chunked_array/ops/full.rs
- polars/polars-core/src/series/any_value.rs
- polars/polars-io/src/ndjson_core/buffer.rs
- polars/polars-io/src/ndjson_core/ndjson.rs
- py-polars/tests/unit/io/test_json.py
> fix(rust, python): respect schema in ndjson

- py-polars/polars/internals/expr/expr.py
- py-polars/tests/unit/test_lazy.py
> fix(python): Raise ValueError on passing multiple expressions Numpy ufunc

- py-polars/src/series.rs
- py-polars/tests/unit/test_constructors.py
> fix(python): implement to_list for null dtype

- py-polars/polars/internals/series/series.py
- py-polars/tests/unit/test_interop.py
> fix(python): fix numpy/datetime regression

- polars/polars-lazy/polars-plan/src/dsl/arithmetic.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/aexpr/schema.rs
- polars/polars-lazy/polars-plan/src/logical_plan/lit.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs
- polars/polars-lazy/src/tests/mod.rs
- py-polars/tests/unit/test_schema.py
> fix(rust, python): stabilize integer operation to minimal required dtype

- py-polars/polars/internals/lazy_functions.py
Ref: https://github.com/pola-rs/polars/pull/6100 - apparently I missed one...
> refactor(python): parenthesise `col` type signature to improve hint interaction with PyCharm

- polars/polars-core/src/datatypes/any_value.rs
- py-polars/tests/unit/test_schema.py
> fix(rust): Do not panic when failing to extract numeric value

- polars/polars-core/src/frame/groupby/aggregations/mod.rs
If groupby has many groups this will save some allocator and atomic churns.
> perf(rust, python): remove unneeded series allocations in groupby aggs

- py-polars/polars/internals/expr/struct.py
Enhanced the examples a little / improved clarity.
> docs(python): further improve struct expr docstrings

- polars/polars-core/src/config.rs
- polars/polars-core/src/frame/groupby/into_groups.rs
- polars/polars-core/src/lib.rs
- polars/polars-core/src/series/from.rs
- polars/polars-io/src/csv/read_impl/batched.rs
- polars/polars-io/src/csv/read_impl/mod.rs
- polars/polars-io/src/lib.rs
- polars/polars-io/src/parquet/async_impl.rs
- polars/polars-lazy/src/physical_plan/state.rs
- polars/polars-lazy/src/physical_plan/streaming/convert.rs
This needs support upstream in arrow2 to work .
> chore(rust): setup support for fixedsizebinary convertion

- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-core/src/series/arithmetic/borrowed.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/type_coercion/binary.rs
- py-polars/tests/unit/test_struct.py
> fix(rust, python): improve recursive casting of nested data

- polars/polars-core/src/frame/asof_join/groups.rs
- polars/polars-ops/src/frame/join/mod.rs
> fix(rust, python): dispatch suffix to asof_join by

- .github/deploy_manylinux.sh
- .github/workflows/benchmark.yaml
- .github/workflows/build-test-rust.yaml
- .github/workflows/create-python-release.yaml
- .github/workflows/docs-deploy.yaml
- .github/workflows/lint-python.yaml
- .github/workflows/test-python.yaml
- py-polars/Cargo.lock
- rust-toolchain.toml
> chore(rust): update rustc to nightly-2023-02-14

- polars/polars-arrow/src/array/list.rs
- py-polars/tests/unit/test_df.py
- py-polars/tests/unit/test_explode.py
> fix(rust, python): fix anonymous list builder

- py-polars/docs/source/reference/series/computation.rst
- py-polars/polars/internals/expr/expr.py
- py-polars/polars/internals/series/series.py
- py-polars/tests/unit/test_series.py
Closes #6929.
```python
s = pl.Series( "num", [1,2,None,4,5] )
s.is_between( 2,4 )
> feat(python): add `is_between` method for Series

- py-polars/polars/internals/construction.py
- py-polars/polars/internals/expr/expr.py
- py-polars/requirements-lint.txt
Bumping this to the latest version because of a bug that was annoying me (and has been fixed in the latest version).
> chore(python): Bump ruff version

- polars/polars-core/src/chunked_array/logical/struct_/mod.rs
- polars/polars-ops/src/series/ops/is_unique.rs
- py-polars/tests/unit/test_struct.py
> feat(rust, python): add is_duplicated/is_unique for struct dtype

- polars/polars-core/src/series/mod.rs
- polars/polars-ops/src/frame/pivot/mod.rs
- py-polars/tests/unit/test_pivot.py
> fix(rust, python): fix temporal logical types in pivot

- py-polars/polars/internals/lazy_functions.py
- py-polars/tests/unit/test_lazy.py
Partially addresses #6451 
Changes:
* Clean up parsing logic for `col` and allow `*args` input.
> feat(python): More ergonomic `col` args

- polars/polars-ops/src/series/ops/is_unique.rs
- py-polars/tests/unit/test_series.py
> fix(rust, python): fix is_duplicated for utf8 dtype

- polars/polars-core/src/chunked_array/cast.rs
- py-polars/tests/unit/test_df.py
> fix(rust, python): fix fill_null for categoricals

- polars/polars-arrow/Cargo.toml
- polars/polars-core/Cargo.toml
- polars/polars-io/Cargo.toml
- polars/polars-time/Cargo.toml
closes https://github.com/pola-rs/polars/issues/6978
> chore(rust): remove time 0.1 dep

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs
- py-polars/tests/unit/test_functions.py
> fix(rust, python): fix coalesce supertype

- py-polars/polars/internals/series/series.py
- py-polars/tests/unit/test_series.py
> feat(python): Improve Series & Numpy arithmetic

- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-core/src/series/implementations/struct_.rs
- py-polars/tests/unit/datatypes/test_struct.py
> fix(rust, python): fix struct append 0 sliced

- polars/polars-core/src/series/series_trait.rs
- py-polars/tests/unit/operations/test_sort.py
> fix(rust, python): ensure set_sorted never panics

- py-polars/tests/unit/test_arity.py
> test(python): test lit series arithmetic order

- polars/polars-core/src/series/implementations/struct_.rs
- py-polars/tests/unit/datatypes/test_struct.py
- py-polars/tests/unit/test_errors.py
> feat(rust, python): add sort for struct dtype

- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-io/src/lib.rs
- polars/polars-io/src/parquet/read.rs
- polars/polars-io/src/parquet/read_impl.rs
- polars/polars-lazy/polars-pipe/src/executors/sources/parquet.rs
- polars/polars-lazy/polars-plan/src/logical_plan/builder.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
- polars/polars-lazy/polars-plan/src/logical_plan/options.rs
- polars/polars-lazy/src/frame/parquet.rs
- polars/polars-lazy/src/physical_plan/executors/scan/parquet.rs
- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/lazyframe/frame.py
- py-polars/polars/io.py
- py-polars/src/dataframe.rs
- py-polars/src/lazy/dataframe.rs
> feat(rust, python): add 'use_statistics' option to parquet readers

- polars/polars-lazy/polars-plan/src/dsl/function_expr/fill_null.rs
- py-polars/tests/unit/test_functions.py
> fix(rust, python): allow fill_null in eager if type now known

- polars/polars-ops/src/chunked_array/list/namespace.rs
- py-polars/tests/unit/namespaces/test_list.py
> fix(rust, python): fix logical types in arr.get

- polars/polars-sql/src/lib.rs
- polars/polars-sql/src/sql_expr.rs
whoops (i accidentally deleted an enum branch). 
fixes #7111
> fix(rust, python): nested sql exprs

- py-polars/Cargo.lock
- py-polars/polars/internals/series/series.py
- py-polars/tests/unit/operations/test_arithmetic.py
> fix(python): subtracting Series from date has wrong sign

- polars/polars-io/src/parquet/write.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/file_sink.rs
- py-polars/Cargo.lock
> fix(rust, python): fix deadlock in scan_csv()->sink_parquet()

- .github/workflows/docs-deploy-python.yml
> ci(python): Adjust target folder for API ref

- py-polars/polars/internals/lazy_functions.py
> docs(python): examples functional programing

- polars/polars-lazy/polars-plan/src/logical_plan/aexpr/schema.rs
- py-polars/tests/unit/test_schema.py
> fix(rust, python): respect f32 schema in deep expressions

- polars/polars-core/src/series/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- py-polars/tests/unit/test_lazy.py
This PR fixes panic on `product` in #6814
> fix(rust, python): fix panic on cum_prod

- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/test_df.py
> fix(python): fix df division dispatch

- polars/polars-core/src/chunked_array/comparison.rs
- py-polars/tests/unit/test_testing.py
> fix(rust, python): fix null cmp fast paths

- py-polars/src/series.rs
- py-polars/tests/unit/operations/test_apply.py
> feat(python): add binary apply

- polars/polars-arrow/src/array/mod.rs
- py-polars/tests/unit/operations/test_explode.py
> feat(rust, python): add explode for binary

- polars/polars-lazy/polars-plan/src/logical_plan/alp.rs
- polars/polars-lazy/src/physical_plan/streaming/convert.rs
- polars/polars-lazy/src/physical_plan/streaming/mod.rs
- polars/polars-lazy/src/physical_plan/streaming/tree.rs
- py-polars/tests/unit/test_streaming.py
> fix(rust, python): validate trees before inserting streaming node

- py-polars/polars/internals/dataframe/frame.py
> doc(python): Make python polars.DataFrame.sample shuffle description more explicit

- polars/polars-lazy/src/physical_plan/executors/groupby_dynamic.rs
- polars/polars-lazy/src/physical_plan/executors/groupby_rolling.rs
- polars/polars-lazy/src/physical_plan/expressions/binary.rs
- polars/polars-lazy/src/physical_plan/expressions/mod.rs
- polars/polars-lazy/src/physical_plan/state.rs
Refactored out a year of edge case on edge case.
> refactor(rust): simplify binary expression evaluation

- polars/polars-lazy/src/physical_plan/expressions/binary.rs
Can save an alloc of new groups depending on the expression.
> perf(rust, python): reuse groups in binary expressions

- py-polars/polars/io.py
> docs(python): add warning of mmap to ipc docstring

- py-polars/polars/utils.py
- py-polars/tests/unit/datatypes/test_temporal.py
> fix(python): dont lose precision in pl.date_range due to floating point arithmetic

- py-polars/polars/datatypes.py
- py-polars/polars/internals/dataframe/frame.py
- py-polars/polars/internals/io_excel.py
- py-polars/polars/internals/lazyframe/frame.py
- py-polars/polars/internals/series/series.py
- py-polars/polars/io.py
- py-polars/polars/testing/_parametric.py
- py-polars/pyproject.toml
- py-polars/requirements-dev.txt
- py-polars/tests/unit/io/test_excel.py
Closes #5568.
Extremely capable Excel export, leveraging `xlsxwriter`; this first iteration supports the following capabilities:
* Export to the filesystem, BytesIO, or write into an existing/open `xlsxwriter.Workbook`.
* Write table to any position on the worksheet, using excel notation like `"B3"` or zero-indexed`(row,col)` coordinates.
* Support named table styles, with optional style modifiers.
* Name the exported table object so it can be targeted by subsequent sheet operations.
* Per-dtype formatting (also supporting dtype _groups_ like `INTEGER_DTYPES`).
* Per-column formatting (can override dtype format and/or change colours, font, etc).
* Conditional formatting; simple/default format types, as well as icon sets, formulae, etc.
* Control over the default floating point precision …
> feat(python): Excel export support via new `write_excel` IO method

- py-polars/Cargo.lock
- py-polars/src/conversion.rs
- py-polars/tests/unit/datatypes/test_temporal.py
> fix(python): fix us precision of datetime to anyvalue conversion

- py-polars/polars/internals/construction.py
> feat(python): don't require pyarrow for initialising Series with Python datetimes

- polars/polars-time/src/groupby/dynamic.rs
- py-polars/tests/unit/datatypes/test_temporal.py
- py-polars/tests/unit/operations/test_groupby.py
- py-polars/tests/unit/operations/test_rolling.py
> fix(rust, python): fix groupby_dynamic's binning when index_column is time-zone-aware

- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
- py-polars/tests/unit/datatypes/test_struct.py
> fix(rust, python): make `pl.struct` mappable

- polars/polars-io/src/ipc/ipc_file.rs
> feat(rust, python): improve error message if mmap fails in ipc

- polars/polars-core/Cargo.toml
- polars/polars-lazy/polars-plan/src/dsl/expr.rs
- polars/polars-lazy/polars-plan/src/logical_plan/lit.rs
> feat(rust, python): implement serde for literal datetime and series

- py-polars/polars/datatypes_constructor.py
- py-polars/tests/unit/test_constructors.py
> feat(python): Support explicit Binary dtype in constructor

- polars/polars-core/src/series/implementations/dates_time.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python): raise error on time -> datetime cast

- py-polars/polars/internals/expr/expr.py
> fix(python): fix offset in threading apply

- py-polars/docs/source/reference/io.rst
- py-polars/polars/internals/dataframe/frame.py
> docs(python): add `write_excel` API docs link

- py-polars/Cargo.toml
patch for a regression due to decimal aggregation.
> python polars 0.16.11

- py-polars/Cargo.lock
- py-polars/tests/unit/io/test_delta.py
- py-polars/tests/unit/io/test_excel.py
- py-polars/tests/unit/io/test_lazy_ipc.py
Not sure why these gave trouble before and needed an ignore...
> chore(python): Clean up type checking lints

- polars/polars-time/src/chunkedarray/utf8/infer.rs
- polars/polars-time/src/chunkedarray/utf8/mod.rs
- py-polars/tests/unit/namespaces/test_strptime.py
> feat(rust, python): parse year-month-day as Datetime in slow-path

- polars/polars-core/src/series/implementations/null.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/datatypes/test_null.py
> fix(rust, python): fix null_dtype slice

- README.md
The example in the README is the perfect use case for the `*args` syntax!
> docs(python): Showcase new ergonomic syntax in README

- polars/polars-core/src/series/from.rs
> feat(rust, python): convert decimal 256 to 128 on entry

- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-core/src/datatypes/dtype.rs
- polars/polars-lazy/polars-plan/src/logical_plan/format.rs
- polars/polars-lazy/polars-plan/src/logical_plan/lit.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
- polars/polars-lazy/polars-plan/src/logical_plan/pyarrow.rs
- polars/polars-lazy/src/physical_plan/expressions/literal.rs
- polars/polars-lazy/src/tests/predicate_queries.rs
- py-polars/polars/internals/anonymous_scan.py
- py-polars/src/conversion.rs
- py-polars/tests/unit/io/test_pyarrow_dataset.py
> feat(python): push down temporal predicates to pyarrow scanner

- polars/polars-time/src/chunkedarray/utf8/patterns.rs
- py-polars/polars/io/csv.py
- py-polars/tests/unit/conftest.py
- py-polars/tests/unit/datatypes/test_temporal.py
> feat(rust, python): automatically infer iso8601-like dates

- polars/polars-sql/src/lib.rs
- polars/polars-sql/src/sql_expr.rs
closes #7440 & adds additional test case
> fix(python, rust): sql floor & ceil

- .github/deploy_manylinux.sh
- .github/workflows/benchmark.yml
- .github/workflows/build-test-rust.yml
- .github/workflows/create-python-release.yml
- .github/workflows/docs-deploy-rust.yml
- .github/workflows/lint-python.yml
- .github/workflows/test-python.yml
- py-polars/polars/internals/dataframe/frame.py
- py-polars/tests/unit/operations/test_statistics.py
- rust-toolchain.toml
> fix(python): fix and test df.corr

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/semi_anti_join.rs
- py-polars/Cargo.lock
Make it easier to follow before fixing #7481
> refactor(rust): refactor join pushdown

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/joins.rs
- polars/polars-lazy/src/tests/mod.rs
- py-polars/tests/unit/operations/test_join_asof.py
> fix(rust, python): fix projection pushdown of asof_joins

- polars/polars-time/Cargo.toml
- polars/polars-time/src/date_range.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/datatypes/test_temporal.py
Reverts pola-rs/polars#7430
See #7496
> Revert "fix(rust, python): allow for hourly date_range to cross DST"

- py-polars/polars/internals/lazyframe/frame.py
Just showcasing the nice new functionality introduced in #7122.
> docs(python): Use new `LazyFrame` init in docs

- py-polars/polars/utils/show_versions.py
- py-polars/pyproject.toml
Added xlsxwriter into the `[project.optional-dependencies]` toml section (and `show_versions`).
> chore(python): update `show_versions` with xlsxwriter (and add as optional dependency)

- py-polars/Cargo.lock
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/datatypes/test_binary.py
> feat(python): literal support for binary

- polars/polars-lazy/polars-plan/Cargo.toml
- polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs
- polars/polars-time/Cargo.toml
- polars/polars-time/src/date_range.rs
- polars/polars-time/src/lib.rs
- polars/polars-time/src/upsample.rs
- polars/polars-time/src/windows/calendar.rs
- polars/polars-time/src/windows/duration.rs
- polars/polars-time/src/windows/groupby.rs
- polars/polars-time/src/windows/test.rs
- polars/polars-time/src/windows/window.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/datatypes/test_temporal.py
> fix(rust, python) respect time zone in date_range

- polars/polars-lazy/polars-plan/src/logical_plan/functions/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/functions/mod.rs
- py-polars/tests/unit/test_projections.py
> fix(rust, python): pushdown key in merge sorted projection pd

- py-polars/polars/internals/series/series.py
- py-polars/src/series.rs
- py-polars/tests/unit/datatypes/test_categorical.py
Also removes a needless `series -> list -> series`
> fix(python): fix logical/list getitem

- polars/polars-arrow/src/kernels/rolling/no_nulls/min_max.rs
- py-polars/tests/unit/operations/test_rolling.py
> fix(rust, python): fix rolling windows for windows that shrink from lhs

- polars/polars-lazy/polars-pipe/src/executors/sinks/memory.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/mod.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/sort/sink.rs
- polars/polars-utils/src/atomic.rs
- polars/polars-utils/src/sys.rs
Some refactoring before we can make groupby out of core.
> refactor(rust): abstract memory collection in sinks

- polars/polars-time/src/date_range.rs
- polars/polars-time/src/lib.rs
- polars/polars-time/src/utils.rs
- polars/polars-time/src/windows/duration.rs
little clean up before tackling #7561
> chore(rust): factor out some utils into polars-time/src/utils

- py-polars/pyproject.toml
- py-polars/requirements-lint.txt
I need this new version specifically for a bugfix that is blocking another improvement that I'm looking to introduce.
> chore(python): Bump ruff

- polars/polars-lazy/polars-pipe/src/executors/sinks/memory.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/sort/sink.rs
fix for a regression caused by #7560. Thank you @MarcoGorelli for the bisect.
> fix memory tracing in sort sink

- py-polars/polars/internals/anonymous_scan.py
> feat(python): use head on pyarrow datasets

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs
- py-polars/tests/unit/test_projections.py
> fix(rust, python): distinct project whole schema if not a subset

- polars/Cargo.toml
- py-polars/tests/unit/operations/test_pivot.py
> fix(rust, python): activate dtype-duration for polars-ops

- polars/polars-core/src/series/implementations/decimal.rs
- polars/polars-core/src/series/series_trait.rs
> fix(rust, python): add decimal chunk_lengths

- polars/polars-core/src/chunked_array/logical/decimal.rs
- py-polars/src/conversion.rs
- py-polars/tests/unit/datatypes/test_decimal.py
> feat(rust, python): implement decimal -> dtype cast

- polars/polars-lazy/polars-plan/Cargo.toml
- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- polars/polars-time/src/round.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/datatypes/test_temporal.py
> fix(rust, python): respect time zone in dt.round

- py-polars/polars/internals/construction.py
Minor fixes and improvements to changes made in #7559
> refactor(python): fix and improve type hints and function names

- polars/polars-lazy/polars-plan/Cargo.toml
- polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/namespaces/test_datetime.py
> fix(rust, python): respect time zone in offset_by

- py-polars/Cargo.lock
Something with arrow2 causing problems.
> chore(python): Update lockfile

- polars/polars-arrow/src/trusted_len/push_unchecked.rs
- polars/polars-core/src/chunked_array/ops/apply.rs
- polars/polars-core/src/lib.rs
- polars/polars-core/src/series/mod.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/mod.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/ooc.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/ooc_state.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/primitive.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/string.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/utils.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/io.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/sort/sink.rs
- polars/polars-lazy/polars-pipe/src/executors/sources/ipc_one_shot.rs
- polars/polars-lazy/polars-pipe/src/pipeline/convert.rs
- polars/polars-lazy/polars-pipe/src/pipeline/mod.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_streaming.py
Out-of-core groupby for generic keys and multiple keys.
> feat(rust, python): full out-of core support for streaming groupby

- polars/polars-core/src/config.rs
- polars/polars-core/src/schema.rs
- polars/polars-core/src/series/from.rs
- polars/polars-lazy/polars-plan/src/logical_plan/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/schema.rs
- py-polars/tests/unit/datatypes/test_decimal.py
- py-polars/tests/unit/test_constructors.py
> fix(rust, python): fix schema of decimal type reads

- py-polars/polars/expr/expr.py
- py-polars/tests/unit/test_exprs.py
Closes #4224.
* Adds equivalent method expressions for the remaining comparison/math operators...
```python
df_op = df.select(
a = pl.col(c1) == pl.col(c2),
b = pl.col(c1) // pl.col(c2),
c = pl.col(c1) > pl.col(c2),
d = pl.col(c1) >= pl.col(c2),
e = pl.col(c1) < pl.col(c2),
f = pl.col(c1) <= pl.col(c2),
g = pl.col(c1) % pl.col(c2),
h = pl.col(c1) != pl.col(c2),
i = pl.col(c1) - pl.col(c2),
j = pl.col(c1) / pl.col(c2),
k = pl.col(c1) ^ pl.col(c2),
)
```
```python
df_expr = df.select(
a = pl.col(c1).eq(pl.col(c2)),
b = pl.col(c1).floordiv(pl.col(c2)),
c = pl.col(c1).gt(pl.col(c2)),
d = pl.col(c1).ge(pl.col(c2)),
e = pl.col(c1).lt(pl.col(c2)),
f = pl.col(c1).le(pl.col(c2)),
g = pl.col(c1).mod(pl.col(c2)),
h = pl.col(c1).ne(pl.col(c2)),
i = pl.col(c1).sub(pl.col(c2)),
j = …
```
> feat(python): add expression method equivalents for existing math/logical operators

- polars/polars-ops/src/chunked_array/strings/namespace.rs
- py-polars/tests/unit/test_empty.py
> fix(rust, python): fix empty case str.replace

- polars/polars-lazy/polars-plan/src/logical_plan/anonymous_scan.rs
- polars/polars-lazy/src/physical_plan/executors/scan/ndjson.rs
allow downcasting AnonymousScan as any.
> feat(rust): anonymous_scan::as_any

- polars/polars-core/src/frame/top_k.rs
- polars/polars-lazy/src/frame/mod.rs
- py-polars/docs/source/reference/dataframe/modify_select.rst
- py-polars/docs/source/reference/lazyframe/modify_select.rst
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
- py-polars/src/lazy/dataframe.rs
- py-polars/tests/unit/operations/test_sort.py
Actually, simply a `.sort(reverse=True).head(k)` and let the optimizer take it from there.
> feat(rust, python): `DataFrame.top_k/ LazyFrame.top_k`

- polars/polars-algo/src/algo.rs
- py-polars/polars/series/series.py
- py-polars/src/series.rs
- py-polars/tests/unit/operations/test_statistics.py
- py-polars/tests/unit/test_series.py
> feat(python): add `Series.hist`

- py-polars/docs/source/reference/series/modify_select.rst
> chore: add hist docs

- py-polars/polars/functions/lazy.py
Partially addresses https://github.com/pola-rs/polars/issues/6451
Changes:
* Allow `*args` syntax for `concat_list`
> feat(python): More ergonomic args for `concat_list`

- polars/polars-lazy/src/physical_plan/expressions/aggregation.rs
- polars/polars-lazy/src/tests/mod.rs
> fix(rust, python): fix null propagation

- polars/polars-core/src/frame/mod.rs
- polars/polars-lazy/polars-pipe/src/pipeline/convert.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
- polars/polars-lazy/src/tests/mod.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
- py-polars/polars/type_aliases.py
- py-polars/src/conversion.rs
- py-polars/tests/unit/operations/test_unique.py
> fix(rust, python): fix predicate pushdown for 'unique' first/last

- polars/polars-lazy/polars-pipe/src/executors/operators/function.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/functions/melt.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/functions/mod.rs
- polars/polars-lazy/src/tests/mod.rs
- py-polars/tests/unit/operations/test_melt.py
> fix(rust, python): fix melt projection pushdown node

- polars/polars-lazy/polars-plan/src/dsl/function_expr/strings.rs
- polars/polars-time/src/windows/duration.rs
(Very) minor, but "may not" can be ambiguous; replaced with "cannot" where it makes sense.
> refactor(rust): minor improvement to some error message text

- polars/polars-core/src/series/implementations/decimal.rs
- polars/polars-core/src/series/implementations/null.rs
- polars/polars-core/src/series/series_trait.rs
> fix(rust, python): make zip_with_same_type obligatory

- polars/polars-core/src/frame/top_k.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/operations/test_sort.py
> fix(rust, python): ensure k is lower than height

- py-polars/Cargo.toml
> python polars 0.16.16

- py-polars/tests/unit/operations/test_groupby.py
follow-up to https://github.com/pola-rs/polars/pull/7784
this hits paths such as 
https://github.com/pola-rs/polars/blob/1036a493d92c0b8eaf08eb0fe0e2474e00af0561/polars/polars-core/src/frame/groupby/aggregations/dispatch.rs#L53-L54
> chore(rust): cover uncovered paths in agg_* functions

- py-polars/tests/unit/test_df.py
> test(python): don't run hash stability test on arch64

- py-polars/polars/functions/eager.py
- py-polars/tests/unit/test_errors.py
> fix(python): raise error on invalid series concat strategy

- polars/polars-ops/src/chunked_array/strings/case.rs
- polars/polars-ops/src/lib.rs
- py-polars/tests/unit/namespaces/test_string.py
> fix(rust, python): fix unicode lower/uppercase

- polars/polars-core/src/chunked_array/ops/explode.rs
- polars/polars-core/src/chunked_array/upstream_traits.rs
- polars/polars-core/src/series/implementations/mod.rs
- polars/polars-core/src/series/implementations/null.rs
- py-polars/tests/unit/operations/test_explode.py
> fix(rust, python): fix explode list[null]

- Cargo.toml
- py-polars/Cargo.lock
- py-polars/tests/benchmark/test_release.py
> fix(rust, python): parquet stats & all kernel

- polars/polars-core/src/chunked_array/ops/shift.rs
Slightly improve performance of shift_and_fill if periods to slice is more or equal to ChunkedArray length.
> chore(rust): improve shift and fill performance in case of periods >= ca.len()

- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-core/src/chunked_array/from.rs
- polars/polars-core/src/chunked_array/ops/any_value.rs
- polars/polars-core/src/frame/groupby/aggregations/agg_list.rs
- polars/polars-core/src/series/from.rs
- py-polars/tests/unit/datatypes/test_categorical.py
> fix(rust, python): fix arbitrary nested logical types

- polars/polars-lazy/polars-plan/src/dsl/function_expr/arg_where.rs
- py-polars/tests/unit/operations/test_comparison.py
> fix(rust, python): correct for chunks in arg_where

- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/test_series.py
> feat(python): Add `Series.pow()`

- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/ooc_state.rs
> fix(rust, python): disable ooc groupby

- polars/polars-lazy/src/physical_plan/planner/lp.rs
First need to determine cardinality.
> perf(rust, python): don't auto-stream groupby

- polars/polars-algo/src/algo.rs
See https://github.com/pola-rs/polars/pull/7724#pullrequestreview-1354911379.
> chore(rust): quantile typo in qcut

- polars/polars-core/src/frame/groupby/proxy.rs
When dealing with high cardinality data. E.g. >100K groups the flattening was really naive and slow. This improves the groups computation by `~10%` locally on a 100K groups and 1M rows.
The flatten would actually not be needed at all, so let's see if we can make it lazy first and gradually remove it.
EDIT: oh, yeah, we use this a lot. :)
> perf: improve group_tuples of high cardinality data `~10%`

- .github/deploy_manylinux.sh
- .github/workflows/create-python-release.yml
- Cargo.toml
- polars/polars-core/src/lib.rs
- polars/polars-io/src/lib.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/src/lib.rs
- polars/src/lib.rs
- py-polars/Cargo.lock
- py-polars/Cargo.toml
- rust-toolchain.toml
> build: update rustc to nightly 2023-04-02

- .github/deploy_manylinux.sh
- .github/workflows/create-python-release.yml
- polars/polars-core/src/lib.rs
- polars/polars-io/src/lib.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/src/lib.rs
- polars/src/lib.rs
- py-polars/Cargo.lock
- py-polars/Cargo.toml
- rust-toolchain.toml
Latest `0.16.x` release. @stinodego you are free to break. :)
> python polars 0.16.18

- polars/polars-core/src/series/mod.rs
- py-polars/src/series.rs
- py-polars/tests/unit/datatypes/test_object.py
> fix(rust, python): concat object types

- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/src/frame/mod.rs
- py-polars/docs/source/reference/dataframe/modify_select.rst
- py-polars/docs/source/reference/expressions/modify_select.rst
- py-polars/docs/source/reference/lazyframe/modify_select.rst
- py-polars/docs/source/reference/series/modify_select.rst
- py-polars/polars/dataframe/frame.py
- py-polars/polars/expr/expr.py
- py-polars/polars/lazyframe/frame.py
- py-polars/polars/series/series.py
- py-polars/src/lazy/dataframe.rs
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/operations/test_sort.py
> feat(rust, python)!: change top_k(descending) -> bottom_k

- polars/polars-core/src/chunked_array/ops/sort/arg_sort_multiple.rs
- polars/polars-core/src/frame/asof_join/groups.rs
- polars/polars-core/src/frame/groupby/hashing.rs
- polars/polars-core/src/frame/groupby/mod.rs
- polars/polars-core/src/frame/hash_join/multiple_keys.rs
- polars/polars-core/src/frame/mod.rs
- polars/polars-core/src/hashing/vector_hasher.rs
- polars/polars-core/src/series/implementations/struct_.rs
- py-polars/tests/unit/datatypes/test_struct.py
> feat(rust, python): support struct in df.unique

- polars/polars-core/src/frame/row/av_buffer.rs
- polars/polars-core/src/series/any_value.rs
- polars/polars-ops/src/frame/pivot/positioning.rs
- py-polars/tests/unit/operations/test_pivot.py
- py-polars/tests/unit/operations/test_transpose.py
> fix(rust, python): fix pivot and transpose of struct data

- polars/polars-core/src/chunked_array/logical/struct_/mod.rs
- polars/polars-core/src/frame/row/mod.rs
- polars/polars-core/src/series/implementations/struct_.rs
- polars/polars-core/src/series/series_trait.rs
- py-polars/tests/unit/operations/test_transpose.py
- py-polars/tests/unit/test_df.py
> fix(rust, python): struct null_count, cast string, tranpose and describe

- py-polars/polars/convert.py
The `data` param can also take individual `RecordBatch` objects,  not just sequences of such.
Minor typing update to account for that.
> refactor(python): add standalone `RecordBatch` to `from_arrow` function typing

- polars/polars-core/src/datatypes/any_value.rs
- py-polars/tests/unit/test_streaming.py
> fix(rust, python): impl to_static for struct

- polars/polars-lazy/polars-pipe/src/executors/operators/function.rs
- polars/polars-lazy/polars-pipe/src/operators/context.rs
- polars/polars-lazy/polars-pipe/src/pipeline/dispatcher.rs
> fix(rust, python): set lower limit for chunk_size

- polars/polars-core/src/chunked_array/ops/sort/arg_sort_multiple.rs
- polars/polars-core/src/chunked_array/ops/sort/mod.rs
- polars/polars-core/src/series/implementations/struct_.rs
- py-polars/tests/unit/operations/test_sort.py
> feat(rust, python): implement arg_sort for struct dtype

- polars/polars-core/src/chunked_array/upstream_traits.rs
This code is hit a lot, so this is a huge win.
Tested on null densities: `0.0, 0.2, 0.5, 0.8` percent. 
50% null density is worst as expected as that kills predictability
```
[]  ritchie46 /home/ritchie46/code/memcheck$ ./target/release/base                            (base) 
null density: 0 took 441ms
100000000
null density: 0.2 took 607ms
100000000
null density: 0.5 took 905ms
100000000
null density: 0.8 took 604ms
100000000
[src/main.rs:3] group_tuples::run() = ()
[]  ritchie46 /home/ritchie46/code/memcheck$ ./target/release/base                            (base) 
null density: 0 took 417ms
100000000
null density: 0.2 took 594ms
100000000
null density: 0.5 took 854ms
100000000
null density: 0.8 took 574ms
100000000
[src/main.rs:3] group_tuples::run() = ()
[]  ritchie46 …
```
> perf(rust, python): parallelize numeric ChunkedArray materialization `~2x`.

- py-polars/Cargo.toml
> python polars 0.17.0

- polars/polars-lazy/polars-plan/src/logical_plan/mod.rs
Avoids exponential growth of backslashes in output. Somewhat fixes #8079, although there is other exponential behavior there that's not related to the backslashes, but instead to the fact that errors include all previous errors.
Input:
```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
let mut df = df! [
"c1" => [0, 1],
]
.unwrap()
.lazy();
// introduce an error, then proceed as normal
df = df
.select([col("xyz")])
.select([col("c1")])
.select([col("c2")])
.select([col("c5")]);
println!("{:?}", df.collect()?);
Ok(())
}
```
Output (manually wrapped):
```
Error: ColumnNotFound(ErrString("xyz\n\nError originated just after this
operation:\nDF [\"c1\"]; PROJECT */1 COLUMNS; SELECTION: \"None\"\n\nError
originated just after this operation:\nErrorStateSync(AlreadyEncountered(not …
```
> fix(rust, python): don't exponentially grow error messages (partial fix). 

- polars/polars-time/src/windows/calendar.rs
- polars/polars-time/src/windows/duration.rs
- py-polars/Cargo.lock
- py-polars/polars/functions/eager.py
- py-polars/tests/unit/datatypes/test_temporal.py
closes #5441
Also adding a docstring to show how to easily get the last day of each month
> feat(python, rust)! make 'mo' interval raise if the target date does not exist

- py-polars/polars/utils/show_versions.py
Closes #8094
Not sure how to test for this... 😕 
@zundertj FYI
> fix(python): Fix `show_versions` util

- polars/polars-lazy/polars-plan/src/logical_plan/aexpr/schema.rs
- polars/polars-sql/src/functions.rs
- py-polars/tests/unit/test_schema.py
> fix(rust, python): lazy: fix boolean sum schema

- py-polars/Cargo.toml
Patch for https://github.com/pola-rs/polars/issues/8063 regression
> python polars 0.17.1

- polars/polars-core/src/chunked_array/ops/is_in.rs
- py-polars/tests/unit/datatypes/test_struct.py
supersedes #8113
fixes https://github.com/pola-rs/polars/issues/7606
> fix(rust, python): struct `is_in`

- polars/polars-arrow/src/array/mod.rs
- polars/polars-arrow/src/array/null.rs
- polars/polars-core/src/chunked_array/builder/list.rs
- py-polars/tests/unit/test_constructors.py
> fix(rust, python): implement list<null> constructor

- py-polars/polars/testing/_parametric.py
The parametric `dataframes` draw function now randomly flips between initialising frames column-wise (as before) or row-wise (new).
This adds zero overhead to our testing as no _new_ frames are generated (no new tests are required), but _significantly_ increases our frame-initialisation coverage with respect to `AnyValue` conversions (ref: #8136).
This update was inspired by (and would have found) the recent #8135 issue, and it also found a previously unknown initialisation issue with large `UInt64` values (fixed by #8146).
> feat(python): Enhanced parametric testing `DataFrame` generation

- polars/polars-lazy/polars-plan/src/dsl/function_expr/dispatch.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/unique.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
> feat(rust, python): make unique expr serde and cmp

- py-polars/src/conversion.rs
- py-polars/tests/unit/datatypes/test_object.py
> fix(python): object conversion in anyvalue

- py-polars/Cargo.toml
- py-polars/src/lazy/dataframe.rs
- py-polars/src/lazy/dsl.rs
These were found by https://github.com/frewsxcv/cargo-all-features. I wonder if we should add that to CI.
> chore(rust): feature flag guards

- py-polars/Cargo.toml
> python polars 0.17.2

- polars/polars-io/src/ipc/ipc_stream.rs
- polars/polars-io/src/lib.rs
> feat(rust): Remove Seek constraint from IpcStreamReader and SerReader

- polars/polars-lazy/src/physical_plan/expressions/mod.rs
- py-polars/tests/unit/operations/test_aggregations.py
> fix(rust, python): keep literal state if elementwise function is applied

- py-polars/polars/datatypes/__init__.py
- py-polars/polars/datatypes/constants.py
- py-polars/polars/testing/asserts.py
- py-polars/tests/unit/test_testing.py
> tests(python): fix potential overflow in testing asserts for 'atol' with unsigned ints

- polars/polars-core/src/series/implementations/duration.rs
- polars/polars-core/src/series/mod.rs
- py-polars/tests/unit/datatypes/test_duration.py
> feat(rust, python): add duration cumsum and remainder

- py-polars/polars/series/series.py
- py-polars/tests/unit/operations/test_arithmetic.py
- py-polars/tests/unit/test_series.py
> feat(python): automatically convert `series OP expr` -> `pl.lit(series) OP expr` where OP is arithmetic

- py-polars/polars/expr/datetime.py
- py-polars/polars/series/datetime.py
xref https://github.com/pola-rs/polars/issues/8217
seems like a common request, so documenting it for now until there's `.dt.month_end` (or some other kind of `'mo'` offset) may help
> doc(python): document how to offset by 1 "month end"

- polars/polars-core/src/chunked_array/logical/struct_/mod.rs
- polars/polars-core/src/chunked_array/mod.rs
- polars/polars-core/src/datatypes/dtype.rs
- polars/polars-core/src/series/any_value.rs
- polars/polars-core/src/series/from.rs
- polars/polars-core/src/series/into.rs
- py-polars/tests/unit/datatypes/test_struct.py
> fix(rust, python): nested struct logical type consistency

- polars/polars-core/src/chunked_array/upstream_traits.rs
- polars/polars-core/src/frame/groupby/aggregations/mod.rs
- py-polars/tests/unit/operations/test_aggregations.py
> fix(rust, python): fix offsets in parallel utf8 materialization

- polars/polars-core/src/chunked_array/upstream_traits.rs
fixes #8247
Regression due to latest optimization. A bit more conservative now.
> fix(rust, python): fix boolean par materialization

- polars/polars-arrow/src/array/list.rs
- polars/polars-core/src/datatypes/any_value.rs
- polars/polars-core/src/datatypes/dtype.rs
- polars/polars-core/src/series/any_value.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/datatypes/test_categorical.py
- py-polars/tests/unit/test_constructors.py
> fix(rust, python): improve nested list construction

- .github/workflows/test-python.yml
> Revert "ci(python): re-enable test parallization for Windows tests"

- polars/polars-core/src/frame/mod.rs
- polars/polars-core/src/frame/row/av_buffer.rs
- polars/polars-lazy/src/frame/mod.rs
Docs before:
<hr />
Docs after:
> fix(rust): Use three slashes for doc comments

- polars/polars-core/src/chunked_array/list/iterator.rs
- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- polars/polars-lazy/src/physical_plan/expressions/apply.rs
- polars/polars-lazy/src/physical_plan/expressions/binary.rs
- polars/polars-lazy/src/physical_plan/expressions/filter.rs
- polars/polars-lazy/src/physical_plan/expressions/group_iter.rs
- polars/polars-lazy/src/physical_plan/expressions/ternary.rs
- py-polars/tests/unit/datatypes/test_struct.py
fixes #8070
fixes #8252
fixes #7763
> fix(rust, python): pass name to struct construction in aggregation

- .github/workflows/create-python-release.yml
- py-polars/Cargo.toml
There were some issues with 0.17.4, so I try again. :crossed_fingers:
> python polars 0.17.5

- polars/polars-lazy/src/dsl/list.rs
- py-polars/Cargo.lock
> fix(rust, python): ensure invalid list eval raises

- py-polars/Cargo.lock
- py-polars/polars/expr/expr.py
- py-polars/src/lazy/dsl.rs
- py-polars/tests/unit/test_errors.py
> fix(python): validate `window_size` user input in rolling_expr

- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- py-polars/tests/unit/test_schema.py
> fix(rust, python): fix coalesce schema

- polars/polars-core/src/datatypes/aliases.rs
- py-polars/src/conversion.rs
- py-polars/tests/unit/test_schema.py
> fix(python): List<Null> consistency

- polars/polars-core/src/named_from.rs
- py-polars/tests/unit/test_serde.py
> fix(rust, python): fix deserialize empty list

- polars/polars-core/src/chunked_array/list/iterator.rs
- polars/polars-core/src/chunked_array/logical/struct_/mod.rs
- polars/polars-core/src/chunked_array/ops/any_value.rs
- polars/polars-core/src/frame/groupby/mod.rs
- polars/polars-core/src/series/into.rs
- polars/polars-core/src/series/mod.rs
- polars/polars-core/src/series/ops/to_list.rs
- polars/polars-lazy/src/physical_plan/expressions/aggregation.rs
- polars/polars-lazy/src/physical_plan/planner/expr.rs
- polars/tests/it/core/list.rs
- py-polars/docs/source/reference/series/aggregation.rst
- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/datatypes/test_categorical.py
Ensure we can handle the logical types all the way down.
> fix(rust, python): nested struct/list/categorical logical/physical

- py-polars/polars/utils/convert.py
Constructing epoch datetimes and calling get_zoneinfo (for tz-aware values) inside the function is expensive as it is called repeatedly and these values are const; hoisted outside so they are only created once, and micro-optimised the rest. 
For example, on output from `Series( <dates|datetimes> ).to_list()` :
* `Date` speedup: ~35%
* `Datetime` speedup: ~10%
> perf(python): ~35% speedup for timestamp → python date conversion, and ~10% speedup for datetime

- polars/polars-core/src/chunked_array/builder/list.rs
- py-polars/tests/unit/datatypes/test_list.py
> fix(rust, python): fix logical dtypes in parallel list collection

- polars/polars-sql/src/functions.rs
> fix(sql): correct count dispatch

- polars/polars-core/src/chunked_array/temporal/time.rs
- polars/polars-core/src/series/implementations/dates_time.rs
- polars/polars-time/src/chunkedarray/time.rs
- py-polars/tests/unit/datatypes/test_temporal.py
- py-polars/tests/unit/datatypes/test_time.py
> fix(rust, python): time.cast(str) as strftime

- polars/polars-lazy/polars-plan/src/dsl/function_expr/fill_null.rs
- polars/polars-lazy/polars-plan/src/logical_plan/builder.rs
- py-polars/tests/unit/datatypes/test_categorical.py
> fix(rust, python): fix fill_null for categorical

- polars/polars-core/src/series/implementations/decimal.rs
- polars/polars-core/src/series/implementations/null.rs
- polars/polars-core/src/series/series_trait.rs
> fix(rust, python): implement clone_inner for all series

- py-polars/polars/testing/parametric/__init__.py
- py-polars/tests/parametric/conftest.py
Fixes #8355.
@alexander-beedie Here's the PR we discussed, a bit earlier than expected :)
I tested it locally and it still correctly applies the different profiles
> fix(python): fix unintentional loading of hypothesis profile

- polars/polars-core/src/chunked_array/ops/mod.rs
- py-polars/tests/unit/datatypes/test_list.py
> fix(rust, python): fix logical type in ListChunked::new_from_index

- py-polars/polars/lazyframe/groupby.py
- py-polars/tests/unit/test_errors.py
> feat(python): raise error on invalid dict aggregation

- Cargo.toml
- py-polars/Cargo.lock
- py-polars/tests/unit/io/test_parquet.py
> fix(rust, python): fix nested null parquet read

- polars/polars-core/src/chunked_array/ops/is_in.rs
- py-polars/tests/unit/datatypes/test_list.py
- py-polars/tests/unit/datatypes/test_struct.py
- py-polars/tests/unit/operations/test_filter.py
- py-polars/tests/unit/operations/test_is_in.py
- py-polars/tests/unit/test_df.py
- py-polars/tests/unit/test_series.py
> fix(rust, python): is_in struct logical types

- py-polars/polars/series/series.py
it is in RUST polars but not in py-polars
> feat(python): add is_integer

- py-polars/polars/functions/lazy.py
* Include `df` before (as well as after) to clarify use of `add` column.
* Tidy-up the table formatting.
> docs(python): update `duration` docstring/example

- polars/polars-core/src/chunked_array/logical/categorical/builder.rs
- polars/polars-core/src/frame/row/av_buffer.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/hash_table.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/thread_local.rs
> fix(rust, python): use physical in streaming unique global table

- polars/polars-sql/src/lib.rs
- polars/polars-sql/src/sql_expr.rs
> feat(python,rust,cli): add support for SQL "IN" expr

- polars/polars-lazy/polars-plan/src/dsl/functions.rs
- py-polars/tests/unit/test_empty.py
> fix(rust, python): duration on empty df

- polars/polars-io/src/json.rs
- py-polars/tests/unit/io/test_json.py
> fix(rust, python): infer supertype in json serde

- py-polars/polars/series/series.py
- py-polars/tests/unit/test_interop.py
Other half of https://github.com/pola-rs/polars/issues/8393
> fix(python): raise upon invalid use of zero_copy_only

- py-polars/polars/testing/parametric/strategies.py
Building on https://github.com/pola-rs/polars/pull/8430 (and cleaning-up a TODO)...
...the (opt-in) `Decimal` strategy is now a composite that can generate values with a varied number of decimal places:
```python
with pl.Config( activate_decimals=True ):
from polars.testing.parametric import dataframes 
df = dataframes(
cols = 3,
size = 5,
allowed_dtypes = pl.Decimal,
).example()
print(df)
```
> feat(python): improved parametric `Decimal` strategy

- py-polars/docs/source/reference/testing.rst
- py-polars/polars/testing/parametric/__init__.py
- py-polars/polars/testing/parametric/primitives.py
- py-polars/polars/testing/parametric/profiles.py
- py-polars/polars/testing/parametric/strategies.py
Various improvements, including a section on the newly-introduced profile set/load functions.
> docs(python): parametric testing docs improvements

- polars/polars-core/src/frame/groupby/hashing.rs
- polars/polars-core/src/frame/groupby/into_groups.rs
- polars/polars-core/src/frame/groupby/proxy.rs
- py-polars/Cargo.lock
Restores a regression and has a speedup due to better materialization.
> perf(rust, python): reinstate old behavior in numeric group-tuples

- polars/polars-time/src/upsample.rs
- polars/polars-time/src/windows/calendar.rs
- polars/polars-time/src/windows/duration.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/expr/datetime.py
- py-polars/polars/expr/expr.py
- py-polars/polars/lazyframe/frame.py
- py-polars/polars/series/datetime.py
- py-polars/tests/unit/namespaces/test_datetime.py
> feat(python, rust): let duration string accept "1mo_saturating"

- py-polars/polars/dataframe/frame.py
- py-polars/polars/testing/parametric/primitives.py
Updated/improved some parametric testing docstrings/examples.
> docs(python): additional parametric testing docs/examples

- polars/polars-core/src/frame/groupby/mod.rs
- polars/polars-time/src/upsample.rs
- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/datatypes/test_temporal.py
> feat(rust, python): require explicitly sorted flag for upsample

- polars/polars-core/src/series/implementations/duration.rs
- py-polars/tests/unit/operations/test_statistics.py
> feat(rust, python): expose quantile/mean for duration

- polars/polars-lazy/src/physical_plan/expressions/window.rs
- py-polars/tests/unit/test_empty.py
> fix(rust, python): ensure window function succeeds on empty frame

- polars/polars-core/src/series/from.rs
- py-polars/tests/unit/datatypes/test_categorical.py
> fix(rust, python): unset fast_unique coming from arrow

- py-polars/tests/unit/test_interop.py
> test(python): add test for categorical input that is not fast_unique

- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
> refactor(python): better type signature for set_sorted

- polars/polars-core/src/chunked_array/logical/categorical/builder.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/fill_null.rs
- py-polars/tests/unit/datatypes/test_categorical.py
> fix(rust, python): fix categorical/string_cache fill_null panic

- py-polars/polars/testing/parametric/primitives.py
- py-polars/polars/testing/parametric/strategies.py
- py-polars/tests/parametric/test_dataframe.py
(In particular, flesh-out/explain the `StrategyLookup` class...)
**Next:** a parametric `Struct` strategy...
> docs(python): add more detail to internal `strategies` docstrings and comments

- py-polars/polars/utils/_construction.py
- py-polars/tests/unit/test_constructors.py
> fix(python): fix edge-case with `NamedTuple` input that contains unhashable field data

- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/aggregates/convert.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/sink.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/thread_local.rs
- polars/polars-lazy/polars-pipe/src/pipeline/convert.rs
- py-polars/tests/unit/test_streaming.py
> fix(rust, python): fix wrong dtype init in streaming groupby

- polars/polars-io/src/csv/parser.rs
- polars/polars-io/src/csv/read_impl/batched_mmap.rs
- polars/polars-io/src/csv/read_impl/batched_read.rs
- polars/polars-io/src/csv/read_impl/mod.rs
- polars/tests/it/io/csv.rs
- To address https://github.com/pola-rs/polars/issues/8402
> fix(rust): fix csv reader with new line in header

- polars/polars-core/src/series/implementations/dates_time.rs
- py-polars/tests/unit/operations/test_sort.py
> fix(rust, python): maintain sortedness in date -> datetime cast

- py-polars/Cargo.lock
- py-polars/Cargo.toml
> python polars 0.17.11

- polars/polars-core/src/chunked_array/cast.rs
- py-polars/tests/unit/datatypes/test_list.py
> fix(rust, python): allow list<null> -> list<cat>

- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/hash_table.rs
- py-polars/tests/unit/streaming/test_streaming.py
> fix(rust, python): fix categorical agg type

- polars/polars-core/src/chunked_array/ops/explode.rs
- py-polars/tests/unit/operations/test_explode.py
> fix(rust, python): fix explode null series

- polars/polars-core/src/series/mod.rs
- py-polars/Cargo.toml
- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/test_series.py
Fixes https://github.com/pola-rs/polars/issues/7655
> feat(python): .to_physical() for List(Categorical)

- py-polars/polars/series/series.py
just for convenience, was looking for this
> doc(python): link to pyarrow to_numpy

- polars/polars-core/src/frame/mod.rs
- polars/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs
> fix(rust, python): don't take logical plan during streaming fmt

- py-polars/tests/unit/test_lazy.py
Adds some coverage for 32/64 bit float rounding (ref: #8706).
> test(python): add rounding coverage for 32/64 bit floats

- py-polars/tests/unit/test_exprs.py
> test(python): add unit tests for `extend_constant` Expr

- Cargo.toml
- polars/polars-io/Cargo.toml
- py-polars/Cargo.lock
- py-polars/Cargo.toml
- py-polars/tests/unit/io/test_parquet.py
> chore: update_arrow

- polars/polars-core/src/chunked_array/cast.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs
- py-polars/tests/unit/operations/test_arithmetic.py
> fix(rust, python): improve supertype coercion of functions

- polars/polars-core/src/frame/mod.rs
- polars/polars-core/src/serde/df.rs
- polars/polars-core/src/serde/mod.rs
- py-polars/src/dataframe.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python): validate data on successful deserialization

- Cargo.toml
- polars/polars-core/src/chunked_array/ops/apply.rs
- polars/polars-core/src/chunked_array/ops/extend.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_df.py
> fix(rust, python): check offset before doing owned mutation

- polars/polars-core/src/chunked_array/iterator/par/list.rs
- polars/polars-core/src/frame/groupby/proxy.rs
- polars/polars-lazy/src/physical_plan/expressions/aggregation.rs
- polars/polars-lazy/src/physical_plan/expressions/mod.rs
- py-polars/tests/unit/operations/test_groupby.py
> fix(rust, python): correct aggregation of overlapping groups

- polars/polars-arrow/src/compute/bitwise.rs
- polars/polars-arrow/src/compute/mod.rs
- polars/polars-core/src/chunked_array/arithmetic.rs
- polars/polars-core/src/chunked_array/bitwise.rs
- py-polars/polars/expr/expr.py
- py-polars/tests/unit/operations/test_arithmetic.py
> fix(rust, python): fix broadcasting on integer bitwise

- polars/polars-arrow/src/compute/take/mod.rs
- py-polars/tests/unit/namespaces/test_list.py
> fix(rust, python): check null data before take

- polars/polars-core/src/frame/groupby/proxy.rs
- polars/polars-lazy/src/physical_plan/expressions/window.rs
- polars/polars-lazy/src/tests/queries.rs
- py-polars/polars/testing/_private.py
- py-polars/tests/unit/operations/test_window.py
> fix(rust, python): sort cached window groups

- polars/polars-sql/src/context.rs
- py-polars/tests/unit/test_sql.py
Closes #8832.
Recognise `OFFSET` keyword and map internally to `slice`.
```python
"a": range(6), 
"b": reversed(range(6)),
})
c = pl.SQLContext( tbl=lf )
c.execute(
"SELECT * FROM tbl LIMIT 2 OFFSET 3",
eager=True,
)
```
**Before:** _(offset not applied)_
```python
```
**After:**
```python
```
> feat(rust,python): add support for `OFFSET` keyword in SQL queries

- polars/polars-lazy/polars-plan/src/logical_plan/aexpr/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/aexpr/schema.rs
- polars/polars-lazy/src/physical_plan/expressions/aggregation.rs
- polars/polars-lazy/src/physical_plan/expressions/count.rs
- polars/polars-lazy/src/physical_plan/planner/expr.rs
- polars/polars-lazy/src/tests/queries.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_empty.py
> fix(rust, python): improve agg expr field types

- polars/polars-core/src/frame/row/transpose.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_errors.py
> feat(rust, python): check categorical cache on transpose

- polars/polars-sql/Cargo.toml
- polars/polars-sql/src/context.rs
- polars/polars-sql/tests/ops_distinct_on.rs
> feat(python,rust,cli): add support for sql DISTINCT ON

- polars/polars-core/src/frame/groupby/proxy.rs
> fix(rust, python): free buffer, but not its contents

- polars/polars-sql/src/context.rs
- polars/polars-sql/src/sql_expr.rs
- polars/polars-sql/tests/statements.rs
> fix(cli,rust,python): sql qualified wildcards

- polars/polars-sql/src/context.rs
- polars/polars-sql/tests/statements.rs
- py-polars/tests/unit/test_sql.py
> feat(cli,rust,python): add sql UNION, UNION ALL & UNION DISTINCT

- py-polars/tests/unit/datatypes/test_struct.py
Sorry @alexander-beedie, jumped the gun a bit and was sloppy with my doc/comments.
> fix(python): remove bad comment/bad period

- py-polars/docs/source/reference/sql.rst
- py-polars/polars/sql/context.py
Additional clarifications, examples, and "see also" sections.
_(Docstring-only update; no functional changes)._
> docs(python): further enhance `SQLContext` docstrings

- polars/polars-lazy/src/physical_plan/planner/expr.rs
- py-polars/tests/unit/test_empty.py
> feat(rust, python): error on invalid sortby expr

- polars/polars-core/src/frame/asof_join/mod.rs
- polars/polars-core/src/utils/series.rs
- polars/polars-time/src/groupby/dynamic.rs
- polars/polars-time/src/upsample.rs
- py-polars/tests/unit/test_errors.py
> feat(rust, python)!: raise error when sorted flag not set

- polars/polars-arrow/src/kernels/time.rs
- polars/polars-core/src/chunked_array/temporal/datetime.rs
- polars/polars-core/src/fmt.rs
- polars/polars-io/src/csv/write_impl.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs
- polars/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs
- polars/polars-time/src/date_range.rs
- polars/polars-time/src/groupby/dynamic.rs
- polars/polars-time/src/upsample.rs
- polars/polars-time/src/windows/groupby.rs
- py-polars/polars/utils/_construction.py
- py-polars/tests/unit/datatypes/test_temporal.py
closes #8860 (final jigsaw piece!)
closes #8289 
gosh this was satisfying
> feat(rust, python)!: disallow time zones other than those in zoneinfo.available_timezones()

- py-polars/polars/series/datetime.py
- py-polars/polars/series/series.py
- py-polars/pyproject.toml
- py-polars/tests/unit/datatypes/test_temporal.py
closes https://github.com/pola-rs/polars/issues/8989
> fix(python): deprecate `time_unit` property from `Series`

- polars/polars-time/src/upsample.rs
sorry, missed this one in #8993
> chore(rust): replace pattern match with unwrap

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/fused.rs
- polars/polars-lazy/src/physical_plan/expressions/apply.rs
- py-polars/tests/unit/operations/test_arithmetic.py
> fix(rust, python): fix fused arithmetic in window functions

- py-polars/polars/sql/context.py
A few small docstring cleanups/updates.
> docs(python): minor `SQLContext` docstring cleanups

- polars/polars-lazy/src/physical_plan/planner/expr.rs
- py-polars/tests/unit/operations/test_aggregations.py
- py-polars/tests/unit/operations/test_window.py
> fix(rust, python): raise error on invalid aggregation

- polars/polars-io/Cargo.toml
- polars/polars-json/Cargo.toml
- py-polars/Cargo.lock
See https://github.com/simd-lite/simd-json/issues/290
> chore: update simd-json

- py-polars/polars/datatypes/constructor.py
- py-polars/src/series/construction.rs
- py-polars/tests/unit/datatypes/test_array.py
> fix(python): respect inner type in Array construction

- polars/polars-core/src/frame/row/av_buffer.rs
- py-polars/tests/unit/test_errors.py
> feat(rust, python): improve error message on row-wise overflow

- py-polars/src/series/mod.rs
- py-polars/tests/unit/operations/test_apply.py
> fix(rust, python): fix apply with passed date/datetime return_dtype

- polars-cli/Cargo.toml
- polars-cli/src/highlighter.rs
- polars-cli/src/interactive.rs
- polars/polars-sql/Cargo.toml
- polars/polars-sql/src/functions.rs
- polars/polars-sql/src/sql_expr.rs
> chore(rust,cli): bump sqlparser version

- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/physical_plan/executors/groupby_dynamic.rs
- polars/polars-lazy/src/physical_plan/executors/groupby_rolling.rs
- polars/polars-lazy/src/physical_plan/planner/lp.rs
- py-polars/Cargo.lock
- py-polars/polars/dataframe/groupby.py
- py-polars/polars/lazyframe/groupby.py
- py-polars/tests/unit/operations/test_groupby.py
- py-polars/tests/unit/operations/test_groupby_rolling.py
> feat(rust, python): implement apply for rolling/dynamic_groupby

- py-polars/polars/exceptions.py
- py-polars/polars/functions/range.py
- py-polars/polars/utils/__init__.py
- py-polars/polars/utils/_construction.py
- py-polars/polars/utils/convert.py
- py-polars/tests/unit/datatypes/test_temporal.py
- py-polars/tests/unit/test_constructors.py
addresses the suggestion in [this comment](https://github.com/pola-rs/polars/pull/8908#issuecomment-1553954826)
> feat(python): warn if constructing Series with time-zone-aware datetimes

- polars/src/docs/lazy.rs
- polars/src/lib.rs
- py-polars/polars/expr/expr.py
> Fix broken links

- polars/polars-time/src/windows/duration.rs
Precursor towards using concrete types in the offsets code
The eventual goal is to have `add_*s_tz_naive` and `add_*s_tz_aware`, instead of just `add_*s` which has to type `tz` with a Trait (even though we know that it can only be `Tz` - unfortunately it can't just be typed as `Tz` because that's only available behind the `timezones` feature)
> chore(rust): factor add_month out of add_impl_month_week_or_day

- polars/polars-core/src/chunked_array/kernels/take.rs
- polars/polars-core/src/frame/hash_join/mod.rs
- polars/polars-core/src/frame/hash_join/zip_outer.rs
- polars/tests/it/core/mod.rs
- polars/tests/it/core/ops/mod.rs
- polars/tests/it/core/ops/take.rs
- py-polars/tests/unit/operations/test_join.py
> fix(rust, python): fix null/empty in List::take_unchecked

- py-polars/polars/dataframe/frame.py
> docs(python): Improve df.clear() docs

- polars/polars-io/src/csv/buffer.rs
- polars/polars-time/src/chunkedarray/utf8/mod.rs
- polars/polars-time/src/chunkedarray/utf8/patterns.rs
cleaning up a few things noticed on the way towards addressing https://github.com/pola-rs/polars/issues/9102
> chore(rust): remove outdated struct, improve naming

- polars/polars-core/src/chunked_array/ops/rolling_window.rs
- py-polars/tests/unit/operations/test_rolling.py
> fix(rust, python): rolling_apply window_size == len

- py-polars/polars/expr/string.py
> docs(python): fix "to_decimal" docstring

- py-polars/tests/unit/test_polars_import.py
> tests(python): stabilise polars importtime check

- polars/polars-core/src/frame/row/dataframe.rs
- py-polars/src/apply/dataframe.rs
- py-polars/tests/unit/operations/test_apply.py
> fix(python): raise error on invalid df.apply return

- py-polars/src/dataframe.rs
- py-polars/tests/unit/operations/test_apply.py
> fix(python): df.apply first rechunk

- polars/polars-core/src/series/mod.rs
- py-polars/tests/unit/datatypes/test_integer.py
> feat(rust, python): support float expression on integers

- py-polars/docs/source/reference/selectors.rst
- py-polars/polars/selectors.py
- py-polars/tests/unit/test_selectors.py
Follow-up to #9204, adding a `datetime` selector, tweaking the API docs, and slightly clarifying some internals.
> feat(python): add a `datetime` selector

- polars/polars-lazy/src/physical_plan/expressions/apply.rs
- polars/polars-lazy/src/physical_plan/expressions/mod.rs
- py-polars/tests/unit/operations/test_aggregations.py
> fix(rust, python): ensure agg(F(lit)) == lit

- polars/polars-arrow/src/conversion.rs
- polars/polars-arrow/src/kernels/concatenate.rs
- polars/polars-core/src/chunked_array/ops/take/traits.rs
- polars/polars-core/src/frame/groupby/perfect.rs
- polars/polars-core/src/series/implementations/object.rs
- polars/polars-json/src/json/deserialize.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/physical_plan/exotic.rs
- polars/polars-row/src/lib.rs
- polars/src/lib.rs
This is actually more of a hassle than I thought 😅 
My goal is to fix all the links and then enforce that the docs build correctly without warnings in the CI.
> docs(rust): Fix some doc links

- .github/workflows/docs-rust.yml
- polars/polars-arrow/src/conversion.rs
- polars/polars-arrow/src/kernels/concatenate.rs
- polars/polars-core/src/chunked_array/array/iterator.rs
- polars/polars-core/src/chunked_array/list/iterator.rs
- polars/polars-core/src/chunked_array/mod.rs
- polars/polars-core/src/chunked_array/object/registry.rs
- polars/polars-core/src/chunked_array/ops/mod.rs
- polars/polars-core/src/chunked_array/upstream_traits.rs
- polars/polars-core/src/frame/groupby/mod.rs
- polars/polars-core/src/schema.rs
- polars/polars-json/src/json/deserialize.rs
- polars/polars-json/src/json/infer_schema.rs
- polars/polars-json/src/ndjson/deserialize.rs
- polars/polars-lazy/polars-plan/src/dsl/array.rs
- polars/polars-lazy/polars-plan/src/dsl/functions/temporal.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/src/dsl/functions.rs
- polars/polars-lazy/src/frame/mod.rs
- polars/polars-time/src/series/_trait.rs
Changes:
* Fix some broken links
* Enforce that docs build without any warnings in the CI
> docs(rust): Fix more broken links

- .github/workflows/cache-rust.yml
- .github/workflows/lint-py-polars.yml
- .github/workflows/lint-python.yml
Changes:
* Separate workflow - no longer triggers on change of Python source code
* Use cache from main branch on branches. Improves performance greatly (1min instead of 4min) and reduces cache size needed.
> ci(python): Update linting for `py-polars` crate

- polars/polars-core/src/chunked_array/ops/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/expr.rs
- polars/polars-lazy/polars-plan/src/dsl/meta.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/selector.rs
- polars/polars-lazy/polars-plan/src/logical_plan/format.rs
- polars/polars-lazy/polars-plan/src/logical_plan/iterator.rs
- polars/polars-lazy/polars-plan/src/logical_plan/options.rs
- polars/polars-lazy/polars-plan/src/logical_plan/projection.rs
- py-polars/polars/expr/meta.py
- py-polars/src/expr/meta.rs
- py-polars/tests/unit/namespaces/test_meta.py
@alexander-beedie  the floor is yours. :)
> feat(rust, python): add intersection primitive for selector API

- polars/polars-lazy/polars-pipe/src/executors/sources/csv.rs
- polars/polars-lazy/polars-pipe/src/executors/sources/parquet.rs
- polars/polars-lazy/polars-pipe/src/pipeline/convert.rs
> fix(rust, python): delay opening files in streaming engine

- polars/polars-lazy/src/physical_plan/expressions/sortby.rs
- py-polars/tests/unit/test_errors.py
> fix(rust, python): raise on invalid sort_by

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
- polars/polars-lazy/polars-plan/src/logical_plan/pyarrow.rs
- py-polars/tests/unit/io/test_pyarrow_dataset.py
> fix(python): fix pyarrow dataset litetal filter

- polars/polars-lazy/polars-plan/src/dsl/meta.rs
- py-polars/docs/source/reference/selectors.rst
- py-polars/polars/selectors.py
- py-polars/src/expr/meta.rs
- py-polars/tests/unit/namespaces/test_meta.py
- py-polars/tests/unit/test_selectors.py
@alexander-beedie FYI. I want to release this afternoon and really want the set operations in there. :)
> feat(python): implement set operations for selector API

- py-polars/polars/utils/_construction.py
- py-polars/tests/unit/test_constructors.py
Closes #9282.
(Note: the issue only affects the upcoming pydantic 2.x series, which is currently in beta).
> fix(python): fix when loading model data from upcoming `pydantic` 2.x release

- .github/workflows/test-rust.yml
- polars/Makefile
- polars/src/lib.rs
This should take care of the last low-hanging fruit for utilizing caching from the main branch.
> ci(rust): Utilize caching in test job

- .github/workflows/lint-global.yml
> ci: Pin typos version

- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/thread_local.rs
- py-polars/tests/unit/streaming/test_ooc.py
> chore: fix test

- py-polars/Cargo.toml
Small patch for the selector API. Will yank the previous one.
> python polars 0.18.2

- py-polars/polars/expr/expr.py
- py-polars/tests/unit/operations/test_is_in.py
> fix(python): avoid `is_in` TypeError with sets of values containing 'None'

- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
This looks like this:
DataFrame.groupby_dynamic:
---
LazyFrame.groupby_dynamic:
> docs(python): add "if you're coming from pandas" tip to groupby_dynamic

- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
> docs(python): clarify when day of week takes effect in groupby_dynamic

- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
> docs(python): document apply 'return_dtype' requirement

- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/hash_table.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/thread_local.rs
- polars/polars-row/src/encode.rs
Reuse the offsets buffer and save an allocation
> perf(rust, python): row encode buffer reuse

- polars/polars-lazy/polars-pipe/src/pipeline/convert.rs
> fix(rust): fix compilation of other rustc versions

- py-polars/polars/config.py
Quick/minor update to previous PR.
> refactor(python): remove extraneous type

- py-polars/polars/config.py
Fix pip install example on legacy cpu
> chore: Fix pip install example

- py-polars/polars/utils/convert.py
- py-polars/tests/parametric/test_lit.py
closes #9437 
right, let's fix this once and for all with a big parametric hypothesis test
> fix(python): pl.lit with datetime was producing slightly incorrect results

- polars/polars-lazy/polars-plan/src/dsl/dt.rs
- polars/polars-time/src/chunkedarray/date.rs
- polars/polars-time/src/series/mod.rs
> docs(rust): note that weekday is actually ISO weekday

- polars/polars-time/src/groupby/dynamic.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
- py-polars/tests/unit/operations/test_rolling.py
> feat(rust, python): raise if period is negative in groupby_rolling

- py-polars/polars/selectors.py
- py-polars/tests/unit/test_selectors.py
* Now we have set operators for selectors, we can also invert `first` and `last`.
* Improved `repr` for selectors with *varargs.
> feat(python): support inversion of `first` & `last` selectors, additional minor repr improvements

- py-polars/polars/dataframe/frame.py
> docs(python): Document aggregate_function=None in pivot

- polars/polars-sql/src/functions.rs
- polars/polars-sql/tests/simple_exprs.rs
> feat(rust,sql,python): update error handling msg for sql functions

- polars/polars-error/src/lib.rs
- polars/polars-lazy/polars-plan/Cargo.toml
- polars/polars-lazy/polars-plan/src/dsl/expr.rs
- polars/polars-lazy/polars-plan/src/dsl/expr_dyn_fn.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/python_udf.rs
- polars/polars-lazy/polars-plan/src/logical_plan/aexpr/schema.rs
- py-polars/Cargo.lock
- py-polars/polars/__init__.py
- py-polars/src/apply/lazy.rs
- py-polars/src/expr/general.rs
- py-polars/src/lib.rs
- py-polars/src/object.rs
- py-polars/tests/unit/test_serde.py
A python function passed to `some_expr().map(..)` now is serializable with `pickle`.
> feat(python): serializable python functions in expressions

- polars/polars-core/src/datatypes/_serde.rs
- polars/polars-core/src/serde/chunked_array.rs
- polars/polars-core/src/serde/mod.rs
- polars/polars-core/src/serde/series.rs
- py-polars/tests/unit/test_serde.py
Also remove unneeded DeDataType
> fix(rust, python): fix serde for small integer dtypes

- py-polars/tests/unit/operations/test_rolling.py
A couple of PRs were merged without having fetched/merged upstream/main in between, so there's a little failure on the main branch
(ignore the branch name, I started this with the intention of working on something else 😄 )
> chore(python): fix test failing CI

- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- py-polars/tests/unit/namespaces/test_datetime.py
> fix(rust, python): unset sortedness for local date and local datetime

- polars/polars-lazy/polars-plan/src/dsl/expr_dyn_fn.rs
- polars/polars-lazy/polars-plan/src/dsl/python_udf.rs
- polars/polars-lazy/polars-plan/src/logical_plan/options.rs
- polars/polars-lazy/src/frame/python.rs
- polars/polars-lazy/src/physical_plan/executors/python_scan.rs
- py-polars/Cargo.lock
- py-polars/polars/io/pyarrow_dataset/anonymous_scan.py
- py-polars/polars/lazyframe/frame.py
- py-polars/polars/utils/__init__.py
- py-polars/polars/utils/_scan.py
- py-polars/src/apply/lazy.rs
- py-polars/src/lazyframe.rs
> refactor(python, rust): don't pickle pyarrow dataset

- .github/deploy_manylinux.sh
- .github/workflows/release-python.yml
- polars/polars-utils/src/atomic.rs
- py-polars/Cargo.lock
- py-polars/Cargo.toml
- rust-toolchain.toml
> python polars 0.18.4

- py-polars/polars/utils/convert.py
Similar to #9452 
On my MacBook Air M2
```python
In [1]: from datetime import datetime, timezone
In [2]: from polars.type_aliases import TimeUnit
In [3]: EPOCH_UTC = datetime(1970, 1, 1, tzinfo=timezone.utc)
In [4]: def _timestamp_in_seconds(dt: datetime) -> int:
...:     du = dt - EPOCH_UTC
...:     return du.days * 86400 + du.seconds
...:
In [5]: def _datetime_to_pl_timestamp(dt: datetime, time_unit: TimeUnit | None) -> int:
...:     """Convert a python datetime to a timestamp in nanoseconds."""
...:     dt = dt.replace(tzinfo=timezone.utc) if dt.tzinfo != timezone.utc else dt
...:     if time_unit == "ns":
...:         micros = dt.microsecond
...:         return 1_000 * (_timestamp_in_seconds(dt) * 1_000_000 + micros)
...:     elif time_unit == "us" or time_unit is None:
...: …
```
> perf(python): optimize `_datetime_to_pl_timestamp`

- polars/polars-core/src/frame/asof_join/groups.rs
- polars/polars-core/src/frame/hash_join/args.rs
- polars/polars-core/src/frame/hash_join/mod.rs
- polars/polars-core/src/frame/hash_join/single_keys.rs
- polars/polars-core/src/frame/hash_join/single_keys_inner.rs
- polars/polars-core/src/frame/hash_join/single_keys_left.rs
- polars/polars-core/src/frame/hash_join/single_keys_outer.rs
- py-polars/tests/unit/operations/test_join.py
> fix(rust, python): fix join validation when swapped

- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- py-polars/tests/unit/functions/test_range.py
closes https://github.com/pola-rs/polars/issues/9036
>  fix(rust, python): fix lazy schema for date_range and time_range with alias

- py-polars/polars/functions/range.py
Working on #9019 and starting small before I make any controversial changes 😅
> refactor(python): Minor cleanup of `arange`

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/test_predicates.py
> fix(rust, python): fix predicate pushdown case before sort

- py-polars/src/apply/series.rs
- py-polars/tests/unit/datatypes/test_object.py
> feat(python): implement apply object -> struct

- py-polars/tests/unit/test_df.py
#9592 was merged a little too early, one of the tests were faulty 😬
> test(python): fix faulty test of `to_numpy`

- polars/polars-lazy/polars-plan/src/dsl/dt.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- polars/polars-time/src/base_utc_offset.rs
- polars/polars-time/src/lib.rs
- py-polars/docs/source/reference/expressions/temporal.rst
- py-polars/docs/source/reference/series/temporal.rst
- py-polars/polars/expr/datetime.py
- py-polars/polars/series/datetime.py
- py-polars/src/expr/datetime.rs
- py-polars/tests/unit/namespaces/test_datetime.py
> feat(rust, python): add dt.base_utc_offset

- py-polars/polars/dataframe/frame.py
- py-polars/polars/lazyframe/frame.py
> docs(python): Add examples to .merge_sorted

- polars/src/lib.rs
> feat(rust): add polars::VERSION

- py-polars/polars/dataframe/frame.py
> docs(python): Clarify Dataframe.corr operates on columns

- polars/polars-core/src/chunked_array/comparison/mod.rs
- py-polars/tests/unit/operations/test_comparison.py
> fix(rust, python): fix ne_missing for booleans vs lit

- polars/polars-core/src/chunked_array/logical/categorical/stringcache.rs
- polars/polars-io/src/csv/read.rs
- polars/polars-io/src/csv/read_impl/batched_mmap.rs
- polars/polars-io/src/csv/read_impl/batched_read.rs
- polars/polars-io/src/parquet/read_impl.rs
- polars/polars-lazy/polars-plan/src/logical_plan/functions/mod.rs
- polars/polars-lazy/src/physical_plan/expressions/window.rs
- polars/tests/it/core/joins.rs
@magarick can you maybe rebase on this one? This should solve the issues in window functions.
> feat(rust, python): set string cache in window functions

- py-polars/polars/dataframe/groupby.py
- py-polars/polars/lazyframe/groupby.py
This PR add an example of aggregating column to a list. This is a trivial example, but for new user it might help.
> docs(python): Added trivial examples for the aggregation of columns in groupby

- polars/polars-io/src/csv/write_impl.rs
Noticed this small typo during usage.
> chore(rust): Fix small typo

- polars/polars-lazy/src/frame/file_list_reader.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/io/_utils.py
> fix(rust, python) improve glob pattern testing

- polars/polars-ops/src/chunked_array/list/sets.rs
- py-polars/polars/expr/list.py
- py-polars/src/conversion.rs
Looks like it was just a typo. Fixed and added a doctest.
Resolves #9728 #9727
> fix(rust, python): Fix list symmetric difference

- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- py-polars/tests/unit/operations/test_statistics.py
- py-polars/tests/unit/test_errors.py
> feat(rust, python): allow qcut in window expressions

- py-polars/Cargo.toml
A small patch to fix the set operations
> python polars 0.18.6

- py-polars/docs/source/reference/dataframe/modify_select.rst
Fixes https://github.com/pola-rs/polars/issues/9765.
Probably.
> docs(python): Add `rows_by_key` docs

- py-polars/docs/source/reference/expressions/functions.rst
> docs(python): add missing `last` entry

- polars/polars-lazy/polars-plan/src/logical_plan/builder.rs
- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs
- polars/polars-lazy/src/frame/mod.rs
- polars/polars-lazy/src/physical_plan/executors/scan/ipc.rs
- polars/polars-lazy/src/physical_plan/executors/scan/mod.rs
- polars/polars-lazy/src/physical_plan/executors/scan/parquet.rs
- polars/polars-lazy/src/tests/mod.rs
- polars/tests/it/lazy/cse.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/io/test_lazy_parquet.py
- py-polars/tests/unit/test_cse.py
> fix(rust, python): fix row-count schema

- py-polars/polars/series/series.py
> perf(python): speed up `in series` 10x

- polars/polars-core/src/series/implementations/array.rs
- polars/polars-core/src/series/ops/null.rs
- py-polars/tests/unit/datatypes/test_array.py
> fix(rust, python): fix array concat and Series::fill_null

- polars/polars-lazy/polars-plan/src/logical_plan/projection.rs
- py-polars/tests/unit/test_expansion.py
- py-polars/tests/unit/test_exprs.py
- py-polars/tests/unit/test_lazy.py
> fix(rust, python): fix regex + exclude

- polars/polars-sql/src/functions.rs
- py-polars/tests/unit/test_sql.py
Adds SQL support for `regexp_like`, and associated unit tests (inc. error conditions).
Handles both the two param (no regex flags) and three param variants.
```python
"scol": ["abcde", "abc", "a", None],
})
"SELECT scol FROM frame WHERE REGEXP_LIKE(scol,'(C|D)','i')",
).collect()
```
> feat(rust,python,cli): add `REGEXP_LIKE` function for SQL (both two and three parameter version)

- polars/polars-core/src/series/series_trait.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/dispatch.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
- polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
- polars/polars-lazy/polars-plan/src/dsl/mod.rs
- polars/polars-lazy/src/physical_plan/streaming/checks.rs
> feat(rust, python): allow set_sorted in streaming

- polars/polars-lazy/polars-plan/src/dsl/function_expr/pow.rs
- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/test_series.py
> fix(rust): Allow None as exponent

- py-polars/polars/dataframe/frame.py
would've closed https://github.com/pola-rs/polars/issues/9754 if it was still open
> docs(python): note ordering guarantee for groupby

- Cargo.toml
- polars-cli/Cargo.toml
- polars/Cargo.toml
- polars/polars-algo/Cargo.toml
- polars/polars-arrow/Cargo.toml
- polars/polars-core/Cargo.toml
- polars/polars-error/Cargo.toml
- polars/polars-io/Cargo.toml
- polars/polars-json/Cargo.toml
- polars/polars-lazy/Cargo.toml
- polars/polars-lazy/polars-pipe/Cargo.toml
- polars/polars-lazy/polars-plan/Cargo.toml
- polars/polars-ops/Cargo.toml
- polars/polars-ops/src/chunked_array/array/min_max.rs
- polars/polars-ops/src/chunked_array/list/any_all.rs
- polars/polars-row/Cargo.toml
- polars/polars-sql/Cargo.toml
- polars/polars-time/Cargo.toml
please wait merging other branches until this one is merged.
> rust polars 0.31.0

- py-polars/polars/functions/aggregation/vertical.py
We have to keep the PyCharm happy 😬
> chore(python): Workaround for PyCharm deprecation warning

- .github/release-drafter.yml
...and of course I messed up the regex 🙃
> chore: Fix autolabeler regex

- py-polars/polars/functions/eager.py
> fix(python): don't SO on align_frames

- py-polars/docs/source/reference/series/modify_select.rst
- py-polars/polars/series/series.py
- py-polars/polars/testing/parametric/primitives.py
- py-polars/polars/utils/_construction.py
- py-polars/tests/unit/datatypes/test_struct.py
- py-polars/tests/unit/series/test_append.py
- py-polars/tests/unit/series/test_extend.py
- py-polars/tests/unit/series/test_series.py
I noticed append/extend behaviour is already separated on the Rust side. We also have it nicely separated for DataFrames (`vstack`/`extend`). But for some reason, Python Series only have `append` with a boolean flag that changes it to an `extend`.
I think it makes sense to have this as a separate function. We already have the right terminology for it. So here's the PR that changes it.
> feat(python): Add `Series.extend`

- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/operations/test_statistics.py
- py-polars/tests/unit/test_errors.py
> refactor(python): deprecate `bins` argument and rename to `breaks` in `Series.cut`

- py-polars/polars/convert.py
Small patch for the documentation under [`polars.from_pandas`](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.from_pandas.html)
> docs(python): fix hyperlinks to pandas

- polars/polars-core/src/frame/hash_join/mod.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/joins/inner_left.rs
- py-polars/tests/unit/operations/test_join.py
> feat(rust, python): keep sorted flag in streaming left join

- py-polars/polars/expr/expr.py
- py-polars/polars/series/series.py
> docs(python): Improve docstrings for renaming operations

- polars/polars-core/src/frame/hash_join/mod.rs
- polars/polars-core/src/frame/mod.rs
- polars/polars-io/src/partition.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/joins/inner_left.rs
- polars/polars-lazy/polars-pipe/src/executors/sinks/sort/ooc.rs
- py-polars/tests/unit/operations/test_sort.py
> feat(rust, python): maintain sorted flag after partition_by

- polars/polars-io/src/csv/utils.rs
- py-polars/tests/unit/io/test_csv.py
> fix(rust, python): potential SO in csv infer schema

- py-polars/polars/functions/lazy.py
Ref: discord [query](https://discord.com/channels/908022250106667068/911186243465904178/1130702088213639188) asking if this was the case.
> docs(python): add note that `collect_all` returns result frames in the same order as input

- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/io/test_excel.py
> feat(python): add freeze_panes option to write_excel

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs
- py-polars/tests/unit/test_projections.py
> fix(rust, python): fix incorrect state in projection pushdown with joins

- py-polars/docs/Makefile
Correctly deletes build files when building docs.
> chore(python): cleans api sections in docs

- py-polars/docs/source/reference/dataframe/attributes.rst
- py-polars/polars/dataframe/frame.py
- py-polars/polars/series/series.py
- py-polars/tests/unit/dataframe/test_df.py
here's a convenience method I often find myself looking for - OK to add it? (no hard feeling if not of course)
> feat(python): add dataframe.flags property

- polars/polars-arrow/src/bitmap/arity.rs
- polars/polars-arrow/src/bitmap/mod.rs
- polars/polars-arrow/src/lib.rs
- polars/polars-core/src/chunked_array/ops/aggregate/mod.rs
- polars/polars-core/src/chunked_array/ops/apply.rs
- polars/polars-core/src/chunked_array/ops/is_in.rs
- py-polars/tests/unit/operations/test_is_in.py
continued on #10073 
fixes #10057
> fix(rust, python): fix Boolean::isin(null values)

- polars/polars-core/src/chunked_array/ops/unique/mod.rs
- polars/polars-core/src/frame/groupby/proxy.rs
- py-polars/tests/unit/series/test_series.py
> perf(rust, python): speedup mode on sorted data

- Cargo.toml
- py-polars/Cargo.lock
- py-polars/tests/unit/io/test_json.py
> feat(rust, python): support writing duration type in json

- Cargo.toml
- polars/polars-time/src/chunkedarray/kernels.rs
- py-polars/Cargo.lock
fixes #10107
and fixes #10049 via https://github.com/jorgecarleitao/arrow2/pull/1510
> fix(rust, python): don't panic if masked out values are invalid in temporal kernels

- py-polars/src/series/construction.rs
- py-polars/tests/unit/datatypes/test_array.py
> fix(rust, python): Allow initialize of pl.Array in Dataframe using schema alone

- polars/polars-lazy/polars-plan/src/logical_plan/optimizer/mod.rs
- py-polars/tests/unit/streaming/test_streaming.py
>  fix(rust, python): don't run file-caching in streaming mode 

- polars/polars-core/src/chunked_array/list/iterator.rs
- polars/polars-core/src/chunked_array/mod.rs
- polars/polars-core/src/series/implementations/array.rs
- polars/polars-core/src/series/implementations/binary.rs
- polars/polars-core/src/series/implementations/boolean.rs
- polars/polars-core/src/series/implementations/categorical.rs
- polars/polars-core/src/series/implementations/dates_time.rs
- polars/polars-core/src/series/implementations/datetime.rs
- polars/polars-core/src/series/implementations/decimal.rs
- polars/polars-core/src/series/implementations/duration.rs
- polars/polars-core/src/series/implementations/floats.rs
- polars/polars-core/src/series/implementations/list.rs
- polars/polars-core/src/series/implementations/mod.rs
- polars/polars-core/src/series/implementations/null.rs
- polars/polars-core/src/series/implementations/object.rs
- polars/polars-core/src/series/implementations/struct_.rs
- polars/polars-core/src/series/implementations/utf8.rs
- polars/polars-core/src/series/mod.rs
- polars/polars-core/src/series/series_trait.rs
- py-polars/tests/unit/datatypes/test_list.py
> fix(rust, python): clear bit settings in list iteration

- py-polars/polars/utils/udfs.py
- py-polars/polars/utils/various.py
- py-polars/tests/test_udfs.py
- py-polars/tests/unit/operations/test_inefficient_apply.py
another attempt at #9958, but starting over after all the refactors
> feat(python): suggest map_dict instead of lambda x: DICT[x]

- crates/polars-lazy/src/physical_plan/executors/mod.rs
- py-polars/tests/unit/operations/test_window.py
> fix(rust, python): ensure window function run partitioned when cse is hit

- crates/polars-row/src/fixed.rs
> fix(rust, python): initialize fixed null values

- py-polars/Cargo.lock
- py-polars/Cargo.toml
Patch for the regressions due to the new cse optimization.
> python polars 0.18.10

- crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs
- py-polars/tests/unit/test_cse.py
> fix(rust, python): no cse in groupby until fixed

- py-polars/Cargo.toml
Another patch for #10215 
Then I can explore in all ease how to make that better. :)
> python polars 0.18.11

- crates/polars-plan/src/utils.rs
- py-polars/polars/expr/expr.py
- py-polars/tests/unit/operations/test_apply.py
> fix(rust, python): don't panic in wildcard apply

- crates/polars-core/src/frame/groupby/aggregations/mod.rs
> fix(rust): correct agg_sum for ChunkedArray.

- crates/polars-pipe/src/executors/sinks/sort/sink_multiple.rs
- py-polars/tests/unit/streaming/test_streaming.py
- py-polars/tests/unit/streaming/test_streaming_sort.py
somehow the PR did not update, so re-opened.
fixes #10245
> fix(rust, python): fix logical columns of streaming multi-column sort

- crates/polars-io/src/parquet/read_impl.rs
- py-polars/tests/unit/streaming/test_streaming.py
> fix(rust, python): fix empty streaming parquet file

- examples/python_rust_compiled_function/Cargo.toml
- examples/python_rust_compiled_function/build.rs
Fixes https://github.com/pola-rs/polars/issues/10254.
> fix(rust): fix pyo3 link errors on macos

- crates/polars-plan/src/dsl/python_udf.rs
- py-polars/tests/unit/io/test_pyarrow_dataset.py
> fix(python): don't panic on cse if function hasn't implemented __eq__

- py-polars/polars/io/pyarrow_dataset/functions.py
Closes https://github.com/pola-rs/polars/issues/10296.
> docs(python): add note about pyarrow partitioning

- crates/polars-ops/src/chunked_array/strings/extract.rs
- crates/polars-ops/src/chunked_array/strings/namespace.rs
- crates/polars-plan/src/dsl/function_expr/mod.rs
- crates/polars-plan/src/dsl/function_expr/strings.rs
- crates/polars-plan/src/dsl/string.rs
- py-polars/src/expr/string.rs
- py-polars/tests/unit/namespaces/test_string.py
> fix(rust, python): Set correct dtype for `.extract_groups()`

- crates/polars/src/lib.rs
> chore(rust): fix typo in lib.rs

- crates/polars-core/src/chunked_array/ops/sort/categorical.rs
- py-polars/tests/unit/namespaces/test_categorical.py
> fix(rust, python): fix categorical lexical sort

- py-polars/src/series/buffers.rs
- py-polars/src/series/mod.rs
@stinodego this should be enough. Would this work?
It is zero copy.
> feat(python): add offsets utility

- py-polars/Cargo.toml
- py-polars/src/series/buffers.rs
- py-polars/src/series/mod.rs
- py-polars/tests/unit/series/test_series.py
#10323 
Macro hygiene. Need to have the feature flags in pypolars as well to reuse that macro.
> feat(python): add ptr for small integer types

- py-polars/Cargo.lock
- py-polars/Cargo.toml
> python polars 0.18.13

- crates/polars-lazy/src/physical_plan/executors/groupby_partitioned.rs
- crates/polars-lazy/src/physical_plan/expressions/cast.rs
- crates/polars-lazy/src/physical_plan/planner/lp.rs
- py-polars/tests/unit/operations/test_groupby.py
> fix(rust, python): finalize cast in partitioned groupby

- py-polars/src/expr/general.rs
Closes https://github.com/pola-rs/polars/issues/10346.
> feat(python): improve take_every(0) exception

- polars-cli/Cargo.toml
https://github.com/nushell/reedline/pull/617
> chore(rust): patch reedline until fix released

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/lib.rs
> docs(rust) Fix duplicate columns in example code.

- py-polars/polars/selectors.py
* Adds `signed_integer` and `unsigned_integer` selectors.
* Adds some new/extra docstring examples.
---
(I thought about adding parameters for `integer` but that looked and felt clunky in use, as well as being less discoverable; having explicit selectors for the signed/unsigned variants makes things _extremely_ obvious).
> feat(python): add explicit `selector` variants for signed/unsigned integers

- crates/polars-core/src/datatypes/any_value.rs
- crates/polars-plan/src/dsl/function_expr/fused.rs
- crates/polars-plan/src/dsl/function_expr/mod.rs
- crates/polars-plan/src/dsl/function_expr/random.rs
- crates/polars-plan/src/logical_plan/aexpr/hash.rs
- crates/polars-plan/src/logical_plan/aexpr/mod.rs
- crates/polars-plan/src/logical_plan/lit.rs
- crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs
> perf(rust, python): use hash as CSE Identifier

- crates/polars-io/src/csv/write.rs
- crates/polars-io/src/csv/write_impl.rs
- crates/polars/tests/it/io/csv.rs
- py-polars/polars/dataframe/frame.py
- py-polars/src/dataframe.rs
- py-polars/tests/unit/io/test_csv.py
Closes https://github.com/pola-rs/polars/issues/10371.
> feat(python,rust): add line_terminator option to write_csv

- crates/polars-core/src/datatypes/any_value.rs
A hash should be dependent on the data, never on the pointer to the data, as the same data can have a different hash in that case.
If we run `cheap` we simply only has the variant. Rather have more collisions than `T::hash != T::hash`
> fix: correct AnyValue::hash

- crates/polars-plan/src/dsl/function_expr/range.rs
> perf(rust, python): pre-alloc int_ranges

- py-polars/Cargo.lock
- py-polars/tests/unit/test_cse.py
> test: add test for 10401

- crates/polars-core/src/chunked_array/list/mod.rs
- crates/polars-core/src/chunked_array/ops/mod.rs
- crates/polars-core/src/frame/groupby/aggregations/agg_list.rs
- crates/polars-core/src/series/implementations/categorical.rs
- crates/polars-core/src/series/ops/to_list.rs
- py-polars/Cargo.lock
- py-polars/tests/unit/datatypes/test_array.py
> fix(rust, python): fix list groupby of array dtype

- py-polars/tests/unit/operations/test_window.py
> test(python): add test for 10417

- crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs
- py-polars/tests/unit/test_cse.py
> fix(rust, python): fix cse input schema

- crates/polars-pipe/src/executors/sinks/groupby/aggregates/last.rs
> fix(rust, python): ensure last aggregation deals with default chunk

- crates/polars-arrow/src/compute/decimal.rs
- py-polars/tests/unit/datatypes/test_decimal.py
> fix(python,rust): fix negative decimal parsing

- crates/polars-io/src/csv/read_impl/mod.rs
- crates/polars-plan/src/dsl/function_expr/strings.rs
- crates/polars-plan/src/dsl/options.rs
- crates/polars-time/src/chunkedarray/utf8/infer.rs
- crates/polars-time/src/chunkedarray/utf8/mod.rs
- crates/polars-time/src/groupby/dynamic.rs
- py-polars/polars/expr/string.py
- py-polars/polars/series/string.py
- py-polars/src/expr/string.rs
- py-polars/tests/unit/namespaces/test_strptime.py
> feat(rust, python): add `use_earliest` to `to_datetime` / `strptime`

- py-polars/src/dataframe.rs
> chore(python): Fix typo

- .github/workflows/test-rust.yml
- crates/Makefile
- crates/polars-io/Cargo.toml
- crates/polars-io/src/utils.rs
- crates/polars-utils/src/wasm.rs
This reverts commit be9ebb85e915bf939b63dc208ca789891fd9a617.
> revert: fix(rust): fix build for wasm (#9502)

- crates/polars-plan/src/logical_plan/projection.rs
- py-polars/tests/unit/test_expr_multi_cols.py
> fix(rust, python): Parsing regex col in Expr::Columns

- README.md
- crates/polars-arrow/src/kernels/rolling/no_nulls/min_max.rs
Closes https://github.com/pola-rs/polars/issues/10509.
> chore(rust): bump MSRV to 1.65

- crates/polars-core/src/chunked_array/ops/compare_inner.rs
- crates/polars-core/src/chunked_array/ops/take/take_random.rs
- crates/polars-core/src/hashing/vector_hasher.rs
- crates/polars-core/src/series/implementations/binary.rs
- crates/polars-core/src/series/implementations/boolean.rs
- crates/polars-core/src/series/implementations/categorical.rs
- crates/polars-core/src/series/implementations/dates_time.rs
- crates/polars-core/src/series/implementations/datetime.rs
- crates/polars-core/src/series/implementations/duration.rs
- crates/polars-core/src/series/implementations/floats.rs
- crates/polars-core/src/series/implementations/list.rs
- crates/polars-core/src/series/implementations/mod.rs
- crates/polars-core/src/series/implementations/object.rs
- crates/polars-core/src/series/implementations/utf8.rs
- crates/polars-error/src/lib.rs
- py-polars/tests/unit/datatypes/test_list.py
- py-polars/tests/unit/operations/test_unique.py
- py-polars/tests/unit/test_errors.py
> feature(rust, python): Multiple groupby key supports list type

- crates/polars-core/src/chunked_array/builder/list/boolean.rs
- crates/polars-core/src/chunked_array/builder/list/mod.rs
- crates/polars-core/src/chunked_array/builder/list/null.rs
- crates/polars/tests/it/core/series.rs
> fix(rust): List<null> chunked builder should take care of series name

- .github/workflows/lint-py-polars.yml
- crates/polars-plan/src/dsl/function_expr/boolean.rs
- py-polars/Cargo.lock
> fix(rust): `AllHorizontal` format string

- crates/polars-plan/src/dsl/function_expr/schema.rs
- py-polars/tests/unit/functions/test_range.py
Preparation for #10006 
* Refactor `map_to_date_range_dtype` to be a bit more readable.
> refactor(rust): Clean up schema calculation for `date_range`

- py-polars/polars/api.py
- py-polars/polars/config.py
- py-polars/polars/dataframe/frame.py
- py-polars/polars/expr/datetime.py
- py-polars/polars/expr/expr.py
- py-polars/polars/expr/string.py
- py-polars/polars/functions/lazy.py
- py-polars/polars/io/_utils.py
- py-polars/polars/io/csv/functions.py
- py-polars/polars/io/database.py
- py-polars/polars/lazyframe/frame.py
- py-polars/polars/selectors.py
- py-polars/polars/series/datetime.py
- py-polars/polars/series/list.py
- py-polars/polars/series/series.py
- py-polars/polars/series/string.py
- py-polars/polars/sql/context.py
> docs(python): add "see also" entries to ne/eq_missing and update related examples

- py-polars/polars/dataframe/frame.py
- py-polars/tests/unit/operations/test_join_asof.py
> fix(python): raise exception with invalid `on` arg type for join_asof

- crates/polars-pipe/src/executors/sources/csv.rs
- py-polars/tests/unit/streaming/test_streaming_io.py
> fix(rust, python): Cast small int type when scan csv in streaming mode.

- .github/workflows/clear-caches.yml
Closes #10148 
* Add new workflow that clears all caches weekly (or on demand).
I don't see a much cleaner way to keep cache sizes in check. Suggestions are welcome though.
> ci: Clear GitHub Actions caches weekly

- crates/polars-lazy/src/tests/io.rs
- crates/polars-plan/src/logical_plan/optimizer/slice_pushdown_lp.rs
> feat(rust, python): improve slice pushdown in unions

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/lib.rs
> docs(rust): Improve docs for `polars-lazy`

- crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs
- py-polars/tests/unit/datatypes/test_temporal.py
Example of when it shouldn't be preserved:
```python
{
"ts": [
datetime(2020, 10, 25, 1),
datetime(2020, 10, 25, 1, 30),
datetime(2020, 10, 25, 1),
],
"ambiguous": ["earliest", "earliest", "latest"],
}
)
df = df.with_columns(
ts_london=pl.col("ts").dt.replace_time_zone(
"Europe/London", ambiguous=pl.col("ambiguous")
)
).sort("ts_london")
df = df.with_columns(pl.col("ts_london").dt.replace_time_zone("UTC"))
print(df)
print(df.flags)
```
output before:
```python
shape: (3, 3)
┌─────────────────────┬───────────┬─────────────────────────┐
│ ts                  ┆ ambiguous ┆ ts_london               │
│ ---                 ┆ ---       ┆ ---                     │
│ datetime[μs]        ┆ str       ┆ datetime[μs, UTC]       │ …
```
> fix(rust, python): only preserve sortedness flag in replace_time_zone when safe

- crates/polars-arrow/src/kernels/rolling/no_nulls/mod.rs
- crates/polars-lazy/src/physical_plan/expressions/column.rs
- crates/polars-lazy/src/tests/io.rs
- crates/polars-plan/src/dsl/expr.rs
- crates/polars-plan/src/dsl/options.rs
- crates/polars-plan/src/frame/opt_state.rs
- crates/polars-plan/src/logical_plan/aexpr/hash.rs
- crates/polars-plan/src/logical_plan/aexpr/mod.rs
- crates/polars-plan/src/logical_plan/format.rs
- crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs
- crates/polars-plan/src/logical_plan/visitor/expr.rs
- crates/polars/tests/it/lazy/expressions/window.rs
- py-polars/tests/unit/test_cse.py
Also made the optimization more robust. Fixed a few bugs as drive by's that were found by activating cse on all rust tests.
> feat(rust, python): activate cse for group_by (again)

- crates/polars-core/src/chunked_array/ops/bit_repr.rs
- crates/polars-ops/src/series/ops/is_in.rs
- py-polars/tests/unit/operations/test_is_in.py
> fix(rust, python): Fix is_in cannot cast list type for float

- crates/polars-lazy/src/physical_plan/expressions/count.rs
- crates/polars-plan/src/dsl/mod.rs
- crates/polars-plan/src/dsl/names.rs
- crates/polars-plan/src/utils.rs
- py-polars/tests/unit/test_lazy.py
> fix(rust, python): get_single_leaf can't handle Expr::Count

- py-polars/polars/dataframe/frame.py
- py-polars/src/dataframe.rs
- py-polars/tests/unit/dataframe/test_df.py
- py-polars/tests/unit/operations/map/test_map.py
- py-polars/tests/unit/operations/map/test_map_rows.py
https://github.com/pola-rs/polars/issues/10744
> depr(python): Rename `DataFrame.apply` to `map_rows`

- crates/polars-plan/src/logical_plan/aexpr/mod.rs
- py-polars/tests/unit/test_cse.py
> fix(rust, python): fix equality of quantile aggregation node

- crates/polars/src/docs/lazy.rs
> docs(rust): Fix the un-compile Black box function parts in polars lazy cookbook

- crates/polars-pipe/src/pipeline/mod.rs
- py-polars/tests/unit/streaming/test_streaming_io.py
> fix(rust, python): Fix divided by zero error when read empty csv in streaming mode

- crates/polars-core/src/chunked_array/ops/aggregate/mod.rs
- crates/polars-core/src/datatypes/mod.rs
- crates/polars-core/src/series/mod.rs
- py-polars/tests/unit/series/test_series.py
Closes https://github.com/pola-rs/polars/issues/8184 and https://github.com/pola-rs/polars/issues/8500.
> fix: empty product returns identity

- py-polars/Cargo.toml
Patch for #10815. I will leave this open until the end of today. Maybe we need to include a few other fixes.
> python polars 0.19.1

- crates/polars-ops/src/chunked_array/strings/namespace.rs
- py-polars/polars/expr/string.py
- py-polars/polars/series/string.py
- py-polars/tests/unit/namespaces/test_string.py
Closes https://github.com/pola-rs/polars/issues/10853.
> fix: make count_match docs and extract_all docs/impl consistent around zero matches

- crates/polars-core/src/frame/arithmetic.rs
> fix: use pool in dataframe arithmetic

- crates/polars-plan/src/dsl/function_expr/boolean.rs
- crates/polars-plan/src/dsl/mod.rs
- crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
- crates/polars-plan/src/logical_plan/pyarrow.rs
- py-polars/docs/source/reference/expressions/boolean.rst
- py-polars/docs/source/reference/series/boolean.rst
- py-polars/polars/dataframe/frame.py
- py-polars/polars/expr/expr.py
- py-polars/polars/lazyframe/frame.py
- py-polars/polars/selectors.py
- py-polars/polars/series/series.py
- py-polars/src/expr/general.rs
- py-polars/src/series/mod.rs
- py-polars/tests/unit/series/test_series.py
- py-polars/tests/unit/test_exprs.py
Closes #10807
As discussed in #10807.
> depr(python): Rename `Expr.is_not()` to `Expr.not_()`

- crates/polars-core/src/chunked_array/array/iterator.rs
- crates/polars-core/src/chunked_array/comparison/mod.rs
- crates/polars-core/src/chunked_array/list/iterator.rs
- crates/polars-lazy/src/physical_plan/expressions/apply.rs
- crates/polars-lazy/src/physical_plan/expressions/binary.rs
- crates/polars-lazy/src/physical_plan/expressions/filter.rs
- crates/polars-lazy/src/physical_plan/expressions/group_iter.rs
- crates/polars-lazy/src/physical_plan/expressions/mod.rs
- crates/polars-lazy/src/physical_plan/expressions/take.rs
- crates/polars-lazy/src/physical_plan/expressions/ternary.rs
- crates/polars-ops/src/chunked_array/list/min_max.rs
- crates/polars-ops/src/chunked_array/list/namespace.rs
- crates/polars-ops/src/chunked_array/list/sum_mean.rs
- crates/polars-ops/src/series/ops/is_in.rs
- crates/polars-plan/src/dsl/function_expr/list.rs
- py-polars/src/series/export.rs
> fix(rust): tag amortized iter unsafe and add safe alternatives

- crates/polars-core/src/chunked_array/ops/chunkops.rs
- crates/polars-error/src/constants.rs
> fix: don't overflow length before checking limit

- crates/polars-core/src/chunked_array/comparison/mod.rs
- crates/polars-core/src/chunked_array/ops/take/take_single.rs
- py-polars/tests/unit/series/test_series.py
> fix(rust): Add broadcasting for list comparisons

- crates/polars-lazy/src/frame/mod.rs
- crates/polars-lazy/src/physical_plan/planner/lp.rs
- crates/polars-plan/src/dot.rs
- crates/polars-plan/src/logical_plan/alp.rs
- crates/polars-plan/src/logical_plan/builder.rs
- crates/polars-plan/src/logical_plan/builder_alp.rs
- crates/polars-plan/src/logical_plan/conversion.rs
- crates/polars-plan/src/logical_plan/format.rs
- crates/polars-plan/src/logical_plan/mod.rs
- crates/polars-plan/src/logical_plan/optimizer/cache_states.rs
- crates/polars-plan/src/logical_plan/optimizer/fast_projection.rs
- crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
- crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs
- crates/polars-plan/src/logical_plan/optimizer/slice_pushdown_lp.rs
- crates/polars-plan/src/logical_plan/schema.rs
- py-polars/polars/lazyframe/frame.py
This was an archaic temporary solution that we needed because we didn't had an optimizer at the time that could optimize all those things away. Now we do. :)
> refactor(rust): remove `LocalProjection`

- crates/polars-core/src/datatypes/any_value.rs
- crates/polars-core/src/series/any_value.rs
- py-polars/tests/unit/datatypes/test_decimal.py
> fix(rust): fix conversion from decimal to float

- .github/ISSUE_TEMPLATE/bug_report_python.yml
- .github/ISSUE_TEMPLATE/bug_report_rust.yml
#10882 broke the issue templates (duplicate ID). I fixed the issue and improved the issue rendering.
> chore: Fix issue templates for bug reports

- crates/polars-plan/src/dsl/function_expr/range/int_range.rs
- py-polars/tests/unit/functions/range/test_int_range.py
Closes https://github.com/pola-rs/polars/issues/10865.
> fix(rust): exclusive negative int_range(s) bounds

- crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs
- py-polars/tests/unit/test_cse.py
> fix: CSE don't accept opaque functions

- crates/polars-lazy/src/dsl/eval.rs
- crates/polars-lazy/src/dsl/list.rs
- crates/polars-lazy/src/physical_plan/executors/sort.rs
- crates/polars-lazy/src/physical_plan/expressions/alias.rs
- crates/polars-lazy/src/physical_plan/expressions/apply.rs
- crates/polars-lazy/src/physical_plan/expressions/binary.rs
- crates/polars-lazy/src/physical_plan/expressions/count.rs
- crates/polars-lazy/src/physical_plan/expressions/filter.rs
- crates/polars-lazy/src/physical_plan/expressions/sortby.rs
- crates/polars-lazy/src/physical_plan/expressions/take.rs
- crates/polars-lazy/src/physical_plan/expressions/ternary.rs
- crates/polars-sql/src/context.rs
- crates/polars-time/src/group_by/dynamic.rs
- py-polars/src/dataframe.rs
- py-polars/src/map/mod.rs
- py-polars/src/series/construction.rs
This is a continuation of https://github.com/pola-rs/polars/pull/10859, although it also contains a bunch of drive-by formatting/style fixes. 
No changes here should have changed any semantics.
> refactor: apply with_name in more places

- py-polars/tests/unit/test_queries.py
> test(python): add test for 10875

- crates/polars-plan/src/logical_plan/aexpr/schema.rs
- py-polars/tests/unit/test_errors.py
>  fix(rust, python): raise error when function didn't receive any inputs 

- py-polars/Cargo.lock
- py-polars/Cargo.toml
> python polars 0.19.2

- crates/polars-core/src/frame/mod.rs
- crates/polars-lazy/src/frame/mod.rs
- crates/polars-pipe/src/executors/operators/projection.rs
- crates/polars-pipe/src/pipeline/convert.rs
- crates/polars-plan/src/frame/opt_state.rs
- crates/polars-plan/src/logical_plan/builder.rs
- crates/polars-plan/src/logical_plan/functions/mod.rs
- crates/polars-plan/src/logical_plan/optimizer/fast_projection.rs
- crates/polars-plan/src/logical_plan/optimizer/mod.rs
- crates/polars-plan/src/logical_plan/options.rs
- py-polars/polars/dataframe/frame.py
- py-polars/polars/functions/lazy.py
- py-polars/polars/lazyframe/frame.py
- py-polars/src/lazyframe.rs
Regains some of #10939.
It probably is still slower in some cases, but we get ensure we don't read columns we drop so it is worth it.
> perf: improve performance of fast projection

- Cargo.toml
- crates/polars-ops/Cargo.toml
- crates/polars-ops/src/chunked_array/strings/namespace.rs
- crates/polars-utils/Cargo.toml
- crates/polars-utils/src/cache.rs
- py-polars/Cargo.lock
The `FastFixedCache` can likely be useful in other places too, so I spent a bit more effort in getting it tight.
> feat(rust): add proper cache for Regex compilation

- crates/polars-plan/src/dsl/function_expr/strings.rs
- py-polars/tests/unit/namespaces/test_string.py
Closes https://github.com/pola-rs/polars/issues/10903.
> fix: allow singular null in regex pattern
