pola-rs/polars

polars/src/chunked_array/mod.rs, polars/src/chunked_array/temporal.rs, polars/src/datatypes.rs, polars/src/fmt.rs, polars/src/frame/group_by.rs, polars/src/frame/hash_join.rs, polars/src/frame/ser/mod.rs, polars/src/lib.rs, polars/src/series/aggregate.rs, polars/src/series/arithmetic.rs, polars/src/series/comparison.rs, polars/src/series/mod.rs, py-polars/src/series.rs
Some clean up still has to be done.
=> Temporal types

polars/Cargo.toml, polars/src/chunked_array/aggregate.rs
=> fix aggregation with nans

py-polars/pypolars/frame.py
I didn't add a unit test, but if you'd prefer it I'll gladly add some.
=> Prevent Untitled12.ipynb by adding `pipe`.

examples/iris_classifier/src/main.rs, polars/src/chunked_array/builder.rs, polars/src/chunked_array/iterator.rs, polars/src/chunked_array/mod.rs, polars/src/chunked_array/ndarray.rs, polars/src/chunked_array/ops/aggregate.rs, polars/src/chunked_array/ops/chunkops.rs, polars/src/chunked_array/ops/take.rs, polars/src/chunked_array/ops/unique.rs, polars/src/chunked_array/temporal/conversions_utils.rs, polars/src/chunked_array/upstream_traits.rs, polars/src/fmt.rs, polars/src/frame/group_by.rs, polars/src/frame/hash_join.rs, polars/src/frame/mod.rs, polars/src/frame/ser/fork/csv.rs, polars/src/lazy/logical_plan/optimizer/projection.rs, polars/src/lazy/physical_plan/executors.rs, polars/src/lazy/physical_plan/expressions.rs, polars/src/utils.rs, py-polars/src/lazy/dataframe.rs
An iteration through some clippy suggestions
=> Apply clippy suggestions

.github/workflows/build-test.yaml, .github/workflows/test-windows.yaml, README.md
Forgot to remove it.
Also added trigger for pull requests
=> Remove deploy docs from build & test. Add pull request to triggers

polars/src/lazy/frame.rs, polars/src/lazy/logical_plan/optimizer/mod.rs, polars/src/lazy/logical_plan/optimizer/simplify_expr.rs, polars/src/lazy/prelude.rs, polars/src/lib.rs
Just testing out what it takes to add an extra optimization pass and rules.
This adds the rule to fold two literal 32 bit floats.
I think the ergonomics of it can still be improved by having some kind of framework?
=> Add simplify expression pass

polars/src/frame/hash_join.rs, polars/src/lazy/logical_plan/optimizer/projection.rs, polars/src/lazy/physical_plan/executors.rs
=> ensure the unique column name constraint in projection pushdown; 

polars/src/lazy/logical_plan/optimizer/simplify_expr.rs
Adds some boolean rules and shows running multiple rules.
Not yet happy with the clone needed in the `SimplifyBooleanRule`
Fixes optimization pass to finish :)
=> Optimizer additions

polars/src/chunked_array/mod.rs, polars/src/chunked_array/ops/mod.rs, polars/src/chunked_array/ops/take.rs, polars/src/frame/hash_join.rs, polars/src/frame/mod.rs, polars/src/series/mod.rs, py-polars/src/dataframe.rs, py-polars/src/series.rs
=> fix null values in join and better document take safety

polars/Cargo.toml
Removes some dependency versions from the dependency tree as shown in here https://github.com/ritchie46/polars/issues/157
=> Upgrade num to 0.3.1

polars/src/chunked_array/random.rs, polars/src/frame/group_by.rs, polars/src/frame/mod.rs, polars/src/lazy/dsl.rs, polars/src/lazy/frame.rs, polars/src/lazy/logical_plan/optimizer/predicate.rs, polars/src/lazy/logical_plan/optimizer/projection.rs, polars/src/lazy/physical_plan/expressions.rs, polars/src/lazy/physical_plan/planner.rs, polars/src/lazy/utils.rs, polars/src/series/ops.rs, py-polars/pypolars/frame.py, py-polars/pypolars/lazy/__init__.py, py-polars/pypolars/series.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs
Apply a window function over a subgroup.
=> [Lazy] Window functions

polars/src/frame/mod.rs, polars/src/lazy/frame.rs, polars/src/lazy/logical_plan/mod.rs, polars/src/lazy/logical_plan/optimizer/aggregate_scan_projections.rs, polars/src/lazy/logical_plan/optimizer/predicate.rs, polars/src/lazy/logical_plan/optimizer/projection.rs, polars/src/lazy/logical_plan/optimizer/simplify_expr.rs, polars/src/lazy/logical_plan/optimizer/type_coercion.rs, polars/src/lazy/mod.rs, polars/src/lazy/physical_plan/executors.rs, polars/src/lazy/physical_plan/expressions.rs, polars/src/lazy/physical_plan/mod.rs, polars/src/lazy/physical_plan/planner.rs, polars/src/lazy/utils.rs, py-polars/Cargo.toml, py-polars/pypolars/lazy/__init__.py, py-polars/src/lazy/dataframe.rs
Optionally parallelize the lazy execution of hte two inputs of a Join in the physical plan.
=> Lazy split at join

polars/src/chunked_array/iterator/mod.rs, polars/src/chunked_array/mod.rs, polars/src/chunked_array/ops/take.rs, polars/src/frame/mod.rs, polars/src/frame/ser/mod.rs, polars/src/series/implementations.rs, polars/src/series/mod.rs
This pull request provides a way to create a `polars::frame::DataFrame` from `Vec<arrow::record_batch::RecordBatch>`.
```
let batches : Vec<RecordBatch> = ...;
let df = DataFrame::try_from(batches).unwrap();
```
=> Feature frame from recordbatch

polars/Makefile, polars/polars-lazy/src/dsl.rs
@TheDan64 a bit more ergonomics for you.
=> [Lazy] temporal exprs

polars/polars-core/src/fmt.rs
=> fix impl Display for DataFrame

py-polars/pypolars/frame.py
I wrote two short docs for pypolars. Is this the way we want to setup the docs for the reference guide?
=> added to_csv and read_csv docs

polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/shift.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/implementations.rs, polars/polars-core/src/series/mod.rs, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/optimizer/mod.rs, polars/polars-lazy/src/physical_plan/planner.rs, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs
=> add overflowing shift

polars/polars-core/src/utils.rs
=> supertype of self is self 

examples/aggregate_multiple_files_in_chunks/Cargo.toml, examples/aggregate_multiple_files_in_chunks/src/main.rs, examples/iris_classifier/Cargo.toml, polars/polars-arrow/Cargo.toml, polars/polars-arrow/src/error.rs, polars/polars-arrow/src/kernels/mod.rs, polars/polars-arrow/src/kernels/set.rs, polars/polars-arrow/src/lib.rs, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ops/apply.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/set.rs, polars/polars-core/src/chunked_array/ops/take.rs, polars/polars-io/Cargo.toml
Overwrite null values
close #338 
Update arrow
close #333
=> make set overwrite null values

examples/iris_classifier/src/main.rs, polars/polars-core/src/datatypes.rs
Fixes compile errors on an iris example.
=> Fix iris example

polars/Cargo.toml, polars/polars-core/src/frame/group_by.rs, polars/polars-lazy/src/physical_plan/executors.rs, polars/src/lib.rs, py-polars/Cargo.toml
use mimalloc as global allocatr ~6,5% increase on q4
=> Add mimalloc

CHANGELOG.md, polars/polars-io/src/csv_core/buffer.rs, polars/polars-io/src/csv_core/parser.rs, py-polars/pypolars/frame.py
The csv-parser accidentally allocated too much memory. This fixes #366
=> Fix memory issue in csv-parser

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/parser.rs
=> fix CsvReader not able to parse line with \r\n new line character in string field.

CHANGELOG.md, py-polars/pypolars/frame.py, py-polars/pypolars/functions.py, py-polars/src/dataframe.rs, py-polars/tests/test_df.py, py-polars/tests/test_io.py, py-polars/tests/utils.py
* Read and write from `io.BytesIO`
* Read from raw web file
* Compress parquet files.
=> [Python] IO utils

CHANGELOG.md, README.md, polars/polars-lazy/src/logical_plan/optimizer/predicate.rs
Output would be incorrect otherwise.
=> Don't let predicate pushdown surpass a node that adds sort expression 

py-polars/pypolars/functions.py
Fix the mention of csv file in a parquet function docstring
=> [docstring] scan_parquet

py-polars/rust-toolchain
Small out-of-the-box quality of life improvement (https://rust-lang.github.io/rustup/overrides.html).
=> Set Rust toolchain to nightly for py-polars (uses SIMD feature)

polars/polars-arrow/src/builder.rs, polars/polars-core/src/chunked_array/builder.rs, polars/polars-core/src/frame/group_by.rs, polars/polars-lazy/src/frame.rs, py-polars/polars/lazy/__init__.py, py-polars/tests/test_lazy.py
This also fixes the example the book.
=> fix panic in List[Utf8] by using arrows builder

.github/workflows/create-py-release-test.yaml, polars/polars-core/src/datatypes.rs, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/mod.rs, py-polars/CHANGELOG.md, py-polars/Cargo.lock, py-polars/polars/functions.py, py-polars/polars/lazy/__init__.py, py-polars/src/lazy/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/tests/test_lazy.py
A shift van fill operation only fills the null values created by the shift operation.
=> [Lazy] Shift and fill

py-polars/polars/frame.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
Allow to get a DataFrame row by index and get a python tuple. Closes #401
=> Python get row tuples

py-polars/CHANGELOG.md, py-polars/polars/frame.py, py-polars/polars/series.py, py-polars/tests/test_df.py
Groupby over a groupby operation and get sub dataframes per group.
Or request the dateframe of a single group with `df.groupby("fruits").get_group("apples")`
=> [Python eager] groupby utils

polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/is_in.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/series/implementations.rs, polars/polars-core/src/series/mod.rs, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/logical_plan/iterator.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown.rs, polars/polars-lazy/src/physical_plan/planner.rs, py-polars/polars/lazy/__init__.py, py-polars/polars/series.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs
This allows one to check if the value of the Series are a member of the sublists in a list array/Series.
=> Series::is_in

py-polars/CHANGELOG.md, py-polars/polars/frame.py, py-polars/polars/lazy/__init__.py, py-polars/tests/test_df.py
[python] horizontal aggregation and eager DataFrame.shift_and_fill 
[Python] from arrow convert decimal128 to floats
=> [Python] arrow convert decimal to floats | horizontal aggregation, and df.shift_and_fill

CHANGELOG.md, polars/polars-core/src/chunked_array/kernels/temporal.rs, polars/polars-core/src/chunked_array/temporal/conversion.rs, polars/polars-core/src/series/implementations.rs, polars/polars-core/src/series/mod.rs, py-polars/CHANGELOG.md, py-polars/polars/datatypes.py, py-polars/polars/functions.py, py-polars/polars/index.md, py-polars/polars/series.py, py-polars/src/series.rs, py-polars/tests/test_pandas.py
=> [python] pandas datetime conversion to polars maintain time information

py-polars/polars/series.py, py-polars/tests/test_series.py
Closes https://github.com/ritchie46/polars/issues/486
=> Add shape for Series

py-polars/polars/lazy/__init__.py, py-polars/tests/test_lazy.py
Closes https://github.com/ritchie46/polars/issues/495
Changing this name didn't break any tests, so I'm wondering if I should add one here. Any ideas on how best to test this @ritchie46?
=> Avoid shadowing range function

polars/polars-core/src/chunked_array/ops/fill_none.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/frame/mod.rs, py-polars/polars/frame.py, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
=> null aware horizontal aggregation

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/builder.rs, polars/polars-io/Cargo.toml, py-polars/Cargo.lock
update arrow to 5bfae36954f7fe1573ec24166ba7d57f2a73b614
That commit also inlines append functions
=> inline append functions of builders

polars/polars-core/src/frame/hash_join.rs, polars/polars-core/src/series/arithmetic.rs
=> Parallelism in outer join.

polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-core/src/chunked_array/ops/fill_none.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/series/implementations/dates.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/mod.rs, py-polars/CHANGELOG.md, py-polars/polars/series.py, py-polars/src/series.rs
It used to take the 50% quantile. Now it takes the 50% quantile OR the average between the middle indexes.
=> Update median algorithm

polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/fmt.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/series/arithmetic.rs, polars/polars-core/src/utils.rs, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/dummies.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/iterator.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/mod.rs, polars/polars-lazy/src/physical_plan/executors.rs, polars/polars-lazy/src/physical_plan/expressions.rs, polars/polars-lazy/src/physical_plan/expressions/default.rs, polars/polars-lazy/src/physical_plan/expressions/final_agg.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/physical_plan/mod.rs, polars/polars-lazy/src/physical_plan/planner.rs, polars/polars-lazy/src/prelude.rs, polars/polars-lazy/src/utils.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/frame.py, py-polars/polars/lazy/__init__.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs
Made a lot of expressions workable from a groupby context. Furthermore there were various stability fixes regarding lazy + groupby.
=> Groupby context

polars/polars-core/src/chunked_array/builder.rs, polars/polars-core/src/frame/row.rs, polars/polars-core/src/utils.rs, py-polars/CHANGELOG.md, py-polars/polars/frame.py, py-polars/src/apply/dataframe.rs, py-polars/src/apply/mod.rs, py-polars/src/apply/series.rs, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/lib.rs, py-polars/src/series.rs, py-polars/tests/test_df.py
Apply a python function over the rows of a DataFrame. The row values are passed as tuple.
=> [Python] DataFrame.apply; closes #401

.github/workflows/build-test.yaml, README.md, polars/Cargo.toml, polars/polars-core/src/fmt.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/frame/groupby/pivot.rs, polars/polars-io/src/lib.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/src/lib.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/src/lib.rs
CI / clippy ran with all features activated. The default features did not compile all tests and had lots of compiler warnings. #550
=> Cleanup code/ tests for default features

py-polars/polars/frame.py, py-polars/tests/test_df.py
=> pyarrow -> polars ensure column name persists

py-polars/polars/datatypes.py, py-polars/polars/series.py, py-polars/tests/test_series.py
I have added summary statistics for additional dtypes. Next to that I have included the missing examples.
=> extended functionality of describe() for series

py-polars/polars/__init__.py, py-polars/polars/frame.py, py-polars/polars/functions.py
read_csv support StringIO
to_csv support return buffer
=> update read_csv and to_csv

polars/polars-core/src/chunked_array/ops/cum_agg.rs
Fixes #599 
This PR also refactors the implementation so that the iterators are not boxed.
=> Fix bug in cum_sum implementation 

polars/polars-lazy/src/logical_plan/optimizer/simplify_expr.rs
=> optimize sort().reverse to sort(reverse)

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/chunked_array/ops/is_in.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/frame/arithmetic.rs, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/arithmetic.rs, polars/polars-core/src/series/implementations/dates.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/implementations/object.rs, polars/polars-core/src/series/mod.rs, polars/polars-io/src/csv.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, polars/polars-lazy/src/physical_plan/expressions/cast.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/polars/lazy/__init__.py, py-polars/polars/series.py, py-polars/src/series.rs, py-polars/tests/test_series.py
=> Expand functionality for `Series::is_in`

README.md, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/sort.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/prelude.rs, polars/polars-core/src/series/implementations/dates.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/utils.rs, polars/polars-lazy/src/datafusion/conversion.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/physical_plan/executors/sort.rs, py-polars/CHANGELOG.md, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/frame.py, py-polars/polars/lazy/__init__.py, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_df.py
=> add multiple orderings to multilevel sort

.github/workflows/build-test.yaml, polars/polars-core/src/chunked_array/builder/mod.rs, polars/polars-core/src/chunked_array/ops/sort.rs, py-polars/Cargo.lock, py-polars/Cargo.toml
=> fix multiple argsort

py-polars/polars/frame.py, py-polars/polars/lazy/__init__.py, py-polars/polars/series.py, py-polars/tests/test_df.py, py-polars/tests/test_series.py
=> Rename 'output_type' to 'dtype_out'

py-polars/polars/frame.py, py-polars/tests/test_df.py
=> Python add more indexing support

polars/polars-io/src/csv_core/buffer.rs, polars/polars-io/src/csv_core/csv.rs, py-polars/polars/functions.py, py-polars/polars/lazy/__init__.py, py-polars/src/lazy/dataframe.rs
The maximum string chunk was tracked to allocate
all new memory chunks. A single outlier could
greatly increase memory usage. Now we use a
few more statistics to estimate needed chunk
size.
=> CSV change running statistics behavior. 

py-polars/polars/frame.py, py-polars/polars/series.py, py-polars/tests/test_df.py
=>  python support more indexing 275f7df 

polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/mod.rs
Take on string data is expensive as we need to copy a lot of data around. Default to multithreaded take for `Utf8` data. The cost of reallocation is low compared with parallelization wins.
```
bench single threaded   time:   [80.953 ms 81.091 ms 81.235 ms]                                  
bench multi-threaded    time:   [20.652 ms 20.820 ms 21.006 ms]                                 
bench multi-threaded no realloc                                                                            
time:   [14.067 ms 14.212 ms 14.374 ms]
```
=> use multithreaded take on string data

polars/Cargo.toml, polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ops/sort.rs, polars/polars-core/src/frame/groupby/resample.rs, polars/polars-core/src/functions.rs, polars/polars-io/Cargo.toml, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/functions.rs, polars/polars-lazy/src/logical_plan/aexpr.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/iterator.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, polars/polars-lazy/src/physical_plan/planner.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/lazy/__init__.py, py-polars/src/lib.rs, py-polars/tests/test_df.py
Closes: #666
Syntax:
```python
df[pl.argsort_by(["int_nulls", "floats"], reverse=[False, True])]
```
=> lazy; argsort_by function

py-polars/polars/frame.py, py-polars/tests/test_df.py
=> python: fix indexing

polars/polars-core/src/chunked_array/ops/sort.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/functions.rs, polars/polars-core/src/utils.rs, polars/polars-lazy/src/frame.rs
@ghuls Checked on the primitive + utf8 combination.
=> argsort by with utf8 and flt

py-polars/polars/lazy/__init__.py, py-polars/tests/test_df.py
=> Python: fix and test named Series literal

polars/polars-core/src/fmt.rs
#732 
We do not round floats anymore. Furthermore it is also more clear that a `Series` has more elements than shown.
Printing a 100 element `Series`:
```
shape: (100,)
Series: 'foo' [i32]
[
0
1
2
3
4
5
6
7
8
9
10
11
...
88
89
90
91
92
93
94
95
96
97
98
99
]
```
=> do not round floats and add shape and '..' to series fmt

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, py-polars/polars/functions.py
=> Don't panic, but error on out of bounds csv projection index

polars/polars-core/src/frame/explode.rs, polars/polars-lazy/src/frame.rs
=> fix panic in explode when columns have different ordering

polars/Cargo.toml, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/aggregate_pushdown.rs, polars/polars-lazy/src/logical_plan/optimizer/aggregate_scan_projections.rs, polars/polars-lazy/src/logical_plan/optimizer/join_pruning.rs, polars/polars-lazy/src/logical_plan/optimizer/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, polars/polars-lazy/src/physical_plan/planner.rs, polars/polars-lazy/src/prelude.rs, polars/polars-lazy/src/utils.rs
Should compile `polars-lazy` on wasm.
Closes #680
=> make csv opt-in in polars-lazy

polars/polars-lazy/src/dsl.rs, py-polars/polars/lazy/__init__.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_lazy.py
=> chained when_then operation

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/datatypes.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/frame/row.rs, polars/polars-core/src/utils.rs, polars/polars-io/src/csv_core/buffer.rs, py-polars/Cargo.toml, py-polars/polars/frame.py, py-polars/polars/functions.py, py-polars/src/arrow_interop/to_rust.rs, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
This is not the recommended way to create a DataFrame, but if users really need it, its better to do it fast then let them struggle.
=> Python/Rust create DataFrame from Rows

examples/aggregate_multiple_files_in_chunks/src/main.rs, polars/polars-core/src/frame/row.rs
I recently read your code since I am pretty interested in this project. I stumbled across some typos which I fixed on the fly. 
If this is not the way I should address typos, feel free to close this PR.
=> fix typos in main.rs and row.rs

polars/polars-core/src/frame/mod.rs
=> fix replace_or_add

py-polars/polars/lazy/__init__.py
=> python: accept single expression in LazyFrame.with_columns

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/float.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/mod.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/polars/lazy/__init__.py, py-polars/polars/series.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_series.py
=> add Series::round

py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/frame.py, py-polars/polars/lazy/__init__.py
=> Python 0.8.4 and head/limit aliases

polars/polars-io/src/csv_core/csv.rs
This decreases memory usage of the parser
=> decrease memory fragmentation of csv parser

polars/polars-core/src/chunked_array/ops/unique.rs
Categorical type `unique` and `n_unique` fast paths and improvements on `is_unique` / `is_duplicated` algorithms.
=> Unique fast path

polars/polars-core/src/series/mod.rs, py-polars/tests/test_series.py
=> fix bug in casting of list to largelist

polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown.rs
=> fix filter + alias combination

polars/polars-lazy/src/frame.rs
=> make sort empty exprs a no-op

polars/polars-core/src/series/iterator.rs, polars/polars-core/src/series/mod.rs, polars/polars-lazy/src/frame.rs
=> fix bug due to broadcasting filter, and splitting threads

polars/polars-core/src/chunked_array/ops/take_random.rs, polars/polars-core/src/utils.rs
Save ~13% in index computation if index has to loop trough all indexes.
=> improve cache coherence of take_random indexes

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/apply.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/take_random.rs, polars/polars-core/src/chunked_array/ops/unique.rs, polars/polars-core/src/fmt.rs, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/prelude.rs, polars/polars-core/src/series/arithmetic.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/iterator.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/utils.rs, polars/polars-io/Cargo.toml, polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown.rs, polars/src/lib.rs
Just a dirty merge-in of master to get latest bug-fixes
=> merge-master-arrow2

polars/polars-core/src/chunked_array/cast.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/physical_plan/expressions/cast.rs
=> Fix ternary null

polars/polars-arrow/Cargo.toml, polars/polars-arrow/src/array.rs, polars/polars-arrow/src/bit_util.rs, polars/polars-arrow/src/buffer.rs, polars/polars-arrow/src/error.rs, polars/polars-arrow/src/kernels/mod.rs, polars/polars-arrow/src/kernels/set.rs, polars/polars-arrow/src/lib.rs, polars/polars-arrow/src/prelude.rs, polars/polars-arrow/src/utils.rs, polars/polars-core/Cargo.toml
Removed older unneeded parts of polars-arrow.
polars-arrow now compiles and the tests run.
=> arrow2: polars-arrow

polars/polars-core/src/chunked_array/comparison.rs
Arrow2 has a function based on an enum instead of different function names per type, which makes it easy to branch off the implementation. Here we use it.
=> [Arrow2] migrated comparison

polars/polars-core/src/chunked_array/ops/zip.rs
Arrow2's name for `zip` is `if_then_else`.
=> [Arrow2] Migrated zip

polars/src/lib.rs
just some small language fixes in the crate docs, it's my first time contributing to open source so please let me know if I've missed anything
=> fix typos and grammar in crate docs

polars/polars-core/src/series/arithmetic.rs
Added checked division for float types
=> Checked division for float

README.md, polars/polars-core/src/chunked_array/cast.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown.rs
=> fix complex alias of complex predicate in projection

polars/polars-core/src/chunked_array/builder/categorical.rs, polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/series/comparison.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/polars-lazy/src/utils.rs
* Comparing categorical to string values does not cast to string array. Fixes #841 
* Casting categorical to categorical is a no-op and not a panic. Fixes #845
=> Improve categorical

py-polars/polars/lazy/__init__.py, py-polars/tests/test_lazy.py
=> python fix exception bug in 'describe_optimized_plan'

polars/polars-core/src/chunked_array/ops/aggregate.rs
by ~3.5x improvement measured on Uint32
=> improve performance of variance and stddev aggregation 

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/builder/categorical.rs, polars/polars-core/src/chunked_array/builder/mod.rs, polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/chunked_array/iterator/mod.rs, polars/polars-core/src/chunked_array/kernels/mod.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/object/builder.rs, polars/polars-core/src/chunked_array/ops/apply.rs, polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/chunked_array/ops/is_in.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/sort.rs, polars/polars-core/src/chunked_array/upstream_traits.rs, polars/polars-core/src/frame/explode.rs, polars/polars-core/src/series/implementations/dates.rs, polars/polars-core/src/series/implementations/object.rs, polars/polars-core/src/series/mod.rs, polars/polars-io/Cargo.toml, polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/ipc.rs, polars/polars-io/src/json.rs, polars/polars-io/src/lib.rs, polars/polars-io/src/parquet.rs, polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, py-polars/Cargo.lock
> Finished dev [unoptimized + debuginfo] target(s) in 1m 43s
^__^
=> [Arrow2] polar-core compiles

py-polars/polars/utils.py
=> python: cast to large-string before collection chunks

polars/polars-arrow/Cargo.toml, polars/polars-arrow/src/array.rs, polars/polars-arrow/src/kernels/set.rs, polars/polars-arrow/src/utils.rs, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ops/repeat_by.rs, polars/polars-core/src/chunked_array/upstream_traits.rs, polars/polars-io/Cargo.toml, polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/buffer.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/ipc.rs, polars/polars-io/src/lib.rs, polars/polars-io/src/parquet.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, py-polars/Cargo.lock
Built on top of #864, migrated io and lazy, `cargo build` exits 0 :)
=> [Arrow2] IO parquet + ipc

polars/polars-core/src/chunked_array/cast.rs, polars/polars-io/src/csv.rs
=> [Arrow2] Minor fix

polars/Makefile, polars/polars-arrow/Cargo.toml, polars/polars-arrow/src/array.rs, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/zip.rs, polars/polars-core/src/frame/groupby/aggregations.rs, polars/polars-core/src/frame/mod.rs, polars/polars-io/Cargo.toml, py-polars/.gitignore, py-polars/Cargo.lock, py-polars/src/arrow_interop/to_py.rs, py-polars/src/arrow_interop/to_rust.rs, py-polars/src/dataframe.rs, py-polars/src/file.rs, py-polars/src/npy.rs, py-polars/src/series.rs
This also ignores the shrink to fit for now, I will work on that one on the arrow2 side.
=> Arrow2 fixed test and compile python

polars/polars-io/src/json.rs
[Work in progress]
To fix #492
Feel free to comment or make suggestions on the progress so far
=> Implement arrow json writer

polars/polars-core/src/chunked_array/builder/mod.rs, polars/polars-core/src/frame/groupby/aggregations.rs
=> Arrow2: improve list aggregation

py-polars/src/dataframe.rs
=> fix is_duplicated dispatch python

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, py-polars/Cargo.lock, py-polars/polars/frame.py, py-polars/tests/db-benchmark/main.py
=> Arrow2 cherry pick

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/parser.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/aggregate_pushdown.rs, polars/polars-lazy/src/logical_plan/optimizer/aggregate_scan_projections.rs, polars/polars-lazy/src/logical_plan/optimizer/join_pruning.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, polars/polars-lazy/src/physical_plan/planner.rs, py-polars/polars/frame.py, py-polars/polars/functions.py, py-polars/polars/lazy/__init__.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/src/series.rs, py-polars/src/utils.rs
=> csv ignore line comments

polars/polars-core/src/chunked_array/comparison.rs
=> use kleene OR and AND

py-polars/Cargo.lock, py-polars/polars/functions.py, py-polars/polars/lazy/__init__.py, py-polars/src/lib.rs, py-polars/tests/test_series.py
=> Python arange add step and eager execution

polars/polars-io/src/csv.rs, py-polars/polars/functions.py, py-polars/tests/test_df.py
=> Python: don't modify orignal dataframe in concat function 

polars/polars-core/src/chunked_array/arithmetic.rs, py-polars/tests/test_df.py
=> broadcast left side of str addition as well

.github/deploy_manylinux.sh, .github/workflows/create-py-release-test.yaml, py-polars/Cargo.toml, py-polars/build.requirements.txt, py-polars/pyproject.toml, py-polars/tasks.sh
=> Build source distribution for Python

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/buffer.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/parser.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, py-polars/polars/frame.py, py-polars/polars/functions.py, py-polars/polars/lazy/__init__.py, py-polars/polars/utils.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_io.py
=> csv-parser add 'null_values' argument

polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs
=> fix bug in projection_pushdown in case of join on different column names

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/series/mod.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/legacy/setup.py, py-polars/polars/lazy/__init__.py, py-polars/polars/series.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_df.py
=> add dot product

polars/polars-arrow/src/vec.rs, polars/polars-io/src/csv_core/buffer.rs
Closes #955. Improves performance of parsing string data.
=> csv-parser, write utf8 data directly into arrow buffer

polars/Cargo.toml, polars/polars-io/Cargo.toml, polars/polars-io/src/csv_core/buffer.rs, polars/src/lib.rs, py-polars/Cargo.lock, py-polars/Cargo.toml
=> add optional simdutf8 for csv-parser

polars/polars-arrow/src/vec.rs, py-polars/polars/series.py, py-polars/tests/test_series.py
=> python: assign name in case of python datetime Series creation

CHANGELOG.md, polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/functions.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/functions.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/src/lib.rs, py-polars/CHANGELOG.md, py-polars/Cargo.toml, py-polars/polars/lazy/expr_functions.py, py-polars/src/lib.rs, py-polars/tests/test_lazy.py
#983 shows that string concatenation is `O(n^2)`. This will add a function that makes that `O(n)`.
=> Add concat_str function

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/comparison.rs, polars/polars-core/src/chunked_array/ops/bit_repr.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/polars/eager/series.py, py-polars/polars/functions.py, py-polars/polars/lazy/expr.py, py-polars/src/file.rs, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/src/utils.rs, py-polars/tests/test_lazy.py, py-polars/tests/test_series.py
@potter420 the interpret_cast. FYI
This PR also fix `pl.lit(True)` and adds broadcasting boolean operations
#893 needed this
=> python reinterpret

polars/polars-core/src/frame/mod.rs, py-polars/Cargo.lock, py-polars/polars/eager/frame.py, py-polars/polars/eager/series.py, py-polars/src/dataframe.rs
@ritchie46 I created this pull request after modified Dataframe `hash_rows` to take the same argument for hash seed as Series `hash`
=> DataFrame hash_rows function with detemine seed

polars/polars-core/src/frame/mod.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/eager/frame.py, py-polars/polars/eager/series.py, py-polars/src/dataframe.rs
@ritchie46 Did I messed up something?
=> Dev to Master

polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ndarray.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/src/apply/series.rs, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/src/lazy/dsl.rs
Python:
pyo3, ndarray, numpy
Rust:
ndarray
#1006
=> update rust/python deps

README.md
@jorgecarleitao Any suggestions for the arrow2 summary?
=> add arrow2 to readme

py-polars/polars/io.py
Hi @ritchie46 ,
This PR is to limit fsspec use to remote files only, due to more features now being implemented on the rust side.
Unfortunately, the following fail:
- read_csv of a local compressed file yields `RuntimeError: Any(Other("Other(\"invalid utf8 data\") on thread line 0;`. it seems the content is not decompressed on the rust side automatically.
- read_csv of something like '~/file.csv' yields a file not found error:
```python
FileNotFoundError                         Traceback (most recent call last)
<timed exec> in <module>
/opt/conda/lib/python3.9/site-packages/polars/io.py in read_csv(file, infer_schema_length, batch_size, has_headers, ignore_errors, stop_after_n_rows, skip_rows, projection, sep, …
```
=> Let rust decompress and normalise path

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/unique.rs, polars/polars-core/src/series/implementations/dates.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/mod.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, py-polars/Cargo.toml, py-polars/polars/eager/series.py, py-polars/polars/lazy/expr.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_series.py
=> add Series::mode

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/unique.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/frame/select.rs, polars/polars-core/src/series/implementations/dates.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/mod.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/optimizer/fast_projection.rs, polars/polars-lazy/src/logical_plan/optimizer/mod.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/__init__.py, py-polars/polars/convert.py, py-polars/polars/eager/frame.py, py-polars/polars/eager/series.py, py-polars/polars/functions.py, py-polars/polars/internals/construction.py, py-polars/polars/io.py, py-polars/polars/lazy/expr.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_df.py, py-polars/tests/test_series.py
@jorgecarleitao thanks for your help and great work on arrow2. Here we go. :slightly_smiling_face: :rocket:
=> Arrow2 cherry pick and python 0.8.13 release

polars/polars-io/src/lib.rs, polars/polars-io/src/tests.rs
=> test filter on utf8 columns

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/utils.rs, polars/polars-io/src/csv.rs, polars/polars-io/src/ipc.rs, polars/polars-io/src/json.rs, polars/polars-io/src/lib.rs, polars/src/lib.rs, py-polars/Cargo.lock, py-polars/Cargo.toml
=> remove lifetime in io writers

polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/physical_plan/executors/various.rs
=> fix select lit on empty frame

polars/polars-io/Cargo.toml, polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/parser.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-io/src/mmap.rs, polars/polars-lazy/src/logical_plan/mod.rs
Hi @ritchie46, 
This is still work in progress, there's a test that's failing but it's failing because of some escape character subtlety and not for legitimate reasons. Also, still working on checking that comment characters are being handled correctly. 
Please let me know if you have any questions or suggestions
=> io: remove csv dependency

py-polars/polars/eager/series.py, py-polars/pyproject.toml, py-polars/tests/test_df.py, py-polars/tests/test_series.py
@ghuls, I think this should be sufficient. for #1069
=> python update pyarrow dependency

CHANGELOG.md, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/iterator.rs, polars/polars-lazy/src/logical_plan/mod.rs, py-polars/CHANGELOG.md, py-polars/docs/source/reference/expression.rst, py-polars/polars/lazy/expr.py, py-polars/src/lazy/dsl.rs
=> keep_name expression

polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/aexpr.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/iterator.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/physical_plan/planner.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/functions.rst, py-polars/polars/eager/frame.py, py-polars/polars/lazy/expr.py, py-polars/polars/lazy/frame.py, py-polars/polars/lazy/functions.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/lib.rs, py-polars/tests/test_lazy.py
=> exclude expression

polars/polars-lazy/src/frame.rs, py-polars/docs/source/reference/dataframe.rst, py-polars/docs/source/reference/lazyframe.rst, py-polars/polars/eager/frame.py, py-polars/polars/lazy/frame.py, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_lazy.py
=> Lazy: groupby().head/tail

polars/polars-core/src/chunked_array/mod.rs, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/series.rs
=> python take collect into alignedvec

py-polars/docs/source/reference/expression.rst, py-polars/polars/eager/frame.py, py-polars/polars/lazy/expr.py, py-polars/tests/test_df.py, py-polars/tests/test_lazy.py
=> Python: drop_nulls and better slicing of Dataframe

polars/polars-lazy/src/logical_plan/iterator.rs, polars/polars-lazy/src/logical_plan/mod.rs
No recursion needed anymore <3
=> Lazy mutate expression

polars/polars-core/src/frame/groupby/aggregations.rs, polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, polars/polars-lazy/src/physical_plan/expressions/alias.rs, polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/physical_plan/expressions/binary_function.rs, polars/polars-lazy/src/physical_plan/expressions/cast.rs, polars/polars-lazy/src/physical_plan/expressions/column.rs, polars/polars-lazy/src/physical_plan/expressions/is_not_null.rs, polars/polars-lazy/src/physical_plan/expressions/is_null.rs, polars/polars-lazy/src/physical_plan/expressions/literal.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/physical_plan/expressions/not.rs, polars/polars-lazy/src/physical_plan/expressions/sort.rs, polars/polars-lazy/src/physical_plan/expressions/take.rs, polars/polars-lazy/src/physical_plan/expressions/ternary.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, polars/polars-lazy/src/test.rs
=> fix bugs in aggregations + filters

py-polars/CHANGELOG.md, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/datatypes.py, py-polars/tests/test_series.py
=>  python: boolean numpy array to boolean type 

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/mod.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-io/src/mmap.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/physical_plan/executors/mod.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, py-polars/tests/test_io.py
=> decompress during csv schema inference

polars/polars-io/src/csv_core/utils.rs
Read all gzip streams in a gzip file.
Fixes: https://github.com/pola-rs/polars/issues/1126
=> Read all gzip streams in a gzip file.

polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, polars/polars-lazy/src/physical_plan/planner.rs, polars/polars-lazy/src/test.rs, py-polars/polars/lazy/expr.py, py-polars/tests/test_lazy.py
This PR greatly improves window expressions. 
They now use the normal aggregation framework which make aggregation in window expressions and groupbys consistent.
We also allow binary and ternary expressions
in window expressions.
=> Improve window expression

polars/polars-core/src/frame/groupby/pivot.rs
=> fix quadratic behavior in pivot.count

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/utils.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/eager/frame.py, py-polars/polars/io.py, py-polars/src/dataframe.rs, py-polars/src/series.rs, py-polars/tests/test_io.py
=> add scientific notation to schema inference of csv parser

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-io/Cargo.toml, polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-io/src/ipc.rs, polars/polars-io/src/parquet.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/eager/frame.py, py-polars/polars/io.py, py-polars/src/dataframe.rs, py-polars/tests/test_io.py
Cherry picks + Also uses arrow2 for float aggregations. Utilizing SIMD and the faster kernels. (It used a boxed iterator before that)
=> Arrow2 cherry pick + faster float aggregation

py-polars/polars/lazy/expr.py
=> Python: inspect expr

polars/src/lib.rs
Hi,
This is a fix to a super minor documentation typo I didn't think was worth a ticket
=> Fix documentation link to ChunkedArray Struct

py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/functions.py, py-polars/src/conversion.rs, py-polars/src/lib.rs
=> python fix slow concat

polars/Cargo.toml, polars/polars-core/src/series/mod.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, py-polars/polars/lazy/expr.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_lazy.py
Expose rolling
- min
- max
- mean
- sum 
in lazy
=> lazy: add rolling window functions

polars/polars-core/src/datatypes.rs
=> add ToPolarsType trait for native rust numbers

polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/mod.rs, polars/polars-lazy/src/dsl.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/eager/series.py, py-polars/polars/lazy/expr.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_lazy.py
```python
s = pl.Series("A", [1.0, 2.0, 9.0, 2.0, 13.0])
s.rolling_apply(window_size=3, function=lambda s: s.std())
```
```
shape: (5,)
Series: 'A' [f64]
[
null
null
4.358898943540674
4.041451884327381
5.5677643628300215
]
```
=> rolling_apply

polars/polars-core/src/chunked_array/list/mod.rs, polars/polars-core/src/chunked_array/list/namespace.rs, polars/polars-lazy/src/physical_plan/expressions/shift.rs, polars/polars-lazy/src/physical_plan/expressions/sort.rs, polars/polars-lazy/src/physical_plan/expressions/sortby.rs, polars/polars-lazy/src/physical_plan/expressions/take.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/eager/series.py, py-polars/polars/lazy/expr.py, py-polars/src/lazy/dsl.rs
=> add arr namespace

py-polars/polars/eager/frame.py, py-polars/polars/eager/series.py
Finished some work that was open from Friday
=> New docs for frame and series

py-polars/polars/eager/frame.py, py-polars/polars/eager/series.py, py-polars/tests/test_series.py
Slices are cheap, take is expensive.
=> python: realize a range == slice

py-polars/polars/convert.py, py-polars/polars/utils.py, py-polars/src/lib.rs, py-polars/tests/test_interop.py
=> fix from_arrow w/ chunkedarray of list types

py-polars/polars/eager/series.py, py-polars/tests/test_series.py
Adding functionality to describe function for Series. 
- Nicer visualisation when returning the results
- Including utf8, float, int, bool and datetime dtypes
Any ideas on the tests? The floats are hard to assert. We could round all the floats to two decimals, but it's not very elegant.
=> Upgrade series.describe()

py-polars/polars/internals/construction.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/lib.rs, py-polars/src/series.rs, py-polars/tests/test_df.py
Also fixes a bug in creation of dataframes with python objects
=> python add from_records

py-polars/docs/source/reference/functions.rst, py-polars/polars/convert.py, py-polars/polars/eager/frame.py, py-polars/polars/internals/construction.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
=> add to_dicts and make sure that column names are stored

py-polars/polars/eager/series.py
I changed a code line of weekday method of eager series.
fix: #1354
Authored-by: fwani <seungfwani@gmail.com>
Signed-off-by: fwani <seungfwani@gmail.com>
=> Modify miss reference code of weekday method of eager series

README.md, py-polars/tests/test_io.py
=> Update some links

py-polars/docs/source/reference/dataframe.rst, py-polars/polars/eager/frame.py, py-polars/tests/test_df.py
=> python DataFrame.with_column -> pl.Series

.github/workflows/test-windows.yaml, py-polars/polars/datatypes.py, py-polars/polars/eager/series.py, py-polars/src/conversion.rs, py-polars/tests/test_series.py
=> Windows test

polars/polars-core/src/export.rs, polars/polars-core/src/lib.rs, py-polars/docs/source/reference/io.rst, py-polars/polars/io.py, py-polars/src/conversion.rs, py-polars/src/lib.rs, py-polars/tests/test_io.py
=> Ipc: read_schema and projection option in read_ipc

polars/polars-core/src/chunked_array/ops/rolling_window.rs
This slightly improves rolling_window functions, `rolling_min, rolling_max, rolling_mean` by removing an expensive modulo in a hot loop and using trusted_length iter collect.
before
```
bench rolling rate: 0%  time:   [134.85 us 135.17 us 135.47 us]  
```
after
```
bench rolling rate: 0%  time:   [104.08 us 104.68 us 105.49 us] 
```
=> improve rolling_window performance

polars/polars-core/src/chunked_array/ops/rolling_window.rs, polars/polars-lazy/src/dsl.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/eager/series.py, py-polars/polars/lazy/expr.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_series.py
This adds:
* rolling_std
* rolling_var
* rolling_quantile
* rolling_median
* rolling_skew
#1388
=> python: More rolling_window functions

polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/frame/explode.rs, py-polars/tests/test_df.py
The name of the series was not maintained in the new explode impl.
=> fix explode

.github/workflows/create-py-universal2-release.yaml
fixes #1345
Adds a workflow that generates universal2 wheel
=> Workflow to generate m1 wheels

polars/polars-lazy/src/logical_plan/optimizer/drop_nulls.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/polars-lazy/src/test.rs, polars/polars-lazy/src/utils.rs
=> fix invalid ReplaceDropNulls optimization

py-polars/src/apply/dataframe.rs, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
=> fix apply with list output type

polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/unique/mod.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/mod.rs, py-polars/polars/eager/series.py, py-polars/polars/lazy/functions.py, py-polars/tests/test_series.py
=> categorical aggregation output consistency

.github/workflows/create-py-universal2-release.yaml, polars/polars-core/src/chunked_array/ops/rolling_window.rs
It lead to UB when window_size was larger than array.
=> fix rolling_std

.github/workflows/create-py-universal2-release.yaml, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/eager/series.py, py-polars/src/series.rs, py-polars/tests/test_series.py
=> fix and test boolean Series indexing 

polars/polars-core/src/chunked_array/arithmetic.rs, polars/polars-core/src/chunked_array/ops/cum_agg.rs, polars/polars-core/src/chunked_array/ops/fill_null.rs, polars/polars-core/src/chunked_array/ops/full.rs, polars/polars-core/src/chunked_array/ops/is_in.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/reverse.rs, polars/polars-core/src/chunked_array/ops/set.rs, polars/polars-core/src/chunked_array/ops/sort.rs, polars/polars-core/src/chunked_array/ops/unique/mod.rs, polars/polars-core/src/chunked_array/ops/zip.rs, polars/polars-core/src/series/implementations/boolean.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/implementations/list.rs, polars/polars-core/src/series/implementations/object.rs, polars/polars-core/src/series/implementations/utf8.rs
Elides a few bounds checks in many operations
=> more collect_trusted

polars/polars-core/src/frame/asof_join.rs, polars/polars-core/src/frame/cross_join.rs, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/executors/join.rs, polars/polars-lazy/src/physical_plan/planner.rs, py-polars/docs/source/reference/lazyframe.rst, py-polars/polars/eager/frame.py, py-polars/polars/lazy/frame.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_lazy.py
=> Lazy: rename columns + Join suffix

polars/polars-core/src/series/implementations/floats.rs, py-polars/tests/test_window.py
=> fix agg_std/agg_var for Float32

polars/polars-core/src/chunked_array/categorical/builder.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/any_value.rs, polars/polars-core/src/datatypes.rs, polars/polars-core/src/fmt.rs, py-polars/src/conversion.rs
=> add categorical anyvalue

polars/polars-core/src/chunked_array/ops/explode.rs, py-polars/polars/eager/frame.py, py-polars/polars/functions.py, py-polars/src/conversion.rs, py-polars/src/lib.rs, py-polars/tests/test_series.py
=> python: concat also Series

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, py-polars/Cargo.lock, py-polars/polars/eager/series.py, py-polars/src/dataframe.rs, py-polars/src/series.rs, py-polars/tests/test_io.py
=> python: fix panic in csv parser with empty quote char

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-lazy/src/logical_plan/mod.rs
=> csv: fix comment before header

polars/polars-io/src/csv.rs, py-polars/tests/test_io.py
=> csv: don't parse dates if schema is set

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/parser.rs
=> csv: fix quoting with projection

polars/polars-core/src/chunked_array/builder/list.rs, polars/polars-core/src/chunked_array/builder/mod.rs, polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/fmt.rs, polars/polars-core/src/frame/groupby/aggregations.rs, polars/polars-core/src/utils.rs, polars/polars-lazy/src/functions.rs, py-polars/src/list_construction.rs, py-polars/tests/test_df.py
=> fix list builders for logical types

polars/polars-core/src/frame/mod.rs
Doc fix for https://github.com/pola-rs/polars/issues/1636
=> Correction to shape in DataFrame impl

CONTRIBUTING.md, py-polars/polars/lazy/expr.py
- Updating references to ./task.sh
- Including pre-commit command in recommendation prior to submitting PR
- Added missing link to create a New Issue
- Fixes spelling in ` py-polars/polars/lazy/expr.py`
=> Updating CONTRIBUTING.md

polars/polars-core/src/series/series_trait.rs
=> improve panic information of Series -> unimplemented

py-polars/polars/eager/series.py, py-polars/polars/lazy/expr.py, py-polars/tests/test_series.py
PR to address https://github.com/pola-rs/polars/issues/861
Adds [`sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan`] from [here](https://numpy.org/doc/stable/reference/routines.math.html)
=> feat(): Add trigonometry functions

py-polars/polars/internals/construction.py, py-polars/tests/test_interop.py
=> fix bug in pandas None arrays

polars/polars-core/src/chunked_array/ndarray.rs
Uninitialized is deprecated, and uninit (using MaybeUninit) is the replacement.
I'd love to have added tests here, but I don't know polars well enough to even build the tests or how to test this.
It sure looks like the old code was only writing to row 0, and the new code should write to every row.
=> Update to_ndarray for uninit changes

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/builder/list.rs, polars/polars-core/src/functions.rs, polars/polars-core/src/series/ops/mod.rs, polars/polars-core/src/series/ops/null.rs, polars/polars-core/src/utils.rs, py-polars/Cargo.toml, py-polars/polars/functions.py, py-polars/src/lib.rs, py-polars/tests/test_df.py
=> add diagonal concat utility

polars/polars-core/src/chunked_array/ops/unique/rank.rs
Fixes #1675. This changes the ranking behavior. The `None` values are now inferred as the latest possible rank.
=> fix rank algoritm with nulls

polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/mod.rs, py-polars/polars/io.py, py-polars/polars/lazy/frame.py, py-polars/src/lazy/dataframe.rs
=> add infer_schema_length to scan_csv

py-polars/polars/eager/series.py, py-polars/src/series.rs
=> python: fix to_list wo/ pyarrow

polars/polars-arrow/Cargo.toml, polars/polars-arrow/src/compute/cast.rs, polars/polars-arrow/src/compute/mod.rs, polars/polars-arrow/src/lib.rs, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/chunked_array/categorical/mod.rs, polars/polars-core/src/chunked_array/ops/unique/rank.rs, polars/polars-core/src/series/from.rs, polars/polars-core/src/series/into.rs, polars/polars-io/Cargo.toml, py-polars/Cargo.lock
=> update arrow: fixes str_slice

py-polars/tests/test_df.py, py-polars/tests/test_io.py, py-polars/tests/test_lazy.py
I think the intention was to have assert statements in these tests.
=> Add missing assert statements to Python tests

polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/utils/mod.rs, polars/polars-core/src/utils/series.rs, py-polars/tests/test_df.py
=> make sure that multiple key join is done on physical typed keys

py-polars/tests/test_df.py
Addressing comment by @ghuls https://github.com/pola-rs/polars/pull/1694#discussion_r744229037
=> Remove separate get_dummies import in tests

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/categorical/mod.rs, polars/polars-core/src/datatypes.rs, polars/polars-core/src/series/from.rs, polars/polars-io/Cargo.toml, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/eager/series.py, py-polars/src/series.rs, py-polars/tests/test_interop.py, py-polars/tests/test_sort.py
**Rust**
Adds categorical string iterator
**Python**
Categorical type to_list
fixes #1686
=> Python polars 0.10.17

py-polars/tests/test_interop.py
* `from_dict` and `from_dicts` were not covered
* the other tests are the examples in docstrings
=> Add tests for all functions in convert.py

polars/polars-core/src/chunked_array/builder/from.rs, polars/polars-core/src/chunked_array/comparison.rs, polars/polars-core/src/chunked_array/ops/full.rs, polars/polars-core/src/chunked_array/ops/zip.rs, polars/polars-lazy/src/dsl.rs
Was pretty old code. Still used iterators instead of arrow kernels in some branches.
=> improve comparissons

polars/polars-core/src/chunked_array/comparison.rs, polars/polars-core/src/chunked_array/list/iterator.rs, polars/polars-core/src/utils/mod.rs, polars/polars-lazy/src/physical_plan/executors/groupby.rs, polars/polars-lazy/src/physical_plan/expressions/take.rs, polars/polars-lazy/src/test.rs
=> fix consistency and ergonomics of take expression

README.md
@potter420 @ghuls @jorgecarleitao @marcvanheerden @olivier-lacroix 
I started a discord server, where more developmen/ questions can be discussed if wanted: https://discord.gg/4UfP5cfBE7
=> update readme with discord server

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, py-polars/Cargo.lock, py-polars/Cargo.toml
=> update arrow + python 0.10.19

py-polars/polars/lazy/expr.py, py-polars/tests/test_datelike.py
=> fix fill_value with python datetimes and expressions

py-polars/polars/lazy/expr.py, py-polars/polars/lazy/functions.py, py-polars/tests/test_datelike.py, py-polars/tests/test_df.py, py-polars/tests/test_interop.py, py-polars/tests/test_lazy.py, py-polars/tests/test_series.py
=> python: refactor tests and add literal datetime.date

polars/polars-core/src/datatypes.rs, polars/polars-lazy/src/dsl.rs, py-polars/docs/source/reference/expression.rst, py-polars/polars/datatypes.py, py-polars/polars/lazy/expr.py, py-polars/polars/lazy/functions.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_exprs.py, py-polars/tests/test_lazy.py
=> lazy upper/lower bound exprs; python: fix horizontal max/ min exprs

polars/polars-core/src/frame/mod.rs
Adding new examples to the DataFrame methods `max`, `std`, `var`, `min`, `sum`, `mean` and `median` using the rustdoc features.
```rust
use polars_core::df;
use polars_core::prelude::*;
fn example() -> Result<()> {
let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
"Die n°2" => &[3, 2, 3, 5, 3])?;
assert_eq!(df1.shape(), (5, 2));
let df2: DataFrame = df1.max();
assert_eq!(df2.shape(), (1, 2));
println!("{}", df2);
Ok(())
}
```
Output:
```text
shape: (1, 2)
+---------+---------+
| Die n°1 | Die n°2 |
| ---     | ---     |
| i32     | i32     |
+=========+=========+
| 6       | 5       |
+---------+---------+
```
```rust
use polars_core::df;
use polars_core::prelude::*;
fn example() -> Result<()> {
let df1: DataFrame = df!("Die n°1" => &[1, 3, 1, 5, 6],
"Die n°2" => &[3, 2, 3, 5, 3])?; …
```
=> Rust documentation: new examples for DataFrame methods

polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs
=> fix projection pushdown in IPC scanning

py-polars/polars/eager/series.py
=> Remove out_to_dtype

py-polars/polars/eager/series.py, py-polars/tests/test_series.py
=> Fix Series.str_concat

polars/Cargo.toml, polars/polars-core/src/series/mod.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, py-polars/polars/lazy/expr.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_series.py
=> rust abs expr; fix expr for floats

polars/polars-core/src/frame/mod.rs
Adding new examples to the `DataFrame` structure using the rustdoc features.
Example
```rust
use polars_core::df;         // or "use polars::df"
use polars_core::prelude::*; // or "use polars::prelude::*"
fn example() -> Result<()> {
let df1: DataFrame = df!("Element" => &["Copper", "Silver", "Gold"])?;
let s1: Series = Series::new("Proton", &[29, 47, 79]);
let s2: Series = Series::new("Electron", &[29, 47, 79]);
let df2: DataFrame = df1.hstack(&[s1, s2])?;
assert_eq!(df2.shape(), (3, 3));
println!("{}", df2);
Ok(())
}
```
Output:
```text
shape: (3, 3)
+---------+--------+----------+
| Element | Proton | Electron |
| ---     | ---    | ---      |
| str     | i32    | i32      |
+=========+========+==========+
| Copper  | 29     | 29       |
+---------+--------+----------+
| Silver  | 47 …
```
=> [Rust][Documentation] New examples for `DataFrame` methods: `hstack`, `vstack` and `vstack_mut`

README.md
The example doesn't work unless you import these symbols first.
=> Add imports to example in README

py-polars/polars/eager/frame.py, py-polars/polars/lazy/frame.py
Wanted to try and start filling in some documentation. I started with one function for now just to make sure this is all formatted correctly.
@ritchie46 - do you want the same examples added for `pl.LazyFrame.filter`?
=> Update `.filter()` docs

polars/polars-core/src/chunked_array/list/namespace.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/object/builder.rs, polars/polars-core/src/chunked_array/ops/is_in.rs, polars/polars-core/src/error.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/implementations/boolean.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/list.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/implementations/object.rs, polars/polars-core/src/series/implementations/utf8.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/series/series_trait.rs
=> check schema in vstack

polars/polars-core/src/series/from.rs
=> convert arrow binary to polarst list<u8>

polars/polars-core/src/chunked_array/list/mod.rs, polars/polars-core/src/frame/groupby/aggregations.rs, polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, polars/polars-lazy/src/physical_plan/expressions/alias.rs, polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/physical_plan/expressions/binary_function.rs, polars/polars-lazy/src/physical_plan/expressions/cast.rs, polars/polars-lazy/src/physical_plan/expressions/column.rs, polars/polars-lazy/src/physical_plan/expressions/is_not_null.rs, polars/polars-lazy/src/physical_plan/expressions/is_null.rs, polars/polars-lazy/src/physical_plan/expressions/literal.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/physical_plan/expressions/not.rs, polars/polars-lazy/src/physical_plan/expressions/shift.rs, polars/polars-lazy/src/physical_plan/expressions/take.rs, polars/polars-lazy/src/physical_plan/expressions/ternary.rs, polars/polars-lazy/src/test.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/polars/eager/series.py
=> support list dtype in groupby aggregations

polars/polars-core/src/chunked_array/ops/take/mod.rs, polars/polars-core/src/frame/hash_join/mod.rs
=> fix segfault in empty df join

polars/polars-core/src/chunked_array/ops/full.rs, polars/polars-core/src/chunked_array/ops/take/mod.rs
@ibENPC fix for the bug you reported.
=> fix invalid dtype when taking from empty list

py-polars/polars/__init__.py, py-polars/polars/testing.py, py-polars/tests/test_series.py
add compare method for series. First step to solve #1167
=> Enh add assert series equal

py-polars/polars/__init__.py
E731 do not assign a lambda expression, use a def
Does not pop up as we ignore the whole file, but still good to fix.
=> Fix flake8 E731

py-polars/polars/__init__.py, py-polars/polars/cfg.py, py-polars/polars/convert.py, py-polars/polars/datatypes.py, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/functions.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/internals/lazy_functions.py, py-polars/polars/internals/series.py, py-polars/polars/internals/whenthen.py, py-polars/polars/io.py, py-polars/polars/string_cache.py, py-polars/polars/testing.py, py-polars/polars/utils.py
As we define the public api in `polars/__init__.py`, the creation of `__all__` has also been done there.
=> Clean imports

py-polars/polars/internals/construction.py, py-polars/polars/utils.py
To remove the public api dependency in utils.py
=> Move coerce_arrow into internals

py-polars/polars/convert.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/internals/lazy_functions.py, py-polars/polars/internals/series.py, py-polars/tests/test_df.py, py-polars/tests/test_exprs.py, py-polars/tests/test_interop.py, py-polars/tests/test_io.py, py-polars/tests/test_lazy.py, py-polars/tests/test_series.py
Increase test coverage + fix several type annotations.
=> Add tests and fix type annotations

py-polars/polars/internals/series.py
The tests do not touch the default value, nor the globals().
=> Simplify get_ffi_func

py-polars/docs/source/reference/dataframe.rst, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/lazyframe.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/__init__.py
Fixes links that failed due to latest refactors.
=> fix python reference

polars/polars-core/src/frame/groupby/mod.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/src/dataframe.rs
=> python fix segfault in groupby.apply

polars/Cargo.toml, polars/polars-core/src/series/implementations/object.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/physical_plan/planner.rs, py-polars/polars/__init__.py, py-polars/tests/test_df.py
This allows to put any python object
in DataFrames and use them in the expression
API.
=> Python: activate extension

polars/polars-lazy/src/physical_plan/expressions/ternary.rs, polars/polars-lazy/src/test.rs
This fixes the masks in ternary expressions
composed of different aggregation states
We also run the 3 expressions on the thread pool,
easy parallelization.
=> Fix ternary and execute on threadpool

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/utils.rs
=> fix schema inference of single line without eol

polars/polars-io/src/csv_core/buffer.rs, polars/polars-io/src/csv_core/parser.rs
fixes #1831 
This makes the csv error messages a bit more clear. Showing the field that could not be parsed, the dtype it was tried to parse into and the column index. 
We also log the offset in bytes in the file. With a `File::seek()` the string could then be found.
We cannot easily log the line number, because we don't know it at this point. And I don't want to do a line count in during the creation of the error, because large potential code branches in hot loops hurt performance of the parser. With the bytes offset all information needed to find the culprit is given.
Last it gives a suggestion of running the parser with `ignore_errors=True` or by adding the field that could not be parsed to the `null_values` list.
=> improve csv error messages

polars/polars-lazy/src/lib.rs, polars/polars-lazy/src/logical_plan/optimizer/drop_nulls.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/utils.rs, polars/polars-lazy/src/tests/mod.rs, polars/polars-lazy/src/tests/predicate_pushdown.rs, polars/polars-lazy/src/tests/queries.rs
Very simple predicates were not
pushed down to the scan level
Fixed and added proper tests.
Will add more.
=> fix bug in predicate pushdown

py-polars/polars/datatypes.py, py-polars/polars/datatypes_constructor.py, py-polars/polars/internals/construction.py, py-polars/polars/testing.py, py-polars/tests/conftest.py, py-polars/tests/test_df.py, py-polars/tests/test_series.py
Plugging some more holes in the coverage.
=> Add additional tests

polars/polars-core/src/frame/mod.rs
Adding new examples for `DataFrame` methods using the rustdoc features:
- `column`
- `columns`
- `select_series`
- `replace`
- `is_unique`
- `is_duplicated`
- `slice`
=> [Rust][Documentation] New examples for `DataFrame` methods

polars/polars-core/src/frame/mod.rs, polars/polars-core/src/prelude.rs
=> [Rust] Add `df` macro to prelude

polars/polars-core/src/frame/mod.rs
Of course it is a first version that should evolve step by step as the crate evolves and the feedbacks are collected.
=> [Rust][Documentation] `DataFrame` introduction

polars/polars-lazy/src/dsl.rs, py-polars/docs/source/reference/expression.rst, py-polars/polars/internals/expr.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_exprs.py
=> add cumcount expr

polars/polars-core/src/datatypes.rs
Adding complete documentation to the `Field` structure using the rustdoc features.
=> [Rust][Documentation] `Field`

.github/workflows/benchmark.yaml, polars/polars-core/src/chunked_array/categorical/mod.rs, polars/polars-core/src/chunked_array/ops/sort.rs, polars/polars-core/src/datatypes.rs, polars/polars-core/src/frame/groupby/mod.rs, py-polars/tests/db-benchmark/various.py
=> fix sort of floating point NaN values

polars/polars-core/src/series/implementations/boolean.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/list.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/implementations/object.rs, polars/polars-core/src/series/implementations/utf8.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/src/tests/queries.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py
=> cast (u)int8 (u)int16 -> i64 in sum/cumsum/cumprod operations

py-polars/docs/source/reference/dataframe.rst, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/convert.py, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/functions.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/internals/lazy_functions.py, py-polars/polars/internals/series.py, py-polars/polars/io.py
Replaces #1935
Rebase meant going through all commits again on #1935. Created a new branch instead (this one),  ran `git merge --squash fix_multiline_docstring_examples` and now it is all cleean.
=> Fix docs & docstrings

README.md
=> Fix sponsor link

py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/lazy_functions.py, py-polars/polars/internals/series.py, py-polars/tests/test_exprs.py, py-polars/tests/test_series.py
=> python: add log, log10, exp

polars/polars-core/src/chunked_array/builder/from.rs, polars/polars-core/src/chunked_array/ops/sort.rs
This improves the performance of recreating the
new array. Also implements the new SortOptions
behavior.
=> improve Utf8 sorting

py-polars/polars/internals/construction.py, py-polars/tests/test_interop.py
=> python fix combine chunk of small integer arrow dictionaries

.github/deploy_manylinux.sh, .github/workflows/benchmark.yaml, .github/workflows/build-test.yaml, .github/workflows/create-py-release-test.yaml, .github/workflows/create-py-universal2-release.yaml, .github/workflows/docs.yaml, .github/workflows/test-windows.yaml, polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, py-polars/Cargo.lock
=> Update arrow + rustc

py-polars/polars/internals/series.py, py-polars/src/conversion.rs, py-polars/src/series.rs, py-polars/tests/test_datelike.py
=> python output date/datetime in to_list and to_dict

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/utils.rs
closes #1969
#1974 (partial fix)
=> csv; fix whitespace header inference

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/utils.rs
=> csv: add scientific notation without dots

polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-core/src/chunked_array/ops/unique/rank.rs
=> fix quantile all null

polars/polars-core/src/frame/hash_join/multiple_keys.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/series/series_trait.rs
=> fix bug in logical type join of window functions

polars/polars-core/src/frame/explode.rs, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/frame/upstream_traits.rs, py-polars/docs/source/reference/series.rst
This may be a fix for #1990. @zundertj can you check?
=> Overwrite existing column in outer join

polars/polars-core/src/chunked_array/ops/unique/rank.rs
=> fix rank empty schema

polars/polars-core/src/frame/mod.rs, py-polars/tests/test_df.py
=> check for duplicates in dataframe renaming

py-polars/polars/internals/frame.py
=> python overload vstack

py-polars/polars/internals/frame.py, py-polars/tests/test_sort.py
xref https://github.com/pola-rs/polars/issues/1984#issuecomment-986546130
=> overload sort

py-polars/polars/internals/frame.py
This is the other case I'd pointed out in #1984, so I think it's OK to close it?
closes #1984
=> overload to_json

polars/polars-io/src/ipc.rs
=> fix panix unsorted ipc projection

polars/polars-core/src/chunked_array/ops/is_in.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py
=> python: `is_in` docstring

polars/polars-core/src/chunked_array/ops/is_in.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/tests/test_lists.py
=> python arr.contains

polars/polars-lazy/src/dsl.rs, py-polars/docs/source/reference/expression.rst, py-polars/polars/internals/expr.py, py-polars/src/conversion.rs, py-polars/src/lazy/dsl.rs, py-polars/tests/test_datelike.py
=> pyhon: rows return date and datetime

py-polars/docs/source/reference/series.rst, py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/polars/io.py, py-polars/tests/test_datelike.py, py-polars/tests/test_df.py, py-polars/tests/test_io.py
=> python to_numpy return date/datetime and break some kwargs names

polars/Cargo.toml, polars/polars-core/src/chunked_array/random.rs, polars/polars-core/src/named_from.rs, polars/polars-core/src/series/implementations/boolean.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/list.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/implementations/object.rs, polars/polars-core/src/series/implementations/utf8.rs, polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_series.py
=> shuffle expr/series

py-polars/docs/source/reference/expression.rst, py-polars/polars/internals/expr.py, py-polars/src/lazy/dsl.rs
Add epoch_days, epoch_seconds and epoch_milliseconds
=> Python expr dt namespace:

.github/workflows/benchmark.yaml, py-polars/pyproject.toml
for Python versions lower than 3.8
=> Add "typing_extensions"

polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/logical_plan/projection.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/src/conversion.rs, py-polars/src/lazy/dsl.rs, py-polars/tests/test_lazy.py
=> exclude by dtype

polars/polars-core/src/frame/mod.rs
Related to https://github.com/pola-rs/polars/discussions/2010
=> Adding function to select columns by range and its documentation.

polars/polars-core/src/chunked_array/ops/filter.rs, py-polars/tests/test_lists.py
=> Fix filter list logical type

polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/polars-lazy/src/tests/queries.rs
=> fix bug in flattened apply (groupby)

polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/physical_plan/expressions/unique.rs, polars/polars-lazy/src/tests/queries.rs
=> fix invalid grouptuples in lazy

polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/tests/predicate_pushdown.rs
=> fix invalid predicate pushdown in left join

polars/polars-core/src/frame/groupby/dynamic.rs, py-polars/polars/internals/frame.py
```python
{"time": pl.date_range(low=datetime(2021, 12, 16), high=datetime(2021, 12, 16, 3), interval="30m"),
"groups": ["a", "a", "a", "b", "b", "a", "a"],
})
print(df)
```
```
shape: (7, 2)
┌─────────────────────┬────────┐
│ time                ┆ groups │
│ ---                 ┆ ---    │
│ datetime            ┆ str    │
╞═════════════════════╪════════╡
│ 2021-12-16 00:00:00 ┆ a      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 00:30:00 ┆ a      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 01:00:00 ┆ a      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 01:30:00 ┆ b      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:00:00 ┆ b      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 02:30:00 ┆ a      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 2021-12-16 03:00:00 ┆ a …
```
=> make dynamic_groupby correct if combined with normal groupby

py-polars/Cargo.lock, py-polars/Cargo.toml
@mhconradt there it is. Thanks for your help on this. It allowed me to finally blast through this time-series problems. :)
=> python 0.12.0

polars/polars-time/src/bounds.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py
=> assert Bound correctness

py-polars/polars/convert.py, py-polars/polars/internals/construction.py, py-polars/polars/internals/series.py, py-polars/tests/test_interop.py
=> python from_arrow respect rechunk argument

polars/polars-lazy/src/logical_plan/mod.rs, py-polars/tests/test_df.py
=> lazy; empty projection should give empty dataframe

nodejs-polars/README.md
@universalmind303 this is correct right?
=> update installation instructions nodejs-polars

polars/polars-lazy/src/logical_plan/mod.rs
=> Tweak to fix combination of lazy+ipc features

polars/polars-time/src/bounds.rs, polars/polars-time/src/groupby.rs, py-polars/tests/test_datelike.py
=> fix panic in dynamic groupby of single groups

py-polars/polars/internals/frame.py, py-polars/polars/utils.py
As per the question of @ghuls at https://github.com/pola-rs/polars/pull/2026#discussion_r767020731
=> Add type annotation for projection variable

nodejs-polars/Cargo.toml, nodejs-polars/package.json
=> chore(nodejs-polars): bump version to 0.0.6

py-polars/polars/internals/series.py
Removing the duplication here.
=> Refactor Series comparison methods

py-polars/polars/internals/frame.py
Indentation was off, and it some unrelated parameter description had been added.
=> Fix DataFrame.agg docstring

polars/polars-core/src/chunked_array/bitwise.rs
=> fix boolean Xor broadcast

py-polars/tests/test_series.py
Does hit the bug described in #2117 , so wont be mergeable currently.
=> Improve Series bitwise ops tests

py-polars/polars/internals/series.py, py-polars/tests/test_series.py
+ some tests for uncovered code paths
=> Allow Series.set with boolean numpy mask

py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/tests/test_series.py
I have made `reverse=False` the default value for `Series.arr.sort()` and `Expr.sort()`.
=> Add tests for Series

py-polars/polars/internals/functions.py
=> Add docstring example to concat

py-polars/polars/internals/frame.py, py-polars/tests/test_df.py
Plugging a number of gaps in test coverage + adding some examples.
=> Add DataFrame tests

polars/polars-core/src/chunked_array/comparison.rs, polars/polars-core/src/frame/groupby/pivot.rs, py-polars/tests/test_df.py
=> add pivot list first

polars/Cargo.toml, polars/polars-arrow/src/kernels/ew/average.rs, polars/polars-arrow/src/kernels/ew/mod.rs, polars/polars-arrow/src/kernels/mod.rs, polars/polars-core/Cargo.toml, polars/polars-core/src/prelude.rs, polars/polars-core/src/series/ops/ew.rs, polars/polars-core/src/series/ops/ewm.rs, polars/polars-core/src/series/ops/mod.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_series.py
=> initial emwa implementation

py-polars/polars/internals/frame.py
=> Remove DataFrame.__setitem__ [int]

py-polars/tests/test_cfg.py
By testing actual behaviour instead of only checking the environment flags.
Note that `test_set_tbl_rows` is skipped per #2162
=> Improve Config tests

polars/polars-arrow/src/array/default_arrays.rs, polars/polars-arrow/src/kernels/ewm/mod.rs, polars/polars-core/src/series/ops/ewm.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_series.py
#2148
Only correct in for cases without nulls atm.
=> add min_periods to ewma

polars/polars-arrow/src/kernels/ewm/mod.rs, polars/polars-arrow/src/kernels/ewm/variance.rs, polars/polars-core/Cargo.toml, polars/polars-core/src/series/ops/ewm.rs, polars/polars-lazy/src/dsl.rs, polars/polars-utils/src/lib.rs, polars/polars-utils/src/mem.rs, py-polars/Cargo.lock, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_series.py
This implements `ewm_std` and `ewm_var` following this recursive formula:
https://stats.stackexchange.com/a/111912/147321
This needs extra attention down the road. I could use some help. It is not the same algorithm pandas uses. Don't know what is correct/ better.
=> implement emw_std/var

py-polars/polars/internals/frame.py, py-polars/polars/io.py, py-polars/polars/utils.py, py-polars/tests/test_io.py
=> Refactor IO projection & columns argument handling

polars/polars-core/src/series/ops/extend.rs, polars/polars-core/src/series/ops/mod.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_series.py
Makes it easier to extend a constant or a null to existing Series. Needed in #2169
=> add Series::extend

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/frame/arithmetic.rs, polars/polars-core/src/frame/mod.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/polars/internals/frame.py, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
=> add DataFrame <-> DataFrame arithmetic

.github/workflows/create-py-release-test.yaml, .github/workflows/create-py-universal2-release.yaml, .github/workflows/test-python.yaml
=> drop python 3.6 support

py-polars/pyproject.toml
=> Update minimum Python to 3.7 in pyproject.toml

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/logical_plan/builder.rs
=> check for null values in csv schema inference

polars/polars-lazy/src/physical_plan/executors/union.rs
=> make lazy union parallel

polars/polars-core/src/chunked_array/arithmetic.rs, py-polars/polars/internals/frame.py, py-polars/tests/test_df.py
=> fix add string name

.github/workflows/docs.yaml
=> compile all rust docs

README.md, polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/tests/mod.rs, polars/polars-lazy/src/tests/queries.rs, polars/polars-lazy/src/utils.rs, polars/src/docs/eager.rs
=> Lazy: extend arguments in groupby context that do not belong to a group

polars/polars-arrow/Cargo.toml, polars/polars-arrow/src/export.rs, polars/polars-arrow/src/lib.rs, polars/polars-arrow/src/trusted_len/mod.rs, polars/polars-arrow/src/trusted_len/push_unchecked.rs, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/categorical/mod.rs, polars/polars-core/src/chunked_array/list/iterator.rs, polars/polars-core/src/chunked_array/ops/cum_agg.rs, polars/polars-core/src/chunked_array/ops/fill_null.rs, polars/polars-core/src/chunked_array/ops/is_in.rs, polars/polars-core/src/chunked_array/ops/sort.rs, polars/polars-core/src/chunked_array/trusted_len.rs, polars/polars-core/src/frame/asof_join/mod.rs, polars/polars-core/src/frame/groupby/hashing.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/prelude.rs, polars/polars-lazy/src/functions.rs, polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, polars/polars-time/src/duration.rs, polars/polars-time/src/test.rs, py-polars/Cargo.lock
Let the type system do our work.
=> reduce unsafe blocks by implementing TrustedLen trait

polars/polars-core/src/frame/row.rs, py-polars/polars/internals/frame.py, py-polars/src/apply/dataframe.rs, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
=> Python dataframe apply return DataFrame

polars/polars-core/src/frame/row.rs, py-polars/polars/internals/frame.py, py-polars/src/apply/dataframe.rs, py-polars/src/dataframe.rs, py-polars/src/lazy/apply.rs, py-polars/src/lazy/dataframe.rs, py-polars/src/series.rs, py-polars/tests/test_df.py
This removes intermediate allocations and a final rechunk, so will be a lot faster.
=> Python: improve `DataFrame.apply -> DataFrame`

polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/frame.rs, polars/polars-lazy/src/tests/io.rs, polars/polars-lazy/src/tests/mod.rs, polars/polars-lazy/src/tests/queries.rs, py-polars/Cargo.lock, py-polars/polars/internals/lazy_frame.py, py-polars/polars/io.py, py-polars/src/lazy/dataframe.rs
@MrPowers this allows scanning a parquet from a globbed string pattern.
=> polars lazy: read globbed parquet paths

polars/polars-arrow/src/kernels/rolling/no_nulls.rs, polars/polars-core/src/chunked_array/ops/rolling_window.rs
I found an issue in my last PR where weighted rolling medians were panicking. I fixed it, added some tests to catch the issue if it recurs and removed some unused code.
=> fix panics with weighted rolling median

polars/polars-core/src/chunked_array/categorical/builder.rs, polars/polars-core/src/chunked_array/categorical/mod.rs, polars/polars-core/src/fmt.rs, polars/polars-core/src/series/implementations/boolean.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/datetime.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/list.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/implementations/object.rs, polars/polars-core/src/series/implementations/utf8.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/series/series_trait.rs
Remove some unneeded function on the trait and set the m on the `Series` struct.
=> simplify series trait

polars/polars-core/src/frame/groupby/pivot.rs, py-polars/polars/internals/frame.py
=> sort pivot output

polars/polars-core/src/frame/asof_join/groups.rs
=> remove no longer needed dbg!

nodejs-polars/polars/lazy/functions.ts, nodejs-polars/src/conversion/into.rs, nodejs-polars/src/series.rs
`ListChunked<T>` was not properly getting converted to `Array<Array<T>>` when downcasting to js.
=> fix(nodejs): minor fixes to list conversion

polars/polars-core/src/chunked_array/list/namespace.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/lazy_functions.py, py-polars/polars/internals/series.py, py-polars/tests/test_df.py, py-polars/tests/test_lists.py
=> add arr.concat singleton lists

polars/polars-core/src/chunked_array/list/mod.rs, polars/polars-core/src/chunked_array/ops/any_value.rs, polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/ops/to_list.rs
=> improve logical types in Lists

polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/tests/queries.rs
=> improve expression engine aggstates

nodejs-polars/src/conversion/into.rs, nodejs-polars/src/datatypes.rs, nodejs-polars/src/series.rs
not yet implemented, just adds the pattern matching so things dont break.
=> update nodejs to handle `Duration` 

py-polars/polars/internals/functions.py, py-polars/tests/test_datelike.py
=> fix date_range time-unit kwargs

polars/polars-lazy/src/frame/csv.rs, polars/polars-lazy/src/frame/ipc.rs, polars/polars-lazy/src/frame/parquet.rs
=> compile on stable

polars/polars-core/src/series/into.rs, py-polars/polars/internals/series.py, py-polars/src/series.rs, py-polars/tests/test_datelike.py, py-polars/tests/test_interop.py
=> python: improve date/datetime get ergonomics

py-polars/docs/source/reference/dataframe.rst
PR #1992 adds this property in the code, but not in docs. This PR adds it to the docs.
=> Add schema to docs

polars/polars-core/src/fmt.rs
=> fix float fmting

polars/polars-io/src/csv_core/buffer.rs, py-polars/src/lazy/dsl.rs, py-polars/tests/test_strings.py
=> python: fix bug in .str.extract dtype

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/datetime.rs, polars/polars-core/src/series/implementations/duration.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/src/dsl.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/docs/source/reference/dataframe.rst, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_df.py, py-polars/tests/test_series.py
=> product expression

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/utils.rs
=> csv: improve float inference regex

py-polars/docs/source/reference/dataframe.rst, py-polars/polars/internals/frame.py, py-polars/polars/io.py, py-polars/tests/test_df.py
=> Add DataFrame constructor to docs

py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_series.py
=> python str.{strip, lstrip, rstrip}

py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs
=> add strict conversion for strptime

polars/polars-core/src/chunked_array/temporal/utf8.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_datelike.py
=> add exact kwarg to strptime

py-polars/polars/internals/functions.py
=> fix typo in python docstring

polars/polars-core/src/frame/groupby/dynamic.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-time/src/duration.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_datelike.py
=> extend dynamic groupby functionality to int{32,64}

polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/from.rs, polars/polars-lazy/src/lib.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/executors/join.rs, polars/polars-lazy/src/tests/mod.rs, polars/polars-lazy/src/tests/projection_pushdown.rs, py-polars/src/lazy/dataframe.rs
=> lazy: fix bug in join suffix and improve call ergonomics

polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/tests/optimization_checks.rs
This would lead to different slice size dependent on
selectivity.
=> [LAZY] do not let predicate pushdown pass slice node

polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/logical_plan/format.rs, polars/polars-lazy/src/logical_plan/optimizer/aggregate_scan_projections.rs, polars/polars-lazy/src/tests/projection_queries.rs
=> fix bug in aggscanprojection

polars/polars-core/src/chunked_array/temporal/duration.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_series.py
=> add duration methods

polars/polars-io/src/csv_core/parser.rs
#2367 fixed a bug in the csv parser but was a performance regression. This PR fixes and improves upon that regression.
Every time we were done parsing a line, because we 1. depleted a line, or 2. depleted all projected columns we search for the new line char that is not quoted. This search happened from a look behind location that was too conservative, meaning we scanned through more bytes. This PR makes sure we search from the current offset AND make sure we can skip an expensive function call if we are already on a `\n` (which is most cases).
Most interesting, time, instructions and branch misses
```
22.175,38 msec task-clock                #    9,403 CPUs utilized          
3.010      context-switches          #    0,136 K/sec                  
50      cpu-migrations            # …
```
=> csv parser improve performance

polars/polars-io/src/csv_core/parser.rs
```
21.019,35 msec task-clock                #    9,306 CPUs utilized          
3.993      context-switches          #    0,190 K/sec                  
22      cpu-migrations            #    0,001 K/sec                  
1.411.263      page-faults               #    0,067 M/sec                  
74.282.315.584      cycles                    #    3,534 GHz                    
104.099.611.130      instructions              #    1,40  insn per cycle         
17.954.097.738      branches                  #  854,170 M/sec                  
164.844.992      branch-misses             #    0,92% of all branches        
2,258783482 seconds time elapsed
18,279651000 seconds user
2,735462000 seconds sys
```
```
20.794,88 msec task-clock                #    9,414 CPUs utilized          
4.865 …
```
=> squeeze out more csv perf

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/parser.rs
=> csv: don't panic if last line misses fields and has no \n

polars/polars-core/src/series/series_trait.rs, py-polars/tests/test_queries.py
=> fix sort multiple with booleans

polars/polars-core/src/series/mod.rs, py-polars/tests/test_datelike.py
=> fix explode for datetime

py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/tests/test_df.py
=> python: Series.fill_nan

polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/series/implementations/boolean.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/datetime.rs, polars/polars-core/src/series/implementations/duration.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/list.rs, polars/polars-core/src/series/implementations/utf8.rs, polars/polars-core/src/series/mod.rs
=> fix bug in outer join on categorical

polars/polars-core/src/frame/groupby/dynamic.rs
=> fix groupby dynamic truncate

polars/polars-core/src/frame/groupby/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/slice_pushdown.rs, polars/polars-lazy/src/tests/io.rs, polars/polars-lazy/src/tests/mod.rs
=> don't let slice pushdown happen on predicate at scan

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/parser.rs
Fixes https://github.com/pola-rs/polars/issues/2433
=> Check byte after "\n" for "\r" instead of 2 bytes after.

polars/polars-time/src/groupby.rs, polars/polars-time/src/test.rs, py-polars/Cargo.lock, py-polars/Cargo.toml
patch for bug in `groupby_rolling`
=> python polars 0.12.15

polars/polars-lazy/src/dsl.rs, polars/polars-lazy/src/functions.rs, polars/polars-lazy/src/prelude.rs, py-polars/polars/internals/lazy_functions.py, py-polars/src/lazy/dsl.rs, py-polars/src/lib.rs, py-polars/tests/test_exprs.py
=> fix hmin/hmax of exprs

polars/polars-core/src/chunked_array/ops/any_value.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/take/traits.rs, polars/polars-core/src/datatypes.rs, polars/polars-core/src/frame/groupby/pivot.rs, polars/polars-core/src/frame/row.rs, polars/polars-core/src/series/from.rs, polars/polars-core/src/series/iterator.rs, polars/polars-core/src/series/mod.rs
fixes #2452 and #2453
Still could do better perf wise. Will look into that later.
=> fix quadratic behavior pivot

polars/polars-core/src/chunked_array/ops/zip.rs, polars/polars-lazy/src/tests/arity.rs
=> fix zip_with categorical

nodejs-polars/__tests__/io.test.ts, nodejs-polars/polars/dataframe.ts, nodejs-polars/src/dataframe/frame.rs, nodejs-polars/src/dataframe/io.rs, nodejs-polars/src/dataframe/mod.rs
add buffer & stream support for writers
=> feat(nodejs): add ipc & parquet buffer & stream writers

polars/polars-lazy/src/functions.rs, py-polars/tests/test_lazy.py
=> fix nested min max

polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/lib.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/time.rs, polars/polars-time/src/bounds.rs, polars/polars-time/src/duration.rs, py-polars/polars/internals/frame.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/tests/test_datelike.py
closes #2468 
This allows upsampling combined with a groupby. This gives us all functionality that pandas resample has. Polars only chooses to be a bit more verbose, so that we get access tot the expression aggregations and therefore are more flexible.
A resample in polars consists of an `upsample` followed by a `groupby_dynamic`.
```python
{"time": [datetime.datetime(2021, 2, 1), datetime.datetime(2021, 4, 1), datetime.datetime(2021, 5, 1), datetime.datetime(2021, 6, 1)],
"admin": ['Åland', 'Netherlands', 'Åland','Netherlands'],
"test2": [0, 1,2, 3],
})
upsampled = (df.upsample("admin", time_column="time", every="1mo", maintain_order=True)
.select(pl.all().forward_fill())
)
print(upsampled)
out = (upsampled
.groupby_dynamic(index_column="time",
every="1mo", …
```
=> add upsample in grouped context

polars/polars-core/src/chunked_array/categorical/merge.rs, polars/polars-core/src/chunked_array/ops/zip.rs, polars/polars-lazy/src/tests/arity.rs, polars/polars-lazy/src/tests/io.rs, polars/polars-lazy/src/tests/mod.rs, polars/polars-lazy/src/tests/optimization_checks.rs
=> check categorical merge correctness

polars/polars-core/src/frame/mod.rs, polars/polars-core/src/prelude.rs, polars/polars-lazy/src/dot.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/logical_plan/options.rs, polars/polars-lazy/src/physical_plan/executors/drop_duplicates.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, polars/polars-lazy/src/physical_plan/planner.rs, polars/polars-lazy/src/prelude.rs, py-polars/docs/source/reference/dataframe.rst, py-polars/docs/source/reference/lazyframe.rst, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs
Change the name from `drop_duplicates` to `distinct`
and add a `keep` argument that indicates which value
must be kept. For now the options are `first` and `last`
=> improve drop_duplicates/distinct

polars/polars-lazy/src/dot.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/functions.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/format.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/drop_nulls.rs, polars/polars-lazy/src/logical_plan/optimizer/fast_projection.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/logical_plan/optimizer/slice_pushdown.rs, polars/polars-lazy/src/logical_plan/options.rs, py-polars/polars/internals/lazy_frame.py, py-polars/polars/utils.py, py-polars/pyproject.toml, py-polars/src/lazy/dataframe.rs
When a lazy query is used in a notebook we will default to showing the naive query plan.
=> Fix dot graph and show by defautlt in jupyter notebooks.

polars/polars-core/src/chunked_array/ops/chunkops.rs, polars/polars-core/src/frame/mod.rs, polars/polars-lazy/src/dot.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/lit.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/physical_plan/executors/stack.rs, polars/polars-lazy/src/tests/predicate_queries.rs, polars/polars-lazy/src/utils.rs, py-polars/polars/internals/lazy_frame.py
=> slice singleton columns that are added to df with 0 rows

Cargo.toml, polars/polars-core/src/chunked_array/bitwise.rs, py-polars/Cargo.lock, py-polars/Cargo.toml
=> fix stackoverflow in comparing null booleans of unit length

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/buffer.rs
=> fix parsing quoted floats

polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-core/src/series/implementations/floats.rs, py-polars/tests/test_series.py
=> fix median float dispatch and fix overflowing mean aggregation

nodejs-polars/__tests__/dataframe.test.ts, nodejs-polars/__tests__/expr.test.ts, nodejs-polars/__tests__/lazyframe.test.ts, nodejs-polars/polars/dataframe.ts, nodejs-polars/polars/lazy/dataframe.ts, nodejs-polars/polars/lazy/expr.ts, nodejs-polars/polars/series/series.ts, nodejs-polars/polars/shared_traits.ts, nodejs-polars/src/conversion/from.rs, nodejs-polars/src/dataframe/frame.rs, nodejs-polars/src/dataframe/io.rs, nodejs-polars/src/dataframe/mod.rs, nodejs-polars/src/lazy/dsl.rs, nodejs-polars/src/lazy/lazyframe.rs, nodejs-polars/src/lazy/lazyframe_object.rs, nodejs-polars/src/series.rs, nodejs-polars/src/series_object.rs
currently blocked pending #2502
=> Nodejs transpose & distinct

polars/polars-arrow/src/kernels/take.rs, polars/polars-core/src/frame/groupby/aggregations.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/tests/aggregations.rs, polars/polars-lazy/src/tests/arity.rs, polars/polars-lazy/src/tests/mod.rs, polars/polars-lazy/src/tests/optimization_checks.rs, polars/polars-lazy/src/tests/queries.rs
=> fix bug in binary aggregation

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-lazy/src/frame/csv.rs, polars/polars-lazy/src/logical_plan/builder.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/io.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/tests/conftest.py, py-polars/tests/test_io.py
=> improve csv row skipping and fix bug

polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-lazy/src/physical_plan/planner.rs, py-polars/polars/internals/frame.py, py-polars/tests/db-benchmark/various.py
=> fix mean overflow

polars/polars-core/src/frame/groupby/aggregations.rs, polars/polars-lazy/src/physical_plan/executors/mod.rs, py-polars/polars/internals/frame.py, py-polars/tests/test_lazy.py, py-polars/tests/test_window.py
=> fix bug in nested/binary window functions

polars/polars-io/src/parquet/read_impl.rs, py-polars/tests/lazy_io/.gitignore, py-polars/tests/lazy_io/test_parquet.py
=> parquet statistics, don't skip if a column has not stats

polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/tests/projection_queries.rs, polars/polars-lazy/src/utils.rs
=> fix bug in projection pushdown on join suffixes

nodejs-polars/__tests__/expr.test.ts, nodejs-polars/polars/dataframe.ts, nodejs-polars/polars/index.ts, nodejs-polars/polars/io.ts, nodejs-polars/polars/lazy/expr.ts, nodejs-polars/polars/lazy/expr/list.ts, nodejs-polars/polars/lazy/expr/string.ts, nodejs-polars/polars/series/list.ts, nodejs-polars/polars/series/series.ts, nodejs-polars/polars/series/string.ts, nodejs-polars/src/dataframe/frame.rs, nodejs-polars/src/dataframe/mod.rs, nodejs-polars/src/lazy/dsl.rs, nodejs-polars/src/lazy/dsl_object.rs, nodejs-polars/src/list_construction.rs, nodejs-polars/src/series.rs, nodejs-polars/src/series_object.rs
adds missing features to nodejs implementation & syncs it up with master branch.
=> feat(nodejs): extend in place, arr.join & str.split

polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/slice_pushdown.rs, polars/polars-lazy/src/tests/io.rs, polars/polars-lazy/src/tests/projection_queries.rs
=> don't overwrite skip_rows in slice_pushdown opotimization

py-polars/polars/convert.py, py-polars/polars/internals/construction.py, py-polars/polars/internals/frame.py, py-polars/tests/test_interop.py
=> python create from empty arrow tbl

py-polars/polars/internals/expr.py, py-polars/src/lazy/dsl.rs
```python
print(pl.col("foo").cumsum().reverse())
```
`col("foo").cumsum().reverse()`
closes #2284
=> python: Expr.__str__()

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, polars/polars-io/src/parquet/predicates.rs, polars/polars-io/src/parquet/read.rs, polars/polars-io/src/parquet/read_impl.rs, py-polars/Cargo.lock
=> update arrow with parquet fixes

polars/polars-core/src/frame/mod.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/tests/optimization_checks.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs
=> fix row_count behavior in lazy optimizations

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/buffer.rs, polars/polars-lazy/src/frame/csv.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/options.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/io.py, py-polars/src/file.rs, py-polars/src/lazy/dataframe.rs, py-polars/tests/lazy_io/.gitignore, py-polars/tests/lazy_io/test_csv.py, py-polars/tests/test_df.py
Exposes `encoding` argument to `scan_csv` and fix bug in in encoding behavior.
=> expose and fix utf8-lossy encoding

polars/polars-core/src/chunked_array/ops/sort.rs, polars/polars-core/src/frame/explode.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/utils/mod.rs, py-polars/src/dataframe.rs
=> make sure we have rechunked in melt and dataframe sort

polars/polars-io/src/avro.rs, polars/polars-io/src/ipc.rs, polars/polars-io/src/lib.rs, polars/polars-io/src/parquet/read.rs, polars/polars-io/src/parquet/read_impl.rs, polars/polars-lazy/src/frame/csv.rs, polars/polars-lazy/src/frame/ipc.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/frame/parquet.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/logical_plan/options.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, polars/polars-lazy/src/tests/io.rs, polars/polars-lazy/src/tests/mod.rs, polars/polars-lazy/src/tests/optimization_checks.rs, polars/polars-lazy/src/tests/projection_queries.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/io.py, py-polars/polars/utils.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/tests/conftest.py, py-polars/tests/test_io.py
=> row_count at scan for ipc and parquet and fix projection pushdown of UDFs

polars/polars-core/src/series/implementations/categorical.rs, py-polars/tests/test_df.py
=> fix outer join dispatch of categorical types

polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/utils.rs, polars/polars-lazy/src/tests/predicate_queries.rs
=> block predicate pushdown in case of strict casts

polars/polars-lazy/src/logical_plan/optimizer/aggregate_scan_projections.rs, polars/polars-lazy/src/tests/projection_queries.rs
=> fix scan projection pushdown of same file

polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/series/comparison.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/simplify_expr.rs, polars/polars-lazy/src/tests/predicate_queries.rs
=> fix predicate pushdown on null generating joins

py-polars/Cargo.lock, py-polars/Cargo.toml
Last patch before breaking to `0.13.x`
=> python polars 0.12.24

polars/polars-io/src/csv_core/csv.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, polars/polars-lazy/src/tests/io.rs
=> fix scan_with_set_null_values

polars/polars-io/src/csv.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/parser.rs, polars/polars-io/src/csv_core/utils.rs
=> fix null row skipping in csv parsing

polars/polars-io/src/avro.rs, py-polars/docs/source/reference/dataframe.rst, py-polars/polars/internals/frame.py, py-polars/polars/io.py, py-polars/src/dataframe.rs, py-polars/tests/test_io.py
- implemented `to_avro` in py-polars, added its test, and added for docs.
- fixed the tests of avro io (use `frame_equal` instead of `assert_eq`)
=> Exported `AvroWriter` to py-polars

.github/workflows/build-test.yaml, .github/workflows/test-windows.yaml, polars/Makefile, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/frame/hash_join/multiple_keys.rs, polars/polars-core/src/utils/series.rs, polars/tests/it/joins.rs, polars/tests/it/main.rs
=> fix NaN in joins and init integration tests

polars/Cargo.toml, polars/polars-core/src/chunked_array/ops/cum_agg.rs, polars/polars-core/src/named_from.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/logical_plan/aexpr.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/tests/mod.rs, polars/tests/it/lazy/mod.rs, polars/tests/it/lazy/window_expressions.rs, polars/tests/it/main.rs
=> fix windows expressions and add range to df macro

polars/polars-io/src/parquet/read_impl.rs
Note to self: always consume iterators. That's what they are for.
Fixes #2651
=> parquet: read all arrays in row-group

polars/polars-io/src/parquet/predicates.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/physical_plan/expressions/is_null.rs, py-polars/tests/lazy_io/test_parquet.py
=> Fix parquet statistics so

polars/polars-core/src/chunked_array/logical/categorical/builder.rs, polars/polars-core/src/chunked_array/logical/categorical/ops/full.rs
=> improve `Categorical::full_null`

polars/Cargo.toml, polars/polars-core/src/export.rs, polars/polars-core/src/named_from.rs, polars/polars-time/Cargo.toml, polars/polars-time/src/date_range.rs, polars/polars-time/src/groupby/dynamic.rs, polars/polars-time/src/upsample.rs, polars/polars-time/src/windows/duration.rs, polars/polars-time/src/windows/window.rs, polars/src/export.rs, polars/tests/it/lazy/groupby_dynamic.rs, polars/tests/it/lazy/mod.rs, py-polars/src/lib.rs
=> fix lower bound of dynamic_groupby of larger intervals

py-polars/polars/internals/frame.py, py-polars/tests/test_interop.py
=> ignore index column in empty pandas dataframe

nodejs-polars/README.md
adds a minimum requirements section for nodejs.
=> docs(nodejs): update nodejs readme

py-polars/src/lazy/dataframe.rs, py-polars/tests/test_lazy.py
=> python fix lazy self join

polars/polars-lazy/src/physical_plan/expressions/mod.rs
=> remove assert; it is a false positive

polars/polars-lazy/src/frame/mod.rs, polars/tests/it/lazy/projection_queries.rs, py-polars/polars/internals/frame.py, py-polars/tests/test_df.py
=> fix_rename

polars/polars-core/src/chunked_array/ops/sort/mod.rs, polars/polars-core/src/series/implementations/categorical.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/functions.py, py-polars/polars/internals/series.py, py-polars/tests/test_categorical.py, py-polars/tests/test_lazy.py
=> fix categorical lexical rechunk

polars/polars-core/src/datatypes.rs, polars/polars-core/src/frame/asof_join/asof.rs, polars/polars-core/src/frame/asof_join/groups.rs, polars/polars-core/src/frame/asof_join/mod.rs, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/datetime.rs, polars/polars-core/src/series/implementations/duration.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/physical_plan/executors/join.rs, polars/polars-time/src/windows/duration.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_df.py
Closes #2681. 
Will still need to add forward strategy to grouper and tolerances, but that's something we can pick up incrementally.
=> add join_asof tolerances

polars/polars-lazy/src/physical_plan/expressions/binary.rs, py-polars/polars/internals/frame.py, py-polars/tests/io/test_lazy_parquet.py
=> fix parquet stats

.github/workflows/test-windows.yaml, polars/polars-io/src/csv_core/parser.rs, polars/polars-io/src/csv_core/utils.rs, polars/tests/it/io/csv.rs
=> fix csv quoting

py-polars/polars/internals/construction.py, py-polars/tests/test_series.py
=> python fix and test list creation without pyarrow

polars/polars-io/src/csv_core/utils.rs, polars/tests/it/io/csv.rs
=> csv; fix edge case of single line, no eol and no header

py-polars/src/arrow_interop/to_rust.rs, py-polars/tests/test_interop.py
=> fix from_pandas null_array

polars/polars-io/src/csv_core/utils.rs, polars/tests/it/io/csv.rs
=> always error on empty csv

polars/polars-arrow/src/kernels/concatenate.rs, polars/polars-arrow/src/kernels/mod.rs, polars/polars-core/src/frame/explode.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/builder.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
=> improve melt function

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/deploy_manylinux.sh, polars/polars-core/src/frame/cross_join.rs, polars/polars-core/src/frame/hash_join/mod.rs, py-polars/tests/test_df.py
=> respect suffix arg in cross join

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/deploy_manylinux.sh, polars/polars-core/src/frame/cross_join.rs, polars/polars-core/src/frame/hash_join/mod.rs, py-polars/tests/test_df.py
=> respect suffix arg in cross join (#2800)

polars/polars-core/src/datatypes.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/series/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, py-polars/tests/test_queries.py
=> fix type coercion when then otherwise

polars/polars-core/src/chunked_array/logical/categorical/merge.rs, polars/polars-core/src/chunked_array/logical/categorical/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/expressions/column.rs
=> improve schema correctness

polars/polars-core/src/chunked_array/list/namespace.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl/list.rs, polars/polars-lazy/src/physical_plan/expressions/column.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_lists.py
```python
s = pl.Series("a", [[1, 2, 3, 4], [10, 2, 1]])
s.arr.head(2)
```
```
shape: (2,)
Series: 'a' [list]
[
[1, 2]
[10, 2]
]
```
=> slice in arr namespace

py-polars/polars/internals/lazy_functions.py, py-polars/tests/test_functions.py
=> python fix horizontal all any

polars/polars-core/src/chunked_array/comparison.rs, py-polars/tests/test_strings.py
=> use eq_and_validity for strings

polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/src/dsl/dt.rs, py-polars/Cargo.toml, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_datelike.py
=> python add units to timestamp and epoch

py-polars/Cargo.lock, py-polars/Makefile, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/tests/test_datelike.py
=> default negative offset in dynamic groupby

polars/polars-io/src/csv.rs, py-polars/tests/io/test_csv.py
=> fix csv writer delimiter

py-polars/docs/source/reference/series.rst, py-polars/polars/internals/series.py, py-polars/tests/test_interop.py
=> python: series.to_pandas

polars/benches/groupby.rs, polars/polars-core/src/chunked_array/logical/struct_/from.rs, polars/polars-core/src/chunked_array/logical/struct_/mod.rs, polars/polars-core/src/chunked_array/ops/any_value.rs, polars/polars-core/src/series/from.rs, polars/polars-core/src/series/implementations/struct_.rs, polars/polars-core/src/series/into.rs, polars/polars-core/src/series/iterator.rs, polars/polars-lazy/src/dsl/functions.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/frame/csv.rs, polars/polars-lazy/src/frame/ipc.rs, polars/polars-lazy/src/frame/parquet.rs, polars/polars-lazy/src/lib.rs, polars/polars-lazy/src/prelude.rs, polars/polars-lazy/src/tests/mod.rs, py-polars/docs/source/reference/expression.rst, py-polars/polars/__init__.py, py-polars/polars/internals/lazy_functions.py, py-polars/src/conversion.rs, py-polars/src/lib.rs, py-polars/src/series.rs, py-polars/tests/test_struct.py
```python
pl.DataFrame({
"int": [1, 2],
"str": ["a", "b"],
"bool": [True, None],
"list": [[1, 2], [3]]
}).select([
pl.struct(pl.all()).alias("my_struct")  # this takes all columns and combines them into Series of type Struct
]).to_series().to_list() == [(1, "a", True, pl.Series([1, 2])), (2, "b", None, pl.Series([3]))]  # convert to a python list of tuples
```
=> improve structs

polars/polars-core/src/frame/mod.rs, polars/polars-lazy/src/dsl/struct_.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/physical_plan/executors/join.rs, py-polars/Makefile, py-polars/docs/source/reference/dataframe.rst, py-polars/docs/source/reference/lazyframe.rst, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_struct.py
```python
df = pl.DataFrame({"a": [1, 2]})
df.select(
[
pl.all().alias("a_original"),
pl.col("a")
.apply(lambda x: (x, x * 2, x % 2 == 0))
.struct.rename_fields(["a", "a_squared", "mod2eq0"])
.alias("foo"),
]
).unnest("foo")
```
```
shape: (2, 4)
┌────────────┬─────┬───────────┬─────────┐
│ a_original ┆ a   ┆ a_squared ┆ mod2eq0 │
│ ---        ┆ --- ┆ ---       ┆ ---     │
│ i64        ┆ i64 ┆ i64       ┆ bool    │
╞════════════╪═════╪═══════════╪═════════╡
│ 1          ┆ 1   ┆ 2         ┆ false   │
├╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┤
│ 2          ┆ 2   ┆ 4         ┆ true    │
└────────────┴─────┴───────────┴─────────┘
```
=> unnest operation

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, py-polars/Cargo.lock, py-polars/tests/db-benchmark/various.py
=> undo std::simd incorrect aggregation

py-polars/Cargo.lock, py-polars/Cargo.toml
Patch incorrect simd aggregation.
=> python polars 0.13.10

polars/polars-core/src/vector_hasher.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/utils.rs, polars/tests/it/lazy/mod.rs, polars/tests/it/lazy/predicate_queries.rs
=> fix bug in predicate pd after renaming node

polars/polars-io/src/csv_core/buffer.rs, polars/polars-io/src/csv_core/parser.rs, py-polars/tests/io/test_csv.py
=> csv check quoted null values

polars/polars-core/src/series/from.rs, py-polars/polars/__init__.py, py-polars/polars/datatypes.py, py-polars/polars/internals/construction.py, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/datatypes.rs, py-polars/src/lazy/apply.rs, py-polars/src/lazy/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/lib.rs, py-polars/src/list_construction.rs, py-polars/src/series.rs, py-polars/src/utils.rs, py-polars/tests/test_lists.py
```python
a = pl.Series([[1, 2]])
b = a.cast(pl.List(bool))
assert b.dtype == pl.List(pl.Boolean)
assert b.to_list() == [[True, True]]
```
=> Python: nested datatypes; Allow casting list inner types.

polars/polars-core/Cargo.toml, polars/polars-core/src/lib.rs, polars/polars-core/src/utils/mod.rs, polars/polars-io/Cargo.toml
=> Remove crate `num_cpus` from polars

nodejs-polars/Cargo.toml, nodejs-polars/polars/lazy/expr.ts, nodejs-polars/src/conversion/from.rs, nodejs-polars/src/dataframe/frame.rs, nodejs-polars/src/dataframe/io.rs, nodejs-polars/src/dataframe/mod.rs, nodejs-polars/src/datatypes.rs, nodejs-polars/src/lazy/dsl.rs, nodejs-polars/src/lazy/dsl_object.rs, nodejs-polars/src/lazy/functions.rs, nodejs-polars/src/lazy/lazyframe.rs, nodejs-polars/src/series.rs, nodejs-polars/tsconfig.json
this gets node pkg into sync with main branch. 
some features that still need to be implemented in node impl 
- struct dtype
- read json array & serde.
=> Nodejs updates

polars/Cargo.toml, polars/polars-lazy/src/dsl/mod.rs, py-polars/polars/internals/expr.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_exprs.py
=> fix unique and drop

polars/Cargo.toml, polars/polars-core/src/chunked_array/ops/explode.rs, py-polars/tests/test_df.py
=> fix explode of empty lists

polars/polars-lazy/src/frame/csv.rs, py-polars/tests/io/test_lazy_csv.py
=> respect dtype overwrite when schema is overwritten in lazy csv scanner

polars/polars-core/src/frame/mod.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/options.rs, polars/polars-lazy/src/physical_plan/executors/drop_duplicates.rs, py-polars/docs/source/reference/dataframe.rst, py-polars/docs/source/reference/lazyframe.rst, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs
=> rename distinct to unique

polars/polars-lazy/src/logical_plan/builder.rs, py-polars/tests/test_df.py
=> fix fill_nan dtypes

polars/polars-time/src/groupby/mod.rs, polars/polars-time/src/lib.rs, polars/polars-time/src/windows/bounds.rs, polars/polars-time/src/windows/groupby.rs, polars/polars-time/src/windows/test.rs
=> fix future calculation in groupby dynamic

polars/polars-core/src/frame/asof_join/groups.rs, polars/polars-core/src/frame/hash_join/mod.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/tests/test_datelike.py
The asof join + groupby functionality will now also work with a given tolerance.
=> add tolerance to asof + by

py-polars/polars/cfg.py
Want to add example to set_tbl_cols because I could not use it properly. Maybe a silly mistake from my side, but I could not find the answer in the documentation with a first glance.
=> Added example to set_tbl_cols

polars/polars-core/src/frame/row.rs
=> handle Utf8Owned AnyValue for DataType

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/series/ops/unique.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/src/lib.rs, polars/tests/it/lazy/expressions/arity.rs, polars/tests/it/lazy/expressions/mod.rs, py-polars/Cargo.toml, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_exprs.py, py-polars/tests/test_struct.py
```python
{
"id": ["a", "b", "b", "c", "c", "c"],
}
)
df.select([
pl.col("id").value_counts(),
])
```
```
shape: (3, 1)
┌─────────────────────────────────────┐
│ id                                  │
│ ---                                 │
│ struct[2]{'id': str, 'counts': u32} │
╞═════════════════════════════════════╡
│ {"c",3}                             │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ {"b",2}                             │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ {"a",1}                             │
└─────────────────────────────────────┘
```
=> `value_counts` and `unique_counts` expression

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/chunked_array/ops/apply.rs, polars/polars-core/src/series/ops/log.rs, polars/polars-core/src/series/ops/mod.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl/mod.rs, polars/src/lib.rs, polars/tests/it/core/mod.rs, py-polars/Cargo.toml, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_exprs.py
=> add native log and entropy expression

polars/polars-io/src/csv.rs, py-polars/polars/internals/frame.py, py-polars/src/dataframe.rs
=> expose quote char to csv writers api

polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, py-polars/tests/test_lazy.py
=> update groups in count() agg and correctly update state

polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/tests/it/lazy/expressions/apply.rs
=> fix groups state after apply

polars/polars-core/src/series/ops/mod.rs, polars/polars-lazy/src/physical_plan/expressions/sort.rs, polars/tests/it/lazy/groupby.rs, polars/tests/it/lazy/mod.rs
=> make sure that sort does not index empty list

py-polars/build.requirements.txt, py-polars/polars/internals/series.py, py-polars/tests/db-benchmark/various.py, py-polars/tests/test_apply.py, py-polars/tests/test_series.py
=> python: improve arithmetic consistency

polars/polars-core/src/chunked_array/ops/explode.rs, polars/tests/it/lazy/groupby.rs
=> fix null in non-fast-explode explode of numeric arrays

polars/polars-lazy/src/logical_plan/builder.rs
=> also expand rename in filters

polars/polars-core/src/chunked_array/bitwise.rs, polars/polars-lazy/src/physical_plan/expressions/ternary.rs, polars/polars-lazy/src/physical_plan/planner.rs, polars/tests/it/lazy/expressions/arity.rs
=> fix when then with literal

polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/frame/mod.rs, polars/tests/it/lazy/projection_queries.rs, py-polars/polars/internals/lazy_frame.py, py-polars/tests/test_categorical.py
=> fix outer join schema

polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/tests/it/lazy/queries.rs
=> fix schemas of groupby rolling/dynamic

polars/polars-core/src/frame/groupby/mod.rs, polars/tests/it/lazy/queries.rs
=> fix div by zero

polars/polars-core/src/frame/groupby/aggregations.rs, py-polars/tests/test_datelike.py
=> fix incorrect match in agg_mean

polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/tests/it/lazy/queries.rs
=> check alias in whole expr on opt

polars/polars-core/src/frame/groupby/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/tests/it/lazy/expressions/apply.rs
=> align groups in binary when they not align

polars/polars-lazy/src/logical_plan/projection.rs, polars/tests/it/lazy/expressions/apply.rs
=> only expand function inputs if wildcard expansion allows it

polars/polars-core/src/frame/groupby/mod.rs, py-polars/tests/test_errors.py
=> throw error on empty keyed groupby

polars/polars-lazy/src/logical_plan/projection.rs, polars/tests/it/lazy/expressions/expand.rs, polars/tests/it/lazy/expressions/mod.rs
=> compare expand_cols by variant not exact datatype

polars/polars-lazy/src/dsl/mod.rs, py-polars/tests/test_exprs.py
=> dot: use apply instead of map

polars/polars-core/src/frame/asof_join/groups.rs, py-polars/tests/test_errors.py
=> error on invalid asof_join by input

polars/polars-core/src/frame/asof_join/groups.rs, py-polars/tests/test_datelike.py, py-polars/tests/test_df.py
=> improve performance of asof_join by equal or more than 2 keys

py-polars/polars/internals/construction.py, py-polars/tests/test_apply.py
=> improve numpy value conversion in apply

py-polars/Cargo.lock, py-polars/src/apply/series.rs, py-polars/tests/test_apply.py
=> handle numpy integers as return values

polars/polars-core/src/series/ops/log.rs, polars/polars-lazy/src/dsl/mod.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/tests/test_exprs.py
=> fix entropy

py-polars/src/apply/series.rs, py-polars/src/conversion.rs, py-polars/src/series.rs, py-polars/tests/test_datelike.py, py-polars/tests/test_df.py
=> python apply can extract anyvalues

py-polars/tests/test_datelike.py
=> python series from timedelta and Duration::to_list

polars/polars-arrow/src/bitmap/mod.rs, polars/polars-arrow/src/bitmap/mutable.rs, polars/polars-arrow/src/lib.rs, polars/polars-arrow/src/prelude.rs, polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/frame/explode.rs, polars/polars-core/src/prelude.rs, polars/polars-core/src/series/implementations/list.rs, polars/polars-core/src/series/series_trait.rs, py-polars/tests/test_df.py
=> fix explode empty lists

polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/planner.rs, polars/tests/it/lazy/groupby.rs
=> Lazy: update schema in explode op

py-polars/src/dataframe.rs
Found a 2x perf improvement in writing csv by using a buffered writer. Use them for all writers.
=> python use buffered writers

py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py
=> Default sample `n` param to 1

polars/polars-time/src/chunkedarray/utf8/mod.rs, polars/polars-time/src/chunkedarray/utf8/strptime.rs
Use the native `strptime` algorithm and fallback to chrono's slower algorithm if polars cannot parse the given `fmt`. 
When polars native parser is used an ~3-5x improvement can be expected.
=> default to native strptime

py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py
=> Raise error in sample() if `n` and `frac` are both passed

polars/polars-arrow/src/data_types.rs, polars/polars-arrow/src/kernels/rolling/no_nulls.rs, polars/polars-arrow/src/kernels/rolling/nulls.rs, polars/polars-arrow/src/lib.rs, polars/polars-core/src/chunked_array/ops/rolling_window.rs, py-polars/polars/internals/expr.py, py-polars/tests/test_series.py
=> Improve rolling agg

polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/mod.rs, py-polars/docs/source/reference/dataframe.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/src/dataframe.rs, py-polars/src/series.rs
=> add estimate_size methods

polars/polars-core/src/chunked_array/random.rs, py-polars/tests/test_df.py, py-polars/tests/test_series.py
=> Remove tests for #3080

nodejs-polars/Cargo.toml, nodejs-polars/package.json
writejson doc fix & read/write avro
=> node release 0.4.1

py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py
Address: https://github.com/pola-rs/polars/issues/2698
=> doc(): to_numpy advice for when working with Utf8

polars/polars-lazy/src/logical_plan/builder.rs, polars/tests/it/lazy/predicate_queries.rs
=> lazy: expand cols in filter

polars/polars-core/src/frame/explode.rs, polars/polars-core/src/prelude.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/executors/melt.rs, polars/polars-lazy/src/physical_plan/planner/lp.rs, polars/polars-lazy/src/tests/queries.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_df.py
=> melt extra arguments

polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/frame/mod.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/docs/source/reference/dataframe.rst, py-polars/polars/internals/frame.py, py-polars/src/dataframe.rs, py-polars/tests/test_df.py
=> DataFrame::partition_by

polars/polars-core/src/chunked_array/ops/any_value.rs, py-polars/src/apply/series.rs, py-polars/src/conversion.rs, py-polars/src/series.rs, py-polars/tests/test_apply.py, py-polars/tests/test_df.py
=> Python: fallback to anyvalue for logical lambda application

polars/polars-lazy/src/frame/mod.rs
Needed clone for lazy group by to be able to represent the value in Nushell
=> derive clone for lazy groupby

py-polars/src/arrow_interop/to_rust.rs
=> python: parallel arrow FFI array conversion

polars/polars-core/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/optimizer/slice_pushdown.rs, polars/polars-lazy/src/logical_plan/options.rs, polars/polars-lazy/src/physical_plan/executors/sort.rs, polars/polars-lazy/src/tests/optimization_checks.rs, py-polars/src/dataframe.rs
=> pushdown slice to sort nodes

polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/tests/it/lazy/projection_queries.rs
=> lazy err on not found col

py-polars/polars/convert.py, py-polars/tests/test_interop.py
Simple Python-only implementation of [#3145](https://github.com/pola-rs/polars/issues/3145#issue-1204920011).
=> Add support for structs to pl.from_dict

polars/polars-core/src/frame/groupby/aggregations.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/datetime.rs, polars/polars-core/src/series/implementations/duration.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/series_trait.rs, py-polars/tests/test_queries.py
=> fix overflow in agg_mean

polars-sql/Cargo.toml, polars/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/series/mod.rs, polars/polars-core/src/series/ops/null.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl/list.rs, py-polars/Cargo.toml, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_exprs.py
Run any expression against the elements of a `List`.
```python
"a": [1, 8, 3],
"b": [4, 5, 2]
})
rank_expr = pl.first().rank()
sdm_expr = pl.first().sum() / pl.first().min()
obs_expr = pl.first().skew() + pl.first().filter(pl.first() != 8).sum()
(df.with_column(
pl.concat_list(["a", "b"]).alias("list")
).select([
pl.all(),
pl.col("list").arr.eval(rank_expr).alias("rank"),
pl.col("list").arr.eval(sdm_expr).alias("sum_div_min").explode(),
pl.col("list").arr.eval(obs_expr).alias("some obscure expr").explode()
]))
```
```
shape: (3, 6)
┌─────┬─────┬────────────┬────────────┬─────────────┬───────────────────┐
│ a   ┆ b   ┆ list       ┆ rank       ┆ sum_div_min ┆ some obscure expr │
│ --- ┆ --- ┆ ---        ┆ ---        ┆ ---         ┆ ---               │
│ i64 ┆ i64 ┆ list …
```
=> list eval expression

polars/polars-core/src/chunked_array/comparison.rs, polars/polars-core/src/series/comparison.rs, py-polars/polars/internals/series.py, py-polars/src/series.rs, py-polars/tests/test_datelike.py, py-polars/tests/test_series.py, py-polars/tests/test_struct.py
=> Python series: min/max logical types

polars/polars-core/src/chunked_array/logical/struct_/mod.rs, py-polars/tests/test_struct.py
=> struct logical type arrow conversion

polars/polars-core/src/chunked_array/comparison.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/ops/unique/rank.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/comparison.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/testing.rs, polars/polars-io/src/tests.rs, polars/polars-lazy/src/dsl/expr.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/tests/optimization_checks.rs, polars/polars-lazy/src/tests/queries.rs, polars/tests/it/lazy/predicate_queries.rs, py-polars/src/series.rs, py-polars/tests/test_df.py, py-polars/tests/test_errors.py, py-polars/tests/test_exprs.py
=> make series comparissons fallible

polars/polars-core/src/chunked_array/logical/struct_/mod.rs, polars/polars-core/src/chunked_array/ops/any_value.rs, polars/polars-core/src/datatypes.rs, polars/polars-core/src/fmt.rs, py-polars/src/apply/mod.rs, py-polars/src/apply/series.rs, py-polars/src/conversion.rs, py-polars/tests/test_interop.py, py-polars/tests/test_struct.py
=> python all anyvalue to python conversion return python types

polars/polars-core/src/series/from.rs, py-polars/src/apply/mod.rs, py-polars/tests/test_struct.py
=> recursively convert arrow

polars/polars-lazy/src/dot.rs, polars/polars-lazy/src/logical_plan/aexpr.rs, polars/tests/it/lazy/predicate_queries.rs
Accumulated filters had O(n^x)
complexity. Don't know how large x was,
but it was big. I think 3-5.
fixes #3210
=> Fix tree traversal complexity

py-polars/polars/internals/series.py
I think these are the only two relevant cases, but please let me know if you spot any more @ritchie46 .
=> Update type hints for Series methods to include datetime types

py-polars/tests/test_df.py, py-polars/tests/test_struct.py
This PR adds some testing for combinations of nested struct and list columns.
=> Adding struct column tests

polars/polars-core/src/series/from.rs, py-polars/tests/test_struct.py
=> struct: handle validity

.github/ISSUE_TEMPLATE/bug_report.md
This should bounce some resolved bug reports.
=> bug template bounce resolved bugs

polars/polars-lazy/src/physical_plan/planner/lp.rs
=> fix partition boundary

polars/polars-core/src/chunked_array/logical/categorical/ops/zip.rs, polars/tests/it/lazy/expressions/arity.rs
=> fix offsets in categorical merge

polars/polars-core/src/series/from.rs, py-polars/polars/utils.py, py-polars/src/conversion.rs, py-polars/src/series.rs, py-polars/tests/test_datelike.py
=> python better datetime.time support

polars/polars-lazy/src/dsl/expr.rs, polars/polars-lazy/src/dsl/function_expr.rs, polars/polars-lazy/src/dsl/functions.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/dsl/string.rs, polars/polars-lazy/src/logical_plan/aexpr.rs, polars/polars-lazy/src/logical_plan/conversion.rs, polars/polars-lazy/src/logical_plan/format.rs, polars/polars-lazy/src/logical_plan/iterator.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/utils.rs, polars/polars-lazy/src/logical_plan/optimizer/slice_pushdown_expr.rs, polars/polars-lazy/src/logical_plan/projection.rs, polars/polars-lazy/src/physical_plan/planner/expr.rs, py-polars/docs/source/reference/expression.rst, py-polars/polars/internals/expr.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_exprs.py
WIP making more function expression serializable and add a `null_count` expression.
=> setup serializable function + null_count expr

polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/tests/aggregations.rs
=> fix skew autoexplode and add test

polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, py-polars/tests/test_lazy.py
=> quantile agg; update grouptuples

polars/polars-io/src/parquet/write.rs, polars/tests/it/io/mod.rs, polars/tests/it/io/parquet.rs
=> do not write empty chunk to parquet

polars/polars-core/src/chunked_array/random.rs
improve sample without replacement performance by 2/2.5 x
=> improve sample_perf

polars/polars-time/src/chunkedarray/utf8/patterns.rs, py-polars/tests/test_datelike.py
=> add iso strptime patterns

polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/csv_core/utils.rs, py-polars/tests/io/test_csv.py
fixes #3166
@ghuls this should open the way to compressed files in lazy.
=> add partial decompression in read_csv

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, py-polars/Cargo.lock
=> upgrade arrow

polars/polars-lazy/src/physical_plan/planner/lp.rs, polars/polars-lazy/src/tests/queries.rs, py-polars/Cargo.lock, py-polars/Cargo.toml
=> python polars 0.13.28

polars/polars-core/src/frame/mod.rs, polars/polars-io/src/csv_core/csv.rs, polars/polars-io/src/lib.rs, polars/polars-io/src/options.rs, polars/polars-io/src/parquet/read_impl.rs, polars/polars-io/src/utils.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/tests/io.rs, polars/polars-lazy/src/tests/optimization_checks.rs, polars/polars-lazy/src/tests/projection_queries.rs
=> fix row count for u64 idx

polars/polars-core/src/chunked_array/builder/list.rs, polars/polars-core/src/frame/row.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/src/conversion.rs, py-polars/src/lib.rs, py-polars/src/prelude.rs, py-polars/src/py_modules.rs, py-polars/tests/test_struct.py
=> recursive list builder in rows

.github/deploy_manylinux.sh, polars/Cargo.toml, polars/polars-core/src/utils/mod.rs, polars/tests/it/io/csv.rs, py-polars/Cargo.toml, py-polars/src/dataframe.rs, py-polars/src/lazy/dataframe.rs, py-polars/src/series.rs
Did not actually release a `bigidx` version of polars. Fixes #3279
=> fix bigidx release

py-polars/Cargo.lock, py-polars/Cargo.toml
=> python polars 0.13.29

.github/deploy_manylinux.sh
@cbilot I think this should make sure we do release the big idx polars next time.
=> sed inplace

.github/workflows/coverage.yaml, polars/Cargo.toml, polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, polars/polars-lazy/Cargo.toml, polars/polars-ops/Cargo.toml, polars/polars-time/Cargo.toml, polars/polars-utils/Cargo.toml, py-polars/Cargo.lock
=> polars 0.21.1

py-polars/polars/internals/construction.py, py-polars/tests/test_interop.py
=> find first non null to determine pandas object type

polars/polars-core/src/utils/mod.rs, polars/polars-lazy/src/dsl/expr.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/tests/it/lazy/groupby.rs, py-polars/polars/internals/lazy_frame.py
Adds partial support for list arithmetic (only in groupby context for now). Closes #3290
=> partial support for list arithmetic

polars/polars-core/src/chunked_array/random.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/physical_plan/executors/groupby_partitioned.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/src/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs
=> shuffle sample option

polars/polars-lazy/src/dsl/function_expr.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/utils.rs, polars/polars-lazy/src/tests/predicate_queries.rs
=> improve predicate pushdown

Makefile
Also include the integration tests in coverage summary.
=> run integration tests in coverage

polars/polars-io/src/csv_core/buffer.rs
=> fix panic in csv parser

polars/Makefile, polars/polars-core/src/chunked_array/object/mod.rs, polars/polars-core/src/frame/row.rs, py-polars/tests/test_datelike.py
=> implement anyvalue -> datatype for all variants

polars/polars-lazy/src/prelude.rs
Serde implementation for these options is required when enabling the serde flag
=> serde for group options

polars/polars-lazy/src/frame/mod.rs, py-polars/tests/test_df.py
=> fix rename same name

polars/polars-core/src/frame/groupby/pivot.rs, polars/tests/it/core/pivot.rs
=> pivot index maintain logical type

polars/polars-core/src/chunked_array/kernels/take.rs, polars/polars-core/src/chunked_array/ops/rolling_window.rs, polars/polars-core/src/series/ops/to_list.rs, polars/polars-core/src/series/unstable.rs, py-polars/tests/test_struct.py
=> use array_ref in favor of chunks

polars/polars-core/src/frame/asof_join/mod.rs, polars/polars-core/src/frame/mod.rs, py-polars/tests/test_df.py
=> rechunk in asof and allow concat to empty df

polars/polars-arrow/src/kernels/take_agg.rs, polars/polars-core/src/frame/groupby/aggregations.rs, polars/polars-core/src/series/comparison.rs, polars/polars-core/src/utils/mod.rs
=> improve overflow of numeric mean

polars/polars-core/src/utils/mod.rs, polars/polars-lazy/src/frame/ipc.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/frame/parquet.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/optimizer/delay_rechunk.rs, polars/polars-lazy/src/logical_plan/optimizer/mod.rs, polars/polars-lazy/src/logical_plan/options.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs
Polars has increase partitioned aggregation functionality. This optimization is a realization that a rechunk before a partitioned groupby is wasteful. This ensures we delay rechunking until we decide if we do a partitioned groupby or not.
=> delay rechunk optimization

polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/frame/mod.rs
=> fix rayon SO in partition_by

py-polars/Cargo.lock, py-polars/Cargo.toml
Patch release for segfault induced by SO in #3390
=> python polars 0.13.33

py-polars/Cargo.lock, py-polars/Cargo.toml
And another patch. 
0.13.32 and 0.13.33 will be yanked and removed.
=> patch python polars 0.13.34

polars/polars-core/src/datatypes.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/polars-lazy/src/physical_plan/expressions/cast.rs, polars/tests/it/lazy/expressions/apply.rs, py-polars/tests/test_queries.py
=> ensure that Cast expressions first updates groups before it flattens

polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/frame/explode.rs, py-polars/tests/test_explode.py
=> fix explode empty df

polars/polars-core/src/chunked_array/builder/list.rs, polars/polars-core/src/chunked_array/list/iterator.rs, polars/polars-core/src/chunked_array/list/namespace.rs, polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/chunked_array/ops/full.rs, polars/polars-core/src/chunked_array/upstream_traits.rs, polars/polars-core/src/named_from.rs, polars/polars-core/src/series/ops/to_list.rs, polars/polars-lazy/src/tests/queries.rs, py-polars/src/apply/dataframe.rs, py-polars/src/apply/mod.rs, py-polars/src/apply/series.rs, py-polars/tests/test_apply.py
If we cannot create a list builder we fall back
on AnyValue's which can handle arbitrary nesting
fixes #3404
=> Python apply -> list

py-polars/Cargo.lock, py-polars/Cargo.toml
An early patch to include the upstream parquet fixes.
=> python polars 0.13.35

polars/Cargo.toml, polars/src/lib.rs
=> feature gate timezones

polars/polars-lazy/src/dsl/eval.rs, py-polars/tests/test_window.py
=> fix cumulative_eval on window expressions

polars/polars-lazy/src/physical_plan/planner/expr.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/tests/test_window.py
Early release because of large perf improvements downstream.
=> python polars 0.13.37

polars/polars-arrow/src/array/list.rs, polars/polars-arrow/src/kernels/take.rs, polars/polars-core/src/chunked_array/builder/list.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/upstream_traits.rs, polars/polars-core/src/frame/groupby/aggregations/agg_list.rs, polars/polars-core/src/named_from.rs, polars/polars-core/src/series/ops/null.rs, polars/polars-ops/src/lib.rs, polars/polars-time/src/lib.rs, polars/polars-utils/src/lib.rs, py-polars/src/conversion.rs, py-polars/tests/test_struct.py
=> infer dtype of empty list in recursive list construction & fix struct.arr take

polars/polars-core/src/chunked_array/logical/struct_/mod.rs, polars/polars-core/src/series/implementations/struct_.rs, polars/polars-ops/src/chunked_array/list/namespace.rs, py-polars/tests/test_struct.py
fixes #3430
I hope we are almost there @cbilot :see_no_evil:
=> fix struct list concat

polars/polars-io/src/csv_core/buffer.rs, py-polars/tests/io/test_csv.py
=> csv parser fallback on chrono if datetime pattern fails

polars/polars-core/src/chunked_array/comparison.rs, py-polars/tests/test_struct.py
=> fix struct equality

polars/polars-core/src/series/any_value.rs, py-polars/src/series.rs, py-polars/tests/test_struct.py
=> Struct error on different dict orders

polars/polars-core/src/chunked_array/logical/struct_/mod.rs, polars/polars-core/src/series/implementations/struct_.rs, py-polars/docs/source/reference/expression.rst, py-polars/polars/__init__.py, py-polars/polars/exceptions.py, py-polars/polars/internals/lazy_functions.py, py-polars/src/error.rs, py-polars/src/lib.rs, py-polars/tests/test_struct.py
=> Struct creations/append/extend stricter schema

py-polars/polars/__init__.py, py-polars/polars/exceptions.py, py-polars/polars/internals/lazy_functions.py, py-polars/src/lib.rs, py-polars/tests/test_errors.py
=> python: expose PanicException

.github/workflows/create-py-mac-universal2-release.yaml, .github/workflows/create-py-release-windows-macos.yaml, .github/workflows/test-python.yaml, .github/workflows/test-windows-python.yaml, Makefile, polars/polars-core/src/lib.rs, polars/polars-lazy/src/logical_plan/format.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/utils.rs, polars/tests/it/lazy/expressions/is_in.rs, polars/tests/it/lazy/expressions/mod.rs, polars/tests/it/lazy/predicate_queries.rs
=> don't allow predicate pushdown if compared column is being coerced

py-polars/polars/internals/frame.py, py-polars/src/file.rs, py-polars/tests/test_df.py
This PR resolves #3432 by catching the original `FileNotFoundError` and reraising it with the file name for context.
=> Improve error message in FileNotFoundError

py-polars/src/apply/series.rs, py-polars/tests/test_apply.py
=> use anyvalue if first apply list result is empty

py-polars/polars/internals/lazy_frame.py, py-polars/tests/test_errors.py
=> python: improve error when passing DataFrame to LazyFrame

polars/polars-core/src/chunked_array/logical/categorical/merge.rs, polars/polars-core/src/chunked_array/logical/categorical/ops/append.rs, polars/polars-core/src/chunked_array/logical/categorical/ops/zip.rs, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/series/implementations/categorical.rs, py-polars/tests/test_categorical.py
=> make cat merge fallible and loossen restrictions on categorical appends

polars/polars-core/src/chunked_array/temporal/time.rs, polars/polars-core/src/fmt.rs, polars/polars-lazy/src/dsl/string.rs, polars/polars-time/src/chunkedarray/time.rs, py-polars/polars/internals/expr.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_series.py
=> feat: support pl.Time in Series.str.strptime

polars/polars-core/src/series/from.rs, py-polars/tests/test_interop.py
=> support all arrow dictionary keys < 64 bit

polars/polars-core/src/chunked_array/builder/list.rs, polars/polars-core/src/chunked_array/upstream_traits.rs, py-polars/tests/test_lists.py
=> fix aggregation of empty list

polars/polars-core/src/chunked_array/ops/sort/mod.rs, py-polars/tests/test_queries.py
=> fix sorting of chunked numeric arrays

py-polars/tests/test_series.py
=> adjust for kleene logic in drop_na

py-polars/polars/internals/frame.py
Some more examples for the docs :)
=> docs examples

polars/polars-arrow/src/kernels/rolling/no_nulls/min_max.rs, polars/polars-arrow/src/kernels/rolling/no_nulls/variance.rs, polars/polars-arrow/src/kernels/rolling/nulls/mean.rs, polars/polars-arrow/src/kernels/rolling/nulls/min_max.rs, polars/polars-arrow/src/kernels/rolling/nulls/mod.rs, polars/polars-arrow/src/kernels/rolling/nulls/sum.rs, polars/polars-arrow/src/kernels/rolling/nulls/variance.rs, polars/polars-arrow/src/trusted_len/mod.rs, polars/polars-core/src/chunked_array/ops/unique/mod.rs, polars/polars-core/src/frame/groupby/aggregations/agg_list.rs, polars/polars-core/src/frame/groupby/aggregations/mod.rs, polars/polars-core/src/frame/groupby/into_groups.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/frame/groupby/proxy.rs, polars/polars-core/src/frame/mod.rs, polars/polars-io/src/partition.rs, polars/polars-lazy/src/physical_plan/expressions/aggregation.rs, polars/polars-lazy/src/physical_plan/expressions/count.rs, polars/polars-lazy/src/physical_plan/expressions/filter.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/physical_plan/expressions/slice.rs, polars/polars-lazy/src/physical_plan/expressions/sort.rs, polars/polars-lazy/src/physical_plan/expressions/take.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, polars/polars-time/Cargo.toml, polars/polars-time/src/groupby/dynamic.rs, polars/polars-time/src/windows/groupby.rs, polars/polars-time/src/windows/test.rs
Fix O(n^2) paths and improve window location computation and parallize that.
=> Improve rolling min max

polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/tests/it/lazy/expressions/window.rs
=> use first series to validate length

polars/polars-core/src/series/mod.rs, polars/polars-core/src/series/ops/round.rs, polars/polars-io/src/csv_core/utils.rs, polars/polars-io/src/ipc.rs, polars/polars-io/src/partition.rs, polars/polars-lazy/src/dsl/mod.rs
Separated the param change; rest are docs-ish
=> Readability Fixes r2

polars/polars-io/src/parquet/write.rs
There is a fix upstream missing, https://github.com/jorgecarleitao/arrow2/pull/1038, and we should be good.
=> Fixed parquet parallel writing

polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/chunkops.rs, polars/polars-core/src/chunked_array/ops/fill_null.rs, polars/polars-core/src/chunked_array/ops/filter.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/chunked_array/trusted_len.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/ops/pct_change.rs, polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/src/dsl/functions.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/tests/queries.rs, polars/polars-time/src/date_range.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/src/conversion.rs, py-polars/src/dataframe.rs, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_df.py
=> fill_null limits

nodejs-polars/__tests__/lazyframe.test.ts, nodejs-polars/polars/functions.ts, nodejs-polars/polars/lazy/dataframe.ts, nodejs-polars/polars/lazy/expr.ts
=> Improve Typescript Readability

py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py
=> Update str replace docs

polars/Cargo.toml, polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/export.rs, polars/polars-io/Cargo.toml, polars/polars-io/src/json.rs, polars/polars-lazy/Cargo.toml, polars/polars-ops/Cargo.toml, polars/polars-time/Cargo.toml, polars/polars-utils/Cargo.toml, py-polars/Cargo.lock, py-polars/src/dataframe.rs, py-polars/src/file.rs
Thanks to great work upstream by @jorgecarleitao  we get ~2x improvement in parsing row oriented json.
=> update arrow to crates.io: `~2x json` parsing improvement

polars/polars-io/src/ipc.rs, polars/polars-lazy/src/logical_plan/optimizer/projection_pushdown.rs, polars/polars-lazy/src/physical_plan/executors/scan.rs, py-polars/tests/io/test_ipc.py
supersedes #3277
fixes #1761
fixes #3590
=> respect ipc column ordering

polars/polars-lazy/src/dsl/string.rs, polars/polars-ops/src/chunked_array/strings/namespace.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_exprs.py
=> zfill expression

polars/polars-core/Cargo.toml, polars/polars-lazy/Cargo.toml
Proofread TOML files; found small changes... didn't want to mix with more `.rs` cleanup.
=> Fix TOML typos

polars/polars-core/src/chunked_array/logical/categorical/builder.rs, polars/polars-lazy/src/dsl/function_expr/is_in.rs, polars/polars-lazy/src/dsl/function_expr/mod.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, py-polars/tests/test_categorical.py
=> cast string to categorical in 'is_in'

polars/polars-core/src/datatypes.rs, py-polars/polars/datatypes.py, py-polars/polars/internals/expr.py, py-polars/src/conversion.rs, py-polars/src/lib.rs, py-polars/tests/test_datelike.py
=> python data type units

polars/polars-core/src/chunked_array/logical/categorical/ops/append.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/append.rs, polars/polars-core/src/frame/explode.rs, polars/polars-lazy/src/dsl/functions.rs, polars/polars-lazy/src/physical_plan/expressions/count.rs, py-polars/tests/test_categorical.py
=> unset sorted metadata on append

nodejs-polars/__tests__/expr.test.ts, nodejs-polars/__tests__/io.test.ts, nodejs-polars/__tests__/serde.test.ts, nodejs-polars/polars/index.ts, nodejs-polars/polars/io.ts, nodejs-polars/src/conversion.rs, nodejs-polars/src/dataframe.rs, nodejs-polars/src/lazy/dataframe.rs, nodejs-polars/src/lazy/dsl.rs
adds a `scanJson` method to allow json sources within the lazyframes.
=> feat(nodejs): scan json

py-polars/Cargo.lock, py-polars/Cargo.toml
=> python polars 0.13.44

polars/polars-lazy/src/dsl/functions.rs, py-polars/tests/test_lists.py
=> fix invalid concat dtype

polars/polars-lazy/src/physical_plan/executors/union.rs, polars/polars-lazy/src/physical_plan/mod.rs
=> restrict parallel branches in lazy Union

py-polars/docs/source/reference/functions.rst, py-polars/polars/__init__.py, py-polars/polars/internals/construction.py, py-polars/polars/utils.py, py-polars/src/lib.rs, py-polars/src/series.rs
Create a `DataFrame` in parallel if all dictionary values are numpy arrays.
=> python dict parallel dataframe creation

polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/tests/io.rs
=> fix row count file projection pushdown

polars/Cargo.toml, polars/Makefile, polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-io/Cargo.toml, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl/functions.rs, polars/polars-ops/Cargo.toml, polars/polars-ops/src/chunked_array/list/namespace.rs, polars/polars-time/Cargo.toml, polars/polars-utils/Cargo.toml, py-polars/Cargo.lock, py-polars/tests/test_lists.py
=> concat list determine supertype

polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/tests/it/lazy/groupby.rs
=> fix groups state in complex aggregation

polars/src/docs/eager.rs, polars/src/docs/lazy.rs, polars/src/lib.rs
=> Rust Comment Readability Fixes

polars/polars-lazy/src/logical_plan/projection.rs, polars/tests/it/lazy/expressions/expand.rs, py-polars/polars/__init__.py, py-polars/polars/internals/lazy_functions.py, py-polars/src/conversion.rs, py-polars/src/lib.rs, py-polars/tests/test_datelike.py
=> improve dtype selection

polars/polars-core/src/chunked_array/bitwise.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/src/logical_plan/builder.rs, py-polars/polars/internals/__init__.py, py-polars/polars/internals/datatypes.py, py-polars/polars/internals/lazy_functions.py, py-polars/tests/test_df.py, py-polars/tests/test_exprs.py
=> accept regex in filter

polars/polars-core/src/frame/row.rs, py-polars/polars/convert.py, py-polars/polars/internals/frame.py, py-polars/src/apply/dataframe.rs, py-polars/src/dataframe.rs
=> Python: infer_schema_len arg to from_dicts

py-polars/polars/internals/__init__.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/io.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/io.py, py-polars/tests/io/test_csv.py, py-polars/tests/io/test_ipc.py, py-polars/tests/io/test_parquet.py
=> python: fix and test globbing

py-polars/polars/string_cache.py
=> Fix StringCache docstring typo

polars/polars-core/src/frame/groupby/into_groups.rs, py-polars/tests/test_groupby.py
=> fix oob in sorted groupby

py-polars/polars/internals/expr.py
Wondering if 
> The hash value is of type Datetime
should be
> The hash value is of type UInt64
=> Add pl.Expr.hash Python example

polars/polars-core/src/series/ops/unique.rs, py-polars/tests/test_datelike.py
=> unique counts for logical types

polars/polars-lazy/src/physical_plan/expressions/mod.rs
This improves performance of creation of the literal state in groupby aggregations.
=> Improve lit agg

py-polars/CHANGELOG.md, py-polars/src/dataframe.rs, py-polars/src/series.rs
Final small cleanup items in `py-polars`
=> docs: Readability improvements in `py-polars`

polars/polars-core/src/chunked_array/logical/categorical/builder.rs, polars/polars-core/src/frame/row.rs, py-polars/src/lib.rs
=> Python: parallel concat df

polars/polars-arrow/Cargo.toml, polars/polars-core/Cargo.toml, polars/polars-core/src/functions.rs, polars/polars-io/Cargo.toml, py-polars/Cargo.lock, py-polars/tests/test_strings.py
=> format empty df

polars/polars-time/src/groupby/dynamic.rs, py-polars/tests/test_datelike.py
=> fix rolling groupby ordering with 'by' argument

polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/physical_plan/executors/groupby.rs, polars/polars-lazy/src/physical_plan/executors/groupby_dynamic.rs, polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/tests/it/lazy/groupby.rs
=> allow literal as aggregation

polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/chunked_array/ops/bit_repr.rs, polars/polars-core/src/chunked_array/ops/mod.rs, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/series/from.rs, polars/polars-core/src/vector_hasher.rs, py-polars/tests/test_joins.py
=> fix join negative keys

py-polars/polars/internals/construction.py, py-polars/tests/test_interop.py
=> fix from_pandas object null array

polars/polars-lazy/src/physical_plan/expressions/binary.rs, py-polars/tests/test_queries.py
=> fix aritmetic bug introduced in #3709

polars/polars-arrow/src/data_types.rs, polars/polars-core/src/chunked_array/ops/sort/argsort.rs, polars/polars-core/src/chunked_array/ops/sort/argsort_multiple.rs, polars/polars-core/src/chunked_array/ops/sort/mod.rs, py-polars/tests/test_sort.py
=> check nan in sort by single column

py-polars/src/lib.rs, py-polars/tests/test_queries.py
=> python fix concat

nodejs-polars/polars/index.ts
add a global "private" variable when importing polars. (this is helpful for external libraries).
=>  add global __pl__

polars/Cargo.toml, polars/polars-core/src/chunked_array/boolean.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/take/take_single.rs, polars/polars-core/src/series/implementations/boolean.rs, polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/Cargo.toml, polars/polars-lazy/src/dsl/function_expr/arg_where.rs, polars/polars-lazy/src/dsl/function_expr/mod.rs, polars/polars-lazy/src/dsl/functions.rs, polars/src/lib.rs, py-polars/Cargo.toml, py-polars/docs/source/reference/functions.rst, py-polars/polars/__init__.py, py-polars/polars/internals/__init__.py, py-polars/polars/internals/functions.py, py-polars/polars/internals/lazy_functions.py, py-polars/polars/internals/series.py, py-polars/src/lib.rs, py-polars/src/series.rs, py-polars/tests/test_df.py
=> `arg_where` expression

polars/polars-lazy/src/dsl/function_expr/mod.rs, polars/polars-lazy/src/dsl/function_expr/strings.rs, polars/polars-lazy/src/dsl/string.rs, polars/polars-ops/src/chunked_array/strings/namespace.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_strings.py
Specialized functions are faster than contains.
=> str.ends_with/ str.starts_with

polars/polars-time/src/windows/test.rs, polars/polars-time/src/windows/window.rs
=> always include offset in groupby_dynamic

polars/polars-io/src/csv_core/csv.rs, py-polars/tests/io/test_csv.py
=> csv don't skip delimiter in whitespace trimming

polars/polars-core/src/chunked_array/arithmetic.rs, polars/polars-core/src/chunked_array/cast.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/chunkops.rs, polars/polars-core/src/chunked_array/ops/filter.rs, polars/polars-core/src/chunked_array/ops/take/mod.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/frame/groupby/proxy.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/implementations/boolean.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/implementations/dates_time.rs, polars/polars-core/src/series/implementations/datetime.rs, polars/polars-core/src/series/implementations/duration.rs, polars/polars-core/src/series/implementations/floats.rs, polars/polars-core/src/series/implementations/list.rs, polars/polars-core/src/series/implementations/mod.rs, polars/polars-core/src/series/implementations/utf8.rs, polars/polars-core/src/series/mod.rs, polars/polars-core/src/series/series_trait.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-time/Cargo.toml, polars/tests/it/core/groupby.rs, py-polars/src/series.rs, py-polars/tests/test_datelike.py
=> don't copy the sorted flag on many operations

polars/polars-lazy/src/dsl/dt.rs, polars/polars-time/src/chunkedarray/date.rs, polars/polars-time/src/chunkedarray/datetime.rs, polars/polars-time/src/chunkedarray/mod.rs, polars/polars-time/src/series/mod.rs, py-polars/docs/source/reference/expression.rst, py-polars/docs/source/reference/series.rst, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/tests/test_datelike.py
=> quarter expression

polars/polars-time/src/groupby/dynamic.rs, py-polars/tests/test_datelike.py
=> rolling groupby fix index column output order

polars/polars-core/src/frame/asof_join/mod.rs, py-polars/tests/test_joins.py
=> fix join asof on floats

polars/polars-core/src/frame/asof_join/asof.rs, polars/polars-core/src/frame/asof_join/groups.rs, polars/polars-core/src/frame/from.rs, polars/polars-core/src/frame/groupby/aggregations/mod.rs, polars/polars-core/src/frame/groupby/mod.rs, polars/polars-core/src/frame/mod.rs
Readability improvements in the `/polars/polars-core/src/frame/` path.
- `left_catched_up` -> `left_caught_up`
- Various comments and a stderr typo fixed
=> chore: `/polars/polars-core/src/frame/` readability

polars/polars-core/src/frame/asof_join/groups.rs, py-polars/tests/test_joins.py
=> fix join asof tolerance

polars/polars-core/src/series/any_value.rs
=> from anyvalue for small integers

polars/polars-core/src/frame/mod.rs, py-polars/tests/test_datelike.py
=> fix sorted unique

polars/polars-lazy/src/physical_plan/expressions/mod.rs, polars/polars-lazy/src/physical_plan/expressions/ternary.rs, polars/polars-lazy/src/tests/aggregations.rs, polars/tests/it/lazy/groupby.rs
=> fix ternary groupby `agg_list`/`not_aggregated` combination

polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/physical_plan/expressions/ternary.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, py-polars/tests/db-benchmark/various.py
=> don't cache in-expression window functions

py-polars/polars/utils.py, py-polars/tests/test_datelike.py
=> python: fix time conversion

py-polars/polars/datatypes.py, py-polars/polars/exceptions.py
Just a small thing I noticed while going through the code base: a bunch of unnecessary pass statements.
Decided to create this small PR to do my scroll wheel a favor.
=> Concise empty class syntax

polars/polars-lazy/src/physical_plan/expressions/take.rs, py-polars/tests/test_groupby.py
=> fix groups after take expression

polars/polars-lazy/src/logical_plan/optimizer/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, py-polars/tests/test_lazy.py
=> fix predicate pushdown in union + count expression

polars/polars-lazy/src/physical_plan/executors/join.rs, polars/polars-lazy/src/physical_plan/executors/union.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, polars/polars-lazy/src/physical_plan/state.rs
=> add join/union branch in window cache keys

polars/polars-io/src/parquet/read.rs, polars/polars-io/src/parquet/read_impl.rs, polars/polars-lazy/src/physical_plan/executors/scan/parquet.rs, py-polars/tests/io/test_parquet.py
=> parquet read: fix remaining_rows counter

polars/polars-time/src/windows/groupby.rs, py-polars/tests/test_groupby.py
=> fix negative offset in groupby_rolling

polars/polars-lazy/src/logical_plan/lit.rs
As per the discussion on discord, I've added an impl to convert `AnyValue` into a `Literal`. I've tried to make sensible decisions if variants didn't have a clear analogue but am open to change them if people think they should be done differently. Also clippy did have some complaints but not about any of the code that I touched so I decided not to mess with it. Hopefully this will be an easy merge.
=> add impl from anyvalue for literal

polars/polars-lazy/src/physical_plan/expressions/binary.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, polars/tests/it/lazy/expressions/arity.rs
=> fix window expression case

polars/polars-core/src/chunked_array/ops/mod.rs, py-polars/polars/internals/series.py, py-polars/tests/test_datelike.py, py-polars/tests/test_interop.py
=> fix oob panic on expand_at_index and series from pyarrow chunkedarray

polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/tests/it/lazy/predicate_queries.rs
=> block equality/ordering based predicates on null producing joins

polars/polars-core/src/series/from.rs, py-polars/tests/io/test_ipc.py
=> upcast float16 to float32

py-polars/polars/internals/series.py, py-polars/tests/test_series.py
=> python: fix already mutable borrowed append

py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py
=> python: loossen truncate sorted restriction in docstring

polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/tests/it/lazy/expressions/apply.rs
=> groupby apply: use inner type to infer dtype

polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs
```python
df = (
pl.scan_parquet("df.parquet")
.filter(pl.col("dt") >= "2020-04-01")
).collect()
```
Will warn with:
```
Warning: Comparing date/datetime/time column to string value, this will lead to string comparison and is unlikely what you want.
If this is intended, consider using an explicit cast to silence this warning.
```
See: #3964 and #3965
=> implicit datelike string comparison warning

polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, polars/tests/it/lazy/predicate_queries.rs
=> fix count union predicate

polars/polars-core/src/frame/cross_join.rs, polars/polars-core/src/frame/mod.rs, polars/polars-core/src/utils/mod.rs
=> fix accidentally slow cross join

polars/polars-lazy/src/dsl/functions.rs, polars/polars-lazy/src/frame/mod.rs, py-polars/tests/io/test_parquet.py
=> ensure main lazyframe gets file cache opt state

polars/tests/it/io/csv.rs, polars/tests/it/lazy/explodes.rs, polars/tests/it/lazy/expressions/window.rs
Tiny fixes in `polars/tests`. 
Running out of these! Going to have to start tackling some functional things soon :)
=> chore(tests): small readability fixes

polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/frame/explode.rs, polars/polars-core/src/series/comparison.rs, polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, py-polars/tests/test_explode.py
=> fix explode offsets for empty lists

polars/polars-io/src/csv_core/buffer.rs, py-polars/src/lib.rs, py-polars/src/series.rs, py-polars/src/utils.rs, py-polars/tests/io/test_csv.py, py-polars/tests/test_apply.py
=> Date encode types

py-polars/polars/internals/frame.py, py-polars/polars/io.py, py-polars/tests/io/test_parquet.py
=> python: fix pyarrow imports

polars/polars-lazy/src/logical_plan/aexpr.rs, py-polars/tests/test_schema.py
=> fix lazy schema

py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/functions.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/internals/series.py, py-polars/polars/io.py
The sprint continues!
**MWE**
* `ljust` / `rjust`
* `cleared` / `clone`
**Others**
* Fix the MWE for `pl.DataFrame.hash_rows` (the method is not named `hash()`)
* I also reworked the `date_range()` MWE, shortened the example output a little while still conveying the same amount of educational information.
* Added internal links in the docstrings among `fetch`, `head`, `limit`, `collect`, etc.
=> docs: add mwe and internal links

polars/polars-core/src/chunked_array/builder/boolean.rs, polars/polars-core/src/chunked_array/builder/utf8.rs, polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-lazy/src/dsl/struct_.rs, py-polars/tests/test_struct.py
=> impl explode for nested lists

polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/tests/tpch.rs, py-polars/polars/internals/lazy_frame.py, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_sort.py
=> allow nulls last in sort by expressions

py-polars/Cargo.lock, py-polars/Cargo.toml
patch release 0.13.53 because of some regressions
=> python polars 0.13.54

polars/polars-core/src/frame/mod.rs, polars/polars-io/src/parquet/read_impl.rs
=> parquet: stop reading when slice is reached

polars/polars-core/src/frame/cross_join.rs, py-polars/tests/db-benchmark/various.py
Fixes silly mistake in cross join. This will be patched today.
=> fix cross join

polars/polars-core/src/chunked_array/logical/categorical/mod.rs, polars/polars-core/src/chunked_array/logical/categorical/ops/append.rs, polars/polars-core/src/chunked_array/logical/categorical/ops/full.rs, polars/polars-core/src/chunked_array/logical/categorical/ops/unique.rs, polars/polars-core/src/chunked_array/logical/categorical/ops/zip.rs, polars/polars-core/src/chunked_array/ops/any_value.rs, polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/chunked_array/ops/sort/categorical.rs, polars/polars-core/src/frame/groupby/pivot.rs, polars/polars-core/src/frame/hash_join/mod.rs, polars/polars-core/src/series/from.rs, polars/polars-core/src/series/implementations/categorical.rs, polars/polars-core/src/series/into.rs, py-polars/tests/test_df.py, py-polars/tests/test_pivot.py
=> pivot: fix categorical logicaltype

polars/polars-lazy/src/dsl/function_expr/fill_null.rs, polars/polars-lazy/src/dsl/function_expr/mod.rs, polars/polars-lazy/src/dsl/function_expr/row_hash.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, py-polars/tests/test_schema.py
=> fill_null expr: ensure minimal supertype

py-polars/polars/internals/lazy_frame.py, py-polars/tests/test_lazy.py
=> Add lazy() method to LazyFrame

polars/polars-core/src/config.rs, polars/polars-core/src/fmt.rs, polars/polars-core/src/lib.rs
=> dataframe display: use POLARS_FMT_STR_LEN

polars/polars-core/src/series/ops/unique.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-ops/src/series/_trait.rs, polars/polars-ops/src/series/ops/mod.rs, polars/polars-ops/src/series/ops/various.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py, py-polars/src/lazy/dsl.rs, py-polars/src/series.rs, py-polars/tests/test_struct.py
=> value_counts add sorted argument

polars/polars-core/src/chunked_array/ops/explode.rs, polars/polars-core/src/frame/row.rs, polars/polars-core/src/series/any_value.rs, py-polars/src/arrow_interop/to_rust.rs, py-polars/tests/test_explode.py
=> fix explode with empty lists

polars/polars-core/src/chunked_array/ops/unique/rank.rs, py-polars/tests/test_exprs.py
=> fix so rank

polars/polars-core/src/chunked_array/ops/chunkops.rs, polars/polars-core/src/chunked_array/ops/explode.rs, py-polars/tests/test_explode.py
=> fix explode for sliced arrays

py-polars/polars/_html.py
=> python: remove css line for vscode

py-polars/polars/internals/series.py, py-polars/tests/test_df.py, py-polars/tests/test_joins.py
fixes https://stackoverflow.com/questions/73048821/how-to-update-the-polars-dataframe
=> python allow set by string

polars/polars-arrow/src/kernels/float.rs, polars/polars-lazy/src/dsl/mod.rs, py-polars/tests/test_lazy.py
=> `fill_nan` preserve name

polars/polars-core/src/series/implementations/duration.rs, py-polars/tests/test_datelike.py
=> allow summing of duration in selection context

polars/polars-io/src/csv/write_impl.rs, py-polars/tests/io/test_csv.py
=> csv writer quote if string contains new line char

polars/polars-core/src/chunked_array/ops/explode.rs, py-polars/tests/test_explode.py
=> fix explode edge cases

py-polars/docs/source/reference/functions.rst, py-polars/polars/__init__.py, py-polars/polars/internals/__init__.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/functions.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/internals/series.py, py-polars/polars/internals/slice.py, py-polars/tests/test_functions.py
closes #4136 
credits to @cbilot for the implementation.
=> add pl.cut utility

polars/polars-lazy/src/logical_plan/alp.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, py-polars/tests/io/test_lazy_ipc.py
=> ensure stack optimizations run at scan nodes

.github/workflows/test-python.yaml, py-polars/polars/internals/series.py, py-polars/pyproject.toml, py-polars/tests/test_df.py
redo PR to remove rogue parquet file.
=> Mypy disallow untyped calls

polars/polars-core/src/frame/groupby/pivot.rs, py-polars/tests/test_pivot.py
=> pivot fix categorical index

polars/polars-core/src/chunked_array/ops/filter.rs, polars/polars-core/src/chunked_array/ops/is_in.rs, py-polars/tests/test_lists.py
=> add `is_in` for categoricals

polars/polars-core/src/frame/groupby/pivot.rs, py-polars/tests/test_pivot.py
=> pivot: fix logical type of multiple indexes

py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/tests/test_df.py
Fixes #4069
Changes:
* Added a `_comp` method and all comparison dunders to `DataFrame`, in a similar fashion to `Series`.
* Added tests
Notes:
* Do we need something similar for `LazyFrame`?
=> Dataframe equality

polars/polars-lazy/src/dot.rs, polars/polars-lazy/src/frame/mod.rs, polars/polars-lazy/src/logical_plan/builder.rs, polars/polars-lazy/src/logical_plan/mod.rs, polars/polars-lazy/src/tests/queries.rs, py-polars/Cargo.toml, py-polars/src/lazy/dataframe.rs, py-polars/tests/test_errors.py
=> throw error on schema failure

polars/polars-lazy/src/physical_plan/executors/stack.rs, py-polars/tests/test_schema.py
=> with_columns update on duplicates

polars/polars-lazy/src/dsl/functions.rs, polars/polars-lazy/src/utils.rs, py-polars/tests/test_expr_multi_cols.py
=> fold regex expand

polars/polars-core/src/frame/groupby/proxy.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, py-polars/tests/test_window.py
=> window functions: sort cached groups if needed

polars/polars-core/src/chunked_array/ops/explode.rs, py-polars/tests/test_explode.py
=> fix utf8 explode for nulls and empty strings

polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, py-polars/tests/test_lazy.py
=> type-coercion: ignore unknown untill replaced

polars/polars-io/src/csv/parser.rs, polars/polars-io/src/csv/read.rs, polars/polars-io/src/csv/read_impl.rs, polars/tests/it/io/csv.rs, py-polars/tests/io/test_csv.py
=> csv: ignore quoted lines in skip lines

polars/polars-io/src/json.rs
=> use native ndjson reader

polars/polars-lazy/src/logical_plan/aexpr.rs, py-polars/tests/test_struct.py
=> use default context for col upstream col expression type

polars/polars-time/src/chunkedarray/datetime.rs, polars/polars-time/src/chunkedarray/kernels.rs, py-polars/tests/test_datelike.py
=> ensure weekday starts at 0

py-polars/polars/internals/frame.py, py-polars/polars/internals/series.py, py-polars/src/lazy/apply.rs, py-polars/src/lazy/dsl.rs, py-polars/tests/test_df.py, py-polars/tests/test_errors.py
=> python: improve error

py-polars/polars/internals/lazy_frame.py
=> python: ensure utf8 encoding when writing dot file

polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/chunked_array/ops/aggregate.rs, polars/polars-core/src/chunked_array/ops/take/take_single.rs, polars/polars-core/src/frame/groupby/aggregations/mod.rs, polars/polars-core/src/utils/mod.rs, polars/polars-lazy/src/physical_plan/planner/expr.rs, py-polars/tests/test_sort.py
=> fast path for sorted min/max

polars/polars-core/src/datatypes/mod.rs, polars/polars-lazy/src/dsl/function_expr/mod.rs, polars/polars-lazy/src/dsl/function_expr/shift_and_fill.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/polars-lazy/src/physical_plan/expressions/ternary.rs, polars/polars-lazy/src/tests/queries.rs, polars/polars-lazy/src/utils.rs, polars/tests/it/lazy/expressions/arity.rs
=> improve strictness/consistency of when then otherwise

polars/polars-lazy/src/dsl/function_expr/mod.rs, py-polars/tests/test_schema.py
=> correct dtype for power

polars/polars-io/src/csv/buffer.rs, polars/polars-io/src/csv/read.rs, polars/polars-time/src/chunkedarray/utf8/infer.rs, py-polars/tests/io/test_csv.py
=> csv: improve data/datetime/bool overwrite

polars/polars-core/src/utils/mod.rs, py-polars/tests/test_schema.py
=> fix boolean/numeric supertypes

polars/polars-lazy/src/physical_plan/expressions/cast.rs, py-polars/tests/test_categorical.py
=> cast null to categorical

polars/polars-core/src/frame/groupby/into_groups.rs, polars/polars-core/src/vector_hasher.rs, polars/polars-time/src/groupby/dynamic.rs, py-polars/Cargo.lock, py-polars/tests/test_queries.py
=> fix groups edge case

py-polars/Cargo.lock, py-polars/Cargo.toml
=> python polars 0.13.61

polars/polars-core/src/chunked_array/ops/compare_inner.rs, polars/polars-core/src/chunked_array/ops/take/take_random.rs
=> fix large idx take chunked

polars/polars-lazy/src/frame/ipc.rs, polars/polars-lazy/src/frame/parquet.rs, py-polars/tests/io/test_lazy_ipc.py, py-polars/tests/io/test_lazy_parquet.py
=> ensure schema update of row_count arguments

polars/Cargo.toml, polars/polars-core/src/chunked_array/ops/bit_repr.rs, polars/polars-core/src/frame/groupby/into_groups.rs, polars/polars-core/src/vector_hasher.rs, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/tests/test_joins.py
Specialize for i8, u8, i16, u16 if `feature="performant"` is activated.
=> Specialize groupby

polars/polars-lazy/src/logical_plan/alp.rs, py-polars/Cargo.lock, py-polars/Cargo.toml, py-polars/tests/test_joins.py
=> python polars 0.13.62 

polars/polars-core/src/frame/groupby/mod.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/physical_plan/expressions/apply.rs, polars/polars-lazy/src/physical_plan/expressions/group_iter.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, py-polars/polars/internals/expr.py, py-polars/tests/test_window.py
=> fix window functions of list datatypes

py-polars/polars/datatypes.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/tests/test_df.py
=> Revert generic LazyFrame

py-polars/polars/internals/construction.py, py-polars/polars/internals/expr.py, py-polars/tests/test_constructors.py, py-polars/tests/test_lazy.py
=> python: deprecate calling comparisson functions directly

py-polars/polars/internals/frame.py
This one snuck in between rebases of #4309 and #4229 , I believe.
=> fix: flake8 import error

py-polars/polars/convert.py, py-polars/polars/datatypes_constructor.py, py-polars/polars/internals/anonymous_scan.py, py-polars/polars/internals/construction.py, py-polars/polars/internals/expr.py, py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/polars/internals/lazy_functions.py, py-polars/polars/internals/series.py, py-polars/polars/io.py, py-polars/polars/testing.py, py-polars/polars/utils.py, py-polars/pyproject.toml, py-polars/tests/run_doc_examples.py, py-polars/tests/test_apply.py, py-polars/tests/test_cfg.py, py-polars/tests/test_df.py, py-polars/tests/test_interop.py, py-polars/tests/test_joins.py, py-polars/tests/test_lazy.py, py-polars/tests/test_series.py, py-polars/tests/test_struct.py
#4052 is probably rather stale after my MR removing generic `LazyFrame`. @zundertj still deserves credit though, so to be clear this is co-authored by @zundertj.
Link #4044
=> Turn on `disallow-any-generics`

polars/benches/groupby.rs, polars/polars-core/src/chunked_array/mod.rs, polars/polars-core/src/functions.rs, polars/polars-core/src/utils/mod.rs, polars/polars-lazy/src/dsl/functions.rs, polars/polars-lazy/src/tests/arity.rs, py-polars/polars/internals/lazy_functions.py, py-polars/src/lib.rs, py-polars/tests/db-benchmark/main.py, py-polars/tests/test_functions.py
=> handle null values in correlation

polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs
=> allow compilation with only 'is_in' feature

py-polars/polars/internals/frame.py, py-polars/polars/internals/lazy_frame.py, py-polars/tests/test_df.py
make `groubpy_dynamic` default to left closed window. This is similar to what users of pandas are used to.
=> python: groupby_dynamic closed left

polars/polars-core/src/utils/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/tests/it/lazy/queries.rs
=> ignore unknown supertype

polars/polars-lazy/src/physical_plan/expressions/window.rs, polars/polars-utils/src/sort.rs, py-polars/tests/test_window.py
=> fix sorted window expression

polars/polars-time/src/windows/duration.rs, py-polars/polars/internals/expr.py, py-polars/polars/internals/series.py
=> Panic if a Duration string has multiple minus signs

polars/polars-arrow/src/kernels/list.rs, polars/polars-core/src/chunked_array/ops/sort/mod.rs, polars/polars-lazy/src/dsl/eval.rs, polars/polars-lazy/src/dsl/function_expr/list.rs, polars/polars-lazy/src/dsl/function_expr/mod.rs, polars/polars-lazy/src/dsl/function_expr/temporal.rs, polars/polars-lazy/src/dsl/functions.rs, polars/polars-lazy/src/dsl/list.rs, polars/polars-lazy/src/dsl/mod.rs, polars/polars-lazy/src/logical_plan/optimizer/type_coercion.rs, polars/polars-lazy/src/physical_plan/expressions/window.rs, polars/polars-lazy/src/tests/tpch.rs, polars/polars-ops/src/series/implementations/time.rs, polars/tests/it/lazy/expressions/expand.rs
Remove a lot of unused imports & properly feature flag other imports.
=> Housekeeping - clean up feature flags & compiler warnings

polars/polars-core/src/chunked_array/ops/unique/mod.rs, py-polars/tests/test_exprs.py
=> fix stackoverflow in unique of empty series

polars/polars-lazy/src/physical_plan/expressions/sortby.rs, py-polars/tests/test_groupby.py
=> fix[expr]: sort_by ensure groups are synced

polars/polars-lazy/src/logical_plan/optimizer/predicate_pushdown/mod.rs, py-polars/tests/test_filter.py
=> fix[rust]: melt default value name was wrong in predicate pushdown

polars/polars-core/src/frame/mod.rs, py-polars/tests/test_groupby.py
=> fix[rust]: fix unique order on 'last' keep setting

polars/polars-core/src/frame/mod.rs, polars/polars-core/src/series/ops/null.rs, py-polars/tests/test_lists.py
=> fix[rust]: fix `Series::full_null` for list dtype

polars/polars-arrow/src/kernels/rolling/no_nulls/variance.rs
=> fix[rust]: improve numeric stability of rolling variance

polars/polars-lazy/src/dsl/mod.rs, py-polars/tests/test_expr_multi_cols.py
=> fix[rust]: argsort argument expansion fixed
