pola-rs/polars

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/io/test_parquet.py

fix(python): fix import error when writing parquet with pyarrow

---

.github/ISSUE_TEMPLATE/bug_report_python.yml
polars/polars-lazy/polars-plan/src/dsl/function_expr/range.rs
polars/polars-lazy/polars-plan/src/dsl/functions/index.rs
polars/tests/it/lazy/expressions/apply.rs
py-polars/Cargo.lock
py-polars/polars/dataframe/frame.py
py-polars/polars/functions/range.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/series.py
py-polars/polars/utils/various.py
py-polars/src/functions/range.rs

Changes:
* Add `dtype` argument for `int_range`. Right now it's just a cast after the fact - but I will try to implement this later such that the Series gets materialized in the right data type.
* Use `int_range` instead of `arange` internally.
* Update `arange` docs with a proper deprecation message and "See Also" section.

refactor(python,rust): More cleanup around `arange`

---

polars/polars-arrow/src/kernels/time.rs
polars/polars-core/src/chunked_array/temporal/datetime.rs
py-polars/Cargo.lock

I find the way it's currently written is quite confusing, as `from_tz` and `to_tz` are swapped

chore(rust): unswap from_tz and to_tz in replace_timezone

---

polars/polars-ops/src/series/ops/various.rs
py-polars/Cargo.lock
py-polars/src/series/mod.rs

This will check sortedness without sorting the entire series even when no flag is set. Seems faster.

perf(rust, python): Faster is_sorted when no flag set

---

polars/polars-core/src/schema.rs
py-polars/tests/unit/test_schema.py

Closes #9751.
Supertype detection was inadvertently order-dependent.
(eg: we would spot if B was a supertype of A, but not if A was a supertype of B).

fix(rust,python): fix supertype detection

---

py-polars/polars/selectors.py
py-polars/tests/unit/test_selectors.py

* Adds a new `duration` selector with the same `time_unit` filtering options as `datetime`.
* Improves `SelectorType` definition for selector-function typing.
* New unit tests.

feat(python): add new `duration` selector and improve selector typing

---

py-polars/polars/dataframe/frame.py

Closes #9774.
Add a little more information in the `Notes` section of functions that may truncate from `ns → μs` precision on export from Polars to Python.

docs(python): improve note about the behaviour when converting from ns-precision temporal values to python-native types

---

py-polars/polars/dataframe/frame.py
py-polars/requirements-dev.txt
py-polars/tests/unit/io/test_database.py

Closes #9548.
* Fixes use of db schema with table names when using the sqlalchemy engine (eg: `schema_name.table_name`).
* Fixes use of quoted table names when using the sqlalchemy engine (eg: `schema_name."table-name"`).
* Handles independently quoted schema / table name (eg: `"schema_name"."table-name"`).
* Adds new `sqlalchemy` engine unit test coverage for all of the above.

fix(python): improve/fix `write_database` handling of db schema and quoted table names

---

polars/polars-sql/src/sql_expr.rs
polars/polars-sql/tests/simple_exprs.rs
py-polars/tests/unit/test_sql.py

Adds SQL type support for Binary dtype, and recognition of additional PostgreSQL type strings such as `double precision` (Float64) and `character varying` (Utf8).
The following now works:
```python
"colx": [1, 2, 3],
"coly": ["a", "b", "c"],
})
with pl.SQLContext( df=df, eager_execution=True ) as ctx:
"""
SELECT
CAST(colx AS DOUBLE PRECISION) AS x_float,
coly::varbinary AS y_binary,
FROM df
"""
)
res.to_dict(False)
```

feat(python,rust,cli): add SQL support for binary data and expand recognised SQL dtype strings

---

polars/polars-sql/src/functions.rs
py-polars/tests/unit/test_sql.py

* Adds support for SQL `SUBSTR` function.
* Adds some unit test coverage for the same.
* Adds `visit_ternary` for this and other funcs that need more than unary/binary (not sure if there are any SQL funcs that require more - if so we may want to revisit and add some kind of n-ary support; for now this appears sufficient 🤔)

feat(python,rust,cli): add support for SQL `SUBSTR` function

---

polars/polars-lazy/src/dsl/list.rs
py-polars/tests/unit/datatypes/test_categorical.py

Just something that popped up during some work I was doing. Let me know if my tags are wrong - wasn't sure where to put them.

chore(python, rust): Remove stray `arr.eval` references

---

polars/polars-lazy/polars-plan/src/dsl/function_expr/temporal.rs
polars/polars-time/src/windows/duration.rs
py-polars/tests/unit/namespaces/test_datetime.py

Example of the issue:
```python
In [22]: ser = pl.date_range(datetime(2020, 10, 25), datetime(2020, 10, 25, 3), '30m', time_zone='Europe/London', eager=True)
In [23]: ser.dt.offset_by('1d')
Out[23]:
shape: (9,)
Series: 'date' [datetime[μs, Europe/London]]
[
2020-10-26 00:00:00 GMT
2020-10-26 00:30:00 GMT
2020-10-26 01:00:00 GMT
2020-10-26 01:30:00 GMT
2020-10-26 01:00:00 GMT
2020-10-26 01:30:00 GMT
2020-10-26 02:00:00 GMT
2020-10-26 02:30:00 GMT
2020-10-26 03:00:00 GMT
]
In [24]: ser.dt.offset_by('1d').flags  # SORTED_ASC should not be set here
Out[24]: {'SORTED_ASC': True, 'SORTED_DESC': False}
```

fix(rust, python): dont preserve sortedness in offset_by for tz-aware non-constant durations

---

polars/polars-lazy/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs
py-polars/tests/unit/streaming/test_streaming.py

Related to https://github.com/pola-rs/polars/issues/9122
Changes:
* Refactor the failing test ~and run all OOC tests on one worker~.
* Comment out a Rust test that doesn't compile. See issue https://github.com/pola-rs/polars/issues/9828 for followup.

test(python,rust): Refactor failing test

---

polars/polars-sql/src/functions.rs
py-polars/tests/unit/test_sql.py

Adds SQL support for the string `left` function, and associated unit tests.
```python
"scol": ["abcde", "abc", "a", None],
})
'SELECT scol, LEFT(scol,2) AS "scol:left2" FROM frame',
).collect()
```

feat(rust,python,cli): add `LEFT` string function for SQL

---

polars/polars-lazy/src/physical_plan/streaming/convert_alp.rs
py-polars/tests/unit/streaming/test_streaming.py

fix(rust, python): don't go into streaming engine when groupby by list

---

polars/polars-row/src/encode.rs
polars/polars-row/src/variable.rs
py-polars/src/conversion.rs

We use a block size of 32 bytes in our row-encoding. By accident we overwrote the final block if `size % 32 == 0`. This ensures we don't.
fixes #9837

fix(rust, python): fix row-encode of 32 byte payloads

---

polars/Cargo.toml
polars/polars-lazy/Cargo.toml
polars/polars-lazy/polars-plan/Cargo.toml
polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
polars/polars-lazy/polars-plan/src/dsl/mod.rs
polars/polars-ops/Cargo.toml
polars/polars-ops/src/series/ops/mod.rs
polars/polars-ops/src/series/ops/rle.rs
py-polars/Cargo.toml
py-polars/docs/source/reference/expressions/modify_select.rst
py-polars/docs/source/reference/series/modify_select.rst
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/src/expr/general.rs

Adds rle and rleid.
Closes https://github.com/pola-rs/polars/issues/9328

feat(rust, python): Add Run-length Encoding functions

---

py-polars/docs/source/conf.py

Closes #9399.
Digging around in the Sphinx docs led me to `logo_url`, and then onto the pydata-specific `link`[^1] which actually worked, so we can now repoint the page reached when clicking the top-left titlebar logo to the _actual_ API reference landing page instead of the dead-end/empty index page..
* Before: https://pola-rs.github.io/polars/py-polars/html/index.html
* After: https://pola-rs.github.io/polars/py-polars/html/reference/index.html
Also: minor refactor to pull-out the various website root paths into top-level constants:
```python
static_assets_root = "https://raw.githubusercontent.com/pola-rs/polars-static/master"
github_root = "https://github.com/pola-rs/polars"
web_root = "https://pola-rs.github.io"
```
[^1]: Customize logo link: …

docs(python): add logo `link` entry to sphinx conf and factor-out website root paths

---

py-polars/Cargo.lock
py-polars/src/conversion.rs

See https://docs.rs/pyo3/latest/pyo3/macro.intern.html

perf(python): Use `pyo3::intern` to avoid needlessly recreating PyString

---

polars/polars-core/src/prelude.rs
polars/polars-error/src/lib.rs
polars/polars-error/src/warning.rs
polars/polars-lazy/polars-plan/src/dsl/string.rs
polars/polars-lazy/src/frame/mod.rs
polars/polars-lazy/src/physical_plan/expressions/mod.rs
py-polars/Cargo.lock
py-polars/Cargo.toml
py-polars/polars/utils/__init__.py
py-polars/polars/utils/various.py
py-polars/src/on_startup.rs

This allows us to raise python warnings on the rust side and they will be silenceable. In a later PR we can follow up supporting different types of warning. I want to have a `PolarsWarning` enum on the rust side that maps to different python warnings.

feat(rust, python): `polars_warn!` macro

---

.github/workflows/lint-rust.yml
Cargo.toml
polars/polars-core/Cargo.toml
py-polars/Cargo.lock

Changes:
* Use wildcards to define workspace members
* Add a missing dev dependency for polars-core
* Update CI so clippy stable runs on `--all-targets`
My goal is to make everything run from the workspace root, but there's still some ways to go for the test suite to behave nicely.

chore(rust): Clean up workspace definition

---

polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/strings.rs
polars/polars-lazy/polars-plan/src/dsl/string.rs
polars/polars-sql/src/functions.rs
py-polars/src/expr/string.rs
py-polars/tests/unit/test_sql.py

Support for SQL string length functions, in terms of both characters (`length`) and bytes (`octet_length`).
Also:
* adds the related functions into `StringNameSpace` on the Rust side.
*  sorts some string function definitions for clarity).
```python
"words": ["Café", None, "東京"],
})
"""
SELECT
words,
LENGTH(words) AS n_chars,
OCTET_LENGTH(words) AS n_bytes
FROM frame
"""
).collect()
```

feat(rust,python,cli): add `LENGTH` and `OCTET_LENGTH` string functions for SQL

---

polars/polars-core/src/chunked_array/logical/categorical/builder.rs
polars/polars-lazy/polars-plan/src/dsl/cat.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/cat.rs
py-polars/docs/source/reference/expressions/categories.rst
py-polars/docs/source/reference/series/categories.rst
py-polars/polars/expr/categorical.py
py-polars/polars/series/categorical.py
py-polars/src/expr/categorical.rs
py-polars/tests/unit/namespaces/test_categorical.py

Get the underlying categories of a `Categorical` data type.

feat(rust, python): Expr.cat.get_categories expression

---

polars/polars-core/src/datatypes/dtype.rs

fix(rust, python): fmt unknown dtype

---

polars/polars-sql/src/functions.rs
polars/polars-sql/src/sql_expr.rs
py-polars/tests/unit/test_sql.py

Coming at you from several kilometres up in the skies, somewhere over (I think?) Bosnia... :)
---
Aliases were getting silently eaten when parsing SQL strings to Polars expressions; parsing as `SelectItem` instead of bare `Expr` allows any (optional) aliases to be captured and translated along with the underlying expression itself.
**Before:**
```python
pl.sql_expr( "MIN(a) as min_a" )
```
**After:**
```python
pl.sql_expr( "MIN(a) as min_a" )
```
**Also:**
Recognise `power` as an alias for `pow` ("power" is the usual PostgreSQL syntax, but I believe both are allowed).

fix(python,rust,cli): preserve expression aliases when parsing SQL with `pl.sql_expr`

---

py-polars/polars/functions/lazy.py
py-polars/tests/unit/functions/test_functions.py
py-polars/tests/unit/test_df.py

Just like in https://github.com/pola-rs/polars/pull/9752
Changes:
* Deprecate the functionality for passing Series into `mean`, `head`, etc. Users should simply use Series.mean() and similar.

depr(python): Deprecate functions series input

---

polars/polars-core/src/schema.rs
polars/polars-io/src/json/mod.rs
polars/polars-io/src/ndjson/buffer.rs
polars/polars-io/src/ndjson/core.rs
polars/polars-io/src/utils.rs
polars/polars-lazy/src/physical_plan/executors/scan/ndjson.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/io/json.py
py-polars/polars/io/ndjson.py
py-polars/src/dataframe.rs
py-polars/tests/unit/io/test_json.py

Accept a `schema` and `schema_override` argument and an option to return `null` on failure. 
#9733

feat(rust, python): respect and allow more options in eager json parsing

---

py-polars/polars/functions/lazy.py
py-polars/tests/unit/test_sql.py

Minor update; allows for...
```python
exprs = pl.sql_expr(["POWER(a,a) AS a_a", "CAST(a AS TEXT) AS a_txt"])
```

feat(python): convenience support for parsing a list of SQL strings with `sql_expr`

---

py-polars/polars/dataframe/frame.py
py-polars/polars/series/series.py
py-polars/src/dataframe.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/dataframe/test_vstack.py
py-polars/tests/unit/test_lazy.py

Doing `df.vstack(df)` would lead to a mysterious "RuntimeError: Already mutably borrowed". This handles it nicely.
Changes:
* Remove the mutability requirement from regular `vstack`. This is not required as there is a `clone` on the Rust implementation. This now allows `df.vstack(df)` without problems.
* Added a try/catch for the in-place variant. If we get the "already mutably borrowed" message, we add a `.clone()` on the input. This is the same strategy as employed in `Series.append`. _(An alternative strategy would be to throw a better error message here.)_
* Renamed the input parameter `df` to `other`, to be more consistent with similar methods.

fix(python): Handle `DataFrame.vstack` stacking itself

---

py-polars/polars/functions/aggregation/vertical.py

Following #9752's new horizontal methods, the usage of the previous one's was deprecated without it being clear what the new function names were. I just stepped through the instances of `**This functionality is deprecated**` and added the new function name after them.

docs(python): Mention func_horizontal on deprecated func docstrings

---

.github/release-drafter.yml

Changes:
* Add the `cli` scope. If you add this scope, it will get the `cli` label. Example:
* `fix(cli): Fix thing` -> gets the `cli` label
* Add a 'global scope' - if you do not specify a scope, it will automatically get the `rust` and `python` labels. Note that the `cli` scope is not included. Example:
* `feat: Cool new thing` -> gets the `rust` and `python` labels
* Add the `depr` label. Deprecations now get their own section in the changelog. Tag your PR with `depr` to add the `deprecation` tag. Example:
* `depr(python): Thing is now deprecated` -> gets the `deprecation` label
* Removed the `ci`, `refactor`, `revert`, `style`, and `test` tags. These are all internal improvements and can be tagged with `chore`. They will get the label `internal`.
* `ci(python): Improve lint workflow` …

chore(python): Update autolabeler

---

py-polars/polars/dataframe/frame.py
py-polars/polars/dataframe/groupby.py
py-polars/polars/expr/expr.py
py-polars/polars/functions/lazy.py
py-polars/polars/lazyframe/groupby.py
py-polars/polars/series/series.py

This would look like this:
, with a big warning right under the one-line summary

docs(python): add big warnings about using apply

---

py-polars/polars/config.py
py-polars/polars/dataframe/frame.py
py-polars/polars/utils/show_versions.py
py-polars/polars/utils/various.py
py-polars/tests/unit/namespaces/test_array.py
py-polars/tests/unit/namespaces/test_struct.py
py-polars/tests/unit/test_api.py
py-polars/tests/unit/test_cfg.py
py-polars/tests/unit/test_show_graph.py
py-polars/tests/unit/utils/test_parse_expr_input.py
py-polars/tests/unit/utils/test_utils.py

chore(python): Add various unit tests

---

py-polars/docs/source/conf.py
py-polars/polars/config.py
py-polars/polars/io/_utils.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/utils/various.py
py-polars/pyproject.toml
py-polars/scripts/check_stacklevels.py
py-polars/tests/benchmark/test_release.py
py-polars/tests/unit/io/conftest.py
py-polars/tests/unit/io/test_csv.py
py-polars/tests/unit/io/test_database.py
py-polars/tests/unit/io/test_lazy_csv.py
py-polars/tests/unit/io/test_lazy_json.py
py-polars/tests/unit/io/test_other.py
py-polars/tests/unit/io/test_parquet.py
py-polars/tests/unit/streaming/conftest.py
py-polars/tests/unit/test_cfg.py
py-polars/tests/unit/test_sql.py

We have a mix of `os.path` and `Pathlib` in our code base. The latter is more ergonomic (see write_text/bytes, etc) and also in use as part of our API. Enabled a Ruff rule to guide us going forward.

chore(python): Use Pathlib everywhere

---

polars/polars-core/src/chunked_array/comparison/mod.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/boolean.rs
polars/polars-lazy/polars-plan/src/dsl/mod.rs
polars/polars-sql/src/sql_expr.rs
polars/tests/it/lazy/expressions/window.rs
py-polars/polars/expr/expr.py
py-polars/polars/functions/aggregation/vertical.py
py-polars/polars/series/series.py
py-polars/src/expr/general.rs

Resolves https://github.com/pola-rs/polars/issues/9472
Adds a drop_nulls parameter to allow null propagation in any and all.

feat(rust, python): Optional three-valued logic for any/all

---

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/dataframe/test_extend.py
py-polars/tests/unit/dataframe/test_vstack.py

Similar to https://github.com/pola-rs/polars/pull/9895
Also added some tests for failure conditions, and updated docs a bit.
I noticed that `extend` works in-place, even though it returns the DataFrame. That can be surprising for users, so I added a warning for this in the docstring.

fix(python): Handle `DataFrame.extend` extending by itself

---

polars/polars-lazy/polars-plan/src/dsl/python_udf.rs
py-polars/polars/utils/show_versions.py
py-polars/pyproject.toml
py-polars/requirements-dev.txt
py-polars/tests/unit/test_serde.py

Currently we use the default `pickle` module to serialize python UDF's. There are various shortcomings of using `pickle` to serialize arbitrary functions which cloudpickle can overcome (mostly because pickle serializes by reference vs. cloudpickle can serialize by value). Here's a quick example with nested functions:
Cloudpickle can do this:
```
import cloudpickle
def f():
def g():
return 5
return cloudpickle.dumps(g)
f()
gives:
b'\x80\x05\x95\xc3\x01\x00\x00\x00\x00\x00\x00\x8c\x17cloudpickle.cloudpickle\x94\x8c\x0e_make_function\x94\x93\x94(h\x00\x8c\r_builtin_type\x94\x93\x94\x8c\x08CodeType\x94\x85\x94R\x94(K\x00K\x00K\x00K\x00K\x01KSC\x04d\x01S\x00\x94NK\x05\x86\x94))\x8c"/tmp/ipykernel_37771/1247407800.py\x94\x8c\x01g\x94K\x03C\x02\x04\x01\x94))t\x94R\x94}\x94(\x8c\x0b__package__\x94 …
```

feat(rust, python): Add cloudpickle for serializing python UDFs

---

py-polars/docs/source/conf.py
py-polars/polars/dataframe/frame.py
py-polars/polars/dataframe/groupby.py
py-polars/polars/datatypes/classes.py
py-polars/polars/datatypes/convert.py
py-polars/polars/expr/datetime.py
py-polars/polars/io/csv/batched_reader.py
py-polars/polars/io/delta.py
py-polars/polars/utils/convert.py
py-polars/polars/utils/various.py
py-polars/pyproject.toml
py-polars/scripts/check_stacklevels.py
py-polars/tests/docs/run_doctest.py
py-polars/tests/unit/utils/test_utils.py

D101, D102 & D103 are all useful rules, so have added docstrings where possible. On some internal utils, I have marked private and/or used a noqa. This should stop us from adding undocumented public functions.
D100 & D104: we are not using module and package docstrings at all, is this something we want/need? As it is in the list of "remove errors" in pyproject.toml.
D105: we should probably do this, but there are a lot here.

docs(python): Address ignored Ruff doc rules

---

py-polars/polars/expr/expr.py
py-polars/polars/series/series.py

Fixes #9934.
Updated docstring to include also one example with nearest interpolation.

docs(python): Add 'nearest' in Expr.interpolation docstring with an example

---

py-polars/docs/source/reference/io.rst
py-polars/docs/source/reference/lazyframe/miscellaneous.rst

docs(python): Move `sink_*` methods to IO chapter

---

polars/polars-core/src/frame/asof_join/groups.rs
py-polars/tests/unit/operations/test_join_asof.py

fix(rust,python): Fix as-of join when `by` groups are interleaved

---

polars/polars-core/src/frame/row/transpose.rs
polars/polars-core/src/series/iterator.rs
py-polars/tests/unit/operations/test_transpose.py

We don't have the architecture in place yet to support objects. Let's raise for now.
fixes #9927

fix(rust, python): raise on unsupported transpose and object types

---

py-polars/polars/dataframe/frame.py

Fixed text suggesting scalar `apply` results create a `Series`; they return a (single-col) `DataFrame`.

docs(python): minor fix for `apply` docstring example text

---

py-polars/polars/expr/expr.py

docs(python): fix or/and docstrings to say bitwise, not logical

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

The
```python
elif value.isidentifier():
if value not in ("True", "False", "None"):
return f'pl.col("{col}")'
```
makes me feel a bit nervous, and I'm worried it's going to break as we add complexity
Can we just pass in `param_name` and explicitly match against that?

chore(python): use param_name more in udfs for greater defensiveness

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Adds awareness of the following opcodes to our `apply` warning generation:
* `POP_JUMP_FORWARD_IF_FALSE`
* `POP_JUMP_FORWARD_IF_TRUE`
* `POP_JUMP_IF_FALSE`
* `POP_JUMP_IF_TRUE`
* `JUMP_IF_FALSE_OR_POP`
* `JUMP_IF_TRUE_OR_POP`
This allows us to additionally recognise functions of the form...
```python
lambda x: x < 0 and (x % 2 == 0) and x < 100 
```
...translating to polars as:
```python
(pl.col("x") < 0) & ((pl.col("x") % 2) == 0) & (pl.col("x") < 100)
```
**Current limitation**: 
Only handles the case where every jump opcode found implies the same logical operation (eg: _all_ `and` or _all_ `or`). 
Properly translating mixed usage requires re-injecting nesting information by inferring it from the specific combination of opcodes and jump targets - it's doable, but not in my lunch break …

feat(python): initial support for parsing the set of `jump` bytecode instructions required to reconstruct `and/or` logic

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

@MarcoGorelli, as promised... updated to use the original/underlying bytecode `Instruction` objects _directly_, so we can use the named properties and avoid "mystery meat" references like `op[0]`, `op[2]` and so forth... 
**Also:**
* Makes `StackValue` a NamedTuple to improve clarity of usage.
* More error information if an unidentified operation is found where it shouldn't be.

refactor(python): use original `Instruction` objects during bytecode translation

---

.github/release-drafter-python.yml
.github/release-drafter-rust.yml
.github/release-drafter.yml
CONTRIBUTING.md

Changes:
* Re-introduce `ci` / `refactor` / `test` types. The resulting label will be `internal`.
* Add `breaking rust` and `breaking python` labels. This is useful for PRs that break one side but not the other. Use it by adding an exclamation point to the scope, e.g. `feat(rust!, python): New feature`
* Add a note to the Contributing guide about the `accepted` label.

chore: Update autolabeler again

---

polars/polars-lazy/polars-plan/src/dsl/arithmetic.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/pow.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
polars/polars-lazy/polars-plan/src/dsl/mod.rs
polars/polars-sql/src/functions.rs
polars/polars-sql/tests/functions_math.rs
py-polars/docs/source/reference/expressions/computation.rst
py-polars/docs/source/reference/series/computation.rst
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/src/expr/general.rs
py-polars/tests/unit/series/test_series.py

Adds three functions to `SQLContext`, as shown below:
I'm grabbing suggestions for SQL features from https://github.com/pola-rs/polars/issues/7227. I threw `PI()` into this pr at the last moment, but I could split it out if needed.

feat(python): adds `SQRT`, `CBRT`, `PI` functions to `SQLContext`

---

py-polars/polars/dataframe/frame.py

Came across this (https://github.com/pola-rs/polars/issues/8095) and did it.
Allows naming the columns of a transposed DataFrame from one of its columns.

feat(python): Name transpose from column

---

py-polars/polars/utils/udfs.py
py-polars/polars/utils/various.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Ref: #9958.
* Accounts for possible leading `COPY_FREE_VARS` in bytecode stack.
* Accounts for use of globals/locals (`LOAD_GLOBAL` and `LOAD_DEREF`).
* Enhances `_get_stack_locals` so we can use it for additional bytecode introspection.

feat(python): improved bytecode edge-cases and stacklevel introspection

---

py-polars/polars/functions/range.py
py-polars/src/functions/eager.rs
py-polars/src/functions/lazy.rs
py-polars/src/functions/range.rs
py-polars/src/lib.rs
py-polars/tests/unit/functions/test_range.py

I am working on a non-breaking version of https://github.com/pola-rs/polars/pull/9653. Figured I'd clean up these functions before reworking them.

refactor(python): Clean up `date_range`/`time_range`

---

py-polars/polars/dataframe/frame.py

PyCharm (and maybe other IDEs?) requires that multi-line type hints are parenthesised.

refactor(python): fix type hint

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Now that the idea has proved itself, I've industrialised a bit; restructured the mash-mash of individual functions into a more organised `BytecodeParser` class that we can interact with cleanly.
```python
from collections import Counter 
from polars.utils.udfs import BytecodeParser
parser = BytecodeParser(
function=lambda x: (x * -x) ** x, 
apply_target="expr",
)
parser.can_rewrite()
parser.to_expression( col="colx" )
parser.param_name
Counter( inst.opname for inst in parser.instructions )
parser.warn("colx")
parser.dis()
```
This is all called internally by the existing `warn_on_inefficient_apply` function.

refactor(python): restructure all UDF parsing/translation methods into a new `BytecodeParser` class

---

py-polars/requirements-dev.txt

When building the Rust bindings, `maturin` loves to complain:
```
⚠️ Warning: Failed to set rpath for /home/stijn/code/polars/py-polars/target/debug/libpolars.so: Failed to execute 'patchelf', did you install it? Hint: Try `pip install maturin[patchelf]` (or just `pip install patchelf`)
```
Apparently it's executing this part of the code, which tries to "Add library search paths in Cargo target directory rpath when building in editable mode".
https://github.com/PyO3/maturin/blob/99a2a5a84443345943aececdf0bf854c49c26110/src/build_context.rs#L330-L355
Not exactly sure what this does, to be honest. But the warning is annoying, and adding this small extra dev dependency fixes it. So I think it's fine to add it.

build(python): Add patchelf extra to maturin

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Ref: #9968.
Can now identify `numpy` calls in `apply` function bytecode and offer a native polars translation... :)
Understands both direct _"numpy.func(x)"_ calls and the standard _"np.func(x)"_ alias.
Note that I have only whitelisted a handful of numpy functions to start with; it's trivial to add more (literally just add the function name to the whitelist), but each one needs verification that we are indeed doing exactly the same thing in the default case - I'll whitelist additional functions as I confirm this.
```python
df = pl.DataFrame({"abc": [27, 64, 125]})
fn = lambda x: 1 + np.cbrt(x) / 3
val = pl.col("abc").apply(fn),
)
```
Underlying function bytecode...
```python
import dis
dis.dis( fn )
```
These instructions get …

feat(python): support bytecode identification of `numpy` functions in UDFs that we can map to native expressions

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Ref: #9968.
Support identification of python string-case functions in UDFs, alongside translation to a native expression. Can look at extending this to functions that take parameters (such as `endswith` or `startswith`) if that is desirable...
```python
"abc": ["AB", "cd", "eF"],
})
fn = lambda x: x.lower() + x.upper()
val = pl.col("abc").apply(fn),
)
```

feat(python): support bytecode identification/mapping of python string-case functions in UDFs

---

polars/polars-lazy/polars-plan/src/logical_plan/optimizer/fused.rs
polars/polars-lazy/polars-plan/src/utils.rs
py-polars/tests/unit/operations/test_arithmetic.py

The current implementation of fused arithmetic does not lead to fused operations when literals are involved.
fix #9857

perf(rust): Remove fused arithmetic from expressions with literals

---

py-polars/polars/utils/udfs.py

Further industrialisation; moves the instruction rewrite logic out of `BytecodeParser` into its own `RewrittenInstructions` class, and the expression translation logic into a new `InstructionTranslator` class, rather than having a single monolith class that does it all.
This gives better separation between...
1) instruction rewrites (where we identify expression translation opportunities for numpy function calls and/or python methods and inject synthetic `POLARS_EXPRESSION` ops)
2) the parsing of the rewritten instructions from postfix-opcode form to a natural-order intermediate stack
3) the final translation of the rewritten/parsed stack into a polars expression string 
...and will make further updates cleaner as we can (largely) leave the parsing/translation logic alone; most of the …

refactor(python): split-out expression translation and instruction-rewrite logic from `BytecodeParser`

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Ref: #9968.
While we can't parse/rewrite bare `numpy` function bytecode (as there isn't any), this PR enables detection of such functions and generates an equivalent warning:
```python
df = pl.DataFrame( {"abc": [16, 25, 36]} )
val = pl.col("abc").apply( np.sqrt ),
)
```

feat(python): detect and warn about bare `numpy` functions passed to `apply`

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_apply.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Ref: #9968.
Detects/handles both formulations...
* `pl.col("foo").apply(json.loads)` 
* `pl.col("foo").apply(lambda x: json.loads(x))`
...resulting in (json.loads)...
```python
```
...or (wrapped in lambda):
```python
```

feat(python): detect and warn about usage of `json.loads` in conjunction with `apply`

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Added a new rule in `RewrittenInstructions` to handle python builtins.
Allows us to spot the use of primitive `int`, `float`, or `str` casts against columns, such as...
```python
"a": [1,2,3,4,5,6,7,8,9],
}).with_columns(
a_str = pl.col("a").apply( lambda x: str(x).title() ),
)
```
... resulting in:
```python
```
**Note:** Will follow-up later with an extension that should also be able to spot use of primitive casts on _compound_ expressions, such as `lambda x: float(x * x // 2)`

feat(python): detect and warn about usage of str/int/float python-based casts with `apply`

---

polars/polars-lazy/src/lib.rs

Correct an erroneous example in API reference.
This example will return a Duplicate Err as "column with name 'rain' has more than one occurrences"

docs(rust): correct example in API reference

---

contribution/polars_ops_multiple_arguments/src/lib.rs

Small typo, `arr_1` should be `arr_2`

docs(rust): fix typo in contribution example

---

py-polars/polars/utils/udfs.py

**TLDR**:
* Cleans up the instruction-matching code; will make it easier to integrate more sophisticated matching later.
---
**Explanation**:
This puts matching specific `Instruction` sequences within the `RewrittenInstructions` class on a stronger footing; streamlines and consolidates the matching logic in a new method and allows for a much cleaner and less verbose (and less potentially error-prone) expression of matching rules.
For example, the following match definition finds (and returns) all `Instruction` sequences representing supported `numpy` function or `json.loads` calls as we advance through the operation stack:
**Before:**
```python
if inst.opname == "LOAD_GLOBAL" and (
inst.argval in _NUMPY_MODULE_ALIASES or inst.argval == "json"
):
instruction_buffer = …
```

refactor(python): much-improved `Instruction` matching for `BytecodeParser`

---

polars/polars-arrow/src/kernels/rolling/no_nulls/quantile.rs
py-polars/tests/unit/operations/test_rolling.py

I made a shameful mistake with handling a zero as the first weight. Now it is fixed. And there are also tests now.
https://github.com/pola-rs/polars/issues/10031

fix(rust, python): Fix weighted quantile for 0 weights

---

py-polars/polars/io/database.py

Closes #10015.
The PostgreSQL docs [explicitly allow](https://www.postgresql.org/docs/current/libpq-connect.html#id-1.7.3.8.3.6) both `postgresql://` _and_ `postgres://` URI prefixes[^1]; we can easily handle this with an entry in the `module_suffix_map` lookup.
[^1]: _...URI scheme designator can be either "postgresql://" or "postgres://"..._

fix(python): map 'postgres' URI prefix to ADBC 'postgresql' module

---

py-polars/polars/config.py
py-polars/polars/convert.py
py-polars/polars/dataframe/frame.py
py-polars/polars/dataframe/groupby.py
py-polars/polars/dependencies.py
py-polars/polars/expr/binary.py
py-polars/polars/expr/datetime.py
py-polars/polars/expr/expr.py
py-polars/polars/expr/list.py
py-polars/polars/expr/meta.py
py-polars/polars/expr/string.py
py-polars/polars/functions/as_datatype.py
py-polars/polars/functions/lazy.py
py-polars/polars/functions/range.py
py-polars/polars/io/csv/batched_reader.py
py-polars/polars/io/delta.py
py-polars/polars/io/ipc/functions.py
py-polars/polars/io/parquet/functions.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/_numpy.py
py-polars/polars/series/binary.py
py-polars/polars/series/datetime.py
py-polars/polars/series/list.py
py-polars/polars/series/series.py
py-polars/polars/series/string.py
py-polars/polars/series/utils.py
py-polars/polars/utils/meta.py

A lot of our Returns sections were not properly formatted according to [numpy docstyle](https://numpydoc.readthedocs.io/en/latest/format.html#returns), resulting in broken Sphinx formatting.
This PR updates all existing Returns sections to conform to the required formatting.
_(I know this one doesn't make sense, it's just to show the formatting)_

docs(python): Properly format `Returns` sections of docstrings

---

polars/polars-sql/src/sql_expr.rs
polars/polars-sql/tests/simple_exprs.rs

Adds a new form of the `CASE` SQL statement. We have this:
```
CASE 
WHEN condition_1  THEN result_1
WHEN condition_2  THEN result_2
[WHEN ...]
ELSE else_result
END
```
This PR adds this form:
```
CASE **expression**
WHEN value_1 THEN result_1
WHEN value_2 THEN result_2 
[WHEN ...]
ELSE else_result
END
```

feat(python, rust): Adds sql `CASE` statement expressions 

---

polars/polars-core/src/frame/explode.rs
polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs
polars/polars-lazy/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
py-polars/tests/unit/test_predicates.py

Block predicate pushdown at a join node when the
predicate contains a `fill_null` as the join
can produce nulls.
fixes #10058

fix(rust, python): predicate pushdown #10058

---

polars/polars-arrow/src/kernels/mod.rs
polars/polars-arrow/src/kernels/time.rs
polars/polars-core/src/chunked_array/temporal/datetime.rs
polars/polars-lazy/polars-plan/src/dsl/dt.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/datetime.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/mod.rs
polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
py-polars/src/expr/datetime.rs
py-polars/tests/unit/datatypes/test_temporal.py

A few chores:
- `tz_localize` was already removed from the Python side in https://github.com/pola-rs/polars/pull/7860 - OK to remove it from the Rust side too?
- rename `CastTimezone` to `ReplaceTimeZone` (leftover old name which never got renamed during the original deprecations)
- some functions are `replace_timezone`, others `replace_time_zone` - standardise to the latter

chore(rust)!: remove deprecate tz_localize, name CastTimezone to ReplaceTimeZone

---

polars/polars-core/src/frame/row/transpose.rs
py-polars/Cargo.lock
py-polars/Cargo.toml
py-polars/polars/dataframe/frame.py
py-polars/src/dataframe.rs

Moves the functionality to customize the names of a transposed DataFrame and keep its column names as a new column into Rust.

feat(rust): Move transpose naming to Rust

---

py-polars/polars/utils/_construction.py
py-polars/tests/unit/operations/test_is_in.py

fix(python): address an inadvertently shallow-copy issue on underlying PySeries

---

polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs

another one that got forgotten during the deprecation 😳

fix(rust): fix error message from cast-timezone to replace-time-zone

---

polars/polars-core/src/series/comparison.rs
polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
polars/polars-lazy/src/physical_plan/expressions/apply.rs
py-polars/tests/unit/io/test_lazy_parquet.py

fix(rust, python): fix false positive in parquet stats evaluation

---

polars/polars-io/src/csv/read.rs
polars/polars-io/src/ndjson/core.rs
polars/polars-io/src/parquet/mod.rs
polars/polars-io/src/partition.rs
polars/polars-lazy/polars-pipe/src/executors/sinks/groupby/generic/source.rs
polars/polars-lazy/polars-pipe/src/executors/sinks/sort/ooc.rs
polars/polars-lazy/polars-pipe/src/executors/sources/ipc_one_shot.rs
polars/polars-lazy/polars-plan/src/logical_plan/builder.rs
polars/polars-lazy/src/frame/csv.rs
polars/polars-lazy/src/physical_plan/executors/scan/ndjson.rs
polars/polars-utils/Cargo.toml
polars/polars-utils/src/io.rs
polars/polars-utils/src/lib.rs

fix #10043 
Add the file path to the error reporting in scan_csv when fail to open the file.

fix(rust, python): add file path to io error in scan_csv

---

polars/polars-core/src/datatypes/any_value.rs
polars/polars-lazy/polars-plan/src/logical_plan/optimizer/simplify_expr.rs

This cleans up literal casts created by the type-coercion pass.

feat(rust, python): inline `lit(Series).cast(..)` to -> `lit(Series.cast(..))`

---

polars/polars-lazy/polars-plan/src/dsl/arity.rs
py-polars/Cargo.lock
py-polars/polars/_reexport.py
py-polars/polars/dataframe/groupby.py
py-polars/polars/expr/__init__.py
py-polars/polars/expr/whenthen.py
py-polars/polars/functions/repeat.py
py-polars/polars/functions/whenthen.py
py-polars/polars/type_aliases.py
py-polars/polars/utils/_parse_expr_input.py
py-polars/src/functions/whenthen.rs
py-polars/tests/unit/datatypes/test_object.py
py-polars/tests/unit/functions/test_whenthen.py
py-polars/tests/unit/test_arity.py
py-polars/tests/unit/test_predicates.py
py-polars/tests/unit/test_queries.py

Closes #9031 
**Syntax for end users remains unchanged.**
Changes:
* Renamed `WhenThen` to `Then`
* Split `WhenThenThen` into `ChainedWhen` and `ChainedThen`.
* This allows us to enforce a valid when-then chain and have nice auto-completion!
* Technically, we could have only `ChainedWhen` and `ChainedThen` - we don't need `When`/`Then`. But I figured I would keep them to avoid allocating a vector for the most common case which is single when/then without a chain.
* Make `Then` and `ChainedThen` inherit from `Expr`.
* This replaces the `getattr` hack
* You now get nice auto-completion on these objects.
* These objects now pass `isinstance` checks for `Expr`, which is great and will solve a lot of hidden bugs.

refactor(python): Refactor `WhenThen` / `WhenThenThen`

---

py-polars/polars/utils/udfs.py
py-polars/pyproject.toml
py-polars/tests/test_udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Ref: #9968.
This was a fun one... enables two additional ops (`POP_JUMP_FORWARD_IF_FALSE` and `POP_JUMP_FORWARD_IF_TRUE` if Python >= 3.11, and `POP_JUMP_IF_FALSE` and `POP_JUMP_IF_TRUE` for earlier versions) in order to support _mixed_ `and/or` chains (previously only supported _all_ `and` or _all_ `or`) with, crucially, nesting resolution being determined from jump offsets.
```python
from polars.utils.udfs import BytecodeParser
fn = lambda x: x > 1 and x != 2 or x % 2 == 0 and x < 3
BytecodeParser( fn,"expr" ).to_expression( col="x" )
```
Notice that we maintain the parenthesised inner `or` block:
```python
fn = lambda x: x > 1 and (x != 2 or x % 2 == 0) and x < 3
BytecodeParser( fn,"expr" ).to_expression( col="x" )
```
**Also**: 
* Tidied-up the loose opname-related sets/dicts/etc; all …

feat(python): BytecodeParser can now handle mixed/nested `and/or` control flow

---

polars/polars-ops/src/series/ops/various.rs

Struct series will now compare correctly.
We'll handle the general case later, along with some possible improvements and enhancements to is_sorted itself.

fix(rust, python): fix is_sorted for structs

---

py-polars/Cargo.lock
py-polars/polars/io/_utils.py
py-polars/polars/utils/various.py
py-polars/requirements-dev.txt
py-polars/tests/unit/io/test_cloud.py

Also error if a glob pattern is passed as fsspec doesn't handle those.
fixes #10008

fix(python): undo regression in scan_parquet from s3

---

polars/polars-time/src/groupby/dynamic.rs
py-polars/tests/unit/operations/test_groupby_rolling.py

fix(rust, python): fix invalid access when groupby rolling produces empty sets

---

py-polars/Cargo.lock
py-polars/Cargo.toml
py-polars/src/conversion.rs
py-polars/src/expr/string.rs

The bugs in #10034 and #9791 only occur in the heavily optimized release binaries. I couldn't replicate them locally with threaded release (and didn't want to wait 40 minutes on fat linking).
But, I did found UB in a debug build while reading the json values. This is fixed in https://github.com/simd-lite/simd-json/pull/301

fix(rust, python): fix ub in simd-json

---

polars/polars-lazy/polars-plan/src/dsl/function_expr/schema.rs
py-polars/tests/unit/datatypes/test_struct.py

fixes #10096
I've just copied the behaviour from the `FieldByName` block.

fix(rust, python): Fix struct get field by index out of bounds error.

---

py-polars/polars/series/series.py
py-polars/polars/utils/udfs.py
py-polars/requirements-lint.txt
py-polars/tests/test_udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py
py-polars/tests/unit/series/test_series.py

Ref: #9968.
* Extends warnings about inefficient `Expr.apply` to `Series.apply`.
* Adds parsing recognition for additional builtin: `abs`.
```python
srs = pl.Series( 
name = "s", 
values = [-20, -12, -5, 0, 5, 12, 20] 
).apply( 
lambda x: (abs(x) != 12) and (x > 10 or x < -10 or x == 0) 
)
```

feat(python): enable "inefficient apply" warnings from `Series`

---

py-polars/polars/expr/expr.py
py-polars/tests/unit/operations/test_inefficient_apply.py

The warning's currently being shown twice, once from `Expr.apply` and once from `Series.apply` :
```python
In [1]: my_dict = {1: "1", 2: "2", 3: "3"}
...: df = pl.DataFrame({"a": [1, 2, 3]})
...: df.select(pl.col("a").apply(lambda x: x**2))
...: 
<ipython-input-1-2741e0b26152>:3: PolarsInefficientApplyWarning: 
Expr.apply is significantly slower than the native expressions API.
Only use if you absolutely CANNOT implement your logic otherwise.
In this case, you can replace your `apply` with the following:
-  pl.col("a").apply(lambda x: ...)
+  pl.col("a") ** 2
df.select(pl.col("a").apply(lambda x: x**2))
sys:1: PolarsInefficientApplyWarning: 
Series.apply is significantly slower than the native series API.
Only use if you absolutely CANNOT implement your logic otherwise.
In this case, you …
```

fix(python): silence Series.apply inefficient apply warning when calling Expr.apply

---

polars/polars-ops/src/chunked_array/strings/replace.rs
py-polars/tests/unit/namespaces/test_string.py

fix(rust, python): adjust for null values in str.replace fast path

---

.github/workflows/test-rust.yml

I don't know what the windows CI failure is. Until we have fixed that, this ensures we at least run the linux tests.

ci: temporarily turn off fail-fast so that ubuntu tests run

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/database.py
py-polars/tests/unit/io/test_database.py

Ref: #10121.
This is a bit of prep before expanding capabilities - no new support (aside from opening ADBC connections via context manger). Deprecates "connection_uri" in favour of "connection", so we can use it for accepting user-created connection objects later.

depr(python): deprecate "connection_uri" → "connection" param in read/write database methods

---

polars/polars-lazy/polars-plan/src/dsl/arity.rs
py-polars/polars/expr/expr.py
py-polars/polars/expr/whenthen.py
py-polars/polars/functions/whenthen.py
py-polars/polars/series/series.py
py-polars/src/functions/whenthen.rs
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/functions/test_whenthen.py
py-polars/tests/unit/operations/test_sort.py

Changes:
* Deprecate parsing string inputs as literals for `when-then-otherwise`. These should be parsed as column names to be consistent with the rest of the API.
* Rename input args to `condition` / `statement`. 
* Expand docstrings

depr(python): Deprecate parsing string inputs as literals for `when-then-otherwise`

---

py-polars/polars/utils/udfs.py
py-polars/polars/utils/various.py
py-polars/tests/test_udfs.py

the bytecode parser tests stopped running in CI after #10123
This is because `udfs` imported `polars`, but that couldn't be found in the `no-polars-installed` environment, so the test was being skipped
I've changed the test so it's only skipped if `udfs` itself can't be imported (because it's not in the path) so this doesn't happen again
---
EDIT ok this worked, it's running again
============================= test session starts ==============================
platform linux -- Python 3.8.17, pytest-7.4.0, pluggy-1.2.0
rootdir: /home/runner/work/polars/polars/py-polars
configfile: pyproject.toml
collected 35 items
tests/test_udfs.py ...................................                   [100%]
============================== 35 passed in 0.14s ==============================

chore(python): get test_udfs running on all python versions again

---

py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/polars/expr/string.py
py-polars/polars/expr/whenthen.py
py-polars/polars/functions/aggregation/vertical.py
py-polars/polars/functions/as_datatype.py
py-polars/polars/functions/lazy.py
py-polars/polars/functions/range.py
py-polars/polars/functions/repeat.py
py-polars/polars/io/pyarrow_dataset/functions.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/lazyframe/groupby.py
py-polars/polars/series/series.py
py-polars/polars/series/string.py
py-polars/polars/string_cache.py
py-polars/polars/utils/_parse_expr_input.py
py-polars/polars/utils/deprecation.py
py-polars/polars/utils/meta.py
py-polars/tests/unit/utils/test_deprecation.py
py-polars/tests/unit/utils/test_utils.py

Partially addresses #8004
Changes:
* Deprecation utils now have a mandatory `version` argument. This helps us determine when it's appropriate to remove the functionality.
* `deprecated_alias` and `redirect` are not included yet - these are a little more complicated.
* Some related refactoring / add some tests.

refactor(python): Track version in deprecation utils

---

crates/polars-pipe/LICENSE
crates/polars-plan/LICENSE
crates/polars/LICENSE

I missed these in the refactor of #10141

chore(rust): Fix LICENSE symlink for moved crates

---

py-polars/polars/io/ipc/anonymous_scan.py
py-polars/polars/io/parquet/anonymous_scan.py

Tthe last piece of malfunctioning `scan_*` since `polars==0.18.4`
Fix #10174 
Fix #9668

fix(python): Don't pickle `_scan_impl`

---

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/io/test_parquet.py

Implements [#9812](https://github.com/pola-rs/polars/issues/9812)
Currently Polars uses _pyarrow.write_table()_ to write parquets with pyarrow. The _pyarrow.write_to_dataset()_ funtion is not used. 
_pyarrow.write_to_dataset()_ does support more features than _write_table()_. Important features like writing partitioned parquet files.
Therefore, I added _pyarrow.write_to_dataset()_ using a new parameter in write_parquet(), namely "use_pyarrow_write_to_dataset".
I added two tests and an example in the docstring.
Currently some parameters like statistics or compressions are not used when calling _write_to_dataset()_ as these are not supported in _write_to_dataset()_.
Links:
- https://arrow.apache.org/docs/python/generated/pyarrow.parquet.write_to_dataset.html

feat(python): Add pyarrow write_to_dataset to write_parquet function

---

py-polars/docs/source/reference/expressions/list.rst
py-polars/docs/source/reference/series/list.rst
py-polars/polars/expr/list.py
py-polars/polars/series/list.py
py-polars/polars/sql/context.py
py-polars/polars/utils/deprecation.py
py-polars/tests/unit/namespaces/test_list.py
py-polars/tests/unit/utils/test_deprecation.py

credit to @magarick for starting the convo around this on discord

refactor(python): prepend set_ to set operations on lists

---

py-polars/polars/io/database.py
py-polars/tests/unit/io/test_database.py

Closes #10177.
Make sure it is clear that we are currently only supporting URI strings for the `connection` param. (Connection _objects_ are coming in the near future).
Also, sets the default engine value to `None` (while continuing to default to `connectorx`). This is prep for accepting user-instantiated connections, as we will be able to infer the engine directly where relevant (and having "engine='connectorx'" in won't make sense in conjunction with a user-supplied connection object).

feat(python): raise a better error message from `read_database` if not passed a string URI

---

py-polars/src/apply/mod.rs
py-polars/tests/unit/operations/test_apply.py

fix(rust, python): prevent re-ordering of dict keys inside `.apply`

---

py-polars/polars/dataframe/frame.py
py-polars/polars/expr/datetime.py
py-polars/polars/expr/expr.py
py-polars/polars/expr/list.py
py-polars/polars/expr/string.py
py-polars/polars/expr/whenthen.py
py-polars/polars/functions/aggregation/vertical.py
py-polars/polars/functions/lazy.py
py-polars/polars/functions/range.py
py-polars/polars/functions/whenthen.py
py-polars/polars/io/database.py
py-polars/polars/io/pyarrow_dataset/functions.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/datetime.py
py-polars/polars/series/list.py
py-polars/polars/series/series.py
py-polars/polars/series/string.py
py-polars/polars/sql/context.py
py-polars/polars/string_cache.py
py-polars/polars/utils/deprecation.py
py-polars/polars/utils/meta.py
py-polars/tests/unit/test_lazy.py
py-polars/tests/unit/utils/test_deprecation.py

Partially addresses https://github.com/pola-rs/polars/issues/8004
Followup of #10147
Changes:
* Refactor the `deprecated_alias` util
* Renamed to ~`deprecate_argument_name`~ `deprecate_renamed_parameter`
* Only renames a single argument. Stack multiple decorators to rename multiple arguments.
* Requires a `version` keyword argument to specify when the deprecation happened.
* Rename the `redirect` util to `deprecate_renamed_methods`. Now requires a `versions` keyword argument.
* Rename some other utils and improve docstrings.
I think this now gives us quite a solid set of utils for doing deprecations:
* `issue_deprecation_warning`
* `deprecate_function`
* `deprecate_renamed_function`
* `deprecate_renamed_parameter`
* `deprecate_renamed_methods`
* `deprecate_nonkeyword_arguments` …

refactor(python): Improve deprecation utils

---

py-polars/polars/utils/udfs.py
py-polars/tests/test_udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Closes #10210.
In Python <= 3.10 `if/else` constructs are modelled in the bytecode using multiple `RETURN_VALUE` ops; we don't support translation of such bytecode yet (and in Python >= 3.11 we spot `if/else` constructs differently, because of the `JUMP_FORWARD` op).
I have generically fixed this class of false positives, as we don't support translation of _any_ functions containing the type of branching implied by multiple `RETURN_VALUE` ops (`if/else` or otherwise).

fix(python): avoid false positives from multiple `RETURN_VALUE` ops when checking `apply` lambdas/functions

---

crates/polars-core/src/cloud.rs

Closes #10206
Added gcs to cloud options parser.
```rust
Ok(match parsed.scheme() {
"s3" => Self::Aws,
"az" | "adl" | "abfs" => Self::Azure,
"gs" | "gcp" | "gcs" => Self::Gcp,
"file" => Self::File,
_ => polars_bail!(ComputeError: "unknown url scheme"),
})
```
This does not fail on passing gcs as the schema and allows ParquetReader to treat it as a cloud option.

feat(rust): added gcs to gcp cloud schema in polars-core::cloud #10206.

---

crates/polars-core/src/chunked_array/logical/struct_/mod.rs
py-polars/tests/unit/datatypes/test_struct.py

resolves https://github.com/pola-rs/polars/issues/10130
Structs now count nulls the way we say they should.
I also added a `total_null_count` field to be used internally for now. It can be exposed later.

fix(rust, python): correct struct null counts

---

.github/dependabot.yml
py-polars/Cargo.lock

I changed the `skip changelog` label, forgot to update Dependabot.

chore: Update dependabot config

---

py-polars/docs/source/_static/css/custom.css
py-polars/docs/source/conf.py

sphinx-doc/sphinx#11011 introduced a sphinx-native way to display parameters on separate lines, setting the value of [`maximum_signature_line_length`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-maximum_signature_line_length) in `conf.py`.
Merging would enable to remove the CSS hack introduced in #2207, and to have short signatures rendered on a single line.
Feel free to change the number of characters set by `maximum_signature_line_length`, I just set it to 88 because it's a common convention in python code files, but I have no strong opinion on what would be the "perfect" number.

docs(python): Use sphinx' `maximum_signature_line_length`

---

crates/Makefile

Partially addresses #10199
Specifying `-p polars` makes the `make integration-tests` command behave exactly like before (since the Makefile used to be in the `polars` crate`). This has to do with how Cargo workspaces behave.
The failing integration tests mentioned in the linked issue are actually not new - this already happened in the old setup when running from the project root. We have to figure out exactly what happens there. I had looked at it before but had not figured it out yet.

chore(rust): Fix `make integration-tests` command

---

py-polars/polars/functions/lazy.py

depr(python): Deprecate `avg` alias for `mean`

---

crates/polars-core/src/chunked_array/object/mod.rs
crates/polars-core/src/chunked_array/ops/append.rs
crates/polars-core/src/chunked_array/ops/downcast.rs
crates/polars-core/src/chunked_array/ops/mod.rs
crates/polars-core/src/chunked_array/ops/take/take_random.rs
crates/polars-core/src/chunked_array/ops/take/take_single.rs

fixes #10226
Can read the file in 1.06 s

perf(rust, python): fix O(n^2) in sorted check during append

---

crates/polars-core/src/chunked_array/object/mod.rs
crates/polars-core/src/chunked_array/ops/fill_null.rs
crates/polars-core/src/chunked_array/ops/mod.rs
crates/polars-core/src/chunked_array/ops/unique/mod.rs
crates/polars-core/src/frame/mod.rs
crates/polars-core/src/series/implementations/object.rs
crates/polars-core/src/series/mod.rs
crates/polars/src/docs/eager.rs
crates/polars/src/lib.rs

Almost entirely solves https://github.com/pola-rs/polars/issues/10246, the only remaining dead links are due to overly aggressive prelude exports from other crates / the standard library.

docs(rust): fix dead links in Rust documentation

---

py-polars/polars/expr/expr.py
py-polars/polars/series/series.py

These were recently renamed to `q`, but that does not match our naming policy. Fortunately, it's a simple fix.

depr(python): Rename first `qcut` parameter to `quantiles`

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/pyarrow_dataset/anonymous_scan.py
py-polars/polars/io/pyarrow_dataset/functions.py
py-polars/tests/unit/io/test_pyarrow_dataset.py

Closes #10162. 
Can have an outsize impact on performance in certain cases; definitely useful to expose it to the caller so they can adjust it as needed.

feat(python): add "batch_size" to `scan_pyarrow_dataset` parameters

---

crates/polars-plan/src/dsl/function_expr/datetime.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/function_expr/temporal.rs
crates/polars-plan/src/dsl/functions/temporal.rs
py-polars/polars/expr/datetime.py
py-polars/polars/functions/as_datatype.py
py-polars/polars/series/datetime.py
py-polars/src/functions/lazy.rs
py-polars/tests/unit/functions/test_as_datatype.py

Closes [#7416](https://github.com/pola-rs/polars/issues/7416)
Changes:
* Add `time_unit`, `time_zone` and `use_earliest` arguments to the `datetime` expression function
* On the Rust side, move everything into the standard expression architecture.
Paging @MarcoGorelli for a review 😄

feat(rust!,python): Extend `datetime` expression function with time zone/time unit parameters

---

py-polars/polars/dataframe/frame.py
py-polars/polars/dependencies.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/series.py
py-polars/requirements-dev.txt
py-polars/tests/unit/test_consortium_standard.py

Here's an entry point to the Consortium's DataFrame API Standard
It enables dataframe-consuming libraries to just check for a `__dataframe_consortium_standard__` attribute on a dataframe they receive - then, so long as they stick to the spec defined in https://data-apis.org/dataframe-api/draft/index.html, then their code should work the same way, regardless of what the original backing dataframe library was
Use-case: currently, scikit-learn is very keen on using this, as they're not keen on having to depend on pyarrow (which will become required in pandas), and the interchange protocol only goes so far (e.g. a way to convert to ndarray is out-of-scope for that). If we can get this to work there, then other use cases may emerge
**Maintenance burden on polars: none** (unless, once it gains …

feat(python): add entry point to the Consortium DataFrame API

---

README.md
py-polars/Cargo.toml
py-polars/Makefile

This provides more performant options (in terms of build time) for release mode through `make build-opt` and more performant options (in terms of runtime) for debug mode through `make build-debug-opt`.
They're also directly available from the Rust side under the profiles `debug-release` and `opt-dev` respectively.

feat(rust): add extra build profiles

---

py-polars/polars/utils/udfs.py
py-polars/tests/test_udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

Integrates `BINARY_SUBSCR` into the generic binary operator translation path so that we can support suggestions where the key is itself an expression.
This enables new suggestions for `apply` functions that use lookups, such as...
```python
ascii = { o:chr(o) for o in range(127) }
"ord": [40,50,60,70,80,90,100,110],
}).with_columns(
prev_chr = pl.col('ord').apply( lambda x: ascii[x-1] ),
next_chr = pl.col('ord').apply( lambda x: ascii[x+1] ),
)
```
...which will now generate the following:
```
PolarsInefficientApplyWarning: 
Expr.apply is significantly slower than the native expressions API.
Only use if you absolutely CANNOT implement your logic otherwise.
In this case, you can replace your `apply` with the following:
- pl.col("ord").apply(lambda x: …
```

feat(python): support bytecode translation to `map_dict` where the lookup key is an expression

---

Cargo.toml
contribution/polars_ops_multiple_arguments/Cargo.toml
crates/polars-algo/Cargo.toml
crates/polars-arrow/Cargo.toml
crates/polars-core/Cargo.toml
crates/polars-error/Cargo.toml
crates/polars-io/Cargo.toml
crates/polars-json/Cargo.toml
crates/polars-lazy/Cargo.toml
crates/polars-ops/Cargo.toml
crates/polars-pipe/Cargo.toml
crates/polars-plan/Cargo.toml
crates/polars-row/Cargo.toml
crates/polars-sql/Cargo.toml
crates/polars-time/Cargo.toml
crates/polars-utils/Cargo.toml
crates/polars/Cargo.toml
examples/python_rust_compiled_function/Cargo.toml
examples/read_csv/Cargo.toml
examples/read_json/Cargo.toml
examples/read_parquet/Cargo.toml
examples/read_parquet_cloud/Cargo.toml
examples/string_filter/Cargo.toml
polars-cli/Cargo.toml
py-polars/Cargo.toml

Changes:
* Define shared `package` info on the workspace level and use it across our crates
* Move the `dependencies` section before the `features` section everywhere (this was inconsistent) according to the [manifest format](https://doc.rust-lang.org/cargo/reference/manifest.html).
This doesn't impact anything except for being a bit nicer to look at. I'd like to move some dependency version definitions to the workspace level as well - I'll do that in a separate PR.

chore(rust): Use workspace package info / organize dependencies section

---

py-polars/polars/io/parquet/functions.py

docs(python): make an explicit note in `read_parquet` and `scan_parquet` about hive-style partitioning (point to `scan_pyarrow_dataset` instead)

---

crates/polars-core/src/frame/asof_join/groups.rs
py-polars/tests/unit/operations/test_join_asof.py

fix(rust): check dtypes of single-column 'by' parameter in asof-join

---

py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/test_lazy.py

Resolves #10274
**Update**: we now simply raise a `TypeError` whenever a comparison operator is called on a lazy frame.
---
~~@MarcoGorelli I mimicked the DataFrame comparison operators, with a couple of notes:~~
~~1. We can still immediately raise when columns do not match.~~
~~2. For value and/or height differences, we cannot detect until `collect()` is called.~~
~~3. Regular DataFrame comparison operator uses `pl.concat("horizontal")` which isn't supported for lazy frames, so instead I did a quick drop-in of `df1.with_context(df2)`. This works well because it will error out when the heights don't match and will still raise a height/dtype difference exception when `collect` is called.~~
~~4. The returned dataframe is still a boolean frame.~~
~~We may need more unit tests than I …

feat(python): raise `TypeError` for all LazyFrame comparison operators

---

.github/workflows/docs-python.yml
.github/workflows/docs-rust.yml

The `gh-pages` branch has ballooned the size of the repository. We do not need to keep the history here, only keeping the latest commit is fine.
Changes:
* Set `single-commit: true` for the GitHub Actions publishing our docs. See config explanation [here](https://github.com/JamesIves/github-pages-deploy-action#configuration-).
I wonder if this works well with multiple workflows trying to publish docs at the same time. We will find out!

ci: Do not keep history in `gh-pages` branch

---

crates/polars-pipe/src/executors/sinks/groupby/primitive/mod.rs
py-polars/tests/unit/streaming/test_streaming_groupby.py

fix(rust, python): fix sorted fast path in streaming groupby wrt nulls

---

crates/Makefile

Right now our Rust API docs are much larger and harder to skim than necessary because we include the full docs of all our dependencies in our `doc` build. This patch removes that.
Before:
After:

docs(rust): avoid outputting docs of dependencies

---

Cargo.toml
polars-cli/Cargo.toml
py-polars/Cargo.lock

Any `cargo build` in the workspace would result in the following warning:
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/stijn/code/polars/polars-cli/Cargo.toml
workspace: /home/stijn/code/polars/Cargo.toml
```
So the profile config wasn't doing anything. Moving the profile definition to the workspace fixes the warning. However, the `lto` and `panick` keys are not supported. See https://github.com/rust-lang/cargo/issues/9330
For now, this at least enables the `strip` option and removes the warning.
@universalmind303 Do you have any input here?

chore(cli): Move `profile` config to workspace

---

crates/polars-plan/src/dsl/function_expr/strings.rs
py-polars/tests/parametric/time_series/test_to_datetime.py
py-polars/tests/unit/namespaces/test_strptime.py

improve error message when parsing `time`, `date` or `datetime`. (inspired by `str.parse_int`)
```python
pl.Series(
name='time',
values=['15:15:15', 'a', 'b', 'c', '16:16:16', '17:17:17'],
).str.to_time(strict=True)
```
```python
pl.Series(
name='date',
values=['2019-01-01', 'a', 'b', '2019-01-02', '2019-01-03', 'c', 'd', 'e', 'a', 'a'],
).str.to_date(exact=False)
```
```python
pl.Series(
name='datetime',
values=[' 2019-01-01 00:00:00', 'XXX', '2019-01-01 00:00:00', 'XXX', 'XXX'],
).str.to_datetime(exact=False)
```

feat(python, rust): improve err msg parsing `time`, `date`, `datetime`

---

.github/workflows/lint-rust.yml
Cargo.toml
crates/Makefile

This way, we're not building the examples by default every time. You can pass `--workspace` to cargo commands to include the examples.
This is relevant because the example `python_rust_compiled_function` causes a linker error when running `cargo test` in the workspace. See [PyO3 docs](https://pyo3.rs/main/faq#i-cant-run-cargo-test-or-i-cant-build-in-a-cargo-workspace-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror).

chore(rust): Exclude examples from workspace default

---

py-polars/polars/utils/udfs.py
py-polars/tests/test_udfs.py

The following doesn't raise on `main`:
```python
def func():
import json
df = pl.DataFrame({'a': '{"a":[1,2,3]}'}).select(pl.col('a').apply(lambda x: json.loads(x)))
func()
```

feat(python): warn about inefficient apply json.loads if json is local import

---

.github/workflows/test-bytecode-parser.yml
py-polars/polars/utils/udfs.py
py-polars/tests/test_udfs.py
py-polars/tests/unit/operations/test_inefficient_apply.py

fixes the bug reported here https://github.com/pola-rs/polars/issues/9968#issuecomment-1666498093
Essentially, the bytecode is _slightly_ different between python and ipython 😧 I think many, many polars users will be running jupyter notebooks, so it's probably important to get this right
The hardest part was coming up with tests which fail on `main`
Gist of the test changes:
- introduce tests in `test_udfs` which runs `ipython` in a subprocess and checks the printed output
- modify `TEST_CASES` so that the function is a string, rather than a function, so it can be used in the above (and change `func` to `eval(func)` in the existing tests)
The only source code change is:
```diff
-    LOAD_ATTR = {"LOAD_ATTR"} if _MIN_PY311 else {"LOAD_METHOD"}
+    LOAD_ATTR = {"LOAD_ATTR", "LOAD_METHOD"} …
```

fix(python): show inefficient apply warning in ipython

---

crates/polars-lazy/src/physical_plan/expressions/apply.rs
crates/polars-lazy/src/physical_plan/expressions/binary.rs
crates/polars-lazy/src/physical_plan/expressions/ternary.rs
crates/polars-lazy/src/physical_plan/planner/expr.rs

There is overhead in calling `par_iter` or `rayon::join`. This is not worth it on literals as they are essentially free.
#10316

perf(rust, python): don't parallelize literal expressions

---

py-polars/docs/source/reference/lazyframe/miscellaneous.rst
py-polars/polars/lazyframe/frame.py
py-polars/src/lazyframe.rs
py-polars/tests/unit/test_serde.py

Closes #4395
~Not sure what to do with `LazyFrame.from_json`. It should also be called `deserialize`... both call the same method on the Rust side. Any suggestions?~ -> Will be deprecated
Changes:
* Rename `LazyFrame.write_json` to `LazyFrame.serialize`
* Rename `LazyFrame.read_json` to `LazyFrame.deserialize`
* Deprecate `LazyFrame.from_json`. Use `LazyFrame.deserialize` in combination with `StringIO`.

depr(python): Rename `LazyFrame.read/write_json` to `de/serialize`

---

crates/polars-lazy/src/frame/mod.rs
crates/polars-lazy/src/physical_plan/executors/projection.rs
crates/polars-lazy/src/physical_plan/executors/projection_utils.rs
crates/polars-lazy/src/physical_plan/executors/stack.rs
crates/polars-lazy/src/physical_plan/planner/lp.rs
crates/polars-plan/src/logical_plan/alp.rs
crates/polars-plan/src/logical_plan/builder.rs
crates/polars-plan/src/logical_plan/builder_alp.rs
crates/polars-plan/src/logical_plan/conversion.rs
crates/polars-plan/src/logical_plan/mod.rs
crates/polars-plan/src/logical_plan/optimizer/cache_states.rs
crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs
crates/polars-plan/src/logical_plan/optimizer/file_caching.rs
crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/functions/melt.rs
crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/functions/mod.rs
crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/generic.rs
crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/hstack.rs
crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/mod.rs
crates/polars-plan/src/logical_plan/optimizer/slice_pushdown_lp.rs
crates/polars-plan/src/logical_plan/options.rs
py-polars/docs/source/reference/dataframe/modify_select.rst
py-polars/docs/source/reference/lazyframe/modify_select.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/src/lazyframe.rs
py-polars/tests/unit/test_lazy.py

Semantics remain the same. Expressions cannot access columns generated in the context. This serves merely as an optimization on small data, when parallelism overhead is too costly.

feat(rust, python): allow sequential runners in select/with_columns

---

crates/polars-error/src/lib.rs
crates/polars-plan/src/dsl/function_expr/strings.rs
py-polars/tests/unit/datatypes/test_temporal.py

Demo
On `main`:
```python-traceback
In [1]: pl.Series(['2020-01-01', '2020-01-o2']).str.to_date()
ComputeError: strict date parsing failed for 1 value(s) (1 unique): ["2020-01-o2"]
You might want to try:
- setting `strict=False`
- explicitly specifying a `format`
In [2]: pl.Series(['2020-01-01', '2020-01-o2']).str.to_date(format='%Y-%m-%d')
ComputeError: strict date parsing failed for 1 value(s) (1 unique): ["2020-01-o2"]
You might want to try:
- setting `strict=False`
- explicitly specifying a `format`
In [3]: pl.Series(['00:00', '00:0l']).str.to_time(format='%H:%M')
------------------------------------------------------------------------- …
```

feat(rust, python): improve datetime parsing error message

---

py-polars/src/series/buffers.rs

@stinodego this should give you the control you need.
Added
* pointer access for binary and utf8 (this will ignore the validity and offset buffer and just get the values pointer).
* buffer access for primitive data
- index 0: values buffer
- index 1: validity buffer
* buffer access for nested data
- index 0: values buffer (can hold other nested data)
- index 1: validity buffer
- index 2: offset buffer
* buffer access for array data
- index 0: values buffer (can hold other nested data)
- index 1: validity buffer

feat(python): utility to get buffers and pointers

---

crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/ops/sort/arg_sort_multiple.rs
crates/polars-core/src/chunked_array/ops/sort/categorical.rs
crates/polars-core/src/series/implementations/categorical.rs
crates/polars-plan/src/dsl/function_expr/cat.rs
py-polars/docs/source/reference/series/categories.rst
py-polars/polars/series/categorical.py
py-polars/src/series/mod.rs
py-polars/tests/unit/series/test_categorical.py

Closes #5671, supersedes #5705, blocker for #10267
I didn't want to rebase the existing PR, so here's a fresh PR.
**WARNING: This functionality is considered experimental for now.**
Changes:
* On the Rust side:
* Rename `set_lexical_sorted` to `set_lexical_ordering`.
* Rename bit setting `LEXICAL_SORT` to `LEXICAL_ORDERING`.
* Rename `use_lexical_sort` to `uses_lexical_ordering` and make it public outside the crate
* On the Python side:
* Expose the `uses_lexical_ordering` method for categorical Series.
~I am really looking for a better name for this method, but I'm struggling to come up with something good. Help is appreciated!~
~I initially thought `is_ordered` would be appropriate. That would be the reverse of this - an ordered categorical sorts by physical type rather than lexical.~ …

feat(rust!,python): Add `Series.cat.uses_lexical_ordering`

---

py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/polars/functions/lazy.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/selectors.py
py-polars/polars/type_aliases.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/datatypes/test_struct.py
py-polars/tests/unit/operations/test_drop.py
py-polars/tests/unit/operations/test_explode.py
py-polars/tests/unit/operations/test_melt.py
py-polars/tests/unit/operations/test_pivot.py
py-polars/tests/unit/test_exprs.py
py-polars/tests/unit/test_selectors.py

~It's nice to be able to pass selectors into drop (and likely other methods; we should have a run through and see where else we can take advantage of this).~
(**Updated:** many additional methods now supported, after having just started with `drop`).
---
It's good ergonomics to be able to pass selectors into frame methods that currently only take one or more string column names. This PR adds selector support to all of the following methods:
* `drop`
* `drop_nulls`
* `explode`
* `melt`
* `partition_by`
* `pivot`
* `unique`
* `unnest`
* `unstack`
* `to_dummies`
```python
{
"foo": [1, 2, 3],
"bar": [6.0, 7.0, 8.0],
"ham": ["a", "b", "c"],
}
)
df.drop( cs.numeric() )
```

feat(python): support `selectors` in additional frame methods

---

crates/polars-ops/src/chunked_array/strings/extract.rs
crates/polars-ops/src/chunked_array/strings/mod.rs
crates/polars-ops/src/chunked_array/strings/namespace.rs

Solves https://github.com/pola-rs/polars/issues/10302.

perf(rust): re-use regex capture allocation (#10302)

---

crates/polars-core/Cargo.toml
crates/polars-core/src/chunked_array/logical/categorical/builder.rs
crates/polars-core/src/chunked_array/logical/categorical/merge.rs
crates/polars-core/src/chunked_array/logical/categorical/stringcache.rs
py-polars/Cargo.lock

Fixes https://github.com/pola-rs/polars/issues/10314.

chore(rust): remove wasm-timer dependency

---

py-polars/src/series/buffers.rs
py-polars/tests/unit/series/test_series.py

Changes:
* `get_buffer(2)` always returns None if the offsets does not exist, rather than raise an error.
* Invalid indices now raise a ValueError rather than a ComputeError.

refactor(python): Small improvement for PySeries.get_buffer

---

crates/polars-lazy/src/physical_plan/executors/groupby.rs
crates/polars-lazy/src/physical_plan/executors/groupby_partitioned.rs
crates/polars-lazy/src/physical_plan/executors/projection_utils.rs
crates/polars-pipe/src/executors/operators/projection.rs
crates/polars-plan/src/logical_plan/optimizer/cse_expr.rs
crates/polars-plan/src/logical_plan/visitor/expr.rs
crates/polars-plan/src/utils.rs
py-polars/tests/unit/test_cse.py

This activates `cse` for groupbys again.
It also improves the Identifier such that we have less collisions between non-equal expressions. This is an intermediate solution, I will follow up with a identifier based on a hash, so that we don't have to allocate.
Another improvement is that we drop the hacky solution for determining the output name of an expression that refers to a `tmp` cse. Those expressions now get a proper `alias` (if they have none), determined by the schema.

feat(rust, python): cse for groupby.agg and reduced cse collisions

---

py-polars/polars/dataframe/frame.py
py-polars/polars/selectors.py
py-polars/tests/unit/test_selectors.py

Ref: https://github.com/pola-rs/polars/pull/10255#issuecomment-1667790606
* **New**: allows selector expansion function to take a bare schema dictionary.
* Deprecates the old name `selector_column_names` for the clearer `expand_selector`.
```python
"foo": ["a", "a", "b", "b", "b"],
"baz": [100, 200, 300, 400, 500],
"bar": ["x", "x", "x", "y", "z"],
})
```
From frame -
```python
cs.expand_selector( df, cs.string() )
```
From schema dict _(new)_ -
```python
schema = { "colx":pl.Utf8, "coly":pl.Int8, "colz":pl.Float64 }
cs.expand_selector( schema, cs.numeric() )
```

feat(python): enhance `selectors` expansion function, so it can operate on a schema as well as a frame

---

py-polars/polars/utils/show_versions.py
py-polars/polars/utils/udfs.py
py-polars/pyproject.toml
py-polars/tests/unit/series/test_series.py

Docstrings for tests is the only (reasonable imo) exception left.
Most exceptions were easy fixes or ignores, the only somewhat useful exception would be to allow statements with no effect for `with pytest.raises( ... )` checks (assign to underscore per convention), but I also found a genuine mistake by removing the exception to the rule here.

chore(python): Address Ruff per file ignores

---

crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/mod.rs
crates/polars-core/src/serde/chunked_array.rs
crates/polars-core/src/serde/mod.rs
crates/polars-core/src/serde/series.rs
crates/polars-core/src/series/implementations/array.rs
crates/polars-core/src/series/implementations/binary.rs
crates/polars-core/src/series/implementations/boolean.rs
crates/polars-core/src/series/implementations/categorical.rs
crates/polars-core/src/series/implementations/dates_time.rs
crates/polars-core/src/series/implementations/datetime.rs
crates/polars-core/src/series/implementations/decimal.rs
crates/polars-core/src/series/implementations/duration.rs
crates/polars-core/src/series/implementations/floats.rs
crates/polars-core/src/series/implementations/list.rs
crates/polars-core/src/series/implementations/mod.rs
crates/polars-core/src/series/implementations/null.rs
crates/polars-core/src/series/implementations/object.rs
crates/polars-core/src/series/implementations/struct_.rs
crates/polars-core/src/series/implementations/utf8.rs
crates/polars-core/src/series/mod.rs
crates/polars-core/src/series/series_trait.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/io/test_json.py

fix #9956 
Very much work in progress, but wanted to get feedback before going further. Serializing the flags is straightforward as we can add them to the map. 
Deserialization however not so much:
- The bit flags can be of different types (ChunkedArray<T> / CategoricalChunked) hence we would need a common ground or create a temporary representation (e.g. Enum of all bitsettings). I choose the first, but this exposes u8 to the outside.
- Where to implement setting the flags. I choose to not do it on the series directly as not all ChunkedXXX implementations necessarily have flags. This would slightly complicate deserialization as we have to first construct the chunkedarray, alter the bit flags and then call `.into_series`

feat(rust): serialize flags

---

py-polars/polars/__init__.py
py-polars/polars/convert.py
py-polars/polars/dataframe/frame.py
py-polars/polars/datatypes/classes.py
py-polars/polars/interchange/__init__.py
py-polars/polars/interchange/buffer.py
py-polars/polars/interchange/column.py
py-polars/polars/interchange/dataframe.py
py-polars/polars/interchange/from_dataframe.py
py-polars/polars/interchange/protocol.py
py-polars/polars/interchange/utils.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/interchange/test_buffer.py
py-polars/tests/unit/interchange/test_column.py
py-polars/tests/unit/interchange/test_dataframe.py
py-polars/tests/unit/interchange/test_from_dataframe.py
py-polars/tests/unit/interchange/test_roundtrip.py
py-polars/tests/unit/interchange/test_utils.py

Closes #10035
Changes:
* Implement `DataFrame.__dataframe__` natively, rather than relying on pyarrow.
* Move existing `from_dataframe` implementation to the new `interchange` module. For this function, we still rely on pyarrow's implementation (for now).

feat(python): Native implementation of dataframe interchange protocol

---

py-polars/polars/dataframe/frame.py

We can get a ~4-5x speedup on `df.item()` by avoiding the unnecessary indirection that comes by passing-through to `__getitem__`. Instead, we can get away with a single `isinstance` check before calling the underlying `PySeries` directly.
(Another way to frame it would be that the _intrinsic_ speed of value retrieval hasn't changed at all, but the latency associated with setting up the call and returning the resulting value has been significantly reduced ;)
Before/after:
```
1.52 µs ± 12.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops)
338 ns ± 1.21 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops)
```

perf(python): optimise retrieval speed of values from `df.item` (~4-5x speedup)

---

crates/polars-plan/src/dsl/function_expr/boolean.rs
crates/polars-plan/src/dsl/functions/horizontal.rs
crates/polars-plan/src/dsl/functions/mod.rs
crates/polars-plan/src/logical_plan/options.rs

This removes the pipeline breaker in #10397
closes #10397

feat(rust, python): {any/all}_horizontal to expression architecture

---

py-polars/docs/requirements-docs.txt
py-polars/docs/source/conf.py
py-polars/polars/expr/datetime.py
py-polars/polars/functions/lazy.py
py-polars/polars/io/csv/functions.py
py-polars/polars/io/delta.py

Changes:
* Drop the deprecated `sphinxcontrib-napoleon` package. It was superseded by the Sphinx built-in `napoleon` extension, but we actually do not need this at all as the `numpydoc` extension already helps us parse numpy-style docstrings. `numpydoc` results in a bit nicer formatting, so we'll use that instead.
* Drop all the other `sphinxcontrib` packages, as they are required dependencies of the `Sphinx` package. No need to specify these transitive dependencies in our requirements.
* Drop the `commonmark` dependency as we do not use Markdown and it is deprecated anyway (superseded by [`markdown-it-py`](https://github.com/executablebooks/markdown-it-py)).
* Set copyright year to 2020 as per the LICENSE file.
* Add some links/explanations to the current Sphinx extension settings.
* Fix …

chore(python): Clean up some `Sphinx` settings

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/delta.py
py-polars/tests/unit/io/test_delta.py

Closes #10153  
Closes #10154 
- Casts all uints to ints with the same bitsize
- Cast all timestamps to 'us' precision
Keep getting this type-arg error, but I don't know exactly which dtypes will come from pyArrow, I am just treating it as a black box ( :
`polars/io/delta.py:324: error: Missing type parameters for generic type "list"  [type-arg`]

fix(python): Create delta compatible schema during writing

---

py-polars/polars/dataframe/frame.py
py-polars/polars/functions/lazy.py
py-polars/tests/unit/dataframe/test_df.py

We were missing test coverage for out-of-bounds column indexes passed to `df.item(…)`. This PR adds that test coverage and now raises the expected `ValueError` from the newly-optimised [^1] `item` method if necessary. 
[^1]: #10411

fix(python): raise appropriate error from newly-optimised `item` on invalid (out of bounds) column index

---

py-polars/polars/testing/asserts.py
py-polars/tests/unit/test_testing.py

Closes #10436.
Simple fix for asserts that can generate `abs(diff)` values > `max(Int64)`.

fix(python): fix potential `OverflowError` in testing asserts with huge `UInt64` diffs

---

py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/operations/test_join_asof.py

Closes #10427.
I noticed that for the right by argument, there was some argument parsing code suggesting it could take expressions, but it will fail. So it is just strings and sequence of strings.

fix(python): Fix by argument handling in join_asof

---

crates/polars-core/Cargo.toml
crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/mod.rs
crates/polars-core/src/datatypes/_serde.rs
crates/polars-core/src/serde/chunked_array.rs
crates/polars-core/src/serde/mod.rs
crates/polars-core/src/serde/series.rs
crates/polars-core/src/series/implementations/array.rs
crates/polars-core/src/series/implementations/binary.rs
crates/polars-core/src/series/implementations/boolean.rs
crates/polars-core/src/series/implementations/categorical.rs
crates/polars-core/src/series/implementations/dates_time.rs
crates/polars-core/src/series/implementations/datetime.rs
crates/polars-core/src/series/implementations/decimal.rs
crates/polars-core/src/series/implementations/duration.rs
crates/polars-core/src/series/implementations/floats.rs
crates/polars-core/src/series/implementations/list.rs
crates/polars-core/src/series/implementations/mod.rs
crates/polars-core/src/series/implementations/null.rs
crates/polars-core/src/series/implementations/object.rs
crates/polars-core/src/series/implementations/struct_.rs
crates/polars-core/src/series/implementations/utf8.rs
crates/polars-core/src/series/mod.rs
crates/polars-core/src/series/series_trait.rs
py-polars/Cargo.lock
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/io/test_json.py

- remove is_sorted_flag / _set_sorted_flag from series traits
- Use Settings struct instead of u8

refactor(rust): Simplify flag methods

---

py-polars/polars/utils/_construction.py
py-polars/tests/unit/test_constructors.py

Closes #10424.
The presence of a schema should not cause transposition on init from square numpy arrays.

fix(python): address inconsistency in init from square numpy arrays with/without an explicit schema

---

py-polars/polars/dataframe/frame.py
py-polars/polars/functions/__init__.py
py-polars/polars/functions/lazy.py
py-polars/polars/functions/lit.py
py-polars/tests/unit/functions/test_as_datatype.py
py-polars/tests/unit/functions/test_lit.py
py-polars/tests/unit/operations/test_random.py
py-polars/tests/unit/test_exprs.py

Prepares #9516
* Move `lit` to its own module - it's pretty long/complex and I want to break up the `lazy` module anyway.
* Add a `DeprecationWarning` when the input is `list` or `tuple`. 
Input:
```python
pl.select(pl.lit([1, 2]))
```
Old behavior:
```
shape: (2, 1)
┌─────┐
│     │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
└─────┘
```
New behavior (to be added later in a breaking change):
```
shape: (1, 1)
┌───────────┐
│ literal   │
│ ---       │
│ list[i64] │
╞═══════════╡
│ [1, 2]    │
└───────────┘
```
Retain the old behavior by wrapping the list in a `Series`:
```python
pl.select(pl.lit(pl.Series([1, 2])))
```
```
shape: (2, 1)
┌─────┐
│     │
│ --- │
│ i64 │
╞═════╡
│ 1   │
│ 2   │
└─────┘
```

depr(python): Deprecate behavior of list/tuple inputs for `lit`

---

crates/polars-plan/src/logical_plan/visitor/expr.rs
crates/polars-plan/src/logical_plan/visitor/lp.rs
crates/polars-plan/src/logical_plan/visitor/visitors.rs
py-polars/tests/unit/test_cse.py

I'm not sure if this is a suitable fix, but many comments in the code indicate that the purpose of `VisitRecursion::Skip` is to no longer continue visiting subexpressions(no hint of also skipping the visit of sibling exprs).  If that's indeed the case, perhaps we should at least fix these comments.
This fixes #10451.

fix(rust): Fix incorrect handling of VisitRecursion::Skip.

---

crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs
crates/polars/tests/it/lazy/predicate_queries.rs

Closes #9506
The main alteration is to introduce a tuple struct that allows to differentiate if a predicate pushdown should be blocked to the left or the right side of a join. I have only altered behaviour for "standard" left joins because I have no experience with asof-joins.

feat(rust): be more permissive on predicate pushdown to left side of left join

---

py-polars/polars/functions/eager.py

From https://stackoverflow.com/questions/76898926/
I noticed `vertical_relaxed` is not present in the `how={...}` section of the docs which can make it easy to miss.
It also seems like having an example could be useful.
Perhaps it would also make sense for `.concat()` to mention `vertical_relaxed` in the error message?

docs(python): add `vertical_relaxed` example for `pl.concat`

---

py-polars/tests/unit/io/test_lazy_csv.py
py-polars/tests/unit/io/test_parquet.py
py-polars/tests/unit/operations/test_aggregations.py
py-polars/tests/unit/operations/test_groupby.py
py-polars/tests/unit/operations/test_join.py
py-polars/tests/unit/operations/test_sort.py
py-polars/tests/unit/streaming/test_streaming.py
py-polars/tests/unit/streaming/test_streaming_cse.py
py-polars/tests/unit/streaming/test_streaming_groupby.py
py-polars/tests/unit/streaming/test_streaming_io.py
py-polars/tests/unit/streaming/test_streaming_join.py
py-polars/tests/unit/streaming/test_streaming_sort.py
py-polars/tests/unit/streaming/test_streaming_unique.py
py-polars/tests/unit/test_cse.py
py-polars/tests/unit/test_predicates.py
py-polars/tests/unit/test_projections.py
py-polars/tests/unit/test_schema.py

Since we're still getting failures on the streaming tests, another attempt at gathering all streaming tests under one runner.
If this doesn't fix it, there must be a bug in the garbage collection.

test(python): Gather all streaming tests

---

py-polars/tests/unit/test_polars_import.py

This avoids running the test locally, but still runs it in the CI.
The timing threshold is tuned for the CI machines. If your local machine is slow it will give many false positives - if it's fast you'll never trigger it even if you mess up the imports. So there's not much use running this locally.
Now that I think about it, the part that checks whether the dependencies are imported at all would make sense locally. Still, it's a relatively slow test so the `slow` marker is appropriate. It will be included with `make test-all`.

test(python): Mark import timing check as slow

---

.github/workflows/docs-python.yml
py-polars/docs/source/_static/css/custom.css
py-polars/docs/source/_static/version_switcher.json
py-polars/docs/source/conf.py

* Adds a version switcher dropdown menu in our Python API docs.

docs(python): Add version switcher to API reference

---

crates/polars-io/Cargo.toml
py-polars/Cargo.lock

chore(rust): features

---

py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/tests/unit/operations/test_statistics.py
py-polars/tests/unit/series/test_cut.py
py-polars/tests/unit/series/test_qcut.py
py-polars/tests/unit/test_errors.py

Partially addresses [#10468](https://github.com/pola-rs/polars/issues/10468)
* Rename `series` parameter to `as_series` and deprecate it. This is a remnant of the old `pl.cut` function. The method should just return a Series - possibly a struct Series if `include_breaks=True`.
* Add overload typing specification (will be removed when `as_series` is removed).
* Deprecate `category_label` and `break_point_label`. This is unnecessary parameter bloat. We should set sensible naming defaults and allow the user to overwrite it with `Series.struct.rename_fields` if they want.
* Clean up docstrings, doc exampes, tests.
To do, in a different PR:
* Split the parameter `quantiles` for `qcut` into two parameters - `probabilities` and `n_bins` (not 100% sure about the names).

depr(python): Deprecate some parameters of `cut`/`qcut`

---

py-polars/tests/unit/streaming/test_streaming_sort.py

I've seen this test fail multiple times in the same way. Example:
https://github.com/pola-rs/polars/actions/runs/5865815103/job/15903441979?pr=10495
Skipping it for now.

test(python): Skip failing test

---

.github/workflows/docs-python.yml
.github/workflows/docs-rust.yml
CONTRIBUTING.md
py-polars/docs/source/_static/version_switcher.json
py-polars/docs/source/conf.py

In preparation for [#6373](https://github.com/pola-rs/polars/issues/6373)
After merging this...
* Rust dev docs will be under: https://pola-rs.github.io/polars/docs/rust/dev
* Python dev docs will be under: https://pola-rs.github.io/polars/docs/python/dev
Stable Python docs will remain the same for now: https://pola-rs.github.io/polars/py-polars/html
Stable Rust docs remain at https://docs.rs/polars/latest/polars/

docs: Update URLs for dev documentation

---

.github/workflows/docs-python.yml
py-polars/docs/source/_static/version_switcher.json
py-polars/docs/source/conf.py

Closes [#6373](https://github.com/pola-rs/polars/issues/6373)
Very simple solution: on new tags, we build the docs like normal, but we also push it to `docs/python/version/VERSION`. That way, we'll keep the most recent docs for each version.

docs(python): Keep versioned docs

---

py-polars/pyproject.toml

This lint often makes things less readable.
https://beta.ruff.rs/docs/rules/if-else-block-instead-of-if-exp/

chore(python): Disable SIM108 lint

---

py-polars/polars/dataframe/_html.py
py-polars/tests/unit/test_cfg.py

I found `pl.Config.set_tbl_hide_column_data_types(True)` to have no effect in Jupyter Notebook, hence this commit. I didn't test this. Are there any unit tests for `HTMLFormatter`?

fix(python): respect `pl.Config` options relating to shape, column names, and types when rendering HTML

---

crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/range.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/functions/range.rs
py-polars/polars/functions/range.py
py-polars/src/functions/range.rs
py-polars/src/lib.rs
py-polars/tests/benchmark/test_release.py
py-polars/tests/unit/functions/test_range.py

**BREAKING**
Changes:
* `arange` no longer switches between `int_range` and `int_ranges` depending on the input. It is now a proper alias for `int_range`.

feat!: Make `arange` an alias for `int_range`

---

.github/workflows/test-rust.yml
crates/Makefile
crates/polars-io/Cargo.toml
crates/polars-io/src/utils.rs
crates/polars-utils/src/wasm.rs

Fixes issue #8783, where v0.29 broke the build for wasm.
This re-applies the fix from #9502, but with the `decompress` feature disabled as a merge race with #10492 caused it to break on wasm.

fix(rust): fix build for wasm

---

py-polars/docs/source/conf.py

Makes the source link (right in the picture) behave correctly when not on the dev version of the docs.

docs(python): Fix link to source code

---

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/io/test_delta.py

Closes #10540
This fixes a bug where the schema is passed twice to the `write_deltalake` method.

fix(python): Fix `write_delta` with schema in `delta_write_options`

---

crates/Makefile
crates/polars-pipe/Cargo.toml

polars-pipe always depended on ipc and async of `polars-io`, but only the `polars-pipe/compile` feature needs ipc.
This also fixes wasm support for several features.

chore(rust) clean up superfluous cross-crate feature dependencies

---

crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/tests/unit/datatypes/test_bool.py

Closes https://github.com/pola-rs/polars/issues/10370 and https://github.com/pola-rs/polars/issues/10530.

fix(rust,python): sanitize column naming in boolean ops

---

py-polars/Cargo.lock
py-polars/polars/__init__.py
py-polars/polars/functions/lazy.py
py-polars/polars/utils/__init__.py
py-polars/polars/utils/meta.py
py-polars/tests/unit/utils/test_utils.py

This should have been included in https://github.com/pola-rs/polars/pull/10527, but I missed it as it was tagged with the wrong version. It was deprecated in version `0.16.12`.
* `get_idx_type` - removed - use `get_index_type`

feat(python): Remove deprecated `get_idx_type` - use `get_index_type` instead

---

crates/polars-lazy/src/physical_plan/executors/filter.rs
crates/polars-lazy/src/physical_plan/executors/scan/mod.rs
crates/polars-lazy/src/physical_plan/planner/lp.rs
py-polars/tests/unit/operations/test_filter.py

fix(rust, python): Clear window cache after evaluate predication expr

---

py-polars/polars/convert.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/test_interop.py

Slightly extends `pl.from_arrow` constructor to allow a generator of `RecordBatch` as input (which the underlying `pa.Table.from_batches` method accepts). 
---
As well as being convenient, _might_ offer some modest memory advantages if receiving multiple batches (started looking into allowing `read_database` to take connection objects, and snowflake has a [fetch_arrow_batches](https://docs.snowflake.com/en/developer-guide/python-connector/python-connector-api#fetch_arrow_batches) method, for example) vs requiring up-front single-batch materialisation. Need to check the pyarrow source to see how it's handled there to confirm that though.

feat(python)!: allow `from_arrow` to take a generator of RecordBatches, change error type to `TypeError`

---

crates/polars-core/src/series/mod.rs
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/test_errors.py

- Add the failed column name to cast exception message.
- Add unit test for cast exception.
```python
NUM_COLS = 10
NUM_ROWS = 1000
RAND_COL = np.random.randint(0, NUM_COLS)
RAND_ROW = np.random.randint(0, NUM_ROWS)
DATA = np.random.randint(0, 100, size=(NUM_ROWS, NUM_COLS))
DATA[RAND_ROW, RAND_COL] = -1
pl.DataFrame(DATA).with_columns(
pl.all().cast(pl.UInt32),
)
```
Now outputs:
```
exceptions.ComputeError: strict conversion from `i64` to `u32` failed for column: column_8, value(s) [-1]; if you were trying to cast Utf8 to temporal dtypes, consider using `strptime`
```
Closes #10480

feat(rust, python): Add failed column to cast exception

---

py-polars/polars/functions/as_datatype.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/lazyframe/groupby.py
py-polars/polars/utils/_parse_expr_input.py
py-polars/tests/unit/functions/test_as_datatype.py
py-polars/tests/unit/operations/test_groupby.py
py-polars/tests/unit/operations/test_groupby_rolling.py
py-polars/tests/unit/operations/test_select.py
py-polars/tests/unit/operations/test_sort.py
py-polars/tests/unit/operations/test_with_columns.py
py-polars/tests/unit/utils/test_parse_expr_input.py

**!! BREAKING !!**
These are some improvements aimed at better handling inputs for `select`/`with_columns` and other methods that take expression inputs. These have already been deprecated - this is the PR that actually changes the behaviour.
Changes:
* Passing `None` as the first input is now parsed as `lit(None)` rather than be ignored.
* Passing an iterable (e.g. `select(["a", "b"])`) is still supported, but can no longer be combined with other positional parameters. If multiple positional parameters are supplied, the first argument is always assumed to be an expression input, rather than a list of expression inputs.
* Methods that accept named expression inputs (`select`, `with_columns`, `agg`, `struct`) no longer have a separate argument for  the first expression input. This means …

feat(python)!: Improve consistency of parsing expression input

---

crates/polars-arrow/src/kernels/mod.rs
crates/polars-arrow/src/kernels/pow.rs
crates/polars-plan/src/dsl/function_expr/pow.rs
py-polars/Cargo.lock

splitting this out from #10446 as it's gonna take me a bit longer to figure that one out
but this is simple and already seems to improve performance
timing
```python
size = 100_000_000
df = pl.DataFrame({'a': np.random.randint(0, 4, size=size), 'b': np.random.randn(size)}, schema_overrides={'a': pl.UInt8})
print(ipython.run_line_magic("timeit", "df.select(pl.col('a').pow(pl.col('a')))"))
print(ipython.run_line_magic("timeit", "df.select(pl.col('b').pow(pl.col('b')))"))
```
on kaggle I see:
- before: `8.35 s ± 2.41 s`, `4.42 s ± 21.2 ms`
- after: `7.29 s ± 2.3 s`, `2.92 s ± 18.6 ms`
source: https://www.kaggle.com/code/marcogorelli/polars-timing/notebook?scriptVersionId=140186516

perf(rust, python): use binary abstraction in pow

---

py-polars/polars/lazyframe/frame.py

docs(python): fix out-of-date explain default parameter

---

crates/polars-lazy/src/physical_plan/planner/lp.rs
py-polars/tests/unit/operations/test_filter.py

fix(rust, python): Take input_schema to create physical expr for Selection

---

crates/polars-arrow/src/kernels/atan2.rs
crates/polars-arrow/src/kernels/mod.rs
crates/polars-plan/src/dsl/function_expr/trigonometry.rs

similar to #10562 , noticed another place where the less performant pattern is used

perf(rust, python): use binary abstraction for atan2

---

crates/polars-core/src/frame/asof_join/asof.rs
crates/polars-core/src/frame/asof_join/groups.rs
crates/polars-core/src/frame/asof_join/mod.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/operations/test_join_asof.py

Resolves #10462, Resolves #10534, and Resolves #10532. Main changes:
1. Implemented tolerance for `strategy="nearest"`
2. Increase test coverage for join_asof with nearest.
3. Allow `timedelta` objects for the tolerance input.

fix(rust): join_asof missing `tolerance` implementation, address edge-cases

---

py-polars/Makefile

Until running the equivalent commands I was getting some mysterious new typing errors from `pre-commit` checks that a vanilla `make requirements` did not fix. Have confirmed locally that this properly refreshes unpinned packages/deps, ensuring that your local env will match what runs in CI (which does a fresh install).
If preferred, could make this a separate option, say `make requirements-clean`? (Though given that, post initial install, you're likely to _want_ it to be thorough I'm not sure there's any real value in two options - I'd say just make this one robust by default unless there's a compelling reason otherwise 🤔).

chore(python): ensure that `make requirements` fully refreshes unpinned packages/deps

---

crates/polars-core/src/chunked_array/arithmetic/decimal.rs
crates/polars-core/src/chunked_array/arithmetic/mod.rs
crates/polars-core/src/chunked_array/arithmetic/numeric.rs
crates/polars-core/src/chunked_array/bitwise.rs
crates/polars-core/src/chunked_array/comparison/mod.rs
crates/polars-core/src/chunked_array/ops/apply.rs
crates/polars-core/src/chunked_array/ops/arity.rs
crates/polars-core/src/chunked_array/ops/downcast.rs
crates/polars-core/src/chunked_array/ops/filter.rs
crates/polars-core/src/chunked_array/ops/min_max_binary.rs
crates/polars-core/src/chunked_array/ops/mod.rs
crates/polars-core/src/chunked_array/ops/repeat_by.rs
crates/polars-core/src/series/arithmetic/borrowed.rs
crates/polars-ops/src/chunked_array/list/sets.rs
crates/polars-ops/src/series/ops/floor_divide.rs
crates/polars-plan/src/dsl/function_expr/pow.rs
crates/polars-plan/src/dsl/function_expr/trigonometry.rs

take @orlp 's new StaticArray trait indirections and clean up a lot of binary chunkedarray logic that can be made dry.
@MarcoGorelli this makes binary functions much easier to deal with for both kernels as well as elementwise functions.

refactor(rust): make binary chunkedarray functions DRY

---

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/dataframe/test_df.py

```python
In [1]:     df = pl.DataFrame({"a": [2, 1, 3], "b": [1, 2, 3]})
...:     s = pl.Series("c", [True, False, True])
...:     df.replace("a", s)
<ipython-input-1-f6d07799c17b>:3: DeprecationWarning: `replace` is deprecated. DataFrame.replace is deprecated and will be removed in a future version. Please use
df = df.with_columns(new_column.alias(column_name))
instead.
df.replace("a", s)
Out[1]: 
shape: (3, 2)
┌───────┬─────┐
│ a     ┆ b   │
│ ---   ┆ --- │
│ bool  ┆ i64 │
╞═══════╪═════╡
│ true  ┆ 1   │
│ false ┆ 2   │
│ true  ┆ 3   │
└───────┴─────┘
```

refactor(python): deprecate DataFrame.replace

---

crates/polars-core/src/serde/chunked_array.rs
py-polars/tests/unit/test_serde.py

fix(rust, python): Fix serialization for categorical chunked.

---

Cargo.toml
crates/polars-core/src/chunked_array/comparison/mod.rs
crates/polars-plan/src/dsl/function_expr/boolean.rs
crates/polars-plan/src/dsl/mod.rs
py-polars/Cargo.lock
py-polars/polars/expr/expr.py
py-polars/polars/expr/list.py
py-polars/polars/functions/aggregation/vertical.py
py-polars/polars/series/list.py
py-polars/polars/series/series.py
py-polars/src/expr/general.rs
py-polars/tests/unit/datatypes/test_bool.py
py-polars/tests/unit/datatypes/test_list.py
py-polars/tests/unit/series/test_all_any.py

Closes #10550 
* `all` will now ignore null values by default, rather than treat them as `False`.
* This change is introduced by updating `arrow2` to a version that includes [this breaking change](https://github.com/jorgecarleitao/arrow2/pull/1545).
Before:
```python
>>> pl.Series([True, None]).all()
False
```
After:
```python
>>> pl.Series([True, None]).all()
True
```
* Fix the implementation of Kleene logic. The output was incorrect in some cases, this has been corrected.
* Rename parameter `drop_nulls` to `ignore_nulls`, to better align with the rest of our API.
* Make the parameter `drop_nulls` keyword-only. _(all boolean flags must be keyword only)_

feat!: Change behavior of `all` - fix Kleene logic implementation for `all`/`any`

---

.github/workflows/lint-py-polars.yml
py-polars/Cargo.lock
py-polars/Makefile

If we require the inclusion of the lockfile, it should remain up-to-date.
I updated the CI linting job and the Makefile to run `cargo clippy --locked`, which will fail if the lockfile is outdated.

ci: Enforce up-to-date `Cargo.lock`

---

crates/polars-core/Cargo.toml
crates/polars-core/src/chunked_array/ops/apply.rs
crates/polars-core/src/chunked_array/ops/bit_repr.rs
crates/polars-core/src/chunked_array/ops/is_in.rs
crates/polars-core/src/chunked_array/ops/min_max_binary.rs
crates/polars-core/src/datatypes/from_values.rs
crates/polars-core/src/datatypes/mod.rs
crates/polars-core/src/datatypes/static_array.rs
crates/polars-core/src/frame/groupby/into_groups.rs
crates/polars-core/src/series/arithmetic/borrowed.rs
py-polars/tests/unit/operations/test_is_in.py

Can reduce the number of kernels with the new traits that can construct from `StaticArray`'s.
closes #10613
closes #9105

feat(rust, python): propagate null is in `is_in` and more generic array construction

---

crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs
py-polars/tests/unit/operations/test_is_in.py

fix(rust, python): fix int/float downcast in `is_in`

---

Cargo.toml
crates/polars-core/src/chunked_array/arithmetic/mod.rs
crates/polars-core/src/chunked_array/arithmetic/numeric.rs
crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/mod.rs
crates/polars-core/src/chunked_array/ops/abs.rs
crates/polars-core/src/chunked_array/ops/aggregate/var.rs
crates/polars-core/src/chunked_array/ops/apply.rs
crates/polars-core/src/chunked_array/ops/is_in.rs
crates/polars-core/src/chunked_array/ops/mod.rs
crates/polars-core/src/datatypes/from_values.rs
crates/polars-core/src/functions.rs
crates/polars-core/src/series/arithmetic/borrowed.rs
crates/polars-core/src/series/ops/round.rs
crates/polars-ops/src/chunked_array/binary/namespace.rs
crates/polars-ops/src/chunked_array/strings/json_path.rs
crates/polars-ops/src/chunked_array/strings/namespace.rs
crates/polars-ops/src/frame/pivot/mod.rs
crates/polars-ops/src/series/ops/floor_divide.rs
crates/polars-ops/src/series/ops/log.rs
crates/polars-plan/src/dsl/function_expr/pow.rs
crates/polars-plan/src/dsl/function_expr/sign.rs
crates/polars-plan/src/dsl/function_expr/strings.rs
crates/polars-plan/src/dsl/function_expr/trigonometry.rs
crates/polars-time/src/base_utc_offset.rs
crates/polars-time/src/dst_offset.rs
crates/polars/src/docs/eager.rs
py-polars/Cargo.lock

Also speeds up `apply` for string and binary dtypes.

refactor(rust): remove unused apply functions and add fallible generic apply functions

---

py-polars/polars/utils/udfs.py
py-polars/polars/utils/various.py

originally reported here: https://github.com/pandas-dev/pandas/issues/54628

chore(python): fix potential memory leak from usage of `inspect.currentframe`

---

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/rename.rs
py-polars/tests/unit/test_projections.py

fix(rust, python): fix rename + projection pushdown

---

crates/polars-core/src/series/mod.rs
crates/polars-core/src/utils/series.rs
crates/polars-io/src/csv/buffer.rs
crates/polars-io/src/csv/read_impl/batched_mmap.rs
crates/polars-io/src/csv/read_impl/batched_read.rs
crates/polars-io/src/csv/read_impl/mod.rs
crates/polars/tests/it/io/csv.rs
py-polars/tests/unit/io/test_csv.py

fix(rust, python): respect 'ignore_errors=False' in csv parser

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/excel/_write_utils.py
py-polars/polars/selectors.py
py-polars/polars/type_aliases.py
py-polars/tests/unit/io/test_excel.py

Continues the recent expansion of selector capabilities in other frame methods, integrating additional support for `write_excel`, specifically with respect to...
* `column_formats`
* `conditional_formats`
* `column_widths`
* `column_totals`
* `row_totals`
Demonstrates use of selectors (in place of column names) in the updated params:
```python
"id": ["aaa", "bbb", "ccc", "ddd", "eee"],
"q1": [100, 55, -20, 0, 35],
"q2": [30, -10, 15, 60, 20],
"q3": [-50, 0, 40, 80, 80],
"q4": [75, 55, 25, -10, -55],
})
df.write_excel(  
table_style = "Table Style Medium 23",
column_formats = {
cs.starts_with("q"): {"italic": True},
},
conditional_formats = {
cs.starts_with("q"): {
"type": "2_color_scale",
"min_color": "#95b3d7",
"max_color": "#ffffff",
},
}, …
```

feat(python): support selector usage in `write_excel` arguments

---

py-polars/polars/functions/aggregation/vertical.py
py-polars/tests/unit/functions/aggregation/test_vertical.py
py-polars/tests/unit/functions/test_functions.py

Not sure if this should be merged yet - it's quite widely used functionality, and it was only deprecated on `0.18.7`. Let's leave this for `1.0`?
* Remove overloaded functionality for `any`, `all`, `min`, `max`, `sum`, `cumsum`
* No longer accepts `Series` input
* No longer calculates a horizontal aggregation when given multiple inputs

feat(python)!: Remove deprecated behavior from vertical aggregations

---

py-polars/polars/dataframe/_html.py

feat(python, rust): preserve whitespace in notebook output

---

Cargo.toml
py-polars/tests/unit/datatypes/test_list.py

feat(rust, python): supports cast to list

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/_utils.py
py-polars/polars/io/delta.py
py-polars/tests/unit/io/test_delta.py

In the recent change, there was fixed mapping between timestamps in ms/ns to us precision. However, delta-rs writes everything in non-timezone timestamps. So we can safely cast any timestamp, regardless of the timezone or precision, simply to us precision with no TZ. 
This change will prevent this from happening when you're writing a delta table:
`Exception: Schema error: Invalid data type for Delta Lake: Timestamp(Millisecond, Some("UTC"))
`
Changed the test cases to include time zones in some of them.

fix(python): fix missing timestamp cast in delta schema

---

crates/polars-io/src/csv/read.rs
crates/polars-io/src/csv/read_impl/batched_mmap.rs
crates/polars-io/src/csv/read_impl/batched_read.rs
crates/polars-lazy/src/frame/csv.rs
crates/polars-pipe/src/executors/sources/csv.rs
crates/polars/tests/it/io/csv.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/io/_utils.py
py-polars/polars/io/csv/functions.py
py-polars/polars/lazyframe/frame.py
py-polars/src/dataframe.rs
py-polars/src/lazyframe.rs
py-polars/tests/unit/io/test_csv.py

Skip schema inference altogether. Solution for issue raised in #10585

feat(python): csv: add schema argument

---

py-polars/docs/source/reference/dataframe/descriptive.rst
py-polars/docs/source/reference/expressions/list.rst
py-polars/docs/source/reference/lazyframe/miscellaneous.rst
py-polars/docs/source/reference/lazyframe/modify_select.rst
py-polars/docs/source/reference/series/list.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/list.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/list.py
py-polars/polars/utils/deprecation.py
py-polars/tests/unit/test_serde.py
py-polars/tests/unit/utils/test_deprecation.py

Closes #8004 
The `deprecate_renamed_methods` decorator has a big downside: the deprecated methods are no longer available in the docs. 
While this is nice from a "move fast and break things" standpoint, it's important that the docs contain the deprecated functionality to help people upgrade their code to newer versions.
* Remove `deprecate_renamed_methods` utility
* Re-add the removed methods and deprecate them with `deprecate_renamed_function`
* Add missing `DataFrame.approx_n_unique` method

refactor(python): Remove `deprecate_renamed_methods` util

---

crates/polars-core/src/chunked_array/ops/aggregate/mod.rs
py-polars/tests/unit/series/test_series.py

fix(rust, python): Sorted Utf8Chunked max_str and min_str should consider null value

---

crates/polars-core/src/chunked_array/ops/aggregate/mod.rs
crates/polars-core/src/chunked_array/ops/fill_null.rs
py-polars/tests/unit/series/test_series.py

feat(rust, python): Support min and max strategy for binary & str columns fill null

---

py-polars/polars/lazyframe/frame.py

Docs mentioned `use_pyarrow`, but this does not exist on `sink_parquet`.

docs(python): Fix minor issue with `sink_parquet` docs

---

crates/polars-core/src/chunked_array/builder/list/binary.rs
py-polars/tests/unit/operations/test_explode.py

fix(rust, python): Set the correct fast_explode flag for ListUtf8ChunkedBuilder

---

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/test_interop.py

New version of `pyarrow` just dropped. Apparently it changes interoperability with pandas slightly for date/datetime types. Had to adjust one of our tests.
EDIT: Also had to update one of our doctests because the `repr` of `RecordBatch` has changed.

test(python): Update for new pyarrow `13.0.0` behavior

---

py-polars/polars/interchange/buffer.py
py-polars/polars/interchange/column.py
py-polars/polars/interchange/dataframe.py
py-polars/polars/interchange/protocol.py

This will be useful for type checking the `from_dataframe` implementation I am working on. And this verifies our the API of our interchange object is correct.

feat(python): Explicitly implement `Protocol` for interchange classes

---

crates/polars-arrow/src/kernels/rolling/window.rs
py-polars/tests/unit/datatypes/test_temporal.py

fix(rust, python): re-sort buffer when update window swap the whole buffer

---

crates/polars-core/src/chunked_array/ops/rolling_window.rs
py-polars/tests/unit/operations/test_rolling.py

fix(rust, python): Reused input series in rolling_apply should not be orderly

---

crates/polars-arrow/src/kernels/time.rs
crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs

Noticed while looking into #10090
I probably introduced this inefficiency the first time round, sorry about that

perf(rust, python): parse time zones outside of downcast_iter() in replace_time_zone

---

crates/polars-time/src/upsample.rs

This request does not refer to an open issue. 
It is just a doc clarification to make using polars-time::upsample a bit easier.

doc(rust): example for upsample method and changed period to every

---

crates/polars-ops/src/series/ops/arg_min_max.rs
py-polars/tests/unit/namespaces/test_list.py
py-polars/tests/unit/series/test_series.py

This based on #10708 and fixes #10707.
Some tests may fail because we changed `arg_min` and `arg_max` behavior. I will fix that cases one by one.

fix(rust, python): Keep min/max and arg_min/arg_max consistent.

---

crates/polars-core/src/named_from.rs

This commit fixes Issue #9182 and makes it possible to create a Series from Vector of empty Series.

fix(rust): Build Series from empty Series vector

---

py-polars/docs/source/reference/testing.rst

Closes #10736.
Adds an extra note about `testing` module import; it's implicit in most of the examples, but no harm making it explicit.

docs(python): add note to `testing` docs about module import

---

crates/polars-ops/src/series/ops/various.rs
crates/polars-plan/src/dsl/mod.rs
py-polars/polars/expr/expr.py
py-polars/polars/expr/list.py
py-polars/polars/series/series.py
py-polars/src/expr/general.rs
py-polars/src/series/mod.rs
py-polars/tests/unit/datatypes/test_struct.py
py-polars/tests/unit/operations/test_value_counts.py
py-polars/tests/unit/series/test_series.py

Fixes #10732
Also did a bunch of code cleanup.
* Add a check when constructing the value counts struct.
* Dispatch `Series.value_counts` to the expression.
* Rename `multithreaded` param to `parallel` - this is more in line with other functions like `concat`.
* Clean up docstrings etc.

fix(rust!, python): Error on `value_counts` on column named `"counts"`

---

crates/polars-core/src/chunked_array/ops/repeat_by.rs
py-polars/tests/unit/dataframe/test_df.py

feat(rust, python): repeat_by should also support broadcasting of LHS

---

crates/polars-core/src/chunked_array/random.rs
py-polars/tests/unit/operations/test_random.py

Sampling n from an empty dataframe panics if with_replacement=True. A test case is added documenting the behavior of sample_n and sample_frac for with_replacement and without.
I am not really sure why ensure_shape is used without symmetry, but it appears intentional.
```rust
let subdf = df.sample_n(50000, true, false, None)?;
```
```
shape: (0, 4)
┌──────────────┬─────┬─────┬─────┐
│ t            ┆ x   ┆ y   ┆ z   │
│ ---          ┆ --- ┆ --- ┆ --- │
│ datetime[μs] ┆ f64 ┆ f64 ┆ f64 │
╞══════════════╪═════╪═════╪═════╡
└──────────────┴─────┴─────┴─────┘
thread 'tokio-runtime-worker' panicked at 'Uniform::new called with `low >= high`', /Users/jwtrueb/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rand-0.8.5/src/distributions/uniform.rs:567:1
0: rust_begin_unwind
at …
```

fix(rust): Prevent panic on sample_n with replacement from empty df

---

py-polars/polars/dataframe/_html.py

Follow-up to #10644, closes #10704.
This improves the previous CSS `whitespace` style definition update/fix such that long strings _can_ still wrap in Notebooks, while preserving accurate whitespace rendering (eg: not collapsing it).

fix(python): whitespace CSS in Notebook HTML updated to use `pre-wrap` instead of `pre`

---

.github/workflows/lint-global.yml
crates/polars-arrow/src/kernels/rolling/mod.rs
py-polars/docs/requirements-docs.txt
py-polars/polars/io/database.py
py-polars/requirements-dev.txt
py-polars/requirements-lint.txt

I got a notification that `connectorx` has finally released a new version, so we can unpin the pre-release version. Also took the opportunity to bump our other Python deps.

chore(python): Unpin `connectorx` and bump other Python dependencies

---

crates/Makefile

This recent change: #10733 fixed the build for decompress on wasm, previously broken by https://github.com/pola-rs/polars/pull/10492#issuecomment-1681031677.

chore(rust) enable wasm test for decompress feature

---

py-polars/tests/unit/io/test_database_write.py

Apparently, the `main.` prefix for table names is no longer needed.

test(python): Fix test failing due to new `adbc` release

---

py-polars/Cargo.lock
py-polars/Cargo.toml
py-polars/tests/unit/io/test_lazy_json.py

Closes https://github.com/pola-rs/polars/issues/10661, https://github.com/pola-rs/polars/issues/9791, https://github.com/pola-rs/polars/issues/10034.
Ultimately I did not figure out what the issue was, and while trying to edit the code in a local copy of `simd-json` I noticed that the issue does not occur on the latest `main` (10.6). Then I realized we have an old patched version (10.0) of `simd-json` by ritchie, that fixes a bug that is also now fixed on `main`. So I bumped the dependency, removing the patch, and that also fixed the issue. So I suppose it was a bug in `simd-json` somewhere that has since been fixed.

fix(rust): fix unicode truncation in json parsing

---

crates/polars-arrow/src/data_types.rs
crates/polars-core/src/chunked_array/ops/aggregate/float_sum.rs
crates/polars-core/src/chunked_array/ops/aggregate/mod.rs

Closes https://github.com/pola-rs/polars/issues/10553. This also allows us to always let us use SIMD regardless of alignment of the input data, and without the result depending on alignment.
Evaluation program:
```python
import timeit
ones = pl.ones(800_000_000, dtype=pl.Float32, eager=True)
print(ones.sum())
print(timeit.timeit(lambda: ones.sum(), number=10))
print(ones.tail(-1).sum())
print(timeit.timeit(lambda: ones.tail(-1).sum(), number=10))
```
Before:
```python
268435456.0
0.5462445419980213
16777216.0
6.95986499999708
```
After:
```python
800000000.0
0.5480892079940531
800000000.0
0.6045084579964168
```

feat(rust): add pairwise float sum implementation

---

py-polars/polars/functions/whenthen.py

docs(python): Document chained when-then behaviour more prominently

---

crates/polars-arrow/src/compute/decimal.rs

Avoid incorrect parsing of trailing characters 12ABC.123BC
See fix #10118

fix(rust): string to decimal parsing 

---

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/io/test_database_write.py

Ref: [#10763](https://github.com/pola-rs/polars/pull/10763#issuecomment-1696945452).
Splits the single "write database" unit test into the following:
* `test_write_database_create`
* `test_write_database_append`
* `test_write_database_create_quoted_tablename`
* `test_write_database_errors`
Due to https://github.com/apache/arrow-adbc/issues/1000, the `test_write_database_create_quoted_tablename` check is skipped when run for `adbc_driver_sqlite` version 0.6.0.

test(python): refactored `write_database` unit tests to properly separate concerns

---

.github/workflows/benchmark.yml
.github/workflows/test-bytecode-parser.yml
CONTRIBUTING.md
Makefile
dprint.json
py-polars/Makefile

Preparation for #10560
Building the user guide requires `mkdocs`, which is a Python dependency. After moving the docs into this repo, we'll also have Python files (code snippets) in the `docs` folder. Because of this, we'll want to run some Python commands from the root of the repo, so it makes sense to move the Python virtual environment to the repo root.
This shouldn't impact anyone's workflow. All existing make commands should still work identically.
* Add top-level Makefile including the following commands (can add more commands later):
* `.venv`
* `requirements`
* `clean`
* `help`
* Adjust the Python Makefile to dispatch to the top-level Makefile for `.venv` / `requirements` commands and use the right venv path.
* Update other `.venv` references
* Update bytecode parser workflow to …

chore(python): Create `.venv` in repo root

---

crates/polars-pipe/src/executors/sinks/ordered.rs
crates/polars-pipe/src/pipeline/convert.rs
py-polars/tests/unit/io/files/only_header.csv
py-polars/tests/unit/streaming/test_streaming_io.py

fix(rust, python): Reading an only-header csv file in streaming mode should not panic

---

py-polars/tests/unit/io/test_parquet.py
py-polars/tests/unit/streaming/test_streaming.py
py-polars/tests/unit/streaming/test_streaming_io.py

This will make sure the `sink` tests are ran on the same runner as other streaming tests. This is important due to possible test failures caused by garbage collection of disk spill.
Fortunately, we haven't had many spurious test failures recently, but I did spot one... I figured this might be the cause.

test(python): Move sink tests to streaming module

---

py-polars/polars/dataframe/frame.py
py-polars/polars/datatypes/classes.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/test_datatypes.py

DataFrames are iterable, with an explicit python-side `__iter__` implementation, returning their component Series in order like so:
```python
df = pl.DataFrame( {"a": [1,2], "b":[2,3], "c":[3,4]} )
list( df )
```
You'll never guess what `list(reversed(df))` currently does though :))
Instead of returning the Series above in reverse order... it returns one DataFrame per row, in reverse row order. 
```python
list(reversed(df))
```
(If anyone can tell me why without looking pretty hard at the code I'll buy you a coffee, heh).
This PR fixes it with a simple/explicit `__reversed__` implementation so that we get the Series in reverse order instead, as expected, consistent with its non-reversed behaviour.
---
**Also:**
* Allows Struct dtype fields to be iterated in reverse too.
* Adds several …

fix(python): behaviour of `reversed(df)`

---

py-polars/polars/interchange/buffer.py
py-polars/polars/interchange/column.py
py-polars/polars/interchange/dataframe.py
py-polars/polars/interchange/protocol.py
py-polars/tests/unit/interchange/test_buffer.py
py-polars/tests/unit/interchange/test_column.py
py-polars/tests/unit/interchange/test_dataframe.py

Instead of stating with every RuntimeError that the operation is not zero copy, I created a `CopyNotAllowedError`. It subclasses `RuntimeError`, so this doesn't break anything.

feat(python): Add custom error for `allow_copy=False`

---

py-polars/polars/dataframe/frame.py

Realised we can be more explicit about the `__iter__` (and`__reversed__`) typing on DataFrame; updated `Iterator[Any]` as `Iterator[Series]` instead.

feat(python): minor typing improvement for DataFrame.__iter__

---

py-polars/polars/dataframe/frame.py
py-polars/polars/dataframe/group_by.py
py-polars/polars/expr/expr.py
py-polars/polars/functions/lazy.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/lazyframe/group_by.py
py-polars/polars/series/series.py
py-polars/polars/utils/udfs.py

Various updates for assorted `map_*` docstrings. Includes additional information, minor clarifications, and a new example showing window function context via `over` grouping.

docs(python): map-related docstring updates

---

py-polars/polars/selectors.py
py-polars/tests/unit/test_selectors.py

Extends the available suite of dtype-based selectors with...
* `cs.categorical()`
* `cs.date()`
* `cs.time()` 
**Update 1**: 
* `cs.binary()`
* `cs.boolean()`
**Update 2**: 
* `cs.object()`

feat(python): add `binary`, `boolean`, `categorical`, `date`, `object`, and `time` selectors

---

crates/polars-plan/src/dsl/function_expr/temporal.rs
crates/polars-time/src/date_range.rs
crates/polars-time/src/windows/calendar.rs
py-polars/tests/unit/functions/range/test_date_range.py
py-polars/tests/unit/functions/range/test_time_range.py

Fixes:
* Intervals of zero duration are now correctly handled (instead of panicking)
* Empty columns are now correctly handled (instead of panicking)
* Columns with more than 1 value will now throw an error, instead of picking the first value. Users should explicitly state `.first()` if they want to pass the first value of a column to `time_range`/`date_range`
Misc:
* Make sure the naming of the `start`, `end`, and `interval` parameters is consistent internally.

fix: Improve bound checks on temporal ranges

---

crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/temporal.rs
crates/polars-time/src/date_range.rs
crates/polars-time/src/group_by/dynamic.rs
crates/polars-time/src/lib.rs
crates/polars-time/src/upsample.rs
crates/polars-time/src/windows/calendar.rs
crates/polars-time/src/windows/test.rs
py-polars/Cargo.lock

Preparation for #10006 
`time_range` and `date_range` are now quite clean.
`date_range` must be re-implemented to work with `i32` instead of `i64`.
`datetime_range` requires a lot more work to clean up...
At least they are now separated, so the new `datetime_range` expression can be added (in a separate PR).

refactor(rust): Further refactor temporal range functions

---

crates/polars-core/src/chunked_array/mod.rs
crates/polars-core/src/chunked_array/ops/apply.rs
crates/polars-core/src/series/mod.rs
crates/polars-time/src/chunkedarray/time.rs
crates/polars-time/src/chunkedarray/utf8/infer.rs

This will let us avoid writing `let mut ca = ...; ca.rename(...); ca` all the time.

refactor: introduce with_name for Series/ChunkedArray

---

py-polars/polars/exceptions.py
py-polars/polars/io/database.py
py-polars/tests/unit/io/test_database_read.py

Closes #10843.
The `read_database` method only handles (and _should_ only handle) statements that return query results; this update just helps make that clear by raising a more explicit exception when given unsuitable SQL.
This PR covers the vast majority of invalid query types; note that (due to differences in backend SQL) we do not positively identify "SELECT"-type queries (as these can also start "WITH", be stored procedures with vendor-specific syntax, etc) - rather, we identify known _invalid_ query types. This means that we shouldn't inadvertently reject a valid query from a lesser-known dialect.
```python
from sqlalchemy import create_engine
conn = create_engine("sqlite:///")
pl.read_database("INSERT INTO xyz VALUES ('polars')", conn)
```
**Before**
_(as no …

feat(python): raise a more helpful error when non-query statements passed to `read_database`

---

crates/polars-core/src/frame/hash_join/args.rs
crates/polars-error/src/lib.rs
crates/polars-lazy/src/physical_plan/expressions/aggregation.rs
crates/polars-sql/src/sql_expr.rs

If only supplied a single argument, `polars_err!(Variant: "format string")` would interpret the first argument as an expression, not as a formatting literal. So things like `polars_err!(Variant: "{foo}")` were broken and would simply print `{foo}`.
This fix also uncovered a couple places where the formatting was just broken.

fix: repair polars_err string interpolation

---

py-polars/src/functions/lazy.rs

Closes #10861.
(Looks like an accidental/leftover debugging remnant).

fix(rust): remove debug `println!` from datetime fn

---

py-polars/polars/io/database.py
py-polars/tests/unit/io/test_database_read.py

Some additional internal comments about what is being done, and improved internal member naming (`driver_name`, rather than `driver`), and an explicit entry in the `Notes` section to reassure the caller that:
1) If we have to create a temporary cursor we will automatically clean it up.
2) We will _never_ attempt to close/clean-up connections/cursors passed-in to the function.

docs(python): add a note about `read_database` connection/cursor behaviour

---

crates/polars-time/src/chunkedarray/utf8/infer.rs
py-polars/tests/unit/io/test_csv.py

this addresses the second half of #10826 (thanks @JulianCologne for the easy-to-reproduce report, this kind of thing is essential for making software better)
doesn't close the issue yet as the first part is unaddressed, will think about that later
Solution:
the pattern was being inferred as `Pattern::DateDMY`, but that wasn't getting matched in
```python
(Pattern::DatetimeDMY, TimeUnit::Milliseconds)
```
, even though `Datetime` can handle such patterns.
So, I just did
```diff
- (Pattern::DatetimeDMY, TimeUnit::Milliseconds)
+ (Pattern::DatetimeDMY | Pattern::DateDMY, TimeUnit::Milliseconds)
```
and similarly for the other arms
---
Note: this one's easier to review hiding whitespace: https://github.com/pola-rs/polars/pull/10877/files?diff=unified&w=1

fix(rust, python): fix bug where datetimes were not parsed in read_csv when pattern had no hour or minute

---

.github/ISSUE_TEMPLATE/bug_report_python.yml
.github/ISSUE_TEMPLATE/bug_report_rust.yml

I often spend several triage iterations requesting for logs. If we ask those immediately, this croudsources the work we have to do and often can given an immediate idea of what is going on.

chore: request verbose logging output of minimal reproducable examples

---

crates/polars-time/src/chunkedarray/utf8/mod.rs
crates/polars-utils/src/cache.rs
crates/polars-utils/src/lib.rs

This should not have changed any semantics.
If we find it to be useful somewhere else we can move `CachedFunc` to `utils` or something.

refactor: eliminate repetition in utf8 datetime functions

---

py-polars/docs/source/reference/expressions/col.rst
py-polars/docs/source/reference/expressions/columns.rst
py-polars/polars/functions/__init__.py
py-polars/polars/functions/col.py
py-polars/polars/functions/lazy.py
py-polars/tests/unit/functions/test_col.py
py-polars/tests/unit/test_exprs.py
py-polars/tests/unit/test_lazy.py

Closes #10866, closes #7398
* Implement `col` as a factory object rather than a function. It supports `col.foo` as an alias for `col("foo")`.

feat(python): Add syntactic sugar for `col("foo")` -> `col.foo`

---

py-polars/polars/io/database.py
py-polars/tests/unit/io/test_database_read.py

Covers both `read_database` and `read_database_uri`. 
Database return types can often be overly broad; this allows individual column dtypes to be specified more exactly where those dtypes are better-known by the caller.
Also: added a performance note to the docs (prefer loading from URI if you have a sqlalchemy/dbapi2 connection and the backend is supported by `connectorx`).
Setup:
```python
import sqlite3
conn = sqlite3.connect("test.db")
conn.executescript(
"""
CREATE TABLE test_data (id INTEGER PRIMARY KEY, name TEXT NOT NULL, value FLOAT);
INSERT INTO test_data(name,value) VALUES ('misc',100.0), ('other',-99.5);
"""
)
```
Sample queries:
```python
pl.read_database(
connection=conn,
query="SELECT * FROM test_data",
)
pl.read_database(
connection=conn,
query="SELECT * FROM test_data", …
```

feat(python): support schema overrides for frames created from databases

---

crates/polars-core/src/serde/series.rs
py-polars/tests/unit/test_serde.py

fix(rust): Retain original dtype when deserializing an empty list

---

crates/polars-plan/src/dsl/function_expr/range/date_range.rs
crates/polars-time/src/windows/duration.rs
py-polars/tests/unit/functions/range/test_date_range.py

~We checked the interval for `nanoseconds == 0`, which is wrong: `24h` should give the same results as `1d`.~
Actually, the original check was correct. I am rebranding this as a refactor.

refactor(rust): Add duration method for checking full days

---

crates/polars-lazy/src/tests/optimization_checks.rs
crates/polars-lazy/src/tests/predicate_queries.rs
crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs
crates/polars/tests/it/lazy/predicate_queries.rs

Closes #7247
I have limited it to left and inner joins for the sole reason that I don't really have experience with the other types. If this can be extended, it is an easy fix.

feat(rust): apply left side predicate pushdown also to right side if all predicate columns are also join columns

---

crates/polars-sql/src/functions.rs
crates/polars-sql/tests/functions_string.rs

Closes #10858.
Accepts `column` and `separator` to join its values
`SELECT a FROM df`:
|         a        |
|------------------|
|['Hello', 'World']|
`SELECT array_to_string(a, ', ') FROM df`:
|         a        |
|------------------|
|  'Hello, World'  |

feat(rust): implementation of `array_to_string`

---

py-polars/polars/expr/datetime.py
py-polars/polars/series/datetime.py

These bullet points don't render at the moment: https://pola-rs.github.io/polars/py-polars/html/reference/expressions/api/polars.Expr.dt.round.html#polars.Expr.dt.round
So, updating them (and updating the formatting of the string language to be consistent with how it is in other docstrings)

docs(python): fix rendering of bullet points in dt.round

---

crates/polars-plan/src/dsl/function_expr/range/date_range.rs
crates/polars-plan/src/dsl/function_expr/range/int_range.rs
crates/polars-plan/src/dsl/function_expr/range/time_range.rs
crates/polars-plan/src/dsl/function_expr/range/utils.rs
py-polars/tests/unit/functions/range/test_date_range.py
py-polars/tests/unit/functions/range/test_int_range.py
py-polars/tests/unit/functions/range/test_time_range.py

Closes #10902 
I'd rather have a more specific error type, but I'll pick that up separately.

fix: Allow exactly one value in start/end for `int_range`

---

py-polars/docs/source/reference/config.rst
py-polars/polars/config.py
py-polars/tests/unit/test_cfg.py

Provides a consistent way to reset _individual_ `Config` options back to their default (without having to know what that default is) by simply setting them to `None`. The related environment var is popped, leaving it in the original/unset state.
**Example**:
```python
pl.Config.set_table_cols( None )
```
Added a note explaining this option to the docs, and added a thorough unit test that validates the behaviour.
Note: it's already easy to reset _all_ values by calling `pl.Config.restore_defaults()`.
---
**Also**: Both `set_tbl_cell_alignment` and `set_tbl_formatting` claimed to raise a `KeyError` if given invalid options. However, they did not actually do this (and a `KeyError` would have been the wrong type of error to raise even if they did ;)
This is now fixed, raising a `ValueError` …

feat(python): allow individual `Config` options to be easily reset to their default value

---

crates/polars-algo/README.md
crates/polars-arrow/README.md
crates/polars-core/README.md
crates/polars-error/README.md
crates/polars-io/README.md
crates/polars-json/README.md
crates/polars-lazy/README.md
crates/polars-ops/README.md
crates/polars-pipe/README.md
crates/polars-plan/README.md
crates/polars-row/README.md
crates/polars-sql/README.md
crates/polars-time/README.md
crates/polars-utils/README.md

As suggested in #10909, internal crates readme has been enhanced with reference to main polars crate.
polars-json and polars-plan had no readme before, so I'd ask for checking if suggested comment by me is relevant and descriptive enough

docs(Rust): enhance internal crates readme with reference to main crate

---

crates/polars-core/src/chunked_array/ops/explode.rs
crates/polars-core/src/fmt.rs
py-polars/tests/unit/operations/test_explode.py

fix: compute length of null array in explode

---

py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/series.py

Closes #10950 
- I only added python docs.
- I don't always know how many blank lines are needed with all this fancy docstring stuff.
- I'm not 100% firm on the wording:
- "original order is preserved" or "relative order is preserved" or simply "order is preserved"
- I didn't add any notes to `Expr.filter()` or `Expr.drop_nulls()`
- The current docstrings for `drop_nulls` mention `Returns a new DataFrame`, whereas the docstrings for `filter` do not.
Since basically everything in polars returns a new copy, I'm not sure whether `Returns a new DataFrame` needs to be said.

docs(python): Document that filter, drop_nulls, left join preserve order

---

py-polars/polars/utils/_construction.py

`_unpack_schema()` is called without the `lookup_names` argument in all but one cases. This PR provides a fast path that results in ~10% to 15% speedup.

perf(python): optimize `_unpack_schema()`

---

crates/polars-core/src/chunked_array/from.rs
crates/polars-core/src/chunked_array/list/iterator.rs
crates/polars-core/src/chunked_array/ops/apply.rs
crates/polars-core/src/chunked_array/ops/arity.rs
crates/polars-core/src/chunked_array/ops/downcast.rs
crates/polars-core/src/chunked_array/ops/mod.rs
crates/polars-core/src/datatypes/mod.rs
crates/polars-ops/src/series/ops/is_in.rs
crates/polars-pipe/src/executors/sinks/group_by/aggregates/mean.rs
crates/polars-pipe/src/executors/sinks/group_by/aggregates/min_max.rs
crates/polars-pipe/src/executors/sinks/group_by/aggregates/sum.rs

This should reduce friction with writing generic code by making the static compile-time type relationships available on `PolarsDataType`s themselves. I also managed to eliminate the`StaticallyMatchesPolars` and `HasUnderlyingArray` traits.

refactor: genericize PolarsDataType

---

py-polars/polars/dataframe/frame.py
py-polars/tests/unit/io/test_excel.py

fix(python): write_excel "hidden_columns" parameter fails when taking a selector

---

crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/strings.rs
crates/polars-plan/src/dsl/string.rs
py-polars/docs/source/reference/expressions/string.rst
py-polars/docs/source/reference/series/string.rst
py-polars/polars/expr/string.py
py-polars/polars/series/string.py
py-polars/src/expr/string.rs
py-polars/tests/unit/namespaces/test_string.py

Partially addresses #10603
This PR adds the two functions `strip_prefix` and `strip_suffix` to both Rust and Python.

feat(python, rust): Add `strip_prefix` and `strip_suffix` to the string namespace

---

py-polars/polars/lazyframe/frame.py

There were 3 occurences of the same code (and in PR #10786 there are 2 more), so generalizing these a bit.

refactor(python): Add private LazyFrame method for setting sink optimizations

---

py-polars/docs/source/reference/dataframe/modify_select.rst
py-polars/docs/source/reference/functions.rst
py-polars/docs/source/reference/lazyframe/miscellaneous.rst
py-polars/docs/source/reference/lazyframe/modify_select.rst

This PR adds missing methods to the API docs, so they are shown in `LazyDataFrame`'s [API docs](https://pola-rs.github.io/polars/py-polars/html/reference/lazyframe/index.html).

docs(python): Adds missing method refs in LazyDataFrame API docs

---

py-polars/src/series/mod.rs
py-polars/tests/unit/series/test_series.py

Closes #11001.
`series_equal` was ignoring dtype comparison when `strict=True` (the call to `eq` just ended-up resolving to `series_equal_missing` without ever actually comparing the dtypes).
```
strict
Don't allow different numerical dtypes, e.g. comparing `pl.UInt32` with a
`pl.Int64` will return `False`.
```
Fixed this so that we now match the behaviour given in the docs (above), and added some new test coverage.

fix(python): ensure `series_equal` properly accounts for dtypes when strict=True

---

py-polars/polars/expr/expr.py

reference: https://github.com/pola-rs/polars/issues/10991
I'm short on time in the coming weeks so won't have time to work on the suggested solution in https://github.com/pola-rs/polars/issues/10991#issuecomment-1712042866 before the next release
Does anyone have time to implement it for 0.19.3? I'm travelling and so don't have time for anything non-trivial at the moment I'm afraid
If not, then I'd appreciate it if either this or https://github.com/pola-rs/polars/pull/11002 could make it in for 0.19.3
[Polars downloads are exploding](https://pypistats.org/packages/polars) and I'm worried that someone might get wrong results and lose faith in the library

docs(python): warn that "by" argument must be sorted for results to be correct in rolling_* functions

---

crates/polars-plan/src/logical_plan/projection.rs
py-polars/tests/unit/test_selectors.py

fix(rust, python): Don't reuse member for Selector::Add

---

crates/polars-plan/src/dsl/mod.rs
py-polars/tests/unit/operations/rolling/test_rolling.py

fix(rust, python): fix rolling_* functions when "by" has nanosecond resolution

---

Cargo.toml
py-polars/Cargo.lock
py-polars/tests/unit/datatypes/test_list.py

This closes #10709.
Upstream pull request: https://github.com/jorgecarleitao/arrow2/pull/1567. Please review it first. :)
I will change the `arrow2` dependency to the correct upstream `rev` after that being merged.

feat: More dtypes supports cast to list

---

crates/polars-lazy/src/physical_plan/executors/ext_context.rs
py-polars/tests/unit/test_predicates.py

fix: pushed-down expr should be considered when evaluating ExternalContext

---

crates/polars-ops/src/chunked_array/strings/namespace.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/strings.rs
crates/polars-plan/src/dsl/string.rs
py-polars/polars/expr/string.py
py-polars/polars/series/string.py
py-polars/src/expr/string.rs
py-polars/tests/unit/namespaces/test_string.py

This PR is committed to solve #10930. But not supports `extract_xxx` as I'm not very clear how to define a `match group` well in this `literal` mode, especially for `str.extract_groups()`.

feat(rust, python): Add `literal` for str count_match

---

crates/Makefile

This adds `make nextest` to the `crates` makefile, which runs the Rust tests using [`nextest`](https://nexte.st/) (`cargo install cargo-nextest`).
This reduced (not counting the compilation time) the time taken to run the Rust tests from like 2 minutes to 0.6 seconds on my machine.

feat(rust): add support for nextest

---

py-polars/polars/utils/_construction.py

Avoid repetitive calls of `dtypes.get(col)` and `dtypes[col]`.

perf(python): optimize `polars.utils._post_apply_columns()`

---

py-polars/pyproject.toml
py-polars/requirements-dev.txt
py-polars/tests/unit/test_interop.py

Latest `deltalake` pinned `pyarrow` at `< 13`, causing some unit test failures on package update (as we had previously updated the test to handle the changes in 13 and got unexpectedly reverted back to 12 by their pin).

tests(python): account for version-based issue with pyarrow datetime units in tests

---

py-polars/polars/utils/_construction.py
py-polars/tests/unit/test_constructors.py

Closes #10943.
@ritchie46 (and @hxzhao527, ref: #10954), as discussed:
This fixes an issue with partial schema creation and addresses the consistency of init from disjoint colnames; also reduces the latency of most "list of dicts" small-frame creation by letting the Rust-side constructor handle almost everything, avoiding Python-side set-construction and unnecessary calls into `_post_apply_columns`, which is the sort of thing that makes @jakob-keller happy ;) 
If we can fix https://github.com/pola-rs/polars/issues/11044 then we will be able to avoid _all_ calls into  `_post_apply_columns` for this constructor.

fix(python): fix partial schema init with `read_dicts` and reduce latency of small-frame creation

---

crates/polars-io/src/csv/write.rs
crates/polars-io/src/csv/write_impl.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/type_aliases.py
py-polars/src/conversion.rs
py-polars/tests/unit/io/test_csv.py

Closes #10992.
Adds a `QuoteStyle::Never` (Rust) or `quote_style="never"` (Python) option for `write_csv`.
Can offer a little additional performance if we know that nothing needs to be quoted, or provide an option to write columns that aren't intended to be true CSV (as per the linked issue).

feat(python,rust): add quote_style="never" option for `write_csv`

---

crates/polars-plan/src/dsl/function_expr/strings.rs
py-polars/tests/unit/functions/test_as_datatype.py

fix(rust, python): Correct field dtype of string concat

---

py-polars/polars/lazyframe/frame.py

Minor improvements to `fetch` docstring.
(Might even be worth further emphasising the _"this is a debug function"_ part in a `warning` block?)

docs(python): put `fetch` explanation in a "notes" block to better highlight it in the docs

---

py-polars/src/conversion.rs

Spotted that a couple of copy/pastes had sneaked in, eg: 
`impl FromPyObject<'_> for Wrap<SetOperation> {`
```
"validate must be one of {{'union', 'difference', ...
```
...instead of:
```
"set operation must be one of {{'union', 'difference', ...
```
Also added an extra word or two of detail/qualification where it helped clarify the error.

fix(python): fixed a few accidental copy/paste gremlins in conversion error messages

---

crates/polars-core/src/chunked_array/ops/filter.rs
py-polars/tests/unit/operations/test_filter.py

fix: Filter on empty objectChunked should not throw error

---

py-polars/polars/type_aliases.py

Trivial simplification of type alias `SchemaDefinition`:
```python
Union[
Sequence[str],  # redundant: covered by more generic Sequence below
Mapping[str, Union[PolarsDataType, PythonDataType]],
Sequence[Union[str, Tuple[str, Union[PolarsDataType, PythonDataType, None]]]],
]
```

refactor(python): simplify `SchemaDefinition` type alias

---

py-polars/polars/dataframe/frame.py
py-polars/polars/series/series.py

Since 0.19 the random module is no longer used (replaced by internal polars one). Some docstrings don't reflect this change yet. This fixes that.

docs(python): remove mentions of the deprecated random module

---

py-polars/tests/unit/io/test_parquet.py

Updates `test_tz_aware_parquet_9586` to use the `io_files_path` fixture instead of implicitly relying on the relative path from the working directory, which could result in a `FileNotFoundError`.

test(python): fix 'tz_aware.parquet' location in test (don't rely on implicit working directory)

---

docs/user-guide/expressions/functions.md

Removed a duplicated example on polars-book
It was originally opened on the polars-book repository (https://github.com/pola-rs/polars-book/pull/405)
But it seems today the whole docs were moved to main

docs: Removed duplicated example

---

crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/struct_.rs
py-polars/tests/unit/test_cse.py

`AExpr` containing `StructFunction::FieldByName` with different `field` names were calculated to have the same `hash` value, resulting in incorrect reuse by `cse`.
This fixes #11116.

fix: Correct hash and fmt for struct expr

---

py-polars/polars/dependencies.py
py-polars/polars/functions/lazy.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/utils/_async.py
py-polars/polars/utils/show_versions.py
py-polars/pyproject.toml
py-polars/requirements-dev.txt
py-polars/tests/unit/test_async.py

In #10616 @jakob-keller proposed to simplify this to `await ldf.collect_async()` for asyncio. Not it's possible.
Api now is way nicer and defaults to asyncio, since its most common usage. Don't need to pass Queue instances.
Also since they had to be thread safe - default queues from asyncio and gevent were not compatible and external dependency janus was required to safely use them.
asyncio implementation turned out fairly simple 
But with gevent  I was not able to to do this with [ILoop.run_callback_threadsafe](https://www.gevent.org/api/gevent.hub.html#gevent._interfaces.ILoop.run_callback_threadsafe) for some reason due to `LoopExit: This operation would block forever`, while they say it's a [asyncio.loop.call_soon_threadsafe](https://docs.python.org/3/library/asyncio-eventloop.html#asy …

feat(python): better async_collect

---

crates/polars-core/src/chunked_array/ops/apply.rs
crates/polars-core/src/datatypes/from_values.rs
crates/polars-ffi/Cargo.toml
crates/polars-ffi/src/lib.rs
crates/polars-plan/Cargo.toml
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/plugin.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/mod.rs
py-polars/Cargo.lock
py-polars/Cargo.toml
py-polars/polars/expr/expr.py
py-polars/polars/utils/udfs.py
py-polars/src/expr/general.rs

This allows support for polars plugins. These are expression exposed in a different shared library and dynamically linked into the polars main library.
This mean we or third parties can create their own expressions and they will run on our engine without python interference. So no blockage by the GIL.
We can therefore keep polars more lean and maybe add support for a `polars-distance`, `polars-geo`, `polars-ml`, etc. Those can then have specialized expressions and don't have to worry as much for code bloat as they can be optionally installed.
The idea is that you define an expression in another Rust crate with a proc_macro `polars_expr`.
That macro can have the following attributes:
- `output_type` -> to define the output type of that expression
- `type_func` -> to define a function that …

feat(python): Polars plugins

---

crates/polars-core/src/chunked_array/ops/arity.rs
crates/polars-core/src/chunked_array/ops/for_each.rs
crates/polars-core/src/chunked_array/ops/mod.rs
crates/polars-ops/src/chunked_array/strings/namespace.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/strings.rs
crates/polars-plan/src/dsl/string.rs
crates/polars/tests/it/lazy/explodes.rs
py-polars/polars/expr/string.py
py-polars/src/expr/string.rs
py-polars/tests/unit/namespaces/test_string.py

feat: Expressify str.split argument.

---

py-polars/polars/exceptions.py
py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #11161.
Fixes an oversight when specifying dtype overrides via "read_csv_options" passthrough for the default `xlsx2csv` engine.

fix(python): only raise on actual parameter collision when "dtypes" specified in `read_excel` "read_csv_options" 

---

crates/polars-plan/src/dsl/function_expr/coerce.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/functions/coerce.rs
py-polars/src/functions/lazy.rs
py-polars/tests/unit/test_serde.py

fix: Make pl.struct serializable

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/utils/convert.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/operations/rolling/test_rolling.py
py-polars/tests/unit/operations/test_group_by.py

closes #11163 
technically breaking, but to be honest I consider the current behaviour buggy as it's not reporting valid windows - my suggestion would be treat it as a bug fix
but, could deprecate the behaviour and make the change in 1.0 if people prefer
---
my understanding of `group_by_dynamic` is the windows are:
- [start, start + period)
- [start + every, start + every + period)
- [start + 2 every, start + 2 every + period)
- ...
and that `start` is `earliest_timestamp.truncate(every) + offset`
So, I don't really see why `offset` depends on `period` at all, but I might be missing something

fix(python)!: consistently use negative every as the default for offset in group_by_dynamic

---

py-polars/polars/expr/binary.py
py-polars/polars/expr/string.py
py-polars/polars/series/binary.py
py-polars/polars/series/string.py

We have already supports expr for these methods, but just forgot to modify the type hint in series module.

fix(python): Add some missing expr type hint for series

---

py-polars/src/map/lazy.rs

This stood out slightly after the switchover from `apply` to `map_*` naming; the other three places I found where we raise errors on pyfunc failure use _"python function failed: ..."_ instead of _"python apply failed: ..."_, so this is just a trivial update for consistency.

fix(python,rust): make error message consistent with other calls to python functions from rust

---

crates/polars-ops/src/chunked_array/strings/namespace.rs
crates/polars-utils/src/cache.rs

per comment(https://github.com/pola-rs/polars/pull/11141#discussion_r1328512435).

perf: Using cache for str.contains regex compilation

---

py-polars/polars/expr/expr.py
py-polars/polars/expr/meta.py
py-polars/tests/unit/namespaces/test_meta.py
py-polars/tests/unit/test_exprs.py
py-polars/tests/unit/test_schema.py

Closes #11149.
Because we implement `-expr` as `lit(0) - expr` (and `+expr` as `lit(0) + expr`) the output name of the resulting expressions is `literal`. While this makes sense (leftmost expr naming convention), it is not something that the caller expects as this is an internal detail that they know nothing about (and shouldn't have to read the source to discover ;)
In accordance with "the principle of least surprise", this PR maintains the _expected_ name, as determined from the rhs `expr` (via `meta.output_name`), and not the anonymous/internal lhs `lit`. As well as resulting in the expected name for a single op, this also ensures that you can easily negate multiple columns without having to explicitly alias them all (to avoid a duplicate colnames error).
I can see that #5669 wanted to …

fix(python): address unexpected expression name from use of unary `-` or `+` operators

---

crates/polars-plan/src/logical_plan/pyarrow.rs
py-polars/polars/io/iceberg.py
py-polars/polars/io/pyarrow_dataset/anonymous_scan.py
py-polars/tests/unit/io/test_iceberg.py
py-polars/tests/unit/io/test_pyarrow_dataset.py

While further probing the new Iceberg functionality[^1] I found (and have now fixed ;) a bug with our own pyarrow predicate generation for Series-nested AnyValue date/datetime literals (eg: as would be constructed by an `is_in` constraint).
(We were also calling out to deprecated/removed params for `_to_python_datetime`, using "tu" and "tz" instead of "time_unit" and "time_zone").
Fixed everything and added new unit tests to increase coverage, including examples of the date and datetime constraints that were previously failing:
```python
df = pl.scan_iceberg( 
"file:///.../tests/unit/io/files/iceberg-table/metadata/v2.metadata.json"
).filter(
pl.col("ts").is_in([
datetime(2023,3,1,18,15),
datetime(2023,3,2,22,0),
])
).collect()
``` …

fix(python,rust): fix translation of Series-nested datetime/date values for `scan_pyarrow` predicates

---

crates/polars-lazy/src/physical_plan/expressions/filter.rs
py-polars/tests/unit/operations/test_filter.py

fix: fix nullable filter mask in group_by

---

py-polars/polars/io/database.py
py-polars/tests/unit/interchange/test_from_dataframe.py
py-polars/tests/unit/io/test_database_read.py

Closes #11131.
Reworked the batched Arrow-return path and improved the related mocked tests. 
**Updates:** 
* Was finally able to install `turbodbc` _with_ the arrow extensions and validate the fix.
* Standardised `duckdb` interactions, adding an entry into the driver registry.

fix(python): improve handling of database drivers that can return arrow data

---

crates/polars-ops/src/series/ops/rle.rs
crates/polars-plan/src/dsl/mod.rs
py-polars/polars/expr/expr.py

Adds various missing doc-comments to the Rust-side expressions, and consistently applies `.` at the end of each comment.

docs(rust): add various missing expression doc-comments

---

crates/nano-arrow/src/bitmap/bitmask.rs
crates/nano-arrow/src/bitmap/mod.rs
crates/polars-core/src/chunked_array/ops/aggregate/float_sum.rs
crates/polars-core/src/chunked_array/ops/gather.rs
crates/polars-core/src/datatypes/static_array.rs
crates/polars-core/src/datatypes/static_array_collect.rs
crates/polars-ops/src/chunked_array/set.rs
crates/polars-utils/src/index.rs
crates/polars-utils/src/lib.rs

If the number of target arrays is > 8 we rechunk, otherwise we do a bitwise binary search to find the chunk index.

feat(rust): binary search and rechunk in chunked gather

---

crates/polars-core/src/series/implementations/duration.rs
crates/polars/tests/it/core/date_like.rs

Closes: https://github.com/pola-rs/polars/issues/11034
This PR adds support for `duration + date`. Supporting that operation will bring the Rust API more in line with the Python API, which already supports it.
* Support `duration + date`
* Tests

feat(rust): Support `duration + date`

---

py-polars/docs/source/reference/config.rst
py-polars/polars/config.py
py-polars/tests/unit/test_cfg.py

Closes #11094 (and addresses https://github.com/pola-rs/polars/pull/9391#discussion_r1233426042).
As well as removing ambiguity, also now raises specific errors if a `Path` object is passed to `Config.load` or a JSON string is passed to `Config.load_from_file`.
**Also:**
Some (minor) docstring improvements, and additional test coverage.

fix(python): don't conflate saved `Config` JSON string with file path

---

crates/polars-sql/src/functions.rs
py-polars/tests/unit/test_sql.py

Adds a pair of functions from the Postgres SQL documentation:
https://www.postgresql.org/docs/current/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL
I'm getting SQL issues from here: https://github.com/pola-rs/polars/issues/7227
Apparently these were community requested, I cannot find who requested them.

feat(python, rust): Adds `NULLIF` and `COALESCE` SQL functions

---

crates/nano-arrow/Cargo.toml

This fixes rust-analyzer in tests (or `cargo check` in general with `--all-features`), because `parquet2` has made the cardinal sin of having mutually exclusive features. This does mean that downstream Rust users of Polars can no longer choose which lz4 library it uses... which I don't think really matters all that much.

refactor(rust): remove lz4_flex feature

---

Cargo.toml

chrono-0.4.31 deprecated `timestamp_nanos` in favor of a new function called `timestamp_nanos_opt` (see [chronotope/chrono#1275)](https://github.com/chronotope/chrono/pull/1275). Polars makes use of this new function, so chrono’s version should be bumped in the root manifest.

chore(rust): bump chrono to 0.4.31

---

crates/polars-time/src/group_by/dynamic.rs
crates/polars-time/src/windows/bounds.rs
crates/polars-time/src/windows/group_by.rs
py-polars/tests/unit/datatypes/test_temporal.py

fix: consume duplicates in rolling_by window

---

py-polars/tests/parametric/test_groupby_rolling.py

from https://github.com/pola-rs/polars/pull/11261#issuecomment-1732274035
on my laptop, 
```
pytest ../py-polars/tests/parametric/test_groupby_rolling.py -m 'not slow' --hypothesis-show-statistics
```
takes `3.75s` - and that's for 2 tests which each generate 200 test cases
worth it IMO, and gives greater confidence whilst doing other perf improvements

test(python): parametric tests for group_by_rolling

---

py-polars/Makefile

The command for `build-debug-opt-subset` was named wrong.
Also made sure the comments show up properly when running `make help` (they have to be on one line, so keep them short and snappy).

chore(python): Fix some minor Makefile issues

---

py-polars/tests/unit/io/test_database_write.py

The new ADBC release doesn't seem to fix the issue. So marking this to `xfail` for now.
@alexander-beedie FYI (also see my message on Discord).

test(python): Properly skip ADBC test

---

.github/workflows/test-python.yml
docs/_build/API_REFERENCE_LINKS.yml
docs/getting-started/series-dataframes.md
docs/src/python/getting-started/series-dataframes.py
docs/src/python/user-guide/expressions/aggregation.py
docs/src/python/user-guide/expressions/casting.py
docs/src/python/user-guide/transformations/time-series/filter.py
docs/src/python/user-guide/transformations/time-series/parsing.py
docs/src/python/user-guide/transformations/time-series/timezones.py
docs/src/rust/getting-started/series-dataframes.rs
docs/src/rust/user-guide/expressions/casting.rs
docs/src/rust/user-guide/transformations/time-series/filter.rs
docs/src/rust/user-guide/transformations/time-series/parsing.rs
docs/src/rust/user-guide/transformations/time-series/timezones.rs
docs/user-guide/expressions/casting.md
docs/user-guide/expressions/column-selections.md
docs/user-guide/expressions/lists.md
docs/user-guide/expressions/strings.md
docs/user-guide/expressions/structs.md
docs/user-guide/io/aws.md
docs/user-guide/transformations/time-series/filter.md
docs/user-guide/transformations/time-series/parsing.md
docs/user-guide/transformations/time-series/rolling.md
docs/user-guide/transformations/time-series/timezones.md
mkdocs.yml

Closes [#11113](https://github.com/pola-rs/polars/issues/11113)
Added/renamed many links to the API reference. Made some small updates to code examples along the way.
This exercise made me realize we have to organize this differently. This is too much of a hassle to keep up to date.

docs(rust): Add API links for Rust user guide examples

---

py-polars/polars/functions/range/date_range.py
py-polars/polars/functions/range/datetime_range.py
py-polars/polars/functions/range/int_range.py
py-polars/polars/functions/range/time_range.py
py-polars/polars/type_aliases.py

This will help narrow down some type signatures, as `IntoExpr` was too broad in many cases.
This new type allows any input that converts into a `col` expression: `Expr`, `Series`, and `str`.

refactor(python): Add type alias `IntoExprColumn`

---

py-polars/polars/dataframe/frame.py
py-polars/polars/selectors.py

Closes #11226.
It seems that PyCharm correctly resolved the `_selector_proxy_` type as `Expr` (so I didn't notice any issues with it), but VSCode didn't (or otherwise got confused), apparently leading to no VSCode autocomplete on selector expressions. 
This PR removes a redundant `SelectorType` declaration (plausibly responsible in some way) and very slightly tweaks the `selectors` module typing. Installed a copy of VSCode to help validate/debug the issue and can confirm that this change seems to fix things (while PyCharm remains happy).
---
VSCode users rejoice  ;)

fix(python): address VSCode issue with autocomplete on `selector` expressions in editor/console

---

crates/polars-core/src/chunked_array/ops/arity.rs
crates/polars-core/src/series/ops/round.rs
crates/polars-ops/src/series/ops/clip.rs
crates/polars-ops/src/series/ops/mod.rs
crates/polars-plan/src/dsl/function_expr/clip.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/mod.rs
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/polars/type_aliases.py
py-polars/src/expr/general.rs
py-polars/tests/unit/dataframe/test_df.py

This closes #6470 and #6535, #8892, #2990.

feat: clip supports expr arguments and physical numeric dtype

---

crates/polars-arrow/src/compute/decimal.rs

Closes https://github.com/pola-rs/polars/issues/11266.

fix(rust): parse sign for decimal properly

---

crates/polars-lazy/src/tests/aggregations.rs
crates/polars-lazy/src/tests/mod.rs
crates/polars-lazy/src/tests/optimization_checks.rs
crates/polars-lazy/src/tests/predicate_queries.rs
crates/polars-lazy/src/tests/queries.rs

Resolves some compiler errors if compiling tests without `--all-features`.

fix(rust): add missing feature flags on tests

---

crates/polars-plan/src/dsl/arithmetic.rs
crates/polars-plan/src/dsl/binary.rs
crates/polars-plan/src/dsl/dt.rs
crates/polars-plan/src/dsl/list.rs
crates/polars-plan/src/dsl/mod.rs
crates/polars-plan/src/dsl/string.rs

per comment(https://github.com/pola-rs/polars/pull/11230#discussion_r1333920358).
Note: I just keep the original value for `auto-explode`, doesn't change any setting. But this may be a good opportunity to check if our previous setting for `auto-explode` was correct. 😆

refactor: remove default auto-explode for map_many_private

---

py-polars/polars/utils/various.py

fix(python): Exclude functools wrapper frames in `find_stacklevel`

---

crates/polars-core/src/chunked_array/logical/categorical/builder.rs
crates/polars-core/src/chunked_array/logical/categorical/merge.rs
crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/logical/categorical/string_cache.rs
crates/polars-core/src/chunked_array/logical/categorical/stringcache.rs
crates/polars-core/src/chunked_array/mod.rs
crates/polars-core/src/chunked_array/ops/sort/categorical.rs
crates/polars-core/src/lib.rs
crates/polars-error/src/lib.rs
crates/polars-io/src/csv/read.rs
crates/polars-io/src/csv/read_impl/batched_mmap.rs
crates/polars-io/src/csv/read_impl/batched_read.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-lazy/src/physical_plan/expressions/window.rs
crates/polars-plan/src/logical_plan/functions/mod.rs
crates/polars/src/docs/performance.rs
crates/polars/tests/it/core/joins.rs
crates/polars/tests/it/lazy/expressions/arity.rs
crates/polars/tests/it/lazy/predicate_queries.rs
py-polars/docs/source/reference/functions.rst
py-polars/polars/__init__.py
py-polars/polars/string_cache.py
py-polars/src/functions/meta.rs
py-polars/src/functions/mod.rs
py-polars/src/functions/string_cache.rs
py-polars/src/lib.rs
py-polars/tests/docs/run_doctest.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/test_cfg.py
py-polars/tests/unit/test_string_cache.py

Closes #10425
* Deprecate the boolean argument for `enable_string_cache`. The function now always enables the string cache.
* Add a new function `disable_string_cache`. This disables the string cache.
* Fix the implementation of the StringCache context manager.
* On the Rust side, rename `IUseStringCache` to `StringCacheHolder`. `IUse...` seemed like a weird name to me - but maybe I am missing some convention here.
* Some internal refactoring.
API is now consistent across the Rust and Python side - with the exception that Python offers a context manager instead of a RAII object.

feat(python, rust!): Add `disable_string_cache`

---

py-polars/polars/utils/_construction.py
py-polars/tests/unit/test_constructors.py

Closes #11306.
Simple patch to fix `DataFrame` init from `collections.namedtuple` values (we already support `typing.NamedTuple`).

fix(python): DataFrame init from `collections.namedtuple` values

---

crates/polars-core/src/chunked_array/logical/struct_/mod.rs
py-polars/tests/unit/datatypes/test_struct.py
py-polars/tests/unit/io/test_json.py

Closes #11259.
There was a potential off-by-one error here when initialising an empty Series; we'd end up with a one-element Series instead.
**Before:** 
_(no data, but we create an unexpected series value)_
```python
pl.Series(dtype=pl.Struct)
```
**After:**
_(empty, as expected)_
```python
pl.Series(dtype=pl.Struct)
```

fix(rust,python): fix empty Series construction edge-case with Struct dtype

---

crates/polars-core/src/chunked_array/random.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/random.rs
crates/polars-plan/src/dsl/random.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/src/dataframe.rs
py-polars/src/expr/general.rs
py-polars/tests/unit/operations/test_random.py

This closes #11244.
This only supports `Expr` that can be evaluated to length of `1`. Otherwise, it seems meaningless(or not well-defined).
But I may create a followup PR to introduce the `sample` method also to `list` namespace, that will taken an `Expr` can be evaluated to a real `column`.

feat: sample n can take an expr

---

py-polars/polars/series/series.py

Quick/minor follow-up, ref: https://github.com/pola-rs/polars/pull/11319#discussion_r1336849942.
Adds explicit advice (and a cross-link) to the `null_count` method to show the right way to confirm that `null` values are present (also fixes the italics; should have used `*`, not `_` ;)

docs(python): cross-reference `null_count` from `has_validity` (clarifies the correct way to check for nulls)

---

py-polars/docs/requirements-docs.txt
py-polars/docs/source/_static/version_switcher.json
py-polars/docs/source/conf.py

This will show a warning when you're browsing a non-stable version of the docs.
Reference:
https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/announcements.html#version-warning-banners

docs(python): Enable version warning banner

---

.github/workflows/docs-global.yml
docs/_build/scripts/people.py

Closes [#11101](https://github.com/pola-rs/polars/issues/11101)
This will use the GITHUB_TOKEN in the CI to get the contributor information. Locally, it will get the information without authentication (which may fail, albeit rarely).

ci: Use `GITHUB_TOKEN` to get contributor information for docs

---

py-polars/polars/dataframe/frame.py

seems like a popular request, so adding a little example until https://github.com/pola-rs/polars/issues/6324 is addressed

docs(python): add lazy pivot example

---

crates/polars-io/src/csv/write_impl.rs
py-polars/tests/unit/io/test_csv.py

Closes #11324.
We missed writing the trailing quote for datetime values in CSV output when `quote_style` was "non_numeric". Fixed, and extended the related test-coverage to include date/datetime values.
```python
df = pl.DataFrame({"dtm": [datetime.now(), datetime.now()]})
```
_(datetime values are missing trailing quotes)_
```python
print( df.write_csv( has_header=True, quote_style = 'non_numeric') )
```
```python
print( df.write_csv( has_header=True, quote_style = 'non_numeric') )
```

fix(rust,python): ensure trailing quote is written for temporal data when CSV `quote_style` is non-numeric

---

Cargo.toml
crates/nano-arrow/Cargo.toml
crates/polars-arrow/Cargo.toml
crates/polars-ffi/Cargo.toml
crates/polars-io/Cargo.toml
crates/polars-json/Cargo.toml
crates/polars-pipe/Cargo.toml
crates/polars/Cargo.toml
py-polars/Cargo.lock

We had some warnings stemming from typos:
* `licence` -> `license`
* `workpace` -> `workspace`
Also cleaned up the `nano-arrow` manifest, moving some dependency versions to the workspace level.

chore(rust): Fix some cargo manifest warnings

---

py-polars/polars/testing/asserts.py
py-polars/tests/unit/test_lazy.py
py-polars/tests/unit/test_testing.py

Ref: https://github.com/pola-rs/polars/pull/11287#discussion_r1337175188 (for @stinodego ;) 
The act of collecting may resolve the schema _before_ it has been checked, potentially hiding some edge-cases. If given two LazyFrames, only collect _after_ schema verification.
(Also: brings the assert error message formatting a little closer to our newer standard).

test(python): tighten `assert_frame_equal` for LazyFrames (don't collect until after the schema has been checked)

---

crates/polars-ops/src/chunked_array/top_k.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/mod.rs
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/src/expr/general.rs
py-polars/tests/unit/operations/test_sort.py

This allow an `expr` evaluated to a single value can be argument of `top_k` and `bottom_k`. It's better to do the same thing for `lazyFrame#top_k`, but that maybe require `LogicalPlan::Slice` supports `expr` arguments, I guess we can do this in the future.

feat: top_k and bottom_k supports pass an expr

---

py-polars/tests/parametric/test_groupby_rolling.py

~closes #11281 ~
~closes #11150~
~I think I'm going to have dreams about `group_by_rolling` tonight~
repurposed as a tests PR

 test(python): improve parametric tests for group_by_rolling by skipping overflowing cases

---

py-polars/docs/source/conf.py

There seems to be a bug in the Sphinx theme:
https://github.com/pydata/pydata-sphinx-theme/issues/1445
Let's disable the banner for now.

docs(python): Disable version warning banner for now

---

.github/workflows/release-python.yml
py-polars/src/error.rs
py-polars/src/on_startup.rs

This should give us enhanced performance. The vast majority of x86-64 CPUs out there support AVX2/BMI, especially among those doing data analysis. The last mainstream desktop/server CPUs without their support were released in 2016.
There are modern low-powered Pentium / Celeron chips found in NUCs, thin-client mini desktops used in offices and (potentially misconfigured) cheap cloud servers that don't have them, those will have to use the `lts-cpu` Polars packages.
To that end I made sure that all our builds have all possible variants with `-lts-cpu` and `-u64-idx`.

feat: modernize CPU features

---

py-polars/polars/io/database.py

Closes #11340.
Clarify use of "batch_size" in the `read_database` docstring (it's not equivalent to "limit").

docs(python): clarify use of "batch_size" for `read_database`

---

py-polars/polars/functions/lit.py
py-polars/tests/unit/functions/test_lit.py

fix(python): handle ambiguous datetimes in pl.lit

---

crates/polars-core/src/series/series_trait.rs
py-polars/Cargo.lock

This resolves a build issue that existed prior to this commit:
```
$ cargo build --no-default-features --features dtype-i8,rows <snip>
error[E0432]: unresolved import `crate::frame::group_by`
--> crates/polars-core/src/series/series_trait.rs:51:23
|
51 |     use crate::frame::group_by::GroupsProxy;
|                       ^^^^^^^^ could not find `group_by` in `frame`
```
Fixes: #11373

Gate a use statement by algorithm_group_by instead of rows

---

crates/polars-core/src/datatypes/dtype.rs
py-polars/tests/unit/datatypes/test_array.py
py-polars/tests/unit/test_interop.py

Came across this one after seeing some inconsistent error messages debugging something else.
(Addresses an edge-case where Array dtype could inadvertantly be considered numeric).
* The `is_numeric` check was a bit peculiar (and likely prone to future breakage if/when adding new dtypes) as it decided that a dtype was numeric if It _wasn't_ various other dtypes, rather than because it _was_ numeric. Changed this so that we positively assert the dtype from the known numeric types instead, which seems a lot cleaner.
---
**Also:** fixes a minor test lint (`mypy` on py 3.11) caused by an update to `pandas-stubs`.
**Note:** for some reason we don't currently consider Decimal to be numeric here; that seems odd, so will probably revisit to better-understand why... this PR does not change this …

fix(rust,python): Fix edge-case where the Array dtype could (internally) be considered numeric

---

Cargo.toml
crates/polars-io/Cargo.toml
crates/polars-io/src/cloud/adaptors.rs
crates/polars-io/src/cloud/glob.rs
crates/polars-io/src/cloud/mod.rs
crates/polars-io/src/cloud/options.rs
crates/polars-io/src/lib.rs
crates/polars-io/src/parquet/async_impl.rs
crates/polars-io/src/parquet/read.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-io/src/pl_async.rs
crates/polars-lazy/Cargo.toml
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs
crates/polars-pipe/Cargo.toml
crates/polars-pipe/src/executors/sinks/file_sink.rs
crates/polars-pipe/src/executors/sources/parquet.rs
crates/polars-utils/src/cache.rs
py-polars/Cargo.lock

This got complicated quickly. This sets the basis for better async support in polars. Had to do some refactors as async traits lead to very complicated HRT errors.
fixes #11389
Also add auto-inference of aws regions as drive by.

fix: async parquet. 

---

crates/polars-lazy/src/scan/file_list_reader.rs
crates/polars-lazy/src/scan/parquet.rs
crates/polars-plan/src/logical_plan/builder.rs

We sequentially did a web request for metadata that matched a glob pattern. Now we only do that for the first one.

perf: don't load N metadata files when globbing N files

---

crates/polars-lazy/src/physical_plan/expressions/sortby.rs
py-polars/tests/unit/test_errors.py

fix: raise on invalid sort_by group lengths

---

.github/workflows/release-python.yml

* Build the same wheels for the alternative packages as for the main Polars package
* Replace the `sed` commands to use [`yq`](https://kislyuk.github.io/yq/) (`jq` for TOML) because `sed -i` is not platform-agnostic (macOS being special again)
This means we now build 15 wheels (5 wheels per package) instead of 7. I think it's worth it, especially for `lts-cpu` since we will be making the main package more restrictive with additional CPU flags (next PR).

ci(python): Build more wheels for `polars-lts-cpu`/`polars-u64-idx`

---

crates/polars-core/src/datatypes/time_unit.rs
crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs
py-polars/polars/expr/expr.py
py-polars/tests/unit/operations/test_is_in.py
py-polars/tests/unit/test_errors.py

Closes #11394.
* The linked issue shows that we were casting `is_in` values to string if the target series was `Utf8`:
```python
"a": ["1","2"],
"b": [3,4],
})
df.filter( pl.col("a").is_in([1,2]) )  # << filtering string by int64 🚫
```
* This led down a surprisingly deep rabbit-hole, as various _other_ incompatible dtype pairs were being allowed via implicit cast, leading to incorrect or weird/misleading results - for example, the following filters silently cast and drop all results:
```python
"a": ["1","2"],
"b": [3,4],
})
df.filter( pl.col("a").is_in([date.today()]) )  # << filtering string by date 🚫
df.filter( pl.col("b").is_in([date.today()]) )  # << filtering int64 by date 🚫
```
I've resolved this …

fix(rust,python): address multiple issues caused by implicit casting of `is_in` values to the column dtype being searched

---

py-polars/polars/functions/col.py

Closes #11433.
Reworks the `ColumnFactory` to improve tab-complete in IPython (without regression in other IDEs).

feat(python): rework `ColumnFactory` to additionally support tab-complete for `col` in IPython

---

py-polars/polars/utils/deprecation.py

This _doesn't_ fix editor autocomplete not showing the method signature, but _does_ fix it in the interactive console.

fix(python): partially address some PyCharm tooltip/signature issues with decorated methods

---

.github/workflows/release-python.yml

This will add wheels and sdist as assets to the GitHub release (see image below from my fork).
I am not adding the `polars-lts-cpu` and `polars-u64-idx` wheels for now as I think they are less important.

ci(python): Add wheels to GitHub release

---

py-polars/polars/expr/expr.py

I had a trainee confused over what `shift` does, so I think showing the original column alongside the shifted one should clarify

docs(python): use with_columns in shift examples

---

crates/polars-core/src/chunked_array/ops/any_value.rs
crates/polars-core/src/fmt.rs
crates/polars-core/src/series/ops/downcast.rs
py-polars/tests/unit/test_constructors.py

Resolves #7153
null array now is shown as:
``` 
shape: (2,)
Series: 'a' [nullarray]
[
null
null
] 
``` 
instead of 
```
nullarray
```
Could refactor the code a bit cause it overlaps with `format_array` a lot, so there is quite some repitition, but made this PR to see if this is in the right direction at all.

feat(rust): Format null arrays in Series

---

CONTRIBUTING.md

Closes #11450
Include a small note about recommended amount of memory. We can include more information after migrating the contributing guide.
Also remove references to NodeJS. That repo has its own contributing guide, this one should be focused on this repo. We can include links to community forks in our user guide.

docs: Update contributing guide to include memory requirement

---

py-polars/polars/io/database.py

Closes #11142.
Not all `snowflake` connections/warehouses are able to return Arrow format data.
Handle the fall back (to a vanilla row-based resultset) transparently.

fix(python): enable `read_database` fallback for Snowflake warehouses/connections that don't support Arrow resultsets

---

.github/workflows/release-python.yml

Just some minor cleanup of things.
Pinned the toolchain version due to a bug in the most recent `maturin-action` version.

ci(python): More release workflow refactor

---

crates/polars-io/src/csv/write_impl.rs
py-polars/tests/unit/io/test_csv.py

We weren't respecting custom "quote" char in two places:
* empty string representation.
* quoting values that contain the quote char.
```python
df = pl.DataFrame( {"string":["","0*0","xyz"]} )
```
Empty string quoted as `""` instead of `**`.
Value containing quote char `*` quoted using `"`.
```python
df.write_csv( quote="*" )
```
Both cases properly use the declared quote char `*`.
```python
df.write_csv( quote="*" )
```

fix(python,rust): fix for `write_csv` when using non-default "quote" char

---

.github/workflows/release-python.yml
py-polars/requirements-dev.txt

I unpinned the maturin version in the dev dependencies, as we want to make sure our builds work on the latest version of maturin. If not, we'll find out quickly :smiling_imp: 
Also, I messed up something (small) in the release workflow.

ci(python): Unpin maturin version, fix release workflow

---

crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs
py-polars/tests/unit/datatypes/test_temporal.py

closes #10516
This adds an early return for:
- None -> UTC
- UTC -> None
- UTC -> UTC
- None -> None
These are the only cases in which the early return can be safely done unfortunately - due to DST nonsense, replacing `'Europe/London'` with `'Europe/London'` might not return the same result

perf(rust, python): early return in replace_time_zone if target and source time zones match

---

.github/workflows/release-python.yml

Run `pip install` on the sdist (this triggers a slow compilation) to verify that it was created correctly. It's ran in parallel with building the wheels, so should not slow down the release process.
Avoids issues like [#11371](https://github.com/pola-rs/polars/issues/11371) from popping up in the future.
We could also test  the wheels by pip installing them and running `python -c 'import polars'`, but I don't think there's a reason to do so as we haven't run into trouble with broken wheels as far as I know.

ci(python): Test sdist before releasing

---

crates/polars-plan/src/logical_plan/lit.rs
py-polars/tests/unit/test_cse.py

fix: literal hash

---

crates/polars-sql/src/functions.rs
py-polars/tests/unit/sql/test_sql.py

Adds support for the SQL equivalent of `to_titlecase` (to which this maps).
```python
df = pl.DataFrame( { "words": ["Test SOME words"] } )
"""
SELECT
words,
INITCAP(words) as cap,
UPPER(words) as upper,
LOWER(words) as lower,
FROM frame
"""
).collect()
```

feat(python): add `INITCAP` string function for SQL

---

crates/polars-sql/src/context.rs
crates/polars-sql/src/sql_expr.rs
py-polars/tests/unit/sql/test_sql.py

Partially addresses #11290.
Ref: https://github.com/pola-rs/polars/issues/11290#issuecomment-1733881081
Ref: https://github.com/pola-rs/polars/pull/11501#issuecomment-1747017914
Turns out we have been silently eating all columns after the first one in `USING` clauses. I've reworked the processing here so that we now properly capture and apply _all_ of the declared constraint columns, and added/fixed some test coverage.

fix(rust,python,sql): rework SQL join constraint processing to properly account for all `USING` columns

---

.github/workflows/release-python.yml

We have enabled extra CPU optimizations for our Linux and Windows x86-64 wheels:
```diff
- RUSTFLAGS=-C target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma
+ RUSTFLAGS=-C target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+avx2,+fma,+bmi1,+bmi2,+lzcnt
```
This will lead to better performance on modern CPUs.
However, for users on old CPUs, this may lead to an error when importing Polars _(illegal instruction)_.
**If this is the case for you, please let us know on Discord or make an issue on GitHub.**
If you can no longer import Polars, you can use the `polars-lts-cpu` package instead.
_Highlighted not for the magnitude of this achievement - but for visiblity in the changelog as this might trip up some of our users._

build(python): Enable additional flags for x86-64 wheels

---

crates/polars-arrow/src/bit_util.rs
py-polars/tests/unit/operations/test_is_first_last_distinct.py

fixes https://github.com/pola-rs/polars/issues/11530
`is_first_distinct` goes through a fast path for boolean arrays whose lengths are >=64, and it currently calculates index offsets from the wrong side (leading bits instead of trailing bits).

 fix(rust,python): incorrect `is_first_distinct` for boolean arrays of length >= 64

---

crates/polars-sql/src/sql_expr.rs
py-polars/tests/unit/sql/test_sql.py

We could silently treat `BinaryOps` in `JoinConstraint` conditions as being `Eq` constraints instead of identifying non equi-joins and raising an informative error, eg:
```sql
SELECT *
FROM table_x
LEFT JOIN table_y ON left_id != right_id  -- treated as '=' 🚫
```
With this PR we now raise a suitable error:
```
InvalidOperationError: SQL interface (currently) only 
supports basic equi-join constraints; found 'NotEq' op
```

fix(rust,python,cli): catch use of non equi-joins in SQL interface and raise appropriate error

---

py-polars/polars/functions/lit.py
py-polars/polars/series/series.py
py-polars/polars/utils/convert.py
py-polars/tests/unit/datatypes/test_temporal.py

closes #11470 
summary of change:
- `_datetime_to_pl_timestamp` would previously always set `UTC` as the time zone before calculating the timestamp. I think this was only the intention for `pl.lit(datetime(...), dtype=(..., time_zone))`, where the time zone is to be replaced at the end
So, I've changed `_datetime_to_pl_timestamp` to only set `UTC` if the time zone is None (to avoid the python stdlib weirdness of using the system's time zone), and otherwise it's up to the caller (in this case, `lit`) to replace the timezone before calling `_datetime_to_pl_timestamp`.
Like this, `__gt__` can just use the datetime as-is and doesn't need to do a "double-replace-time-zone"

fix(python): fix comparing tz-aware series with stdlib datetime

---

crates/polars-plan/src/logical_plan/optimizer/type_coercion/mod.rs
py-polars/tests/unit/operations/test_is_in.py

Closes #11523.
Revisits #11427 and cleans things up while addressing the linked regression. Cleaner dtype match branches now, resulting in more obvious (and less) code, with additional `is_in` test coverage for list dtype.

fix(rust,python): streamline `is_in` handling of mismatched dtypes and fix a minor regression

---

.github/workflows/release-drafter.yml
.github/workflows/release-python.yml
CONTRIBUTING.md

* Releases are now triggered by manually triggering the GitHub Actions [workflow](https://github.com/pola-rs/polars/actions/workflows/release-python.yml).
* The benefit of this new approach is that all artifacts are built first, and only if everything succeeds, we publish to PyPI and publish a GitHub release.
* Includes the option to do a dry-run (only build artifacts, do not publish) and specifying a commit hash (if some PRs were merged that should not be included).
* Includes support for pre-releases (when `py-polars/Cargo.toml` version includes pre-release information, e.g. `1.0.0-rc.1`)
* Updated `CONTRIBUTING.md` to describe the new way of working.
This change should make the release process a lot more reliable!

ci(python): Trigger Python release from Actions workflow dispatch

---

.github/workflows/release-python.yml

This [issue](https://github.com/PyO3/maturin-action/issues/215) was fixed, so this workaround is no longer necessary.

ci(python): Remove toolchain specification workaround

---

crates/polars-core/src/datatypes/dtype.rs

Trivial, but cleaner 😅 
Rather than `is_integer` being `is_numeric && !is_float`, `is_integer` and `is_float` both now positively assert what they are and `is_numeric` becomes `is_float || is_integer`. 
Added the one-line docstrings and briefly noted that `decimal` does not count for the purposes of either `is_numeric` or `is_float`.

refactor(rust): use positive assertion for all float/int/numeric dtype checks, rather than partial exclusion

---

crates/polars-core/src/chunked_array/from.rs
crates/polars-core/src/chunked_array/ops/full.rs
py-polars/tests/unit/datatypes/test_list.py

fix: ensure ListChunked::full_null uses physical types

---

crates/nano-arrow/src/compute/arithmetics/basic/div.rs
crates/polars-core/src/chunked_array/arithmetic/numeric.rs
docs/user-guide/concepts/data-types.md

This was in (luckily rather quick) hindsight not the best idea.

revert: reduce guarantees on signed zero/nan

---

py-polars/polars/dataframe/frame.py
py-polars/polars/functions/lazy.py
py-polars/polars/lazyframe/frame.py
py-polars/src/lazyframe.rs

I noticed `collect` had a `**kwargs` argument that was intended for 'internal use' with the only purpose of allowing an `eager` argument. This is definitely bad form. Mostly because users might misspell a parameter name and get unexpected results (instead of an error), e.g. `.collect(straeming=True)` would pass silently.
So I removed `**kwargs` and added a private parameter `_eager`. Easy fix, avoids potential footguns.

refactor(python): Remove `**kwargs` from `LazyFrame.collect()`

---

crates/polars-core/src/chunked_array/ops/append.rs
crates/polars-core/src/utils/mod.rs

Fixes https://github.com/pola-rs/polars/issues/11561.

perf: skip empty chunks in concat

---

crates/nano-arrow/src/io/parquet/read/deserialize/nested_utils.rs
py-polars/tests/unit/io/test_parquet.py

fixes https://github.com/pola-rs/polars/issues/11548.
Error turned out to be from arrow2 / nano-arrow. The reading impl for nested types appears to be copied from the non-nested impl, and ended up inheriting some assumptions that weren't correct for nested types - namely it stopped loading the moment the row count matched the total. In practice this caused the last row in every row group for lists to be incomplete if their data was stored in more than one page.

fix(rust,python): incomplete reading of list types from parquet

---

py-polars/polars/datatypes/constructor.py
py-polars/polars/series/datetime.py
py-polars/polars/series/series.py
py-polars/tests/unit/datatypes/test_temporal.py

fix(python): Add initialization support for python Timedeltas

---

crates/polars-sql/src/context.rs
py-polars/tests/unit/sql/test_sql.py

Ref: https://github.com/pola-rs/polars/issues/9370.
Will come back to this and add proper `UNION BY NAME` and `UNION ALL BY NAME` support later, but we currently silently conflate both of these variations with `UNION [DISTINCT]`.
This PR catches such usage and raises a suitable error, eg:
```
InvalidOperationError: UNION [ALL] BY NAME not yet supported
```
(Will also notice any future flavours of `UNION` that we don't explicitly support, should any new ones be added to the parser later).

fix(rust,python,cli): don't conflate supported UNION ops in the SQL parser with (currently) unsupported UNION "BY NAME" variations

---

crates/polars-sql/src/sql_expr.rs
py-polars/tests/unit/sql/test_sql.py

Closes #8890.
```python
"aa": [-2, -1, 1, 2],
"bb": ["w","x","y","z"],
})
res = ctx.execute("SELECT * FROM frame WHERE aa IN (-3,-1,+2,+4)")
```
```
ComputeError: SQL expression UnaryOp 
{ op: Minus, expr: Value(Number("3", false)) } is not yet supported
```
```
shape: (2, 2)
┌─────┬─────┐
│ aa  ┆ bb  │
│ --- ┆ --- │
│ i64 ┆ str │
╞═════╪═════╡
│ -1  ┆ x   │
│ 2   ┆ z   │
└─────┴─────┘
```

fix(rust,python,cli): handle unary operators applied to numbers used in SQL `IN` clauses

---

py-polars/polars/io/database.py
py-polars/tests/unit/io/test_database_read.py

Closes #7376 and closes #10835.
Continuing to build-out database connectivity; this PR adds support for passthrough of arbitrary parameters to the underlying connection's `execute`.
This enables clean support for _parameterised_ SQL queries (amongst other things, such as control over `arrow-odbc` varchar/binary max buffer length[^1], and more).
Added test coverage for both the feature itself and new potential error conditions.
Parameterised `sqlalchemy` query:
```python
df = pl.read_database(
connection = alchemy_connection,
query = "SELECT * FROM tbl WHERE metric > :value",
execute_options = {"parameters": {"value": 0}},
)
```
Custom `arrow-odbc` upper limits on text/binary buffers bound to variadic columns:
```python
df = pl.read_database(
connection = odbc_connection_string,
query = …
```

feat(python): support `read_database` options passthrough to the underlying connection's `execute` method (enables parameterised SQL queries, etc)

---

docs/src/python/user-guide/expressions/structs.py
docs/user-guide/expressions/structs.md

fixed typo, small layout improvement, removed capitalization from variable name

docs(python): improve struct documentation

---

crates/polars-plan/src/dsl/functions/mod.rs
crates/polars-plan/src/dsl/functions/temporal.rs
py-polars/polars/functions/as_datatype.py
py-polars/src/functions/lazy.rs
py-polars/tests/unit/functions/test_as_datatype.py

feat(rust, python)!: add time_unit argument to duration, default to "us"

---

crates/polars-core/src/frame/group_by/mod.rs
py-polars/tests/unit/operations/test_group_by.py

fix: expand all literals before group_by

---

crates/polars-plan/src/dsl/function_expr/dispatch.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/mod.rs

refactor: Make value_counts and unique_counts function expr non-anonymous

---

crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs
crates/polars-plan/src/dsl/function_expr/temporal.rs

same as https://github.com/pola-rs/polars/pull/11189
none of these functions is "very very cheap" either
there's no `try_binary_elementwise_values` left after this

perf(rust, python): use try_binary_elementwise over try_binary_elementwise_values

---

crates/polars-ops/src/chunked_array/strings/case.rs

Fixes https://github.com/pola-rs/polars/issues/11609.

refactor(rust): avoid nightly rust for case conversion

---

crates/polars-io/src/cloud/mod.rs
crates/polars-io/src/cloud/object_store_setup.rs
crates/polars-io/src/cloud/options.rs
crates/polars-io/src/parquet/async_impl.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-io/src/pl_async.rs
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs

This greatly reduces wall time of reading many small files from an object store. Wall time went from over a minute to ~15 seconds.
This is achieved by caching the latest object-store instance as we would otherwise do multiple dns calls which seem to be rate-limited and can take up to 5secs after a while.
Secondly this resolves #11582 by keeping track of rayon threads that drive the async executor. If the rayon thread is already used driving an async runtime, we spawn a new thread. This doesn't happen often and when it does it is a drop in the bucket of the total runtime as at that point we are reading over 100s of files in parallel from the cloud.

feat: improve performance and fix panic in async parquet reader

---

crates/polars-io/src/json/mod.rs
py-polars/tests/unit/io/test_json.py

This PR fixes `"ComputeError: "schema arguments not yet supported for Array json"`, see https://github.com/pola-rs/polars/issues/11505
The following operations are now supported, (taken from unit tests)
```python
def test_to_from_buffer_arraywise_schema() -> None:
buf = io.StringIO(
"""
[
{"a": 5, "b": "foo", "c": null},
{"a": 11.4, "b": null, "c": true, "d": 8},
{"a": -25.8, "b": "bar", "c": false}
]"""
)
read_df = pl.read_json(buf, schema={"b": pl.Utf8, "e": pl.Int16})
assert_frame_equal(
read_df,
pl.DataFrame(
{
"b": pl.Series(["foo", None, "bar"], dtype=pl.Utf8),
"e": pl.Series([None, None, None], dtype=pl.Int16),
}
),
)
def test_to_from_buffer_arraywise_schema_override() -> None:
buf = io.StringIO(
"""
[
{"a": 5, "b": "foo", "c": null},
{"a": 11.4, "b": null, "c": true, "d": 8}, …
```

feat(rust, python): Implement `schema`, `schema_override` for `pl.read_json` with array-like input

---

py-polars/polars/expr/string.py
py-polars/polars/series/string.py
py-polars/tests/unit/namespaces/test_string.py

The default value of `2` does not make much sense here. This PR deprecates the default value.
@orlp FYI

depr(python): Deprecate default value for `radix` in `parse_int`

---

crates/polars-plan/src/logical_plan/visitor/expr.rs
py-polars/tests/unit/test_cse.py

This fixes #11594.
I'm not 100% sure, but I feel that `slice` can be reused by `cse`.
-------------------------------------------------------------------
Besides:
There should be other bug in reusing CSE that can cause the following plan to occur. I will delve deeper into how to fix this in next PR.
```sql
SELECT [
col("__POLARS_CSER_14783041659764827719").slice(offset=1, length=[(count()) - (1)]).alias("1"),
col("__POLARS_CSER_14783041659764827719").slice(offset=2, length=[(count()) - (1)]).alias("2"),
[(count()) - (1)].alias("__POLARS_CSER_14783041659764827719")] FROM
DF ["a", "b"]; PROJECT 1/2 COLUMNS; SELECTION: "None"
```

fix: slice expr can be taken in cse

---

crates/polars-plan/src/logical_plan/aexpr/mod.rs
py-polars/tests/unit/test_cse.py

This try to fix the bug pointed out in #11628.
BTW, @ritchie46 I sent you a private message yesterday on Discord and I'm not sure if you can receive it. :)

fix: Fix input replacement logic for slice

---

crates/polars-io/src/parquet/read_impl.rs
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs

Whoops, we accidentally didn't use the projection in aysnc parquet reading. fixes #10685

perf: actually use projection information in async parquet reader

---

crates/polars-io/src/cloud/options.rs

Smarter people than me might want to use [`object_store::parse_url`](https://docs.rs/object_store/latest/object_store/fn.parse_url.html) to process `parsed` into an `ObjectStore`. Then decide which cloud provider it is, based on the type of the object store.
Then we could even support http(s) urls as targets. Plus, all the logic would be in something we don't need to maintain :)

refactor(rust): Bring cloud monikers in line with the ones in `is_cloud_url`

---

py-polars/polars/dataframe/frame.py
py-polars/polars/datatypes/classes.py
py-polars/polars/datatypes/constructor.py
py-polars/polars/expr/binary.py
py-polars/polars/expr/datetime.py
py-polars/polars/expr/expr.py
py-polars/polars/expr/string.py
py-polars/polars/functions/col.py
py-polars/polars/functions/lazy.py
py-polars/polars/io/csv/functions.py
py-polars/polars/io/database.py
py-polars/polars/io/delta.py
py-polars/polars/io/ipc/functions.py
py-polars/polars/io/spreadsheet/functions.py
py-polars/polars/series/series.py
py-polars/polars/slice.py
py-polars/polars/testing/asserts.py
py-polars/polars/testing/parametric/primitives.py
py-polars/polars/utils/_construction.py
py-polars/polars/utils/convert.py
py-polars/polars/utils/deprecation.py
py-polars/polars/utils/udfs.py
py-polars/polars/utils/various.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/io/test_spreadsheet.py
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/test_datatypes.py
py-polars/tests/unit/test_testing.py

Addresses #10421 for `py-polars` folder but not rust yet. Some unit tests had to be updated as well due to the new formatting.
All files in `py-polars` have been searched on `raise` and have been checked on the bullet points mentioned in #10421.

feat(python): Standardize error message format

---

crates/nano-arrow/src/util/total_ord.rs

Incredibly minor but came across it while upstreaming to https://github.com/reem/rust-ordered-float, so might as well backport.

perf: slightly faster float equality

---

crates/polars-ops/src/series/ops/rank.rs
py-polars/tests/unit/test_exprs.py

Fixes https://github.com/pola-rs/polars/issues/11252.

refactor: improve rank implementation, especially around nulls

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/datatypes/test_struct.py
py-polars/tests/unit/operations/test_melt.py

Closes #11635.
Fixes a minor oversight; the upgrade of these two methods (to better interop with polars column `selectors`) was accidentally omitted from the previous/larger #10255 update.

feat(python): column selector support for `DataFrame.melt` and `LazyFrame.unnest`

---

py-polars/polars/io/database.py
py-polars/polars/utils/_construction.py
py-polars/tests/unit/io/test_database_read.py

Adding another component to the database connectivity feature set; this PR enables support for generator return of `DataFrame` batches from `read_database`, using a new `iter_batches` mode/option. Works generically across SQLAlchemy, ODBC, and more (provided that the underlying backend/driver actually _has_ such support).
Note that you can set `batch_size` _without_ also setting `iter_batches` (in which case the batches are assembled into a single `DataFrame` for you), but you cannot set `iter_batches` without also providing a `batch_size`.
```python
for frame in pl.read_database(
query = "SELECT * FROM some_table",
connection = user_connection,
iter_batches = True,  # << new mode
batch_size = 1000,
):
do_something(frame)
```
___
Also: closes #10697 as a drive-by (adds …

feat(python): support batched frame iteration over `read_database` queries

---

README.md

Ref: https://github.com/pola-rs/polars/issues/11650.
Seems worth noting this additional use-case for `polars-lts-cpu` in the README.

docs: add note about use of `polars-lts-cpu` for macOS x86-64/rosetta

---

crates/polars-lazy/src/scan/csv.rs
crates/polars-lazy/src/scan/file_list_reader.rs
crates/polars-lazy/src/scan/ipc.rs
crates/polars-lazy/src/scan/ndjson.rs
crates/polars-lazy/src/scan/parquet.rs
crates/polars-lazy/src/tests/io.rs
crates/polars-ops/src/frame/mod.rs
crates/polars-ops/src/series/ops/approx_unique.rs
crates/polars/tests/it/io/csv.rs
examples/read_parquet/src/main.rs
examples/read_parquet_cloud/src/main.rs
py-polars/polars/io/csv/functions.py
py-polars/polars/io/ipc/functions.py
py-polars/polars/io/ndjson.py
py-polars/polars/io/parquet/functions.py
py-polars/polars/lazyframe/frame.py
py-polars/src/lazyframe.rs
py-polars/tests/unit/io/test_lazy_csv.py
py-polars/tests/unit/io/test_lazy_ipc.py
py-polars/tests/unit/io/test_lazy_json.py
py-polars/tests/unit/io/test_lazy_parquet.py

This can improve performance of reading multiple files from the cloud that cannot be globbed. Creating a single `LazyFrame` will amortize the cost of retrieving a schema and dns lookups.
It is of course also more ergonomic. :)

feat: support multiple sources in scan_file

---

crates/polars-lazy/src/tests/queries.rs

When checking out PRs to close, I was testing one and found that I couldn't somehow compile because these annotations were not there to block the test from being compiled.

test(rust): Adding feature annotation

---

crates/polars-time/src/chunkedarray/utf8/infer.rs

While investigating issues, I encountered this block and thought it could be more cleanly written.

refactor(rust): Cleanup the match block for date inference

---

crates/polars-ops/src/frame/join/asof/default.rs
crates/polars-ops/src/frame/join/asof/groups.rs
py-polars/tests/unit/operations/test_join_asof.py

fix(rust, python): Fix match on last item for `join_asof` with `strategy="nearest"`

---

crates/polars-core/src/chunked_array/ops/mod.rs
crates/polars-lazy/src/frame/mod.rs
crates/polars-ops/src/series/ops/horizontal.rs
crates/polars-ops/src/series/ops/mod.rs
crates/polars-plan/src/dsl/function_expr/boolean.rs
crates/polars-plan/src/dsl/function_expr/dispatch.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/functions/horizontal.rs
crates/polars/tests/it/lazy/folds.rs
py-polars/tests/unit/test_errors.py

Will handle other `*_horizontal` dependent on `reduce_exprs` in the next PR.

refactor: sum_horizontal to expression architecture

---

crates/polars-lazy/src/physical_plan/expressions/sortby.rs
py-polars/tests/unit/operations/test_sort.py

fix(python): fix sort_by regression

---

.github/workflows/release-python.yml

Very minor update. Only publish the release after all assets have been uploaded.
Also creates the draft release with all assets when in dry-run mode.

ci(python): Publish release after uploading assets

---

crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/group_by.rs
crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
py-polars/tests/unit/test_predicates.py

perf: push down predicates that refer to group_by keys

---

README.md
crates/nano-arrow/src/array/dictionary/value_map.rs
crates/polars-core/src/hashing/vector_hasher.rs
crates/polars-io/src/cloud/options.rs
crates/polars-ops/src/frame/hashing.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_dispatch.rs
crates/polars-ops/src/frame/join/mod.rs
crates/polars-ops/src/series/ops/approx_algo/hyperloglogplus.rs
crates/polars-plan/src/logical_plan/optimizer/cse.rs
crates/polars-utils/src/functions.rs
py-polars/tests/unit/dataframe/test_df.py
rust-toolchain.toml

chore: update rustc and fix future

---

crates/polars-ops/src/chunked_array/strings/concat.rs
py-polars/tests/unit/functions/test_concat.py

fix: fix seg fault in concat_str of empty series

---

py-polars/polars/dataframe/frame.py
py-polars/polars/series/series.py
py-polars/polars/utils/various.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/utils/test_utils.py

Closes #11691, by clarifying that the 50% percentile _is_ the median.
(Also, as a minor drive-by, includes the `0.50` median in the default percentiles instead of injecting it specially, as otherwise there is no way to _exclude_ that percentile, if desired - this does not change the default behaviour, it just makes things a bit more consistent by allowing the median percentile to play nice with the "percentiles" param).

docs(python): clarify that median is equivalent to the 50% percentile shown in `describe` metrics

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/operations/test_join.py

Closes #11684.
We didn't explicitly support `how="outer"` here, but did let it through silently. It would mostly work, except in the edge-case described in the linked issue; this PR now explicitly allows for an "outer" mode, explicitly _disallows_ any join strategy that we don't support in `update`, and better validates all of the expected behaviour.
Also adds more examples and tests, as the various "how" options (outside of the default "left") were either barely tested or not tested at all (and had no supporting examples).

feat(python): add support for "outer" mode to frame `update` method

---

crates/polars-io/src/parquet/read_impl.rs
py-polars/tests/unit/io/test_hive.py

Fixes https://github.com/pola-rs/polars/issues/11682
`md.num_rows()` cannot be used as `column_idx_to_series` may not read the entire row group when there is a SELECT->LIMIT

fix(rust,python): use actual number of read rows for hive materialization

---

crates/nano-arrow/src/io/parquet/read/statistics/mod.rs
crates/polars-io/Cargo.toml
crates/polars-io/src/parquet/async_impl.rs
crates/polars-io/src/parquet/mod.rs
crates/polars-io/src/parquet/predicates.rs
crates/polars-io/src/parquet/read.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-io/src/predicates.rs
crates/polars-io/src/utils.rs
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs
crates/polars-plan/src/logical_plan/builder.rs
crates/polars-plan/src/logical_plan/hive.rs

A bit wasteful to download a row-group and not use it. :)

perf: process parquet statistics before downloading row-group

---

crates/polars-plan/src/dsl/function_expr/trigonometry.rs
crates/polars-sql/src/functions.rs

1. moving degrees & radians under the mathematic section. It doesn't belong in the array section.
2. Adding documentation for all others that were missing. I know it's kind of obvious in most cases (like sin/cos/floor/...), but still it's better to have it documented.

docs(rust): Improving the documentation of the SQL expressions

---

py-polars/polars/functions/as_datatype.py
py-polars/src/functions/lazy.rs

reordering `pl.duration` arguments in descending value/size order like discussed in #11625 (@MarcoGorelli)

refactor(python): reorder pl.duration arguments

---

crates/polars-plan/src/dsl/function_expr/trigonometry.rs
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/src/expr/general.rs
py-polars/tests/unit/series/test_series.py

During the adjustments of the docs, I noticed that `cot` was implemented as `cos/sin`.
But actually cotangent is just the inverse of tangent. So I was wondering what the effect would be of taking the tangent and inverse it.
Here are the results against the "build-opt" binary on wsl:
_original:_ Time taken to execute 1000000x the collect: 11.39s
_new:_ Time taken to execute 1000000x the collect: 11.10s
I was wondering why I couldn't do `1.0 / tan(v)`... As that might even be faster than what I made here.
And I know it's not much gain, but any gain is good right? 😁
**test script**
```python
import timeit
{
"a": [-4, -3, -2, -1.00001, 0, 1.00001, 2, 3, 4],
}
)
ctx = pl.SQLContext(df=df, eager_execution=False)
"""
SELECT
cot(a) AS …
```

perf(rust): Improve performance of `cot` (cotangent)

---

crates/polars-plan/src/logical_plan/builder.rs

fixes https://github.com/pola-rs/polars/issues/11697.
There's a PanicException overflow when using `ldf.drop_columns(columns)` with `columns.len() > ldf.schema.len()`, because of the substraction of two `usize` integers. Using `saturating_sub` to clamp the difference solves the issue.
I greped for the `*.len() - *.len()` pattern, and found a couple of  subtraction between `usize`s , but they're not as dangerous as this one. This search does not exhaust the `usize-usize` pattern, so there are probably better methods to look for it!

fix(rust): LazyFrame.drop_columns overflow issue when columns.len()>schema.len()

---

docs/src/python/user-guide/transformations/time-series/rolling.py
docs/src/rust/user-guide/transformations/time-series/rolling.rs
py-polars/docs/source/reference/expressions/computation.rst
py-polars/docs/source/reference/series/computation.rst

Closes #11165
The example is a bit more clear without the explode.
Also add the doc entry for `cot` that was missed in https://github.com/pola-rs/polars/pull/11717

docs: Update group_by_dynamic example

---

py-polars/polars/convert.py
py-polars/polars/dataframe/frame.py
py-polars/polars/functions/as_datatype.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/struct.py
py-polars/tests/unit/dataframe/test_df.py

I was writing some tests and found out that our schemas aren't ordered, e.g.:
```python
df = pl.DataFrame({"foo": [1, 2, 3], "bar": [6.0, 7.0, 8.0]})
df_rev = df.select("bar", "foo")
assert df.schema == df_rev.schema   # passes ?!
```
The order of columns might not always be relevant, but it definitely is in some cases. And the schema shouldn't be considered equal if the column order is different.
The simple fix is to use `OrderedDict` for our schemas instead of a regular `dict`. Amazingly, switching doesn't cause any of our tests/lints to fail - only some doctests as the repr is different.
@alexander-beedie Anything I'm missing here, or is this just a quick win?

feat(python): Use `OrderedDict` for schemas

---

docs/user-guide/migration/pandas.md

Based on the `df` output, it seems that the order of columns should be ["c", "type"] rather than ["type", "c"].
```
c type size
0  1    m    3
1  1    n    3
2  1    o    3
3  2    m    4
4  2    m    4
5  2    n    4
6  2    n    4
```

docs: The orders of the df columns in user guide - Migrating: Coming from Pandas

---

crates/polars-plan/src/dsl/functions/temporal.rs
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/functions/as_datatype/test_as_datatype.py
py-polars/tests/unit/functions/as_datatype/test_duration.py
py-polars/tests/unit/operations/test_aggregations.py
py-polars/tests/unit/test_schema.py

Closes #11747
* Refactor the function and related tests
* Add new test and fix the bug

fix: Correctly process subseconds in `pl.duration`

---

Cargo.toml
crates/polars-arrow/Cargo.toml
py-polars/Cargo.lock

The `polars-arrow` crate should be versioned together with the other Polars crates.
I also noticed the license for arrow2 is slightly different from our license; not sure if there's something we can do about that?

chore(rust): Version `polars-arrow` with the other crates

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/utils/_parse_expr_input.py
py-polars/polars/utils/various.py
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/test_lazy.py

Closes #11642, supersedes #11674.
Ended up going a little deeper down the rabbit hole so moved it into my own branch to finish off as I was having issues rebasing / force-pushing to a branch I don't own (some sort of credentials/token issue? 🤷); kudos to @mcrumiller for getting things started with the initial implementation!
* Turns out we can cleanly disambiguate new/old usage of the `predicate` keyword, so only warns on old-style usage.
* Noticed a fast-path for recognising numpy-based boolean masks (and int sequences), so integrated this too.
* The `parse_as_expression` docstring claimed it had a "wrap" param but it didn't - so I added it (and used it) ;)
Adds support for:
* `*predicates` (one _or more_ predicates as positional arguments).
* `**constraints` (`col == value` matches as …

feat(python): extend `filter` capabilities with new support for `*args` predicates, `**kwargs` constraints, and chained boolean masks

---

py-polars/tests/unit/dataframe/test_to_dict.py
py-polars/tests/unit/series/test_to_list.py

I am unhappy with many of our unit tests using `df.to_dict(False)`, for a number of reasons:
1. It doesn't verify dtypes (integer bit width, datetime precision, etc.)
2. It doesn't verify column order (python dictionaries are unordered)
3. It often results in poor test code formatting
4. It prohibits making the `as_series` argument keyword-only, which all booleans should be.
The main argument for using `to_dict(False)` was that the `to_dict` calls passingly test AnyValue conversion, which has caught bugs in the past.
To solve this, I added a proper parametric test for `to_dict` and `to_list`. With this covered, and `to_dict`/AnyValue conversion tested properly, we can now write the rest of our test suite using proper assert tooling (`assert_frame_equal` / `assert_series_equal`).

test(python): Add parametric test for `df.to_dict`/`series.to_list`

---

crates/polars-lazy/src/dsl/list.rs
crates/polars-lazy/src/physical_plan/expressions/aggregation.rs
crates/polars-lazy/src/physical_plan/expressions/apply.rs
crates/polars-lazy/src/physical_plan/expressions/binary.rs
crates/polars-lazy/src/physical_plan/expressions/cast.rs
crates/polars-lazy/src/physical_plan/expressions/group_iter.rs
crates/polars-lazy/src/physical_plan/expressions/mod.rs
crates/polars-lazy/src/physical_plan/expressions/take.rs
crates/polars-lazy/src/physical_plan/expressions/ternary.rs
crates/polars-lazy/src/physical_plan/expressions/window.rs
py-polars/tests/unit/operations/test_group_by.py

fix: fix ambiguity wrt list aggregation states

---

py-polars/polars/utils/convert.py
py-polars/tests/unit/dataframe/test_from_dict.py
py-polars/tests/unit/dataframe/test_to_dict.py
py-polars/tests/unit/series/test_to_list.py

Fixes https://github.com/pola-rs/polars/issues/11744
The culprit was float arithmetic. To illustrate:
```
>>> td = timedelta(seconds=1, microseconds=1000)
>>> td.total_seconds()
1.001
>>> td.total_seconds() * 1_000
1000.9999999999999
>>> int(td.total_seconds() * 1_000)
1000
```
So we cannot use `timedelta.total_seconds()` here - we have to compute the number of subseconds from the `day`/`second`/`microsecond` components.

fix(python): Fix subsecond parsing in timedelta conversions

---

docs/_build/API_REFERENCE_LINKS.yml
docs/user-guide/expressions/column-selections.md

This PR updates the user guide to point to `expand_selector`, which is referenced by the code snippet:
https://github.com/pola-rs/polars/blob/abd758653c02a18e5b6d5bdbd8cbdcf7a0ff0433/docs/src/python/user-guide/expressions/column-selections.py#L86-L91

docs: Link to `expand_selector` in user guide

---

crates/polars-lazy/src/frame/mod.rs
crates/polars-plan/src/logical_plan/projection.rs
py-polars/tests/unit/operations/test_group_by.py

Fixes https://github.com/pola-rs/polars/issues/11762 and https://github.com/pola-rs/polars/issues/11766.

fix(rust,python): only exclude final output names of group_by key expressions

---

py-polars/docs/source/reference/dataframe/modify_select.rst
py-polars/docs/source/reference/lazyframe/modify_select.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/dataframe/group_by.py
py-polars/polars/expr/expr.py
py-polars/polars/lazyframe/frame.py
py-polars/src/lazyframe.rs
py-polars/tests/parametric/test_groupby_rolling.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/operations/map/test_map_groups.py
py-polars/tests/unit/operations/rolling/test_rolling.py
py-polars/tests/unit/operations/test_group_by.py
py-polars/tests/unit/operations/test_group_by_dynamic.py
py-polars/tests/unit/operations/test_group_by_rolling.py

Addresses  #11432
This is just the Python side.
It's not entirely clear to me whether it's still a group-by type operation or not. It's baked into the GroupBy architecture quite firmly on the Rust side 🤔

depr(python): Rename `group_by_rolling` to `rolling`

---

crates/polars-sql/Cargo.toml
crates/polars-sql/src/functions.rs
py-polars/tests/unit/sql/test_sql.py

https://stackoverflow.com/questions/77227895/polars-sql-context-filter-by-date-or-datetime
This was a recent question on SO and the mentioned `DATE` function doesn't seem to exist yet.
I was interested in seeing how `polars-sql` worked and thought I'd have a look.
```python
import datetime
"date": [
datetime.date(2021, 3, 15),
datetime.date(2021, 3, 28),
datetime.date(2021, 4, 4),
],
"version": ["0.0.1", "0.7.3", "0.7.4"]
})
with pl.SQLContext(df=df, eager_execution=True) as ctx:
print(ctx.execute("""SELECT *, date < DATE('2021-03-20') AS "alpha" from df"""))
```
Should `DATETIME` also be added as part of this?

feat(python,rust,cli): add `DATE` function for SQL

---

py-polars/polars/series/series.py
py-polars/tests/unit/series/test_series.py

Now that we have proper AnyValue conversion, pyarrow is no longer needed to convert to Python objects.

depr(python): Deprecate `use_pyarrow` param for `Series.to_list`

---

py-polars/src/error.rs

Before:
```
>>> raise pl.ComputeError('stuff went wrong')
exceptions.ComputeError: stuff went wrong      <--- polars module missing from module path
```
After:
```
>>> raise pl.ComputeError('stuff went wrong')
polars.exceptions.ComputeError: stuff went wrong
```

refactor(python): Fix Exception module paths

---

py-polars/polars/dataframe/frame.py
py-polars/src/dataframe.rs

`DataFrame.get_column(name)` simply called `self[name]` under the hood, which went through a bunch of checks until it finally called `wrap_s(self._df.column(name))`.
Instead, we should call the PySeries method directly, and `__getitem__` should dispatch to `DataFrame.get_column`.

perf(python): Improve `DataFrame.get_column` performance by ~35%

---

py-polars/src/lazygroupby.rs
py-polars/tests/unit/operations/test_group_by.py

Fixes https://github.com/pola-rs/polars/issues/10793.

fix(rust,python): make `PyLazyGroupby` reusable

---

docs/user-guide/migration/pandas.md

While it's true that `Polars` offers the capability to execute data transformations in parallel using expressions, some of the examples in the documentation don't provide a complete 1-to-1 comparison between `Pandas` and `Polars`. To make this comparison more comprehensive, I would recommend contrasting `Pandas` `assign` and `query` methods with `Polars` `with_columns` and `filter` methods.

docs(python): Minor tweak in code example in section Coming from Pandas

---

py-polars/polars/expr/expr.py
py-polars/polars/series/series.py
py-polars/tests/unit/series/test_series.py

Since the first four arguments are mutually exclusive, they should be keyword-only.

depr(python): Deprecate non-keyword args for `ewm` methods

---

crates/polars-arrow/src/io/parquet/read/deserialize/nested_utils.rs
crates/polars-io/src/parquet/read_impl.rs
py-polars/tests/unit/io/test_hive.py

Fixes https://github.com/pola-rs/polars/issues/11796 (regression introduced by https://github.com/pola-rs/polars/pull/11690).
This adds back the `num_rows` arg and includes some more detail in the comment above the function, as well as a test case.
Also did some refactoring around to calculate the `projection_height` upfront, which ended up causing the test from https://github.com/pola-rs/polars/pull/11578 to fail. This PR also improves on that fix to make it more robust.
I'm not actually certain exactly why it fails, but it's likely that the fix done by https://github.com/pola-rs/polars/pull/11578 was happened to produce the correct results because row groups prior to the last were always calling `column_idx_to_series` with the total number of rows remaining to read from the current row …

fix(rust,python): ensure projections containing only hive columns are projected

---

crates/polars-plan/src/dsl/mod.rs

fix(rust): remove flag inconsistency 'map_many'

---

crates/polars-arrow/src/io/parquet/read/deserialize/nested_utils.rs

small cleanup after https://github.com/pola-rs/polars/pull/11803 - the if branch is never executed, so remove it to avoid confusing the next person that reads this.

refactor(rust): remove redundant if branch in nested parquet

---

crates/polars-io/src/cloud/object_store_setup.rs

feat: don't require empty config for cloud scan_parquet

---

crates/polars-io/src/parquet/read.rs
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs
crates/polars-pipe/src/executors/sources/parquet.rs
crates/polars-plan/src/logical_plan/schema.rs

Fixes https://github.com/pola-rs/polars/issues/11809.
This is probably the simplest way to fix it, but I'm unsure whether it's the best way. It appears the async parquet reader gets passed a schema to reduce metadata scanning from cloud, but currently the schema can contain extra hive columns that don't exist in the parquet file, which leads to oob.
This also adds `.with_schema()` to the standard parquet reader - this is purely to align the behavior with the async reader so that the unit tests can catch any potential errors, as currently it appears there isn't any way to directly test the cloud readers.

fix(rust): panic on hive scan from cloud

---

crates/polars-ops/src/frame/join/asof/groups.rs
crates/polars-ops/src/frame/join/hash_join/mod.rs
crates/polars-ops/src/frame/join/mod.rs
crates/polars-ops/src/series/ops/round.rs

In the case of an asof join we can perform the slice before any join indices are calculated instead of right before the final materialization.
For a left join, if the slice is purely a LIMIT we can also LIMIT the left input side.

perf: properly push down slice before left/asof join

---

.github/workflows/test-rust.yml
crates/Makefile
crates/polars-ops/src/chunked_array/interpolate.rs
crates/polars-ops/src/frame/join/mod.rs
crates/polars-ops/src/series/ops/approx_algo/hyperloglogplus.rs
crates/polars-ops/src/series/ops/round.rs
crates/polars-plan/src/dsl/functions/temporal.rs
crates/polars-plan/src/dsl/mod.rs

We somehow weren't running the `polars-ops` tests in the CI.

refactor: add missing polars-ops tests to CI

---

docs/src/python/user-guide/expressions/operators.py

docs(python): fix typo in code example in section Expressions - Basic operators

---

docs/user-guide/transformations/time-series/timezones.md

fix #11774
Doubt the `;` were intended, so replaced them by `.`

docs: fix incorrect example of valid time zones

---

crates/polars-plan/src/logical_plan/optimizer/projection_pushdown/projection.rs
py-polars/tests/unit/test_projections.py

fix: fix project pushdown for double projection contains count

---

crates/polars-core/src/chunked_array/from.rs
crates/polars-ops/src/series/ops/rank.rs
py-polars/src/series/numpy_ufunc.rs

Found this name a bit long/outdated.

refactor(rust): rename new_from_owned_with_null_bitmap

---

crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs
py-polars/tests/unit/streaming/test_streaming_categoricals.py

fixes #11815
supersedes #11834

fix: recursively check allowed streaming dtypes

---

Cargo.toml
crates/polars-arrow/Cargo.toml
crates/polars-error/Cargo.toml
crates/polars-io/Cargo.toml
crates/polars-lazy/Cargo.toml
crates/polars-ops/Cargo.toml
crates/polars-plan/Cargo.toml
crates/polars-time/Cargo.toml
crates/polars/Cargo.toml

Fixes the following warning that appears with every build:
```
warning: /home/stijn/code/polars/crates/polars-error/Cargo.toml: `default-features` is ignored for parquet2, since `default-features` was true for `workspace.dependencies.parquet2`, this could become a hard error in the future
```
Unfortunately there is no way to turn these warnings into errors 😕 
https://github.com/rust-lang/cargo/issues/2568
Also remove some useless `default-features = false` entries for dependencies where this is already specified on the workspace level.

chore: Fix Cargo warning for parquet2 dependency

---

crates/polars-core/src/chunked_array/cast.rs
crates/polars-core/src/series/mod.rs
py-polars/tests/unit/datatypes/test_categorical.py

fixes #11792
supersedes: #11826

fix: recursively apply `cast_unchecked` in lists

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/database.py
py-polars/tests/unit/io/test_database_read.py

Performance enhancement plus bugfix (now I have access to a Databricks env was able to much more thoroughly test this out).
* SQLAlchemy connections against Databricks are introspected and the query is issued against the underlying _raw_ connection so we can take advantage of Arrow transport. 
* Improved/refactored Arrow return codepath in `ConnectionExecutor` indirection.
* Fixed an issue with 'iter_batches' mode prematurely closing the query cursor.
* Fixed 'iter_batches' mode not working for Databricks SQL connections.
* Parameterised and refactored `test_read_database_mocked`.
```python
from sqlalchemy.engine import create_engine
alchemy_connection = create_engine(
"databricks://token:***@***.azuredatabricks.net:443/blah",
connect_args={
"http_path": …
```

perf(python): optimise `read_database` Databricks queries made using SQLAlchemy connections

---

crates/polars-core/src/chunked_array/ops/append.rs

Calling `ca.null_count()` and `ca.last_non_null()` is potentially quadratic if append is called in a loop.

perf: fix quadratic behavior in append sorted check

---

crates/polars-core/src/chunked_array/builder/binary.rs
crates/polars-core/src/chunked_array/builder/boolean.rs
crates/polars-core/src/chunked_array/builder/primitive.rs
crates/polars-core/src/chunked_array/builder/utf8.rs
crates/polars-core/src/chunked_array/from.rs
crates/polars-core/src/chunked_array/mod.rs
crates/polars-core/src/chunked_array/object/builder.rs
crates/polars-core/src/chunked_array/ops/append.rs
crates/polars-core/src/chunked_array/ops/apply.rs
crates/polars-core/src/chunked_array/ops/chunkops.rs
crates/polars-core/src/chunked_array/upstream_traits.rs
crates/polars-core/src/series/mod.rs
crates/polars-core/src/utils/mod.rs
crates/polars-lazy/src/physical_plan/streaming/convert_alp.rs

@orlp changed order semantics which made it necessary to check null_count whilst doing an append. That showed our quadratic behavior as we iterated over all chunks to sum the null count per append.
This fixes that by caching the null count on the chunkedarray.

perf: fix accidental quadratic behavior; cache null_count

---

py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #11877.
Raises a _much_ more helpful error if the requested sheet is not found.
```python
pl.read_excel("test.xlsx", sheet_id=999)
```
```python
```

fix(python): raise a suitable error from `read_excel` and/or `read_ods` when target sheet does not exist

---

py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #11850.
Need to take a shallow-copy of "read_csv_options" before modifying/updating it, or reading from multiple sheets with the default engine (when we have "schema_overrides") fails with an inadvertent `ParameterCollisionError`.

fix(python): address issue with inadvertently shared options dict in `read_excel`

---

py-polars/polars/io/spreadsheet/functions.py
py-polars/polars/utils/_construction.py
py-polars/tests/unit/io/test_spreadsheet.py
py-polars/tests/unit/test_constructors.py
py-polars/tests/unit/test_errors.py

Closes #11896.
Straightforward fix; avoid implicit boolean inference (we _know_ we have a sequence at this point, but that sequence may be a numpy array which -quite rightly- doesn't like implicit bool usage). Also adds the missing test coverage.

fix(python): address DataFrame construction error with lists of `numpy` arrays

---

crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
py-polars/tests/unit/test_predicates.py

This fixes #11883. More details see https://github.com/pola-rs/polars/issues/11883#issuecomment-1772493101.

fix: predicate push-down remove predicate refers to alias for more branch

---

crates/polars-core/src/chunked_array/logical/categorical/from.rs
crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/logical/categorical/ops/append.rs
crates/polars-core/src/chunked_array/logical/categorical/ops/unique.rs
crates/polars-core/src/chunked_array/logical/categorical/ops/zip.rs
crates/polars-core/src/chunked_array/mod.rs
crates/polars-core/src/chunked_array/ops/chunkops.rs
crates/polars-core/src/chunked_array/ops/compare_inner.rs
crates/polars-core/src/chunked_array/ops/sort/arg_sort_multiple.rs
crates/polars-core/src/chunked_array/ops/sort/categorical.rs
crates/polars-core/src/frame/group_by/perfect.rs
crates/polars-core/src/series/comparison.rs
crates/polars-core/src/series/implementations/categorical.rs
crates/polars-core/src/series/into.rs
crates/polars-ops/src/frame/join/hash_join/zip_outer.rs
crates/polars-ops/src/series/ops/is_in.rs
py-polars/tests/unit/datatypes/test_categorical.py

fix(python): set null_count on categorical append

---

docs/user-guide/concepts/lazy-vs-eager.md
docs/user-guide/expressions/plugins.md

@MarcoGorelli polars-business is on the list. ;)

docs: fix some typos and add polars-business to curated plugin list

---

py-polars/polars/expr/expr.py
py-polars/polars/expr/list.py
py-polars/polars/series/list.py
py-polars/polars/series/series.py

Addressing docs issue described in #11874. 
Different PR #11875 was failing on Windows, possibly for some CRLF issue, or potentially something even more subtle. Created this instead.

docs(python): Fix docstring for `diff` methods

---

py-polars/polars/lazyframe/frame.py
py-polars/polars/utils/various.py
py-polars/tests/unit/test_predicates.py
py-polars/tests/unit/utils/test_utils.py

* Noticed we were accepting (and essentially ignoring) invalid predicates, returning _all_ rows instead of raising an error. 
* Codified the existing behaviour of `filter(True)` and `filter(False)` with dedicated fast-paths and new unit tests.
* Added test coverage for a number of utility functions (and marginally enhanced them).
```python
df = pl.DataFrame({"colx": ["aa", "bb", "cc"]})
```
```python
df.filter( 1, 2, 3, 4, 5, 6, 7 )
```
```
ValueError: Invalid predicate for `filter`: 1
```

fix(python): raise suitable error on invalid predicates passed to `filter` method

---

crates/polars-io/src/csv/utils.rs
py-polars/tests/unit/io/test_csv.py

To fix https://github.com/pola-rs/polars/issues/11611

fix: `read_csv` for empty lines

---

.github/workflows/test-python.yml
crates/polars-core/src/config.rs
crates/polars-error/src/lib.rs
crates/polars-io/src/cloud/glob.rs
crates/polars-io/src/cloud/mod.rs
crates/polars-io/src/cloud/object_store_setup.rs
crates/polars-io/src/cloud/options.rs
crates/polars-io/src/parquet/read.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-io/src/utils.rs
crates/polars-lazy/Cargo.toml
crates/polars-lazy/src/physical_plan/executors/scan/ipc.rs
crates/polars-lazy/src/physical_plan/executors/scan/mod.rs
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs
crates/polars-lazy/src/physical_plan/planner/lp.rs
crates/polars-lazy/src/scan/csv.rs
crates/polars-lazy/src/scan/file_list_reader.rs
crates/polars-lazy/src/scan/ipc.rs
crates/polars-lazy/src/scan/ndjson.rs
crates/polars-lazy/src/scan/parquet.rs
crates/polars-pipe/src/executors/sources/parquet.rs
crates/polars-pipe/src/pipeline/convert.rs
crates/polars-plan/src/logical_plan/builder.rs
crates/polars-plan/src/logical_plan/file_scan.rs
crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/logical_plan/options.rs
crates/polars-plan/src/logical_plan/schema.rs
py-polars/Cargo.lock
py-polars/src/lazyframe.rs
py-polars/tests/unit/io/test_parquet.py

This will amortize the dag cost and ensures we can run aysync on a single runtime.

perf: support multiple files in a single scan parquet node.

---

py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/polars/expr/list.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/list.py
py-polars/polars/series/series.py
py-polars/src/dataframe.rs
py-polars/src/expr/general.rs
py-polars/src/lazyframe.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/operations/map/test_map_batches.py
py-polars/tests/unit/operations/rolling/test_rolling.py
py-polars/tests/unit/operations/test_group_by_dynamic.py
py-polars/tests/unit/operations/test_window.py
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/test_lazy.py

Closes https://github.com/pola-rs/polars/issues/11874
The parameter should align with `diff`. As discussed in the linked issue, the name `periods` doesn't make much sense here. `n` is simpler and easy to understand in this context.
Also added a default value to `DataFrame.shift` and dispatch it to the lazy implementation.

depr(python): Rename `shift` parameter from `periods` to `n`

---

crates/polars-lazy/src/dsl/list.rs

Fixes https://github.com/pola-rs/polars/issues/11782
1. I have no rust background, so make sure this is the correct fix
2. I assume the reason this bug wasn't caught is that no testing is done for bigidx builds. Is that something worth exploring? Since `polars-u64-idx` builds are published on pypi, I was assuming some level of testing was done.

fix: avoid integer overflow in offsets_to_groups when bigidx is enabled

---

py-polars/docs/source/reference/config.rst

Closes #11935 
Added set_fmt_table_cell_len to API docs folder

docs(python): Add `set_fmt_table_cell_list_len` to API docs

---

py-polars/polars/dataframe/frame.py
py-polars/polars/io/json.py
py-polars/src/dataframe.rs
py-polars/tests/unit/io/test_json.py

This PR partially fixes #11148 
The following operations are now supported, (taken from unit tests)
```
def test_json_infer_schema_length_11148() -> None:
response = [{"col1": 1}] * 100 + [{"col1": 1, "col2": 2}] * 50
result = pl.read_json(json.dumps(response).encode(), infer_schema_length=101)
assert set(result.columns) == {"col1", "col2"}
```

feat(python): Add `infer_schema_length` to `pl.read_json`

---

py-polars/src/expr/binary.rs
py-polars/src/expr/datetime.rs
py-polars/src/expr/general.rs
py-polars/src/expr/rolling.rs
py-polars/src/expr/string.rs

I noticed a lot of the `PyExpr` methods would clone the `PyExpr` and then take the inner `Expr`. It should be slightly more efficient to take the inner `Expr` and clone that.

refactor(python): make cloning `PyExpr` consistent

---

py-polars/Cargo.lock
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/polars/expr/list.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/list.py
py-polars/polars/series/series.py
py-polars/src/expr/general.rs
py-polars/src/lazyframe.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/operations/map/test_map_batches.py
py-polars/tests/unit/operations/rolling/test_rolling.py
py-polars/tests/unit/operations/test_group_by_dynamic.py
py-polars/tests/unit/operations/test_shift.py
py-polars/tests/unit/operations/test_window.py
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/test_lazy.py

Closes #10629 
In the Python API, it makes a lot of sense for this to be one function, with an optional `fill_value`.
In the Rust API, it actually makes sense for there to be two separate functions, as there are no default arguments. So I left the Rust side intact.

depr(python): Deprecate `shift_and_fill` in favor of `shift`

---

crates/polars-core/src/prelude.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs
py-polars/Cargo.lock

we first downloaded all the files before we applied the limit. This also ensures we will batch reads by the number of threads we have. E.g. not that we start downloading 2000 files concurrently and completely smother.

perf: drasticly improve performance of limit on async parquet datasets

---

py-polars/docs/Makefile

If we're going to `make clean`, let's make it _really_ clean  ;)

chore(python): include the "build" dir when running `make clean` for docs

---

.github/workflows/docs-global.yml
docs/development/contributing.md
docs/development/versioning.md
docs/index.md
docs/mlc-config.json
docs/releases/changelog.md
docs/releases/migration/0.19.md
docs/releases/upgrade/0.19.md
mkdocs.yml

* Added a section "Development" with two subsections:
* Contributing - for now I copied the CONTRIBUTING.md here, but we can extend this with subpages including things like preferred code style etc.
* Versioning - includes our versioning scheme and I wrote down our policy on breaking changes. I think this is important for managing user expectations going into 1.0.0
* Added a section "Releases" with two subsections:
* Changelog - for now this points to our GitHub releases, but I intend to set up our CI to publish the changelog to our docs too.
* Upgrade guide - this should include an upgrade guide for each breaking release.
* Add config file for the Markdown Link Checker, as it somehow is tripped up by crates.io links
After this is released, I will update CONTRIBUTING.md to point to the …

docs: Add `Development` and `Releases` sections to the documentation

---

crates/polars-core/src/datatypes/mod.rs
crates/polars-ops/src/frame/join/asof/default.rs
crates/polars-ops/src/frame/join/asof/groups.rs
crates/polars-ops/src/frame/join/asof/mod.rs
crates/polars-utils/src/abs_diff.rs
crates/polars-utils/src/lib.rs
py-polars/tests/unit/operations/test_join_asof.py
py-polars/tests/unit/test_errors.py

This PR should reduce the code size and optimize the performance of the `asof_join`, as well as allow null and string keys.
Fixes https://github.com/pola-rs/polars/issues/11966.

feat: optimize asof_join and allow null/string keys

---

crates/polars-ops/src/frame/join/asof/default.rs
crates/polars-ops/src/frame/join/asof/groups.rs
crates/polars-ops/src/frame/join/asof/mod.rs

My previous PR gave a regression for inputs without any nulls, this resolves that.

perf: fix regression non-null asof join

---

.github/workflows/release-drafter.yml
.github/workflows/release-python.yml

If new commits were merged while the release workflow was running, the GitHub release would pick up those new commits and end up tagging the wrong commit. This fixes the issue.

ci(python): Fix release tag

---

py-polars/pyproject.toml

This is the second time this package breaks our CI due to type hint issues.
I opened a [PR](https://github.com/data-apis/dataframe-api-compat/pull/18) in the repo to fix this specific one, but it seems that there is no type checking in their CI. So I think it's best to turn off type checking for this package until the type hints are more reliable.
@MarcoGorelli FYI - I don't mind helping out a bit in that repo with regards to type hints, with the Polars side of things at least. Let me know if there is something I can help you with.

chore(python): Disable type checking for `dataframe_api_compat` dependency

---

crates/polars-ops/src/chunked_array/strings/pad.rs
py-polars/polars/expr/string.py
py-polars/polars/series/string.py
py-polars/tests/unit/namespaces/string/test_pad.py

Padding should take into account the number of characters, not the number of bytes. See the tests for examples.
I left the implementation of `zfill` alone, as it's intended for numeric strings which are ASCII, and operating on bytes is slightly more efficient.

fix: Fix padding for non-ASCII strings

---

.github/workflows/lint-python.yml
CONTRIBUTING.md
docs/development/contributing.md
py-polars/Makefile
py-polars/polars/config.py
py-polars/polars/dataframe/frame.py
py-polars/polars/datatypes/convert.py
py-polars/polars/interchange/dataframe.py
py-polars/polars/interchange/protocol.py
py-polars/polars/testing/parametric/primitives.py
py-polars/polars/utils/_async.py
py-polars/polars/utils/_construction.py
py-polars/pyproject.toml
py-polars/requirements-lint.txt
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/datatypes/test_categorical.py
py-polars/tests/unit/datatypes/test_decimal.py
py-polars/tests/unit/datatypes/test_list.py
py-polars/tests/unit/datatypes/test_struct.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/functions/as_datatype/test_as_datatype.py
py-polars/tests/unit/io/test_hive.py
py-polars/tests/unit/namespaces/test_binary.py
py-polars/tests/unit/namespaces/test_list.py
py-polars/tests/unit/operations/map/test_map_elements.py
py-polars/tests/unit/operations/test_group_by_dynamic.py
py-polars/tests/unit/operations/test_group_by_rolling.py
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/test_lazy.py

Closes https://github.com/pola-rs/polars/issues/11993
Overal, some nice formatting improvements, and of course, much faster formatting!

chore: Replace `black` by `ruff format`

---

py-polars/polars/testing/asserts/frame.py
py-polars/polars/testing/asserts/series.py
py-polars/tests/unit/test_constructors.py
py-polars/tests/unit/testing/test_assert_frame_equal.py
py-polars/tests/unit/testing/test_assert_series_equal.py

With the upcoming fix that makes NaN values equal by default, this parameter is no longer useful.
If people really want the functionality of unequal NaNs, they can fill the NaNs in one of the frames/series with a sentinel value.
Removing this option will greatly simplify the assert utils code.

depr(python): Deprecate `nans_compare_equal` parameter in assert utils

---

crates/polars-core/src/chunked_array/list/mod.rs
py-polars/tests/unit/functions/test_repeat.py

fix: fix apply_to_inner's dtype

---

crates/polars-ops/src/series/ops/horizontal.rs
py-polars/tests/unit/functions/aggregation/test_horizontal.py

fix: sum_horizontal should not always cast to int

---

crates/polars-arrow/src/legacy/kernels/comparison.rs
crates/polars-core/src/chunked_array/comparison/mod.rs
crates/polars-core/src/series/comparison.rs
py-polars/tests/unit/datatypes/test_array.py

This closes #12012.
Due to another bug(https://github.com/pola-rs/polars/issues/12012#issuecomment-1779189266), tests for `null` array can't introduce atm.

feat: enable eq and neq for array dtype

---

crates/polars-core/src/utils/supertype.rs
py-polars/tests/unit/datatypes/test_array.py

Partially addresses #12012
This allows operations between List and Array types by casting to List.
Also should allow operations between Array types (though they are not implemented, so I cannot test for this...).

feat: Add supertype for `List`/`Array`

---

crates/polars-lazy/src/physical_plan/expressions/binary.rs
py-polars/tests/unit/operations/test_group_by.py

fix: binary agg should group aware if literal not a scalar

---

py-polars/polars/datatypes/convert.py
py-polars/polars/dependencies.py
py-polars/polars/utils/_construction.py
py-polars/tests/unit/test_constructors.py

Closes #12007.
Something of an edge-case as you'd usually expect numpy values in `np.array` form, not as a list of scalars; in this case we load via AnyValue (as before), and then refine the type (new).

fix(python): improve ingest from `numpy` scalar values

---

py-polars/polars/lazyframe/frame.py
py-polars/polars/utils/_construction.py
py-polars/tests/unit/test_schema.py

We had a slight inconsistency with schema typing: both `SchemaDefinition` and `SchemaDict` are defined as `Mapping`, but there were a handful of internal checks being made against `dict` instead.
This allowed otherwise invalid schema-like objects to be passed to most constructors _without_ triggering an error; the given object would mostly just be ignored (a colleague hit this one at work just now ;)
Have fixed the `isinstance` checks and added explicit coverage of schema objects derived from `Mapping`.
```python
df = pl.DataFrame(schema=MappingSchema(colx="eggs", coly="sausages"))
```
```
ValueError: cannot infer dtype from 'eggs' (type: 'str')
```

fix(python): fix issue with invalid `Mapping` objects used as schema being silently ignored

---

crates/polars-parquet/Cargo.toml
py-polars/Cargo.lock

`polars-arrow` is already using zstd 0.13:
https://github.com/pola-rs/polars/blob/51e3d9a980f9f2543b32ffba4173a524990a4e5b/crates/polars-arrow/Cargo.toml#L49

chore(rust): upgrade zstd to 0.13 in `polars-parquet`

---

docs/_build/API_REFERENCE_LINKS.yml
docs/src/python/user-guide/io/excel.py
docs/user-guide/io/excel.md
mkdocs.yml

- Add basic excel markdown and python page
- Add excel page to user guide index
- Add links to excel API pages

docs(python): Add Excel page to user guide

---

.github/workflows/lint-global.yml
py-polars/requirements-lint.txt
py-polars/tests/unit/series/test_series.py

Was starting to integrate these further into our codebase at work, so spotted the new releases...
Only a single line of code changed.
All minor point updates:
* `ruff`: 0.1.2 → 0.1.3
* `mypy`: 1.60 → 1.61
* `typos`: 1.16.20 → 1.16.21
@stinodego: Looks like the `ruff` update includes a fix for something 
that I think you spotted earlier? (unexpected spacing around `**`) 😄

chore(python): minor updates to lint-related dependencies

---

crates/polars-arrow/src/compute/cast/mod.rs
crates/polars-arrow/src/compute/cast/utf8_to.rs
crates/polars-arrow/src/temporal_conversions.rs
crates/polars-core/src/chunked_array/cast.rs
py-polars/tests/unit/operations/test_cast.py
py-polars/tests/unit/test_lazy.py
py-polars/tests/unit/test_queries.py

Closes #9994 , closes https://github.com/pola-rs/polars/issues/10478
The implementation I did in this PR support converting strings to date or datetime, it only support specific formats which are the following:
* %Y-%m-%d
* %Y-%m-%dT%H:%M:%S
* %Y-%m-%dT%H:%M:%S.3f
* %Y-%m-%dT%H:%M:%S%.f%:z
Additionally:
* <s>I found that timestamp casting for time-unit milliseconds and microseconds is not implemented in arrow2 library, so I opened [this issue](https://github.com/jorgecarleitao/arrow2/issues/1541). </s> This is now implemented in nano-arrow crate inside polars.
* Converting date times with the following format `"2021-01-01 12:54:58.432"` or `"2021-01-01 12:54:58"` is not supported by nano-arrow cast function, it only supports RFC3339(or a variation of it), should  the other formats be …

feat(rust): casting utf8 to temporal 

---

crates/polars-ops/src/chunked_array/strings/concat.rs
py-polars/tests/unit/namespaces/string/test_string.py

aggregation methods should always return a single value, otherwise it can lead to unexpected behavior and bugs (e.g. #12053)
current behavior:
- empty list: return Series of shape (0,) >>>>> this is the bug
- otherwise: return Series of shape (1,) with the concatenated/joined string
PR:
- always return Series of shape (1,) with the concatenated/joined string
- if empty list, return empty string (as discussed here:https://github.com/pola-rs/polars/issues/10814#issuecomment-1700971115)
```python
pl.Series([], dtype=pl.Utf8).str.concat()
shape: (0,)
[
]
shape: (1,)
[
""
]
```
Note: this does not address the issue of skipping nulls (#10814) but only fixes the bug for empty lists

fix(python,rust): str.concat on empty list

---

py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #12054 and closes #12054. If the user hasn't explicitly set these options themselves, we should default them to sensible values - otherwise we can silently lose data and/or precision that _is_ available in the target worksheet.
Applies to "xlsx2csv" engine (so _before_ we read the resulting CSV data with our own parser):
* `skip_hidden_rows` → False,
* `floatformat` → "%f"
(The other two defaults are _not_ a change from the existing behaviour, they just codify the expected values).
* `read_excel` supports more than one engine now, but "read_csv_options" and "xlsx2csv_options" only apply when using the xlsx2csv engine; we now ensure that these options are not mis-specified alongside the openpyxl engine (will think about cleaning this up further to make it more generic later 🤔)

fix(python): improved xlsx2csv defaults for `read_excel`

---

py-polars/polars/series/series.py
py-polars/polars/testing/asserts/series.py
py-polars/src/series/mod.rs

Elements now return a `Series` rather than a Python `list`. This is consistent with the behavior of `List` types.
Also remove the Array compatibility workaround for the assert utils.

fix(python): Fix `get_index`/iteration for `Array` types

---

docs/src/python/user-guide/expressions/null.py

It can be observed that the output format of `fill_literal_df` is not consistent with other examples in this section. This inconsistency is due to the presence of an extra comma. Instead of simply removing the extra comma, I would suggest rewriting the code as proposed, which aligns with the format of other code examples in this section.
```python
fill_literal_df = (
pl.col("col2").fill_null(
pl.lit(2),
),
), # <= extra comma
)
print(fill_literal_df)
```
```
(shape: (3, 2)
┌──────┬──────┐
│ col1 ┆ col2 │
│ ---  ┆ ---  │
│ i64  ┆ i64  │
╞══════╪══════╡
│ 1    ┆ 1    │
│ 2    ┆ 2    │
│ 3    ┆ 3    │
└──────┴──────┘,)
```

docs(python): Minor tweak in code example in section Expressions/Missing data

---

docs/user-guide/expressions/plugins.md

This might make it easier to grok how the rust and python files should be organized.

docs: visualize plugin directory layout in user guide

---

crates/polars-plan/src/logical_plan/builder.rs
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/test_errors.py
py-polars/tests/unit/test_schema.py

Fixes https://github.com/pola-rs/polars/issues/12074.
This makes `LogicalPlanBuilder::filter` error immediately if `.filter()` is passed non-existent columns, whereas previously the error would only be raised after executing the physical plan (or not raised at all if `PredicatePushDown::push_down`  sent it to a `Node` where the column name existed).
Note there are multiple other functions under `LogicalPlanBuilder` that also currently don't error:
```python
>>> pl.LazyFrame().sort("x")
<LazyFrame [0 cols, {}] at 0x7F78FF5E1590>
>>> pl.LazyFrame().drop_nulls("x")  # notably under discussion https://github.com/pola-rs/polars/issues/11913
<LazyFrame [0 cols, {}] at 0x7F78F15046D0>
```

fix: ensure filter predicate inputs exist in schema

---

crates/polars-ops/src/chunked_array/strings/concat.rs
crates/polars-plan/src/dsl/function_expr/mod.rs
crates/polars-plan/src/dsl/function_expr/strings.rs
crates/polars-plan/src/dsl/string.rs
py-polars/polars/expr/string.py
py-polars/polars/series/string.py
py-polars/src/expr/string.rs
py-polars/tests/unit/namespaces/string/test_string.py

This closes #6919.
Per comment(https://github.com/pola-rs/polars/issues/10814#issuecomment-1700983024) and our discuss in discord channel.
Please note that this change the behavior of `str.concat` contains `null` values as we no longer display null as string `"null"`. So this might be a breaking change, do I need to do some extra steps on the python side to mark this behavior change?

feat: Introduce ignore_nulls for str.concat

---

py-polars/polars/dataframe/frame.py
py-polars/src/file.rs
py-polars/tests/unit/io/test_csv.py

Closes #7420.
Simple expansion of supported write-targets; we were unnecessarily excluding potentially valid write-targets by insisting that they _also_ had `read` and `seek` methods (which are not actually used for writes). We can use the value of the existing "truncate" param to infer whether or not we are writing and adjust the detection of required methods accordingly.
As per @ghuls' original issue this prevented the use of compressed write-targets mediated by libraries such as `xopen` (which creates a writer with no associated read/seek methods).
```python
import xopen
"a": [10,20,30],
"b": ["x"x,"yy","zz"],
})
target = "test.csv.zst"
with xopen.xopen(target, "wb") as f:
df.write_csv(f)
with open(target, "rb") as buf:
magic_bytes = buf.read(4) …
```

feat(python): improved support for use of file-like objects with `DataFrame` "write" methods

---

py-polars/polars/testing/asserts/frame.py
py-polars/polars/testing/asserts/series.py
py-polars/tests/unit/testing/test_assert_frame_equal.py
py-polars/tests/unit/testing/test_assert_series_equal.py

Closes #11771
* Some refactoring of assertion of nested values.
* Improved some tracebacks.
* Support for Decimal types (through casting to float - until https://github.com/pola-rs/polars/issues/12118 is fixed)
Done with the improvements to this util for now. I'll wait until NaNs equality is fixed and the nan equality parameter is removed - then we can achieve some good improvements.

feat(python): Support decimals in assert utils

---

docs/development/contributing/index.md
docs/src/python/user-guide/io/cloud-storage.py

doc: fix incorrect `filter` syntax

---

crates/polars-plan/src/dsl/function_expr/strings.rs

Addendum to https://github.com/pola-rs/polars/pull/10298#issuecomment-1786722819 in light of comments from https://github.com/pola-rs/polars/pull/10671
In https://buttondown.email/NotANumber/archive/faster-development-with-polars-and-a-bit-of/, this error message was praised:
> I rather like the short error report on [" Nov 2013", "June 2022"]
This keeps the part which was praised:
```python
In [1]: pl.Series(
...:     name='date',
...:     values=['2019-01-01', 'a', 'b', '2019-01-02', '2019-01-03', 'c', 'd', 'e', 'a', 'a'],
...: ).str.to_date(exact=False)
ComputeError: strict date parsing failed for 7 value(s) (first 3 failures: ["a", "b", "c"])
You might want to try:
- setting `strict=False`
- setting …
```

perf: Reduce compute in error message for failed datetime parsing

---

crates/polars-core/src/schema.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/utils/_construction.py
py-polars/src/dataframe.rs
py-polars/tests/unit/dataframe/test_df.py

Closes #12032.
* We weren't passing information available in the user-provided "schema_overrides" param down into the Rust-side functions where the initial type inference occurs; consequently large UInt64 values would first get inferred as Float64 _before_ being cast back to UInt64, thereby losing accuracy.
* This PR enhances the Rust-side `read_dicts` and `finish_from_rows` methods, allowing them to integrate the additional/optional information so that they can establish the correct dtypes for overridden columns _without_ first mediating via an inferred type.
```python
recs = [
{"id":9187643043065364490, "misc":333},
{"id":9223671840084328467, "misc":666},
{"id":9187643043065364505, "misc":999},
]
df = pl.from_records( recs, schema_overrides={"id":pl.UInt64} )
``` …

fix(rust,python): make python `schema_overrides` information available to the rust-side inference code when initialising from records/dicts

---

README.md

Fixed the casing of `Dataframe` to `DataFrame` in the README.

doc: Fix casing in DataFrame in README.

---

.github/workflows/docs-global.yml
.github/workflows/docs-python.yml
.github/workflows/release-python.yml

Closes #12152
The tags created by the new release workflow did not trigger the docs deployment workflows. So I set up a "repository dispatch" to trigger them.
Note that we'll have to wait until the new Python release before the stable API reference is updated.

ci: Fix triggers for docs deployment

---

py-polars/polars/expr/string.py

The PR contrast the behavior, cross-references, and gives additional examples on 
- `strip_chars_start`
- `strip_chars_end`
- `strip_prefix`
- `strip_suffix`

docs(python): Improve `strip_{prefix, suffix}` & `strip_chars_{start, end}`

---

crates/polars-lazy/src/frame/mod.rs
crates/polars-plan/src/dsl/functions/horizontal.rs
crates/polars-plan/src/dsl/functions/mod.rs
crates/polars-plan/src/logical_plan/builder.rs
crates/polars/tests/it/lazy/folds.rs
py-polars/src/functions/aggregation.rs
py-polars/tests/unit/functions/aggregation/test_horizontal.py

This fixes #12093.
Currently, `all/any/sum_horizontal` will raise: `expression: '{method_name}' didn't get any inputs`. But `min/max_horizontal` does not. I'm not sure whether we should raise an error here or not, in other words whether we allow `*_horizontal` without any inputs. But I think they should at least maintain consistent behavior in this case. 
This PR tend to raise in this case, but If all of them shouldn't raise an error, then I would modify `all/any/sum_horizontal` instead. 
Another thing to note is that in the Python API they all allow no parameters to be passed in(as only have `*` args):
```python
def *_horizontal(*exprs: IntoExpr | Iterable[IntoExpr]) -> Expr:
```
So if we decide to raise, perhaps corresponding modifications should also be made here.

fix(rust): Raise if *_horizontal without inputs

---

.github/workflows/release-python.yml
py-polars/Cargo.lock
py-polars/Cargo.toml

Related to https://github.com/pola-rs/polars/issues/12180

ci: Temporarily disable aarch linux wheel in Python release workflow

---

py-polars/polars/interchange/buffer.py
py-polars/tests/unit/interchange/test_buffer.py
py-polars/tests/unit/interchange/test_roundtrip.py

As of pyarrow 14, we can now roundtrip booleans. This caught a bug for boolean buffers with an offset.

fix(python): Fix interchange protocol boolean buffer size

---

Cargo.toml
crates/polars-sql/src/context.rs
crates/polars-sql/src/sql_expr.rs
py-polars/Cargo.lock
py-polars/tests/unit/sql/test_sql.py

Follow-up to https://github.com/pola-rs/polars/pull/11597; enables [support](https://github.com/sqlparser-rs/sqlparser-rs/pull/997) for `UNION [DISTINCT] BY NAME`. Needed a few minor code updates on our side, following enhancements to `ARRAY`, `CAST`, and `TRIM` parsing support.

build: update `sqlparser-rs` to `0.39`

---

crates/polars-plan/src/dsl/function_expr/list.rs
crates/polars-plan/src/dsl/list.rs
py-polars/docs/source/reference/expressions/list.rst
py-polars/docs/source/reference/series/list.rst
py-polars/polars/expr/list.py
py-polars/polars/series/array.py
py-polars/polars/series/list.py
py-polars/src/expr/list.rs
py-polars/tests/unit/namespaces/test_list.py

Related to https://github.com/pola-rs/polars/issues/9978
To be honest, I'm having doubts about the usefulness of this expression.
In lazy mode, we cannot infer the width from the data, so we'll have to provide it as an argument. And at that point, we might as well just use `cast` and provide the inner dtype too. So the usefulness is limited.
Anyway, I already put in the work so let me know what you think.

feat: Add `.list.to_array` expression

---

.github/workflows/release-python.yml
py-polars/pyproject.toml
py-polars/rust-toolchain.toml

* Include `rust-toolchain.toml` with sdist/wheels. This allows maturin to find the right toolchain when building from source during a `pip install` of the sdist.
* A symlink to the toplevel `rust-toolchain.toml` was added to the py-polars directory. maturin automatically includes the real file.
* Remove the step to replace the symlinked README with the real README. maturin does this automatically for the sdist. The wheels do not include the README anyway.

build(python): Include `rust-toolchain.toml` with sdist/wheels

---

crates/polars-arrow/src/legacy/kernels/mod.rs
crates/polars-arrow/src/legacy/kernels/time.rs
crates/polars-ops/src/chunked_array/datetime/replace_time_zone.rs
crates/polars-time/src/month_start.rs
crates/polars-time/src/round.rs
crates/polars-time/src/truncate.rs
crates/polars-time/src/utils.rs
crates/polars-time/src/windows/duration.rs
crates/polars-time/src/windows/window.rs
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/functions/as_datatype/test_as_datatype.py
py-polars/tests/unit/namespaces/test_strptime.py

Ahead of addressing #12149 
Currently `"raise"` is often allocated within a loop - it should be cheaper to just pass `Ambiguous::Raise`, right? At least from [this test](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=dba8520f3633806d2a309dae5d72ef51) I'm seeing a nearly 4x improvement

refactor(rust): use enum for Ambiguous

---

docs/src/python/user-guide/transformations/time-series/rolling.py
py-polars/docs/source/reference/expressions/temporal.rst
py-polars/docs/source/reference/series/temporal.rst
py-polars/polars/expr/datetime.py
py-polars/polars/series/datetime.py
py-polars/src/expr/datetime.rs
py-polars/tests/parametric/test_series.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/functions/as_datatype/test_duration.py
py-polars/tests/unit/namespaces/test_datetime.py
py-polars/tests/unit/test_queries.py

closes #6445 
as mentioned in the issue, `.seconds` looks like `.seconds` from pandas / Python stdlib, but it actually equivalent to `.total_seconds`

depr(python,rust!): Rename `dt.seconds` to `dt.total_seconds` (likewise for days, hours, minutes, milliseconds, microseconds, and nanoseconds)

---

crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
py-polars/tests/unit/io/test_lazy_csv.py

This fixes #12186.
This is the simplest fix, but it will affect the optimization of predicates unrelated to `row_count`. A more complex approach might be that we allow the optimization here, but re-evaluate all predicates(or identify predicates containing only `row_count`, but this may be more complicated) after all chunks have been accumulated. I haven't thought carefully about whether the latter option is completely feasible, but the current solution is at least feasible. So it's up to you.

fix: with_row_count should block predicate push down for lazy csv

---

.github/workflows/release-python.yml

Closes #12180
Tested this on my fork, the wheel builds fine using `manylinux_2_28` 👌 thanks for investigating @orlp !

build(python): Build Python wheels on `manylinux_2_28`

---

crates/polars-core/src/frame/group_by/hashing.rs
crates/polars-core/src/hashing/partition.rs
crates/polars-core/src/utils/mod.rs
crates/polars-ops/src/frame/join/asof/groups.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_inner.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_left.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_outer.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_semi_anti.rs
crates/polars-utils/src/functions.rs

This should improve performance for machines with a number of cores that isn't divisible exactly by a power of two for partitioned operations. E.g. if you have a 14-core machine a partitioned join can now use 14 cores instead of only 8.
There is a small bit overhead because it uses two multiplications (one of which is kind of necessary to fix some bad hashing we have in places for the moment anyway) instead of a binary AND, but I did not find that to be meaningful.

perf: allow non-power-of-two partitions

---

py-polars/polars/utils/udfs.py

closes https://github.com/MarcoGorelli/polars-business/issues/23
With this fix, it works on Windows:
```python
(base) C:\Users\User>python
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:30:19) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import polars
>>> polars.__file__
'C:\\Users\\User\\mambaforge\\lib\\site-packages\\polars\\__init__.py'
>>> import os
>>> os.listdir('C:\\Users\\User\\mambaforge\\lib\\site-packages\\polars_business')
['polars_business.cp310-win_amd64.pyd', 'py.typed', 'ranges.py', '__init__.py', '__pycache__']
>>> from datetime import date
>>> import polars_business as plb
>>>
>>> print(plb.date_range(date(2023, 1, 1), date(2023, 1, 10), eager=True))
shape: (7,)
Series: 'date' [date]
[ …
```

fix(python): fix plugins system on Windows

---

py-polars/polars/expr/expr.py
py-polars/polars/expr/name.py

Adds some versioned deprecation notices to the docs (with a link to the new location) and fixes some "see also" links.

docs(python): add deprecation notices to the docs for expressions moved into the new `name` namespace

---

py-polars/polars/dataframe/frame.py

I suspect that `_significantly_` is a typo and should be used with asterisks for emphasis, like `*significantly*`.

docs(python): Fix emphasis formatting in docstring

---

crates/polars-core/src/frame/group_by/perfect.rs
crates/polars-core/src/hashing/partition.rs
crates/polars-utils/src/functions.rs
py-polars/tests/unit/dataframe/test_df.py

This ensures we improve `as_u64` to not return an identity, but always spread the values by doing a wrapping multiply. 
This elides that multiply in hash values that are already properly randomized.

perf: remove extra multiplication in hash_to_partition

---

py-polars/tests/unit/io/test_lazy_csv.py

Closes https://github.com/pola-rs/polars/issues/9887
@jonashaag if I understand correctly, the bug in the linked issue was fixed, but you want to add a test to make sure behavior stays correct.
I'm not sure this test will do it, as the bug apparently pops up in very specific circumstances. But it's better than nothing. Maybe in the future we will run the test suite on various platforms before releasing the wheel, then this test will be valuable.

test(python): Add test for `scan_csv` plus `slice`

---

crates/polars-core/src/chunked_array/ops/set.rs
py-polars/polars/series/series.py
py-polars/tests/unit/series/test_series.py

Closes #10233 
When applying a `numpy` ufunc to a series, the resulting series would get its validity mask from only the first series in the argument list. If there were multiple series arguments, then the null values in those other series would all be treated like zeros.
This PR makes sure that output will be null anywhere one of the inputs is null, not just where the first one is. Sometimes ufuncs will treat nulls like the equivalent polars functions, like how both `numpy.add` and series addition propagate null values. However, that's not the case for the function in the linked issue, where `numpy.maximum` propagates null values but `pl.max_horizontal` ignores them. At least `numpy.maximum` won't depend on the argument order anymore.
In the course of fixing this bug, I also added …

fix(rust,python): Consistently propagate nulls for `numpy` ufuncs

---

py-polars/polars/expr/string.py

As per our discussion in #12161, this PR changes `.select` to `.with_columns` in the docstrings to have a side-by-side output. The changes here go beyond the four functions in #12161 and indeed the side-by-side output mostly makes the examples easier to read IMO. However, the examples where whitespace is stripped look kinda funky. Any opinions on what we should do here? Leave as is, keep the `.select` version (looks less funky), or try to change the examples to avoid `\n` and `\t`?
cc @MarcoGorelli

docs(python): use `.with_columns` in docstrings

---

docs/_build/API_REFERENCE_LINKS.yml

The document lacks feature flag `list.eval` for [eval (ListNameSpace)](https://pola-rs.github.io/polars/docs/rust/dev/polars/prelude/trait.ListNameSpaceExtension.html#method.eval) in Rust, which also makes the user guide incomplete, for example  https://pola-rs.github.io/polars/user-guide/expressions/lists/#row-wise-computations.

docs(rust): Add feature flag for `list.eval`

---

py-polars/polars/io/spreadsheet/functions.py
py-polars/tests/unit/io/test_spreadsheet.py

Closes #11995.
Minor fix to ensure that when we load multiple frames from `read_excel` we return them in the _user's_ specified order, not in the underlying _workbook_ order.
**Before** _(workbook order)_
```python
pl.read_excel( workbook, sheet_names=["sheet2","sheet1"] )
```
**After** _(user-specified order)_
```python
pl.read_excel( workbook, sheet_names=["sheet2","sheet1"] )
```

fix(python): return frames from `read_excel` in the originally specified order

---

.github/workflows/test-python.yml
.gitignore
Cargo.lock
Cargo.toml
crates/polars-core/Cargo.toml
py-polars/.gitignore
py-polars/Cargo.toml
py-polars/build.rs

This adds the `py-polars` crate to the workspace as a non-default member. Benefits:
* Integrates everything in the workspace. Can run everything from the workspace root (clippy / build / ...). This will help simplify the CI in the future (for now, everything keeps working as before).
* Removes duplication between dependency versions in workspace / py-polars manifest
* Only a single `target` folder in the workspace - saves a whole bunch of space on my device and saves re-compiling things.
The `Cargo.lock` is now in the repo root, as well as the `profile` definitions. These will still be picked up by `maturin` and included in the `sdist`.
For some context, the official recommendation for Rust projects is now to check in the lockfile, even for libraries: …

chore(python): Add `py-polars` to Cargo workspace

---

crates/polars-arrow/src/io/avro/write/schema.rs
crates/polars-io/src/avro/write.rs
py-polars/polars/dataframe/frame.py
py-polars/src/dataframe.rs
py-polars/tests/unit/io/test_avro.py
py-polars/tests/unit/series/test_series.py

Attempts to resolve #9446 
I've not used AVRO but apparently an empty schema name can cause issues with data ingestion downstream.
https://github.com/pola-rs/polars/blob/99472416b4b330768b72ed0fee792720434a5f7a/crates/polars-arrow/src/io/avro/write/schema.rs#L18
```python
import io
f = io.BytesIO()
pl.DataFrame({"foo":[]}).write_avro(f)
f.seek(0)
f.read()[:60]
^^
```
With this patch:
```python
f = io.BytesIO()
pl.DataFrame({"foo":[]}).write_avro(f, name="my name")
f.seek(0)
f.read()[:60]
^^^^^^^^^
```
The original issue just got a bump, so some additional discussion may be required.

feat(rust,python): Add `name=` in `.write_avro` to set schema name

---

py-polars/polars/selectors.py

We should be very explicit that it does not select based on whether the data contains anything.

docs(python): clarify contains selector

---

.github/workflows/test-python.yml

We can use `maturin develop` rather than `maturin build` on Windows - this allows simplifying the workflow.
The async tests don't run on Windows - we should look into that.
The doctest / import tests are skipped, as it's not really necessary to test on Windows, and this saves some time on what is currently the slowest workflow out of the three.
_Workflows ran exceptionally slow here, probably due to the cache missing. If we Windows test remains slower with `maturin develop`, we can revert._

ci(python): Clean up Python test workflow

---

docs/development/contributing/ide.md

Setting this is no longer required with `py-polars` part of the workspace.

docs: Remove recommended setting from IDE docs

---

crates/polars-time/src/chunkedarray/rolling_window/rolling_kernels/no_nulls.rs
crates/polars-time/src/windows/group_by.rs
crates/polars-time/src/windows/test.rs

Noticed this while addressing https://github.com/pola-rs/polars/issues/12218 - `add(&period, lower, tz.as_ref()).unwrap()` may indeed error

chore(rust): remove unwrap from group_by

---

crates/polars-plan/src/logical_plan/aexpr/schema.rs
py-polars/tests/unit/test_exprs.py
py-polars/tests/unit/test_schema.py

Fixes https://github.com/pola-rs/polars/issues/12227.
There was a match block that unconditionally gave priority to the non-literal side for the case when one side was a literal and the other was not, which became incorrect when the type of the `Literal` was the super type.
This fix adds an additional check to make it so that the type of the `Literal` is ignored only when both sides are integer types.

fix: incorrect super type for literals in nested binary exprs

---

py-polars/polars/datatypes/classes.py
py-polars/src/conversion.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/datatypes/test_decimal.py
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/test_constructors.py

Having `precision` as the second argument is inconsistent with our own code on the Rust side, as well as with literally every other API I could find (Arrow / SQL / ...). So I'm doing the same trick as with `Array` to switch the arguments.
Setting a default value of 0 for `scale` also follows Arrow / SQL defaults.

depr(python): Switch args for `Decimal` and set default `scale=0`

---

crates/polars-lazy/src/physical_plan/expressions/ternary.rs
py-polars/tests/unit/operations/test_group_by.py

Was flagged as experimental. Behavior remains the same, but we don't throw a warning anymore.

feat: allow non-aggregation predicate in ternary groupby

---

.gitignore

Almost accidentally committed 26,000 files from my `.venv_312` dir just now... 
Let's not let that one happen 🤣

chore: ensure we git-ignore ALL `.venv` dirs

---

.github/workflows/lint-rust.yml
Makefile
crates/polars-arrow/src/io/ipc/read/common.rs
crates/polars-core/src/datatypes/any_value.rs
crates/polars-lazy/src/tests/queries.rs
crates/polars-ops/src/chunked_array/gather_skip_nulls.rs
crates/polars-ops/src/chunked_array/strings/concat.rs
crates/polars-ops/src/frame/join/asof/default.rs
crates/polars-parquet/src/parquet/encoding/delta_length_byte_array/mod.rs
crates/polars-parquet/src/parquet/encoding/hybrid_rle/decoder.rs

Tests were ignored by `clippy` and there were a few warnings there. I fixed those and enabled linting for all targets.

chore(rust): Run `clippy` on all targets

---

Cargo.lock
crates/polars-arrow/Cargo.toml

The original `avro-rs` is no longer being maintained:
https://github.com/flavray/avro-rs
It is now maintained as `apache-avro`:
https://crates.io/crates/apache-avro
This updates the dependency, and fixes the associated `clippy` warning.

chore(rust): Replace dev dependency `avro-rs` with `apache-avro`

---

crates/polars-time/src/windows/group_by.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/polars/lazyframe/frame.py
py-polars/tests/unit/operations/rolling/test_rolling.py

fix(python, rust): don't move right endpoint of windows in rolling in default `offset==-period` case

---

crates/polars-core/src/chunked_array/cast.rs
crates/polars-core/src/datatypes/any_value.rs
crates/polars-core/src/datatypes/dtype.rs
crates/polars-core/src/series/any_value.rs
crates/polars-core/src/utils/supertype.rs
crates/polars-ops/src/chunked_array/list/namespace.rs
crates/polars-ops/src/series/ops/index.rs
crates/polars-plan/src/dsl/function_expr/schema.rs
crates/polars-plan/src/dsl/function_expr/shrink_type.rs

`is_signed` and `is_unsigned` were for checking signed/unsigned integer types. The name is actually a misnomer as floats and decimals are also signed, but they weren't included.
This renames:
* `is_signed` -> `is_signed_integer`
* `is_unsigned` -> `is_unsigned_integer`
This renames the functions in line with https://github.com/pola-rs/polars/pull/12200

feat(rust!): Rename `is_signed` to `is_signed_integer`

---

crates/polars-io/src/cloud/options.rs
py-polars/tests/unit/io/test_lazy_parquet.py

path resolution incorrectly went up by 1 directory. E.g. if `PWD=/home/user/polars/` and the relative path `x/data.parquet` is used, then it would resolve to `/home/user/x/data.parquet` instead of `/home/user/polars/x/data.parquet`

fix: object store path derivation for local URL

---

crates/polars-plan/src/logical_plan/aexpr/mod.rs
crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/join.rs
crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/utils.rs
py-polars/tests/unit/io/test_lazy_parquet.py
py-polars/tests/unit/test_predicates.py

Resolves https://github.com/pola-rs/polars/issues/12116, this mainly does some refactoring around the utility functions in predicate pushdown.
Consolidates the following 3 functions into a single function `aexpr_blocks_predicate_pushdown`:
* `predicate_is_pushdown_boundary`
* `projection_is_definite_pushdown_boundary`
* `partition_by_full_context`
The new function is only called from 2 places:
* Under `push_down::match::Selection`, which checks all predicate exprs and blocks pushdown appropriately if needed
* Under `pushdown_and_continue`, which checks all projection exprs and blocks pushdown appropriately if needed
Otherwise, any previous usage of the 3 removed functions are replaced by an assertion `assert_aexpr_allows_predicate_pushdown`, since boundary exprs are not expected outside …

refactor: simplify expr checking in predicate push down

---

.github/scripts/test_bytecode_parser.py
.github/workflows/test-bytecode-parser.yml
py-polars/tests/test_udfs.py
py-polars/tests/unit/operations/map/test_inefficient_map_warning.py

* The code defining all test cases is moved to the test module in the test suite.
* The script for testing the bytecode without Polars installed is moved closer to the CI, as it's only purpose is to easily test on multiple Python versions.
Reason for this change is that we want to avoid doing relative imports when running the pytest suite. In fact, this fails when running on Python 3.12. I took it a step further and moved the testing script into the CI folder.

ci(python): Move script for testing map warning

---

crates/polars-io/src/parquet/async_impl.rs
py-polars/tests/unit/io/test_lazy_parquet.py

fixes #12297 
Also improves performance as we accidentally downloaded more than we needed.

fix: fix download ranges in parquet

---

py-polars/polars/functions/range/date_range.py

Closes #12303.
The "s" in "saturating" was triggering an invalid `DeprecationWarning` ;)

fix(python): Fix invalid DeprecationWarning generated from `date_range` defined with 'saturating' interval

---

crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs
crates/polars-pipe/src/executors/sources/parquet.rs
crates/polars-plan/src/logical_plan/optimizer/predicate_pushdown/mod.rs
crates/polars-plan/src/logical_plan/schema.rs
py-polars/tests/unit/io/test_hive.py

`update_hive...` always set the hive partitions irregardless of user settings.

fix: respect hive_partitioning flag when dealing with multiple files

---

crates/polars-core/src/chunked_array/ops/zip.rs
py-polars/tests/unit/functions/test_whenthen.py

Per discuss in discord, and It seems that all test can be passed.

fix: zip_with also broadcast mask

---

crates/polars-io/src/csv/read_impl/mod.rs
py-polars/tests/unit/io/test_lazy_csv.py

I tested it and found that not only `parquet`, but `scan_csv` also has the same problem, so give it a fix.

fix: scan emtpy csv miss row_count

---

crates/polars-lazy/src/physical_plan/expressions/literal.rs
crates/polars-plan/src/dsl/consts.rs
crates/polars-plan/src/utils.rs
py-polars/tests/unit/namespaces/test_meta.py
py-polars/tests/unit/operations/rolling/test_rolling.py

This fix the bug posted in comment(https://github.com/pola-rs/polars/issues/12326#issuecomment-1803146105). Also fixes the original issue #12326.

fix: expr_output_name include literal

---

py-polars/pyproject.toml

Ref: #12314.
Closing in on the last two `BytecodeParser` test failures - had to add this "filterwarnings" entry in order to debug tests under py3.12, as PyCharm introspection would trigger a _"co_lnotab is deprecated, use co_lines instead"_ `DeprecationWarning`.

fix(python): ignore IDE-mediated DeprecationWarning when debugging tests under 3.12

---

py-polars/src/conversion.rs
py-polars/tests/unit/dataframe/test_df.py

This fixes #12329.
I'm not sure if this is the best fix, but it seems that we extract a integer large than `i64` to `f64` instead of `u64`.

fix: uint64 should be correctly extracted from python object

---

crates/polars-io/src/csv/mod.rs
crates/polars-io/src/csv/write.rs
crates/polars-pipe/src/executors/sinks/file_sink.rs
crates/polars-plan/src/logical_plan/options.rs
crates/polars/src/docs/eager.rs
crates/polars/tests/it/io/csv.rs
docs/src/rust/user-guide/basics/reading-writing.rs
py-polars/polars/dataframe/frame.py
py-polars/polars/io/csv/functions.py
py-polars/polars/io/spreadsheet/_write_utils.py
py-polars/polars/lazyframe/frame.py
py-polars/src/dataframe.rs
py-polars/src/lazyframe.rs
py-polars/tests/unit/io/test_spreadsheet.py
py-polars/tests/unit/streaming/test_streaming_io.py

This PR is a follow up on #12253
As a result of the discussion in the PR, `has_header` is renamed to `include_header`, because include sounds more suitable for writing side.

depr(rust!,python): Rename `write_csv` parameter `has_header` to `include_header`

---

.github/workflows/lint-python.yml

Turns out `ruff check --diff` will exit 0 if there are errors but Ruff cannot autofix them. This is undesirable. Passing `--no-fix` will exit non-zero if there are any lint failures.

ci(python): Fix ruff linting invocation

---

crates/polars-ops/src/frame/join/asof/groups.rs
crates/polars-ops/src/frame/join/hash_join/single_keys.rs
crates/polars-ops/src/frame/join/hash_join/single_keys_inner.rs
crates/polars-utils/src/idx_vec.rs
crates/polars-utils/src/lib.rs

We can probably use the `IdxVec` in more places, but first a small PR.
```python
0.19.2
cardinality n:n
3.281125207999139
cardinality n:1
1.9747477909986628
main
cardinality n:n
2.5034849580115406
cardinality n:1
1.27836137500708
idx_vec
cardinality n:n
1.7044463330239523
cardinality n:1
0.7827337920025457
```
With this small micro-benchmark:
```python
n = 1_000_000
ids1 = np.arange(n)
ids2 = np.arange(n)
np.random.shuffle(ids1)
np.random.shuffle(ids2)
ids3 = np.random.randint(100, size=n)
ids4 = np.zeros(n, dtype=int)
df1 = pl.DataFrame({"x": ids1, "f": np.random.random(len(ids1))})
df2 = pl.DataFrame({"x": ids2, "g": np.random.random(len(ids2))})
df3 = pl.DataFrame({"x": ids3, "i": np.random.random(len(ids3))})
df4 = …
```

perf: reduce allocations in hash join

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

docs(python): Fix incorrect boundary column name in `group_by_dynamic` docstrings

---

Cargo.lock
Cargo.toml
py-polars/pyproject.toml

See https://github.com/PyO3/maturin/issues/1844
This is a workaround for an issue with maturin which causes the Polars sdist to be broken (not installable by pip).
Actually I want to remove the examples directory anyway, and merge the examples with the docs, so the workaround doesn't hurt too badly.
I will follow up on this when the maturin issue has been addressed.

build(python): Workaround for maturin issue

---

py-polars/polars/utils/udfs.py
py-polars/tests/unit/operations/map/test_inefficient_map_warning.py

Ref: #12094.
Account for bytecode changes in py3.12. 
~~(Only two unit tests left to fix; both connected to establishing the correct nesting level of expressions connected with `&` and `|` ops)~~
---
**Update**: Done!
Much-improved (and streamlined) logic for reconstructing expression nesting levels...

feat(python): updated `BytecodeParser` for Python 3.12

---

crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs

This fixes #12340.
I'm not introduce the support of casting `Utf8` `AnyValue` to other dtypes in this PR(perhaps we can consider it in future PR). Our release build has a fallback mechanism here, so it will not cause any problems indeed. But I think our goal should be to gradually remove the fallback, so this may be one of the steps.

fix: Do not cast lit if has same dtype

---

py-polars/polars/dataframe/frame.py
py-polars/polars/dataframe/group_by.py
py-polars/polars/dependencies.py
py-polars/polars/expr/expr.py
py-polars/polars/io/iceberg.py
py-polars/polars/lazyframe/frame.py
py-polars/polars/series/series.py
py-polars/polars/utils/_construction.py

Clarifying an example as per Discord question
Drive-by: more bullet points not rendering have crept in 😉 
Example:
**before**
**after**
----
another drive-by: italics in sphinx should be `*word*`, not `_word_` (yeah, I made this mistake too 😳 )

docs(python): use with_columns in is_in example, and fix some bullet points not rendering

---

.github/workflows/release-python.yml

Recently we had to ditch manylinux2014 because of an issue with one of our dependencies:
https://github.com/pola-rs/polars/pull/12211
Maturin offers three options: 2014 (oldest version), 2.24, and 2.28:
https://github.com/PyO3/maturin-action#manylinux-docker-container
We switched to manylinux 2.28, but 2.24 also seems to work. After a complaint from a user about compatibility issues with 2.28 (their gclib version was 2.26), I tested if 2.24 also works and it does. So let's use that instead.
I have also updated the 0.19.13 PyPI release to include the 2.24 wheels.

build(python): Use manylinux 2.24 instead of 2.28 for compatibility reasons

---

docs/user-guide/expressions/aggregation.md
docs/user-guide/installation.md

I been reading through the docs to get started with polars (absolutely loving it btw) and notice there are some formatting issues with bullet points. With mkdocs nested bullet points need two tabs additional to be rendered properly, I've fixed this in the installation.md and aggregation.md files
Also note that I put in some ignore flags for the dprint linter around the bullet points. I couldn't find any finer-grained configuration options.

fix(docs): Correct nested bullet point format for mkdocs

---

crates/polars-core/src/chunked_array/mod.rs
crates/polars-core/src/chunked_array/ops/chunkops.rs
crates/polars-core/src/chunked_array/ops/explode.rs
crates/polars-core/src/chunked_array/ops/zip.rs
crates/polars-lazy/src/physical_plan/expressions/ternary.rs
crates/polars-lazy/src/tests/optimization_checks.rs
crates/polars-plan/src/logical_plan/optimizer/simplify_expr.rs
py-polars/tests/unit/functions/test_whenthen.py

This PR would revert when-then broadcasting behavior introduced by https://github.com/pola-rs/polars/pull/12357. to the previous behavior:
- For any of the 3 `mask`, `truthy` and `falsy` that are of length-1, will be broadcasted to the max length of the 3. If there is more than 1 unique length > 1, then instead there will be a `ShapeMismatch` error.
Supersedes https://github.com/pola-rs/polars/pull/12381
Would re-open https://github.com/pola-rs/polars/issues/12354

fix: revert ternary special broadcast, ensure broadcast is always to max height

---

.github/workflows/release-python.yml

Closes #12390
Lesson learned: take backwards compatibility seriously, even for 8+ year old systems.
PyPI release for Polars 0.19.13 has been updated.

build(python): Use `manylinux_2_17` for building `x86-64` wheel

---

docs/user-guide/installation.md
dprint.json

Just bumping the markdown linter (hoped the nested bullet points would be fixed in a newer version, but alas no such luck).
Also removed some unnecessary pragma comments for MLC as the config file takes care of this.

chore: dprint/markdown link checker minor updates

---

Cargo.lock
crates/polars-arrow/Cargo.toml
crates/polars-arrow/src/legacy/kernels/rolling/no_nulls/quantile.rs
crates/polars-arrow/src/legacy/kernels/rolling/nulls/mod.rs
crates/polars-arrow/src/legacy/kernels/rolling/nulls/quantile.rs

factoring out some more "chore"-like bits from https://github.com/pola-rs/polars/pull/11750

chore(rust): use unwrap_or_else and get_unchecked_release in rolling kernels

---

crates/polars-ops/src/chunked_array/cov.rs
crates/polars-plan/src/dsl/function_expr/correlation.rs
crates/polars-plan/src/dsl/functions/correlation.rs
py-polars/polars/functions/lazy.py
py-polars/src/functions/lazy.rs
py-polars/tests/unit/test_lazy.py

Fill in on this promise ;) : https://www.reddit.com/r/Python/comments/17rjedo/comment/k8x0c3d/?utm_source=share&utm_medium=web2x&context=3
This makes us `2x` faster than before and `~35%` faster than numpy.

perf: use online algorithm for cov/corr `~2x`

---

py-polars/polars/dataframe/_html.py

We don't need to over-specify the CSS selectors here; while some environments restyle frame tables (so the issue isn't seen there) others take the raw HTML"as-is" and could see misaligned dtype descriptions (as the dtype sits inside a `td`, not a `th`).
**First:** misaligned dtype.
**Second:** after the fix.

fix(python): raw HTML output alignment was incorrect for dtype in header

---

py-polars/polars/dataframe/frame.py
py-polars/polars/lazyframe/frame.py

Ref #7349
The auto-structify setting is disabled by default, but it does not need to be considered experimental.

docs(python): Remove 'experimental' tag for auto-structify setting

---

Cargo.lock
crates/polars-plan/src/logical_plan/builder.rs
crates/polars-utils/src/io.rs
py-polars/Cargo.toml
py-polars/src/error.rs
py-polars/src/file.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/io/test_other.py
py-polars/tests/unit/test_errors.py

Closes https://github.com/pola-rs/polars/issues/10640
Inspired by @romanovacca 's work in #11976
* All IO functions now use the `open_file` util from polars-utils _(there were 3 competing implementations)_
* Revisit the `open_file` util to raise a Polars IO error rather than a ComputeError.
* Translate Polars IO errors to specific Python IO errors such as `FileNotFoundError`.
* ~Remove truncation of the path to 88 characters. Paths may be long sometimes, but I am definitely interested in the full path if it turns out there is an error.~

fix(python,rust!): Fix `scan_csv` error type

---

py-polars/polars/expr/expr.py
py-polars/tests/unit/test_exprs.py

Closes #12410, partially addresses #11332.
* Significantly streamlined `map_dicts` implementation to avoid a lot of copy/paste and make it a little easier to reason about.
* Fixed issue where an explicitly-provided "result_dtype" value was not being passed through to the underlying `map_batches` expression, and added some coverage.
Note: only partially addresses #11332 as we should probably be able to do better with inference in the absence of an explicit "result_dtype", such that the `fill_null` succeeds (it currently fails as the expression dtype is considered "Unknown" and it is looking for numeric columns to fill, ref: #7700).

fix(python): ensure explicit "return_dtype" is respected by `map_dicts`

---

py-polars/polars/series/series.py
py-polars/tests/unit/series/test_series.py

Ref #12196
Check the Series dtype instead using the equality operator, e.g. `s.dtype == pl.Boolean`.

depr(python): Deprecate Series methods `is_boolean` and `is_utf8`

---

crates/polars-io/src/csv/read_impl/mod.rs
crates/polars-io/src/lib.rs
crates/polars-io/src/parquet/read.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-io/src/predicates.rs
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs
crates/polars-lazy/src/physical_plan/expressions/mod.rs
crates/polars-lazy/src/physical_plan/streaming/construct_pipeline.rs
crates/polars-pipe/src/executors/sinks/group_by/aggregates/convert.rs
crates/polars-pipe/src/executors/sources/parquet.rs
crates/polars-pipe/src/expressions.rs
crates/polars-pipe/src/pipeline/convert.rs
py-polars/tests/unit/io/test_lazy_parquet.py

It turned out we didn't push the predicates all the way in the readers for streaming queries. Meaning that we still loaded, and worse, downloaded files we don't need.
closes #12419

perf: apply predicates and statistics of parquet files in streaming mode

---

py-polars/polars/datatypes/classes.py
py-polars/polars/utils/_construction.py
py-polars/tests/unit/datatypes/test_duration.py
py-polars/tests/unit/datatypes/test_struct.py

This method does not offer anything that `DataType.is_` does not already offer us. We don't offer `is_not_integer`, `is_not_nested` etc. either, so I think we're better off without this method. It's not like this is used so commonly that the method is a must-have.
@alexander-beedie I think you introduced this one - what are your thoughts on this?

depr(python): Deprecate DataType method `is_not`

---

Cargo.lock
crates/polars-io/Cargo.toml
crates/polars-io/src/partition.rs

`tempdir` is archived:
https://github.com/rust-lang-deprecated/tempdir
Its dependencies contain a security vulnerability:
https://github.com/pola-rs/polars/security/dependabot/29
So we replace it by `tempfile`, as recommended by the original package authors:
https://docs.rs/tempfile/latest/tempfile/fn.tempdir.html

chore(rust): Replace outdated dev dependency `tempdir`

---

crates/polars-plan/src/dsl/function_expr/range/date_range.rs
crates/polars-plan/src/dsl/function_expr/range/datetime_range.rs
crates/polars-plan/src/dsl/function_expr/range/time_range.rs
crates/polars-plan/src/dsl/function_expr/range/utils.rs
py-polars/tests/unit/functions/range/test_date_range.py

fix: Do not panic if time is invalid

---

py-polars/polars/expr/list.py

Not sure if I need to make an issue for this first:
I noticed `.select()` was used when checking the docs for `.list.join` so I thought I'd update all the examples.
A couple of other changes:
- replaced all `.alias()` calls with named expressions
- a few examples used `pl.Series` so I changed them to `pl.DataFrame`
- `.list.take()` had no example, so I added one
- I added some `max_width` examples/notes to `.list.to_struct()`

docs(python): Use `.with_columns()` in all `.list` namespace examples

---

py-polars/tests/unit/test_polars_import.py

Ref: https://github.com/pola-rs/polars/pull/12094#issuecomment-1809238204.
Improves the test in several ways:
* Adds an up-front `.py` → `.pyc` step (fast, only runs once).
* Factors-out (and fixes!) the "cumulative_time" sort that chooses the fastest run.
* Early-exits from the test as soon as an import run meets the max allowed time.
Should be much more reliable now.
(Fastest time I saw while testing was ~0.059 secs, so initial import remains _extremely_ fast).

test(python): improved `import polars` timing test; now much more consistent/reliable

---

crates/polars-time/src/windows/duration.rs
py-polars/tests/unit/functions/range/test_date_range.py

fix: dont overflow when calculating date range over very long periods

---

py-polars/polars/series/series.py
py-polars/src/series/mod.rs
py-polars/tests/unit/datatypes/test_list.py

This property doesn't make much sense. Just use `Series.dtype` and call `.inner` on it if you know it's a List/Array.

depr(python): Deprecate `Series.inner_dtype` property

---

.github/workflows/benchmark.yml
.github/workflows/docs-global.yml
.github/workflows/docs-python.yml
.github/workflows/lint-python.yml
.github/workflows/test-bytecode-parser.yml
.github/workflows/test-python.yml
docs/development/contributing/index.md
py-polars/polars/dataframe/frame.py
py-polars/polars/functions/as_datatype.py
py-polars/polars/lazyframe/frame.py
py-polars/pyproject.toml
py-polars/requirements-dev.txt
py-polars/tests/docs/run_doctest.py
py-polars/tests/unit/io/test_database_read.py
py-polars/tests/unit/io/test_database_write.py
py-polars/tests/unit/test_polars_import.py

Closes [#11348](https://github.com/pola-rs/polars/issues/11348)
* Update Python version in the CI.

build(python): Support Python 3.12

---

docs/user-guide/expressions/plugins.md
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/expr.py
py-polars/polars/series/series.py

As per discussion on discord @MarcoGorelli, adding a note on the instability of `hash` across versions and mentioning they can use polars-hash if they require stability.

docs(python): Add note on hash stability and mention `polars-hash`

---

py-polars/polars/expr/expr.py

Keep mention in the docs, but keep docstrings about native polars implementation.

docs(python): Update `polars-hash` reference

---

py-polars/polars/series/series.py
py-polars/tests/unit/series/test_series.py

Closes #12481.
We were missing a dedicated Duration/timedelta path inside Series `_comp`; fixed, and added some coverage.

fix(python): Ensure behaviour  of`Series` comparison with `timedelta` matches that of other types

---

crates/polars-core/src/chunked_array/builder/list/categorical.rs
crates/polars-core/src/chunked_array/logical/categorical/builder.rs
crates/polars-core/src/chunked_array/logical/categorical/from.rs
crates/polars-core/src/chunked_array/logical/categorical/merge.rs
crates/polars-core/src/chunked_array/logical/categorical/mod.rs
crates/polars-core/src/chunked_array/logical/categorical/ops/unique.rs
crates/polars-core/src/chunked_array/ops/compare_inner.rs
crates/polars-core/src/datatypes/any_value.rs
crates/polars-core/src/datatypes/dtype.rs
crates/polars-core/src/frame/group_by/perfect.rs
crates/polars-core/src/frame/row/transpose.rs
crates/polars-core/src/series/any_value.rs
crates/polars-core/src/series/mod.rs
py-polars/tests/unit/operations/test_transpose.py
py-polars/tests/unit/test_errors.py

fix #12502 
In the past we would only allow comparisons between two categoricals if the pointers are equal
This adds a hash to the local categorical, if two categories have the same hash we allow comparison. 
Note that this does not support comparison of arbritrary local categoricals as both have to have the same categories in the same order.

feat(rust): Allow comparison of two local categories with the same hash

---

crates/polars-pipe/src/executors/sinks/joins/cross.rs
crates/polars-pipe/src/executors/sinks/sort/sink_multiple.rs
crates/polars-pipe/src/operators/chunks.rs
py-polars/tests/unit/streaming/test_streaming_join.py

fix: rechunk cross join output in streaming

---

py-polars/tests/unit/test_consortium_standard.py

It's quite likely that the dataframe api will have a `Scalar` class, and that `Column.get_value` will return that
I'm suggesting to just simplify the test to make an assertion about `Column.name`, which realistically isn't going to change
---
corresponding pandas PR: https://github.com/pandas-dev/pandas/pull/55993

test(python): Future-proof consortium standard test

---

crates/polars-arrow/src/compute/aggregate/memory.rs
py-polars/tests/unit/datatypes/test_decimal.py

fixes #12375
When adding the test, I was reading the result back but the precision changes, so I took it out.
```python
>>> df.lazy()
<LazyFrame [2 cols, {"hi": Boolean, "bye": Decimal(precision=None, scale=0)}] at 0x120FF7590>
>>> pl.scan_parquet("decimal_test.parquet")
<LazyFrame [2 cols, {"hi": Boolean, "bye": Decimal(precision=38, scale=0)}] at 0x134B4EB90>
```
I've not used decimals so I'm not sure if this is expected behaviour or not.

fix: fix panic when writing `Decimal` type to parquet

---

crates/polars-io/src/lib.rs

fix: saturating sub in debug msg

---

crates/polars-core/src/frame/mod.rs
crates/polars-ops/src/series/ops/horizontal.rs
py-polars/docs/source/reference/dataframe/aggregation.rst
py-polars/polars/dataframe/frame.py
py-polars/src/dataframe.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/operations/test_aggregations.py
py-polars/tests/unit/operations/test_arithmetic.py
py-polars/tests/unit/test_exprs.py

Closes https://github.com/pola-rs/polars/issues/12484
- Add the following `DataFrame` methods:
- `sum_horizontal`
- `mean_horizontal`
- `max_horizontal`
- `min_horizontal`
- On the Rust side, rename `hsum/hmean/hmax/hmin` to the names above.
- On the Python side, deprecate the horizontal component of the overloaded `sum/mean/max/min` methods.
There is more cleanup to be done around these methods (e.g. add LazyFrame methods, proper dispatching), but at least this takes care of the deprecation and public API.

feat(python,rust!): Add dedicated horizontal aggregation methods to `DataFrame`

---

crates/polars-core/src/chunked_array/ops/explode_and_offsets.rs
crates/polars-core/src/chunked_array/ops/mod.rs
crates/polars-core/src/chunked_array/ops/zip.rs
crates/polars-lazy/src/physical_plan/expressions/aggregation.rs
crates/polars-lazy/src/physical_plan/expressions/alias.rs
crates/polars-lazy/src/physical_plan/expressions/apply.rs
crates/polars-lazy/src/physical_plan/expressions/binary.rs
crates/polars-lazy/src/physical_plan/expressions/cast.rs
crates/polars-lazy/src/physical_plan/expressions/column.rs
crates/polars-lazy/src/physical_plan/expressions/count.rs
crates/polars-lazy/src/physical_plan/expressions/filter.rs
crates/polars-lazy/src/physical_plan/expressions/literal.rs
crates/polars-lazy/src/physical_plan/expressions/mod.rs
crates/polars-lazy/src/physical_plan/expressions/rolling.rs
crates/polars-lazy/src/physical_plan/expressions/slice.rs
crates/polars-lazy/src/physical_plan/expressions/sort.rs
crates/polars-lazy/src/physical_plan/expressions/sortby.rs
crates/polars-lazy/src/physical_plan/expressions/take.rs
crates/polars-lazy/src/physical_plan/expressions/ternary.rs
crates/polars-lazy/src/physical_plan/expressions/window.rs
crates/polars/tests/it/lazy/expressions/arity.rs
py-polars/tests/unit/functions/test_whenthen.py

Fixes https://github.com/pola-rs/polars/issues/12242, https://github.com/pola-rs/polars/issues/12382, https://github.com/pola-rs/polars/issues/12526.
Execution is now done w.r.t the agg states of the predicate, truthy and falsy - it previously only looked at the agg states of the truthy and falsy, and for the predicate relied on `is_valid_aggregation`, which didn't capture / didn't make sense for some edge cases (a separate interesting issue is that `is_in` isn't setting `auto_explode` properly).
The `expand_lengths` function is moved to `zip.rs` as a macro. It was previously always being called before a `zip_with` from `ternary.rs`, but this is now changed to only be called when doing `zip_with` operations on `ListChunked` and `PolarsObject` types as they cannot use …

fix: fix and improve ternary evaluation on groups

---

docs/user-guide/expressions/numpy.md
py-polars/polars/series/series.py
py-polars/tests/unit/interop/test_interop.py
py-polars/tests/unit/interop/test_numpy.py
py-polars/tests/unit/series/test_series.py

As mention in our meeting.
I'm not sure what exactly `view` would be used for, but it seems like it's used as a way to get a NumPy zero copy array, so we can use `to_numpy(zero_copy_only=True)` for that.
For now it's converted to a private method.

depr(python): Deprecate `Series.view`

---

crates/polars-lazy/src/physical_plan/expressions/slice.rs
crates/polars-lazy/src/physical_plan/expressions/ternary.rs
py-polars/tests/unit/functions/test_whenthen.py

follow-up to https://github.com/pola-rs/polars/pull/12529
ran into a few things after activating some of the recently added tests to also run agg contexts 😅
```rust
ternary agg: finish all not-aggregated or unit literal
thread '<unnamed>' panicked at crates/polars-core/src/frame/group_by/aggregations/agg_list.rs:47:29:
assertion failed: (*idx as usize) < values.len()
```
* fix: return correct ternary agg state from `not-aggregated / unit literal` path
* fix: ensure `SliceExpr` sets original len to `false`
* fix: do not run `not-aggregated / unit literal` path if the groups were filtered/sliced
* tests: increase coverage of ternary in agg contexts

fix: fix incorrect ternary agg states

---

crates/polars-core/src/frame/mod.rs
crates/polars-io/src/csv/read_impl/mod.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-pipe/src/executors/sinks/joins/inner_left.rs
crates/polars-plan/src/logical_plan/functions/rename.rs
py-polars/docs/source/reference/dataframe/modify_select.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/io/spreadsheet/_write_utils.py
py-polars/src/dataframe.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/functions/test_functions.py
py-polars/tests/unit/test_constructors.py

* Rename the following `DataFrame` methods:
* `find_idx_by_name` -> `get_column_index`
* `insert_at_idx` -> `insert_column`
* `replace_at_idx` -> `replace_column`
Motivation for this change is that "index" often refers to a _row_ index in the context of a DataFrame. These methods are about column indices.

depr(python,rust!): Rename DataFrame column index methods

---

crates/polars-plan/src/logical_plan/functions/mod.rs
py-polars/tests/unit/streaming/test_streaming.py
py-polars/tests/unit/streaming/test_streaming_cse.py
py-polars/tests/unit/streaming/test_streaming_group_by.py

feat: In explain(), rename PIPELINE to STREAMING so it's clearer what it means

---

py-polars/polars/expr/expr.py
py-polars/polars/utils/_parse_expr_input.py

We should use the `parse_as_expression` util here but there's some more work to be done before we can do that.

refactor(python): Minor cleanup in Expr class

---

crates/polars-plan/src/dsl/function_expr/range/int_range.rs
py-polars/tests/unit/functions/range/test_int_range.py

Ref: https://github.com/ibis-project/ibis/pull/7576#issuecomment-1817150271. 
* Simple fix for incorrect `vec` capacity calculation on `int_ranges` with negative "step" (and/or "end" < "start").
* Also, no need to raise error over "end" < "start" with positive "step"; result should be empty list.
* Additional test coverage for all of the above.

fix(rust,python): address overflow on vec capacity calculation for `int_ranges` with negative step

---

crates/polars-plan/src/logical_plan/builder.rs
crates/polars-plan/src/logical_plan/builder_alp.rs
py-polars/tests/unit/operations/test_group_by.py
py-polars/tests/unit/operations/test_group_by_dynamic.py
py-polars/tests/unit/operations/test_rolling.py

Closes https://github.com/pola-rs/polars/issues/11339
* Fixes the ordering of columns in the schema - aggregation columns should be at the end.
* Properly inserts `_lower_bound` and `_upper_bound` into the schema when `include_boundaries` is specified for `group_by_dynamic` _(Should these columns have better names?_ 🤔 
* Refactor some related tests

fix: Fix lazy schema for `group_by_dynamic` and `rolling`

---

crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/binary/dictionary.rs
crates/polars-parquet/src/arrow/read/deserialize/boolean/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/boolean/nested.rs
crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/dictionary.rs
crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/nested.rs
crates/polars-parquet/src/arrow/read/deserialize/null/nested.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/dictionary.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/nested.rs

https://github.com/pola-rs/polars/pull/11471 converted binary deserialize to iterative, this PR applies the same change for all of the others.

refactor: convert all recursive parquet deserialize to iterative

---

Cargo.lock
Cargo.toml
crates/polars-io/src/parquet/mod.rs
crates/polars-io/src/parquet/read.rs
crates/polars-io/src/parquet/read_impl.rs
crates/polars-lazy/src/physical_plan/executors/scan/ipc.rs
crates/polars-lazy/src/physical_plan/executors/scan/mod.rs
crates/polars-lazy/src/physical_plan/executors/scan/parquet.rs
py-polars/tests/unit/io/test_hive.py

fix: accidental panic if predicate selects no files

---

crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs

Handle a potential case where `extend_offsets2` gets called with an existing `nested` state that is already complete after the previous call returned `Ok(false)` due to not being able to see the next page. This is done by moving the `peek` of the repetition level to the first step after refactoring the loop.
Also does some refactoring to make it more robust:
* in `extend`, use a single loop to remove the duplicated code in the `while` loop, this ensures the return value of `extend_offsets2` is always respected
* correct `wrapping_sub` with (it was supposed to be) `saturating_sub` (what on earth was I doing before 😅😅). This is also only needed to be a `saturating_sub` when calculating `additional` - the below `*remaining -= ..` is restored.

fix: parquet: do not extend existing nested that is already complete

---

Cargo.lock
crates/polars-core/src/chunked_array/logical/struct_/mod.rs
crates/polars-json/src/json/write/mod.rs
crates/polars-json/src/json/write/serialize.rs
crates/polars-json/src/json/write/utf8.rs
crates/polars-plan/Cargo.toml
crates/polars-plan/src/dsl/function_expr/struct_.rs
crates/polars-plan/src/dsl/struct_.rs
py-polars/docs/source/reference/expressions/struct.rst
py-polars/docs/source/reference/series/struct.rst
py-polars/polars/expr/struct.py
py-polars/polars/series/struct.py
py-polars/src/expr/struct.rs
py-polars/tests/unit/namespaces/test_struct.py

closes #12581
closes #8912
closes #11728
closes #10271
The name of the expression is `json_encode`. I want to propose to rename `json_extract` to `json_decode`. @stinodego pinging the chief of deprecations.

feat: struct -> json encoding expression

---

crates/polars-plan/src/dsl/function_expr/rolling.rs
crates/polars-plan/src/dsl/mod.rs
crates/polars-time/src/chunkedarray/rolling_window/mod.rs
py-polars/polars/expr/expr.py
py-polars/src/expr/rolling.rs
py-polars/tests/unit/operations/rolling/test_rolling.py

closes #11225
Even if #11134 were addressed, then the warning would still show, because the sortedness flags don't propagate during `over`

feat: warn if `by` column is not sorted in rolling aggregations (as opposed to raising), add warn_if_unsorted argument

---

crates/polars-core/src/chunked_array/ops/aggregate/mod.rs
crates/polars-ops/src/chunked_array/cov.rs
py-polars/tests/unit/operations/test_statistics.py

The [previous PR](https://github.com/pola-rs/polars/pull/12471) which was reverted did not implement the new algorithm completely correctly. This PR does, with a relative error of ~1.2e-15 compared to numpy for the correlation query found in the H2OAI benchmark. It should be a bit faster still because it does not subtract in a loop either, it computes the sums of `x`, `y`, `x^2`, `y^2` and `xy` per batch and updates the online covariances using these aggregates.

perf: improve cov/corr algorithm

---

crates/polars-parquet/src/arrow/read/deserialize/nested_utils.rs
py-polars/tests/unit/io/test_parquet.py

Fix https://github.com/pola-rs/polars/issues/12610
Issue caused by https://github.com/pola-rs/polars/pull/12569 - it accidentally subtracted twice 😓.

fix: panic reading parquet nested struct column

---

crates/polars-arrow/src/array/dictionary/mutable.rs
crates/polars-arrow/src/compute/cast/mod.rs
crates/polars-io/src/parquet/write.rs
crates/polars-parquet/src/arrow/write/binary/basic.rs
crates/polars-parquet/src/arrow/write/dictionary.rs
crates/polars-parquet/src/arrow/write/mod.rs
crates/polars-parquet/src/arrow/write/pages.rs
crates/polars-parquet/src/parquet/page/mod.rs

…rquet file size)
Parquet files written by polars are much larger than the pyarrow counterparts because they are written mostly wo/ any encoding. This enables RLE_DICTIONARY encoding for utf8 and binary columns and will fallback to PLAIN if the dictionaries get too big or there is a cardinality higher than 75%.
Pyarrow also uses this for integers, I will follow up with that as well.

feat: implement RLE_DICT encoding for utf8/binary columns (reduced parquet file size)

---

crates/polars-plan/src/dsl/function_expr/boolean.rs

Ref https://github.com/pola-rs/polars/pull/10838#issuecomment-1818741317
The expression should be named `not` on the Rust side. In Python, it has to be named `not_` due to naming conflict with language defaults.

fix(rust)!: Rename `not_` expression to `not` on the Rust side

---

py-polars/polars/expr/whenthen.py
py-polars/polars/functions/whenthen.py
py-polars/polars/utils/_parse_expr_input.py
py-polars/tests/unit/functions/test_whenthen.py

Closes #12577.
Coming at you from ~12km altitude and a speed of ~950km/h on some awful (but free) in-flight WiFi... (heading back home after a few days in Madrid ;))
Preserves existing behaviour of `when` (with a suitable `DeprecationWarning`), but now allows for the same convenient/flexible multi-predicate & kwargs syntax that was recently afforded to `filter`, eg:
Using kwargs -
```python
{
"x": [10, 20, 30, 40],
"y": [15, -20, None, 1],
"z": ["a", "b", "c", "d"],
}
)
matched = pl.when( x=40, y=1, z="d" ).then( pl.lit(":)") ).otherwise( pl.lit(":(") )
)
```
Multiple predicates -
```python
matched=pl.when(
pl.col("x") <= 30,
pl.col("y").is_not_null(),
pl.col("z").is_in(["b", "c", "d"]),
)
.then(":)")
.otherwise(":(")
)
```
(And can …

feat(python): extend recent `filter` syntax upgrades to `when/then` construct

---

py-polars/src/series/construction.rs
py-polars/tests/unit/series/test_from_buffer.py

Ref https://github.com/pola-rs/polars/issues/10718
Implements zero-copy foreign buffer for integer and float types.
TODO: Booleans.

feat(python): Implement `PySeries.from_buffer` for numeric types

---

crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/binary/dictionary.rs
crates/polars-parquet/src/arrow/read/deserialize/binary/nested.rs
crates/polars-parquet/src/arrow/read/deserialize/binary/utils.rs

Don't allocate a vec of vec, but inline the bytes in single allocation.

perf: optimize dict binary decoding in parquet

---

py-polars/docs/source/reference/dataframe/miscellaneous.rst
py-polars/docs/source/reference/series/miscellaneous.rst
py-polars/polars/dataframe/frame.py
py-polars/polars/expr/datetime.py
py-polars/polars/series/datetime.py
py-polars/polars/series/series.py
py-polars/src/dataframe.rs
py-polars/src/series/mod.rs
py-polars/tests/unit/dataframe/test_df.py
py-polars/tests/unit/dataframe/test_equals.py
py-polars/tests/unit/datatypes/test_list.py
py-polars/tests/unit/datatypes/test_temporal.py
py-polars/tests/unit/io/test_hive.py
py-polars/tests/unit/namespaces/string/test_string.py
py-polars/tests/unit/namespaces/test_binary.py
py-polars/tests/unit/namespaces/test_list.py
py-polars/tests/unit/operations/test_group_by.py
py-polars/tests/unit/series/test_equals.py
py-polars/tests/unit/series/test_series.py
py-polars/tests/unit/sql/test_sql.py
py-polars/tests/unit/test_empty.py
py-polars/tests/unit/test_lazy.py
py-polars/tests/unit/test_predicates.py

Closes #12000
I left the Rust side alone for now as that basically hits the entire test suite - I want to be sure this is the way to go before I go ahead with that.
`frame_equal` is a weird name as we know we have a DataFrame - we do not prefix all other methods with `frame` either. It should just be `df1.equals(df2)` which is clear and concise. Same for `series_equal`. This also happens to correspond to what `pandas` does.

depr(python): Rename `series_equal`/`frame_equal` to `equals`

---

crates/polars-arrow/src/ffi/mmap.rs
py-polars/polars/interchange/buffer.py
py-polars/src/series/construction.rs
py-polars/tests/unit/series/test_from_buffer.py

Ref #10718
Followup of https://github.com/pola-rs/polars/pull/12646
* Reading in foreign boolean buffers (bitmaps) in `PySeries._from_buffer` is now supported.

feat(python): Implement `PySeries.from_buffer` for boolean buffers

---

crates/polars-arrow/src/array/growable/utf8.rs
crates/polars-arrow/src/array/mod.rs
crates/polars-arrow/src/array/specification.rs
crates/polars-arrow/src/array/utf8/mod.rs
crates/polars-arrow/src/lib.rs
crates/polars-arrow/src/offset.rs
crates/polars-core/src/chunked_array/cast.rs
crates/polars-core/src/datatypes/static_array_collect.rs
crates/polars-parquet/src/arrow/read/deserialize/binary/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/boolean/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/dictionary/mod.rs
crates/polars-parquet/src/arrow/read/deserialize/fixed_size_binary/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/basic.rs
crates/polars-parquet/src/arrow/read/deserialize/primitive/integer.rs
crates/polars-parquet/src/arrow/read/deserialize/utils.rs

When deserialising UTF8 columns/pages in parquet to an arrow buffer UTF8 validation was done at the end when the final buffer was finished.
For dictionary pages this is highly ineffective, as we can just validate the dictionary to hold valid UTF8 strings and then elide the checks when the page gets decoded.

perf: improve parquet utf8 validation
